/* Adlam.h – Unicode constants for U+1E95E … U+1E95F
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_ADLAM_INITIAL_EXCLAMATION_MARK        0x1E95E 0  // 𞥞
#define UC_ADLAM_INITIAL_QUESTION_MARK           0x1E95F 0  // 𞥟
