/* Adlam.h – Unicode constants for U+1E900 … U+1E95F
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_ADLAM_CAPITAL_LETTER_ALIF             0x1E900   /* U+1E900 (ADLAM CAPITAL LETTER ALIF) 𞤀 */
#define UC_ADLAM_CAPITAL_LETTER_DAALI            0x1E901   /* U+1E901 (ADLAM CAPITAL LETTER DAALI) 𞤁 */
#define UC_ADLAM_CAPITAL_LETTER_LAAM             0x1E902   /* U+1E902 (ADLAM CAPITAL LETTER LAAM) 𞤂 */
#define UC_ADLAM_CAPITAL_LETTER_MIIM             0x1E903   /* U+1E903 (ADLAM CAPITAL LETTER MIIM) 𞤃 */
#define UC_ADLAM_CAPITAL_LETTER_BA               0x1E904   /* U+1E904 (ADLAM CAPITAL LETTER BA) 𞤄 */
#define UC_ADLAM_CAPITAL_LETTER_SINNYIIYHE       0x1E905   /* U+1E905 (ADLAM CAPITAL LETTER SINNYIIYHE) 𞤅 */
#define UC_ADLAM_CAPITAL_LETTER_PE               0x1E906   /* U+1E906 (ADLAM CAPITAL LETTER PE) 𞤆 */
#define UC_ADLAM_CAPITAL_LETTER_BHE              0x1E907   /* U+1E907 (ADLAM CAPITAL LETTER BHE) 𞤇 */
#define UC_ADLAM_CAPITAL_LETTER_RA               0x1E908   /* U+1E908 (ADLAM CAPITAL LETTER RA) 𞤈 */
#define UC_ADLAM_CAPITAL_LETTER_E                0x1E909   /* U+1E909 (ADLAM CAPITAL LETTER E) 𞤉 */
#define UC_ADLAM_CAPITAL_LETTER_FA               0x1E90A   /* U+1E90A (ADLAM CAPITAL LETTER FA) 𞤊 */
#define UC_ADLAM_CAPITAL_LETTER_I                0x1E90B   /* U+1E90B (ADLAM CAPITAL LETTER I) 𞤋 */
#define UC_ADLAM_CAPITAL_LETTER_O                0x1E90C   /* U+1E90C (ADLAM CAPITAL LETTER O) 𞤌 */
#define UC_ADLAM_CAPITAL_LETTER_DHA              0x1E90D   /* U+1E90D (ADLAM CAPITAL LETTER DHA) 𞤍 */
#define UC_ADLAM_CAPITAL_LETTER_YHE              0x1E90E   /* U+1E90E (ADLAM CAPITAL LETTER YHE) 𞤎 */
#define UC_ADLAM_CAPITAL_LETTER_WAW              0x1E90F   /* U+1E90F (ADLAM CAPITAL LETTER WAW) 𞤏 */
#define UC_ADLAM_CAPITAL_LETTER_NUN              0x1E910   /* U+1E910 (ADLAM CAPITAL LETTER NUN) 𞤐 */
#define UC_ADLAM_CAPITAL_LETTER_KAF              0x1E911   /* U+1E911 (ADLAM CAPITAL LETTER KAF) 𞤑 */
#define UC_ADLAM_CAPITAL_LETTER_YA               0x1E912   /* U+1E912 (ADLAM CAPITAL LETTER YA) 𞤒 */
#define UC_ADLAM_CAPITAL_LETTER_U                0x1E913   /* U+1E913 (ADLAM CAPITAL LETTER U) 𞤓 */
#define UC_ADLAM_CAPITAL_LETTER_JIIM             0x1E914   /* U+1E914 (ADLAM CAPITAL LETTER JIIM) 𞤔 */
#define UC_ADLAM_CAPITAL_LETTER_CHI              0x1E915   /* U+1E915 (ADLAM CAPITAL LETTER CHI) 𞤕 */
#define UC_ADLAM_CAPITAL_LETTER_HA               0x1E916   /* U+1E916 (ADLAM CAPITAL LETTER HA) 𞤖 */
#define UC_ADLAM_CAPITAL_LETTER_QAAF             0x1E917   /* U+1E917 (ADLAM CAPITAL LETTER QAAF) 𞤗 */
#define UC_ADLAM_CAPITAL_LETTER_GA               0x1E918   /* U+1E918 (ADLAM CAPITAL LETTER GA) 𞤘 */
#define UC_ADLAM_CAPITAL_LETTER_NYA              0x1E919   /* U+1E919 (ADLAM CAPITAL LETTER NYA) 𞤙 */
#define UC_ADLAM_CAPITAL_LETTER_TU               0x1E91A   /* U+1E91A (ADLAM CAPITAL LETTER TU) 𞤚 */
#define UC_ADLAM_CAPITAL_LETTER_NHA              0x1E91B   /* U+1E91B (ADLAM CAPITAL LETTER NHA) 𞤛 */
#define UC_ADLAM_CAPITAL_LETTER_VA               0x1E91C   /* U+1E91C (ADLAM CAPITAL LETTER VA) 𞤜 */
#define UC_ADLAM_CAPITAL_LETTER_KHA              0x1E91D   /* U+1E91D (ADLAM CAPITAL LETTER KHA) 𞤝 */
#define UC_ADLAM_CAPITAL_LETTER_GBE              0x1E91E   /* U+1E91E (ADLAM CAPITAL LETTER GBE) 𞤞 */
#define UC_ADLAM_CAPITAL_LETTER_ZAL              0x1E91F   /* U+1E91F (ADLAM CAPITAL LETTER ZAL) 𞤟 */
#define UC_ADLAM_CAPITAL_LETTER_KPO              0x1E920   /* U+1E920 (ADLAM CAPITAL LETTER KPO) 𞤠 */
#define UC_ADLAM_CAPITAL_LETTER_SHA              0x1E921   /* U+1E921 (ADLAM CAPITAL LETTER SHA) 𞤡 */
#define UC_ADLAM_SMALL_LETTER_ALIF               0x1E922   /* U+1E922 (ADLAM SMALL LETTER ALIF) 𞤢 */
#define UC_ADLAM_SMALL_LETTER_DAALI              0x1E923   /* U+1E923 (ADLAM SMALL LETTER DAALI) 𞤣 */
#define UC_ADLAM_SMALL_LETTER_LAAM               0x1E924   /* U+1E924 (ADLAM SMALL LETTER LAAM) 𞤤 */
#define UC_ADLAM_SMALL_LETTER_MIIM               0x1E925   /* U+1E925 (ADLAM SMALL LETTER MIIM) 𞤥 */
#define UC_ADLAM_SMALL_LETTER_BA                 0x1E926   /* U+1E926 (ADLAM SMALL LETTER BA) 𞤦 */
#define UC_ADLAM_SMALL_LETTER_SINNYIIYHE         0x1E927   /* U+1E927 (ADLAM SMALL LETTER SINNYIIYHE) 𞤧 */
#define UC_ADLAM_SMALL_LETTER_PE                 0x1E928   /* U+1E928 (ADLAM SMALL LETTER PE) 𞤨 */
#define UC_ADLAM_SMALL_LETTER_BHE                0x1E929   /* U+1E929 (ADLAM SMALL LETTER BHE) 𞤩 */
#define UC_ADLAM_SMALL_LETTER_RA                 0x1E92A   /* U+1E92A (ADLAM SMALL LETTER RA) 𞤪 */
#define UC_ADLAM_SMALL_LETTER_E                  0x1E92B   /* U+1E92B (ADLAM SMALL LETTER E) 𞤫 */
#define UC_ADLAM_SMALL_LETTER_FA                 0x1E92C   /* U+1E92C (ADLAM SMALL LETTER FA) 𞤬 */
#define UC_ADLAM_SMALL_LETTER_I                  0x1E92D   /* U+1E92D (ADLAM SMALL LETTER I) 𞤭 */
#define UC_ADLAM_SMALL_LETTER_O                  0x1E92E   /* U+1E92E (ADLAM SMALL LETTER O) 𞤮 */
#define UC_ADLAM_SMALL_LETTER_DHA                0x1E92F   /* U+1E92F (ADLAM SMALL LETTER DHA) 𞤯 */
#define UC_ADLAM_SMALL_LETTER_YHE                0x1E930   /* U+1E930 (ADLAM SMALL LETTER YHE) 𞤰 */
#define UC_ADLAM_SMALL_LETTER_WAW                0x1E931   /* U+1E931 (ADLAM SMALL LETTER WAW) 𞤱 */
#define UC_ADLAM_SMALL_LETTER_NUN                0x1E932   /* U+1E932 (ADLAM SMALL LETTER NUN) 𞤲 */
#define UC_ADLAM_SMALL_LETTER_KAF                0x1E933   /* U+1E933 (ADLAM SMALL LETTER KAF) 𞤳 */
#define UC_ADLAM_SMALL_LETTER_YA                 0x1E934   /* U+1E934 (ADLAM SMALL LETTER YA) 𞤴 */
#define UC_ADLAM_SMALL_LETTER_U                  0x1E935   /* U+1E935 (ADLAM SMALL LETTER U) 𞤵 */
#define UC_ADLAM_SMALL_LETTER_JIIM               0x1E936   /* U+1E936 (ADLAM SMALL LETTER JIIM) 𞤶 */
#define UC_ADLAM_SMALL_LETTER_CHI                0x1E937   /* U+1E937 (ADLAM SMALL LETTER CHI) 𞤷 */
#define UC_ADLAM_SMALL_LETTER_HA                 0x1E938   /* U+1E938 (ADLAM SMALL LETTER HA) 𞤸 */
#define UC_ADLAM_SMALL_LETTER_QAAF               0x1E939   /* U+1E939 (ADLAM SMALL LETTER QAAF) 𞤹 */
#define UC_ADLAM_SMALL_LETTER_GA                 0x1E93A   /* U+1E93A (ADLAM SMALL LETTER GA) 𞤺 */
#define UC_ADLAM_SMALL_LETTER_NYA                0x1E93B   /* U+1E93B (ADLAM SMALL LETTER NYA) 𞤻 */
#define UC_ADLAM_SMALL_LETTER_TU                 0x1E93C   /* U+1E93C (ADLAM SMALL LETTER TU) 𞤼 */
#define UC_ADLAM_SMALL_LETTER_NHA                0x1E93D   /* U+1E93D (ADLAM SMALL LETTER NHA) 𞤽 */
#define UC_ADLAM_SMALL_LETTER_VA                 0x1E93E   /* U+1E93E (ADLAM SMALL LETTER VA) 𞤾 */
#define UC_ADLAM_SMALL_LETTER_KHA                0x1E93F   /* U+1E93F (ADLAM SMALL LETTER KHA) 𞤿 */
#define UC_ADLAM_SMALL_LETTER_GBE                0x1E940   /* U+1E940 (ADLAM SMALL LETTER GBE) 𞥀 */
#define UC_ADLAM_SMALL_LETTER_ZAL                0x1E941   /* U+1E941 (ADLAM SMALL LETTER ZAL) 𞥁 */
#define UC_ADLAM_SMALL_LETTER_KPO                0x1E942   /* U+1E942 (ADLAM SMALL LETTER KPO) 𞥂 */
#define UC_ADLAM_SMALL_LETTER_SHA                0x1E943   /* U+1E943 (ADLAM SMALL LETTER SHA) 𞥃 */
#define UC_ADLAM_ALIF_LENGTHENER                 0x1E944   /* U+1E944 (ADLAM ALIF LENGTHENER) 𞥄 */
#define UC_ADLAM_VOWEL_LENGTHENER                0x1E945   /* U+1E945 (ADLAM VOWEL LENGTHENER) 𞥅 */
#define UC_ADLAM_GEMINATION_MARK                 0x1E946   /* U+1E946 (ADLAM GEMINATION MARK) 𞥆 */
#define UC_ADLAM_HAMZA                           0x1E947   /* U+1E947 (ADLAM HAMZA) 𞥇 */
#define UC_ADLAM_CONSONANT_MODIFIER              0x1E948   /* U+1E948 (ADLAM CONSONANT MODIFIER) 𞥈 */
#define UC_ADLAM_GEMINATE_CONSONANT_MODIFIER     0x1E949   /* U+1E949 (ADLAM GEMINATE CONSONANT MODIFIER) 𞥉 */
#define UC_ADLAM_NUKTA                           0x1E94A   /* U+1E94A (ADLAM NUKTA) 𞥊 */
#define UC_ADLAM_NASALIZATION_MARK               0x1E94B   /* U+1E94B (ADLAM NASALIZATION MARK) 𞥋 */
#define UC_UNKNOWN_1E94C                         0x1E94C   /* U+1E94C (UNKNOWN_1E94C) */
#define UC_UNKNOWN_1E94D                         0x1E94D   /* U+1E94D (UNKNOWN_1E94D) */
#define UC_UNKNOWN_1E94E                         0x1E94E   /* U+1E94E (UNKNOWN_1E94E) */
#define UC_UNKNOWN_1E94F                         0x1E94F   /* U+1E94F (UNKNOWN_1E94F) */
#define UC_ADLAM_DIGIT_ZERO                      0x1E950   /* U+1E950 (ADLAM DIGIT ZERO) 𞥐 */
#define UC_ADLAM_DIGIT_ONE                       0x1E951   /* U+1E951 (ADLAM DIGIT ONE) 𞥑 */
#define UC_ADLAM_DIGIT_TWO                       0x1E952   /* U+1E952 (ADLAM DIGIT TWO) 𞥒 */
#define UC_ADLAM_DIGIT_THREE                     0x1E953   /* U+1E953 (ADLAM DIGIT THREE) 𞥓 */
#define UC_ADLAM_DIGIT_FOUR                      0x1E954   /* U+1E954 (ADLAM DIGIT FOUR) 𞥔 */
#define UC_ADLAM_DIGIT_FIVE                      0x1E955   /* U+1E955 (ADLAM DIGIT FIVE) 𞥕 */
#define UC_ADLAM_DIGIT_SIX                       0x1E956   /* U+1E956 (ADLAM DIGIT SIX) 𞥖 */
#define UC_ADLAM_DIGIT_SEVEN                     0x1E957   /* U+1E957 (ADLAM DIGIT SEVEN) 𞥗 */
#define UC_ADLAM_DIGIT_EIGHT                     0x1E958   /* U+1E958 (ADLAM DIGIT EIGHT) 𞥘 */
#define UC_ADLAM_DIGIT_NINE                      0x1E959   /* U+1E959 (ADLAM DIGIT NINE) 𞥙 */
#define UC_UNKNOWN_1E95A                         0x1E95A   /* U+1E95A (UNKNOWN_1E95A) */
#define UC_UNKNOWN_1E95B                         0x1E95B   /* U+1E95B (UNKNOWN_1E95B) */
#define UC_UNKNOWN_1E95C                         0x1E95C   /* U+1E95C (UNKNOWN_1E95C) */
#define UC_UNKNOWN_1E95D                         0x1E95D   /* U+1E95D (UNKNOWN_1E95D) */
#define UC_ADLAM_INITIAL_EXCLAMATION_MARK        0x1E95E   /* U+1E95E (ADLAM INITIAL EXCLAMATION MARK) 𞥞 */
#define UC_ADLAM_INITIAL_QUESTION_MARK           0x1E95F   /* U+1E95F (ADLAM INITIAL QUESTION MARK) 𞥟 */
