/* adlam.h – Unicode constants for U+1E900 … U+1E95F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
*
* See https://www.unicode.org/versions/latest/ for source data.

 * Adlam may refer to:
 *

* Consistency Check:
* Total Defined Code Points: 88
* Total Significant Hex Values: 88
* Status: OK (Counts Match)

*/

#ifndef ADLAM_H
#define ADLAM_H

#define UC_ADLAM_ALIF                            0x1E922 0x1E900  // 𞤢/𞤀
#define UC_ADLAM_DAALI                           0x1E923 0x1E901  // 𞤣/𞤁
#define UC_ADLAM_LAAM                            0x1E924 0x1E902  // 𞤤/𞤂
#define UC_ADLAM_MIIM                            0x1E925 0x1E903  // 𞤥/𞤃
#define UC_ADLAM_BA                              0x1E926 0x1E904  // 𞤦/𞤄
#define UC_ADLAM_SINNYIIYHE                      0x1E927 0x1E905  // 𞤧/𞤅
#define UC_ADLAM_PE                              0x1E928 0x1E906  // 𞤨/𞤆
#define UC_ADLAM_BHE                             0x1E929 0x1E907  // 𞤩/𞤇
#define UC_ADLAM_RA                              0x1E92A 0x1E908  // 𞤪/𞤈
#define UC_ADLAM_E                               0x1E92B 0x1E909  // 𞤫/𞤉
#define UC_ADLAM_FA                              0x1E92C 0x1E90A  // 𞤬/𞤊
#define UC_ADLAM_I                               0x1E92D 0x1E90B  // 𞤭/𞤋
#define UC_ADLAM_O                               0x1E92E 0x1E90C  // 𞤮/𞤌
#define UC_ADLAM_DHA                             0x1E92F 0x1E90D  // 𞤯/𞤍
#define UC_ADLAM_YHE                             0x1E930 0x1E90E  // 𞤰/𞤎
#define UC_ADLAM_WAW                             0x1E931 0x1E90F  // 𞤱/𞤏
#define UC_ADLAM_NUN                             0x1E932 0x1E910  // 𞤲/𞤐
#define UC_ADLAM_KAF                             0x1E933 0x1E911  // 𞤳/𞤑
#define UC_ADLAM_YA                              0x1E934 0x1E912  // 𞤴/𞤒
#define UC_ADLAM_U                               0x1E935 0x1E913  // 𞤵/𞤓
#define UC_ADLAM_JIIM                            0x1E936 0x1E914  // 𞤶/𞤔
#define UC_ADLAM_CHI                             0x1E937 0x1E915  // 𞤷/𞤕
#define UC_ADLAM_HA                              0x1E938 0x1E916  // 𞤸/𞤖
#define UC_ADLAM_QAAF                            0x1E939 0x1E917  // 𞤹/𞤗
#define UC_ADLAM_GA                              0x1E93A 0x1E918  // 𞤺/𞤘
#define UC_ADLAM_NYA                             0x1E93B 0x1E919  // 𞤻/𞤙
#define UC_ADLAM_TU                              0x1E93C 0x1E91A  // 𞤼/𞤚
#define UC_ADLAM_NHA                             0x1E93D 0x1E91B  // 𞤽/𞤛
#define UC_ADLAM_VA                              0x1E93E 0x1E91C  // 𞤾/𞤜
#define UC_ADLAM_KHA                             0x1E93F 0x1E91D  // 𞤿/𞤝
#define UC_ADLAM_GBE                             0x1E940 0x1E91E  // 𞥀/𞤞
#define UC_ADLAM_ZAL                             0x1E941 0x1E91F  // 𞥁/𞤟
#define UC_ADLAM_KPO                             0x1E942 0x1E920  // 𞥂/𞤠
#define UC_ADLAM_SHA                             0x1E943 0x1E921  // 𞥃/𞤡
#define UC_ADLAM_ALIF_LENGTHENER                 0x1E944 0  // 𞥄
#define UC_ADLAM_VOWEL_LENGTHENER                0x1E945 0  // 𞥅
#define UC_ADLAM_GEMINATION_MARK                 0x1E946 0  // 𞥆
#define UC_ADLAM_HAMZA                           0x1E947 0  // 𞥇
#define UC_ADLAM_CONSONANT_MODIFIER              0x1E948 0  // 𞥈
#define UC_ADLAM_GEMINATE_CONSONANT_MODIFIER     0x1E949 0  // 𞥉
#define UC_ADLAM_NUKTA                           0x1E94A 0  // 𞥊
#define UC_ADLAM_NASALIZATION_MARK               0x1E94B 0  // 𞥋
#define UC_ADLAM_ZERO                            0x1E950 0  // 𞥐
#define UC_ADLAM_ONE                             0x1E951 0  // 𞥑
#define UC_ADLAM_TWO                             0x1E952 0  // 𞥒
#define UC_ADLAM_THREE                           0x1E953 0  // 𞥓
#define UC_ADLAM_FOUR                            0x1E954 0  // 𞥔
#define UC_ADLAM_FIVE                            0x1E955 0  // 𞥕
#define UC_ADLAM_SIX                             0x1E956 0  // 𞥖
#define UC_ADLAM_SEVEN                           0x1E957 0  // 𞥗
#define UC_ADLAM_EIGHT                           0x1E958 0  // 𞥘
#define UC_ADLAM_NINE                            0x1E959 0  // 𞥙
#define UC_ADLAM_INITIAL_EXCLAMATION_MARK        0x1E95E 0  // 𞥞
#define UC_ADLAM_INITIAL_QUESTION_MARK           0x1E95F 0  // 𞥟

#endif // ADLAM_H
