/* aegean_numbers.h – Unicode constants for U+10100 … U+1013F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_AEGEAN_WORD_SEPARATOR_LINE            0x10100 0  // 𐄀
#define UC_AEGEAN_WORD_SEPARATOR_DOT             0x10101 0  // 𐄁
#define UC_AEGEAN_CHECK_MARK                     0x10102 0  // 𐄂
#define UC_AEGEAN_ONE                            0x10107 0  // 𐄇
#define UC_AEGEAN_TWO                            0x10108 0  // 𐄈
#define UC_AEGEAN_THREE                          0x10109 0  // 𐄉
#define UC_AEGEAN_FOUR                           0x1010A 0  // 𐄊
#define UC_AEGEAN_FIVE                           0x1010B 0  // 𐄋
#define UC_AEGEAN_SIX                            0x1010C 0  // 𐄌
#define UC_AEGEAN_SEVEN                          0x1010D 0  // 𐄍
#define UC_AEGEAN_EIGHT                          0x1010E 0  // 𐄎
#define UC_AEGEAN_NINE                           0x1010F 0  // 𐄏
#define UC_AEGEAN_TEN                            0x10110 0  // 𐄐
#define UC_AEGEAN_TWENTY                         0x10111 0  // 𐄑
#define UC_AEGEAN_THIRTY                         0x10112 0  // 𐄒
#define UC_AEGEAN_FORTY                          0x10113 0  // 𐄓
#define UC_AEGEAN_FIFTY                          0x10114 0  // 𐄔
#define UC_AEGEAN_SIXTY                          0x10115 0  // 𐄕
#define UC_AEGEAN_SEVENTY                        0x10116 0  // 𐄖
#define UC_AEGEAN_EIGHTY                         0x10117 0  // 𐄗
#define UC_AEGEAN_NINETY                         0x10118 0  // 𐄘
#define UC_AEGEAN_ONE_HUNDRED                    0x10119 0  // 𐄙
#define UC_AEGEAN_TWO_HUNDRED                    0x1011A 0  // 𐄚
#define UC_AEGEAN_THREE_HUNDRED                  0x1011B 0  // 𐄛
#define UC_AEGEAN_FOUR_HUNDRED                   0x1011C 0  // 𐄜
#define UC_AEGEAN_FIVE_HUNDRED                   0x1011D 0  // 𐄝
#define UC_AEGEAN_SIX_HUNDRED                    0x1011E 0  // 𐄞
#define UC_AEGEAN_SEVEN_HUNDRED                  0x1011F 0  // 𐄟
#define UC_AEGEAN_EIGHT_HUNDRED                  0x10120 0  // 𐄠
#define UC_AEGEAN_NINE_HUNDRED                   0x10121 0  // 𐄡
#define UC_AEGEAN_ONE_THOUSAND                   0x10122 0  // 𐄢
#define UC_AEGEAN_TWO_THOUSAND                   0x10123 0  // 𐄣
#define UC_AEGEAN_THREE_THOUSAND                 0x10124 0  // 𐄤
#define UC_AEGEAN_FOUR_THOUSAND                  0x10125 0  // 𐄥
#define UC_AEGEAN_FIVE_THOUSAND                  0x10126 0  // 𐄦
#define UC_AEGEAN_SIX_THOUSAND                   0x10127 0  // 𐄧
#define UC_AEGEAN_SEVEN_THOUSAND                 0x10128 0  // 𐄨
#define UC_AEGEAN_EIGHT_THOUSAND                 0x10129 0  // 𐄩
#define UC_AEGEAN_NINE_THOUSAND                  0x1012A 0  // 𐄪
#define UC_AEGEAN_TEN_THOUSAND                   0x1012B 0  // 𐄫
#define UC_AEGEAN_TWENTY_THOUSAND                0x1012C 0  // 𐄬
#define UC_AEGEAN_THIRTY_THOUSAND                0x1012D 0  // 𐄭
#define UC_AEGEAN_FORTY_THOUSAND                 0x1012E 0  // 𐄮
#define UC_AEGEAN_FIFTY_THOUSAND                 0x1012F 0  // 𐄯
#define UC_AEGEAN_SIXTY_THOUSAND                 0x10130 0  // 𐄰
#define UC_AEGEAN_SEVENTY_THOUSAND               0x10131 0  // 𐄱
#define UC_AEGEAN_EIGHTY_THOUSAND                0x10132 0  // 𐄲
#define UC_AEGEAN_NINETY_THOUSAND                0x10133 0  // 𐄳
#define UC_AEGEAN_WEIGHT_BASE_UNIT               0x10137 0  // 𐄷
#define UC_AEGEAN_WEIGHT_FIRST_SUBUNIT           0x10138 0  // 𐄸
#define UC_AEGEAN_WEIGHT_SECOND_SUBUNIT          0x10139 0  // 𐄹
#define UC_AEGEAN_WEIGHT_THIRD_SUBUNIT           0x1013A 0  // 𐄺
#define UC_AEGEAN_WEIGHT_FOURTH_SUBUNIT          0x1013B 0  // 𐄻
#define UC_AEGEAN_DRY_MEASURE_FIRST_SUBUNIT      0x1013C 0  // 𐄼
#define UC_AEGEAN_LIQUID_MEASURE_FIRST_SUBUNIT   0x1013D 0  // 𐄽
#define UC_AEGEAN_MEASURE_SECOND_SUBUNIT         0x1013E 0  // 𐄾
#define UC_AEGEAN_MEASURE_THIRD_SUBUNIT          0x1013F 0  // 𐄿
