/* Alchemical Symbols.h – Unicode constants for U+1F77B … U+1F77F
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_HAUMEA                                0x1F77B 0  // 🝻
#define UC_MAKEMAKE                              0x1F77C 0  // 🝼
#define UC_GONGGONG                              0x1F77D 0  // 🝽
#define UC_QUAOAR                                0x1F77E 0  // 🝾
#define UC_ORCUS                                 0x1F77F 0  // 🝿
