/* ancient_greek_musical_notation.h – Unicode constants for U+1D200 … U+1D24F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.

* Consistency Check:
* Total Defined Code Points: 70
* Total Significant Hex Values: 70
* Status: OK (Counts Match)

*/

#pragma once

#define UC_VOCAL_NOTATION_1                      0x1D200 0  // 𝈀
#define UC_VOCAL_NOTATION_2                      0x1D201 0  // 𝈁
#define UC_VOCAL_NOTATION_3                      0x1D202 0  // 𝈂
#define UC_VOCAL_NOTATION_4                      0x1D203 0  // 𝈃
#define UC_VOCAL_NOTATION_5                      0x1D204 0  // 𝈄
#define UC_VOCAL_NOTATION_6                      0x1D205 0  // 𝈅
#define UC_VOCAL_NOTATION_7                      0x1D206 0  // 𝈆
#define UC_VOCAL_NOTATION_8                      0x1D207 0  // 𝈇
#define UC_VOCAL_NOTATION_9                      0x1D208 0  // 𝈈
#define UC_VOCAL_NOTATION_10                     0x1D209 0  // 𝈉
#define UC_VOCAL_NOTATION_11                     0x1D20A 0  // 𝈊
#define UC_VOCAL_NOTATION_12                     0x1D20B 0  // 𝈋
#define UC_VOCAL_NOTATION_13                     0x1D20C 0  // 𝈌
#define UC_VOCAL_NOTATION_14                     0x1D20D 0  // 𝈍
#define UC_VOCAL_NOTATION_15                     0x1D20E 0  // 𝈎
#define UC_VOCAL_NOTATION_16                     0x1D20F 0  // 𝈏
#define UC_VOCAL_NOTATION_17                     0x1D210 0  // 𝈐
#define UC_VOCAL_NOTATION_18                     0x1D211 0  // 𝈑
#define UC_VOCAL_NOTATION_19                     0x1D212 0  // 𝈒
#define UC_VOCAL_NOTATION_20                     0x1D213 0  // 𝈓
#define UC_VOCAL_NOTATION_21                     0x1D214 0  // 𝈔
#define UC_VOCAL_NOTATION_22                     0x1D215 0  // 𝈕
#define UC_VOCAL_NOTATION_23                     0x1D216 0  // 𝈖
#define UC_VOCAL_NOTATION_24                     0x1D217 0  // 𝈗
#define UC_VOCAL_NOTATION_50                     0x1D218 0  // 𝈘
#define UC_VOCAL_NOTATION_51                     0x1D219 0  // 𝈙
#define UC_VOCAL_NOTATION_52                     0x1D21A 0  // 𝈚
#define UC_VOCAL_NOTATION_53                     0x1D21B 0  // 𝈛
#define UC_VOCAL_NOTATION_54                     0x1D21C 0  // 𝈜
#define UC_INSTRUMENTAL_NOTATION_1               0x1D21D 0  // 𝈝
#define UC_INSTRUMENTAL_NOTATION_2               0x1D21E 0  // 𝈞
#define UC_INSTRUMENTAL_NOTATION_4               0x1D21F 0  // 𝈟
#define UC_INSTRUMENTAL_NOTATION_5               0x1D220 0  // 𝈠
#define UC_INSTRUMENTAL_NOTATION_7               0x1D221 0  // 𝈡
#define UC_INSTRUMENTAL_NOTATION_8               0x1D222 0  // 𝈢
#define UC_INSTRUMENTAL_NOTATION_11              0x1D223 0  // 𝈣
#define UC_INSTRUMENTAL_NOTATION_12              0x1D224 0  // 𝈤
#define UC_INSTRUMENTAL_NOTATION_13              0x1D225 0  // 𝈥
#define UC_INSTRUMENTAL_NOTATION_14              0x1D226 0  // 𝈦
#define UC_INSTRUMENTAL_NOTATION_17              0x1D227 0  // 𝈧
#define UC_INSTRUMENTAL_NOTATION_18              0x1D228 0  // 𝈨
#define UC_INSTRUMENTAL_NOTATION_19              0x1D229 0  // 𝈩
#define UC_INSTRUMENTAL_NOTATION_23              0x1D22A 0  // 𝈪
#define UC_INSTRUMENTAL_NOTATION_24              0x1D22B 0  // 𝈫
#define UC_INSTRUMENTAL_NOTATION_25              0x1D22C 0  // 𝈬
#define UC_INSTRUMENTAL_NOTATION_26              0x1D22D 0  // 𝈭
#define UC_INSTRUMENTAL_NOTATION_27              0x1D22E 0  // 𝈮
#define UC_INSTRUMENTAL_NOTATION_29              0x1D22F 0  // 𝈯
#define UC_INSTRUMENTAL_NOTATION_30              0x1D230 0  // 𝈰
#define UC_INSTRUMENTAL_NOTATION_32              0x1D231 0  // 𝈱
#define UC_INSTRUMENTAL_NOTATION_36              0x1D232 0  // 𝈲
#define UC_INSTRUMENTAL_NOTATION_37              0x1D233 0  // 𝈳
#define UC_INSTRUMENTAL_NOTATION_38              0x1D234 0  // 𝈴
#define UC_INSTRUMENTAL_NOTATION_39              0x1D235 0  // 𝈵
#define UC_INSTRUMENTAL_NOTATION_40              0x1D236 0  // 𝈶
#define UC_INSTRUMENTAL_NOTATION_42              0x1D237 0  // 𝈷
#define UC_INSTRUMENTAL_NOTATION_43              0x1D238 0  // 𝈸
#define UC_INSTRUMENTAL_NOTATION_45              0x1D239 0  // 𝈹
#define UC_INSTRUMENTAL_NOTATION_47              0x1D23A 0  // 𝈺
#define UC_INSTRUMENTAL_NOTATION_48              0x1D23B 0  // 𝈻
#define UC_INSTRUMENTAL_NOTATION_49              0x1D23C 0  // 𝈼
#define UC_INSTRUMENTAL_NOTATION_50              0x1D23D 0  // 𝈽
#define UC_INSTRUMENTAL_NOTATION_51              0x1D23E 0  // 𝈾
#define UC_INSTRUMENTAL_NOTATION_52              0x1D23F 0  // 𝈿
#define UC_INSTRUMENTAL_NOTATION_53              0x1D240 0  // 𝉀
#define UC_INSTRUMENTAL_NOTATION_54              0x1D241 0  // 𝉁
#define UC_COMBINING_MUSICAL_TRISEME             0x1D242 0  // 𝉂
#define UC_COMBINING_MUSICAL_TETRASEME           0x1D243 0  // 𝉃
#define UC_COMBINING_MUSICAL_PENTASEME           0x1D244 0  // 𝉄
#define UC_MUSICAL_LEIMMA                        0x1D245 0  // 𝉅
