/* ancient_symbols.h – Unicode constants for U+101A0 … U+101A0
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_TAU_RHO                               0x101A0 0  // 𐆠
