/* arabic_extended_b.h – Unicode constants for U+0870 … U+089F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.

* Consistency Check:
* Total Defined Code Points: 43
* Total Significant Hex Values: 43
* Status: OK (Counts Match)

*/

#pragma once

#define UC_AREB_ALEF_ATTACHED_FATHA              0x0870 0  // ࡰ
#define UC_AREB_ALEF_ATTACHED_TOP_RIGHT_FATHA    0x0871 0  // ࡱ
#define UC_AREB_ALEF_RIGHT_MIDDLE_STROKE         0x0872 0  // ࡲ
#define UC_AREB_ALEF_LEFT_MIDDLE_STROKE          0x0873 0  // ࡳ
#define UC_AREB_ALEF_ATTACHED_KASRA              0x0874 0  // ࡴ
#define UC_AREB_ALEF_ATTACHED_BOTTOM_RIGHT_KASRA 0x0875 0  // ࡵ
#define UC_AREB_ALEF_ATTACHED_ROUND_DOT_ABOVE    0x0876 0  // ࡶ
#define UC_AREB_ALEF_ATTACHED_RIGHT_ROUND_DOT    0x0877 0  // ࡷ
#define UC_AREB_ALEF_ATTACHED_LEFT_ROUND_DOT     0x0878 0  // ࡸ
#define UC_AREB_ALEF_ATTACHED_ROUND_DOT_BELOW    0x0879 0  // ࡹ
#define UC_AREB_ALEF_DOT_ABOVE                   0x087A 0  // ࡺ
#define UC_AREB_ALEF_ATTACHED_TOP_RIGHT_FATHA_AND_DOT_ABOVE 0x087B 0  // ࡻ
#define UC_AREB_ALEF_RIGHT_MIDDLE_STROKE_AND_DOT_ABOVE 0x087C 0  // ࡼ
#define UC_AREB_ALEF_ATTACHED_BOTTOM_RIGHT_KASRA_AND_DOT_ABOVE 0x087D 0  // ࡽ
#define UC_AREB_ALEF_ATTACHED_TOP_RIGHT_FATHA_AND_LEFT_RING 0x087E 0  // ࡾ
#define UC_AREB_ALEF_RIGHT_MIDDLE_STROKE_AND_LEFT_RING 0x087F 0  // ࡿ
#define UC_AREB_ALEF_ATTACHED_BOTTOM_RIGHT_KASRA_AND_LEFT_RING 0x0880 0  // ࢀ
#define UC_AREB_ALEF_ATTACHED_RIGHT_HAMZA        0x0881 0  // ࢁ
#define UC_AREB_ALEF_ATTACHED_LEFT_HAMZA         0x0882 0  // ࢂ
#define UC_AREB_TATWEEL_OVERSTRUCK_HAMZA         0x0883 0  // ࢃ
#define UC_AREB_TATWEEL_OVERSTRUCK_WAW           0x0884 0  // ࢄ
#define UC_AREB_TATWEEL_TWO_DOTS_BELOW           0x0885 0  // ࢅ
#define UC_AREB_THIN_YEH                         0x0886 0  // ࢆ
#define UC_AREB_BASELINE_ROUND_DOT               0x0887 0  // ࢇ
#define UC_AREB_RAISED_ROUND_DOT                 0x0888 0  // ࢈
#define UC_AREB_NOON_INVERTED_SMALL_V            0x0889 0  // ࢉ
#define UC_AREB_HAH_INVERTED_SMALL_V_BELOW       0x088A 0  // ࢊ
#define UC_AREB_TAH_DOT_BELOW                    0x088B 0  // ࢋ
#define UC_AREB_TAH_THREE_DOTS_BELOW             0x088C 0  // ࢌ
#define UC_AREB_KEHEH_TWO_DOTS_VERTICALLY_BELOW  0x088D 0  // ࢍ
#define UC_AREB_VERTICAL_TAIL                    0x088E 0  // ࢎ
#define UC_AREB_NOON_RING_ABOVE                  0x088F 0  /* U+088F (ARABIC LETTER NOON WITH RING ABOVE) */
#define UC_AREB_POUND_MARK_ABOVE                 0x0890 0  /* U+0890 (ARABIC POUND MARK ABOVE) */
#define UC_AREB_PIASTRE_MARK_ABOVE               0x0891 0  /* U+0891 (ARABIC PIASTRE MARK ABOVE) */
#define UC_AREB_PEPET                            0x0897 0  /* U+0897 (ARABIC PEPET) */
#define UC_AREB_SMALL_HIGH_WORD_AL_JUZ           0x0898 0  // ࢘
#define UC_AREB_SMALL_LOW_WORD_ISHMAAM           0x0899 0  // ࢙
#define UC_AREB_SMALL_LOW_WORD_IMAALA            0x089A 0  // ࢚
#define UC_AREB_SMALL_LOW_WORD_TASHEEL           0x089B 0  // ࢛
#define UC_AREB_MADDA_WAAJIB                     0x089C 0  // ࢜
#define UC_AREB_SUPERSC_ALEF_MOKHASSAS           0x089D 0  // ࢝
#define UC_AREB_DOUBLED_MADDA                    0x089E 0  // ࢞
#define UC_AREB_HALF_MADDA_OVER_MADDA            0x089F 0  // ࢟
