/* armenian.h – Unicode constants for U+0530 … U+058F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_AM_ARMENIAN_MODIFIER_LEFT_HALF_RING   0x0559 0  // ՙ
#define UC_AM_ARMENIAN_APOSTROPHE                0x055A 0  // ՚
#define UC_AM_ARMENIAN_EMPHASIS_MARK             0x055B 0  // ՛
#define UC_AM_ARMENIAN_EXCLAMATION_MARK          0x055C 0  // ՜
#define UC_AM_ARMENIAN                           0x055D 0  // ՝
#define UC_AM_ARMENIAN_QUESTION_MARK             0x055E 0  // ՞
#define UC_AM_ARMENIAN_ABBREVIATION_MARK         0x055F 0  // ՟
#define UC_AM_ARMENIAN_SMALL_TURNED_AYB          0x0560 0  // ՠ
#define UC_AM_ARMENIAN_AYB                       0x0531 0x0561  // Ա/ա
#define UC_AM_ARMENIAN_BEN                       0x0532 0x0562  // Բ/բ
#define UC_AM_ARMENIAN_GIM                       0x0533 0x0563  // Գ/գ
#define UC_AM_ARMENIAN_DA                        0x0534 0x0564  // Դ/դ
#define UC_AM_ARMENIAN_ECH                       0x0535 0x0565  // Ե/ե
#define UC_AM_ARMENIAN_ZA                        0x0536 0x0566  // Զ/զ
#define UC_AM_ARMENIAN_EH                        0x0537 0x0567  // Է/է
#define UC_AM_ARMENIAN_ET                        0x0538 0x0568  // Ը/ը
#define UC_AM_ARMENIAN_TO                        0x0539 0x0569  // Թ/թ
#define UC_AM_ARMENIAN_ZHE                       0x053A 0x056A  // Ժ/ժ
#define UC_AM_ARMENIAN_INI                       0x053B 0x056B  // Ի/ի
#define UC_AM_ARMENIAN_LIWN                      0x053C 0x056C  // Լ/լ
#define UC_AM_ARMENIAN_XEH                       0x053D 0x056D  // Խ/խ
#define UC_AM_ARMENIAN_CA                        0x053E 0x056E  // Ծ/ծ
#define UC_AM_ARMENIAN_KEN                       0x053F 0x056F  // Կ/կ
#define UC_AM_ARMENIAN_HO                        0x0540 0x0570  // Հ/հ
#define UC_AM_ARMENIAN_JA                        0x0541 0x0571  // Ձ/ձ
#define UC_AM_ARMENIAN_GHAD                      0x0542 0x0572  // Ղ/ղ
#define UC_AM_ARMENIAN_CHEH                      0x0543 0x0573  // Ճ/ճ
#define UC_AM_ARMENIAN_MEN                       0x0544 0x0574  // Մ/մ
#define UC_AM_ARMENIAN_YI                        0x0545 0x0575  // Յ/յ
#define UC_AM_ARMENIAN_NOW                       0x0546 0x0576  // Ն/ն
#define UC_AM_ARMENIAN_SHA                       0x0547 0x0577  // Շ/շ
#define UC_AM_ARMENIAN_VO                        0x0548 0x0578  // Ո/ո
#define UC_AM_ARMENIAN_CHA                       0x0549 0x0579  // Չ/չ
#define UC_AM_ARMENIAN_PEH                       0x054A 0x057A  // Պ/պ
#define UC_AM_ARMENIAN_JHEH                      0x054B 0x057B  // Ջ/ջ
#define UC_AM_ARMENIAN_RA                        0x054C 0x057C  // Ռ/ռ
#define UC_AM_ARMENIAN_SEH                       0x054D 0x057D  // Ս/ս
#define UC_AM_ARMENIAN_VEW                       0x054E 0x057E  // Վ/վ
#define UC_AM_ARMENIAN_TIWN                      0x054F 0x057F  // Տ/տ
#define UC_AM_ARMENIAN_REH                       0x0550 0x0580  // Ր/ր
#define UC_AM_ARMENIAN_CO                        0x0551 0x0581  // Ց/ց
#define UC_AM_ARMENIAN_YIWN                      0x0552 0x0582  // Ւ/ւ
#define UC_AM_ARMENIAN_PIWR                      0x0553 0x0583  // Փ/փ
#define UC_AM_ARMENIAN_KEH                       0x0554 0x0584  // Ք/ք
#define UC_AM_ARMENIAN_OH                        0x0555 0x0585  // Օ/օ
#define UC_AM_ARMENIAN_FEH                       0x0556 0x0586  // Ֆ/ֆ
#define UC_AM_ARMENIAN_SMALL_LIGATURE_ECH_YIWN   0x0587 0  // և
#define UC_AM_ARMENIAN_SMALL_YI_STROKE           0x0588 0  // ֈ
#define UC_AM_ARMENIAN_FULL_STOP                 0x0589 0  // ։
#define UC_AM_ARMENIAN_HYPHEN                    0x058A 0  // ֊
#define UC_AM_RIGHT_FACING_ARMENIAN_ETERNITY_SIGN 0x058D 0  // ֍
#define UC_AM_LEFT_FACING_ARMENIAN_ETERNITY_SIGN 0x058E 0  // ֎
#define UC_AM_ARMENIAN_DRAM_SIGN                 0x058F 0  // ֏
