/* batak.h – Unicode constants for U+1BC0 … U+1BFF
*
* Generated by generate_unicode_headers.py (Unicode 17.0.0)
*
* Source data for blocks: Blocks.txt (Unicode 17.0.0)
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_BATAK_A                               0x1BC0 0  // ᯀ
#define UC_BATAK_SIMALUNGUN_A                    0x1BC1 0  // ᯁ
#define UC_BATAK_HA                              0x1BC2 0  // ᯂ
#define UC_BATAK_SIMALUNGUN_HA                   0x1BC3 0  // ᯃ
#define UC_BATAK_MANDAILING_HA                   0x1BC4 0  // ᯄ
#define UC_BATAK_BA                              0x1BC5 0  // ᯅ
#define UC_BATAK_KARO_BA                         0x1BC6 0  // ᯆ
#define UC_BATAK_PA                              0x1BC7 0  // ᯇ
#define UC_BATAK_SIMALUNGUN_PA                   0x1BC8 0  // ᯈ
#define UC_BATAK_NA                              0x1BC9 0  // ᯉ
#define UC_BATAK_MANDAILING_NA                   0x1BCA 0  // ᯊ
#define UC_BATAK_WA                              0x1BCB 0  // ᯋ
#define UC_BATAK_SIMALUNGUN_WA                   0x1BCC 0  // ᯌ
#define UC_BATAK_PAKPAK_WA                       0x1BCD 0  // ᯍ
#define UC_BATAK_GA                              0x1BCE 0  // ᯎ
#define UC_BATAK_SIMALUNGUN_GA                   0x1BCF 0  // ᯏ
#define UC_BATAK_JA                              0x1BD0 0  // ᯐ
#define UC_BATAK_DA                              0x1BD1 0  // ᯑ
#define UC_BATAK_RA                              0x1BD2 0  // ᯒ
#define UC_BATAK_SIMALUNGUN_RA                   0x1BD3 0  // ᯓ
#define UC_BATAK_MA                              0x1BD4 0  // ᯔ
#define UC_BATAK_SIMALUNGUN_MA                   0x1BD5 0  // ᯕ
#define UC_BATAK_SOUTHERN_TA                     0x1BD6 0  // ᯖ
#define UC_BATAK_NORTHERN_TA                     0x1BD7 0  // ᯗ
#define UC_BATAK_SA                              0x1BD8 0  // ᯘ
#define UC_BATAK_SIMALUNGUN_SA                   0x1BD9 0  // ᯙ
#define UC_BATAK_MANDAILING_SA                   0x1BDA 0  // ᯚ
#define UC_BATAK_YA                              0x1BDB 0  // ᯛ
#define UC_BATAK_SIMALUNGUN_YA                   0x1BDC 0  // ᯜ
#define UC_BATAK_NGA                             0x1BDD 0  // ᯝ
#define UC_BATAK_LA                              0x1BDE 0  // ᯞ
#define UC_BATAK_SIMALUNGUN_LA                   0x1BDF 0  // ᯟ
#define UC_BATAK_NYA                             0x1BE0 0  // ᯠ
#define UC_BATAK_CA                              0x1BE1 0  // ᯡ
#define UC_BATAK_NDA                             0x1BE2 0  // ᯢ
#define UC_BATAK_MBA                             0x1BE3 0  // ᯣ
#define UC_BATAK_I                               0x1BE4 0  // ᯤ
#define UC_BATAK_U                               0x1BE5 0  // ᯥ
#define UC_BATAK_SIGN_TOMPI                      0x1BE6 0  // ᯦
#define UC_BATAK_VOWEL_SIGN_E                    0x1BE7 0  // ᯧ
#define UC_BATAK_VOWEL_SIGN_PAKPAK_E             0x1BE8 0  // ᯨ
#define UC_BATAK_VOWEL_SIGN_EE                   0x1BE9 0  // ᯩ
#define UC_BATAK_VOWEL_SIGN_I                    0x1BEA 0  // ᯪ
#define UC_BATAK_VOWEL_SIGN_KARO_I               0x1BEB 0  // ᯫ
#define UC_BATAK_VOWEL_SIGN_O                    0x1BEC 0  // ᯬ
#define UC_BATAK_VOWEL_SIGN_KARO_O               0x1BED 0  // ᯭ
#define UC_BATAK_VOWEL_SIGN_U                    0x1BEE 0  // ᯮ
#define UC_BATAK_VOWEL_SIGN_U_FOR_SIMALUNGUN_SA  0x1BEF 0  // ᯯ
#define UC_BATAK_CONSONANT_SIGN_NG               0x1BF0 0  // ᯰ
#define UC_BATAK_CONSONANT_SIGN_H                0x1BF1 0  // ᯱ
#define UC_BATAK_PANGOLAT                        0x1BF2 0  // ᯲
#define UC_BATAK_PANONGONAN                      0x1BF3 0  // ᯳
#define UC_BATAK_BINDU_NA_METEK                  0x1BFC 0  // ᯼
#define UC_BATAK_BINDU_PINARBORAS                0x1BFD 0  // ᯽
#define UC_BATAK_BINDU_JUDUL                     0x1BFE 0  // ᯾
#define UC_BATAK_BINDU_PANGOLAT                  0x1BFF 0  // ᯿
