/* beria_erfe.h – Unicode constants for U+16EA0 … U+16EDF
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
*
* See https://www.unicode.org/versions/latest/ for source data.

 * The Zaghawa or Beria script , Beria Giray Erfe (𖺡𖺾𖻌𖻂𖺻 𖺥𖻂𖻌𖺻𖻓 𖺣𖻌𖺿𖺾𖺾)
 * ('Zaghawa Writing Marks'), is an indigenous alphabetic script proposed for
 * the Zaghawa language (also known as Beria) of Sudan , Chad , and Libya . It
 * is one of three scripts used to write Zaghawa, alongside Latin and
 * incipiently Arabic.
 * In the 1950s, a Sudanese Zaghawa schoolteacher named Adam Tajir created a
 * script for the Zaghawa language, sometimes known as the camel alphabet ,
 * deriving its glyphs from the clan brands used for camels and other
 * livestock. He copied the inventory of the Arabic script , so the system was
 * not ideal for Zaghawa.
 *

* Consistency Check:
* Total Defined Code Points: 50
* Total Significant Hex Values: 50
* Status: OK (Counts Match)

*/

#ifndef BERIA_ERFE_H
#define BERIA_ERFE_H

#define UC_BERIA_ERFE_CAPITAL_ARKAB              0x16EA0 0  // 𖺠
#define UC_BERIA_ERFE_CAPITAL_BASIGNA            0x16EA1 0  // 𖺡
#define UC_BERIA_ERFE_CAPITAL_DARBAI             0x16EA2 0  // 𖺢
#define UC_BERIA_ERFE_CAPITAL_EH                 0x16EA3 0  // 𖺣
#define UC_BERIA_ERFE_CAPITAL_FITKO              0x16EA4 0  // 𖺤
#define UC_BERIA_ERFE_CAPITAL_GOWAY              0x16EA5 0  // 𖺥
#define UC_BERIA_ERFE_CAPITAL_HIRDEABO           0x16EA6 0  // 𖺦
#define UC_BERIA_ERFE_CAPITAL_I                  0x16EA7 0  // 𖺧
#define UC_BERIA_ERFE_CAPITAL_DJAI               0x16EA8 0  // 𖺨
#define UC_BERIA_ERFE_CAPITAL_KOBO               0x16EA9 0  // 𖺩
#define UC_BERIA_ERFE_CAPITAL_LAKKO              0x16EAA 0  // 𖺪
#define UC_BERIA_ERFE_CAPITAL_MERI               0x16EAB 0  // 𖺫
#define UC_BERIA_ERFE_CAPITAL_NINI               0x16EAC 0  // 𖺬
#define UC_BERIA_ERFE_CAPITAL_GNA                0x16EAD 0  // 𖺭
#define UC_BERIA_ERFE_CAPITAL_NGAY               0x16EAE 0  // 𖺮
#define UC_BERIA_ERFE_CAPITAL_OI                 0x16EAF 0  // 𖺯
#define UC_BERIA_ERFE_CAPITAL_PI                 0x16EB0 0  // 𖺰
#define UC_BERIA_ERFE_CAPITAL_ERIGO              0x16EB1 0  // 𖺱
#define UC_BERIA_ERFE_CAPITAL_ERIGO_TAMURA       0x16EB2 0  // 𖺲
#define UC_BERIA_ERFE_CAPITAL_SERI               0x16EB3 0  // 𖺳
#define UC_BERIA_ERFE_CAPITAL_SHEP               0x16EB4 0  // 𖺴
#define UC_BERIA_ERFE_CAPITAL_TATASOUE           0x16EB5 0  // 𖺵
#define UC_BERIA_ERFE_CAPITAL_UI                 0x16EB6 0  // 𖺶
#define UC_BERIA_ERFE_CAPITAL_WASSE              0x16EB7 0  // 𖺷
#define UC_BERIA_ERFE_CAPITAL_AY                 0x16EB8 0  // 𖺸
#define UC_BERIA_ERFE_SMALL_ARKAB                0x16EBB 0  // 𖺻
#define UC_BERIA_ERFE_SMALL_BASIGNA              0x16EBC 0  // 𖺼
#define UC_BERIA_ERFE_SMALL_DARBAI               0x16EBD 0  // 𖺽
#define UC_BERIA_ERFE_SMALL_EH                   0x16EBE 0  // 𖺾
#define UC_BERIA_ERFE_SMALL_FITKO                0x16EBF 0  // 𖺿
#define UC_BERIA_ERFE_SMALL_GOWAY                0x16EC0 0  // 𖻀
#define UC_BERIA_ERFE_SMALL_HIRDEABO             0x16EC1 0  // 𖻁
#define UC_BERIA_ERFE_SMALL_I                    0x16EC2 0  // 𖻂
#define UC_BERIA_ERFE_SMALL_DJAI                 0x16EC3 0  // 𖻃
#define UC_BERIA_ERFE_SMALL_KOBO                 0x16EC4 0  // 𖻄
#define UC_BERIA_ERFE_SMALL_LAKKO                0x16EC5 0  // 𖻅
#define UC_BERIA_ERFE_SMALL_MERI                 0x16EC6 0  // 𖻆
#define UC_BERIA_ERFE_SMALL_NINI                 0x16EC7 0  // 𖻇
#define UC_BERIA_ERFE_SMALL_GNA                  0x16EC8 0  // 𖻈
#define UC_BERIA_ERFE_SMALL_NGAY                 0x16EC9 0  // 𖻉
#define UC_BERIA_ERFE_SMALL_OI                   0x16ECA 0  // 𖻊
#define UC_BERIA_ERFE_SMALL_PI                   0x16ECB 0  // 𖻋
#define UC_BERIA_ERFE_SMALL_ERIGO                0x16ECC 0  // 𖻌
#define UC_BERIA_ERFE_SMALL_ERIGO_TAMURA         0x16ECD 0  // 𖻍
#define UC_BERIA_ERFE_SMALL_SERI                 0x16ECE 0  // 𖻎
#define UC_BERIA_ERFE_SMALL_SHEP                 0x16ECF 0  // 𖻏
#define UC_BERIA_ERFE_SMALL_TATASOUE             0x16ED0 0  // 𖻐
#define UC_BERIA_ERFE_SMALL_UI                   0x16ED1 0  // 𖻑
#define UC_BERIA_ERFE_SMALL_WASSE                0x16ED2 0  // 𖻒
#define UC_BERIA_ERFE_SMALL_AY                   0x16ED3 0  // 𖻓

#endif // BERIA_ERFE_H
