/* Bhaiksuki.h – Unicode constants for U+11C00 … U+11C6F
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_BHAIKSUKI_LETTER_A                    0x11C00   /* U+11C00 (BHAIKSUKI LETTER A) 𑰀 */
#define UC_BHAIKSUKI_LETTER_AA                   0x11C01   /* U+11C01 (BHAIKSUKI LETTER AA) 𑰁 */
#define UC_BHAIKSUKI_LETTER_I                    0x11C02   /* U+11C02 (BHAIKSUKI LETTER I) 𑰂 */
#define UC_BHAIKSUKI_LETTER_II                   0x11C03   /* U+11C03 (BHAIKSUKI LETTER II) 𑰃 */
#define UC_BHAIKSUKI_LETTER_U                    0x11C04   /* U+11C04 (BHAIKSUKI LETTER U) 𑰄 */
#define UC_BHAIKSUKI_LETTER_UU                   0x11C05   /* U+11C05 (BHAIKSUKI LETTER UU) 𑰅 */
#define UC_BHAIKSUKI_LETTER_VOCALIC_R            0x11C06   /* U+11C06 (BHAIKSUKI LETTER VOCALIC R) 𑰆 */
#define UC_BHAIKSUKI_LETTER_VOCALIC_RR           0x11C07   /* U+11C07 (BHAIKSUKI LETTER VOCALIC RR) 𑰇 */
#define UC_BHAIKSUKI_LETTER_VOCALIC_L            0x11C08   /* U+11C08 (BHAIKSUKI LETTER VOCALIC L) 𑰈 */
#define UC_UNKNOWN_11C09                         0x11C09   /* U+11C09 (UNKNOWN_11C09) */
#define UC_BHAIKSUKI_LETTER_E                    0x11C0A   /* U+11C0A (BHAIKSUKI LETTER E) 𑰊 */
#define UC_BHAIKSUKI_LETTER_AI                   0x11C0B   /* U+11C0B (BHAIKSUKI LETTER AI) 𑰋 */
#define UC_BHAIKSUKI_LETTER_O                    0x11C0C   /* U+11C0C (BHAIKSUKI LETTER O) 𑰌 */
#define UC_BHAIKSUKI_LETTER_AU                   0x11C0D   /* U+11C0D (BHAIKSUKI LETTER AU) 𑰍 */
#define UC_BHAIKSUKI_LETTER_KA                   0x11C0E   /* U+11C0E (BHAIKSUKI LETTER KA) 𑰎 */
#define UC_BHAIKSUKI_LETTER_KHA                  0x11C0F   /* U+11C0F (BHAIKSUKI LETTER KHA) 𑰏 */
#define UC_BHAIKSUKI_LETTER_GA                   0x11C10   /* U+11C10 (BHAIKSUKI LETTER GA) 𑰐 */
#define UC_BHAIKSUKI_LETTER_GHA                  0x11C11   /* U+11C11 (BHAIKSUKI LETTER GHA) 𑰑 */
#define UC_BHAIKSUKI_LETTER_NGA                  0x11C12   /* U+11C12 (BHAIKSUKI LETTER NGA) 𑰒 */
#define UC_BHAIKSUKI_LETTER_CA                   0x11C13   /* U+11C13 (BHAIKSUKI LETTER CA) 𑰓 */
#define UC_BHAIKSUKI_LETTER_CHA                  0x11C14   /* U+11C14 (BHAIKSUKI LETTER CHA) 𑰔 */
#define UC_BHAIKSUKI_LETTER_JA                   0x11C15   /* U+11C15 (BHAIKSUKI LETTER JA) 𑰕 */
#define UC_BHAIKSUKI_LETTER_JHA                  0x11C16   /* U+11C16 (BHAIKSUKI LETTER JHA) 𑰖 */
#define UC_BHAIKSUKI_LETTER_NYA                  0x11C17   /* U+11C17 (BHAIKSUKI LETTER NYA) 𑰗 */
#define UC_BHAIKSUKI_LETTER_TTA                  0x11C18   /* U+11C18 (BHAIKSUKI LETTER TTA) 𑰘 */
#define UC_BHAIKSUKI_LETTER_TTHA                 0x11C19   /* U+11C19 (BHAIKSUKI LETTER TTHA) 𑰙 */
#define UC_BHAIKSUKI_LETTER_DDA                  0x11C1A   /* U+11C1A (BHAIKSUKI LETTER DDA) 𑰚 */
#define UC_BHAIKSUKI_LETTER_DDHA                 0x11C1B   /* U+11C1B (BHAIKSUKI LETTER DDHA) 𑰛 */
#define UC_BHAIKSUKI_LETTER_NNA                  0x11C1C   /* U+11C1C (BHAIKSUKI LETTER NNA) 𑰜 */
#define UC_BHAIKSUKI_LETTER_TA                   0x11C1D   /* U+11C1D (BHAIKSUKI LETTER TA) 𑰝 */
#define UC_BHAIKSUKI_LETTER_THA                  0x11C1E   /* U+11C1E (BHAIKSUKI LETTER THA) 𑰞 */
#define UC_BHAIKSUKI_LETTER_DA                   0x11C1F   /* U+11C1F (BHAIKSUKI LETTER DA) 𑰟 */
#define UC_BHAIKSUKI_LETTER_DHA                  0x11C20   /* U+11C20 (BHAIKSUKI LETTER DHA) 𑰠 */
#define UC_BHAIKSUKI_LETTER_NA                   0x11C21   /* U+11C21 (BHAIKSUKI LETTER NA) 𑰡 */
#define UC_BHAIKSUKI_LETTER_PA                   0x11C22   /* U+11C22 (BHAIKSUKI LETTER PA) 𑰢 */
#define UC_BHAIKSUKI_LETTER_PHA                  0x11C23   /* U+11C23 (BHAIKSUKI LETTER PHA) 𑰣 */
#define UC_BHAIKSUKI_LETTER_BA                   0x11C24   /* U+11C24 (BHAIKSUKI LETTER BA) 𑰤 */
#define UC_BHAIKSUKI_LETTER_BHA                  0x11C25   /* U+11C25 (BHAIKSUKI LETTER BHA) 𑰥 */
#define UC_BHAIKSUKI_LETTER_MA                   0x11C26   /* U+11C26 (BHAIKSUKI LETTER MA) 𑰦 */
#define UC_BHAIKSUKI_LETTER_YA                   0x11C27   /* U+11C27 (BHAIKSUKI LETTER YA) 𑰧 */
#define UC_BHAIKSUKI_LETTER_RA                   0x11C28   /* U+11C28 (BHAIKSUKI LETTER RA) 𑰨 */
#define UC_BHAIKSUKI_LETTER_LA                   0x11C29   /* U+11C29 (BHAIKSUKI LETTER LA) 𑰩 */
#define UC_BHAIKSUKI_LETTER_VA                   0x11C2A   /* U+11C2A (BHAIKSUKI LETTER VA) 𑰪 */
#define UC_BHAIKSUKI_LETTER_SHA                  0x11C2B   /* U+11C2B (BHAIKSUKI LETTER SHA) 𑰫 */
#define UC_BHAIKSUKI_LETTER_SSA                  0x11C2C   /* U+11C2C (BHAIKSUKI LETTER SSA) 𑰬 */
#define UC_BHAIKSUKI_LETTER_SA                   0x11C2D   /* U+11C2D (BHAIKSUKI LETTER SA) 𑰭 */
#define UC_BHAIKSUKI_LETTER_HA                   0x11C2E   /* U+11C2E (BHAIKSUKI LETTER HA) 𑰮 */
#define UC_BHAIKSUKI_VOWEL_SIGN_AA               0x11C2F   /* U+11C2F (BHAIKSUKI VOWEL SIGN AA) 𑰯 */
#define UC_BHAIKSUKI_VOWEL_SIGN_I                0x11C30   /* U+11C30 (BHAIKSUKI VOWEL SIGN I) 𑰰 */
#define UC_BHAIKSUKI_VOWEL_SIGN_II               0x11C31   /* U+11C31 (BHAIKSUKI VOWEL SIGN II) 𑰱 */
#define UC_BHAIKSUKI_VOWEL_SIGN_U                0x11C32   /* U+11C32 (BHAIKSUKI VOWEL SIGN U) 𑰲 */
#define UC_BHAIKSUKI_VOWEL_SIGN_UU               0x11C33   /* U+11C33 (BHAIKSUKI VOWEL SIGN UU) 𑰳 */
#define UC_BHAIKSUKI_VOWEL_SIGN_VOCALIC_R        0x11C34   /* U+11C34 (BHAIKSUKI VOWEL SIGN VOCALIC R) 𑰴 */
#define UC_BHAIKSUKI_VOWEL_SIGN_VOCALIC_RR       0x11C35   /* U+11C35 (BHAIKSUKI VOWEL SIGN VOCALIC RR) 𑰵 */
#define UC_BHAIKSUKI_VOWEL_SIGN_VOCALIC_L        0x11C36   /* U+11C36 (BHAIKSUKI VOWEL SIGN VOCALIC L) 𑰶 */
#define UC_UNKNOWN_11C37                         0x11C37   /* U+11C37 (UNKNOWN_11C37) */
#define UC_BHAIKSUKI_VOWEL_SIGN_E                0x11C38   /* U+11C38 (BHAIKSUKI VOWEL SIGN E) 𑰸 */
#define UC_BHAIKSUKI_VOWEL_SIGN_AI               0x11C39   /* U+11C39 (BHAIKSUKI VOWEL SIGN AI) 𑰹 */
#define UC_BHAIKSUKI_VOWEL_SIGN_O                0x11C3A   /* U+11C3A (BHAIKSUKI VOWEL SIGN O) 𑰺 */
#define UC_BHAIKSUKI_VOWEL_SIGN_AU               0x11C3B   /* U+11C3B (BHAIKSUKI VOWEL SIGN AU) 𑰻 */
#define UC_BHAIKSUKI_SIGN_CANDRABINDU            0x11C3C   /* U+11C3C (BHAIKSUKI SIGN CANDRABINDU) 𑰼 */
#define UC_BHAIKSUKI_SIGN_ANUSVARA               0x11C3D   /* U+11C3D (BHAIKSUKI SIGN ANUSVARA) 𑰽 */
#define UC_BHAIKSUKI_SIGN_VISARGA                0x11C3E   /* U+11C3E (BHAIKSUKI SIGN VISARGA) 𑰾 */
#define UC_BHAIKSUKI_SIGN_VIRAMA                 0x11C3F   /* U+11C3F (BHAIKSUKI SIGN VIRAMA) 𑰿 */
#define UC_BHAIKSUKI_SIGN_AVAGRAHA               0x11C40   /* U+11C40 (BHAIKSUKI SIGN AVAGRAHA) 𑱀 */
#define UC_BHAIKSUKI_DANDA                       0x11C41   /* U+11C41 (BHAIKSUKI DANDA) 𑱁 */
#define UC_BHAIKSUKI_DOUBLE_DANDA                0x11C42   /* U+11C42 (BHAIKSUKI DOUBLE DANDA) 𑱂 */
#define UC_BHAIKSUKI_WORD_SEPARATOR              0x11C43   /* U+11C43 (BHAIKSUKI WORD SEPARATOR) 𑱃 */
#define UC_BHAIKSUKI_GAP_FILLER_1                0x11C44   /* U+11C44 (BHAIKSUKI GAP FILLER-1) 𑱄 */
#define UC_BHAIKSUKI_GAP_FILLER_2                0x11C45   /* U+11C45 (BHAIKSUKI GAP FILLER-2) 𑱅 */
#define UC_UNKNOWN_11C46                         0x11C46   /* U+11C46 (UNKNOWN_11C46) */
#define UC_UNKNOWN_11C47                         0x11C47   /* U+11C47 (UNKNOWN_11C47) */
#define UC_UNKNOWN_11C48                         0x11C48   /* U+11C48 (UNKNOWN_11C48) */
#define UC_UNKNOWN_11C49                         0x11C49   /* U+11C49 (UNKNOWN_11C49) */
#define UC_UNKNOWN_11C4A                         0x11C4A   /* U+11C4A (UNKNOWN_11C4A) */
#define UC_UNKNOWN_11C4B                         0x11C4B   /* U+11C4B (UNKNOWN_11C4B) */
#define UC_UNKNOWN_11C4C                         0x11C4C   /* U+11C4C (UNKNOWN_11C4C) */
#define UC_UNKNOWN_11C4D                         0x11C4D   /* U+11C4D (UNKNOWN_11C4D) */
#define UC_UNKNOWN_11C4E                         0x11C4E   /* U+11C4E (UNKNOWN_11C4E) */
#define UC_UNKNOWN_11C4F                         0x11C4F   /* U+11C4F (UNKNOWN_11C4F) */
#define UC_BHAIKSUKI_DIGIT_ZERO                  0x11C50   /* U+11C50 (BHAIKSUKI DIGIT ZERO) 𑱐 */
#define UC_BHAIKSUKI_DIGIT_ONE                   0x11C51   /* U+11C51 (BHAIKSUKI DIGIT ONE) 𑱑 */
#define UC_BHAIKSUKI_DIGIT_TWO                   0x11C52   /* U+11C52 (BHAIKSUKI DIGIT TWO) 𑱒 */
#define UC_BHAIKSUKI_DIGIT_THREE                 0x11C53   /* U+11C53 (BHAIKSUKI DIGIT THREE) 𑱓 */
#define UC_BHAIKSUKI_DIGIT_FOUR                  0x11C54   /* U+11C54 (BHAIKSUKI DIGIT FOUR) 𑱔 */
#define UC_BHAIKSUKI_DIGIT_FIVE                  0x11C55   /* U+11C55 (BHAIKSUKI DIGIT FIVE) 𑱕 */
#define UC_BHAIKSUKI_DIGIT_SIX                   0x11C56   /* U+11C56 (BHAIKSUKI DIGIT SIX) 𑱖 */
#define UC_BHAIKSUKI_DIGIT_SEVEN                 0x11C57   /* U+11C57 (BHAIKSUKI DIGIT SEVEN) 𑱗 */
#define UC_BHAIKSUKI_DIGIT_EIGHT                 0x11C58   /* U+11C58 (BHAIKSUKI DIGIT EIGHT) 𑱘 */
#define UC_BHAIKSUKI_DIGIT_NINE                  0x11C59   /* U+11C59 (BHAIKSUKI DIGIT NINE) 𑱙 */
#define UC_BHAIKSUKI_NUMBER_ONE                  0x11C5A   /* U+11C5A (BHAIKSUKI NUMBER ONE) 𑱚 */
#define UC_BHAIKSUKI_NUMBER_TWO                  0x11C5B   /* U+11C5B (BHAIKSUKI NUMBER TWO) 𑱛 */
#define UC_BHAIKSUKI_NUMBER_THREE                0x11C5C   /* U+11C5C (BHAIKSUKI NUMBER THREE) 𑱜 */
#define UC_BHAIKSUKI_NUMBER_FOUR                 0x11C5D   /* U+11C5D (BHAIKSUKI NUMBER FOUR) 𑱝 */
#define UC_BHAIKSUKI_NUMBER_FIVE                 0x11C5E   /* U+11C5E (BHAIKSUKI NUMBER FIVE) 𑱞 */
#define UC_BHAIKSUKI_NUMBER_SIX                  0x11C5F   /* U+11C5F (BHAIKSUKI NUMBER SIX) 𑱟 */
#define UC_BHAIKSUKI_NUMBER_SEVEN                0x11C60   /* U+11C60 (BHAIKSUKI NUMBER SEVEN) 𑱠 */
#define UC_BHAIKSUKI_NUMBER_EIGHT                0x11C61   /* U+11C61 (BHAIKSUKI NUMBER EIGHT) 𑱡 */
#define UC_BHAIKSUKI_NUMBER_NINE                 0x11C62   /* U+11C62 (BHAIKSUKI NUMBER NINE) 𑱢 */
#define UC_BHAIKSUKI_NUMBER_TEN                  0x11C63   /* U+11C63 (BHAIKSUKI NUMBER TEN) 𑱣 */
#define UC_BHAIKSUKI_NUMBER_TWENTY               0x11C64   /* U+11C64 (BHAIKSUKI NUMBER TWENTY) 𑱤 */
#define UC_BHAIKSUKI_NUMBER_THIRTY               0x11C65   /* U+11C65 (BHAIKSUKI NUMBER THIRTY) 𑱥 */
#define UC_BHAIKSUKI_NUMBER_FORTY                0x11C66   /* U+11C66 (BHAIKSUKI NUMBER FORTY) 𑱦 */
#define UC_BHAIKSUKI_NUMBER_FIFTY                0x11C67   /* U+11C67 (BHAIKSUKI NUMBER FIFTY) 𑱧 */
#define UC_BHAIKSUKI_NUMBER_SIXTY                0x11C68   /* U+11C68 (BHAIKSUKI NUMBER SIXTY) 𑱨 */
#define UC_BHAIKSUKI_NUMBER_SEVENTY              0x11C69   /* U+11C69 (BHAIKSUKI NUMBER SEVENTY) 𑱩 */
#define UC_BHAIKSUKI_NUMBER_EIGHTY               0x11C6A   /* U+11C6A (BHAIKSUKI NUMBER EIGHTY) 𑱪 */
#define UC_BHAIKSUKI_NUMBER_NINETY               0x11C6B   /* U+11C6B (BHAIKSUKI NUMBER NINETY) 𑱫 */
#define UC_BHAIKSUKI_HUNDREDS_UNIT_MARK          0x11C6C   /* U+11C6C (BHAIKSUKI HUNDREDS UNIT MARK) 𑱬 */
#define UC_UNKNOWN_11C6D                         0x11C6D   /* U+11C6D (UNKNOWN_11C6D) */
#define UC_UNKNOWN_11C6E                         0x11C6E   /* U+11C6E (UNKNOWN_11C6E) */
#define UC_UNKNOWN_11C6F                         0x11C6F   /* U+11C6F (UNKNOWN_11C6F) */
