/* Latin Extended-G.h – Unicode constants for U+1DF00 … U+1DFFF
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_LATIN_SMALL_LETTER_FENG_DIGRAPH_WITH_TRILL 0x1DF00   /* U+1DF00 (LATIN SMALL LETTER FENG DIGRAPH WITH TRILL) 𝼀 */
#define UC_LATIN_SMALL_LETTER_REVERSED_SCRIPT_G  0x1DF01   /* U+1DF01 (LATIN SMALL LETTER REVERSED SCRIPT G) 𝼁 */
#define UC_LATIN_LETTER_SMALL_CAPITAL_TURNED_G   0x1DF02   /* U+1DF02 (LATIN LETTER SMALL CAPITAL TURNED G) 𝼂 */
#define UC_LATIN_SMALL_LETTER_REVERSED_K         0x1DF03   /* U+1DF03 (LATIN SMALL LETTER REVERSED K) 𝼃 */
#define UC_LATIN_LETTER_SMALL_CAPITAL_L_WITH_BELT 0x1DF04   /* U+1DF04 (LATIN LETTER SMALL CAPITAL L WITH BELT) 𝼄 */
#define UC_LATIN_SMALL_LETTER_LEZH_WITH_RETROFLEX_HOOK 0x1DF05   /* U+1DF05 (LATIN SMALL LETTER LEZH WITH RETROFLEX HOOK) 𝼅 */
#define UC_LATIN_SMALL_LETTER_TURNED_Y_WITH_BELT 0x1DF06   /* U+1DF06 (LATIN SMALL LETTER TURNED Y WITH BELT) 𝼆 */
#define UC_LATIN_SMALL_LETTER_REVERSED_ENG       0x1DF07   /* U+1DF07 (LATIN SMALL LETTER REVERSED ENG) 𝼇 */
#define UC_LATIN_SMALL_LETTER_TURNED_R_WITH_LONG_LEG_AND_RETROFLEX_HOOK 0x1DF08   /* U+1DF08 (LATIN SMALL LETTER TURNED R WITH LONG LEG AND RETROFLEX HOOK) 𝼈 */
#define UC_LATIN_SMALL_LETTER_T_WITH_HOOK_AND_RETROFLEX_HOOK 0x1DF09   /* U+1DF09 (LATIN SMALL LETTER T WITH HOOK AND RETROFLEX HOOK) 𝼉 */
#define UC_LATIN_LETTER_RETROFLEX_CLICK_WITH_RETROFLEX_HOOK 0x1DF0A   /* U+1DF0A (LATIN LETTER RETROFLEX CLICK WITH RETROFLEX HOOK) 𝼊 */
#define UC_LATIN_SMALL_LETTER_ESH_WITH_DOUBLE_BAR 0x1DF0B   /* U+1DF0B (LATIN SMALL LETTER ESH WITH DOUBLE BAR) 𝼋 */
#define UC_LATIN_SMALL_LETTER_ESH_WITH_DOUBLE_BAR_AND_CURL 0x1DF0C   /* U+1DF0C (LATIN SMALL LETTER ESH WITH DOUBLE BAR AND CURL) 𝼌 */
#define UC_LATIN_SMALL_LETTER_TURNED_T_WITH_CURL 0x1DF0D   /* U+1DF0D (LATIN SMALL LETTER TURNED T WITH CURL) 𝼍 */
#define UC_LATIN_LETTER_INVERTED_GLOTTAL_STOP_WITH_CURL 0x1DF0E   /* U+1DF0E (LATIN LETTER INVERTED GLOTTAL STOP WITH CURL) 𝼎 */
#define UC_LATIN_LETTER_STRETCHED_C_WITH_CURL    0x1DF0F   /* U+1DF0F (LATIN LETTER STRETCHED C WITH CURL) 𝼏 */
#define UC_LATIN_LETTER_SMALL_CAPITAL_TURNED_K   0x1DF10   /* U+1DF10 (LATIN LETTER SMALL CAPITAL TURNED K) 𝼐 */
#define UC_LATIN_SMALL_LETTER_L_WITH_FISHHOOK    0x1DF11   /* U+1DF11 (LATIN SMALL LETTER L WITH FISHHOOK) 𝼑 */
#define UC_LATIN_SMALL_LETTER_DEZH_DIGRAPH_WITH_PALATAL_HOOK 0x1DF12   /* U+1DF12 (LATIN SMALL LETTER DEZH DIGRAPH WITH PALATAL HOOK) 𝼒 */
#define UC_LATIN_SMALL_LETTER_L_WITH_BELT_AND_PALATAL_HOOK 0x1DF13   /* U+1DF13 (LATIN SMALL LETTER L WITH BELT AND PALATAL HOOK) 𝼓 */
#define UC_LATIN_SMALL_LETTER_ENG_WITH_PALATAL_HOOK 0x1DF14   /* U+1DF14 (LATIN SMALL LETTER ENG WITH PALATAL HOOK) 𝼔 */
#define UC_LATIN_SMALL_LETTER_TURNED_R_WITH_PALATAL_HOOK 0x1DF15   /* U+1DF15 (LATIN SMALL LETTER TURNED R WITH PALATAL HOOK) 𝼕 */
#define UC_LATIN_SMALL_LETTER_R_WITH_FISHHOOK_AND_PALATAL_HOOK 0x1DF16   /* U+1DF16 (LATIN SMALL LETTER R WITH FISHHOOK AND PALATAL HOOK) 𝼖 */
#define UC_LATIN_SMALL_LETTER_TESH_DIGRAPH_WITH_PALATAL_HOOK 0x1DF17   /* U+1DF17 (LATIN SMALL LETTER TESH DIGRAPH WITH PALATAL HOOK) 𝼗 */
#define UC_LATIN_SMALL_LETTER_EZH_WITH_PALATAL_HOOK 0x1DF18   /* U+1DF18 (LATIN SMALL LETTER EZH WITH PALATAL HOOK) 𝼘 */
#define UC_LATIN_SMALL_LETTER_DEZH_DIGRAPH_WITH_RETROFLEX_HOOK 0x1DF19   /* U+1DF19 (LATIN SMALL LETTER DEZH DIGRAPH WITH RETROFLEX HOOK) 𝼙 */
#define UC_LATIN_SMALL_LETTER_I_WITH_STROKE_AND_RETROFLEX_HOOK 0x1DF1A   /* U+1DF1A (LATIN SMALL LETTER I WITH STROKE AND RETROFLEX HOOK) 𝼚 */
#define UC_LATIN_SMALL_LETTER_O_WITH_RETROFLEX_HOOK 0x1DF1B   /* U+1DF1B (LATIN SMALL LETTER O WITH RETROFLEX HOOK) 𝼛 */
#define UC_LATIN_SMALL_LETTER_TESH_DIGRAPH_WITH_RETROFLEX_HOOK 0x1DF1C   /* U+1DF1C (LATIN SMALL LETTER TESH DIGRAPH WITH RETROFLEX HOOK) 𝼜 */
#define UC_LATIN_SMALL_LETTER_C_WITH_RETROFLEX_HOOK 0x1DF1D   /* U+1DF1D (LATIN SMALL LETTER C WITH RETROFLEX HOOK) 𝼝 */
#define UC_LATIN_SMALL_LETTER_S_WITH_CURL        0x1DF1E   /* U+1DF1E (LATIN SMALL LETTER S WITH CURL) 𝼞 */
#define UC_UNKNOWN_1DF1F                         0x1DF1F   /* U+1DF1F (UNKNOWN_1DF1F) */
#define UC_UNKNOWN_1DF20                         0x1DF20   /* U+1DF20 (UNKNOWN_1DF20) */
#define UC_UNKNOWN_1DF21                         0x1DF21   /* U+1DF21 (UNKNOWN_1DF21) */
#define UC_UNKNOWN_1DF22                         0x1DF22   /* U+1DF22 (UNKNOWN_1DF22) */
#define UC_UNKNOWN_1DF23                         0x1DF23   /* U+1DF23 (UNKNOWN_1DF23) */
#define UC_UNKNOWN_1DF24                         0x1DF24   /* U+1DF24 (UNKNOWN_1DF24) */
#define UC_LATIN_SMALL_LETTER_D_WITH_MID_HEIGHT_LEFT_HOOK 0x1DF25   /* U+1DF25 (LATIN SMALL LETTER D WITH MID-HEIGHT LEFT HOOK) 𝼥 */
#define UC_LATIN_SMALL_LETTER_L_WITH_MID_HEIGHT_LEFT_HOOK 0x1DF26   /* U+1DF26 (LATIN SMALL LETTER L WITH MID-HEIGHT LEFT HOOK) 𝼦 */
#define UC_LATIN_SMALL_LETTER_N_WITH_MID_HEIGHT_LEFT_HOOK 0x1DF27   /* U+1DF27 (LATIN SMALL LETTER N WITH MID-HEIGHT LEFT HOOK) 𝼧 */
#define UC_LATIN_SMALL_LETTER_R_WITH_MID_HEIGHT_LEFT_HOOK 0x1DF28   /* U+1DF28 (LATIN SMALL LETTER R WITH MID-HEIGHT LEFT HOOK) 𝼨 */
#define UC_LATIN_SMALL_LETTER_S_WITH_MID_HEIGHT_LEFT_HOOK 0x1DF29   /* U+1DF29 (LATIN SMALL LETTER S WITH MID-HEIGHT LEFT HOOK) 𝼩 */
#define UC_LATIN_SMALL_LETTER_T_WITH_MID_HEIGHT_LEFT_HOOK 0x1DF2A   /* U+1DF2A (LATIN SMALL LETTER T WITH MID-HEIGHT LEFT HOOK) 𝼪 */
#define UC_UNKNOWN_1DF2B                         0x1DF2B   /* U+1DF2B (UNKNOWN_1DF2B) */
#define UC_UNKNOWN_1DF2C                         0x1DF2C   /* U+1DF2C (UNKNOWN_1DF2C) */
#define UC_UNKNOWN_1DF2D                         0x1DF2D   /* U+1DF2D (UNKNOWN_1DF2D) */
#define UC_UNKNOWN_1DF2E                         0x1DF2E   /* U+1DF2E (UNKNOWN_1DF2E) */
#define UC_UNKNOWN_1DF2F                         0x1DF2F   /* U+1DF2F (UNKNOWN_1DF2F) */
#define UC_UNKNOWN_1DF30                         0x1DF30   /* U+1DF30 (UNKNOWN_1DF30) */
#define UC_UNKNOWN_1DF31                         0x1DF31   /* U+1DF31 (UNKNOWN_1DF31) */
#define UC_UNKNOWN_1DF32                         0x1DF32   /* U+1DF32 (UNKNOWN_1DF32) */
#define UC_UNKNOWN_1DF33                         0x1DF33   /* U+1DF33 (UNKNOWN_1DF33) */
#define UC_UNKNOWN_1DF34                         0x1DF34   /* U+1DF34 (UNKNOWN_1DF34) */
#define UC_UNKNOWN_1DF35                         0x1DF35   /* U+1DF35 (UNKNOWN_1DF35) */
#define UC_UNKNOWN_1DF36                         0x1DF36   /* U+1DF36 (UNKNOWN_1DF36) */
#define UC_UNKNOWN_1DF37                         0x1DF37   /* U+1DF37 (UNKNOWN_1DF37) */
#define UC_UNKNOWN_1DF38                         0x1DF38   /* U+1DF38 (UNKNOWN_1DF38) */
#define UC_UNKNOWN_1DF39                         0x1DF39   /* U+1DF39 (UNKNOWN_1DF39) */
#define UC_UNKNOWN_1DF3A                         0x1DF3A   /* U+1DF3A (UNKNOWN_1DF3A) */
#define UC_UNKNOWN_1DF3B                         0x1DF3B   /* U+1DF3B (UNKNOWN_1DF3B) */
#define UC_UNKNOWN_1DF3C                         0x1DF3C   /* U+1DF3C (UNKNOWN_1DF3C) */
#define UC_UNKNOWN_1DF3D                         0x1DF3D   /* U+1DF3D (UNKNOWN_1DF3D) */
#define UC_UNKNOWN_1DF3E                         0x1DF3E   /* U+1DF3E (UNKNOWN_1DF3E) */
#define UC_UNKNOWN_1DF3F                         0x1DF3F   /* U+1DF3F (UNKNOWN_1DF3F) */
#define UC_UNKNOWN_1DF40                         0x1DF40   /* U+1DF40 (UNKNOWN_1DF40) */
#define UC_UNKNOWN_1DF41                         0x1DF41   /* U+1DF41 (UNKNOWN_1DF41) */
#define UC_UNKNOWN_1DF42                         0x1DF42   /* U+1DF42 (UNKNOWN_1DF42) */
#define UC_UNKNOWN_1DF43                         0x1DF43   /* U+1DF43 (UNKNOWN_1DF43) */
#define UC_UNKNOWN_1DF44                         0x1DF44   /* U+1DF44 (UNKNOWN_1DF44) */
#define UC_UNKNOWN_1DF45                         0x1DF45   /* U+1DF45 (UNKNOWN_1DF45) */
#define UC_UNKNOWN_1DF46                         0x1DF46   /* U+1DF46 (UNKNOWN_1DF46) */
#define UC_UNKNOWN_1DF47                         0x1DF47   /* U+1DF47 (UNKNOWN_1DF47) */
#define UC_UNKNOWN_1DF48                         0x1DF48   /* U+1DF48 (UNKNOWN_1DF48) */
#define UC_UNKNOWN_1DF49                         0x1DF49   /* U+1DF49 (UNKNOWN_1DF49) */
#define UC_UNKNOWN_1DF4A                         0x1DF4A   /* U+1DF4A (UNKNOWN_1DF4A) */
#define UC_UNKNOWN_1DF4B                         0x1DF4B   /* U+1DF4B (UNKNOWN_1DF4B) */
#define UC_UNKNOWN_1DF4C                         0x1DF4C   /* U+1DF4C (UNKNOWN_1DF4C) */
#define UC_UNKNOWN_1DF4D                         0x1DF4D   /* U+1DF4D (UNKNOWN_1DF4D) */
#define UC_UNKNOWN_1DF4E                         0x1DF4E   /* U+1DF4E (UNKNOWN_1DF4E) */
#define UC_UNKNOWN_1DF4F                         0x1DF4F   /* U+1DF4F (UNKNOWN_1DF4F) */
#define UC_UNKNOWN_1DF50                         0x1DF50   /* U+1DF50 (UNKNOWN_1DF50) */
#define UC_UNKNOWN_1DF51                         0x1DF51   /* U+1DF51 (UNKNOWN_1DF51) */
#define UC_UNKNOWN_1DF52                         0x1DF52   /* U+1DF52 (UNKNOWN_1DF52) */
#define UC_UNKNOWN_1DF53                         0x1DF53   /* U+1DF53 (UNKNOWN_1DF53) */
#define UC_UNKNOWN_1DF54                         0x1DF54   /* U+1DF54 (UNKNOWN_1DF54) */
#define UC_UNKNOWN_1DF55                         0x1DF55   /* U+1DF55 (UNKNOWN_1DF55) */
#define UC_UNKNOWN_1DF56                         0x1DF56   /* U+1DF56 (UNKNOWN_1DF56) */
#define UC_UNKNOWN_1DF57                         0x1DF57   /* U+1DF57 (UNKNOWN_1DF57) */
#define UC_UNKNOWN_1DF58                         0x1DF58   /* U+1DF58 (UNKNOWN_1DF58) */
#define UC_UNKNOWN_1DF59                         0x1DF59   /* U+1DF59 (UNKNOWN_1DF59) */
#define UC_UNKNOWN_1DF5A                         0x1DF5A   /* U+1DF5A (UNKNOWN_1DF5A) */
#define UC_UNKNOWN_1DF5B                         0x1DF5B   /* U+1DF5B (UNKNOWN_1DF5B) */
#define UC_UNKNOWN_1DF5C                         0x1DF5C   /* U+1DF5C (UNKNOWN_1DF5C) */
#define UC_UNKNOWN_1DF5D                         0x1DF5D   /* U+1DF5D (UNKNOWN_1DF5D) */
#define UC_UNKNOWN_1DF5E                         0x1DF5E   /* U+1DF5E (UNKNOWN_1DF5E) */
#define UC_UNKNOWN_1DF5F                         0x1DF5F   /* U+1DF5F (UNKNOWN_1DF5F) */
#define UC_UNKNOWN_1DF60                         0x1DF60   /* U+1DF60 (UNKNOWN_1DF60) */
#define UC_UNKNOWN_1DF61                         0x1DF61   /* U+1DF61 (UNKNOWN_1DF61) */
#define UC_UNKNOWN_1DF62                         0x1DF62   /* U+1DF62 (UNKNOWN_1DF62) */
#define UC_UNKNOWN_1DF63                         0x1DF63   /* U+1DF63 (UNKNOWN_1DF63) */
#define UC_UNKNOWN_1DF64                         0x1DF64   /* U+1DF64 (UNKNOWN_1DF64) */
#define UC_UNKNOWN_1DF65                         0x1DF65   /* U+1DF65 (UNKNOWN_1DF65) */
#define UC_UNKNOWN_1DF66                         0x1DF66   /* U+1DF66 (UNKNOWN_1DF66) */
#define UC_UNKNOWN_1DF67                         0x1DF67   /* U+1DF67 (UNKNOWN_1DF67) */
#define UC_UNKNOWN_1DF68                         0x1DF68   /* U+1DF68 (UNKNOWN_1DF68) */
#define UC_UNKNOWN_1DF69                         0x1DF69   /* U+1DF69 (UNKNOWN_1DF69) */
#define UC_UNKNOWN_1DF6A                         0x1DF6A   /* U+1DF6A (UNKNOWN_1DF6A) */
#define UC_UNKNOWN_1DF6B                         0x1DF6B   /* U+1DF6B (UNKNOWN_1DF6B) */
#define UC_UNKNOWN_1DF6C                         0x1DF6C   /* U+1DF6C (UNKNOWN_1DF6C) */
#define UC_UNKNOWN_1DF6D                         0x1DF6D   /* U+1DF6D (UNKNOWN_1DF6D) */
#define UC_UNKNOWN_1DF6E                         0x1DF6E   /* U+1DF6E (UNKNOWN_1DF6E) */
#define UC_UNKNOWN_1DF6F                         0x1DF6F   /* U+1DF6F (UNKNOWN_1DF6F) */
#define UC_UNKNOWN_1DF70                         0x1DF70   /* U+1DF70 (UNKNOWN_1DF70) */
#define UC_UNKNOWN_1DF71                         0x1DF71   /* U+1DF71 (UNKNOWN_1DF71) */
#define UC_UNKNOWN_1DF72                         0x1DF72   /* U+1DF72 (UNKNOWN_1DF72) */
#define UC_UNKNOWN_1DF73                         0x1DF73   /* U+1DF73 (UNKNOWN_1DF73) */
#define UC_UNKNOWN_1DF74                         0x1DF74   /* U+1DF74 (UNKNOWN_1DF74) */
#define UC_UNKNOWN_1DF75                         0x1DF75   /* U+1DF75 (UNKNOWN_1DF75) */
#define UC_UNKNOWN_1DF76                         0x1DF76   /* U+1DF76 (UNKNOWN_1DF76) */
#define UC_UNKNOWN_1DF77                         0x1DF77   /* U+1DF77 (UNKNOWN_1DF77) */
#define UC_UNKNOWN_1DF78                         0x1DF78   /* U+1DF78 (UNKNOWN_1DF78) */
#define UC_UNKNOWN_1DF79                         0x1DF79   /* U+1DF79 (UNKNOWN_1DF79) */
#define UC_UNKNOWN_1DF7A                         0x1DF7A   /* U+1DF7A (UNKNOWN_1DF7A) */
#define UC_UNKNOWN_1DF7B                         0x1DF7B   /* U+1DF7B (UNKNOWN_1DF7B) */
#define UC_UNKNOWN_1DF7C                         0x1DF7C   /* U+1DF7C (UNKNOWN_1DF7C) */
#define UC_UNKNOWN_1DF7D                         0x1DF7D   /* U+1DF7D (UNKNOWN_1DF7D) */
#define UC_UNKNOWN_1DF7E                         0x1DF7E   /* U+1DF7E (UNKNOWN_1DF7E) */
#define UC_UNKNOWN_1DF7F                         0x1DF7F   /* U+1DF7F (UNKNOWN_1DF7F) */
#define UC_UNKNOWN_1DF80                         0x1DF80   /* U+1DF80 (UNKNOWN_1DF80) */
#define UC_UNKNOWN_1DF81                         0x1DF81   /* U+1DF81 (UNKNOWN_1DF81) */
#define UC_UNKNOWN_1DF82                         0x1DF82   /* U+1DF82 (UNKNOWN_1DF82) */
#define UC_UNKNOWN_1DF83                         0x1DF83   /* U+1DF83 (UNKNOWN_1DF83) */
#define UC_UNKNOWN_1DF84                         0x1DF84   /* U+1DF84 (UNKNOWN_1DF84) */
#define UC_UNKNOWN_1DF85                         0x1DF85   /* U+1DF85 (UNKNOWN_1DF85) */
#define UC_UNKNOWN_1DF86                         0x1DF86   /* U+1DF86 (UNKNOWN_1DF86) */
#define UC_UNKNOWN_1DF87                         0x1DF87   /* U+1DF87 (UNKNOWN_1DF87) */
#define UC_UNKNOWN_1DF88                         0x1DF88   /* U+1DF88 (UNKNOWN_1DF88) */
#define UC_UNKNOWN_1DF89                         0x1DF89   /* U+1DF89 (UNKNOWN_1DF89) */
#define UC_UNKNOWN_1DF8A                         0x1DF8A   /* U+1DF8A (UNKNOWN_1DF8A) */
#define UC_UNKNOWN_1DF8B                         0x1DF8B   /* U+1DF8B (UNKNOWN_1DF8B) */
#define UC_UNKNOWN_1DF8C                         0x1DF8C   /* U+1DF8C (UNKNOWN_1DF8C) */
#define UC_UNKNOWN_1DF8D                         0x1DF8D   /* U+1DF8D (UNKNOWN_1DF8D) */
#define UC_UNKNOWN_1DF8E                         0x1DF8E   /* U+1DF8E (UNKNOWN_1DF8E) */
#define UC_UNKNOWN_1DF8F                         0x1DF8F   /* U+1DF8F (UNKNOWN_1DF8F) */
#define UC_UNKNOWN_1DF90                         0x1DF90   /* U+1DF90 (UNKNOWN_1DF90) */
#define UC_UNKNOWN_1DF91                         0x1DF91   /* U+1DF91 (UNKNOWN_1DF91) */
#define UC_UNKNOWN_1DF92                         0x1DF92   /* U+1DF92 (UNKNOWN_1DF92) */
#define UC_UNKNOWN_1DF93                         0x1DF93   /* U+1DF93 (UNKNOWN_1DF93) */
#define UC_UNKNOWN_1DF94                         0x1DF94   /* U+1DF94 (UNKNOWN_1DF94) */
#define UC_UNKNOWN_1DF95                         0x1DF95   /* U+1DF95 (UNKNOWN_1DF95) */
#define UC_UNKNOWN_1DF96                         0x1DF96   /* U+1DF96 (UNKNOWN_1DF96) */
#define UC_UNKNOWN_1DF97                         0x1DF97   /* U+1DF97 (UNKNOWN_1DF97) */
#define UC_UNKNOWN_1DF98                         0x1DF98   /* U+1DF98 (UNKNOWN_1DF98) */
#define UC_UNKNOWN_1DF99                         0x1DF99   /* U+1DF99 (UNKNOWN_1DF99) */
#define UC_UNKNOWN_1DF9A                         0x1DF9A   /* U+1DF9A (UNKNOWN_1DF9A) */
#define UC_UNKNOWN_1DF9B                         0x1DF9B   /* U+1DF9B (UNKNOWN_1DF9B) */
#define UC_UNKNOWN_1DF9C                         0x1DF9C   /* U+1DF9C (UNKNOWN_1DF9C) */
#define UC_UNKNOWN_1DF9D                         0x1DF9D   /* U+1DF9D (UNKNOWN_1DF9D) */
#define UC_UNKNOWN_1DF9E                         0x1DF9E   /* U+1DF9E (UNKNOWN_1DF9E) */
#define UC_UNKNOWN_1DF9F                         0x1DF9F   /* U+1DF9F (UNKNOWN_1DF9F) */
#define UC_UNKNOWN_1DFA0                         0x1DFA0   /* U+1DFA0 (UNKNOWN_1DFA0) */
#define UC_UNKNOWN_1DFA1                         0x1DFA1   /* U+1DFA1 (UNKNOWN_1DFA1) */
#define UC_UNKNOWN_1DFA2                         0x1DFA2   /* U+1DFA2 (UNKNOWN_1DFA2) */
#define UC_UNKNOWN_1DFA3                         0x1DFA3   /* U+1DFA3 (UNKNOWN_1DFA3) */
#define UC_UNKNOWN_1DFA4                         0x1DFA4   /* U+1DFA4 (UNKNOWN_1DFA4) */
#define UC_UNKNOWN_1DFA5                         0x1DFA5   /* U+1DFA5 (UNKNOWN_1DFA5) */
#define UC_UNKNOWN_1DFA6                         0x1DFA6   /* U+1DFA6 (UNKNOWN_1DFA6) */
#define UC_UNKNOWN_1DFA7                         0x1DFA7   /* U+1DFA7 (UNKNOWN_1DFA7) */
#define UC_UNKNOWN_1DFA8                         0x1DFA8   /* U+1DFA8 (UNKNOWN_1DFA8) */
#define UC_UNKNOWN_1DFA9                         0x1DFA9   /* U+1DFA9 (UNKNOWN_1DFA9) */
#define UC_UNKNOWN_1DFAA                         0x1DFAA   /* U+1DFAA (UNKNOWN_1DFAA) */
#define UC_UNKNOWN_1DFAB                         0x1DFAB   /* U+1DFAB (UNKNOWN_1DFAB) */
#define UC_UNKNOWN_1DFAC                         0x1DFAC   /* U+1DFAC (UNKNOWN_1DFAC) */
#define UC_UNKNOWN_1DFAD                         0x1DFAD   /* U+1DFAD (UNKNOWN_1DFAD) */
#define UC_UNKNOWN_1DFAE                         0x1DFAE   /* U+1DFAE (UNKNOWN_1DFAE) */
#define UC_UNKNOWN_1DFAF                         0x1DFAF   /* U+1DFAF (UNKNOWN_1DFAF) */
#define UC_UNKNOWN_1DFB0                         0x1DFB0   /* U+1DFB0 (UNKNOWN_1DFB0) */
#define UC_UNKNOWN_1DFB1                         0x1DFB1   /* U+1DFB1 (UNKNOWN_1DFB1) */
#define UC_UNKNOWN_1DFB2                         0x1DFB2   /* U+1DFB2 (UNKNOWN_1DFB2) */
#define UC_UNKNOWN_1DFB3                         0x1DFB3   /* U+1DFB3 (UNKNOWN_1DFB3) */
#define UC_UNKNOWN_1DFB4                         0x1DFB4   /* U+1DFB4 (UNKNOWN_1DFB4) */
#define UC_UNKNOWN_1DFB5                         0x1DFB5   /* U+1DFB5 (UNKNOWN_1DFB5) */
#define UC_UNKNOWN_1DFB6                         0x1DFB6   /* U+1DFB6 (UNKNOWN_1DFB6) */
#define UC_UNKNOWN_1DFB7                         0x1DFB7   /* U+1DFB7 (UNKNOWN_1DFB7) */
#define UC_UNKNOWN_1DFB8                         0x1DFB8   /* U+1DFB8 (UNKNOWN_1DFB8) */
#define UC_UNKNOWN_1DFB9                         0x1DFB9   /* U+1DFB9 (UNKNOWN_1DFB9) */
#define UC_UNKNOWN_1DFBA                         0x1DFBA   /* U+1DFBA (UNKNOWN_1DFBA) */
#define UC_UNKNOWN_1DFBB                         0x1DFBB   /* U+1DFBB (UNKNOWN_1DFBB) */
#define UC_UNKNOWN_1DFBC                         0x1DFBC   /* U+1DFBC (UNKNOWN_1DFBC) */
#define UC_UNKNOWN_1DFBD                         0x1DFBD   /* U+1DFBD (UNKNOWN_1DFBD) */
#define UC_UNKNOWN_1DFBE                         0x1DFBE   /* U+1DFBE (UNKNOWN_1DFBE) */
#define UC_UNKNOWN_1DFBF                         0x1DFBF   /* U+1DFBF (UNKNOWN_1DFBF) */
#define UC_UNKNOWN_1DFC0                         0x1DFC0   /* U+1DFC0 (UNKNOWN_1DFC0) */
#define UC_UNKNOWN_1DFC1                         0x1DFC1   /* U+1DFC1 (UNKNOWN_1DFC1) */
#define UC_UNKNOWN_1DFC2                         0x1DFC2   /* U+1DFC2 (UNKNOWN_1DFC2) */
#define UC_UNKNOWN_1DFC3                         0x1DFC3   /* U+1DFC3 (UNKNOWN_1DFC3) */
#define UC_UNKNOWN_1DFC4                         0x1DFC4   /* U+1DFC4 (UNKNOWN_1DFC4) */
#define UC_UNKNOWN_1DFC5                         0x1DFC5   /* U+1DFC5 (UNKNOWN_1DFC5) */
#define UC_UNKNOWN_1DFC6                         0x1DFC6   /* U+1DFC6 (UNKNOWN_1DFC6) */
#define UC_UNKNOWN_1DFC7                         0x1DFC7   /* U+1DFC7 (UNKNOWN_1DFC7) */
#define UC_UNKNOWN_1DFC8                         0x1DFC8   /* U+1DFC8 (UNKNOWN_1DFC8) */
#define UC_UNKNOWN_1DFC9                         0x1DFC9   /* U+1DFC9 (UNKNOWN_1DFC9) */
#define UC_UNKNOWN_1DFCA                         0x1DFCA   /* U+1DFCA (UNKNOWN_1DFCA) */
#define UC_UNKNOWN_1DFCB                         0x1DFCB   /* U+1DFCB (UNKNOWN_1DFCB) */
#define UC_UNKNOWN_1DFCC                         0x1DFCC   /* U+1DFCC (UNKNOWN_1DFCC) */
#define UC_UNKNOWN_1DFCD                         0x1DFCD   /* U+1DFCD (UNKNOWN_1DFCD) */
#define UC_UNKNOWN_1DFCE                         0x1DFCE   /* U+1DFCE (UNKNOWN_1DFCE) */
#define UC_UNKNOWN_1DFCF                         0x1DFCF   /* U+1DFCF (UNKNOWN_1DFCF) */
#define UC_UNKNOWN_1DFD0                         0x1DFD0   /* U+1DFD0 (UNKNOWN_1DFD0) */
#define UC_UNKNOWN_1DFD1                         0x1DFD1   /* U+1DFD1 (UNKNOWN_1DFD1) */
#define UC_UNKNOWN_1DFD2                         0x1DFD2   /* U+1DFD2 (UNKNOWN_1DFD2) */
#define UC_UNKNOWN_1DFD3                         0x1DFD3   /* U+1DFD3 (UNKNOWN_1DFD3) */
#define UC_UNKNOWN_1DFD4                         0x1DFD4   /* U+1DFD4 (UNKNOWN_1DFD4) */
#define UC_UNKNOWN_1DFD5                         0x1DFD5   /* U+1DFD5 (UNKNOWN_1DFD5) */
#define UC_UNKNOWN_1DFD6                         0x1DFD6   /* U+1DFD6 (UNKNOWN_1DFD6) */
#define UC_UNKNOWN_1DFD7                         0x1DFD7   /* U+1DFD7 (UNKNOWN_1DFD7) */
#define UC_UNKNOWN_1DFD8                         0x1DFD8   /* U+1DFD8 (UNKNOWN_1DFD8) */
#define UC_UNKNOWN_1DFD9                         0x1DFD9   /* U+1DFD9 (UNKNOWN_1DFD9) */
#define UC_UNKNOWN_1DFDA                         0x1DFDA   /* U+1DFDA (UNKNOWN_1DFDA) */
#define UC_UNKNOWN_1DFDB                         0x1DFDB   /* U+1DFDB (UNKNOWN_1DFDB) */
#define UC_UNKNOWN_1DFDC                         0x1DFDC   /* U+1DFDC (UNKNOWN_1DFDC) */
#define UC_UNKNOWN_1DFDD                         0x1DFDD   /* U+1DFDD (UNKNOWN_1DFDD) */
#define UC_UNKNOWN_1DFDE                         0x1DFDE   /* U+1DFDE (UNKNOWN_1DFDE) */
#define UC_UNKNOWN_1DFDF                         0x1DFDF   /* U+1DFDF (UNKNOWN_1DFDF) */
#define UC_UNKNOWN_1DFE0                         0x1DFE0   /* U+1DFE0 (UNKNOWN_1DFE0) */
#define UC_UNKNOWN_1DFE1                         0x1DFE1   /* U+1DFE1 (UNKNOWN_1DFE1) */
#define UC_UNKNOWN_1DFE2                         0x1DFE2   /* U+1DFE2 (UNKNOWN_1DFE2) */
#define UC_UNKNOWN_1DFE3                         0x1DFE3   /* U+1DFE3 (UNKNOWN_1DFE3) */
#define UC_UNKNOWN_1DFE4                         0x1DFE4   /* U+1DFE4 (UNKNOWN_1DFE4) */
#define UC_UNKNOWN_1DFE5                         0x1DFE5   /* U+1DFE5 (UNKNOWN_1DFE5) */
#define UC_UNKNOWN_1DFE6                         0x1DFE6   /* U+1DFE6 (UNKNOWN_1DFE6) */
#define UC_UNKNOWN_1DFE7                         0x1DFE7   /* U+1DFE7 (UNKNOWN_1DFE7) */
#define UC_UNKNOWN_1DFE8                         0x1DFE8   /* U+1DFE8 (UNKNOWN_1DFE8) */
#define UC_UNKNOWN_1DFE9                         0x1DFE9   /* U+1DFE9 (UNKNOWN_1DFE9) */
#define UC_UNKNOWN_1DFEA                         0x1DFEA   /* U+1DFEA (UNKNOWN_1DFEA) */
#define UC_UNKNOWN_1DFEB                         0x1DFEB   /* U+1DFEB (UNKNOWN_1DFEB) */
#define UC_UNKNOWN_1DFEC                         0x1DFEC   /* U+1DFEC (UNKNOWN_1DFEC) */
#define UC_UNKNOWN_1DFED                         0x1DFED   /* U+1DFED (UNKNOWN_1DFED) */
#define UC_UNKNOWN_1DFEE                         0x1DFEE   /* U+1DFEE (UNKNOWN_1DFEE) */
#define UC_UNKNOWN_1DFEF                         0x1DFEF   /* U+1DFEF (UNKNOWN_1DFEF) */
#define UC_UNKNOWN_1DFF0                         0x1DFF0   /* U+1DFF0 (UNKNOWN_1DFF0) */
#define UC_UNKNOWN_1DFF1                         0x1DFF1   /* U+1DFF1 (UNKNOWN_1DFF1) */
#define UC_UNKNOWN_1DFF2                         0x1DFF2   /* U+1DFF2 (UNKNOWN_1DFF2) */
#define UC_UNKNOWN_1DFF3                         0x1DFF3   /* U+1DFF3 (UNKNOWN_1DFF3) */
#define UC_UNKNOWN_1DFF4                         0x1DFF4   /* U+1DFF4 (UNKNOWN_1DFF4) */
#define UC_UNKNOWN_1DFF5                         0x1DFF5   /* U+1DFF5 (UNKNOWN_1DFF5) */
#define UC_UNKNOWN_1DFF6                         0x1DFF6   /* U+1DFF6 (UNKNOWN_1DFF6) */
#define UC_UNKNOWN_1DFF7                         0x1DFF7   /* U+1DFF7 (UNKNOWN_1DFF7) */
#define UC_UNKNOWN_1DFF8                         0x1DFF8   /* U+1DFF8 (UNKNOWN_1DFF8) */
#define UC_UNKNOWN_1DFF9                         0x1DFF9   /* U+1DFF9 (UNKNOWN_1DFF9) */
#define UC_UNKNOWN_1DFFA                         0x1DFFA   /* U+1DFFA (UNKNOWN_1DFFA) */
#define UC_UNKNOWN_1DFFB                         0x1DFFB   /* U+1DFFB (UNKNOWN_1DFFB) */
#define UC_UNKNOWN_1DFFC                         0x1DFFC   /* U+1DFFC (UNKNOWN_1DFFC) */
#define UC_UNKNOWN_1DFFD                         0x1DFFD   /* U+1DFFD (UNKNOWN_1DFFD) */
#define UC_UNKNOWN_1DFFE                         0x1DFFE   /* U+1DFFE (UNKNOWN_1DFFE) */
#define UC_UNKNOWN_1DFFF                         0x1DFFF   /* U+1DFFF (UNKNOWN_1DFFF) */
