/* Symbols and Pictographs Extended-A.h – Unicode constants for U+1FA70 … U+1FA7C
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_BALLET_SHOES                          0x1FA70 0  // 🩰
#define UC_ONE_PIECE_SWIMSUIT                    0x1FA71 0  // 🩱
#define UC_BRIEFS                                0x1FA72 0  // 🩲
#define UC_SHORTS                                0x1FA73 0  // 🩳
#define UC_THONG_SANDAL                          0x1FA74 0  // 🩴
#define UC_LIGHT_BLUE_HEART                      0x1FA75 0  // 🩵
#define UC_GREY_HEART                            0x1FA76 0  // 🩶
#define UC_PINK_HEART                            0x1FA77 0  // 🩷
#define UC_DROP_OF_BLOOD                         0x1FA78 0  // 🩸
#define UC_ADHESIVE_BANDAGE                      0x1FA79 0  // 🩹
#define UC_STETHOSCOPE                           0x1FA7A 0  // 🩺
#define UC_X_RAY                                 0x1FA7B 0  // 🩻
#define UC_CRUTCH                                0x1FA7C 0  // 🩼
