/* Kana Extended-B.h – Unicode constants for U+1AFF5 … U+1AFFB
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_KATAKANA_LETTER_MINNAN_TONE_7         0x1AFF5 0  // 𚿵
#define UC_KATAKANA_LETTER_MINNAN_TONE_8         0x1AFF6 0  // 𚿶
#define UC_KATAKANA_LETTER_MINNAN_NASALIZED_TONE_1 0x1AFF7 0  // 𚿷
#define UC_KATAKANA_LETTER_MINNAN_NASALIZED_TONE_2 0x1AFF8 0  // 𚿸
#define UC_KATAKANA_LETTER_MINNAN_NASALIZED_TONE_3 0x1AFF9 0  // 𚿹
#define UC_KATAKANA_LETTER_MINNAN_NASALIZED_TONE_4 0x1AFFA 0  // 𚿺
#define UC_KATAKANA_LETTER_MINNAN_NASALIZED_TONE_5 0x1AFFB 0  // 𚿻
