/* Tulu-Tigalari.h – Unicode constants for U+113C2 … U+113C2
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_TULU_TIGALARI_VOWEL_SIGN_EE           0x113C2 0  /* U+113C2 (TULU-TIGALARI VOWEL SIGN EE) */
