/* Symbols and Pictographs Extended-A.h – Unicode constants for U+1FADF … U+1FAE9
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_SPLATTER                              0x1FADF 0  /* U+1FADF (SPLATTER) */
#define UC_MELTING_FACE                          0x1FAE0 0  // 🫠
#define UC_SALUTING_FACE                         0x1FAE1 0  // 🫡
#define UC_FACE_WITH_OPEN_EYES_AND_HAND_OVER_MOUTH 0x1FAE2 0  // 🫢
#define UC_FACE_WITH_PEEKING_EYE                 0x1FAE3 0  // 🫣
#define UC_FACE_WITH_DIAGONAL_MOUTH              0x1FAE4 0  // 🫤
#define UC_DOTTED_LINE_FACE                      0x1FAE5 0  // 🫥
#define UC_BITING_LIP                            0x1FAE6 0  // 🫦
#define UC_BUBBLES                               0x1FAE7 0  // 🫧
#define UC_SHAKING_FACE                          0x1FAE8 0  // 🫨
#define UC_FACE_WITH_BAGS_UNDER_EYES             0x1FAE9 0  /* U+1FAE9 (FACE WITH BAGS UNDER EYES) */
