/* Supplementary Private Use Area-B.h – Unicode constants for U+100000 … U+10FFFD
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

