/* Kana Extended-B.h – Unicode constants for U+1AFF0 … U+1AFF3
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_KATAKANA_LETTER_MINNAN_TONE_2         0x1AFF0 0  // 𚿰
#define UC_KATAKANA_LETTER_MINNAN_TONE_3         0x1AFF1 0  // 𚿱
#define UC_KATAKANA_LETTER_MINNAN_TONE_4         0x1AFF2 0  // 𚿲
#define UC_KATAKANA_LETTER_MINNAN_TONE_5         0x1AFF3 0  // 𚿳
