/* Kana Extended-A.h – Unicode constants for U+1B100 … U+1B12F
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_HENTAIGANA_LETTER_RE_3                0x1B100   /* U+1B100 (HENTAIGANA LETTER RE-3) 𛄀 */
#define UC_HENTAIGANA_LETTER_RE_4                0x1B101   /* U+1B101 (HENTAIGANA LETTER RE-4) 𛄁 */
#define UC_HENTAIGANA_LETTER_RO_1                0x1B102   /* U+1B102 (HENTAIGANA LETTER RO-1) 𛄂 */
#define UC_HENTAIGANA_LETTER_RO_2                0x1B103   /* U+1B103 (HENTAIGANA LETTER RO-2) 𛄃 */
#define UC_HENTAIGANA_LETTER_RO_3                0x1B104   /* U+1B104 (HENTAIGANA LETTER RO-3) 𛄄 */
#define UC_HENTAIGANA_LETTER_RO_4                0x1B105   /* U+1B105 (HENTAIGANA LETTER RO-4) 𛄅 */
#define UC_HENTAIGANA_LETTER_RO_5                0x1B106   /* U+1B106 (HENTAIGANA LETTER RO-5) 𛄆 */
#define UC_HENTAIGANA_LETTER_RO_6                0x1B107   /* U+1B107 (HENTAIGANA LETTER RO-6) 𛄇 */
#define UC_HENTAIGANA_LETTER_WA_1                0x1B108   /* U+1B108 (HENTAIGANA LETTER WA-1) 𛄈 */
#define UC_HENTAIGANA_LETTER_WA_2                0x1B109   /* U+1B109 (HENTAIGANA LETTER WA-2) 𛄉 */
#define UC_HENTAIGANA_LETTER_WA_3                0x1B10A   /* U+1B10A (HENTAIGANA LETTER WA-3) 𛄊 */
#define UC_HENTAIGANA_LETTER_WA_4                0x1B10B   /* U+1B10B (HENTAIGANA LETTER WA-4) 𛄋 */
#define UC_HENTAIGANA_LETTER_WA_5                0x1B10C   /* U+1B10C (HENTAIGANA LETTER WA-5) 𛄌 */
#define UC_HENTAIGANA_LETTER_WI_1                0x1B10D   /* U+1B10D (HENTAIGANA LETTER WI-1) 𛄍 */
#define UC_HENTAIGANA_LETTER_WI_2                0x1B10E   /* U+1B10E (HENTAIGANA LETTER WI-2) 𛄎 */
#define UC_HENTAIGANA_LETTER_WI_3                0x1B10F   /* U+1B10F (HENTAIGANA LETTER WI-3) 𛄏 */
#define UC_HENTAIGANA_LETTER_WI_4                0x1B110   /* U+1B110 (HENTAIGANA LETTER WI-4) 𛄐 */
#define UC_HENTAIGANA_LETTER_WI_5                0x1B111   /* U+1B111 (HENTAIGANA LETTER WI-5) 𛄑 */
#define UC_HENTAIGANA_LETTER_WE_1                0x1B112   /* U+1B112 (HENTAIGANA LETTER WE-1) 𛄒 */
#define UC_HENTAIGANA_LETTER_WE_2                0x1B113   /* U+1B113 (HENTAIGANA LETTER WE-2) 𛄓 */
#define UC_HENTAIGANA_LETTER_WE_3                0x1B114   /* U+1B114 (HENTAIGANA LETTER WE-3) 𛄔 */
#define UC_HENTAIGANA_LETTER_WE_4                0x1B115   /* U+1B115 (HENTAIGANA LETTER WE-4) 𛄕 */
#define UC_HENTAIGANA_LETTER_WO_1                0x1B116   /* U+1B116 (HENTAIGANA LETTER WO-1) 𛄖 */
#define UC_HENTAIGANA_LETTER_WO_2                0x1B117   /* U+1B117 (HENTAIGANA LETTER WO-2) 𛄗 */
#define UC_HENTAIGANA_LETTER_WO_3                0x1B118   /* U+1B118 (HENTAIGANA LETTER WO-3) 𛄘 */
#define UC_HENTAIGANA_LETTER_WO_4                0x1B119   /* U+1B119 (HENTAIGANA LETTER WO-4) 𛄙 */
#define UC_HENTAIGANA_LETTER_WO_5                0x1B11A   /* U+1B11A (HENTAIGANA LETTER WO-5) 𛄚 */
#define UC_HENTAIGANA_LETTER_WO_6                0x1B11B   /* U+1B11B (HENTAIGANA LETTER WO-6) 𛄛 */
#define UC_HENTAIGANA_LETTER_WO_7                0x1B11C   /* U+1B11C (HENTAIGANA LETTER WO-7) 𛄜 */
#define UC_HENTAIGANA_LETTER_N_MU_MO_1           0x1B11D   /* U+1B11D (HENTAIGANA LETTER N-MU-MO-1) 𛄝 */
#define UC_HENTAIGANA_LETTER_N_MU_MO_2           0x1B11E   /* U+1B11E (HENTAIGANA LETTER N-MU-MO-2) 𛄞 */
#define UC_HIRAGANA_LETTER_ARCHAIC_WU            0x1B11F   /* U+1B11F (HIRAGANA LETTER ARCHAIC WU) 𛄟 */
#define UC_KATAKANA_LETTER_ARCHAIC_YI            0x1B120   /* U+1B120 (KATAKANA LETTER ARCHAIC YI) 𛄠 */
#define UC_KATAKANA_LETTER_ARCHAIC_YE            0x1B121   /* U+1B121 (KATAKANA LETTER ARCHAIC YE) 𛄡 */
#define UC_KATAKANA_LETTER_ARCHAIC_WU            0x1B122   /* U+1B122 (KATAKANA LETTER ARCHAIC WU) 𛄢 */
#define UC_UNKNOWN_1B123                         0x1B123   /* U+1B123 (UNKNOWN_1B123) */
#define UC_UNKNOWN_1B124                         0x1B124   /* U+1B124 (UNKNOWN_1B124) */
#define UC_UNKNOWN_1B125                         0x1B125   /* U+1B125 (UNKNOWN_1B125) */
#define UC_UNKNOWN_1B126                         0x1B126   /* U+1B126 (UNKNOWN_1B126) */
#define UC_UNKNOWN_1B127                         0x1B127   /* U+1B127 (UNKNOWN_1B127) */
#define UC_UNKNOWN_1B128                         0x1B128   /* U+1B128 (UNKNOWN_1B128) */
#define UC_UNKNOWN_1B129                         0x1B129   /* U+1B129 (UNKNOWN_1B129) */
#define UC_UNKNOWN_1B12A                         0x1B12A   /* U+1B12A (UNKNOWN_1B12A) */
#define UC_UNKNOWN_1B12B                         0x1B12B   /* U+1B12B (UNKNOWN_1B12B) */
#define UC_UNKNOWN_1B12C                         0x1B12C   /* U+1B12C (UNKNOWN_1B12C) */
#define UC_UNKNOWN_1B12D                         0x1B12D   /* U+1B12D (UNKNOWN_1B12D) */
#define UC_UNKNOWN_1B12E                         0x1B12E   /* U+1B12E (UNKNOWN_1B12E) */
#define UC_UNKNOWN_1B12F                         0x1B12F   /* U+1B12F (UNKNOWN_1B12F) */
