/* brahmi.h – Unicode constants for U+1107F … U+1107F
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_BRAHMI_NUMBER_JOINER                  0x1107F 0  // 𑁿
