/* Cham.h – Unicode constants for U+AA00 … U+AA5F
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_CHAM_LETTER_A                         0xAA00   /* U+AA00 (CHAM LETTER A) ꨀ */
#define UC_CHAM_LETTER_I                         0xAA01   /* U+AA01 (CHAM LETTER I) ꨁ */
#define UC_CHAM_LETTER_U                         0xAA02   /* U+AA02 (CHAM LETTER U) ꨂ */
#define UC_CHAM_LETTER_E                         0xAA03   /* U+AA03 (CHAM LETTER E) ꨃ */
#define UC_CHAM_LETTER_AI                        0xAA04   /* U+AA04 (CHAM LETTER AI) ꨄ */
#define UC_CHAM_LETTER_O                         0xAA05   /* U+AA05 (CHAM LETTER O) ꨅ */
#define UC_CHAM_LETTER_KA                        0xAA06   /* U+AA06 (CHAM LETTER KA) ꨆ */
#define UC_CHAM_LETTER_KHA                       0xAA07   /* U+AA07 (CHAM LETTER KHA) ꨇ */
#define UC_CHAM_LETTER_GA                        0xAA08   /* U+AA08 (CHAM LETTER GA) ꨈ */
#define UC_CHAM_LETTER_GHA                       0xAA09   /* U+AA09 (CHAM LETTER GHA) ꨉ */
#define UC_CHAM_LETTER_NGUE                      0xAA0A   /* U+AA0A (CHAM LETTER NGUE) ꨊ */
#define UC_CHAM_LETTER_NGA                       0xAA0B   /* U+AA0B (CHAM LETTER NGA) ꨋ */
#define UC_CHAM_LETTER_CHA                       0xAA0C   /* U+AA0C (CHAM LETTER CHA) ꨌ */
#define UC_CHAM_LETTER_CHHA                      0xAA0D   /* U+AA0D (CHAM LETTER CHHA) ꨍ */
#define UC_CHAM_LETTER_JA                        0xAA0E   /* U+AA0E (CHAM LETTER JA) ꨎ */
#define UC_CHAM_LETTER_JHA                       0xAA0F   /* U+AA0F (CHAM LETTER JHA) ꨏ */
#define UC_CHAM_LETTER_NHUE                      0xAA10   /* U+AA10 (CHAM LETTER NHUE) ꨐ */
#define UC_CHAM_LETTER_NHA                       0xAA11   /* U+AA11 (CHAM LETTER NHA) ꨑ */
#define UC_CHAM_LETTER_NHJA                      0xAA12   /* U+AA12 (CHAM LETTER NHJA) ꨒ */
#define UC_CHAM_LETTER_TA                        0xAA13   /* U+AA13 (CHAM LETTER TA) ꨓ */
#define UC_CHAM_LETTER_THA                       0xAA14   /* U+AA14 (CHAM LETTER THA) ꨔ */
#define UC_CHAM_LETTER_DA                        0xAA15   /* U+AA15 (CHAM LETTER DA) ꨕ */
#define UC_CHAM_LETTER_DHA                       0xAA16   /* U+AA16 (CHAM LETTER DHA) ꨖ */
#define UC_CHAM_LETTER_NUE                       0xAA17   /* U+AA17 (CHAM LETTER NUE) ꨗ */
#define UC_CHAM_LETTER_NA                        0xAA18   /* U+AA18 (CHAM LETTER NA) ꨘ */
#define UC_CHAM_LETTER_DDA                       0xAA19   /* U+AA19 (CHAM LETTER DDA) ꨙ */
#define UC_CHAM_LETTER_PA                        0xAA1A   /* U+AA1A (CHAM LETTER PA) ꨚ */
#define UC_CHAM_LETTER_PPA                       0xAA1B   /* U+AA1B (CHAM LETTER PPA) ꨛ */
#define UC_CHAM_LETTER_PHA                       0xAA1C   /* U+AA1C (CHAM LETTER PHA) ꨜ */
#define UC_CHAM_LETTER_BA                        0xAA1D   /* U+AA1D (CHAM LETTER BA) ꨝ */
#define UC_CHAM_LETTER_BHA                       0xAA1E   /* U+AA1E (CHAM LETTER BHA) ꨞ */
#define UC_CHAM_LETTER_MUE                       0xAA1F   /* U+AA1F (CHAM LETTER MUE) ꨟ */
#define UC_CHAM_LETTER_MA                        0xAA20   /* U+AA20 (CHAM LETTER MA) ꨠ */
#define UC_CHAM_LETTER_BBA                       0xAA21   /* U+AA21 (CHAM LETTER BBA) ꨡ */
#define UC_CHAM_LETTER_YA                        0xAA22   /* U+AA22 (CHAM LETTER YA) ꨢ */
#define UC_CHAM_LETTER_RA                        0xAA23   /* U+AA23 (CHAM LETTER RA) ꨣ */
#define UC_CHAM_LETTER_LA                        0xAA24   /* U+AA24 (CHAM LETTER LA) ꨤ */
#define UC_CHAM_LETTER_VA                        0xAA25   /* U+AA25 (CHAM LETTER VA) ꨥ */
#define UC_CHAM_LETTER_SSA                       0xAA26   /* U+AA26 (CHAM LETTER SSA) ꨦ */
#define UC_CHAM_LETTER_SA                        0xAA27   /* U+AA27 (CHAM LETTER SA) ꨧ */
#define UC_CHAM_LETTER_HA                        0xAA28   /* U+AA28 (CHAM LETTER HA) ꨨ */
#define UC_CHAM_VOWEL_SIGN_AA                    0xAA29   /* U+AA29 (CHAM VOWEL SIGN AA) ꨩ */
#define UC_CHAM_VOWEL_SIGN_I                     0xAA2A   /* U+AA2A (CHAM VOWEL SIGN I) ꨪ */
#define UC_CHAM_VOWEL_SIGN_II                    0xAA2B   /* U+AA2B (CHAM VOWEL SIGN II) ꨫ */
#define UC_CHAM_VOWEL_SIGN_EI                    0xAA2C   /* U+AA2C (CHAM VOWEL SIGN EI) ꨬ */
#define UC_CHAM_VOWEL_SIGN_U                     0xAA2D   /* U+AA2D (CHAM VOWEL SIGN U) ꨭ */
#define UC_CHAM_VOWEL_SIGN_OE                    0xAA2E   /* U+AA2E (CHAM VOWEL SIGN OE) ꨮ */
#define UC_CHAM_VOWEL_SIGN_O                     0xAA2F   /* U+AA2F (CHAM VOWEL SIGN O) ꨯ */
#define UC_CHAM_VOWEL_SIGN_AI                    0xAA30   /* U+AA30 (CHAM VOWEL SIGN AI) ꨰ */
#define UC_CHAM_VOWEL_SIGN_AU                    0xAA31   /* U+AA31 (CHAM VOWEL SIGN AU) ꨱ */
#define UC_CHAM_VOWEL_SIGN_UE                    0xAA32   /* U+AA32 (CHAM VOWEL SIGN UE) ꨲ */
#define UC_CHAM_CONSONANT_SIGN_YA                0xAA33   /* U+AA33 (CHAM CONSONANT SIGN YA) ꨳ */
#define UC_CHAM_CONSONANT_SIGN_RA                0xAA34   /* U+AA34 (CHAM CONSONANT SIGN RA) ꨴ */
#define UC_CHAM_CONSONANT_SIGN_LA                0xAA35   /* U+AA35 (CHAM CONSONANT SIGN LA) ꨵ */
#define UC_CHAM_CONSONANT_SIGN_WA                0xAA36   /* U+AA36 (CHAM CONSONANT SIGN WA) ꨶ */
#define UC_UNKNOWN_AA37                          0xAA37   /* U+AA37 (UNKNOWN_AA37) */
#define UC_UNKNOWN_AA38                          0xAA38   /* U+AA38 (UNKNOWN_AA38) */
#define UC_UNKNOWN_AA39                          0xAA39   /* U+AA39 (UNKNOWN_AA39) */
#define UC_UNKNOWN_AA3A                          0xAA3A   /* U+AA3A (UNKNOWN_AA3A) */
#define UC_UNKNOWN_AA3B                          0xAA3B   /* U+AA3B (UNKNOWN_AA3B) */
#define UC_UNKNOWN_AA3C                          0xAA3C   /* U+AA3C (UNKNOWN_AA3C) */
#define UC_UNKNOWN_AA3D                          0xAA3D   /* U+AA3D (UNKNOWN_AA3D) */
#define UC_UNKNOWN_AA3E                          0xAA3E   /* U+AA3E (UNKNOWN_AA3E) */
#define UC_UNKNOWN_AA3F                          0xAA3F   /* U+AA3F (UNKNOWN_AA3F) */
#define UC_CHAM_LETTER_FINAL_K                   0xAA40   /* U+AA40 (CHAM LETTER FINAL K) ꩀ */
#define UC_CHAM_LETTER_FINAL_G                   0xAA41   /* U+AA41 (CHAM LETTER FINAL G) ꩁ */
#define UC_CHAM_LETTER_FINAL_NG                  0xAA42   /* U+AA42 (CHAM LETTER FINAL NG) ꩂ */
#define UC_CHAM_CONSONANT_SIGN_FINAL_NG          0xAA43   /* U+AA43 (CHAM CONSONANT SIGN FINAL NG) ꩃ */
#define UC_CHAM_LETTER_FINAL_CH                  0xAA44   /* U+AA44 (CHAM LETTER FINAL CH) ꩄ */
#define UC_CHAM_LETTER_FINAL_T                   0xAA45   /* U+AA45 (CHAM LETTER FINAL T) ꩅ */
#define UC_CHAM_LETTER_FINAL_N                   0xAA46   /* U+AA46 (CHAM LETTER FINAL N) ꩆ */
#define UC_CHAM_LETTER_FINAL_P                   0xAA47   /* U+AA47 (CHAM LETTER FINAL P) ꩇ */
#define UC_CHAM_LETTER_FINAL_Y                   0xAA48   /* U+AA48 (CHAM LETTER FINAL Y) ꩈ */
#define UC_CHAM_LETTER_FINAL_R                   0xAA49   /* U+AA49 (CHAM LETTER FINAL R) ꩉ */
#define UC_CHAM_LETTER_FINAL_L                   0xAA4A   /* U+AA4A (CHAM LETTER FINAL L) ꩊ */
#define UC_CHAM_LETTER_FINAL_SS                  0xAA4B   /* U+AA4B (CHAM LETTER FINAL SS) ꩋ */
#define UC_CHAM_CONSONANT_SIGN_FINAL_M           0xAA4C   /* U+AA4C (CHAM CONSONANT SIGN FINAL M) ꩌ */
#define UC_CHAM_CONSONANT_SIGN_FINAL_H           0xAA4D   /* U+AA4D (CHAM CONSONANT SIGN FINAL H) ꩍ */
#define UC_UNKNOWN_AA4E                          0xAA4E   /* U+AA4E (UNKNOWN_AA4E) */
#define UC_UNKNOWN_AA4F                          0xAA4F   /* U+AA4F (UNKNOWN_AA4F) */
#define UC_CHAM_DIGIT_ZERO                       0xAA50   /* U+AA50 (CHAM DIGIT ZERO) ꩐ */
#define UC_CHAM_DIGIT_ONE                        0xAA51   /* U+AA51 (CHAM DIGIT ONE) ꩑ */
#define UC_CHAM_DIGIT_TWO                        0xAA52   /* U+AA52 (CHAM DIGIT TWO) ꩒ */
#define UC_CHAM_DIGIT_THREE                      0xAA53   /* U+AA53 (CHAM DIGIT THREE) ꩓ */
#define UC_CHAM_DIGIT_FOUR                       0xAA54   /* U+AA54 (CHAM DIGIT FOUR) ꩔ */
#define UC_CHAM_DIGIT_FIVE                       0xAA55   /* U+AA55 (CHAM DIGIT FIVE) ꩕ */
#define UC_CHAM_DIGIT_SIX                        0xAA56   /* U+AA56 (CHAM DIGIT SIX) ꩖ */
#define UC_CHAM_DIGIT_SEVEN                      0xAA57   /* U+AA57 (CHAM DIGIT SEVEN) ꩗ */
#define UC_CHAM_DIGIT_EIGHT                      0xAA58   /* U+AA58 (CHAM DIGIT EIGHT) ꩘ */
#define UC_CHAM_DIGIT_NINE                       0xAA59   /* U+AA59 (CHAM DIGIT NINE) ꩙ */
#define UC_UNKNOWN_AA5A                          0xAA5A   /* U+AA5A (UNKNOWN_AA5A) */
#define UC_UNKNOWN_AA5B                          0xAA5B   /* U+AA5B (UNKNOWN_AA5B) */
#define UC_CHAM_PUNCTUATION_SPIRAL               0xAA5C   /* U+AA5C (CHAM PUNCTUATION SPIRAL) ꩜ */
#define UC_CHAM_PUNCTUATION_DANDA                0xAA5D   /* U+AA5D (CHAM PUNCTUATION DANDA) ꩝ */
#define UC_CHAM_PUNCTUATION_DOUBLE_DANDA         0xAA5E   /* U+AA5E (CHAM PUNCTUATION DOUBLE DANDA) ꩞ */
#define UC_CHAM_PUNCTUATION_TRIPLE_DANDA         0xAA5F   /* U+AA5F (CHAM PUNCTUATION TRIPLE DANDA) ꩟ */
