/* cham.h – Unicode constants for U+AA5C … U+AA5F
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_CHAM_PUNCTUATION_SPIRAL               0xAA5C 0  // ꩜
#define UC_CHAM_PUNCTUATION_DANDA                0xAA5D 0  // ꩝
#define UC_CHAM_PUNCTUATION_DOUBLE_DANDA         0xAA5E 0  // ꩞
#define UC_CHAM_PUNCTUATION_TRIPLE_DANDA         0xAA5F 0  // ꩟
