/* cherokee.h – Unicode constants for U+13A0 … U+13FF
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
*
* See https://www.unicode.org/versions/latest/ for source data.

 * The Cherokee ( / ˈ tʃ ɛr ə k iː / CHEH -rə-kee , / ˌ tʃ ɛr ə ˈ k iː / ⓘ
 * CHEH -rə- KEE ; Cherokee : ᎠᏂᏴᏫᏯᎢ , romanized: Aniyvwiyaʔi / Anigiduwagi ,
 * or ᏣᎳᎩ , Tsalagi ) people are one of the Indigenous peoples of the
 * Southeastern Woodlands of the United States . Prior to the 18th century,
 * they were concentrated in their homelands, in towns along river valleys of
 * what is now southwestern North Carolina , southeastern Tennessee ,
 * southwestern Virginia , edges of western South Carolina , northern Georgia
 * and northeastern Alabama with hunting grounds in Kentucky , together
 * consisting of around 40,000 square miles.
 * The Cherokee language is part of the Iroquoian language group. In the 19th
 * century, James Mooney , an early American ethnographer , recorded one oral
 * tradition that told of the tribe having migrated south in ancient times
 * from the Great Lakes region, where other Iroquoian peoples have been based.
 * However, anthropologist Thomas R. Whyte, writing in 2007, dated the split
 * among the peoples as occurring earlier. He believes that the origin of the
 * proto-Iroquoian language was likely the Appalachian region , and the split
 * between Northern and Southern Iroquoian languages began 4,000 years ago.
 *

* Consistency Check:
* Total Defined Code Points: 12
* Total Significant Hex Values: 12
* Status: OK (Counts Match)

*/

#ifndef CHEROKEE_H
#define CHEROKEE_H

#define UC_CHEROKEE_YE                           0x13F8 0x13F0  // ᏸ/Ᏸ
#define UC_CHEROKEE_YI                           0x13F9 0x13F1  // ᏹ/Ᏹ
#define UC_CHEROKEE_YO                           0x13FA 0x13F2  // ᏺ/Ᏺ
#define UC_CHEROKEE_YU                           0x13FB 0x13F3  // ᏻ/Ᏻ
#define UC_CHEROKEE_YV                           0x13FC 0x13F4  // ᏼ/Ᏼ
#define UC_CHEROKEE_MV                           0x13FD 0x13F5  // ᏽ/Ᏽ

#endif // CHEROKEE_H
