/* chorasmian.h – Unicode constants for U+10FB0 … U+10FDF
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_CHORASMIAN_ALEPH                      0x10FB0 0  // 𐾰
#define UC_CHORASMIAN_SMALL_ALEPH                0x10FB1 0  // 𐾱
#define UC_CHORASMIAN_BETH                       0x10FB2 0  // 𐾲
#define UC_CHORASMIAN_GIMEL                      0x10FB3 0  // 𐾳
#define UC_CHORASMIAN_DALETH                     0x10FB4 0  // 𐾴
#define UC_CHORASMIAN_HE                         0x10FB5 0  // 𐾵
#define UC_CHORASMIAN_WAW                        0x10FB6 0  // 𐾶
#define UC_CHORASMIAN_CURLED_WAW                 0x10FB7 0  // 𐾷
#define UC_CHORASMIAN_ZAYIN                      0x10FB8 0  // 𐾸
#define UC_CHORASMIAN_HETH                       0x10FB9 0  // 𐾹
#define UC_CHORASMIAN_YODH                       0x10FBA 0  // 𐾺
#define UC_CHORASMIAN_KAPH                       0x10FBB 0  // 𐾻
#define UC_CHORASMIAN_LAMEDH                     0x10FBC 0  // 𐾼
#define UC_CHORASMIAN_MEM                        0x10FBD 0  // 𐾽
#define UC_CHORASMIAN_NUN                        0x10FBE 0  // 𐾾
#define UC_CHORASMIAN_SAMEKH                     0x10FBF 0  // 𐾿
#define UC_CHORASMIAN_AYIN                       0x10FC0 0  // 𐿀
#define UC_CHORASMIAN_PE                         0x10FC1 0  // 𐿁
#define UC_CHORASMIAN_RESH                       0x10FC2 0  // 𐿂
#define UC_CHORASMIAN_SHIN                       0x10FC3 0  // 𐿃
#define UC_CHORASMIAN_TAW                        0x10FC4 0  // 𐿄
#define UC_CHORASMIAN_ONE                        0x10FC5 0  // 𐿅
#define UC_CHORASMIAN_TWO                        0x10FC6 0  // 𐿆
#define UC_CHORASMIAN_THREE                      0x10FC7 0  // 𐿇
#define UC_CHORASMIAN_FOUR                       0x10FC8 0  // 𐿈
#define UC_CHORASMIAN_TEN                        0x10FC9 0  // 𐿉
#define UC_CHORASMIAN_TWENTY                     0x10FCA 0  // 𐿊
#define UC_CHORASMIAN_ONE_HUNDRED                0x10FCB 0  // 𐿋
