/* cjk_strokes.h – Unicode constants for U+31C0 … U+31EF
*
* Generated by generate_unicode_headers.py
* Defined Code Points: 39
* Total Hex Codes: 39
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_CJS_CJK_STROKE_T                      0x31C0 0  // ㇀
#define UC_CJS_CJK_STROKE_WG                     0x31C1 0  // ㇁
#define UC_CJS_CJK_STROKE_XG                     0x31C2 0  // ㇂
#define UC_CJS_CJK_STROKE_BXG                    0x31C3 0  // ㇃
#define UC_CJS_CJK_STROKE_SW                     0x31C4 0  // ㇄
#define UC_CJS_CJK_STROKE_HZZ                    0x31C5 0  // ㇅
#define UC_CJS_CJK_STROKE_HZG                    0x31C6 0  // ㇆
#define UC_CJS_CJK_STROKE_HP                     0x31C7 0  // ㇇
#define UC_CJS_CJK_STROKE_HZWG                   0x31C8 0  // ㇈
#define UC_CJS_CJK_STROKE_SZWG                   0x31C9 0  // ㇉
#define UC_CJS_CJK_STROKE_HZT                    0x31CA 0  // ㇊
#define UC_CJS_CJK_STROKE_HZZP                   0x31CB 0  // ㇋
#define UC_CJS_CJK_STROKE_HPWG                   0x31CC 0  // ㇌
#define UC_CJS_CJK_STROKE_HZW                    0x31CD 0  // ㇍
#define UC_CJS_CJK_STROKE_HZZZ                   0x31CE 0  // ㇎
#define UC_CJS_CJK_STROKE_N                      0x31CF 0  // ㇏
#define UC_CJS_CJK_STROKE_H                      0x31D0 0  // ㇐
#define UC_CJS_CJK_STROKE_S                      0x31D1 0  // ㇑
#define UC_CJS_CJK_STROKE_P                      0x31D2 0  // ㇒
#define UC_CJS_CJK_STROKE_SP                     0x31D3 0  // ㇓
#define UC_CJS_CJK_STROKE_D                      0x31D4 0  // ㇔
#define UC_CJS_CJK_STROKE_HZ                     0x31D5 0  // ㇕
#define UC_CJS_CJK_STROKE_HG                     0x31D6 0  // ㇖
#define UC_CJS_CJK_STROKE_SZ                     0x31D7 0  // ㇗
#define UC_CJS_CJK_STROKE_SWZ                    0x31D8 0  // ㇘
#define UC_CJS_CJK_STROKE_ST                     0x31D9 0  // ㇙
#define UC_CJS_CJK_STROKE_SG                     0x31DA 0  // ㇚
#define UC_CJS_CJK_STROKE_PD                     0x31DB 0  // ㇛
#define UC_CJS_CJK_STROKE_PZ                     0x31DC 0  // ㇜
#define UC_CJS_CJK_STROKE_TN                     0x31DD 0  // ㇝
#define UC_CJS_CJK_STROKE_SZZ                    0x31DE 0  // ㇞
#define UC_CJS_CJK_STROKE_SWG                    0x31DF 0  // ㇟
#define UC_CJS_CJK_STROKE_HXWG                   0x31E0 0  // ㇠
#define UC_CJS_CJK_STROKE_HZZZG                  0x31E1 0  // ㇡
#define UC_CJS_CJK_STROKE_PG                     0x31E2 0  // ㇢
#define UC_CJS_CJK_STROKE_Q                      0x31E3 0  // ㇣
#define UC_CJS_CJK_STROKE_HXG                    0x31E4 0  /* U+31E4 (CJK STROKE HXG) */
#define UC_CJS_CJK_STROKE_SZP                    0x31E5 0  /* U+31E5 (CJK STROKE SZP) */
#define UC_CJS_IDEOGRAPHIC_DESCION_SUBTRACTION   0x31EF 0  // ㇯
