/* Combining Diacritical Marks for Symbols.h – Unicode constants for U+20D0 … U+20F0
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_CM_LEFT_HARPOON_ABOVE                 0x20D0 0  // ⃐
#define UC_CM_RIGHT_HARPOON_ABOVE                0x20D1 0  // ⃑
#define UC_CM_LONG_VERTICAL_LINE_OVERLAY         0x20D2 0  // ⃒
#define UC_CM_SHORT_VERTICAL_LINE_OVERLAY        0x20D3 0  // ⃓
#define UC_CM_ANTICLOCKWISE_ARROW_ABOVE          0x20D4 0  // ⃔
#define UC_CM_CLOCKWISE_ARROW_ABOVE              0x20D5 0  // ⃕
#define UC_CM_LEFT_ARROW_ABOVE                   0x20D6 0  // ⃖
#define UC_CM_RIGHT_ARROW_ABOVE                  0x20D7 0  // ⃗
#define UC_CM_RING_OVERLAY                       0x20D8 0  // ⃘
#define UC_CM_CLOCKWISE_RING_OVERLAY             0x20D9 0  // ⃙
#define UC_CM_ANTICLOCKWISE_RING_OVERLAY         0x20DA 0  // ⃚
#define UC_CM_THREE_DOTS_ABOVE                   0x20DB 0  // ⃛
#define UC_CM_FOUR_DOTS_ABOVE                    0x20DC 0  // ⃜
#define UC_CM_ENCLOSING_CIRCLE                   0x20DD 0  // ⃝
#define UC_CM_ENCLOSING_SQUARE                   0x20DE 0  // ⃞
#define UC_CM_ENCLOSING_DIAMOND                  0x20DF 0  // ⃟
#define UC_CM_ENCLOSING_CIRCLE_BACKSLASH         0x20E0 0  // ⃠
#define UC_CM_LEFT_RIGHT_ARROW_ABOVE             0x20E1 0  // ⃡
#define UC_CM_ENCLOSING_SCREEN                   0x20E2 0  // ⃢
#define UC_CM_ENCLOSING_KEYCAP                   0x20E3 0  // ⃣
#define UC_CM_ENCLOSING_UPWARD_POINTING_TRIANGLE 0x20E4 0  // ⃤
#define UC_CM_REVERSE_SOLIDUS_OVERLAY            0x20E5 0  // ⃥
#define UC_CM_DOUBLE_VERTICAL_STROKE_OVERLAY     0x20E6 0  // ⃦
#define UC_CM_ANNUITY_SYMBOL                     0x20E7 0  // ⃧
#define UC_CM_TRIPLE_UNDERDOT                    0x20E8 0  // ⃨
#define UC_CM_WIDE_BRIDGE_ABOVE                  0x20E9 0  // ⃩
#define UC_CM_LEFTWARDS_ARROW_OVERLAY            0x20EA 0  // ⃪
#define UC_CM_LONG_DOUBLE_SOLIDUS_OVERLAY        0x20EB 0  // ⃫
#define UC_CM_RIGHTWARDS_HARPOON_WITH_BARB_DOWNWARDS 0x20EC 0  // ⃬
#define UC_CM_LEFTWARDS_HARPOON_WITH_BARB_DOWNWARDS 0x20ED 0  // ⃭
#define UC_CM_LEFT_ARROW_BELOW                   0x20EE 0  // ⃮
#define UC_CM_RIGHT_ARROW_BELOW                  0x20EF 0  // ⃯
#define UC_CM_ASTERISK_ABOVE                     0x20F0 0  // ⃰
