/* Combining Diacritical Marks Supplement.h – Unicode constants for U+1DC0 … U+1DFF
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_CM_DOTTED_GRAVE_ACCENT                0x1DC0 0  // ᷀
#define UC_CM_DOTTED_ACUTE_ACCENT                0x1DC1 0  // ᷁
#define UC_CM_SNAKE_BELOW                        0x1DC2 0  // ᷂
#define UC_CM_SUSPENSION_MARK                    0x1DC3 0  // ᷃
#define UC_CM_MACRON_ACUTE                       0x1DC4 0  // ᷄
#define UC_CM_GRAVE_MACRON                       0x1DC5 0  // ᷅
#define UC_CM_MACRON_GRAVE                       0x1DC6 0  // ᷆
#define UC_CM_ACUTE_MACRON                       0x1DC7 0  // ᷇
#define UC_CM_GRAVE_ACUTE_GRAVE                  0x1DC8 0  // ᷈
#define UC_CM_ACUTE_GRAVE_ACUTE                  0x1DC9 0  // ᷉
#define UC_CM_LATIN_SMALL_LETTER_R_BELOW         0x1DCA 0  // ᷊
#define UC_CM_BREVE_MACRON                       0x1DCB 0  // ᷋
#define UC_CM_MACRON_BREVE                       0x1DCC 0  // ᷌
#define UC_CM_DOUBLE_CIRCUMFLEX_ABOVE            0x1DCD 0  // ᷍
#define UC_CM_OGONEK_ABOVE                       0x1DCE 0  // ᷎
#define UC_CM_ZIGZAG_BELOW                       0x1DCF 0  // ᷏
#define UC_CM_IS_BELOW                           0x1DD0 0  // ᷐
#define UC_CM_UR_ABOVE                           0x1DD1 0  // ᷑
#define UC_CM_US_ABOVE                           0x1DD2 0  // ᷒
#define UC_CM_LATIN_SMALL_LETTER_FLATTENED_OPEN_A_ABOVE 0x1DD3 0  // ᷓ
#define UC_CM_LATIN_SMALL_LETTER_AE              0x1DD4 0  // ᷔ
#define UC_CM_LATIN_SMALL_LETTER_AO              0x1DD5 0  // ᷕ
#define UC_CM_LATIN_SMALL_LETTER_AV              0x1DD6 0  // ᷖ
#define UC_CM_LATIN_SMALL_LETTER_C_CEDILLA       0x1DD7 0  // ᷗ
#define UC_CM_LATIN_SMALL_LETTER_INSULAR_D       0x1DD8 0  // ᷘ
#define UC_CM_LATIN_SMALL_LETTER_ETH             0x1DD9 0  // ᷙ
#define UC_CM_LATIN_SMALL_LETTER_G               0x1DDA 0  // ᷚ
#define UC_CM_LATIN_LETTER_SMALL_CAPITAL_G       0x1DDB 0  // ᷛ
#define UC_CM_LATIN_SMALL_LETTER_K               0x1DDC 0  // ᷜ
#define UC_CM_LATIN_SMALL_LETTER_L               0x1DDD 0  // ᷝ
#define UC_CM_LATIN_LETTER_SMALL_CAPITAL_L       0x1DDE 0  // ᷞ
#define UC_CM_LATIN_LETTER_SMALL_CAPITAL_M       0x1DDF 0  // ᷟ
#define UC_CM_LATIN_SMALL_LETTER_N               0x1DE0 0  // ᷠ
#define UC_CM_LATIN_LETTER_SMALL_CAPITAL_N       0x1DE1 0  // ᷡ
#define UC_CM_LATIN_LETTER_SMALL_CAPITAL_R       0x1DE2 0  // ᷢ
#define UC_CM_LATIN_SMALL_LETTER_R_ROTUNDA       0x1DE3 0  // ᷣ
#define UC_CM_LATIN_SMALL_LETTER_S               0x1DE4 0  // ᷤ
#define UC_CM_LATIN_SMALL_LETTER_LONG_S          0x1DE5 0  // ᷥ
#define UC_CM_LATIN_SMALL_LETTER_Z               0x1DE6 0  // ᷦ
#define UC_CM_LATIN_SMALL_LETTER_ALPHA           0x1DE7 0  // ᷧ
#define UC_CM_LATIN_SMALL_LETTER_B               0x1DE8 0  // ᷨ
#define UC_CM_LATIN_SMALL_LETTER_BETA            0x1DE9 0  // ᷩ
#define UC_CM_LATIN_SMALL_LETTER_SCHWA           0x1DEA 0  // ᷪ
#define UC_CM_LATIN_SMALL_LETTER_F               0x1DEB 0  // ᷫ
#define UC_CM_LATIN_SMALL_LETTER_L_WITH_DOUBLE_MIDDLE_TILDE 0x1DEC 0  // ᷬ
#define UC_CM_LATIN_SMALL_LETTER_O_WITH_LIGHT_CENTRALIZATION_STROKE 0x1DED 0  // ᷭ
#define UC_CM_LATIN_SMALL_LETTER_P               0x1DEE 0  // ᷮ
#define UC_CM_LATIN_SMALL_LETTER_ESH             0x1DEF 0  // ᷯ
#define UC_CM_LATIN_SMALL_LETTER_U_WITH_LIGHT_CENTRALIZATION_STROKE 0x1DF0 0  // ᷰ
#define UC_CM_LATIN_SMALL_LETTER_W               0x1DF1 0  // ᷱ
#define UC_CM_LATIN_SMALL_LETTER_A_WITH_DIAERESIS 0x1DF2 0  // ᷲ
#define UC_CM_LATIN_SMALL_LETTER_O_WITH_DIAERESIS 0x1DF3 0  // ᷳ
#define UC_CM_LATIN_SMALL_LETTER_U_WITH_DIAERESIS 0x1DF4 0  // ᷴ
#define UC_CM_UP_TACK_ABOVE                      0x1DF5 0  // ᷵
#define UC_CM_KAVYKA_ABOVE_RIGHT                 0x1DF6 0  // ᷶
#define UC_CM_KAVYKA_ABOVE_LEFT                  0x1DF7 0  // ᷷
#define UC_CM_DOT_ABOVE_LEFT                     0x1DF8 0  // ᷸
#define UC_CM_WIDE_INVERTED_BRIDGE_BELOW         0x1DF9 0  // ᷹
#define UC_CM_DOT_BELOW_LEFT                     0x1DFA 0  // ᷺
#define UC_CM_DELETION_MARK                      0x1DFB 0  // ᷻
#define UC_CM_DOUBLE_INVERTED_BREVE_BELOW        0x1DFC 0  // ᷼
#define UC_CM_ALMOST_EQUAL_TO_BELOW              0x1DFD 0  // ᷽
#define UC_CM_LEFT_ARROWHEAD_ABOVE               0x1DFE 0  // ᷾
#define UC_CM_RIGHT_ARROWHEAD_AND_DOWN_ARROWHEAD_BELOW 0x1DFF 0  // ᷿
