/* Cypriot Syllabary.h – Unicode constants for U+10800 … U+1083F
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_CYPRIOT_SYLLABLE_A                    0x10800   /* U+10800 (CYPRIOT SYLLABLE A) 𐠀 */
#define UC_CYPRIOT_SYLLABLE_E                    0x10801   /* U+10801 (CYPRIOT SYLLABLE E) 𐠁 */
#define UC_CYPRIOT_SYLLABLE_I                    0x10802   /* U+10802 (CYPRIOT SYLLABLE I) 𐠂 */
#define UC_CYPRIOT_SYLLABLE_O                    0x10803   /* U+10803 (CYPRIOT SYLLABLE O) 𐠃 */
#define UC_CYPRIOT_SYLLABLE_U                    0x10804   /* U+10804 (CYPRIOT SYLLABLE U) 𐠄 */
#define UC_CYPRIOT_SYLLABLE_JA                   0x10805   /* U+10805 (CYPRIOT SYLLABLE JA) 𐠅 */
#define UC_UNKNOWN_10806                         0x10806   /* U+10806 (UNKNOWN_10806) */
#define UC_UNKNOWN_10807                         0x10807   /* U+10807 (UNKNOWN_10807) */
#define UC_CYPRIOT_SYLLABLE_JO                   0x10808   /* U+10808 (CYPRIOT SYLLABLE JO) 𐠈 */
#define UC_UNKNOWN_10809                         0x10809   /* U+10809 (UNKNOWN_10809) */
#define UC_CYPRIOT_SYLLABLE_KA                   0x1080A   /* U+1080A (CYPRIOT SYLLABLE KA) 𐠊 */
#define UC_CYPRIOT_SYLLABLE_KE                   0x1080B   /* U+1080B (CYPRIOT SYLLABLE KE) 𐠋 */
#define UC_CYPRIOT_SYLLABLE_KI                   0x1080C   /* U+1080C (CYPRIOT SYLLABLE KI) 𐠌 */
#define UC_CYPRIOT_SYLLABLE_KO                   0x1080D   /* U+1080D (CYPRIOT SYLLABLE KO) 𐠍 */
#define UC_CYPRIOT_SYLLABLE_KU                   0x1080E   /* U+1080E (CYPRIOT SYLLABLE KU) 𐠎 */
#define UC_CYPRIOT_SYLLABLE_LA                   0x1080F   /* U+1080F (CYPRIOT SYLLABLE LA) 𐠏 */
#define UC_CYPRIOT_SYLLABLE_LE                   0x10810   /* U+10810 (CYPRIOT SYLLABLE LE) 𐠐 */
#define UC_CYPRIOT_SYLLABLE_LI                   0x10811   /* U+10811 (CYPRIOT SYLLABLE LI) 𐠑 */
#define UC_CYPRIOT_SYLLABLE_LO                   0x10812   /* U+10812 (CYPRIOT SYLLABLE LO) 𐠒 */
#define UC_CYPRIOT_SYLLABLE_LU                   0x10813   /* U+10813 (CYPRIOT SYLLABLE LU) 𐠓 */
#define UC_CYPRIOT_SYLLABLE_MA                   0x10814   /* U+10814 (CYPRIOT SYLLABLE MA) 𐠔 */
#define UC_CYPRIOT_SYLLABLE_ME                   0x10815   /* U+10815 (CYPRIOT SYLLABLE ME) 𐠕 */
#define UC_CYPRIOT_SYLLABLE_MI                   0x10816   /* U+10816 (CYPRIOT SYLLABLE MI) 𐠖 */
#define UC_CYPRIOT_SYLLABLE_MO                   0x10817   /* U+10817 (CYPRIOT SYLLABLE MO) 𐠗 */
#define UC_CYPRIOT_SYLLABLE_MU                   0x10818   /* U+10818 (CYPRIOT SYLLABLE MU) 𐠘 */
#define UC_CYPRIOT_SYLLABLE_NA                   0x10819   /* U+10819 (CYPRIOT SYLLABLE NA) 𐠙 */
#define UC_CYPRIOT_SYLLABLE_NE                   0x1081A   /* U+1081A (CYPRIOT SYLLABLE NE) 𐠚 */
#define UC_CYPRIOT_SYLLABLE_NI                   0x1081B   /* U+1081B (CYPRIOT SYLLABLE NI) 𐠛 */
#define UC_CYPRIOT_SYLLABLE_NO                   0x1081C   /* U+1081C (CYPRIOT SYLLABLE NO) 𐠜 */
#define UC_CYPRIOT_SYLLABLE_NU                   0x1081D   /* U+1081D (CYPRIOT SYLLABLE NU) 𐠝 */
#define UC_CYPRIOT_SYLLABLE_PA                   0x1081E   /* U+1081E (CYPRIOT SYLLABLE PA) 𐠞 */
#define UC_CYPRIOT_SYLLABLE_PE                   0x1081F   /* U+1081F (CYPRIOT SYLLABLE PE) 𐠟 */
#define UC_CYPRIOT_SYLLABLE_PI                   0x10820   /* U+10820 (CYPRIOT SYLLABLE PI) 𐠠 */
#define UC_CYPRIOT_SYLLABLE_PO                   0x10821   /* U+10821 (CYPRIOT SYLLABLE PO) 𐠡 */
#define UC_CYPRIOT_SYLLABLE_PU                   0x10822   /* U+10822 (CYPRIOT SYLLABLE PU) 𐠢 */
#define UC_CYPRIOT_SYLLABLE_RA                   0x10823   /* U+10823 (CYPRIOT SYLLABLE RA) 𐠣 */
#define UC_CYPRIOT_SYLLABLE_RE                   0x10824   /* U+10824 (CYPRIOT SYLLABLE RE) 𐠤 */
#define UC_CYPRIOT_SYLLABLE_RI                   0x10825   /* U+10825 (CYPRIOT SYLLABLE RI) 𐠥 */
#define UC_CYPRIOT_SYLLABLE_RO                   0x10826   /* U+10826 (CYPRIOT SYLLABLE RO) 𐠦 */
#define UC_CYPRIOT_SYLLABLE_RU                   0x10827   /* U+10827 (CYPRIOT SYLLABLE RU) 𐠧 */
#define UC_CYPRIOT_SYLLABLE_SA                   0x10828   /* U+10828 (CYPRIOT SYLLABLE SA) 𐠨 */
#define UC_CYPRIOT_SYLLABLE_SE                   0x10829   /* U+10829 (CYPRIOT SYLLABLE SE) 𐠩 */
#define UC_CYPRIOT_SYLLABLE_SI                   0x1082A   /* U+1082A (CYPRIOT SYLLABLE SI) 𐠪 */
#define UC_CYPRIOT_SYLLABLE_SO                   0x1082B   /* U+1082B (CYPRIOT SYLLABLE SO) 𐠫 */
#define UC_CYPRIOT_SYLLABLE_SU                   0x1082C   /* U+1082C (CYPRIOT SYLLABLE SU) 𐠬 */
#define UC_CYPRIOT_SYLLABLE_TA                   0x1082D   /* U+1082D (CYPRIOT SYLLABLE TA) 𐠭 */
#define UC_CYPRIOT_SYLLABLE_TE                   0x1082E   /* U+1082E (CYPRIOT SYLLABLE TE) 𐠮 */
#define UC_CYPRIOT_SYLLABLE_TI                   0x1082F   /* U+1082F (CYPRIOT SYLLABLE TI) 𐠯 */
#define UC_CYPRIOT_SYLLABLE_TO                   0x10830   /* U+10830 (CYPRIOT SYLLABLE TO) 𐠰 */
#define UC_CYPRIOT_SYLLABLE_TU                   0x10831   /* U+10831 (CYPRIOT SYLLABLE TU) 𐠱 */
#define UC_CYPRIOT_SYLLABLE_WA                   0x10832   /* U+10832 (CYPRIOT SYLLABLE WA) 𐠲 */
#define UC_CYPRIOT_SYLLABLE_WE                   0x10833   /* U+10833 (CYPRIOT SYLLABLE WE) 𐠳 */
#define UC_CYPRIOT_SYLLABLE_WI                   0x10834   /* U+10834 (CYPRIOT SYLLABLE WI) 𐠴 */
#define UC_CYPRIOT_SYLLABLE_WO                   0x10835   /* U+10835 (CYPRIOT SYLLABLE WO) 𐠵 */
#define UC_UNKNOWN_10836                         0x10836   /* U+10836 (UNKNOWN_10836) */
#define UC_CYPRIOT_SYLLABLE_XA                   0x10837   /* U+10837 (CYPRIOT SYLLABLE XA) 𐠷 */
#define UC_CYPRIOT_SYLLABLE_XE                   0x10838   /* U+10838 (CYPRIOT SYLLABLE XE) 𐠸 */
#define UC_UNKNOWN_10839                         0x10839   /* U+10839 (UNKNOWN_10839) */
#define UC_UNKNOWN_1083A                         0x1083A   /* U+1083A (UNKNOWN_1083A) */
#define UC_UNKNOWN_1083B                         0x1083B   /* U+1083B (UNKNOWN_1083B) */
#define UC_CYPRIOT_SYLLABLE_ZA                   0x1083C   /* U+1083C (CYPRIOT SYLLABLE ZA) 𐠼 */
#define UC_UNKNOWN_1083D                         0x1083D   /* U+1083D (UNKNOWN_1083D) */
#define UC_UNKNOWN_1083E                         0x1083E   /* U+1083E (UNKNOWN_1083E) */
#define UC_CYPRIOT_SYLLABLE_ZO                   0x1083F   /* U+1083F (CYPRIOT SYLLABLE ZO) 𐠿 */
