/* cyrillic_supplement.h – Unicode constants for U+0500 … U+052F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_CYS_KOMI_DE                           0x0500 0x0501  // Ԁ/ԁ
#define UC_CYS_KOMI_DJE                          0x0502 0x0503  // Ԃ/ԃ
#define UC_CYS_KOMI_ZJE                          0x0504 0x0505  // Ԅ/ԅ
#define UC_CYS_KOMI_DZJE                         0x0506 0x0507  // Ԇ/ԇ
#define UC_CYS_KOMI_LJE                          0x0508 0x0509  // Ԉ/ԉ
#define UC_CYS_KOMI_NJE                          0x050A 0x050B  // Ԋ/ԋ
#define UC_CYS_KOMI_SJE                          0x050C 0x050D  // Ԍ/ԍ
#define UC_CYS_KOMI_TJE                          0x050E 0x050F  // Ԏ/ԏ
#define UC_CYS_REVERSED_ZE                       0x0510 0x0511  // Ԑ/ԑ
#define UC_CYS_EL_HOOK                           0x0512 0x0513  // Ԓ/ԓ
#define UC_CYS_LHA                               0x0514 0x0515  // Ԕ/ԕ
#define UC_CYS_RHA                               0x0516 0x0517  // Ԗ/ԗ
#define UC_CYS_YAE                               0x0518 0x0519  // Ԙ/ԙ
#define UC_CYS_QA                                0x051A 0x051B  // Ԛ/ԛ
#define UC_CYS_WE                                0x051C 0x051D  // Ԝ/ԝ
#define UC_CYS_ALEUT_KA                          0x051E 0x051F  // Ԟ/ԟ
#define UC_CYS_EL_MIDDLE_HOOK                    0x0520 0x0521  // Ԡ/ԡ
#define UC_CYS_EN_MIDDLE_HOOK                    0x0522 0x0523  // Ԣ/ԣ
#define UC_CYS_PE_DESCENDER                      0x0524 0x0525  // Ԥ/ԥ
#define UC_CYS_SHHA_DESCENDER                    0x0526 0x0527  // Ԧ/ԧ
#define UC_CYS_EN_LEFT_HOOK                      0x0528 0x0529  // Ԩ/ԩ
#define UC_CYS_DZZHE                             0x052A 0x052B  // Ԫ/ԫ
#define UC_CYS_DCHE                              0x052C 0x052D  // Ԭ/ԭ
#define UC_CYS_EL_DESCENDER                      0x052E 0x052F  // Ԯ/ԯ
