/* cyrillic_extended_b.h – Unicode constants for U+A640 … U+A69F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_ZEMLYA                                0xA640 0xA641  // Ꙁ/ꙁ
#define UC_DZELO                                 0xA642 0xA643  // Ꙃ/ꙃ
#define UC_REVERSED_DZE                          0xA644 0xA645  // Ꙅ/ꙅ
#define UC_IOTA                                  0xA646 0xA647  // Ꙇ/ꙇ
#define UC_DJERV                                 0xA648 0xA649  // Ꙉ/ꙉ
#define UC_MONOGRAPH_UK                          0xA64A 0xA64B  // Ꙋ/ꙋ
#define UC_BROAD_OMEGA                           0xA64C 0xA64D  // Ꙍ/ꙍ
#define UC_NEUTRAL_YER                           0xA64E 0xA64F  // Ꙏ/ꙏ
#define UC_YERU_BACK_YER                         0xA650 0xA651  // Ꙑ/ꙑ
#define UC_IOTIFIED_YAT                          0xA652 0xA653  // Ꙓ/ꙓ
#define UC_REVERSED_YU                           0xA654 0xA655  // Ꙕ/ꙕ
#define UC_IOTIFIED_A                            0xA656 0xA657  // Ꙗ/ꙗ
#define UC_CLOSED_LITTLE_YUS                     0xA658 0xA659  // Ꙙ/ꙙ
#define UC_BLENDED_YUS                           0xA65A 0xA65B  // Ꙛ/ꙛ
#define UC_IOTIFIED_CLOSED_LITTLE_YUS            0xA65C 0xA65D  // Ꙝ/ꙝ
#define UC_YN                                    0xA65E 0xA65F  // Ꙟ/ꙟ
#define UC_REVERSED_TSE                          0xA660 0xA661  // Ꙡ/ꙡ
#define UC_SOFT_DE                               0xA662 0xA663  // Ꙣ/ꙣ
#define UC_SOFT_EL                               0xA664 0xA665  // Ꙥ/ꙥ
#define UC_SOFT_EM                               0xA666 0xA667  // Ꙧ/ꙧ
#define UC_MONOCULAR_O                           0xA668 0xA669  // Ꙩ/ꙩ
#define UC_BINOCULAR_O                           0xA66A 0xA66B  // Ꙫ/ꙫ
#define UC_DOUBLE_MONOCULAR_O                    0xA66C 0xA66D  // Ꙭ/ꙭ
#define UC_MULTIOCULAR_O                         0xA66E 0  // ꙮ
#define UC_COMBINING_VZMET                       0xA66F 0  // ꙯
#define UC_COMBINING_TEN_MILLIONS_SIGN           0xA670 0  // ꙰
#define UC_COMBINING_HUNDRED_MILLIONS_SIGN       0xA671 0  // ꙱
#define UC_COMBINING_THOUSAND_MILLIONS_SIGN      0xA672 0  // ꙲
#define UC_SLAVONIC_ASTERISK                     0xA673 0  // ꙳
#define UC_COMBINING_UKRAINIAN_IE                0xA674 0  // ꙴ
#define UC_COMBINING_I                           0xA675 0  // ꙵ
#define UC_COMBINING_YI                          0xA676 0  // ꙶ
#define UC_COMBINING_U                           0xA677 0  // ꙷ
#define UC_COMBINING_HARD_SIGN                   0xA678 0  // ꙸ
#define UC_COMBINING_YERU                        0xA679 0  // ꙹ
#define UC_COMBINING_SOFT_SIGN                   0xA67A 0  // ꙺ
#define UC_COMBINING_OMEGA                       0xA67B 0  // ꙻ
#define UC_COMBINING_KAVYKA                      0xA67C 0  // ꙼
#define UC_COMBINING_PAYEROK                     0xA67D 0  // ꙽
#define UC_KAVYKA                                0xA67E 0  // ꙾
#define UC_PAYEROK                               0xA67F 0  // ꙿ
#define UC_DWE                                   0xA680 0xA681  // Ꚁ/ꚁ
#define UC_DZWE                                  0xA682 0xA683  // Ꚃ/ꚃ
#define UC_ZHWE                                  0xA684 0xA685  // Ꚅ/ꚅ
#define UC_CCHE                                  0xA686 0xA687  // Ꚇ/ꚇ
#define UC_DZZE                                  0xA688 0xA689  // Ꚉ/ꚉ
#define UC_TE_MIDDLE_HOOK                        0xA68A 0xA68B  // Ꚋ/ꚋ
#define UC_TWE                                   0xA68C 0xA68D  // Ꚍ/ꚍ
#define UC_TSWE                                  0xA68E 0xA68F  // Ꚏ/ꚏ
#define UC_TSSE                                  0xA690 0xA691  // Ꚑ/ꚑ
#define UC_TCHE                                  0xA692 0xA693  // Ꚓ/ꚓ
#define UC_HWE                                   0xA694 0xA695  // Ꚕ/ꚕ
#define UC_SHWE                                  0xA696 0xA697  // Ꚗ/ꚗ
#define UC_DOUBLE_O                              0xA698 0xA699  // Ꚙ/ꚙ
#define UC_CROSSED_O                             0xA69A 0xA69B  // Ꚛ/ꚛ
#define UC_MODIFIER_HARD_SIGN                    0xA69C 0  // ꚜ
#define UC_MODIFIER_SOFT_SIGN                    0xA69D 0  // ꚝ
#define UC_COMBINING_EF                          0xA69E 0  // ꚞ
#define UC_COMBINING_IOTIFIED_E                  0xA69F 0  // ꚟ
