/* devanagari_extended_a.h – Unicode constants for U+11B00 … U+11B09
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_DV_HEAD_MARK                          0x11B00 0  // 𑬀
#define UC_DV_HEAD_MARK_WITH_HEADSTROKE          0x11B01 0  // 𑬁
#define UC_DV_SIGN_BHALE                         0x11B02 0  // 𑬂
#define UC_DV_SIGN_BHALE_WITH_HOOK               0x11B03 0  // 𑬃
#define UC_DV_SIGN_EXTENDED_BHALE                0x11B04 0  // 𑬄
#define UC_DV_SIGN_EXTENDED_BHALE_WITH_HOOK      0x11B05 0  // 𑬅
#define UC_DV_SIGN_WESTERN_FIVE_LIKE_BHALE       0x11B06 0  // 𑬆
#define UC_DV_SIGN_WESTERN_NINE_LIKE_BHALE       0x11B07 0  // 𑬇
#define UC_DV_SIGN_REVERSED_NINE_LIKE_BHALE      0x11B08 0  // 𑬈
#define UC_DV_SIGN_MINDU                         0x11B09 0  // 𑬉
