/* Elbasan.h – Unicode constants for U+10500 … U+1052F
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_ELBASAN_LETTER_A                      0x10500   /* U+10500 (ELBASAN LETTER A) 𐔀 */
#define UC_ELBASAN_LETTER_BE                     0x10501   /* U+10501 (ELBASAN LETTER BE) 𐔁 */
#define UC_ELBASAN_LETTER_CE                     0x10502   /* U+10502 (ELBASAN LETTER CE) 𐔂 */
#define UC_ELBASAN_LETTER_CHE                    0x10503   /* U+10503 (ELBASAN LETTER CHE) 𐔃 */
#define UC_ELBASAN_LETTER_DE                     0x10504   /* U+10504 (ELBASAN LETTER DE) 𐔄 */
#define UC_ELBASAN_LETTER_NDE                    0x10505   /* U+10505 (ELBASAN LETTER NDE) 𐔅 */
#define UC_ELBASAN_LETTER_DHE                    0x10506   /* U+10506 (ELBASAN LETTER DHE) 𐔆 */
#define UC_ELBASAN_LETTER_EI                     0x10507   /* U+10507 (ELBASAN LETTER EI) 𐔇 */
#define UC_ELBASAN_LETTER_E                      0x10508   /* U+10508 (ELBASAN LETTER E) 𐔈 */
#define UC_ELBASAN_LETTER_FE                     0x10509   /* U+10509 (ELBASAN LETTER FE) 𐔉 */
#define UC_ELBASAN_LETTER_GE                     0x1050A   /* U+1050A (ELBASAN LETTER GE) 𐔊 */
#define UC_ELBASAN_LETTER_GJE                    0x1050B   /* U+1050B (ELBASAN LETTER GJE) 𐔋 */
#define UC_ELBASAN_LETTER_HE                     0x1050C   /* U+1050C (ELBASAN LETTER HE) 𐔌 */
#define UC_ELBASAN_LETTER_I                      0x1050D   /* U+1050D (ELBASAN LETTER I) 𐔍 */
#define UC_ELBASAN_LETTER_JE                     0x1050E   /* U+1050E (ELBASAN LETTER JE) 𐔎 */
#define UC_ELBASAN_LETTER_KE                     0x1050F   /* U+1050F (ELBASAN LETTER KE) 𐔏 */
#define UC_ELBASAN_LETTER_LE                     0x10510   /* U+10510 (ELBASAN LETTER LE) 𐔐 */
#define UC_ELBASAN_LETTER_LLE                    0x10511   /* U+10511 (ELBASAN LETTER LLE) 𐔑 */
#define UC_ELBASAN_LETTER_ME                     0x10512   /* U+10512 (ELBASAN LETTER ME) 𐔒 */
#define UC_ELBASAN_LETTER_NE                     0x10513   /* U+10513 (ELBASAN LETTER NE) 𐔓 */
#define UC_ELBASAN_LETTER_NA                     0x10514   /* U+10514 (ELBASAN LETTER NA) 𐔔 */
#define UC_ELBASAN_LETTER_NJE                    0x10515   /* U+10515 (ELBASAN LETTER NJE) 𐔕 */
#define UC_ELBASAN_LETTER_O                      0x10516   /* U+10516 (ELBASAN LETTER O) 𐔖 */
#define UC_ELBASAN_LETTER_PE                     0x10517   /* U+10517 (ELBASAN LETTER PE) 𐔗 */
#define UC_ELBASAN_LETTER_QE                     0x10518   /* U+10518 (ELBASAN LETTER QE) 𐔘 */
#define UC_ELBASAN_LETTER_RE                     0x10519   /* U+10519 (ELBASAN LETTER RE) 𐔙 */
#define UC_ELBASAN_LETTER_RRE                    0x1051A   /* U+1051A (ELBASAN LETTER RRE) 𐔚 */
#define UC_ELBASAN_LETTER_SE                     0x1051B   /* U+1051B (ELBASAN LETTER SE) 𐔛 */
#define UC_ELBASAN_LETTER_SHE                    0x1051C   /* U+1051C (ELBASAN LETTER SHE) 𐔜 */
#define UC_ELBASAN_LETTER_TE                     0x1051D   /* U+1051D (ELBASAN LETTER TE) 𐔝 */
#define UC_ELBASAN_LETTER_THE                    0x1051E   /* U+1051E (ELBASAN LETTER THE) 𐔞 */
#define UC_ELBASAN_LETTER_U                      0x1051F   /* U+1051F (ELBASAN LETTER U) 𐔟 */
#define UC_ELBASAN_LETTER_VE                     0x10520   /* U+10520 (ELBASAN LETTER VE) 𐔠 */
#define UC_ELBASAN_LETTER_XE                     0x10521   /* U+10521 (ELBASAN LETTER XE) 𐔡 */
#define UC_ELBASAN_LETTER_Y                      0x10522   /* U+10522 (ELBASAN LETTER Y) 𐔢 */
#define UC_ELBASAN_LETTER_ZE                     0x10523   /* U+10523 (ELBASAN LETTER ZE) 𐔣 */
#define UC_ELBASAN_LETTER_ZHE                    0x10524   /* U+10524 (ELBASAN LETTER ZHE) 𐔤 */
#define UC_ELBASAN_LETTER_GHE                    0x10525   /* U+10525 (ELBASAN LETTER GHE) 𐔥 */
#define UC_ELBASAN_LETTER_GHAMMA                 0x10526   /* U+10526 (ELBASAN LETTER GHAMMA) 𐔦 */
#define UC_ELBASAN_LETTER_KHE                    0x10527   /* U+10527 (ELBASAN LETTER KHE) 𐔧 */
#define UC_UNKNOWN_10528                         0x10528   /* U+10528 (UNKNOWN_10528) */
#define UC_UNKNOWN_10529                         0x10529   /* U+10529 (UNKNOWN_10529) */
#define UC_UNKNOWN_1052A                         0x1052A   /* U+1052A (UNKNOWN_1052A) */
#define UC_UNKNOWN_1052B                         0x1052B   /* U+1052B (UNKNOWN_1052B) */
#define UC_UNKNOWN_1052C                         0x1052C   /* U+1052C (UNKNOWN_1052C) */
#define UC_UNKNOWN_1052D                         0x1052D   /* U+1052D (UNKNOWN_1052D) */
#define UC_UNKNOWN_1052E                         0x1052E   /* U+1052E (UNKNOWN_1052E) */
#define UC_UNKNOWN_1052F                         0x1052F   /* U+1052F (UNKNOWN_1052F) */
