/* Enclosed Ideographic Supplement.h – Unicode constants for U+1F260 … U+1F265
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_ROUNDED_SYMBOL_FOR_FU                 0x1F260 0  // 🉠
#define UC_ROUNDED_SYMBOL_FOR_LU                 0x1F261 0  // 🉡
#define UC_ROUNDED_SYMBOL_FOR_SHOU               0x1F262 0  // 🉢
#define UC_ROUNDED_SYMBOL_FOR_XI                 0x1F263 0  // 🉣
#define UC_ROUNDED_SYMBOL_FOR_SHUANGXI           0x1F264 0  // 🉤
#define UC_ROUNDED_SYMBOL_FOR_CAI                0x1F265 0  // 🉥
