/* Ethiopic Extended.h – Unicode constants for U+2DD8 … U+2DDE
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_ETHIOPIC_SYLLABLE_GYA                 0x2DD8 0  // ⷘ
#define UC_ETHIOPIC_SYLLABLE_GYU                 0x2DD9 0  // ⷙ
#define UC_ETHIOPIC_SYLLABLE_GYI                 0x2DDA 0  // ⷚ
#define UC_ETHIOPIC_SYLLABLE_GYAA                0x2DDB 0  // ⷛ
#define UC_ETHIOPIC_SYLLABLE_GYEE                0x2DDC 0  // ⷜ
#define UC_ETHIOPIC_SYLLABLE_GYE                 0x2DDD 0  // ⷝ
#define UC_ETHIOPIC_SYLLABLE_GYO                 0x2DDE 0  // ⷞ
