/* garay.h – Unicode constants for U+10D40 … U+10D8F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
*
* See https://www.unicode.org/versions/latest/ for source data.

 * Garay may refer to:
 *

* Consistency Check:
* Total Defined Code Points: 69
* Total Significant Hex Values: 69
* Status: OK (Counts Match)

*/

#pragma once

#define UC_GARAY_ZERO                            0x10D40 0  // 𐵀
#define UC_GARAY_ONE                             0x10D41 0  // 𐵁
#define UC_GARAY_TWO                             0x10D42 0  // 𐵂
#define UC_GARAY_THREE                           0x10D43 0  // 𐵃
#define UC_GARAY_FOUR                            0x10D44 0  // 𐵄
#define UC_GARAY_FIVE                            0x10D45 0  // 𐵅
#define UC_GARAY_SIX                             0x10D46 0  // 𐵆
#define UC_GARAY_SEVEN                           0x10D47 0  // 𐵇
#define UC_GARAY_EIGHT                           0x10D48 0  // 𐵈
#define UC_GARAY_NINE                            0x10D49 0  // 𐵉
#define UC_GARAY_VOWEL_SIGN_A                    0x10D4A 0  // 𐵊
#define UC_GARAY_VOWEL_SIGN_I                    0x10D4B 0  // 𐵋
#define UC_GARAY_VOWEL_SIGN_O                    0x10D4C 0  // 𐵌
#define UC_GARAY_VOWEL_SIGN_EE                   0x10D4D 0  // 𐵍
#define UC_GARAY_VOWEL_LENGTH_MARK               0x10D4E 0  // 𐵎
#define UC_GARAY_SUKUN                           0x10D4F 0  // 𐵏
#define UC_GARAY_CAPITAL_A                       0x10D50 0  // 𐵐
#define UC_GARAY_CAPITAL_CA                      0x10D51 0  // 𐵑
#define UC_GARAY_CAPITAL_MA                      0x10D52 0  // 𐵒
#define UC_GARAY_CAPITAL_KA                      0x10D53 0  // 𐵓
#define UC_GARAY_CAPITAL_BA                      0x10D54 0  // 𐵔
#define UC_GARAY_CAPITAL_JA                      0x10D55 0  // 𐵕
#define UC_GARAY_CAPITAL_SA                      0x10D56 0  // 𐵖
#define UC_GARAY_CAPITAL_WA                      0x10D57 0  // 𐵗
#define UC_GARAY_CAPITAL_LA                      0x10D58 0  // 𐵘
#define UC_GARAY_CAPITAL_GA                      0x10D59 0  // 𐵙
#define UC_GARAY_CAPITAL_DA                      0x10D5A 0  // 𐵚
#define UC_GARAY_CAPITAL_XA                      0x10D5B 0  // 𐵛
#define UC_GARAY_CAPITAL_YA                      0x10D5C 0  // 𐵜
#define UC_GARAY_CAPITAL_TA                      0x10D5D 0  // 𐵝
#define UC_GARAY_CAPITAL_RA                      0x10D5E 0  // 𐵞
#define UC_GARAY_CAPITAL_NYA                     0x10D5F 0  // 𐵟
#define UC_GARAY_CAPITAL_FA                      0x10D60 0  // 𐵠
#define UC_GARAY_CAPITAL_NA                      0x10D61 0  // 𐵡
#define UC_GARAY_CAPITAL_PA                      0x10D62 0  // 𐵢
#define UC_GARAY_CAPITAL_HA                      0x10D63 0  // 𐵣
#define UC_GARAY_CAPITAL_OLD_KA                  0x10D64 0  // 𐵤
#define UC_GARAY_CAPITAL_OLD_NA                  0x10D65 0  // 𐵥
#define UC_GARAY_VOWEL_SIGN_E                    0x10D69 0  // 𐵩
#define UC_GARAY_CONSONANT_GEMINATION_MARK       0x10D6A 0  // 𐵪
#define UC_GARAY_COMBINING_DOT_ABOVE             0x10D6B 0  // 𐵫
#define UC_GARAY_COMBINING_DOUBLE_DOT_ABOVE      0x10D6C 0  // 𐵬
#define UC_GARAY_CONSONANT_NASALIZATION_MARK     0x10D6D 0  // 𐵭
#define UC_GARAY_HYPHEN                          0x10D6E 0  // 𐵮
#define UC_GARAY_REDUPLICATION_MARK              0x10D6F 0  // 𐵯
#define UC_GARAY_SMALL_A                         0x10D70 0  // 𐵰
#define UC_GARAY_SMALL_CA                        0x10D71 0  // 𐵱
#define UC_GARAY_SMALL_MA                        0x10D72 0  // 𐵲
#define UC_GARAY_SMALL_KA                        0x10D73 0  // 𐵳
#define UC_GARAY_SMALL_BA                        0x10D74 0  // 𐵴
#define UC_GARAY_SMALL_JA                        0x10D75 0  // 𐵵
#define UC_GARAY_SMALL_SA                        0x10D76 0  // 𐵶
#define UC_GARAY_SMALL_WA                        0x10D77 0  // 𐵷
#define UC_GARAY_SMALL_LA                        0x10D78 0  // 𐵸
#define UC_GARAY_SMALL_GA                        0x10D79 0  // 𐵹
#define UC_GARAY_SMALL_DA                        0x10D7A 0  // 𐵺
#define UC_GARAY_SMALL_XA                        0x10D7B 0  // 𐵻
#define UC_GARAY_SMALL_YA                        0x10D7C 0  // 𐵼
#define UC_GARAY_SMALL_TA                        0x10D7D 0  // 𐵽
#define UC_GARAY_SMALL_RA                        0x10D7E 0  // 𐵾
#define UC_GARAY_SMALL_NYA                       0x10D7F 0  // 𐵿
#define UC_GARAY_SMALL_FA                        0x10D80 0  // 𐶀
#define UC_GARAY_SMALL_NA                        0x10D81 0  // 𐶁
#define UC_GARAY_SMALL_PA                        0x10D82 0  // 𐶂
#define UC_GARAY_SMALL_HA                        0x10D83 0  // 𐶃
#define UC_GARAY_SMALL_OLD_KA                    0x10D84 0  // 𐶄
#define UC_GARAY_SMALL_OLD_NA                    0x10D85 0  // 𐶅
#define UC_GARAY_PLUS_SIGN                       0x10D8E 0  // 𐶎
#define UC_GARAY_MINUS_SIGN                      0x10D8F 0  // 𐶏
