/* general_punctuation.h – Unicode constants for U+2066 … U+206F
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_LEFT_TO_RIGHT_ISOLATE                 0x2066 0  /* U+2066 (LEFT-TO-RIGHT ISOLATE) */
#define UC_RIGHT_TO_LEFT_ISOLATE                 0x2067 0  /* U+2067 (RIGHT-TO-LEFT ISOLATE) */
#define UC_FIRST_STRONG_ISOLATE                  0x2068 0  /* U+2068 (FIRST STRONG ISOLATE) */
#define UC_POP_DIRECTIONAL_ISOLATE               0x2069 0  /* U+2069 (POP DIRECTIONAL ISOLATE) */
#define UC_INHIBIT_SYMMETRIC_SWAPPING            0x206A 0  /* U+206A (INHIBIT SYMMETRIC SWAPPING) */
#define UC_ACTIVATE_SYMMETRIC_SWAPPING           0x206B 0  /* U+206B (ACTIVATE SYMMETRIC SWAPPING) */
#define UC_INHIBIT_ARABIC_FORM_SHAPING           0x206C 0  /* U+206C (INHIBIT ARABIC FORM SHAPING) */
#define UC_ACTIVATE_ARABIC_FORM_SHAPING          0x206D 0  /* U+206D (ACTIVATE ARABIC FORM SHAPING) */
#define UC_NATIONAL_DIGIT_SHAPES                 0x206E 0  /* U+206E (NATIONAL DIGIT SHAPES) */
#define UC_NOMINAL_DIGIT_SHAPES                  0x206F 0  /* U+206F (NOMINAL DIGIT SHAPES) */
