/* georgian_extended.h – Unicode constants for U+1CBD … U+1CBF
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_GEORGIAN_MTAVRULI_CAPITAL_LETTER_AEN  0x1CBD 0  // Ჽ
#define UC_GEORGIAN_MTAVRULI_CAPITAL_LETTER_HARD_SIGN 0x1CBE 0  // Ჾ
#define UC_GEORGIAN_MTAVRULI_CAPITAL_LETTER_LABIAL_SIGN 0x1CBF 0  // Ჿ
