/* gunjala_gondi.h – Unicode constants for U+11DA0 … U+11DA9
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_GUNJALA_GONDI_DIGIT_ZERO              0x11DA0 0  // 𑶠
#define UC_GUNJALA_GONDI_DIGIT_ONE               0x11DA1 0  // 𑶡
#define UC_GUNJALA_GONDI_DIGIT_TWO               0x11DA2 0  // 𑶢
#define UC_GUNJALA_GONDI_DIGIT_THREE             0x11DA3 0  // 𑶣
#define UC_GUNJALA_GONDI_DIGIT_FOUR              0x11DA4 0  // 𑶤
#define UC_GUNJALA_GONDI_DIGIT_FIVE              0x11DA5 0  // 𑶥
#define UC_GUNJALA_GONDI_DIGIT_SIX               0x11DA6 0  // 𑶦
#define UC_GUNJALA_GONDI_DIGIT_SEVEN             0x11DA7 0  // 𑶧
#define UC_GUNJALA_GONDI_DIGIT_EIGHT             0x11DA8 0  // 𑶨
#define UC_GUNJALA_GONDI_DIGIT_NINE              0x11DA9 0  // 𑶩
