/* Gurmukhi.h – Unicode constants for U+0A00 … U+0A7F
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_UNKNOWN_0A00                          0x0A00   /* U+0A00 (UNKNOWN_0A00) */
#define UC_GURMUKHI_SIGN_ADAK_BINDI              0x0A01   /* U+0A01 (GURMUKHI SIGN ADAK BINDI) ਁ */
#define UC_GURMUKHI_SIGN_BINDI                   0x0A02   /* U+0A02 (GURMUKHI SIGN BINDI) ਂ */
#define UC_GURMUKHI_SIGN_VISARGA                 0x0A03   /* U+0A03 (GURMUKHI SIGN VISARGA) ਃ */
#define UC_UNKNOWN_0A04                          0x0A04   /* U+0A04 (UNKNOWN_0A04) */
#define UC_GURMUKHI_LETTER_A                     0x0A05   /* U+0A05 (GURMUKHI LETTER A) ਅ */
#define UC_GURMUKHI_LETTER_AA                    0x0A06   /* U+0A06 (GURMUKHI LETTER AA) ਆ */
#define UC_GURMUKHI_LETTER_I                     0x0A07   /* U+0A07 (GURMUKHI LETTER I) ਇ */
#define UC_GURMUKHI_LETTER_II                    0x0A08   /* U+0A08 (GURMUKHI LETTER II) ਈ */
#define UC_GURMUKHI_LETTER_U                     0x0A09   /* U+0A09 (GURMUKHI LETTER U) ਉ */
#define UC_GURMUKHI_LETTER_UU                    0x0A0A   /* U+0A0A (GURMUKHI LETTER UU) ਊ */
#define UC_UNKNOWN_0A0B                          0x0A0B   /* U+0A0B (UNKNOWN_0A0B) */
#define UC_UNKNOWN_0A0C                          0x0A0C   /* U+0A0C (UNKNOWN_0A0C) */
#define UC_UNKNOWN_0A0D                          0x0A0D   /* U+0A0D (UNKNOWN_0A0D) */
#define UC_UNKNOWN_0A0E                          0x0A0E   /* U+0A0E (UNKNOWN_0A0E) */
#define UC_GURMUKHI_LETTER_EE                    0x0A0F   /* U+0A0F (GURMUKHI LETTER EE) ਏ */
#define UC_GURMUKHI_LETTER_AI                    0x0A10   /* U+0A10 (GURMUKHI LETTER AI) ਐ */
#define UC_UNKNOWN_0A11                          0x0A11   /* U+0A11 (UNKNOWN_0A11) */
#define UC_UNKNOWN_0A12                          0x0A12   /* U+0A12 (UNKNOWN_0A12) */
#define UC_GURMUKHI_LETTER_OO                    0x0A13   /* U+0A13 (GURMUKHI LETTER OO) ਓ */
#define UC_GURMUKHI_LETTER_AU                    0x0A14   /* U+0A14 (GURMUKHI LETTER AU) ਔ */
#define UC_GURMUKHI_LETTER_KA                    0x0A15   /* U+0A15 (GURMUKHI LETTER KA) ਕ */
#define UC_GURMUKHI_LETTER_KHA                   0x0A16   /* U+0A16 (GURMUKHI LETTER KHA) ਖ */
#define UC_GURMUKHI_LETTER_GA                    0x0A17   /* U+0A17 (GURMUKHI LETTER GA) ਗ */
#define UC_GURMUKHI_LETTER_GHA                   0x0A18   /* U+0A18 (GURMUKHI LETTER GHA) ਘ */
#define UC_GURMUKHI_LETTER_NGA                   0x0A19   /* U+0A19 (GURMUKHI LETTER NGA) ਙ */
#define UC_GURMUKHI_LETTER_CA                    0x0A1A   /* U+0A1A (GURMUKHI LETTER CA) ਚ */
#define UC_GURMUKHI_LETTER_CHA                   0x0A1B   /* U+0A1B (GURMUKHI LETTER CHA) ਛ */
#define UC_GURMUKHI_LETTER_JA                    0x0A1C   /* U+0A1C (GURMUKHI LETTER JA) ਜ */
#define UC_GURMUKHI_LETTER_JHA                   0x0A1D   /* U+0A1D (GURMUKHI LETTER JHA) ਝ */
#define UC_GURMUKHI_LETTER_NYA                   0x0A1E   /* U+0A1E (GURMUKHI LETTER NYA) ਞ */
#define UC_GURMUKHI_LETTER_TTA                   0x0A1F   /* U+0A1F (GURMUKHI LETTER TTA) ਟ */
#define UC_GURMUKHI_LETTER_TTHA                  0x0A20   /* U+0A20 (GURMUKHI LETTER TTHA) ਠ */
#define UC_GURMUKHI_LETTER_DDA                   0x0A21   /* U+0A21 (GURMUKHI LETTER DDA) ਡ */
#define UC_GURMUKHI_LETTER_DDHA                  0x0A22   /* U+0A22 (GURMUKHI LETTER DDHA) ਢ */
#define UC_GURMUKHI_LETTER_NNA                   0x0A23   /* U+0A23 (GURMUKHI LETTER NNA) ਣ */
#define UC_GURMUKHI_LETTER_TA                    0x0A24   /* U+0A24 (GURMUKHI LETTER TA) ਤ */
#define UC_GURMUKHI_LETTER_THA                   0x0A25   /* U+0A25 (GURMUKHI LETTER THA) ਥ */
#define UC_GURMUKHI_LETTER_DA                    0x0A26   /* U+0A26 (GURMUKHI LETTER DA) ਦ */
#define UC_GURMUKHI_LETTER_DHA                   0x0A27   /* U+0A27 (GURMUKHI LETTER DHA) ਧ */
#define UC_GURMUKHI_LETTER_NA                    0x0A28   /* U+0A28 (GURMUKHI LETTER NA) ਨ */
#define UC_UNKNOWN_0A29                          0x0A29   /* U+0A29 (UNKNOWN_0A29) */
#define UC_GURMUKHI_LETTER_PA                    0x0A2A   /* U+0A2A (GURMUKHI LETTER PA) ਪ */
#define UC_GURMUKHI_LETTER_PHA                   0x0A2B   /* U+0A2B (GURMUKHI LETTER PHA) ਫ */
#define UC_GURMUKHI_LETTER_BA                    0x0A2C   /* U+0A2C (GURMUKHI LETTER BA) ਬ */
#define UC_GURMUKHI_LETTER_BHA                   0x0A2D   /* U+0A2D (GURMUKHI LETTER BHA) ਭ */
#define UC_GURMUKHI_LETTER_MA                    0x0A2E   /* U+0A2E (GURMUKHI LETTER MA) ਮ */
#define UC_GURMUKHI_LETTER_YA                    0x0A2F   /* U+0A2F (GURMUKHI LETTER YA) ਯ */
#define UC_GURMUKHI_LETTER_RA                    0x0A30   /* U+0A30 (GURMUKHI LETTER RA) ਰ */
#define UC_UNKNOWN_0A31                          0x0A31   /* U+0A31 (UNKNOWN_0A31) */
#define UC_GURMUKHI_LETTER_LA                    0x0A32   /* U+0A32 (GURMUKHI LETTER LA) ਲ */
#define UC_GURMUKHI_LETTER_LLA                   0x0A33   /* U+0A33 (GURMUKHI LETTER LLA) ਲ਼ */
#define UC_UNKNOWN_0A34                          0x0A34   /* U+0A34 (UNKNOWN_0A34) */
#define UC_GURMUKHI_LETTER_VA                    0x0A35   /* U+0A35 (GURMUKHI LETTER VA) ਵ */
#define UC_GURMUKHI_LETTER_SHA                   0x0A36   /* U+0A36 (GURMUKHI LETTER SHA) ਸ਼ */
#define UC_UNKNOWN_0A37                          0x0A37   /* U+0A37 (UNKNOWN_0A37) */
#define UC_GURMUKHI_LETTER_SA                    0x0A38   /* U+0A38 (GURMUKHI LETTER SA) ਸ */
#define UC_GURMUKHI_LETTER_HA                    0x0A39   /* U+0A39 (GURMUKHI LETTER HA) ਹ */
#define UC_UNKNOWN_0A3A                          0x0A3A   /* U+0A3A (UNKNOWN_0A3A) */
#define UC_UNKNOWN_0A3B                          0x0A3B   /* U+0A3B (UNKNOWN_0A3B) */
#define UC_GURMUKHI_SIGN_NUKTA                   0x0A3C   /* U+0A3C (GURMUKHI SIGN NUKTA) ਼ */
#define UC_UNKNOWN_0A3D                          0x0A3D   /* U+0A3D (UNKNOWN_0A3D) */
#define UC_GURMUKHI_VOWEL_SIGN_AA                0x0A3E   /* U+0A3E (GURMUKHI VOWEL SIGN AA) ਾ */
#define UC_GURMUKHI_VOWEL_SIGN_I                 0x0A3F   /* U+0A3F (GURMUKHI VOWEL SIGN I) ਿ */
#define UC_GURMUKHI_VOWEL_SIGN_II                0x0A40   /* U+0A40 (GURMUKHI VOWEL SIGN II) ੀ */
#define UC_GURMUKHI_VOWEL_SIGN_U                 0x0A41   /* U+0A41 (GURMUKHI VOWEL SIGN U) ੁ */
#define UC_GURMUKHI_VOWEL_SIGN_UU                0x0A42   /* U+0A42 (GURMUKHI VOWEL SIGN UU) ੂ */
#define UC_UNKNOWN_0A43                          0x0A43   /* U+0A43 (UNKNOWN_0A43) */
#define UC_UNKNOWN_0A44                          0x0A44   /* U+0A44 (UNKNOWN_0A44) */
#define UC_UNKNOWN_0A45                          0x0A45   /* U+0A45 (UNKNOWN_0A45) */
#define UC_UNKNOWN_0A46                          0x0A46   /* U+0A46 (UNKNOWN_0A46) */
#define UC_GURMUKHI_VOWEL_SIGN_EE                0x0A47   /* U+0A47 (GURMUKHI VOWEL SIGN EE) ੇ */
#define UC_GURMUKHI_VOWEL_SIGN_AI                0x0A48   /* U+0A48 (GURMUKHI VOWEL SIGN AI) ੈ */
#define UC_UNKNOWN_0A49                          0x0A49   /* U+0A49 (UNKNOWN_0A49) */
#define UC_UNKNOWN_0A4A                          0x0A4A   /* U+0A4A (UNKNOWN_0A4A) */
#define UC_GURMUKHI_VOWEL_SIGN_OO                0x0A4B   /* U+0A4B (GURMUKHI VOWEL SIGN OO) ੋ */
#define UC_GURMUKHI_VOWEL_SIGN_AU                0x0A4C   /* U+0A4C (GURMUKHI VOWEL SIGN AU) ੌ */
#define UC_GURMUKHI_SIGN_VIRAMA                  0x0A4D   /* U+0A4D (GURMUKHI SIGN VIRAMA) ੍ */
#define UC_UNKNOWN_0A4E                          0x0A4E   /* U+0A4E (UNKNOWN_0A4E) */
#define UC_UNKNOWN_0A4F                          0x0A4F   /* U+0A4F (UNKNOWN_0A4F) */
#define UC_UNKNOWN_0A50                          0x0A50   /* U+0A50 (UNKNOWN_0A50) */
#define UC_GURMUKHI_SIGN_UDAAT                   0x0A51   /* U+0A51 (GURMUKHI SIGN UDAAT) ੑ */
#define UC_UNKNOWN_0A52                          0x0A52   /* U+0A52 (UNKNOWN_0A52) */
#define UC_UNKNOWN_0A53                          0x0A53   /* U+0A53 (UNKNOWN_0A53) */
#define UC_UNKNOWN_0A54                          0x0A54   /* U+0A54 (UNKNOWN_0A54) */
#define UC_UNKNOWN_0A55                          0x0A55   /* U+0A55 (UNKNOWN_0A55) */
#define UC_UNKNOWN_0A56                          0x0A56   /* U+0A56 (UNKNOWN_0A56) */
#define UC_UNKNOWN_0A57                          0x0A57   /* U+0A57 (UNKNOWN_0A57) */
#define UC_UNKNOWN_0A58                          0x0A58   /* U+0A58 (UNKNOWN_0A58) */
#define UC_GURMUKHI_LETTER_KHHA                  0x0A59   /* U+0A59 (GURMUKHI LETTER KHHA) ਖ਼ */
#define UC_GURMUKHI_LETTER_GHHA                  0x0A5A   /* U+0A5A (GURMUKHI LETTER GHHA) ਗ਼ */
#define UC_GURMUKHI_LETTER_ZA                    0x0A5B   /* U+0A5B (GURMUKHI LETTER ZA) ਜ਼ */
#define UC_GURMUKHI_LETTER_RRA                   0x0A5C   /* U+0A5C (GURMUKHI LETTER RRA) ੜ */
#define UC_UNKNOWN_0A5D                          0x0A5D   /* U+0A5D (UNKNOWN_0A5D) */
#define UC_GURMUKHI_LETTER_FA                    0x0A5E   /* U+0A5E (GURMUKHI LETTER FA) ਫ਼ */
#define UC_UNKNOWN_0A5F                          0x0A5F   /* U+0A5F (UNKNOWN_0A5F) */
#define UC_UNKNOWN_0A60                          0x0A60   /* U+0A60 (UNKNOWN_0A60) */
#define UC_UNKNOWN_0A61                          0x0A61   /* U+0A61 (UNKNOWN_0A61) */
#define UC_UNKNOWN_0A62                          0x0A62   /* U+0A62 (UNKNOWN_0A62) */
#define UC_UNKNOWN_0A63                          0x0A63   /* U+0A63 (UNKNOWN_0A63) */
#define UC_UNKNOWN_0A64                          0x0A64   /* U+0A64 (UNKNOWN_0A64) */
#define UC_UNKNOWN_0A65                          0x0A65   /* U+0A65 (UNKNOWN_0A65) */
#define UC_GURMUKHI_DIGIT_ZERO                   0x0A66   /* U+0A66 (GURMUKHI DIGIT ZERO) ੦ */
#define UC_GURMUKHI_DIGIT_ONE                    0x0A67   /* U+0A67 (GURMUKHI DIGIT ONE) ੧ */
#define UC_GURMUKHI_DIGIT_TWO                    0x0A68   /* U+0A68 (GURMUKHI DIGIT TWO) ੨ */
#define UC_GURMUKHI_DIGIT_THREE                  0x0A69   /* U+0A69 (GURMUKHI DIGIT THREE) ੩ */
#define UC_GURMUKHI_DIGIT_FOUR                   0x0A6A   /* U+0A6A (GURMUKHI DIGIT FOUR) ੪ */
#define UC_GURMUKHI_DIGIT_FIVE                   0x0A6B   /* U+0A6B (GURMUKHI DIGIT FIVE) ੫ */
#define UC_GURMUKHI_DIGIT_SIX                    0x0A6C   /* U+0A6C (GURMUKHI DIGIT SIX) ੬ */
#define UC_GURMUKHI_DIGIT_SEVEN                  0x0A6D   /* U+0A6D (GURMUKHI DIGIT SEVEN) ੭ */
#define UC_GURMUKHI_DIGIT_EIGHT                  0x0A6E   /* U+0A6E (GURMUKHI DIGIT EIGHT) ੮ */
#define UC_GURMUKHI_DIGIT_NINE                   0x0A6F   /* U+0A6F (GURMUKHI DIGIT NINE) ੯ */
#define UC_GURMUKHI_TIPPI                        0x0A70   /* U+0A70 (GURMUKHI TIPPI) ੰ */
#define UC_GURMUKHI_ADDAK                        0x0A71   /* U+0A71 (GURMUKHI ADDAK) ੱ */
#define UC_GURMUKHI_IRI                          0x0A72   /* U+0A72 (GURMUKHI IRI) ੲ */
#define UC_GURMUKHI_URA                          0x0A73   /* U+0A73 (GURMUKHI URA) ੳ */
#define UC_GURMUKHI_EK_ONKAR                     0x0A74   /* U+0A74 (GURMUKHI EK ONKAR) ੴ */
#define UC_GURMUKHI_SIGN_YAKASH                  0x0A75   /* U+0A75 (GURMUKHI SIGN YAKASH) ੵ */
#define UC_GURMUKHI_ABBREVIATION_SIGN            0x0A76   /* U+0A76 (GURMUKHI ABBREVIATION SIGN) ੶ */
#define UC_UNKNOWN_0A77                          0x0A77   /* U+0A77 (UNKNOWN_0A77) */
#define UC_UNKNOWN_0A78                          0x0A78   /* U+0A78 (UNKNOWN_0A78) */
#define UC_UNKNOWN_0A79                          0x0A79   /* U+0A79 (UNKNOWN_0A79) */
#define UC_UNKNOWN_0A7A                          0x0A7A   /* U+0A7A (UNKNOWN_0A7A) */
#define UC_UNKNOWN_0A7B                          0x0A7B   /* U+0A7B (UNKNOWN_0A7B) */
#define UC_UNKNOWN_0A7C                          0x0A7C   /* U+0A7C (UNKNOWN_0A7C) */
#define UC_UNKNOWN_0A7D                          0x0A7D   /* U+0A7D (UNKNOWN_0A7D) */
#define UC_UNKNOWN_0A7E                          0x0A7E   /* U+0A7E (UNKNOWN_0A7E) */
#define UC_UNKNOWN_0A7F                          0x0A7F   /* U+0A7F (UNKNOWN_0A7F) */
