/* gurmukhi.h – Unicode constants for U+0A66 … U+0A76
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_GK_DIGIT_ZERO                         0x0A66 0  // ੦
#define UC_GK_DIGIT_ONE                          0x0A67 0  // ੧
#define UC_GK_DIGIT_TWO                          0x0A68 0  // ੨
#define UC_GK_DIGIT_THREE                        0x0A69 0  // ੩
#define UC_GK_DIGIT_FOUR                         0x0A6A 0  // ੪
#define UC_GK_DIGIT_FIVE                         0x0A6B 0  // ੫
#define UC_GK_DIGIT_SIX                          0x0A6C 0  // ੬
#define UC_GK_DIGIT_SEVEN                        0x0A6D 0  // ੭
#define UC_GK_DIGIT_EIGHT                        0x0A6E 0  // ੮
#define UC_GK_DIGIT_NINE                         0x0A6F 0  // ੯
#define UC_GK_TIPPI                              0x0A70 0  // ੰ
#define UC_GK_ADDAK                              0x0A71 0  // ੱ
#define UC_GK_IRI                                0x0A72 0  // ੲ
#define UC_GK_URA                                0x0A73 0  // ੳ
#define UC_GK_EK_ONKAR                           0x0A74 0  // ੴ
#define UC_GK_SIGN_YAKASH                        0x0A75 0  // ੵ
#define UC_GK_ABBREVIATION_SIGN                  0x0A76 0  // ੶
