/* halfwidth_and_fullwidth_forms.h – Unicode constants for U+FFE8 … U+FFEE
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_UC_HALFWIDTH_LIGHT_VERTICAL           0xFFE8 0  // ￨
#define UC_UC_HALFWIDTH_LEFTWARDS_ARROW          0xFFE9 0  // ￩
#define UC_UC_HALFWIDTH_UPWARDS_ARROW            0xFFEA 0  // ￪
#define UC_UC_HALFWIDTH_RIGHTWARDS_ARROW         0xFFEB 0  // ￫
#define UC_UC_HALFWIDTH_DOWNWARDS_ARROW          0xFFEC 0  // ￬
#define UC_UC_HALFWIDTH_BLACK_SQUARE             0xFFED 0  // ￭
#define UC_UC_HALFWIDTH_WHITE_CIRCLE             0xFFEE 0  // ￮
