/* Hanunoo.h – Unicode constants for U+1720 … U+173F
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_HANUNOO_LETTER_A                      0x1720   /* U+1720 (HANUNOO LETTER A) ᜠ */
#define UC_HANUNOO_LETTER_I                      0x1721   /* U+1721 (HANUNOO LETTER I) ᜡ */
#define UC_HANUNOO_LETTER_U                      0x1722   /* U+1722 (HANUNOO LETTER U) ᜢ */
#define UC_HANUNOO_LETTER_KA                     0x1723   /* U+1723 (HANUNOO LETTER KA) ᜣ */
#define UC_HANUNOO_LETTER_GA                     0x1724   /* U+1724 (HANUNOO LETTER GA) ᜤ */
#define UC_HANUNOO_LETTER_NGA                    0x1725   /* U+1725 (HANUNOO LETTER NGA) ᜥ */
#define UC_HANUNOO_LETTER_TA                     0x1726   /* U+1726 (HANUNOO LETTER TA) ᜦ */
#define UC_HANUNOO_LETTER_DA                     0x1727   /* U+1727 (HANUNOO LETTER DA) ᜧ */
#define UC_HANUNOO_LETTER_NA                     0x1728   /* U+1728 (HANUNOO LETTER NA) ᜨ */
#define UC_HANUNOO_LETTER_PA                     0x1729   /* U+1729 (HANUNOO LETTER PA) ᜩ */
#define UC_HANUNOO_LETTER_BA                     0x172A   /* U+172A (HANUNOO LETTER BA) ᜪ */
#define UC_HANUNOO_LETTER_MA                     0x172B   /* U+172B (HANUNOO LETTER MA) ᜫ */
#define UC_HANUNOO_LETTER_YA                     0x172C   /* U+172C (HANUNOO LETTER YA) ᜬ */
#define UC_HANUNOO_LETTER_RA                     0x172D   /* U+172D (HANUNOO LETTER RA) ᜭ */
#define UC_HANUNOO_LETTER_LA                     0x172E   /* U+172E (HANUNOO LETTER LA) ᜮ */
#define UC_HANUNOO_LETTER_WA                     0x172F   /* U+172F (HANUNOO LETTER WA) ᜯ */
#define UC_HANUNOO_LETTER_SA                     0x1730   /* U+1730 (HANUNOO LETTER SA) ᜰ */
#define UC_HANUNOO_LETTER_HA                     0x1731   /* U+1731 (HANUNOO LETTER HA) ᜱ */
#define UC_HANUNOO_VOWEL_SIGN_I                  0x1732   /* U+1732 (HANUNOO VOWEL SIGN I) ᜲ */
#define UC_HANUNOO_VOWEL_SIGN_U                  0x1733   /* U+1733 (HANUNOO VOWEL SIGN U) ᜳ */
#define UC_HANUNOO_SIGN_PAMUDPOD                 0x1734   /* U+1734 (HANUNOO SIGN PAMUDPOD) ᜴ */
#define UC_PHILIPPINE_SINGLE_PUNCTUATION         0x1735   /* U+1735 (PHILIPPINE SINGLE PUNCTUATION) ᜵ */
#define UC_PHILIPPINE_DOUBLE_PUNCTUATION         0x1736   /* U+1736 (PHILIPPINE DOUBLE PUNCTUATION) ᜶ */
#define UC_UNKNOWN_1737                          0x1737   /* U+1737 (UNKNOWN_1737) */
#define UC_UNKNOWN_1738                          0x1738   /* U+1738 (UNKNOWN_1738) */
#define UC_UNKNOWN_1739                          0x1739   /* U+1739 (UNKNOWN_1739) */
#define UC_UNKNOWN_173A                          0x173A   /* U+173A (UNKNOWN_173A) */
#define UC_UNKNOWN_173B                          0x173B   /* U+173B (UNKNOWN_173B) */
#define UC_UNKNOWN_173C                          0x173C   /* U+173C (UNKNOWN_173C) */
#define UC_UNKNOWN_173D                          0x173D   /* U+173D (UNKNOWN_173D) */
#define UC_UNKNOWN_173E                          0x173E   /* U+173E (UNKNOWN_173E) */
#define UC_UNKNOWN_173F                          0x173F   /* U+173F (UNKNOWN_173F) */
