/* hanunoo.h – Unicode constants for U+1720 … U+173F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.

* Consistency Check:
* Total Defined Code Points: 23
* Total Significant Hex Values: 23
* Status: OK (Counts Match)

*/

#pragma once

#define UC_HANUNOO_A                             0x1720 0  // ᜠ
#define UC_HANUNOO_I                             0x1721 0  // ᜡ
#define UC_HANUNOO_U                             0x1722 0  // ᜢ
#define UC_HANUNOO_KA                            0x1723 0  // ᜣ
#define UC_HANUNOO_GA                            0x1724 0  // ᜤ
#define UC_HANUNOO_NGA                           0x1725 0  // ᜥ
#define UC_HANUNOO_TA                            0x1726 0  // ᜦ
#define UC_HANUNOO_DA                            0x1727 0  // ᜧ
#define UC_HANUNOO_NA                            0x1728 0  // ᜨ
#define UC_HANUNOO_PA                            0x1729 0  // ᜩ
#define UC_HANUNOO_BA                            0x172A 0  // ᜪ
#define UC_HANUNOO_MA                            0x172B 0  // ᜫ
#define UC_HANUNOO_YA                            0x172C 0  // ᜬ
#define UC_HANUNOO_RA                            0x172D 0  // ᜭ
#define UC_HANUNOO_LA                            0x172E 0  // ᜮ
#define UC_HANUNOO_WA                            0x172F 0  // ᜯ
#define UC_HANUNOO_SA                            0x1730 0  // ᜰ
#define UC_HANUNOO_HA                            0x1731 0  // ᜱ
#define UC_HANUNOO_VOWEL_SIGN_I                  0x1732 0  // ᜲ
#define UC_HANUNOO_VOWEL_SIGN_U                  0x1733 0  // ᜳ
#define UC_HANUNOO_SIGN_PAMUDPOD                 0x1734 0  // ᜴
#define UC_PHILIPPINE_SINGLE_PUNCTUATION         0x1735 0  // ᜵
#define UC_PHILIPPINE_DOUBLE_PUNCTUATION         0x1736 0  // ᜶
