/* Hatran.h – Unicode constants for U+108E0 … U+108FF
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_HATRAN_LETTER_ALEPH                   0x108E0   /* U+108E0 (HATRAN LETTER ALEPH) 𐣠 */
#define UC_HATRAN_LETTER_BETH                    0x108E1   /* U+108E1 (HATRAN LETTER BETH) 𐣡 */
#define UC_HATRAN_LETTER_GIMEL                   0x108E2   /* U+108E2 (HATRAN LETTER GIMEL) 𐣢 */
#define UC_HATRAN_LETTER_DALETH_RESH             0x108E3   /* U+108E3 (HATRAN LETTER DALETH-RESH) 𐣣 */
#define UC_HATRAN_LETTER_HE                      0x108E4   /* U+108E4 (HATRAN LETTER HE) 𐣤 */
#define UC_HATRAN_LETTER_WAW                     0x108E5   /* U+108E5 (HATRAN LETTER WAW) 𐣥 */
#define UC_HATRAN_LETTER_ZAYN                    0x108E6   /* U+108E6 (HATRAN LETTER ZAYN) 𐣦 */
#define UC_HATRAN_LETTER_HETH                    0x108E7   /* U+108E7 (HATRAN LETTER HETH) 𐣧 */
#define UC_HATRAN_LETTER_TETH                    0x108E8   /* U+108E8 (HATRAN LETTER TETH) 𐣨 */
#define UC_HATRAN_LETTER_YODH                    0x108E9   /* U+108E9 (HATRAN LETTER YODH) 𐣩 */
#define UC_HATRAN_LETTER_KAPH                    0x108EA   /* U+108EA (HATRAN LETTER KAPH) 𐣪 */
#define UC_HATRAN_LETTER_LAMEDH                  0x108EB   /* U+108EB (HATRAN LETTER LAMEDH) 𐣫 */
#define UC_HATRAN_LETTER_MEM                     0x108EC   /* U+108EC (HATRAN LETTER MEM) 𐣬 */
#define UC_HATRAN_LETTER_NUN                     0x108ED   /* U+108ED (HATRAN LETTER NUN) 𐣭 */
#define UC_HATRAN_LETTER_SAMEKH                  0x108EE   /* U+108EE (HATRAN LETTER SAMEKH) 𐣮 */
#define UC_HATRAN_LETTER_AYN                     0x108EF   /* U+108EF (HATRAN LETTER AYN) 𐣯 */
#define UC_HATRAN_LETTER_PE                      0x108F0   /* U+108F0 (HATRAN LETTER PE) 𐣰 */
#define UC_HATRAN_LETTER_SADHE                   0x108F1   /* U+108F1 (HATRAN LETTER SADHE) 𐣱 */
#define UC_HATRAN_LETTER_QOPH                    0x108F2   /* U+108F2 (HATRAN LETTER QOPH) 𐣲 */
#define UC_UNKNOWN_108F3                         0x108F3   /* U+108F3 (UNKNOWN_108F3) */
#define UC_HATRAN_LETTER_SHIN                    0x108F4   /* U+108F4 (HATRAN LETTER SHIN) 𐣴 */
#define UC_HATRAN_LETTER_TAW                     0x108F5   /* U+108F5 (HATRAN LETTER TAW) 𐣵 */
#define UC_UNKNOWN_108F6                         0x108F6   /* U+108F6 (UNKNOWN_108F6) */
#define UC_UNKNOWN_108F7                         0x108F7   /* U+108F7 (UNKNOWN_108F7) */
#define UC_UNKNOWN_108F8                         0x108F8   /* U+108F8 (UNKNOWN_108F8) */
#define UC_UNKNOWN_108F9                         0x108F9   /* U+108F9 (UNKNOWN_108F9) */
#define UC_UNKNOWN_108FA                         0x108FA   /* U+108FA (UNKNOWN_108FA) */
#define UC_HATRAN_NUMBER_ONE                     0x108FB   /* U+108FB (HATRAN NUMBER ONE) 𐣻 */
#define UC_HATRAN_NUMBER_FIVE                    0x108FC   /* U+108FC (HATRAN NUMBER FIVE) 𐣼 */
#define UC_HATRAN_NUMBER_TEN                     0x108FD   /* U+108FD (HATRAN NUMBER TEN) 𐣽 */
#define UC_HATRAN_NUMBER_TWENTY                  0x108FE   /* U+108FE (HATRAN NUMBER TWENTY) 𐣾 */
#define UC_HATRAN_NUMBER_ONE_HUNDRED             0x108FF   /* U+108FF (HATRAN NUMBER ONE HUNDRED) 𐣿 */
