/* High Surrogates.h – Unicode constants for U+D800 … U+DB7F
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

