/* High Private Use Surrogates.h – Unicode constants for U+DB80 … U+DBFF
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

