/* ideographic_symbols_and_punctuation.h – Unicode constants for U+16FE0 … U+16FFF
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
*
* See https://www.unicode.org/versions/latest/ for source data.

 * Ideographic Symbols and Punctuation is a Unicode block containing symbols
 * and punctuation marks used by ideographic scripts such as Tangut and Nüshu
 * , in addition to punctuation marks, symbols, diacritics and modifier
 * letters supplementing those in the CJK Symbols and Punctuation block.
 * The following Unicode-related documents record the purpose and process of
 * defining specific characters in the Ideographic Symbols and Punctuation
 * block:
 *

* Consistency Check:
* Total Defined Code Points: 12
* Total Significant Hex Values: 12
* Status: OK (Counts Match)

*/

#ifndef IDEOGRAPHIC_SYMBOLS_AND_PUNCTUATION_H
#define IDEOGRAPHIC_SYMBOLS_AND_PUNCTUATION_H

#define UC_TANGUT_ITERATION_MARK                 0x16FE0 0  // 𖿠
#define UC_NUSHU_ITERATION_MARK                  0x16FE1 0  // 𖿡
#define UC_OLD_CHINESE_HOOK_MARK                 0x16FE2 0  // 𖿢
#define UC_OLD_CHINESE_ITERATION_MARK            0x16FE3 0  // 𖿣
#define UC_KHITAN_SMALL_SC_FILLER                0x16FE4 0  // 𖿤
#define UC_VIETNAMESE_ALTERNATE_READING_MARK_CA  0x16FF0 0  // 𖿰
#define UC_VIETNAMESE_ALTERNATE_READING_MARK_NHAY 0x16FF1 0  // 𖿱
#define UC_CHINESE_SMALL_SIMPLIFIED_ER           0x16FF2 0  /* U+16FF2 (CHINESE SMALL SIMPLIFIED ER) */
#define UC_CHINESE_SMALL_TRADITIONAL_ER          0x16FF3 0  /* U+16FF3 (CHINESE SMALL TRADITIONAL ER) */
#define UC_YANGQIN_SIGN_SLOW_ONE_BEAT            0x16FF4 0  /* U+16FF4 (YANGQIN SIGN SLOW ONE BEAT) */
#define UC_YANGQIN_SIGN_SLOW_THREE_HALF_BEATS    0x16FF5 0  /* U+16FF5 (YANGQIN SIGN SLOW THREE HALF BEATS) */
#define UC_YANGQIN_SIGN_SLOW_TWO_BEATS           0x16FF6 0  /* U+16FF6 (YANGQIN SIGN SLOW TWO BEATS) */

#endif // IDEOGRAPHIC_SYMBOLS_AND_PUNCTUATION_H
