/* ideographic_symbols_and_punctuation.h – Unicode constants for U+16FF0 … U+16FF1
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_VIETNAMESE_ALTERNATE_READING_MARK_CA  0x16FF0 0  // 𖿰
#define UC_VIETNAMESE_ALTERNATE_READING_MARK_NHAY 0x16FF1 0  // 𖿱
