/* indic_siyaq_numbers.h – Unicode constants for U+1EC70 … U+1ECBF
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
*
* See https://www.unicode.org/versions/latest/ for source data.


* Consistency Check:
* Total Defined Code Points: 68
* Total Significant Hex Values: 68
* Status: OK (Counts Match)

*/

#pragma once

#define UC_INDIC_SIYAQ_ONE                       0x1EC71 0  // 𞱱
#define UC_INDIC_SIYAQ_TWO                       0x1EC72 0  // 𞱲
#define UC_INDIC_SIYAQ_THREE                     0x1EC73 0  // 𞱳
#define UC_INDIC_SIYAQ_FOUR                      0x1EC74 0  // 𞱴
#define UC_INDIC_SIYAQ_FIVE                      0x1EC75 0  // 𞱵
#define UC_INDIC_SIYAQ_SIX                       0x1EC76 0  // 𞱶
#define UC_INDIC_SIYAQ_SEVEN                     0x1EC77 0  // 𞱷
#define UC_INDIC_SIYAQ_EIGHT                     0x1EC78 0  // 𞱸
#define UC_INDIC_SIYAQ_NINE                      0x1EC79 0  // 𞱹
#define UC_INDIC_SIYAQ_TEN                       0x1EC7A 0  // 𞱺
#define UC_INDIC_SIYAQ_TWENTY                    0x1EC7B 0  // 𞱻
#define UC_INDIC_SIYAQ_THIRTY                    0x1EC7C 0  // 𞱼
#define UC_INDIC_SIYAQ_FORTY                     0x1EC7D 0  // 𞱽
#define UC_INDIC_SIYAQ_FIFTY                     0x1EC7E 0  // 𞱾
#define UC_INDIC_SIYAQ_SIXTY                     0x1EC7F 0  // 𞱿
#define UC_INDIC_SIYAQ_SEVENTY                   0x1EC80 0  // 𞲀
#define UC_INDIC_SIYAQ_EIGHTY                    0x1EC81 0  // 𞲁
#define UC_INDIC_SIYAQ_NINETY                    0x1EC82 0  // 𞲂
#define UC_INDIC_SIYAQ_ONE_HUNDRED               0x1EC83 0  // 𞲃
#define UC_INDIC_SIYAQ_TWO_HUNDRED               0x1EC84 0  // 𞲄
#define UC_INDIC_SIYAQ_THREE_HUNDRED             0x1EC85 0  // 𞲅
#define UC_INDIC_SIYAQ_FOUR_HUNDRED              0x1EC86 0  // 𞲆
#define UC_INDIC_SIYAQ_FIVE_HUNDRED              0x1EC87 0  // 𞲇
#define UC_INDIC_SIYAQ_SIX_HUNDRED               0x1EC88 0  // 𞲈
#define UC_INDIC_SIYAQ_SEVEN_HUNDRED             0x1EC89 0  // 𞲉
#define UC_INDIC_SIYAQ_EIGHT_HUNDRED             0x1EC8A 0  // 𞲊
#define UC_INDIC_SIYAQ_NINE_HUNDRED              0x1EC8B 0  // 𞲋
#define UC_INDIC_SIYAQ_ONE_THOUSAND              0x1EC8C 0  // 𞲌
#define UC_INDIC_SIYAQ_TWO_THOUSAND              0x1EC8D 0  // 𞲍
#define UC_INDIC_SIYAQ_THREE_THOUSAND            0x1EC8E 0  // 𞲎
#define UC_INDIC_SIYAQ_FOUR_THOUSAND             0x1EC8F 0  // 𞲏
#define UC_INDIC_SIYAQ_FIVE_THOUSAND             0x1EC90 0  // 𞲐
#define UC_INDIC_SIYAQ_SIX_THOUSAND              0x1EC91 0  // 𞲑
#define UC_INDIC_SIYAQ_SEVEN_THOUSAND            0x1EC92 0  // 𞲒
#define UC_INDIC_SIYAQ_EIGHT_THOUSAND            0x1EC93 0  // 𞲓
#define UC_INDIC_SIYAQ_NINE_THOUSAND             0x1EC94 0  // 𞲔
#define UC_INDIC_SIYAQ_TEN_THOUSAND              0x1EC95 0  // 𞲕
#define UC_INDIC_SIYAQ_TWENTY_THOUSAND           0x1EC96 0  // 𞲖
#define UC_INDIC_SIYAQ_THIRTY_THOUSAND           0x1EC97 0  // 𞲗
#define UC_INDIC_SIYAQ_FORTY_THOUSAND            0x1EC98 0  // 𞲘
#define UC_INDIC_SIYAQ_FIFTY_THOUSAND            0x1EC99 0  // 𞲙
#define UC_INDIC_SIYAQ_SIXTY_THOUSAND            0x1EC9A 0  // 𞲚
#define UC_INDIC_SIYAQ_SEVENTY_THOUSAND          0x1EC9B 0  // 𞲛
#define UC_INDIC_SIYAQ_EIGHTY_THOUSAND           0x1EC9C 0  // 𞲜
#define UC_INDIC_SIYAQ_NINETY_THOUSAND           0x1EC9D 0  // 𞲝
#define UC_INDIC_SIYAQ_LAKH                      0x1EC9E 0  // 𞲞
#define UC_INDIC_SIYAQ_LAKHAN                    0x1EC9F 0  // 𞲟
#define UC_INDIC_SIYAQ_LAKH_MARK                 0x1ECA0 0  // 𞲠
#define UC_INDIC_SIYAQ_KAROR                     0x1ECA1 0  // 𞲡
#define UC_INDIC_SIYAQ_KARORAN                   0x1ECA2 0  // 𞲢
#define UC_INDIC_SIYAQ_PREFIXED_ONE              0x1ECA3 0  // 𞲣
#define UC_INDIC_SIYAQ_PREFIXED_TWO              0x1ECA4 0  // 𞲤
#define UC_INDIC_SIYAQ_PREFIXED_THREE            0x1ECA5 0  // 𞲥
#define UC_INDIC_SIYAQ_PREFIXED_FOUR             0x1ECA6 0  // 𞲦
#define UC_INDIC_SIYAQ_PREFIXED_FIVE             0x1ECA7 0  // 𞲧
#define UC_INDIC_SIYAQ_PREFIXED_SIX              0x1ECA8 0  // 𞲨
#define UC_INDIC_SIYAQ_PREFIXED_SEVEN            0x1ECA9 0  // 𞲩
#define UC_INDIC_SIYAQ_PREFIXED_EIGHT            0x1ECAA 0  // 𞲪
#define UC_INDIC_SIYAQ_PREFIXED_NINE             0x1ECAB 0  // 𞲫
#define UC_INDIC_SIYAQ_PLACEHOLDER               0x1ECAC 0  // 𞲬
#define UC_INDIC_SIYAQ_FRACTION_ONE_QUARTER      0x1ECAD 0  // 𞲭
#define UC_INDIC_SIYAQ_FRACTION_ONE_HALF         0x1ECAE 0  // 𞲮
#define UC_INDIC_SIYAQ_FRACTION_THREE_QUARTERS   0x1ECAF 0  // 𞲯
#define UC_INDIC_SIYAQ_RUPEE_MARK                0x1ECB0 0  // 𞲰
#define UC_INDIC_SIYAQ_ALTERNATE_ONE             0x1ECB1 0  // 𞲱
#define UC_INDIC_SIYAQ_ALTERNATE_TWO             0x1ECB2 0  // 𞲲
#define UC_INDIC_SIYAQ_ALTERNATE_TEN_THOUSAND    0x1ECB3 0  // 𞲳
#define UC_INDIC_SIYAQ_ALTERNATE_LAKH_MARK       0x1ECB4 0  // 𞲴
