/* Katakana Phonetic Extensions.h – Unicode constants for U+31F0 … U+31FF
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_KATAKANA_LETTER_SMALL_KU              0x31F0   /* U+31F0 (KATAKANA LETTER SMALL KU) ㇰ */
#define UC_KATAKANA_LETTER_SMALL_SI              0x31F1   /* U+31F1 (KATAKANA LETTER SMALL SI) ㇱ */
#define UC_KATAKANA_LETTER_SMALL_SU              0x31F2   /* U+31F2 (KATAKANA LETTER SMALL SU) ㇲ */
#define UC_KATAKANA_LETTER_SMALL_TO              0x31F3   /* U+31F3 (KATAKANA LETTER SMALL TO) ㇳ */
#define UC_KATAKANA_LETTER_SMALL_NU              0x31F4   /* U+31F4 (KATAKANA LETTER SMALL NU) ㇴ */
#define UC_KATAKANA_LETTER_SMALL_HA              0x31F5   /* U+31F5 (KATAKANA LETTER SMALL HA) ㇵ */
#define UC_KATAKANA_LETTER_SMALL_HI              0x31F6   /* U+31F6 (KATAKANA LETTER SMALL HI) ㇶ */
#define UC_KATAKANA_LETTER_SMALL_HU              0x31F7   /* U+31F7 (KATAKANA LETTER SMALL HU) ㇷ */
#define UC_KATAKANA_LETTER_SMALL_HE              0x31F8   /* U+31F8 (KATAKANA LETTER SMALL HE) ㇸ */
#define UC_KATAKANA_LETTER_SMALL_HO              0x31F9   /* U+31F9 (KATAKANA LETTER SMALL HO) ㇹ */
#define UC_KATAKANA_LETTER_SMALL_MU              0x31FA   /* U+31FA (KATAKANA LETTER SMALL MU) ㇺ */
#define UC_KATAKANA_LETTER_SMALL_RA              0x31FB   /* U+31FB (KATAKANA LETTER SMALL RA) ㇻ */
#define UC_KATAKANA_LETTER_SMALL_RI              0x31FC   /* U+31FC (KATAKANA LETTER SMALL RI) ㇼ */
#define UC_KATAKANA_LETTER_SMALL_RU              0x31FD   /* U+31FD (KATAKANA LETTER SMALL RU) ㇽ */
#define UC_KATAKANA_LETTER_SMALL_RE              0x31FE   /* U+31FE (KATAKANA LETTER SMALL RE) ㇾ */
#define UC_KATAKANA_LETTER_SMALL_RO              0x31FF   /* U+31FF (KATAKANA LETTER SMALL RO) ㇿ */
