/* kirat_rai.h – Unicode constants for U+16D40 … U+16D7F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_KIRAT_RAI_SIGN_ANUSVARA               0x16D40 0  /* U+16D40 (KIRAT RAI SIGN ANUSVARA) */
#define UC_KIRAT_RAI_SIGN_TONPI                  0x16D41 0  /* U+16D41 (KIRAT RAI SIGN TONPI) */
#define UC_KIRAT_RAI_SIGN_VISARGA                0x16D42 0  /* U+16D42 (KIRAT RAI SIGN VISARGA) */
#define UC_KIRAT_RAI_A                           0x16D43 0  /* U+16D43 (KIRAT RAI LETTER A) */
#define UC_KIRAT_RAI_KA                          0x16D44 0  /* U+16D44 (KIRAT RAI LETTER KA) */
#define UC_KIRAT_RAI_KHA                         0x16D45 0  /* U+16D45 (KIRAT RAI LETTER KHA) */
#define UC_KIRAT_RAI_GA                          0x16D46 0  /* U+16D46 (KIRAT RAI LETTER GA) */
#define UC_KIRAT_RAI_GHA                         0x16D47 0  /* U+16D47 (KIRAT RAI LETTER GHA) */
#define UC_KIRAT_RAI_NGA                         0x16D48 0  /* U+16D48 (KIRAT RAI LETTER NGA) */
#define UC_KIRAT_RAI_CA                          0x16D49 0  /* U+16D49 (KIRAT RAI LETTER CA) */
#define UC_KIRAT_RAI_CHA                         0x16D4A 0  /* U+16D4A (KIRAT RAI LETTER CHA) */
#define UC_KIRAT_RAI_JA                          0x16D4B 0  /* U+16D4B (KIRAT RAI LETTER JA) */
#define UC_KIRAT_RAI_JHA                         0x16D4C 0  /* U+16D4C (KIRAT RAI LETTER JHA) */
#define UC_KIRAT_RAI_NYA                         0x16D4D 0  /* U+16D4D (KIRAT RAI LETTER NYA) */
#define UC_KIRAT_RAI_TTA                         0x16D4E 0  /* U+16D4E (KIRAT RAI LETTER TTA) */
#define UC_KIRAT_RAI_TTHA                        0x16D4F 0  /* U+16D4F (KIRAT RAI LETTER TTHA) */
#define UC_KIRAT_RAI_DDA                         0x16D50 0  /* U+16D50 (KIRAT RAI LETTER DDA) */
#define UC_KIRAT_RAI_DDHA                        0x16D51 0  /* U+16D51 (KIRAT RAI LETTER DDHA) */
#define UC_KIRAT_RAI_TA                          0x16D52 0  /* U+16D52 (KIRAT RAI LETTER TA) */
#define UC_KIRAT_RAI_THA                         0x16D53 0  /* U+16D53 (KIRAT RAI LETTER THA) */
#define UC_KIRAT_RAI_DA                          0x16D54 0  /* U+16D54 (KIRAT RAI LETTER DA) */
#define UC_KIRAT_RAI_DHA                         0x16D55 0  /* U+16D55 (KIRAT RAI LETTER DHA) */
#define UC_KIRAT_RAI_NA                          0x16D56 0  /* U+16D56 (KIRAT RAI LETTER NA) */
#define UC_KIRAT_RAI_PA                          0x16D57 0  /* U+16D57 (KIRAT RAI LETTER PA) */
#define UC_KIRAT_RAI_PHA                         0x16D58 0  /* U+16D58 (KIRAT RAI LETTER PHA) */
#define UC_KIRAT_RAI_BA                          0x16D59 0  /* U+16D59 (KIRAT RAI LETTER BA) */
#define UC_KIRAT_RAI_BHA                         0x16D5A 0  /* U+16D5A (KIRAT RAI LETTER BHA) */
#define UC_KIRAT_RAI_MA                          0x16D5B 0  /* U+16D5B (KIRAT RAI LETTER MA) */
#define UC_KIRAT_RAI_YA                          0x16D5C 0  /* U+16D5C (KIRAT RAI LETTER YA) */
#define UC_KIRAT_RAI_RA                          0x16D5D 0  /* U+16D5D (KIRAT RAI LETTER RA) */
#define UC_KIRAT_RAI_LA                          0x16D5E 0  /* U+16D5E (KIRAT RAI LETTER LA) */
#define UC_KIRAT_RAI_VA                          0x16D5F 0  /* U+16D5F (KIRAT RAI LETTER VA) */
#define UC_KIRAT_RAI_SA                          0x16D60 0  /* U+16D60 (KIRAT RAI LETTER SA) */
#define UC_KIRAT_RAI_SHA                         0x16D61 0  /* U+16D61 (KIRAT RAI LETTER SHA) */
#define UC_KIRAT_RAI_HA                          0x16D62 0  /* U+16D62 (KIRAT RAI LETTER HA) */
#define UC_KIRAT_RAI_VOWEL_SIGN_AA               0x16D63 0  /* U+16D63 (KIRAT RAI VOWEL SIGN AA) */
#define UC_KIRAT_RAI_VOWEL_SIGN_I                0x16D64 0  /* U+16D64 (KIRAT RAI VOWEL SIGN I) */
#define UC_KIRAT_RAI_VOWEL_SIGN_U                0x16D65 0  /* U+16D65 (KIRAT RAI VOWEL SIGN U) */
#define UC_KIRAT_RAI_VOWEL_SIGN_UE               0x16D66 0  /* U+16D66 (KIRAT RAI VOWEL SIGN UE) */
#define UC_KIRAT_RAI_VOWEL_SIGN_E                0x16D67 0  /* U+16D67 (KIRAT RAI VOWEL SIGN E) */
#define UC_KIRAT_RAI_VOWEL_SIGN_AI               0x16D68 0  /* U+16D68 (KIRAT RAI VOWEL SIGN AI) */
#define UC_KIRAT_RAI_VOWEL_SIGN_O                0x16D69 0  /* U+16D69 (KIRAT RAI VOWEL SIGN O) */
#define UC_KIRAT_RAI_VOWEL_SIGN_AU               0x16D6A 0  /* U+16D6A (KIRAT RAI VOWEL SIGN AU) */
#define UC_KIRAT_RAI_SIGN_VIRAMA                 0x16D6B 0  /* U+16D6B (KIRAT RAI SIGN VIRAMA) */
#define UC_KIRAT_RAI_SIGN_SAAT                   0x16D6C 0  /* U+16D6C (KIRAT RAI SIGN SAAT) */
#define UC_KIRAT_RAI_SIGN_YUPI                   0x16D6D 0  /* U+16D6D (KIRAT RAI SIGN YUPI) */
#define UC_KIRAT_RAI_DANDA                       0x16D6E 0  /* U+16D6E (KIRAT RAI DANDA) */
#define UC_KIRAT_RAI_DOUBLE_DANDA                0x16D6F 0  /* U+16D6F (KIRAT RAI DOUBLE DANDA) */
#define UC_KIRAT_RAI_ZERO                        0x16D70 0  /* U+16D70 (KIRAT RAI DIGIT ZERO) */
#define UC_KIRAT_RAI_ONE                         0x16D71 0  /* U+16D71 (KIRAT RAI DIGIT ONE) */
#define UC_KIRAT_RAI_TWO                         0x16D72 0  /* U+16D72 (KIRAT RAI DIGIT TWO) */
#define UC_KIRAT_RAI_THREE                       0x16D73 0  /* U+16D73 (KIRAT RAI DIGIT THREE) */
#define UC_KIRAT_RAI_FOUR                        0x16D74 0  /* U+16D74 (KIRAT RAI DIGIT FOUR) */
#define UC_KIRAT_RAI_FIVE                        0x16D75 0  /* U+16D75 (KIRAT RAI DIGIT FIVE) */
#define UC_KIRAT_RAI_SIX                         0x16D76 0  /* U+16D76 (KIRAT RAI DIGIT SIX) */
#define UC_KIRAT_RAI_SEVEN                       0x16D77 0  /* U+16D77 (KIRAT RAI DIGIT SEVEN) */
#define UC_KIRAT_RAI_EIGHT                       0x16D78 0  /* U+16D78 (KIRAT RAI DIGIT EIGHT) */
#define UC_KIRAT_RAI_NINE                        0x16D79 0  /* U+16D79 (KIRAT RAI DIGIT NINE) */
