/* latin_1_supplement.h – Unicode constants for U+0080 … U+00FF
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
*
* See https://www.unicode.org/versions/latest/ for source data.


* Consistency Check:
* Total Defined Code Points: 130
* Total Significant Hex Values: 130
* Status: OK (Counts Match)

*/

#pragma once

#define UC_L1S_CC_U0080                          0x0080 0  /* U+0080 (Cc_U0080) */
#define UC_L1S_CC_U0081                          0x0081 0  /* U+0081 (Cc_U0081) */
#define UC_L1S_CC_U0082                          0x0082 0  /* U+0082 (Cc_U0082) */
#define UC_L1S_CC_U0083                          0x0083 0  /* U+0083 (Cc_U0083) */
#define UC_L1S_CC_U0084                          0x0084 0  /* U+0084 (Cc_U0084) */
#define UC_L1S_CC_U0085                          0x0085 0  /* U+0085 (Cc_U0085) */
#define UC_L1S_CC_U0086                          0x0086 0  /* U+0086 (Cc_U0086) */
#define UC_L1S_CC_U0087                          0x0087 0  /* U+0087 (Cc_U0087) */
#define UC_L1S_CC_U0088                          0x0088 0  /* U+0088 (Cc_U0088) */
#define UC_L1S_CC_U0089                          0x0089 0  /* U+0089 (Cc_U0089) */
#define UC_L1S_CC_U008A                          0x008A 0  /* U+008A (Cc_U008A) */
#define UC_L1S_CC_U008B                          0x008B 0  /* U+008B (Cc_U008B) */
#define UC_L1S_CC_U008C                          0x008C 0  /* U+008C (Cc_U008C) */
#define UC_L1S_CC_U008D                          0x008D 0  /* U+008D (Cc_U008D) */
#define UC_L1S_CC_U008E                          0x008E 0  /* U+008E (Cc_U008E) */
#define UC_L1S_CC_U008F                          0x008F 0  /* U+008F (Cc_U008F) */
#define UC_L1S_CC_U0090                          0x0090 0  /* U+0090 (Cc_U0090) */
#define UC_L1S_CC_U0091                          0x0091 0  /* U+0091 (Cc_U0091) */
#define UC_L1S_CC_U0092                          0x0092 0  /* U+0092 (Cc_U0092) */
#define UC_L1S_CC_U0093                          0x0093 0  /* U+0093 (Cc_U0093) */
#define UC_L1S_CC_U0094                          0x0094 0  /* U+0094 (Cc_U0094) */
#define UC_L1S_CC_U0095                          0x0095 0  /* U+0095 (Cc_U0095) */
#define UC_L1S_CC_U0096                          0x0096 0  /* U+0096 (Cc_U0096) */
#define UC_L1S_CC_U0097                          0x0097 0  /* U+0097 (Cc_U0097) */
#define UC_L1S_CC_U0098                          0x0098 0  /* U+0098 (Cc_U0098) */
#define UC_L1S_CC_U0099                          0x0099 0  /* U+0099 (Cc_U0099) */
#define UC_L1S_CC_U009A                          0x009A 0  /* U+009A (Cc_U009A) */
#define UC_L1S_CC_U009B                          0x009B 0  /* U+009B (Cc_U009B) */
#define UC_L1S_CC_U009C                          0x009C 0  /* U+009C (Cc_U009C) */
#define UC_L1S_CC_U009D                          0x009D 0  /* U+009D (Cc_U009D) */
#define UC_L1S_CC_U009E                          0x009E 0  /* U+009E (Cc_U009E) */
#define UC_L1S_CC_U009F                          0x009F 0  /* U+009F (Cc_U009F) */
#define UC_L1S_NO_BREAK_SPACE                    0x00A0 0  /* U+00A0 (NO-BREAK SPACE) */
#define UC_L1S_INVERTED_EXCLAMATION_MARK         0x00A1 0  // ¡
#define UC_L1S_CENT_SIGN                         0x00A2 0  // ¢
#define UC_L1S_POUND_SIGN                        0x00A3 0  // £
#define UC_L1S_CURRENCY_SIGN                     0x00A4 0  // ¤
#define UC_L1S_YEN_SIGN                          0x00A5 0  // ¥
#define UC_L1S_BROKEN_BAR                        0x00A6 0  // ¦
#define UC_L1S_SECTION_SIGN                      0x00A7 0  // §
#define UC_L1S_DIAERESIS                         0x00A8 0  // ¨
#define UC_L1S_COPYRIGHT_SIGN                    0x00A9 0  // ©
#define UC_L1S_FEMININE_ORDINAL_INDICATOR        0x00AA 0  // ª
#define UC_L1S_LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK 0x00AB 0  // «
#define UC_L1S_NOT_SIGN                          0x00AC 0  // ¬
#define UC_L1S_SOFT_HYPHEN                       0x00AD 0  /* U+00AD (SOFT HYPHEN) */
#define UC_L1S_REGISTERED_SIGN                   0x00AE 0  // ®
#define UC_L1S_MACRON                            0x00AF 0  // ¯
#define UC_L1S_DEGREE_SIGN                       0x00B0 0  // °
#define UC_L1S_PLUS_MINUS_SIGN                   0x00B1 0  // ±
#define UC_L1S_SUPERSC_TWO                       0x00B2 0  // ²
#define UC_L1S_SUPERSC_THREE                     0x00B3 0  // ³
#define UC_L1S_ACUTE_ACCENT                      0x00B4 0  // ´
#define UC_L1S_MICRO_SIGN                        0x00B5 0x039C  // µ/Μ
#define UC_L1S_PILCROW_SIGN                      0x00B6 0  // ¶
#define UC_L1S_MIDDLE_DOT                        0x00B7 0  // ·
#define UC_L1S_CEDILLA                           0x00B8 0  // ¸
#define UC_L1S_SUPERSC_ONE                       0x00B9 0  // ¹
#define UC_L1S_MASCULINE_ORDINAL_INDICATOR       0x00BA 0  // º
#define UC_L1S_RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK 0x00BB 0  // »
#define UC_L1S_VULGAR_FRACTION_ONE_QUARTER       0x00BC 0  // ¼
#define UC_L1S_VULGAR_FRACTION_ONE_HALF          0x00BD 0  // ½
#define UC_L1S_VULGAR_FRACTION_THREE_QUARTERS    0x00BE 0  // ¾
#define UC_L1S_INVERTED_QUESTION_MARK            0x00BF 0  // ¿
#define UC_L1S_MULTIPLICATION_SIGN               0x00D7 0  // ×
#define UC_L1S_SMALL_SHARP_S                     0x00DF 0  // ß
#define UC_L1S_A_GRAVE                           0x00E0 0x00C0  // à/À
#define UC_L1S_A_ACUTE                           0x00E1 0x00C1  // á/Á
#define UC_L1S_A_CIRCUMFLEX                      0x00E2 0x00C2  // â/Â
#define UC_L1S_A_TILDE                           0x00E3 0x00C3  // ã/Ã
#define UC_L1S_A_DIAERESIS                       0x00E4 0x00C4  // ä/Ä
#define UC_L1S_A_RING_ABOVE                      0x00E5 0x00C5  // å/Å
#define UC_L1S_AE                                0x00E6 0x00C6  // æ/Æ
#define UC_L1S_C_CEDILLA                         0x00E7 0x00C7  // ç/Ç
#define UC_L1S_E_GRAVE                           0x00E8 0x00C8  // è/È
#define UC_L1S_E_ACUTE                           0x00E9 0x00C9  // é/É
#define UC_L1S_E_CIRCUMFLEX                      0x00EA 0x00CA  // ê/Ê
#define UC_L1S_E_DIAERESIS                       0x00EB 0x00CB  // ë/Ë
#define UC_L1S_I_GRAVE                           0x00EC 0x00CC  // ì/Ì
#define UC_L1S_I_ACUTE                           0x00ED 0x00CD  // í/Í
#define UC_L1S_I_CIRCUMFLEX                      0x00EE 0x00CE  // î/Î
#define UC_L1S_I_DIAERESIS                       0x00EF 0x00CF  // ï/Ï
#define UC_L1S_ETH                               0x00F0 0x00D0  // ð/Ð
#define UC_L1S_N_TILDE                           0x00F1 0x00D1  // ñ/Ñ
#define UC_L1S_O_GRAVE                           0x00F2 0x00D2  // ò/Ò
#define UC_L1S_O_ACUTE                           0x00F3 0x00D3  // ó/Ó
#define UC_L1S_O_CIRCUMFLEX                      0x00F4 0x00D4  // ô/Ô
#define UC_L1S_O_TILDE                           0x00F5 0x00D5  // õ/Õ
#define UC_L1S_O_DIAERESIS                       0x00F6 0x00D6  // ö/Ö
#define UC_L1S_DIVISION_SIGN                     0x00F7 0  // ÷
#define UC_L1S_O_STROKE                          0x00F8 0x00D8  // ø/Ø
#define UC_L1S_U_GRAVE                           0x00F9 0x00D9  // ù/Ù
#define UC_L1S_U_ACUTE                           0x00FA 0x00DA  // ú/Ú
#define UC_L1S_U_CIRCUMFLEX                      0x00FB 0x00DB  // û/Û
#define UC_L1S_U_DIAERESIS                       0x00FC 0x00DC  // ü/Ü
#define UC_L1S_Y_ACUTE                           0x00FD 0x00DD  // ý/Ý
#define UC_L1S_THORN                             0x00FE 0x00DE  // þ/Þ
#define UC_L1S_Y_DIAERESIS                       0x00FF 0x0178  // ÿ/Ÿ
