/* latin_extended_f.h – Unicode constants for U+107B2 … U+107BA
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_UC_MODIFIER_SMALL_CAPITAL_Y           0x107B2 0  // 𐞲
#define UC_UC_MODIFIER_GLOTTAL_STOP_WITH_STROKE  0x107B3 0  // 𐞳
#define UC_UC_MODIFIER_REVERSED_GLOTTAL_STOP_WITH_STROKE 0x107B4 0  // 𐞴
#define UC_UC_MODIFIER_BILABIAL_CLICK            0x107B5 0  // 𐞵
#define UC_UC_MODIFIER_DENTAL_CLICK              0x107B6 0  // 𐞶
#define UC_UC_MODIFIER_LATERAL_CLICK             0x107B7 0  // 𐞷
#define UC_UC_MODIFIER_ALVEOLAR_CLICK            0x107B8 0  // 𐞸
#define UC_UC_MODIFIER_RETROFLEX_CLICK_WITH_RETROFLEX_HOOK 0x107B9 0  // 𐞹
#define UC_UC_MODIFIER_SMALL_S_WITH_CURL         0x107BA 0  // 𐞺
