/* latin_extended_g.h – Unicode constants for U+1DF00 … U+1DFFF
*
* Generated by generate_unicode_headers.py
* Defined Code Points: 37
* Total Hex Codes: 37
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_SMALL_FENG_DIGRAPH_TRILL              0x1DF00 0  // 𝼀
#define UC_SMALL_REVERSED_SC_G                   0x1DF01 0  // 𝼁
#define UC_SMALL_CAPITAL_TURNED_G                0x1DF02 0  // 𝼂
#define UC_SMALL_REVERSED_K                      0x1DF03 0  // 𝼃
#define UC_SMALL_CAPITAL_L_BELT                  0x1DF04 0  // 𝼄
#define UC_SMALL_LEZH_RETROFLEX_HOOK             0x1DF05 0  // 𝼅
#define UC_SMALL_TURNED_Y_BELT                   0x1DF06 0  // 𝼆
#define UC_SMALL_REVERSED_ENG                    0x1DF07 0  // 𝼇
#define UC_SMALL_TURNED_R_LONG_LEG_AND_RETROFLEX_HOOK 0x1DF08 0  // 𝼈
#define UC_SMALL_T_HOOK_AND_RETROFLEX_HOOK       0x1DF09 0  // 𝼉
#define UC_RETROFLEX_CLICK_RETROFLEX_HOOK        0x1DF0A 0  // 𝼊
#define UC_SMALL_ESH_DOUBLE_BAR                  0x1DF0B 0  // 𝼋
#define UC_SMALL_ESH_DOUBLE_BAR_AND_CURL         0x1DF0C 0  // 𝼌
#define UC_SMALL_TURNED_T_CURL                   0x1DF0D 0  // 𝼍
#define UC_INVERTED_GLOTTAL_STOP_CURL            0x1DF0E 0  // 𝼎
#define UC_STRETCHED_C_CURL                      0x1DF0F 0  // 𝼏
#define UC_SMALL_CAPITAL_TURNED_K                0x1DF10 0  // 𝼐
#define UC_SMALL_L_FISHHOOK                      0x1DF11 0  // 𝼑
#define UC_SMALL_DEZH_DIGRAPH_PALATAL_HOOK       0x1DF12 0  // 𝼒
#define UC_SMALL_L_BELT_AND_PALATAL_HOOK         0x1DF13 0  // 𝼓
#define UC_SMALL_ENG_PALATAL_HOOK                0x1DF14 0  // 𝼔
#define UC_SMALL_TURNED_R_PALATAL_HOOK           0x1DF15 0  // 𝼕
#define UC_SMALL_R_FISHHOOK_AND_PALATAL_HOOK     0x1DF16 0  // 𝼖
#define UC_SMALL_TESH_DIGRAPH_PALATAL_HOOK       0x1DF17 0  // 𝼗
#define UC_SMALL_EZH_PALATAL_HOOK                0x1DF18 0  // 𝼘
#define UC_SMALL_DEZH_DIGRAPH_RETROFLEX_HOOK     0x1DF19 0  // 𝼙
#define UC_SMALL_I_STROKE_AND_RETROFLEX_HOOK     0x1DF1A 0  // 𝼚
#define UC_SMALL_O_RETROFLEX_HOOK                0x1DF1B 0  // 𝼛
#define UC_SMALL_TESH_DIGRAPH_RETROFLEX_HOOK     0x1DF1C 0  // 𝼜
#define UC_SMALL_C_RETROFLEX_HOOK                0x1DF1D 0  // 𝼝
#define UC_SMALL_S_CURL                          0x1DF1E 0  // 𝼞
#define UC_SMALL_D_MID_HEIGHT_LEFT_HOOK          0x1DF25 0  // 𝼥
#define UC_SMALL_L_MID_HEIGHT_LEFT_HOOK          0x1DF26 0  // 𝼦
#define UC_SMALL_N_MID_HEIGHT_LEFT_HOOK          0x1DF27 0  // 𝼧
#define UC_SMALL_R_MID_HEIGHT_LEFT_HOOK          0x1DF28 0  // 𝼨
#define UC_SMALL_S_MID_HEIGHT_LEFT_HOOK          0x1DF29 0  // 𝼩
#define UC_SMALL_T_MID_HEIGHT_LEFT_HOOK          0x1DF2A 0  // 𝼪
