/* Lisu Supplement.h – Unicode constants for U+11FB0 … U+11FBF
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_LISU_LETTER_YHA                       0x11FB0   /* U+11FB0 (LISU LETTER YHA) 𑾰 */
#define UC_UNKNOWN_11FB1                         0x11FB1   /* U+11FB1 (UNKNOWN_11FB1) */
#define UC_UNKNOWN_11FB2                         0x11FB2   /* U+11FB2 (UNKNOWN_11FB2) */
#define UC_UNKNOWN_11FB3                         0x11FB3   /* U+11FB3 (UNKNOWN_11FB3) */
#define UC_UNKNOWN_11FB4                         0x11FB4   /* U+11FB4 (UNKNOWN_11FB4) */
#define UC_UNKNOWN_11FB5                         0x11FB5   /* U+11FB5 (UNKNOWN_11FB5) */
#define UC_UNKNOWN_11FB6                         0x11FB6   /* U+11FB6 (UNKNOWN_11FB6) */
#define UC_UNKNOWN_11FB7                         0x11FB7   /* U+11FB7 (UNKNOWN_11FB7) */
#define UC_UNKNOWN_11FB8                         0x11FB8   /* U+11FB8 (UNKNOWN_11FB8) */
#define UC_UNKNOWN_11FB9                         0x11FB9   /* U+11FB9 (UNKNOWN_11FB9) */
#define UC_UNKNOWN_11FBA                         0x11FBA   /* U+11FBA (UNKNOWN_11FBA) */
#define UC_UNKNOWN_11FBB                         0x11FBB   /* U+11FBB (UNKNOWN_11FBB) */
#define UC_UNKNOWN_11FBC                         0x11FBC   /* U+11FBC (UNKNOWN_11FBC) */
#define UC_UNKNOWN_11FBD                         0x11FBD   /* U+11FBD (UNKNOWN_11FBD) */
#define UC_UNKNOWN_11FBE                         0x11FBE   /* U+11FBE (UNKNOWN_11FBE) */
#define UC_UNKNOWN_11FBF                         0x11FBF   /* U+11FBF (UNKNOWN_11FBF) */
