/* lydian.h – Unicode constants for U+10920 … U+1093F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_LYDIAN_A                              0x10920 0  // 𐤠
#define UC_LYDIAN_B                              0x10921 0  // 𐤡
#define UC_LYDIAN_G                              0x10922 0  // 𐤢
#define UC_LYDIAN_D                              0x10923 0  // 𐤣
#define UC_LYDIAN_E                              0x10924 0  // 𐤤
#define UC_LYDIAN_V                              0x10925 0  // 𐤥
#define UC_LYDIAN_I                              0x10926 0  // 𐤦
#define UC_LYDIAN_Y                              0x10927 0  // 𐤧
#define UC_LYDIAN_K                              0x10928 0  // 𐤨
#define UC_LYDIAN_L                              0x10929 0  // 𐤩
#define UC_LYDIAN_M                              0x1092A 0  // 𐤪
#define UC_LYDIAN_N                              0x1092B 0  // 𐤫
#define UC_LYDIAN_O                              0x1092C 0  // 𐤬
#define UC_LYDIAN_R                              0x1092D 0  // 𐤭
#define UC_LYDIAN_SS                             0x1092E 0  // 𐤮
#define UC_LYDIAN_T                              0x1092F 0  // 𐤯
#define UC_LYDIAN_U                              0x10930 0  // 𐤰
#define UC_LYDIAN_F                              0x10931 0  // 𐤱
#define UC_LYDIAN_Q                              0x10932 0  // 𐤲
#define UC_LYDIAN_S                              0x10933 0  // 𐤳
#define UC_LYDIAN_TT                             0x10934 0  // 𐤴
#define UC_LYDIAN_AN                             0x10935 0  // 𐤵
#define UC_LYDIAN_EN                             0x10936 0  // 𐤶
#define UC_LYDIAN_LY                             0x10937 0  // 𐤷
#define UC_LYDIAN_NN                             0x10938 0  // 𐤸
#define UC_LYDIAN_C                              0x10939 0  // 𐤹
#define UC_LYDIAN_TRIANGULAR_MARK                0x1093F 0  // 𐤿
