/* mahajani.h – Unicode constants for U+11150 … U+1117F
*
* Generated by generate_unicode_headers.py (Unicode 17.0.0)
*
* Source data for blocks: Blocks.txt (Unicode 17.0.0)
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_MAHAJANI_A                            0x11150 0  // 𑅐
#define UC_MAHAJANI_I                            0x11151 0  // 𑅑
#define UC_MAHAJANI_U                            0x11152 0  // 𑅒
#define UC_MAHAJANI_E                            0x11153 0  // 𑅓
#define UC_MAHAJANI_O                            0x11154 0  // 𑅔
#define UC_MAHAJANI_KA                           0x11155 0  // 𑅕
#define UC_MAHAJANI_KHA                          0x11156 0  // 𑅖
#define UC_MAHAJANI_GA                           0x11157 0  // 𑅗
#define UC_MAHAJANI_GHA                          0x11158 0  // 𑅘
#define UC_MAHAJANI_CA                           0x11159 0  // 𑅙
#define UC_MAHAJANI_CHA                          0x1115A 0  // 𑅚
#define UC_MAHAJANI_JA                           0x1115B 0  // 𑅛
#define UC_MAHAJANI_JHA                          0x1115C 0  // 𑅜
#define UC_MAHAJANI_NYA                          0x1115D 0  // 𑅝
#define UC_MAHAJANI_TTA                          0x1115E 0  // 𑅞
#define UC_MAHAJANI_TTHA                         0x1115F 0  // 𑅟
#define UC_MAHAJANI_DDA                          0x11160 0  // 𑅠
#define UC_MAHAJANI_DDHA                         0x11161 0  // 𑅡
#define UC_MAHAJANI_NNA                          0x11162 0  // 𑅢
#define UC_MAHAJANI_TA                           0x11163 0  // 𑅣
#define UC_MAHAJANI_THA                          0x11164 0  // 𑅤
#define UC_MAHAJANI_DA                           0x11165 0  // 𑅥
#define UC_MAHAJANI_DHA                          0x11166 0  // 𑅦
#define UC_MAHAJANI_NA                           0x11167 0  // 𑅧
#define UC_MAHAJANI_PA                           0x11168 0  // 𑅨
#define UC_MAHAJANI_PHA                          0x11169 0  // 𑅩
#define UC_MAHAJANI_BA                           0x1116A 0  // 𑅪
#define UC_MAHAJANI_BHA                          0x1116B 0  // 𑅫
#define UC_MAHAJANI_MA                           0x1116C 0  // 𑅬
#define UC_MAHAJANI_RA                           0x1116D 0  // 𑅭
#define UC_MAHAJANI_LA                           0x1116E 0  // 𑅮
#define UC_MAHAJANI_VA                           0x1116F 0  // 𑅯
#define UC_MAHAJANI_SA                           0x11170 0  // 𑅰
#define UC_MAHAJANI_HA                           0x11171 0  // 𑅱
#define UC_MAHAJANI_RRA                          0x11172 0  // 𑅲
#define UC_MAHAJANI_SIGN_NUKTA                   0x11173 0  // 𑅳
#define UC_MAHAJANI_ABBREVIATION_SIGN            0x11174 0  // 𑅴
#define UC_MAHAJANI_SECTION_MARK                 0x11175 0  // 𑅵
#define UC_MAHAJANI_LIGATURE_SHRI                0x11176 0  // 𑅶
