/* Mandaic.h – Unicode constants for U+085E … U+085E
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_MANDAIC_PUNCTUATION                   0x085E 0  // ࡞
