/* mandaic.h – Unicode constants for U+0840 … U+085F
*
* Generated by generate_unicode_headers.py (Unicode 17.0.0)
*
* Source data for blocks: Blocks.txt (Unicode 17.0.0)
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_MANDAIC_HALQA                         0x0840 0  // ࡀ
#define UC_MANDAIC_AB                            0x0841 0  // ࡁ
#define UC_MANDAIC_AG                            0x0842 0  // ࡂ
#define UC_MANDAIC_AD                            0x0843 0  // ࡃ
#define UC_MANDAIC_AH                            0x0844 0  // ࡄ
#define UC_MANDAIC_USHENNA                       0x0845 0  // ࡅ
#define UC_MANDAIC_AZ                            0x0846 0  // ࡆ
#define UC_MANDAIC_IT                            0x0847 0  // ࡇ
#define UC_MANDAIC_ATT                           0x0848 0  // ࡈ
#define UC_MANDAIC_AKSA                          0x0849 0  // ࡉ
#define UC_MANDAIC_AK                            0x084A 0  // ࡊ
#define UC_MANDAIC_AL                            0x084B 0  // ࡋ
#define UC_MANDAIC_AM                            0x084C 0  // ࡌ
#define UC_MANDAIC_AN                            0x084D 0  // ࡍ
#define UC_MANDAIC_AS                            0x084E 0  // ࡎ
#define UC_MANDAIC_IN                            0x084F 0  // ࡏ
#define UC_MANDAIC_AP                            0x0850 0  // ࡐ
#define UC_MANDAIC_ASZ                           0x0851 0  // ࡑ
#define UC_MANDAIC_AQ                            0x0852 0  // ࡒ
#define UC_MANDAIC_AR                            0x0853 0  // ࡓ
#define UC_MANDAIC_ASH                           0x0854 0  // ࡔ
#define UC_MANDAIC_AT                            0x0855 0  // ࡕ
#define UC_MANDAIC_DUSHENNA                      0x0856 0  // ࡖ
#define UC_MANDAIC_KAD                           0x0857 0  // ࡗ
#define UC_MANDAIC_AIN                           0x0858 0  // ࡘ
#define UC_MANDAIC_AFFRICATION_MARK              0x0859 0  // ࡙
#define UC_MANDAIC_VOCALIZATION_MARK             0x085A 0  // ࡚
#define UC_MANDAIC_GEMINATION_MARK               0x085B 0  // ࡛
#define UC_MANDAIC_PUNCTUATION                   0x085E 0  // ࡞
