/* manichaean.h – Unicode constants for U+10AC0 … U+10AFF
*
* Generated by generate_unicode_headers.py
* Defined Code Points: 51
* Total Hex Codes: 51
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_MANICHAEAN_ALEPH                      0x10AC0 0  // 𐫀
#define UC_MANICHAEAN_BETH                       0x10AC1 0  // 𐫁
#define UC_MANICHAEAN_BHETH                      0x10AC2 0  // 𐫂
#define UC_MANICHAEAN_GIMEL                      0x10AC3 0  // 𐫃
#define UC_MANICHAEAN_GHIMEL                     0x10AC4 0  // 𐫄
#define UC_MANICHAEAN_DALETH                     0x10AC5 0  // 𐫅
#define UC_MANICHAEAN_HE                         0x10AC6 0  // 𐫆
#define UC_MANICHAEAN_WAW                        0x10AC7 0  // 𐫇
#define UC_MANICHAEAN_SIGN_UD                    0x10AC8 0  // 𐫈
#define UC_MANICHAEAN_ZAYIN                      0x10AC9 0  // 𐫉
#define UC_MANICHAEAN_ZHAYIN                     0x10ACA 0  // 𐫊
#define UC_MANICHAEAN_JAYIN                      0x10ACB 0  // 𐫋
#define UC_MANICHAEAN_JHAYIN                     0x10ACC 0  // 𐫌
#define UC_MANICHAEAN_HETH                       0x10ACD 0  // 𐫍
#define UC_MANICHAEAN_TETH                       0x10ACE 0  // 𐫎
#define UC_MANICHAEAN_YODH                       0x10ACF 0  // 𐫏
#define UC_MANICHAEAN_KAPH                       0x10AD0 0  // 𐫐
#define UC_MANICHAEAN_XAPH                       0x10AD1 0  // 𐫑
#define UC_MANICHAEAN_KHAPH                      0x10AD2 0  // 𐫒
#define UC_MANICHAEAN_LAMEDH                     0x10AD3 0  // 𐫓
#define UC_MANICHAEAN_DHAMEDH                    0x10AD4 0  // 𐫔
#define UC_MANICHAEAN_THAMEDH                    0x10AD5 0  // 𐫕
#define UC_MANICHAEAN_MEM                        0x10AD6 0  // 𐫖
#define UC_MANICHAEAN_NUN                        0x10AD7 0  // 𐫗
#define UC_MANICHAEAN_SAMEKH                     0x10AD8 0  // 𐫘
#define UC_MANICHAEAN_AYIN                       0x10AD9 0  // 𐫙
#define UC_MANICHAEAN_AAYIN                      0x10ADA 0  // 𐫚
#define UC_MANICHAEAN_PE                         0x10ADB 0  // 𐫛
#define UC_MANICHAEAN_FE                         0x10ADC 0  // 𐫜
#define UC_MANICHAEAN_SADHE                      0x10ADD 0  // 𐫝
#define UC_MANICHAEAN_QOPH                       0x10ADE 0  // 𐫞
#define UC_MANICHAEAN_XOPH                       0x10ADF 0  // 𐫟
#define UC_MANICHAEAN_QHOPH                      0x10AE0 0  // 𐫠
#define UC_MANICHAEAN_RESH                       0x10AE1 0  // 𐫡
#define UC_MANICHAEAN_SHIN                       0x10AE2 0  // 𐫢
#define UC_MANICHAEAN_SSHIN                      0x10AE3 0  // 𐫣
#define UC_MANICHAEAN_TAW                        0x10AE4 0  // 𐫤
#define UC_MANICHAEAN_ABBREVIATION_MARK_ABOVE    0x10AE5 0  // 𐫥
#define UC_MANICHAEAN_ABBREVIATION_MARK_BELOW    0x10AE6 0  // 𐫦
#define UC_MANICHAEAN_ONE                        0x10AEB 0  // 𐫫
#define UC_MANICHAEAN_FIVE                       0x10AEC 0  // 𐫬
#define UC_MANICHAEAN_TEN                        0x10AED 0  // 𐫭
#define UC_MANICHAEAN_TWENTY                     0x10AEE 0  // 𐫮
#define UC_MANICHAEAN_ONE_HUNDRED                0x10AEF 0  // 𐫯
#define UC_MANICHAEAN_PUNCTUATION_STAR           0x10AF0 0  // 𐫰
#define UC_MANICHAEAN_PUNCTUATION_FLEURON        0x10AF1 0  // 𐫱
#define UC_MANICHAEAN_PUNCTUATION_DOUBLE_DOT_WITHIN_DOT 0x10AF2 0  // 𐫲
#define UC_MANICHAEAN_PUNCTUATION_DOT_WITHIN_DOT 0x10AF3 0  // 𐫳
#define UC_MANICHAEAN_PUNCTUATION_DOT            0x10AF4 0  // 𐫴
#define UC_MANICHAEAN_PUNCTUATION_TWO_DOTS       0x10AF5 0  // 𐫵
#define UC_MANICHAEAN_PUNCTUATION_LINE_FILLER    0x10AF6 0  // 𐫶
