/* Meetei Mayek Extensions.h – Unicode constants for U+AAE0 … U+AAFF
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_MEETEI_MAYEK_LETTER_E                 0xAAE0   /* U+AAE0 (MEETEI MAYEK LETTER E) ꫠ */
#define UC_MEETEI_MAYEK_LETTER_O                 0xAAE1   /* U+AAE1 (MEETEI MAYEK LETTER O) ꫡ */
#define UC_MEETEI_MAYEK_LETTER_CHA               0xAAE2   /* U+AAE2 (MEETEI MAYEK LETTER CHA) ꫢ */
#define UC_MEETEI_MAYEK_LETTER_NYA               0xAAE3   /* U+AAE3 (MEETEI MAYEK LETTER NYA) ꫣ */
#define UC_MEETEI_MAYEK_LETTER_TTA               0xAAE4   /* U+AAE4 (MEETEI MAYEK LETTER TTA) ꫤ */
#define UC_MEETEI_MAYEK_LETTER_TTHA              0xAAE5   /* U+AAE5 (MEETEI MAYEK LETTER TTHA) ꫥ */
#define UC_MEETEI_MAYEK_LETTER_DDA               0xAAE6   /* U+AAE6 (MEETEI MAYEK LETTER DDA) ꫦ */
#define UC_MEETEI_MAYEK_LETTER_DDHA              0xAAE7   /* U+AAE7 (MEETEI MAYEK LETTER DDHA) ꫧ */
#define UC_MEETEI_MAYEK_LETTER_NNA               0xAAE8   /* U+AAE8 (MEETEI MAYEK LETTER NNA) ꫨ */
#define UC_MEETEI_MAYEK_LETTER_SHA               0xAAE9   /* U+AAE9 (MEETEI MAYEK LETTER SHA) ꫩ */
#define UC_MEETEI_MAYEK_LETTER_SSA               0xAAEA   /* U+AAEA (MEETEI MAYEK LETTER SSA) ꫪ */
#define UC_MEETEI_MAYEK_VOWEL_SIGN_II            0xAAEB   /* U+AAEB (MEETEI MAYEK VOWEL SIGN II) ꫫ */
#define UC_MEETEI_MAYEK_VOWEL_SIGN_UU            0xAAEC   /* U+AAEC (MEETEI MAYEK VOWEL SIGN UU) ꫬ */
#define UC_MEETEI_MAYEK_VOWEL_SIGN_AAI           0xAAED   /* U+AAED (MEETEI MAYEK VOWEL SIGN AAI) ꫭ */
#define UC_MEETEI_MAYEK_VOWEL_SIGN_AU            0xAAEE   /* U+AAEE (MEETEI MAYEK VOWEL SIGN AU) ꫮ */
#define UC_MEETEI_MAYEK_VOWEL_SIGN_AAU           0xAAEF   /* U+AAEF (MEETEI MAYEK VOWEL SIGN AAU) ꫯ */
#define UC_MEETEI_MAYEK_CHEIKHAN                 0xAAF0   /* U+AAF0 (MEETEI MAYEK CHEIKHAN) ꫰ */
#define UC_MEETEI_MAYEK_AHANG_KHUDAM             0xAAF1   /* U+AAF1 (MEETEI MAYEK AHANG KHUDAM) ꫱ */
#define UC_MEETEI_MAYEK_ANJI                     0xAAF2   /* U+AAF2 (MEETEI MAYEK ANJI) ꫲ */
#define UC_MEETEI_MAYEK_SYLLABLE_REPETITION_MARK 0xAAF3   /* U+AAF3 (MEETEI MAYEK SYLLABLE REPETITION MARK) ꫳ */
#define UC_MEETEI_MAYEK_WORD_REPETITION_MARK     0xAAF4   /* U+AAF4 (MEETEI MAYEK WORD REPETITION MARK) ꫴ */
#define UC_MEETEI_MAYEK_VOWEL_SIGN_VISARGA       0xAAF5   /* U+AAF5 (MEETEI MAYEK VOWEL SIGN VISARGA) ꫵ */
#define UC_MEETEI_MAYEK_VIRAMA                   0xAAF6   /* U+AAF6 (MEETEI MAYEK VIRAMA) ꫶ */
#define UC_UNKNOWN_AAF7                          0xAAF7   /* U+AAF7 (UNKNOWN_AAF7) */
#define UC_UNKNOWN_AAF8                          0xAAF8   /* U+AAF8 (UNKNOWN_AAF8) */
#define UC_UNKNOWN_AAF9                          0xAAF9   /* U+AAF9 (UNKNOWN_AAF9) */
#define UC_UNKNOWN_AAFA                          0xAAFA   /* U+AAFA (UNKNOWN_AAFA) */
#define UC_UNKNOWN_AAFB                          0xAAFB   /* U+AAFB (UNKNOWN_AAFB) */
#define UC_UNKNOWN_AAFC                          0xAAFC   /* U+AAFC (UNKNOWN_AAFC) */
#define UC_UNKNOWN_AAFD                          0xAAFD   /* U+AAFD (UNKNOWN_AAFD) */
#define UC_UNKNOWN_AAFE                          0xAAFE   /* U+AAFE (UNKNOWN_AAFE) */
#define UC_UNKNOWN_AAFF                          0xAAFF   /* U+AAFF (UNKNOWN_AAFF) */
