/* meetei_mayek_extensions.h – Unicode constants for U+AAE0 … U+AAFF
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_MEETEI_MAYEK_E                        0xAAE0 0  // ꫠ
#define UC_MEETEI_MAYEK_O                        0xAAE1 0  // ꫡ
#define UC_MEETEI_MAYEK_CHA                      0xAAE2 0  // ꫢ
#define UC_MEETEI_MAYEK_NYA                      0xAAE3 0  // ꫣ
#define UC_MEETEI_MAYEK_TTA                      0xAAE4 0  // ꫤ
#define UC_MEETEI_MAYEK_TTHA                     0xAAE5 0  // ꫥ
#define UC_MEETEI_MAYEK_DDA                      0xAAE6 0  // ꫦ
#define UC_MEETEI_MAYEK_DDHA                     0xAAE7 0  // ꫧ
#define UC_MEETEI_MAYEK_NNA                      0xAAE8 0  // ꫨ
#define UC_MEETEI_MAYEK_SHA                      0xAAE9 0  // ꫩ
#define UC_MEETEI_MAYEK_SSA                      0xAAEA 0  // ꫪ
#define UC_MEETEI_MAYEK_VOWEL_SIGN_II            0xAAEB 0  // ꫫ
#define UC_MEETEI_MAYEK_VOWEL_SIGN_UU            0xAAEC 0  // ꫬ
#define UC_MEETEI_MAYEK_VOWEL_SIGN_AAI           0xAAED 0  // ꫭ
#define UC_MEETEI_MAYEK_VOWEL_SIGN_AU            0xAAEE 0  // ꫮ
#define UC_MEETEI_MAYEK_VOWEL_SIGN_AAU           0xAAEF 0  // ꫯ
#define UC_MEETEI_MAYEK_CHEIKHAN                 0xAAF0 0  // ꫰
#define UC_MEETEI_MAYEK_AHANG_KHUDAM             0xAAF1 0  // ꫱
#define UC_MEETEI_MAYEK_ANJI                     0xAAF2 0  // ꫲ
#define UC_MEETEI_MAYEK_SYLLABLE_REPETITION_MARK 0xAAF3 0  // ꫳ
#define UC_MEETEI_MAYEK_WORD_REPETITION_MARK     0xAAF4 0  // ꫴ
#define UC_MEETEI_MAYEK_VOWEL_SIGN_VISARGA       0xAAF5 0  // ꫵ
#define UC_MEETEI_MAYEK_VIRAMA                   0xAAF6 0  // ꫶
