/* Miscellaneous Symbols Supplement.h – Unicode constants for U+1CEC0 … U+1CEFF
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_HEBE                                  0x1CEC0   /* U+1CEC0 (HEBE) */
#define UC_IRIS                                  0x1CEC1   /* U+1CEC1 (IRIS) */
#define UC_FLORA                                 0x1CEC2   /* U+1CEC2 (FLORA) */
#define UC_METIS                                 0x1CEC3   /* U+1CEC3 (METIS) */
#define UC_PARTHENOPE                            0x1CEC4   /* U+1CEC4 (PARTHENOPE) */
#define UC_VICTORIA                              0x1CEC5   /* U+1CEC5 (VICTORIA) */
#define UC_EGERIA                                0x1CEC6   /* U+1CEC6 (EGERIA) */
#define UC_IRENE                                 0x1CEC7   /* U+1CEC7 (IRENE) */
#define UC_EUNOMIA                               0x1CEC8   /* U+1CEC8 (EUNOMIA) */
#define UC_PSYCHE                                0x1CEC9   /* U+1CEC9 (PSYCHE) */
#define UC_THETIS                                0x1CECA   /* U+1CECA (THETIS) */
#define UC_MELPOMENE                             0x1CECB   /* U+1CECB (MELPOMENE) */
#define UC_FORTUNA                               0x1CECC   /* U+1CECC (FORTUNA) */
#define UC_ASTRONOMICAL_SYMBOL_FOR_ASTEROID_PROSERPINA 0x1CECD   /* U+1CECD (ASTRONOMICAL SYMBOL FOR ASTEROID PROSERPINA) */
#define UC_BELLONA                               0x1CECE   /* U+1CECE (BELLONA) */
#define UC_AMPHITRITE                            0x1CECF   /* U+1CECF (AMPHITRITE) */
#define UC_LEUKOTHEA                             0x1CED0   /* U+1CED0 (LEUKOTHEA) */
#define UC_UNKNOWN_1CED1                         0x1CED1   /* U+1CED1 (UNKNOWN_1CED1) */
#define UC_UNKNOWN_1CED2                         0x1CED2   /* U+1CED2 (UNKNOWN_1CED2) */
#define UC_UNKNOWN_1CED3                         0x1CED3   /* U+1CED3 (UNKNOWN_1CED3) */
#define UC_UNKNOWN_1CED4                         0x1CED4   /* U+1CED4 (UNKNOWN_1CED4) */
#define UC_UNKNOWN_1CED5                         0x1CED5   /* U+1CED5 (UNKNOWN_1CED5) */
#define UC_UNKNOWN_1CED6                         0x1CED6   /* U+1CED6 (UNKNOWN_1CED6) */
#define UC_UNKNOWN_1CED7                         0x1CED7   /* U+1CED7 (UNKNOWN_1CED7) */
#define UC_UNKNOWN_1CED8                         0x1CED8   /* U+1CED8 (UNKNOWN_1CED8) */
#define UC_UNKNOWN_1CED9                         0x1CED9   /* U+1CED9 (UNKNOWN_1CED9) */
#define UC_UNKNOWN_1CEDA                         0x1CEDA   /* U+1CEDA (UNKNOWN_1CEDA) */
#define UC_UNKNOWN_1CEDB                         0x1CEDB   /* U+1CEDB (UNKNOWN_1CEDB) */
#define UC_UNKNOWN_1CEDC                         0x1CEDC   /* U+1CEDC (UNKNOWN_1CEDC) */
#define UC_UNKNOWN_1CEDD                         0x1CEDD   /* U+1CEDD (UNKNOWN_1CEDD) */
#define UC_UNKNOWN_1CEDE                         0x1CEDE   /* U+1CEDE (UNKNOWN_1CEDE) */
#define UC_UNKNOWN_1CEDF                         0x1CEDF   /* U+1CEDF (UNKNOWN_1CEDF) */
#define UC_GEOMANTIC_FIGURE_POPULUS              0x1CEE0   /* U+1CEE0 (GEOMANTIC FIGURE POPULUS) */
#define UC_GEOMANTIC_FIGURE_TRISTITIA            0x1CEE1   /* U+1CEE1 (GEOMANTIC FIGURE TRISTITIA) */
#define UC_GEOMANTIC_FIGURE_ALBUS                0x1CEE2   /* U+1CEE2 (GEOMANTIC FIGURE ALBUS) */
#define UC_GEOMANTIC_FIGURE_FORTUNA_MAJOR        0x1CEE3   /* U+1CEE3 (GEOMANTIC FIGURE FORTUNA MAJOR) */
#define UC_GEOMANTIC_FIGURE_RUBEUS               0x1CEE4   /* U+1CEE4 (GEOMANTIC FIGURE RUBEUS) */
#define UC_GEOMANTIC_FIGURE_ACQUISITIO           0x1CEE5   /* U+1CEE5 (GEOMANTIC FIGURE ACQUISITIO) */
#define UC_GEOMANTIC_FIGURE_CONJUNCTIO           0x1CEE6   /* U+1CEE6 (GEOMANTIC FIGURE CONJUNCTIO) */
#define UC_GEOMANTIC_FIGURE_CAPUT_DRACONIS       0x1CEE7   /* U+1CEE7 (GEOMANTIC FIGURE CAPUT DRACONIS) */
#define UC_GEOMANTIC_FIGURE_LAETITIA             0x1CEE8   /* U+1CEE8 (GEOMANTIC FIGURE LAETITIA) */
#define UC_GEOMANTIC_FIGURE_CARCER               0x1CEE9   /* U+1CEE9 (GEOMANTIC FIGURE CARCER) */
#define UC_GEOMANTIC_FIGURE_AMISSIO              0x1CEEA   /* U+1CEEA (GEOMANTIC FIGURE AMISSIO) */
#define UC_GEOMANTIC_FIGURE_PUELLA               0x1CEEB   /* U+1CEEB (GEOMANTIC FIGURE PUELLA) */
#define UC_GEOMANTIC_FIGURE_FORTUNA_MINOR        0x1CEEC   /* U+1CEEC (GEOMANTIC FIGURE FORTUNA MINOR) */
#define UC_GEOMANTIC_FIGURE_PUER                 0x1CEED   /* U+1CEED (GEOMANTIC FIGURE PUER) */
#define UC_GEOMANTIC_FIGURE_CAUDA_DRACONIS       0x1CEEE   /* U+1CEEE (GEOMANTIC FIGURE CAUDA DRACONIS) */
#define UC_GEOMANTIC_FIGURE_VIA                  0x1CEEF   /* U+1CEEF (GEOMANTIC FIGURE VIA) */
#define UC_MEDIUM_SMALL_WHITE_CIRCLE_WITH_HORIZONTAL_BAR 0x1CEF0   /* U+1CEF0 (MEDIUM SMALL WHITE CIRCLE WITH HORIZONTAL BAR) */
#define UC_UNKNOWN_1CEF1                         0x1CEF1   /* U+1CEF1 (UNKNOWN_1CEF1) */
#define UC_UNKNOWN_1CEF2                         0x1CEF2   /* U+1CEF2 (UNKNOWN_1CEF2) */
#define UC_UNKNOWN_1CEF3                         0x1CEF3   /* U+1CEF3 (UNKNOWN_1CEF3) */
#define UC_UNKNOWN_1CEF4                         0x1CEF4   /* U+1CEF4 (UNKNOWN_1CEF4) */
#define UC_UNKNOWN_1CEF5                         0x1CEF5   /* U+1CEF5 (UNKNOWN_1CEF5) */
#define UC_UNKNOWN_1CEF6                         0x1CEF6   /* U+1CEF6 (UNKNOWN_1CEF6) */
#define UC_UNKNOWN_1CEF7                         0x1CEF7   /* U+1CEF7 (UNKNOWN_1CEF7) */
#define UC_UNKNOWN_1CEF8                         0x1CEF8   /* U+1CEF8 (UNKNOWN_1CEF8) */
#define UC_UNKNOWN_1CEF9                         0x1CEF9   /* U+1CEF9 (UNKNOWN_1CEF9) */
#define UC_UNKNOWN_1CEFA                         0x1CEFA   /* U+1CEFA (UNKNOWN_1CEFA) */
#define UC_UNKNOWN_1CEFB                         0x1CEFB   /* U+1CEFB (UNKNOWN_1CEFB) */
#define UC_UNKNOWN_1CEFC                         0x1CEFC   /* U+1CEFC (UNKNOWN_1CEFC) */
#define UC_UNKNOWN_1CEFD                         0x1CEFD   /* U+1CEFD (UNKNOWN_1CEFD) */
#define UC_UNKNOWN_1CEFE                         0x1CEFE   /* U+1CEFE (UNKNOWN_1CEFE) */
#define UC_UNKNOWN_1CEFF                         0x1CEFF   /* U+1CEFF (UNKNOWN_1CEFF) */
