/* mongolian_supplement.h – Unicode constants for U+11660 … U+1167F
*
* Generated by generate_unicode_headers.py
* Defined Code Points: 13
* Total Hex Codes: 13
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_MONGOLIAN_BIRGA_ORNAMENT              0x11660 0  // 𑙠
#define UC_MONGOLIAN_ROTATED_BIRGA               0x11661 0  // 𑙡
#define UC_MONGOLIAN_DOUBLE_BIRGA_ORNAMENT       0x11662 0  // 𑙢
#define UC_MONGOLIAN_TRIPLE_BIRGA_ORNAMENT       0x11663 0  // 𑙣
#define UC_MONGOLIAN_BIRGA_DOUBLE_ORNAMENT       0x11664 0  // 𑙤
#define UC_MONGOLIAN_ROTATED_BIRGA_ORNAMENT      0x11665 0  // 𑙥
#define UC_MONGOLIAN_ROTATED_BIRGA_DOUBLE_ORNAMENT 0x11666 0  // 𑙦
#define UC_MONGOLIAN_INVERTED_BIRGA              0x11667 0  // 𑙧
#define UC_MONGOLIAN_INVERTED_BIRGA_DOUBLE_ORNAMENT 0x11668 0  // 𑙨
#define UC_MONGOLIAN_SWIRL_BIRGA                 0x11669 0  // 𑙩
#define UC_MONGOLIAN_SWIRL_BIRGA_ORNAMENT        0x1166A 0  // 𑙪
#define UC_MONGOLIAN_SWIRL_BIRGA_DOUBLE_ORNAMENT 0x1166B 0  // 𑙫
#define UC_MONGOLIAN_TURNED_SWIRL_BIRGA_DOUBLE_ORNAMENT 0x1166C 0  // 𑙬
