/* Mro.h – Unicode constants for U+16A40 … U+16A6F
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_MRO_LETTER_TA                         0x16A40   /* U+16A40 (MRO LETTER TA) 𖩀 */
#define UC_MRO_LETTER_NGI                        0x16A41   /* U+16A41 (MRO LETTER NGI) 𖩁 */
#define UC_MRO_LETTER_YO                         0x16A42   /* U+16A42 (MRO LETTER YO) 𖩂 */
#define UC_MRO_LETTER_MIM                        0x16A43   /* U+16A43 (MRO LETTER MIM) 𖩃 */
#define UC_MRO_LETTER_BA                         0x16A44   /* U+16A44 (MRO LETTER BA) 𖩄 */
#define UC_MRO_LETTER_DA                         0x16A45   /* U+16A45 (MRO LETTER DA) 𖩅 */
#define UC_MRO_LETTER_A                          0x16A46   /* U+16A46 (MRO LETTER A) 𖩆 */
#define UC_MRO_LETTER_PHI                        0x16A47   /* U+16A47 (MRO LETTER PHI) 𖩇 */
#define UC_MRO_LETTER_KHAI                       0x16A48   /* U+16A48 (MRO LETTER KHAI) 𖩈 */
#define UC_MRO_LETTER_HAO                        0x16A49   /* U+16A49 (MRO LETTER HAO) 𖩉 */
#define UC_MRO_LETTER_DAI                        0x16A4A   /* U+16A4A (MRO LETTER DAI) 𖩊 */
#define UC_MRO_LETTER_CHU                        0x16A4B   /* U+16A4B (MRO LETTER CHU) 𖩋 */
#define UC_MRO_LETTER_KEAAE                      0x16A4C   /* U+16A4C (MRO LETTER KEAAE) 𖩌 */
#define UC_MRO_LETTER_OL                         0x16A4D   /* U+16A4D (MRO LETTER OL) 𖩍 */
#define UC_MRO_LETTER_MAEM                       0x16A4E   /* U+16A4E (MRO LETTER MAEM) 𖩎 */
#define UC_MRO_LETTER_NIN                        0x16A4F   /* U+16A4F (MRO LETTER NIN) 𖩏 */
#define UC_MRO_LETTER_PA                         0x16A50   /* U+16A50 (MRO LETTER PA) 𖩐 */
#define UC_MRO_LETTER_OO                         0x16A51   /* U+16A51 (MRO LETTER OO) 𖩑 */
#define UC_MRO_LETTER_O                          0x16A52   /* U+16A52 (MRO LETTER O) 𖩒 */
#define UC_MRO_LETTER_RO                         0x16A53   /* U+16A53 (MRO LETTER RO) 𖩓 */
#define UC_MRO_LETTER_SHI                        0x16A54   /* U+16A54 (MRO LETTER SHI) 𖩔 */
#define UC_MRO_LETTER_THEA                       0x16A55   /* U+16A55 (MRO LETTER THEA) 𖩕 */
#define UC_MRO_LETTER_EA                         0x16A56   /* U+16A56 (MRO LETTER EA) 𖩖 */
#define UC_MRO_LETTER_WA                         0x16A57   /* U+16A57 (MRO LETTER WA) 𖩗 */
#define UC_MRO_LETTER_E                          0x16A58   /* U+16A58 (MRO LETTER E) 𖩘 */
#define UC_MRO_LETTER_KO                         0x16A59   /* U+16A59 (MRO LETTER KO) 𖩙 */
#define UC_MRO_LETTER_LAN                        0x16A5A   /* U+16A5A (MRO LETTER LAN) 𖩚 */
#define UC_MRO_LETTER_LA                         0x16A5B   /* U+16A5B (MRO LETTER LA) 𖩛 */
#define UC_MRO_LETTER_HAI                        0x16A5C   /* U+16A5C (MRO LETTER HAI) 𖩜 */
#define UC_MRO_LETTER_RI                         0x16A5D   /* U+16A5D (MRO LETTER RI) 𖩝 */
#define UC_MRO_LETTER_TEK                        0x16A5E   /* U+16A5E (MRO LETTER TEK) 𖩞 */
#define UC_UNKNOWN_16A5F                         0x16A5F   /* U+16A5F (UNKNOWN_16A5F) */
#define UC_MRO_DIGIT_ZERO                        0x16A60   /* U+16A60 (MRO DIGIT ZERO) 𖩠 */
#define UC_MRO_DIGIT_ONE                         0x16A61   /* U+16A61 (MRO DIGIT ONE) 𖩡 */
#define UC_MRO_DIGIT_TWO                         0x16A62   /* U+16A62 (MRO DIGIT TWO) 𖩢 */
#define UC_MRO_DIGIT_THREE                       0x16A63   /* U+16A63 (MRO DIGIT THREE) 𖩣 */
#define UC_MRO_DIGIT_FOUR                        0x16A64   /* U+16A64 (MRO DIGIT FOUR) 𖩤 */
#define UC_MRO_DIGIT_FIVE                        0x16A65   /* U+16A65 (MRO DIGIT FIVE) 𖩥 */
#define UC_MRO_DIGIT_SIX                         0x16A66   /* U+16A66 (MRO DIGIT SIX) 𖩦 */
#define UC_MRO_DIGIT_SEVEN                       0x16A67   /* U+16A67 (MRO DIGIT SEVEN) 𖩧 */
#define UC_MRO_DIGIT_EIGHT                       0x16A68   /* U+16A68 (MRO DIGIT EIGHT) 𖩨 */
#define UC_MRO_DIGIT_NINE                        0x16A69   /* U+16A69 (MRO DIGIT NINE) 𖩩 */
#define UC_UNKNOWN_16A6A                         0x16A6A   /* U+16A6A (UNKNOWN_16A6A) */
#define UC_UNKNOWN_16A6B                         0x16A6B   /* U+16A6B (UNKNOWN_16A6B) */
#define UC_UNKNOWN_16A6C                         0x16A6C   /* U+16A6C (UNKNOWN_16A6C) */
#define UC_UNKNOWN_16A6D                         0x16A6D   /* U+16A6D (UNKNOWN_16A6D) */
#define UC_MRO_DANDA                             0x16A6E   /* U+16A6E (MRO DANDA) 𖩮 */
#define UC_MRO_DOUBLE_DANDA                      0x16A6F   /* U+16A6F (MRO DOUBLE DANDA) 𖩯 */
