/* nabataean.h – Unicode constants for U+10880 … U+108AF
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.

* Consistency Check:
* Total Defined Code Points: 40
* Total Significant Hex Values: 40
* Status: OK (Counts Match)

*/

#pragma once

#define UC_NABATAEAN_FINAL_ALEPH                 0x10880 0  // 𐢀
#define UC_NABATAEAN_ALEPH                       0x10881 0  // 𐢁
#define UC_NABATAEAN_FINAL_BETH                  0x10882 0  // 𐢂
#define UC_NABATAEAN_BETH                        0x10883 0  // 𐢃
#define UC_NABATAEAN_GIMEL                       0x10884 0  // 𐢄
#define UC_NABATAEAN_DALETH                      0x10885 0  // 𐢅
#define UC_NABATAEAN_FINAL_HE                    0x10886 0  // 𐢆
#define UC_NABATAEAN_HE                          0x10887 0  // 𐢇
#define UC_NABATAEAN_WAW                         0x10888 0  // 𐢈
#define UC_NABATAEAN_ZAYIN                       0x10889 0  // 𐢉
#define UC_NABATAEAN_HETH                        0x1088A 0  // 𐢊
#define UC_NABATAEAN_TETH                        0x1088B 0  // 𐢋
#define UC_NABATAEAN_FINAL_YODH                  0x1088C 0  // 𐢌
#define UC_NABATAEAN_YODH                        0x1088D 0  // 𐢍
#define UC_NABATAEAN_FINAL_KAPH                  0x1088E 0  // 𐢎
#define UC_NABATAEAN_KAPH                        0x1088F 0  // 𐢏
#define UC_NABATAEAN_FINAL_LAMEDH                0x10890 0  // 𐢐
#define UC_NABATAEAN_LAMEDH                      0x10891 0  // 𐢑
#define UC_NABATAEAN_FINAL_MEM                   0x10892 0  // 𐢒
#define UC_NABATAEAN_MEM                         0x10893 0  // 𐢓
#define UC_NABATAEAN_FINAL_NUN                   0x10894 0  // 𐢔
#define UC_NABATAEAN_NUN                         0x10895 0  // 𐢕
#define UC_NABATAEAN_SAMEKH                      0x10896 0  // 𐢖
#define UC_NABATAEAN_AYIN                        0x10897 0  // 𐢗
#define UC_NABATAEAN_PE                          0x10898 0  // 𐢘
#define UC_NABATAEAN_SADHE                       0x10899 0  // 𐢙
#define UC_NABATAEAN_QOPH                        0x1089A 0  // 𐢚
#define UC_NABATAEAN_RESH                        0x1089B 0  // 𐢛
#define UC_NABATAEAN_FINAL_SHIN                  0x1089C 0  // 𐢜
#define UC_NABATAEAN_SHIN                        0x1089D 0  // 𐢝
#define UC_NABATAEAN_TAW                         0x1089E 0  // 𐢞
#define UC_NABATAEAN_ONE                         0x108A7 0  // 𐢧
#define UC_NABATAEAN_TWO                         0x108A8 0  // 𐢨
#define UC_NABATAEAN_THREE                       0x108A9 0  // 𐢩
#define UC_NABATAEAN_FOUR                        0x108AA 0  // 𐢪
#define UC_NABATAEAN_CRUCIFORM_FOUR              0x108AB 0  // 𐢫
#define UC_NABATAEAN_FIVE                        0x108AC 0  // 𐢬
#define UC_NABATAEAN_TEN                         0x108AD 0  // 𐢭
#define UC_NABATAEAN_TWENTY                      0x108AE 0  // 𐢮
#define UC_NABATAEAN_ONE_HUNDRED                 0x108AF 0  // 𐢯
