/* Nag Mundari.h – Unicode constants for U+1E4D0 … U+1E4FF
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_NAG_MUNDARI_LETTER_O                  0x1E4D0   /* U+1E4D0 (NAG MUNDARI LETTER O) 𞓐 */
#define UC_NAG_MUNDARI_LETTER_OP                 0x1E4D1   /* U+1E4D1 (NAG MUNDARI LETTER OP) 𞓑 */
#define UC_NAG_MUNDARI_LETTER_OL                 0x1E4D2   /* U+1E4D2 (NAG MUNDARI LETTER OL) 𞓒 */
#define UC_NAG_MUNDARI_LETTER_OY                 0x1E4D3   /* U+1E4D3 (NAG MUNDARI LETTER OY) 𞓓 */
#define UC_NAG_MUNDARI_LETTER_ONG                0x1E4D4   /* U+1E4D4 (NAG MUNDARI LETTER ONG) 𞓔 */
#define UC_NAG_MUNDARI_LETTER_A                  0x1E4D5   /* U+1E4D5 (NAG MUNDARI LETTER A) 𞓕 */
#define UC_NAG_MUNDARI_LETTER_AJ                 0x1E4D6   /* U+1E4D6 (NAG MUNDARI LETTER AJ) 𞓖 */
#define UC_NAG_MUNDARI_LETTER_AB                 0x1E4D7   /* U+1E4D7 (NAG MUNDARI LETTER AB) 𞓗 */
#define UC_NAG_MUNDARI_LETTER_ANY                0x1E4D8   /* U+1E4D8 (NAG MUNDARI LETTER ANY) 𞓘 */
#define UC_NAG_MUNDARI_LETTER_AH                 0x1E4D9   /* U+1E4D9 (NAG MUNDARI LETTER AH) 𞓙 */
#define UC_NAG_MUNDARI_LETTER_I                  0x1E4DA   /* U+1E4DA (NAG MUNDARI LETTER I) 𞓚 */
#define UC_NAG_MUNDARI_LETTER_IS                 0x1E4DB   /* U+1E4DB (NAG MUNDARI LETTER IS) 𞓛 */
#define UC_NAG_MUNDARI_LETTER_IDD                0x1E4DC   /* U+1E4DC (NAG MUNDARI LETTER IDD) 𞓜 */
#define UC_NAG_MUNDARI_LETTER_IT                 0x1E4DD   /* U+1E4DD (NAG MUNDARI LETTER IT) 𞓝 */
#define UC_NAG_MUNDARI_LETTER_IH                 0x1E4DE   /* U+1E4DE (NAG MUNDARI LETTER IH) 𞓞 */
#define UC_NAG_MUNDARI_LETTER_U                  0x1E4DF   /* U+1E4DF (NAG MUNDARI LETTER U) 𞓟 */
#define UC_NAG_MUNDARI_LETTER_UC                 0x1E4E0   /* U+1E4E0 (NAG MUNDARI LETTER UC) 𞓠 */
#define UC_NAG_MUNDARI_LETTER_UD                 0x1E4E1   /* U+1E4E1 (NAG MUNDARI LETTER UD) 𞓡 */
#define UC_NAG_MUNDARI_LETTER_UK                 0x1E4E2   /* U+1E4E2 (NAG MUNDARI LETTER UK) 𞓢 */
#define UC_NAG_MUNDARI_LETTER_UR                 0x1E4E3   /* U+1E4E3 (NAG MUNDARI LETTER UR) 𞓣 */
#define UC_NAG_MUNDARI_LETTER_E                  0x1E4E4   /* U+1E4E4 (NAG MUNDARI LETTER E) 𞓤 */
#define UC_NAG_MUNDARI_LETTER_ENN                0x1E4E5   /* U+1E4E5 (NAG MUNDARI LETTER ENN) 𞓥 */
#define UC_NAG_MUNDARI_LETTER_EG                 0x1E4E6   /* U+1E4E6 (NAG MUNDARI LETTER EG) 𞓦 */
#define UC_NAG_MUNDARI_LETTER_EM                 0x1E4E7   /* U+1E4E7 (NAG MUNDARI LETTER EM) 𞓧 */
#define UC_NAG_MUNDARI_LETTER_EN                 0x1E4E8   /* U+1E4E8 (NAG MUNDARI LETTER EN) 𞓨 */
#define UC_NAG_MUNDARI_LETTER_ETT                0x1E4E9   /* U+1E4E9 (NAG MUNDARI LETTER ETT) 𞓩 */
#define UC_NAG_MUNDARI_LETTER_ELL                0x1E4EA   /* U+1E4EA (NAG MUNDARI LETTER ELL) 𞓪 */
#define UC_NAG_MUNDARI_SIGN_OJOD                 0x1E4EB   /* U+1E4EB (NAG MUNDARI SIGN OJOD) 𞓫 */
#define UC_NAG_MUNDARI_SIGN_MUHOR                0x1E4EC   /* U+1E4EC (NAG MUNDARI SIGN MUHOR) 𞓬 */
#define UC_NAG_MUNDARI_SIGN_TOYOR                0x1E4ED   /* U+1E4ED (NAG MUNDARI SIGN TOYOR) 𞓭 */
#define UC_NAG_MUNDARI_SIGN_IKIR                 0x1E4EE   /* U+1E4EE (NAG MUNDARI SIGN IKIR) 𞓮 */
#define UC_NAG_MUNDARI_SIGN_SUTUH                0x1E4EF   /* U+1E4EF (NAG MUNDARI SIGN SUTUH) 𞓯 */
#define UC_NAG_MUNDARI_DIGIT_ZERO                0x1E4F0   /* U+1E4F0 (NAG MUNDARI DIGIT ZERO) 𞓰 */
#define UC_NAG_MUNDARI_DIGIT_ONE                 0x1E4F1   /* U+1E4F1 (NAG MUNDARI DIGIT ONE) 𞓱 */
#define UC_NAG_MUNDARI_DIGIT_TWO                 0x1E4F2   /* U+1E4F2 (NAG MUNDARI DIGIT TWO) 𞓲 */
#define UC_NAG_MUNDARI_DIGIT_THREE               0x1E4F3   /* U+1E4F3 (NAG MUNDARI DIGIT THREE) 𞓳 */
#define UC_NAG_MUNDARI_DIGIT_FOUR                0x1E4F4   /* U+1E4F4 (NAG MUNDARI DIGIT FOUR) 𞓴 */
#define UC_NAG_MUNDARI_DIGIT_FIVE                0x1E4F5   /* U+1E4F5 (NAG MUNDARI DIGIT FIVE) 𞓵 */
#define UC_NAG_MUNDARI_DIGIT_SIX                 0x1E4F6   /* U+1E4F6 (NAG MUNDARI DIGIT SIX) 𞓶 */
#define UC_NAG_MUNDARI_DIGIT_SEVEN               0x1E4F7   /* U+1E4F7 (NAG MUNDARI DIGIT SEVEN) 𞓷 */
#define UC_NAG_MUNDARI_DIGIT_EIGHT               0x1E4F8   /* U+1E4F8 (NAG MUNDARI DIGIT EIGHT) 𞓸 */
#define UC_NAG_MUNDARI_DIGIT_NINE                0x1E4F9   /* U+1E4F9 (NAG MUNDARI DIGIT NINE) 𞓹 */
#define UC_UNKNOWN_1E4FA                         0x1E4FA   /* U+1E4FA (UNKNOWN_1E4FA) */
#define UC_UNKNOWN_1E4FB                         0x1E4FB   /* U+1E4FB (UNKNOWN_1E4FB) */
#define UC_UNKNOWN_1E4FC                         0x1E4FC   /* U+1E4FC (UNKNOWN_1E4FC) */
#define UC_UNKNOWN_1E4FD                         0x1E4FD   /* U+1E4FD (UNKNOWN_1E4FD) */
#define UC_UNKNOWN_1E4FE                         0x1E4FE   /* U+1E4FE (UNKNOWN_1E4FE) */
#define UC_UNKNOWN_1E4FF                         0x1E4FF   /* U+1E4FF (UNKNOWN_1E4FF) */
