/* nandinagari.h – Unicode constants for U+119A0 … U+119FF
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
*
* See https://www.unicode.org/versions/latest/ for source data.

 * Nandināgarī is a Brahmic script derived from the Nāgarī script which
 * appeared in the 7th century AD. This script and its variants were used in
 * the central Deccan region and south India , and an abundance of Sanskrit
 * manuscripts in Nandināgarī have been discovered but remain
 * untransliterated. Some of the discovered manuscripts of Madhvacharya of the
 * Dvaita Vedanta school of Hinduism are in Nandināgarī script.
 * It is a sister script to Devanāgarī , which is common in other parts of
 * India.
 *

* Consistency Check:
* Total Defined Code Points: 65
* Total Significant Hex Values: 65
* Status: OK (Counts Match)

*/

#ifndef NANDINAGARI_H
#define NANDINAGARI_H

#define UC_NANDINAGARI_A                         0x119A0 0  // 𑦠
#define UC_NANDINAGARI_AA                        0x119A1 0  // 𑦡
#define UC_NANDINAGARI_I                         0x119A2 0  // 𑦢
#define UC_NANDINAGARI_II                        0x119A3 0  // 𑦣
#define UC_NANDINAGARI_U                         0x119A4 0  // 𑦤
#define UC_NANDINAGARI_UU                        0x119A5 0  // 𑦥
#define UC_NANDINAGARI_VOCALIC_R                 0x119A6 0  // 𑦦
#define UC_NANDINAGARI_VOCALIC_RR                0x119A7 0  // 𑦧
#define UC_NANDINAGARI_E                         0x119AA 0  // 𑦪
#define UC_NANDINAGARI_AI                        0x119AB 0  // 𑦫
#define UC_NANDINAGARI_O                         0x119AC 0  // 𑦬
#define UC_NANDINAGARI_AU                        0x119AD 0  // 𑦭
#define UC_NANDINAGARI_KA                        0x119AE 0  // 𑦮
#define UC_NANDINAGARI_KHA                       0x119AF 0  // 𑦯
#define UC_NANDINAGARI_GA                        0x119B0 0  // 𑦰
#define UC_NANDINAGARI_GHA                       0x119B1 0  // 𑦱
#define UC_NANDINAGARI_NGA                       0x119B2 0  // 𑦲
#define UC_NANDINAGARI_CA                        0x119B3 0  // 𑦳
#define UC_NANDINAGARI_CHA                       0x119B4 0  // 𑦴
#define UC_NANDINAGARI_JA                        0x119B5 0  // 𑦵
#define UC_NANDINAGARI_JHA                       0x119B6 0  // 𑦶
#define UC_NANDINAGARI_NYA                       0x119B7 0  // 𑦷
#define UC_NANDINAGARI_TTA                       0x119B8 0  // 𑦸
#define UC_NANDINAGARI_TTHA                      0x119B9 0  // 𑦹
#define UC_NANDINAGARI_DDA                       0x119BA 0  // 𑦺
#define UC_NANDINAGARI_DDHA                      0x119BB 0  // 𑦻
#define UC_NANDINAGARI_NNA                       0x119BC 0  // 𑦼
#define UC_NANDINAGARI_TA                        0x119BD 0  // 𑦽
#define UC_NANDINAGARI_THA                       0x119BE 0  // 𑦾
#define UC_NANDINAGARI_DA                        0x119BF 0  // 𑦿
#define UC_NANDINAGARI_DHA                       0x119C0 0  // 𑧀
#define UC_NANDINAGARI_NA                        0x119C1 0  // 𑧁
#define UC_NANDINAGARI_PA                        0x119C2 0  // 𑧂
#define UC_NANDINAGARI_PHA                       0x119C3 0  // 𑧃
#define UC_NANDINAGARI_BA                        0x119C4 0  // 𑧄
#define UC_NANDINAGARI_BHA                       0x119C5 0  // 𑧅
#define UC_NANDINAGARI_MA                        0x119C6 0  // 𑧆
#define UC_NANDINAGARI_YA                        0x119C7 0  // 𑧇
#define UC_NANDINAGARI_RA                        0x119C8 0  // 𑧈
#define UC_NANDINAGARI_LA                        0x119C9 0  // 𑧉
#define UC_NANDINAGARI_VA                        0x119CA 0  // 𑧊
#define UC_NANDINAGARI_SHA                       0x119CB 0  // 𑧋
#define UC_NANDINAGARI_SSA                       0x119CC 0  // 𑧌
#define UC_NANDINAGARI_SA                        0x119CD 0  // 𑧍
#define UC_NANDINAGARI_HA                        0x119CE 0  // 𑧎
#define UC_NANDINAGARI_LLA                       0x119CF 0  // 𑧏
#define UC_NANDINAGARI_RRA                       0x119D0 0  // 𑧐
#define UC_NANDINAGARI_VOWEL_SIGN_AA             0x119D1 0  // 𑧑
#define UC_NANDINAGARI_VOWEL_SIGN_I              0x119D2 0  // 𑧒
#define UC_NANDINAGARI_VOWEL_SIGN_II             0x119D3 0  // 𑧓
#define UC_NANDINAGARI_VOWEL_SIGN_U              0x119D4 0  // 𑧔
#define UC_NANDINAGARI_VOWEL_SIGN_UU             0x119D5 0  // 𑧕
#define UC_NANDINAGARI_VOWEL_SIGN_VOCALIC_R      0x119D6 0  // 𑧖
#define UC_NANDINAGARI_VOWEL_SIGN_VOCALIC_RR     0x119D7 0  // 𑧗
#define UC_NANDINAGARI_VOWEL_SIGN_E              0x119DA 0  // 𑧚
#define UC_NANDINAGARI_VOWEL_SIGN_AI             0x119DB 0  // 𑧛
#define UC_NANDINAGARI_VOWEL_SIGN_O              0x119DC 0  // 𑧜
#define UC_NANDINAGARI_VOWEL_SIGN_AU             0x119DD 0  // 𑧝
#define UC_NANDINAGARI_SIGN_ANUSVARA             0x119DE 0  // 𑧞
#define UC_NANDINAGARI_SIGN_VISARGA              0x119DF 0  // 𑧟
#define UC_NANDINAGARI_SIGN_VIRAMA               0x119E0 0  // 𑧠
#define UC_NANDINAGARI_SIGN_AVAGRAHA             0x119E1 0  // 𑧡
#define UC_NANDINAGARI_SIGN_SIDDHAM              0x119E2 0  // 𑧢
#define UC_NANDINAGARI_HEADSTROKE                0x119E3 0  // 𑧣
#define UC_NANDINAGARI_VOWEL_SIGN_PRISHTHAMATRA_E 0x119E4 0  // 𑧤

#endif // NANDINAGARI_H
