/* Nandinagari.h – Unicode constants for U+119A0 … U+119FF
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_NANDINAGARI_LETTER_A                  0x119A0   /* U+119A0 (NANDINAGARI LETTER A) 𑦠 */
#define UC_NANDINAGARI_LETTER_AA                 0x119A1   /* U+119A1 (NANDINAGARI LETTER AA) 𑦡 */
#define UC_NANDINAGARI_LETTER_I                  0x119A2   /* U+119A2 (NANDINAGARI LETTER I) 𑦢 */
#define UC_NANDINAGARI_LETTER_II                 0x119A3   /* U+119A3 (NANDINAGARI LETTER II) 𑦣 */
#define UC_NANDINAGARI_LETTER_U                  0x119A4   /* U+119A4 (NANDINAGARI LETTER U) 𑦤 */
#define UC_NANDINAGARI_LETTER_UU                 0x119A5   /* U+119A5 (NANDINAGARI LETTER UU) 𑦥 */
#define UC_NANDINAGARI_LETTER_VOCALIC_R          0x119A6   /* U+119A6 (NANDINAGARI LETTER VOCALIC R) 𑦦 */
#define UC_NANDINAGARI_LETTER_VOCALIC_RR         0x119A7   /* U+119A7 (NANDINAGARI LETTER VOCALIC RR) 𑦧 */
#define UC_UNKNOWN_119A8                         0x119A8   /* U+119A8 (UNKNOWN_119A8) */
#define UC_UNKNOWN_119A9                         0x119A9   /* U+119A9 (UNKNOWN_119A9) */
#define UC_NANDINAGARI_LETTER_E                  0x119AA   /* U+119AA (NANDINAGARI LETTER E) 𑦪 */
#define UC_NANDINAGARI_LETTER_AI                 0x119AB   /* U+119AB (NANDINAGARI LETTER AI) 𑦫 */
#define UC_NANDINAGARI_LETTER_O                  0x119AC   /* U+119AC (NANDINAGARI LETTER O) 𑦬 */
#define UC_NANDINAGARI_LETTER_AU                 0x119AD   /* U+119AD (NANDINAGARI LETTER AU) 𑦭 */
#define UC_NANDINAGARI_LETTER_KA                 0x119AE   /* U+119AE (NANDINAGARI LETTER KA) 𑦮 */
#define UC_NANDINAGARI_LETTER_KHA                0x119AF   /* U+119AF (NANDINAGARI LETTER KHA) 𑦯 */
#define UC_NANDINAGARI_LETTER_GA                 0x119B0   /* U+119B0 (NANDINAGARI LETTER GA) 𑦰 */
#define UC_NANDINAGARI_LETTER_GHA                0x119B1   /* U+119B1 (NANDINAGARI LETTER GHA) 𑦱 */
#define UC_NANDINAGARI_LETTER_NGA                0x119B2   /* U+119B2 (NANDINAGARI LETTER NGA) 𑦲 */
#define UC_NANDINAGARI_LETTER_CA                 0x119B3   /* U+119B3 (NANDINAGARI LETTER CA) 𑦳 */
#define UC_NANDINAGARI_LETTER_CHA                0x119B4   /* U+119B4 (NANDINAGARI LETTER CHA) 𑦴 */
#define UC_NANDINAGARI_LETTER_JA                 0x119B5   /* U+119B5 (NANDINAGARI LETTER JA) 𑦵 */
#define UC_NANDINAGARI_LETTER_JHA                0x119B6   /* U+119B6 (NANDINAGARI LETTER JHA) 𑦶 */
#define UC_NANDINAGARI_LETTER_NYA                0x119B7   /* U+119B7 (NANDINAGARI LETTER NYA) 𑦷 */
#define UC_NANDINAGARI_LETTER_TTA                0x119B8   /* U+119B8 (NANDINAGARI LETTER TTA) 𑦸 */
#define UC_NANDINAGARI_LETTER_TTHA               0x119B9   /* U+119B9 (NANDINAGARI LETTER TTHA) 𑦹 */
#define UC_NANDINAGARI_LETTER_DDA                0x119BA   /* U+119BA (NANDINAGARI LETTER DDA) 𑦺 */
#define UC_NANDINAGARI_LETTER_DDHA               0x119BB   /* U+119BB (NANDINAGARI LETTER DDHA) 𑦻 */
#define UC_NANDINAGARI_LETTER_NNA                0x119BC   /* U+119BC (NANDINAGARI LETTER NNA) 𑦼 */
#define UC_NANDINAGARI_LETTER_TA                 0x119BD   /* U+119BD (NANDINAGARI LETTER TA) 𑦽 */
#define UC_NANDINAGARI_LETTER_THA                0x119BE   /* U+119BE (NANDINAGARI LETTER THA) 𑦾 */
#define UC_NANDINAGARI_LETTER_DA                 0x119BF   /* U+119BF (NANDINAGARI LETTER DA) 𑦿 */
#define UC_NANDINAGARI_LETTER_DHA                0x119C0   /* U+119C0 (NANDINAGARI LETTER DHA) 𑧀 */
#define UC_NANDINAGARI_LETTER_NA                 0x119C1   /* U+119C1 (NANDINAGARI LETTER NA) 𑧁 */
#define UC_NANDINAGARI_LETTER_PA                 0x119C2   /* U+119C2 (NANDINAGARI LETTER PA) 𑧂 */
#define UC_NANDINAGARI_LETTER_PHA                0x119C3   /* U+119C3 (NANDINAGARI LETTER PHA) 𑧃 */
#define UC_NANDINAGARI_LETTER_BA                 0x119C4   /* U+119C4 (NANDINAGARI LETTER BA) 𑧄 */
#define UC_NANDINAGARI_LETTER_BHA                0x119C5   /* U+119C5 (NANDINAGARI LETTER BHA) 𑧅 */
#define UC_NANDINAGARI_LETTER_MA                 0x119C6   /* U+119C6 (NANDINAGARI LETTER MA) 𑧆 */
#define UC_NANDINAGARI_LETTER_YA                 0x119C7   /* U+119C7 (NANDINAGARI LETTER YA) 𑧇 */
#define UC_NANDINAGARI_LETTER_RA                 0x119C8   /* U+119C8 (NANDINAGARI LETTER RA) 𑧈 */
#define UC_NANDINAGARI_LETTER_LA                 0x119C9   /* U+119C9 (NANDINAGARI LETTER LA) 𑧉 */
#define UC_NANDINAGARI_LETTER_VA                 0x119CA   /* U+119CA (NANDINAGARI LETTER VA) 𑧊 */
#define UC_NANDINAGARI_LETTER_SHA                0x119CB   /* U+119CB (NANDINAGARI LETTER SHA) 𑧋 */
#define UC_NANDINAGARI_LETTER_SSA                0x119CC   /* U+119CC (NANDINAGARI LETTER SSA) 𑧌 */
#define UC_NANDINAGARI_LETTER_SA                 0x119CD   /* U+119CD (NANDINAGARI LETTER SA) 𑧍 */
#define UC_NANDINAGARI_LETTER_HA                 0x119CE   /* U+119CE (NANDINAGARI LETTER HA) 𑧎 */
#define UC_NANDINAGARI_LETTER_LLA                0x119CF   /* U+119CF (NANDINAGARI LETTER LLA) 𑧏 */
#define UC_NANDINAGARI_LETTER_RRA                0x119D0   /* U+119D0 (NANDINAGARI LETTER RRA) 𑧐 */
#define UC_NANDINAGARI_VOWEL_SIGN_AA             0x119D1   /* U+119D1 (NANDINAGARI VOWEL SIGN AA) 𑧑 */
#define UC_NANDINAGARI_VOWEL_SIGN_I              0x119D2   /* U+119D2 (NANDINAGARI VOWEL SIGN I) 𑧒 */
#define UC_NANDINAGARI_VOWEL_SIGN_II             0x119D3   /* U+119D3 (NANDINAGARI VOWEL SIGN II) 𑧓 */
#define UC_NANDINAGARI_VOWEL_SIGN_U              0x119D4   /* U+119D4 (NANDINAGARI VOWEL SIGN U) 𑧔 */
#define UC_NANDINAGARI_VOWEL_SIGN_UU             0x119D5   /* U+119D5 (NANDINAGARI VOWEL SIGN UU) 𑧕 */
#define UC_NANDINAGARI_VOWEL_SIGN_VOCALIC_R      0x119D6   /* U+119D6 (NANDINAGARI VOWEL SIGN VOCALIC R) 𑧖 */
#define UC_NANDINAGARI_VOWEL_SIGN_VOCALIC_RR     0x119D7   /* U+119D7 (NANDINAGARI VOWEL SIGN VOCALIC RR) 𑧗 */
#define UC_UNKNOWN_119D8                         0x119D8   /* U+119D8 (UNKNOWN_119D8) */
#define UC_UNKNOWN_119D9                         0x119D9   /* U+119D9 (UNKNOWN_119D9) */
#define UC_NANDINAGARI_VOWEL_SIGN_E              0x119DA   /* U+119DA (NANDINAGARI VOWEL SIGN E) 𑧚 */
#define UC_NANDINAGARI_VOWEL_SIGN_AI             0x119DB   /* U+119DB (NANDINAGARI VOWEL SIGN AI) 𑧛 */
#define UC_NANDINAGARI_VOWEL_SIGN_O              0x119DC   /* U+119DC (NANDINAGARI VOWEL SIGN O) 𑧜 */
#define UC_NANDINAGARI_VOWEL_SIGN_AU             0x119DD   /* U+119DD (NANDINAGARI VOWEL SIGN AU) 𑧝 */
#define UC_NANDINAGARI_SIGN_ANUSVARA             0x119DE   /* U+119DE (NANDINAGARI SIGN ANUSVARA) 𑧞 */
#define UC_NANDINAGARI_SIGN_VISARGA              0x119DF   /* U+119DF (NANDINAGARI SIGN VISARGA) 𑧟 */
#define UC_NANDINAGARI_SIGN_VIRAMA               0x119E0   /* U+119E0 (NANDINAGARI SIGN VIRAMA) 𑧠 */
#define UC_NANDINAGARI_SIGN_AVAGRAHA             0x119E1   /* U+119E1 (NANDINAGARI SIGN AVAGRAHA) 𑧡 */
#define UC_NANDINAGARI_SIGN_SIDDHAM              0x119E2   /* U+119E2 (NANDINAGARI SIGN SIDDHAM) 𑧢 */
#define UC_NANDINAGARI_HEADSTROKE                0x119E3   /* U+119E3 (NANDINAGARI HEADSTROKE) 𑧣 */
#define UC_NANDINAGARI_VOWEL_SIGN_PRISHTHAMATRA_E 0x119E4   /* U+119E4 (NANDINAGARI VOWEL SIGN PRISHTHAMATRA E) 𑧤 */
#define UC_UNKNOWN_119E5                         0x119E5   /* U+119E5 (UNKNOWN_119E5) */
#define UC_UNKNOWN_119E6                         0x119E6   /* U+119E6 (UNKNOWN_119E6) */
#define UC_UNKNOWN_119E7                         0x119E7   /* U+119E7 (UNKNOWN_119E7) */
#define UC_UNKNOWN_119E8                         0x119E8   /* U+119E8 (UNKNOWN_119E8) */
#define UC_UNKNOWN_119E9                         0x119E9   /* U+119E9 (UNKNOWN_119E9) */
#define UC_UNKNOWN_119EA                         0x119EA   /* U+119EA (UNKNOWN_119EA) */
#define UC_UNKNOWN_119EB                         0x119EB   /* U+119EB (UNKNOWN_119EB) */
#define UC_UNKNOWN_119EC                         0x119EC   /* U+119EC (UNKNOWN_119EC) */
#define UC_UNKNOWN_119ED                         0x119ED   /* U+119ED (UNKNOWN_119ED) */
#define UC_UNKNOWN_119EE                         0x119EE   /* U+119EE (UNKNOWN_119EE) */
#define UC_UNKNOWN_119EF                         0x119EF   /* U+119EF (UNKNOWN_119EF) */
#define UC_UNKNOWN_119F0                         0x119F0   /* U+119F0 (UNKNOWN_119F0) */
#define UC_UNKNOWN_119F1                         0x119F1   /* U+119F1 (UNKNOWN_119F1) */
#define UC_UNKNOWN_119F2                         0x119F2   /* U+119F2 (UNKNOWN_119F2) */
#define UC_UNKNOWN_119F3                         0x119F3   /* U+119F3 (UNKNOWN_119F3) */
#define UC_UNKNOWN_119F4                         0x119F4   /* U+119F4 (UNKNOWN_119F4) */
#define UC_UNKNOWN_119F5                         0x119F5   /* U+119F5 (UNKNOWN_119F5) */
#define UC_UNKNOWN_119F6                         0x119F6   /* U+119F6 (UNKNOWN_119F6) */
#define UC_UNKNOWN_119F7                         0x119F7   /* U+119F7 (UNKNOWN_119F7) */
#define UC_UNKNOWN_119F8                         0x119F8   /* U+119F8 (UNKNOWN_119F8) */
#define UC_UNKNOWN_119F9                         0x119F9   /* U+119F9 (UNKNOWN_119F9) */
#define UC_UNKNOWN_119FA                         0x119FA   /* U+119FA (UNKNOWN_119FA) */
#define UC_UNKNOWN_119FB                         0x119FB   /* U+119FB (UNKNOWN_119FB) */
#define UC_UNKNOWN_119FC                         0x119FC   /* U+119FC (UNKNOWN_119FC) */
#define UC_UNKNOWN_119FD                         0x119FD   /* U+119FD (UNKNOWN_119FD) */
#define UC_UNKNOWN_119FE                         0x119FE   /* U+119FE (UNKNOWN_119FE) */
#define UC_UNKNOWN_119FF                         0x119FF   /* U+119FF (UNKNOWN_119FF) */
