/* newa.h – Unicode constants for U+11400 … U+1147F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.

* Consistency Check:
* Total Defined Code Points: 97
* Total Significant Hex Values: 97
* Status: OK (Counts Match)

*/

#pragma once

#define UC_NEWA_A                                0x11400 0  // 𑐀
#define UC_NEWA_AA                               0x11401 0  // 𑐁
#define UC_NEWA_I                                0x11402 0  // 𑐂
#define UC_NEWA_II                               0x11403 0  // 𑐃
#define UC_NEWA_U                                0x11404 0  // 𑐄
#define UC_NEWA_UU                               0x11405 0  // 𑐅
#define UC_NEWA_VOCALIC_R                        0x11406 0  // 𑐆
#define UC_NEWA_VOCALIC_RR                       0x11407 0  // 𑐇
#define UC_NEWA_VOCALIC_L                        0x11408 0  // 𑐈
#define UC_NEWA_VOCALIC_LL                       0x11409 0  // 𑐉
#define UC_NEWA_E                                0x1140A 0  // 𑐊
#define UC_NEWA_AI                               0x1140B 0  // 𑐋
#define UC_NEWA_O                                0x1140C 0  // 𑐌
#define UC_NEWA_AU                               0x1140D 0  // 𑐍
#define UC_NEWA_KA                               0x1140E 0  // 𑐎
#define UC_NEWA_KHA                              0x1140F 0  // 𑐏
#define UC_NEWA_GA                               0x11410 0  // 𑐐
#define UC_NEWA_GHA                              0x11411 0  // 𑐑
#define UC_NEWA_NGA                              0x11412 0  // 𑐒
#define UC_NEWA_NGHA                             0x11413 0  // 𑐓
#define UC_NEWA_CA                               0x11414 0  // 𑐔
#define UC_NEWA_CHA                              0x11415 0  // 𑐕
#define UC_NEWA_JA                               0x11416 0  // 𑐖
#define UC_NEWA_JHA                              0x11417 0  // 𑐗
#define UC_NEWA_NYA                              0x11418 0  // 𑐘
#define UC_NEWA_NYHA                             0x11419 0  // 𑐙
#define UC_NEWA_TTA                              0x1141A 0  // 𑐚
#define UC_NEWA_TTHA                             0x1141B 0  // 𑐛
#define UC_NEWA_DDA                              0x1141C 0  // 𑐜
#define UC_NEWA_DDHA                             0x1141D 0  // 𑐝
#define UC_NEWA_NNA                              0x1141E 0  // 𑐞
#define UC_NEWA_TA                               0x1141F 0  // 𑐟
#define UC_NEWA_THA                              0x11420 0  // 𑐠
#define UC_NEWA_DA                               0x11421 0  // 𑐡
#define UC_NEWA_DHA                              0x11422 0  // 𑐢
#define UC_NEWA_NA                               0x11423 0  // 𑐣
#define UC_NEWA_NHA                              0x11424 0  // 𑐤
#define UC_NEWA_PA                               0x11425 0  // 𑐥
#define UC_NEWA_PHA                              0x11426 0  // 𑐦
#define UC_NEWA_BA                               0x11427 0  // 𑐧
#define UC_NEWA_BHA                              0x11428 0  // 𑐨
#define UC_NEWA_MA                               0x11429 0  // 𑐩
#define UC_NEWA_MHA                              0x1142A 0  // 𑐪
#define UC_NEWA_YA                               0x1142B 0  // 𑐫
#define UC_NEWA_RA                               0x1142C 0  // 𑐬
#define UC_NEWA_RHA                              0x1142D 0  // 𑐭
#define UC_NEWA_LA                               0x1142E 0  // 𑐮
#define UC_NEWA_LHA                              0x1142F 0  // 𑐯
#define UC_NEWA_WA                               0x11430 0  // 𑐰
#define UC_NEWA_SHA                              0x11431 0  // 𑐱
#define UC_NEWA_SSA                              0x11432 0  // 𑐲
#define UC_NEWA_SA                               0x11433 0  // 𑐳
#define UC_NEWA_HA                               0x11434 0  // 𑐴
#define UC_NEWA_VOWEL_SIGN_AA                    0x11435 0  // 𑐵
#define UC_NEWA_VOWEL_SIGN_I                     0x11436 0  // 𑐶
#define UC_NEWA_VOWEL_SIGN_II                    0x11437 0  // 𑐷
#define UC_NEWA_VOWEL_SIGN_U                     0x11438 0  // 𑐸
#define UC_NEWA_VOWEL_SIGN_UU                    0x11439 0  // 𑐹
#define UC_NEWA_VOWEL_SIGN_VOCALIC_R             0x1143A 0  // 𑐺
#define UC_NEWA_VOWEL_SIGN_VOCALIC_RR            0x1143B 0  // 𑐻
#define UC_NEWA_VOWEL_SIGN_VOCALIC_L             0x1143C 0  // 𑐼
#define UC_NEWA_VOWEL_SIGN_VOCALIC_LL            0x1143D 0  // 𑐽
#define UC_NEWA_VOWEL_SIGN_E                     0x1143E 0  // 𑐾
#define UC_NEWA_VOWEL_SIGN_AI                    0x1143F 0  // 𑐿
#define UC_NEWA_VOWEL_SIGN_O                     0x11440 0  // 𑑀
#define UC_NEWA_VOWEL_SIGN_AU                    0x11441 0  // 𑑁
#define UC_NEWA_SIGN_VIRAMA                      0x11442 0  // 𑑂
#define UC_NEWA_SIGN_CANDRABINDU                 0x11443 0  // 𑑃
#define UC_NEWA_SIGN_ANUSVARA                    0x11444 0  // 𑑄
#define UC_NEWA_SIGN_VISARGA                     0x11445 0  // 𑑅
#define UC_NEWA_SIGN_NUKTA                       0x11446 0  // 𑑆
#define UC_NEWA_SIGN_AVAGRAHA                    0x11447 0  // 𑑇
#define UC_NEWA_SIGN_FINAL_ANUSVARA              0x11448 0  // 𑑈
#define UC_NEWA_OM                               0x11449 0  // 𑑉
#define UC_NEWA_SIDDHI                           0x1144A 0  // 𑑊
#define UC_NEWA_DANDA                            0x1144B 0  // 𑑋
#define UC_NEWA_DOUBLE_DANDA                     0x1144C 0  // 𑑌
#define UC_NEWA                                  0x1144D 0  // 𑑍
#define UC_NEWA_GAP_FILLER                       0x1144E 0  // 𑑎
#define UC_NEWA_ABBREVIATION_SIGN                0x1144F 0  // 𑑏
#define UC_NEWA_ZERO                             0x11450 0  // 𑑐
#define UC_NEWA_ONE                              0x11451 0  // 𑑑
#define UC_NEWA_TWO                              0x11452 0  // 𑑒
#define UC_NEWA_THREE                            0x11453 0  // 𑑓
#define UC_NEWA_FOUR                             0x11454 0  // 𑑔
#define UC_NEWA_FIVE                             0x11455 0  // 𑑕
#define UC_NEWA_SIX                              0x11456 0  // 𑑖
#define UC_NEWA_SEVEN                            0x11457 0  // 𑑗
#define UC_NEWA_EIGHT                            0x11458 0  // 𑑘
#define UC_NEWA_NINE                             0x11459 0  // 𑑙
#define UC_NEWA_DOUBLE                           0x1145A 0  // 𑑚
#define UC_NEWA_PLACEHOLDER_MARK                 0x1145B 0  // 𑑛
#define UC_NEWA_INSERTION_SIGN                   0x1145D 0  // 𑑝
#define UC_NEWA_SANDHI_MARK                      0x1145E 0  // 𑑞
#define UC_NEWA_VEDIC_ANUSVARA                   0x1145F 0  // 𑑟
#define UC_NEWA_SIGN_JIHVAMULIYA                 0x11460 0  // 𑑠
#define UC_NEWA_SIGN_UPADHMANIYA                 0x11461 0  // 𑑡
