/* Newa.h – Unicode constants for U+1145D … U+11461
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_NEWA_INSERTION_SIGN                   0x1145D 0  // 𑑝
#define UC_NEWA_SANDHI_MARK                      0x1145E 0  // 𑑞
#define UC_NEWA_LETTER_VEDIC_ANUSVARA            0x1145F 0  // 𑑟
#define UC_NEWA_SIGN_JIHVAMULIYA                 0x11460 0  // 𑑠
#define UC_NEWA_SIGN_UPADHMANIYA                 0x11461 0  // 𑑡
