/* Ogham.h – Unicode constants for U+1680 … U+169F
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_OGHAM_SPACE_MARK                      0x1680   /* U+1680 (OGHAM SPACE MARK) */
#define UC_OGHAM_LETTER_BEITH                    0x1681   /* U+1681 (OGHAM LETTER BEITH) ᚁ */
#define UC_OGHAM_LETTER_LUIS                     0x1682   /* U+1682 (OGHAM LETTER LUIS) ᚂ */
#define UC_OGHAM_LETTER_FEARN                    0x1683   /* U+1683 (OGHAM LETTER FEARN) ᚃ */
#define UC_OGHAM_LETTER_SAIL                     0x1684   /* U+1684 (OGHAM LETTER SAIL) ᚄ */
#define UC_OGHAM_LETTER_NION                     0x1685   /* U+1685 (OGHAM LETTER NION) ᚅ */
#define UC_OGHAM_LETTER_UATH                     0x1686   /* U+1686 (OGHAM LETTER UATH) ᚆ */
#define UC_OGHAM_LETTER_DAIR                     0x1687   /* U+1687 (OGHAM LETTER DAIR) ᚇ */
#define UC_OGHAM_LETTER_TINNE                    0x1688   /* U+1688 (OGHAM LETTER TINNE) ᚈ */
#define UC_OGHAM_LETTER_COLL                     0x1689   /* U+1689 (OGHAM LETTER COLL) ᚉ */
#define UC_OGHAM_LETTER_CEIRT                    0x168A   /* U+168A (OGHAM LETTER CEIRT) ᚊ */
#define UC_OGHAM_LETTER_MUIN                     0x168B   /* U+168B (OGHAM LETTER MUIN) ᚋ */
#define UC_OGHAM_LETTER_GORT                     0x168C   /* U+168C (OGHAM LETTER GORT) ᚌ */
#define UC_OGHAM_LETTER_NGEADAL                  0x168D   /* U+168D (OGHAM LETTER NGEADAL) ᚍ */
#define UC_OGHAM_LETTER_STRAIF                   0x168E   /* U+168E (OGHAM LETTER STRAIF) ᚎ */
#define UC_OGHAM_LETTER_RUIS                     0x168F   /* U+168F (OGHAM LETTER RUIS) ᚏ */
#define UC_OGHAM_LETTER_AILM                     0x1690   /* U+1690 (OGHAM LETTER AILM) ᚐ */
#define UC_OGHAM_LETTER_ONN                      0x1691   /* U+1691 (OGHAM LETTER ONN) ᚑ */
#define UC_OGHAM_LETTER_UR                       0x1692   /* U+1692 (OGHAM LETTER UR) ᚒ */
#define UC_OGHAM_LETTER_EADHADH                  0x1693   /* U+1693 (OGHAM LETTER EADHADH) ᚓ */
#define UC_OGHAM_LETTER_IODHADH                  0x1694   /* U+1694 (OGHAM LETTER IODHADH) ᚔ */
#define UC_OGHAM_LETTER_EABHADH                  0x1695   /* U+1695 (OGHAM LETTER EABHADH) ᚕ */
#define UC_OGHAM_LETTER_OR                       0x1696   /* U+1696 (OGHAM LETTER OR) ᚖ */
#define UC_OGHAM_LETTER_UILLEANN                 0x1697   /* U+1697 (OGHAM LETTER UILLEANN) ᚗ */
#define UC_OGHAM_LETTER_IFIN                     0x1698   /* U+1698 (OGHAM LETTER IFIN) ᚘ */
#define UC_OGHAM_LETTER_EAMHANCHOLL              0x1699   /* U+1699 (OGHAM LETTER EAMHANCHOLL) ᚙ */
#define UC_OGHAM_LETTER_PEITH                    0x169A   /* U+169A (OGHAM LETTER PEITH) ᚚ */
#define UC_OGHAM_FEATHER_MARK                    0x169B   /* U+169B (OGHAM FEATHER MARK) ᚛ */
#define UC_OGHAM_REVERSED_FEATHER_MARK           0x169C   /* U+169C (OGHAM REVERSED FEATHER MARK) ᚜ */
#define UC_UNKNOWN_169D                          0x169D   /* U+169D (UNKNOWN_169D) */
#define UC_UNKNOWN_169E                          0x169E   /* U+169E (UNKNOWN_169E) */
#define UC_UNKNOWN_169F                          0x169F   /* U+169F (UNKNOWN_169F) */
