/* old_turkic.h – Unicode constants for U+10C00 … U+10C4F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.

* Consistency Check:
* Total Defined Code Points: 73
* Total Significant Hex Values: 73
* Status: OK (Counts Match)

*/

#pragma once

#define UC_OLD_TURKIC_ORKHON_A                   0x10C00 0  // 𐰀
#define UC_OLD_TURKIC_YENISEI_A                  0x10C01 0  // 𐰁
#define UC_OLD_TURKIC_YENISEI_AE                 0x10C02 0  // 𐰂
#define UC_OLD_TURKIC_ORKHON_I                   0x10C03 0  // 𐰃
#define UC_OLD_TURKIC_YENISEI_I                  0x10C04 0  // 𐰄
#define UC_OLD_TURKIC_YENISEI_E                  0x10C05 0  // 𐰅
#define UC_OLD_TURKIC_ORKHON_O                   0x10C06 0  // 𐰆
#define UC_OLD_TURKIC_ORKHON_OE                  0x10C07 0  // 𐰇
#define UC_OLD_TURKIC_YENISEI_OE                 0x10C08 0  // 𐰈
#define UC_OLD_TURKIC_ORKHON_AB                  0x10C09 0  // 𐰉
#define UC_OLD_TURKIC_YENISEI_AB                 0x10C0A 0  // 𐰊
#define UC_OLD_TURKIC_ORKHON_AEB                 0x10C0B 0  // 𐰋
#define UC_OLD_TURKIC_YENISEI_AEB                0x10C0C 0  // 𐰌
#define UC_OLD_TURKIC_ORKHON_AG                  0x10C0D 0  // 𐰍
#define UC_OLD_TURKIC_YENISEI_AG                 0x10C0E 0  // 𐰎
#define UC_OLD_TURKIC_ORKHON_AEG                 0x10C0F 0  // 𐰏
#define UC_OLD_TURKIC_YENISEI_AEG                0x10C10 0  // 𐰐
#define UC_OLD_TURKIC_ORKHON_AD                  0x10C11 0  // 𐰑
#define UC_OLD_TURKIC_YENISEI_AD                 0x10C12 0  // 𐰒
#define UC_OLD_TURKIC_ORKHON_AED                 0x10C13 0  // 𐰓
#define UC_OLD_TURKIC_ORKHON_EZ                  0x10C14 0  // 𐰔
#define UC_OLD_TURKIC_YENISEI_EZ                 0x10C15 0  // 𐰕
#define UC_OLD_TURKIC_ORKHON_AY                  0x10C16 0  // 𐰖
#define UC_OLD_TURKIC_YENISEI_AY                 0x10C17 0  // 𐰗
#define UC_OLD_TURKIC_ORKHON_AEY                 0x10C18 0  // 𐰘
#define UC_OLD_TURKIC_YENISEI_AEY                0x10C19 0  // 𐰙
#define UC_OLD_TURKIC_ORKHON_AEK                 0x10C1A 0  // 𐰚
#define UC_OLD_TURKIC_YENISEI_AEK                0x10C1B 0  // 𐰛
#define UC_OLD_TURKIC_ORKHON_OEK                 0x10C1C 0  // 𐰜
#define UC_OLD_TURKIC_YENISEI_OEK                0x10C1D 0  // 𐰝
#define UC_OLD_TURKIC_ORKHON_AL                  0x10C1E 0  // 𐰞
#define UC_OLD_TURKIC_YENISEI_AL                 0x10C1F 0  // 𐰟
#define UC_OLD_TURKIC_ORKHON_AEL                 0x10C20 0  // 𐰠
#define UC_OLD_TURKIC_ORKHON_ELT                 0x10C21 0  // 𐰡
#define UC_OLD_TURKIC_ORKHON_EM                  0x10C22 0  // 𐰢
#define UC_OLD_TURKIC_ORKHON_AN                  0x10C23 0  // 𐰣
#define UC_OLD_TURKIC_ORKHON_AEN                 0x10C24 0  // 𐰤
#define UC_OLD_TURKIC_YENISEI_AEN                0x10C25 0  // 𐰥
#define UC_OLD_TURKIC_ORKHON_ENT                 0x10C26 0  // 𐰦
#define UC_OLD_TURKIC_YENISEI_ENT                0x10C27 0  // 𐰧
#define UC_OLD_TURKIC_ORKHON_ENC                 0x10C28 0  // 𐰨
#define UC_OLD_TURKIC_YENISEI_ENC                0x10C29 0  // 𐰩
#define UC_OLD_TURKIC_ORKHON_ENY                 0x10C2A 0  // 𐰪
#define UC_OLD_TURKIC_YENISEI_ENY                0x10C2B 0  // 𐰫
#define UC_OLD_TURKIC_YENISEI_ANG                0x10C2C 0  // 𐰬
#define UC_OLD_TURKIC_ORKHON_ENG                 0x10C2D 0  // 𐰭
#define UC_OLD_TURKIC_YENISEI_AENG               0x10C2E 0  // 𐰮
#define UC_OLD_TURKIC_ORKHON_EP                  0x10C2F 0  // 𐰯
#define UC_OLD_TURKIC_ORKHON_OP                  0x10C30 0  // 𐰰
#define UC_OLD_TURKIC_ORKHON_IC                  0x10C31 0  // 𐰱
#define UC_OLD_TURKIC_ORKHON_EC                  0x10C32 0  // 𐰲
#define UC_OLD_TURKIC_YENISEI_EC                 0x10C33 0  // 𐰳
#define UC_OLD_TURKIC_ORKHON_AQ                  0x10C34 0  // 𐰴
#define UC_OLD_TURKIC_YENISEI_AQ                 0x10C35 0  // 𐰵
#define UC_OLD_TURKIC_ORKHON_IQ                  0x10C36 0  // 𐰶
#define UC_OLD_TURKIC_YENISEI_IQ                 0x10C37 0  // 𐰷
#define UC_OLD_TURKIC_ORKHON_OQ                  0x10C38 0  // 𐰸
#define UC_OLD_TURKIC_YENISEI_OQ                 0x10C39 0  // 𐰹
#define UC_OLD_TURKIC_ORKHON_AR                  0x10C3A 0  // 𐰺
#define UC_OLD_TURKIC_YENISEI_AR                 0x10C3B 0  // 𐰻
#define UC_OLD_TURKIC_ORKHON_AER                 0x10C3C 0  // 𐰼
#define UC_OLD_TURKIC_ORKHON_AS                  0x10C3D 0  // 𐰽
#define UC_OLD_TURKIC_ORKHON_AES                 0x10C3E 0  // 𐰾
#define UC_OLD_TURKIC_ORKHON_ASH                 0x10C3F 0  // 𐰿
#define UC_OLD_TURKIC_YENISEI_ASH                0x10C40 0  // 𐱀
#define UC_OLD_TURKIC_ORKHON_ESH                 0x10C41 0  // 𐱁
#define UC_OLD_TURKIC_YENISEI_ESH                0x10C42 0  // 𐱂
#define UC_OLD_TURKIC_ORKHON_AT                  0x10C43 0  // 𐱃
#define UC_OLD_TURKIC_YENISEI_AT                 0x10C44 0  // 𐱄
#define UC_OLD_TURKIC_ORKHON_AET                 0x10C45 0  // 𐱅
#define UC_OLD_TURKIC_YENISEI_AET                0x10C46 0  // 𐱆
#define UC_OLD_TURKIC_ORKHON_OT                  0x10C47 0  // 𐱇
#define UC_OLD_TURKIC_ORKHON_BASH                0x10C48 0  // 𐱈
