/* old_italic.h – Unicode constants for U+10300 … U+1032F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
*
* See https://www.unicode.org/versions/latest/ for source data.

 * Old Italic may refer to:
 *

* Consistency Check:
* Total Defined Code Points: 39
* Total Significant Hex Values: 39
* Status: OK (Counts Match)

*/

#pragma once

#define UC_OLD_IT_A                              0x10300 0  // 𐌀
#define UC_OLD_IT_BE                             0x10301 0  // 𐌁
#define UC_OLD_IT_KE                             0x10302 0  // 𐌂
#define UC_OLD_IT_DE                             0x10303 0  // 𐌃
#define UC_OLD_IT_E                              0x10304 0  // 𐌄
#define UC_OLD_IT_VE                             0x10305 0  // 𐌅
#define UC_OLD_IT_ZE                             0x10306 0  // 𐌆
#define UC_OLD_IT_HE                             0x10307 0  // 𐌇
#define UC_OLD_IT_THE                            0x10308 0  // 𐌈
#define UC_OLD_IT_I                              0x10309 0  // 𐌉
#define UC_OLD_IT_KA                             0x1030A 0  // 𐌊
#define UC_OLD_IT_EL                             0x1030B 0  // 𐌋
#define UC_OLD_IT_EM                             0x1030C 0  // 𐌌
#define UC_OLD_IT_EN                             0x1030D 0  // 𐌍
#define UC_OLD_IT_ESH                            0x1030E 0  // 𐌎
#define UC_OLD_IT_O                              0x1030F 0  // 𐌏
#define UC_OLD_IT_PE                             0x10310 0  // 𐌐
#define UC_OLD_IT_SHE                            0x10311 0  // 𐌑
#define UC_OLD_IT_KU                             0x10312 0  // 𐌒
#define UC_OLD_IT_ER                             0x10313 0  // 𐌓
#define UC_OLD_IT_ES                             0x10314 0  // 𐌔
#define UC_OLD_IT_TE                             0x10315 0  // 𐌕
#define UC_OLD_IT_U                              0x10316 0  // 𐌖
#define UC_OLD_IT_EKS                            0x10317 0  // 𐌗
#define UC_OLD_IT_PHE                            0x10318 0  // 𐌘
#define UC_OLD_IT_KHE                            0x10319 0  // 𐌙
#define UC_OLD_IT_EF                             0x1031A 0  // 𐌚
#define UC_OLD_IT_ERS                            0x1031B 0  // 𐌛
#define UC_OLD_IT_CHE                            0x1031C 0  // 𐌜
#define UC_OLD_IT_II                             0x1031D 0  // 𐌝
#define UC_OLD_IT_UU                             0x1031E 0  // 𐌞
#define UC_OLD_IT_ESS                            0x1031F 0  // 𐌟
#define UC_OLD_IT_NUMERAL_ONE                    0x10320 0  // 𐌠
#define UC_OLD_IT_NUMERAL_FIVE                   0x10321 0  // 𐌡
#define UC_OLD_IT_NUMERAL_TEN                    0x10322 0  // 𐌢
#define UC_OLD_IT_NUMERAL_FIFTY                  0x10323 0  // 𐌣
#define UC_OLD_IT_YE                             0x1032D 0  // 𐌭
#define UC_OLD_IT_NORTHERN_TSE                   0x1032E 0  // 𐌮
#define UC_OLD_IT_SOUTHERN_TSE                   0x1032F 0  // 𐌯
