/* old_permic.h – Unicode constants for U+10350 … U+1037F
*
* Generated by generate_unicode_headers.py (Unicode 17.0.0)
*
* Source data for blocks: Blocks.txt (Unicode 17.0.0)
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_OLD_PERMIC_AN                         0x10350 0  // 𐍐
#define UC_OLD_PERMIC_BUR                        0x10351 0  // 𐍑
#define UC_OLD_PERMIC_GAI                        0x10352 0  // 𐍒
#define UC_OLD_PERMIC_DOI                        0x10353 0  // 𐍓
#define UC_OLD_PERMIC_E                          0x10354 0  // 𐍔
#define UC_OLD_PERMIC_ZHOI                       0x10355 0  // 𐍕
#define UC_OLD_PERMIC_DZHOI                      0x10356 0  // 𐍖
#define UC_OLD_PERMIC_ZATA                       0x10357 0  // 𐍗
#define UC_OLD_PERMIC_DZITA                      0x10358 0  // 𐍘
#define UC_OLD_PERMIC_I                          0x10359 0  // 𐍙
#define UC_OLD_PERMIC_KOKE                       0x1035A 0  // 𐍚
#define UC_OLD_PERMIC_LEI                        0x1035B 0  // 𐍛
#define UC_OLD_PERMIC_MENOE                      0x1035C 0  // 𐍜
#define UC_OLD_PERMIC_NENOE                      0x1035D 0  // 𐍝
#define UC_OLD_PERMIC_VOOI                       0x1035E 0  // 𐍞
#define UC_OLD_PERMIC_PEEI                       0x1035F 0  // 𐍟
#define UC_OLD_PERMIC_REI                        0x10360 0  // 𐍠
#define UC_OLD_PERMIC_SII                        0x10361 0  // 𐍡
#define UC_OLD_PERMIC_TAI                        0x10362 0  // 𐍢
#define UC_OLD_PERMIC_U                          0x10363 0  // 𐍣
#define UC_OLD_PERMIC_CHERY                      0x10364 0  // 𐍤
#define UC_OLD_PERMIC_SHOOI                      0x10365 0  // 𐍥
#define UC_OLD_PERMIC_SHCHOOI                    0x10366 0  // 𐍦
#define UC_OLD_PERMIC_YRY                        0x10367 0  // 𐍧
#define UC_OLD_PERMIC_YERU                       0x10368 0  // 𐍨
#define UC_OLD_PERMIC_O                          0x10369 0  // 𐍩
#define UC_OLD_PERMIC_OO                         0x1036A 0  // 𐍪
#define UC_OLD_PERMIC_EF                         0x1036B 0  // 𐍫
#define UC_OLD_PERMIC_HA                         0x1036C 0  // 𐍬
#define UC_OLD_PERMIC_TSIU                       0x1036D 0  // 𐍭
#define UC_OLD_PERMIC_VER                        0x1036E 0  // 𐍮
#define UC_OLD_PERMIC_YER                        0x1036F 0  // 𐍯
#define UC_OLD_PERMIC_YERI                       0x10370 0  // 𐍰
#define UC_OLD_PERMIC_YAT                        0x10371 0  // 𐍱
#define UC_OLD_PERMIC_IE                         0x10372 0  // 𐍲
#define UC_OLD_PERMIC_YU                         0x10373 0  // 𐍳
#define UC_OLD_PERMIC_YA                         0x10374 0  // 𐍴
#define UC_OLD_PERMIC_IA                         0x10375 0  // 𐍵
#define UC_COMBINING_OLD_PERMIC_AN               0x10376 0  // 𐍶
#define UC_COMBINING_OLD_PERMIC_DOI              0x10377 0  // 𐍷
#define UC_COMBINING_OLD_PERMIC_ZATA             0x10378 0  // 𐍸
#define UC_COMBINING_OLD_PERMIC_NENOE            0x10379 0  // 𐍹
#define UC_COMBINING_OLD_PERMIC_SII              0x1037A 0  // 𐍺
