/* Optical Character Recognition.h – Unicode constants for U+2440 … U+245F
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_OCR_HOOK                              0x2440   /* U+2440 (OCR HOOK) ⑀ */
#define UC_OCR_CHAIR                             0x2441   /* U+2441 (OCR CHAIR) ⑁ */
#define UC_OCR_FORK                              0x2442   /* U+2442 (OCR FORK) ⑂ */
#define UC_OCR_INVERTED_FORK                     0x2443   /* U+2443 (OCR INVERTED FORK) ⑃ */
#define UC_OCR_BELT_BUCKLE                       0x2444   /* U+2444 (OCR BELT BUCKLE) ⑄ */
#define UC_OCR_BOW_TIE                           0x2445   /* U+2445 (OCR BOW TIE) ⑅ */
#define UC_OCR_BRANCH_BANK_IDENTIFICATION        0x2446   /* U+2446 (OCR BRANCH BANK IDENTIFICATION) ⑆ */
#define UC_OCR_AMOUNT_OF_CHECK                   0x2447   /* U+2447 (OCR AMOUNT OF CHECK) ⑇ */
#define UC_OCR_DASH                              0x2448   /* U+2448 (OCR DASH) ⑈ */
#define UC_OCR_CUSTOMER_ACCOUNT_NUMBER           0x2449   /* U+2449 (OCR CUSTOMER ACCOUNT NUMBER) ⑉ */
#define UC_OCR_DOUBLE_BACKSLASH                  0x244A   /* U+244A (OCR DOUBLE BACKSLASH) ⑊ */
#define UC_UNKNOWN_244B                          0x244B   /* U+244B (UNKNOWN_244B) */
#define UC_UNKNOWN_244C                          0x244C   /* U+244C (UNKNOWN_244C) */
#define UC_UNKNOWN_244D                          0x244D   /* U+244D (UNKNOWN_244D) */
#define UC_UNKNOWN_244E                          0x244E   /* U+244E (UNKNOWN_244E) */
#define UC_UNKNOWN_244F                          0x244F   /* U+244F (UNKNOWN_244F) */
#define UC_UNKNOWN_2450                          0x2450   /* U+2450 (UNKNOWN_2450) */
#define UC_UNKNOWN_2451                          0x2451   /* U+2451 (UNKNOWN_2451) */
#define UC_UNKNOWN_2452                          0x2452   /* U+2452 (UNKNOWN_2452) */
#define UC_UNKNOWN_2453                          0x2453   /* U+2453 (UNKNOWN_2453) */
#define UC_UNKNOWN_2454                          0x2454   /* U+2454 (UNKNOWN_2454) */
#define UC_UNKNOWN_2455                          0x2455   /* U+2455 (UNKNOWN_2455) */
#define UC_UNKNOWN_2456                          0x2456   /* U+2456 (UNKNOWN_2456) */
#define UC_UNKNOWN_2457                          0x2457   /* U+2457 (UNKNOWN_2457) */
#define UC_UNKNOWN_2458                          0x2458   /* U+2458 (UNKNOWN_2458) */
#define UC_UNKNOWN_2459                          0x2459   /* U+2459 (UNKNOWN_2459) */
#define UC_UNKNOWN_245A                          0x245A   /* U+245A (UNKNOWN_245A) */
#define UC_UNKNOWN_245B                          0x245B   /* U+245B (UNKNOWN_245B) */
#define UC_UNKNOWN_245C                          0x245C   /* U+245C (UNKNOWN_245C) */
#define UC_UNKNOWN_245D                          0x245D   /* U+245D (UNKNOWN_245D) */
#define UC_UNKNOWN_245E                          0x245E   /* U+245E (UNKNOWN_245E) */
#define UC_UNKNOWN_245F                          0x245F   /* U+245F (UNKNOWN_245F) */
