/* oriya.h – Unicode constants for U+0B66 … U+0B77
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_UC_ZERO                               0x0B66 0  // ୦
#define UC_UC_ONE                                0x0B67 0  // ୧
#define UC_UC_TWO                                0x0B68 0  // ୨
#define UC_UC_THREE                              0x0B69 0  // ୩
#define UC_UC_FOUR                               0x0B6A 0  // ୪
#define UC_UC_FIVE                               0x0B6B 0  // ୫
#define UC_UC_SIX                                0x0B6C 0  // ୬
#define UC_UC_SEVEN                              0x0B6D 0  // ୭
#define UC_UC_EIGHT                              0x0B6E 0  // ୮
#define UC_UC_NINE                               0x0B6F 0  // ୯
#define UC_UC_ISSHAR                             0x0B70 0  // ୰
#define UC_UC_WA                                 0x0B71 0  // ୱ
#define UC_UC_FRACTION_ONE_QUARTER               0x0B72 0  // ୲
#define UC_UC_FRACTION_ONE_HALF                  0x0B73 0  // ୳
#define UC_UC_FRACTION_THREE_QUARTERS            0x0B74 0  // ୴
#define UC_UC_FRACTION_ONE_SIXTEENTH             0x0B75 0  // ୵
#define UC_UC_FRACTION_ONE_EIGHTH                0x0B76 0  // ୶
#define UC_UC_FRACTION_THREE_SIXTEENTHS          0x0B77 0  // ୷
