/* Palmyrene.h – Unicode constants for U+10860 … U+1087F
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_PALMYRENE_LETTER_ALEPH                0x10860   /* U+10860 (PALMYRENE LETTER ALEPH) 𐡠 */
#define UC_PALMYRENE_LETTER_BETH                 0x10861   /* U+10861 (PALMYRENE LETTER BETH) 𐡡 */
#define UC_PALMYRENE_LETTER_GIMEL                0x10862   /* U+10862 (PALMYRENE LETTER GIMEL) 𐡢 */
#define UC_PALMYRENE_LETTER_DALETH               0x10863   /* U+10863 (PALMYRENE LETTER DALETH) 𐡣 */
#define UC_PALMYRENE_LETTER_HE                   0x10864   /* U+10864 (PALMYRENE LETTER HE) 𐡤 */
#define UC_PALMYRENE_LETTER_WAW                  0x10865   /* U+10865 (PALMYRENE LETTER WAW) 𐡥 */
#define UC_PALMYRENE_LETTER_ZAYIN                0x10866   /* U+10866 (PALMYRENE LETTER ZAYIN) 𐡦 */
#define UC_PALMYRENE_LETTER_HETH                 0x10867   /* U+10867 (PALMYRENE LETTER HETH) 𐡧 */
#define UC_PALMYRENE_LETTER_TETH                 0x10868   /* U+10868 (PALMYRENE LETTER TETH) 𐡨 */
#define UC_PALMYRENE_LETTER_YODH                 0x10869   /* U+10869 (PALMYRENE LETTER YODH) 𐡩 */
#define UC_PALMYRENE_LETTER_KAPH                 0x1086A   /* U+1086A (PALMYRENE LETTER KAPH) 𐡪 */
#define UC_PALMYRENE_LETTER_LAMEDH               0x1086B   /* U+1086B (PALMYRENE LETTER LAMEDH) 𐡫 */
#define UC_PALMYRENE_LETTER_MEM                  0x1086C   /* U+1086C (PALMYRENE LETTER MEM) 𐡬 */
#define UC_PALMYRENE_LETTER_FINAL_NUN            0x1086D   /* U+1086D (PALMYRENE LETTER FINAL NUN) 𐡭 */
#define UC_PALMYRENE_LETTER_NUN                  0x1086E   /* U+1086E (PALMYRENE LETTER NUN) 𐡮 */
#define UC_PALMYRENE_LETTER_SAMEKH               0x1086F   /* U+1086F (PALMYRENE LETTER SAMEKH) 𐡯 */
#define UC_PALMYRENE_LETTER_AYIN                 0x10870   /* U+10870 (PALMYRENE LETTER AYIN) 𐡰 */
#define UC_PALMYRENE_LETTER_PE                   0x10871   /* U+10871 (PALMYRENE LETTER PE) 𐡱 */
#define UC_PALMYRENE_LETTER_SADHE                0x10872   /* U+10872 (PALMYRENE LETTER SADHE) 𐡲 */
#define UC_PALMYRENE_LETTER_QOPH                 0x10873   /* U+10873 (PALMYRENE LETTER QOPH) 𐡳 */
#define UC_PALMYRENE_LETTER_RESH                 0x10874   /* U+10874 (PALMYRENE LETTER RESH) 𐡴 */
#define UC_PALMYRENE_LETTER_SHIN                 0x10875   /* U+10875 (PALMYRENE LETTER SHIN) 𐡵 */
#define UC_PALMYRENE_LETTER_TAW                  0x10876   /* U+10876 (PALMYRENE LETTER TAW) 𐡶 */
#define UC_PALMYRENE_LEFT_POINTING_FLEURON       0x10877   /* U+10877 (PALMYRENE LEFT-POINTING FLEURON) 𐡷 */
#define UC_PALMYRENE_RIGHT_POINTING_FLEURON      0x10878   /* U+10878 (PALMYRENE RIGHT-POINTING FLEURON) 𐡸 */
#define UC_PALMYRENE_NUMBER_ONE                  0x10879   /* U+10879 (PALMYRENE NUMBER ONE) 𐡹 */
#define UC_PALMYRENE_NUMBER_TWO                  0x1087A   /* U+1087A (PALMYRENE NUMBER TWO) 𐡺 */
#define UC_PALMYRENE_NUMBER_THREE                0x1087B   /* U+1087B (PALMYRENE NUMBER THREE) 𐡻 */
#define UC_PALMYRENE_NUMBER_FOUR                 0x1087C   /* U+1087C (PALMYRENE NUMBER FOUR) 𐡼 */
#define UC_PALMYRENE_NUMBER_FIVE                 0x1087D   /* U+1087D (PALMYRENE NUMBER FIVE) 𐡽 */
#define UC_PALMYRENE_NUMBER_TEN                  0x1087E   /* U+1087E (PALMYRENE NUMBER TEN) 𐡾 */
#define UC_PALMYRENE_NUMBER_TWENTY               0x1087F   /* U+1087F (PALMYRENE NUMBER TWENTY) 𐡿 */
