/* phoenician.h – Unicode constants for U+10900 … U+1091F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_PHOENICIAN_ALF                        0x10900 0  // 𐤀
#define UC_PHOENICIAN_BET                        0x10901 0  // 𐤁
#define UC_PHOENICIAN_GAML                       0x10902 0  // 𐤂
#define UC_PHOENICIAN_DELT                       0x10903 0  // 𐤃
#define UC_PHOENICIAN_HE                         0x10904 0  // 𐤄
#define UC_PHOENICIAN_WAU                        0x10905 0  // 𐤅
#define UC_PHOENICIAN_ZAI                        0x10906 0  // 𐤆
#define UC_PHOENICIAN_HET                        0x10907 0  // 𐤇
#define UC_PHOENICIAN_TET                        0x10908 0  // 𐤈
#define UC_PHOENICIAN_YOD                        0x10909 0  // 𐤉
#define UC_PHOENICIAN_KAF                        0x1090A 0  // 𐤊
#define UC_PHOENICIAN_LAMD                       0x1090B 0  // 𐤋
#define UC_PHOENICIAN_MEM                        0x1090C 0  // 𐤌
#define UC_PHOENICIAN_NUN                        0x1090D 0  // 𐤍
#define UC_PHOENICIAN_SEMK                       0x1090E 0  // 𐤎
#define UC_PHOENICIAN_AIN                        0x1090F 0  // 𐤏
#define UC_PHOENICIAN_PE                         0x10910 0  // 𐤐
#define UC_PHOENICIAN_SADE                       0x10911 0  // 𐤑
#define UC_PHOENICIAN_QOF                        0x10912 0  // 𐤒
#define UC_PHOENICIAN_ROSH                       0x10913 0  // 𐤓
#define UC_PHOENICIAN_SHIN                       0x10914 0  // 𐤔
#define UC_PHOENICIAN_TAU                        0x10915 0  // 𐤕
#define UC_PHOENICIAN_ONE                        0x10916 0  // 𐤖
#define UC_PHOENICIAN_TEN                        0x10917 0  // 𐤗
#define UC_PHOENICIAN_TWENTY                     0x10918 0  // 𐤘
#define UC_PHOENICIAN_ONE_HUNDRED                0x10919 0  // 𐤙
#define UC_PHOENICIAN_TWO                        0x1091A 0  // 𐤚
#define UC_PHOENICIAN_THREE                      0x1091B 0  // 𐤛
#define UC_PHOENICIAN_WORD_SEPARATOR             0x1091F 0  // 𐤟
