/* rumi_numeral_symbols.h – Unicode constants for U+10E60 … U+10E7E
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_RUMI_DIGIT_ONE                        0x10E60 0  // 𐹠
#define UC_RUMI_DIGIT_TWO                        0x10E61 0  // 𐹡
#define UC_RUMI_DIGIT_THREE                      0x10E62 0  // 𐹢
#define UC_RUMI_DIGIT_FOUR                       0x10E63 0  // 𐹣
#define UC_RUMI_DIGIT_FIVE                       0x10E64 0  // 𐹤
#define UC_RUMI_DIGIT_SIX                        0x10E65 0  // 𐹥
#define UC_RUMI_DIGIT_SEVEN                      0x10E66 0  // 𐹦
#define UC_RUMI_DIGIT_EIGHT                      0x10E67 0  // 𐹧
#define UC_RUMI_DIGIT_NINE                       0x10E68 0  // 𐹨
#define UC_RUMI_NUMBER_TEN                       0x10E69 0  // 𐹩
#define UC_RUMI_NUMBER_TWENTY                    0x10E6A 0  // 𐹪
#define UC_RUMI_NUMBER_THIRTY                    0x10E6B 0  // 𐹫
#define UC_RUMI_NUMBER_FORTY                     0x10E6C 0  // 𐹬
#define UC_RUMI_NUMBER_FIFTY                     0x10E6D 0  // 𐹭
#define UC_RUMI_NUMBER_SIXTY                     0x10E6E 0  // 𐹮
#define UC_RUMI_NUMBER_SEVENTY                   0x10E6F 0  // 𐹯
#define UC_RUMI_NUMBER_EIGHTY                    0x10E70 0  // 𐹰
#define UC_RUMI_NUMBER_NINETY                    0x10E71 0  // 𐹱
#define UC_RUMI_NUMBER_ONE_HUNDRED               0x10E72 0  // 𐹲
#define UC_RUMI_NUMBER_TWO_HUNDRED               0x10E73 0  // 𐹳
#define UC_RUMI_NUMBER_THREE_HUNDRED             0x10E74 0  // 𐹴
#define UC_RUMI_NUMBER_FOUR_HUNDRED              0x10E75 0  // 𐹵
#define UC_RUMI_NUMBER_FIVE_HUNDRED              0x10E76 0  // 𐹶
#define UC_RUMI_NUMBER_SIX_HUNDRED               0x10E77 0  // 𐹷
#define UC_RUMI_NUMBER_SEVEN_HUNDRED             0x10E78 0  // 𐹸
#define UC_RUMI_NUMBER_EIGHT_HUNDRED             0x10E79 0  // 𐹹
#define UC_RUMI_NUMBER_NINE_HUNDRED              0x10E7A 0  // 𐹺
#define UC_RUMI_FRACTION_ONE_HALF                0x10E7B 0  // 𐹻
#define UC_RUMI_FRACTION_ONE_QUARTER             0x10E7C 0  // 𐹼
#define UC_RUMI_FRACTION_ONE_THIRD               0x10E7D 0  // 𐹽
#define UC_RUMI_FRACTION_TWO_THIRDS              0x10E7E 0  // 𐹾
