/* Sharada.h – Unicode constants for U+11180 … U+111DF
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_SHARADA_SIGN_CANDRABINDU              0x11180   /* U+11180 (SHARADA SIGN CANDRABINDU) 𑆀 */
#define UC_SHARADA_SIGN_ANUSVARA                 0x11181   /* U+11181 (SHARADA SIGN ANUSVARA) 𑆁 */
#define UC_SHARADA_SIGN_VISARGA                  0x11182   /* U+11182 (SHARADA SIGN VISARGA) 𑆂 */
#define UC_SHARADA_LETTER_A                      0x11183   /* U+11183 (SHARADA LETTER A) 𑆃 */
#define UC_SHARADA_LETTER_AA                     0x11184   /* U+11184 (SHARADA LETTER AA) 𑆄 */
#define UC_SHARADA_LETTER_I                      0x11185   /* U+11185 (SHARADA LETTER I) 𑆅 */
#define UC_SHARADA_LETTER_II                     0x11186   /* U+11186 (SHARADA LETTER II) 𑆆 */
#define UC_SHARADA_LETTER_U                      0x11187   /* U+11187 (SHARADA LETTER U) 𑆇 */
#define UC_SHARADA_LETTER_UU                     0x11188   /* U+11188 (SHARADA LETTER UU) 𑆈 */
#define UC_SHARADA_LETTER_VOCALIC_R              0x11189   /* U+11189 (SHARADA LETTER VOCALIC R) 𑆉 */
#define UC_SHARADA_LETTER_VOCALIC_RR             0x1118A   /* U+1118A (SHARADA LETTER VOCALIC RR) 𑆊 */
#define UC_SHARADA_LETTER_VOCALIC_L              0x1118B   /* U+1118B (SHARADA LETTER VOCALIC L) 𑆋 */
#define UC_SHARADA_LETTER_VOCALIC_LL             0x1118C   /* U+1118C (SHARADA LETTER VOCALIC LL) 𑆌 */
#define UC_SHARADA_LETTER_E                      0x1118D   /* U+1118D (SHARADA LETTER E) 𑆍 */
#define UC_SHARADA_LETTER_AI                     0x1118E   /* U+1118E (SHARADA LETTER AI) 𑆎 */
#define UC_SHARADA_LETTER_O                      0x1118F   /* U+1118F (SHARADA LETTER O) 𑆏 */
#define UC_SHARADA_LETTER_AU                     0x11190   /* U+11190 (SHARADA LETTER AU) 𑆐 */
#define UC_SHARADA_LETTER_KA                     0x11191   /* U+11191 (SHARADA LETTER KA) 𑆑 */
#define UC_SHARADA_LETTER_KHA                    0x11192   /* U+11192 (SHARADA LETTER KHA) 𑆒 */
#define UC_SHARADA_LETTER_GA                     0x11193   /* U+11193 (SHARADA LETTER GA) 𑆓 */
#define UC_SHARADA_LETTER_GHA                    0x11194   /* U+11194 (SHARADA LETTER GHA) 𑆔 */
#define UC_SHARADA_LETTER_NGA                    0x11195   /* U+11195 (SHARADA LETTER NGA) 𑆕 */
#define UC_SHARADA_LETTER_CA                     0x11196   /* U+11196 (SHARADA LETTER CA) 𑆖 */
#define UC_SHARADA_LETTER_CHA                    0x11197   /* U+11197 (SHARADA LETTER CHA) 𑆗 */
#define UC_SHARADA_LETTER_JA                     0x11198   /* U+11198 (SHARADA LETTER JA) 𑆘 */
#define UC_SHARADA_LETTER_JHA                    0x11199   /* U+11199 (SHARADA LETTER JHA) 𑆙 */
#define UC_SHARADA_LETTER_NYA                    0x1119A   /* U+1119A (SHARADA LETTER NYA) 𑆚 */
#define UC_SHARADA_LETTER_TTA                    0x1119B   /* U+1119B (SHARADA LETTER TTA) 𑆛 */
#define UC_SHARADA_LETTER_TTHA                   0x1119C   /* U+1119C (SHARADA LETTER TTHA) 𑆜 */
#define UC_SHARADA_LETTER_DDA                    0x1119D   /* U+1119D (SHARADA LETTER DDA) 𑆝 */
#define UC_SHARADA_LETTER_DDHA                   0x1119E   /* U+1119E (SHARADA LETTER DDHA) 𑆞 */
#define UC_SHARADA_LETTER_NNA                    0x1119F   /* U+1119F (SHARADA LETTER NNA) 𑆟 */
#define UC_SHARADA_LETTER_TA                     0x111A0   /* U+111A0 (SHARADA LETTER TA) 𑆠 */
#define UC_SHARADA_LETTER_THA                    0x111A1   /* U+111A1 (SHARADA LETTER THA) 𑆡 */
#define UC_SHARADA_LETTER_DA                     0x111A2   /* U+111A2 (SHARADA LETTER DA) 𑆢 */
#define UC_SHARADA_LETTER_DHA                    0x111A3   /* U+111A3 (SHARADA LETTER DHA) 𑆣 */
#define UC_SHARADA_LETTER_NA                     0x111A4   /* U+111A4 (SHARADA LETTER NA) 𑆤 */
#define UC_SHARADA_LETTER_PA                     0x111A5   /* U+111A5 (SHARADA LETTER PA) 𑆥 */
#define UC_SHARADA_LETTER_PHA                    0x111A6   /* U+111A6 (SHARADA LETTER PHA) 𑆦 */
#define UC_SHARADA_LETTER_BA                     0x111A7   /* U+111A7 (SHARADA LETTER BA) 𑆧 */
#define UC_SHARADA_LETTER_BHA                    0x111A8   /* U+111A8 (SHARADA LETTER BHA) 𑆨 */
#define UC_SHARADA_LETTER_MA                     0x111A9   /* U+111A9 (SHARADA LETTER MA) 𑆩 */
#define UC_SHARADA_LETTER_YA                     0x111AA   /* U+111AA (SHARADA LETTER YA) 𑆪 */
#define UC_SHARADA_LETTER_RA                     0x111AB   /* U+111AB (SHARADA LETTER RA) 𑆫 */
#define UC_SHARADA_LETTER_LA                     0x111AC   /* U+111AC (SHARADA LETTER LA) 𑆬 */
#define UC_SHARADA_LETTER_LLA                    0x111AD   /* U+111AD (SHARADA LETTER LLA) 𑆭 */
#define UC_SHARADA_LETTER_VA                     0x111AE   /* U+111AE (SHARADA LETTER VA) 𑆮 */
#define UC_SHARADA_LETTER_SHA                    0x111AF   /* U+111AF (SHARADA LETTER SHA) 𑆯 */
#define UC_SHARADA_LETTER_SSA                    0x111B0   /* U+111B0 (SHARADA LETTER SSA) 𑆰 */
#define UC_SHARADA_LETTER_SA                     0x111B1   /* U+111B1 (SHARADA LETTER SA) 𑆱 */
#define UC_SHARADA_LETTER_HA                     0x111B2   /* U+111B2 (SHARADA LETTER HA) 𑆲 */
#define UC_SHARADA_VOWEL_SIGN_AA                 0x111B3   /* U+111B3 (SHARADA VOWEL SIGN AA) 𑆳 */
#define UC_SHARADA_VOWEL_SIGN_I                  0x111B4   /* U+111B4 (SHARADA VOWEL SIGN I) 𑆴 */
#define UC_SHARADA_VOWEL_SIGN_II                 0x111B5   /* U+111B5 (SHARADA VOWEL SIGN II) 𑆵 */
#define UC_SHARADA_VOWEL_SIGN_U                  0x111B6   /* U+111B6 (SHARADA VOWEL SIGN U) 𑆶 */
#define UC_SHARADA_VOWEL_SIGN_UU                 0x111B7   /* U+111B7 (SHARADA VOWEL SIGN UU) 𑆷 */
#define UC_SHARADA_VOWEL_SIGN_VOCALIC_R          0x111B8   /* U+111B8 (SHARADA VOWEL SIGN VOCALIC R) 𑆸 */
#define UC_SHARADA_VOWEL_SIGN_VOCALIC_RR         0x111B9   /* U+111B9 (SHARADA VOWEL SIGN VOCALIC RR) 𑆹 */
#define UC_SHARADA_VOWEL_SIGN_VOCALIC_L          0x111BA   /* U+111BA (SHARADA VOWEL SIGN VOCALIC L) 𑆺 */
#define UC_SHARADA_VOWEL_SIGN_VOCALIC_LL         0x111BB   /* U+111BB (SHARADA VOWEL SIGN VOCALIC LL) 𑆻 */
#define UC_SHARADA_VOWEL_SIGN_E                  0x111BC   /* U+111BC (SHARADA VOWEL SIGN E) 𑆼 */
#define UC_SHARADA_VOWEL_SIGN_AI                 0x111BD   /* U+111BD (SHARADA VOWEL SIGN AI) 𑆽 */
#define UC_SHARADA_VOWEL_SIGN_O                  0x111BE   /* U+111BE (SHARADA VOWEL SIGN O) 𑆾 */
#define UC_SHARADA_VOWEL_SIGN_AU                 0x111BF   /* U+111BF (SHARADA VOWEL SIGN AU) 𑆿 */
#define UC_SHARADA_SIGN_VIRAMA                   0x111C0   /* U+111C0 (SHARADA SIGN VIRAMA) 𑇀 */
#define UC_SHARADA_SIGN_AVAGRAHA                 0x111C1   /* U+111C1 (SHARADA SIGN AVAGRAHA) 𑇁 */
#define UC_SHARADA_SIGN_JIHVAMULIYA              0x111C2   /* U+111C2 (SHARADA SIGN JIHVAMULIYA) 𑇂 */
#define UC_SHARADA_SIGN_UPADHMANIYA              0x111C3   /* U+111C3 (SHARADA SIGN UPADHMANIYA) 𑇃 */
#define UC_SHARADA_OM                            0x111C4   /* U+111C4 (SHARADA OM) 𑇄 */
#define UC_SHARADA_DANDA                         0x111C5   /* U+111C5 (SHARADA DANDA) 𑇅 */
#define UC_SHARADA_DOUBLE_DANDA                  0x111C6   /* U+111C6 (SHARADA DOUBLE DANDA) 𑇆 */
#define UC_SHARADA_ABBREVIATION_SIGN             0x111C7   /* U+111C7 (SHARADA ABBREVIATION SIGN) 𑇇 */
#define UC_SHARADA_SEPARATOR                     0x111C8   /* U+111C8 (SHARADA SEPARATOR) 𑇈 */
#define UC_SHARADA_SANDHI_MARK                   0x111C9   /* U+111C9 (SHARADA SANDHI MARK) 𑇉 */
#define UC_SHARADA_SIGN_NUKTA                    0x111CA   /* U+111CA (SHARADA SIGN NUKTA) 𑇊 */
#define UC_SHARADA_VOWEL_MODIFIER_MARK           0x111CB   /* U+111CB (SHARADA VOWEL MODIFIER MARK) 𑇋 */
#define UC_SHARADA_EXTRA_SHORT_VOWEL_MARK        0x111CC   /* U+111CC (SHARADA EXTRA SHORT VOWEL MARK) 𑇌 */
#define UC_SHARADA_SUTRA_MARK                    0x111CD   /* U+111CD (SHARADA SUTRA MARK) 𑇍 */
#define UC_SHARADA_VOWEL_SIGN_PRISHTHAMATRA_E    0x111CE   /* U+111CE (SHARADA VOWEL SIGN PRISHTHAMATRA E) 𑇎 */
#define UC_SHARADA_SIGN_INVERTED_CANDRABINDU     0x111CF   /* U+111CF (SHARADA SIGN INVERTED CANDRABINDU) 𑇏 */
#define UC_SHARADA_DIGIT_ZERO                    0x111D0   /* U+111D0 (SHARADA DIGIT ZERO) 𑇐 */
#define UC_SHARADA_DIGIT_ONE                     0x111D1   /* U+111D1 (SHARADA DIGIT ONE) 𑇑 */
#define UC_SHARADA_DIGIT_TWO                     0x111D2   /* U+111D2 (SHARADA DIGIT TWO) 𑇒 */
#define UC_SHARADA_DIGIT_THREE                   0x111D3   /* U+111D3 (SHARADA DIGIT THREE) 𑇓 */
#define UC_SHARADA_DIGIT_FOUR                    0x111D4   /* U+111D4 (SHARADA DIGIT FOUR) 𑇔 */
#define UC_SHARADA_DIGIT_FIVE                    0x111D5   /* U+111D5 (SHARADA DIGIT FIVE) 𑇕 */
#define UC_SHARADA_DIGIT_SIX                     0x111D6   /* U+111D6 (SHARADA DIGIT SIX) 𑇖 */
#define UC_SHARADA_DIGIT_SEVEN                   0x111D7   /* U+111D7 (SHARADA DIGIT SEVEN) 𑇗 */
#define UC_SHARADA_DIGIT_EIGHT                   0x111D8   /* U+111D8 (SHARADA DIGIT EIGHT) 𑇘 */
#define UC_SHARADA_DIGIT_NINE                    0x111D9   /* U+111D9 (SHARADA DIGIT NINE) 𑇙 */
#define UC_SHARADA_EKAM                          0x111DA   /* U+111DA (SHARADA EKAM) 𑇚 */
#define UC_SHARADA_SIGN_SIDDHAM                  0x111DB   /* U+111DB (SHARADA SIGN SIDDHAM) 𑇛 */
#define UC_SHARADA_HEADSTROKE                    0x111DC   /* U+111DC (SHARADA HEADSTROKE) 𑇜 */
#define UC_SHARADA_CONTINUATION_SIGN             0x111DD   /* U+111DD (SHARADA CONTINUATION SIGN) 𑇝 */
#define UC_SHARADA_SECTION_MARK_1                0x111DE   /* U+111DE (SHARADA SECTION MARK-1) 𑇞 */
#define UC_SHARADA_SECTION_MARK_2                0x111DF   /* U+111DF (SHARADA SECTION MARK-2) 𑇟 */
