/* Shavian.h – Unicode constants for U+10450 … U+1047F
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_SHAVIAN_LETTER_PEEP                   0x10450   /* U+10450 (SHAVIAN LETTER PEEP) 𐑐 */
#define UC_SHAVIAN_LETTER_TOT                    0x10451   /* U+10451 (SHAVIAN LETTER TOT) 𐑑 */
#define UC_SHAVIAN_LETTER_KICK                   0x10452   /* U+10452 (SHAVIAN LETTER KICK) 𐑒 */
#define UC_SHAVIAN_LETTER_FEE                    0x10453   /* U+10453 (SHAVIAN LETTER FEE) 𐑓 */
#define UC_SHAVIAN_LETTER_THIGH                  0x10454   /* U+10454 (SHAVIAN LETTER THIGH) 𐑔 */
#define UC_SHAVIAN_LETTER_SO                     0x10455   /* U+10455 (SHAVIAN LETTER SO) 𐑕 */
#define UC_SHAVIAN_LETTER_SURE                   0x10456   /* U+10456 (SHAVIAN LETTER SURE) 𐑖 */
#define UC_SHAVIAN_LETTER_CHURCH                 0x10457   /* U+10457 (SHAVIAN LETTER CHURCH) 𐑗 */
#define UC_SHAVIAN_LETTER_YEA                    0x10458   /* U+10458 (SHAVIAN LETTER YEA) 𐑘 */
#define UC_SHAVIAN_LETTER_HUNG                   0x10459   /* U+10459 (SHAVIAN LETTER HUNG) 𐑙 */
#define UC_SHAVIAN_LETTER_BIB                    0x1045A   /* U+1045A (SHAVIAN LETTER BIB) 𐑚 */
#define UC_SHAVIAN_LETTER_DEAD                   0x1045B   /* U+1045B (SHAVIAN LETTER DEAD) 𐑛 */
#define UC_SHAVIAN_LETTER_GAG                    0x1045C   /* U+1045C (SHAVIAN LETTER GAG) 𐑜 */
#define UC_SHAVIAN_LETTER_VOW                    0x1045D   /* U+1045D (SHAVIAN LETTER VOW) 𐑝 */
#define UC_SHAVIAN_LETTER_THEY                   0x1045E   /* U+1045E (SHAVIAN LETTER THEY) 𐑞 */
#define UC_SHAVIAN_LETTER_ZOO                    0x1045F   /* U+1045F (SHAVIAN LETTER ZOO) 𐑟 */
#define UC_SHAVIAN_LETTER_MEASURE                0x10460   /* U+10460 (SHAVIAN LETTER MEASURE) 𐑠 */
#define UC_SHAVIAN_LETTER_JUDGE                  0x10461   /* U+10461 (SHAVIAN LETTER JUDGE) 𐑡 */
#define UC_SHAVIAN_LETTER_WOE                    0x10462   /* U+10462 (SHAVIAN LETTER WOE) 𐑢 */
#define UC_SHAVIAN_LETTER_HA_HA                  0x10463   /* U+10463 (SHAVIAN LETTER HA-HA) 𐑣 */
#define UC_SHAVIAN_LETTER_LOLL                   0x10464   /* U+10464 (SHAVIAN LETTER LOLL) 𐑤 */
#define UC_SHAVIAN_LETTER_MIME                   0x10465   /* U+10465 (SHAVIAN LETTER MIME) 𐑥 */
#define UC_SHAVIAN_LETTER_IF                     0x10466   /* U+10466 (SHAVIAN LETTER IF) 𐑦 */
#define UC_SHAVIAN_LETTER_EGG                    0x10467   /* U+10467 (SHAVIAN LETTER EGG) 𐑧 */
#define UC_SHAVIAN_LETTER_ASH                    0x10468   /* U+10468 (SHAVIAN LETTER ASH) 𐑨 */
#define UC_SHAVIAN_LETTER_ADO                    0x10469   /* U+10469 (SHAVIAN LETTER ADO) 𐑩 */
#define UC_SHAVIAN_LETTER_ON                     0x1046A   /* U+1046A (SHAVIAN LETTER ON) 𐑪 */
#define UC_SHAVIAN_LETTER_WOOL                   0x1046B   /* U+1046B (SHAVIAN LETTER WOOL) 𐑫 */
#define UC_SHAVIAN_LETTER_OUT                    0x1046C   /* U+1046C (SHAVIAN LETTER OUT) 𐑬 */
#define UC_SHAVIAN_LETTER_AH                     0x1046D   /* U+1046D (SHAVIAN LETTER AH) 𐑭 */
#define UC_SHAVIAN_LETTER_ROAR                   0x1046E   /* U+1046E (SHAVIAN LETTER ROAR) 𐑮 */
#define UC_SHAVIAN_LETTER_NUN                    0x1046F   /* U+1046F (SHAVIAN LETTER NUN) 𐑯 */
#define UC_SHAVIAN_LETTER_EAT                    0x10470   /* U+10470 (SHAVIAN LETTER EAT) 𐑰 */
#define UC_SHAVIAN_LETTER_AGE                    0x10471   /* U+10471 (SHAVIAN LETTER AGE) 𐑱 */
#define UC_SHAVIAN_LETTER_ICE                    0x10472   /* U+10472 (SHAVIAN LETTER ICE) 𐑲 */
#define UC_SHAVIAN_LETTER_UP                     0x10473   /* U+10473 (SHAVIAN LETTER UP) 𐑳 */
#define UC_SHAVIAN_LETTER_OAK                    0x10474   /* U+10474 (SHAVIAN LETTER OAK) 𐑴 */
#define UC_SHAVIAN_LETTER_OOZE                   0x10475   /* U+10475 (SHAVIAN LETTER OOZE) 𐑵 */
#define UC_SHAVIAN_LETTER_OIL                    0x10476   /* U+10476 (SHAVIAN LETTER OIL) 𐑶 */
#define UC_SHAVIAN_LETTER_AWE                    0x10477   /* U+10477 (SHAVIAN LETTER AWE) 𐑷 */
#define UC_SHAVIAN_LETTER_ARE                    0x10478   /* U+10478 (SHAVIAN LETTER ARE) 𐑸 */
#define UC_SHAVIAN_LETTER_OR                     0x10479   /* U+10479 (SHAVIAN LETTER OR) 𐑹 */
#define UC_SHAVIAN_LETTER_AIR                    0x1047A   /* U+1047A (SHAVIAN LETTER AIR) 𐑺 */
#define UC_SHAVIAN_LETTER_ERR                    0x1047B   /* U+1047B (SHAVIAN LETTER ERR) 𐑻 */
#define UC_SHAVIAN_LETTER_ARRAY                  0x1047C   /* U+1047C (SHAVIAN LETTER ARRAY) 𐑼 */
#define UC_SHAVIAN_LETTER_EAR                    0x1047D   /* U+1047D (SHAVIAN LETTER EAR) 𐑽 */
#define UC_SHAVIAN_LETTER_IAN                    0x1047E   /* U+1047E (SHAVIAN LETTER IAN) 𐑾 */
#define UC_SHAVIAN_LETTER_YEW                    0x1047F   /* U+1047F (SHAVIAN LETTER YEW) 𐑿 */
