/* shavian.h – Unicode constants for U+10450 … U+1047F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.

* Consistency Check:
* Total Defined Code Points: 48
* Total Significant Hex Values: 48
* Status: OK (Counts Match)

*/

#pragma once

#define UC_SH_PEEP                               0x10450 0  // 𐑐
#define UC_SH_TOT                                0x10451 0  // 𐑑
#define UC_SH_KICK                               0x10452 0  // 𐑒
#define UC_SH_FEE                                0x10453 0  // 𐑓
#define UC_SH_THIGH                              0x10454 0  // 𐑔
#define UC_SH_SO                                 0x10455 0  // 𐑕
#define UC_SH_SURE                               0x10456 0  // 𐑖
#define UC_SH_CHURCH                             0x10457 0  // 𐑗
#define UC_SH_YEA                                0x10458 0  // 𐑘
#define UC_SH_HUNG                               0x10459 0  // 𐑙
#define UC_SH_BIB                                0x1045A 0  // 𐑚
#define UC_SH_DEAD                               0x1045B 0  // 𐑛
#define UC_SH_GAG                                0x1045C 0  // 𐑜
#define UC_SH_VOW                                0x1045D 0  // 𐑝
#define UC_SH_THEY                               0x1045E 0  // 𐑞
#define UC_SH_ZOO                                0x1045F 0  // 𐑟
#define UC_SH_MEASURE                            0x10460 0  // 𐑠
#define UC_SH_JUDGE                              0x10461 0  // 𐑡
#define UC_SH_WOE                                0x10462 0  // 𐑢
#define UC_SH_HA_HA                              0x10463 0  // 𐑣
#define UC_SH_LOLL                               0x10464 0  // 𐑤
#define UC_SH_MIME                               0x10465 0  // 𐑥
#define UC_SH_IF                                 0x10466 0  // 𐑦
#define UC_SH_EGG                                0x10467 0  // 𐑧
#define UC_SH_ASH                                0x10468 0  // 𐑨
#define UC_SH_ADO                                0x10469 0  // 𐑩
#define UC_SH_ON                                 0x1046A 0  // 𐑪
#define UC_SH_WOOL                               0x1046B 0  // 𐑫
#define UC_SH_OUT                                0x1046C 0  // 𐑬
#define UC_SH_AH                                 0x1046D 0  // 𐑭
#define UC_SH_ROAR                               0x1046E 0  // 𐑮
#define UC_SH_NUN                                0x1046F 0  // 𐑯
#define UC_SH_EAT                                0x10470 0  // 𐑰
#define UC_SH_AGE                                0x10471 0  // 𐑱
#define UC_SH_ICE                                0x10472 0  // 𐑲
#define UC_SH_UP                                 0x10473 0  // 𐑳
#define UC_SH_OAK                                0x10474 0  // 𐑴
#define UC_SH_OOZE                               0x10475 0  // 𐑵
#define UC_SH_OIL                                0x10476 0  // 𐑶
#define UC_SH_AWE                                0x10477 0  // 𐑷
#define UC_SH_ARE                                0x10478 0  // 𐑸
#define UC_SH_OR                                 0x10479 0  // 𐑹
#define UC_SH_AIR                                0x1047A 0  // 𐑺
#define UC_SH_ERR                                0x1047B 0  // 𐑻
#define UC_SH_ARRAY                              0x1047C 0  // 𐑼
#define UC_SH_EAR                                0x1047D 0  // 𐑽
#define UC_SH_IAN                                0x1047E 0  // 𐑾
#define UC_SH_YEW                                0x1047F 0  // 𐑿
