/* Siddham.h – Unicode constants for U+11580 … U+115FF
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_SIDDHAM_LETTER_A                      0x11580   /* U+11580 (SIDDHAM LETTER A) 𑖀 */
#define UC_SIDDHAM_LETTER_AA                     0x11581   /* U+11581 (SIDDHAM LETTER AA) 𑖁 */
#define UC_SIDDHAM_LETTER_I                      0x11582   /* U+11582 (SIDDHAM LETTER I) 𑖂 */
#define UC_SIDDHAM_LETTER_II                     0x11583   /* U+11583 (SIDDHAM LETTER II) 𑖃 */
#define UC_SIDDHAM_LETTER_U                      0x11584   /* U+11584 (SIDDHAM LETTER U) 𑖄 */
#define UC_SIDDHAM_LETTER_UU                     0x11585   /* U+11585 (SIDDHAM LETTER UU) 𑖅 */
#define UC_SIDDHAM_LETTER_VOCALIC_R              0x11586   /* U+11586 (SIDDHAM LETTER VOCALIC R) 𑖆 */
#define UC_SIDDHAM_LETTER_VOCALIC_RR             0x11587   /* U+11587 (SIDDHAM LETTER VOCALIC RR) 𑖇 */
#define UC_SIDDHAM_LETTER_VOCALIC_L              0x11588   /* U+11588 (SIDDHAM LETTER VOCALIC L) 𑖈 */
#define UC_SIDDHAM_LETTER_VOCALIC_LL             0x11589   /* U+11589 (SIDDHAM LETTER VOCALIC LL) 𑖉 */
#define UC_SIDDHAM_LETTER_E                      0x1158A   /* U+1158A (SIDDHAM LETTER E) 𑖊 */
#define UC_SIDDHAM_LETTER_AI                     0x1158B   /* U+1158B (SIDDHAM LETTER AI) 𑖋 */
#define UC_SIDDHAM_LETTER_O                      0x1158C   /* U+1158C (SIDDHAM LETTER O) 𑖌 */
#define UC_SIDDHAM_LETTER_AU                     0x1158D   /* U+1158D (SIDDHAM LETTER AU) 𑖍 */
#define UC_SIDDHAM_LETTER_KA                     0x1158E   /* U+1158E (SIDDHAM LETTER KA) 𑖎 */
#define UC_SIDDHAM_LETTER_KHA                    0x1158F   /* U+1158F (SIDDHAM LETTER KHA) 𑖏 */
#define UC_SIDDHAM_LETTER_GA                     0x11590   /* U+11590 (SIDDHAM LETTER GA) 𑖐 */
#define UC_SIDDHAM_LETTER_GHA                    0x11591   /* U+11591 (SIDDHAM LETTER GHA) 𑖑 */
#define UC_SIDDHAM_LETTER_NGA                    0x11592   /* U+11592 (SIDDHAM LETTER NGA) 𑖒 */
#define UC_SIDDHAM_LETTER_CA                     0x11593   /* U+11593 (SIDDHAM LETTER CA) 𑖓 */
#define UC_SIDDHAM_LETTER_CHA                    0x11594   /* U+11594 (SIDDHAM LETTER CHA) 𑖔 */
#define UC_SIDDHAM_LETTER_JA                     0x11595   /* U+11595 (SIDDHAM LETTER JA) 𑖕 */
#define UC_SIDDHAM_LETTER_JHA                    0x11596   /* U+11596 (SIDDHAM LETTER JHA) 𑖖 */
#define UC_SIDDHAM_LETTER_NYA                    0x11597   /* U+11597 (SIDDHAM LETTER NYA) 𑖗 */
#define UC_SIDDHAM_LETTER_TTA                    0x11598   /* U+11598 (SIDDHAM LETTER TTA) 𑖘 */
#define UC_SIDDHAM_LETTER_TTHA                   0x11599   /* U+11599 (SIDDHAM LETTER TTHA) 𑖙 */
#define UC_SIDDHAM_LETTER_DDA                    0x1159A   /* U+1159A (SIDDHAM LETTER DDA) 𑖚 */
#define UC_SIDDHAM_LETTER_DDHA                   0x1159B   /* U+1159B (SIDDHAM LETTER DDHA) 𑖛 */
#define UC_SIDDHAM_LETTER_NNA                    0x1159C   /* U+1159C (SIDDHAM LETTER NNA) 𑖜 */
#define UC_SIDDHAM_LETTER_TA                     0x1159D   /* U+1159D (SIDDHAM LETTER TA) 𑖝 */
#define UC_SIDDHAM_LETTER_THA                    0x1159E   /* U+1159E (SIDDHAM LETTER THA) 𑖞 */
#define UC_SIDDHAM_LETTER_DA                     0x1159F   /* U+1159F (SIDDHAM LETTER DA) 𑖟 */
#define UC_SIDDHAM_LETTER_DHA                    0x115A0   /* U+115A0 (SIDDHAM LETTER DHA) 𑖠 */
#define UC_SIDDHAM_LETTER_NA                     0x115A1   /* U+115A1 (SIDDHAM LETTER NA) 𑖡 */
#define UC_SIDDHAM_LETTER_PA                     0x115A2   /* U+115A2 (SIDDHAM LETTER PA) 𑖢 */
#define UC_SIDDHAM_LETTER_PHA                    0x115A3   /* U+115A3 (SIDDHAM LETTER PHA) 𑖣 */
#define UC_SIDDHAM_LETTER_BA                     0x115A4   /* U+115A4 (SIDDHAM LETTER BA) 𑖤 */
#define UC_SIDDHAM_LETTER_BHA                    0x115A5   /* U+115A5 (SIDDHAM LETTER BHA) 𑖥 */
#define UC_SIDDHAM_LETTER_MA                     0x115A6   /* U+115A6 (SIDDHAM LETTER MA) 𑖦 */
#define UC_SIDDHAM_LETTER_YA                     0x115A7   /* U+115A7 (SIDDHAM LETTER YA) 𑖧 */
#define UC_SIDDHAM_LETTER_RA                     0x115A8   /* U+115A8 (SIDDHAM LETTER RA) 𑖨 */
#define UC_SIDDHAM_LETTER_LA                     0x115A9   /* U+115A9 (SIDDHAM LETTER LA) 𑖩 */
#define UC_SIDDHAM_LETTER_VA                     0x115AA   /* U+115AA (SIDDHAM LETTER VA) 𑖪 */
#define UC_SIDDHAM_LETTER_SHA                    0x115AB   /* U+115AB (SIDDHAM LETTER SHA) 𑖫 */
#define UC_SIDDHAM_LETTER_SSA                    0x115AC   /* U+115AC (SIDDHAM LETTER SSA) 𑖬 */
#define UC_SIDDHAM_LETTER_SA                     0x115AD   /* U+115AD (SIDDHAM LETTER SA) 𑖭 */
#define UC_SIDDHAM_LETTER_HA                     0x115AE   /* U+115AE (SIDDHAM LETTER HA) 𑖮 */
#define UC_SIDDHAM_VOWEL_SIGN_AA                 0x115AF   /* U+115AF (SIDDHAM VOWEL SIGN AA) 𑖯 */
#define UC_SIDDHAM_VOWEL_SIGN_I                  0x115B0   /* U+115B0 (SIDDHAM VOWEL SIGN I) 𑖰 */
#define UC_SIDDHAM_VOWEL_SIGN_II                 0x115B1   /* U+115B1 (SIDDHAM VOWEL SIGN II) 𑖱 */
#define UC_SIDDHAM_VOWEL_SIGN_U                  0x115B2   /* U+115B2 (SIDDHAM VOWEL SIGN U) 𑖲 */
#define UC_SIDDHAM_VOWEL_SIGN_UU                 0x115B3   /* U+115B3 (SIDDHAM VOWEL SIGN UU) 𑖳 */
#define UC_SIDDHAM_VOWEL_SIGN_VOCALIC_R          0x115B4   /* U+115B4 (SIDDHAM VOWEL SIGN VOCALIC R) 𑖴 */
#define UC_SIDDHAM_VOWEL_SIGN_VOCALIC_RR         0x115B5   /* U+115B5 (SIDDHAM VOWEL SIGN VOCALIC RR) 𑖵 */
#define UC_UNKNOWN_115B6                         0x115B6   /* U+115B6 (UNKNOWN_115B6) */
#define UC_UNKNOWN_115B7                         0x115B7   /* U+115B7 (UNKNOWN_115B7) */
#define UC_SIDDHAM_VOWEL_SIGN_E                  0x115B8   /* U+115B8 (SIDDHAM VOWEL SIGN E) 𑖸 */
#define UC_SIDDHAM_VOWEL_SIGN_AI                 0x115B9   /* U+115B9 (SIDDHAM VOWEL SIGN AI) 𑖹 */
#define UC_SIDDHAM_VOWEL_SIGN_O                  0x115BA   /* U+115BA (SIDDHAM VOWEL SIGN O) 𑖺 */
#define UC_SIDDHAM_VOWEL_SIGN_AU                 0x115BB   /* U+115BB (SIDDHAM VOWEL SIGN AU) 𑖻 */
#define UC_SIDDHAM_SIGN_CANDRABINDU              0x115BC   /* U+115BC (SIDDHAM SIGN CANDRABINDU) 𑖼 */
#define UC_SIDDHAM_SIGN_ANUSVARA                 0x115BD   /* U+115BD (SIDDHAM SIGN ANUSVARA) 𑖽 */
#define UC_SIDDHAM_SIGN_VISARGA                  0x115BE   /* U+115BE (SIDDHAM SIGN VISARGA) 𑖾 */
#define UC_SIDDHAM_SIGN_VIRAMA                   0x115BF   /* U+115BF (SIDDHAM SIGN VIRAMA) 𑖿 */
#define UC_SIDDHAM_SIGN_NUKTA                    0x115C0   /* U+115C0 (SIDDHAM SIGN NUKTA) 𑗀 */
#define UC_SIDDHAM_SIGN_SIDDHAM                  0x115C1   /* U+115C1 (SIDDHAM SIGN SIDDHAM) 𑗁 */
#define UC_SIDDHAM_DANDA                         0x115C2   /* U+115C2 (SIDDHAM DANDA) 𑗂 */
#define UC_SIDDHAM_DOUBLE_DANDA                  0x115C3   /* U+115C3 (SIDDHAM DOUBLE DANDA) 𑗃 */
#define UC_SIDDHAM_SEPARATOR_DOT                 0x115C4   /* U+115C4 (SIDDHAM SEPARATOR DOT) 𑗄 */
#define UC_SIDDHAM_SEPARATOR_BAR                 0x115C5   /* U+115C5 (SIDDHAM SEPARATOR BAR) 𑗅 */
#define UC_SIDDHAM_REPETITION_MARK_1             0x115C6   /* U+115C6 (SIDDHAM REPETITION MARK-1) 𑗆 */
#define UC_SIDDHAM_REPETITION_MARK_2             0x115C7   /* U+115C7 (SIDDHAM REPETITION MARK-2) 𑗇 */
#define UC_SIDDHAM_REPETITION_MARK_3             0x115C8   /* U+115C8 (SIDDHAM REPETITION MARK-3) 𑗈 */
#define UC_SIDDHAM_END_OF_TEXT_MARK              0x115C9   /* U+115C9 (SIDDHAM END OF TEXT MARK) 𑗉 */
#define UC_SIDDHAM_SECTION_MARK_WITH_TRIDENT_AND_U_SHAPED_ORNAMENTS 0x115CA   /* U+115CA (SIDDHAM SECTION MARK WITH TRIDENT AND U-SHAPED ORNAMENTS) 𑗊 */
#define UC_SIDDHAM_SECTION_MARK_WITH_TRIDENT_AND_DOTTED_CRESCENTS 0x115CB   /* U+115CB (SIDDHAM SECTION MARK WITH TRIDENT AND DOTTED CRESCENTS) 𑗋 */
#define UC_SIDDHAM_SECTION_MARK_WITH_RAYS_AND_DOTTED_CRESCENTS 0x115CC   /* U+115CC (SIDDHAM SECTION MARK WITH RAYS AND DOTTED CRESCENTS) 𑗌 */
#define UC_SIDDHAM_SECTION_MARK_WITH_RAYS_AND_DOTTED_DOUBLE_CRESCENTS 0x115CD   /* U+115CD (SIDDHAM SECTION MARK WITH RAYS AND DOTTED DOUBLE CRESCENTS) 𑗍 */
#define UC_SIDDHAM_SECTION_MARK_WITH_RAYS_AND_DOTTED_TRIPLE_CRESCENTS 0x115CE   /* U+115CE (SIDDHAM SECTION MARK WITH RAYS AND DOTTED TRIPLE CRESCENTS) 𑗎 */
#define UC_SIDDHAM_SECTION_MARK_DOUBLE_RING      0x115CF   /* U+115CF (SIDDHAM SECTION MARK DOUBLE RING) 𑗏 */
#define UC_SIDDHAM_SECTION_MARK_DOUBLE_RING_WITH_RAYS 0x115D0   /* U+115D0 (SIDDHAM SECTION MARK DOUBLE RING WITH RAYS) 𑗐 */
#define UC_SIDDHAM_SECTION_MARK_WITH_DOUBLE_CRESCENTS 0x115D1   /* U+115D1 (SIDDHAM SECTION MARK WITH DOUBLE CRESCENTS) 𑗑 */
#define UC_SIDDHAM_SECTION_MARK_WITH_TRIPLE_CRESCENTS 0x115D2   /* U+115D2 (SIDDHAM SECTION MARK WITH TRIPLE CRESCENTS) 𑗒 */
#define UC_SIDDHAM_SECTION_MARK_WITH_QUADRUPLE_CRESCENTS 0x115D3   /* U+115D3 (SIDDHAM SECTION MARK WITH QUADRUPLE CRESCENTS) 𑗓 */
#define UC_SIDDHAM_SECTION_MARK_WITH_SEPTUPLE_CRESCENTS 0x115D4   /* U+115D4 (SIDDHAM SECTION MARK WITH SEPTUPLE CRESCENTS) 𑗔 */
#define UC_SIDDHAM_SECTION_MARK_WITH_CIRCLES_AND_RAYS 0x115D5   /* U+115D5 (SIDDHAM SECTION MARK WITH CIRCLES AND RAYS) 𑗕 */
#define UC_SIDDHAM_SECTION_MARK_WITH_CIRCLES_AND_TWO_ENCLOSURES 0x115D6   /* U+115D6 (SIDDHAM SECTION MARK WITH CIRCLES AND TWO ENCLOSURES) 𑗖 */
#define UC_SIDDHAM_SECTION_MARK_WITH_CIRCLES_AND_FOUR_ENCLOSURES 0x115D7   /* U+115D7 (SIDDHAM SECTION MARK WITH CIRCLES AND FOUR ENCLOSURES) 𑗗 */
#define UC_SIDDHAM_LETTER_THREE_CIRCLE_ALTERNATE_I 0x115D8   /* U+115D8 (SIDDHAM LETTER THREE-CIRCLE ALTERNATE I) 𑗘 */
#define UC_SIDDHAM_LETTER_TWO_CIRCLE_ALTERNATE_I 0x115D9   /* U+115D9 (SIDDHAM LETTER TWO-CIRCLE ALTERNATE I) 𑗙 */
#define UC_SIDDHAM_LETTER_TWO_CIRCLE_ALTERNATE_II 0x115DA   /* U+115DA (SIDDHAM LETTER TWO-CIRCLE ALTERNATE II) 𑗚 */
#define UC_SIDDHAM_LETTER_ALTERNATE_U            0x115DB   /* U+115DB (SIDDHAM LETTER ALTERNATE U) 𑗛 */
#define UC_SIDDHAM_VOWEL_SIGN_ALTERNATE_U        0x115DC   /* U+115DC (SIDDHAM VOWEL SIGN ALTERNATE U) 𑗜 */
#define UC_SIDDHAM_VOWEL_SIGN_ALTERNATE_UU       0x115DD   /* U+115DD (SIDDHAM VOWEL SIGN ALTERNATE UU) 𑗝 */
#define UC_UNKNOWN_115DE                         0x115DE   /* U+115DE (UNKNOWN_115DE) */
#define UC_UNKNOWN_115DF                         0x115DF   /* U+115DF (UNKNOWN_115DF) */
#define UC_UNKNOWN_115E0                         0x115E0   /* U+115E0 (UNKNOWN_115E0) */
#define UC_UNKNOWN_115E1                         0x115E1   /* U+115E1 (UNKNOWN_115E1) */
#define UC_UNKNOWN_115E2                         0x115E2   /* U+115E2 (UNKNOWN_115E2) */
#define UC_UNKNOWN_115E3                         0x115E3   /* U+115E3 (UNKNOWN_115E3) */
#define UC_UNKNOWN_115E4                         0x115E4   /* U+115E4 (UNKNOWN_115E4) */
#define UC_UNKNOWN_115E5                         0x115E5   /* U+115E5 (UNKNOWN_115E5) */
#define UC_UNKNOWN_115E6                         0x115E6   /* U+115E6 (UNKNOWN_115E6) */
#define UC_UNKNOWN_115E7                         0x115E7   /* U+115E7 (UNKNOWN_115E7) */
#define UC_UNKNOWN_115E8                         0x115E8   /* U+115E8 (UNKNOWN_115E8) */
#define UC_UNKNOWN_115E9                         0x115E9   /* U+115E9 (UNKNOWN_115E9) */
#define UC_UNKNOWN_115EA                         0x115EA   /* U+115EA (UNKNOWN_115EA) */
#define UC_UNKNOWN_115EB                         0x115EB   /* U+115EB (UNKNOWN_115EB) */
#define UC_UNKNOWN_115EC                         0x115EC   /* U+115EC (UNKNOWN_115EC) */
#define UC_UNKNOWN_115ED                         0x115ED   /* U+115ED (UNKNOWN_115ED) */
#define UC_UNKNOWN_115EE                         0x115EE   /* U+115EE (UNKNOWN_115EE) */
#define UC_UNKNOWN_115EF                         0x115EF   /* U+115EF (UNKNOWN_115EF) */
#define UC_UNKNOWN_115F0                         0x115F0   /* U+115F0 (UNKNOWN_115F0) */
#define UC_UNKNOWN_115F1                         0x115F1   /* U+115F1 (UNKNOWN_115F1) */
#define UC_UNKNOWN_115F2                         0x115F2   /* U+115F2 (UNKNOWN_115F2) */
#define UC_UNKNOWN_115F3                         0x115F3   /* U+115F3 (UNKNOWN_115F3) */
#define UC_UNKNOWN_115F4                         0x115F4   /* U+115F4 (UNKNOWN_115F4) */
#define UC_UNKNOWN_115F5                         0x115F5   /* U+115F5 (UNKNOWN_115F5) */
#define UC_UNKNOWN_115F6                         0x115F6   /* U+115F6 (UNKNOWN_115F6) */
#define UC_UNKNOWN_115F7                         0x115F7   /* U+115F7 (UNKNOWN_115F7) */
#define UC_UNKNOWN_115F8                         0x115F8   /* U+115F8 (UNKNOWN_115F8) */
#define UC_UNKNOWN_115F9                         0x115F9   /* U+115F9 (UNKNOWN_115F9) */
#define UC_UNKNOWN_115FA                         0x115FA   /* U+115FA (UNKNOWN_115FA) */
#define UC_UNKNOWN_115FB                         0x115FB   /* U+115FB (UNKNOWN_115FB) */
#define UC_UNKNOWN_115FC                         0x115FC   /* U+115FC (UNKNOWN_115FC) */
#define UC_UNKNOWN_115FD                         0x115FD   /* U+115FD (UNKNOWN_115FD) */
#define UC_UNKNOWN_115FE                         0x115FE   /* U+115FE (UNKNOWN_115FE) */
#define UC_UNKNOWN_115FF                         0x115FF   /* U+115FF (UNKNOWN_115FF) */
