/* Sogdian.h – Unicode constants for U+10F30 … U+10F6F
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_SOGDIAN_LETTER_ALEPH                  0x10F30   /* U+10F30 (SOGDIAN LETTER ALEPH) 𐼰 */
#define UC_SOGDIAN_LETTER_BETH                   0x10F31   /* U+10F31 (SOGDIAN LETTER BETH) 𐼱 */
#define UC_SOGDIAN_LETTER_GIMEL                  0x10F32   /* U+10F32 (SOGDIAN LETTER GIMEL) 𐼲 */
#define UC_SOGDIAN_LETTER_HE                     0x10F33   /* U+10F33 (SOGDIAN LETTER HE) 𐼳 */
#define UC_SOGDIAN_LETTER_WAW                    0x10F34   /* U+10F34 (SOGDIAN LETTER WAW) 𐼴 */
#define UC_SOGDIAN_LETTER_ZAYIN                  0x10F35   /* U+10F35 (SOGDIAN LETTER ZAYIN) 𐼵 */
#define UC_SOGDIAN_LETTER_HETH                   0x10F36   /* U+10F36 (SOGDIAN LETTER HETH) 𐼶 */
#define UC_SOGDIAN_LETTER_YODH                   0x10F37   /* U+10F37 (SOGDIAN LETTER YODH) 𐼷 */
#define UC_SOGDIAN_LETTER_KAPH                   0x10F38   /* U+10F38 (SOGDIAN LETTER KAPH) 𐼸 */
#define UC_SOGDIAN_LETTER_LAMEDH                 0x10F39   /* U+10F39 (SOGDIAN LETTER LAMEDH) 𐼹 */
#define UC_SOGDIAN_LETTER_MEM                    0x10F3A   /* U+10F3A (SOGDIAN LETTER MEM) 𐼺 */
#define UC_SOGDIAN_LETTER_NUN                    0x10F3B   /* U+10F3B (SOGDIAN LETTER NUN) 𐼻 */
#define UC_SOGDIAN_LETTER_SAMEKH                 0x10F3C   /* U+10F3C (SOGDIAN LETTER SAMEKH) 𐼼 */
#define UC_SOGDIAN_LETTER_AYIN                   0x10F3D   /* U+10F3D (SOGDIAN LETTER AYIN) 𐼽 */
#define UC_SOGDIAN_LETTER_PE                     0x10F3E   /* U+10F3E (SOGDIAN LETTER PE) 𐼾 */
#define UC_SOGDIAN_LETTER_SADHE                  0x10F3F   /* U+10F3F (SOGDIAN LETTER SADHE) 𐼿 */
#define UC_SOGDIAN_LETTER_RESH_AYIN              0x10F40   /* U+10F40 (SOGDIAN LETTER RESH-AYIN) 𐽀 */
#define UC_SOGDIAN_LETTER_SHIN                   0x10F41   /* U+10F41 (SOGDIAN LETTER SHIN) 𐽁 */
#define UC_SOGDIAN_LETTER_TAW                    0x10F42   /* U+10F42 (SOGDIAN LETTER TAW) 𐽂 */
#define UC_SOGDIAN_LETTER_FETH                   0x10F43   /* U+10F43 (SOGDIAN LETTER FETH) 𐽃 */
#define UC_SOGDIAN_LETTER_LESH                   0x10F44   /* U+10F44 (SOGDIAN LETTER LESH) 𐽄 */
#define UC_SOGDIAN_INDEPENDENT_SHIN              0x10F45   /* U+10F45 (SOGDIAN INDEPENDENT SHIN) 𐽅 */
#define UC_SOGDIAN_COMBINING_DOT_BELOW           0x10F46   /* U+10F46 (SOGDIAN COMBINING DOT BELOW) 𐽆 */
#define UC_SOGDIAN_COMBINING_TWO_DOTS_BELOW      0x10F47   /* U+10F47 (SOGDIAN COMBINING TWO DOTS BELOW) 𐽇 */
#define UC_SOGDIAN_COMBINING_DOT_ABOVE           0x10F48   /* U+10F48 (SOGDIAN COMBINING DOT ABOVE) 𐽈 */
#define UC_SOGDIAN_COMBINING_TWO_DOTS_ABOVE      0x10F49   /* U+10F49 (SOGDIAN COMBINING TWO DOTS ABOVE) 𐽉 */
#define UC_SOGDIAN_COMBINING_CURVE_ABOVE         0x10F4A   /* U+10F4A (SOGDIAN COMBINING CURVE ABOVE) 𐽊 */
#define UC_SOGDIAN_COMBINING_CURVE_BELOW         0x10F4B   /* U+10F4B (SOGDIAN COMBINING CURVE BELOW) 𐽋 */
#define UC_SOGDIAN_COMBINING_HOOK_ABOVE          0x10F4C   /* U+10F4C (SOGDIAN COMBINING HOOK ABOVE) 𐽌 */
#define UC_SOGDIAN_COMBINING_HOOK_BELOW          0x10F4D   /* U+10F4D (SOGDIAN COMBINING HOOK BELOW) 𐽍 */
#define UC_SOGDIAN_COMBINING_LONG_HOOK_BELOW     0x10F4E   /* U+10F4E (SOGDIAN COMBINING LONG HOOK BELOW) 𐽎 */
#define UC_SOGDIAN_COMBINING_RESH_BELOW          0x10F4F   /* U+10F4F (SOGDIAN COMBINING RESH BELOW) 𐽏 */
#define UC_SOGDIAN_COMBINING_STROKE_BELOW        0x10F50   /* U+10F50 (SOGDIAN COMBINING STROKE BELOW) 𐽐 */
#define UC_SOGDIAN_NUMBER_ONE                    0x10F51   /* U+10F51 (SOGDIAN NUMBER ONE) 𐽑 */
#define UC_SOGDIAN_NUMBER_TEN                    0x10F52   /* U+10F52 (SOGDIAN NUMBER TEN) 𐽒 */
#define UC_SOGDIAN_NUMBER_TWENTY                 0x10F53   /* U+10F53 (SOGDIAN NUMBER TWENTY) 𐽓 */
#define UC_SOGDIAN_NUMBER_ONE_HUNDRED            0x10F54   /* U+10F54 (SOGDIAN NUMBER ONE HUNDRED) 𐽔 */
#define UC_SOGDIAN_PUNCTUATION_TWO_VERTICAL_BARS 0x10F55   /* U+10F55 (SOGDIAN PUNCTUATION TWO VERTICAL BARS) 𐽕 */
#define UC_SOGDIAN_PUNCTUATION_TWO_VERTICAL_BARS_WITH_DOTS 0x10F56   /* U+10F56 (SOGDIAN PUNCTUATION TWO VERTICAL BARS WITH DOTS) 𐽖 */
#define UC_SOGDIAN_PUNCTUATION_CIRCLE_WITH_DOT   0x10F57   /* U+10F57 (SOGDIAN PUNCTUATION CIRCLE WITH DOT) 𐽗 */
#define UC_SOGDIAN_PUNCTUATION_TWO_CIRCLES_WITH_DOTS 0x10F58   /* U+10F58 (SOGDIAN PUNCTUATION TWO CIRCLES WITH DOTS) 𐽘 */
#define UC_SOGDIAN_PUNCTUATION_HALF_CIRCLE_WITH_DOT 0x10F59   /* U+10F59 (SOGDIAN PUNCTUATION HALF CIRCLE WITH DOT) 𐽙 */
#define UC_UNKNOWN_10F5A                         0x10F5A   /* U+10F5A (UNKNOWN_10F5A) */
#define UC_UNKNOWN_10F5B                         0x10F5B   /* U+10F5B (UNKNOWN_10F5B) */
#define UC_UNKNOWN_10F5C                         0x10F5C   /* U+10F5C (UNKNOWN_10F5C) */
#define UC_UNKNOWN_10F5D                         0x10F5D   /* U+10F5D (UNKNOWN_10F5D) */
#define UC_UNKNOWN_10F5E                         0x10F5E   /* U+10F5E (UNKNOWN_10F5E) */
#define UC_UNKNOWN_10F5F                         0x10F5F   /* U+10F5F (UNKNOWN_10F5F) */
#define UC_UNKNOWN_10F60                         0x10F60   /* U+10F60 (UNKNOWN_10F60) */
#define UC_UNKNOWN_10F61                         0x10F61   /* U+10F61 (UNKNOWN_10F61) */
#define UC_UNKNOWN_10F62                         0x10F62   /* U+10F62 (UNKNOWN_10F62) */
#define UC_UNKNOWN_10F63                         0x10F63   /* U+10F63 (UNKNOWN_10F63) */
#define UC_UNKNOWN_10F64                         0x10F64   /* U+10F64 (UNKNOWN_10F64) */
#define UC_UNKNOWN_10F65                         0x10F65   /* U+10F65 (UNKNOWN_10F65) */
#define UC_UNKNOWN_10F66                         0x10F66   /* U+10F66 (UNKNOWN_10F66) */
#define UC_UNKNOWN_10F67                         0x10F67   /* U+10F67 (UNKNOWN_10F67) */
#define UC_UNKNOWN_10F68                         0x10F68   /* U+10F68 (UNKNOWN_10F68) */
#define UC_UNKNOWN_10F69                         0x10F69   /* U+10F69 (UNKNOWN_10F69) */
#define UC_UNKNOWN_10F6A                         0x10F6A   /* U+10F6A (UNKNOWN_10F6A) */
#define UC_UNKNOWN_10F6B                         0x10F6B   /* U+10F6B (UNKNOWN_10F6B) */
#define UC_UNKNOWN_10F6C                         0x10F6C   /* U+10F6C (UNKNOWN_10F6C) */
#define UC_UNKNOWN_10F6D                         0x10F6D   /* U+10F6D (UNKNOWN_10F6D) */
#define UC_UNKNOWN_10F6E                         0x10F6E   /* U+10F6E (UNKNOWN_10F6E) */
#define UC_UNKNOWN_10F6F                         0x10F6F   /* U+10F6F (UNKNOWN_10F6F) */
