/* sundanese_supplement.h – Unicode constants for U+1CC0 … U+1CCF
*
* Generated by generate_unicode_headers.py (Unicode 17.0.0)
*
* Source data for blocks: Blocks.txt (Unicode 17.0.0)
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_SUNDANESE_PUNCTUATION_BINDU_SURYA     0x1CC0 0  // ᳀
#define UC_SUNDANESE_PUNCTUATION_BINDU_PANGLONG  0x1CC1 0  // ᳁
#define UC_SUNDANESE_PUNCTUATION_BINDU_PURNAMA   0x1CC2 0  // ᳂
#define UC_SUNDANESE_PUNCTUATION_BINDU_CAKRA     0x1CC3 0  // ᳃
#define UC_SUNDANESE_PUNCTUATION_BINDU_LEU_SATANGA 0x1CC4 0  // ᳄
#define UC_SUNDANESE_PUNCTUATION_BINDU_KA_SATANGA 0x1CC5 0  // ᳅
#define UC_SUNDANESE_PUNCTUATION_BINDU_DA_SATANGA 0x1CC6 0  // ᳆
#define UC_SUNDANESE_PUNCTUATION_BINDU_BA_SATANGA 0x1CC7 0  // ᳇
