/* supplemental_arrows_a.h – Unicode constants for U+27F0 … U+27FF
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
*
* See https://www.unicode.org/versions/latest/ for source data.


* Consistency Check:
* Total Defined Code Points: 16
* Total Significant Hex Values: 16
* Status: OK (Counts Match)

*/

#ifndef SUPPLEMENTAL_ARROWS_A_H
#define SUPPLEMENTAL_ARROWS_A_H

#define UC_UPWARDS_QUADRUPLE_ARROW               0x27F0 0  // ⟰
#define UC_DOWNWARDS_QUADRUPLE_ARROW             0x27F1 0  // ⟱
#define UC_ANTICLOCKWISE_GAPPED_CIRCLE_ARROW     0x27F2 0  // ⟲
#define UC_CLOCKWISE_GAPPED_CIRCLE_ARROW         0x27F3 0  // ⟳
#define UC_RIGHT_ARROW_C_PLUS                    0x27F4 0  // ⟴
#define UC_LONG_LEFTWARDS_ARROW                  0x27F5 0  // ⟵
#define UC_LONG_RIGHTWARDS_ARROW                 0x27F6 0  // ⟶
#define UC_LONG_LEFT_RIGHT_ARROW                 0x27F7 0  // ⟷
#define UC_LONG_LEFTWARDS_DOUBLE_ARROW           0x27F8 0  // ⟸
#define UC_LONG_RIGHTWARDS_DOUBLE_ARROW          0x27F9 0  // ⟹
#define UC_LONG_LEFT_RIGHT_DOUBLE_ARROW          0x27FA 0  // ⟺
#define UC_LONG_LEFTWARDS_ARROW_FROM_BAR         0x27FB 0  // ⟻
#define UC_LONG_RIGHTWARDS_ARROW_FROM_BAR        0x27FC 0  // ⟼
#define UC_LONG_LEFTWARDS_DOUBLE_ARROW_FROM_BAR  0x27FD 0  // ⟽
#define UC_LONG_RIGHTWARDS_DOUBLE_ARROW_FROM_BAR 0x27FE 0  // ⟾
#define UC_LONG_RIGHTWARDS_SQUIGGLE_ARROW        0x27FF 0  // ⟿

#endif // SUPPLEMENTAL_ARROWS_A_H
