/* Supplemental Punctuation.h – Unicode constants for U+2E00 … U+2E7F
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_RIGHT_ANGLE_SUBSTITUTION_MARKER       0x2E00   /* U+2E00 (RIGHT ANGLE SUBSTITUTION MARKER) ⸀ */
#define UC_RIGHT_ANGLE_DOTTED_SUBSTITUTION_MARKER 0x2E01   /* U+2E01 (RIGHT ANGLE DOTTED SUBSTITUTION MARKER) ⸁ */
#define UC_LEFT_SUBSTITUTION_BRACKET             0x2E02   /* U+2E02 (LEFT SUBSTITUTION BRACKET) ⸂ */
#define UC_RIGHT_SUBSTITUTION_BRACKET            0x2E03   /* U+2E03 (RIGHT SUBSTITUTION BRACKET) ⸃ */
#define UC_LEFT_DOTTED_SUBSTITUTION_BRACKET      0x2E04   /* U+2E04 (LEFT DOTTED SUBSTITUTION BRACKET) ⸄ */
#define UC_RIGHT_DOTTED_SUBSTITUTION_BRACKET     0x2E05   /* U+2E05 (RIGHT DOTTED SUBSTITUTION BRACKET) ⸅ */
#define UC_RAISED_INTERPOLATION_MARKER           0x2E06   /* U+2E06 (RAISED INTERPOLATION MARKER) ⸆ */
#define UC_RAISED_DOTTED_INTERPOLATION_MARKER    0x2E07   /* U+2E07 (RAISED DOTTED INTERPOLATION MARKER) ⸇ */
#define UC_DOTTED_TRANSPOSITION_MARKER           0x2E08   /* U+2E08 (DOTTED TRANSPOSITION MARKER) ⸈ */
#define UC_LEFT_TRANSPOSITION_BRACKET            0x2E09   /* U+2E09 (LEFT TRANSPOSITION BRACKET) ⸉ */
#define UC_RIGHT_TRANSPOSITION_BRACKET           0x2E0A   /* U+2E0A (RIGHT TRANSPOSITION BRACKET) ⸊ */
#define UC_RAISED_SQUARE                         0x2E0B   /* U+2E0B (RAISED SQUARE) ⸋ */
#define UC_LEFT_RAISED_OMISSION_BRACKET          0x2E0C   /* U+2E0C (LEFT RAISED OMISSION BRACKET) ⸌ */
#define UC_RIGHT_RAISED_OMISSION_BRACKET         0x2E0D   /* U+2E0D (RIGHT RAISED OMISSION BRACKET) ⸍ */
#define UC_EDITORIAL_CORONIS                     0x2E0E   /* U+2E0E (EDITORIAL CORONIS) ⸎ */
#define UC_PARAGRAPHOS                           0x2E0F   /* U+2E0F (PARAGRAPHOS) ⸏ */
#define UC_FORKED_PARAGRAPHOS                    0x2E10   /* U+2E10 (FORKED PARAGRAPHOS) ⸐ */
#define UC_REVERSED_FORKED_PARAGRAPHOS           0x2E11   /* U+2E11 (REVERSED FORKED PARAGRAPHOS) ⸑ */
#define UC_HYPODIASTOLE                          0x2E12   /* U+2E12 (HYPODIASTOLE) ⸒ */
#define UC_DOTTED_OBELOS                         0x2E13   /* U+2E13 (DOTTED OBELOS) ⸓ */
#define UC_DOWNWARDS_ANCORA                      0x2E14   /* U+2E14 (DOWNWARDS ANCORA) ⸔ */
#define UC_UPWARDS_ANCORA                        0x2E15   /* U+2E15 (UPWARDS ANCORA) ⸕ */
#define UC_DOTTED_RIGHT_POINTING_ANGLE           0x2E16   /* U+2E16 (DOTTED RIGHT-POINTING ANGLE) ⸖ */
#define UC_DOUBLE_OBLIQUE_HYPHEN                 0x2E17   /* U+2E17 (DOUBLE OBLIQUE HYPHEN) ⸗ */
#define UC_INVERTED_INTERROBANG                  0x2E18   /* U+2E18 (INVERTED INTERROBANG) ⸘ */
#define UC_PALM_BRANCH                           0x2E19   /* U+2E19 (PALM BRANCH) ⸙ */
#define UC_HYPHEN_WITH_DIAERESIS                 0x2E1A   /* U+2E1A (HYPHEN WITH DIAERESIS) ⸚ */
#define UC_TILDE_WITH_RING_ABOVE                 0x2E1B   /* U+2E1B (TILDE WITH RING ABOVE) ⸛ */
#define UC_LEFT_LOW_PARAPHRASE_BRACKET           0x2E1C   /* U+2E1C (LEFT LOW PARAPHRASE BRACKET) ⸜ */
#define UC_RIGHT_LOW_PARAPHRASE_BRACKET          0x2E1D   /* U+2E1D (RIGHT LOW PARAPHRASE BRACKET) ⸝ */
#define UC_TILDE_WITH_DOT_ABOVE                  0x2E1E   /* U+2E1E (TILDE WITH DOT ABOVE) ⸞ */
#define UC_TILDE_WITH_DOT_BELOW                  0x2E1F   /* U+2E1F (TILDE WITH DOT BELOW) ⸟ */
#define UC_LEFT_VERTICAL_BAR_WITH_QUILL          0x2E20   /* U+2E20 (LEFT VERTICAL BAR WITH QUILL) ⸠ */
#define UC_RIGHT_VERTICAL_BAR_WITH_QUILL         0x2E21   /* U+2E21 (RIGHT VERTICAL BAR WITH QUILL) ⸡ */
#define UC_TOP_LEFT_HALF_BRACKET                 0x2E22   /* U+2E22 (TOP LEFT HALF BRACKET) ⸢ */
#define UC_TOP_RIGHT_HALF_BRACKET                0x2E23   /* U+2E23 (TOP RIGHT HALF BRACKET) ⸣ */
#define UC_BOTTOM_LEFT_HALF_BRACKET              0x2E24   /* U+2E24 (BOTTOM LEFT HALF BRACKET) ⸤ */
#define UC_BOTTOM_RIGHT_HALF_BRACKET             0x2E25   /* U+2E25 (BOTTOM RIGHT HALF BRACKET) ⸥ */
#define UC_LEFT_SIDEWAYS_U_BRACKET               0x2E26   /* U+2E26 (LEFT SIDEWAYS U BRACKET) ⸦ */
#define UC_RIGHT_SIDEWAYS_U_BRACKET              0x2E27   /* U+2E27 (RIGHT SIDEWAYS U BRACKET) ⸧ */
#define UC_LEFT_DOUBLE_PARENTHESIS               0x2E28   /* U+2E28 (LEFT DOUBLE PARENTHESIS) ⸨ */
#define UC_RIGHT_DOUBLE_PARENTHESIS              0x2E29   /* U+2E29 (RIGHT DOUBLE PARENTHESIS) ⸩ */
#define UC_TWO_DOTS_OVER_ONE_DOT_PUNCTUATION     0x2E2A   /* U+2E2A (TWO DOTS OVER ONE DOT PUNCTUATION) ⸪ */
#define UC_ONE_DOT_OVER_TWO_DOTS_PUNCTUATION     0x2E2B   /* U+2E2B (ONE DOT OVER TWO DOTS PUNCTUATION) ⸫ */
#define UC_SQUARED_FOUR_DOT_PUNCTUATION          0x2E2C   /* U+2E2C (SQUARED FOUR DOT PUNCTUATION) ⸬ */
#define UC_FIVE_DOT_MARK                         0x2E2D   /* U+2E2D (FIVE DOT MARK) ⸭ */
#define UC_REVERSED_QUESTION_MARK                0x2E2E   /* U+2E2E (REVERSED QUESTION MARK) ⸮ */
#define UC_VERTICAL_TILDE                        0x2E2F   /* U+2E2F (VERTICAL TILDE) ⸯ */
#define UC_RING_POINT                            0x2E30   /* U+2E30 (RING POINT) ⸰ */
#define UC_WORD_SEPARATOR_MIDDLE_DOT             0x2E31   /* U+2E31 (WORD SEPARATOR MIDDLE DOT) ⸱ */
#define UC_TURNED_COMMA                          0x2E32   /* U+2E32 (TURNED COMMA) ⸲ */
#define UC_RAISED_DOT                            0x2E33   /* U+2E33 (RAISED DOT) ⸳ */
#define UC_RAISED_COMMA                          0x2E34   /* U+2E34 (RAISED COMMA) ⸴ */
#define UC_TURNED_SEMICOLON                      0x2E35   /* U+2E35 (TURNED SEMICOLON) ⸵ */
#define UC_DAGGER_WITH_LEFT_GUARD                0x2E36   /* U+2E36 (DAGGER WITH LEFT GUARD) ⸶ */
#define UC_DAGGER_WITH_RIGHT_GUARD               0x2E37   /* U+2E37 (DAGGER WITH RIGHT GUARD) ⸷ */
#define UC_TURNED_DAGGER                         0x2E38   /* U+2E38 (TURNED DAGGER) ⸸ */
#define UC_TOP_HALF_SECTION_SIGN                 0x2E39   /* U+2E39 (TOP HALF SECTION SIGN) ⸹ */
#define UC_TWO_EM_DASH                           0x2E3A   /* U+2E3A (TWO-EM DASH) ⸺ */
#define UC_THREE_EM_DASH                         0x2E3B   /* U+2E3B (THREE-EM DASH) ⸻ */
#define UC_STENOGRAPHIC_FULL_STOP                0x2E3C   /* U+2E3C (STENOGRAPHIC FULL STOP) ⸼ */
#define UC_VERTICAL_SIX_DOTS                     0x2E3D   /* U+2E3D (VERTICAL SIX DOTS) ⸽ */
#define UC_WIGGLY_VERTICAL_LINE                  0x2E3E   /* U+2E3E (WIGGLY VERTICAL LINE) ⸾ */
#define UC_CAPITULUM                             0x2E3F   /* U+2E3F (CAPITULUM) ⸿ */
#define UC_DOUBLE_HYPHEN                         0x2E40   /* U+2E40 (DOUBLE HYPHEN) ⹀ */
#define UC_REVERSED_COMMA                        0x2E41   /* U+2E41 (REVERSED COMMA) ⹁ */
#define UC_DOUBLE_LOW_REVERSED_9_QUOTATION_MARK  0x2E42   /* U+2E42 (DOUBLE LOW-REVERSED-9 QUOTATION MARK) ⹂ */
#define UC_DASH_WITH_LEFT_UPTURN                 0x2E43   /* U+2E43 (DASH WITH LEFT UPTURN) ⹃ */
#define UC_DOUBLE_SUSPENSION_MARK                0x2E44   /* U+2E44 (DOUBLE SUSPENSION MARK) ⹄ */
#define UC_INVERTED_LOW_KAVYKA                   0x2E45   /* U+2E45 (INVERTED LOW KAVYKA) ⹅ */
#define UC_INVERTED_LOW_KAVYKA_WITH_KAVYKA_ABOVE 0x2E46   /* U+2E46 (INVERTED LOW KAVYKA WITH KAVYKA ABOVE) ⹆ */
#define UC_LOW_KAVYKA                            0x2E47   /* U+2E47 (LOW KAVYKA) ⹇ */
#define UC_LOW_KAVYKA_WITH_DOT                   0x2E48   /* U+2E48 (LOW KAVYKA WITH DOT) ⹈ */
#define UC_DOUBLE_STACKED_COMMA                  0x2E49   /* U+2E49 (DOUBLE STACKED COMMA) ⹉ */
#define UC_DOTTED_SOLIDUS                        0x2E4A   /* U+2E4A (DOTTED SOLIDUS) ⹊ */
#define UC_TRIPLE_DAGGER                         0x2E4B   /* U+2E4B (TRIPLE DAGGER) ⹋ */
#define UC_MEDIEVAL_COMMA                        0x2E4C   /* U+2E4C (MEDIEVAL COMMA) ⹌ */
#define UC_PARAGRAPHUS_MARK                      0x2E4D   /* U+2E4D (PARAGRAPHUS MARK) ⹍ */
#define UC_PUNCTUS_ELEVATUS_MARK                 0x2E4E   /* U+2E4E (PUNCTUS ELEVATUS MARK) ⹎ */
#define UC_CORNISH_VERSE_DIVIDER                 0x2E4F   /* U+2E4F (CORNISH VERSE DIVIDER) ⹏ */
#define UC_CROSS_PATTY_WITH_RIGHT_CROSSBAR       0x2E50   /* U+2E50 (CROSS PATTY WITH RIGHT CROSSBAR) ⹐ */
#define UC_CROSS_PATTY_WITH_LEFT_CROSSBAR        0x2E51   /* U+2E51 (CROSS PATTY WITH LEFT CROSSBAR) ⹑ */
#define UC_TIRONIAN_SIGN_CAPITAL_ET              0x2E52   /* U+2E52 (TIRONIAN SIGN CAPITAL ET) ⹒ */
#define UC_MEDIEVAL_EXCLAMATION_MARK             0x2E53   /* U+2E53 (MEDIEVAL EXCLAMATION MARK) ⹓ */
#define UC_MEDIEVAL_QUESTION_MARK                0x2E54   /* U+2E54 (MEDIEVAL QUESTION MARK) ⹔ */
#define UC_LEFT_SQUARE_BRACKET_WITH_STROKE       0x2E55   /* U+2E55 (LEFT SQUARE BRACKET WITH STROKE) ⹕ */
#define UC_RIGHT_SQUARE_BRACKET_WITH_STROKE      0x2E56   /* U+2E56 (RIGHT SQUARE BRACKET WITH STROKE) ⹖ */
#define UC_LEFT_SQUARE_BRACKET_WITH_DOUBLE_STROKE 0x2E57   /* U+2E57 (LEFT SQUARE BRACKET WITH DOUBLE STROKE) ⹗ */
#define UC_RIGHT_SQUARE_BRACKET_WITH_DOUBLE_STROKE 0x2E58   /* U+2E58 (RIGHT SQUARE BRACKET WITH DOUBLE STROKE) ⹘ */
#define UC_TOP_HALF_LEFT_PARENTHESIS             0x2E59   /* U+2E59 (TOP HALF LEFT PARENTHESIS) ⹙ */
#define UC_TOP_HALF_RIGHT_PARENTHESIS            0x2E5A   /* U+2E5A (TOP HALF RIGHT PARENTHESIS) ⹚ */
#define UC_BOTTOM_HALF_LEFT_PARENTHESIS          0x2E5B   /* U+2E5B (BOTTOM HALF LEFT PARENTHESIS) ⹛ */
#define UC_BOTTOM_HALF_RIGHT_PARENTHESIS         0x2E5C   /* U+2E5C (BOTTOM HALF RIGHT PARENTHESIS) ⹜ */
#define UC_OBLIQUE_HYPHEN                        0x2E5D   /* U+2E5D (OBLIQUE HYPHEN) ⹝ */
#define UC_UNKNOWN_2E5E                          0x2E5E   /* U+2E5E (UNKNOWN_2E5E) */
#define UC_UNKNOWN_2E5F                          0x2E5F   /* U+2E5F (UNKNOWN_2E5F) */
#define UC_UNKNOWN_2E60                          0x2E60   /* U+2E60 (UNKNOWN_2E60) */
#define UC_UNKNOWN_2E61                          0x2E61   /* U+2E61 (UNKNOWN_2E61) */
#define UC_UNKNOWN_2E62                          0x2E62   /* U+2E62 (UNKNOWN_2E62) */
#define UC_UNKNOWN_2E63                          0x2E63   /* U+2E63 (UNKNOWN_2E63) */
#define UC_UNKNOWN_2E64                          0x2E64   /* U+2E64 (UNKNOWN_2E64) */
#define UC_UNKNOWN_2E65                          0x2E65   /* U+2E65 (UNKNOWN_2E65) */
#define UC_UNKNOWN_2E66                          0x2E66   /* U+2E66 (UNKNOWN_2E66) */
#define UC_UNKNOWN_2E67                          0x2E67   /* U+2E67 (UNKNOWN_2E67) */
#define UC_UNKNOWN_2E68                          0x2E68   /* U+2E68 (UNKNOWN_2E68) */
#define UC_UNKNOWN_2E69                          0x2E69   /* U+2E69 (UNKNOWN_2E69) */
#define UC_UNKNOWN_2E6A                          0x2E6A   /* U+2E6A (UNKNOWN_2E6A) */
#define UC_UNKNOWN_2E6B                          0x2E6B   /* U+2E6B (UNKNOWN_2E6B) */
#define UC_UNKNOWN_2E6C                          0x2E6C   /* U+2E6C (UNKNOWN_2E6C) */
#define UC_UNKNOWN_2E6D                          0x2E6D   /* U+2E6D (UNKNOWN_2E6D) */
#define UC_UNKNOWN_2E6E                          0x2E6E   /* U+2E6E (UNKNOWN_2E6E) */
#define UC_UNKNOWN_2E6F                          0x2E6F   /* U+2E6F (UNKNOWN_2E6F) */
#define UC_UNKNOWN_2E70                          0x2E70   /* U+2E70 (UNKNOWN_2E70) */
#define UC_UNKNOWN_2E71                          0x2E71   /* U+2E71 (UNKNOWN_2E71) */
#define UC_UNKNOWN_2E72                          0x2E72   /* U+2E72 (UNKNOWN_2E72) */
#define UC_UNKNOWN_2E73                          0x2E73   /* U+2E73 (UNKNOWN_2E73) */
#define UC_UNKNOWN_2E74                          0x2E74   /* U+2E74 (UNKNOWN_2E74) */
#define UC_UNKNOWN_2E75                          0x2E75   /* U+2E75 (UNKNOWN_2E75) */
#define UC_UNKNOWN_2E76                          0x2E76   /* U+2E76 (UNKNOWN_2E76) */
#define UC_UNKNOWN_2E77                          0x2E77   /* U+2E77 (UNKNOWN_2E77) */
#define UC_UNKNOWN_2E78                          0x2E78   /* U+2E78 (UNKNOWN_2E78) */
#define UC_UNKNOWN_2E79                          0x2E79   /* U+2E79 (UNKNOWN_2E79) */
#define UC_UNKNOWN_2E7A                          0x2E7A   /* U+2E7A (UNKNOWN_2E7A) */
#define UC_UNKNOWN_2E7B                          0x2E7B   /* U+2E7B (UNKNOWN_2E7B) */
#define UC_UNKNOWN_2E7C                          0x2E7C   /* U+2E7C (UNKNOWN_2E7C) */
#define UC_UNKNOWN_2E7D                          0x2E7D   /* U+2E7D (UNKNOWN_2E7D) */
#define UC_UNKNOWN_2E7E                          0x2E7E   /* U+2E7E (UNKNOWN_2E7E) */
#define UC_UNKNOWN_2E7F                          0x2E7F   /* U+2E7F (UNKNOWN_2E7F) */
