/* syloti_nagri.h – Unicode constants for U+A800 … U+A82C
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_UC_SYLOTI_NAGRI_A                     0xA800 0  // ꠀ
#define UC_UC_SYLOTI_NAGRI_I                     0xA801 0  // ꠁ
#define UC_UC_SYLOTI_NAGRI_SIGN_DVISVARA         0xA802 0  // ꠂ
#define UC_UC_SYLOTI_NAGRI_U                     0xA803 0  // ꠃ
#define UC_UC_SYLOTI_NAGRI_E                     0xA804 0  // ꠄ
#define UC_UC_SYLOTI_NAGRI_O                     0xA805 0  // ꠅ
#define UC_UC_SYLOTI_NAGRI_SIGN_HASANTA          0xA806 0  // ꠆
#define UC_UC_SYLOTI_NAGRI_KO                    0xA807 0  // ꠇ
#define UC_UC_SYLOTI_NAGRI_KHO                   0xA808 0  // ꠈ
#define UC_UC_SYLOTI_NAGRI_GO                    0xA809 0  // ꠉ
#define UC_UC_SYLOTI_NAGRI_GHO                   0xA80A 0  // ꠊ
#define UC_UC_SYLOTI_NAGRI_SIGN_ANUSVARA         0xA80B 0  // ꠋ
#define UC_UC_SYLOTI_NAGRI_CO                    0xA80C 0  // ꠌ
#define UC_UC_SYLOTI_NAGRI_CHO                   0xA80D 0  // ꠍ
#define UC_UC_SYLOTI_NAGRI_JO                    0xA80E 0  // ꠎ
#define UC_UC_SYLOTI_NAGRI_JHO                   0xA80F 0  // ꠏ
#define UC_UC_SYLOTI_NAGRI_TTO                   0xA810 0  // ꠐ
#define UC_UC_SYLOTI_NAGRI_TTHO                  0xA811 0  // ꠑ
#define UC_UC_SYLOTI_NAGRI_DDO                   0xA812 0  // ꠒ
#define UC_UC_SYLOTI_NAGRI_DDHO                  0xA813 0  // ꠓ
#define UC_UC_SYLOTI_NAGRI_TO                    0xA814 0  // ꠔ
#define UC_UC_SYLOTI_NAGRI_THO                   0xA815 0  // ꠕ
#define UC_UC_SYLOTI_NAGRI_DO                    0xA816 0  // ꠖ
#define UC_UC_SYLOTI_NAGRI_DHO                   0xA817 0  // ꠗ
#define UC_UC_SYLOTI_NAGRI_NO                    0xA818 0  // ꠘ
#define UC_UC_SYLOTI_NAGRI_PO                    0xA819 0  // ꠙ
#define UC_UC_SYLOTI_NAGRI_PHO                   0xA81A 0  // ꠚ
#define UC_UC_SYLOTI_NAGRI_BO                    0xA81B 0  // ꠛ
#define UC_UC_SYLOTI_NAGRI_BHO                   0xA81C 0  // ꠜ
#define UC_UC_SYLOTI_NAGRI_MO                    0xA81D 0  // ꠝ
#define UC_UC_SYLOTI_NAGRI_RO                    0xA81E 0  // ꠞ
#define UC_UC_SYLOTI_NAGRI_LO                    0xA81F 0  // ꠟ
#define UC_UC_SYLOTI_NAGRI_RRO                   0xA820 0  // ꠠ
#define UC_UC_SYLOTI_NAGRI_SO                    0xA821 0  // ꠡ
#define UC_UC_SYLOTI_NAGRI_HO                    0xA822 0  // ꠢ
#define UC_UC_SYLOTI_NAGRI_VOWEL_SIGN_A          0xA823 0  // ꠣ
#define UC_UC_SYLOTI_NAGRI_VOWEL_SIGN_I          0xA824 0  // ꠤ
#define UC_UC_SYLOTI_NAGRI_VOWEL_SIGN_U          0xA825 0  // ꠥ
#define UC_UC_SYLOTI_NAGRI_VOWEL_SIGN_E          0xA826 0  // ꠦ
#define UC_UC_SYLOTI_NAGRI_VOWEL_SIGN_OO         0xA827 0  // ꠧ
#define UC_UC_SYLOTI_NAGRI_POETRY_MARK_1         0xA828 0  // ꠨
#define UC_UC_SYLOTI_NAGRI_POETRY_MARK_2         0xA829 0  // ꠩
#define UC_UC_SYLOTI_NAGRI_POETRY_MARK_3         0xA82A 0  // ꠪
#define UC_UC_SYLOTI_NAGRI_POETRY_MARK_4         0xA82B 0  // ꠫
#define UC_UC_SYLOTI_NAGRI_SIGN_ALTERNATE_HASANTA 0xA82C 0  // ꠬
