/* tagalog.h – Unicode constants for U+1700 … U+171F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
*
* See https://www.unicode.org/versions/latest/ for source data.

 * Tagalog may refer to:
 *

* Consistency Check:
* Total Defined Code Points: 23
* Total Significant Hex Values: 23
* Status: OK (Counts Match)

*/

#ifndef TAGALOG_H
#define TAGALOG_H

#define UC_TAGALOG_A                             0x1700 0  // ᜀ
#define UC_TAGALOG_I                             0x1701 0  // ᜁ
#define UC_TAGALOG_U                             0x1702 0  // ᜂ
#define UC_TAGALOG_KA                            0x1703 0  // ᜃ
#define UC_TAGALOG_GA                            0x1704 0  // ᜄ
#define UC_TAGALOG_NGA                           0x1705 0  // ᜅ
#define UC_TAGALOG_TA                            0x1706 0  // ᜆ
#define UC_TAGALOG_DA                            0x1707 0  // ᜇ
#define UC_TAGALOG_NA                            0x1708 0  // ᜈ
#define UC_TAGALOG_PA                            0x1709 0  // ᜉ
#define UC_TAGALOG_BA                            0x170A 0  // ᜊ
#define UC_TAGALOG_MA                            0x170B 0  // ᜋ
#define UC_TAGALOG_YA                            0x170C 0  // ᜌ
#define UC_TAGALOG_RA                            0x170D 0  // ᜍ
#define UC_TAGALOG_LA                            0x170E 0  // ᜎ
#define UC_TAGALOG_WA                            0x170F 0  // ᜏ
#define UC_TAGALOG_SA                            0x1710 0  // ᜐ
#define UC_TAGALOG_HA                            0x1711 0  // ᜑ
#define UC_TAGALOG_VOWEL_SIGN_I                  0x1712 0  // ᜒ
#define UC_TAGALOG_VOWEL_SIGN_U                  0x1713 0  // ᜓ
#define UC_TAGALOG_SIGN_VIRAMA                   0x1714 0  // ᜔
#define UC_TAGALOG_SIGN_PAMUDPOD                 0x1715 0  // ᜕
#define UC_TAGALOG_ARCHAIC_RA                    0x171F 0  // ᜟ

#endif // TAGALOG_H
