/* Tagbanwa.h – Unicode constants for U+1772 … U+1773
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_TAGBANWA_VOWEL_SIGN_I                 0x1772 0  // ᝲ
#define UC_TAGBANWA_VOWEL_SIGN_U                 0x1773 0  // ᝳ
