/* Tai Le.h – Unicode constants for U+1950 … U+197F
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_TAI_LE_LETTER_KA                      0x1950   /* U+1950 (TAI LE LETTER KA) ᥐ */
#define UC_TAI_LE_LETTER_XA                      0x1951   /* U+1951 (TAI LE LETTER XA) ᥑ */
#define UC_TAI_LE_LETTER_NGA                     0x1952   /* U+1952 (TAI LE LETTER NGA) ᥒ */
#define UC_TAI_LE_LETTER_TSA                     0x1953   /* U+1953 (TAI LE LETTER TSA) ᥓ */
#define UC_TAI_LE_LETTER_SA                      0x1954   /* U+1954 (TAI LE LETTER SA) ᥔ */
#define UC_TAI_LE_LETTER_YA                      0x1955   /* U+1955 (TAI LE LETTER YA) ᥕ */
#define UC_TAI_LE_LETTER_TA                      0x1956   /* U+1956 (TAI LE LETTER TA) ᥖ */
#define UC_TAI_LE_LETTER_THA                     0x1957   /* U+1957 (TAI LE LETTER THA) ᥗ */
#define UC_TAI_LE_LETTER_LA                      0x1958   /* U+1958 (TAI LE LETTER LA) ᥘ */
#define UC_TAI_LE_LETTER_PA                      0x1959   /* U+1959 (TAI LE LETTER PA) ᥙ */
#define UC_TAI_LE_LETTER_PHA                     0x195A   /* U+195A (TAI LE LETTER PHA) ᥚ */
#define UC_TAI_LE_LETTER_MA                      0x195B   /* U+195B (TAI LE LETTER MA) ᥛ */
#define UC_TAI_LE_LETTER_FA                      0x195C   /* U+195C (TAI LE LETTER FA) ᥜ */
#define UC_TAI_LE_LETTER_VA                      0x195D   /* U+195D (TAI LE LETTER VA) ᥝ */
#define UC_TAI_LE_LETTER_HA                      0x195E   /* U+195E (TAI LE LETTER HA) ᥞ */
#define UC_TAI_LE_LETTER_QA                      0x195F   /* U+195F (TAI LE LETTER QA) ᥟ */
#define UC_TAI_LE_LETTER_KHA                     0x1960   /* U+1960 (TAI LE LETTER KHA) ᥠ */
#define UC_TAI_LE_LETTER_TSHA                    0x1961   /* U+1961 (TAI LE LETTER TSHA) ᥡ */
#define UC_TAI_LE_LETTER_NA                      0x1962   /* U+1962 (TAI LE LETTER NA) ᥢ */
#define UC_TAI_LE_LETTER_A                       0x1963   /* U+1963 (TAI LE LETTER A) ᥣ */
#define UC_TAI_LE_LETTER_I                       0x1964   /* U+1964 (TAI LE LETTER I) ᥤ */
#define UC_TAI_LE_LETTER_EE                      0x1965   /* U+1965 (TAI LE LETTER EE) ᥥ */
#define UC_TAI_LE_LETTER_EH                      0x1966   /* U+1966 (TAI LE LETTER EH) ᥦ */
#define UC_TAI_LE_LETTER_U                       0x1967   /* U+1967 (TAI LE LETTER U) ᥧ */
#define UC_TAI_LE_LETTER_OO                      0x1968   /* U+1968 (TAI LE LETTER OO) ᥨ */
#define UC_TAI_LE_LETTER_O                       0x1969   /* U+1969 (TAI LE LETTER O) ᥩ */
#define UC_TAI_LE_LETTER_UE                      0x196A   /* U+196A (TAI LE LETTER UE) ᥪ */
#define UC_TAI_LE_LETTER_E                       0x196B   /* U+196B (TAI LE LETTER E) ᥫ */
#define UC_TAI_LE_LETTER_AUE                     0x196C   /* U+196C (TAI LE LETTER AUE) ᥬ */
#define UC_TAI_LE_LETTER_AI                      0x196D   /* U+196D (TAI LE LETTER AI) ᥭ */
#define UC_UNKNOWN_196E                          0x196E   /* U+196E (UNKNOWN_196E) */
#define UC_UNKNOWN_196F                          0x196F   /* U+196F (UNKNOWN_196F) */
#define UC_TAI_LE_LETTER_TONE_2                  0x1970   /* U+1970 (TAI LE LETTER TONE-2) ᥰ */
#define UC_TAI_LE_LETTER_TONE_3                  0x1971   /* U+1971 (TAI LE LETTER TONE-3) ᥱ */
#define UC_TAI_LE_LETTER_TONE_4                  0x1972   /* U+1972 (TAI LE LETTER TONE-4) ᥲ */
#define UC_TAI_LE_LETTER_TONE_5                  0x1973   /* U+1973 (TAI LE LETTER TONE-5) ᥳ */
#define UC_TAI_LE_LETTER_TONE_6                  0x1974   /* U+1974 (TAI LE LETTER TONE-6) ᥴ */
#define UC_UNKNOWN_1975                          0x1975   /* U+1975 (UNKNOWN_1975) */
#define UC_UNKNOWN_1976                          0x1976   /* U+1976 (UNKNOWN_1976) */
#define UC_UNKNOWN_1977                          0x1977   /* U+1977 (UNKNOWN_1977) */
#define UC_UNKNOWN_1978                          0x1978   /* U+1978 (UNKNOWN_1978) */
#define UC_UNKNOWN_1979                          0x1979   /* U+1979 (UNKNOWN_1979) */
#define UC_UNKNOWN_197A                          0x197A   /* U+197A (UNKNOWN_197A) */
#define UC_UNKNOWN_197B                          0x197B   /* U+197B (UNKNOWN_197B) */
#define UC_UNKNOWN_197C                          0x197C   /* U+197C (UNKNOWN_197C) */
#define UC_UNKNOWN_197D                          0x197D   /* U+197D (UNKNOWN_197D) */
#define UC_UNKNOWN_197E                          0x197E   /* U+197E (UNKNOWN_197E) */
#define UC_UNKNOWN_197F                          0x197F   /* U+197F (UNKNOWN_197F) */
