/* Tamil.h – Unicode constants for U+0B80 … U+0BFF
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_UNKNOWN_0B80                          0x0B80   /* U+0B80 (UNKNOWN_0B80) */
#define UC_UNKNOWN_0B81                          0x0B81   /* U+0B81 (UNKNOWN_0B81) */
#define UC_TAMIL_SIGN_ANUSVARA                   0x0B82   /* U+0B82 (TAMIL SIGN ANUSVARA) ஂ */
#define UC_TAMIL_SIGN_VISARGA                    0x0B83   /* U+0B83 (TAMIL SIGN VISARGA) ஃ */
#define UC_UNKNOWN_0B84                          0x0B84   /* U+0B84 (UNKNOWN_0B84) */
#define UC_TAMIL_LETTER_A                        0x0B85   /* U+0B85 (TAMIL LETTER A) அ */
#define UC_TAMIL_LETTER_AA                       0x0B86   /* U+0B86 (TAMIL LETTER AA) ஆ */
#define UC_TAMIL_LETTER_I                        0x0B87   /* U+0B87 (TAMIL LETTER I) இ */
#define UC_TAMIL_LETTER_II                       0x0B88   /* U+0B88 (TAMIL LETTER II) ஈ */
#define UC_TAMIL_LETTER_U                        0x0B89   /* U+0B89 (TAMIL LETTER U) உ */
#define UC_TAMIL_LETTER_UU                       0x0B8A   /* U+0B8A (TAMIL LETTER UU) ஊ */
#define UC_UNKNOWN_0B8B                          0x0B8B   /* U+0B8B (UNKNOWN_0B8B) */
#define UC_UNKNOWN_0B8C                          0x0B8C   /* U+0B8C (UNKNOWN_0B8C) */
#define UC_UNKNOWN_0B8D                          0x0B8D   /* U+0B8D (UNKNOWN_0B8D) */
#define UC_TAMIL_LETTER_E                        0x0B8E   /* U+0B8E (TAMIL LETTER E) எ */
#define UC_TAMIL_LETTER_EE                       0x0B8F   /* U+0B8F (TAMIL LETTER EE) ஏ */
#define UC_TAMIL_LETTER_AI                       0x0B90   /* U+0B90 (TAMIL LETTER AI) ஐ */
#define UC_UNKNOWN_0B91                          0x0B91   /* U+0B91 (UNKNOWN_0B91) */
#define UC_TAMIL_LETTER_O                        0x0B92   /* U+0B92 (TAMIL LETTER O) ஒ */
#define UC_TAMIL_LETTER_OO                       0x0B93   /* U+0B93 (TAMIL LETTER OO) ஓ */
#define UC_TAMIL_LETTER_AU                       0x0B94   /* U+0B94 (TAMIL LETTER AU) ஔ */
#define UC_TAMIL_LETTER_KA                       0x0B95   /* U+0B95 (TAMIL LETTER KA) க */
#define UC_UNKNOWN_0B96                          0x0B96   /* U+0B96 (UNKNOWN_0B96) */
#define UC_UNKNOWN_0B97                          0x0B97   /* U+0B97 (UNKNOWN_0B97) */
#define UC_UNKNOWN_0B98                          0x0B98   /* U+0B98 (UNKNOWN_0B98) */
#define UC_TAMIL_LETTER_NGA                      0x0B99   /* U+0B99 (TAMIL LETTER NGA) ங */
#define UC_TAMIL_LETTER_CA                       0x0B9A   /* U+0B9A (TAMIL LETTER CA) ச */
#define UC_UNKNOWN_0B9B                          0x0B9B   /* U+0B9B (UNKNOWN_0B9B) */
#define UC_TAMIL_LETTER_JA                       0x0B9C   /* U+0B9C (TAMIL LETTER JA) ஜ */
#define UC_UNKNOWN_0B9D                          0x0B9D   /* U+0B9D (UNKNOWN_0B9D) */
#define UC_TAMIL_LETTER_NYA                      0x0B9E   /* U+0B9E (TAMIL LETTER NYA) ஞ */
#define UC_TAMIL_LETTER_TTA                      0x0B9F   /* U+0B9F (TAMIL LETTER TTA) ட */
#define UC_UNKNOWN_0BA0                          0x0BA0   /* U+0BA0 (UNKNOWN_0BA0) */
#define UC_UNKNOWN_0BA1                          0x0BA1   /* U+0BA1 (UNKNOWN_0BA1) */
#define UC_UNKNOWN_0BA2                          0x0BA2   /* U+0BA2 (UNKNOWN_0BA2) */
#define UC_TAMIL_LETTER_NNA                      0x0BA3   /* U+0BA3 (TAMIL LETTER NNA) ண */
#define UC_TAMIL_LETTER_TA                       0x0BA4   /* U+0BA4 (TAMIL LETTER TA) த */
#define UC_UNKNOWN_0BA5                          0x0BA5   /* U+0BA5 (UNKNOWN_0BA5) */
#define UC_UNKNOWN_0BA6                          0x0BA6   /* U+0BA6 (UNKNOWN_0BA6) */
#define UC_UNKNOWN_0BA7                          0x0BA7   /* U+0BA7 (UNKNOWN_0BA7) */
#define UC_TAMIL_LETTER_NA                       0x0BA8   /* U+0BA8 (TAMIL LETTER NA) ந */
#define UC_TAMIL_LETTER_NNNA                     0x0BA9   /* U+0BA9 (TAMIL LETTER NNNA) ன */
#define UC_TAMIL_LETTER_PA                       0x0BAA   /* U+0BAA (TAMIL LETTER PA) ப */
#define UC_UNKNOWN_0BAB                          0x0BAB   /* U+0BAB (UNKNOWN_0BAB) */
#define UC_UNKNOWN_0BAC                          0x0BAC   /* U+0BAC (UNKNOWN_0BAC) */
#define UC_UNKNOWN_0BAD                          0x0BAD   /* U+0BAD (UNKNOWN_0BAD) */
#define UC_TAMIL_LETTER_MA                       0x0BAE   /* U+0BAE (TAMIL LETTER MA) ம */
#define UC_TAMIL_LETTER_YA                       0x0BAF   /* U+0BAF (TAMIL LETTER YA) ய */
#define UC_TAMIL_LETTER_RA                       0x0BB0   /* U+0BB0 (TAMIL LETTER RA) ர */
#define UC_TAMIL_LETTER_RRA                      0x0BB1   /* U+0BB1 (TAMIL LETTER RRA) ற */
#define UC_TAMIL_LETTER_LA                       0x0BB2   /* U+0BB2 (TAMIL LETTER LA) ல */
#define UC_TAMIL_LETTER_LLA                      0x0BB3   /* U+0BB3 (TAMIL LETTER LLA) ள */
#define UC_TAMIL_LETTER_LLLA                     0x0BB4   /* U+0BB4 (TAMIL LETTER LLLA) ழ */
#define UC_TAMIL_LETTER_VA                       0x0BB5   /* U+0BB5 (TAMIL LETTER VA) வ */
#define UC_TAMIL_LETTER_SHA                      0x0BB6   /* U+0BB6 (TAMIL LETTER SHA) ஶ */
#define UC_TAMIL_LETTER_SSA                      0x0BB7   /* U+0BB7 (TAMIL LETTER SSA) ஷ */
#define UC_TAMIL_LETTER_SA                       0x0BB8   /* U+0BB8 (TAMIL LETTER SA) ஸ */
#define UC_TAMIL_LETTER_HA                       0x0BB9   /* U+0BB9 (TAMIL LETTER HA) ஹ */
#define UC_UNKNOWN_0BBA                          0x0BBA   /* U+0BBA (UNKNOWN_0BBA) */
#define UC_UNKNOWN_0BBB                          0x0BBB   /* U+0BBB (UNKNOWN_0BBB) */
#define UC_UNKNOWN_0BBC                          0x0BBC   /* U+0BBC (UNKNOWN_0BBC) */
#define UC_UNKNOWN_0BBD                          0x0BBD   /* U+0BBD (UNKNOWN_0BBD) */
#define UC_TAMIL_VOWEL_SIGN_AA                   0x0BBE   /* U+0BBE (TAMIL VOWEL SIGN AA) ா */
#define UC_TAMIL_VOWEL_SIGN_I                    0x0BBF   /* U+0BBF (TAMIL VOWEL SIGN I) ி */
#define UC_TAMIL_VOWEL_SIGN_II                   0x0BC0   /* U+0BC0 (TAMIL VOWEL SIGN II) ீ */
#define UC_TAMIL_VOWEL_SIGN_U                    0x0BC1   /* U+0BC1 (TAMIL VOWEL SIGN U) ு */
#define UC_TAMIL_VOWEL_SIGN_UU                   0x0BC2   /* U+0BC2 (TAMIL VOWEL SIGN UU) ூ */
#define UC_UNKNOWN_0BC3                          0x0BC3   /* U+0BC3 (UNKNOWN_0BC3) */
#define UC_UNKNOWN_0BC4                          0x0BC4   /* U+0BC4 (UNKNOWN_0BC4) */
#define UC_UNKNOWN_0BC5                          0x0BC5   /* U+0BC5 (UNKNOWN_0BC5) */
#define UC_TAMIL_VOWEL_SIGN_E                    0x0BC6   /* U+0BC6 (TAMIL VOWEL SIGN E) ெ */
#define UC_TAMIL_VOWEL_SIGN_EE                   0x0BC7   /* U+0BC7 (TAMIL VOWEL SIGN EE) ே */
#define UC_TAMIL_VOWEL_SIGN_AI                   0x0BC8   /* U+0BC8 (TAMIL VOWEL SIGN AI) ை */
#define UC_UNKNOWN_0BC9                          0x0BC9   /* U+0BC9 (UNKNOWN_0BC9) */
#define UC_TAMIL_VOWEL_SIGN_O                    0x0BCA   /* U+0BCA (TAMIL VOWEL SIGN O) ொ */
#define UC_TAMIL_VOWEL_SIGN_OO                   0x0BCB   /* U+0BCB (TAMIL VOWEL SIGN OO) ோ */
#define UC_TAMIL_VOWEL_SIGN_AU                   0x0BCC   /* U+0BCC (TAMIL VOWEL SIGN AU) ௌ */
#define UC_TAMIL_SIGN_VIRAMA                     0x0BCD   /* U+0BCD (TAMIL SIGN VIRAMA) ் */
#define UC_UNKNOWN_0BCE                          0x0BCE   /* U+0BCE (UNKNOWN_0BCE) */
#define UC_UNKNOWN_0BCF                          0x0BCF   /* U+0BCF (UNKNOWN_0BCF) */
#define UC_TAMIL_OM                              0x0BD0   /* U+0BD0 (TAMIL OM) ௐ */
#define UC_UNKNOWN_0BD1                          0x0BD1   /* U+0BD1 (UNKNOWN_0BD1) */
#define UC_UNKNOWN_0BD2                          0x0BD2   /* U+0BD2 (UNKNOWN_0BD2) */
#define UC_UNKNOWN_0BD3                          0x0BD3   /* U+0BD3 (UNKNOWN_0BD3) */
#define UC_UNKNOWN_0BD4                          0x0BD4   /* U+0BD4 (UNKNOWN_0BD4) */
#define UC_UNKNOWN_0BD5                          0x0BD5   /* U+0BD5 (UNKNOWN_0BD5) */
#define UC_UNKNOWN_0BD6                          0x0BD6   /* U+0BD6 (UNKNOWN_0BD6) */
#define UC_TAMIL_AU_LENGTH_MARK                  0x0BD7   /* U+0BD7 (TAMIL AU LENGTH MARK) ௗ */
#define UC_UNKNOWN_0BD8                          0x0BD8   /* U+0BD8 (UNKNOWN_0BD8) */
#define UC_UNKNOWN_0BD9                          0x0BD9   /* U+0BD9 (UNKNOWN_0BD9) */
#define UC_UNKNOWN_0BDA                          0x0BDA   /* U+0BDA (UNKNOWN_0BDA) */
#define UC_UNKNOWN_0BDB                          0x0BDB   /* U+0BDB (UNKNOWN_0BDB) */
#define UC_UNKNOWN_0BDC                          0x0BDC   /* U+0BDC (UNKNOWN_0BDC) */
#define UC_UNKNOWN_0BDD                          0x0BDD   /* U+0BDD (UNKNOWN_0BDD) */
#define UC_UNKNOWN_0BDE                          0x0BDE   /* U+0BDE (UNKNOWN_0BDE) */
#define UC_UNKNOWN_0BDF                          0x0BDF   /* U+0BDF (UNKNOWN_0BDF) */
#define UC_UNKNOWN_0BE0                          0x0BE0   /* U+0BE0 (UNKNOWN_0BE0) */
#define UC_UNKNOWN_0BE1                          0x0BE1   /* U+0BE1 (UNKNOWN_0BE1) */
#define UC_UNKNOWN_0BE2                          0x0BE2   /* U+0BE2 (UNKNOWN_0BE2) */
#define UC_UNKNOWN_0BE3                          0x0BE3   /* U+0BE3 (UNKNOWN_0BE3) */
#define UC_UNKNOWN_0BE4                          0x0BE4   /* U+0BE4 (UNKNOWN_0BE4) */
#define UC_UNKNOWN_0BE5                          0x0BE5   /* U+0BE5 (UNKNOWN_0BE5) */
#define UC_TAMIL_DIGIT_ZERO                      0x0BE6   /* U+0BE6 (TAMIL DIGIT ZERO) ௦ */
#define UC_TAMIL_DIGIT_ONE                       0x0BE7   /* U+0BE7 (TAMIL DIGIT ONE) ௧ */
#define UC_TAMIL_DIGIT_TWO                       0x0BE8   /* U+0BE8 (TAMIL DIGIT TWO) ௨ */
#define UC_TAMIL_DIGIT_THREE                     0x0BE9   /* U+0BE9 (TAMIL DIGIT THREE) ௩ */
#define UC_TAMIL_DIGIT_FOUR                      0x0BEA   /* U+0BEA (TAMIL DIGIT FOUR) ௪ */
#define UC_TAMIL_DIGIT_FIVE                      0x0BEB   /* U+0BEB (TAMIL DIGIT FIVE) ௫ */
#define UC_TAMIL_DIGIT_SIX                       0x0BEC   /* U+0BEC (TAMIL DIGIT SIX) ௬ */
#define UC_TAMIL_DIGIT_SEVEN                     0x0BED   /* U+0BED (TAMIL DIGIT SEVEN) ௭ */
#define UC_TAMIL_DIGIT_EIGHT                     0x0BEE   /* U+0BEE (TAMIL DIGIT EIGHT) ௮ */
#define UC_TAMIL_DIGIT_NINE                      0x0BEF   /* U+0BEF (TAMIL DIGIT NINE) ௯ */
#define UC_TAMIL_NUMBER_TEN                      0x0BF0   /* U+0BF0 (TAMIL NUMBER TEN) ௰ */
#define UC_TAMIL_NUMBER_ONE_HUNDRED              0x0BF1   /* U+0BF1 (TAMIL NUMBER ONE HUNDRED) ௱ */
#define UC_TAMIL_NUMBER_ONE_THOUSAND             0x0BF2   /* U+0BF2 (TAMIL NUMBER ONE THOUSAND) ௲ */
#define UC_TAMIL_DAY_SIGN                        0x0BF3   /* U+0BF3 (TAMIL DAY SIGN) ௳ */
#define UC_TAMIL_MONTH_SIGN                      0x0BF4   /* U+0BF4 (TAMIL MONTH SIGN) ௴ */
#define UC_TAMIL_YEAR_SIGN                       0x0BF5   /* U+0BF5 (TAMIL YEAR SIGN) ௵ */
#define UC_TAMIL_DEBIT_SIGN                      0x0BF6   /* U+0BF6 (TAMIL DEBIT SIGN) ௶ */
#define UC_TAMIL_CREDIT_SIGN                     0x0BF7   /* U+0BF7 (TAMIL CREDIT SIGN) ௷ */
#define UC_TAMIL_AS_ABOVE_SIGN                   0x0BF8   /* U+0BF8 (TAMIL AS ABOVE SIGN) ௸ */
#define UC_TAMIL_RUPEE_SIGN                      0x0BF9   /* U+0BF9 (TAMIL RUPEE SIGN) ௹ */
#define UC_TAMIL_NUMBER_SIGN                     0x0BFA   /* U+0BFA (TAMIL NUMBER SIGN) ௺ */
#define UC_UNKNOWN_0BFB                          0x0BFB   /* U+0BFB (UNKNOWN_0BFB) */
#define UC_UNKNOWN_0BFC                          0x0BFC   /* U+0BFC (UNKNOWN_0BFC) */
#define UC_UNKNOWN_0BFD                          0x0BFD   /* U+0BFD (UNKNOWN_0BFD) */
#define UC_UNKNOWN_0BFE                          0x0BFE   /* U+0BFE (UNKNOWN_0BFE) */
#define UC_UNKNOWN_0BFF                          0x0BFF   /* U+0BFF (UNKNOWN_0BFF) */
