/* Tangsa.h – Unicode constants for U+16A70 … U+16ACF
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_TANGSA_LETTER_OZ                      0x16A70   /* U+16A70 (TANGSA LETTER OZ) 𖩰 */
#define UC_TANGSA_LETTER_OC                      0x16A71   /* U+16A71 (TANGSA LETTER OC) 𖩱 */
#define UC_TANGSA_LETTER_OQ                      0x16A72   /* U+16A72 (TANGSA LETTER OQ) 𖩲 */
#define UC_TANGSA_LETTER_OX                      0x16A73   /* U+16A73 (TANGSA LETTER OX) 𖩳 */
#define UC_TANGSA_LETTER_AZ                      0x16A74   /* U+16A74 (TANGSA LETTER AZ) 𖩴 */
#define UC_TANGSA_LETTER_AC                      0x16A75   /* U+16A75 (TANGSA LETTER AC) 𖩵 */
#define UC_TANGSA_LETTER_AQ                      0x16A76   /* U+16A76 (TANGSA LETTER AQ) 𖩶 */
#define UC_TANGSA_LETTER_AX                      0x16A77   /* U+16A77 (TANGSA LETTER AX) 𖩷 */
#define UC_TANGSA_LETTER_VZ                      0x16A78   /* U+16A78 (TANGSA LETTER VZ) 𖩸 */
#define UC_TANGSA_LETTER_VC                      0x16A79   /* U+16A79 (TANGSA LETTER VC) 𖩹 */
#define UC_TANGSA_LETTER_VQ                      0x16A7A   /* U+16A7A (TANGSA LETTER VQ) 𖩺 */
#define UC_TANGSA_LETTER_VX                      0x16A7B   /* U+16A7B (TANGSA LETTER VX) 𖩻 */
#define UC_TANGSA_LETTER_EZ                      0x16A7C   /* U+16A7C (TANGSA LETTER EZ) 𖩼 */
#define UC_TANGSA_LETTER_EC                      0x16A7D   /* U+16A7D (TANGSA LETTER EC) 𖩽 */
#define UC_TANGSA_LETTER_EQ                      0x16A7E   /* U+16A7E (TANGSA LETTER EQ) 𖩾 */
#define UC_TANGSA_LETTER_EX                      0x16A7F   /* U+16A7F (TANGSA LETTER EX) 𖩿 */
#define UC_TANGSA_LETTER_IZ                      0x16A80   /* U+16A80 (TANGSA LETTER IZ) 𖪀 */
#define UC_TANGSA_LETTER_IC                      0x16A81   /* U+16A81 (TANGSA LETTER IC) 𖪁 */
#define UC_TANGSA_LETTER_IQ                      0x16A82   /* U+16A82 (TANGSA LETTER IQ) 𖪂 */
#define UC_TANGSA_LETTER_IX                      0x16A83   /* U+16A83 (TANGSA LETTER IX) 𖪃 */
#define UC_TANGSA_LETTER_UZ                      0x16A84   /* U+16A84 (TANGSA LETTER UZ) 𖪄 */
#define UC_TANGSA_LETTER_UC                      0x16A85   /* U+16A85 (TANGSA LETTER UC) 𖪅 */
#define UC_TANGSA_LETTER_UQ                      0x16A86   /* U+16A86 (TANGSA LETTER UQ) 𖪆 */
#define UC_TANGSA_LETTER_UX                      0x16A87   /* U+16A87 (TANGSA LETTER UX) 𖪇 */
#define UC_TANGSA_LETTER_AWZ                     0x16A88   /* U+16A88 (TANGSA LETTER AWZ) 𖪈 */
#define UC_TANGSA_LETTER_AWC                     0x16A89   /* U+16A89 (TANGSA LETTER AWC) 𖪉 */
#define UC_TANGSA_LETTER_AWQ                     0x16A8A   /* U+16A8A (TANGSA LETTER AWQ) 𖪊 */
#define UC_TANGSA_LETTER_AWX                     0x16A8B   /* U+16A8B (TANGSA LETTER AWX) 𖪋 */
#define UC_TANGSA_LETTER_UIZ                     0x16A8C   /* U+16A8C (TANGSA LETTER UIZ) 𖪌 */
#define UC_TANGSA_LETTER_UIC                     0x16A8D   /* U+16A8D (TANGSA LETTER UIC) 𖪍 */
#define UC_TANGSA_LETTER_UIQ                     0x16A8E   /* U+16A8E (TANGSA LETTER UIQ) 𖪎 */
#define UC_TANGSA_LETTER_UIX                     0x16A8F   /* U+16A8F (TANGSA LETTER UIX) 𖪏 */
#define UC_TANGSA_LETTER_FINAL_NG                0x16A90   /* U+16A90 (TANGSA LETTER FINAL NG) 𖪐 */
#define UC_TANGSA_LETTER_LONG_UEX                0x16A91   /* U+16A91 (TANGSA LETTER LONG UEX) 𖪑 */
#define UC_TANGSA_LETTER_SHORT_UEZ               0x16A92   /* U+16A92 (TANGSA LETTER SHORT UEZ) 𖪒 */
#define UC_TANGSA_LETTER_SHORT_AWX               0x16A93   /* U+16A93 (TANGSA LETTER SHORT AWX) 𖪓 */
#define UC_TANGSA_LETTER_UEC                     0x16A94   /* U+16A94 (TANGSA LETTER UEC) 𖪔 */
#define UC_TANGSA_LETTER_UEZ                     0x16A95   /* U+16A95 (TANGSA LETTER UEZ) 𖪕 */
#define UC_TANGSA_LETTER_UEQ                     0x16A96   /* U+16A96 (TANGSA LETTER UEQ) 𖪖 */
#define UC_TANGSA_LETTER_UEX                     0x16A97   /* U+16A97 (TANGSA LETTER UEX) 𖪗 */
#define UC_TANGSA_LETTER_UIUZ                    0x16A98   /* U+16A98 (TANGSA LETTER UIUZ) 𖪘 */
#define UC_TANGSA_LETTER_UIUC                    0x16A99   /* U+16A99 (TANGSA LETTER UIUC) 𖪙 */
#define UC_TANGSA_LETTER_UIUQ                    0x16A9A   /* U+16A9A (TANGSA LETTER UIUQ) 𖪚 */
#define UC_TANGSA_LETTER_UIUX                    0x16A9B   /* U+16A9B (TANGSA LETTER UIUX) 𖪛 */
#define UC_TANGSA_LETTER_MZ                      0x16A9C   /* U+16A9C (TANGSA LETTER MZ) 𖪜 */
#define UC_TANGSA_LETTER_MC                      0x16A9D   /* U+16A9D (TANGSA LETTER MC) 𖪝 */
#define UC_TANGSA_LETTER_MQ                      0x16A9E   /* U+16A9E (TANGSA LETTER MQ) 𖪞 */
#define UC_TANGSA_LETTER_MX                      0x16A9F   /* U+16A9F (TANGSA LETTER MX) 𖪟 */
#define UC_TANGSA_LETTER_KA                      0x16AA0   /* U+16AA0 (TANGSA LETTER KA) 𖪠 */
#define UC_TANGSA_LETTER_KHA                     0x16AA1   /* U+16AA1 (TANGSA LETTER KHA) 𖪡 */
#define UC_TANGSA_LETTER_GA                      0x16AA2   /* U+16AA2 (TANGSA LETTER GA) 𖪢 */
#define UC_TANGSA_LETTER_NGA                     0x16AA3   /* U+16AA3 (TANGSA LETTER NGA) 𖪣 */
#define UC_TANGSA_LETTER_SA                      0x16AA4   /* U+16AA4 (TANGSA LETTER SA) 𖪤 */
#define UC_TANGSA_LETTER_YA                      0x16AA5   /* U+16AA5 (TANGSA LETTER YA) 𖪥 */
#define UC_TANGSA_LETTER_WA                      0x16AA6   /* U+16AA6 (TANGSA LETTER WA) 𖪦 */
#define UC_TANGSA_LETTER_PA                      0x16AA7   /* U+16AA7 (TANGSA LETTER PA) 𖪧 */
#define UC_TANGSA_LETTER_NYA                     0x16AA8   /* U+16AA8 (TANGSA LETTER NYA) 𖪨 */
#define UC_TANGSA_LETTER_PHA                     0x16AA9   /* U+16AA9 (TANGSA LETTER PHA) 𖪩 */
#define UC_TANGSA_LETTER_BA                      0x16AAA   /* U+16AAA (TANGSA LETTER BA) 𖪪 */
#define UC_TANGSA_LETTER_MA                      0x16AAB   /* U+16AAB (TANGSA LETTER MA) 𖪫 */
#define UC_TANGSA_LETTER_NA                      0x16AAC   /* U+16AAC (TANGSA LETTER NA) 𖪬 */
#define UC_TANGSA_LETTER_HA                      0x16AAD   /* U+16AAD (TANGSA LETTER HA) 𖪭 */
#define UC_TANGSA_LETTER_LA                      0x16AAE   /* U+16AAE (TANGSA LETTER LA) 𖪮 */
#define UC_TANGSA_LETTER_HTA                     0x16AAF   /* U+16AAF (TANGSA LETTER HTA) 𖪯 */
#define UC_TANGSA_LETTER_TA                      0x16AB0   /* U+16AB0 (TANGSA LETTER TA) 𖪰 */
#define UC_TANGSA_LETTER_DA                      0x16AB1   /* U+16AB1 (TANGSA LETTER DA) 𖪱 */
#define UC_TANGSA_LETTER_RA                      0x16AB2   /* U+16AB2 (TANGSA LETTER RA) 𖪲 */
#define UC_TANGSA_LETTER_NHA                     0x16AB3   /* U+16AB3 (TANGSA LETTER NHA) 𖪳 */
#define UC_TANGSA_LETTER_SHA                     0x16AB4   /* U+16AB4 (TANGSA LETTER SHA) 𖪴 */
#define UC_TANGSA_LETTER_CA                      0x16AB5   /* U+16AB5 (TANGSA LETTER CA) 𖪵 */
#define UC_TANGSA_LETTER_TSA                     0x16AB6   /* U+16AB6 (TANGSA LETTER TSA) 𖪶 */
#define UC_TANGSA_LETTER_GHA                     0x16AB7   /* U+16AB7 (TANGSA LETTER GHA) 𖪷 */
#define UC_TANGSA_LETTER_HTTA                    0x16AB8   /* U+16AB8 (TANGSA LETTER HTTA) 𖪸 */
#define UC_TANGSA_LETTER_THA                     0x16AB9   /* U+16AB9 (TANGSA LETTER THA) 𖪹 */
#define UC_TANGSA_LETTER_XA                      0x16ABA   /* U+16ABA (TANGSA LETTER XA) 𖪺 */
#define UC_TANGSA_LETTER_FA                      0x16ABB   /* U+16ABB (TANGSA LETTER FA) 𖪻 */
#define UC_TANGSA_LETTER_DHA                     0x16ABC   /* U+16ABC (TANGSA LETTER DHA) 𖪼 */
#define UC_TANGSA_LETTER_CHA                     0x16ABD   /* U+16ABD (TANGSA LETTER CHA) 𖪽 */
#define UC_TANGSA_LETTER_ZA                      0x16ABE   /* U+16ABE (TANGSA LETTER ZA) 𖪾 */
#define UC_UNKNOWN_16ABF                         0x16ABF   /* U+16ABF (UNKNOWN_16ABF) */
#define UC_TANGSA_DIGIT_ZERO                     0x16AC0   /* U+16AC0 (TANGSA DIGIT ZERO) 𖫀 */
#define UC_TANGSA_DIGIT_ONE                      0x16AC1   /* U+16AC1 (TANGSA DIGIT ONE) 𖫁 */
#define UC_TANGSA_DIGIT_TWO                      0x16AC2   /* U+16AC2 (TANGSA DIGIT TWO) 𖫂 */
#define UC_TANGSA_DIGIT_THREE                    0x16AC3   /* U+16AC3 (TANGSA DIGIT THREE) 𖫃 */
#define UC_TANGSA_DIGIT_FOUR                     0x16AC4   /* U+16AC4 (TANGSA DIGIT FOUR) 𖫄 */
#define UC_TANGSA_DIGIT_FIVE                     0x16AC5   /* U+16AC5 (TANGSA DIGIT FIVE) 𖫅 */
#define UC_TANGSA_DIGIT_SIX                      0x16AC6   /* U+16AC6 (TANGSA DIGIT SIX) 𖫆 */
#define UC_TANGSA_DIGIT_SEVEN                    0x16AC7   /* U+16AC7 (TANGSA DIGIT SEVEN) 𖫇 */
#define UC_TANGSA_DIGIT_EIGHT                    0x16AC8   /* U+16AC8 (TANGSA DIGIT EIGHT) 𖫈 */
#define UC_TANGSA_DIGIT_NINE                     0x16AC9   /* U+16AC9 (TANGSA DIGIT NINE) 𖫉 */
#define UC_UNKNOWN_16ACA                         0x16ACA   /* U+16ACA (UNKNOWN_16ACA) */
#define UC_UNKNOWN_16ACB                         0x16ACB   /* U+16ACB (UNKNOWN_16ACB) */
#define UC_UNKNOWN_16ACC                         0x16ACC   /* U+16ACC (UNKNOWN_16ACC) */
#define UC_UNKNOWN_16ACD                         0x16ACD   /* U+16ACD (UNKNOWN_16ACD) */
#define UC_UNKNOWN_16ACE                         0x16ACE   /* U+16ACE (UNKNOWN_16ACE) */
#define UC_UNKNOWN_16ACF                         0x16ACF   /* U+16ACF (UNKNOWN_16ACF) */
