/* telugu.h – Unicode constants for U+0C77 … U+0C7F
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_UC_SIGN_SIDDHAM                       0x0C77 0  // ౷
#define UC_UC_FRACTION_ZERO_FOR_ODD_POWERS_OF_FOUR 0x0C78 0  // ౸
#define UC_UC_FRACTION_ONE_FOR_ODD_POWERS_OF_FOUR 0x0C79 0  // ౹
#define UC_UC_FRACTION_TWO_FOR_ODD_POWERS_OF_FOUR 0x0C7A 0  // ౺
#define UC_UC_FRACTION_THREE_FOR_ODD_POWERS_OF_FOUR 0x0C7B 0  // ౻
#define UC_UC_FRACTION_ONE_FOR_EVEN_POWERS_OF_FOUR 0x0C7C 0  // ౼
#define UC_UC_FRACTION_TWO_FOR_EVEN_POWERS_OF_FOUR 0x0C7D 0  // ౽
#define UC_UC_FRACTION_THREE_FOR_EVEN_POWERS_OF_FOUR 0x0C7E 0  // ౾
#define UC_UC_SIGN_TUUMU                         0x0C7F 0  // ౿
