/*
 * Unicode Block: Arabic Extended-C
 * Range: U+10EC0..U+10EFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_ARABIC_EXTENDED_C
#define UC_H_ARABIC_EXTENDED_C

#define UC_MACRO_NAME_10EC2 0x10EC2 //  ARABIC LETTER DAL WITH TWO DOTS VERTICALLY BELOW
#define UC_MACRO_NAME_10EC3 0x10EC3 //  ARABIC LETTER TAH WITH TWO DOTS VERTICALLY BELOW
#define UC_MACRO_NAME_10EC4 0x10EC4 //  ARABIC LETTER KAF WITH TWO DOTS VERTICALLY BELOW
#define UC_MACRO_NAME_10EC5 0x10EC5 //  ARABIC SMALL YEH BARREE WITH TWO DOTS BELOW
#define UC_MACRO_NAME_10EC6 0x10EC6 //  ARABIC LETTER THIN NOON
#define UC_MACRO_NAME_10EC7 0x10EC7 //  ARABIC LETTER YEH WITH FOUR DOTS BELOW
#define UC_MACRO_NAME_10ED0 0x10ED0 //  ARABIC BIBLICAL END OF VERSE
#define UC_MACRO_NAME_10ED1 0x10ED1 //  ARABIC LIGATURE ALAYHAA AS-SALAATU WAS-SALAAM
#define UC_MACRO_NAME_10ED2 0x10ED2 //  ARABIC LIGATURE ALAYHIM AS-SALAATU WAS-SALAAM
#define UC_MACRO_NAME_10ED3 0x10ED3 //  ARABIC LIGATURE ALAYHIMAA AS-SALAATU WAS-SALAAM
#define UC_MACRO_NAME_10ED4 0x10ED4 //  ARABIC LIGATURE QADDASA ALLAAHU SIRRAH
#define UC_MACRO_NAME_10ED5 0x10ED5 //  ARABIC LIGATURE QUDDISA SIRRUHUM
#define UC_MACRO_NAME_10ED6 0x10ED6 //  ARABIC LIGATURE QUDDISA SIRRUHUMAA
#define UC_MACRO_NAME_10ED7 0x10ED7 //  ARABIC LIGATURE QUDDISAT ASRAARUHUM
#define UC_MACRO_NAME_10ED8 0x10ED8 //  ARABIC LIGATURE NAWWARA ALLAAHU MARQADAH
#define UC_MACRO_NAME_10EFA 0x10EFA //  ARABIC DOUBLE VERTICAL BAR BELOW
#define UC_MACRO_NAME_10EFB 0x10EFB //  ARABIC SMALL LOW NOON
#define UC_MACRO_NAME_10EFC 0x10EFC //  ARABIC COMBINING ALEF OVERLAY
#define UC_MACRO_NAME_10EFD 0x10EFD // 𐻽 ARABIC SMALL LOW WORD SAKTA
#define UC_MACRO_NAME_10EFE 0x10EFE // 𐻾 ARABIC SMALL LOW WORD QASR
#define UC_MACRO_NAME_10EFF 0x10EFF // 𐻿 ARABIC SMALL LOW WORD MADDA


#endif // UC_H_ARABIC_EXTENDED_C
