/*
 * Unicode Block: Arabic Presentation Forms-B
 * Range: U+FE70..U+FEFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_ARABIC_PRESENTATION_FORMS_B
#define UC_H_ARABIC_PRESENTATION_FORMS_B

#define UC_MACRO_NAME_FE70 0xFE70 // ﹰ ARABIC FATHATAN ISOLATED FORM
#define UC_MACRO_NAME_FE71 0xFE71 // ﹱ ARABIC TATWEEL WITH FATHATAN ABOVE
#define UC_MACRO_NAME_FE72 0xFE72 // ﹲ ARABIC DAMMATAN ISOLATED FORM
#define UC_MACRO_NAME_FE73 0xFE73 // ﹳ ARABIC TAIL FRAGMENT
#define UC_MACRO_NAME_FE74 0xFE74 // ﹴ ARABIC KASRATAN ISOLATED FORM
#define UC_MACRO_NAME_FE76 0xFE76 // ﹶ ARABIC FATHA ISOLATED FORM
#define UC_MACRO_NAME_FE77 0xFE77 // ﹷ ARABIC FATHA MEDIAL FORM
#define UC_MACRO_NAME_FE78 0xFE78 // ﹸ ARABIC DAMMA ISOLATED FORM
#define UC_MACRO_NAME_FE79 0xFE79 // ﹹ ARABIC DAMMA MEDIAL FORM
#define UC_MACRO_NAME_FE7A 0xFE7A // ﹺ ARABIC KASRA ISOLATED FORM
#define UC_MACRO_NAME_FE7B 0xFE7B // ﹻ ARABIC KASRA MEDIAL FORM
#define UC_MACRO_NAME_FE7C 0xFE7C // ﹼ ARABIC SHADDA ISOLATED FORM
#define UC_MACRO_NAME_FE7D 0xFE7D // ﹽ ARABIC SHADDA MEDIAL FORM
#define UC_MACRO_NAME_FE7E 0xFE7E // ﹾ ARABIC SUKUN ISOLATED FORM
#define UC_MACRO_NAME_FE7F 0xFE7F // ﹿ ARABIC SUKUN MEDIAL FORM
#define UC_MACRO_NAME_FE80 0xFE80 // ﺀ ARABIC LETTER HAMZA ISOLATED FORM
#define UC_MACRO_NAME_FE81 0xFE81 // ﺁ ARABIC LETTER ALEF WITH MADDA ABOVE ISOLATED FORM
#define UC_MACRO_NAME_FE82 0xFE82 // ﺂ ARABIC LETTER ALEF WITH MADDA ABOVE FINAL FORM
#define UC_MACRO_NAME_FE83 0xFE83 // ﺃ ARABIC LETTER ALEF WITH HAMZA ABOVE ISOLATED FORM
#define UC_MACRO_NAME_FE84 0xFE84 // ﺄ ARABIC LETTER ALEF WITH HAMZA ABOVE FINAL FORM
#define UC_MACRO_NAME_FE85 0xFE85 // ﺅ ARABIC LETTER WAW WITH HAMZA ABOVE ISOLATED FORM
#define UC_MACRO_NAME_FE86 0xFE86 // ﺆ ARABIC LETTER WAW WITH HAMZA ABOVE FINAL FORM
#define UC_MACRO_NAME_FE87 0xFE87 // ﺇ ARABIC LETTER ALEF WITH HAMZA BELOW ISOLATED FORM
#define UC_MACRO_NAME_FE88 0xFE88 // ﺈ ARABIC LETTER ALEF WITH HAMZA BELOW FINAL FORM
#define UC_MACRO_NAME_FE89 0xFE89 // ﺉ ARABIC LETTER YEH WITH HAMZA ABOVE ISOLATED FORM
#define UC_MACRO_NAME_FE8A 0xFE8A // ﺊ ARABIC LETTER YEH WITH HAMZA ABOVE FINAL FORM
#define UC_MACRO_NAME_FE8B 0xFE8B // ﺋ ARABIC LETTER YEH WITH HAMZA ABOVE INITIAL FORM
#define UC_MACRO_NAME_FE8C 0xFE8C // ﺌ ARABIC LETTER YEH WITH HAMZA ABOVE MEDIAL FORM
#define UC_MACRO_NAME_FE8D 0xFE8D // ﺍ ARABIC LETTER ALEF ISOLATED FORM
#define UC_MACRO_NAME_FE8E 0xFE8E // ﺎ ARABIC LETTER ALEF FINAL FORM
#define UC_MACRO_NAME_FE8F 0xFE8F // ﺏ ARABIC LETTER BEH ISOLATED FORM
#define UC_MACRO_NAME_FE90 0xFE90 // ﺐ ARABIC LETTER BEH FINAL FORM
#define UC_MACRO_NAME_FE91 0xFE91 // ﺑ ARABIC LETTER BEH INITIAL FORM
#define UC_MACRO_NAME_FE92 0xFE92 // ﺒ ARABIC LETTER BEH MEDIAL FORM
#define UC_MACRO_NAME_FE93 0xFE93 // ﺓ ARABIC LETTER TEH MARBUTA ISOLATED FORM
#define UC_MACRO_NAME_FE94 0xFE94 // ﺔ ARABIC LETTER TEH MARBUTA FINAL FORM
#define UC_MACRO_NAME_FE95 0xFE95 // ﺕ ARABIC LETTER TEH ISOLATED FORM
#define UC_MACRO_NAME_FE96 0xFE96 // ﺖ ARABIC LETTER TEH FINAL FORM
#define UC_MACRO_NAME_FE97 0xFE97 // ﺗ ARABIC LETTER TEH INITIAL FORM
#define UC_MACRO_NAME_FE98 0xFE98 // ﺘ ARABIC LETTER TEH MEDIAL FORM
#define UC_MACRO_NAME_FE99 0xFE99 // ﺙ ARABIC LETTER THEH ISOLATED FORM
#define UC_MACRO_NAME_FE9A 0xFE9A // ﺚ ARABIC LETTER THEH FINAL FORM
#define UC_MACRO_NAME_FE9B 0xFE9B // ﺛ ARABIC LETTER THEH INITIAL FORM
#define UC_MACRO_NAME_FE9C 0xFE9C // ﺜ ARABIC LETTER THEH MEDIAL FORM
#define UC_MACRO_NAME_FE9D 0xFE9D // ﺝ ARABIC LETTER JEEM ISOLATED FORM
#define UC_MACRO_NAME_FE9E 0xFE9E // ﺞ ARABIC LETTER JEEM FINAL FORM
#define UC_MACRO_NAME_FE9F 0xFE9F // ﺟ ARABIC LETTER JEEM INITIAL FORM
#define UC_MACRO_NAME_FEA0 0xFEA0 // ﺠ ARABIC LETTER JEEM MEDIAL FORM
#define UC_MACRO_NAME_FEA1 0xFEA1 // ﺡ ARABIC LETTER HAH ISOLATED FORM
#define UC_MACRO_NAME_FEA2 0xFEA2 // ﺢ ARABIC LETTER HAH FINAL FORM
#define UC_MACRO_NAME_FEA3 0xFEA3 // ﺣ ARABIC LETTER HAH INITIAL FORM
#define UC_MACRO_NAME_FEA4 0xFEA4 // ﺤ ARABIC LETTER HAH MEDIAL FORM
#define UC_MACRO_NAME_FEA5 0xFEA5 // ﺥ ARABIC LETTER KHAH ISOLATED FORM
#define UC_MACRO_NAME_FEA6 0xFEA6 // ﺦ ARABIC LETTER KHAH FINAL FORM
#define UC_MACRO_NAME_FEA7 0xFEA7 // ﺧ ARABIC LETTER KHAH INITIAL FORM
#define UC_MACRO_NAME_FEA8 0xFEA8 // ﺨ ARABIC LETTER KHAH MEDIAL FORM
#define UC_MACRO_NAME_FEA9 0xFEA9 // ﺩ ARABIC LETTER DAL ISOLATED FORM
#define UC_MACRO_NAME_FEAA 0xFEAA // ﺪ ARABIC LETTER DAL FINAL FORM
#define UC_MACRO_NAME_FEAB 0xFEAB // ﺫ ARABIC LETTER THAL ISOLATED FORM
#define UC_MACRO_NAME_FEAC 0xFEAC // ﺬ ARABIC LETTER THAL FINAL FORM
#define UC_MACRO_NAME_FEAD 0xFEAD // ﺭ ARABIC LETTER REH ISOLATED FORM
#define UC_MACRO_NAME_FEAE 0xFEAE // ﺮ ARABIC LETTER REH FINAL FORM
#define UC_MACRO_NAME_FEAF 0xFEAF // ﺯ ARABIC LETTER ZAIN ISOLATED FORM
#define UC_MACRO_NAME_FEB0 0xFEB0 // ﺰ ARABIC LETTER ZAIN FINAL FORM
#define UC_MACRO_NAME_FEB1 0xFEB1 // ﺱ ARABIC LETTER SEEN ISOLATED FORM
#define UC_MACRO_NAME_FEB2 0xFEB2 // ﺲ ARABIC LETTER SEEN FINAL FORM
#define UC_MACRO_NAME_FEB3 0xFEB3 // ﺳ ARABIC LETTER SEEN INITIAL FORM
#define UC_MACRO_NAME_FEB4 0xFEB4 // ﺴ ARABIC LETTER SEEN MEDIAL FORM
#define UC_MACRO_NAME_FEB5 0xFEB5 // ﺵ ARABIC LETTER SHEEN ISOLATED FORM
#define UC_MACRO_NAME_FEB6 0xFEB6 // ﺶ ARABIC LETTER SHEEN FINAL FORM
#define UC_MACRO_NAME_FEB7 0xFEB7 // ﺷ ARABIC LETTER SHEEN INITIAL FORM
#define UC_MACRO_NAME_FEB8 0xFEB8 // ﺸ ARABIC LETTER SHEEN MEDIAL FORM
#define UC_MACRO_NAME_FEB9 0xFEB9 // ﺹ ARABIC LETTER SAD ISOLATED FORM
#define UC_MACRO_NAME_FEBA 0xFEBA // ﺺ ARABIC LETTER SAD FINAL FORM
#define UC_MACRO_NAME_FEBB 0xFEBB // ﺻ ARABIC LETTER SAD INITIAL FORM
#define UC_MACRO_NAME_FEBC 0xFEBC // ﺼ ARABIC LETTER SAD MEDIAL FORM
#define UC_MACRO_NAME_FEBD 0xFEBD // ﺽ ARABIC LETTER DAD ISOLATED FORM
#define UC_MACRO_NAME_FEBE 0xFEBE // ﺾ ARABIC LETTER DAD FINAL FORM
#define UC_MACRO_NAME_FEBF 0xFEBF // ﺿ ARABIC LETTER DAD INITIAL FORM
#define UC_MACRO_NAME_FEC0 0xFEC0 // ﻀ ARABIC LETTER DAD MEDIAL FORM
#define UC_MACRO_NAME_FEC1 0xFEC1 // ﻁ ARABIC LETTER TAH ISOLATED FORM
#define UC_MACRO_NAME_FEC2 0xFEC2 // ﻂ ARABIC LETTER TAH FINAL FORM
#define UC_MACRO_NAME_FEC3 0xFEC3 // ﻃ ARABIC LETTER TAH INITIAL FORM
#define UC_MACRO_NAME_FEC4 0xFEC4 // ﻄ ARABIC LETTER TAH MEDIAL FORM
#define UC_MACRO_NAME_FEC5 0xFEC5 // ﻅ ARABIC LETTER ZAH ISOLATED FORM
#define UC_MACRO_NAME_FEC6 0xFEC6 // ﻆ ARABIC LETTER ZAH FINAL FORM
#define UC_MACRO_NAME_FEC7 0xFEC7 // ﻇ ARABIC LETTER ZAH INITIAL FORM
#define UC_MACRO_NAME_FEC8 0xFEC8 // ﻈ ARABIC LETTER ZAH MEDIAL FORM
#define UC_MACRO_NAME_FEC9 0xFEC9 // ﻉ ARABIC LETTER AIN ISOLATED FORM
#define UC_MACRO_NAME_FECA 0xFECA // ﻊ ARABIC LETTER AIN FINAL FORM
#define UC_MACRO_NAME_FECB 0xFECB // ﻋ ARABIC LETTER AIN INITIAL FORM
#define UC_MACRO_NAME_FECC 0xFECC // ﻌ ARABIC LETTER AIN MEDIAL FORM
#define UC_MACRO_NAME_FECD 0xFECD // ﻍ ARABIC LETTER GHAIN ISOLATED FORM
#define UC_MACRO_NAME_FECE 0xFECE // ﻎ ARABIC LETTER GHAIN FINAL FORM
#define UC_MACRO_NAME_FECF 0xFECF // ﻏ ARABIC LETTER GHAIN INITIAL FORM
#define UC_MACRO_NAME_FED0 0xFED0 // ﻐ ARABIC LETTER GHAIN MEDIAL FORM
#define UC_MACRO_NAME_FED1 0xFED1 // ﻑ ARABIC LETTER FEH ISOLATED FORM
#define UC_MACRO_NAME_FED2 0xFED2 // ﻒ ARABIC LETTER FEH FINAL FORM
#define UC_MACRO_NAME_FED3 0xFED3 // ﻓ ARABIC LETTER FEH INITIAL FORM
#define UC_MACRO_NAME_FED4 0xFED4 // ﻔ ARABIC LETTER FEH MEDIAL FORM
#define UC_MACRO_NAME_FED5 0xFED5 // ﻕ ARABIC LETTER QAF ISOLATED FORM
#define UC_MACRO_NAME_FED6 0xFED6 // ﻖ ARABIC LETTER QAF FINAL FORM
#define UC_MACRO_NAME_FED7 0xFED7 // ﻗ ARABIC LETTER QAF INITIAL FORM
#define UC_MACRO_NAME_FED8 0xFED8 // ﻘ ARABIC LETTER QAF MEDIAL FORM
#define UC_MACRO_NAME_FED9 0xFED9 // ﻙ ARABIC LETTER KAF ISOLATED FORM
#define UC_MACRO_NAME_FEDA 0xFEDA // ﻚ ARABIC LETTER KAF FINAL FORM
#define UC_MACRO_NAME_FEDB 0xFEDB // ﻛ ARABIC LETTER KAF INITIAL FORM
#define UC_MACRO_NAME_FEDC 0xFEDC // ﻜ ARABIC LETTER KAF MEDIAL FORM
#define UC_MACRO_NAME_FEDD 0xFEDD // ﻝ ARABIC LETTER LAM ISOLATED FORM
#define UC_MACRO_NAME_FEDE 0xFEDE // ﻞ ARABIC LETTER LAM FINAL FORM
#define UC_MACRO_NAME_FEDF 0xFEDF // ﻟ ARABIC LETTER LAM INITIAL FORM
#define UC_MACRO_NAME_FEE0 0xFEE0 // ﻠ ARABIC LETTER LAM MEDIAL FORM
#define UC_MACRO_NAME_FEE1 0xFEE1 // ﻡ ARABIC LETTER MEEM ISOLATED FORM
#define UC_MACRO_NAME_FEE2 0xFEE2 // ﻢ ARABIC LETTER MEEM FINAL FORM
#define UC_MACRO_NAME_FEE3 0xFEE3 // ﻣ ARABIC LETTER MEEM INITIAL FORM
#define UC_MACRO_NAME_FEE4 0xFEE4 // ﻤ ARABIC LETTER MEEM MEDIAL FORM
#define UC_MACRO_NAME_FEE5 0xFEE5 // ﻥ ARABIC LETTER NOON ISOLATED FORM
#define UC_MACRO_NAME_FEE6 0xFEE6 // ﻦ ARABIC LETTER NOON FINAL FORM
#define UC_MACRO_NAME_FEE7 0xFEE7 // ﻧ ARABIC LETTER NOON INITIAL FORM
#define UC_MACRO_NAME_FEE8 0xFEE8 // ﻨ ARABIC LETTER NOON MEDIAL FORM
#define UC_MACRO_NAME_FEE9 0xFEE9 // ﻩ ARABIC LETTER HEH ISOLATED FORM
#define UC_MACRO_NAME_FEEA 0xFEEA // ﻪ ARABIC LETTER HEH FINAL FORM
#define UC_MACRO_NAME_FEEB 0xFEEB // ﻫ ARABIC LETTER HEH INITIAL FORM
#define UC_MACRO_NAME_FEEC 0xFEEC // ﻬ ARABIC LETTER HEH MEDIAL FORM
#define UC_MACRO_NAME_FEED 0xFEED // ﻭ ARABIC LETTER WAW ISOLATED FORM
#define UC_MACRO_NAME_FEEE 0xFEEE // ﻮ ARABIC LETTER WAW FINAL FORM
#define UC_MACRO_NAME_FEEF 0xFEEF // ﻯ ARABIC LETTER ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FEF0 0xFEF0 // ﻰ ARABIC LETTER ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FEF1 0xFEF1 // ﻱ ARABIC LETTER YEH ISOLATED FORM
#define UC_MACRO_NAME_FEF2 0xFEF2 // ﻲ ARABIC LETTER YEH FINAL FORM
#define UC_MACRO_NAME_FEF3 0xFEF3 // ﻳ ARABIC LETTER YEH INITIAL FORM
#define UC_MACRO_NAME_FEF4 0xFEF4 // ﻴ ARABIC LETTER YEH MEDIAL FORM
#define UC_MACRO_NAME_FEF5 0xFEF5 // ﻵ ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE ISOLATED FORM
#define UC_MACRO_NAME_FEF6 0xFEF6 // ﻶ ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE FINAL FORM
#define UC_MACRO_NAME_FEF7 0xFEF7 // ﻷ ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE ISOLATED FORM
#define UC_MACRO_NAME_FEF8 0xFEF8 // ﻸ ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE FINAL FORM
#define UC_MACRO_NAME_FEF9 0xFEF9 // ﻹ ARABIC LIGATURE LAM WITH ALEF WITH HAMZA BELOW ISOLATED FORM
#define UC_MACRO_NAME_FEFA 0xFEFA // ﻺ ARABIC LIGATURE LAM WITH ALEF WITH HAMZA BELOW FINAL FORM
#define UC_MACRO_NAME_FEFB 0xFEFB // ﻻ ARABIC LIGATURE LAM WITH ALEF ISOLATED FORM
#define UC_MACRO_NAME_FEFC 0xFEFC // ﻼ ARABIC LIGATURE LAM WITH ALEF FINAL FORM
#define UC_MACRO_NAME_FEFF 0xFEFF //  ZERO WIDTH NO-BREAK SPACE


#endif // UC_H_ARABIC_PRESENTATION_FORMS_B
