/*
 * Unicode Block: Arabic Mathematical Alphabetic Symbols
 * Range: U+1EE00..U+1EEFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS
#define UC_H_ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS

#define UC_MACRO_NAME_1EE00 0x1EE00 // 𞸀 ARABIC MATHEMATICAL ALEF
#define UC_MACRO_NAME_1EE01 0x1EE01 // 𞸁 ARABIC MATHEMATICAL BEH
#define UC_MACRO_NAME_1EE02 0x1EE02 // 𞸂 ARABIC MATHEMATICAL JEEM
#define UC_MACRO_NAME_1EE03 0x1EE03 // 𞸃 ARABIC MATHEMATICAL DAL
#define UC_MACRO_NAME_1EE05 0x1EE05 // 𞸅 ARABIC MATHEMATICAL WAW
#define UC_MACRO_NAME_1EE06 0x1EE06 // 𞸆 ARABIC MATHEMATICAL ZAIN
#define UC_MACRO_NAME_1EE07 0x1EE07 // 𞸇 ARABIC MATHEMATICAL HAH
#define UC_MACRO_NAME_1EE08 0x1EE08 // 𞸈 ARABIC MATHEMATICAL TAH
#define UC_MACRO_NAME_1EE09 0x1EE09 // 𞸉 ARABIC MATHEMATICAL YEH
#define UC_MACRO_NAME_1EE0A 0x1EE0A // 𞸊 ARABIC MATHEMATICAL KAF
#define UC_MACRO_NAME_1EE0B 0x1EE0B // 𞸋 ARABIC MATHEMATICAL LAM
#define UC_MACRO_NAME_1EE0C 0x1EE0C // 𞸌 ARABIC MATHEMATICAL MEEM
#define UC_MACRO_NAME_1EE0D 0x1EE0D // 𞸍 ARABIC MATHEMATICAL NOON
#define UC_MACRO_NAME_1EE0E 0x1EE0E // 𞸎 ARABIC MATHEMATICAL SEEN
#define UC_MACRO_NAME_1EE0F 0x1EE0F // 𞸏 ARABIC MATHEMATICAL AIN
#define UC_MACRO_NAME_1EE10 0x1EE10 // 𞸐 ARABIC MATHEMATICAL FEH
#define UC_MACRO_NAME_1EE11 0x1EE11 // 𞸑 ARABIC MATHEMATICAL SAD
#define UC_MACRO_NAME_1EE12 0x1EE12 // 𞸒 ARABIC MATHEMATICAL QAF
#define UC_MACRO_NAME_1EE13 0x1EE13 // 𞸓 ARABIC MATHEMATICAL REH
#define UC_MACRO_NAME_1EE14 0x1EE14 // 𞸔 ARABIC MATHEMATICAL SHEEN
#define UC_MACRO_NAME_1EE15 0x1EE15 // 𞸕 ARABIC MATHEMATICAL TEH
#define UC_MACRO_NAME_1EE16 0x1EE16 // 𞸖 ARABIC MATHEMATICAL THEH
#define UC_MACRO_NAME_1EE17 0x1EE17 // 𞸗 ARABIC MATHEMATICAL KHAH
#define UC_MACRO_NAME_1EE18 0x1EE18 // 𞸘 ARABIC MATHEMATICAL THAL
#define UC_MACRO_NAME_1EE19 0x1EE19 // 𞸙 ARABIC MATHEMATICAL DAD
#define UC_MACRO_NAME_1EE1A 0x1EE1A // 𞸚 ARABIC MATHEMATICAL ZAH
#define UC_MACRO_NAME_1EE1B 0x1EE1B // 𞸛 ARABIC MATHEMATICAL GHAIN
#define UC_MACRO_NAME_1EE1C 0x1EE1C // 𞸜 ARABIC MATHEMATICAL DOTLESS BEH
#define UC_MACRO_NAME_1EE1D 0x1EE1D // 𞸝 ARABIC MATHEMATICAL DOTLESS NOON
#define UC_MACRO_NAME_1EE1E 0x1EE1E // 𞸞 ARABIC MATHEMATICAL DOTLESS FEH
#define UC_MACRO_NAME_1EE1F 0x1EE1F // 𞸟 ARABIC MATHEMATICAL DOTLESS QAF
#define UC_MACRO_NAME_1EE21 0x1EE21 // 𞸡 ARABIC MATHEMATICAL INITIAL BEH
#define UC_MACRO_NAME_1EE22 0x1EE22 // 𞸢 ARABIC MATHEMATICAL INITIAL JEEM
#define UC_MACRO_NAME_1EE24 0x1EE24 // 𞸤 ARABIC MATHEMATICAL INITIAL HEH
#define UC_MACRO_NAME_1EE27 0x1EE27 // 𞸧 ARABIC MATHEMATICAL INITIAL HAH
#define UC_MACRO_NAME_1EE29 0x1EE29 // 𞸩 ARABIC MATHEMATICAL INITIAL YEH
#define UC_MACRO_NAME_1EE2A 0x1EE2A // 𞸪 ARABIC MATHEMATICAL INITIAL KAF
#define UC_MACRO_NAME_1EE2B 0x1EE2B // 𞸫 ARABIC MATHEMATICAL INITIAL LAM
#define UC_MACRO_NAME_1EE2C 0x1EE2C // 𞸬 ARABIC MATHEMATICAL INITIAL MEEM
#define UC_MACRO_NAME_1EE2D 0x1EE2D // 𞸭 ARABIC MATHEMATICAL INITIAL NOON
#define UC_MACRO_NAME_1EE2E 0x1EE2E // 𞸮 ARABIC MATHEMATICAL INITIAL SEEN
#define UC_MACRO_NAME_1EE2F 0x1EE2F // 𞸯 ARABIC MATHEMATICAL INITIAL AIN
#define UC_MACRO_NAME_1EE30 0x1EE30 // 𞸰 ARABIC MATHEMATICAL INITIAL FEH
#define UC_MACRO_NAME_1EE31 0x1EE31 // 𞸱 ARABIC MATHEMATICAL INITIAL SAD
#define UC_MACRO_NAME_1EE32 0x1EE32 // 𞸲 ARABIC MATHEMATICAL INITIAL QAF
#define UC_MACRO_NAME_1EE34 0x1EE34 // 𞸴 ARABIC MATHEMATICAL INITIAL SHEEN
#define UC_MACRO_NAME_1EE35 0x1EE35 // 𞸵 ARABIC MATHEMATICAL INITIAL TEH
#define UC_MACRO_NAME_1EE36 0x1EE36 // 𞸶 ARABIC MATHEMATICAL INITIAL THEH
#define UC_MACRO_NAME_1EE37 0x1EE37 // 𞸷 ARABIC MATHEMATICAL INITIAL KHAH
#define UC_MACRO_NAME_1EE39 0x1EE39 // 𞸹 ARABIC MATHEMATICAL INITIAL DAD
#define UC_MACRO_NAME_1EE3B 0x1EE3B // 𞸻 ARABIC MATHEMATICAL INITIAL GHAIN
#define UC_MACRO_NAME_1EE42 0x1EE42 // 𞹂 ARABIC MATHEMATICAL TAILED JEEM
#define UC_MACRO_NAME_1EE47 0x1EE47 // 𞹇 ARABIC MATHEMATICAL TAILED HAH
#define UC_MACRO_NAME_1EE49 0x1EE49 // 𞹉 ARABIC MATHEMATICAL TAILED YEH
#define UC_MACRO_NAME_1EE4B 0x1EE4B // 𞹋 ARABIC MATHEMATICAL TAILED LAM
#define UC_MACRO_NAME_1EE4D 0x1EE4D // 𞹍 ARABIC MATHEMATICAL TAILED NOON
#define UC_MACRO_NAME_1EE4E 0x1EE4E // 𞹎 ARABIC MATHEMATICAL TAILED SEEN
#define UC_MACRO_NAME_1EE4F 0x1EE4F // 𞹏 ARABIC MATHEMATICAL TAILED AIN
#define UC_MACRO_NAME_1EE51 0x1EE51 // 𞹑 ARABIC MATHEMATICAL TAILED SAD
#define UC_MACRO_NAME_1EE52 0x1EE52 // 𞹒 ARABIC MATHEMATICAL TAILED QAF
#define UC_MACRO_NAME_1EE54 0x1EE54 // 𞹔 ARABIC MATHEMATICAL TAILED SHEEN
#define UC_MACRO_NAME_1EE57 0x1EE57 // 𞹗 ARABIC MATHEMATICAL TAILED KHAH
#define UC_MACRO_NAME_1EE59 0x1EE59 // 𞹙 ARABIC MATHEMATICAL TAILED DAD
#define UC_MACRO_NAME_1EE5B 0x1EE5B // 𞹛 ARABIC MATHEMATICAL TAILED GHAIN
#define UC_MACRO_NAME_1EE5D 0x1EE5D // 𞹝 ARABIC MATHEMATICAL TAILED DOTLESS NOON
#define UC_MACRO_NAME_1EE5F 0x1EE5F // 𞹟 ARABIC MATHEMATICAL TAILED DOTLESS QAF
#define UC_MACRO_NAME_1EE61 0x1EE61 // 𞹡 ARABIC MATHEMATICAL STRETCHED BEH
#define UC_MACRO_NAME_1EE62 0x1EE62 // 𞹢 ARABIC MATHEMATICAL STRETCHED JEEM
#define UC_MACRO_NAME_1EE64 0x1EE64 // 𞹤 ARABIC MATHEMATICAL STRETCHED HEH
#define UC_MACRO_NAME_1EE67 0x1EE67 // 𞹧 ARABIC MATHEMATICAL STRETCHED HAH
#define UC_MACRO_NAME_1EE68 0x1EE68 // 𞹨 ARABIC MATHEMATICAL STRETCHED TAH
#define UC_MACRO_NAME_1EE69 0x1EE69 // 𞹩 ARABIC MATHEMATICAL STRETCHED YEH
#define UC_MACRO_NAME_1EE6A 0x1EE6A // 𞹪 ARABIC MATHEMATICAL STRETCHED KAF
#define UC_MACRO_NAME_1EE6C 0x1EE6C // 𞹬 ARABIC MATHEMATICAL STRETCHED MEEM
#define UC_MACRO_NAME_1EE6D 0x1EE6D // 𞹭 ARABIC MATHEMATICAL STRETCHED NOON
#define UC_MACRO_NAME_1EE6E 0x1EE6E // 𞹮 ARABIC MATHEMATICAL STRETCHED SEEN
#define UC_MACRO_NAME_1EE6F 0x1EE6F // 𞹯 ARABIC MATHEMATICAL STRETCHED AIN
#define UC_MACRO_NAME_1EE70 0x1EE70 // 𞹰 ARABIC MATHEMATICAL STRETCHED FEH
#define UC_MACRO_NAME_1EE71 0x1EE71 // 𞹱 ARABIC MATHEMATICAL STRETCHED SAD
#define UC_MACRO_NAME_1EE72 0x1EE72 // 𞹲 ARABIC MATHEMATICAL STRETCHED QAF
#define UC_MACRO_NAME_1EE74 0x1EE74 // 𞹴 ARABIC MATHEMATICAL STRETCHED SHEEN
#define UC_MACRO_NAME_1EE75 0x1EE75 // 𞹵 ARABIC MATHEMATICAL STRETCHED TEH
#define UC_MACRO_NAME_1EE76 0x1EE76 // 𞹶 ARABIC MATHEMATICAL STRETCHED THEH
#define UC_MACRO_NAME_1EE77 0x1EE77 // 𞹷 ARABIC MATHEMATICAL STRETCHED KHAH
#define UC_MACRO_NAME_1EE79 0x1EE79 // 𞹹 ARABIC MATHEMATICAL STRETCHED DAD
#define UC_MACRO_NAME_1EE7A 0x1EE7A // 𞹺 ARABIC MATHEMATICAL STRETCHED ZAH
#define UC_MACRO_NAME_1EE7B 0x1EE7B // 𞹻 ARABIC MATHEMATICAL STRETCHED GHAIN
#define UC_MACRO_NAME_1EE7C 0x1EE7C // 𞹼 ARABIC MATHEMATICAL STRETCHED DOTLESS BEH
#define UC_MACRO_NAME_1EE7E 0x1EE7E // 𞹾 ARABIC MATHEMATICAL STRETCHED DOTLESS FEH
#define UC_MACRO_NAME_1EE80 0x1EE80 // 𞺀 ARABIC MATHEMATICAL LOOPED ALEF
#define UC_MACRO_NAME_1EE81 0x1EE81 // 𞺁 ARABIC MATHEMATICAL LOOPED BEH
#define UC_MACRO_NAME_1EE82 0x1EE82 // 𞺂 ARABIC MATHEMATICAL LOOPED JEEM
#define UC_MACRO_NAME_1EE83 0x1EE83 // 𞺃 ARABIC MATHEMATICAL LOOPED DAL
#define UC_MACRO_NAME_1EE84 0x1EE84 // 𞺄 ARABIC MATHEMATICAL LOOPED HEH
#define UC_MACRO_NAME_1EE85 0x1EE85 // 𞺅 ARABIC MATHEMATICAL LOOPED WAW
#define UC_MACRO_NAME_1EE86 0x1EE86 // 𞺆 ARABIC MATHEMATICAL LOOPED ZAIN
#define UC_MACRO_NAME_1EE87 0x1EE87 // 𞺇 ARABIC MATHEMATICAL LOOPED HAH
#define UC_MACRO_NAME_1EE88 0x1EE88 // 𞺈 ARABIC MATHEMATICAL LOOPED TAH
#define UC_MACRO_NAME_1EE89 0x1EE89 // 𞺉 ARABIC MATHEMATICAL LOOPED YEH
#define UC_MACRO_NAME_1EE8B 0x1EE8B // 𞺋 ARABIC MATHEMATICAL LOOPED LAM
#define UC_MACRO_NAME_1EE8C 0x1EE8C // 𞺌 ARABIC MATHEMATICAL LOOPED MEEM
#define UC_MACRO_NAME_1EE8D 0x1EE8D // 𞺍 ARABIC MATHEMATICAL LOOPED NOON
#define UC_MACRO_NAME_1EE8E 0x1EE8E // 𞺎 ARABIC MATHEMATICAL LOOPED SEEN
#define UC_MACRO_NAME_1EE8F 0x1EE8F // 𞺏 ARABIC MATHEMATICAL LOOPED AIN
#define UC_MACRO_NAME_1EE90 0x1EE90 // 𞺐 ARABIC MATHEMATICAL LOOPED FEH
#define UC_MACRO_NAME_1EE91 0x1EE91 // 𞺑 ARABIC MATHEMATICAL LOOPED SAD
#define UC_MACRO_NAME_1EE92 0x1EE92 // 𞺒 ARABIC MATHEMATICAL LOOPED QAF
#define UC_MACRO_NAME_1EE93 0x1EE93 // 𞺓 ARABIC MATHEMATICAL LOOPED REH
#define UC_MACRO_NAME_1EE94 0x1EE94 // 𞺔 ARABIC MATHEMATICAL LOOPED SHEEN
#define UC_MACRO_NAME_1EE95 0x1EE95 // 𞺕 ARABIC MATHEMATICAL LOOPED TEH
#define UC_MACRO_NAME_1EE96 0x1EE96 // 𞺖 ARABIC MATHEMATICAL LOOPED THEH
#define UC_MACRO_NAME_1EE97 0x1EE97 // 𞺗 ARABIC MATHEMATICAL LOOPED KHAH
#define UC_MACRO_NAME_1EE98 0x1EE98 // 𞺘 ARABIC MATHEMATICAL LOOPED THAL
#define UC_MACRO_NAME_1EE99 0x1EE99 // 𞺙 ARABIC MATHEMATICAL LOOPED DAD
#define UC_MACRO_NAME_1EE9A 0x1EE9A // 𞺚 ARABIC MATHEMATICAL LOOPED ZAH
#define UC_MACRO_NAME_1EE9B 0x1EE9B // 𞺛 ARABIC MATHEMATICAL LOOPED GHAIN
#define UC_MACRO_NAME_1EEA1 0x1EEA1 // 𞺡 ARABIC MATHEMATICAL DOUBLE-STRUCK BEH
#define UC_MACRO_NAME_1EEA2 0x1EEA2 // 𞺢 ARABIC MATHEMATICAL DOUBLE-STRUCK JEEM
#define UC_MACRO_NAME_1EEA3 0x1EEA3 // 𞺣 ARABIC MATHEMATICAL DOUBLE-STRUCK DAL
#define UC_MACRO_NAME_1EEA5 0x1EEA5 // 𞺥 ARABIC MATHEMATICAL DOUBLE-STRUCK WAW
#define UC_MACRO_NAME_1EEA6 0x1EEA6 // 𞺦 ARABIC MATHEMATICAL DOUBLE-STRUCK ZAIN
#define UC_MACRO_NAME_1EEA7 0x1EEA7 // 𞺧 ARABIC MATHEMATICAL DOUBLE-STRUCK HAH
#define UC_MACRO_NAME_1EEA8 0x1EEA8 // 𞺨 ARABIC MATHEMATICAL DOUBLE-STRUCK TAH
#define UC_MACRO_NAME_1EEA9 0x1EEA9 // 𞺩 ARABIC MATHEMATICAL DOUBLE-STRUCK YEH
#define UC_MACRO_NAME_1EEAB 0x1EEAB // 𞺫 ARABIC MATHEMATICAL DOUBLE-STRUCK LAM
#define UC_MACRO_NAME_1EEAC 0x1EEAC // 𞺬 ARABIC MATHEMATICAL DOUBLE-STRUCK MEEM
#define UC_MACRO_NAME_1EEAD 0x1EEAD // 𞺭 ARABIC MATHEMATICAL DOUBLE-STRUCK NOON
#define UC_MACRO_NAME_1EEAE 0x1EEAE // 𞺮 ARABIC MATHEMATICAL DOUBLE-STRUCK SEEN
#define UC_MACRO_NAME_1EEAF 0x1EEAF // 𞺯 ARABIC MATHEMATICAL DOUBLE-STRUCK AIN
#define UC_MACRO_NAME_1EEB0 0x1EEB0 // 𞺰 ARABIC MATHEMATICAL DOUBLE-STRUCK FEH
#define UC_MACRO_NAME_1EEB1 0x1EEB1 // 𞺱 ARABIC MATHEMATICAL DOUBLE-STRUCK SAD
#define UC_MACRO_NAME_1EEB2 0x1EEB2 // 𞺲 ARABIC MATHEMATICAL DOUBLE-STRUCK QAF
#define UC_MACRO_NAME_1EEB3 0x1EEB3 // 𞺳 ARABIC MATHEMATICAL DOUBLE-STRUCK REH
#define UC_MACRO_NAME_1EEB4 0x1EEB4 // 𞺴 ARABIC MATHEMATICAL DOUBLE-STRUCK SHEEN
#define UC_MACRO_NAME_1EEB5 0x1EEB5 // 𞺵 ARABIC MATHEMATICAL DOUBLE-STRUCK TEH
#define UC_MACRO_NAME_1EEB6 0x1EEB6 // 𞺶 ARABIC MATHEMATICAL DOUBLE-STRUCK THEH
#define UC_MACRO_NAME_1EEB7 0x1EEB7 // 𞺷 ARABIC MATHEMATICAL DOUBLE-STRUCK KHAH
#define UC_MACRO_NAME_1EEB8 0x1EEB8 // 𞺸 ARABIC MATHEMATICAL DOUBLE-STRUCK THAL
#define UC_MACRO_NAME_1EEB9 0x1EEB9 // 𞺹 ARABIC MATHEMATICAL DOUBLE-STRUCK DAD
#define UC_MACRO_NAME_1EEBA 0x1EEBA // 𞺺 ARABIC MATHEMATICAL DOUBLE-STRUCK ZAH
#define UC_MACRO_NAME_1EEBB 0x1EEBB // 𞺻 ARABIC MATHEMATICAL DOUBLE-STRUCK GHAIN
#define UC_MACRO_NAME_1EEF0 0x1EEF0 // 𞻰 ARABIC MATHEMATICAL OPERATOR MEEM WITH HAH WITH TATWEEL
#define UC_MACRO_NAME_1EEF1 0x1EEF1 // 𞻱 ARABIC MATHEMATICAL OPERATOR HAH WITH DAL


#endif // UC_H_ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS
