/*
 * Unicode Block: Arabic Extended-A
 * Range: U+08A0..U+08FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_ARABIC_EXTENDED_A
#define UC_H_ARABIC_EXTENDED_A

#define UC_MACRO_NAME_8A0 0x08A0 // ࢠ ARABIC LETTER BEH WITH SMALL V BELOW
#define UC_MACRO_NAME_8A1 0x08A1 // ࢡ ARABIC LETTER BEH WITH HAMZA ABOVE
#define UC_MACRO_NAME_8A2 0x08A2 // ࢢ ARABIC LETTER JEEM WITH TWO DOTS ABOVE
#define UC_MACRO_NAME_8A3 0x08A3 // ࢣ ARABIC LETTER TAH WITH TWO DOTS ABOVE
#define UC_MACRO_NAME_8A4 0x08A4 // ࢤ ARABIC LETTER FEH WITH DOT BELOW AND THREE DOTS ABOVE
#define UC_MACRO_NAME_8A5 0x08A5 // ࢥ ARABIC LETTER QAF WITH DOT BELOW
#define UC_MACRO_NAME_8A6 0x08A6 // ࢦ ARABIC LETTER LAM WITH DOUBLE BAR
#define UC_MACRO_NAME_8A7 0x08A7 // ࢧ ARABIC LETTER MEEM WITH THREE DOTS ABOVE
#define UC_MACRO_NAME_8A8 0x08A8 // ࢨ ARABIC LETTER YEH WITH TWO DOTS BELOW AND HAMZA ABOVE
#define UC_MACRO_NAME_8A9 0x08A9 // ࢩ ARABIC LETTER YEH WITH TWO DOTS BELOW AND DOT ABOVE
#define UC_MACRO_NAME_8AA 0x08AA // ࢪ ARABIC LETTER REH WITH LOOP
#define UC_MACRO_NAME_8AB 0x08AB // ࢫ ARABIC LETTER WAW WITH DOT WITHIN
#define UC_MACRO_NAME_8AC 0x08AC // ࢬ ARABIC LETTER ROHINGYA YEH
#define UC_MACRO_NAME_8AD 0x08AD // ࢭ ARABIC LETTER LOW ALEF
#define UC_MACRO_NAME_8AE 0x08AE // ࢮ ARABIC LETTER DAL WITH THREE DOTS BELOW
#define UC_MACRO_NAME_8AF 0x08AF // ࢯ ARABIC LETTER SAD WITH THREE DOTS BELOW
#define UC_MACRO_NAME_8B0 0x08B0 // ࢰ ARABIC LETTER GAF WITH INVERTED STROKE
#define UC_MACRO_NAME_8B1 0x08B1 // ࢱ ARABIC LETTER STRAIGHT WAW
#define UC_MACRO_NAME_8B2 0x08B2 // ࢲ ARABIC LETTER ZAIN WITH INVERTED V ABOVE
#define UC_MACRO_NAME_8B3 0x08B3 // ࢳ ARABIC LETTER AIN WITH THREE DOTS BELOW
#define UC_MACRO_NAME_8B4 0x08B4 // ࢴ ARABIC LETTER KAF WITH DOT BELOW
#define UC_MACRO_NAME_8B5 0x08B5 // ࢵ ARABIC LETTER QAF WITH DOT BELOW AND NO DOTS ABOVE
#define UC_MACRO_NAME_8B6 0x08B6 // ࢶ ARABIC LETTER BEH WITH SMALL MEEM ABOVE
#define UC_MACRO_NAME_8B7 0x08B7 // ࢷ ARABIC LETTER PEH WITH SMALL MEEM ABOVE
#define UC_MACRO_NAME_8B8 0x08B8 // ࢸ ARABIC LETTER TEH WITH SMALL TEH ABOVE
#define UC_MACRO_NAME_8B9 0x08B9 // ࢹ ARABIC LETTER REH WITH SMALL NOON ABOVE
#define UC_MACRO_NAME_8BA 0x08BA // ࢺ ARABIC LETTER YEH WITH TWO DOTS BELOW AND SMALL NOON ABOVE
#define UC_MACRO_NAME_8BB 0x08BB // ࢻ ARABIC LETTER AFRICAN FEH
#define UC_MACRO_NAME_8BC 0x08BC // ࢼ ARABIC LETTER AFRICAN QAF
#define UC_MACRO_NAME_8BD 0x08BD // ࢽ ARABIC LETTER AFRICAN NOON
#define UC_MACRO_NAME_8BE 0x08BE // ࢾ ARABIC LETTER PEH WITH SMALL V
#define UC_MACRO_NAME_8BF 0x08BF // ࢿ ARABIC LETTER TEH WITH SMALL V
#define UC_MACRO_NAME_8C0 0x08C0 // ࣀ ARABIC LETTER TTEH WITH SMALL V
#define UC_MACRO_NAME_8C1 0x08C1 // ࣁ ARABIC LETTER TCHEH WITH SMALL V
#define UC_MACRO_NAME_8C2 0x08C2 // ࣂ ARABIC LETTER KEHEH WITH SMALL V
#define UC_MACRO_NAME_8C3 0x08C3 // ࣃ ARABIC LETTER GHAIN WITH THREE DOTS ABOVE
#define UC_MACRO_NAME_8C4 0x08C4 // ࣄ ARABIC LETTER AFRICAN QAF WITH THREE DOTS ABOVE
#define UC_MACRO_NAME_8C5 0x08C5 // ࣅ ARABIC LETTER JEEM WITH THREE DOTS ABOVE
#define UC_MACRO_NAME_8C6 0x08C6 // ࣆ ARABIC LETTER JEEM WITH THREE DOTS BELOW
#define UC_MACRO_NAME_8C7 0x08C7 // ࣇ ARABIC LETTER LAM WITH SMALL ARABIC LETTER TAH ABOVE
#define UC_MACRO_NAME_8C8 0x08C8 // ࣈ ARABIC LETTER GRAF
#define UC_MACRO_NAME_8C9 0x08C9 // ࣉ ARABIC SMALL FARSI YEH
#define UC_MACRO_NAME_8CA 0x08CA // ࣊ ARABIC SMALL HIGH FARSI YEH
#define UC_MACRO_NAME_8CB 0x08CB // ࣋ ARABIC SMALL HIGH YEH BARREE WITH TWO DOTS BELOW
#define UC_MACRO_NAME_8CC 0x08CC // ࣌ ARABIC SMALL HIGH WORD SAH
#define UC_MACRO_NAME_8CD 0x08CD // ࣍ ARABIC SMALL HIGH ZAH
#define UC_MACRO_NAME_8CE 0x08CE // ࣎ ARABIC LARGE ROUND DOT ABOVE
#define UC_MACRO_NAME_8CF 0x08CF // ࣏ ARABIC LARGE ROUND DOT BELOW
#define UC_MACRO_NAME_8D0 0x08D0 // ࣐ ARABIC SUKUN BELOW
#define UC_MACRO_NAME_8D1 0x08D1 // ࣑ ARABIC LARGE CIRCLE BELOW
#define UC_MACRO_NAME_8D2 0x08D2 // ࣒ ARABIC LARGE ROUND DOT INSIDE CIRCLE BELOW
#define UC_MACRO_NAME_8D3 0x08D3 // ࣓ ARABIC SMALL LOW WAW
#define UC_MACRO_NAME_8D4 0x08D4 // ࣔ ARABIC SMALL HIGH WORD AR-RUB
#define UC_MACRO_NAME_8D5 0x08D5 // ࣕ ARABIC SMALL HIGH SAD
#define UC_MACRO_NAME_8D6 0x08D6 // ࣖ ARABIC SMALL HIGH AIN
#define UC_MACRO_NAME_8D7 0x08D7 // ࣗ ARABIC SMALL HIGH QAF
#define UC_MACRO_NAME_8D8 0x08D8 // ࣘ ARABIC SMALL HIGH NOON WITH KASRA
#define UC_MACRO_NAME_8D9 0x08D9 // ࣙ ARABIC SMALL LOW NOON WITH KASRA
#define UC_MACRO_NAME_8DA 0x08DA // ࣚ ARABIC SMALL HIGH WORD ATH-THALATHA
#define UC_MACRO_NAME_8DB 0x08DB // ࣛ ARABIC SMALL HIGH WORD AS-SAJDA
#define UC_MACRO_NAME_8DC 0x08DC // ࣜ ARABIC SMALL HIGH WORD AN-NISF
#define UC_MACRO_NAME_8DD 0x08DD // ࣝ ARABIC SMALL HIGH WORD SAKTA
#define UC_MACRO_NAME_8DE 0x08DE // ࣞ ARABIC SMALL HIGH WORD QIF
#define UC_MACRO_NAME_8DF 0x08DF // ࣟ ARABIC SMALL HIGH WORD WAQFA
#define UC_MACRO_NAME_8E0 0x08E0 // ࣠ ARABIC SMALL HIGH FOOTNOTE MARKER
#define UC_MACRO_NAME_8E1 0x08E1 // ࣡ ARABIC SMALL HIGH SIGN SAFHA
#define UC_MACRO_NAME_8E2 0x08E2 //  ARABIC DISPUTED END OF AYAH
#define UC_MACRO_NAME_8E3 0x08E3 // ࣣ ARABIC TURNED DAMMA BELOW
#define UC_MACRO_NAME_8E4 0x08E4 // ࣤ ARABIC CURLY FATHA
#define UC_MACRO_NAME_8E5 0x08E5 // ࣥ ARABIC CURLY DAMMA
#define UC_MACRO_NAME_8E6 0x08E6 // ࣦ ARABIC CURLY KASRA
#define UC_MACRO_NAME_8E7 0x08E7 // ࣧ ARABIC CURLY FATHATAN
#define UC_MACRO_NAME_8E8 0x08E8 // ࣨ ARABIC CURLY DAMMATAN
#define UC_MACRO_NAME_8E9 0x08E9 // ࣩ ARABIC CURLY KASRATAN
#define UC_MACRO_NAME_8EA 0x08EA // ࣪ ARABIC TONE ONE DOT ABOVE
#define UC_MACRO_NAME_8EB 0x08EB // ࣫ ARABIC TONE TWO DOTS ABOVE
#define UC_MACRO_NAME_8EC 0x08EC // ࣬ ARABIC TONE LOOP ABOVE
#define UC_MACRO_NAME_8ED 0x08ED // ࣭ ARABIC TONE ONE DOT BELOW
#define UC_MACRO_NAME_8EE 0x08EE // ࣮ ARABIC TONE TWO DOTS BELOW
#define UC_MACRO_NAME_8EF 0x08EF // ࣯ ARABIC TONE LOOP BELOW
#define UC_MACRO_NAME_8F0 0x08F0 // ࣰ ARABIC OPEN FATHATAN
#define UC_MACRO_NAME_8F1 0x08F1 // ࣱ ARABIC OPEN DAMMATAN
#define UC_MACRO_NAME_8F2 0x08F2 // ࣲ ARABIC OPEN KASRATAN
#define UC_MACRO_NAME_8F3 0x08F3 // ࣳ ARABIC SMALL HIGH WAW
#define UC_MACRO_NAME_8F4 0x08F4 // ࣴ ARABIC FATHA WITH RING
#define UC_MACRO_NAME_8F5 0x08F5 // ࣵ ARABIC FATHA WITH DOT ABOVE
#define UC_MACRO_NAME_8F6 0x08F6 // ࣶ ARABIC KASRA WITH DOT BELOW
#define UC_MACRO_NAME_8F7 0x08F7 // ࣷ ARABIC LEFT ARROWHEAD ABOVE
#define UC_MACRO_NAME_8F8 0x08F8 // ࣸ ARABIC RIGHT ARROWHEAD ABOVE
#define UC_MACRO_NAME_8F9 0x08F9 // ࣹ ARABIC LEFT ARROWHEAD BELOW
#define UC_MACRO_NAME_8FA 0x08FA // ࣺ ARABIC RIGHT ARROWHEAD BELOW
#define UC_MACRO_NAME_8FB 0x08FB // ࣻ ARABIC DOUBLE RIGHT ARROWHEAD ABOVE
#define UC_MACRO_NAME_8FC 0x08FC // ࣼ ARABIC DOUBLE RIGHT ARROWHEAD ABOVE WITH DOT
#define UC_MACRO_NAME_8FD 0x08FD // ࣽ ARABIC RIGHT ARROWHEAD ABOVE WITH DOT
#define UC_MACRO_NAME_8FE 0x08FE // ࣾ ARABIC DAMMA WITH DOT
#define UC_MACRO_NAME_8FF 0x08FF // ࣿ ARABIC MARK SIDEWAYS NOON GHUNNA


#endif // UC_H_ARABIC_EXTENDED_A
