/*
 * Unicode Block: Arabic Presentation Forms-A
 * Range: U+FB50..U+FDFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_ARABIC_PRESENTATION_FORMS_A
#define UC_H_ARABIC_PRESENTATION_FORMS_A

#define UC_MACRO_NAME_FB50 0xFB50 // ﭐ ARABIC LETTER ALEF WASLA ISOLATED FORM
#define UC_MACRO_NAME_FB51 0xFB51 // ﭑ ARABIC LETTER ALEF WASLA FINAL FORM
#define UC_MACRO_NAME_FB52 0xFB52 // ﭒ ARABIC LETTER BEEH ISOLATED FORM
#define UC_MACRO_NAME_FB53 0xFB53 // ﭓ ARABIC LETTER BEEH FINAL FORM
#define UC_MACRO_NAME_FB54 0xFB54 // ﭔ ARABIC LETTER BEEH INITIAL FORM
#define UC_MACRO_NAME_FB55 0xFB55 // ﭕ ARABIC LETTER BEEH MEDIAL FORM
#define UC_MACRO_NAME_FB56 0xFB56 // ﭖ ARABIC LETTER PEH ISOLATED FORM
#define UC_MACRO_NAME_FB57 0xFB57 // ﭗ ARABIC LETTER PEH FINAL FORM
#define UC_MACRO_NAME_FB58 0xFB58 // ﭘ ARABIC LETTER PEH INITIAL FORM
#define UC_MACRO_NAME_FB59 0xFB59 // ﭙ ARABIC LETTER PEH MEDIAL FORM
#define UC_MACRO_NAME_FB5A 0xFB5A // ﭚ ARABIC LETTER BEHEH ISOLATED FORM
#define UC_MACRO_NAME_FB5B 0xFB5B // ﭛ ARABIC LETTER BEHEH FINAL FORM
#define UC_MACRO_NAME_FB5C 0xFB5C // ﭜ ARABIC LETTER BEHEH INITIAL FORM
#define UC_MACRO_NAME_FB5D 0xFB5D // ﭝ ARABIC LETTER BEHEH MEDIAL FORM
#define UC_MACRO_NAME_FB5E 0xFB5E // ﭞ ARABIC LETTER TTEHEH ISOLATED FORM
#define UC_MACRO_NAME_FB5F 0xFB5F // ﭟ ARABIC LETTER TTEHEH FINAL FORM
#define UC_MACRO_NAME_FB60 0xFB60 // ﭠ ARABIC LETTER TTEHEH INITIAL FORM
#define UC_MACRO_NAME_FB61 0xFB61 // ﭡ ARABIC LETTER TTEHEH MEDIAL FORM
#define UC_MACRO_NAME_FB62 0xFB62 // ﭢ ARABIC LETTER TEHEH ISOLATED FORM
#define UC_MACRO_NAME_FB63 0xFB63 // ﭣ ARABIC LETTER TEHEH FINAL FORM
#define UC_MACRO_NAME_FB64 0xFB64 // ﭤ ARABIC LETTER TEHEH INITIAL FORM
#define UC_MACRO_NAME_FB65 0xFB65 // ﭥ ARABIC LETTER TEHEH MEDIAL FORM
#define UC_MACRO_NAME_FB66 0xFB66 // ﭦ ARABIC LETTER TTEH ISOLATED FORM
#define UC_MACRO_NAME_FB67 0xFB67 // ﭧ ARABIC LETTER TTEH FINAL FORM
#define UC_MACRO_NAME_FB68 0xFB68 // ﭨ ARABIC LETTER TTEH INITIAL FORM
#define UC_MACRO_NAME_FB69 0xFB69 // ﭩ ARABIC LETTER TTEH MEDIAL FORM
#define UC_MACRO_NAME_FB6A 0xFB6A // ﭪ ARABIC LETTER VEH ISOLATED FORM
#define UC_MACRO_NAME_FB6B 0xFB6B // ﭫ ARABIC LETTER VEH FINAL FORM
#define UC_MACRO_NAME_FB6C 0xFB6C // ﭬ ARABIC LETTER VEH INITIAL FORM
#define UC_MACRO_NAME_FB6D 0xFB6D // ﭭ ARABIC LETTER VEH MEDIAL FORM
#define UC_MACRO_NAME_FB6E 0xFB6E // ﭮ ARABIC LETTER PEHEH ISOLATED FORM
#define UC_MACRO_NAME_FB6F 0xFB6F // ﭯ ARABIC LETTER PEHEH FINAL FORM
#define UC_MACRO_NAME_FB70 0xFB70 // ﭰ ARABIC LETTER PEHEH INITIAL FORM
#define UC_MACRO_NAME_FB71 0xFB71 // ﭱ ARABIC LETTER PEHEH MEDIAL FORM
#define UC_MACRO_NAME_FB72 0xFB72 // ﭲ ARABIC LETTER DYEH ISOLATED FORM
#define UC_MACRO_NAME_FB73 0xFB73 // ﭳ ARABIC LETTER DYEH FINAL FORM
#define UC_MACRO_NAME_FB74 0xFB74 // ﭴ ARABIC LETTER DYEH INITIAL FORM
#define UC_MACRO_NAME_FB75 0xFB75 // ﭵ ARABIC LETTER DYEH MEDIAL FORM
#define UC_MACRO_NAME_FB76 0xFB76 // ﭶ ARABIC LETTER NYEH ISOLATED FORM
#define UC_MACRO_NAME_FB77 0xFB77 // ﭷ ARABIC LETTER NYEH FINAL FORM
#define UC_MACRO_NAME_FB78 0xFB78 // ﭸ ARABIC LETTER NYEH INITIAL FORM
#define UC_MACRO_NAME_FB79 0xFB79 // ﭹ ARABIC LETTER NYEH MEDIAL FORM
#define UC_MACRO_NAME_FB7A 0xFB7A // ﭺ ARABIC LETTER TCHEH ISOLATED FORM
#define UC_MACRO_NAME_FB7B 0xFB7B // ﭻ ARABIC LETTER TCHEH FINAL FORM
#define UC_MACRO_NAME_FB7C 0xFB7C // ﭼ ARABIC LETTER TCHEH INITIAL FORM
#define UC_MACRO_NAME_FB7D 0xFB7D // ﭽ ARABIC LETTER TCHEH MEDIAL FORM
#define UC_MACRO_NAME_FB7E 0xFB7E // ﭾ ARABIC LETTER TCHEHEH ISOLATED FORM
#define UC_MACRO_NAME_FB7F 0xFB7F // ﭿ ARABIC LETTER TCHEHEH FINAL FORM
#define UC_MACRO_NAME_FB80 0xFB80 // ﮀ ARABIC LETTER TCHEHEH INITIAL FORM
#define UC_MACRO_NAME_FB81 0xFB81 // ﮁ ARABIC LETTER TCHEHEH MEDIAL FORM
#define UC_MACRO_NAME_FB82 0xFB82 // ﮂ ARABIC LETTER DDAHAL ISOLATED FORM
#define UC_MACRO_NAME_FB83 0xFB83 // ﮃ ARABIC LETTER DDAHAL FINAL FORM
#define UC_MACRO_NAME_FB84 0xFB84 // ﮄ ARABIC LETTER DAHAL ISOLATED FORM
#define UC_MACRO_NAME_FB85 0xFB85 // ﮅ ARABIC LETTER DAHAL FINAL FORM
#define UC_MACRO_NAME_FB86 0xFB86 // ﮆ ARABIC LETTER DUL ISOLATED FORM
#define UC_MACRO_NAME_FB87 0xFB87 // ﮇ ARABIC LETTER DUL FINAL FORM
#define UC_MACRO_NAME_FB88 0xFB88 // ﮈ ARABIC LETTER DDAL ISOLATED FORM
#define UC_MACRO_NAME_FB89 0xFB89 // ﮉ ARABIC LETTER DDAL FINAL FORM
#define UC_MACRO_NAME_FB8A 0xFB8A // ﮊ ARABIC LETTER JEH ISOLATED FORM
#define UC_MACRO_NAME_FB8B 0xFB8B // ﮋ ARABIC LETTER JEH FINAL FORM
#define UC_MACRO_NAME_FB8C 0xFB8C // ﮌ ARABIC LETTER RREH ISOLATED FORM
#define UC_MACRO_NAME_FB8D 0xFB8D // ﮍ ARABIC LETTER RREH FINAL FORM
#define UC_MACRO_NAME_FB8E 0xFB8E // ﮎ ARABIC LETTER KEHEH ISOLATED FORM
#define UC_MACRO_NAME_FB8F 0xFB8F // ﮏ ARABIC LETTER KEHEH FINAL FORM
#define UC_MACRO_NAME_FB90 0xFB90 // ﮐ ARABIC LETTER KEHEH INITIAL FORM
#define UC_MACRO_NAME_FB91 0xFB91 // ﮑ ARABIC LETTER KEHEH MEDIAL FORM
#define UC_MACRO_NAME_FB92 0xFB92 // ﮒ ARABIC LETTER GAF ISOLATED FORM
#define UC_MACRO_NAME_FB93 0xFB93 // ﮓ ARABIC LETTER GAF FINAL FORM
#define UC_MACRO_NAME_FB94 0xFB94 // ﮔ ARABIC LETTER GAF INITIAL FORM
#define UC_MACRO_NAME_FB95 0xFB95 // ﮕ ARABIC LETTER GAF MEDIAL FORM
#define UC_MACRO_NAME_FB96 0xFB96 // ﮖ ARABIC LETTER GUEH ISOLATED FORM
#define UC_MACRO_NAME_FB97 0xFB97 // ﮗ ARABIC LETTER GUEH FINAL FORM
#define UC_MACRO_NAME_FB98 0xFB98 // ﮘ ARABIC LETTER GUEH INITIAL FORM
#define UC_MACRO_NAME_FB99 0xFB99 // ﮙ ARABIC LETTER GUEH MEDIAL FORM
#define UC_MACRO_NAME_FB9A 0xFB9A // ﮚ ARABIC LETTER NGOEH ISOLATED FORM
#define UC_MACRO_NAME_FB9B 0xFB9B // ﮛ ARABIC LETTER NGOEH FINAL FORM
#define UC_MACRO_NAME_FB9C 0xFB9C // ﮜ ARABIC LETTER NGOEH INITIAL FORM
#define UC_MACRO_NAME_FB9D 0xFB9D // ﮝ ARABIC LETTER NGOEH MEDIAL FORM
#define UC_MACRO_NAME_FB9E 0xFB9E // ﮞ ARABIC LETTER NOON GHUNNA ISOLATED FORM
#define UC_MACRO_NAME_FB9F 0xFB9F // ﮟ ARABIC LETTER NOON GHUNNA FINAL FORM
#define UC_MACRO_NAME_FBA0 0xFBA0 // ﮠ ARABIC LETTER RNOON ISOLATED FORM
#define UC_MACRO_NAME_FBA1 0xFBA1 // ﮡ ARABIC LETTER RNOON FINAL FORM
#define UC_MACRO_NAME_FBA2 0xFBA2 // ﮢ ARABIC LETTER RNOON INITIAL FORM
#define UC_MACRO_NAME_FBA3 0xFBA3 // ﮣ ARABIC LETTER RNOON MEDIAL FORM
#define UC_MACRO_NAME_FBA4 0xFBA4 // ﮤ ARABIC LETTER HEH WITH YEH ABOVE ISOLATED FORM
#define UC_MACRO_NAME_FBA5 0xFBA5 // ﮥ ARABIC LETTER HEH WITH YEH ABOVE FINAL FORM
#define UC_MACRO_NAME_FBA6 0xFBA6 // ﮦ ARABIC LETTER HEH GOAL ISOLATED FORM
#define UC_MACRO_NAME_FBA7 0xFBA7 // ﮧ ARABIC LETTER HEH GOAL FINAL FORM
#define UC_MACRO_NAME_FBA8 0xFBA8 // ﮨ ARABIC LETTER HEH GOAL INITIAL FORM
#define UC_MACRO_NAME_FBA9 0xFBA9 // ﮩ ARABIC LETTER HEH GOAL MEDIAL FORM
#define UC_MACRO_NAME_FBAA 0xFBAA // ﮪ ARABIC LETTER HEH DOACHASHMEE ISOLATED FORM
#define UC_MACRO_NAME_FBAB 0xFBAB // ﮫ ARABIC LETTER HEH DOACHASHMEE FINAL FORM
#define UC_MACRO_NAME_FBAC 0xFBAC // ﮬ ARABIC LETTER HEH DOACHASHMEE INITIAL FORM
#define UC_MACRO_NAME_FBAD 0xFBAD // ﮭ ARABIC LETTER HEH DOACHASHMEE MEDIAL FORM
#define UC_MACRO_NAME_FBAE 0xFBAE // ﮮ ARABIC LETTER YEH BARREE ISOLATED FORM
#define UC_MACRO_NAME_FBAF 0xFBAF // ﮯ ARABIC LETTER YEH BARREE FINAL FORM
#define UC_MACRO_NAME_FBB0 0xFBB0 // ﮰ ARABIC LETTER YEH BARREE WITH HAMZA ABOVE ISOLATED FORM
#define UC_MACRO_NAME_FBB1 0xFBB1 // ﮱ ARABIC LETTER YEH BARREE WITH HAMZA ABOVE FINAL FORM
#define UC_MACRO_NAME_FBB2 0xFBB2 // ﮲ ARABIC SYMBOL DOT ABOVE
#define UC_MACRO_NAME_FBB3 0xFBB3 // ﮳ ARABIC SYMBOL DOT BELOW
#define UC_MACRO_NAME_FBB4 0xFBB4 // ﮴ ARABIC SYMBOL TWO DOTS ABOVE
#define UC_MACRO_NAME_FBB5 0xFBB5 // ﮵ ARABIC SYMBOL TWO DOTS BELOW
#define UC_MACRO_NAME_FBB6 0xFBB6 // ﮶ ARABIC SYMBOL THREE DOTS ABOVE
#define UC_MACRO_NAME_FBB7 0xFBB7 // ﮷ ARABIC SYMBOL THREE DOTS BELOW
#define UC_MACRO_NAME_FBB8 0xFBB8 // ﮸ ARABIC SYMBOL THREE DOTS POINTING DOWNWARDS ABOVE
#define UC_MACRO_NAME_FBB9 0xFBB9 // ﮹ ARABIC SYMBOL THREE DOTS POINTING DOWNWARDS BELOW
#define UC_MACRO_NAME_FBBA 0xFBBA // ﮺ ARABIC SYMBOL FOUR DOTS ABOVE
#define UC_MACRO_NAME_FBBB 0xFBBB // ﮻ ARABIC SYMBOL FOUR DOTS BELOW
#define UC_MACRO_NAME_FBBC 0xFBBC // ﮼ ARABIC SYMBOL DOUBLE VERTICAL BAR BELOW
#define UC_MACRO_NAME_FBBD 0xFBBD // ﮽ ARABIC SYMBOL TWO DOTS VERTICALLY ABOVE
#define UC_MACRO_NAME_FBBE 0xFBBE // ﮾ ARABIC SYMBOL TWO DOTS VERTICALLY BELOW
#define UC_MACRO_NAME_FBBF 0xFBBF // ﮿ ARABIC SYMBOL RING
#define UC_MACRO_NAME_FBC0 0xFBC0 // ﯀ ARABIC SYMBOL SMALL TAH ABOVE
#define UC_MACRO_NAME_FBC1 0xFBC1 // ﯁ ARABIC SYMBOL SMALL TAH BELOW
#define UC_MACRO_NAME_FBC2 0xFBC2 // ﯂ ARABIC SYMBOL WASLA ABOVE
#define UC_MACRO_NAME_FBC3 0xFBC3 //  ARABIC LIGATURE JALLA WA-ALAA
#define UC_MACRO_NAME_FBC4 0xFBC4 //  ARABIC LIGATURE DAAMAT BARAKAATUHUM
#define UC_MACRO_NAME_FBC5 0xFBC5 //  ARABIC LIGATURE RAHMATU ALLAAHI TAAALAA ALAYH
#define UC_MACRO_NAME_FBC6 0xFBC6 //  ARABIC LIGATURE RAHMATU ALLAAHI ALAYHIM
#define UC_MACRO_NAME_FBC7 0xFBC7 //  ARABIC LIGATURE RAHMATU ALLAAHI ALAYHIMAA
#define UC_MACRO_NAME_FBC8 0xFBC8 //  ARABIC LIGATURE RAHIMAHUM ALLAAHU TAAALAA
#define UC_MACRO_NAME_FBC9 0xFBC9 //  ARABIC LIGATURE RAHIMAHUMAA ALLAAH
#define UC_MACRO_NAME_FBCA 0xFBCA //  ARABIC LIGATURE RAHIMAHUMAA ALLAAHU TAAALAA
#define UC_MACRO_NAME_FBCB 0xFBCB //  ARABIC LIGATURE RADI ALLAAHU TAAALAA ANHUM
#define UC_MACRO_NAME_FBCC 0xFBCC //  ARABIC LIGATURE HAFIZAHU ALLAAH
#define UC_MACRO_NAME_FBCD 0xFBCD //  ARABIC LIGATURE HAFIZAHU ALLAAHU TAAALAA
#define UC_MACRO_NAME_FBCE 0xFBCE //  ARABIC LIGATURE HAFIZAHUM ALLAAHU TAAALAA
#define UC_MACRO_NAME_FBCF 0xFBCF //  ARABIC LIGATURE HAFIZAHUMAA ALLAAHU TAAALAA
#define UC_MACRO_NAME_FBD0 0xFBD0 //  ARABIC LIGATURE SALLALLAAHU TAAALAA ALAYHI WA-SALLAM
#define UC_MACRO_NAME_FBD1 0xFBD1 //  ARABIC LIGATURE AJJAL ALLAAHU FARAJAHU ASH-SHAREEF
#define UC_MACRO_NAME_FBD2 0xFBD2 //  ARABIC LIGATURE ALAYHI AR-RAHMAH
#define UC_MACRO_NAME_FBD3 0xFBD3 // ﯓ ARABIC LETTER NG ISOLATED FORM
#define UC_MACRO_NAME_FBD4 0xFBD4 // ﯔ ARABIC LETTER NG FINAL FORM
#define UC_MACRO_NAME_FBD5 0xFBD5 // ﯕ ARABIC LETTER NG INITIAL FORM
#define UC_MACRO_NAME_FBD6 0xFBD6 // ﯖ ARABIC LETTER NG MEDIAL FORM
#define UC_MACRO_NAME_FBD7 0xFBD7 // ﯗ ARABIC LETTER U ISOLATED FORM
#define UC_MACRO_NAME_FBD8 0xFBD8 // ﯘ ARABIC LETTER U FINAL FORM
#define UC_MACRO_NAME_FBD9 0xFBD9 // ﯙ ARABIC LETTER OE ISOLATED FORM
#define UC_MACRO_NAME_FBDA 0xFBDA // ﯚ ARABIC LETTER OE FINAL FORM
#define UC_MACRO_NAME_FBDB 0xFBDB // ﯛ ARABIC LETTER YU ISOLATED FORM
#define UC_MACRO_NAME_FBDC 0xFBDC // ﯜ ARABIC LETTER YU FINAL FORM
#define UC_MACRO_NAME_FBDD 0xFBDD // ﯝ ARABIC LETTER U WITH HAMZA ABOVE ISOLATED FORM
#define UC_MACRO_NAME_FBDE 0xFBDE // ﯞ ARABIC LETTER VE ISOLATED FORM
#define UC_MACRO_NAME_FBDF 0xFBDF // ﯟ ARABIC LETTER VE FINAL FORM
#define UC_MACRO_NAME_FBE0 0xFBE0 // ﯠ ARABIC LETTER KIRGHIZ OE ISOLATED FORM
#define UC_MACRO_NAME_FBE1 0xFBE1 // ﯡ ARABIC LETTER KIRGHIZ OE FINAL FORM
#define UC_MACRO_NAME_FBE2 0xFBE2 // ﯢ ARABIC LETTER KIRGHIZ YU ISOLATED FORM
#define UC_MACRO_NAME_FBE3 0xFBE3 // ﯣ ARABIC LETTER KIRGHIZ YU FINAL FORM
#define UC_MACRO_NAME_FBE4 0xFBE4 // ﯤ ARABIC LETTER E ISOLATED FORM
#define UC_MACRO_NAME_FBE5 0xFBE5 // ﯥ ARABIC LETTER E FINAL FORM
#define UC_MACRO_NAME_FBE6 0xFBE6 // ﯦ ARABIC LETTER E INITIAL FORM
#define UC_MACRO_NAME_FBE7 0xFBE7 // ﯧ ARABIC LETTER E MEDIAL FORM
#define UC_MACRO_NAME_FBE8 0xFBE8 // ﯨ ARABIC LETTER UIGHUR KAZAKH KIRGHIZ ALEF MAKSURA INITIAL FORM
#define UC_MACRO_NAME_FBE9 0xFBE9 // ﯩ ARABIC LETTER UIGHUR KAZAKH KIRGHIZ ALEF MAKSURA MEDIAL FORM
#define UC_MACRO_NAME_FBEA 0xFBEA // ﯪ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH ALEF ISOLATED FORM
#define UC_MACRO_NAME_FBEB 0xFBEB // ﯫ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH ALEF FINAL FORM
#define UC_MACRO_NAME_FBEC 0xFBEC // ﯬ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH AE ISOLATED FORM
#define UC_MACRO_NAME_FBED 0xFBED // ﯭ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH AE FINAL FORM
#define UC_MACRO_NAME_FBEE 0xFBEE // ﯮ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH WAW ISOLATED FORM
#define UC_MACRO_NAME_FBEF 0xFBEF // ﯯ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH WAW FINAL FORM
#define UC_MACRO_NAME_FBF0 0xFBF0 // ﯰ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH U ISOLATED FORM
#define UC_MACRO_NAME_FBF1 0xFBF1 // ﯱ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH U FINAL FORM
#define UC_MACRO_NAME_FBF2 0xFBF2 // ﯲ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH OE ISOLATED FORM
#define UC_MACRO_NAME_FBF3 0xFBF3 // ﯳ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH OE FINAL FORM
#define UC_MACRO_NAME_FBF4 0xFBF4 // ﯴ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH YU ISOLATED FORM
#define UC_MACRO_NAME_FBF5 0xFBF5 // ﯵ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH YU FINAL FORM
#define UC_MACRO_NAME_FBF6 0xFBF6 // ﯶ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH E ISOLATED FORM
#define UC_MACRO_NAME_FBF7 0xFBF7 // ﯷ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH E FINAL FORM
#define UC_MACRO_NAME_FBF8 0xFBF8 // ﯸ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH E INITIAL FORM
#define UC_MACRO_NAME_FBF9 0xFBF9 // ﯹ ARABIC LIGATURE UIGHUR KIRGHIZ YEH WITH HAMZA ABOVE WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FBFA 0xFBFA // ﯺ ARABIC LIGATURE UIGHUR KIRGHIZ YEH WITH HAMZA ABOVE WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FBFB 0xFBFB // ﯻ ARABIC LIGATURE UIGHUR KIRGHIZ YEH WITH HAMZA ABOVE WITH ALEF MAKSURA INITIAL FORM
#define UC_MACRO_NAME_FBFC 0xFBFC // ﯼ ARABIC LETTER FARSI YEH ISOLATED FORM
#define UC_MACRO_NAME_FBFD 0xFBFD // ﯽ ARABIC LETTER FARSI YEH FINAL FORM
#define UC_MACRO_NAME_FBFE 0xFBFE // ﯾ ARABIC LETTER FARSI YEH INITIAL FORM
#define UC_MACRO_NAME_FBFF 0xFBFF // ﯿ ARABIC LETTER FARSI YEH MEDIAL FORM
#define UC_MACRO_NAME_FC00 0xFC00 // ﰀ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FC01 0xFC01 // ﰁ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH HAH ISOLATED FORM
#define UC_MACRO_NAME_FC02 0xFC02 // ﰂ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC03 0xFC03 // ﰃ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FC04 0xFC04 // ﰄ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FC05 0xFC05 // ﰅ ARABIC LIGATURE BEH WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FC06 0xFC06 // ﰆ ARABIC LIGATURE BEH WITH HAH ISOLATED FORM
#define UC_MACRO_NAME_FC07 0xFC07 // ﰇ ARABIC LIGATURE BEH WITH KHAH ISOLATED FORM
#define UC_MACRO_NAME_FC08 0xFC08 // ﰈ ARABIC LIGATURE BEH WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC09 0xFC09 // ﰉ ARABIC LIGATURE BEH WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FC0A 0xFC0A // ﰊ ARABIC LIGATURE BEH WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FC0B 0xFC0B // ﰋ ARABIC LIGATURE TEH WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FC0C 0xFC0C // ﰌ ARABIC LIGATURE TEH WITH HAH ISOLATED FORM
#define UC_MACRO_NAME_FC0D 0xFC0D // ﰍ ARABIC LIGATURE TEH WITH KHAH ISOLATED FORM
#define UC_MACRO_NAME_FC0E 0xFC0E // ﰎ ARABIC LIGATURE TEH WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC0F 0xFC0F // ﰏ ARABIC LIGATURE TEH WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FC10 0xFC10 // ﰐ ARABIC LIGATURE TEH WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FC11 0xFC11 // ﰑ ARABIC LIGATURE THEH WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FC12 0xFC12 // ﰒ ARABIC LIGATURE THEH WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC13 0xFC13 // ﰓ ARABIC LIGATURE THEH WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FC14 0xFC14 // ﰔ ARABIC LIGATURE THEH WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FC15 0xFC15 // ﰕ ARABIC LIGATURE JEEM WITH HAH ISOLATED FORM
#define UC_MACRO_NAME_FC16 0xFC16 // ﰖ ARABIC LIGATURE JEEM WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC17 0xFC17 // ﰗ ARABIC LIGATURE HAH WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FC18 0xFC18 // ﰘ ARABIC LIGATURE HAH WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC19 0xFC19 // ﰙ ARABIC LIGATURE KHAH WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FC1A 0xFC1A // ﰚ ARABIC LIGATURE KHAH WITH HAH ISOLATED FORM
#define UC_MACRO_NAME_FC1B 0xFC1B // ﰛ ARABIC LIGATURE KHAH WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC1C 0xFC1C // ﰜ ARABIC LIGATURE SEEN WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FC1D 0xFC1D // ﰝ ARABIC LIGATURE SEEN WITH HAH ISOLATED FORM
#define UC_MACRO_NAME_FC1E 0xFC1E // ﰞ ARABIC LIGATURE SEEN WITH KHAH ISOLATED FORM
#define UC_MACRO_NAME_FC1F 0xFC1F // ﰟ ARABIC LIGATURE SEEN WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC20 0xFC20 // ﰠ ARABIC LIGATURE SAD WITH HAH ISOLATED FORM
#define UC_MACRO_NAME_FC21 0xFC21 // ﰡ ARABIC LIGATURE SAD WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC22 0xFC22 // ﰢ ARABIC LIGATURE DAD WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FC23 0xFC23 // ﰣ ARABIC LIGATURE DAD WITH HAH ISOLATED FORM
#define UC_MACRO_NAME_FC24 0xFC24 // ﰤ ARABIC LIGATURE DAD WITH KHAH ISOLATED FORM
#define UC_MACRO_NAME_FC25 0xFC25 // ﰥ ARABIC LIGATURE DAD WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC26 0xFC26 // ﰦ ARABIC LIGATURE TAH WITH HAH ISOLATED FORM
#define UC_MACRO_NAME_FC27 0xFC27 // ﰧ ARABIC LIGATURE TAH WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC28 0xFC28 // ﰨ ARABIC LIGATURE ZAH WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC29 0xFC29 // ﰩ ARABIC LIGATURE AIN WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FC2A 0xFC2A // ﰪ ARABIC LIGATURE AIN WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC2B 0xFC2B // ﰫ ARABIC LIGATURE GHAIN WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FC2C 0xFC2C // ﰬ ARABIC LIGATURE GHAIN WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC2D 0xFC2D // ﰭ ARABIC LIGATURE FEH WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FC2E 0xFC2E // ﰮ ARABIC LIGATURE FEH WITH HAH ISOLATED FORM
#define UC_MACRO_NAME_FC2F 0xFC2F // ﰯ ARABIC LIGATURE FEH WITH KHAH ISOLATED FORM
#define UC_MACRO_NAME_FC30 0xFC30 // ﰰ ARABIC LIGATURE FEH WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC31 0xFC31 // ﰱ ARABIC LIGATURE FEH WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FC32 0xFC32 // ﰲ ARABIC LIGATURE FEH WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FC33 0xFC33 // ﰳ ARABIC LIGATURE QAF WITH HAH ISOLATED FORM
#define UC_MACRO_NAME_FC34 0xFC34 // ﰴ ARABIC LIGATURE QAF WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC35 0xFC35 // ﰵ ARABIC LIGATURE QAF WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FC36 0xFC36 // ﰶ ARABIC LIGATURE QAF WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FC37 0xFC37 // ﰷ ARABIC LIGATURE KAF WITH ALEF ISOLATED FORM
#define UC_MACRO_NAME_FC38 0xFC38 // ﰸ ARABIC LIGATURE KAF WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FC39 0xFC39 // ﰹ ARABIC LIGATURE KAF WITH HAH ISOLATED FORM
#define UC_MACRO_NAME_FC3A 0xFC3A // ﰺ ARABIC LIGATURE KAF WITH KHAH ISOLATED FORM
#define UC_MACRO_NAME_FC3B 0xFC3B // ﰻ ARABIC LIGATURE KAF WITH LAM ISOLATED FORM
#define UC_MACRO_NAME_FC3C 0xFC3C // ﰼ ARABIC LIGATURE KAF WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC3D 0xFC3D // ﰽ ARABIC LIGATURE KAF WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FC3E 0xFC3E // ﰾ ARABIC LIGATURE KAF WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FC3F 0xFC3F // ﰿ ARABIC LIGATURE LAM WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FC40 0xFC40 // ﱀ ARABIC LIGATURE LAM WITH HAH ISOLATED FORM
#define UC_MACRO_NAME_FC41 0xFC41 // ﱁ ARABIC LIGATURE LAM WITH KHAH ISOLATED FORM
#define UC_MACRO_NAME_FC42 0xFC42 // ﱂ ARABIC LIGATURE LAM WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC43 0xFC43 // ﱃ ARABIC LIGATURE LAM WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FC44 0xFC44 // ﱄ ARABIC LIGATURE LAM WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FC45 0xFC45 // ﱅ ARABIC LIGATURE MEEM WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FC46 0xFC46 // ﱆ ARABIC LIGATURE MEEM WITH HAH ISOLATED FORM
#define UC_MACRO_NAME_FC47 0xFC47 // ﱇ ARABIC LIGATURE MEEM WITH KHAH ISOLATED FORM
#define UC_MACRO_NAME_FC48 0xFC48 // ﱈ ARABIC LIGATURE MEEM WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC49 0xFC49 // ﱉ ARABIC LIGATURE MEEM WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FC4A 0xFC4A // ﱊ ARABIC LIGATURE MEEM WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FC4B 0xFC4B // ﱋ ARABIC LIGATURE NOON WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FC4C 0xFC4C // ﱌ ARABIC LIGATURE NOON WITH HAH ISOLATED FORM
#define UC_MACRO_NAME_FC4D 0xFC4D // ﱍ ARABIC LIGATURE NOON WITH KHAH ISOLATED FORM
#define UC_MACRO_NAME_FC4E 0xFC4E // ﱎ ARABIC LIGATURE NOON WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC4F 0xFC4F // ﱏ ARABIC LIGATURE NOON WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FC50 0xFC50 // ﱐ ARABIC LIGATURE NOON WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FC51 0xFC51 // ﱑ ARABIC LIGATURE HEH WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FC52 0xFC52 // ﱒ ARABIC LIGATURE HEH WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC53 0xFC53 // ﱓ ARABIC LIGATURE HEH WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FC54 0xFC54 // ﱔ ARABIC LIGATURE HEH WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FC55 0xFC55 // ﱕ ARABIC LIGATURE YEH WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FC56 0xFC56 // ﱖ ARABIC LIGATURE YEH WITH HAH ISOLATED FORM
#define UC_MACRO_NAME_FC57 0xFC57 // ﱗ ARABIC LIGATURE YEH WITH KHAH ISOLATED FORM
#define UC_MACRO_NAME_FC58 0xFC58 // ﱘ ARABIC LIGATURE YEH WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FC59 0xFC59 // ﱙ ARABIC LIGATURE YEH WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FC5A 0xFC5A // ﱚ ARABIC LIGATURE YEH WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FC5B 0xFC5B // ﱛ ARABIC LIGATURE THAL WITH SUPERSCRIPT ALEF ISOLATED FORM
#define UC_MACRO_NAME_FC5C 0xFC5C // ﱜ ARABIC LIGATURE REH WITH SUPERSCRIPT ALEF ISOLATED FORM
#define UC_MACRO_NAME_FC5D 0xFC5D // ﱝ ARABIC LIGATURE ALEF MAKSURA WITH SUPERSCRIPT ALEF ISOLATED FORM
#define UC_MACRO_NAME_FC5E 0xFC5E // ﱞ ARABIC LIGATURE SHADDA WITH DAMMATAN ISOLATED FORM
#define UC_MACRO_NAME_FC5F 0xFC5F // ﱟ ARABIC LIGATURE SHADDA WITH KASRATAN ISOLATED FORM
#define UC_MACRO_NAME_FC60 0xFC60 // ﱠ ARABIC LIGATURE SHADDA WITH FATHA ISOLATED FORM
#define UC_MACRO_NAME_FC61 0xFC61 // ﱡ ARABIC LIGATURE SHADDA WITH DAMMA ISOLATED FORM
#define UC_MACRO_NAME_FC62 0xFC62 // ﱢ ARABIC LIGATURE SHADDA WITH KASRA ISOLATED FORM
#define UC_MACRO_NAME_FC63 0xFC63 // ﱣ ARABIC LIGATURE SHADDA WITH SUPERSCRIPT ALEF ISOLATED FORM
#define UC_MACRO_NAME_FC64 0xFC64 // ﱤ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH REH FINAL FORM
#define UC_MACRO_NAME_FC65 0xFC65 // ﱥ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH ZAIN FINAL FORM
#define UC_MACRO_NAME_FC66 0xFC66 // ﱦ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FC67 0xFC67 // ﱧ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH NOON FINAL FORM
#define UC_MACRO_NAME_FC68 0xFC68 // ﱨ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FC69 0xFC69 // ﱩ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH YEH FINAL FORM
#define UC_MACRO_NAME_FC6A 0xFC6A // ﱪ ARABIC LIGATURE BEH WITH REH FINAL FORM
#define UC_MACRO_NAME_FC6B 0xFC6B // ﱫ ARABIC LIGATURE BEH WITH ZAIN FINAL FORM
#define UC_MACRO_NAME_FC6C 0xFC6C // ﱬ ARABIC LIGATURE BEH WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FC6D 0xFC6D // ﱭ ARABIC LIGATURE BEH WITH NOON FINAL FORM
#define UC_MACRO_NAME_FC6E 0xFC6E // ﱮ ARABIC LIGATURE BEH WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FC6F 0xFC6F // ﱯ ARABIC LIGATURE BEH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FC70 0xFC70 // ﱰ ARABIC LIGATURE TEH WITH REH FINAL FORM
#define UC_MACRO_NAME_FC71 0xFC71 // ﱱ ARABIC LIGATURE TEH WITH ZAIN FINAL FORM
#define UC_MACRO_NAME_FC72 0xFC72 // ﱲ ARABIC LIGATURE TEH WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FC73 0xFC73 // ﱳ ARABIC LIGATURE TEH WITH NOON FINAL FORM
#define UC_MACRO_NAME_FC74 0xFC74 // ﱴ ARABIC LIGATURE TEH WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FC75 0xFC75 // ﱵ ARABIC LIGATURE TEH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FC76 0xFC76 // ﱶ ARABIC LIGATURE THEH WITH REH FINAL FORM
#define UC_MACRO_NAME_FC77 0xFC77 // ﱷ ARABIC LIGATURE THEH WITH ZAIN FINAL FORM
#define UC_MACRO_NAME_FC78 0xFC78 // ﱸ ARABIC LIGATURE THEH WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FC79 0xFC79 // ﱹ ARABIC LIGATURE THEH WITH NOON FINAL FORM
#define UC_MACRO_NAME_FC7A 0xFC7A // ﱺ ARABIC LIGATURE THEH WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FC7B 0xFC7B // ﱻ ARABIC LIGATURE THEH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FC7C 0xFC7C // ﱼ ARABIC LIGATURE FEH WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FC7D 0xFC7D // ﱽ ARABIC LIGATURE FEH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FC7E 0xFC7E // ﱾ ARABIC LIGATURE QAF WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FC7F 0xFC7F // ﱿ ARABIC LIGATURE QAF WITH YEH FINAL FORM
#define UC_MACRO_NAME_FC80 0xFC80 // ﲀ ARABIC LIGATURE KAF WITH ALEF FINAL FORM
#define UC_MACRO_NAME_FC81 0xFC81 // ﲁ ARABIC LIGATURE KAF WITH LAM FINAL FORM
#define UC_MACRO_NAME_FC82 0xFC82 // ﲂ ARABIC LIGATURE KAF WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FC83 0xFC83 // ﲃ ARABIC LIGATURE KAF WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FC84 0xFC84 // ﲄ ARABIC LIGATURE KAF WITH YEH FINAL FORM
#define UC_MACRO_NAME_FC85 0xFC85 // ﲅ ARABIC LIGATURE LAM WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FC86 0xFC86 // ﲆ ARABIC LIGATURE LAM WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FC87 0xFC87 // ﲇ ARABIC LIGATURE LAM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FC88 0xFC88 // ﲈ ARABIC LIGATURE MEEM WITH ALEF FINAL FORM
#define UC_MACRO_NAME_FC89 0xFC89 // ﲉ ARABIC LIGATURE MEEM WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FC8A 0xFC8A // ﲊ ARABIC LIGATURE NOON WITH REH FINAL FORM
#define UC_MACRO_NAME_FC8B 0xFC8B // ﲋ ARABIC LIGATURE NOON WITH ZAIN FINAL FORM
#define UC_MACRO_NAME_FC8C 0xFC8C // ﲌ ARABIC LIGATURE NOON WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FC8D 0xFC8D // ﲍ ARABIC LIGATURE NOON WITH NOON FINAL FORM
#define UC_MACRO_NAME_FC8E 0xFC8E // ﲎ ARABIC LIGATURE NOON WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FC8F 0xFC8F // ﲏ ARABIC LIGATURE NOON WITH YEH FINAL FORM
#define UC_MACRO_NAME_FC90 0xFC90 // ﲐ ARABIC LIGATURE ALEF MAKSURA WITH SUPERSCRIPT ALEF FINAL FORM
#define UC_MACRO_NAME_FC91 0xFC91 // ﲑ ARABIC LIGATURE YEH WITH REH FINAL FORM
#define UC_MACRO_NAME_FC92 0xFC92 // ﲒ ARABIC LIGATURE YEH WITH ZAIN FINAL FORM
#define UC_MACRO_NAME_FC93 0xFC93 // ﲓ ARABIC LIGATURE YEH WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FC94 0xFC94 // ﲔ ARABIC LIGATURE YEH WITH NOON FINAL FORM
#define UC_MACRO_NAME_FC95 0xFC95 // ﲕ ARABIC LIGATURE YEH WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FC96 0xFC96 // ﲖ ARABIC LIGATURE YEH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FC97 0xFC97 // ﲗ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FC98 0xFC98 // ﲘ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FC99 0xFC99 // ﲙ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH KHAH INITIAL FORM
#define UC_MACRO_NAME_FC9A 0xFC9A // ﲚ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FC9B 0xFC9B // ﲛ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH HEH INITIAL FORM
#define UC_MACRO_NAME_FC9C 0xFC9C // ﲜ ARABIC LIGATURE BEH WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FC9D 0xFC9D // ﲝ ARABIC LIGATURE BEH WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FC9E 0xFC9E // ﲞ ARABIC LIGATURE BEH WITH KHAH INITIAL FORM
#define UC_MACRO_NAME_FC9F 0xFC9F // ﲟ ARABIC LIGATURE BEH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCA0 0xFCA0 // ﲠ ARABIC LIGATURE BEH WITH HEH INITIAL FORM
#define UC_MACRO_NAME_FCA1 0xFCA1 // ﲡ ARABIC LIGATURE TEH WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FCA2 0xFCA2 // ﲢ ARABIC LIGATURE TEH WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FCA3 0xFCA3 // ﲣ ARABIC LIGATURE TEH WITH KHAH INITIAL FORM
#define UC_MACRO_NAME_FCA4 0xFCA4 // ﲤ ARABIC LIGATURE TEH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCA5 0xFCA5 // ﲥ ARABIC LIGATURE TEH WITH HEH INITIAL FORM
#define UC_MACRO_NAME_FCA6 0xFCA6 // ﲦ ARABIC LIGATURE THEH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCA7 0xFCA7 // ﲧ ARABIC LIGATURE JEEM WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FCA8 0xFCA8 // ﲨ ARABIC LIGATURE JEEM WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCA9 0xFCA9 // ﲩ ARABIC LIGATURE HAH WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FCAA 0xFCAA // ﲪ ARABIC LIGATURE HAH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCAB 0xFCAB // ﲫ ARABIC LIGATURE KHAH WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FCAC 0xFCAC // ﲬ ARABIC LIGATURE KHAH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCAD 0xFCAD // ﲭ ARABIC LIGATURE SEEN WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FCAE 0xFCAE // ﲮ ARABIC LIGATURE SEEN WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FCAF 0xFCAF // ﲯ ARABIC LIGATURE SEEN WITH KHAH INITIAL FORM
#define UC_MACRO_NAME_FCB0 0xFCB0 // ﲰ ARABIC LIGATURE SEEN WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCB1 0xFCB1 // ﲱ ARABIC LIGATURE SAD WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FCB2 0xFCB2 // ﲲ ARABIC LIGATURE SAD WITH KHAH INITIAL FORM
#define UC_MACRO_NAME_FCB3 0xFCB3 // ﲳ ARABIC LIGATURE SAD WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCB4 0xFCB4 // ﲴ ARABIC LIGATURE DAD WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FCB5 0xFCB5 // ﲵ ARABIC LIGATURE DAD WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FCB6 0xFCB6 // ﲶ ARABIC LIGATURE DAD WITH KHAH INITIAL FORM
#define UC_MACRO_NAME_FCB7 0xFCB7 // ﲷ ARABIC LIGATURE DAD WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCB8 0xFCB8 // ﲸ ARABIC LIGATURE TAH WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FCB9 0xFCB9 // ﲹ ARABIC LIGATURE ZAH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCBA 0xFCBA // ﲺ ARABIC LIGATURE AIN WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FCBB 0xFCBB // ﲻ ARABIC LIGATURE AIN WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCBC 0xFCBC // ﲼ ARABIC LIGATURE GHAIN WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FCBD 0xFCBD // ﲽ ARABIC LIGATURE GHAIN WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCBE 0xFCBE // ﲾ ARABIC LIGATURE FEH WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FCBF 0xFCBF // ﲿ ARABIC LIGATURE FEH WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FCC0 0xFCC0 // ﳀ ARABIC LIGATURE FEH WITH KHAH INITIAL FORM
#define UC_MACRO_NAME_FCC1 0xFCC1 // ﳁ ARABIC LIGATURE FEH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCC2 0xFCC2 // ﳂ ARABIC LIGATURE QAF WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FCC3 0xFCC3 // ﳃ ARABIC LIGATURE QAF WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCC4 0xFCC4 // ﳄ ARABIC LIGATURE KAF WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FCC5 0xFCC5 // ﳅ ARABIC LIGATURE KAF WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FCC6 0xFCC6 // ﳆ ARABIC LIGATURE KAF WITH KHAH INITIAL FORM
#define UC_MACRO_NAME_FCC7 0xFCC7 // ﳇ ARABIC LIGATURE KAF WITH LAM INITIAL FORM
#define UC_MACRO_NAME_FCC8 0xFCC8 // ﳈ ARABIC LIGATURE KAF WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCC9 0xFCC9 // ﳉ ARABIC LIGATURE LAM WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FCCA 0xFCCA // ﳊ ARABIC LIGATURE LAM WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FCCB 0xFCCB // ﳋ ARABIC LIGATURE LAM WITH KHAH INITIAL FORM
#define UC_MACRO_NAME_FCCC 0xFCCC // ﳌ ARABIC LIGATURE LAM WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCCD 0xFCCD // ﳍ ARABIC LIGATURE LAM WITH HEH INITIAL FORM
#define UC_MACRO_NAME_FCCE 0xFCCE // ﳎ ARABIC LIGATURE MEEM WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FCCF 0xFCCF // ﳏ ARABIC LIGATURE MEEM WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FCD0 0xFCD0 // ﳐ ARABIC LIGATURE MEEM WITH KHAH INITIAL FORM
#define UC_MACRO_NAME_FCD1 0xFCD1 // ﳑ ARABIC LIGATURE MEEM WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCD2 0xFCD2 // ﳒ ARABIC LIGATURE NOON WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FCD3 0xFCD3 // ﳓ ARABIC LIGATURE NOON WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FCD4 0xFCD4 // ﳔ ARABIC LIGATURE NOON WITH KHAH INITIAL FORM
#define UC_MACRO_NAME_FCD5 0xFCD5 // ﳕ ARABIC LIGATURE NOON WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCD6 0xFCD6 // ﳖ ARABIC LIGATURE NOON WITH HEH INITIAL FORM
#define UC_MACRO_NAME_FCD7 0xFCD7 // ﳗ ARABIC LIGATURE HEH WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FCD8 0xFCD8 // ﳘ ARABIC LIGATURE HEH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCD9 0xFCD9 // ﳙ ARABIC LIGATURE HEH WITH SUPERSCRIPT ALEF INITIAL FORM
#define UC_MACRO_NAME_FCDA 0xFCDA // ﳚ ARABIC LIGATURE YEH WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FCDB 0xFCDB // ﳛ ARABIC LIGATURE YEH WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FCDC 0xFCDC // ﳜ ARABIC LIGATURE YEH WITH KHAH INITIAL FORM
#define UC_MACRO_NAME_FCDD 0xFCDD // ﳝ ARABIC LIGATURE YEH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FCDE 0xFCDE // ﳞ ARABIC LIGATURE YEH WITH HEH INITIAL FORM
#define UC_MACRO_NAME_FCDF 0xFCDF // ﳟ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH MEEM MEDIAL FORM
#define UC_MACRO_NAME_FCE0 0xFCE0 // ﳠ ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH HEH MEDIAL FORM
#define UC_MACRO_NAME_FCE1 0xFCE1 // ﳡ ARABIC LIGATURE BEH WITH MEEM MEDIAL FORM
#define UC_MACRO_NAME_FCE2 0xFCE2 // ﳢ ARABIC LIGATURE BEH WITH HEH MEDIAL FORM
#define UC_MACRO_NAME_FCE3 0xFCE3 // ﳣ ARABIC LIGATURE TEH WITH MEEM MEDIAL FORM
#define UC_MACRO_NAME_FCE4 0xFCE4 // ﳤ ARABIC LIGATURE TEH WITH HEH MEDIAL FORM
#define UC_MACRO_NAME_FCE5 0xFCE5 // ﳥ ARABIC LIGATURE THEH WITH MEEM MEDIAL FORM
#define UC_MACRO_NAME_FCE6 0xFCE6 // ﳦ ARABIC LIGATURE THEH WITH HEH MEDIAL FORM
#define UC_MACRO_NAME_FCE7 0xFCE7 // ﳧ ARABIC LIGATURE SEEN WITH MEEM MEDIAL FORM
#define UC_MACRO_NAME_FCE8 0xFCE8 // ﳨ ARABIC LIGATURE SEEN WITH HEH MEDIAL FORM
#define UC_MACRO_NAME_FCE9 0xFCE9 // ﳩ ARABIC LIGATURE SHEEN WITH MEEM MEDIAL FORM
#define UC_MACRO_NAME_FCEA 0xFCEA // ﳪ ARABIC LIGATURE SHEEN WITH HEH MEDIAL FORM
#define UC_MACRO_NAME_FCEB 0xFCEB // ﳫ ARABIC LIGATURE KAF WITH LAM MEDIAL FORM
#define UC_MACRO_NAME_FCEC 0xFCEC // ﳬ ARABIC LIGATURE KAF WITH MEEM MEDIAL FORM
#define UC_MACRO_NAME_FCED 0xFCED // ﳭ ARABIC LIGATURE LAM WITH MEEM MEDIAL FORM
#define UC_MACRO_NAME_FCEE 0xFCEE // ﳮ ARABIC LIGATURE NOON WITH MEEM MEDIAL FORM
#define UC_MACRO_NAME_FCEF 0xFCEF // ﳯ ARABIC LIGATURE NOON WITH HEH MEDIAL FORM
#define UC_MACRO_NAME_FCF0 0xFCF0 // ﳰ ARABIC LIGATURE YEH WITH MEEM MEDIAL FORM
#define UC_MACRO_NAME_FCF1 0xFCF1 // ﳱ ARABIC LIGATURE YEH WITH HEH MEDIAL FORM
#define UC_MACRO_NAME_FCF2 0xFCF2 // ﳲ ARABIC LIGATURE SHADDA WITH FATHA MEDIAL FORM
#define UC_MACRO_NAME_FCF3 0xFCF3 // ﳳ ARABIC LIGATURE SHADDA WITH DAMMA MEDIAL FORM
#define UC_MACRO_NAME_FCF4 0xFCF4 // ﳴ ARABIC LIGATURE SHADDA WITH KASRA MEDIAL FORM
#define UC_MACRO_NAME_FCF5 0xFCF5 // ﳵ ARABIC LIGATURE TAH WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FCF6 0xFCF6 // ﳶ ARABIC LIGATURE TAH WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FCF7 0xFCF7 // ﳷ ARABIC LIGATURE AIN WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FCF8 0xFCF8 // ﳸ ARABIC LIGATURE AIN WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FCF9 0xFCF9 // ﳹ ARABIC LIGATURE GHAIN WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FCFA 0xFCFA // ﳺ ARABIC LIGATURE GHAIN WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FCFB 0xFCFB // ﳻ ARABIC LIGATURE SEEN WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FCFC 0xFCFC // ﳼ ARABIC LIGATURE SEEN WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FCFD 0xFCFD // ﳽ ARABIC LIGATURE SHEEN WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FCFE 0xFCFE // ﳾ ARABIC LIGATURE SHEEN WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FCFF 0xFCFF // ﳿ ARABIC LIGATURE HAH WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FD00 0xFD00 // ﴀ ARABIC LIGATURE HAH WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FD01 0xFD01 // ﴁ ARABIC LIGATURE JEEM WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FD02 0xFD02 // ﴂ ARABIC LIGATURE JEEM WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FD03 0xFD03 // ﴃ ARABIC LIGATURE KHAH WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FD04 0xFD04 // ﴄ ARABIC LIGATURE KHAH WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FD05 0xFD05 // ﴅ ARABIC LIGATURE SAD WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FD06 0xFD06 // ﴆ ARABIC LIGATURE SAD WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FD07 0xFD07 // ﴇ ARABIC LIGATURE DAD WITH ALEF MAKSURA ISOLATED FORM
#define UC_MACRO_NAME_FD08 0xFD08 // ﴈ ARABIC LIGATURE DAD WITH YEH ISOLATED FORM
#define UC_MACRO_NAME_FD09 0xFD09 // ﴉ ARABIC LIGATURE SHEEN WITH JEEM ISOLATED FORM
#define UC_MACRO_NAME_FD0A 0xFD0A // ﴊ ARABIC LIGATURE SHEEN WITH HAH ISOLATED FORM
#define UC_MACRO_NAME_FD0B 0xFD0B // ﴋ ARABIC LIGATURE SHEEN WITH KHAH ISOLATED FORM
#define UC_MACRO_NAME_FD0C 0xFD0C // ﴌ ARABIC LIGATURE SHEEN WITH MEEM ISOLATED FORM
#define UC_MACRO_NAME_FD0D 0xFD0D // ﴍ ARABIC LIGATURE SHEEN WITH REH ISOLATED FORM
#define UC_MACRO_NAME_FD0E 0xFD0E // ﴎ ARABIC LIGATURE SEEN WITH REH ISOLATED FORM
#define UC_MACRO_NAME_FD0F 0xFD0F // ﴏ ARABIC LIGATURE SAD WITH REH ISOLATED FORM
#define UC_MACRO_NAME_FD10 0xFD10 // ﴐ ARABIC LIGATURE DAD WITH REH ISOLATED FORM
#define UC_MACRO_NAME_FD11 0xFD11 // ﴑ ARABIC LIGATURE TAH WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD12 0xFD12 // ﴒ ARABIC LIGATURE TAH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD13 0xFD13 // ﴓ ARABIC LIGATURE AIN WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD14 0xFD14 // ﴔ ARABIC LIGATURE AIN WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD15 0xFD15 // ﴕ ARABIC LIGATURE GHAIN WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD16 0xFD16 // ﴖ ARABIC LIGATURE GHAIN WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD17 0xFD17 // ﴗ ARABIC LIGATURE SEEN WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD18 0xFD18 // ﴘ ARABIC LIGATURE SEEN WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD19 0xFD19 // ﴙ ARABIC LIGATURE SHEEN WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD1A 0xFD1A // ﴚ ARABIC LIGATURE SHEEN WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD1B 0xFD1B // ﴛ ARABIC LIGATURE HAH WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD1C 0xFD1C // ﴜ ARABIC LIGATURE HAH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD1D 0xFD1D // ﴝ ARABIC LIGATURE JEEM WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD1E 0xFD1E // ﴞ ARABIC LIGATURE JEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD1F 0xFD1F // ﴟ ARABIC LIGATURE KHAH WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD20 0xFD20 // ﴠ ARABIC LIGATURE KHAH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD21 0xFD21 // ﴡ ARABIC LIGATURE SAD WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD22 0xFD22 // ﴢ ARABIC LIGATURE SAD WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD23 0xFD23 // ﴣ ARABIC LIGATURE DAD WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD24 0xFD24 // ﴤ ARABIC LIGATURE DAD WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD25 0xFD25 // ﴥ ARABIC LIGATURE SHEEN WITH JEEM FINAL FORM
#define UC_MACRO_NAME_FD26 0xFD26 // ﴦ ARABIC LIGATURE SHEEN WITH HAH FINAL FORM
#define UC_MACRO_NAME_FD27 0xFD27 // ﴧ ARABIC LIGATURE SHEEN WITH KHAH FINAL FORM
#define UC_MACRO_NAME_FD28 0xFD28 // ﴨ ARABIC LIGATURE SHEEN WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FD29 0xFD29 // ﴩ ARABIC LIGATURE SHEEN WITH REH FINAL FORM
#define UC_MACRO_NAME_FD2A 0xFD2A // ﴪ ARABIC LIGATURE SEEN WITH REH FINAL FORM
#define UC_MACRO_NAME_FD2B 0xFD2B // ﴫ ARABIC LIGATURE SAD WITH REH FINAL FORM
#define UC_MACRO_NAME_FD2C 0xFD2C // ﴬ ARABIC LIGATURE DAD WITH REH FINAL FORM
#define UC_MACRO_NAME_FD2D 0xFD2D // ﴭ ARABIC LIGATURE SHEEN WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FD2E 0xFD2E // ﴮ ARABIC LIGATURE SHEEN WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FD2F 0xFD2F // ﴯ ARABIC LIGATURE SHEEN WITH KHAH INITIAL FORM
#define UC_MACRO_NAME_FD30 0xFD30 // ﴰ ARABIC LIGATURE SHEEN WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD31 0xFD31 // ﴱ ARABIC LIGATURE SEEN WITH HEH INITIAL FORM
#define UC_MACRO_NAME_FD32 0xFD32 // ﴲ ARABIC LIGATURE SHEEN WITH HEH INITIAL FORM
#define UC_MACRO_NAME_FD33 0xFD33 // ﴳ ARABIC LIGATURE TAH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD34 0xFD34 // ﴴ ARABIC LIGATURE SEEN WITH JEEM MEDIAL FORM
#define UC_MACRO_NAME_FD35 0xFD35 // ﴵ ARABIC LIGATURE SEEN WITH HAH MEDIAL FORM
#define UC_MACRO_NAME_FD36 0xFD36 // ﴶ ARABIC LIGATURE SEEN WITH KHAH MEDIAL FORM
#define UC_MACRO_NAME_FD37 0xFD37 // ﴷ ARABIC LIGATURE SHEEN WITH JEEM MEDIAL FORM
#define UC_MACRO_NAME_FD38 0xFD38 // ﴸ ARABIC LIGATURE SHEEN WITH HAH MEDIAL FORM
#define UC_MACRO_NAME_FD39 0xFD39 // ﴹ ARABIC LIGATURE SHEEN WITH KHAH MEDIAL FORM
#define UC_MACRO_NAME_FD3A 0xFD3A // ﴺ ARABIC LIGATURE TAH WITH MEEM MEDIAL FORM
#define UC_MACRO_NAME_FD3B 0xFD3B // ﴻ ARABIC LIGATURE ZAH WITH MEEM MEDIAL FORM
#define UC_MACRO_NAME_FD3C 0xFD3C // ﴼ ARABIC LIGATURE ALEF WITH FATHATAN FINAL FORM
#define UC_MACRO_NAME_FD3D 0xFD3D // ﴽ ARABIC LIGATURE ALEF WITH FATHATAN ISOLATED FORM
#define UC_MACRO_NAME_FD3E 0xFD3E // ﴾ ORNATE LEFT PARENTHESIS
#define UC_MACRO_NAME_FD3F 0xFD3F // ﴿ ORNATE RIGHT PARENTHESIS
#define UC_MACRO_NAME_FD40 0xFD40 // ﵀ ARABIC LIGATURE RAHIMAHU ALLAAH
#define UC_MACRO_NAME_FD41 0xFD41 // ﵁ ARABIC LIGATURE RADI ALLAAHU ANH
#define UC_MACRO_NAME_FD42 0xFD42 // ﵂ ARABIC LIGATURE RADI ALLAAHU ANHAA
#define UC_MACRO_NAME_FD43 0xFD43 // ﵃ ARABIC LIGATURE RADI ALLAAHU ANHUM
#define UC_MACRO_NAME_FD44 0xFD44 // ﵄ ARABIC LIGATURE RADI ALLAAHU ANHUMAA
#define UC_MACRO_NAME_FD45 0xFD45 // ﵅ ARABIC LIGATURE RADI ALLAAHU ANHUNNA
#define UC_MACRO_NAME_FD46 0xFD46 // ﵆ ARABIC LIGATURE SALLALLAAHU ALAYHI WA-AALIH
#define UC_MACRO_NAME_FD47 0xFD47 // ﵇ ARABIC LIGATURE ALAYHI AS-SALAAM
#define UC_MACRO_NAME_FD48 0xFD48 // ﵈ ARABIC LIGATURE ALAYHIM AS-SALAAM
#define UC_MACRO_NAME_FD49 0xFD49 // ﵉ ARABIC LIGATURE ALAYHIMAA AS-SALAAM
#define UC_MACRO_NAME_FD4A 0xFD4A // ﵊ ARABIC LIGATURE ALAYHI AS-SALAATU WAS-SALAAM
#define UC_MACRO_NAME_FD4B 0xFD4B // ﵋ ARABIC LIGATURE QUDDISA SIRRAH
#define UC_MACRO_NAME_FD4C 0xFD4C // ﵌ ARABIC LIGATURE SALLALLAHU ALAYHI WAAALIHEE WA-SALLAM
#define UC_MACRO_NAME_FD4D 0xFD4D // ﵍ ARABIC LIGATURE ALAYHAA AS-SALAAM
#define UC_MACRO_NAME_FD4E 0xFD4E // ﵎ ARABIC LIGATURE TABAARAKA WA-TAAALAA
#define UC_MACRO_NAME_FD4F 0xFD4F // ﵏ ARABIC LIGATURE RAHIMAHUM ALLAAH
#define UC_MACRO_NAME_FD50 0xFD50 // ﵐ ARABIC LIGATURE TEH WITH JEEM WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD51 0xFD51 // ﵑ ARABIC LIGATURE TEH WITH HAH WITH JEEM FINAL FORM
#define UC_MACRO_NAME_FD52 0xFD52 // ﵒ ARABIC LIGATURE TEH WITH HAH WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FD53 0xFD53 // ﵓ ARABIC LIGATURE TEH WITH HAH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD54 0xFD54 // ﵔ ARABIC LIGATURE TEH WITH KHAH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD55 0xFD55 // ﵕ ARABIC LIGATURE TEH WITH MEEM WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FD56 0xFD56 // ﵖ ARABIC LIGATURE TEH WITH MEEM WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FD57 0xFD57 // ﵗ ARABIC LIGATURE TEH WITH MEEM WITH KHAH INITIAL FORM
#define UC_MACRO_NAME_FD58 0xFD58 // ﵘ ARABIC LIGATURE JEEM WITH MEEM WITH HAH FINAL FORM
#define UC_MACRO_NAME_FD59 0xFD59 // ﵙ ARABIC LIGATURE JEEM WITH MEEM WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FD5A 0xFD5A // ﵚ ARABIC LIGATURE HAH WITH MEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD5B 0xFD5B // ﵛ ARABIC LIGATURE HAH WITH MEEM WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD5C 0xFD5C // ﵜ ARABIC LIGATURE SEEN WITH HAH WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FD5D 0xFD5D // ﵝ ARABIC LIGATURE SEEN WITH JEEM WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FD5E 0xFD5E // ﵞ ARABIC LIGATURE SEEN WITH JEEM WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD5F 0xFD5F // ﵟ ARABIC LIGATURE SEEN WITH MEEM WITH HAH FINAL FORM
#define UC_MACRO_NAME_FD60 0xFD60 // ﵠ ARABIC LIGATURE SEEN WITH MEEM WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FD61 0xFD61 // ﵡ ARABIC LIGATURE SEEN WITH MEEM WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FD62 0xFD62 // ﵢ ARABIC LIGATURE SEEN WITH MEEM WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FD63 0xFD63 // ﵣ ARABIC LIGATURE SEEN WITH MEEM WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD64 0xFD64 // ﵤ ARABIC LIGATURE SAD WITH HAH WITH HAH FINAL FORM
#define UC_MACRO_NAME_FD65 0xFD65 // ﵥ ARABIC LIGATURE SAD WITH HAH WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FD66 0xFD66 // ﵦ ARABIC LIGATURE SAD WITH MEEM WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FD67 0xFD67 // ﵧ ARABIC LIGATURE SHEEN WITH HAH WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FD68 0xFD68 // ﵨ ARABIC LIGATURE SHEEN WITH HAH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD69 0xFD69 // ﵩ ARABIC LIGATURE SHEEN WITH JEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD6A 0xFD6A // ﵪ ARABIC LIGATURE SHEEN WITH MEEM WITH KHAH FINAL FORM
#define UC_MACRO_NAME_FD6B 0xFD6B // ﵫ ARABIC LIGATURE SHEEN WITH MEEM WITH KHAH INITIAL FORM
#define UC_MACRO_NAME_FD6C 0xFD6C // ﵬ ARABIC LIGATURE SHEEN WITH MEEM WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FD6D 0xFD6D // ﵭ ARABIC LIGATURE SHEEN WITH MEEM WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD6E 0xFD6E // ﵮ ARABIC LIGATURE DAD WITH HAH WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD6F 0xFD6F // ﵯ ARABIC LIGATURE DAD WITH KHAH WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FD70 0xFD70 // ﵰ ARABIC LIGATURE DAD WITH KHAH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD71 0xFD71 // ﵱ ARABIC LIGATURE TAH WITH MEEM WITH HAH FINAL FORM
#define UC_MACRO_NAME_FD72 0xFD72 // ﵲ ARABIC LIGATURE TAH WITH MEEM WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FD73 0xFD73 // ﵳ ARABIC LIGATURE TAH WITH MEEM WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD74 0xFD74 // ﵴ ARABIC LIGATURE TAH WITH MEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD75 0xFD75 // ﵵ ARABIC LIGATURE AIN WITH JEEM WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FD76 0xFD76 // ﵶ ARABIC LIGATURE AIN WITH MEEM WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FD77 0xFD77 // ﵷ ARABIC LIGATURE AIN WITH MEEM WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD78 0xFD78 // ﵸ ARABIC LIGATURE AIN WITH MEEM WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD79 0xFD79 // ﵹ ARABIC LIGATURE GHAIN WITH MEEM WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FD7A 0xFD7A // ﵺ ARABIC LIGATURE GHAIN WITH MEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD7B 0xFD7B // ﵻ ARABIC LIGATURE GHAIN WITH MEEM WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD7C 0xFD7C // ﵼ ARABIC LIGATURE FEH WITH KHAH WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FD7D 0xFD7D // ﵽ ARABIC LIGATURE FEH WITH KHAH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD7E 0xFD7E // ﵾ ARABIC LIGATURE QAF WITH MEEM WITH HAH FINAL FORM
#define UC_MACRO_NAME_FD7F 0xFD7F // ﵿ ARABIC LIGATURE QAF WITH MEEM WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FD80 0xFD80 // ﶀ ARABIC LIGATURE LAM WITH HAH WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FD81 0xFD81 // ﶁ ARABIC LIGATURE LAM WITH HAH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD82 0xFD82 // ﶂ ARABIC LIGATURE LAM WITH HAH WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD83 0xFD83 // ﶃ ARABIC LIGATURE LAM WITH JEEM WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FD84 0xFD84 // ﶄ ARABIC LIGATURE LAM WITH JEEM WITH JEEM FINAL FORM
#define UC_MACRO_NAME_FD85 0xFD85 // ﶅ ARABIC LIGATURE LAM WITH KHAH WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FD86 0xFD86 // ﶆ ARABIC LIGATURE LAM WITH KHAH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD87 0xFD87 // ﶇ ARABIC LIGATURE LAM WITH MEEM WITH HAH FINAL FORM
#define UC_MACRO_NAME_FD88 0xFD88 // ﶈ ARABIC LIGATURE LAM WITH MEEM WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FD89 0xFD89 // ﶉ ARABIC LIGATURE MEEM WITH HAH WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FD8A 0xFD8A // ﶊ ARABIC LIGATURE MEEM WITH HAH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD8B 0xFD8B // ﶋ ARABIC LIGATURE MEEM WITH HAH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD8C 0xFD8C // ﶌ ARABIC LIGATURE MEEM WITH JEEM WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FD8D 0xFD8D // ﶍ ARABIC LIGATURE MEEM WITH JEEM WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD8E 0xFD8E // ﶎ ARABIC LIGATURE MEEM WITH KHAH WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FD8F 0xFD8F // ﶏ ARABIC LIGATURE MEEM WITH KHAH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD90 0xFD90 //  ARABIC LIGATURE RAHMATU ALLAAHI ALAYH
#define UC_MACRO_NAME_FD91 0xFD91 //  ARABIC LIGATURE RAHMATU ALLAAHI ALAYHAA
#define UC_MACRO_NAME_FD92 0xFD92 // ﶒ ARABIC LIGATURE MEEM WITH JEEM WITH KHAH INITIAL FORM
#define UC_MACRO_NAME_FD93 0xFD93 // ﶓ ARABIC LIGATURE HEH WITH MEEM WITH JEEM INITIAL FORM
#define UC_MACRO_NAME_FD94 0xFD94 // ﶔ ARABIC LIGATURE HEH WITH MEEM WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD95 0xFD95 // ﶕ ARABIC LIGATURE NOON WITH HAH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD96 0xFD96 // ﶖ ARABIC LIGATURE NOON WITH HAH WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD97 0xFD97 // ﶗ ARABIC LIGATURE NOON WITH JEEM WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FD98 0xFD98 // ﶘ ARABIC LIGATURE NOON WITH JEEM WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD99 0xFD99 // ﶙ ARABIC LIGATURE NOON WITH JEEM WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD9A 0xFD9A // ﶚ ARABIC LIGATURE NOON WITH MEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD9B 0xFD9B // ﶛ ARABIC LIGATURE NOON WITH MEEM WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FD9C 0xFD9C // ﶜ ARABIC LIGATURE YEH WITH MEEM WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FD9D 0xFD9D // ﶝ ARABIC LIGATURE YEH WITH MEEM WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FD9E 0xFD9E // ﶞ ARABIC LIGATURE BEH WITH KHAH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FD9F 0xFD9F // ﶟ ARABIC LIGATURE TEH WITH JEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDA0 0xFDA0 // ﶠ ARABIC LIGATURE TEH WITH JEEM WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FDA1 0xFDA1 // ﶡ ARABIC LIGATURE TEH WITH KHAH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDA2 0xFDA2 // ﶢ ARABIC LIGATURE TEH WITH KHAH WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FDA3 0xFDA3 // ﶣ ARABIC LIGATURE TEH WITH MEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDA4 0xFDA4 // ﶤ ARABIC LIGATURE TEH WITH MEEM WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FDA5 0xFDA5 // ﶥ ARABIC LIGATURE JEEM WITH MEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDA6 0xFDA6 // ﶦ ARABIC LIGATURE JEEM WITH HAH WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FDA7 0xFDA7 // ﶧ ARABIC LIGATURE JEEM WITH MEEM WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FDA8 0xFDA8 // ﶨ ARABIC LIGATURE SEEN WITH KHAH WITH ALEF MAKSURA FINAL FORM
#define UC_MACRO_NAME_FDA9 0xFDA9 // ﶩ ARABIC LIGATURE SAD WITH HAH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDAA 0xFDAA // ﶪ ARABIC LIGATURE SHEEN WITH HAH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDAB 0xFDAB // ﶫ ARABIC LIGATURE DAD WITH HAH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDAC 0xFDAC // ﶬ ARABIC LIGATURE LAM WITH JEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDAD 0xFDAD // ﶭ ARABIC LIGATURE LAM WITH MEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDAE 0xFDAE // ﶮ ARABIC LIGATURE YEH WITH HAH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDAF 0xFDAF // ﶯ ARABIC LIGATURE YEH WITH JEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDB0 0xFDB0 // ﶰ ARABIC LIGATURE YEH WITH MEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDB1 0xFDB1 // ﶱ ARABIC LIGATURE MEEM WITH MEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDB2 0xFDB2 // ﶲ ARABIC LIGATURE QAF WITH MEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDB3 0xFDB3 // ﶳ ARABIC LIGATURE NOON WITH HAH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDB4 0xFDB4 // ﶴ ARABIC LIGATURE QAF WITH MEEM WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FDB5 0xFDB5 // ﶵ ARABIC LIGATURE LAM WITH HAH WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FDB6 0xFDB6 // ﶶ ARABIC LIGATURE AIN WITH MEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDB7 0xFDB7 // ﶷ ARABIC LIGATURE KAF WITH MEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDB8 0xFDB8 // ﶸ ARABIC LIGATURE NOON WITH JEEM WITH HAH INITIAL FORM
#define UC_MACRO_NAME_FDB9 0xFDB9 // ﶹ ARABIC LIGATURE MEEM WITH KHAH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDBA 0xFDBA // ﶺ ARABIC LIGATURE LAM WITH JEEM WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FDBB 0xFDBB // ﶻ ARABIC LIGATURE KAF WITH MEEM WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FDBC 0xFDBC // ﶼ ARABIC LIGATURE LAM WITH JEEM WITH MEEM FINAL FORM
#define UC_MACRO_NAME_FDBD 0xFDBD // ﶽ ARABIC LIGATURE NOON WITH JEEM WITH HAH FINAL FORM
#define UC_MACRO_NAME_FDBE 0xFDBE // ﶾ ARABIC LIGATURE JEEM WITH HAH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDBF 0xFDBF // ﶿ ARABIC LIGATURE HAH WITH JEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDC0 0xFDC0 // ﷀ ARABIC LIGATURE MEEM WITH JEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDC1 0xFDC1 // ﷁ ARABIC LIGATURE FEH WITH MEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDC2 0xFDC2 // ﷂ ARABIC LIGATURE BEH WITH HAH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDC3 0xFDC3 // ﷃ ARABIC LIGATURE KAF WITH MEEM WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FDC4 0xFDC4 // ﷄ ARABIC LIGATURE AIN WITH JEEM WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FDC5 0xFDC5 // ﷅ ARABIC LIGATURE SAD WITH MEEM WITH MEEM INITIAL FORM
#define UC_MACRO_NAME_FDC6 0xFDC6 // ﷆ ARABIC LIGATURE SEEN WITH KHAH WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDC7 0xFDC7 // ﷇ ARABIC LIGATURE NOON WITH JEEM WITH YEH FINAL FORM
#define UC_MACRO_NAME_FDC8 0xFDC8 //  ARABIC LIGATURE RAHIMAHU ALLAAH TAAALAA
#define UC_MACRO_NAME_FDC9 0xFDC9 //  ARABIC LIGATURE RADI ALLAAHU TAAALAA ANH
#define UC_MACRO_NAME_FDCA 0xFDCA //  ARABIC LIGATURE RADI ALLAAHU TAAALAA ANHAA
#define UC_MACRO_NAME_FDCB 0xFDCB //  ARABIC LIGATURE RADI ALLAAHU TAAALAA ANHUMAA
#define UC_MACRO_NAME_FDCC 0xFDCC //  ARABIC LIGATURE SALLALLAHU ALAYHI WA-ALAA AALIHEE WA-SALLAM
#define UC_MACRO_NAME_FDCD 0xFDCD //  ARABIC LIGATURE AJJAL ALLAAHU TAAALAA FARAJAHU ASH-SHAREEF
#define UC_MACRO_NAME_FDCE 0xFDCE //  ARABIC LIGATURE KARRAMA ALLAAHU WAJHAH
#define UC_MACRO_NAME_FDCF 0xFDCF // ﷏ ARABIC LIGATURE SALAAMUHU ALAYNAA
#define UC_MACRO_NAME_FDF0 0xFDF0 // ﷰ ARABIC LIGATURE SALLA USED AS KORANIC STOP SIGN ISOLATED FORM
#define UC_MACRO_NAME_FDF1 0xFDF1 // ﷱ ARABIC LIGATURE QALA USED AS KORANIC STOP SIGN ISOLATED FORM
#define UC_MACRO_NAME_FDF2 0xFDF2 // ﷲ ARABIC LIGATURE ALLAH ISOLATED FORM
#define UC_MACRO_NAME_FDF3 0xFDF3 // ﷳ ARABIC LIGATURE AKBAR ISOLATED FORM
#define UC_MACRO_NAME_FDF4 0xFDF4 // ﷴ ARABIC LIGATURE MOHAMMAD ISOLATED FORM
#define UC_MACRO_NAME_FDF5 0xFDF5 // ﷵ ARABIC LIGATURE SALAM ISOLATED FORM
#define UC_MACRO_NAME_FDF6 0xFDF6 // ﷶ ARABIC LIGATURE RASOUL ISOLATED FORM
#define UC_MACRO_NAME_FDF7 0xFDF7 // ﷷ ARABIC LIGATURE ALAYHE ISOLATED FORM
#define UC_MACRO_NAME_FDF8 0xFDF8 // ﷸ ARABIC LIGATURE WASALLAM ISOLATED FORM
#define UC_MACRO_NAME_FDF9 0xFDF9 // ﷹ ARABIC LIGATURE SALLA ISOLATED FORM
#define UC_MACRO_NAME_FDFA 0xFDFA // ﷺ ARABIC LIGATURE SALLALLAHOU ALAYHE WASALLAM
#define UC_MACRO_NAME_FDFB 0xFDFB // ﷻ ARABIC LIGATURE JALLAJALALOUHOU
#define UC_MACRO_NAME_FDFC 0xFDFC // ﷼ RIAL SIGN
#define UC_MACRO_NAME_FDFD 0xFDFD // ﷽ ARABIC LIGATURE BISMILLAH AR-RAHMAN AR-RAHEEM
#define UC_MACRO_NAME_FDFE 0xFDFE // ﷾ ARABIC LIGATURE SUBHAANAHU WA TAAALAA
#define UC_MACRO_NAME_FDFF 0xFDFF // ﷿ ARABIC LIGATURE AZZA WA JALL


#endif // UC_H_ARABIC_PRESENTATION_FORMS_A
