/*
 * Unicode Block: Arabic Extended-B
 * Range: U+0870..U+089F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_ARABIC_EXTENDED_B
#define UC_H_ARABIC_EXTENDED_B

#define UC_MACRO_NAME_870 0x0870 // ࡰ ARABIC LETTER ALEF WITH ATTACHED FATHA
#define UC_MACRO_NAME_871 0x0871 // ࡱ ARABIC LETTER ALEF WITH ATTACHED TOP RIGHT FATHA
#define UC_MACRO_NAME_872 0x0872 // ࡲ ARABIC LETTER ALEF WITH RIGHT MIDDLE STROKE
#define UC_MACRO_NAME_873 0x0873 // ࡳ ARABIC LETTER ALEF WITH LEFT MIDDLE STROKE
#define UC_MACRO_NAME_874 0x0874 // ࡴ ARABIC LETTER ALEF WITH ATTACHED KASRA
#define UC_MACRO_NAME_875 0x0875 // ࡵ ARABIC LETTER ALEF WITH ATTACHED BOTTOM RIGHT KASRA
#define UC_MACRO_NAME_876 0x0876 // ࡶ ARABIC LETTER ALEF WITH ATTACHED ROUND DOT ABOVE
#define UC_MACRO_NAME_877 0x0877 // ࡷ ARABIC LETTER ALEF WITH ATTACHED RIGHT ROUND DOT
#define UC_MACRO_NAME_878 0x0878 // ࡸ ARABIC LETTER ALEF WITH ATTACHED LEFT ROUND DOT
#define UC_MACRO_NAME_879 0x0879 // ࡹ ARABIC LETTER ALEF WITH ATTACHED ROUND DOT BELOW
#define UC_MACRO_NAME_87A 0x087A // ࡺ ARABIC LETTER ALEF WITH DOT ABOVE
#define UC_MACRO_NAME_87B 0x087B // ࡻ ARABIC LETTER ALEF WITH ATTACHED TOP RIGHT FATHA AND DOT ABOVE
#define UC_MACRO_NAME_87C 0x087C // ࡼ ARABIC LETTER ALEF WITH RIGHT MIDDLE STROKE AND DOT ABOVE
#define UC_MACRO_NAME_87D 0x087D // ࡽ ARABIC LETTER ALEF WITH ATTACHED BOTTOM RIGHT KASRA AND DOT ABOVE
#define UC_MACRO_NAME_87E 0x087E // ࡾ ARABIC LETTER ALEF WITH ATTACHED TOP RIGHT FATHA AND LEFT RING
#define UC_MACRO_NAME_87F 0x087F // ࡿ ARABIC LETTER ALEF WITH RIGHT MIDDLE STROKE AND LEFT RING
#define UC_MACRO_NAME_880 0x0880 // ࢀ ARABIC LETTER ALEF WITH ATTACHED BOTTOM RIGHT KASRA AND LEFT RING
#define UC_MACRO_NAME_881 0x0881 // ࢁ ARABIC LETTER ALEF WITH ATTACHED RIGHT HAMZA
#define UC_MACRO_NAME_882 0x0882 // ࢂ ARABIC LETTER ALEF WITH ATTACHED LEFT HAMZA
#define UC_MACRO_NAME_883 0x0883 // ࢃ ARABIC TATWEEL WITH OVERSTRUCK HAMZA
#define UC_MACRO_NAME_884 0x0884 // ࢄ ARABIC TATWEEL WITH OVERSTRUCK WAW
#define UC_MACRO_NAME_885 0x0885 // ࢅ ARABIC TATWEEL WITH TWO DOTS BELOW
#define UC_MACRO_NAME_886 0x0886 // ࢆ ARABIC LETTER THIN YEH
#define UC_MACRO_NAME_887 0x0887 // ࢇ ARABIC BASELINE ROUND DOT
#define UC_MACRO_NAME_888 0x0888 // ࢈ ARABIC RAISED ROUND DOT
#define UC_MACRO_NAME_889 0x0889 // ࢉ ARABIC LETTER NOON WITH INVERTED SMALL V
#define UC_MACRO_NAME_88A 0x088A // ࢊ ARABIC LETTER HAH WITH INVERTED SMALL V BELOW
#define UC_MACRO_NAME_88B 0x088B // ࢋ ARABIC LETTER TAH WITH DOT BELOW
#define UC_MACRO_NAME_88C 0x088C // ࢌ ARABIC LETTER TAH WITH THREE DOTS BELOW
#define UC_MACRO_NAME_88D 0x088D // ࢍ ARABIC LETTER KEHEH WITH TWO DOTS VERTICALLY BELOW
#define UC_MACRO_NAME_88E 0x088E // ࢎ ARABIC VERTICAL TAIL
#define UC_MACRO_NAME_88F 0x088F //  ARABIC LETTER NOON WITH RING ABOVE
#define UC_MACRO_NAME_890 0x0890 //  ARABIC POUND MARK ABOVE
#define UC_MACRO_NAME_891 0x0891 //  ARABIC PIASTRE MARK ABOVE
#define UC_MACRO_NAME_897 0x0897 //  ARABIC PEPET
#define UC_MACRO_NAME_898 0x0898 // ࢘ ARABIC SMALL HIGH WORD AL-JUZ
#define UC_MACRO_NAME_899 0x0899 // ࢙ ARABIC SMALL LOW WORD ISHMAAM
#define UC_MACRO_NAME_89A 0x089A // ࢚ ARABIC SMALL LOW WORD IMAALA
#define UC_MACRO_NAME_89B 0x089B // ࢛ ARABIC SMALL LOW WORD TASHEEL
#define UC_MACRO_NAME_89C 0x089C // ࢜ ARABIC MADDA WAAJIB
#define UC_MACRO_NAME_89D 0x089D // ࢝ ARABIC SUPERSCRIPT ALEF MOKHASSAS
#define UC_MACRO_NAME_89E 0x089E // ࢞ ARABIC DOUBLED MADDA
#define UC_MACRO_NAME_89F 0x089F // ࢟ ARABIC HALF MADDA OVER MADDA


#endif // UC_H_ARABIC_EXTENDED_B
