/*
 * Unicode Block: Arabic Supplement
 * Range: U+0750..U+077F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Arabic Supplement is a Unicode block that encodes Arabic letter
 * variants used for writing non-Arabic languages, including languages of
 * Pakistan and Africa, and Old Persian.
 * The following Unicode-related documents record the purpose and process
 * of defining specific characters in the Arabic Supplement block:
 *
 */
#ifndef UC_H_ARABIC_SUPPLEMENT
#define UC_H_ARABIC_SUPPLEMENT

#define UC_MACRO_NAME_750 0x0750 // ݐ ARABIC LETTER BEH WITH THREE DOTS HORIZONTALLY BELOW
#define UC_MACRO_NAME_751 0x0751 // ݑ ARABIC LETTER BEH WITH DOT BELOW AND THREE DOTS ABOVE
#define UC_MACRO_NAME_752 0x0752 // ݒ ARABIC LETTER BEH WITH THREE DOTS POINTING UPWARDS BELOW
#define UC_MACRO_NAME_753 0x0753 // ݓ ARABIC LETTER BEH WITH THREE DOTS POINTING UPWARDS BELOW AND TWO DOTS ABOVE
#define UC_MACRO_NAME_754 0x0754 // ݔ ARABIC LETTER BEH WITH TWO DOTS BELOW AND DOT ABOVE
#define UC_MACRO_NAME_755 0x0755 // ݕ ARABIC LETTER BEH WITH INVERTED SMALL V BELOW
#define UC_MACRO_NAME_756 0x0756 // ݖ ARABIC LETTER BEH WITH SMALL V
#define UC_MACRO_NAME_757 0x0757 // ݗ ARABIC LETTER HAH WITH TWO DOTS ABOVE
#define UC_MACRO_NAME_758 0x0758 // ݘ ARABIC LETTER HAH WITH THREE DOTS POINTING UPWARDS BELOW
#define UC_MACRO_NAME_759 0x0759 // ݙ ARABIC LETTER DAL WITH TWO DOTS VERTICALLY BELOW AND SMALL TAH
#define UC_MACRO_NAME_75A 0x075A // ݚ ARABIC LETTER DAL WITH INVERTED SMALL V BELOW
#define UC_MACRO_NAME_75B 0x075B // ݛ ARABIC LETTER REH WITH STROKE
#define UC_MACRO_NAME_75C 0x075C // ݜ ARABIC LETTER SEEN WITH FOUR DOTS ABOVE
#define UC_MACRO_NAME_75D 0x075D // ݝ ARABIC LETTER AIN WITH TWO DOTS ABOVE
#define UC_MACRO_NAME_75E 0x075E // ݞ ARABIC LETTER AIN WITH THREE DOTS POINTING DOWNWARDS ABOVE
#define UC_MACRO_NAME_75F 0x075F // ݟ ARABIC LETTER AIN WITH TWO DOTS VERTICALLY ABOVE
#define UC_MACRO_NAME_760 0x0760 // ݠ ARABIC LETTER FEH WITH TWO DOTS BELOW
#define UC_MACRO_NAME_761 0x0761 // ݡ ARABIC LETTER FEH WITH THREE DOTS POINTING UPWARDS BELOW
#define UC_MACRO_NAME_762 0x0762 // ݢ ARABIC LETTER KEHEH WITH DOT ABOVE
#define UC_MACRO_NAME_763 0x0763 // ݣ ARABIC LETTER KEHEH WITH THREE DOTS ABOVE
#define UC_MACRO_NAME_764 0x0764 // ݤ ARABIC LETTER KEHEH WITH THREE DOTS POINTING UPWARDS BELOW
#define UC_MACRO_NAME_765 0x0765 // ݥ ARABIC LETTER MEEM WITH DOT ABOVE
#define UC_MACRO_NAME_766 0x0766 // ݦ ARABIC LETTER MEEM WITH DOT BELOW
#define UC_MACRO_NAME_767 0x0767 // ݧ ARABIC LETTER NOON WITH TWO DOTS BELOW
#define UC_MACRO_NAME_768 0x0768 // ݨ ARABIC LETTER NOON WITH SMALL TAH
#define UC_MACRO_NAME_769 0x0769 // ݩ ARABIC LETTER NOON WITH SMALL V
#define UC_MACRO_NAME_76A 0x076A // ݪ ARABIC LETTER LAM WITH BAR
#define UC_MACRO_NAME_76B 0x076B // ݫ ARABIC LETTER REH WITH TWO DOTS VERTICALLY ABOVE
#define UC_MACRO_NAME_76C 0x076C // ݬ ARABIC LETTER REH WITH HAMZA ABOVE
#define UC_MACRO_NAME_76D 0x076D // ݭ ARABIC LETTER SEEN WITH TWO DOTS VERTICALLY ABOVE
#define UC_MACRO_NAME_76E 0x076E // ݮ ARABIC LETTER HAH WITH SMALL ARABIC LETTER TAH BELOW
#define UC_MACRO_NAME_76F 0x076F // ݯ ARABIC LETTER HAH WITH SMALL ARABIC LETTER TAH AND TWO DOTS
#define UC_MACRO_NAME_770 0x0770 // ݰ ARABIC LETTER SEEN WITH SMALL ARABIC LETTER TAH AND TWO DOTS
#define UC_MACRO_NAME_771 0x0771 // ݱ ARABIC LETTER REH WITH SMALL ARABIC LETTER TAH AND TWO DOTS
#define UC_MACRO_NAME_772 0x0772 // ݲ ARABIC LETTER HAH WITH SMALL ARABIC LETTER TAH ABOVE
#define UC_MACRO_NAME_773 0x0773 // ݳ ARABIC LETTER ALEF WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE
#define UC_MACRO_NAME_774 0x0774 // ݴ ARABIC LETTER ALEF WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE
#define UC_MACRO_NAME_775 0x0775 // ݵ ARABIC LETTER FARSI YEH WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE
#define UC_MACRO_NAME_776 0x0776 // ݶ ARABIC LETTER FARSI YEH WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE
#define UC_MACRO_NAME_777 0x0777 // ݷ ARABIC LETTER FARSI YEH WITH EXTENDED ARABIC-INDIC DIGIT FOUR BELOW
#define UC_MACRO_NAME_778 0x0778 // ݸ ARABIC LETTER WAW WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE
#define UC_MACRO_NAME_779 0x0779 // ݹ ARABIC LETTER WAW WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE
#define UC_MACRO_NAME_77A 0x077A // ݺ ARABIC LETTER YEH BARREE WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE
#define UC_MACRO_NAME_77B 0x077B // ݻ ARABIC LETTER YEH BARREE WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE
#define UC_MACRO_NAME_77C 0x077C // ݼ ARABIC LETTER HAH WITH EXTENDED ARABIC-INDIC DIGIT FOUR BELOW
#define UC_MACRO_NAME_77D 0x077D // ݽ ARABIC LETTER SEEN WITH EXTENDED ARABIC-INDIC DIGIT FOUR ABOVE
#define UC_MACRO_NAME_77E 0x077E // ݾ ARABIC LETTER SEEN WITH INVERTED V
#define UC_MACRO_NAME_77F 0x077F // ݿ ARABIC LETTER KAF WITH TWO DOTS ABOVE


#endif // UC_H_ARABIC_SUPPLEMENT
