/*
 * Unicode Block: Alphabetic Presentation Forms
 * Range: U+FB00..U+FB4F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Alphabetic Presentation Forms is a Unicode block containing standard
 * ligatures for the Latin, Armenian, and Hebrew scripts.
 *
 */
#ifndef UC_H_ALPHABETIC_PRESENTATION_FORMS
#define UC_H_ALPHABETIC_PRESENTATION_FORMS

#define UC_MACRO_NAME_FB00 0xFB00 // ﬀ LATIN SMALL LIGATURE FF
#define UC_MACRO_NAME_FB01 0xFB01 // ﬁ LATIN SMALL LIGATURE FI
#define UC_MACRO_NAME_FB02 0xFB02 // ﬂ LATIN SMALL LIGATURE FL
#define UC_MACRO_NAME_FB03 0xFB03 // ﬃ LATIN SMALL LIGATURE FFI
#define UC_MACRO_NAME_FB04 0xFB04 // ﬄ LATIN SMALL LIGATURE FFL
#define UC_MACRO_NAME_FB05 0xFB05 // ﬅ LATIN SMALL LIGATURE LONG S T
#define UC_MACRO_NAME_FB06 0xFB06 // ﬆ LATIN SMALL LIGATURE ST
#define UC_MACRO_NAME_FB13 0xFB13 // ﬓ ARMENIAN SMALL LIGATURE MEN NOW
#define UC_MACRO_NAME_FB14 0xFB14 // ﬔ ARMENIAN SMALL LIGATURE MEN ECH
#define UC_MACRO_NAME_FB15 0xFB15 // ﬕ ARMENIAN SMALL LIGATURE MEN INI
#define UC_MACRO_NAME_FB16 0xFB16 // ﬖ ARMENIAN SMALL LIGATURE VEW NOW
#define UC_MACRO_NAME_FB17 0xFB17 // ﬗ ARMENIAN SMALL LIGATURE MEN XEH
#define UC_MACRO_NAME_FB1D 0xFB1D // יִ HEBREW LETTER YOD WITH HIRIQ
#define UC_MACRO_NAME_FB1E 0xFB1E // ﬞ HEBREW POINT JUDEO-SPANISH VARIKA
#define UC_MACRO_NAME_FB1F 0xFB1F // ײַ HEBREW LIGATURE YIDDISH YOD YOD PATAH
#define UC_MACRO_NAME_FB20 0xFB20 // ﬠ HEBREW LETTER ALTERNATIVE AYIN
#define UC_MACRO_NAME_FB21 0xFB21 // ﬡ HEBREW LETTER WIDE ALEF
#define UC_MACRO_NAME_FB22 0xFB22 // ﬢ HEBREW LETTER WIDE DALET
#define UC_MACRO_NAME_FB23 0xFB23 // ﬣ HEBREW LETTER WIDE HE
#define UC_MACRO_NAME_FB24 0xFB24 // ﬤ HEBREW LETTER WIDE KAF
#define UC_MACRO_NAME_FB25 0xFB25 // ﬥ HEBREW LETTER WIDE LAMED
#define UC_MACRO_NAME_FB26 0xFB26 // ﬦ HEBREW LETTER WIDE FINAL MEM
#define UC_MACRO_NAME_FB27 0xFB27 // ﬧ HEBREW LETTER WIDE RESH
#define UC_MACRO_NAME_FB28 0xFB28 // ﬨ HEBREW LETTER WIDE TAV
#define UC_MACRO_NAME_FB29 0xFB29 // ﬩ HEBREW LETTER ALTERNATIVE PLUS SIGN
#define UC_MACRO_NAME_FB2A 0xFB2A // שׁ HEBREW LETTER SHIN WITH SHIN DOT
#define UC_MACRO_NAME_FB2B 0xFB2B // שׂ HEBREW LETTER SHIN WITH SIN DOT
#define UC_MACRO_NAME_FB2C 0xFB2C // שּׁ HEBREW LETTER SHIN WITH DAGESH AND SHIN DOT
#define UC_MACRO_NAME_FB2D 0xFB2D // שּׂ HEBREW LETTER SHIN WITH DAGESH AND SIN DOT
#define UC_MACRO_NAME_FB2E 0xFB2E // אַ HEBREW LETTER ALEF WITH PATAH
#define UC_MACRO_NAME_FB2F 0xFB2F // אָ HEBREW LETTER ALEF WITH QAMATS
#define UC_MACRO_NAME_FB30 0xFB30 // אּ HEBREW LETTER ALEF WITH MAPIQ
#define UC_MACRO_NAME_FB31 0xFB31 // בּ HEBREW LETTER BET WITH DAGESH
#define UC_MACRO_NAME_FB32 0xFB32 // גּ HEBREW LETTER GIMEL WITH DAGESH
#define UC_MACRO_NAME_FB33 0xFB33 // דּ HEBREW LETTER DALET WITH DAGESH
#define UC_MACRO_NAME_FB34 0xFB34 // הּ HEBREW LETTER HE WITH MAPIQ
#define UC_MACRO_NAME_FB35 0xFB35 // וּ HEBREW LETTER VAV WITH DAGESH
#define UC_MACRO_NAME_FB36 0xFB36 // זּ HEBREW LETTER ZAYIN WITH DAGESH
#define UC_MACRO_NAME_FB38 0xFB38 // טּ HEBREW LETTER TET WITH DAGESH
#define UC_MACRO_NAME_FB39 0xFB39 // יּ HEBREW LETTER YOD WITH DAGESH
#define UC_MACRO_NAME_FB3A 0xFB3A // ךּ HEBREW LETTER FINAL KAF WITH DAGESH
#define UC_MACRO_NAME_FB3B 0xFB3B // כּ HEBREW LETTER KAF WITH DAGESH
#define UC_MACRO_NAME_FB3C 0xFB3C // לּ HEBREW LETTER LAMED WITH DAGESH
#define UC_MACRO_NAME_FB3E 0xFB3E // מּ HEBREW LETTER MEM WITH DAGESH
#define UC_MACRO_NAME_FB40 0xFB40 // נּ HEBREW LETTER NUN WITH DAGESH
#define UC_MACRO_NAME_FB41 0xFB41 // סּ HEBREW LETTER SAMEKH WITH DAGESH
#define UC_MACRO_NAME_FB43 0xFB43 // ףּ HEBREW LETTER FINAL PE WITH DAGESH
#define UC_MACRO_NAME_FB44 0xFB44 // פּ HEBREW LETTER PE WITH DAGESH
#define UC_MACRO_NAME_FB46 0xFB46 // צּ HEBREW LETTER TSADI WITH DAGESH
#define UC_MACRO_NAME_FB47 0xFB47 // קּ HEBREW LETTER QOF WITH DAGESH
#define UC_MACRO_NAME_FB48 0xFB48 // רּ HEBREW LETTER RESH WITH DAGESH
#define UC_MACRO_NAME_FB49 0xFB49 // שּ HEBREW LETTER SHIN WITH DAGESH
#define UC_MACRO_NAME_FB4A 0xFB4A // תּ HEBREW LETTER TAV WITH DAGESH
#define UC_MACRO_NAME_FB4B 0xFB4B // וֹ HEBREW LETTER VAV WITH HOLAM
#define UC_MACRO_NAME_FB4C 0xFB4C // בֿ HEBREW LETTER BET WITH RAFE
#define UC_MACRO_NAME_FB4D 0xFB4D // כֿ HEBREW LETTER KAF WITH RAFE
#define UC_MACRO_NAME_FB4E 0xFB4E // פֿ HEBREW LETTER PE WITH RAFE
#define UC_MACRO_NAME_FB4F 0xFB4F // ﭏ HEBREW LIGATURE ALEF LAMED


#endif // UC_H_ALPHABETIC_PRESENTATION_FORMS
