/*
 * Unicode Block: Arrows
 * Range: U+2190..U+21FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * An arrow is a projectile launched from a bow.
 * Arrow or Arrows may also refer to:
 *
 */
#ifndef UC_H_ARROWS
#define UC_H_ARROWS

#define UC_MACRO_NAME_2190 0x2190 // ← LEFTWARDS ARROW
#define UC_MACRO_NAME_2191 0x2191 // ↑ UPWARDS ARROW
#define UC_MACRO_NAME_2192 0x2192 // → RIGHTWARDS ARROW
#define UC_MACRO_NAME_2193 0x2193 // ↓ DOWNWARDS ARROW
#define UC_MACRO_NAME_2194 0x2194 // ↔ LEFT RIGHT ARROW
#define UC_MACRO_NAME_2195 0x2195 // ↕ UP DOWN ARROW
#define UC_MACRO_NAME_2196 0x2196 // ↖ NORTH WEST ARROW
#define UC_MACRO_NAME_2197 0x2197 // ↗ NORTH EAST ARROW
#define UC_MACRO_NAME_2198 0x2198 // ↘ SOUTH EAST ARROW
#define UC_MACRO_NAME_2199 0x2199 // ↙ SOUTH WEST ARROW
#define UC_MACRO_NAME_219A 0x219A // ↚ LEFTWARDS ARROW WITH STROKE
#define UC_MACRO_NAME_219B 0x219B // ↛ RIGHTWARDS ARROW WITH STROKE
#define UC_MACRO_NAME_219C 0x219C // ↜ LEFTWARDS WAVE ARROW
#define UC_MACRO_NAME_219D 0x219D // ↝ RIGHTWARDS WAVE ARROW
#define UC_MACRO_NAME_219E 0x219E // ↞ LEFTWARDS TWO HEADED ARROW
#define UC_MACRO_NAME_219F 0x219F // ↟ UPWARDS TWO HEADED ARROW
#define UC_MACRO_NAME_21A0 0x21A0 // ↠ RIGHTWARDS TWO HEADED ARROW
#define UC_MACRO_NAME_21A1 0x21A1 // ↡ DOWNWARDS TWO HEADED ARROW
#define UC_MACRO_NAME_21A2 0x21A2 // ↢ LEFTWARDS ARROW WITH TAIL
#define UC_MACRO_NAME_21A3 0x21A3 // ↣ RIGHTWARDS ARROW WITH TAIL
#define UC_MACRO_NAME_21A4 0x21A4 // ↤ LEFTWARDS ARROW FROM BAR
#define UC_MACRO_NAME_21A5 0x21A5 // ↥ UPWARDS ARROW FROM BAR
#define UC_MACRO_NAME_21A6 0x21A6 // ↦ RIGHTWARDS ARROW FROM BAR
#define UC_MACRO_NAME_21A7 0x21A7 // ↧ DOWNWARDS ARROW FROM BAR
#define UC_MACRO_NAME_21A8 0x21A8 // ↨ UP DOWN ARROW WITH BASE
#define UC_MACRO_NAME_21A9 0x21A9 // ↩ LEFTWARDS ARROW WITH HOOK
#define UC_MACRO_NAME_21AA 0x21AA // ↪ RIGHTWARDS ARROW WITH HOOK
#define UC_MACRO_NAME_21AB 0x21AB // ↫ LEFTWARDS ARROW WITH LOOP
#define UC_MACRO_NAME_21AC 0x21AC // ↬ RIGHTWARDS ARROW WITH LOOP
#define UC_MACRO_NAME_21AD 0x21AD // ↭ LEFT RIGHT WAVE ARROW
#define UC_MACRO_NAME_21AE 0x21AE // ↮ LEFT RIGHT ARROW WITH STROKE
#define UC_MACRO_NAME_21AF 0x21AF // ↯ DOWNWARDS ZIGZAG ARROW
#define UC_MACRO_NAME_21B0 0x21B0 // ↰ UPWARDS ARROW WITH TIP LEFTWARDS
#define UC_MACRO_NAME_21B1 0x21B1 // ↱ UPWARDS ARROW WITH TIP RIGHTWARDS
#define UC_MACRO_NAME_21B2 0x21B2 // ↲ DOWNWARDS ARROW WITH TIP LEFTWARDS
#define UC_MACRO_NAME_21B3 0x21B3 // ↳ DOWNWARDS ARROW WITH TIP RIGHTWARDS
#define UC_MACRO_NAME_21B4 0x21B4 // ↴ RIGHTWARDS ARROW WITH CORNER DOWNWARDS
#define UC_MACRO_NAME_21B5 0x21B5 // ↵ DOWNWARDS ARROW WITH CORNER LEFTWARDS
#define UC_MACRO_NAME_21B6 0x21B6 // ↶ ANTICLOCKWISE TOP SEMICIRCLE ARROW
#define UC_MACRO_NAME_21B7 0x21B7 // ↷ CLOCKWISE TOP SEMICIRCLE ARROW
#define UC_MACRO_NAME_21B8 0x21B8 // ↸ NORTH WEST ARROW TO LONG BAR
#define UC_MACRO_NAME_21B9 0x21B9 // ↹ LEFTWARDS ARROW TO BAR OVER RIGHTWARDS ARROW TO BAR
#define UC_MACRO_NAME_21BA 0x21BA // ↺ ANTICLOCKWISE OPEN CIRCLE ARROW
#define UC_MACRO_NAME_21BB 0x21BB // ↻ CLOCKWISE OPEN CIRCLE ARROW
#define UC_MACRO_NAME_21BC 0x21BC // ↼ LEFTWARDS HARPOON WITH BARB UPWARDS
#define UC_MACRO_NAME_21BD 0x21BD // ↽ LEFTWARDS HARPOON WITH BARB DOWNWARDS
#define UC_MACRO_NAME_21BE 0x21BE // ↾ UPWARDS HARPOON WITH BARB RIGHTWARDS
#define UC_MACRO_NAME_21BF 0x21BF // ↿ UPWARDS HARPOON WITH BARB LEFTWARDS
#define UC_MACRO_NAME_21C0 0x21C0 // ⇀ RIGHTWARDS HARPOON WITH BARB UPWARDS
#define UC_MACRO_NAME_21C1 0x21C1 // ⇁ RIGHTWARDS HARPOON WITH BARB DOWNWARDS
#define UC_MACRO_NAME_21C2 0x21C2 // ⇂ DOWNWARDS HARPOON WITH BARB RIGHTWARDS
#define UC_MACRO_NAME_21C3 0x21C3 // ⇃ DOWNWARDS HARPOON WITH BARB LEFTWARDS
#define UC_MACRO_NAME_21C4 0x21C4 // ⇄ RIGHTWARDS ARROW OVER LEFTWARDS ARROW
#define UC_MACRO_NAME_21C5 0x21C5 // ⇅ UPWARDS ARROW LEFTWARDS OF DOWNWARDS ARROW
#define UC_MACRO_NAME_21C6 0x21C6 // ⇆ LEFTWARDS ARROW OVER RIGHTWARDS ARROW
#define UC_MACRO_NAME_21C7 0x21C7 // ⇇ LEFTWARDS PAIRED ARROWS
#define UC_MACRO_NAME_21C8 0x21C8 // ⇈ UPWARDS PAIRED ARROWS
#define UC_MACRO_NAME_21C9 0x21C9 // ⇉ RIGHTWARDS PAIRED ARROWS
#define UC_MACRO_NAME_21CA 0x21CA // ⇊ DOWNWARDS PAIRED ARROWS
#define UC_MACRO_NAME_21CB 0x21CB // ⇋ LEFTWARDS HARPOON OVER RIGHTWARDS HARPOON
#define UC_MACRO_NAME_21CC 0x21CC // ⇌ RIGHTWARDS HARPOON OVER LEFTWARDS HARPOON
#define UC_MACRO_NAME_21CD 0x21CD // ⇍ LEFTWARDS DOUBLE ARROW WITH STROKE
#define UC_MACRO_NAME_21CE 0x21CE // ⇎ LEFT RIGHT DOUBLE ARROW WITH STROKE
#define UC_MACRO_NAME_21CF 0x21CF // ⇏ RIGHTWARDS DOUBLE ARROW WITH STROKE
#define UC_MACRO_NAME_21D0 0x21D0 // ⇐ LEFTWARDS DOUBLE ARROW
#define UC_MACRO_NAME_21D1 0x21D1 // ⇑ UPWARDS DOUBLE ARROW
#define UC_MACRO_NAME_21D2 0x21D2 // ⇒ RIGHTWARDS DOUBLE ARROW
#define UC_MACRO_NAME_21D3 0x21D3 // ⇓ DOWNWARDS DOUBLE ARROW
#define UC_MACRO_NAME_21D4 0x21D4 // ⇔ LEFT RIGHT DOUBLE ARROW
#define UC_MACRO_NAME_21D5 0x21D5 // ⇕ UP DOWN DOUBLE ARROW
#define UC_MACRO_NAME_21D6 0x21D6 // ⇖ NORTH WEST DOUBLE ARROW
#define UC_MACRO_NAME_21D7 0x21D7 // ⇗ NORTH EAST DOUBLE ARROW
#define UC_MACRO_NAME_21D8 0x21D8 // ⇘ SOUTH EAST DOUBLE ARROW
#define UC_MACRO_NAME_21D9 0x21D9 // ⇙ SOUTH WEST DOUBLE ARROW
#define UC_MACRO_NAME_21DA 0x21DA // ⇚ LEFTWARDS TRIPLE ARROW
#define UC_MACRO_NAME_21DB 0x21DB // ⇛ RIGHTWARDS TRIPLE ARROW
#define UC_MACRO_NAME_21DC 0x21DC // ⇜ LEFTWARDS SQUIGGLE ARROW
#define UC_MACRO_NAME_21DD 0x21DD // ⇝ RIGHTWARDS SQUIGGLE ARROW
#define UC_MACRO_NAME_21DE 0x21DE // ⇞ UPWARDS ARROW WITH DOUBLE STROKE
#define UC_MACRO_NAME_21DF 0x21DF // ⇟ DOWNWARDS ARROW WITH DOUBLE STROKE
#define UC_MACRO_NAME_21E0 0x21E0 // ⇠ LEFTWARDS DASHED ARROW
#define UC_MACRO_NAME_21E1 0x21E1 // ⇡ UPWARDS DASHED ARROW
#define UC_MACRO_NAME_21E2 0x21E2 // ⇢ RIGHTWARDS DASHED ARROW
#define UC_MACRO_NAME_21E3 0x21E3 // ⇣ DOWNWARDS DASHED ARROW
#define UC_MACRO_NAME_21E4 0x21E4 // ⇤ LEFTWARDS ARROW TO BAR
#define UC_MACRO_NAME_21E5 0x21E5 // ⇥ RIGHTWARDS ARROW TO BAR
#define UC_MACRO_NAME_21E6 0x21E6 // ⇦ LEFTWARDS WHITE ARROW
#define UC_MACRO_NAME_21E7 0x21E7 // ⇧ UPWARDS WHITE ARROW
#define UC_MACRO_NAME_21E8 0x21E8 // ⇨ RIGHTWARDS WHITE ARROW
#define UC_MACRO_NAME_21E9 0x21E9 // ⇩ DOWNWARDS WHITE ARROW
#define UC_MACRO_NAME_21EA 0x21EA // ⇪ UPWARDS WHITE ARROW FROM BAR
#define UC_MACRO_NAME_21EB 0x21EB // ⇫ UPWARDS WHITE ARROW ON PEDESTAL
#define UC_MACRO_NAME_21EC 0x21EC // ⇬ UPWARDS WHITE ARROW ON PEDESTAL WITH HORIZONTAL BAR
#define UC_MACRO_NAME_21ED 0x21ED // ⇭ UPWARDS WHITE ARROW ON PEDESTAL WITH VERTICAL BAR
#define UC_MACRO_NAME_21EE 0x21EE // ⇮ UPWARDS WHITE DOUBLE ARROW
#define UC_MACRO_NAME_21EF 0x21EF // ⇯ UPWARDS WHITE DOUBLE ARROW ON PEDESTAL
#define UC_MACRO_NAME_21F0 0x21F0 // ⇰ RIGHTWARDS WHITE ARROW FROM WALL
#define UC_MACRO_NAME_21F1 0x21F1 // ⇱ NORTH WEST ARROW TO CORNER
#define UC_MACRO_NAME_21F2 0x21F2 // ⇲ SOUTH EAST ARROW TO CORNER
#define UC_MACRO_NAME_21F3 0x21F3 // ⇳ UP DOWN WHITE ARROW
#define UC_MACRO_NAME_21F4 0x21F4 // ⇴ RIGHT ARROW WITH SMALL CIRCLE
#define UC_MACRO_NAME_21F5 0x21F5 // ⇵ DOWNWARDS ARROW LEFTWARDS OF UPWARDS ARROW
#define UC_MACRO_NAME_21F6 0x21F6 // ⇶ THREE RIGHTWARDS ARROWS
#define UC_MACRO_NAME_21F7 0x21F7 // ⇷ LEFTWARDS ARROW WITH VERTICAL STROKE
#define UC_MACRO_NAME_21F8 0x21F8 // ⇸ RIGHTWARDS ARROW WITH VERTICAL STROKE
#define UC_MACRO_NAME_21F9 0x21F9 // ⇹ LEFT RIGHT ARROW WITH VERTICAL STROKE
#define UC_MACRO_NAME_21FA 0x21FA // ⇺ LEFTWARDS ARROW WITH DOUBLE VERTICAL STROKE
#define UC_MACRO_NAME_21FB 0x21FB // ⇻ RIGHTWARDS ARROW WITH DOUBLE VERTICAL STROKE
#define UC_MACRO_NAME_21FC 0x21FC // ⇼ LEFT RIGHT ARROW WITH DOUBLE VERTICAL STROKE
#define UC_MACRO_NAME_21FD 0x21FD // ⇽ LEFTWARDS OPEN-HEADED ARROW
#define UC_MACRO_NAME_21FE 0x21FE // ⇾ RIGHTWARDS OPEN-HEADED ARROW
#define UC_MACRO_NAME_21FF 0x21FF // ⇿ LEFT RIGHT OPEN-HEADED ARROW


#endif // UC_H_ARROWS
