/*
 * Unicode Block: Bengali
 * Range: U+0980..U+09FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Bengali or Bengalee , or Bengalese may refer to:
 *
 */
#ifndef UC_H_BENGALI
#define UC_H_BENGALI

#define UC_MACRO_NAME_980 0x0980 // ঀ BENGALI ANJI
#define UC_MACRO_NAME_981 0x0981 // ঁ BENGALI SIGN CANDRABINDU
#define UC_MACRO_NAME_982 0x0982 // ং BENGALI SIGN ANUSVARA
#define UC_MACRO_NAME_983 0x0983 // ঃ BENGALI SIGN VISARGA
#define UC_MACRO_NAME_985 0x0985 // অ BENGALI LETTER A
#define UC_MACRO_NAME_986 0x0986 // আ BENGALI LETTER AA
#define UC_MACRO_NAME_987 0x0987 // ই BENGALI LETTER I
#define UC_MACRO_NAME_988 0x0988 // ঈ BENGALI LETTER II
#define UC_MACRO_NAME_989 0x0989 // উ BENGALI LETTER U
#define UC_MACRO_NAME_98A 0x098A // ঊ BENGALI LETTER UU
#define UC_MACRO_NAME_98B 0x098B // ঋ BENGALI LETTER VOCALIC R
#define UC_MACRO_NAME_98C 0x098C // ঌ BENGALI LETTER VOCALIC L
#define UC_MACRO_NAME_98F 0x098F // এ BENGALI LETTER E
#define UC_MACRO_NAME_990 0x0990 // ঐ BENGALI LETTER AI
#define UC_MACRO_NAME_993 0x0993 // ও BENGALI LETTER O
#define UC_MACRO_NAME_994 0x0994 // ঔ BENGALI LETTER AU
#define UC_MACRO_NAME_995 0x0995 // ক BENGALI LETTER KA
#define UC_MACRO_NAME_996 0x0996 // খ BENGALI LETTER KHA
#define UC_MACRO_NAME_997 0x0997 // গ BENGALI LETTER GA
#define UC_MACRO_NAME_998 0x0998 // ঘ BENGALI LETTER GHA
#define UC_MACRO_NAME_999 0x0999 // ঙ BENGALI LETTER NGA
#define UC_MACRO_NAME_99A 0x099A // চ BENGALI LETTER CA
#define UC_MACRO_NAME_99B 0x099B // ছ BENGALI LETTER CHA
#define UC_MACRO_NAME_99C 0x099C // জ BENGALI LETTER JA
#define UC_MACRO_NAME_99D 0x099D // ঝ BENGALI LETTER JHA
#define UC_MACRO_NAME_99E 0x099E // ঞ BENGALI LETTER NYA
#define UC_MACRO_NAME_99F 0x099F // ট BENGALI LETTER TTA
#define UC_MACRO_NAME_9A0 0x09A0 // ঠ BENGALI LETTER TTHA
#define UC_MACRO_NAME_9A1 0x09A1 // ড BENGALI LETTER DDA
#define UC_MACRO_NAME_9A2 0x09A2 // ঢ BENGALI LETTER DDHA
#define UC_MACRO_NAME_9A3 0x09A3 // ণ BENGALI LETTER NNA
#define UC_MACRO_NAME_9A4 0x09A4 // ত BENGALI LETTER TA
#define UC_MACRO_NAME_9A5 0x09A5 // থ BENGALI LETTER THA
#define UC_MACRO_NAME_9A6 0x09A6 // দ BENGALI LETTER DA
#define UC_MACRO_NAME_9A7 0x09A7 // ধ BENGALI LETTER DHA
#define UC_MACRO_NAME_9A8 0x09A8 // ন BENGALI LETTER NA
#define UC_MACRO_NAME_9AA 0x09AA // প BENGALI LETTER PA
#define UC_MACRO_NAME_9AB 0x09AB // ফ BENGALI LETTER PHA
#define UC_MACRO_NAME_9AC 0x09AC // ব BENGALI LETTER BA
#define UC_MACRO_NAME_9AD 0x09AD // ভ BENGALI LETTER BHA
#define UC_MACRO_NAME_9AE 0x09AE // ম BENGALI LETTER MA
#define UC_MACRO_NAME_9AF 0x09AF // য BENGALI LETTER YA
#define UC_MACRO_NAME_9B0 0x09B0 // র BENGALI LETTER RA
#define UC_MACRO_NAME_9B2 0x09B2 // ল BENGALI LETTER LA
#define UC_MACRO_NAME_9B6 0x09B6 // শ BENGALI LETTER SHA
#define UC_MACRO_NAME_9B7 0x09B7 // ষ BENGALI LETTER SSA
#define UC_MACRO_NAME_9B8 0x09B8 // স BENGALI LETTER SA
#define UC_MACRO_NAME_9B9 0x09B9 // হ BENGALI LETTER HA
#define UC_MACRO_NAME_9BC 0x09BC // ় BENGALI SIGN NUKTA
#define UC_MACRO_NAME_9BD 0x09BD // ঽ BENGALI SIGN AVAGRAHA
#define UC_MACRO_NAME_9BE 0x09BE // া BENGALI VOWEL SIGN AA
#define UC_MACRO_NAME_9BF 0x09BF // ি BENGALI VOWEL SIGN I
#define UC_MACRO_NAME_9C0 0x09C0 // ী BENGALI VOWEL SIGN II
#define UC_MACRO_NAME_9C1 0x09C1 // ু BENGALI VOWEL SIGN U
#define UC_MACRO_NAME_9C2 0x09C2 // ূ BENGALI VOWEL SIGN UU
#define UC_MACRO_NAME_9C3 0x09C3 // ৃ BENGALI VOWEL SIGN VOCALIC R
#define UC_MACRO_NAME_9C4 0x09C4 // ৄ BENGALI VOWEL SIGN VOCALIC RR
#define UC_MACRO_NAME_9C7 0x09C7 // ে BENGALI VOWEL SIGN E
#define UC_MACRO_NAME_9C8 0x09C8 // ৈ BENGALI VOWEL SIGN AI
#define UC_MACRO_NAME_9CB 0x09CB // ো BENGALI VOWEL SIGN O
#define UC_MACRO_NAME_9CC 0x09CC // ৌ BENGALI VOWEL SIGN AU
#define UC_MACRO_NAME_9CD 0x09CD // ্ BENGALI SIGN VIRAMA
#define UC_MACRO_NAME_9CE 0x09CE // ৎ BENGALI LETTER KHANDA TA
#define UC_MACRO_NAME_9D7 0x09D7 // ৗ BENGALI AU LENGTH MARK
#define UC_MACRO_NAME_9DC 0x09DC // ড় BENGALI LETTER RRA
#define UC_MACRO_NAME_9DD 0x09DD // ঢ় BENGALI LETTER RHA
#define UC_MACRO_NAME_9DF 0x09DF // য় BENGALI LETTER YYA
#define UC_MACRO_NAME_9E0 0x09E0 // ৠ BENGALI LETTER VOCALIC RR
#define UC_MACRO_NAME_9E1 0x09E1 // ৡ BENGALI LETTER VOCALIC LL
#define UC_MACRO_NAME_9E2 0x09E2 // ৢ BENGALI VOWEL SIGN VOCALIC L
#define UC_MACRO_NAME_9E3 0x09E3 // ৣ BENGALI VOWEL SIGN VOCALIC LL
#define UC_MACRO_NAME_9E6 0x09E6 // ০ BENGALI DIGIT ZERO
#define UC_MACRO_NAME_9E7 0x09E7 // ১ BENGALI DIGIT ONE
#define UC_MACRO_NAME_9E8 0x09E8 // ২ BENGALI DIGIT TWO
#define UC_MACRO_NAME_9E9 0x09E9 // ৩ BENGALI DIGIT THREE
#define UC_MACRO_NAME_9EA 0x09EA // ৪ BENGALI DIGIT FOUR
#define UC_MACRO_NAME_9EB 0x09EB // ৫ BENGALI DIGIT FIVE
#define UC_MACRO_NAME_9EC 0x09EC // ৬ BENGALI DIGIT SIX
#define UC_MACRO_NAME_9ED 0x09ED // ৭ BENGALI DIGIT SEVEN
#define UC_MACRO_NAME_9EE 0x09EE // ৮ BENGALI DIGIT EIGHT
#define UC_MACRO_NAME_9EF 0x09EF // ৯ BENGALI DIGIT NINE
#define UC_MACRO_NAME_9F0 0x09F0 // ৰ BENGALI LETTER RA WITH MIDDLE DIAGONAL
#define UC_MACRO_NAME_9F1 0x09F1 // ৱ BENGALI LETTER RA WITH LOWER DIAGONAL
#define UC_MACRO_NAME_9F2 0x09F2 // ৲ BENGALI RUPEE MARK
#define UC_MACRO_NAME_9F3 0x09F3 // ৳ BENGALI RUPEE SIGN
#define UC_MACRO_NAME_9F4 0x09F4 // ৴ BENGALI CURRENCY NUMERATOR ONE
#define UC_MACRO_NAME_9F5 0x09F5 // ৵ BENGALI CURRENCY NUMERATOR TWO
#define UC_MACRO_NAME_9F6 0x09F6 // ৶ BENGALI CURRENCY NUMERATOR THREE
#define UC_MACRO_NAME_9F7 0x09F7 // ৷ BENGALI CURRENCY NUMERATOR FOUR
#define UC_MACRO_NAME_9F8 0x09F8 // ৸ BENGALI CURRENCY NUMERATOR ONE LESS THAN THE DENOMINATOR
#define UC_MACRO_NAME_9F9 0x09F9 // ৹ BENGALI CURRENCY DENOMINATOR SIXTEEN
#define UC_MACRO_NAME_9FA 0x09FA // ৺ BENGALI ISSHAR
#define UC_MACRO_NAME_9FB 0x09FB // ৻ BENGALI GANDA MARK
#define UC_MACRO_NAME_9FC 0x09FC // ৼ BENGALI LETTER VEDIC ANUSVARA
#define UC_MACRO_NAME_9FD 0x09FD // ৽ BENGALI ABBREVIATION SIGN
#define UC_MACRO_NAME_9FE 0x09FE // ৾ BENGALI SANDHI MARK


#endif // UC_H_BENGALI
