/*
 * Unicode Block: Byzantine Musical Symbols
 * Range: U+1D000..U+1D0FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Byzantine Musical Symbols is a Unicode block containing characters for
 * representing Byzantine music in ekphonetic notation .
 *
 */
#ifndef UC_H_BYZANTINE_MUSICAL_SYMBOLS
#define UC_H_BYZANTINE_MUSICAL_SYMBOLS

#define UC_MACRO_NAME_1D000 0x1D000 // 𝀀 BYZANTINE MUSICAL SYMBOL PSILI
#define UC_MACRO_NAME_1D001 0x1D001 // 𝀁 BYZANTINE MUSICAL SYMBOL DASEIA
#define UC_MACRO_NAME_1D002 0x1D002 // 𝀂 BYZANTINE MUSICAL SYMBOL PERISPOMENI
#define UC_MACRO_NAME_1D003 0x1D003 // 𝀃 BYZANTINE MUSICAL SYMBOL OXEIA EKFONITIKON
#define UC_MACRO_NAME_1D004 0x1D004 // 𝀄 BYZANTINE MUSICAL SYMBOL OXEIA DIPLI
#define UC_MACRO_NAME_1D005 0x1D005 // 𝀅 BYZANTINE MUSICAL SYMBOL VAREIA EKFONITIKON
#define UC_MACRO_NAME_1D006 0x1D006 // 𝀆 BYZANTINE MUSICAL SYMBOL VAREIA DIPLI
#define UC_MACRO_NAME_1D007 0x1D007 // 𝀇 BYZANTINE MUSICAL SYMBOL KATHISTI
#define UC_MACRO_NAME_1D008 0x1D008 // 𝀈 BYZANTINE MUSICAL SYMBOL SYRMATIKI
#define UC_MACRO_NAME_1D009 0x1D009 // 𝀉 BYZANTINE MUSICAL SYMBOL PARAKLITIKI
#define UC_MACRO_NAME_1D00A 0x1D00A // 𝀊 BYZANTINE MUSICAL SYMBOL YPOKRISIS
#define UC_MACRO_NAME_1D00B 0x1D00B // 𝀋 BYZANTINE MUSICAL SYMBOL YPOKRISIS DIPLI
#define UC_MACRO_NAME_1D00C 0x1D00C // 𝀌 BYZANTINE MUSICAL SYMBOL KREMASTI
#define UC_MACRO_NAME_1D00D 0x1D00D // 𝀍 BYZANTINE MUSICAL SYMBOL APESO EKFONITIKON
#define UC_MACRO_NAME_1D00E 0x1D00E // 𝀎 BYZANTINE MUSICAL SYMBOL EXO EKFONITIKON
#define UC_MACRO_NAME_1D00F 0x1D00F // 𝀏 BYZANTINE MUSICAL SYMBOL TELEIA
#define UC_MACRO_NAME_1D010 0x1D010 // 𝀐 BYZANTINE MUSICAL SYMBOL KENTIMATA
#define UC_MACRO_NAME_1D011 0x1D011 // 𝀑 BYZANTINE MUSICAL SYMBOL APOSTROFOS
#define UC_MACRO_NAME_1D012 0x1D012 // 𝀒 BYZANTINE MUSICAL SYMBOL APOSTROFOS DIPLI
#define UC_MACRO_NAME_1D013 0x1D013 // 𝀓 BYZANTINE MUSICAL SYMBOL SYNEVMA
#define UC_MACRO_NAME_1D014 0x1D014 // 𝀔 BYZANTINE MUSICAL SYMBOL THITA
#define UC_MACRO_NAME_1D015 0x1D015 // 𝀕 BYZANTINE MUSICAL SYMBOL OLIGON ARCHAION
#define UC_MACRO_NAME_1D016 0x1D016 // 𝀖 BYZANTINE MUSICAL SYMBOL GORGON ARCHAION
#define UC_MACRO_NAME_1D017 0x1D017 // 𝀗 BYZANTINE MUSICAL SYMBOL PSILON
#define UC_MACRO_NAME_1D018 0x1D018 // 𝀘 BYZANTINE MUSICAL SYMBOL CHAMILON
#define UC_MACRO_NAME_1D019 0x1D019 // 𝀙 BYZANTINE MUSICAL SYMBOL VATHY
#define UC_MACRO_NAME_1D01A 0x1D01A // 𝀚 BYZANTINE MUSICAL SYMBOL ISON ARCHAION
#define UC_MACRO_NAME_1D01B 0x1D01B // 𝀛 BYZANTINE MUSICAL SYMBOL KENTIMA ARCHAION
#define UC_MACRO_NAME_1D01C 0x1D01C // 𝀜 BYZANTINE MUSICAL SYMBOL KENTIMATA ARCHAION
#define UC_MACRO_NAME_1D01D 0x1D01D // 𝀝 BYZANTINE MUSICAL SYMBOL SAXIMATA
#define UC_MACRO_NAME_1D01E 0x1D01E // 𝀞 BYZANTINE MUSICAL SYMBOL PARICHON
#define UC_MACRO_NAME_1D01F 0x1D01F // 𝀟 BYZANTINE MUSICAL SYMBOL STAVROS APODEXIA
#define UC_MACRO_NAME_1D020 0x1D020 // 𝀠 BYZANTINE MUSICAL SYMBOL OXEIAI ARCHAION
#define UC_MACRO_NAME_1D021 0x1D021 // 𝀡 BYZANTINE MUSICAL SYMBOL VAREIAI ARCHAION
#define UC_MACRO_NAME_1D022 0x1D022 // 𝀢 BYZANTINE MUSICAL SYMBOL APODERMA ARCHAION
#define UC_MACRO_NAME_1D023 0x1D023 // 𝀣 BYZANTINE MUSICAL SYMBOL APOTHEMA
#define UC_MACRO_NAME_1D024 0x1D024 // 𝀤 BYZANTINE MUSICAL SYMBOL KLASMA
#define UC_MACRO_NAME_1D025 0x1D025 // 𝀥 BYZANTINE MUSICAL SYMBOL REVMA
#define UC_MACRO_NAME_1D026 0x1D026 // 𝀦 BYZANTINE MUSICAL SYMBOL PIASMA ARCHAION
#define UC_MACRO_NAME_1D027 0x1D027 // 𝀧 BYZANTINE MUSICAL SYMBOL TINAGMA
#define UC_MACRO_NAME_1D028 0x1D028 // 𝀨 BYZANTINE MUSICAL SYMBOL ANATRICHISMA
#define UC_MACRO_NAME_1D029 0x1D029 // 𝀩 BYZANTINE MUSICAL SYMBOL SEISMA
#define UC_MACRO_NAME_1D02A 0x1D02A // 𝀪 BYZANTINE MUSICAL SYMBOL SYNAGMA ARCHAION
#define UC_MACRO_NAME_1D02B 0x1D02B // 𝀫 BYZANTINE MUSICAL SYMBOL SYNAGMA META STAVROU
#define UC_MACRO_NAME_1D02C 0x1D02C // 𝀬 BYZANTINE MUSICAL SYMBOL OYRANISMA ARCHAION
#define UC_MACRO_NAME_1D02D 0x1D02D // 𝀭 BYZANTINE MUSICAL SYMBOL THEMA
#define UC_MACRO_NAME_1D02E 0x1D02E // 𝀮 BYZANTINE MUSICAL SYMBOL LEMOI
#define UC_MACRO_NAME_1D02F 0x1D02F // 𝀯 BYZANTINE MUSICAL SYMBOL DYO
#define UC_MACRO_NAME_1D030 0x1D030 // 𝀰 BYZANTINE MUSICAL SYMBOL TRIA
#define UC_MACRO_NAME_1D031 0x1D031 // 𝀱 BYZANTINE MUSICAL SYMBOL TESSERA
#define UC_MACRO_NAME_1D032 0x1D032 // 𝀲 BYZANTINE MUSICAL SYMBOL KRATIMATA
#define UC_MACRO_NAME_1D033 0x1D033 // 𝀳 BYZANTINE MUSICAL SYMBOL APESO EXO NEO
#define UC_MACRO_NAME_1D034 0x1D034 // 𝀴 BYZANTINE MUSICAL SYMBOL FTHORA ARCHAION
#define UC_MACRO_NAME_1D035 0x1D035 // 𝀵 BYZANTINE MUSICAL SYMBOL IMIFTHORA
#define UC_MACRO_NAME_1D036 0x1D036 // 𝀶 BYZANTINE MUSICAL SYMBOL TROMIKON ARCHAION
#define UC_MACRO_NAME_1D037 0x1D037 // 𝀷 BYZANTINE MUSICAL SYMBOL KATAVA TROMIKON
#define UC_MACRO_NAME_1D038 0x1D038 // 𝀸 BYZANTINE MUSICAL SYMBOL PELASTON
#define UC_MACRO_NAME_1D039 0x1D039 // 𝀹 BYZANTINE MUSICAL SYMBOL PSIFISTON
#define UC_MACRO_NAME_1D03A 0x1D03A // 𝀺 BYZANTINE MUSICAL SYMBOL KONTEVMA
#define UC_MACRO_NAME_1D03B 0x1D03B // 𝀻 BYZANTINE MUSICAL SYMBOL CHOREVMA ARCHAION
#define UC_MACRO_NAME_1D03C 0x1D03C // 𝀼 BYZANTINE MUSICAL SYMBOL RAPISMA
#define UC_MACRO_NAME_1D03D 0x1D03D // 𝀽 BYZANTINE MUSICAL SYMBOL PARAKALESMA ARCHAION
#define UC_MACRO_NAME_1D03E 0x1D03E // 𝀾 BYZANTINE MUSICAL SYMBOL PARAKLITIKI ARCHAION
#define UC_MACRO_NAME_1D03F 0x1D03F // 𝀿 BYZANTINE MUSICAL SYMBOL ICHADIN
#define UC_MACRO_NAME_1D040 0x1D040 // 𝁀 BYZANTINE MUSICAL SYMBOL NANA
#define UC_MACRO_NAME_1D041 0x1D041 // 𝁁 BYZANTINE MUSICAL SYMBOL PETASMA
#define UC_MACRO_NAME_1D042 0x1D042 // 𝁂 BYZANTINE MUSICAL SYMBOL KONTEVMA ALLO
#define UC_MACRO_NAME_1D043 0x1D043 // 𝁃 BYZANTINE MUSICAL SYMBOL TROMIKON ALLO
#define UC_MACRO_NAME_1D044 0x1D044 // 𝁄 BYZANTINE MUSICAL SYMBOL STRAGGISMATA
#define UC_MACRO_NAME_1D045 0x1D045 // 𝁅 BYZANTINE MUSICAL SYMBOL GRONTHISMATA
#define UC_MACRO_NAME_1D046 0x1D046 // 𝁆 BYZANTINE MUSICAL SYMBOL ISON NEO
#define UC_MACRO_NAME_1D047 0x1D047 // 𝁇 BYZANTINE MUSICAL SYMBOL OLIGON NEO
#define UC_MACRO_NAME_1D048 0x1D048 // 𝁈 BYZANTINE MUSICAL SYMBOL OXEIA NEO
#define UC_MACRO_NAME_1D049 0x1D049 // 𝁉 BYZANTINE MUSICAL SYMBOL PETASTI
#define UC_MACRO_NAME_1D04A 0x1D04A // 𝁊 BYZANTINE MUSICAL SYMBOL KOUFISMA
#define UC_MACRO_NAME_1D04B 0x1D04B // 𝁋 BYZANTINE MUSICAL SYMBOL PETASTOKOUFISMA
#define UC_MACRO_NAME_1D04C 0x1D04C // 𝁌 BYZANTINE MUSICAL SYMBOL KRATIMOKOUFISMA
#define UC_MACRO_NAME_1D04D 0x1D04D // 𝁍 BYZANTINE MUSICAL SYMBOL PELASTON NEO
#define UC_MACRO_NAME_1D04E 0x1D04E // 𝁎 BYZANTINE MUSICAL SYMBOL KENTIMATA NEO ANO
#define UC_MACRO_NAME_1D04F 0x1D04F // 𝁏 BYZANTINE MUSICAL SYMBOL KENTIMA NEO ANO
#define UC_MACRO_NAME_1D050 0x1D050 // 𝁐 BYZANTINE MUSICAL SYMBOL YPSILI
#define UC_MACRO_NAME_1D051 0x1D051 // 𝁑 BYZANTINE MUSICAL SYMBOL APOSTROFOS NEO
#define UC_MACRO_NAME_1D052 0x1D052 // 𝁒 BYZANTINE MUSICAL SYMBOL APOSTROFOI SYNDESMOS NEO
#define UC_MACRO_NAME_1D053 0x1D053 // 𝁓 BYZANTINE MUSICAL SYMBOL YPORROI
#define UC_MACRO_NAME_1D054 0x1D054 // 𝁔 BYZANTINE MUSICAL SYMBOL KRATIMOYPORROON
#define UC_MACRO_NAME_1D055 0x1D055 // 𝁕 BYZANTINE MUSICAL SYMBOL ELAFRON
#define UC_MACRO_NAME_1D056 0x1D056 // 𝁖 BYZANTINE MUSICAL SYMBOL CHAMILI
#define UC_MACRO_NAME_1D057 0x1D057 // 𝁗 BYZANTINE MUSICAL SYMBOL MIKRON ISON
#define UC_MACRO_NAME_1D058 0x1D058 // 𝁘 BYZANTINE MUSICAL SYMBOL VAREIA NEO
#define UC_MACRO_NAME_1D059 0x1D059 // 𝁙 BYZANTINE MUSICAL SYMBOL PIASMA NEO
#define UC_MACRO_NAME_1D05A 0x1D05A // 𝁚 BYZANTINE MUSICAL SYMBOL PSIFISTON NEO
#define UC_MACRO_NAME_1D05B 0x1D05B // 𝁛 BYZANTINE MUSICAL SYMBOL OMALON
#define UC_MACRO_NAME_1D05C 0x1D05C // 𝁜 BYZANTINE MUSICAL SYMBOL ANTIKENOMA
#define UC_MACRO_NAME_1D05D 0x1D05D // 𝁝 BYZANTINE MUSICAL SYMBOL LYGISMA
#define UC_MACRO_NAME_1D05E 0x1D05E // 𝁞 BYZANTINE MUSICAL SYMBOL PARAKLITIKI NEO
#define UC_MACRO_NAME_1D05F 0x1D05F // 𝁟 BYZANTINE MUSICAL SYMBOL PARAKALESMA NEO
#define UC_MACRO_NAME_1D060 0x1D060 // 𝁠 BYZANTINE MUSICAL SYMBOL ETERON PARAKALESMA
#define UC_MACRO_NAME_1D061 0x1D061 // 𝁡 BYZANTINE MUSICAL SYMBOL KYLISMA
#define UC_MACRO_NAME_1D062 0x1D062 // 𝁢 BYZANTINE MUSICAL SYMBOL ANTIKENOKYLISMA
#define UC_MACRO_NAME_1D063 0x1D063 // 𝁣 BYZANTINE MUSICAL SYMBOL TROMIKON NEO
#define UC_MACRO_NAME_1D064 0x1D064 // 𝁤 BYZANTINE MUSICAL SYMBOL EKSTREPTON
#define UC_MACRO_NAME_1D065 0x1D065 // 𝁥 BYZANTINE MUSICAL SYMBOL SYNAGMA NEO
#define UC_MACRO_NAME_1D066 0x1D066 // 𝁦 BYZANTINE MUSICAL SYMBOL SYRMA
#define UC_MACRO_NAME_1D067 0x1D067 // 𝁧 BYZANTINE MUSICAL SYMBOL CHOREVMA NEO
#define UC_MACRO_NAME_1D068 0x1D068 // 𝁨 BYZANTINE MUSICAL SYMBOL EPEGERMA
#define UC_MACRO_NAME_1D069 0x1D069 // 𝁩 BYZANTINE MUSICAL SYMBOL SEISMA NEO
#define UC_MACRO_NAME_1D06A 0x1D06A // 𝁪 BYZANTINE MUSICAL SYMBOL XIRON KLASMA
#define UC_MACRO_NAME_1D06B 0x1D06B // 𝁫 BYZANTINE MUSICAL SYMBOL TROMIKOPSIFISTON
#define UC_MACRO_NAME_1D06C 0x1D06C // 𝁬 BYZANTINE MUSICAL SYMBOL PSIFISTOLYGISMA
#define UC_MACRO_NAME_1D06D 0x1D06D // 𝁭 BYZANTINE MUSICAL SYMBOL TROMIKOLYGISMA
#define UC_MACRO_NAME_1D06E 0x1D06E // 𝁮 BYZANTINE MUSICAL SYMBOL TROMIKOPARAKALESMA
#define UC_MACRO_NAME_1D06F 0x1D06F // 𝁯 BYZANTINE MUSICAL SYMBOL PSIFISTOPARAKALESMA
#define UC_MACRO_NAME_1D070 0x1D070 // 𝁰 BYZANTINE MUSICAL SYMBOL TROMIKOSYNAGMA
#define UC_MACRO_NAME_1D071 0x1D071 // 𝁱 BYZANTINE MUSICAL SYMBOL PSIFISTOSYNAGMA
#define UC_MACRO_NAME_1D072 0x1D072 // 𝁲 BYZANTINE MUSICAL SYMBOL GORGOSYNTHETON
#define UC_MACRO_NAME_1D073 0x1D073 // 𝁳 BYZANTINE MUSICAL SYMBOL ARGOSYNTHETON
#define UC_MACRO_NAME_1D074 0x1D074 // 𝁴 BYZANTINE MUSICAL SYMBOL ETERON ARGOSYNTHETON
#define UC_MACRO_NAME_1D075 0x1D075 // 𝁵 BYZANTINE MUSICAL SYMBOL OYRANISMA NEO
#define UC_MACRO_NAME_1D076 0x1D076 // 𝁶 BYZANTINE MUSICAL SYMBOL THEMATISMOS ESO
#define UC_MACRO_NAME_1D077 0x1D077 // 𝁷 BYZANTINE MUSICAL SYMBOL THEMATISMOS EXO
#define UC_MACRO_NAME_1D078 0x1D078 // 𝁸 BYZANTINE MUSICAL SYMBOL THEMA APLOUN
#define UC_MACRO_NAME_1D079 0x1D079 // 𝁹 BYZANTINE MUSICAL SYMBOL THES KAI APOTHES
#define UC_MACRO_NAME_1D07A 0x1D07A // 𝁺 BYZANTINE MUSICAL SYMBOL KATAVASMA
#define UC_MACRO_NAME_1D07B 0x1D07B // 𝁻 BYZANTINE MUSICAL SYMBOL ENDOFONON
#define UC_MACRO_NAME_1D07C 0x1D07C // 𝁼 BYZANTINE MUSICAL SYMBOL YFEN KATO
#define UC_MACRO_NAME_1D07D 0x1D07D // 𝁽 BYZANTINE MUSICAL SYMBOL YFEN ANO
#define UC_MACRO_NAME_1D07E 0x1D07E // 𝁾 BYZANTINE MUSICAL SYMBOL STAVROS
#define UC_MACRO_NAME_1D07F 0x1D07F // 𝁿 BYZANTINE MUSICAL SYMBOL KLASMA ANO
#define UC_MACRO_NAME_1D080 0x1D080 // 𝂀 BYZANTINE MUSICAL SYMBOL DIPLI ARCHAION
#define UC_MACRO_NAME_1D081 0x1D081 // 𝂁 BYZANTINE MUSICAL SYMBOL KRATIMA ARCHAION
#define UC_MACRO_NAME_1D082 0x1D082 // 𝂂 BYZANTINE MUSICAL SYMBOL KRATIMA ALLO
#define UC_MACRO_NAME_1D083 0x1D083 // 𝂃 BYZANTINE MUSICAL SYMBOL KRATIMA NEO
#define UC_MACRO_NAME_1D084 0x1D084 // 𝂄 BYZANTINE MUSICAL SYMBOL APODERMA NEO
#define UC_MACRO_NAME_1D085 0x1D085 // 𝂅 BYZANTINE MUSICAL SYMBOL APLI
#define UC_MACRO_NAME_1D086 0x1D086 // 𝂆 BYZANTINE MUSICAL SYMBOL DIPLI
#define UC_MACRO_NAME_1D087 0x1D087 // 𝂇 BYZANTINE MUSICAL SYMBOL TRIPLI
#define UC_MACRO_NAME_1D088 0x1D088 // 𝂈 BYZANTINE MUSICAL SYMBOL TETRAPLI
#define UC_MACRO_NAME_1D089 0x1D089 // 𝂉 BYZANTINE MUSICAL SYMBOL KORONIS
#define UC_MACRO_NAME_1D08A 0x1D08A // 𝂊 BYZANTINE MUSICAL SYMBOL LEIMMA ENOS CHRONOU
#define UC_MACRO_NAME_1D08B 0x1D08B // 𝂋 BYZANTINE MUSICAL SYMBOL LEIMMA DYO CHRONON
#define UC_MACRO_NAME_1D08C 0x1D08C // 𝂌 BYZANTINE MUSICAL SYMBOL LEIMMA TRION CHRONON
#define UC_MACRO_NAME_1D08D 0x1D08D // 𝂍 BYZANTINE MUSICAL SYMBOL LEIMMA TESSARON CHRONON
#define UC_MACRO_NAME_1D08E 0x1D08E // 𝂎 BYZANTINE MUSICAL SYMBOL LEIMMA IMISEOS CHRONOU
#define UC_MACRO_NAME_1D08F 0x1D08F // 𝂏 BYZANTINE MUSICAL SYMBOL GORGON NEO ANO
#define UC_MACRO_NAME_1D090 0x1D090 // 𝂐 BYZANTINE MUSICAL SYMBOL GORGON PARESTIGMENON ARISTERA
#define UC_MACRO_NAME_1D091 0x1D091 // 𝂑 BYZANTINE MUSICAL SYMBOL GORGON PARESTIGMENON DEXIA
#define UC_MACRO_NAME_1D092 0x1D092 // 𝂒 BYZANTINE MUSICAL SYMBOL DIGORGON
#define UC_MACRO_NAME_1D093 0x1D093 // 𝂓 BYZANTINE MUSICAL SYMBOL DIGORGON PARESTIGMENON ARISTERA KATO
#define UC_MACRO_NAME_1D094 0x1D094 // 𝂔 BYZANTINE MUSICAL SYMBOL DIGORGON PARESTIGMENON ARISTERA ANO
#define UC_MACRO_NAME_1D095 0x1D095 // 𝂕 BYZANTINE MUSICAL SYMBOL DIGORGON PARESTIGMENON DEXIA
#define UC_MACRO_NAME_1D096 0x1D096 // 𝂖 BYZANTINE MUSICAL SYMBOL TRIGORGON
#define UC_MACRO_NAME_1D097 0x1D097 // 𝂗 BYZANTINE MUSICAL SYMBOL ARGON
#define UC_MACRO_NAME_1D098 0x1D098 // 𝂘 BYZANTINE MUSICAL SYMBOL IMIDIARGON
#define UC_MACRO_NAME_1D099 0x1D099 // 𝂙 BYZANTINE MUSICAL SYMBOL DIARGON
#define UC_MACRO_NAME_1D09A 0x1D09A // 𝂚 BYZANTINE MUSICAL SYMBOL AGOGI POLI ARGI
#define UC_MACRO_NAME_1D09B 0x1D09B // 𝂛 BYZANTINE MUSICAL SYMBOL AGOGI ARGOTERI
#define UC_MACRO_NAME_1D09C 0x1D09C // 𝂜 BYZANTINE MUSICAL SYMBOL AGOGI ARGI
#define UC_MACRO_NAME_1D09D 0x1D09D // 𝂝 BYZANTINE MUSICAL SYMBOL AGOGI METRIA
#define UC_MACRO_NAME_1D09E 0x1D09E // 𝂞 BYZANTINE MUSICAL SYMBOL AGOGI MESI
#define UC_MACRO_NAME_1D09F 0x1D09F // 𝂟 BYZANTINE MUSICAL SYMBOL AGOGI GORGI
#define UC_MACRO_NAME_1D0A0 0x1D0A0 // 𝂠 BYZANTINE MUSICAL SYMBOL AGOGI GORGOTERI
#define UC_MACRO_NAME_1D0A1 0x1D0A1 // 𝂡 BYZANTINE MUSICAL SYMBOL AGOGI POLI GORGI
#define UC_MACRO_NAME_1D0A2 0x1D0A2 // 𝂢 BYZANTINE MUSICAL SYMBOL MARTYRIA PROTOS ICHOS
#define UC_MACRO_NAME_1D0A3 0x1D0A3 // 𝂣 BYZANTINE MUSICAL SYMBOL MARTYRIA ALLI PROTOS ICHOS
#define UC_MACRO_NAME_1D0A4 0x1D0A4 // 𝂤 BYZANTINE MUSICAL SYMBOL MARTYRIA DEYTEROS ICHOS
#define UC_MACRO_NAME_1D0A5 0x1D0A5 // 𝂥 BYZANTINE MUSICAL SYMBOL MARTYRIA ALLI DEYTEROS ICHOS
#define UC_MACRO_NAME_1D0A6 0x1D0A6 // 𝂦 BYZANTINE MUSICAL SYMBOL MARTYRIA TRITOS ICHOS
#define UC_MACRO_NAME_1D0A7 0x1D0A7 // 𝂧 BYZANTINE MUSICAL SYMBOL MARTYRIA TRIFONIAS
#define UC_MACRO_NAME_1D0A8 0x1D0A8 // 𝂨 BYZANTINE MUSICAL SYMBOL MARTYRIA TETARTOS ICHOS
#define UC_MACRO_NAME_1D0A9 0x1D0A9 // 𝂩 BYZANTINE MUSICAL SYMBOL MARTYRIA TETARTOS LEGETOS ICHOS
#define UC_MACRO_NAME_1D0AA 0x1D0AA // 𝂪 BYZANTINE MUSICAL SYMBOL MARTYRIA LEGETOS ICHOS
#define UC_MACRO_NAME_1D0AB 0x1D0AB // 𝂫 BYZANTINE MUSICAL SYMBOL MARTYRIA PLAGIOS ICHOS
#define UC_MACRO_NAME_1D0AC 0x1D0AC // 𝂬 BYZANTINE MUSICAL SYMBOL ISAKIA TELOUS ICHIMATOS
#define UC_MACRO_NAME_1D0AD 0x1D0AD // 𝂭 BYZANTINE MUSICAL SYMBOL APOSTROFOI TELOUS ICHIMATOS
#define UC_MACRO_NAME_1D0AE 0x1D0AE // 𝂮 BYZANTINE MUSICAL SYMBOL FANEROSIS TETRAFONIAS
#define UC_MACRO_NAME_1D0AF 0x1D0AF // 𝂯 BYZANTINE MUSICAL SYMBOL FANEROSIS MONOFONIAS
#define UC_MACRO_NAME_1D0B0 0x1D0B0 // 𝂰 BYZANTINE MUSICAL SYMBOL FANEROSIS DIFONIAS
#define UC_MACRO_NAME_1D0B1 0x1D0B1 // 𝂱 BYZANTINE MUSICAL SYMBOL MARTYRIA VARYS ICHOS
#define UC_MACRO_NAME_1D0B2 0x1D0B2 // 𝂲 BYZANTINE MUSICAL SYMBOL MARTYRIA PROTOVARYS ICHOS
#define UC_MACRO_NAME_1D0B3 0x1D0B3 // 𝂳 BYZANTINE MUSICAL SYMBOL MARTYRIA PLAGIOS TETARTOS ICHOS
#define UC_MACRO_NAME_1D0B4 0x1D0B4 // 𝂴 BYZANTINE MUSICAL SYMBOL GORTHMIKON N APLOUN
#define UC_MACRO_NAME_1D0B5 0x1D0B5 // 𝂵 BYZANTINE MUSICAL SYMBOL GORTHMIKON N DIPLOUN
#define UC_MACRO_NAME_1D0B6 0x1D0B6 // 𝂶 BYZANTINE MUSICAL SYMBOL ENARXIS KAI FTHORA VOU
#define UC_MACRO_NAME_1D0B7 0x1D0B7 // 𝂷 BYZANTINE MUSICAL SYMBOL IMIFONON
#define UC_MACRO_NAME_1D0B8 0x1D0B8 // 𝂸 BYZANTINE MUSICAL SYMBOL IMIFTHORON
#define UC_MACRO_NAME_1D0B9 0x1D0B9 // 𝂹 BYZANTINE MUSICAL SYMBOL FTHORA ARCHAION DEYTEROU ICHOU
#define UC_MACRO_NAME_1D0BA 0x1D0BA // 𝂺 BYZANTINE MUSICAL SYMBOL FTHORA DIATONIKI PA
#define UC_MACRO_NAME_1D0BB 0x1D0BB // 𝂻 BYZANTINE MUSICAL SYMBOL FTHORA DIATONIKI NANA
#define UC_MACRO_NAME_1D0BC 0x1D0BC // 𝂼 BYZANTINE MUSICAL SYMBOL FTHORA NAOS ICHOS
#define UC_MACRO_NAME_1D0BD 0x1D0BD // 𝂽 BYZANTINE MUSICAL SYMBOL FTHORA DIATONIKI DI
#define UC_MACRO_NAME_1D0BE 0x1D0BE // 𝂾 BYZANTINE MUSICAL SYMBOL FTHORA SKLIRON DIATONON DI
#define UC_MACRO_NAME_1D0BF 0x1D0BF // 𝂿 BYZANTINE MUSICAL SYMBOL FTHORA DIATONIKI KE
#define UC_MACRO_NAME_1D0C0 0x1D0C0 // 𝃀 BYZANTINE MUSICAL SYMBOL FTHORA DIATONIKI ZO
#define UC_MACRO_NAME_1D0C1 0x1D0C1 // 𝃁 BYZANTINE MUSICAL SYMBOL FTHORA DIATONIKI NI KATO
#define UC_MACRO_NAME_1D0C2 0x1D0C2 // 𝃂 BYZANTINE MUSICAL SYMBOL FTHORA DIATONIKI NI ANO
#define UC_MACRO_NAME_1D0C3 0x1D0C3 // 𝃃 BYZANTINE MUSICAL SYMBOL FTHORA MALAKON CHROMA DIFONIAS
#define UC_MACRO_NAME_1D0C4 0x1D0C4 // 𝃄 BYZANTINE MUSICAL SYMBOL FTHORA MALAKON CHROMA MONOFONIAS
#define UC_MACRO_NAME_1D0C5 0x1D0C5 // 𝃅 BYZANTINE MUSICAL SYMBOL FHTORA SKLIRON CHROMA VASIS
#define UC_MACRO_NAME_1D0C6 0x1D0C6 // 𝃆 BYZANTINE MUSICAL SYMBOL FTHORA SKLIRON CHROMA SYNAFI
#define UC_MACRO_NAME_1D0C7 0x1D0C7 // 𝃇 BYZANTINE MUSICAL SYMBOL FTHORA NENANO
#define UC_MACRO_NAME_1D0C8 0x1D0C8 // 𝃈 BYZANTINE MUSICAL SYMBOL CHROA ZYGOS
#define UC_MACRO_NAME_1D0C9 0x1D0C9 // 𝃉 BYZANTINE MUSICAL SYMBOL CHROA KLITON
#define UC_MACRO_NAME_1D0CA 0x1D0CA // 𝃊 BYZANTINE MUSICAL SYMBOL CHROA SPATHI
#define UC_MACRO_NAME_1D0CB 0x1D0CB // 𝃋 BYZANTINE MUSICAL SYMBOL FTHORA I YFESIS TETARTIMORION
#define UC_MACRO_NAME_1D0CC 0x1D0CC // 𝃌 BYZANTINE MUSICAL SYMBOL FTHORA ENARMONIOS ANTIFONIA
#define UC_MACRO_NAME_1D0CD 0x1D0CD // 𝃍 BYZANTINE MUSICAL SYMBOL YFESIS TRITIMORION
#define UC_MACRO_NAME_1D0CE 0x1D0CE // 𝃎 BYZANTINE MUSICAL SYMBOL DIESIS TRITIMORION
#define UC_MACRO_NAME_1D0CF 0x1D0CF // 𝃏 BYZANTINE MUSICAL SYMBOL DIESIS TETARTIMORION
#define UC_MACRO_NAME_1D0D0 0x1D0D0 // 𝃐 BYZANTINE MUSICAL SYMBOL DIESIS APLI DYO DODEKATA
#define UC_MACRO_NAME_1D0D1 0x1D0D1 // 𝃑 BYZANTINE MUSICAL SYMBOL DIESIS MONOGRAMMOS TESSERA DODEKATA
#define UC_MACRO_NAME_1D0D2 0x1D0D2 // 𝃒 BYZANTINE MUSICAL SYMBOL DIESIS DIGRAMMOS EX DODEKATA
#define UC_MACRO_NAME_1D0D3 0x1D0D3 // 𝃓 BYZANTINE MUSICAL SYMBOL DIESIS TRIGRAMMOS OKTO DODEKATA
#define UC_MACRO_NAME_1D0D4 0x1D0D4 // 𝃔 BYZANTINE MUSICAL SYMBOL YFESIS APLI DYO DODEKATA
#define UC_MACRO_NAME_1D0D5 0x1D0D5 // 𝃕 BYZANTINE MUSICAL SYMBOL YFESIS MONOGRAMMOS TESSERA DODEKATA
#define UC_MACRO_NAME_1D0D6 0x1D0D6 // 𝃖 BYZANTINE MUSICAL SYMBOL YFESIS DIGRAMMOS EX DODEKATA
#define UC_MACRO_NAME_1D0D7 0x1D0D7 // 𝃗 BYZANTINE MUSICAL SYMBOL YFESIS TRIGRAMMOS OKTO DODEKATA
#define UC_MACRO_NAME_1D0D8 0x1D0D8 // 𝃘 BYZANTINE MUSICAL SYMBOL GENIKI DIESIS
#define UC_MACRO_NAME_1D0D9 0x1D0D9 // 𝃙 BYZANTINE MUSICAL SYMBOL GENIKI YFESIS
#define UC_MACRO_NAME_1D0DA 0x1D0DA // 𝃚 BYZANTINE MUSICAL SYMBOL DIASTOLI APLI MIKRI
#define UC_MACRO_NAME_1D0DB 0x1D0DB // 𝃛 BYZANTINE MUSICAL SYMBOL DIASTOLI APLI MEGALI
#define UC_MACRO_NAME_1D0DC 0x1D0DC // 𝃜 BYZANTINE MUSICAL SYMBOL DIASTOLI DIPLI
#define UC_MACRO_NAME_1D0DD 0x1D0DD // 𝃝 BYZANTINE MUSICAL SYMBOL DIASTOLI THESEOS
#define UC_MACRO_NAME_1D0DE 0x1D0DE // 𝃞 BYZANTINE MUSICAL SYMBOL SIMANSIS THESEOS
#define UC_MACRO_NAME_1D0DF 0x1D0DF // 𝃟 BYZANTINE MUSICAL SYMBOL SIMANSIS THESEOS DISIMOU
#define UC_MACRO_NAME_1D0E0 0x1D0E0 // 𝃠 BYZANTINE MUSICAL SYMBOL SIMANSIS THESEOS TRISIMOU
#define UC_MACRO_NAME_1D0E1 0x1D0E1 // 𝃡 BYZANTINE MUSICAL SYMBOL SIMANSIS THESEOS TETRASIMOU
#define UC_MACRO_NAME_1D0E2 0x1D0E2 // 𝃢 BYZANTINE MUSICAL SYMBOL SIMANSIS ARSEOS
#define UC_MACRO_NAME_1D0E3 0x1D0E3 // 𝃣 BYZANTINE MUSICAL SYMBOL SIMANSIS ARSEOS DISIMOU
#define UC_MACRO_NAME_1D0E4 0x1D0E4 // 𝃤 BYZANTINE MUSICAL SYMBOL SIMANSIS ARSEOS TRISIMOU
#define UC_MACRO_NAME_1D0E5 0x1D0E5 // 𝃥 BYZANTINE MUSICAL SYMBOL SIMANSIS ARSEOS TETRASIMOU
#define UC_MACRO_NAME_1D0E6 0x1D0E6 // 𝃦 BYZANTINE MUSICAL SYMBOL DIGRAMMA GG
#define UC_MACRO_NAME_1D0E7 0x1D0E7 // 𝃧 BYZANTINE MUSICAL SYMBOL DIFTOGGOS OU
#define UC_MACRO_NAME_1D0E8 0x1D0E8 // 𝃨 BYZANTINE MUSICAL SYMBOL STIGMA
#define UC_MACRO_NAME_1D0E9 0x1D0E9 // 𝃩 BYZANTINE MUSICAL SYMBOL ARKTIKO PA
#define UC_MACRO_NAME_1D0EA 0x1D0EA // 𝃪 BYZANTINE MUSICAL SYMBOL ARKTIKO VOU
#define UC_MACRO_NAME_1D0EB 0x1D0EB // 𝃫 BYZANTINE MUSICAL SYMBOL ARKTIKO GA
#define UC_MACRO_NAME_1D0EC 0x1D0EC // 𝃬 BYZANTINE MUSICAL SYMBOL ARKTIKO DI
#define UC_MACRO_NAME_1D0ED 0x1D0ED // 𝃭 BYZANTINE MUSICAL SYMBOL ARKTIKO KE
#define UC_MACRO_NAME_1D0EE 0x1D0EE // 𝃮 BYZANTINE MUSICAL SYMBOL ARKTIKO ZO
#define UC_MACRO_NAME_1D0EF 0x1D0EF // 𝃯 BYZANTINE MUSICAL SYMBOL ARKTIKO NI
#define UC_MACRO_NAME_1D0F0 0x1D0F0 // 𝃰 BYZANTINE MUSICAL SYMBOL KENTIMATA NEO MESO
#define UC_MACRO_NAME_1D0F1 0x1D0F1 // 𝃱 BYZANTINE MUSICAL SYMBOL KENTIMA NEO MESO
#define UC_MACRO_NAME_1D0F2 0x1D0F2 // 𝃲 BYZANTINE MUSICAL SYMBOL KENTIMATA NEO KATO
#define UC_MACRO_NAME_1D0F3 0x1D0F3 // 𝃳 BYZANTINE MUSICAL SYMBOL KENTIMA NEO KATO
#define UC_MACRO_NAME_1D0F4 0x1D0F4 // 𝃴 BYZANTINE MUSICAL SYMBOL KLASMA KATO
#define UC_MACRO_NAME_1D0F5 0x1D0F5 // 𝃵 BYZANTINE MUSICAL SYMBOL GORGON NEO KATO


#endif // UC_H_BYZANTINE_MUSICAL_SYMBOLS
