/*
 * Unicode Block: Batak
 * Range: U+1BC0..U+1BFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_BATAK
#define UC_H_BATAK

#define UC_MACRO_NAME_1BC0 0x1BC0 // ᯀ BATAK LETTER A
#define UC_MACRO_NAME_1BC1 0x1BC1 // ᯁ BATAK LETTER SIMALUNGUN A
#define UC_MACRO_NAME_1BC2 0x1BC2 // ᯂ BATAK LETTER HA
#define UC_MACRO_NAME_1BC3 0x1BC3 // ᯃ BATAK LETTER SIMALUNGUN HA
#define UC_MACRO_NAME_1BC4 0x1BC4 // ᯄ BATAK LETTER MANDAILING HA
#define UC_MACRO_NAME_1BC5 0x1BC5 // ᯅ BATAK LETTER BA
#define UC_MACRO_NAME_1BC6 0x1BC6 // ᯆ BATAK LETTER KARO BA
#define UC_MACRO_NAME_1BC7 0x1BC7 // ᯇ BATAK LETTER PA
#define UC_MACRO_NAME_1BC8 0x1BC8 // ᯈ BATAK LETTER SIMALUNGUN PA
#define UC_MACRO_NAME_1BC9 0x1BC9 // ᯉ BATAK LETTER NA
#define UC_MACRO_NAME_1BCA 0x1BCA // ᯊ BATAK LETTER MANDAILING NA
#define UC_MACRO_NAME_1BCB 0x1BCB // ᯋ BATAK LETTER WA
#define UC_MACRO_NAME_1BCC 0x1BCC // ᯌ BATAK LETTER SIMALUNGUN WA
#define UC_MACRO_NAME_1BCD 0x1BCD // ᯍ BATAK LETTER PAKPAK WA
#define UC_MACRO_NAME_1BCE 0x1BCE // ᯎ BATAK LETTER GA
#define UC_MACRO_NAME_1BCF 0x1BCF // ᯏ BATAK LETTER SIMALUNGUN GA
#define UC_MACRO_NAME_1BD0 0x1BD0 // ᯐ BATAK LETTER JA
#define UC_MACRO_NAME_1BD1 0x1BD1 // ᯑ BATAK LETTER DA
#define UC_MACRO_NAME_1BD2 0x1BD2 // ᯒ BATAK LETTER RA
#define UC_MACRO_NAME_1BD3 0x1BD3 // ᯓ BATAK LETTER SIMALUNGUN RA
#define UC_MACRO_NAME_1BD4 0x1BD4 // ᯔ BATAK LETTER MA
#define UC_MACRO_NAME_1BD5 0x1BD5 // ᯕ BATAK LETTER SIMALUNGUN MA
#define UC_MACRO_NAME_1BD6 0x1BD6 // ᯖ BATAK LETTER SOUTHERN TA
#define UC_MACRO_NAME_1BD7 0x1BD7 // ᯗ BATAK LETTER NORTHERN TA
#define UC_MACRO_NAME_1BD8 0x1BD8 // ᯘ BATAK LETTER SA
#define UC_MACRO_NAME_1BD9 0x1BD9 // ᯙ BATAK LETTER SIMALUNGUN SA
#define UC_MACRO_NAME_1BDA 0x1BDA // ᯚ BATAK LETTER MANDAILING SA
#define UC_MACRO_NAME_1BDB 0x1BDB // ᯛ BATAK LETTER YA
#define UC_MACRO_NAME_1BDC 0x1BDC // ᯜ BATAK LETTER SIMALUNGUN YA
#define UC_MACRO_NAME_1BDD 0x1BDD // ᯝ BATAK LETTER NGA
#define UC_MACRO_NAME_1BDE 0x1BDE // ᯞ BATAK LETTER LA
#define UC_MACRO_NAME_1BDF 0x1BDF // ᯟ BATAK LETTER SIMALUNGUN LA
#define UC_MACRO_NAME_1BE0 0x1BE0 // ᯠ BATAK LETTER NYA
#define UC_MACRO_NAME_1BE1 0x1BE1 // ᯡ BATAK LETTER CA
#define UC_MACRO_NAME_1BE2 0x1BE2 // ᯢ BATAK LETTER NDA
#define UC_MACRO_NAME_1BE3 0x1BE3 // ᯣ BATAK LETTER MBA
#define UC_MACRO_NAME_1BE4 0x1BE4 // ᯤ BATAK LETTER I
#define UC_MACRO_NAME_1BE5 0x1BE5 // ᯥ BATAK LETTER U
#define UC_MACRO_NAME_1BE6 0x1BE6 // ᯦ BATAK SIGN TOMPI
#define UC_MACRO_NAME_1BE7 0x1BE7 // ᯧ BATAK VOWEL SIGN E
#define UC_MACRO_NAME_1BE8 0x1BE8 // ᯨ BATAK VOWEL SIGN PAKPAK E
#define UC_MACRO_NAME_1BE9 0x1BE9 // ᯩ BATAK VOWEL SIGN EE
#define UC_MACRO_NAME_1BEA 0x1BEA // ᯪ BATAK VOWEL SIGN I
#define UC_MACRO_NAME_1BEB 0x1BEB // ᯫ BATAK VOWEL SIGN KARO I
#define UC_MACRO_NAME_1BEC 0x1BEC // ᯬ BATAK VOWEL SIGN O
#define UC_MACRO_NAME_1BED 0x1BED // ᯭ BATAK VOWEL SIGN KARO O
#define UC_MACRO_NAME_1BEE 0x1BEE // ᯮ BATAK VOWEL SIGN U
#define UC_MACRO_NAME_1BEF 0x1BEF // ᯯ BATAK VOWEL SIGN U FOR SIMALUNGUN SA
#define UC_MACRO_NAME_1BF0 0x1BF0 // ᯰ BATAK CONSONANT SIGN NG
#define UC_MACRO_NAME_1BF1 0x1BF1 // ᯱ BATAK CONSONANT SIGN H
#define UC_MACRO_NAME_1BF2 0x1BF2 // ᯲ BATAK PANGOLAT
#define UC_MACRO_NAME_1BF3 0x1BF3 // ᯳ BATAK PANONGONAN
#define UC_MACRO_NAME_1BFC 0x1BFC // ᯼ BATAK SYMBOL BINDU NA METEK
#define UC_MACRO_NAME_1BFD 0x1BFD // ᯽ BATAK SYMBOL BINDU PINARBORAS
#define UC_MACRO_NAME_1BFE 0x1BFE // ᯾ BATAK SYMBOL BINDU JUDUL
#define UC_MACRO_NAME_1BFF 0x1BFF // ᯿ BATAK SYMBOL BINDU PANGOLAT


#endif // UC_H_BATAK
