/*
 * Unicode Block: Beria Erfe
 * Range: U+16EA0..U+16EDF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * The Zaghawa or Beria script , Beria Giray Erfe (𖺡𖺾𖻌𖻂𖺻 𖺥𖻂𖻌𖺻𖻓 𖺣𖻌𖺿𖺾𖺾)
 * ('Zaghawa Writing Marks'), is an indigenous alphabetic script proposed
 * for the Zaghawa language (also known as Beria) of Sudan , Chad , and
 * Libya . It is one of three scripts used to write Zaghawa, alongside
 * Latin and incipiently Arabic.
 * In the 1950s, a Sudanese Zaghawa schoolteacher named Adam Tajir
 * created a script for the Zaghawa language, sometimes known as the
 * camel alphabet , deriving its glyphs from the clan brands used for
 * camels and other livestock. He copied the inventory of the Arabic
 * script , so the system was not ideal for Zaghawa.
 *
 */
#ifndef UC_H_BERIA_ERFE
#define UC_H_BERIA_ERFE

#define UC_MACRO_NAME_16EA0 0x16EA0 //  BERIA ERFE CAPITAL LETTER ARKAB
#define UC_MACRO_NAME_16EA1 0x16EA1 //  BERIA ERFE CAPITAL LETTER BASIGNA
#define UC_MACRO_NAME_16EA2 0x16EA2 //  BERIA ERFE CAPITAL LETTER DARBAI
#define UC_MACRO_NAME_16EA3 0x16EA3 //  BERIA ERFE CAPITAL LETTER EH
#define UC_MACRO_NAME_16EA4 0x16EA4 //  BERIA ERFE CAPITAL LETTER FITKO
#define UC_MACRO_NAME_16EA5 0x16EA5 //  BERIA ERFE CAPITAL LETTER GOWAY
#define UC_MACRO_NAME_16EA6 0x16EA6 //  BERIA ERFE CAPITAL LETTER HIRDEABO
#define UC_MACRO_NAME_16EA7 0x16EA7 //  BERIA ERFE CAPITAL LETTER I
#define UC_MACRO_NAME_16EA8 0x16EA8 //  BERIA ERFE CAPITAL LETTER DJAI
#define UC_MACRO_NAME_16EA9 0x16EA9 //  BERIA ERFE CAPITAL LETTER KOBO
#define UC_MACRO_NAME_16EAA 0x16EAA //  BERIA ERFE CAPITAL LETTER LAKKO
#define UC_MACRO_NAME_16EAB 0x16EAB //  BERIA ERFE CAPITAL LETTER MERI
#define UC_MACRO_NAME_16EAC 0x16EAC //  BERIA ERFE CAPITAL LETTER NINI
#define UC_MACRO_NAME_16EAD 0x16EAD //  BERIA ERFE CAPITAL LETTER GNA
#define UC_MACRO_NAME_16EAE 0x16EAE //  BERIA ERFE CAPITAL LETTER NGAY
#define UC_MACRO_NAME_16EAF 0x16EAF //  BERIA ERFE CAPITAL LETTER OI
#define UC_MACRO_NAME_16EB0 0x16EB0 //  BERIA ERFE CAPITAL LETTER PI
#define UC_MACRO_NAME_16EB1 0x16EB1 //  BERIA ERFE CAPITAL LETTER ERIGO
#define UC_MACRO_NAME_16EB2 0x16EB2 //  BERIA ERFE CAPITAL LETTER ERIGO TAMURA
#define UC_MACRO_NAME_16EB3 0x16EB3 //  BERIA ERFE CAPITAL LETTER SERI
#define UC_MACRO_NAME_16EB4 0x16EB4 //  BERIA ERFE CAPITAL LETTER SHEP
#define UC_MACRO_NAME_16EB5 0x16EB5 //  BERIA ERFE CAPITAL LETTER TATASOUE
#define UC_MACRO_NAME_16EB6 0x16EB6 //  BERIA ERFE CAPITAL LETTER UI
#define UC_MACRO_NAME_16EB7 0x16EB7 //  BERIA ERFE CAPITAL LETTER WASSE
#define UC_MACRO_NAME_16EB8 0x16EB8 //  BERIA ERFE CAPITAL LETTER AY
#define UC_MACRO_NAME_16EBB 0x16EBB //  BERIA ERFE SMALL LETTER ARKAB
#define UC_MACRO_NAME_16EBC 0x16EBC //  BERIA ERFE SMALL LETTER BASIGNA
#define UC_MACRO_NAME_16EBD 0x16EBD //  BERIA ERFE SMALL LETTER DARBAI
#define UC_MACRO_NAME_16EBE 0x16EBE //  BERIA ERFE SMALL LETTER EH
#define UC_MACRO_NAME_16EBF 0x16EBF //  BERIA ERFE SMALL LETTER FITKO
#define UC_MACRO_NAME_16EC0 0x16EC0 //  BERIA ERFE SMALL LETTER GOWAY
#define UC_MACRO_NAME_16EC1 0x16EC1 //  BERIA ERFE SMALL LETTER HIRDEABO
#define UC_MACRO_NAME_16EC2 0x16EC2 //  BERIA ERFE SMALL LETTER I
#define UC_MACRO_NAME_16EC3 0x16EC3 //  BERIA ERFE SMALL LETTER DJAI
#define UC_MACRO_NAME_16EC4 0x16EC4 //  BERIA ERFE SMALL LETTER KOBO
#define UC_MACRO_NAME_16EC5 0x16EC5 //  BERIA ERFE SMALL LETTER LAKKO
#define UC_MACRO_NAME_16EC6 0x16EC6 //  BERIA ERFE SMALL LETTER MERI
#define UC_MACRO_NAME_16EC7 0x16EC7 //  BERIA ERFE SMALL LETTER NINI
#define UC_MACRO_NAME_16EC8 0x16EC8 //  BERIA ERFE SMALL LETTER GNA
#define UC_MACRO_NAME_16EC9 0x16EC9 //  BERIA ERFE SMALL LETTER NGAY
#define UC_MACRO_NAME_16ECA 0x16ECA //  BERIA ERFE SMALL LETTER OI
#define UC_MACRO_NAME_16ECB 0x16ECB //  BERIA ERFE SMALL LETTER PI
#define UC_MACRO_NAME_16ECC 0x16ECC //  BERIA ERFE SMALL LETTER ERIGO
#define UC_MACRO_NAME_16ECD 0x16ECD //  BERIA ERFE SMALL LETTER ERIGO TAMURA
#define UC_MACRO_NAME_16ECE 0x16ECE //  BERIA ERFE SMALL LETTER SERI
#define UC_MACRO_NAME_16ECF 0x16ECF //  BERIA ERFE SMALL LETTER SHEP
#define UC_MACRO_NAME_16ED0 0x16ED0 //  BERIA ERFE SMALL LETTER TATASOUE
#define UC_MACRO_NAME_16ED1 0x16ED1 //  BERIA ERFE SMALL LETTER UI
#define UC_MACRO_NAME_16ED2 0x16ED2 //  BERIA ERFE SMALL LETTER WASSE
#define UC_MACRO_NAME_16ED3 0x16ED3 //  BERIA ERFE SMALL LETTER AY


#endif // UC_H_BERIA_ERFE
