/*
 * Unicode Block: Bopomofo Extended
 * Range: U+31A0..U+31BF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Bopomofo Extended is a Unicode block containing additional Bopomofo
 * characters for writing phonetic Min Nan , Hakka Chinese , Cantonese ,
 * Hmu , and Ge . The basic set of Bopomofo characters can be found in
 * the Bopomofo block.
 *
 */
#ifndef UC_H_BOPOMOFO_EXTENDED
#define UC_H_BOPOMOFO_EXTENDED

#define UC_MACRO_NAME_31A0 0x31A0 // ㆠ BOPOMOFO LETTER BU
#define UC_MACRO_NAME_31A1 0x31A1 // ㆡ BOPOMOFO LETTER ZI
#define UC_MACRO_NAME_31A2 0x31A2 // ㆢ BOPOMOFO LETTER JI
#define UC_MACRO_NAME_31A3 0x31A3 // ㆣ BOPOMOFO LETTER GU
#define UC_MACRO_NAME_31A4 0x31A4 // ㆤ BOPOMOFO LETTER EE
#define UC_MACRO_NAME_31A5 0x31A5 // ㆥ BOPOMOFO LETTER ENN
#define UC_MACRO_NAME_31A6 0x31A6 // ㆦ BOPOMOFO LETTER OO
#define UC_MACRO_NAME_31A7 0x31A7 // ㆧ BOPOMOFO LETTER ONN
#define UC_MACRO_NAME_31A8 0x31A8 // ㆨ BOPOMOFO LETTER IR
#define UC_MACRO_NAME_31A9 0x31A9 // ㆩ BOPOMOFO LETTER ANN
#define UC_MACRO_NAME_31AA 0x31AA // ㆪ BOPOMOFO LETTER INN
#define UC_MACRO_NAME_31AB 0x31AB // ㆫ BOPOMOFO LETTER UNN
#define UC_MACRO_NAME_31AC 0x31AC // ㆬ BOPOMOFO LETTER IM
#define UC_MACRO_NAME_31AD 0x31AD // ㆭ BOPOMOFO LETTER NGG
#define UC_MACRO_NAME_31AE 0x31AE // ㆮ BOPOMOFO LETTER AINN
#define UC_MACRO_NAME_31AF 0x31AF // ㆯ BOPOMOFO LETTER AUNN
#define UC_MACRO_NAME_31B0 0x31B0 // ㆰ BOPOMOFO LETTER AM
#define UC_MACRO_NAME_31B1 0x31B1 // ㆱ BOPOMOFO LETTER OM
#define UC_MACRO_NAME_31B2 0x31B2 // ㆲ BOPOMOFO LETTER ONG
#define UC_MACRO_NAME_31B3 0x31B3 // ㆳ BOPOMOFO LETTER INNN
#define UC_MACRO_NAME_31B4 0x31B4 // ㆴ BOPOMOFO FINAL LETTER P
#define UC_MACRO_NAME_31B5 0x31B5 // ㆵ BOPOMOFO FINAL LETTER T
#define UC_MACRO_NAME_31B6 0x31B6 // ㆶ BOPOMOFO FINAL LETTER K
#define UC_MACRO_NAME_31B7 0x31B7 // ㆷ BOPOMOFO FINAL LETTER H
#define UC_MACRO_NAME_31B8 0x31B8 // ㆸ BOPOMOFO LETTER GH
#define UC_MACRO_NAME_31B9 0x31B9 // ㆹ BOPOMOFO LETTER LH
#define UC_MACRO_NAME_31BA 0x31BA // ㆺ BOPOMOFO LETTER ZY
#define UC_MACRO_NAME_31BB 0x31BB // ㆻ BOPOMOFO FINAL LETTER G
#define UC_MACRO_NAME_31BC 0x31BC // ㆼ BOPOMOFO LETTER GW
#define UC_MACRO_NAME_31BD 0x31BD // ㆽ BOPOMOFO LETTER KW
#define UC_MACRO_NAME_31BE 0x31BE // ㆾ BOPOMOFO LETTER OE
#define UC_MACRO_NAME_31BF 0x31BF // ㆿ BOPOMOFO LETTER AH


#endif // UC_H_BOPOMOFO_EXTENDED
