/*
 * Unicode Block: Bamum
 * Range: U+A6A0..U+A6FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Bamum , also spelled Bamoum , Bamun , or Bamoun , may refer to:
 *
 */
#ifndef UC_H_BAMUM
#define UC_H_BAMUM

#define UC_MACRO_NAME_A6A0 0xA6A0 // ꚠ BAMUM LETTER A
#define UC_MACRO_NAME_A6A1 0xA6A1 // ꚡ BAMUM LETTER KA
#define UC_MACRO_NAME_A6A2 0xA6A2 // ꚢ BAMUM LETTER U
#define UC_MACRO_NAME_A6A3 0xA6A3 // ꚣ BAMUM LETTER KU
#define UC_MACRO_NAME_A6A4 0xA6A4 // ꚤ BAMUM LETTER EE
#define UC_MACRO_NAME_A6A5 0xA6A5 // ꚥ BAMUM LETTER REE
#define UC_MACRO_NAME_A6A6 0xA6A6 // ꚦ BAMUM LETTER TAE
#define UC_MACRO_NAME_A6A7 0xA6A7 // ꚧ BAMUM LETTER O
#define UC_MACRO_NAME_A6A8 0xA6A8 // ꚨ BAMUM LETTER NYI
#define UC_MACRO_NAME_A6A9 0xA6A9 // ꚩ BAMUM LETTER I
#define UC_MACRO_NAME_A6AA 0xA6AA // ꚪ BAMUM LETTER LA
#define UC_MACRO_NAME_A6AB 0xA6AB // ꚫ BAMUM LETTER PA
#define UC_MACRO_NAME_A6AC 0xA6AC // ꚬ BAMUM LETTER RII
#define UC_MACRO_NAME_A6AD 0xA6AD // ꚭ BAMUM LETTER RIEE
#define UC_MACRO_NAME_A6AE 0xA6AE // ꚮ BAMUM LETTER LEEEE
#define UC_MACRO_NAME_A6AF 0xA6AF // ꚯ BAMUM LETTER MEEEE
#define UC_MACRO_NAME_A6B0 0xA6B0 // ꚰ BAMUM LETTER TAA
#define UC_MACRO_NAME_A6B1 0xA6B1 // ꚱ BAMUM LETTER NDAA
#define UC_MACRO_NAME_A6B2 0xA6B2 // ꚲ BAMUM LETTER NJAEM
#define UC_MACRO_NAME_A6B3 0xA6B3 // ꚳ BAMUM LETTER M
#define UC_MACRO_NAME_A6B4 0xA6B4 // ꚴ BAMUM LETTER SUU
#define UC_MACRO_NAME_A6B5 0xA6B5 // ꚵ BAMUM LETTER MU
#define UC_MACRO_NAME_A6B6 0xA6B6 // ꚶ BAMUM LETTER SHII
#define UC_MACRO_NAME_A6B7 0xA6B7 // ꚷ BAMUM LETTER SI
#define UC_MACRO_NAME_A6B8 0xA6B8 // ꚸ BAMUM LETTER SHEUX
#define UC_MACRO_NAME_A6B9 0xA6B9 // ꚹ BAMUM LETTER SEUX
#define UC_MACRO_NAME_A6BA 0xA6BA // ꚺ BAMUM LETTER KYEE
#define UC_MACRO_NAME_A6BB 0xA6BB // ꚻ BAMUM LETTER KET
#define UC_MACRO_NAME_A6BC 0xA6BC // ꚼ BAMUM LETTER NUAE
#define UC_MACRO_NAME_A6BD 0xA6BD // ꚽ BAMUM LETTER NU
#define UC_MACRO_NAME_A6BE 0xA6BE // ꚾ BAMUM LETTER NJUAE
#define UC_MACRO_NAME_A6BF 0xA6BF // ꚿ BAMUM LETTER YOQ
#define UC_MACRO_NAME_A6C0 0xA6C0 // ꛀ BAMUM LETTER SHU
#define UC_MACRO_NAME_A6C1 0xA6C1 // ꛁ BAMUM LETTER YUQ
#define UC_MACRO_NAME_A6C2 0xA6C2 // ꛂ BAMUM LETTER YA
#define UC_MACRO_NAME_A6C3 0xA6C3 // ꛃ BAMUM LETTER NSHA
#define UC_MACRO_NAME_A6C4 0xA6C4 // ꛄ BAMUM LETTER KEUX
#define UC_MACRO_NAME_A6C5 0xA6C5 // ꛅ BAMUM LETTER PEUX
#define UC_MACRO_NAME_A6C6 0xA6C6 // ꛆ BAMUM LETTER NJEE
#define UC_MACRO_NAME_A6C7 0xA6C7 // ꛇ BAMUM LETTER NTEE
#define UC_MACRO_NAME_A6C8 0xA6C8 // ꛈ BAMUM LETTER PUE
#define UC_MACRO_NAME_A6C9 0xA6C9 // ꛉ BAMUM LETTER WUE
#define UC_MACRO_NAME_A6CA 0xA6CA // ꛊ BAMUM LETTER PEE
#define UC_MACRO_NAME_A6CB 0xA6CB // ꛋ BAMUM LETTER FEE
#define UC_MACRO_NAME_A6CC 0xA6CC // ꛌ BAMUM LETTER RU
#define UC_MACRO_NAME_A6CD 0xA6CD // ꛍ BAMUM LETTER LU
#define UC_MACRO_NAME_A6CE 0xA6CE // ꛎ BAMUM LETTER MI
#define UC_MACRO_NAME_A6CF 0xA6CF // ꛏ BAMUM LETTER NI
#define UC_MACRO_NAME_A6D0 0xA6D0 // ꛐ BAMUM LETTER REUX
#define UC_MACRO_NAME_A6D1 0xA6D1 // ꛑ BAMUM LETTER RAE
#define UC_MACRO_NAME_A6D2 0xA6D2 // ꛒ BAMUM LETTER KEN
#define UC_MACRO_NAME_A6D3 0xA6D3 // ꛓ BAMUM LETTER NGKWAEN
#define UC_MACRO_NAME_A6D4 0xA6D4 // ꛔ BAMUM LETTER NGGA
#define UC_MACRO_NAME_A6D5 0xA6D5 // ꛕ BAMUM LETTER NGA
#define UC_MACRO_NAME_A6D6 0xA6D6 // ꛖ BAMUM LETTER SHO
#define UC_MACRO_NAME_A6D7 0xA6D7 // ꛗ BAMUM LETTER PUAE
#define UC_MACRO_NAME_A6D8 0xA6D8 // ꛘ BAMUM LETTER FU
#define UC_MACRO_NAME_A6D9 0xA6D9 // ꛙ BAMUM LETTER FOM
#define UC_MACRO_NAME_A6DA 0xA6DA // ꛚ BAMUM LETTER WA
#define UC_MACRO_NAME_A6DB 0xA6DB // ꛛ BAMUM LETTER NA
#define UC_MACRO_NAME_A6DC 0xA6DC // ꛜ BAMUM LETTER LI
#define UC_MACRO_NAME_A6DD 0xA6DD // ꛝ BAMUM LETTER PI
#define UC_MACRO_NAME_A6DE 0xA6DE // ꛞ BAMUM LETTER LOQ
#define UC_MACRO_NAME_A6DF 0xA6DF // ꛟ BAMUM LETTER KO
#define UC_MACRO_NAME_A6E0 0xA6E0 // ꛠ BAMUM LETTER MBEN
#define UC_MACRO_NAME_A6E1 0xA6E1 // ꛡ BAMUM LETTER REN
#define UC_MACRO_NAME_A6E2 0xA6E2 // ꛢ BAMUM LETTER MEN
#define UC_MACRO_NAME_A6E3 0xA6E3 // ꛣ BAMUM LETTER MA
#define UC_MACRO_NAME_A6E4 0xA6E4 // ꛤ BAMUM LETTER TI
#define UC_MACRO_NAME_A6E5 0xA6E5 // ꛥ BAMUM LETTER KI
#define UC_MACRO_NAME_A6E6 0xA6E6 // ꛦ BAMUM LETTER MO
#define UC_MACRO_NAME_A6E7 0xA6E7 // ꛧ BAMUM LETTER MBAA
#define UC_MACRO_NAME_A6E8 0xA6E8 // ꛨ BAMUM LETTER TET
#define UC_MACRO_NAME_A6E9 0xA6E9 // ꛩ BAMUM LETTER KPA
#define UC_MACRO_NAME_A6EA 0xA6EA // ꛪ BAMUM LETTER TEN
#define UC_MACRO_NAME_A6EB 0xA6EB // ꛫ BAMUM LETTER NTUU
#define UC_MACRO_NAME_A6EC 0xA6EC // ꛬ BAMUM LETTER SAMBA
#define UC_MACRO_NAME_A6ED 0xA6ED // ꛭ BAMUM LETTER FAAMAE
#define UC_MACRO_NAME_A6EE 0xA6EE // ꛮ BAMUM LETTER KOVUU
#define UC_MACRO_NAME_A6EF 0xA6EF // ꛯ BAMUM LETTER KOGHOM
#define UC_MACRO_NAME_A6F0 0xA6F0 // ꛰ BAMUM COMBINING MARK KOQNDON
#define UC_MACRO_NAME_A6F1 0xA6F1 // ꛱ BAMUM COMBINING MARK TUKWENTIS
#define UC_MACRO_NAME_A6F2 0xA6F2 // ꛲ BAMUM NJAEMLI
#define UC_MACRO_NAME_A6F3 0xA6F3 // ꛳ BAMUM FULL STOP
#define UC_MACRO_NAME_A6F4 0xA6F4 // ꛴ BAMUM COLON
#define UC_MACRO_NAME_A6F5 0xA6F5 // ꛵ BAMUM COMMA
#define UC_MACRO_NAME_A6F6 0xA6F6 // ꛶ BAMUM SEMICOLON
#define UC_MACRO_NAME_A6F7 0xA6F7 // ꛷ BAMUM QUESTION MARK


#endif // UC_H_BAMUM
