/*
 * Unicode Block: Balinese
 * Range: U+1B00..U+1B7F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Balinese may refer to:
 *
 */
#ifndef UC_H_BALINESE
#define UC_H_BALINESE

#define UC_MACRO_NAME_1B00 0x1B00 // ᬀ BALINESE SIGN ULU RICEM
#define UC_MACRO_NAME_1B01 0x1B01 // ᬁ BALINESE SIGN ULU CANDRA
#define UC_MACRO_NAME_1B02 0x1B02 // ᬂ BALINESE SIGN CECEK
#define UC_MACRO_NAME_1B03 0x1B03 // ᬃ BALINESE SIGN SURANG
#define UC_MACRO_NAME_1B04 0x1B04 // ᬄ BALINESE SIGN BISAH
#define UC_MACRO_NAME_1B05 0x1B05 // ᬅ BALINESE LETTER AKARA
#define UC_MACRO_NAME_1B06 0x1B06 // ᬆ BALINESE LETTER AKARA TEDUNG
#define UC_MACRO_NAME_1B07 0x1B07 // ᬇ BALINESE LETTER IKARA
#define UC_MACRO_NAME_1B08 0x1B08 // ᬈ BALINESE LETTER IKARA TEDUNG
#define UC_MACRO_NAME_1B09 0x1B09 // ᬉ BALINESE LETTER UKARA
#define UC_MACRO_NAME_1B0A 0x1B0A // ᬊ BALINESE LETTER UKARA TEDUNG
#define UC_MACRO_NAME_1B0B 0x1B0B // ᬋ BALINESE LETTER RA REPA
#define UC_MACRO_NAME_1B0C 0x1B0C // ᬌ BALINESE LETTER RA REPA TEDUNG
#define UC_MACRO_NAME_1B0D 0x1B0D // ᬍ BALINESE LETTER LA LENGA
#define UC_MACRO_NAME_1B0E 0x1B0E // ᬎ BALINESE LETTER LA LENGA TEDUNG
#define UC_MACRO_NAME_1B0F 0x1B0F // ᬏ BALINESE LETTER EKARA
#define UC_MACRO_NAME_1B10 0x1B10 // ᬐ BALINESE LETTER AIKARA
#define UC_MACRO_NAME_1B11 0x1B11 // ᬑ BALINESE LETTER OKARA
#define UC_MACRO_NAME_1B12 0x1B12 // ᬒ BALINESE LETTER OKARA TEDUNG
#define UC_MACRO_NAME_1B13 0x1B13 // ᬓ BALINESE LETTER KA
#define UC_MACRO_NAME_1B14 0x1B14 // ᬔ BALINESE LETTER KA MAHAPRANA
#define UC_MACRO_NAME_1B15 0x1B15 // ᬕ BALINESE LETTER GA
#define UC_MACRO_NAME_1B16 0x1B16 // ᬖ BALINESE LETTER GA GORA
#define UC_MACRO_NAME_1B17 0x1B17 // ᬗ BALINESE LETTER NGA
#define UC_MACRO_NAME_1B18 0x1B18 // ᬘ BALINESE LETTER CA
#define UC_MACRO_NAME_1B19 0x1B19 // ᬙ BALINESE LETTER CA LACA
#define UC_MACRO_NAME_1B1A 0x1B1A // ᬚ BALINESE LETTER JA
#define UC_MACRO_NAME_1B1B 0x1B1B // ᬛ BALINESE LETTER JA JERA
#define UC_MACRO_NAME_1B1C 0x1B1C // ᬜ BALINESE LETTER NYA
#define UC_MACRO_NAME_1B1D 0x1B1D // ᬝ BALINESE LETTER TA LATIK
#define UC_MACRO_NAME_1B1E 0x1B1E // ᬞ BALINESE LETTER TA MURDA MAHAPRANA
#define UC_MACRO_NAME_1B1F 0x1B1F // ᬟ BALINESE LETTER DA MURDA ALPAPRANA
#define UC_MACRO_NAME_1B20 0x1B20 // ᬠ BALINESE LETTER DA MURDA MAHAPRANA
#define UC_MACRO_NAME_1B21 0x1B21 // ᬡ BALINESE LETTER NA RAMBAT
#define UC_MACRO_NAME_1B22 0x1B22 // ᬢ BALINESE LETTER TA
#define UC_MACRO_NAME_1B23 0x1B23 // ᬣ BALINESE LETTER TA TAWA
#define UC_MACRO_NAME_1B24 0x1B24 // ᬤ BALINESE LETTER DA
#define UC_MACRO_NAME_1B25 0x1B25 // ᬥ BALINESE LETTER DA MADU
#define UC_MACRO_NAME_1B26 0x1B26 // ᬦ BALINESE LETTER NA
#define UC_MACRO_NAME_1B27 0x1B27 // ᬧ BALINESE LETTER PA
#define UC_MACRO_NAME_1B28 0x1B28 // ᬨ BALINESE LETTER PA KAPAL
#define UC_MACRO_NAME_1B29 0x1B29 // ᬩ BALINESE LETTER BA
#define UC_MACRO_NAME_1B2A 0x1B2A // ᬪ BALINESE LETTER BA KEMBANG
#define UC_MACRO_NAME_1B2B 0x1B2B // ᬫ BALINESE LETTER MA
#define UC_MACRO_NAME_1B2C 0x1B2C // ᬬ BALINESE LETTER YA
#define UC_MACRO_NAME_1B2D 0x1B2D // ᬭ BALINESE LETTER RA
#define UC_MACRO_NAME_1B2E 0x1B2E // ᬮ BALINESE LETTER LA
#define UC_MACRO_NAME_1B2F 0x1B2F // ᬯ BALINESE LETTER WA
#define UC_MACRO_NAME_1B30 0x1B30 // ᬰ BALINESE LETTER SA SAGA
#define UC_MACRO_NAME_1B31 0x1B31 // ᬱ BALINESE LETTER SA SAPA
#define UC_MACRO_NAME_1B32 0x1B32 // ᬲ BALINESE LETTER SA
#define UC_MACRO_NAME_1B33 0x1B33 // ᬳ BALINESE LETTER HA
#define UC_MACRO_NAME_1B34 0x1B34 // ᬴ BALINESE SIGN REREKAN
#define UC_MACRO_NAME_1B35 0x1B35 // ᬵ BALINESE VOWEL SIGN TEDUNG
#define UC_MACRO_NAME_1B36 0x1B36 // ᬶ BALINESE VOWEL SIGN ULU
#define UC_MACRO_NAME_1B37 0x1B37 // ᬷ BALINESE VOWEL SIGN ULU SARI
#define UC_MACRO_NAME_1B38 0x1B38 // ᬸ BALINESE VOWEL SIGN SUKU
#define UC_MACRO_NAME_1B39 0x1B39 // ᬹ BALINESE VOWEL SIGN SUKU ILUT
#define UC_MACRO_NAME_1B3A 0x1B3A // ᬺ BALINESE VOWEL SIGN RA REPA
#define UC_MACRO_NAME_1B3B 0x1B3B // ᬻ BALINESE VOWEL SIGN RA REPA TEDUNG
#define UC_MACRO_NAME_1B3C 0x1B3C // ᬼ BALINESE VOWEL SIGN LA LENGA
#define UC_MACRO_NAME_1B3D 0x1B3D // ᬽ BALINESE VOWEL SIGN LA LENGA TEDUNG
#define UC_MACRO_NAME_1B3E 0x1B3E // ᬾ BALINESE VOWEL SIGN TALING
#define UC_MACRO_NAME_1B3F 0x1B3F // ᬿ BALINESE VOWEL SIGN TALING REPA
#define UC_MACRO_NAME_1B40 0x1B40 // ᭀ BALINESE VOWEL SIGN TALING TEDUNG
#define UC_MACRO_NAME_1B41 0x1B41 // ᭁ BALINESE VOWEL SIGN TALING REPA TEDUNG
#define UC_MACRO_NAME_1B42 0x1B42 // ᭂ BALINESE VOWEL SIGN PEPET
#define UC_MACRO_NAME_1B43 0x1B43 // ᭃ BALINESE VOWEL SIGN PEPET TEDUNG
#define UC_MACRO_NAME_1B44 0x1B44 // ᭄ BALINESE ADEG ADEG
#define UC_MACRO_NAME_1B45 0x1B45 // ᭅ BALINESE LETTER KAF SASAK
#define UC_MACRO_NAME_1B46 0x1B46 // ᭆ BALINESE LETTER KHOT SASAK
#define UC_MACRO_NAME_1B47 0x1B47 // ᭇ BALINESE LETTER TZIR SASAK
#define UC_MACRO_NAME_1B48 0x1B48 // ᭈ BALINESE LETTER EF SASAK
#define UC_MACRO_NAME_1B49 0x1B49 // ᭉ BALINESE LETTER VE SASAK
#define UC_MACRO_NAME_1B4A 0x1B4A // ᭊ BALINESE LETTER ZAL SASAK
#define UC_MACRO_NAME_1B4B 0x1B4B // ᭋ BALINESE LETTER ASYURA SASAK
#define UC_MACRO_NAME_1B4C 0x1B4C // ᭌ BALINESE LETTER ARCHAIC JNYA
#define UC_MACRO_NAME_1B4E 0x1B4E //  BALINESE INVERTED CARIK SIKI
#define UC_MACRO_NAME_1B4F 0x1B4F //  BALINESE INVERTED CARIK PAREREN
#define UC_MACRO_NAME_1B50 0x1B50 // ᭐ BALINESE DIGIT ZERO
#define UC_MACRO_NAME_1B51 0x1B51 // ᭑ BALINESE DIGIT ONE
#define UC_MACRO_NAME_1B52 0x1B52 // ᭒ BALINESE DIGIT TWO
#define UC_MACRO_NAME_1B53 0x1B53 // ᭓ BALINESE DIGIT THREE
#define UC_MACRO_NAME_1B54 0x1B54 // ᭔ BALINESE DIGIT FOUR
#define UC_MACRO_NAME_1B55 0x1B55 // ᭕ BALINESE DIGIT FIVE
#define UC_MACRO_NAME_1B56 0x1B56 // ᭖ BALINESE DIGIT SIX
#define UC_MACRO_NAME_1B57 0x1B57 // ᭗ BALINESE DIGIT SEVEN
#define UC_MACRO_NAME_1B58 0x1B58 // ᭘ BALINESE DIGIT EIGHT
#define UC_MACRO_NAME_1B59 0x1B59 // ᭙ BALINESE DIGIT NINE
#define UC_MACRO_NAME_1B5A 0x1B5A // ᭚ BALINESE PANTI
#define UC_MACRO_NAME_1B5B 0x1B5B // ᭛ BALINESE PAMADA
#define UC_MACRO_NAME_1B5C 0x1B5C // ᭜ BALINESE WINDU
#define UC_MACRO_NAME_1B5D 0x1B5D // ᭝ BALINESE CARIK PAMUNGKAH
#define UC_MACRO_NAME_1B5E 0x1B5E // ᭞ BALINESE CARIK SIKI
#define UC_MACRO_NAME_1B5F 0x1B5F // ᭟ BALINESE CARIK PAREREN
#define UC_MACRO_NAME_1B60 0x1B60 // ᭠ BALINESE PAMENENG
#define UC_MACRO_NAME_1B61 0x1B61 // ᭡ BALINESE MUSICAL SYMBOL DONG
#define UC_MACRO_NAME_1B62 0x1B62 // ᭢ BALINESE MUSICAL SYMBOL DENG
#define UC_MACRO_NAME_1B63 0x1B63 // ᭣ BALINESE MUSICAL SYMBOL DUNG
#define UC_MACRO_NAME_1B64 0x1B64 // ᭤ BALINESE MUSICAL SYMBOL DANG
#define UC_MACRO_NAME_1B65 0x1B65 // ᭥ BALINESE MUSICAL SYMBOL DANG SURANG
#define UC_MACRO_NAME_1B66 0x1B66 // ᭦ BALINESE MUSICAL SYMBOL DING
#define UC_MACRO_NAME_1B67 0x1B67 // ᭧ BALINESE MUSICAL SYMBOL DAENG
#define UC_MACRO_NAME_1B68 0x1B68 // ᭨ BALINESE MUSICAL SYMBOL DEUNG
#define UC_MACRO_NAME_1B69 0x1B69 // ᭩ BALINESE MUSICAL SYMBOL DAING
#define UC_MACRO_NAME_1B6A 0x1B6A // ᭪ BALINESE MUSICAL SYMBOL DANG GEDE
#define UC_MACRO_NAME_1B6B 0x1B6B // ᭫ BALINESE MUSICAL SYMBOL COMBINING TEGEH
#define UC_MACRO_NAME_1B6C 0x1B6C // ᭬ BALINESE MUSICAL SYMBOL COMBINING ENDEP
#define UC_MACRO_NAME_1B6D 0x1B6D // ᭭ BALINESE MUSICAL SYMBOL COMBINING KEMPUL
#define UC_MACRO_NAME_1B6E 0x1B6E // ᭮ BALINESE MUSICAL SYMBOL COMBINING KEMPLI
#define UC_MACRO_NAME_1B6F 0x1B6F // ᭯ BALINESE MUSICAL SYMBOL COMBINING JEGOGAN
#define UC_MACRO_NAME_1B70 0x1B70 // ᭰ BALINESE MUSICAL SYMBOL COMBINING KEMPUL WITH JEGOGAN
#define UC_MACRO_NAME_1B71 0x1B71 // ᭱ BALINESE MUSICAL SYMBOL COMBINING KEMPLI WITH JEGOGAN
#define UC_MACRO_NAME_1B72 0x1B72 // ᭲ BALINESE MUSICAL SYMBOL COMBINING BENDE
#define UC_MACRO_NAME_1B73 0x1B73 // ᭳ BALINESE MUSICAL SYMBOL COMBINING GONG
#define UC_MACRO_NAME_1B74 0x1B74 // ᭴ BALINESE MUSICAL SYMBOL RIGHT-HAND OPEN DUG
#define UC_MACRO_NAME_1B75 0x1B75 // ᭵ BALINESE MUSICAL SYMBOL RIGHT-HAND OPEN DAG
#define UC_MACRO_NAME_1B76 0x1B76 // ᭶ BALINESE MUSICAL SYMBOL RIGHT-HAND CLOSED TUK
#define UC_MACRO_NAME_1B77 0x1B77 // ᭷ BALINESE MUSICAL SYMBOL RIGHT-HAND CLOSED TAK
#define UC_MACRO_NAME_1B78 0x1B78 // ᭸ BALINESE MUSICAL SYMBOL LEFT-HAND OPEN PANG
#define UC_MACRO_NAME_1B79 0x1B79 // ᭹ BALINESE MUSICAL SYMBOL LEFT-HAND OPEN PUNG
#define UC_MACRO_NAME_1B7A 0x1B7A // ᭺ BALINESE MUSICAL SYMBOL LEFT-HAND CLOSED PLAK
#define UC_MACRO_NAME_1B7B 0x1B7B // ᭻ BALINESE MUSICAL SYMBOL LEFT-HAND CLOSED PLUK
#define UC_MACRO_NAME_1B7C 0x1B7C // ᭼ BALINESE MUSICAL SYMBOL LEFT-HAND OPEN PING
#define UC_MACRO_NAME_1B7D 0x1B7D // ᭽ BALINESE PANTI LANTANG
#define UC_MACRO_NAME_1B7E 0x1B7E // ᭾ BALINESE PAMADA LANTANG
#define UC_MACRO_NAME_1B7F 0x1B7F //  BALINESE PANTI BAWAK


#endif // UC_H_BALINESE
