/*
 * Unicode Block: Buginese
 * Range: U+1A00..U+1A1F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Buginese may refer to:
 *
 */
#ifndef UC_H_BUGINESE
#define UC_H_BUGINESE

#define UC_MACRO_NAME_1A00 0x1A00 // ᨀ BUGINESE LETTER KA
#define UC_MACRO_NAME_1A01 0x1A01 // ᨁ BUGINESE LETTER GA
#define UC_MACRO_NAME_1A02 0x1A02 // ᨂ BUGINESE LETTER NGA
#define UC_MACRO_NAME_1A03 0x1A03 // ᨃ BUGINESE LETTER NGKA
#define UC_MACRO_NAME_1A04 0x1A04 // ᨄ BUGINESE LETTER PA
#define UC_MACRO_NAME_1A05 0x1A05 // ᨅ BUGINESE LETTER BA
#define UC_MACRO_NAME_1A06 0x1A06 // ᨆ BUGINESE LETTER MA
#define UC_MACRO_NAME_1A07 0x1A07 // ᨇ BUGINESE LETTER MPA
#define UC_MACRO_NAME_1A08 0x1A08 // ᨈ BUGINESE LETTER TA
#define UC_MACRO_NAME_1A09 0x1A09 // ᨉ BUGINESE LETTER DA
#define UC_MACRO_NAME_1A0A 0x1A0A // ᨊ BUGINESE LETTER NA
#define UC_MACRO_NAME_1A0B 0x1A0B // ᨋ BUGINESE LETTER NRA
#define UC_MACRO_NAME_1A0C 0x1A0C // ᨌ BUGINESE LETTER CA
#define UC_MACRO_NAME_1A0D 0x1A0D // ᨍ BUGINESE LETTER JA
#define UC_MACRO_NAME_1A0E 0x1A0E // ᨎ BUGINESE LETTER NYA
#define UC_MACRO_NAME_1A0F 0x1A0F // ᨏ BUGINESE LETTER NYCA
#define UC_MACRO_NAME_1A10 0x1A10 // ᨐ BUGINESE LETTER YA
#define UC_MACRO_NAME_1A11 0x1A11 // ᨑ BUGINESE LETTER RA
#define UC_MACRO_NAME_1A12 0x1A12 // ᨒ BUGINESE LETTER LA
#define UC_MACRO_NAME_1A13 0x1A13 // ᨓ BUGINESE LETTER VA
#define UC_MACRO_NAME_1A14 0x1A14 // ᨔ BUGINESE LETTER SA
#define UC_MACRO_NAME_1A15 0x1A15 // ᨕ BUGINESE LETTER A
#define UC_MACRO_NAME_1A16 0x1A16 // ᨖ BUGINESE LETTER HA
#define UC_MACRO_NAME_1A17 0x1A17 // ᨗ BUGINESE VOWEL SIGN I
#define UC_MACRO_NAME_1A18 0x1A18 // ᨘ BUGINESE VOWEL SIGN U
#define UC_MACRO_NAME_1A19 0x1A19 // ᨙ BUGINESE VOWEL SIGN E
#define UC_MACRO_NAME_1A1A 0x1A1A // ᨚ BUGINESE VOWEL SIGN O
#define UC_MACRO_NAME_1A1B 0x1A1B // ᨛ BUGINESE VOWEL SIGN AE
#define UC_MACRO_NAME_1A1E 0x1A1E // ᨞ BUGINESE PALLAWA
#define UC_MACRO_NAME_1A1F 0x1A1F // ᨟ BUGINESE END OF SECTION


#endif // UC_H_BUGINESE
