/*
 * Unicode Block: CJK Radicals Supplement
 * Range: U+2E80..U+2EFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_CJK_RADICALS_SUPPLEMENT
#define UC_H_CJK_RADICALS_SUPPLEMENT

#define UC_MACRO_NAME_2E80 0x2E80 // ⺀ CJK RADICAL REPEAT
#define UC_MACRO_NAME_2E81 0x2E81 // ⺁ CJK RADICAL CLIFF
#define UC_MACRO_NAME_2E82 0x2E82 // ⺂ CJK RADICAL SECOND ONE
#define UC_MACRO_NAME_2E83 0x2E83 // ⺃ CJK RADICAL SECOND TWO
#define UC_MACRO_NAME_2E84 0x2E84 // ⺄ CJK RADICAL SECOND THREE
#define UC_MACRO_NAME_2E85 0x2E85 // ⺅ CJK RADICAL PERSON
#define UC_MACRO_NAME_2E86 0x2E86 // ⺆ CJK RADICAL BOX
#define UC_MACRO_NAME_2E87 0x2E87 // ⺇ CJK RADICAL TABLE
#define UC_MACRO_NAME_2E88 0x2E88 // ⺈ CJK RADICAL KNIFE ONE
#define UC_MACRO_NAME_2E89 0x2E89 // ⺉ CJK RADICAL KNIFE TWO
#define UC_MACRO_NAME_2E8A 0x2E8A // ⺊ CJK RADICAL DIVINATION
#define UC_MACRO_NAME_2E8B 0x2E8B // ⺋ CJK RADICAL SEAL
#define UC_MACRO_NAME_2E8C 0x2E8C // ⺌ CJK RADICAL SMALL ONE
#define UC_MACRO_NAME_2E8D 0x2E8D // ⺍ CJK RADICAL SMALL TWO
#define UC_MACRO_NAME_2E8E 0x2E8E // ⺎ CJK RADICAL LAME ONE
#define UC_MACRO_NAME_2E8F 0x2E8F // ⺏ CJK RADICAL LAME TWO
#define UC_MACRO_NAME_2E90 0x2E90 // ⺐ CJK RADICAL LAME THREE
#define UC_MACRO_NAME_2E91 0x2E91 // ⺑ CJK RADICAL LAME FOUR
#define UC_MACRO_NAME_2E92 0x2E92 // ⺒ CJK RADICAL SNAKE
#define UC_MACRO_NAME_2E93 0x2E93 // ⺓ CJK RADICAL THREAD
#define UC_MACRO_NAME_2E94 0x2E94 // ⺔ CJK RADICAL SNOUT ONE
#define UC_MACRO_NAME_2E95 0x2E95 // ⺕ CJK RADICAL SNOUT TWO
#define UC_MACRO_NAME_2E96 0x2E96 // ⺖ CJK RADICAL HEART ONE
#define UC_MACRO_NAME_2E97 0x2E97 // ⺗ CJK RADICAL HEART TWO
#define UC_MACRO_NAME_2E98 0x2E98 // ⺘ CJK RADICAL HAND
#define UC_MACRO_NAME_2E99 0x2E99 // ⺙ CJK RADICAL RAP
#define UC_MACRO_NAME_2E9B 0x2E9B // ⺛ CJK RADICAL CHOKE
#define UC_MACRO_NAME_2E9C 0x2E9C // ⺜ CJK RADICAL SUN
#define UC_MACRO_NAME_2E9D 0x2E9D // ⺝ CJK RADICAL MOON
#define UC_MACRO_NAME_2E9E 0x2E9E // ⺞ CJK RADICAL DEATH
#define UC_MACRO_NAME_2E9F 0x2E9F // ⺟ CJK RADICAL MOTHER
#define UC_MACRO_NAME_2EA0 0x2EA0 // ⺠ CJK RADICAL CIVILIAN
#define UC_MACRO_NAME_2EA1 0x2EA1 // ⺡ CJK RADICAL WATER ONE
#define UC_MACRO_NAME_2EA2 0x2EA2 // ⺢ CJK RADICAL WATER TWO
#define UC_MACRO_NAME_2EA3 0x2EA3 // ⺣ CJK RADICAL FIRE
#define UC_MACRO_NAME_2EA4 0x2EA4 // ⺤ CJK RADICAL PAW ONE
#define UC_MACRO_NAME_2EA5 0x2EA5 // ⺥ CJK RADICAL PAW TWO
#define UC_MACRO_NAME_2EA6 0x2EA6 // ⺦ CJK RADICAL SIMPLIFIED HALF TREE TRUNK
#define UC_MACRO_NAME_2EA7 0x2EA7 // ⺧ CJK RADICAL COW
#define UC_MACRO_NAME_2EA8 0x2EA8 // ⺨ CJK RADICAL DOG
#define UC_MACRO_NAME_2EA9 0x2EA9 // ⺩ CJK RADICAL JADE
#define UC_MACRO_NAME_2EAA 0x2EAA // ⺪ CJK RADICAL BOLT OF CLOTH
#define UC_MACRO_NAME_2EAB 0x2EAB // ⺫ CJK RADICAL EYE
#define UC_MACRO_NAME_2EAC 0x2EAC // ⺬ CJK RADICAL SPIRIT ONE
#define UC_MACRO_NAME_2EAD 0x2EAD // ⺭ CJK RADICAL SPIRIT TWO
#define UC_MACRO_NAME_2EAE 0x2EAE // ⺮ CJK RADICAL BAMBOO
#define UC_MACRO_NAME_2EAF 0x2EAF // ⺯ CJK RADICAL SILK
#define UC_MACRO_NAME_2EB0 0x2EB0 // ⺰ CJK RADICAL C-SIMPLIFIED SILK
#define UC_MACRO_NAME_2EB1 0x2EB1 // ⺱ CJK RADICAL NET ONE
#define UC_MACRO_NAME_2EB2 0x2EB2 // ⺲ CJK RADICAL NET TWO
#define UC_MACRO_NAME_2EB3 0x2EB3 // ⺳ CJK RADICAL NET THREE
#define UC_MACRO_NAME_2EB4 0x2EB4 // ⺴ CJK RADICAL NET FOUR
#define UC_MACRO_NAME_2EB5 0x2EB5 // ⺵ CJK RADICAL MESH
#define UC_MACRO_NAME_2EB6 0x2EB6 // ⺶ CJK RADICAL SHEEP
#define UC_MACRO_NAME_2EB7 0x2EB7 // ⺷ CJK RADICAL RAM
#define UC_MACRO_NAME_2EB8 0x2EB8 // ⺸ CJK RADICAL EWE
#define UC_MACRO_NAME_2EB9 0x2EB9 // ⺹ CJK RADICAL OLD
#define UC_MACRO_NAME_2EBA 0x2EBA // ⺺ CJK RADICAL BRUSH ONE
#define UC_MACRO_NAME_2EBB 0x2EBB // ⺻ CJK RADICAL BRUSH TWO
#define UC_MACRO_NAME_2EBC 0x2EBC // ⺼ CJK RADICAL MEAT
#define UC_MACRO_NAME_2EBD 0x2EBD // ⺽ CJK RADICAL MORTAR
#define UC_MACRO_NAME_2EBE 0x2EBE // ⺾ CJK RADICAL GRASS ONE
#define UC_MACRO_NAME_2EBF 0x2EBF // ⺿ CJK RADICAL GRASS TWO
#define UC_MACRO_NAME_2EC0 0x2EC0 // ⻀ CJK RADICAL GRASS THREE
#define UC_MACRO_NAME_2EC1 0x2EC1 // ⻁ CJK RADICAL TIGER
#define UC_MACRO_NAME_2EC2 0x2EC2 // ⻂ CJK RADICAL CLOTHES
#define UC_MACRO_NAME_2EC3 0x2EC3 // ⻃ CJK RADICAL WEST ONE
#define UC_MACRO_NAME_2EC4 0x2EC4 // ⻄ CJK RADICAL WEST TWO
#define UC_MACRO_NAME_2EC5 0x2EC5 // ⻅ CJK RADICAL C-SIMPLIFIED SEE
#define UC_MACRO_NAME_2EC6 0x2EC6 // ⻆ CJK RADICAL SIMPLIFIED HORN
#define UC_MACRO_NAME_2EC7 0x2EC7 // ⻇ CJK RADICAL HORN
#define UC_MACRO_NAME_2EC8 0x2EC8 // ⻈ CJK RADICAL C-SIMPLIFIED SPEECH
#define UC_MACRO_NAME_2EC9 0x2EC9 // ⻉ CJK RADICAL C-SIMPLIFIED SHELL
#define UC_MACRO_NAME_2ECA 0x2ECA // ⻊ CJK RADICAL FOOT
#define UC_MACRO_NAME_2ECB 0x2ECB // ⻋ CJK RADICAL C-SIMPLIFIED CART
#define UC_MACRO_NAME_2ECC 0x2ECC // ⻌ CJK RADICAL SIMPLIFIED WALK
#define UC_MACRO_NAME_2ECD 0x2ECD // ⻍ CJK RADICAL WALK ONE
#define UC_MACRO_NAME_2ECE 0x2ECE // ⻎ CJK RADICAL WALK TWO
#define UC_MACRO_NAME_2ECF 0x2ECF // ⻏ CJK RADICAL CITY
#define UC_MACRO_NAME_2ED0 0x2ED0 // ⻐ CJK RADICAL C-SIMPLIFIED GOLD
#define UC_MACRO_NAME_2ED1 0x2ED1 // ⻑ CJK RADICAL LONG ONE
#define UC_MACRO_NAME_2ED2 0x2ED2 // ⻒ CJK RADICAL LONG TWO
#define UC_MACRO_NAME_2ED3 0x2ED3 // ⻓ CJK RADICAL C-SIMPLIFIED LONG
#define UC_MACRO_NAME_2ED4 0x2ED4 // ⻔ CJK RADICAL C-SIMPLIFIED GATE
#define UC_MACRO_NAME_2ED5 0x2ED5 // ⻕ CJK RADICAL MOUND ONE
#define UC_MACRO_NAME_2ED6 0x2ED6 // ⻖ CJK RADICAL MOUND TWO
#define UC_MACRO_NAME_2ED7 0x2ED7 // ⻗ CJK RADICAL RAIN
#define UC_MACRO_NAME_2ED8 0x2ED8 // ⻘ CJK RADICAL BLUE
#define UC_MACRO_NAME_2ED9 0x2ED9 // ⻙ CJK RADICAL C-SIMPLIFIED TANNED LEATHER
#define UC_MACRO_NAME_2EDA 0x2EDA // ⻚ CJK RADICAL C-SIMPLIFIED LEAF
#define UC_MACRO_NAME_2EDB 0x2EDB // ⻛ CJK RADICAL C-SIMPLIFIED WIND
#define UC_MACRO_NAME_2EDC 0x2EDC // ⻜ CJK RADICAL C-SIMPLIFIED FLY
#define UC_MACRO_NAME_2EDD 0x2EDD // ⻝ CJK RADICAL EAT ONE
#define UC_MACRO_NAME_2EDE 0x2EDE // ⻞ CJK RADICAL EAT TWO
#define UC_MACRO_NAME_2EDF 0x2EDF // ⻟ CJK RADICAL EAT THREE
#define UC_MACRO_NAME_2EE0 0x2EE0 // ⻠ CJK RADICAL C-SIMPLIFIED EAT
#define UC_MACRO_NAME_2EE1 0x2EE1 // ⻡ CJK RADICAL HEAD
#define UC_MACRO_NAME_2EE2 0x2EE2 // ⻢ CJK RADICAL C-SIMPLIFIED HORSE
#define UC_MACRO_NAME_2EE3 0x2EE3 // ⻣ CJK RADICAL BONE
#define UC_MACRO_NAME_2EE4 0x2EE4 // ⻤ CJK RADICAL GHOST
#define UC_MACRO_NAME_2EE5 0x2EE5 // ⻥ CJK RADICAL C-SIMPLIFIED FISH
#define UC_MACRO_NAME_2EE6 0x2EE6 // ⻦ CJK RADICAL C-SIMPLIFIED BIRD
#define UC_MACRO_NAME_2EE7 0x2EE7 // ⻧ CJK RADICAL C-SIMPLIFIED SALT
#define UC_MACRO_NAME_2EE8 0x2EE8 // ⻨ CJK RADICAL SIMPLIFIED WHEAT
#define UC_MACRO_NAME_2EE9 0x2EE9 // ⻩ CJK RADICAL SIMPLIFIED YELLOW
#define UC_MACRO_NAME_2EEA 0x2EEA // ⻪ CJK RADICAL C-SIMPLIFIED FROG
#define UC_MACRO_NAME_2EEB 0x2EEB // ⻫ CJK RADICAL J-SIMPLIFIED EVEN
#define UC_MACRO_NAME_2EEC 0x2EEC // ⻬ CJK RADICAL C-SIMPLIFIED EVEN
#define UC_MACRO_NAME_2EED 0x2EED // ⻭ CJK RADICAL J-SIMPLIFIED TOOTH
#define UC_MACRO_NAME_2EEE 0x2EEE // ⻮ CJK RADICAL C-SIMPLIFIED TOOTH
#define UC_MACRO_NAME_2EEF 0x2EEF // ⻯ CJK RADICAL J-SIMPLIFIED DRAGON
#define UC_MACRO_NAME_2EF0 0x2EF0 // ⻰ CJK RADICAL C-SIMPLIFIED DRAGON
#define UC_MACRO_NAME_2EF1 0x2EF1 // ⻱ CJK RADICAL TURTLE
#define UC_MACRO_NAME_2EF2 0x2EF2 // ⻲ CJK RADICAL J-SIMPLIFIED TURTLE
#define UC_MACRO_NAME_2EF3 0x2EF3 // ⻳ CJK RADICAL C-SIMPLIFIED TURTLE


#endif // UC_H_CJK_RADICALS_SUPPLEMENT
