/*
 * Unicode Block: Cyrillic Extended-C
 * Range: U+1C80..U+1C8F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_CYRILLIC_EXTENDED_C
#define UC_H_CYRILLIC_EXTENDED_C

#define UC_MACRO_NAME_1C80 0x1C80 // ᲀ CYRILLIC SMALL LETTER ROUNDED VE
#define UC_MACRO_NAME_1C81 0x1C81 // ᲁ CYRILLIC SMALL LETTER LONG-LEGGED DE
#define UC_MACRO_NAME_1C82 0x1C82 // ᲂ CYRILLIC SMALL LETTER NARROW O
#define UC_MACRO_NAME_1C83 0x1C83 // ᲃ CYRILLIC SMALL LETTER WIDE ES
#define UC_MACRO_NAME_1C84 0x1C84 // ᲄ CYRILLIC SMALL LETTER TALL TE
#define UC_MACRO_NAME_1C85 0x1C85 // ᲅ CYRILLIC SMALL LETTER THREE-LEGGED TE
#define UC_MACRO_NAME_1C86 0x1C86 // ᲆ CYRILLIC SMALL LETTER TALL HARD SIGN
#define UC_MACRO_NAME_1C87 0x1C87 // ᲇ CYRILLIC SMALL LETTER TALL YAT
#define UC_MACRO_NAME_1C88 0x1C88 // ᲈ CYRILLIC SMALL LETTER UNBLENDED UK
#define UC_MACRO_NAME_1C89 0x1C89 //  CYRILLIC CAPITAL LETTER TJE
#define UC_MACRO_NAME_1C8A 0x1C8A //  CYRILLIC SMALL LETTER TJE


#endif // UC_H_CYRILLIC_EXTENDED_C
