/*
 * Unicode Block: Cham
 * Range: U+AA00..U+AA5F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Cham or CHAM may refer to:
 *
 */
#ifndef UC_H_CHAM
#define UC_H_CHAM

#define UC_MACRO_NAME_AA00 0xAA00 // ꨀ CHAM LETTER A
#define UC_MACRO_NAME_AA01 0xAA01 // ꨁ CHAM LETTER I
#define UC_MACRO_NAME_AA02 0xAA02 // ꨂ CHAM LETTER U
#define UC_MACRO_NAME_AA03 0xAA03 // ꨃ CHAM LETTER E
#define UC_MACRO_NAME_AA04 0xAA04 // ꨄ CHAM LETTER AI
#define UC_MACRO_NAME_AA05 0xAA05 // ꨅ CHAM LETTER O
#define UC_MACRO_NAME_AA06 0xAA06 // ꨆ CHAM LETTER KA
#define UC_MACRO_NAME_AA07 0xAA07 // ꨇ CHAM LETTER KHA
#define UC_MACRO_NAME_AA08 0xAA08 // ꨈ CHAM LETTER GA
#define UC_MACRO_NAME_AA09 0xAA09 // ꨉ CHAM LETTER GHA
#define UC_MACRO_NAME_AA0A 0xAA0A // ꨊ CHAM LETTER NGUE
#define UC_MACRO_NAME_AA0B 0xAA0B // ꨋ CHAM LETTER NGA
#define UC_MACRO_NAME_AA0C 0xAA0C // ꨌ CHAM LETTER CHA
#define UC_MACRO_NAME_AA0D 0xAA0D // ꨍ CHAM LETTER CHHA
#define UC_MACRO_NAME_AA0E 0xAA0E // ꨎ CHAM LETTER JA
#define UC_MACRO_NAME_AA0F 0xAA0F // ꨏ CHAM LETTER JHA
#define UC_MACRO_NAME_AA10 0xAA10 // ꨐ CHAM LETTER NHUE
#define UC_MACRO_NAME_AA11 0xAA11 // ꨑ CHAM LETTER NHA
#define UC_MACRO_NAME_AA12 0xAA12 // ꨒ CHAM LETTER NHJA
#define UC_MACRO_NAME_AA13 0xAA13 // ꨓ CHAM LETTER TA
#define UC_MACRO_NAME_AA14 0xAA14 // ꨔ CHAM LETTER THA
#define UC_MACRO_NAME_AA15 0xAA15 // ꨕ CHAM LETTER DA
#define UC_MACRO_NAME_AA16 0xAA16 // ꨖ CHAM LETTER DHA
#define UC_MACRO_NAME_AA17 0xAA17 // ꨗ CHAM LETTER NUE
#define UC_MACRO_NAME_AA18 0xAA18 // ꨘ CHAM LETTER NA
#define UC_MACRO_NAME_AA19 0xAA19 // ꨙ CHAM LETTER DDA
#define UC_MACRO_NAME_AA1A 0xAA1A // ꨚ CHAM LETTER PA
#define UC_MACRO_NAME_AA1B 0xAA1B // ꨛ CHAM LETTER PPA
#define UC_MACRO_NAME_AA1C 0xAA1C // ꨜ CHAM LETTER PHA
#define UC_MACRO_NAME_AA1D 0xAA1D // ꨝ CHAM LETTER BA
#define UC_MACRO_NAME_AA1E 0xAA1E // ꨞ CHAM LETTER BHA
#define UC_MACRO_NAME_AA1F 0xAA1F // ꨟ CHAM LETTER MUE
#define UC_MACRO_NAME_AA20 0xAA20 // ꨠ CHAM LETTER MA
#define UC_MACRO_NAME_AA21 0xAA21 // ꨡ CHAM LETTER BBA
#define UC_MACRO_NAME_AA22 0xAA22 // ꨢ CHAM LETTER YA
#define UC_MACRO_NAME_AA23 0xAA23 // ꨣ CHAM LETTER RA
#define UC_MACRO_NAME_AA24 0xAA24 // ꨤ CHAM LETTER LA
#define UC_MACRO_NAME_AA25 0xAA25 // ꨥ CHAM LETTER VA
#define UC_MACRO_NAME_AA26 0xAA26 // ꨦ CHAM LETTER SSA
#define UC_MACRO_NAME_AA27 0xAA27 // ꨧ CHAM LETTER SA
#define UC_MACRO_NAME_AA28 0xAA28 // ꨨ CHAM LETTER HA
#define UC_MACRO_NAME_AA29 0xAA29 // ꨩ CHAM VOWEL SIGN AA
#define UC_MACRO_NAME_AA2A 0xAA2A // ꨪ CHAM VOWEL SIGN I
#define UC_MACRO_NAME_AA2B 0xAA2B // ꨫ CHAM VOWEL SIGN II
#define UC_MACRO_NAME_AA2C 0xAA2C // ꨬ CHAM VOWEL SIGN EI
#define UC_MACRO_NAME_AA2D 0xAA2D // ꨭ CHAM VOWEL SIGN U
#define UC_MACRO_NAME_AA2E 0xAA2E // ꨮ CHAM VOWEL SIGN OE
#define UC_MACRO_NAME_AA2F 0xAA2F // ꨯ CHAM VOWEL SIGN O
#define UC_MACRO_NAME_AA30 0xAA30 // ꨰ CHAM VOWEL SIGN AI
#define UC_MACRO_NAME_AA31 0xAA31 // ꨱ CHAM VOWEL SIGN AU
#define UC_MACRO_NAME_AA32 0xAA32 // ꨲ CHAM VOWEL SIGN UE
#define UC_MACRO_NAME_AA33 0xAA33 // ꨳ CHAM CONSONANT SIGN YA
#define UC_MACRO_NAME_AA34 0xAA34 // ꨴ CHAM CONSONANT SIGN RA
#define UC_MACRO_NAME_AA35 0xAA35 // ꨵ CHAM CONSONANT SIGN LA
#define UC_MACRO_NAME_AA36 0xAA36 // ꨶ CHAM CONSONANT SIGN WA
#define UC_MACRO_NAME_AA40 0xAA40 // ꩀ CHAM LETTER FINAL K
#define UC_MACRO_NAME_AA41 0xAA41 // ꩁ CHAM LETTER FINAL G
#define UC_MACRO_NAME_AA42 0xAA42 // ꩂ CHAM LETTER FINAL NG
#define UC_MACRO_NAME_AA43 0xAA43 // ꩃ CHAM CONSONANT SIGN FINAL NG
#define UC_MACRO_NAME_AA44 0xAA44 // ꩄ CHAM LETTER FINAL CH
#define UC_MACRO_NAME_AA45 0xAA45 // ꩅ CHAM LETTER FINAL T
#define UC_MACRO_NAME_AA46 0xAA46 // ꩆ CHAM LETTER FINAL N
#define UC_MACRO_NAME_AA47 0xAA47 // ꩇ CHAM LETTER FINAL P
#define UC_MACRO_NAME_AA48 0xAA48 // ꩈ CHAM LETTER FINAL Y
#define UC_MACRO_NAME_AA49 0xAA49 // ꩉ CHAM LETTER FINAL R
#define UC_MACRO_NAME_AA4A 0xAA4A // ꩊ CHAM LETTER FINAL L
#define UC_MACRO_NAME_AA4B 0xAA4B // ꩋ CHAM LETTER FINAL SS
#define UC_MACRO_NAME_AA4C 0xAA4C // ꩌ CHAM CONSONANT SIGN FINAL M
#define UC_MACRO_NAME_AA4D 0xAA4D // ꩍ CHAM CONSONANT SIGN FINAL H
#define UC_MACRO_NAME_AA50 0xAA50 // ꩐ CHAM DIGIT ZERO
#define UC_MACRO_NAME_AA51 0xAA51 // ꩑ CHAM DIGIT ONE
#define UC_MACRO_NAME_AA52 0xAA52 // ꩒ CHAM DIGIT TWO
#define UC_MACRO_NAME_AA53 0xAA53 // ꩓ CHAM DIGIT THREE
#define UC_MACRO_NAME_AA54 0xAA54 // ꩔ CHAM DIGIT FOUR
#define UC_MACRO_NAME_AA55 0xAA55 // ꩕ CHAM DIGIT FIVE
#define UC_MACRO_NAME_AA56 0xAA56 // ꩖ CHAM DIGIT SIX
#define UC_MACRO_NAME_AA57 0xAA57 // ꩗ CHAM DIGIT SEVEN
#define UC_MACRO_NAME_AA58 0xAA58 // ꩘ CHAM DIGIT EIGHT
#define UC_MACRO_NAME_AA59 0xAA59 // ꩙ CHAM DIGIT NINE
#define UC_MACRO_NAME_AA5C 0xAA5C // ꩜ CHAM PUNCTUATION SPIRAL
#define UC_MACRO_NAME_AA5D 0xAA5D // ꩝ CHAM PUNCTUATION DANDA
#define UC_MACRO_NAME_AA5E 0xAA5E // ꩞ CHAM PUNCTUATION DOUBLE DANDA
#define UC_MACRO_NAME_AA5F 0xAA5F // ꩟ CHAM PUNCTUATION TRIPLE DANDA


#endif // UC_H_CHAM
