/*
 * Unicode Block: Cherokee
 * Range: U+13A0..U+13FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * The Cherokee ( / ˈ tʃ ɛr ə k iː / CHEH -rə-kee , / ˌ tʃ ɛr ə ˈ k iː /
 * ⓘ CHEH -rə- KEE ; Cherokee : ᎠᏂᏴᏫᏯᎢ , romanized: Aniyvwiyaʔi /
 * Anigiduwagi , or ᏣᎳᎩ , Tsalagi ) people are one of the Indigenous
 * peoples of the Southeastern Woodlands of the United States . Prior to
 * the 18th century, they were concentrated in their homelands, in towns
 * along river valleys of what is now southwestern North Carolina ,
 * southeastern Tennessee , southwestern Virginia , edges of western
 * South Carolina , northern Georgia and northeastern Alabama with
 * hunting grounds in Kentucky , together consisting of around 40,000
 * square miles.
 * The Cherokee language is part of the Iroquoian language group. In the
 * 19th century, James Mooney , an early American ethnographer , recorded
 * one oral tradition that told of the tribe having migrated south in
 * ancient times from the Great Lakes region, where other Iroquoian
 * peoples have been based. However, anthropologist Thomas R. Whyte,
 * writing in 2007, dated the split among the peoples as occurring
 * earlier. He believes that the origin of the proto-Iroquoian language
 * was likely the Appalachian region , and the split between Northern and
 * Southern Iroquoian languages began 4,000 years ago.
 *
 */
#ifndef UC_H_CHEROKEE
#define UC_H_CHEROKEE

#define UC_MACRO_NAME_13A0 0x13A0 // Ꭰ CHEROKEE LETTER A
#define UC_MACRO_NAME_13A1 0x13A1 // Ꭱ CHEROKEE LETTER E
#define UC_MACRO_NAME_13A2 0x13A2 // Ꭲ CHEROKEE LETTER I
#define UC_MACRO_NAME_13A3 0x13A3 // Ꭳ CHEROKEE LETTER O
#define UC_MACRO_NAME_13A4 0x13A4 // Ꭴ CHEROKEE LETTER U
#define UC_MACRO_NAME_13A5 0x13A5 // Ꭵ CHEROKEE LETTER V
#define UC_MACRO_NAME_13A6 0x13A6 // Ꭶ CHEROKEE LETTER GA
#define UC_MACRO_NAME_13A7 0x13A7 // Ꭷ CHEROKEE LETTER KA
#define UC_MACRO_NAME_13A8 0x13A8 // Ꭸ CHEROKEE LETTER GE
#define UC_MACRO_NAME_13A9 0x13A9 // Ꭹ CHEROKEE LETTER GI
#define UC_MACRO_NAME_13AA 0x13AA // Ꭺ CHEROKEE LETTER GO
#define UC_MACRO_NAME_13AB 0x13AB // Ꭻ CHEROKEE LETTER GU
#define UC_MACRO_NAME_13AC 0x13AC // Ꭼ CHEROKEE LETTER GV
#define UC_MACRO_NAME_13AD 0x13AD // Ꭽ CHEROKEE LETTER HA
#define UC_MACRO_NAME_13AE 0x13AE // Ꭾ CHEROKEE LETTER HE
#define UC_MACRO_NAME_13AF 0x13AF // Ꭿ CHEROKEE LETTER HI
#define UC_MACRO_NAME_13B0 0x13B0 // Ꮀ CHEROKEE LETTER HO
#define UC_MACRO_NAME_13B1 0x13B1 // Ꮁ CHEROKEE LETTER HU
#define UC_MACRO_NAME_13B2 0x13B2 // Ꮂ CHEROKEE LETTER HV
#define UC_MACRO_NAME_13B3 0x13B3 // Ꮃ CHEROKEE LETTER LA
#define UC_MACRO_NAME_13B4 0x13B4 // Ꮄ CHEROKEE LETTER LE
#define UC_MACRO_NAME_13B5 0x13B5 // Ꮅ CHEROKEE LETTER LI
#define UC_MACRO_NAME_13B6 0x13B6 // Ꮆ CHEROKEE LETTER LO
#define UC_MACRO_NAME_13B7 0x13B7 // Ꮇ CHEROKEE LETTER LU
#define UC_MACRO_NAME_13B8 0x13B8 // Ꮈ CHEROKEE LETTER LV
#define UC_MACRO_NAME_13B9 0x13B9 // Ꮉ CHEROKEE LETTER MA
#define UC_MACRO_NAME_13BA 0x13BA // Ꮊ CHEROKEE LETTER ME
#define UC_MACRO_NAME_13BB 0x13BB // Ꮋ CHEROKEE LETTER MI
#define UC_MACRO_NAME_13BC 0x13BC // Ꮌ CHEROKEE LETTER MO
#define UC_MACRO_NAME_13BD 0x13BD // Ꮍ CHEROKEE LETTER MU
#define UC_MACRO_NAME_13BE 0x13BE // Ꮎ CHEROKEE LETTER NA
#define UC_MACRO_NAME_13BF 0x13BF // Ꮏ CHEROKEE LETTER HNA
#define UC_MACRO_NAME_13C0 0x13C0 // Ꮐ CHEROKEE LETTER NAH
#define UC_MACRO_NAME_13C1 0x13C1 // Ꮑ CHEROKEE LETTER NE
#define UC_MACRO_NAME_13C2 0x13C2 // Ꮒ CHEROKEE LETTER NI
#define UC_MACRO_NAME_13C3 0x13C3 // Ꮓ CHEROKEE LETTER NO
#define UC_MACRO_NAME_13C4 0x13C4 // Ꮔ CHEROKEE LETTER NU
#define UC_MACRO_NAME_13C5 0x13C5 // Ꮕ CHEROKEE LETTER NV
#define UC_MACRO_NAME_13C6 0x13C6 // Ꮖ CHEROKEE LETTER QUA
#define UC_MACRO_NAME_13C7 0x13C7 // Ꮗ CHEROKEE LETTER QUE
#define UC_MACRO_NAME_13C8 0x13C8 // Ꮘ CHEROKEE LETTER QUI
#define UC_MACRO_NAME_13C9 0x13C9 // Ꮙ CHEROKEE LETTER QUO
#define UC_MACRO_NAME_13CA 0x13CA // Ꮚ CHEROKEE LETTER QUU
#define UC_MACRO_NAME_13CB 0x13CB // Ꮛ CHEROKEE LETTER QUV
#define UC_MACRO_NAME_13CC 0x13CC // Ꮜ CHEROKEE LETTER SA
#define UC_MACRO_NAME_13CD 0x13CD // Ꮝ CHEROKEE LETTER S
#define UC_MACRO_NAME_13CE 0x13CE // Ꮞ CHEROKEE LETTER SE
#define UC_MACRO_NAME_13CF 0x13CF // Ꮟ CHEROKEE LETTER SI
#define UC_MACRO_NAME_13D0 0x13D0 // Ꮠ CHEROKEE LETTER SO
#define UC_MACRO_NAME_13D1 0x13D1 // Ꮡ CHEROKEE LETTER SU
#define UC_MACRO_NAME_13D2 0x13D2 // Ꮢ CHEROKEE LETTER SV
#define UC_MACRO_NAME_13D3 0x13D3 // Ꮣ CHEROKEE LETTER DA
#define UC_MACRO_NAME_13D4 0x13D4 // Ꮤ CHEROKEE LETTER TA
#define UC_MACRO_NAME_13D5 0x13D5 // Ꮥ CHEROKEE LETTER DE
#define UC_MACRO_NAME_13D6 0x13D6 // Ꮦ CHEROKEE LETTER TE
#define UC_MACRO_NAME_13D7 0x13D7 // Ꮧ CHEROKEE LETTER DI
#define UC_MACRO_NAME_13D8 0x13D8 // Ꮨ CHEROKEE LETTER TI
#define UC_MACRO_NAME_13D9 0x13D9 // Ꮩ CHEROKEE LETTER DO
#define UC_MACRO_NAME_13DA 0x13DA // Ꮪ CHEROKEE LETTER DU
#define UC_MACRO_NAME_13DB 0x13DB // Ꮫ CHEROKEE LETTER DV
#define UC_MACRO_NAME_13DC 0x13DC // Ꮬ CHEROKEE LETTER DLA
#define UC_MACRO_NAME_13DD 0x13DD // Ꮭ CHEROKEE LETTER TLA
#define UC_MACRO_NAME_13DE 0x13DE // Ꮮ CHEROKEE LETTER TLE
#define UC_MACRO_NAME_13DF 0x13DF // Ꮯ CHEROKEE LETTER TLI
#define UC_MACRO_NAME_13E0 0x13E0 // Ꮰ CHEROKEE LETTER TLO
#define UC_MACRO_NAME_13E1 0x13E1 // Ꮱ CHEROKEE LETTER TLU
#define UC_MACRO_NAME_13E2 0x13E2 // Ꮲ CHEROKEE LETTER TLV
#define UC_MACRO_NAME_13E3 0x13E3 // Ꮳ CHEROKEE LETTER TSA
#define UC_MACRO_NAME_13E4 0x13E4 // Ꮴ CHEROKEE LETTER TSE
#define UC_MACRO_NAME_13E5 0x13E5 // Ꮵ CHEROKEE LETTER TSI
#define UC_MACRO_NAME_13E6 0x13E6 // Ꮶ CHEROKEE LETTER TSO
#define UC_MACRO_NAME_13E7 0x13E7 // Ꮷ CHEROKEE LETTER TSU
#define UC_MACRO_NAME_13E8 0x13E8 // Ꮸ CHEROKEE LETTER TSV
#define UC_MACRO_NAME_13E9 0x13E9 // Ꮹ CHEROKEE LETTER WA
#define UC_MACRO_NAME_13EA 0x13EA // Ꮺ CHEROKEE LETTER WE
#define UC_MACRO_NAME_13EB 0x13EB // Ꮻ CHEROKEE LETTER WI
#define UC_MACRO_NAME_13EC 0x13EC // Ꮼ CHEROKEE LETTER WO
#define UC_MACRO_NAME_13ED 0x13ED // Ꮽ CHEROKEE LETTER WU
#define UC_MACRO_NAME_13EE 0x13EE // Ꮾ CHEROKEE LETTER WV
#define UC_MACRO_NAME_13EF 0x13EF // Ꮿ CHEROKEE LETTER YA
#define UC_MACRO_NAME_13F0 0x13F0 // Ᏸ CHEROKEE LETTER YE
#define UC_MACRO_NAME_13F1 0x13F1 // Ᏹ CHEROKEE LETTER YI
#define UC_MACRO_NAME_13F2 0x13F2 // Ᏺ CHEROKEE LETTER YO
#define UC_MACRO_NAME_13F3 0x13F3 // Ᏻ CHEROKEE LETTER YU
#define UC_MACRO_NAME_13F4 0x13F4 // Ᏼ CHEROKEE LETTER YV
#define UC_MACRO_NAME_13F5 0x13F5 // Ᏽ CHEROKEE LETTER MV
#define UC_MACRO_NAME_13F8 0x13F8 // ᏸ CHEROKEE SMALL LETTER YE
#define UC_MACRO_NAME_13F9 0x13F9 // ᏹ CHEROKEE SMALL LETTER YI
#define UC_MACRO_NAME_13FA 0x13FA // ᏺ CHEROKEE SMALL LETTER YO
#define UC_MACRO_NAME_13FB 0x13FB // ᏻ CHEROKEE SMALL LETTER YU
#define UC_MACRO_NAME_13FC 0x13FC // ᏼ CHEROKEE SMALL LETTER YV
#define UC_MACRO_NAME_13FD 0x13FD // ᏽ CHEROKEE SMALL LETTER MV


#endif // UC_H_CHEROKEE
