/*
 * Unicode Block: Combining Diacritical Marks for Symbols
 * Range: U+20D0..U+20FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_COMBINING_DIACRITICAL_MARKS_FOR_SYMBOLS
#define UC_H_COMBINING_DIACRITICAL_MARKS_FOR_SYMBOLS

#define UC_MACRO_NAME_20D0 0x20D0 // ⃐ COMBINING LEFT HARPOON ABOVE
#define UC_MACRO_NAME_20D1 0x20D1 // ⃑ COMBINING RIGHT HARPOON ABOVE
#define UC_MACRO_NAME_20D2 0x20D2 // ⃒ COMBINING LONG VERTICAL LINE OVERLAY
#define UC_MACRO_NAME_20D3 0x20D3 // ⃓ COMBINING SHORT VERTICAL LINE OVERLAY
#define UC_MACRO_NAME_20D4 0x20D4 // ⃔ COMBINING ANTICLOCKWISE ARROW ABOVE
#define UC_MACRO_NAME_20D5 0x20D5 // ⃕ COMBINING CLOCKWISE ARROW ABOVE
#define UC_MACRO_NAME_20D6 0x20D6 // ⃖ COMBINING LEFT ARROW ABOVE
#define UC_MACRO_NAME_20D7 0x20D7 // ⃗ COMBINING RIGHT ARROW ABOVE
#define UC_MACRO_NAME_20D8 0x20D8 // ⃘ COMBINING RING OVERLAY
#define UC_MACRO_NAME_20D9 0x20D9 // ⃙ COMBINING CLOCKWISE RING OVERLAY
#define UC_MACRO_NAME_20DA 0x20DA // ⃚ COMBINING ANTICLOCKWISE RING OVERLAY
#define UC_MACRO_NAME_20DB 0x20DB // ⃛ COMBINING THREE DOTS ABOVE
#define UC_MACRO_NAME_20DC 0x20DC // ⃜ COMBINING FOUR DOTS ABOVE
#define UC_MACRO_NAME_20DD 0x20DD // ⃝ COMBINING ENCLOSING CIRCLE
#define UC_MACRO_NAME_20DE 0x20DE // ⃞ COMBINING ENCLOSING SQUARE
#define UC_MACRO_NAME_20DF 0x20DF // ⃟ COMBINING ENCLOSING DIAMOND
#define UC_MACRO_NAME_20E0 0x20E0 // ⃠ COMBINING ENCLOSING CIRCLE BACKSLASH
#define UC_MACRO_NAME_20E1 0x20E1 // ⃡ COMBINING LEFT RIGHT ARROW ABOVE
#define UC_MACRO_NAME_20E2 0x20E2 // ⃢ COMBINING ENCLOSING SCREEN
#define UC_MACRO_NAME_20E3 0x20E3 // ⃣ COMBINING ENCLOSING KEYCAP
#define UC_MACRO_NAME_20E4 0x20E4 // ⃤ COMBINING ENCLOSING UPWARD POINTING TRIANGLE
#define UC_MACRO_NAME_20E5 0x20E5 // ⃥ COMBINING REVERSE SOLIDUS OVERLAY
#define UC_MACRO_NAME_20E6 0x20E6 // ⃦ COMBINING DOUBLE VERTICAL STROKE OVERLAY
#define UC_MACRO_NAME_20E7 0x20E7 // ⃧ COMBINING ANNUITY SYMBOL
#define UC_MACRO_NAME_20E8 0x20E8 // ⃨ COMBINING TRIPLE UNDERDOT
#define UC_MACRO_NAME_20E9 0x20E9 // ⃩ COMBINING WIDE BRIDGE ABOVE
#define UC_MACRO_NAME_20EA 0x20EA // ⃪ COMBINING LEFTWARDS ARROW OVERLAY
#define UC_MACRO_NAME_20EB 0x20EB // ⃫ COMBINING LONG DOUBLE SOLIDUS OVERLAY
#define UC_MACRO_NAME_20EC 0x20EC // ⃬ COMBINING RIGHTWARDS HARPOON WITH BARB DOWNWARDS
#define UC_MACRO_NAME_20ED 0x20ED // ⃭ COMBINING LEFTWARDS HARPOON WITH BARB DOWNWARDS
#define UC_MACRO_NAME_20EE 0x20EE // ⃮ COMBINING LEFT ARROW BELOW
#define UC_MACRO_NAME_20EF 0x20EF // ⃯ COMBINING RIGHT ARROW BELOW
#define UC_MACRO_NAME_20F0 0x20F0 // ⃰ COMBINING ASTERISK ABOVE


#endif // UC_H_COMBINING_DIACRITICAL_MARKS_FOR_SYMBOLS
