/*
 * Unicode Block: Chorasmian
 * Range: U+10FB0..U+10FDF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * The name Khwarazmian (also Khwarezmian , Khwarizmim , Khorezmian ,
 * Chorasmian , Carizmian , and others) may refer to:
 *
 */
#ifndef UC_H_CHORASMIAN
#define UC_H_CHORASMIAN

#define UC_MACRO_NAME_10FB0 0x10FB0 // 𐾰 CHORASMIAN LETTER ALEPH
#define UC_MACRO_NAME_10FB1 0x10FB1 // 𐾱 CHORASMIAN LETTER SMALL ALEPH
#define UC_MACRO_NAME_10FB2 0x10FB2 // 𐾲 CHORASMIAN LETTER BETH
#define UC_MACRO_NAME_10FB3 0x10FB3 // 𐾳 CHORASMIAN LETTER GIMEL
#define UC_MACRO_NAME_10FB4 0x10FB4 // 𐾴 CHORASMIAN LETTER DALETH
#define UC_MACRO_NAME_10FB5 0x10FB5 // 𐾵 CHORASMIAN LETTER HE
#define UC_MACRO_NAME_10FB6 0x10FB6 // 𐾶 CHORASMIAN LETTER WAW
#define UC_MACRO_NAME_10FB7 0x10FB7 // 𐾷 CHORASMIAN LETTER CURLED WAW
#define UC_MACRO_NAME_10FB8 0x10FB8 // 𐾸 CHORASMIAN LETTER ZAYIN
#define UC_MACRO_NAME_10FB9 0x10FB9 // 𐾹 CHORASMIAN LETTER HETH
#define UC_MACRO_NAME_10FBA 0x10FBA // 𐾺 CHORASMIAN LETTER YODH
#define UC_MACRO_NAME_10FBB 0x10FBB // 𐾻 CHORASMIAN LETTER KAPH
#define UC_MACRO_NAME_10FBC 0x10FBC // 𐾼 CHORASMIAN LETTER LAMEDH
#define UC_MACRO_NAME_10FBD 0x10FBD // 𐾽 CHORASMIAN LETTER MEM
#define UC_MACRO_NAME_10FBE 0x10FBE // 𐾾 CHORASMIAN LETTER NUN
#define UC_MACRO_NAME_10FBF 0x10FBF // 𐾿 CHORASMIAN LETTER SAMEKH
#define UC_MACRO_NAME_10FC0 0x10FC0 // 𐿀 CHORASMIAN LETTER AYIN
#define UC_MACRO_NAME_10FC1 0x10FC1 // 𐿁 CHORASMIAN LETTER PE
#define UC_MACRO_NAME_10FC2 0x10FC2 // 𐿂 CHORASMIAN LETTER RESH
#define UC_MACRO_NAME_10FC3 0x10FC3 // 𐿃 CHORASMIAN LETTER SHIN
#define UC_MACRO_NAME_10FC4 0x10FC4 // 𐿄 CHORASMIAN LETTER TAW
#define UC_MACRO_NAME_10FC5 0x10FC5 // 𐿅 CHORASMIAN NUMBER ONE
#define UC_MACRO_NAME_10FC6 0x10FC6 // 𐿆 CHORASMIAN NUMBER TWO
#define UC_MACRO_NAME_10FC7 0x10FC7 // 𐿇 CHORASMIAN NUMBER THREE
#define UC_MACRO_NAME_10FC8 0x10FC8 // 𐿈 CHORASMIAN NUMBER FOUR
#define UC_MACRO_NAME_10FC9 0x10FC9 // 𐿉 CHORASMIAN NUMBER TEN
#define UC_MACRO_NAME_10FCA 0x10FCA // 𐿊 CHORASMIAN NUMBER TWENTY
#define UC_MACRO_NAME_10FCB 0x10FCB // 𐿋 CHORASMIAN NUMBER ONE HUNDRED


#endif // UC_H_CHORASMIAN
