/*
 * Unicode Block: Coptic
 * Range: U+2C80..U+2CFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Coptic may refer to:
 *
 */
#ifndef UC_H_COPTIC
#define UC_H_COPTIC

#define UC_MACRO_NAME_2C80 0x2C80 // Ⲁ COPTIC CAPITAL LETTER ALFA
#define UC_MACRO_NAME_2C81 0x2C81 // ⲁ COPTIC SMALL LETTER ALFA
#define UC_MACRO_NAME_2C82 0x2C82 // Ⲃ COPTIC CAPITAL LETTER VIDA
#define UC_MACRO_NAME_2C83 0x2C83 // ⲃ COPTIC SMALL LETTER VIDA
#define UC_MACRO_NAME_2C84 0x2C84 // Ⲅ COPTIC CAPITAL LETTER GAMMA
#define UC_MACRO_NAME_2C85 0x2C85 // ⲅ COPTIC SMALL LETTER GAMMA
#define UC_MACRO_NAME_2C86 0x2C86 // Ⲇ COPTIC CAPITAL LETTER DALDA
#define UC_MACRO_NAME_2C87 0x2C87 // ⲇ COPTIC SMALL LETTER DALDA
#define UC_MACRO_NAME_2C88 0x2C88 // Ⲉ COPTIC CAPITAL LETTER EIE
#define UC_MACRO_NAME_2C89 0x2C89 // ⲉ COPTIC SMALL LETTER EIE
#define UC_MACRO_NAME_2C8A 0x2C8A // Ⲋ COPTIC CAPITAL LETTER SOU
#define UC_MACRO_NAME_2C8B 0x2C8B // ⲋ COPTIC SMALL LETTER SOU
#define UC_MACRO_NAME_2C8C 0x2C8C // Ⲍ COPTIC CAPITAL LETTER ZATA
#define UC_MACRO_NAME_2C8D 0x2C8D // ⲍ COPTIC SMALL LETTER ZATA
#define UC_MACRO_NAME_2C8E 0x2C8E // Ⲏ COPTIC CAPITAL LETTER HATE
#define UC_MACRO_NAME_2C8F 0x2C8F // ⲏ COPTIC SMALL LETTER HATE
#define UC_MACRO_NAME_2C90 0x2C90 // Ⲑ COPTIC CAPITAL LETTER THETHE
#define UC_MACRO_NAME_2C91 0x2C91 // ⲑ COPTIC SMALL LETTER THETHE
#define UC_MACRO_NAME_2C92 0x2C92 // Ⲓ COPTIC CAPITAL LETTER IAUDA
#define UC_MACRO_NAME_2C93 0x2C93 // ⲓ COPTIC SMALL LETTER IAUDA
#define UC_MACRO_NAME_2C94 0x2C94 // Ⲕ COPTIC CAPITAL LETTER KAPA
#define UC_MACRO_NAME_2C95 0x2C95 // ⲕ COPTIC SMALL LETTER KAPA
#define UC_MACRO_NAME_2C96 0x2C96 // Ⲗ COPTIC CAPITAL LETTER LAULA
#define UC_MACRO_NAME_2C97 0x2C97 // ⲗ COPTIC SMALL LETTER LAULA
#define UC_MACRO_NAME_2C98 0x2C98 // Ⲙ COPTIC CAPITAL LETTER MI
#define UC_MACRO_NAME_2C99 0x2C99 // ⲙ COPTIC SMALL LETTER MI
#define UC_MACRO_NAME_2C9A 0x2C9A // Ⲛ COPTIC CAPITAL LETTER NI
#define UC_MACRO_NAME_2C9B 0x2C9B // ⲛ COPTIC SMALL LETTER NI
#define UC_MACRO_NAME_2C9C 0x2C9C // Ⲝ COPTIC CAPITAL LETTER KSI
#define UC_MACRO_NAME_2C9D 0x2C9D // ⲝ COPTIC SMALL LETTER KSI
#define UC_MACRO_NAME_2C9E 0x2C9E // Ⲟ COPTIC CAPITAL LETTER O
#define UC_MACRO_NAME_2C9F 0x2C9F // ⲟ COPTIC SMALL LETTER O
#define UC_MACRO_NAME_2CA0 0x2CA0 // Ⲡ COPTIC CAPITAL LETTER PI
#define UC_MACRO_NAME_2CA1 0x2CA1 // ⲡ COPTIC SMALL LETTER PI
#define UC_MACRO_NAME_2CA2 0x2CA2 // Ⲣ COPTIC CAPITAL LETTER RO
#define UC_MACRO_NAME_2CA3 0x2CA3 // ⲣ COPTIC SMALL LETTER RO
#define UC_MACRO_NAME_2CA4 0x2CA4 // Ⲥ COPTIC CAPITAL LETTER SIMA
#define UC_MACRO_NAME_2CA5 0x2CA5 // ⲥ COPTIC SMALL LETTER SIMA
#define UC_MACRO_NAME_2CA6 0x2CA6 // Ⲧ COPTIC CAPITAL LETTER TAU
#define UC_MACRO_NAME_2CA7 0x2CA7 // ⲧ COPTIC SMALL LETTER TAU
#define UC_MACRO_NAME_2CA8 0x2CA8 // Ⲩ COPTIC CAPITAL LETTER UA
#define UC_MACRO_NAME_2CA9 0x2CA9 // ⲩ COPTIC SMALL LETTER UA
#define UC_MACRO_NAME_2CAA 0x2CAA // Ⲫ COPTIC CAPITAL LETTER FI
#define UC_MACRO_NAME_2CAB 0x2CAB // ⲫ COPTIC SMALL LETTER FI
#define UC_MACRO_NAME_2CAC 0x2CAC // Ⲭ COPTIC CAPITAL LETTER KHI
#define UC_MACRO_NAME_2CAD 0x2CAD // ⲭ COPTIC SMALL LETTER KHI
#define UC_MACRO_NAME_2CAE 0x2CAE // Ⲯ COPTIC CAPITAL LETTER PSI
#define UC_MACRO_NAME_2CAF 0x2CAF // ⲯ COPTIC SMALL LETTER PSI
#define UC_MACRO_NAME_2CB0 0x2CB0 // Ⲱ COPTIC CAPITAL LETTER OOU
#define UC_MACRO_NAME_2CB1 0x2CB1 // ⲱ COPTIC SMALL LETTER OOU
#define UC_MACRO_NAME_2CB2 0x2CB2 // Ⲳ COPTIC CAPITAL LETTER DIALECT-P ALEF
#define UC_MACRO_NAME_2CB3 0x2CB3 // ⲳ COPTIC SMALL LETTER DIALECT-P ALEF
#define UC_MACRO_NAME_2CB4 0x2CB4 // Ⲵ COPTIC CAPITAL LETTER OLD COPTIC AIN
#define UC_MACRO_NAME_2CB5 0x2CB5 // ⲵ COPTIC SMALL LETTER OLD COPTIC AIN
#define UC_MACRO_NAME_2CB6 0x2CB6 // Ⲷ COPTIC CAPITAL LETTER CRYPTOGRAMMIC EIE
#define UC_MACRO_NAME_2CB7 0x2CB7 // ⲷ COPTIC SMALL LETTER CRYPTOGRAMMIC EIE
#define UC_MACRO_NAME_2CB8 0x2CB8 // Ⲹ COPTIC CAPITAL LETTER DIALECT-P KAPA
#define UC_MACRO_NAME_2CB9 0x2CB9 // ⲹ COPTIC SMALL LETTER DIALECT-P KAPA
#define UC_MACRO_NAME_2CBA 0x2CBA // Ⲻ COPTIC CAPITAL LETTER DIALECT-P NI
#define UC_MACRO_NAME_2CBB 0x2CBB // ⲻ COPTIC SMALL LETTER DIALECT-P NI
#define UC_MACRO_NAME_2CBC 0x2CBC // Ⲽ COPTIC CAPITAL LETTER CRYPTOGRAMMIC NI
#define UC_MACRO_NAME_2CBD 0x2CBD // ⲽ COPTIC SMALL LETTER CRYPTOGRAMMIC NI
#define UC_MACRO_NAME_2CBE 0x2CBE // Ⲿ COPTIC CAPITAL LETTER OLD COPTIC OOU
#define UC_MACRO_NAME_2CBF 0x2CBF // ⲿ COPTIC SMALL LETTER OLD COPTIC OOU
#define UC_MACRO_NAME_2CC0 0x2CC0 // Ⳁ COPTIC CAPITAL LETTER SAMPI
#define UC_MACRO_NAME_2CC1 0x2CC1 // ⳁ COPTIC SMALL LETTER SAMPI
#define UC_MACRO_NAME_2CC2 0x2CC2 // Ⳃ COPTIC CAPITAL LETTER CROSSED SHEI
#define UC_MACRO_NAME_2CC3 0x2CC3 // ⳃ COPTIC SMALL LETTER CROSSED SHEI
#define UC_MACRO_NAME_2CC4 0x2CC4 // Ⳅ COPTIC CAPITAL LETTER OLD COPTIC SHEI
#define UC_MACRO_NAME_2CC5 0x2CC5 // ⳅ COPTIC SMALL LETTER OLD COPTIC SHEI
#define UC_MACRO_NAME_2CC6 0x2CC6 // Ⳇ COPTIC CAPITAL LETTER OLD COPTIC ESH
#define UC_MACRO_NAME_2CC7 0x2CC7 // ⳇ COPTIC SMALL LETTER OLD COPTIC ESH
#define UC_MACRO_NAME_2CC8 0x2CC8 // Ⳉ COPTIC CAPITAL LETTER AKHMIMIC KHEI
#define UC_MACRO_NAME_2CC9 0x2CC9 // ⳉ COPTIC SMALL LETTER AKHMIMIC KHEI
#define UC_MACRO_NAME_2CCA 0x2CCA // Ⳋ COPTIC CAPITAL LETTER DIALECT-P HORI
#define UC_MACRO_NAME_2CCB 0x2CCB // ⳋ COPTIC SMALL LETTER DIALECT-P HORI
#define UC_MACRO_NAME_2CCC 0x2CCC // Ⳍ COPTIC CAPITAL LETTER OLD COPTIC HORI
#define UC_MACRO_NAME_2CCD 0x2CCD // ⳍ COPTIC SMALL LETTER OLD COPTIC HORI
#define UC_MACRO_NAME_2CCE 0x2CCE // Ⳏ COPTIC CAPITAL LETTER OLD COPTIC HA
#define UC_MACRO_NAME_2CCF 0x2CCF // ⳏ COPTIC SMALL LETTER OLD COPTIC HA
#define UC_MACRO_NAME_2CD0 0x2CD0 // Ⳑ COPTIC CAPITAL LETTER L-SHAPED HA
#define UC_MACRO_NAME_2CD1 0x2CD1 // ⳑ COPTIC SMALL LETTER L-SHAPED HA
#define UC_MACRO_NAME_2CD2 0x2CD2 // Ⳓ COPTIC CAPITAL LETTER OLD COPTIC HEI
#define UC_MACRO_NAME_2CD3 0x2CD3 // ⳓ COPTIC SMALL LETTER OLD COPTIC HEI
#define UC_MACRO_NAME_2CD4 0x2CD4 // Ⳕ COPTIC CAPITAL LETTER OLD COPTIC HAT
#define UC_MACRO_NAME_2CD5 0x2CD5 // ⳕ COPTIC SMALL LETTER OLD COPTIC HAT
#define UC_MACRO_NAME_2CD6 0x2CD6 // Ⳗ COPTIC CAPITAL LETTER OLD COPTIC GANGIA
#define UC_MACRO_NAME_2CD7 0x2CD7 // ⳗ COPTIC SMALL LETTER OLD COPTIC GANGIA
#define UC_MACRO_NAME_2CD8 0x2CD8 // Ⳙ COPTIC CAPITAL LETTER OLD COPTIC DJA
#define UC_MACRO_NAME_2CD9 0x2CD9 // ⳙ COPTIC SMALL LETTER OLD COPTIC DJA
#define UC_MACRO_NAME_2CDA 0x2CDA // Ⳛ COPTIC CAPITAL LETTER OLD COPTIC SHIMA
#define UC_MACRO_NAME_2CDB 0x2CDB // ⳛ COPTIC SMALL LETTER OLD COPTIC SHIMA
#define UC_MACRO_NAME_2CDC 0x2CDC // Ⳝ COPTIC CAPITAL LETTER OLD NUBIAN SHIMA
#define UC_MACRO_NAME_2CDD 0x2CDD // ⳝ COPTIC SMALL LETTER OLD NUBIAN SHIMA
#define UC_MACRO_NAME_2CDE 0x2CDE // Ⳟ COPTIC CAPITAL LETTER OLD NUBIAN NGI
#define UC_MACRO_NAME_2CDF 0x2CDF // ⳟ COPTIC SMALL LETTER OLD NUBIAN NGI
#define UC_MACRO_NAME_2CE0 0x2CE0 // Ⳡ COPTIC CAPITAL LETTER OLD NUBIAN NYI
#define UC_MACRO_NAME_2CE1 0x2CE1 // ⳡ COPTIC SMALL LETTER OLD NUBIAN NYI
#define UC_MACRO_NAME_2CE2 0x2CE2 // Ⳣ COPTIC CAPITAL LETTER OLD NUBIAN WAU
#define UC_MACRO_NAME_2CE3 0x2CE3 // ⳣ COPTIC SMALL LETTER OLD NUBIAN WAU
#define UC_MACRO_NAME_2CE4 0x2CE4 // ⳤ COPTIC SYMBOL KAI
#define UC_MACRO_NAME_2CE5 0x2CE5 // ⳥ COPTIC SYMBOL MI RO
#define UC_MACRO_NAME_2CE6 0x2CE6 // ⳦ COPTIC SYMBOL PI RO
#define UC_MACRO_NAME_2CE7 0x2CE7 // ⳧ COPTIC SYMBOL STAUROS
#define UC_MACRO_NAME_2CE8 0x2CE8 // ⳨ COPTIC SYMBOL TAU RO
#define UC_MACRO_NAME_2CE9 0x2CE9 // ⳩ COPTIC SYMBOL KHI RO
#define UC_MACRO_NAME_2CEA 0x2CEA // ⳪ COPTIC SYMBOL SHIMA SIMA
#define UC_MACRO_NAME_2CEB 0x2CEB // Ⳬ COPTIC CAPITAL LETTER CRYPTOGRAMMIC SHEI
#define UC_MACRO_NAME_2CEC 0x2CEC // ⳬ COPTIC SMALL LETTER CRYPTOGRAMMIC SHEI
#define UC_MACRO_NAME_2CED 0x2CED // Ⳮ COPTIC CAPITAL LETTER CRYPTOGRAMMIC GANGIA
#define UC_MACRO_NAME_2CEE 0x2CEE // ⳮ COPTIC SMALL LETTER CRYPTOGRAMMIC GANGIA
#define UC_MACRO_NAME_2CEF 0x2CEF // ⳯ COPTIC COMBINING NI ABOVE
#define UC_MACRO_NAME_2CF0 0x2CF0 // ⳰ COPTIC COMBINING SPIRITUS ASPER
#define UC_MACRO_NAME_2CF1 0x2CF1 // ⳱ COPTIC COMBINING SPIRITUS LENIS
#define UC_MACRO_NAME_2CF2 0x2CF2 // Ⳳ COPTIC CAPITAL LETTER BOHAIRIC KHEI
#define UC_MACRO_NAME_2CF3 0x2CF3 // ⳳ COPTIC SMALL LETTER BOHAIRIC KHEI
#define UC_MACRO_NAME_2CF9 0x2CF9 // ⳹ COPTIC OLD NUBIAN FULL STOP
#define UC_MACRO_NAME_2CFA 0x2CFA // ⳺ COPTIC OLD NUBIAN DIRECT QUESTION MARK
#define UC_MACRO_NAME_2CFB 0x2CFB // ⳻ COPTIC OLD NUBIAN INDIRECT QUESTION MARK
#define UC_MACRO_NAME_2CFC 0x2CFC // ⳼ COPTIC OLD NUBIAN VERSE DIVIDER
#define UC_MACRO_NAME_2CFD 0x2CFD // ⳽ COPTIC FRACTION ONE HALF
#define UC_MACRO_NAME_2CFE 0x2CFE // ⳾ COPTIC FULL STOP
#define UC_MACRO_NAME_2CFF 0x2CFF // ⳿ COPTIC MORPHOLOGICAL DIVIDER


#endif // UC_H_COPTIC
