/*
 * Unicode Block: Combining Half Marks
 * Range: U+FE20..U+FE2F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Combining Half Marks is a Unicode block containing diacritical
 * combining characters for spanning multiple characters.
 *
 */
#ifndef UC_H_COMBINING_HALF_MARKS
#define UC_H_COMBINING_HALF_MARKS

#define UC_MACRO_NAME_FE20 0xFE20 // ︠ COMBINING LIGATURE LEFT HALF
#define UC_MACRO_NAME_FE21 0xFE21 // ︡ COMBINING LIGATURE RIGHT HALF
#define UC_MACRO_NAME_FE22 0xFE22 // ︢ COMBINING DOUBLE TILDE LEFT HALF
#define UC_MACRO_NAME_FE23 0xFE23 // ︣ COMBINING DOUBLE TILDE RIGHT HALF
#define UC_MACRO_NAME_FE24 0xFE24 // ︤ COMBINING MACRON LEFT HALF
#define UC_MACRO_NAME_FE25 0xFE25 // ︥ COMBINING MACRON RIGHT HALF
#define UC_MACRO_NAME_FE26 0xFE26 // ︦ COMBINING CONJOINING MACRON
#define UC_MACRO_NAME_FE27 0xFE27 // ︧ COMBINING LIGATURE LEFT HALF BELOW
#define UC_MACRO_NAME_FE28 0xFE28 // ︨ COMBINING LIGATURE RIGHT HALF BELOW
#define UC_MACRO_NAME_FE29 0xFE29 // ︩ COMBINING TILDE LEFT HALF BELOW
#define UC_MACRO_NAME_FE2A 0xFE2A // ︪ COMBINING TILDE RIGHT HALF BELOW
#define UC_MACRO_NAME_FE2B 0xFE2B // ︫ COMBINING MACRON LEFT HALF BELOW
#define UC_MACRO_NAME_FE2C 0xFE2C // ︬ COMBINING MACRON RIGHT HALF BELOW
#define UC_MACRO_NAME_FE2D 0xFE2D // ︭ COMBINING CONJOINING MACRON BELOW
#define UC_MACRO_NAME_FE2E 0xFE2E // ︮ COMBINING CYRILLIC TITLO LEFT HALF
#define UC_MACRO_NAME_FE2F 0xFE2F // ︯ COMBINING CYRILLIC TITLO RIGHT HALF


#endif // UC_H_COMBINING_HALF_MARKS
