/*
 * Unicode Block: Cyrillic
 * Range: U+0400..U+04FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * The Cyrillic script ( / s ɪ ˈ r ɪ l ɪ k / ⓘ sih- RI -lik ) is a
 * writing system used for various languages across Eurasia . It is the
 * designated national script in various Slavic , Turkic , Mongolic ,
 * Uralic , Caucasian and Iranic -speaking countries in Southeastern
 * Europe , Eastern Europe , the Caucasus , Central Asia , North Asia ,
 * and East Asia , and used by many other minority languages .
 * As of 2019 , around 250 million people in Eurasia use Cyrillic as the
 * official script for their national languages , with Russia accounting
 * for about half of them. With the accession of Bulgaria to the European
 * Union in 2007, Cyrillic became the third official script of the
 * European Union , following the Latin and Greek alphabets.
 *
 */
#ifndef UC_H_CYRILLIC
#define UC_H_CYRILLIC

#define UC_MACRO_NAME_400 0x0400 // Ѐ CYRILLIC CAPITAL LETTER IE WITH GRAVE
#define UC_MACRO_NAME_401 0x0401 // Ё CYRILLIC CAPITAL LETTER IO
#define UC_MACRO_NAME_402 0x0402 // Ђ CYRILLIC CAPITAL LETTER DJE
#define UC_MACRO_NAME_403 0x0403 // Ѓ CYRILLIC CAPITAL LETTER GJE
#define UC_MACRO_NAME_404 0x0404 // Є CYRILLIC CAPITAL LETTER UKRAINIAN IE
#define UC_MACRO_NAME_405 0x0405 // Ѕ CYRILLIC CAPITAL LETTER DZE
#define UC_MACRO_NAME_406 0x0406 // І CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I
#define UC_MACRO_NAME_407 0x0407 // Ї CYRILLIC CAPITAL LETTER YI
#define UC_MACRO_NAME_408 0x0408 // Ј CYRILLIC CAPITAL LETTER JE
#define UC_MACRO_NAME_409 0x0409 // Љ CYRILLIC CAPITAL LETTER LJE
#define UC_MACRO_NAME_40A 0x040A // Њ CYRILLIC CAPITAL LETTER NJE
#define UC_MACRO_NAME_40B 0x040B // Ћ CYRILLIC CAPITAL LETTER TSHE
#define UC_MACRO_NAME_40C 0x040C // Ќ CYRILLIC CAPITAL LETTER KJE
#define UC_MACRO_NAME_40D 0x040D // Ѝ CYRILLIC CAPITAL LETTER I WITH GRAVE
#define UC_MACRO_NAME_40E 0x040E // Ў CYRILLIC CAPITAL LETTER SHORT U
#define UC_MACRO_NAME_40F 0x040F // Џ CYRILLIC CAPITAL LETTER DZHE
#define UC_MACRO_NAME_410 0x0410 // А CYRILLIC CAPITAL LETTER A
#define UC_MACRO_NAME_411 0x0411 // Б CYRILLIC CAPITAL LETTER BE
#define UC_MACRO_NAME_412 0x0412 // В CYRILLIC CAPITAL LETTER VE
#define UC_MACRO_NAME_413 0x0413 // Г CYRILLIC CAPITAL LETTER GHE
#define UC_MACRO_NAME_414 0x0414 // Д CYRILLIC CAPITAL LETTER DE
#define UC_MACRO_NAME_415 0x0415 // Е CYRILLIC CAPITAL LETTER IE
#define UC_MACRO_NAME_416 0x0416 // Ж CYRILLIC CAPITAL LETTER ZHE
#define UC_MACRO_NAME_417 0x0417 // З CYRILLIC CAPITAL LETTER ZE
#define UC_MACRO_NAME_418 0x0418 // И CYRILLIC CAPITAL LETTER I
#define UC_MACRO_NAME_419 0x0419 // Й CYRILLIC CAPITAL LETTER SHORT I
#define UC_MACRO_NAME_41A 0x041A // К CYRILLIC CAPITAL LETTER KA
#define UC_MACRO_NAME_41B 0x041B // Л CYRILLIC CAPITAL LETTER EL
#define UC_MACRO_NAME_41C 0x041C // М CYRILLIC CAPITAL LETTER EM
#define UC_MACRO_NAME_41D 0x041D // Н CYRILLIC CAPITAL LETTER EN
#define UC_MACRO_NAME_41E 0x041E // О CYRILLIC CAPITAL LETTER O
#define UC_MACRO_NAME_41F 0x041F // П CYRILLIC CAPITAL LETTER PE
#define UC_MACRO_NAME_420 0x0420 // Р CYRILLIC CAPITAL LETTER ER
#define UC_MACRO_NAME_421 0x0421 // С CYRILLIC CAPITAL LETTER ES
#define UC_MACRO_NAME_422 0x0422 // Т CYRILLIC CAPITAL LETTER TE
#define UC_MACRO_NAME_423 0x0423 // У CYRILLIC CAPITAL LETTER U
#define UC_MACRO_NAME_424 0x0424 // Ф CYRILLIC CAPITAL LETTER EF
#define UC_MACRO_NAME_425 0x0425 // Х CYRILLIC CAPITAL LETTER HA
#define UC_MACRO_NAME_426 0x0426 // Ц CYRILLIC CAPITAL LETTER TSE
#define UC_MACRO_NAME_427 0x0427 // Ч CYRILLIC CAPITAL LETTER CHE
#define UC_MACRO_NAME_428 0x0428 // Ш CYRILLIC CAPITAL LETTER SHA
#define UC_MACRO_NAME_429 0x0429 // Щ CYRILLIC CAPITAL LETTER SHCHA
#define UC_MACRO_NAME_42A 0x042A // Ъ CYRILLIC CAPITAL LETTER HARD SIGN
#define UC_MACRO_NAME_42B 0x042B // Ы CYRILLIC CAPITAL LETTER YERU
#define UC_MACRO_NAME_42C 0x042C // Ь CYRILLIC CAPITAL LETTER SOFT SIGN
#define UC_MACRO_NAME_42D 0x042D // Э CYRILLIC CAPITAL LETTER E
#define UC_MACRO_NAME_42E 0x042E // Ю CYRILLIC CAPITAL LETTER YU
#define UC_MACRO_NAME_42F 0x042F // Я CYRILLIC CAPITAL LETTER YA
#define UC_MACRO_NAME_430 0x0430 // а CYRILLIC SMALL LETTER A
#define UC_MACRO_NAME_431 0x0431 // б CYRILLIC SMALL LETTER BE
#define UC_MACRO_NAME_432 0x0432 // в CYRILLIC SMALL LETTER VE
#define UC_MACRO_NAME_433 0x0433 // г CYRILLIC SMALL LETTER GHE
#define UC_MACRO_NAME_434 0x0434 // д CYRILLIC SMALL LETTER DE
#define UC_MACRO_NAME_435 0x0435 // е CYRILLIC SMALL LETTER IE
#define UC_MACRO_NAME_436 0x0436 // ж CYRILLIC SMALL LETTER ZHE
#define UC_MACRO_NAME_437 0x0437 // з CYRILLIC SMALL LETTER ZE
#define UC_MACRO_NAME_438 0x0438 // и CYRILLIC SMALL LETTER I
#define UC_MACRO_NAME_439 0x0439 // й CYRILLIC SMALL LETTER SHORT I
#define UC_MACRO_NAME_43A 0x043A // к CYRILLIC SMALL LETTER KA
#define UC_MACRO_NAME_43B 0x043B // л CYRILLIC SMALL LETTER EL
#define UC_MACRO_NAME_43C 0x043C // м CYRILLIC SMALL LETTER EM
#define UC_MACRO_NAME_43D 0x043D // н CYRILLIC SMALL LETTER EN
#define UC_MACRO_NAME_43E 0x043E // о CYRILLIC SMALL LETTER O
#define UC_MACRO_NAME_43F 0x043F // п CYRILLIC SMALL LETTER PE
#define UC_MACRO_NAME_440 0x0440 // р CYRILLIC SMALL LETTER ER
#define UC_MACRO_NAME_441 0x0441 // с CYRILLIC SMALL LETTER ES
#define UC_MACRO_NAME_442 0x0442 // т CYRILLIC SMALL LETTER TE
#define UC_MACRO_NAME_443 0x0443 // у CYRILLIC SMALL LETTER U
#define UC_MACRO_NAME_444 0x0444 // ф CYRILLIC SMALL LETTER EF
#define UC_MACRO_NAME_445 0x0445 // х CYRILLIC SMALL LETTER HA
#define UC_MACRO_NAME_446 0x0446 // ц CYRILLIC SMALL LETTER TSE
#define UC_MACRO_NAME_447 0x0447 // ч CYRILLIC SMALL LETTER CHE
#define UC_MACRO_NAME_448 0x0448 // ш CYRILLIC SMALL LETTER SHA
#define UC_MACRO_NAME_449 0x0449 // щ CYRILLIC SMALL LETTER SHCHA
#define UC_MACRO_NAME_44A 0x044A // ъ CYRILLIC SMALL LETTER HARD SIGN
#define UC_MACRO_NAME_44B 0x044B // ы CYRILLIC SMALL LETTER YERU
#define UC_MACRO_NAME_44C 0x044C // ь CYRILLIC SMALL LETTER SOFT SIGN
#define UC_MACRO_NAME_44D 0x044D // э CYRILLIC SMALL LETTER E
#define UC_MACRO_NAME_44E 0x044E // ю CYRILLIC SMALL LETTER YU
#define UC_MACRO_NAME_44F 0x044F // я CYRILLIC SMALL LETTER YA
#define UC_MACRO_NAME_450 0x0450 // ѐ CYRILLIC SMALL LETTER IE WITH GRAVE
#define UC_MACRO_NAME_451 0x0451 // ё CYRILLIC SMALL LETTER IO
#define UC_MACRO_NAME_452 0x0452 // ђ CYRILLIC SMALL LETTER DJE
#define UC_MACRO_NAME_453 0x0453 // ѓ CYRILLIC SMALL LETTER GJE
#define UC_MACRO_NAME_454 0x0454 // є CYRILLIC SMALL LETTER UKRAINIAN IE
#define UC_MACRO_NAME_455 0x0455 // ѕ CYRILLIC SMALL LETTER DZE
#define UC_MACRO_NAME_456 0x0456 // і CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
#define UC_MACRO_NAME_457 0x0457 // ї CYRILLIC SMALL LETTER YI
#define UC_MACRO_NAME_458 0x0458 // ј CYRILLIC SMALL LETTER JE
#define UC_MACRO_NAME_459 0x0459 // љ CYRILLIC SMALL LETTER LJE
#define UC_MACRO_NAME_45A 0x045A // њ CYRILLIC SMALL LETTER NJE
#define UC_MACRO_NAME_45B 0x045B // ћ CYRILLIC SMALL LETTER TSHE
#define UC_MACRO_NAME_45C 0x045C // ќ CYRILLIC SMALL LETTER KJE
#define UC_MACRO_NAME_45D 0x045D // ѝ CYRILLIC SMALL LETTER I WITH GRAVE
#define UC_MACRO_NAME_45E 0x045E // ў CYRILLIC SMALL LETTER SHORT U
#define UC_MACRO_NAME_45F 0x045F // џ CYRILLIC SMALL LETTER DZHE
#define UC_MACRO_NAME_460 0x0460 // Ѡ CYRILLIC CAPITAL LETTER OMEGA
#define UC_MACRO_NAME_461 0x0461 // ѡ CYRILLIC SMALL LETTER OMEGA
#define UC_MACRO_NAME_462 0x0462 // Ѣ CYRILLIC CAPITAL LETTER YAT
#define UC_MACRO_NAME_463 0x0463 // ѣ CYRILLIC SMALL LETTER YAT
#define UC_MACRO_NAME_464 0x0464 // Ѥ CYRILLIC CAPITAL LETTER IOTIFIED E
#define UC_MACRO_NAME_465 0x0465 // ѥ CYRILLIC SMALL LETTER IOTIFIED E
#define UC_MACRO_NAME_466 0x0466 // Ѧ CYRILLIC CAPITAL LETTER LITTLE YUS
#define UC_MACRO_NAME_467 0x0467 // ѧ CYRILLIC SMALL LETTER LITTLE YUS
#define UC_MACRO_NAME_468 0x0468 // Ѩ CYRILLIC CAPITAL LETTER IOTIFIED LITTLE YUS
#define UC_MACRO_NAME_469 0x0469 // ѩ CYRILLIC SMALL LETTER IOTIFIED LITTLE YUS
#define UC_MACRO_NAME_46A 0x046A // Ѫ CYRILLIC CAPITAL LETTER BIG YUS
#define UC_MACRO_NAME_46B 0x046B // ѫ CYRILLIC SMALL LETTER BIG YUS
#define UC_MACRO_NAME_46C 0x046C // Ѭ CYRILLIC CAPITAL LETTER IOTIFIED BIG YUS
#define UC_MACRO_NAME_46D 0x046D // ѭ CYRILLIC SMALL LETTER IOTIFIED BIG YUS
#define UC_MACRO_NAME_46E 0x046E // Ѯ CYRILLIC CAPITAL LETTER KSI
#define UC_MACRO_NAME_46F 0x046F // ѯ CYRILLIC SMALL LETTER KSI
#define UC_MACRO_NAME_470 0x0470 // Ѱ CYRILLIC CAPITAL LETTER PSI
#define UC_MACRO_NAME_471 0x0471 // ѱ CYRILLIC SMALL LETTER PSI
#define UC_MACRO_NAME_472 0x0472 // Ѳ CYRILLIC CAPITAL LETTER FITA
#define UC_MACRO_NAME_473 0x0473 // ѳ CYRILLIC SMALL LETTER FITA
#define UC_MACRO_NAME_474 0x0474 // Ѵ CYRILLIC CAPITAL LETTER IZHITSA
#define UC_MACRO_NAME_475 0x0475 // ѵ CYRILLIC SMALL LETTER IZHITSA
#define UC_MACRO_NAME_476 0x0476 // Ѷ CYRILLIC CAPITAL LETTER IZHITSA WITH DOUBLE GRAVE ACCENT
#define UC_MACRO_NAME_477 0x0477 // ѷ CYRILLIC SMALL LETTER IZHITSA WITH DOUBLE GRAVE ACCENT
#define UC_MACRO_NAME_478 0x0478 // Ѹ CYRILLIC CAPITAL LETTER UK
#define UC_MACRO_NAME_479 0x0479 // ѹ CYRILLIC SMALL LETTER UK
#define UC_MACRO_NAME_47A 0x047A // Ѻ CYRILLIC CAPITAL LETTER ROUND OMEGA
#define UC_MACRO_NAME_47B 0x047B // ѻ CYRILLIC SMALL LETTER ROUND OMEGA
#define UC_MACRO_NAME_47C 0x047C // Ѽ CYRILLIC CAPITAL LETTER OMEGA WITH TITLO
#define UC_MACRO_NAME_47D 0x047D // ѽ CYRILLIC SMALL LETTER OMEGA WITH TITLO
#define UC_MACRO_NAME_47E 0x047E // Ѿ CYRILLIC CAPITAL LETTER OT
#define UC_MACRO_NAME_47F 0x047F // ѿ CYRILLIC SMALL LETTER OT
#define UC_MACRO_NAME_480 0x0480 // Ҁ CYRILLIC CAPITAL LETTER KOPPA
#define UC_MACRO_NAME_481 0x0481 // ҁ CYRILLIC SMALL LETTER KOPPA
#define UC_MACRO_NAME_482 0x0482 // ҂ CYRILLIC THOUSANDS SIGN
#define UC_MACRO_NAME_483 0x0483 // ҃ COMBINING CYRILLIC TITLO
#define UC_MACRO_NAME_484 0x0484 // ҄ COMBINING CYRILLIC PALATALIZATION
#define UC_MACRO_NAME_485 0x0485 // ҅ COMBINING CYRILLIC DASIA PNEUMATA
#define UC_MACRO_NAME_486 0x0486 // ҆ COMBINING CYRILLIC PSILI PNEUMATA
#define UC_MACRO_NAME_487 0x0487 // ҇ COMBINING CYRILLIC POKRYTIE
#define UC_MACRO_NAME_488 0x0488 // ҈ COMBINING CYRILLIC HUNDRED THOUSANDS SIGN
#define UC_MACRO_NAME_489 0x0489 // ҉ COMBINING CYRILLIC MILLIONS SIGN
#define UC_MACRO_NAME_48A 0x048A // Ҋ CYRILLIC CAPITAL LETTER SHORT I WITH TAIL
#define UC_MACRO_NAME_48B 0x048B // ҋ CYRILLIC SMALL LETTER SHORT I WITH TAIL
#define UC_MACRO_NAME_48C 0x048C // Ҍ CYRILLIC CAPITAL LETTER SEMISOFT SIGN
#define UC_MACRO_NAME_48D 0x048D // ҍ CYRILLIC SMALL LETTER SEMISOFT SIGN
#define UC_MACRO_NAME_48E 0x048E // Ҏ CYRILLIC CAPITAL LETTER ER WITH TICK
#define UC_MACRO_NAME_48F 0x048F // ҏ CYRILLIC SMALL LETTER ER WITH TICK
#define UC_MACRO_NAME_490 0x0490 // Ґ CYRILLIC CAPITAL LETTER GHE WITH UPTURN
#define UC_MACRO_NAME_491 0x0491 // ґ CYRILLIC SMALL LETTER GHE WITH UPTURN
#define UC_MACRO_NAME_492 0x0492 // Ғ CYRILLIC CAPITAL LETTER GHE WITH STROKE
#define UC_MACRO_NAME_493 0x0493 // ғ CYRILLIC SMALL LETTER GHE WITH STROKE
#define UC_MACRO_NAME_494 0x0494 // Ҕ CYRILLIC CAPITAL LETTER GHE WITH MIDDLE HOOK
#define UC_MACRO_NAME_495 0x0495 // ҕ CYRILLIC SMALL LETTER GHE WITH MIDDLE HOOK
#define UC_MACRO_NAME_496 0x0496 // Җ CYRILLIC CAPITAL LETTER ZHE WITH DESCENDER
#define UC_MACRO_NAME_497 0x0497 // җ CYRILLIC SMALL LETTER ZHE WITH DESCENDER
#define UC_MACRO_NAME_498 0x0498 // Ҙ CYRILLIC CAPITAL LETTER ZE WITH DESCENDER
#define UC_MACRO_NAME_499 0x0499 // ҙ CYRILLIC SMALL LETTER ZE WITH DESCENDER
#define UC_MACRO_NAME_49A 0x049A // Қ CYRILLIC CAPITAL LETTER KA WITH DESCENDER
#define UC_MACRO_NAME_49B 0x049B // қ CYRILLIC SMALL LETTER KA WITH DESCENDER
#define UC_MACRO_NAME_49C 0x049C // Ҝ CYRILLIC CAPITAL LETTER KA WITH VERTICAL STROKE
#define UC_MACRO_NAME_49D 0x049D // ҝ CYRILLIC SMALL LETTER KA WITH VERTICAL STROKE
#define UC_MACRO_NAME_49E 0x049E // Ҟ CYRILLIC CAPITAL LETTER KA WITH STROKE
#define UC_MACRO_NAME_49F 0x049F // ҟ CYRILLIC SMALL LETTER KA WITH STROKE
#define UC_MACRO_NAME_4A0 0x04A0 // Ҡ CYRILLIC CAPITAL LETTER BASHKIR KA
#define UC_MACRO_NAME_4A1 0x04A1 // ҡ CYRILLIC SMALL LETTER BASHKIR KA
#define UC_MACRO_NAME_4A2 0x04A2 // Ң CYRILLIC CAPITAL LETTER EN WITH DESCENDER
#define UC_MACRO_NAME_4A3 0x04A3 // ң CYRILLIC SMALL LETTER EN WITH DESCENDER
#define UC_MACRO_NAME_4A4 0x04A4 // Ҥ CYRILLIC CAPITAL LIGATURE EN GHE
#define UC_MACRO_NAME_4A5 0x04A5 // ҥ CYRILLIC SMALL LIGATURE EN GHE
#define UC_MACRO_NAME_4A6 0x04A6 // Ҧ CYRILLIC CAPITAL LETTER PE WITH MIDDLE HOOK
#define UC_MACRO_NAME_4A7 0x04A7 // ҧ CYRILLIC SMALL LETTER PE WITH MIDDLE HOOK
#define UC_MACRO_NAME_4A8 0x04A8 // Ҩ CYRILLIC CAPITAL LETTER ABKHASIAN HA
#define UC_MACRO_NAME_4A9 0x04A9 // ҩ CYRILLIC SMALL LETTER ABKHASIAN HA
#define UC_MACRO_NAME_4AA 0x04AA // Ҫ CYRILLIC CAPITAL LETTER ES WITH DESCENDER
#define UC_MACRO_NAME_4AB 0x04AB // ҫ CYRILLIC SMALL LETTER ES WITH DESCENDER
#define UC_MACRO_NAME_4AC 0x04AC // Ҭ CYRILLIC CAPITAL LETTER TE WITH DESCENDER
#define UC_MACRO_NAME_4AD 0x04AD // ҭ CYRILLIC SMALL LETTER TE WITH DESCENDER
#define UC_MACRO_NAME_4AE 0x04AE // Ү CYRILLIC CAPITAL LETTER STRAIGHT U
#define UC_MACRO_NAME_4AF 0x04AF // ү CYRILLIC SMALL LETTER STRAIGHT U
#define UC_MACRO_NAME_4B0 0x04B0 // Ұ CYRILLIC CAPITAL LETTER STRAIGHT U WITH STROKE
#define UC_MACRO_NAME_4B1 0x04B1 // ұ CYRILLIC SMALL LETTER STRAIGHT U WITH STROKE
#define UC_MACRO_NAME_4B2 0x04B2 // Ҳ CYRILLIC CAPITAL LETTER HA WITH DESCENDER
#define UC_MACRO_NAME_4B3 0x04B3 // ҳ CYRILLIC SMALL LETTER HA WITH DESCENDER
#define UC_MACRO_NAME_4B4 0x04B4 // Ҵ CYRILLIC CAPITAL LIGATURE TE TSE
#define UC_MACRO_NAME_4B5 0x04B5 // ҵ CYRILLIC SMALL LIGATURE TE TSE
#define UC_MACRO_NAME_4B6 0x04B6 // Ҷ CYRILLIC CAPITAL LETTER CHE WITH DESCENDER
#define UC_MACRO_NAME_4B7 0x04B7 // ҷ CYRILLIC SMALL LETTER CHE WITH DESCENDER
#define UC_MACRO_NAME_4B8 0x04B8 // Ҹ CYRILLIC CAPITAL LETTER CHE WITH VERTICAL STROKE
#define UC_MACRO_NAME_4B9 0x04B9 // ҹ CYRILLIC SMALL LETTER CHE WITH VERTICAL STROKE
#define UC_MACRO_NAME_4BA 0x04BA // Һ CYRILLIC CAPITAL LETTER SHHA
#define UC_MACRO_NAME_4BB 0x04BB // һ CYRILLIC SMALL LETTER SHHA
#define UC_MACRO_NAME_4BC 0x04BC // Ҽ CYRILLIC CAPITAL LETTER ABKHASIAN CHE
#define UC_MACRO_NAME_4BD 0x04BD // ҽ CYRILLIC SMALL LETTER ABKHASIAN CHE
#define UC_MACRO_NAME_4BE 0x04BE // Ҿ CYRILLIC CAPITAL LETTER ABKHASIAN CHE WITH DESCENDER
#define UC_MACRO_NAME_4BF 0x04BF // ҿ CYRILLIC SMALL LETTER ABKHASIAN CHE WITH DESCENDER
#define UC_MACRO_NAME_4C0 0x04C0 // Ӏ CYRILLIC LETTER PALOCHKA
#define UC_MACRO_NAME_4C1 0x04C1 // Ӂ CYRILLIC CAPITAL LETTER ZHE WITH BREVE
#define UC_MACRO_NAME_4C2 0x04C2 // ӂ CYRILLIC SMALL LETTER ZHE WITH BREVE
#define UC_MACRO_NAME_4C3 0x04C3 // Ӄ CYRILLIC CAPITAL LETTER KA WITH HOOK
#define UC_MACRO_NAME_4C4 0x04C4 // ӄ CYRILLIC SMALL LETTER KA WITH HOOK
#define UC_MACRO_NAME_4C5 0x04C5 // Ӆ CYRILLIC CAPITAL LETTER EL WITH TAIL
#define UC_MACRO_NAME_4C6 0x04C6 // ӆ CYRILLIC SMALL LETTER EL WITH TAIL
#define UC_MACRO_NAME_4C7 0x04C7 // Ӈ CYRILLIC CAPITAL LETTER EN WITH HOOK
#define UC_MACRO_NAME_4C8 0x04C8 // ӈ CYRILLIC SMALL LETTER EN WITH HOOK
#define UC_MACRO_NAME_4C9 0x04C9 // Ӊ CYRILLIC CAPITAL LETTER EN WITH TAIL
#define UC_MACRO_NAME_4CA 0x04CA // ӊ CYRILLIC SMALL LETTER EN WITH TAIL
#define UC_MACRO_NAME_4CB 0x04CB // Ӌ CYRILLIC CAPITAL LETTER KHAKASSIAN CHE
#define UC_MACRO_NAME_4CC 0x04CC // ӌ CYRILLIC SMALL LETTER KHAKASSIAN CHE
#define UC_MACRO_NAME_4CD 0x04CD // Ӎ CYRILLIC CAPITAL LETTER EM WITH TAIL
#define UC_MACRO_NAME_4CE 0x04CE // ӎ CYRILLIC SMALL LETTER EM WITH TAIL
#define UC_MACRO_NAME_4CF 0x04CF // ӏ CYRILLIC SMALL LETTER PALOCHKA
#define UC_MACRO_NAME_4D0 0x04D0 // Ӑ CYRILLIC CAPITAL LETTER A WITH BREVE
#define UC_MACRO_NAME_4D1 0x04D1 // ӑ CYRILLIC SMALL LETTER A WITH BREVE
#define UC_MACRO_NAME_4D2 0x04D2 // Ӓ CYRILLIC CAPITAL LETTER A WITH DIAERESIS
#define UC_MACRO_NAME_4D3 0x04D3 // ӓ CYRILLIC SMALL LETTER A WITH DIAERESIS
#define UC_MACRO_NAME_4D4 0x04D4 // Ӕ CYRILLIC CAPITAL LIGATURE A IE
#define UC_MACRO_NAME_4D5 0x04D5 // ӕ CYRILLIC SMALL LIGATURE A IE
#define UC_MACRO_NAME_4D6 0x04D6 // Ӗ CYRILLIC CAPITAL LETTER IE WITH BREVE
#define UC_MACRO_NAME_4D7 0x04D7 // ӗ CYRILLIC SMALL LETTER IE WITH BREVE
#define UC_MACRO_NAME_4D8 0x04D8 // Ә CYRILLIC CAPITAL LETTER SCHWA
#define UC_MACRO_NAME_4D9 0x04D9 // ә CYRILLIC SMALL LETTER SCHWA
#define UC_MACRO_NAME_4DA 0x04DA // Ӛ CYRILLIC CAPITAL LETTER SCHWA WITH DIAERESIS
#define UC_MACRO_NAME_4DB 0x04DB // ӛ CYRILLIC SMALL LETTER SCHWA WITH DIAERESIS
#define UC_MACRO_NAME_4DC 0x04DC // Ӝ CYRILLIC CAPITAL LETTER ZHE WITH DIAERESIS
#define UC_MACRO_NAME_4DD 0x04DD // ӝ CYRILLIC SMALL LETTER ZHE WITH DIAERESIS
#define UC_MACRO_NAME_4DE 0x04DE // Ӟ CYRILLIC CAPITAL LETTER ZE WITH DIAERESIS
#define UC_MACRO_NAME_4DF 0x04DF // ӟ CYRILLIC SMALL LETTER ZE WITH DIAERESIS
#define UC_MACRO_NAME_4E0 0x04E0 // Ӡ CYRILLIC CAPITAL LETTER ABKHASIAN DZE
#define UC_MACRO_NAME_4E1 0x04E1 // ӡ CYRILLIC SMALL LETTER ABKHASIAN DZE
#define UC_MACRO_NAME_4E2 0x04E2 // Ӣ CYRILLIC CAPITAL LETTER I WITH MACRON
#define UC_MACRO_NAME_4E3 0x04E3 // ӣ CYRILLIC SMALL LETTER I WITH MACRON
#define UC_MACRO_NAME_4E4 0x04E4 // Ӥ CYRILLIC CAPITAL LETTER I WITH DIAERESIS
#define UC_MACRO_NAME_4E5 0x04E5 // ӥ CYRILLIC SMALL LETTER I WITH DIAERESIS
#define UC_MACRO_NAME_4E6 0x04E6 // Ӧ CYRILLIC CAPITAL LETTER O WITH DIAERESIS
#define UC_MACRO_NAME_4E7 0x04E7 // ӧ CYRILLIC SMALL LETTER O WITH DIAERESIS
#define UC_MACRO_NAME_4E8 0x04E8 // Ө CYRILLIC CAPITAL LETTER BARRED O
#define UC_MACRO_NAME_4E9 0x04E9 // ө CYRILLIC SMALL LETTER BARRED O
#define UC_MACRO_NAME_4EA 0x04EA // Ӫ CYRILLIC CAPITAL LETTER BARRED O WITH DIAERESIS
#define UC_MACRO_NAME_4EB 0x04EB // ӫ CYRILLIC SMALL LETTER BARRED O WITH DIAERESIS
#define UC_MACRO_NAME_4EC 0x04EC // Ӭ CYRILLIC CAPITAL LETTER E WITH DIAERESIS
#define UC_MACRO_NAME_4ED 0x04ED // ӭ CYRILLIC SMALL LETTER E WITH DIAERESIS
#define UC_MACRO_NAME_4EE 0x04EE // Ӯ CYRILLIC CAPITAL LETTER U WITH MACRON
#define UC_MACRO_NAME_4EF 0x04EF // ӯ CYRILLIC SMALL LETTER U WITH MACRON
#define UC_MACRO_NAME_4F0 0x04F0 // Ӱ CYRILLIC CAPITAL LETTER U WITH DIAERESIS
#define UC_MACRO_NAME_4F1 0x04F1 // ӱ CYRILLIC SMALL LETTER U WITH DIAERESIS
#define UC_MACRO_NAME_4F2 0x04F2 // Ӳ CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE
#define UC_MACRO_NAME_4F3 0x04F3 // ӳ CYRILLIC SMALL LETTER U WITH DOUBLE ACUTE
#define UC_MACRO_NAME_4F4 0x04F4 // Ӵ CYRILLIC CAPITAL LETTER CHE WITH DIAERESIS
#define UC_MACRO_NAME_4F5 0x04F5 // ӵ CYRILLIC SMALL LETTER CHE WITH DIAERESIS
#define UC_MACRO_NAME_4F6 0x04F6 // Ӷ CYRILLIC CAPITAL LETTER GHE WITH DESCENDER
#define UC_MACRO_NAME_4F7 0x04F7 // ӷ CYRILLIC SMALL LETTER GHE WITH DESCENDER
#define UC_MACRO_NAME_4F8 0x04F8 // Ӹ CYRILLIC CAPITAL LETTER YERU WITH DIAERESIS
#define UC_MACRO_NAME_4F9 0x04F9 // ӹ CYRILLIC SMALL LETTER YERU WITH DIAERESIS
#define UC_MACRO_NAME_4FA 0x04FA // Ӻ CYRILLIC CAPITAL LETTER GHE WITH STROKE AND HOOK
#define UC_MACRO_NAME_4FB 0x04FB // ӻ CYRILLIC SMALL LETTER GHE WITH STROKE AND HOOK
#define UC_MACRO_NAME_4FC 0x04FC // Ӽ CYRILLIC CAPITAL LETTER HA WITH HOOK
#define UC_MACRO_NAME_4FD 0x04FD // ӽ CYRILLIC SMALL LETTER HA WITH HOOK
#define UC_MACRO_NAME_4FE 0x04FE // Ӿ CYRILLIC CAPITAL LETTER HA WITH STROKE
#define UC_MACRO_NAME_4FF 0x04FF // ӿ CYRILLIC SMALL LETTER HA WITH STROKE


#endif // UC_H_CYRILLIC
