/*
 * Unicode Block: Cherokee Supplement
 * Range: U+AB70..U+ABBF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Cherokee Supplement is a Unicode block containing the syllabic
 * characters for writing the Cherokee language . When Cherokee was first
 * added to Unicode in version 3.0 it was treated as a unicameral
 * alphabet , but in version 8.0 it was redefined as a bicameral script .
 * The Cherokee Supplement block contains lowercase letters only, whereas
 * the Cherokee block contains all the uppercase letters, together with
 * six lowercase letters. For backwards compatibility, the Unicode case
 * folding algorithm—which usually converts a string to lowercase
 * characters—maps Cherokee characters to uppercase.
 * The following Unicode-related documents record the purpose and process
 * of defining specific characters in the Cherokee Supplement block:
 *
 */
#ifndef UC_H_CHEROKEE_SUPPLEMENT
#define UC_H_CHEROKEE_SUPPLEMENT

#define UC_MACRO_NAME_AB70 0xAB70 // ꭰ CHEROKEE SMALL LETTER A
#define UC_MACRO_NAME_AB71 0xAB71 // ꭱ CHEROKEE SMALL LETTER E
#define UC_MACRO_NAME_AB72 0xAB72 // ꭲ CHEROKEE SMALL LETTER I
#define UC_MACRO_NAME_AB73 0xAB73 // ꭳ CHEROKEE SMALL LETTER O
#define UC_MACRO_NAME_AB74 0xAB74 // ꭴ CHEROKEE SMALL LETTER U
#define UC_MACRO_NAME_AB75 0xAB75 // ꭵ CHEROKEE SMALL LETTER V
#define UC_MACRO_NAME_AB76 0xAB76 // ꭶ CHEROKEE SMALL LETTER GA
#define UC_MACRO_NAME_AB77 0xAB77 // ꭷ CHEROKEE SMALL LETTER KA
#define UC_MACRO_NAME_AB78 0xAB78 // ꭸ CHEROKEE SMALL LETTER GE
#define UC_MACRO_NAME_AB79 0xAB79 // ꭹ CHEROKEE SMALL LETTER GI
#define UC_MACRO_NAME_AB7A 0xAB7A // ꭺ CHEROKEE SMALL LETTER GO
#define UC_MACRO_NAME_AB7B 0xAB7B // ꭻ CHEROKEE SMALL LETTER GU
#define UC_MACRO_NAME_AB7C 0xAB7C // ꭼ CHEROKEE SMALL LETTER GV
#define UC_MACRO_NAME_AB7D 0xAB7D // ꭽ CHEROKEE SMALL LETTER HA
#define UC_MACRO_NAME_AB7E 0xAB7E // ꭾ CHEROKEE SMALL LETTER HE
#define UC_MACRO_NAME_AB7F 0xAB7F // ꭿ CHEROKEE SMALL LETTER HI
#define UC_MACRO_NAME_AB80 0xAB80 // ꮀ CHEROKEE SMALL LETTER HO
#define UC_MACRO_NAME_AB81 0xAB81 // ꮁ CHEROKEE SMALL LETTER HU
#define UC_MACRO_NAME_AB82 0xAB82 // ꮂ CHEROKEE SMALL LETTER HV
#define UC_MACRO_NAME_AB83 0xAB83 // ꮃ CHEROKEE SMALL LETTER LA
#define UC_MACRO_NAME_AB84 0xAB84 // ꮄ CHEROKEE SMALL LETTER LE
#define UC_MACRO_NAME_AB85 0xAB85 // ꮅ CHEROKEE SMALL LETTER LI
#define UC_MACRO_NAME_AB86 0xAB86 // ꮆ CHEROKEE SMALL LETTER LO
#define UC_MACRO_NAME_AB87 0xAB87 // ꮇ CHEROKEE SMALL LETTER LU
#define UC_MACRO_NAME_AB88 0xAB88 // ꮈ CHEROKEE SMALL LETTER LV
#define UC_MACRO_NAME_AB89 0xAB89 // ꮉ CHEROKEE SMALL LETTER MA
#define UC_MACRO_NAME_AB8A 0xAB8A // ꮊ CHEROKEE SMALL LETTER ME
#define UC_MACRO_NAME_AB8B 0xAB8B // ꮋ CHEROKEE SMALL LETTER MI
#define UC_MACRO_NAME_AB8C 0xAB8C // ꮌ CHEROKEE SMALL LETTER MO
#define UC_MACRO_NAME_AB8D 0xAB8D // ꮍ CHEROKEE SMALL LETTER MU
#define UC_MACRO_NAME_AB8E 0xAB8E // ꮎ CHEROKEE SMALL LETTER NA
#define UC_MACRO_NAME_AB8F 0xAB8F // ꮏ CHEROKEE SMALL LETTER HNA
#define UC_MACRO_NAME_AB90 0xAB90 // ꮐ CHEROKEE SMALL LETTER NAH
#define UC_MACRO_NAME_AB91 0xAB91 // ꮑ CHEROKEE SMALL LETTER NE
#define UC_MACRO_NAME_AB92 0xAB92 // ꮒ CHEROKEE SMALL LETTER NI
#define UC_MACRO_NAME_AB93 0xAB93 // ꮓ CHEROKEE SMALL LETTER NO
#define UC_MACRO_NAME_AB94 0xAB94 // ꮔ CHEROKEE SMALL LETTER NU
#define UC_MACRO_NAME_AB95 0xAB95 // ꮕ CHEROKEE SMALL LETTER NV
#define UC_MACRO_NAME_AB96 0xAB96 // ꮖ CHEROKEE SMALL LETTER QUA
#define UC_MACRO_NAME_AB97 0xAB97 // ꮗ CHEROKEE SMALL LETTER QUE
#define UC_MACRO_NAME_AB98 0xAB98 // ꮘ CHEROKEE SMALL LETTER QUI
#define UC_MACRO_NAME_AB99 0xAB99 // ꮙ CHEROKEE SMALL LETTER QUO
#define UC_MACRO_NAME_AB9A 0xAB9A // ꮚ CHEROKEE SMALL LETTER QUU
#define UC_MACRO_NAME_AB9B 0xAB9B // ꮛ CHEROKEE SMALL LETTER QUV
#define UC_MACRO_NAME_AB9C 0xAB9C // ꮜ CHEROKEE SMALL LETTER SA
#define UC_MACRO_NAME_AB9D 0xAB9D // ꮝ CHEROKEE SMALL LETTER S
#define UC_MACRO_NAME_AB9E 0xAB9E // ꮞ CHEROKEE SMALL LETTER SE
#define UC_MACRO_NAME_AB9F 0xAB9F // ꮟ CHEROKEE SMALL LETTER SI
#define UC_MACRO_NAME_ABA0 0xABA0 // ꮠ CHEROKEE SMALL LETTER SO
#define UC_MACRO_NAME_ABA1 0xABA1 // ꮡ CHEROKEE SMALL LETTER SU
#define UC_MACRO_NAME_ABA2 0xABA2 // ꮢ CHEROKEE SMALL LETTER SV
#define UC_MACRO_NAME_ABA3 0xABA3 // ꮣ CHEROKEE SMALL LETTER DA
#define UC_MACRO_NAME_ABA4 0xABA4 // ꮤ CHEROKEE SMALL LETTER TA
#define UC_MACRO_NAME_ABA5 0xABA5 // ꮥ CHEROKEE SMALL LETTER DE
#define UC_MACRO_NAME_ABA6 0xABA6 // ꮦ CHEROKEE SMALL LETTER TE
#define UC_MACRO_NAME_ABA7 0xABA7 // ꮧ CHEROKEE SMALL LETTER DI
#define UC_MACRO_NAME_ABA8 0xABA8 // ꮨ CHEROKEE SMALL LETTER TI
#define UC_MACRO_NAME_ABA9 0xABA9 // ꮩ CHEROKEE SMALL LETTER DO
#define UC_MACRO_NAME_ABAA 0xABAA // ꮪ CHEROKEE SMALL LETTER DU
#define UC_MACRO_NAME_ABAB 0xABAB // ꮫ CHEROKEE SMALL LETTER DV
#define UC_MACRO_NAME_ABAC 0xABAC // ꮬ CHEROKEE SMALL LETTER DLA
#define UC_MACRO_NAME_ABAD 0xABAD // ꮭ CHEROKEE SMALL LETTER TLA
#define UC_MACRO_NAME_ABAE 0xABAE // ꮮ CHEROKEE SMALL LETTER TLE
#define UC_MACRO_NAME_ABAF 0xABAF // ꮯ CHEROKEE SMALL LETTER TLI
#define UC_MACRO_NAME_ABB0 0xABB0 // ꮰ CHEROKEE SMALL LETTER TLO
#define UC_MACRO_NAME_ABB1 0xABB1 // ꮱ CHEROKEE SMALL LETTER TLU
#define UC_MACRO_NAME_ABB2 0xABB2 // ꮲ CHEROKEE SMALL LETTER TLV
#define UC_MACRO_NAME_ABB3 0xABB3 // ꮳ CHEROKEE SMALL LETTER TSA
#define UC_MACRO_NAME_ABB4 0xABB4 // ꮴ CHEROKEE SMALL LETTER TSE
#define UC_MACRO_NAME_ABB5 0xABB5 // ꮵ CHEROKEE SMALL LETTER TSI
#define UC_MACRO_NAME_ABB6 0xABB6 // ꮶ CHEROKEE SMALL LETTER TSO
#define UC_MACRO_NAME_ABB7 0xABB7 // ꮷ CHEROKEE SMALL LETTER TSU
#define UC_MACRO_NAME_ABB8 0xABB8 // ꮸ CHEROKEE SMALL LETTER TSV
#define UC_MACRO_NAME_ABB9 0xABB9 // ꮹ CHEROKEE SMALL LETTER WA
#define UC_MACRO_NAME_ABBA 0xABBA // ꮺ CHEROKEE SMALL LETTER WE
#define UC_MACRO_NAME_ABBB 0xABBB // ꮻ CHEROKEE SMALL LETTER WI
#define UC_MACRO_NAME_ABBC 0xABBC // ꮼ CHEROKEE SMALL LETTER WO
#define UC_MACRO_NAME_ABBD 0xABBD // ꮽ CHEROKEE SMALL LETTER WU
#define UC_MACRO_NAME_ABBE 0xABBE // ꮾ CHEROKEE SMALL LETTER WV
#define UC_MACRO_NAME_ABBF 0xABBF // ꮿ CHEROKEE SMALL LETTER YA


#endif // UC_H_CHEROKEE_SUPPLEMENT
