/*
 * Unicode Block: Combining Diacritical Marks Extended
 * Range: U+1AB0..U+1AFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Combining Diacritical Marks Extended is a Unicode block containing
 * diacritical marks used in German dialectology ( Teuthonista ).
 * The following Unicode-related documents record the purpose and process
 * of defining specific characters in the Combining Diacritical Marks
 * Extended block:
 *
 */
#ifndef UC_H_COMBINING_DIACRITICAL_MARKS_EXTENDED
#define UC_H_COMBINING_DIACRITICAL_MARKS_EXTENDED

#define UC_MACRO_NAME_1AB0 0x1AB0 // ᪰ COMBINING DOUBLED CIRCUMFLEX ACCENT
#define UC_MACRO_NAME_1AB1 0x1AB1 // ᪱ COMBINING DIAERESIS-RING
#define UC_MACRO_NAME_1AB2 0x1AB2 // ᪲ COMBINING INFINITY
#define UC_MACRO_NAME_1AB3 0x1AB3 // ᪳ COMBINING DOWNWARDS ARROW
#define UC_MACRO_NAME_1AB4 0x1AB4 // ᪴ COMBINING TRIPLE DOT
#define UC_MACRO_NAME_1AB5 0x1AB5 // ᪵ COMBINING X-X BELOW
#define UC_MACRO_NAME_1AB6 0x1AB6 // ᪶ COMBINING WIGGLY LINE BELOW
#define UC_MACRO_NAME_1AB7 0x1AB7 // ᪷ COMBINING OPEN MARK BELOW
#define UC_MACRO_NAME_1AB8 0x1AB8 // ᪸ COMBINING DOUBLE OPEN MARK BELOW
#define UC_MACRO_NAME_1AB9 0x1AB9 // ᪹ COMBINING LIGHT CENTRALIZATION STROKE BELOW
#define UC_MACRO_NAME_1ABA 0x1ABA // ᪺ COMBINING STRONG CENTRALIZATION STROKE BELOW
#define UC_MACRO_NAME_1ABB 0x1ABB // ᪻ COMBINING PARENTHESES ABOVE
#define UC_MACRO_NAME_1ABC 0x1ABC // ᪼ COMBINING DOUBLE PARENTHESES ABOVE
#define UC_MACRO_NAME_1ABD 0x1ABD // ᪽ COMBINING PARENTHESES BELOW
#define UC_MACRO_NAME_1ABE 0x1ABE // ᪾ COMBINING PARENTHESES OVERLAY
#define UC_MACRO_NAME_1ABF 0x1ABF // ᪿ COMBINING LATIN SMALL LETTER W BELOW
#define UC_MACRO_NAME_1AC0 0x1AC0 // ᫀ COMBINING LATIN SMALL LETTER TURNED W BELOW
#define UC_MACRO_NAME_1AC1 0x1AC1 // ᫁ COMBINING LEFT PARENTHESIS ABOVE LEFT
#define UC_MACRO_NAME_1AC2 0x1AC2 // ᫂ COMBINING RIGHT PARENTHESIS ABOVE RIGHT
#define UC_MACRO_NAME_1AC3 0x1AC3 // ᫃ COMBINING LEFT PARENTHESIS BELOW LEFT
#define UC_MACRO_NAME_1AC4 0x1AC4 // ᫄ COMBINING RIGHT PARENTHESIS BELOW RIGHT
#define UC_MACRO_NAME_1AC5 0x1AC5 // ᫅ COMBINING SQUARE BRACKETS ABOVE
#define UC_MACRO_NAME_1AC6 0x1AC6 // ᫆ COMBINING NUMBER SIGN ABOVE
#define UC_MACRO_NAME_1AC7 0x1AC7 // ᫇ COMBINING INVERTED DOUBLE ARCH ABOVE
#define UC_MACRO_NAME_1AC8 0x1AC8 // ᫈ COMBINING PLUS SIGN ABOVE
#define UC_MACRO_NAME_1AC9 0x1AC9 // ᫉ COMBINING DOUBLE PLUS SIGN ABOVE
#define UC_MACRO_NAME_1ACA 0x1ACA // ᫊ COMBINING DOUBLE PLUS SIGN BELOW
#define UC_MACRO_NAME_1ACB 0x1ACB // ᫋ COMBINING TRIPLE ACUTE ACCENT
#define UC_MACRO_NAME_1ACC 0x1ACC // ᫌ COMBINING LATIN SMALL LETTER INSULAR G
#define UC_MACRO_NAME_1ACD 0x1ACD // ᫍ COMBINING LATIN SMALL LETTER INSULAR R
#define UC_MACRO_NAME_1ACE 0x1ACE // ᫎ COMBINING LATIN SMALL LETTER INSULAR T
#define UC_MACRO_NAME_1ACF 0x1ACF //  COMBINING DOUBLE CARON
#define UC_MACRO_NAME_1AD0 0x1AD0 //  COMBINING VERTICAL-LINE-ACUTE
#define UC_MACRO_NAME_1AD1 0x1AD1 //  COMBINING GRAVE-VERTICAL-LINE
#define UC_MACRO_NAME_1AD2 0x1AD2 //  COMBINING VERTICAL-LINE-GRAVE
#define UC_MACRO_NAME_1AD3 0x1AD3 //  COMBINING ACUTE-VERTICAL-LINE
#define UC_MACRO_NAME_1AD4 0x1AD4 //  COMBINING VERTICAL-LINE-MACRON
#define UC_MACRO_NAME_1AD5 0x1AD5 //  COMBINING MACRON-VERTICAL-LINE
#define UC_MACRO_NAME_1AD6 0x1AD6 //  COMBINING VERTICAL-LINE-ACUTE-GRAVE
#define UC_MACRO_NAME_1AD7 0x1AD7 //  COMBINING VERTICAL-LINE-GRAVE-ACUTE
#define UC_MACRO_NAME_1AD8 0x1AD8 //  COMBINING MACRON-ACUTE-GRAVE
#define UC_MACRO_NAME_1AD9 0x1AD9 //  COMBINING SHARP SIGN
#define UC_MACRO_NAME_1ADA 0x1ADA //  COMBINING FLAT SIGN
#define UC_MACRO_NAME_1ADB 0x1ADB //  COMBINING DOWN TACK ABOVE
#define UC_MACRO_NAME_1ADC 0x1ADC //  COMBINING DIAERESIS WITH RAISED LEFT DOT
#define UC_MACRO_NAME_1ADD 0x1ADD //  COMBINING DOT-AND-RING BELOW
#define UC_MACRO_NAME_1AE0 0x1AE0 //  COMBINING LEFT TACK ABOVE
#define UC_MACRO_NAME_1AE1 0x1AE1 //  COMBINING RIGHT TACK ABOVE
#define UC_MACRO_NAME_1AE2 0x1AE2 //  COMBINING MINUS SIGN ABOVE
#define UC_MACRO_NAME_1AE3 0x1AE3 //  COMBINING INVERTED BRIDGE ABOVE
#define UC_MACRO_NAME_1AE4 0x1AE4 //  COMBINING SQUARE ABOVE
#define UC_MACRO_NAME_1AE5 0x1AE5 //  COMBINING SEAGULL ABOVE
#define UC_MACRO_NAME_1AE6 0x1AE6 //  COMBINING DOUBLE ARCH BELOW
#define UC_MACRO_NAME_1AE7 0x1AE7 //  COMBINING DOUBLE ARCH ABOVE
#define UC_MACRO_NAME_1AE8 0x1AE8 //  COMBINING EQUALS SIGN ABOVE
#define UC_MACRO_NAME_1AE9 0x1AE9 //  COMBINING LEFT ANGLE CENTRED ABOVE
#define UC_MACRO_NAME_1AEA 0x1AEA //  COMBINING UPWARDS ARROW ABOVE
#define UC_MACRO_NAME_1AEB 0x1AEB //  COMBINING DOUBLE RIGHTWARDS ARROW ABOVE


#endif // UC_H_COMBINING_DIACRITICAL_MARKS_EXTENDED
