/*
 * Unicode Block: Cyrillic Extended-A
 * Range: U+2DE0..U+2DFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_CYRILLIC_EXTENDED_A
#define UC_H_CYRILLIC_EXTENDED_A

#define UC_MACRO_NAME_2DE0 0x2DE0 // ⷠ COMBINING CYRILLIC LETTER BE
#define UC_MACRO_NAME_2DE1 0x2DE1 // ⷡ COMBINING CYRILLIC LETTER VE
#define UC_MACRO_NAME_2DE2 0x2DE2 // ⷢ COMBINING CYRILLIC LETTER GHE
#define UC_MACRO_NAME_2DE3 0x2DE3 // ⷣ COMBINING CYRILLIC LETTER DE
#define UC_MACRO_NAME_2DE4 0x2DE4 // ⷤ COMBINING CYRILLIC LETTER ZHE
#define UC_MACRO_NAME_2DE5 0x2DE5 // ⷥ COMBINING CYRILLIC LETTER ZE
#define UC_MACRO_NAME_2DE6 0x2DE6 // ⷦ COMBINING CYRILLIC LETTER KA
#define UC_MACRO_NAME_2DE7 0x2DE7 // ⷧ COMBINING CYRILLIC LETTER EL
#define UC_MACRO_NAME_2DE8 0x2DE8 // ⷨ COMBINING CYRILLIC LETTER EM
#define UC_MACRO_NAME_2DE9 0x2DE9 // ⷩ COMBINING CYRILLIC LETTER EN
#define UC_MACRO_NAME_2DEA 0x2DEA // ⷪ COMBINING CYRILLIC LETTER O
#define UC_MACRO_NAME_2DEB 0x2DEB // ⷫ COMBINING CYRILLIC LETTER PE
#define UC_MACRO_NAME_2DEC 0x2DEC // ⷬ COMBINING CYRILLIC LETTER ER
#define UC_MACRO_NAME_2DED 0x2DED // ⷭ COMBINING CYRILLIC LETTER ES
#define UC_MACRO_NAME_2DEE 0x2DEE // ⷮ COMBINING CYRILLIC LETTER TE
#define UC_MACRO_NAME_2DEF 0x2DEF // ⷯ COMBINING CYRILLIC LETTER HA
#define UC_MACRO_NAME_2DF0 0x2DF0 // ⷰ COMBINING CYRILLIC LETTER TSE
#define UC_MACRO_NAME_2DF1 0x2DF1 // ⷱ COMBINING CYRILLIC LETTER CHE
#define UC_MACRO_NAME_2DF2 0x2DF2 // ⷲ COMBINING CYRILLIC LETTER SHA
#define UC_MACRO_NAME_2DF3 0x2DF3 // ⷳ COMBINING CYRILLIC LETTER SHCHA
#define UC_MACRO_NAME_2DF4 0x2DF4 // ⷴ COMBINING CYRILLIC LETTER FITA
#define UC_MACRO_NAME_2DF5 0x2DF5 // ⷵ COMBINING CYRILLIC LETTER ES-TE
#define UC_MACRO_NAME_2DF6 0x2DF6 // ⷶ COMBINING CYRILLIC LETTER A
#define UC_MACRO_NAME_2DF7 0x2DF7 // ⷷ COMBINING CYRILLIC LETTER IE
#define UC_MACRO_NAME_2DF8 0x2DF8 // ⷸ COMBINING CYRILLIC LETTER DJERV
#define UC_MACRO_NAME_2DF9 0x2DF9 // ⷹ COMBINING CYRILLIC LETTER MONOGRAPH UK
#define UC_MACRO_NAME_2DFA 0x2DFA // ⷺ COMBINING CYRILLIC LETTER YAT
#define UC_MACRO_NAME_2DFB 0x2DFB // ⷻ COMBINING CYRILLIC LETTER YU
#define UC_MACRO_NAME_2DFC 0x2DFC // ⷼ COMBINING CYRILLIC LETTER IOTIFIED A
#define UC_MACRO_NAME_2DFD 0x2DFD // ⷽ COMBINING CYRILLIC LETTER LITTLE YUS
#define UC_MACRO_NAME_2DFE 0x2DFE // ⷾ COMBINING CYRILLIC LETTER BIG YUS
#define UC_MACRO_NAME_2DFF 0x2DFF // ⷿ COMBINING CYRILLIC LETTER IOTIFIED BIG YUS


#endif // UC_H_CYRILLIC_EXTENDED_A
