/*
 * Unicode Block: CJK Compatibility Forms
 * Range: U+FE30..U+FE4F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_CJK_COMPATIBILITY_FORMS
#define UC_H_CJK_COMPATIBILITY_FORMS

#define UC_MACRO_NAME_FE30 0xFE30 // ︰ PRESENTATION FORM FOR VERTICAL TWO DOT LEADER
#define UC_MACRO_NAME_FE31 0xFE31 // ︱ PRESENTATION FORM FOR VERTICAL EM DASH
#define UC_MACRO_NAME_FE32 0xFE32 // ︲ PRESENTATION FORM FOR VERTICAL EN DASH
#define UC_MACRO_NAME_FE33 0xFE33 // ︳ PRESENTATION FORM FOR VERTICAL LOW LINE
#define UC_MACRO_NAME_FE34 0xFE34 // ︴ PRESENTATION FORM FOR VERTICAL WAVY LOW LINE
#define UC_MACRO_NAME_FE35 0xFE35 // ︵ PRESENTATION FORM FOR VERTICAL LEFT PARENTHESIS
#define UC_MACRO_NAME_FE36 0xFE36 // ︶ PRESENTATION FORM FOR VERTICAL RIGHT PARENTHESIS
#define UC_MACRO_NAME_FE37 0xFE37 // ︷ PRESENTATION FORM FOR VERTICAL LEFT CURLY BRACKET
#define UC_MACRO_NAME_FE38 0xFE38 // ︸ PRESENTATION FORM FOR VERTICAL RIGHT CURLY BRACKET
#define UC_MACRO_NAME_FE39 0xFE39 // ︹ PRESENTATION FORM FOR VERTICAL LEFT TORTOISE SHELL BRACKET
#define UC_MACRO_NAME_FE3A 0xFE3A // ︺ PRESENTATION FORM FOR VERTICAL RIGHT TORTOISE SHELL BRACKET
#define UC_MACRO_NAME_FE3B 0xFE3B // ︻ PRESENTATION FORM FOR VERTICAL LEFT BLACK LENTICULAR BRACKET
#define UC_MACRO_NAME_FE3C 0xFE3C // ︼ PRESENTATION FORM FOR VERTICAL RIGHT BLACK LENTICULAR BRACKET
#define UC_MACRO_NAME_FE3D 0xFE3D // ︽ PRESENTATION FORM FOR VERTICAL LEFT DOUBLE ANGLE BRACKET
#define UC_MACRO_NAME_FE3E 0xFE3E // ︾ PRESENTATION FORM FOR VERTICAL RIGHT DOUBLE ANGLE BRACKET
#define UC_MACRO_NAME_FE3F 0xFE3F // ︿ PRESENTATION FORM FOR VERTICAL LEFT ANGLE BRACKET
#define UC_MACRO_NAME_FE40 0xFE40 // ﹀ PRESENTATION FORM FOR VERTICAL RIGHT ANGLE BRACKET
#define UC_MACRO_NAME_FE41 0xFE41 // ﹁ PRESENTATION FORM FOR VERTICAL LEFT CORNER BRACKET
#define UC_MACRO_NAME_FE42 0xFE42 // ﹂ PRESENTATION FORM FOR VERTICAL RIGHT CORNER BRACKET
#define UC_MACRO_NAME_FE43 0xFE43 // ﹃ PRESENTATION FORM FOR VERTICAL LEFT WHITE CORNER BRACKET
#define UC_MACRO_NAME_FE44 0xFE44 // ﹄ PRESENTATION FORM FOR VERTICAL RIGHT WHITE CORNER BRACKET
#define UC_MACRO_NAME_FE45 0xFE45 // ﹅ SESAME DOT
#define UC_MACRO_NAME_FE46 0xFE46 // ﹆ WHITE SESAME DOT
#define UC_MACRO_NAME_FE47 0xFE47 // ﹇ PRESENTATION FORM FOR VERTICAL LEFT SQUARE BRACKET
#define UC_MACRO_NAME_FE48 0xFE48 // ﹈ PRESENTATION FORM FOR VERTICAL RIGHT SQUARE BRACKET
#define UC_MACRO_NAME_FE49 0xFE49 // ﹉ DASHED OVERLINE
#define UC_MACRO_NAME_FE4A 0xFE4A // ﹊ CENTRELINE OVERLINE
#define UC_MACRO_NAME_FE4B 0xFE4B // ﹋ WAVY OVERLINE
#define UC_MACRO_NAME_FE4C 0xFE4C // ﹌ DOUBLE WAVY OVERLINE
#define UC_MACRO_NAME_FE4D 0xFE4D // ﹍ DASHED LOW LINE
#define UC_MACRO_NAME_FE4E 0xFE4E // ﹎ CENTRELINE LOW LINE
#define UC_MACRO_NAME_FE4F 0xFE4F // ﹏ WAVY LOW LINE


#endif // UC_H_CJK_COMPATIBILITY_FORMS
