/*
 * Unicode Block: Chess Symbols
 * Range: U+1FA00..U+1FA6F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Chess Symbols is a Unicode block containing characters for fairy chess
 * and related notations beyond the basic Western chess symbols (U+2654
 * to U+265F) in the Miscellaneous Symbols block, as well as symbols
 * representing game pieces for xiangqi (Chinese chess).
 *
 */
#ifndef UC_H_CHESS_SYMBOLS
#define UC_H_CHESS_SYMBOLS

#define UC_MACRO_NAME_1FA00 0x1FA00 // 🨀 NEUTRAL CHESS KING
#define UC_MACRO_NAME_1FA01 0x1FA01 // 🨁 NEUTRAL CHESS QUEEN
#define UC_MACRO_NAME_1FA02 0x1FA02 // 🨂 NEUTRAL CHESS ROOK
#define UC_MACRO_NAME_1FA03 0x1FA03 // 🨃 NEUTRAL CHESS BISHOP
#define UC_MACRO_NAME_1FA04 0x1FA04 // 🨄 NEUTRAL CHESS KNIGHT
#define UC_MACRO_NAME_1FA05 0x1FA05 // 🨅 NEUTRAL CHESS PAWN
#define UC_MACRO_NAME_1FA06 0x1FA06 // 🨆 WHITE CHESS KNIGHT ROTATED FORTY-FIVE DEGREES
#define UC_MACRO_NAME_1FA07 0x1FA07 // 🨇 BLACK CHESS KNIGHT ROTATED FORTY-FIVE DEGREES
#define UC_MACRO_NAME_1FA08 0x1FA08 // 🨈 NEUTRAL CHESS KNIGHT ROTATED FORTY-FIVE DEGREES
#define UC_MACRO_NAME_1FA09 0x1FA09 // 🨉 WHITE CHESS KING ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA0A 0x1FA0A // 🨊 WHITE CHESS QUEEN ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA0B 0x1FA0B // 🨋 WHITE CHESS ROOK ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA0C 0x1FA0C // 🨌 WHITE CHESS BISHOP ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA0D 0x1FA0D // 🨍 WHITE CHESS KNIGHT ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA0E 0x1FA0E // 🨎 WHITE CHESS PAWN ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA0F 0x1FA0F // 🨏 BLACK CHESS KING ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA10 0x1FA10 // 🨐 BLACK CHESS QUEEN ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA11 0x1FA11 // 🨑 BLACK CHESS ROOK ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA12 0x1FA12 // 🨒 BLACK CHESS BISHOP ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA13 0x1FA13 // 🨓 BLACK CHESS KNIGHT ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA14 0x1FA14 // 🨔 BLACK CHESS PAWN ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA15 0x1FA15 // 🨕 NEUTRAL CHESS KING ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA16 0x1FA16 // 🨖 NEUTRAL CHESS QUEEN ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA17 0x1FA17 // 🨗 NEUTRAL CHESS ROOK ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA18 0x1FA18 // 🨘 NEUTRAL CHESS BISHOP ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA19 0x1FA19 // 🨙 NEUTRAL CHESS KNIGHT ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA1A 0x1FA1A // 🨚 NEUTRAL CHESS PAWN ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA1B 0x1FA1B // 🨛 WHITE CHESS KNIGHT ROTATED ONE HUNDRED THIRTY-FIVE DEGREES
#define UC_MACRO_NAME_1FA1C 0x1FA1C // 🨜 BLACK CHESS KNIGHT ROTATED ONE HUNDRED THIRTY-FIVE DEGREES
#define UC_MACRO_NAME_1FA1D 0x1FA1D // 🨝 NEUTRAL CHESS KNIGHT ROTATED ONE HUNDRED THIRTY-FIVE DEGREES
#define UC_MACRO_NAME_1FA1E 0x1FA1E // 🨞 WHITE CHESS TURNED KING
#define UC_MACRO_NAME_1FA1F 0x1FA1F // 🨟 WHITE CHESS TURNED QUEEN
#define UC_MACRO_NAME_1FA20 0x1FA20 // 🨠 WHITE CHESS TURNED ROOK
#define UC_MACRO_NAME_1FA21 0x1FA21 // 🨡 WHITE CHESS TURNED BISHOP
#define UC_MACRO_NAME_1FA22 0x1FA22 // 🨢 WHITE CHESS TURNED KNIGHT
#define UC_MACRO_NAME_1FA23 0x1FA23 // 🨣 WHITE CHESS TURNED PAWN
#define UC_MACRO_NAME_1FA24 0x1FA24 // 🨤 BLACK CHESS TURNED KING
#define UC_MACRO_NAME_1FA25 0x1FA25 // 🨥 BLACK CHESS TURNED QUEEN
#define UC_MACRO_NAME_1FA26 0x1FA26 // 🨦 BLACK CHESS TURNED ROOK
#define UC_MACRO_NAME_1FA27 0x1FA27 // 🨧 BLACK CHESS TURNED BISHOP
#define UC_MACRO_NAME_1FA28 0x1FA28 // 🨨 BLACK CHESS TURNED KNIGHT
#define UC_MACRO_NAME_1FA29 0x1FA29 // 🨩 BLACK CHESS TURNED PAWN
#define UC_MACRO_NAME_1FA2A 0x1FA2A // 🨪 NEUTRAL CHESS TURNED KING
#define UC_MACRO_NAME_1FA2B 0x1FA2B // 🨫 NEUTRAL CHESS TURNED QUEEN
#define UC_MACRO_NAME_1FA2C 0x1FA2C // 🨬 NEUTRAL CHESS TURNED ROOK
#define UC_MACRO_NAME_1FA2D 0x1FA2D // 🨭 NEUTRAL CHESS TURNED BISHOP
#define UC_MACRO_NAME_1FA2E 0x1FA2E // 🨮 NEUTRAL CHESS TURNED KNIGHT
#define UC_MACRO_NAME_1FA2F 0x1FA2F // 🨯 NEUTRAL CHESS TURNED PAWN
#define UC_MACRO_NAME_1FA30 0x1FA30 // 🨰 WHITE CHESS KNIGHT ROTATED TWO HUNDRED TWENTY-FIVE DEGREES
#define UC_MACRO_NAME_1FA31 0x1FA31 // 🨱 BLACK CHESS KNIGHT ROTATED TWO HUNDRED TWENTY-FIVE DEGREES
#define UC_MACRO_NAME_1FA32 0x1FA32 // 🨲 NEUTRAL CHESS KNIGHT ROTATED TWO HUNDRED TWENTY-FIVE DEGREES
#define UC_MACRO_NAME_1FA33 0x1FA33 // 🨳 WHITE CHESS KING ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA34 0x1FA34 // 🨴 WHITE CHESS QUEEN ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA35 0x1FA35 // 🨵 WHITE CHESS ROOK ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA36 0x1FA36 // 🨶 WHITE CHESS BISHOP ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA37 0x1FA37 // 🨷 WHITE CHESS KNIGHT ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA38 0x1FA38 // 🨸 WHITE CHESS PAWN ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA39 0x1FA39 // 🨹 BLACK CHESS KING ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA3A 0x1FA3A // 🨺 BLACK CHESS QUEEN ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA3B 0x1FA3B // 🨻 BLACK CHESS ROOK ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA3C 0x1FA3C // 🨼 BLACK CHESS BISHOP ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA3D 0x1FA3D // 🨽 BLACK CHESS KNIGHT ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA3E 0x1FA3E // 🨾 BLACK CHESS PAWN ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA3F 0x1FA3F // 🨿 NEUTRAL CHESS KING ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA40 0x1FA40 // 🩀 NEUTRAL CHESS QUEEN ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA41 0x1FA41 // 🩁 NEUTRAL CHESS ROOK ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA42 0x1FA42 // 🩂 NEUTRAL CHESS BISHOP ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA43 0x1FA43 // 🩃 NEUTRAL CHESS KNIGHT ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA44 0x1FA44 // 🩄 NEUTRAL CHESS PAWN ROTATED TWO HUNDRED SEVENTY DEGREES
#define UC_MACRO_NAME_1FA45 0x1FA45 // 🩅 WHITE CHESS KNIGHT ROTATED THREE HUNDRED FIFTEEN DEGREES
#define UC_MACRO_NAME_1FA46 0x1FA46 // 🩆 BLACK CHESS KNIGHT ROTATED THREE HUNDRED FIFTEEN DEGREES
#define UC_MACRO_NAME_1FA47 0x1FA47 // 🩇 NEUTRAL CHESS KNIGHT ROTATED THREE HUNDRED FIFTEEN DEGREES
#define UC_MACRO_NAME_1FA48 0x1FA48 // 🩈 WHITE CHESS EQUIHOPPER
#define UC_MACRO_NAME_1FA49 0x1FA49 // 🩉 BLACK CHESS EQUIHOPPER
#define UC_MACRO_NAME_1FA4A 0x1FA4A // 🩊 NEUTRAL CHESS EQUIHOPPER
#define UC_MACRO_NAME_1FA4B 0x1FA4B // 🩋 WHITE CHESS EQUIHOPPER ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA4C 0x1FA4C // 🩌 BLACK CHESS EQUIHOPPER ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA4D 0x1FA4D // 🩍 NEUTRAL CHESS EQUIHOPPER ROTATED NINETY DEGREES
#define UC_MACRO_NAME_1FA4E 0x1FA4E // 🩎 WHITE CHESS KNIGHT-QUEEN
#define UC_MACRO_NAME_1FA4F 0x1FA4F // 🩏 WHITE CHESS KNIGHT-ROOK
#define UC_MACRO_NAME_1FA50 0x1FA50 // 🩐 WHITE CHESS KNIGHT-BISHOP
#define UC_MACRO_NAME_1FA51 0x1FA51 // 🩑 BLACK CHESS KNIGHT-QUEEN
#define UC_MACRO_NAME_1FA52 0x1FA52 // 🩒 BLACK CHESS KNIGHT-ROOK
#define UC_MACRO_NAME_1FA53 0x1FA53 // 🩓 BLACK CHESS KNIGHT-BISHOP
#define UC_MACRO_NAME_1FA54 0x1FA54 //  WHITE CHESS FERZ
#define UC_MACRO_NAME_1FA55 0x1FA55 //  WHITE CHESS ALFIL
#define UC_MACRO_NAME_1FA56 0x1FA56 //  BLACK CHESS FERZ
#define UC_MACRO_NAME_1FA57 0x1FA57 //  BLACK CHESS ALFIL
#define UC_MACRO_NAME_1FA60 0x1FA60 // 🩠 XIANGQI RED GENERAL
#define UC_MACRO_NAME_1FA61 0x1FA61 // 🩡 XIANGQI RED MANDARIN
#define UC_MACRO_NAME_1FA62 0x1FA62 // 🩢 XIANGQI RED ELEPHANT
#define UC_MACRO_NAME_1FA63 0x1FA63 // 🩣 XIANGQI RED HORSE
#define UC_MACRO_NAME_1FA64 0x1FA64 // 🩤 XIANGQI RED CHARIOT
#define UC_MACRO_NAME_1FA65 0x1FA65 // 🩥 XIANGQI RED CANNON
#define UC_MACRO_NAME_1FA66 0x1FA66 // 🩦 XIANGQI RED SOLDIER
#define UC_MACRO_NAME_1FA67 0x1FA67 // 🩧 XIANGQI BLACK GENERAL
#define UC_MACRO_NAME_1FA68 0x1FA68 // 🩨 XIANGQI BLACK MANDARIN
#define UC_MACRO_NAME_1FA69 0x1FA69 // 🩩 XIANGQI BLACK ELEPHANT
#define UC_MACRO_NAME_1FA6A 0x1FA6A // 🩪 XIANGQI BLACK HORSE
#define UC_MACRO_NAME_1FA6B 0x1FA6B // 🩫 XIANGQI BLACK CHARIOT
#define UC_MACRO_NAME_1FA6C 0x1FA6C // 🩬 XIANGQI BLACK CANNON
#define UC_MACRO_NAME_1FA6D 0x1FA6D // 🩭 XIANGQI BLACK SOLDIER


#endif // UC_H_CHESS_SYMBOLS
