/*
 * Unicode Block: Cyrillic Supplement
 * Range: U+0500..U+052F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Cyrillic Supplement is a Unicode block containing Cyrillic letters for
 * writing several minority languages, including Abkhaz , Kurdish , Komi
 * , Mordvin , Aleut , Azerbaijani , and Jakovlev's Chuvash orthography.
 * The following Unicode-related documents record the purpose and process
 * of defining specific characters in the Cyrillic Supplement block:
 *
 */
#ifndef UC_H_CYRILLIC_SUPPLEMENT
#define UC_H_CYRILLIC_SUPPLEMENT

#define UC_MACRO_NAME_500 0x0500 // Ԁ CYRILLIC CAPITAL LETTER KOMI DE
#define UC_MACRO_NAME_501 0x0501 // ԁ CYRILLIC SMALL LETTER KOMI DE
#define UC_MACRO_NAME_502 0x0502 // Ԃ CYRILLIC CAPITAL LETTER KOMI DJE
#define UC_MACRO_NAME_503 0x0503 // ԃ CYRILLIC SMALL LETTER KOMI DJE
#define UC_MACRO_NAME_504 0x0504 // Ԅ CYRILLIC CAPITAL LETTER KOMI ZJE
#define UC_MACRO_NAME_505 0x0505 // ԅ CYRILLIC SMALL LETTER KOMI ZJE
#define UC_MACRO_NAME_506 0x0506 // Ԇ CYRILLIC CAPITAL LETTER KOMI DZJE
#define UC_MACRO_NAME_507 0x0507 // ԇ CYRILLIC SMALL LETTER KOMI DZJE
#define UC_MACRO_NAME_508 0x0508 // Ԉ CYRILLIC CAPITAL LETTER KOMI LJE
#define UC_MACRO_NAME_509 0x0509 // ԉ CYRILLIC SMALL LETTER KOMI LJE
#define UC_MACRO_NAME_50A 0x050A // Ԋ CYRILLIC CAPITAL LETTER KOMI NJE
#define UC_MACRO_NAME_50B 0x050B // ԋ CYRILLIC SMALL LETTER KOMI NJE
#define UC_MACRO_NAME_50C 0x050C // Ԍ CYRILLIC CAPITAL LETTER KOMI SJE
#define UC_MACRO_NAME_50D 0x050D // ԍ CYRILLIC SMALL LETTER KOMI SJE
#define UC_MACRO_NAME_50E 0x050E // Ԏ CYRILLIC CAPITAL LETTER KOMI TJE
#define UC_MACRO_NAME_50F 0x050F // ԏ CYRILLIC SMALL LETTER KOMI TJE
#define UC_MACRO_NAME_510 0x0510 // Ԑ CYRILLIC CAPITAL LETTER REVERSED ZE
#define UC_MACRO_NAME_511 0x0511 // ԑ CYRILLIC SMALL LETTER REVERSED ZE
#define UC_MACRO_NAME_512 0x0512 // Ԓ CYRILLIC CAPITAL LETTER EL WITH HOOK
#define UC_MACRO_NAME_513 0x0513 // ԓ CYRILLIC SMALL LETTER EL WITH HOOK
#define UC_MACRO_NAME_514 0x0514 // Ԕ CYRILLIC CAPITAL LETTER LHA
#define UC_MACRO_NAME_515 0x0515 // ԕ CYRILLIC SMALL LETTER LHA
#define UC_MACRO_NAME_516 0x0516 // Ԗ CYRILLIC CAPITAL LETTER RHA
#define UC_MACRO_NAME_517 0x0517 // ԗ CYRILLIC SMALL LETTER RHA
#define UC_MACRO_NAME_518 0x0518 // Ԙ CYRILLIC CAPITAL LETTER YAE
#define UC_MACRO_NAME_519 0x0519 // ԙ CYRILLIC SMALL LETTER YAE
#define UC_MACRO_NAME_51A 0x051A // Ԛ CYRILLIC CAPITAL LETTER QA
#define UC_MACRO_NAME_51B 0x051B // ԛ CYRILLIC SMALL LETTER QA
#define UC_MACRO_NAME_51C 0x051C // Ԝ CYRILLIC CAPITAL LETTER WE
#define UC_MACRO_NAME_51D 0x051D // ԝ CYRILLIC SMALL LETTER WE
#define UC_MACRO_NAME_51E 0x051E // Ԟ CYRILLIC CAPITAL LETTER ALEUT KA
#define UC_MACRO_NAME_51F 0x051F // ԟ CYRILLIC SMALL LETTER ALEUT KA
#define UC_MACRO_NAME_520 0x0520 // Ԡ CYRILLIC CAPITAL LETTER EL WITH MIDDLE HOOK
#define UC_MACRO_NAME_521 0x0521 // ԡ CYRILLIC SMALL LETTER EL WITH MIDDLE HOOK
#define UC_MACRO_NAME_522 0x0522 // Ԣ CYRILLIC CAPITAL LETTER EN WITH MIDDLE HOOK
#define UC_MACRO_NAME_523 0x0523 // ԣ CYRILLIC SMALL LETTER EN WITH MIDDLE HOOK
#define UC_MACRO_NAME_524 0x0524 // Ԥ CYRILLIC CAPITAL LETTER PE WITH DESCENDER
#define UC_MACRO_NAME_525 0x0525 // ԥ CYRILLIC SMALL LETTER PE WITH DESCENDER
#define UC_MACRO_NAME_526 0x0526 // Ԧ CYRILLIC CAPITAL LETTER SHHA WITH DESCENDER
#define UC_MACRO_NAME_527 0x0527 // ԧ CYRILLIC SMALL LETTER SHHA WITH DESCENDER
#define UC_MACRO_NAME_528 0x0528 // Ԩ CYRILLIC CAPITAL LETTER EN WITH LEFT HOOK
#define UC_MACRO_NAME_529 0x0529 // ԩ CYRILLIC SMALL LETTER EN WITH LEFT HOOK
#define UC_MACRO_NAME_52A 0x052A // Ԫ CYRILLIC CAPITAL LETTER DZZHE
#define UC_MACRO_NAME_52B 0x052B // ԫ CYRILLIC SMALL LETTER DZZHE
#define UC_MACRO_NAME_52C 0x052C // Ԭ CYRILLIC CAPITAL LETTER DCHE
#define UC_MACRO_NAME_52D 0x052D // ԭ CYRILLIC SMALL LETTER DCHE
#define UC_MACRO_NAME_52E 0x052E // Ԯ CYRILLIC CAPITAL LETTER EL WITH DESCENDER
#define UC_MACRO_NAME_52F 0x052F // ԯ CYRILLIC SMALL LETTER EL WITH DESCENDER


#endif // UC_H_CYRILLIC_SUPPLEMENT
