/*
 * Unicode Block: Cyrillic Extended-B
 * Range: U+A640..U+A69F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_CYRILLIC_EXTENDED_B
#define UC_H_CYRILLIC_EXTENDED_B

#define UC_MACRO_NAME_A640 0xA640 // Ꙁ CYRILLIC CAPITAL LETTER ZEMLYA
#define UC_MACRO_NAME_A641 0xA641 // ꙁ CYRILLIC SMALL LETTER ZEMLYA
#define UC_MACRO_NAME_A642 0xA642 // Ꙃ CYRILLIC CAPITAL LETTER DZELO
#define UC_MACRO_NAME_A643 0xA643 // ꙃ CYRILLIC SMALL LETTER DZELO
#define UC_MACRO_NAME_A644 0xA644 // Ꙅ CYRILLIC CAPITAL LETTER REVERSED DZE
#define UC_MACRO_NAME_A645 0xA645 // ꙅ CYRILLIC SMALL LETTER REVERSED DZE
#define UC_MACRO_NAME_A646 0xA646 // Ꙇ CYRILLIC CAPITAL LETTER IOTA
#define UC_MACRO_NAME_A647 0xA647 // ꙇ CYRILLIC SMALL LETTER IOTA
#define UC_MACRO_NAME_A648 0xA648 // Ꙉ CYRILLIC CAPITAL LETTER DJERV
#define UC_MACRO_NAME_A649 0xA649 // ꙉ CYRILLIC SMALL LETTER DJERV
#define UC_MACRO_NAME_A64A 0xA64A // Ꙋ CYRILLIC CAPITAL LETTER MONOGRAPH UK
#define UC_MACRO_NAME_A64B 0xA64B // ꙋ CYRILLIC SMALL LETTER MONOGRAPH UK
#define UC_MACRO_NAME_A64C 0xA64C // Ꙍ CYRILLIC CAPITAL LETTER BROAD OMEGA
#define UC_MACRO_NAME_A64D 0xA64D // ꙍ CYRILLIC SMALL LETTER BROAD OMEGA
#define UC_MACRO_NAME_A64E 0xA64E // Ꙏ CYRILLIC CAPITAL LETTER NEUTRAL YER
#define UC_MACRO_NAME_A64F 0xA64F // ꙏ CYRILLIC SMALL LETTER NEUTRAL YER
#define UC_MACRO_NAME_A650 0xA650 // Ꙑ CYRILLIC CAPITAL LETTER YERU WITH BACK YER
#define UC_MACRO_NAME_A651 0xA651 // ꙑ CYRILLIC SMALL LETTER YERU WITH BACK YER
#define UC_MACRO_NAME_A652 0xA652 // Ꙓ CYRILLIC CAPITAL LETTER IOTIFIED YAT
#define UC_MACRO_NAME_A653 0xA653 // ꙓ CYRILLIC SMALL LETTER IOTIFIED YAT
#define UC_MACRO_NAME_A654 0xA654 // Ꙕ CYRILLIC CAPITAL LETTER REVERSED YU
#define UC_MACRO_NAME_A655 0xA655 // ꙕ CYRILLIC SMALL LETTER REVERSED YU
#define UC_MACRO_NAME_A656 0xA656 // Ꙗ CYRILLIC CAPITAL LETTER IOTIFIED A
#define UC_MACRO_NAME_A657 0xA657 // ꙗ CYRILLIC SMALL LETTER IOTIFIED A
#define UC_MACRO_NAME_A658 0xA658 // Ꙙ CYRILLIC CAPITAL LETTER CLOSED LITTLE YUS
#define UC_MACRO_NAME_A659 0xA659 // ꙙ CYRILLIC SMALL LETTER CLOSED LITTLE YUS
#define UC_MACRO_NAME_A65A 0xA65A // Ꙛ CYRILLIC CAPITAL LETTER BLENDED YUS
#define UC_MACRO_NAME_A65B 0xA65B // ꙛ CYRILLIC SMALL LETTER BLENDED YUS
#define UC_MACRO_NAME_A65C 0xA65C // Ꙝ CYRILLIC CAPITAL LETTER IOTIFIED CLOSED LITTLE YUS
#define UC_MACRO_NAME_A65D 0xA65D // ꙝ CYRILLIC SMALL LETTER IOTIFIED CLOSED LITTLE YUS
#define UC_MACRO_NAME_A65E 0xA65E // Ꙟ CYRILLIC CAPITAL LETTER YN
#define UC_MACRO_NAME_A65F 0xA65F // ꙟ CYRILLIC SMALL LETTER YN
#define UC_MACRO_NAME_A660 0xA660 // Ꙡ CYRILLIC CAPITAL LETTER REVERSED TSE
#define UC_MACRO_NAME_A661 0xA661 // ꙡ CYRILLIC SMALL LETTER REVERSED TSE
#define UC_MACRO_NAME_A662 0xA662 // Ꙣ CYRILLIC CAPITAL LETTER SOFT DE
#define UC_MACRO_NAME_A663 0xA663 // ꙣ CYRILLIC SMALL LETTER SOFT DE
#define UC_MACRO_NAME_A664 0xA664 // Ꙥ CYRILLIC CAPITAL LETTER SOFT EL
#define UC_MACRO_NAME_A665 0xA665 // ꙥ CYRILLIC SMALL LETTER SOFT EL
#define UC_MACRO_NAME_A666 0xA666 // Ꙧ CYRILLIC CAPITAL LETTER SOFT EM
#define UC_MACRO_NAME_A667 0xA667 // ꙧ CYRILLIC SMALL LETTER SOFT EM
#define UC_MACRO_NAME_A668 0xA668 // Ꙩ CYRILLIC CAPITAL LETTER MONOCULAR O
#define UC_MACRO_NAME_A669 0xA669 // ꙩ CYRILLIC SMALL LETTER MONOCULAR O
#define UC_MACRO_NAME_A66A 0xA66A // Ꙫ CYRILLIC CAPITAL LETTER BINOCULAR O
#define UC_MACRO_NAME_A66B 0xA66B // ꙫ CYRILLIC SMALL LETTER BINOCULAR O
#define UC_MACRO_NAME_A66C 0xA66C // Ꙭ CYRILLIC CAPITAL LETTER DOUBLE MONOCULAR O
#define UC_MACRO_NAME_A66D 0xA66D // ꙭ CYRILLIC SMALL LETTER DOUBLE MONOCULAR O
#define UC_MACRO_NAME_A66E 0xA66E // ꙮ CYRILLIC LETTER MULTIOCULAR O
#define UC_MACRO_NAME_A66F 0xA66F // ꙯ COMBINING CYRILLIC VZMET
#define UC_MACRO_NAME_A670 0xA670 // ꙰ COMBINING CYRILLIC TEN MILLIONS SIGN
#define UC_MACRO_NAME_A671 0xA671 // ꙱ COMBINING CYRILLIC HUNDRED MILLIONS SIGN
#define UC_MACRO_NAME_A672 0xA672 // ꙲ COMBINING CYRILLIC THOUSAND MILLIONS SIGN
#define UC_MACRO_NAME_A673 0xA673 // ꙳ SLAVONIC ASTERISK
#define UC_MACRO_NAME_A674 0xA674 // ꙴ COMBINING CYRILLIC LETTER UKRAINIAN IE
#define UC_MACRO_NAME_A675 0xA675 // ꙵ COMBINING CYRILLIC LETTER I
#define UC_MACRO_NAME_A676 0xA676 // ꙶ COMBINING CYRILLIC LETTER YI
#define UC_MACRO_NAME_A677 0xA677 // ꙷ COMBINING CYRILLIC LETTER U
#define UC_MACRO_NAME_A678 0xA678 // ꙸ COMBINING CYRILLIC LETTER HARD SIGN
#define UC_MACRO_NAME_A679 0xA679 // ꙹ COMBINING CYRILLIC LETTER YERU
#define UC_MACRO_NAME_A67A 0xA67A // ꙺ COMBINING CYRILLIC LETTER SOFT SIGN
#define UC_MACRO_NAME_A67B 0xA67B // ꙻ COMBINING CYRILLIC LETTER OMEGA
#define UC_MACRO_NAME_A67C 0xA67C // ꙼ COMBINING CYRILLIC KAVYKA
#define UC_MACRO_NAME_A67D 0xA67D // ꙽ COMBINING CYRILLIC PAYEROK
#define UC_MACRO_NAME_A67E 0xA67E // ꙾ CYRILLIC KAVYKA
#define UC_MACRO_NAME_A67F 0xA67F // ꙿ CYRILLIC PAYEROK
#define UC_MACRO_NAME_A680 0xA680 // Ꚁ CYRILLIC CAPITAL LETTER DWE
#define UC_MACRO_NAME_A681 0xA681 // ꚁ CYRILLIC SMALL LETTER DWE
#define UC_MACRO_NAME_A682 0xA682 // Ꚃ CYRILLIC CAPITAL LETTER DZWE
#define UC_MACRO_NAME_A683 0xA683 // ꚃ CYRILLIC SMALL LETTER DZWE
#define UC_MACRO_NAME_A684 0xA684 // Ꚅ CYRILLIC CAPITAL LETTER ZHWE
#define UC_MACRO_NAME_A685 0xA685 // ꚅ CYRILLIC SMALL LETTER ZHWE
#define UC_MACRO_NAME_A686 0xA686 // Ꚇ CYRILLIC CAPITAL LETTER CCHE
#define UC_MACRO_NAME_A687 0xA687 // ꚇ CYRILLIC SMALL LETTER CCHE
#define UC_MACRO_NAME_A688 0xA688 // Ꚉ CYRILLIC CAPITAL LETTER DZZE
#define UC_MACRO_NAME_A689 0xA689 // ꚉ CYRILLIC SMALL LETTER DZZE
#define UC_MACRO_NAME_A68A 0xA68A // Ꚋ CYRILLIC CAPITAL LETTER TE WITH MIDDLE HOOK
#define UC_MACRO_NAME_A68B 0xA68B // ꚋ CYRILLIC SMALL LETTER TE WITH MIDDLE HOOK
#define UC_MACRO_NAME_A68C 0xA68C // Ꚍ CYRILLIC CAPITAL LETTER TWE
#define UC_MACRO_NAME_A68D 0xA68D // ꚍ CYRILLIC SMALL LETTER TWE
#define UC_MACRO_NAME_A68E 0xA68E // Ꚏ CYRILLIC CAPITAL LETTER TSWE
#define UC_MACRO_NAME_A68F 0xA68F // ꚏ CYRILLIC SMALL LETTER TSWE
#define UC_MACRO_NAME_A690 0xA690 // Ꚑ CYRILLIC CAPITAL LETTER TSSE
#define UC_MACRO_NAME_A691 0xA691 // ꚑ CYRILLIC SMALL LETTER TSSE
#define UC_MACRO_NAME_A692 0xA692 // Ꚓ CYRILLIC CAPITAL LETTER TCHE
#define UC_MACRO_NAME_A693 0xA693 // ꚓ CYRILLIC SMALL LETTER TCHE
#define UC_MACRO_NAME_A694 0xA694 // Ꚕ CYRILLIC CAPITAL LETTER HWE
#define UC_MACRO_NAME_A695 0xA695 // ꚕ CYRILLIC SMALL LETTER HWE
#define UC_MACRO_NAME_A696 0xA696 // Ꚗ CYRILLIC CAPITAL LETTER SHWE
#define UC_MACRO_NAME_A697 0xA697 // ꚗ CYRILLIC SMALL LETTER SHWE
#define UC_MACRO_NAME_A698 0xA698 // Ꚙ CYRILLIC CAPITAL LETTER DOUBLE O
#define UC_MACRO_NAME_A699 0xA699 // ꚙ CYRILLIC SMALL LETTER DOUBLE O
#define UC_MACRO_NAME_A69A 0xA69A // Ꚛ CYRILLIC CAPITAL LETTER CROSSED O
#define UC_MACRO_NAME_A69B 0xA69B // ꚛ CYRILLIC SMALL LETTER CROSSED O
#define UC_MACRO_NAME_A69C 0xA69C // ꚜ MODIFIER LETTER CYRILLIC HARD SIGN
#define UC_MACRO_NAME_A69D 0xA69D // ꚝ MODIFIER LETTER CYRILLIC SOFT SIGN
#define UC_MACRO_NAME_A69E 0xA69E // ꚞ COMBINING CYRILLIC LETTER EF
#define UC_MACRO_NAME_A69F 0xA69F // ꚟ COMBINING CYRILLIC LETTER IOTIFIED E


#endif // UC_H_CYRILLIC_EXTENDED_B
