/*
 * Unicode Block: Combining Diacritical Marks Supplement
 * Range: U+1DC0..U+1DFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Combining Diacritical Marks Supplement is a Unicode block containing
 * combining characters for the Uralic Phonetic Alphabet , Medievalist
 * notations, and German dialectology ( Teuthonista ). It is an extension
 * of the diacritic characters found in the Combining Diacritical Marks
 * block.
 * The following Unicode-related documents record the purpose and process
 * of defining specific characters in the Combining Diacritical Marks
 * Supplement block:
 *
 */
#ifndef UC_H_COMBINING_DIACRITICAL_MARKS_SUPPLEMENT
#define UC_H_COMBINING_DIACRITICAL_MARKS_SUPPLEMENT

#define UC_MACRO_NAME_1DC0 0x1DC0 // ᷀ COMBINING DOTTED GRAVE ACCENT
#define UC_MACRO_NAME_1DC1 0x1DC1 // ᷁ COMBINING DOTTED ACUTE ACCENT
#define UC_MACRO_NAME_1DC2 0x1DC2 // ᷂ COMBINING SNAKE BELOW
#define UC_MACRO_NAME_1DC3 0x1DC3 // ᷃ COMBINING SUSPENSION MARK
#define UC_MACRO_NAME_1DC4 0x1DC4 // ᷄ COMBINING MACRON-ACUTE
#define UC_MACRO_NAME_1DC5 0x1DC5 // ᷅ COMBINING GRAVE-MACRON
#define UC_MACRO_NAME_1DC6 0x1DC6 // ᷆ COMBINING MACRON-GRAVE
#define UC_MACRO_NAME_1DC7 0x1DC7 // ᷇ COMBINING ACUTE-MACRON
#define UC_MACRO_NAME_1DC8 0x1DC8 // ᷈ COMBINING GRAVE-ACUTE-GRAVE
#define UC_MACRO_NAME_1DC9 0x1DC9 // ᷉ COMBINING ACUTE-GRAVE-ACUTE
#define UC_MACRO_NAME_1DCA 0x1DCA // ᷊ COMBINING LATIN SMALL LETTER R BELOW
#define UC_MACRO_NAME_1DCB 0x1DCB // ᷋ COMBINING BREVE-MACRON
#define UC_MACRO_NAME_1DCC 0x1DCC // ᷌ COMBINING MACRON-BREVE
#define UC_MACRO_NAME_1DCD 0x1DCD // ᷍ COMBINING DOUBLE CIRCUMFLEX ABOVE
#define UC_MACRO_NAME_1DCE 0x1DCE // ᷎ COMBINING OGONEK ABOVE
#define UC_MACRO_NAME_1DCF 0x1DCF // ᷏ COMBINING ZIGZAG BELOW
#define UC_MACRO_NAME_1DD0 0x1DD0 // ᷐ COMBINING IS BELOW
#define UC_MACRO_NAME_1DD1 0x1DD1 // ᷑ COMBINING UR ABOVE
#define UC_MACRO_NAME_1DD2 0x1DD2 // ᷒ COMBINING US ABOVE
#define UC_MACRO_NAME_1DD3 0x1DD3 // ᷓ COMBINING LATIN SMALL LETTER FLATTENED OPEN A ABOVE
#define UC_MACRO_NAME_1DD4 0x1DD4 // ᷔ COMBINING LATIN SMALL LETTER AE
#define UC_MACRO_NAME_1DD5 0x1DD5 // ᷕ COMBINING LATIN SMALL LETTER AO
#define UC_MACRO_NAME_1DD6 0x1DD6 // ᷖ COMBINING LATIN SMALL LETTER AV
#define UC_MACRO_NAME_1DD7 0x1DD7 // ᷗ COMBINING LATIN SMALL LETTER C CEDILLA
#define UC_MACRO_NAME_1DD8 0x1DD8 // ᷘ COMBINING LATIN SMALL LETTER INSULAR D
#define UC_MACRO_NAME_1DD9 0x1DD9 // ᷙ COMBINING LATIN SMALL LETTER ETH
#define UC_MACRO_NAME_1DDA 0x1DDA // ᷚ COMBINING LATIN SMALL LETTER G
#define UC_MACRO_NAME_1DDB 0x1DDB // ᷛ COMBINING LATIN LETTER SMALL CAPITAL G
#define UC_MACRO_NAME_1DDC 0x1DDC // ᷜ COMBINING LATIN SMALL LETTER K
#define UC_MACRO_NAME_1DDD 0x1DDD // ᷝ COMBINING LATIN SMALL LETTER L
#define UC_MACRO_NAME_1DDE 0x1DDE // ᷞ COMBINING LATIN LETTER SMALL CAPITAL L
#define UC_MACRO_NAME_1DDF 0x1DDF // ᷟ COMBINING LATIN LETTER SMALL CAPITAL M
#define UC_MACRO_NAME_1DE0 0x1DE0 // ᷠ COMBINING LATIN SMALL LETTER N
#define UC_MACRO_NAME_1DE1 0x1DE1 // ᷡ COMBINING LATIN LETTER SMALL CAPITAL N
#define UC_MACRO_NAME_1DE2 0x1DE2 // ᷢ COMBINING LATIN LETTER SMALL CAPITAL R
#define UC_MACRO_NAME_1DE3 0x1DE3 // ᷣ COMBINING LATIN SMALL LETTER R ROTUNDA
#define UC_MACRO_NAME_1DE4 0x1DE4 // ᷤ COMBINING LATIN SMALL LETTER S
#define UC_MACRO_NAME_1DE5 0x1DE5 // ᷥ COMBINING LATIN SMALL LETTER LONG S
#define UC_MACRO_NAME_1DE6 0x1DE6 // ᷦ COMBINING LATIN SMALL LETTER Z
#define UC_MACRO_NAME_1DE7 0x1DE7 // ᷧ COMBINING LATIN SMALL LETTER ALPHA
#define UC_MACRO_NAME_1DE8 0x1DE8 // ᷨ COMBINING LATIN SMALL LETTER B
#define UC_MACRO_NAME_1DE9 0x1DE9 // ᷩ COMBINING LATIN SMALL LETTER BETA
#define UC_MACRO_NAME_1DEA 0x1DEA // ᷪ COMBINING LATIN SMALL LETTER SCHWA
#define UC_MACRO_NAME_1DEB 0x1DEB // ᷫ COMBINING LATIN SMALL LETTER F
#define UC_MACRO_NAME_1DEC 0x1DEC // ᷬ COMBINING LATIN SMALL LETTER L WITH DOUBLE MIDDLE TILDE
#define UC_MACRO_NAME_1DED 0x1DED // ᷭ COMBINING LATIN SMALL LETTER O WITH LIGHT CENTRALIZATION STROKE
#define UC_MACRO_NAME_1DEE 0x1DEE // ᷮ COMBINING LATIN SMALL LETTER P
#define UC_MACRO_NAME_1DEF 0x1DEF // ᷯ COMBINING LATIN SMALL LETTER ESH
#define UC_MACRO_NAME_1DF0 0x1DF0 // ᷰ COMBINING LATIN SMALL LETTER U WITH LIGHT CENTRALIZATION STROKE
#define UC_MACRO_NAME_1DF1 0x1DF1 // ᷱ COMBINING LATIN SMALL LETTER W
#define UC_MACRO_NAME_1DF2 0x1DF2 // ᷲ COMBINING LATIN SMALL LETTER A WITH DIAERESIS
#define UC_MACRO_NAME_1DF3 0x1DF3 // ᷳ COMBINING LATIN SMALL LETTER O WITH DIAERESIS
#define UC_MACRO_NAME_1DF4 0x1DF4 // ᷴ COMBINING LATIN SMALL LETTER U WITH DIAERESIS
#define UC_MACRO_NAME_1DF5 0x1DF5 // ᷵ COMBINING UP TACK ABOVE
#define UC_MACRO_NAME_1DF6 0x1DF6 // ᷶ COMBINING KAVYKA ABOVE RIGHT
#define UC_MACRO_NAME_1DF7 0x1DF7 // ᷷ COMBINING KAVYKA ABOVE LEFT
#define UC_MACRO_NAME_1DF8 0x1DF8 // ᷸ COMBINING DOT ABOVE LEFT
#define UC_MACRO_NAME_1DF9 0x1DF9 // ᷹ COMBINING WIDE INVERTED BRIDGE BELOW
#define UC_MACRO_NAME_1DFA 0x1DFA // ᷺ COMBINING DOT BELOW LEFT
#define UC_MACRO_NAME_1DFB 0x1DFB // ᷻ COMBINING DELETION MARK
#define UC_MACRO_NAME_1DFC 0x1DFC // ᷼ COMBINING DOUBLE INVERTED BREVE BELOW
#define UC_MACRO_NAME_1DFD 0x1DFD // ᷽ COMBINING ALMOST EQUAL TO BELOW
#define UC_MACRO_NAME_1DFE 0x1DFE // ᷾ COMBINING LEFT ARROWHEAD ABOVE
#define UC_MACRO_NAME_1DFF 0x1DFF // ᷿ COMBINING RIGHT ARROWHEAD AND DOWN ARROWHEAD BELOW


#endif // UC_H_COMBINING_DIACRITICAL_MARKS_SUPPLEMENT
