/*
 * Unicode Block: Duployan
 * Range: U+1BC00..U+1BC9F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * The Duployan shorthand , or Duployan stenography ( French :
 * Sténographie Duployé ), is a shorthand writing system created by
 * Father Émile Duployé in 1860 originally for writing French . Since
 * then, it has been expanded and adapted for writing English , German ,
 * Spanish , Romanian , Latin , Danish , and Chinook Jargon . The
 * Duployan stenography is classified as a geometric , alphabetic
 * stenography and is written left-to-right in connected stenographic
 * style. The Duployan shorthands, including Chinook writing, Pernin's
 * Universal Phonography, Perrault's English Shorthand, the
 * Sloan-Duployan Modern Shorthand, and Romanian stenography, were
 * included as a single script in version 7.0 of the Unicode Standard /
 * ISO 10646
 *
 */
#ifndef UC_H_DUPLOYAN
#define UC_H_DUPLOYAN

#define UC_MACRO_NAME_1BC00 0x1BC00 // 𛰀 DUPLOYAN LETTER H
#define UC_MACRO_NAME_1BC01 0x1BC01 // 𛰁 DUPLOYAN LETTER X
#define UC_MACRO_NAME_1BC02 0x1BC02 // 𛰂 DUPLOYAN LETTER P
#define UC_MACRO_NAME_1BC03 0x1BC03 // 𛰃 DUPLOYAN LETTER T
#define UC_MACRO_NAME_1BC04 0x1BC04 // 𛰄 DUPLOYAN LETTER F
#define UC_MACRO_NAME_1BC05 0x1BC05 // 𛰅 DUPLOYAN LETTER K
#define UC_MACRO_NAME_1BC06 0x1BC06 // 𛰆 DUPLOYAN LETTER L
#define UC_MACRO_NAME_1BC07 0x1BC07 // 𛰇 DUPLOYAN LETTER B
#define UC_MACRO_NAME_1BC08 0x1BC08 // 𛰈 DUPLOYAN LETTER D
#define UC_MACRO_NAME_1BC09 0x1BC09 // 𛰉 DUPLOYAN LETTER V
#define UC_MACRO_NAME_1BC0A 0x1BC0A // 𛰊 DUPLOYAN LETTER G
#define UC_MACRO_NAME_1BC0B 0x1BC0B // 𛰋 DUPLOYAN LETTER R
#define UC_MACRO_NAME_1BC0C 0x1BC0C // 𛰌 DUPLOYAN LETTER P N
#define UC_MACRO_NAME_1BC0D 0x1BC0D // 𛰍 DUPLOYAN LETTER D S
#define UC_MACRO_NAME_1BC0E 0x1BC0E // 𛰎 DUPLOYAN LETTER F N
#define UC_MACRO_NAME_1BC0F 0x1BC0F // 𛰏 DUPLOYAN LETTER K M
#define UC_MACRO_NAME_1BC10 0x1BC10 // 𛰐 DUPLOYAN LETTER R S
#define UC_MACRO_NAME_1BC11 0x1BC11 // 𛰑 DUPLOYAN LETTER TH
#define UC_MACRO_NAME_1BC12 0x1BC12 // 𛰒 DUPLOYAN LETTER SLOAN DH
#define UC_MACRO_NAME_1BC13 0x1BC13 // 𛰓 DUPLOYAN LETTER DH
#define UC_MACRO_NAME_1BC14 0x1BC14 // 𛰔 DUPLOYAN LETTER KK
#define UC_MACRO_NAME_1BC15 0x1BC15 // 𛰕 DUPLOYAN LETTER SLOAN J
#define UC_MACRO_NAME_1BC16 0x1BC16 // 𛰖 DUPLOYAN LETTER HL
#define UC_MACRO_NAME_1BC17 0x1BC17 // 𛰗 DUPLOYAN LETTER LH
#define UC_MACRO_NAME_1BC18 0x1BC18 // 𛰘 DUPLOYAN LETTER RH
#define UC_MACRO_NAME_1BC19 0x1BC19 // 𛰙 DUPLOYAN LETTER M
#define UC_MACRO_NAME_1BC1A 0x1BC1A // 𛰚 DUPLOYAN LETTER N
#define UC_MACRO_NAME_1BC1B 0x1BC1B // 𛰛 DUPLOYAN LETTER J
#define UC_MACRO_NAME_1BC1C 0x1BC1C // 𛰜 DUPLOYAN LETTER S
#define UC_MACRO_NAME_1BC1D 0x1BC1D // 𛰝 DUPLOYAN LETTER M N
#define UC_MACRO_NAME_1BC1E 0x1BC1E // 𛰞 DUPLOYAN LETTER N M
#define UC_MACRO_NAME_1BC1F 0x1BC1F // 𛰟 DUPLOYAN LETTER J M
#define UC_MACRO_NAME_1BC20 0x1BC20 // 𛰠 DUPLOYAN LETTER S J
#define UC_MACRO_NAME_1BC21 0x1BC21 // 𛰡 DUPLOYAN LETTER M WITH DOT
#define UC_MACRO_NAME_1BC22 0x1BC22 // 𛰢 DUPLOYAN LETTER N WITH DOT
#define UC_MACRO_NAME_1BC23 0x1BC23 // 𛰣 DUPLOYAN LETTER J WITH DOT
#define UC_MACRO_NAME_1BC24 0x1BC24 // 𛰤 DUPLOYAN LETTER J WITH DOTS INSIDE AND ABOVE
#define UC_MACRO_NAME_1BC25 0x1BC25 // 𛰥 DUPLOYAN LETTER S WITH DOT
#define UC_MACRO_NAME_1BC26 0x1BC26 // 𛰦 DUPLOYAN LETTER S WITH DOT BELOW
#define UC_MACRO_NAME_1BC27 0x1BC27 // 𛰧 DUPLOYAN LETTER M S
#define UC_MACRO_NAME_1BC28 0x1BC28 // 𛰨 DUPLOYAN LETTER N S
#define UC_MACRO_NAME_1BC29 0x1BC29 // 𛰩 DUPLOYAN LETTER J S
#define UC_MACRO_NAME_1BC2A 0x1BC2A // 𛰪 DUPLOYAN LETTER S S
#define UC_MACRO_NAME_1BC2B 0x1BC2B // 𛰫 DUPLOYAN LETTER M N S
#define UC_MACRO_NAME_1BC2C 0x1BC2C // 𛰬 DUPLOYAN LETTER N M S
#define UC_MACRO_NAME_1BC2D 0x1BC2D // 𛰭 DUPLOYAN LETTER J M S
#define UC_MACRO_NAME_1BC2E 0x1BC2E // 𛰮 DUPLOYAN LETTER S J S
#define UC_MACRO_NAME_1BC2F 0x1BC2F // 𛰯 DUPLOYAN LETTER J S WITH DOT
#define UC_MACRO_NAME_1BC30 0x1BC30 // 𛰰 DUPLOYAN LETTER J N
#define UC_MACRO_NAME_1BC31 0x1BC31 // 𛰱 DUPLOYAN LETTER J N S
#define UC_MACRO_NAME_1BC32 0x1BC32 // 𛰲 DUPLOYAN LETTER S T
#define UC_MACRO_NAME_1BC33 0x1BC33 // 𛰳 DUPLOYAN LETTER S T R
#define UC_MACRO_NAME_1BC34 0x1BC34 // 𛰴 DUPLOYAN LETTER S P
#define UC_MACRO_NAME_1BC35 0x1BC35 // 𛰵 DUPLOYAN LETTER S P R
#define UC_MACRO_NAME_1BC36 0x1BC36 // 𛰶 DUPLOYAN LETTER T S
#define UC_MACRO_NAME_1BC37 0x1BC37 // 𛰷 DUPLOYAN LETTER T R S
#define UC_MACRO_NAME_1BC38 0x1BC38 // 𛰸 DUPLOYAN LETTER W
#define UC_MACRO_NAME_1BC39 0x1BC39 // 𛰹 DUPLOYAN LETTER WH
#define UC_MACRO_NAME_1BC3A 0x1BC3A // 𛰺 DUPLOYAN LETTER W R
#define UC_MACRO_NAME_1BC3B 0x1BC3B // 𛰻 DUPLOYAN LETTER S N
#define UC_MACRO_NAME_1BC3C 0x1BC3C // 𛰼 DUPLOYAN LETTER S M
#define UC_MACRO_NAME_1BC3D 0x1BC3D // 𛰽 DUPLOYAN LETTER K R S
#define UC_MACRO_NAME_1BC3E 0x1BC3E // 𛰾 DUPLOYAN LETTER G R S
#define UC_MACRO_NAME_1BC3F 0x1BC3F // 𛰿 DUPLOYAN LETTER S K
#define UC_MACRO_NAME_1BC40 0x1BC40 // 𛱀 DUPLOYAN LETTER S K R
#define UC_MACRO_NAME_1BC41 0x1BC41 // 𛱁 DUPLOYAN LETTER A
#define UC_MACRO_NAME_1BC42 0x1BC42 // 𛱂 DUPLOYAN LETTER SLOAN OW
#define UC_MACRO_NAME_1BC43 0x1BC43 // 𛱃 DUPLOYAN LETTER OA
#define UC_MACRO_NAME_1BC44 0x1BC44 // 𛱄 DUPLOYAN LETTER O
#define UC_MACRO_NAME_1BC45 0x1BC45 // 𛱅 DUPLOYAN LETTER AOU
#define UC_MACRO_NAME_1BC46 0x1BC46 // 𛱆 DUPLOYAN LETTER I
#define UC_MACRO_NAME_1BC47 0x1BC47 // 𛱇 DUPLOYAN LETTER E
#define UC_MACRO_NAME_1BC48 0x1BC48 // 𛱈 DUPLOYAN LETTER IE
#define UC_MACRO_NAME_1BC49 0x1BC49 // 𛱉 DUPLOYAN LETTER SHORT I
#define UC_MACRO_NAME_1BC4A 0x1BC4A // 𛱊 DUPLOYAN LETTER UI
#define UC_MACRO_NAME_1BC4B 0x1BC4B // 𛱋 DUPLOYAN LETTER EE
#define UC_MACRO_NAME_1BC4C 0x1BC4C // 𛱌 DUPLOYAN LETTER SLOAN EH
#define UC_MACRO_NAME_1BC4D 0x1BC4D // 𛱍 DUPLOYAN LETTER ROMANIAN I
#define UC_MACRO_NAME_1BC4E 0x1BC4E // 𛱎 DUPLOYAN LETTER SLOAN EE
#define UC_MACRO_NAME_1BC4F 0x1BC4F // 𛱏 DUPLOYAN LETTER LONG I
#define UC_MACRO_NAME_1BC50 0x1BC50 // 𛱐 DUPLOYAN LETTER YE
#define UC_MACRO_NAME_1BC51 0x1BC51 // 𛱑 DUPLOYAN LETTER U
#define UC_MACRO_NAME_1BC52 0x1BC52 // 𛱒 DUPLOYAN LETTER EU
#define UC_MACRO_NAME_1BC53 0x1BC53 // 𛱓 DUPLOYAN LETTER XW
#define UC_MACRO_NAME_1BC54 0x1BC54 // 𛱔 DUPLOYAN LETTER U N
#define UC_MACRO_NAME_1BC55 0x1BC55 // 𛱕 DUPLOYAN LETTER LONG U
#define UC_MACRO_NAME_1BC56 0x1BC56 // 𛱖 DUPLOYAN LETTER ROMANIAN U
#define UC_MACRO_NAME_1BC57 0x1BC57 // 𛱗 DUPLOYAN LETTER UH
#define UC_MACRO_NAME_1BC58 0x1BC58 // 𛱘 DUPLOYAN LETTER SLOAN U
#define UC_MACRO_NAME_1BC59 0x1BC59 // 𛱙 DUPLOYAN LETTER OOH
#define UC_MACRO_NAME_1BC5A 0x1BC5A // 𛱚 DUPLOYAN LETTER OW
#define UC_MACRO_NAME_1BC5B 0x1BC5B // 𛱛 DUPLOYAN LETTER OU
#define UC_MACRO_NAME_1BC5C 0x1BC5C // 𛱜 DUPLOYAN LETTER WA
#define UC_MACRO_NAME_1BC5D 0x1BC5D // 𛱝 DUPLOYAN LETTER WO
#define UC_MACRO_NAME_1BC5E 0x1BC5E // 𛱞 DUPLOYAN LETTER WI
#define UC_MACRO_NAME_1BC5F 0x1BC5F // 𛱟 DUPLOYAN LETTER WEI
#define UC_MACRO_NAME_1BC60 0x1BC60 // 𛱠 DUPLOYAN LETTER WOW
#define UC_MACRO_NAME_1BC61 0x1BC61 // 𛱡 DUPLOYAN LETTER NASAL U
#define UC_MACRO_NAME_1BC62 0x1BC62 // 𛱢 DUPLOYAN LETTER NASAL O
#define UC_MACRO_NAME_1BC63 0x1BC63 // 𛱣 DUPLOYAN LETTER NASAL I
#define UC_MACRO_NAME_1BC64 0x1BC64 // 𛱤 DUPLOYAN LETTER NASAL A
#define UC_MACRO_NAME_1BC65 0x1BC65 // 𛱥 DUPLOYAN LETTER PERNIN AN
#define UC_MACRO_NAME_1BC66 0x1BC66 // 𛱦 DUPLOYAN LETTER PERNIN AM
#define UC_MACRO_NAME_1BC67 0x1BC67 // 𛱧 DUPLOYAN LETTER SLOAN EN
#define UC_MACRO_NAME_1BC68 0x1BC68 // 𛱨 DUPLOYAN LETTER SLOAN AN
#define UC_MACRO_NAME_1BC69 0x1BC69 // 𛱩 DUPLOYAN LETTER SLOAN ON
#define UC_MACRO_NAME_1BC6A 0x1BC6A // 𛱪 DUPLOYAN LETTER VOCALIC M
#define UC_MACRO_NAME_1BC70 0x1BC70 // 𛱰 DUPLOYAN AFFIX LEFT HORIZONTAL SECANT
#define UC_MACRO_NAME_1BC71 0x1BC71 // 𛱱 DUPLOYAN AFFIX MID HORIZONTAL SECANT
#define UC_MACRO_NAME_1BC72 0x1BC72 // 𛱲 DUPLOYAN AFFIX RIGHT HORIZONTAL SECANT
#define UC_MACRO_NAME_1BC73 0x1BC73 // 𛱳 DUPLOYAN AFFIX LOW VERTICAL SECANT
#define UC_MACRO_NAME_1BC74 0x1BC74 // 𛱴 DUPLOYAN AFFIX MID VERTICAL SECANT
#define UC_MACRO_NAME_1BC75 0x1BC75 // 𛱵 DUPLOYAN AFFIX HIGH VERTICAL SECANT
#define UC_MACRO_NAME_1BC76 0x1BC76 // 𛱶 DUPLOYAN AFFIX ATTACHED SECANT
#define UC_MACRO_NAME_1BC77 0x1BC77 // 𛱷 DUPLOYAN AFFIX ATTACHED LEFT-TO-RIGHT SECANT
#define UC_MACRO_NAME_1BC78 0x1BC78 // 𛱸 DUPLOYAN AFFIX ATTACHED TANGENT
#define UC_MACRO_NAME_1BC79 0x1BC79 // 𛱹 DUPLOYAN AFFIX ATTACHED TAIL
#define UC_MACRO_NAME_1BC7A 0x1BC7A // 𛱺 DUPLOYAN AFFIX ATTACHED E HOOK
#define UC_MACRO_NAME_1BC7B 0x1BC7B // 𛱻 DUPLOYAN AFFIX ATTACHED I HOOK
#define UC_MACRO_NAME_1BC7C 0x1BC7C // 𛱼 DUPLOYAN AFFIX ATTACHED TANGENT HOOK
#define UC_MACRO_NAME_1BC80 0x1BC80 // 𛲀 DUPLOYAN AFFIX HIGH ACUTE
#define UC_MACRO_NAME_1BC81 0x1BC81 // 𛲁 DUPLOYAN AFFIX HIGH TIGHT ACUTE
#define UC_MACRO_NAME_1BC82 0x1BC82 // 𛲂 DUPLOYAN AFFIX HIGH GRAVE
#define UC_MACRO_NAME_1BC83 0x1BC83 // 𛲃 DUPLOYAN AFFIX HIGH LONG GRAVE
#define UC_MACRO_NAME_1BC84 0x1BC84 // 𛲄 DUPLOYAN AFFIX HIGH DOT
#define UC_MACRO_NAME_1BC85 0x1BC85 // 𛲅 DUPLOYAN AFFIX HIGH CIRCLE
#define UC_MACRO_NAME_1BC86 0x1BC86 // 𛲆 DUPLOYAN AFFIX HIGH LINE
#define UC_MACRO_NAME_1BC87 0x1BC87 // 𛲇 DUPLOYAN AFFIX HIGH WAVE
#define UC_MACRO_NAME_1BC88 0x1BC88 // 𛲈 DUPLOYAN AFFIX HIGH VERTICAL
#define UC_MACRO_NAME_1BC90 0x1BC90 // 𛲐 DUPLOYAN AFFIX LOW ACUTE
#define UC_MACRO_NAME_1BC91 0x1BC91 // 𛲑 DUPLOYAN AFFIX LOW TIGHT ACUTE
#define UC_MACRO_NAME_1BC92 0x1BC92 // 𛲒 DUPLOYAN AFFIX LOW GRAVE
#define UC_MACRO_NAME_1BC93 0x1BC93 // 𛲓 DUPLOYAN AFFIX LOW LONG GRAVE
#define UC_MACRO_NAME_1BC94 0x1BC94 // 𛲔 DUPLOYAN AFFIX LOW DOT
#define UC_MACRO_NAME_1BC95 0x1BC95 // 𛲕 DUPLOYAN AFFIX LOW CIRCLE
#define UC_MACRO_NAME_1BC96 0x1BC96 // 𛲖 DUPLOYAN AFFIX LOW LINE
#define UC_MACRO_NAME_1BC97 0x1BC97 // 𛲗 DUPLOYAN AFFIX LOW WAVE
#define UC_MACRO_NAME_1BC98 0x1BC98 // 𛲘 DUPLOYAN AFFIX LOW VERTICAL
#define UC_MACRO_NAME_1BC99 0x1BC99 // 𛲙 DUPLOYAN AFFIX LOW ARROW
#define UC_MACRO_NAME_1BC9C 0x1BC9C // 𛲜 DUPLOYAN SIGN O WITH CROSS
#define UC_MACRO_NAME_1BC9D 0x1BC9D // 𛲝 DUPLOYAN THICK LETTER SELECTOR
#define UC_MACRO_NAME_1BC9E 0x1BC9E // 𛲞 DUPLOYAN DOUBLE MARK
#define UC_MACRO_NAME_1BC9F 0x1BC9F // 𛲟 DUPLOYAN PUNCTUATION CHINOOK FULL STOP


#endif // UC_H_DUPLOYAN
