/*
 * Unicode Block: Devanagari Extended
 * Range: U+A8E0..U+A8FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Devanagari Extended is a Unicode block containing cantillation marks
 * for writing the Samaveda, and nasalization marks for the Devanagari
 * script.
 *
 */
#ifndef UC_H_DEVANAGARI_EXTENDED
#define UC_H_DEVANAGARI_EXTENDED

#define UC_MACRO_NAME_A8E0 0xA8E0 // ꣠ COMBINING DEVANAGARI DIGIT ZERO
#define UC_MACRO_NAME_A8E1 0xA8E1 // ꣡ COMBINING DEVANAGARI DIGIT ONE
#define UC_MACRO_NAME_A8E2 0xA8E2 // ꣢ COMBINING DEVANAGARI DIGIT TWO
#define UC_MACRO_NAME_A8E3 0xA8E3 // ꣣ COMBINING DEVANAGARI DIGIT THREE
#define UC_MACRO_NAME_A8E4 0xA8E4 // ꣤ COMBINING DEVANAGARI DIGIT FOUR
#define UC_MACRO_NAME_A8E5 0xA8E5 // ꣥ COMBINING DEVANAGARI DIGIT FIVE
#define UC_MACRO_NAME_A8E6 0xA8E6 // ꣦ COMBINING DEVANAGARI DIGIT SIX
#define UC_MACRO_NAME_A8E7 0xA8E7 // ꣧ COMBINING DEVANAGARI DIGIT SEVEN
#define UC_MACRO_NAME_A8E8 0xA8E8 // ꣨ COMBINING DEVANAGARI DIGIT EIGHT
#define UC_MACRO_NAME_A8E9 0xA8E9 // ꣩ COMBINING DEVANAGARI DIGIT NINE
#define UC_MACRO_NAME_A8EA 0xA8EA // ꣪ COMBINING DEVANAGARI LETTER A
#define UC_MACRO_NAME_A8EB 0xA8EB // ꣫ COMBINING DEVANAGARI LETTER U
#define UC_MACRO_NAME_A8EC 0xA8EC // ꣬ COMBINING DEVANAGARI LETTER KA
#define UC_MACRO_NAME_A8ED 0xA8ED // ꣭ COMBINING DEVANAGARI LETTER NA
#define UC_MACRO_NAME_A8EE 0xA8EE // ꣮ COMBINING DEVANAGARI LETTER PA
#define UC_MACRO_NAME_A8EF 0xA8EF // ꣯ COMBINING DEVANAGARI LETTER RA
#define UC_MACRO_NAME_A8F0 0xA8F0 // ꣰ COMBINING DEVANAGARI LETTER VI
#define UC_MACRO_NAME_A8F1 0xA8F1 // ꣱ COMBINING DEVANAGARI SIGN AVAGRAHA
#define UC_MACRO_NAME_A8F2 0xA8F2 // ꣲ DEVANAGARI SIGN SPACING CANDRABINDU
#define UC_MACRO_NAME_A8F3 0xA8F3 // ꣳ DEVANAGARI SIGN CANDRABINDU VIRAMA
#define UC_MACRO_NAME_A8F4 0xA8F4 // ꣴ DEVANAGARI SIGN DOUBLE CANDRABINDU VIRAMA
#define UC_MACRO_NAME_A8F5 0xA8F5 // ꣵ DEVANAGARI SIGN CANDRABINDU TWO
#define UC_MACRO_NAME_A8F6 0xA8F6 // ꣶ DEVANAGARI SIGN CANDRABINDU THREE
#define UC_MACRO_NAME_A8F7 0xA8F7 // ꣷ DEVANAGARI SIGN CANDRABINDU AVAGRAHA
#define UC_MACRO_NAME_A8F8 0xA8F8 // ꣸ DEVANAGARI SIGN PUSHPIKA
#define UC_MACRO_NAME_A8F9 0xA8F9 // ꣹ DEVANAGARI GAP FILLER
#define UC_MACRO_NAME_A8FA 0xA8FA // ꣺ DEVANAGARI CARET
#define UC_MACRO_NAME_A8FB 0xA8FB // ꣻ DEVANAGARI HEADSTROKE
#define UC_MACRO_NAME_A8FC 0xA8FC // ꣼ DEVANAGARI SIGN SIDDHAM
#define UC_MACRO_NAME_A8FD 0xA8FD // ꣽ DEVANAGARI JAIN OM
#define UC_MACRO_NAME_A8FE 0xA8FE // ꣾ DEVANAGARI LETTER AY
#define UC_MACRO_NAME_A8FF 0xA8FF // ꣿ DEVANAGARI VOWEL SIGN AY


#endif // UC_H_DEVANAGARI_EXTENDED
