/*
 * Unicode Block: Ethiopic Extended-A
 * Range: U+AB00..U+AB2F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_ETHIOPIC_EXTENDED_A
#define UC_H_ETHIOPIC_EXTENDED_A

#define UC_MACRO_NAME_AB01 0xAB01 // ꬁ ETHIOPIC SYLLABLE TTHU
#define UC_MACRO_NAME_AB02 0xAB02 // ꬂ ETHIOPIC SYLLABLE TTHI
#define UC_MACRO_NAME_AB03 0xAB03 // ꬃ ETHIOPIC SYLLABLE TTHAA
#define UC_MACRO_NAME_AB04 0xAB04 // ꬄ ETHIOPIC SYLLABLE TTHEE
#define UC_MACRO_NAME_AB05 0xAB05 // ꬅ ETHIOPIC SYLLABLE TTHE
#define UC_MACRO_NAME_AB06 0xAB06 // ꬆ ETHIOPIC SYLLABLE TTHO
#define UC_MACRO_NAME_AB09 0xAB09 // ꬉ ETHIOPIC SYLLABLE DDHU
#define UC_MACRO_NAME_AB0A 0xAB0A // ꬊ ETHIOPIC SYLLABLE DDHI
#define UC_MACRO_NAME_AB0B 0xAB0B // ꬋ ETHIOPIC SYLLABLE DDHAA
#define UC_MACRO_NAME_AB0C 0xAB0C // ꬌ ETHIOPIC SYLLABLE DDHEE
#define UC_MACRO_NAME_AB0D 0xAB0D // ꬍ ETHIOPIC SYLLABLE DDHE
#define UC_MACRO_NAME_AB0E 0xAB0E // ꬎ ETHIOPIC SYLLABLE DDHO
#define UC_MACRO_NAME_AB11 0xAB11 // ꬑ ETHIOPIC SYLLABLE DZU
#define UC_MACRO_NAME_AB12 0xAB12 // ꬒ ETHIOPIC SYLLABLE DZI
#define UC_MACRO_NAME_AB13 0xAB13 // ꬓ ETHIOPIC SYLLABLE DZAA
#define UC_MACRO_NAME_AB14 0xAB14 // ꬔ ETHIOPIC SYLLABLE DZEE
#define UC_MACRO_NAME_AB15 0xAB15 // ꬕ ETHIOPIC SYLLABLE DZE
#define UC_MACRO_NAME_AB16 0xAB16 // ꬖ ETHIOPIC SYLLABLE DZO
#define UC_MACRO_NAME_AB20 0xAB20 // ꬠ ETHIOPIC SYLLABLE CCHHA
#define UC_MACRO_NAME_AB21 0xAB21 // ꬡ ETHIOPIC SYLLABLE CCHHU
#define UC_MACRO_NAME_AB22 0xAB22 // ꬢ ETHIOPIC SYLLABLE CCHHI
#define UC_MACRO_NAME_AB23 0xAB23 // ꬣ ETHIOPIC SYLLABLE CCHHAA
#define UC_MACRO_NAME_AB24 0xAB24 // ꬤ ETHIOPIC SYLLABLE CCHHEE
#define UC_MACRO_NAME_AB25 0xAB25 // ꬥ ETHIOPIC SYLLABLE CCHHE
#define UC_MACRO_NAME_AB26 0xAB26 // ꬦ ETHIOPIC SYLLABLE CCHHO
#define UC_MACRO_NAME_AB28 0xAB28 // ꬨ ETHIOPIC SYLLABLE BBA
#define UC_MACRO_NAME_AB29 0xAB29 // ꬩ ETHIOPIC SYLLABLE BBU
#define UC_MACRO_NAME_AB2A 0xAB2A // ꬪ ETHIOPIC SYLLABLE BBI
#define UC_MACRO_NAME_AB2B 0xAB2B // ꬫ ETHIOPIC SYLLABLE BBAA
#define UC_MACRO_NAME_AB2C 0xAB2C // ꬬ ETHIOPIC SYLLABLE BBEE
#define UC_MACRO_NAME_AB2D 0xAB2D // ꬭ ETHIOPIC SYLLABLE BBE
#define UC_MACRO_NAME_AB2E 0xAB2E // ꬮ ETHIOPIC SYLLABLE BBO


#endif // UC_H_ETHIOPIC_EXTENDED_A
