/*
 * Unicode Block: Ethiopic Extended-B
 * Range: U+1E7E0..U+1E7FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_ETHIOPIC_EXTENDED_B
#define UC_H_ETHIOPIC_EXTENDED_B

#define UC_MACRO_NAME_1E7E0 0x1E7E0 // 𞟠 ETHIOPIC SYLLABLE HHYA
#define UC_MACRO_NAME_1E7E1 0x1E7E1 // 𞟡 ETHIOPIC SYLLABLE HHYU
#define UC_MACRO_NAME_1E7E2 0x1E7E2 // 𞟢 ETHIOPIC SYLLABLE HHYI
#define UC_MACRO_NAME_1E7E3 0x1E7E3 // 𞟣 ETHIOPIC SYLLABLE HHYAA
#define UC_MACRO_NAME_1E7E4 0x1E7E4 // 𞟤 ETHIOPIC SYLLABLE HHYEE
#define UC_MACRO_NAME_1E7E5 0x1E7E5 // 𞟥 ETHIOPIC SYLLABLE HHYE
#define UC_MACRO_NAME_1E7E6 0x1E7E6 // 𞟦 ETHIOPIC SYLLABLE HHYO
#define UC_MACRO_NAME_1E7E8 0x1E7E8 // 𞟨 ETHIOPIC SYLLABLE GURAGE HHWA
#define UC_MACRO_NAME_1E7E9 0x1E7E9 // 𞟩 ETHIOPIC SYLLABLE HHWI
#define UC_MACRO_NAME_1E7EA 0x1E7EA // 𞟪 ETHIOPIC SYLLABLE HHWEE
#define UC_MACRO_NAME_1E7EB 0x1E7EB // 𞟫 ETHIOPIC SYLLABLE HHWE
#define UC_MACRO_NAME_1E7ED 0x1E7ED // 𞟭 ETHIOPIC SYLLABLE GURAGE MWI
#define UC_MACRO_NAME_1E7EE 0x1E7EE // 𞟮 ETHIOPIC SYLLABLE GURAGE MWEE
#define UC_MACRO_NAME_1E7F0 0x1E7F0 // 𞟰 ETHIOPIC SYLLABLE GURAGE QWI
#define UC_MACRO_NAME_1E7F1 0x1E7F1 // 𞟱 ETHIOPIC SYLLABLE GURAGE QWEE
#define UC_MACRO_NAME_1E7F2 0x1E7F2 // 𞟲 ETHIOPIC SYLLABLE GURAGE QWE
#define UC_MACRO_NAME_1E7F3 0x1E7F3 // 𞟳 ETHIOPIC SYLLABLE GURAGE BWI
#define UC_MACRO_NAME_1E7F4 0x1E7F4 // 𞟴 ETHIOPIC SYLLABLE GURAGE BWEE
#define UC_MACRO_NAME_1E7F5 0x1E7F5 // 𞟵 ETHIOPIC SYLLABLE GURAGE KWI
#define UC_MACRO_NAME_1E7F6 0x1E7F6 // 𞟶 ETHIOPIC SYLLABLE GURAGE KWEE
#define UC_MACRO_NAME_1E7F7 0x1E7F7 // 𞟷 ETHIOPIC SYLLABLE GURAGE KWE
#define UC_MACRO_NAME_1E7F8 0x1E7F8 // 𞟸 ETHIOPIC SYLLABLE GURAGE GWI
#define UC_MACRO_NAME_1E7F9 0x1E7F9 // 𞟹 ETHIOPIC SYLLABLE GURAGE GWEE
#define UC_MACRO_NAME_1E7FA 0x1E7FA // 𞟺 ETHIOPIC SYLLABLE GURAGE GWE
#define UC_MACRO_NAME_1E7FB 0x1E7FB // 𞟻 ETHIOPIC SYLLABLE GURAGE FWI
#define UC_MACRO_NAME_1E7FC 0x1E7FC // 𞟼 ETHIOPIC SYLLABLE GURAGE FWEE
#define UC_MACRO_NAME_1E7FD 0x1E7FD // 𞟽 ETHIOPIC SYLLABLE GURAGE PWI
#define UC_MACRO_NAME_1E7FE 0x1E7FE // 𞟾 ETHIOPIC SYLLABLE GURAGE PWEE


#endif // UC_H_ETHIOPIC_EXTENDED_B
