/*
 * Unicode Block: Ethiopic Extended
 * Range: U+2D80..U+2DDF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Ethiopic Extended is a Unicode block containing Geʽez characters for
 * the Me'en , Blin , and Sebat Bet Gurage languages.
 * The following Unicode-related documents record the purpose and process
 * of defining specific characters in the Ethiopic Extended block:
 *
 */
#ifndef UC_H_ETHIOPIC_EXTENDED
#define UC_H_ETHIOPIC_EXTENDED

#define UC_MACRO_NAME_2D80 0x2D80 // ⶀ ETHIOPIC SYLLABLE LOA
#define UC_MACRO_NAME_2D81 0x2D81 // ⶁ ETHIOPIC SYLLABLE MOA
#define UC_MACRO_NAME_2D82 0x2D82 // ⶂ ETHIOPIC SYLLABLE ROA
#define UC_MACRO_NAME_2D83 0x2D83 // ⶃ ETHIOPIC SYLLABLE SOA
#define UC_MACRO_NAME_2D84 0x2D84 // ⶄ ETHIOPIC SYLLABLE SHOA
#define UC_MACRO_NAME_2D85 0x2D85 // ⶅ ETHIOPIC SYLLABLE BOA
#define UC_MACRO_NAME_2D86 0x2D86 // ⶆ ETHIOPIC SYLLABLE TOA
#define UC_MACRO_NAME_2D87 0x2D87 // ⶇ ETHIOPIC SYLLABLE COA
#define UC_MACRO_NAME_2D88 0x2D88 // ⶈ ETHIOPIC SYLLABLE NOA
#define UC_MACRO_NAME_2D89 0x2D89 // ⶉ ETHIOPIC SYLLABLE NYOA
#define UC_MACRO_NAME_2D8A 0x2D8A // ⶊ ETHIOPIC SYLLABLE GLOTTAL OA
#define UC_MACRO_NAME_2D8B 0x2D8B // ⶋ ETHIOPIC SYLLABLE ZOA
#define UC_MACRO_NAME_2D8C 0x2D8C // ⶌ ETHIOPIC SYLLABLE DOA
#define UC_MACRO_NAME_2D8D 0x2D8D // ⶍ ETHIOPIC SYLLABLE DDOA
#define UC_MACRO_NAME_2D8E 0x2D8E // ⶎ ETHIOPIC SYLLABLE JOA
#define UC_MACRO_NAME_2D8F 0x2D8F // ⶏ ETHIOPIC SYLLABLE THOA
#define UC_MACRO_NAME_2D90 0x2D90 // ⶐ ETHIOPIC SYLLABLE CHOA
#define UC_MACRO_NAME_2D91 0x2D91 // ⶑ ETHIOPIC SYLLABLE PHOA
#define UC_MACRO_NAME_2D92 0x2D92 // ⶒ ETHIOPIC SYLLABLE POA
#define UC_MACRO_NAME_2D93 0x2D93 // ⶓ ETHIOPIC SYLLABLE GGWA
#define UC_MACRO_NAME_2D94 0x2D94 // ⶔ ETHIOPIC SYLLABLE GGWI
#define UC_MACRO_NAME_2D95 0x2D95 // ⶕ ETHIOPIC SYLLABLE GGWEE
#define UC_MACRO_NAME_2D96 0x2D96 // ⶖ ETHIOPIC SYLLABLE GGWE
#define UC_MACRO_NAME_2DA0 0x2DA0 // ⶠ ETHIOPIC SYLLABLE SSA
#define UC_MACRO_NAME_2DA1 0x2DA1 // ⶡ ETHIOPIC SYLLABLE SSU
#define UC_MACRO_NAME_2DA2 0x2DA2 // ⶢ ETHIOPIC SYLLABLE SSI
#define UC_MACRO_NAME_2DA3 0x2DA3 // ⶣ ETHIOPIC SYLLABLE SSAA
#define UC_MACRO_NAME_2DA4 0x2DA4 // ⶤ ETHIOPIC SYLLABLE SSEE
#define UC_MACRO_NAME_2DA5 0x2DA5 // ⶥ ETHIOPIC SYLLABLE SSE
#define UC_MACRO_NAME_2DA6 0x2DA6 // ⶦ ETHIOPIC SYLLABLE SSO
#define UC_MACRO_NAME_2DA8 0x2DA8 // ⶨ ETHIOPIC SYLLABLE CCA
#define UC_MACRO_NAME_2DA9 0x2DA9 // ⶩ ETHIOPIC SYLLABLE CCU
#define UC_MACRO_NAME_2DAA 0x2DAA // ⶪ ETHIOPIC SYLLABLE CCI
#define UC_MACRO_NAME_2DAB 0x2DAB // ⶫ ETHIOPIC SYLLABLE CCAA
#define UC_MACRO_NAME_2DAC 0x2DAC // ⶬ ETHIOPIC SYLLABLE CCEE
#define UC_MACRO_NAME_2DAD 0x2DAD // ⶭ ETHIOPIC SYLLABLE CCE
#define UC_MACRO_NAME_2DAE 0x2DAE // ⶮ ETHIOPIC SYLLABLE CCO
#define UC_MACRO_NAME_2DB0 0x2DB0 // ⶰ ETHIOPIC SYLLABLE ZZA
#define UC_MACRO_NAME_2DB1 0x2DB1 // ⶱ ETHIOPIC SYLLABLE ZZU
#define UC_MACRO_NAME_2DB2 0x2DB2 // ⶲ ETHIOPIC SYLLABLE ZZI
#define UC_MACRO_NAME_2DB3 0x2DB3 // ⶳ ETHIOPIC SYLLABLE ZZAA
#define UC_MACRO_NAME_2DB4 0x2DB4 // ⶴ ETHIOPIC SYLLABLE ZZEE
#define UC_MACRO_NAME_2DB5 0x2DB5 // ⶵ ETHIOPIC SYLLABLE ZZE
#define UC_MACRO_NAME_2DB6 0x2DB6 // ⶶ ETHIOPIC SYLLABLE ZZO
#define UC_MACRO_NAME_2DB8 0x2DB8 // ⶸ ETHIOPIC SYLLABLE CCHA
#define UC_MACRO_NAME_2DB9 0x2DB9 // ⶹ ETHIOPIC SYLLABLE CCHU
#define UC_MACRO_NAME_2DBA 0x2DBA // ⶺ ETHIOPIC SYLLABLE CCHI
#define UC_MACRO_NAME_2DBB 0x2DBB // ⶻ ETHIOPIC SYLLABLE CCHAA
#define UC_MACRO_NAME_2DBC 0x2DBC // ⶼ ETHIOPIC SYLLABLE CCHEE
#define UC_MACRO_NAME_2DBD 0x2DBD // ⶽ ETHIOPIC SYLLABLE CCHE
#define UC_MACRO_NAME_2DBE 0x2DBE // ⶾ ETHIOPIC SYLLABLE CCHO
#define UC_MACRO_NAME_2DC0 0x2DC0 // ⷀ ETHIOPIC SYLLABLE QYA
#define UC_MACRO_NAME_2DC1 0x2DC1 // ⷁ ETHIOPIC SYLLABLE QYU
#define UC_MACRO_NAME_2DC2 0x2DC2 // ⷂ ETHIOPIC SYLLABLE QYI
#define UC_MACRO_NAME_2DC3 0x2DC3 // ⷃ ETHIOPIC SYLLABLE QYAA
#define UC_MACRO_NAME_2DC4 0x2DC4 // ⷄ ETHIOPIC SYLLABLE QYEE
#define UC_MACRO_NAME_2DC5 0x2DC5 // ⷅ ETHIOPIC SYLLABLE QYE
#define UC_MACRO_NAME_2DC6 0x2DC6 // ⷆ ETHIOPIC SYLLABLE QYO
#define UC_MACRO_NAME_2DC8 0x2DC8 // ⷈ ETHIOPIC SYLLABLE KYA
#define UC_MACRO_NAME_2DC9 0x2DC9 // ⷉ ETHIOPIC SYLLABLE KYU
#define UC_MACRO_NAME_2DCA 0x2DCA // ⷊ ETHIOPIC SYLLABLE KYI
#define UC_MACRO_NAME_2DCB 0x2DCB // ⷋ ETHIOPIC SYLLABLE KYAA
#define UC_MACRO_NAME_2DCC 0x2DCC // ⷌ ETHIOPIC SYLLABLE KYEE
#define UC_MACRO_NAME_2DCD 0x2DCD // ⷍ ETHIOPIC SYLLABLE KYE
#define UC_MACRO_NAME_2DCE 0x2DCE // ⷎ ETHIOPIC SYLLABLE KYO
#define UC_MACRO_NAME_2DD0 0x2DD0 // ⷐ ETHIOPIC SYLLABLE XYA
#define UC_MACRO_NAME_2DD1 0x2DD1 // ⷑ ETHIOPIC SYLLABLE XYU
#define UC_MACRO_NAME_2DD2 0x2DD2 // ⷒ ETHIOPIC SYLLABLE XYI
#define UC_MACRO_NAME_2DD3 0x2DD3 // ⷓ ETHIOPIC SYLLABLE XYAA
#define UC_MACRO_NAME_2DD4 0x2DD4 // ⷔ ETHIOPIC SYLLABLE XYEE
#define UC_MACRO_NAME_2DD5 0x2DD5 // ⷕ ETHIOPIC SYLLABLE XYE
#define UC_MACRO_NAME_2DD6 0x2DD6 // ⷖ ETHIOPIC SYLLABLE XYO
#define UC_MACRO_NAME_2DD8 0x2DD8 // ⷘ ETHIOPIC SYLLABLE GYA
#define UC_MACRO_NAME_2DD9 0x2DD9 // ⷙ ETHIOPIC SYLLABLE GYU
#define UC_MACRO_NAME_2DDA 0x2DDA // ⷚ ETHIOPIC SYLLABLE GYI
#define UC_MACRO_NAME_2DDB 0x2DDB // ⷛ ETHIOPIC SYLLABLE GYAA
#define UC_MACRO_NAME_2DDC 0x2DDC // ⷜ ETHIOPIC SYLLABLE GYEE
#define UC_MACRO_NAME_2DDD 0x2DDD // ⷝ ETHIOPIC SYLLABLE GYE
#define UC_MACRO_NAME_2DDE 0x2DDE // ⷞ ETHIOPIC SYLLABLE GYO


#endif // UC_H_ETHIOPIC_EXTENDED
