/*
 * Unicode Block: Georgian
 * Range: U+10A0..U+10FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Georgian may refer to:
 *
 */
#ifndef UC_H_GEORGIAN
#define UC_H_GEORGIAN

#define UC_MACRO_NAME_10A0 0x10A0 // Ⴀ GEORGIAN CAPITAL LETTER AN
#define UC_MACRO_NAME_10A1 0x10A1 // Ⴁ GEORGIAN CAPITAL LETTER BAN
#define UC_MACRO_NAME_10A2 0x10A2 // Ⴂ GEORGIAN CAPITAL LETTER GAN
#define UC_MACRO_NAME_10A3 0x10A3 // Ⴃ GEORGIAN CAPITAL LETTER DON
#define UC_MACRO_NAME_10A4 0x10A4 // Ⴄ GEORGIAN CAPITAL LETTER EN
#define UC_MACRO_NAME_10A5 0x10A5 // Ⴅ GEORGIAN CAPITAL LETTER VIN
#define UC_MACRO_NAME_10A6 0x10A6 // Ⴆ GEORGIAN CAPITAL LETTER ZEN
#define UC_MACRO_NAME_10A7 0x10A7 // Ⴇ GEORGIAN CAPITAL LETTER TAN
#define UC_MACRO_NAME_10A8 0x10A8 // Ⴈ GEORGIAN CAPITAL LETTER IN
#define UC_MACRO_NAME_10A9 0x10A9 // Ⴉ GEORGIAN CAPITAL LETTER KAN
#define UC_MACRO_NAME_10AA 0x10AA // Ⴊ GEORGIAN CAPITAL LETTER LAS
#define UC_MACRO_NAME_10AB 0x10AB // Ⴋ GEORGIAN CAPITAL LETTER MAN
#define UC_MACRO_NAME_10AC 0x10AC // Ⴌ GEORGIAN CAPITAL LETTER NAR
#define UC_MACRO_NAME_10AD 0x10AD // Ⴍ GEORGIAN CAPITAL LETTER ON
#define UC_MACRO_NAME_10AE 0x10AE // Ⴎ GEORGIAN CAPITAL LETTER PAR
#define UC_MACRO_NAME_10AF 0x10AF // Ⴏ GEORGIAN CAPITAL LETTER ZHAR
#define UC_MACRO_NAME_10B0 0x10B0 // Ⴐ GEORGIAN CAPITAL LETTER RAE
#define UC_MACRO_NAME_10B1 0x10B1 // Ⴑ GEORGIAN CAPITAL LETTER SAN
#define UC_MACRO_NAME_10B2 0x10B2 // Ⴒ GEORGIAN CAPITAL LETTER TAR
#define UC_MACRO_NAME_10B3 0x10B3 // Ⴓ GEORGIAN CAPITAL LETTER UN
#define UC_MACRO_NAME_10B4 0x10B4 // Ⴔ GEORGIAN CAPITAL LETTER PHAR
#define UC_MACRO_NAME_10B5 0x10B5 // Ⴕ GEORGIAN CAPITAL LETTER KHAR
#define UC_MACRO_NAME_10B6 0x10B6 // Ⴖ GEORGIAN CAPITAL LETTER GHAN
#define UC_MACRO_NAME_10B7 0x10B7 // Ⴗ GEORGIAN CAPITAL LETTER QAR
#define UC_MACRO_NAME_10B8 0x10B8 // Ⴘ GEORGIAN CAPITAL LETTER SHIN
#define UC_MACRO_NAME_10B9 0x10B9 // Ⴙ GEORGIAN CAPITAL LETTER CHIN
#define UC_MACRO_NAME_10BA 0x10BA // Ⴚ GEORGIAN CAPITAL LETTER CAN
#define UC_MACRO_NAME_10BB 0x10BB // Ⴛ GEORGIAN CAPITAL LETTER JIL
#define UC_MACRO_NAME_10BC 0x10BC // Ⴜ GEORGIAN CAPITAL LETTER CIL
#define UC_MACRO_NAME_10BD 0x10BD // Ⴝ GEORGIAN CAPITAL LETTER CHAR
#define UC_MACRO_NAME_10BE 0x10BE // Ⴞ GEORGIAN CAPITAL LETTER XAN
#define UC_MACRO_NAME_10BF 0x10BF // Ⴟ GEORGIAN CAPITAL LETTER JHAN
#define UC_MACRO_NAME_10C0 0x10C0 // Ⴠ GEORGIAN CAPITAL LETTER HAE
#define UC_MACRO_NAME_10C1 0x10C1 // Ⴡ GEORGIAN CAPITAL LETTER HE
#define UC_MACRO_NAME_10C2 0x10C2 // Ⴢ GEORGIAN CAPITAL LETTER HIE
#define UC_MACRO_NAME_10C3 0x10C3 // Ⴣ GEORGIAN CAPITAL LETTER WE
#define UC_MACRO_NAME_10C4 0x10C4 // Ⴤ GEORGIAN CAPITAL LETTER HAR
#define UC_MACRO_NAME_10C5 0x10C5 // Ⴥ GEORGIAN CAPITAL LETTER HOE
#define UC_MACRO_NAME_10C7 0x10C7 // Ⴧ GEORGIAN CAPITAL LETTER YN
#define UC_MACRO_NAME_10CD 0x10CD // Ⴭ GEORGIAN CAPITAL LETTER AEN
#define UC_MACRO_NAME_10D0 0x10D0 // ა GEORGIAN LETTER AN
#define UC_MACRO_NAME_10D1 0x10D1 // ბ GEORGIAN LETTER BAN
#define UC_MACRO_NAME_10D2 0x10D2 // გ GEORGIAN LETTER GAN
#define UC_MACRO_NAME_10D3 0x10D3 // დ GEORGIAN LETTER DON
#define UC_MACRO_NAME_10D4 0x10D4 // ე GEORGIAN LETTER EN
#define UC_MACRO_NAME_10D5 0x10D5 // ვ GEORGIAN LETTER VIN
#define UC_MACRO_NAME_10D6 0x10D6 // ზ GEORGIAN LETTER ZEN
#define UC_MACRO_NAME_10D7 0x10D7 // თ GEORGIAN LETTER TAN
#define UC_MACRO_NAME_10D8 0x10D8 // ი GEORGIAN LETTER IN
#define UC_MACRO_NAME_10D9 0x10D9 // კ GEORGIAN LETTER KAN
#define UC_MACRO_NAME_10DA 0x10DA // ლ GEORGIAN LETTER LAS
#define UC_MACRO_NAME_10DB 0x10DB // მ GEORGIAN LETTER MAN
#define UC_MACRO_NAME_10DC 0x10DC // ნ GEORGIAN LETTER NAR
#define UC_MACRO_NAME_10DD 0x10DD // ო GEORGIAN LETTER ON
#define UC_MACRO_NAME_10DE 0x10DE // პ GEORGIAN LETTER PAR
#define UC_MACRO_NAME_10DF 0x10DF // ჟ GEORGIAN LETTER ZHAR
#define UC_MACRO_NAME_10E0 0x10E0 // რ GEORGIAN LETTER RAE
#define UC_MACRO_NAME_10E1 0x10E1 // ს GEORGIAN LETTER SAN
#define UC_MACRO_NAME_10E2 0x10E2 // ტ GEORGIAN LETTER TAR
#define UC_MACRO_NAME_10E3 0x10E3 // უ GEORGIAN LETTER UN
#define UC_MACRO_NAME_10E4 0x10E4 // ფ GEORGIAN LETTER PHAR
#define UC_MACRO_NAME_10E5 0x10E5 // ქ GEORGIAN LETTER KHAR
#define UC_MACRO_NAME_10E6 0x10E6 // ღ GEORGIAN LETTER GHAN
#define UC_MACRO_NAME_10E7 0x10E7 // ყ GEORGIAN LETTER QAR
#define UC_MACRO_NAME_10E8 0x10E8 // შ GEORGIAN LETTER SHIN
#define UC_MACRO_NAME_10E9 0x10E9 // ჩ GEORGIAN LETTER CHIN
#define UC_MACRO_NAME_10EA 0x10EA // ც GEORGIAN LETTER CAN
#define UC_MACRO_NAME_10EB 0x10EB // ძ GEORGIAN LETTER JIL
#define UC_MACRO_NAME_10EC 0x10EC // წ GEORGIAN LETTER CIL
#define UC_MACRO_NAME_10ED 0x10ED // ჭ GEORGIAN LETTER CHAR
#define UC_MACRO_NAME_10EE 0x10EE // ხ GEORGIAN LETTER XAN
#define UC_MACRO_NAME_10EF 0x10EF // ჯ GEORGIAN LETTER JHAN
#define UC_MACRO_NAME_10F0 0x10F0 // ჰ GEORGIAN LETTER HAE
#define UC_MACRO_NAME_10F1 0x10F1 // ჱ GEORGIAN LETTER HE
#define UC_MACRO_NAME_10F2 0x10F2 // ჲ GEORGIAN LETTER HIE
#define UC_MACRO_NAME_10F3 0x10F3 // ჳ GEORGIAN LETTER WE
#define UC_MACRO_NAME_10F4 0x10F4 // ჴ GEORGIAN LETTER HAR
#define UC_MACRO_NAME_10F5 0x10F5 // ჵ GEORGIAN LETTER HOE
#define UC_MACRO_NAME_10F6 0x10F6 // ჶ GEORGIAN LETTER FI
#define UC_MACRO_NAME_10F7 0x10F7 // ჷ GEORGIAN LETTER YN
#define UC_MACRO_NAME_10F8 0x10F8 // ჸ GEORGIAN LETTER ELIFI
#define UC_MACRO_NAME_10F9 0x10F9 // ჹ GEORGIAN LETTER TURNED GAN
#define UC_MACRO_NAME_10FA 0x10FA // ჺ GEORGIAN LETTER AIN
#define UC_MACRO_NAME_10FB 0x10FB // ჻ GEORGIAN PARAGRAPH SEPARATOR
#define UC_MACRO_NAME_10FC 0x10FC // ჼ MODIFIER LETTER GEORGIAN NAR
#define UC_MACRO_NAME_10FD 0x10FD // ჽ GEORGIAN LETTER AEN
#define UC_MACRO_NAME_10FE 0x10FE // ჾ GEORGIAN LETTER HARD SIGN
#define UC_MACRO_NAME_10FF 0x10FF // ჿ GEORGIAN LETTER LABIAL SIGN


#endif // UC_H_GEORGIAN
