/*
 * Unicode Block: Geometric Shapes Extended
 * Range: U+1F780..U+1F7FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Geometric Shapes Extended is a Unicode block containing Webdings /
 * Wingdings symbols, mostly different weights of squares , crosses , and
 * saltires , and different weights of variously spoked asterisks , stars
 * , and various color squares and circles for emoji.
 * The Geometric Shapes Extended block contains thirteen emoji :
 * U+1F7E0–U+1F7EB and U+1F7F0.
 *
 */
#ifndef UC_H_GEOMETRIC_SHAPES_EXTENDED
#define UC_H_GEOMETRIC_SHAPES_EXTENDED

#define UC_MACRO_NAME_1F780 0x1F780 // 🞀 BLACK LEFT-POINTING ISOSCELES RIGHT TRIANGLE
#define UC_MACRO_NAME_1F781 0x1F781 // 🞁 BLACK UP-POINTING ISOSCELES RIGHT TRIANGLE
#define UC_MACRO_NAME_1F782 0x1F782 // 🞂 BLACK RIGHT-POINTING ISOSCELES RIGHT TRIANGLE
#define UC_MACRO_NAME_1F783 0x1F783 // 🞃 BLACK DOWN-POINTING ISOSCELES RIGHT TRIANGLE
#define UC_MACRO_NAME_1F784 0x1F784 // 🞄 BLACK SLIGHTLY SMALL CIRCLE
#define UC_MACRO_NAME_1F785 0x1F785 // 🞅 MEDIUM BOLD WHITE CIRCLE
#define UC_MACRO_NAME_1F786 0x1F786 // 🞆 BOLD WHITE CIRCLE
#define UC_MACRO_NAME_1F787 0x1F787 // 🞇 HEAVY WHITE CIRCLE
#define UC_MACRO_NAME_1F788 0x1F788 // 🞈 VERY HEAVY WHITE CIRCLE
#define UC_MACRO_NAME_1F789 0x1F789 // 🞉 EXTREMELY HEAVY WHITE CIRCLE
#define UC_MACRO_NAME_1F78A 0x1F78A // 🞊 WHITE CIRCLE CONTAINING BLACK SMALL CIRCLE
#define UC_MACRO_NAME_1F78B 0x1F78B // 🞋 ROUND TARGET
#define UC_MACRO_NAME_1F78C 0x1F78C // 🞌 BLACK TINY SQUARE
#define UC_MACRO_NAME_1F78D 0x1F78D // 🞍 BLACK SLIGHTLY SMALL SQUARE
#define UC_MACRO_NAME_1F78E 0x1F78E // 🞎 LIGHT WHITE SQUARE
#define UC_MACRO_NAME_1F78F 0x1F78F // 🞏 MEDIUM WHITE SQUARE
#define UC_MACRO_NAME_1F790 0x1F790 // 🞐 BOLD WHITE SQUARE
#define UC_MACRO_NAME_1F791 0x1F791 // 🞑 HEAVY WHITE SQUARE
#define UC_MACRO_NAME_1F792 0x1F792 // 🞒 VERY HEAVY WHITE SQUARE
#define UC_MACRO_NAME_1F793 0x1F793 // 🞓 EXTREMELY HEAVY WHITE SQUARE
#define UC_MACRO_NAME_1F794 0x1F794 // 🞔 WHITE SQUARE CONTAINING BLACK VERY SMALL SQUARE
#define UC_MACRO_NAME_1F795 0x1F795 // 🞕 WHITE SQUARE CONTAINING BLACK MEDIUM SQUARE
#define UC_MACRO_NAME_1F796 0x1F796 // 🞖 SQUARE TARGET
#define UC_MACRO_NAME_1F797 0x1F797 // 🞗 BLACK TINY DIAMOND
#define UC_MACRO_NAME_1F798 0x1F798 // 🞘 BLACK VERY SMALL DIAMOND
#define UC_MACRO_NAME_1F799 0x1F799 // 🞙 BLACK MEDIUM SMALL DIAMOND
#define UC_MACRO_NAME_1F79A 0x1F79A // 🞚 WHITE DIAMOND CONTAINING BLACK VERY SMALL DIAMOND
#define UC_MACRO_NAME_1F79B 0x1F79B // 🞛 WHITE DIAMOND CONTAINING BLACK MEDIUM DIAMOND
#define UC_MACRO_NAME_1F79C 0x1F79C // 🞜 DIAMOND TARGET
#define UC_MACRO_NAME_1F79D 0x1F79D // 🞝 BLACK TINY LOZENGE
#define UC_MACRO_NAME_1F79E 0x1F79E // 🞞 BLACK VERY SMALL LOZENGE
#define UC_MACRO_NAME_1F79F 0x1F79F // 🞟 BLACK MEDIUM SMALL LOZENGE
#define UC_MACRO_NAME_1F7A0 0x1F7A0 // 🞠 WHITE LOZENGE CONTAINING BLACK SMALL LOZENGE
#define UC_MACRO_NAME_1F7A1 0x1F7A1 // 🞡 THIN GREEK CROSS
#define UC_MACRO_NAME_1F7A2 0x1F7A2 // 🞢 LIGHT GREEK CROSS
#define UC_MACRO_NAME_1F7A3 0x1F7A3 // 🞣 MEDIUM GREEK CROSS
#define UC_MACRO_NAME_1F7A4 0x1F7A4 // 🞤 BOLD GREEK CROSS
#define UC_MACRO_NAME_1F7A5 0x1F7A5 // 🞥 VERY BOLD GREEK CROSS
#define UC_MACRO_NAME_1F7A6 0x1F7A6 // 🞦 VERY HEAVY GREEK CROSS
#define UC_MACRO_NAME_1F7A7 0x1F7A7 // 🞧 EXTREMELY HEAVY GREEK CROSS
#define UC_MACRO_NAME_1F7A8 0x1F7A8 // 🞨 THIN SALTIRE
#define UC_MACRO_NAME_1F7A9 0x1F7A9 // 🞩 LIGHT SALTIRE
#define UC_MACRO_NAME_1F7AA 0x1F7AA // 🞪 MEDIUM SALTIRE
#define UC_MACRO_NAME_1F7AB 0x1F7AB // 🞫 BOLD SALTIRE
#define UC_MACRO_NAME_1F7AC 0x1F7AC // 🞬 HEAVY SALTIRE
#define UC_MACRO_NAME_1F7AD 0x1F7AD // 🞭 VERY HEAVY SALTIRE
#define UC_MACRO_NAME_1F7AE 0x1F7AE // 🞮 EXTREMELY HEAVY SALTIRE
#define UC_MACRO_NAME_1F7AF 0x1F7AF // 🞯 LIGHT FIVE SPOKED ASTERISK
#define UC_MACRO_NAME_1F7B0 0x1F7B0 // 🞰 MEDIUM FIVE SPOKED ASTERISK
#define UC_MACRO_NAME_1F7B1 0x1F7B1 // 🞱 BOLD FIVE SPOKED ASTERISK
#define UC_MACRO_NAME_1F7B2 0x1F7B2 // 🞲 HEAVY FIVE SPOKED ASTERISK
#define UC_MACRO_NAME_1F7B3 0x1F7B3 // 🞳 VERY HEAVY FIVE SPOKED ASTERISK
#define UC_MACRO_NAME_1F7B4 0x1F7B4 // 🞴 EXTREMELY HEAVY FIVE SPOKED ASTERISK
#define UC_MACRO_NAME_1F7B5 0x1F7B5 // 🞵 LIGHT SIX SPOKED ASTERISK
#define UC_MACRO_NAME_1F7B6 0x1F7B6 // 🞶 MEDIUM SIX SPOKED ASTERISK
#define UC_MACRO_NAME_1F7B7 0x1F7B7 // 🞷 BOLD SIX SPOKED ASTERISK
#define UC_MACRO_NAME_1F7B8 0x1F7B8 // 🞸 HEAVY SIX SPOKED ASTERISK
#define UC_MACRO_NAME_1F7B9 0x1F7B9 // 🞹 VERY HEAVY SIX SPOKED ASTERISK
#define UC_MACRO_NAME_1F7BA 0x1F7BA // 🞺 EXTREMELY HEAVY SIX SPOKED ASTERISK
#define UC_MACRO_NAME_1F7BB 0x1F7BB // 🞻 LIGHT EIGHT SPOKED ASTERISK
#define UC_MACRO_NAME_1F7BC 0x1F7BC // 🞼 MEDIUM EIGHT SPOKED ASTERISK
#define UC_MACRO_NAME_1F7BD 0x1F7BD // 🞽 BOLD EIGHT SPOKED ASTERISK
#define UC_MACRO_NAME_1F7BE 0x1F7BE // 🞾 HEAVY EIGHT SPOKED ASTERISK
#define UC_MACRO_NAME_1F7BF 0x1F7BF // 🞿 VERY HEAVY EIGHT SPOKED ASTERISK
#define UC_MACRO_NAME_1F7C0 0x1F7C0 // 🟀 LIGHT THREE POINTED BLACK STAR
#define UC_MACRO_NAME_1F7C1 0x1F7C1 // 🟁 MEDIUM THREE POINTED BLACK STAR
#define UC_MACRO_NAME_1F7C2 0x1F7C2 // 🟂 THREE POINTED BLACK STAR
#define UC_MACRO_NAME_1F7C3 0x1F7C3 // 🟃 MEDIUM THREE POINTED PINWHEEL STAR
#define UC_MACRO_NAME_1F7C4 0x1F7C4 // 🟄 LIGHT FOUR POINTED BLACK STAR
#define UC_MACRO_NAME_1F7C5 0x1F7C5 // 🟅 MEDIUM FOUR POINTED BLACK STAR
#define UC_MACRO_NAME_1F7C6 0x1F7C6 // 🟆 FOUR POINTED BLACK STAR
#define UC_MACRO_NAME_1F7C7 0x1F7C7 // 🟇 MEDIUM FOUR POINTED PINWHEEL STAR
#define UC_MACRO_NAME_1F7C8 0x1F7C8 // 🟈 REVERSE LIGHT FOUR POINTED PINWHEEL STAR
#define UC_MACRO_NAME_1F7C9 0x1F7C9 // 🟉 LIGHT FIVE POINTED BLACK STAR
#define UC_MACRO_NAME_1F7CA 0x1F7CA // 🟊 HEAVY FIVE POINTED BLACK STAR
#define UC_MACRO_NAME_1F7CB 0x1F7CB // 🟋 MEDIUM SIX POINTED BLACK STAR
#define UC_MACRO_NAME_1F7CC 0x1F7CC // 🟌 HEAVY SIX POINTED BLACK STAR
#define UC_MACRO_NAME_1F7CD 0x1F7CD // 🟍 SIX POINTED PINWHEEL STAR
#define UC_MACRO_NAME_1F7CE 0x1F7CE // 🟎 MEDIUM EIGHT POINTED BLACK STAR
#define UC_MACRO_NAME_1F7CF 0x1F7CF // 🟏 HEAVY EIGHT POINTED BLACK STAR
#define UC_MACRO_NAME_1F7D0 0x1F7D0 // 🟐 VERY HEAVY EIGHT POINTED BLACK STAR
#define UC_MACRO_NAME_1F7D1 0x1F7D1 // 🟑 HEAVY EIGHT POINTED PINWHEEL STAR
#define UC_MACRO_NAME_1F7D2 0x1F7D2 // 🟒 LIGHT TWELVE POINTED BLACK STAR
#define UC_MACRO_NAME_1F7D3 0x1F7D3 // 🟓 HEAVY TWELVE POINTED BLACK STAR
#define UC_MACRO_NAME_1F7D4 0x1F7D4 // 🟔 HEAVY TWELVE POINTED PINWHEEL STAR
#define UC_MACRO_NAME_1F7D5 0x1F7D5 // 🟕 CIRCLED TRIANGLE
#define UC_MACRO_NAME_1F7D6 0x1F7D6 // 🟖 NEGATIVE CIRCLED TRIANGLE
#define UC_MACRO_NAME_1F7D7 0x1F7D7 // 🟗 CIRCLED SQUARE
#define UC_MACRO_NAME_1F7D8 0x1F7D8 // 🟘 NEGATIVE CIRCLED SQUARE
#define UC_MACRO_NAME_1F7D9 0x1F7D9 // 🟙 NINE POINTED WHITE STAR
#define UC_MACRO_NAME_1F7E0 0x1F7E0 // 🟠 LARGE ORANGE CIRCLE
#define UC_MACRO_NAME_1F7E1 0x1F7E1 // 🟡 LARGE YELLOW CIRCLE
#define UC_MACRO_NAME_1F7E2 0x1F7E2 // 🟢 LARGE GREEN CIRCLE
#define UC_MACRO_NAME_1F7E3 0x1F7E3 // 🟣 LARGE PURPLE CIRCLE
#define UC_MACRO_NAME_1F7E4 0x1F7E4 // 🟤 LARGE BROWN CIRCLE
#define UC_MACRO_NAME_1F7E5 0x1F7E5 // 🟥 LARGE RED SQUARE
#define UC_MACRO_NAME_1F7E6 0x1F7E6 // 🟦 LARGE BLUE SQUARE
#define UC_MACRO_NAME_1F7E7 0x1F7E7 // 🟧 LARGE ORANGE SQUARE
#define UC_MACRO_NAME_1F7E8 0x1F7E8 // 🟨 LARGE YELLOW SQUARE
#define UC_MACRO_NAME_1F7E9 0x1F7E9 // 🟩 LARGE GREEN SQUARE
#define UC_MACRO_NAME_1F7EA 0x1F7EA // 🟪 LARGE PURPLE SQUARE
#define UC_MACRO_NAME_1F7EB 0x1F7EB // 🟫 LARGE BROWN SQUARE
#define UC_MACRO_NAME_1F7F0 0x1F7F0 // 🟰 HEAVY EQUALS SIGN


#endif // UC_H_GEOMETRIC_SHAPES_EXTENDED
