/*
 * Unicode Block: Glagolitic Supplement
 * Range: U+1E000..U+1E02F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Glagolitic Supplement is a Unicode block containing supplementary
 * characters used in the Glagolitic script . It currently contains 38
 * combining letters.
 * The following Unicode-related documents record the purpose and process
 * of defining specific characters in the Glagolitic Supplement block:
 *
 */
#ifndef UC_H_GLAGOLITIC_SUPPLEMENT
#define UC_H_GLAGOLITIC_SUPPLEMENT

#define UC_MACRO_NAME_1E000 0x1E000 // 𞀀 COMBINING GLAGOLITIC LETTER AZU
#define UC_MACRO_NAME_1E001 0x1E001 // 𞀁 COMBINING GLAGOLITIC LETTER BUKY
#define UC_MACRO_NAME_1E002 0x1E002 // 𞀂 COMBINING GLAGOLITIC LETTER VEDE
#define UC_MACRO_NAME_1E003 0x1E003 // 𞀃 COMBINING GLAGOLITIC LETTER GLAGOLI
#define UC_MACRO_NAME_1E004 0x1E004 // 𞀄 COMBINING GLAGOLITIC LETTER DOBRO
#define UC_MACRO_NAME_1E005 0x1E005 // 𞀅 COMBINING GLAGOLITIC LETTER YESTU
#define UC_MACRO_NAME_1E006 0x1E006 // 𞀆 COMBINING GLAGOLITIC LETTER ZHIVETE
#define UC_MACRO_NAME_1E008 0x1E008 // 𞀈 COMBINING GLAGOLITIC LETTER ZEMLJA
#define UC_MACRO_NAME_1E009 0x1E009 // 𞀉 COMBINING GLAGOLITIC LETTER IZHE
#define UC_MACRO_NAME_1E00A 0x1E00A // 𞀊 COMBINING GLAGOLITIC LETTER INITIAL IZHE
#define UC_MACRO_NAME_1E00B 0x1E00B // 𞀋 COMBINING GLAGOLITIC LETTER I
#define UC_MACRO_NAME_1E00C 0x1E00C // 𞀌 COMBINING GLAGOLITIC LETTER DJERVI
#define UC_MACRO_NAME_1E00D 0x1E00D // 𞀍 COMBINING GLAGOLITIC LETTER KAKO
#define UC_MACRO_NAME_1E00E 0x1E00E // 𞀎 COMBINING GLAGOLITIC LETTER LJUDIJE
#define UC_MACRO_NAME_1E00F 0x1E00F // 𞀏 COMBINING GLAGOLITIC LETTER MYSLITE
#define UC_MACRO_NAME_1E010 0x1E010 // 𞀐 COMBINING GLAGOLITIC LETTER NASHI
#define UC_MACRO_NAME_1E011 0x1E011 // 𞀑 COMBINING GLAGOLITIC LETTER ONU
#define UC_MACRO_NAME_1E012 0x1E012 // 𞀒 COMBINING GLAGOLITIC LETTER POKOJI
#define UC_MACRO_NAME_1E013 0x1E013 // 𞀓 COMBINING GLAGOLITIC LETTER RITSI
#define UC_MACRO_NAME_1E014 0x1E014 // 𞀔 COMBINING GLAGOLITIC LETTER SLOVO
#define UC_MACRO_NAME_1E015 0x1E015 // 𞀕 COMBINING GLAGOLITIC LETTER TVRIDO
#define UC_MACRO_NAME_1E016 0x1E016 // 𞀖 COMBINING GLAGOLITIC LETTER UKU
#define UC_MACRO_NAME_1E017 0x1E017 // 𞀗 COMBINING GLAGOLITIC LETTER FRITU
#define UC_MACRO_NAME_1E018 0x1E018 // 𞀘 COMBINING GLAGOLITIC LETTER HERU
#define UC_MACRO_NAME_1E01B 0x1E01B // 𞀛 COMBINING GLAGOLITIC LETTER SHTA
#define UC_MACRO_NAME_1E01C 0x1E01C // 𞀜 COMBINING GLAGOLITIC LETTER TSI
#define UC_MACRO_NAME_1E01D 0x1E01D // 𞀝 COMBINING GLAGOLITIC LETTER CHRIVI
#define UC_MACRO_NAME_1E01E 0x1E01E // 𞀞 COMBINING GLAGOLITIC LETTER SHA
#define UC_MACRO_NAME_1E01F 0x1E01F // 𞀟 COMBINING GLAGOLITIC LETTER YERU
#define UC_MACRO_NAME_1E020 0x1E020 // 𞀠 COMBINING GLAGOLITIC LETTER YERI
#define UC_MACRO_NAME_1E021 0x1E021 // 𞀡 COMBINING GLAGOLITIC LETTER YATI
#define UC_MACRO_NAME_1E023 0x1E023 // 𞀣 COMBINING GLAGOLITIC LETTER YU
#define UC_MACRO_NAME_1E024 0x1E024 // 𞀤 COMBINING GLAGOLITIC LETTER SMALL YUS
#define UC_MACRO_NAME_1E026 0x1E026 // 𞀦 COMBINING GLAGOLITIC LETTER YO
#define UC_MACRO_NAME_1E027 0x1E027 // 𞀧 COMBINING GLAGOLITIC LETTER IOTATED SMALL YUS
#define UC_MACRO_NAME_1E028 0x1E028 // 𞀨 COMBINING GLAGOLITIC LETTER BIG YUS
#define UC_MACRO_NAME_1E029 0x1E029 // 𞀩 COMBINING GLAGOLITIC LETTER IOTATED BIG YUS
#define UC_MACRO_NAME_1E02A 0x1E02A // 𞀪 COMBINING GLAGOLITIC LETTER FITA


#endif // UC_H_GLAGOLITIC_SUPPLEMENT
