/*
 * Unicode Block: Greek Extended
 * Range: U+1F00..U+1FFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Greek Extended is a Unicode block containing the accented vowels
 * necessary for writing polytonic Greek . The regular, unaccented Greek
 * characters as well as the characters with tonos and diaeresis can be
 * found in the Greek and Coptic block . Greek Extended was encoded in
 * version 1.1 of the Unicode Standard . As an alternative to Greek
 * Extended, combining characters can be used to represent the tones and
 * breath marks of polytonic Greek.
 * In this block, the letters with oxia ( acute accent ) and no other
 * accent are not used in any of the Unicode normalizations .
 * Decomposition of U+1F71 ά GREEK SMALL LETTER ALPHA WITH OXIA , for
 * example, yields U+03B1 α GREEK SMALL LETTER ALPHA followed by a U+0301
 * ◌́ COMBINING ACUTE ACCENT , while composition yields the same letter
 * with tonos, U+03AC ά GREEK SMALL LETTER ALPHA WITH TONOS , from the
 * Greek and Coptic block.
 *
 */
#ifndef UC_H_GREEK_EXTENDED
#define UC_H_GREEK_EXTENDED

#define UC_MACRO_NAME_1F00 0x1F00 // ἀ GREEK SMALL LETTER ALPHA WITH PSILI
#define UC_MACRO_NAME_1F01 0x1F01 // ἁ GREEK SMALL LETTER ALPHA WITH DASIA
#define UC_MACRO_NAME_1F02 0x1F02 // ἂ GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA
#define UC_MACRO_NAME_1F03 0x1F03 // ἃ GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA
#define UC_MACRO_NAME_1F04 0x1F04 // ἄ GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA
#define UC_MACRO_NAME_1F05 0x1F05 // ἅ GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA
#define UC_MACRO_NAME_1F06 0x1F06 // ἆ GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI
#define UC_MACRO_NAME_1F07 0x1F07 // ἇ GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI
#define UC_MACRO_NAME_1F08 0x1F08 // Ἀ GREEK CAPITAL LETTER ALPHA WITH PSILI
#define UC_MACRO_NAME_1F09 0x1F09 // Ἁ GREEK CAPITAL LETTER ALPHA WITH DASIA
#define UC_MACRO_NAME_1F0A 0x1F0A // Ἂ GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA
#define UC_MACRO_NAME_1F0B 0x1F0B // Ἃ GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA
#define UC_MACRO_NAME_1F0C 0x1F0C // Ἄ GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA
#define UC_MACRO_NAME_1F0D 0x1F0D // Ἅ GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA
#define UC_MACRO_NAME_1F0E 0x1F0E // Ἆ GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI
#define UC_MACRO_NAME_1F0F 0x1F0F // Ἇ GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI
#define UC_MACRO_NAME_1F10 0x1F10 // ἐ GREEK SMALL LETTER EPSILON WITH PSILI
#define UC_MACRO_NAME_1F11 0x1F11 // ἑ GREEK SMALL LETTER EPSILON WITH DASIA
#define UC_MACRO_NAME_1F12 0x1F12 // ἒ GREEK SMALL LETTER EPSILON WITH PSILI AND VARIA
#define UC_MACRO_NAME_1F13 0x1F13 // ἓ GREEK SMALL LETTER EPSILON WITH DASIA AND VARIA
#define UC_MACRO_NAME_1F14 0x1F14 // ἔ GREEK SMALL LETTER EPSILON WITH PSILI AND OXIA
#define UC_MACRO_NAME_1F15 0x1F15 // ἕ GREEK SMALL LETTER EPSILON WITH DASIA AND OXIA
#define UC_MACRO_NAME_1F18 0x1F18 // Ἐ GREEK CAPITAL LETTER EPSILON WITH PSILI
#define UC_MACRO_NAME_1F19 0x1F19 // Ἑ GREEK CAPITAL LETTER EPSILON WITH DASIA
#define UC_MACRO_NAME_1F1A 0x1F1A // Ἒ GREEK CAPITAL LETTER EPSILON WITH PSILI AND VARIA
#define UC_MACRO_NAME_1F1B 0x1F1B // Ἓ GREEK CAPITAL LETTER EPSILON WITH DASIA AND VARIA
#define UC_MACRO_NAME_1F1C 0x1F1C // Ἔ GREEK CAPITAL LETTER EPSILON WITH PSILI AND OXIA
#define UC_MACRO_NAME_1F1D 0x1F1D // Ἕ GREEK CAPITAL LETTER EPSILON WITH DASIA AND OXIA
#define UC_MACRO_NAME_1F20 0x1F20 // ἠ GREEK SMALL LETTER ETA WITH PSILI
#define UC_MACRO_NAME_1F21 0x1F21 // ἡ GREEK SMALL LETTER ETA WITH DASIA
#define UC_MACRO_NAME_1F22 0x1F22 // ἢ GREEK SMALL LETTER ETA WITH PSILI AND VARIA
#define UC_MACRO_NAME_1F23 0x1F23 // ἣ GREEK SMALL LETTER ETA WITH DASIA AND VARIA
#define UC_MACRO_NAME_1F24 0x1F24 // ἤ GREEK SMALL LETTER ETA WITH PSILI AND OXIA
#define UC_MACRO_NAME_1F25 0x1F25 // ἥ GREEK SMALL LETTER ETA WITH DASIA AND OXIA
#define UC_MACRO_NAME_1F26 0x1F26 // ἦ GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI
#define UC_MACRO_NAME_1F27 0x1F27 // ἧ GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI
#define UC_MACRO_NAME_1F28 0x1F28 // Ἠ GREEK CAPITAL LETTER ETA WITH PSILI
#define UC_MACRO_NAME_1F29 0x1F29 // Ἡ GREEK CAPITAL LETTER ETA WITH DASIA
#define UC_MACRO_NAME_1F2A 0x1F2A // Ἢ GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA
#define UC_MACRO_NAME_1F2B 0x1F2B // Ἣ GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA
#define UC_MACRO_NAME_1F2C 0x1F2C // Ἤ GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA
#define UC_MACRO_NAME_1F2D 0x1F2D // Ἥ GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA
#define UC_MACRO_NAME_1F2E 0x1F2E // Ἦ GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI
#define UC_MACRO_NAME_1F2F 0x1F2F // Ἧ GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI
#define UC_MACRO_NAME_1F30 0x1F30 // ἰ GREEK SMALL LETTER IOTA WITH PSILI
#define UC_MACRO_NAME_1F31 0x1F31 // ἱ GREEK SMALL LETTER IOTA WITH DASIA
#define UC_MACRO_NAME_1F32 0x1F32 // ἲ GREEK SMALL LETTER IOTA WITH PSILI AND VARIA
#define UC_MACRO_NAME_1F33 0x1F33 // ἳ GREEK SMALL LETTER IOTA WITH DASIA AND VARIA
#define UC_MACRO_NAME_1F34 0x1F34 // ἴ GREEK SMALL LETTER IOTA WITH PSILI AND OXIA
#define UC_MACRO_NAME_1F35 0x1F35 // ἵ GREEK SMALL LETTER IOTA WITH DASIA AND OXIA
#define UC_MACRO_NAME_1F36 0x1F36 // ἶ GREEK SMALL LETTER IOTA WITH PSILI AND PERISPOMENI
#define UC_MACRO_NAME_1F37 0x1F37 // ἷ GREEK SMALL LETTER IOTA WITH DASIA AND PERISPOMENI
#define UC_MACRO_NAME_1F38 0x1F38 // Ἰ GREEK CAPITAL LETTER IOTA WITH PSILI
#define UC_MACRO_NAME_1F39 0x1F39 // Ἱ GREEK CAPITAL LETTER IOTA WITH DASIA
#define UC_MACRO_NAME_1F3A 0x1F3A // Ἲ GREEK CAPITAL LETTER IOTA WITH PSILI AND VARIA
#define UC_MACRO_NAME_1F3B 0x1F3B // Ἳ GREEK CAPITAL LETTER IOTA WITH DASIA AND VARIA
#define UC_MACRO_NAME_1F3C 0x1F3C // Ἴ GREEK CAPITAL LETTER IOTA WITH PSILI AND OXIA
#define UC_MACRO_NAME_1F3D 0x1F3D // Ἵ GREEK CAPITAL LETTER IOTA WITH DASIA AND OXIA
#define UC_MACRO_NAME_1F3E 0x1F3E // Ἶ GREEK CAPITAL LETTER IOTA WITH PSILI AND PERISPOMENI
#define UC_MACRO_NAME_1F3F 0x1F3F // Ἷ GREEK CAPITAL LETTER IOTA WITH DASIA AND PERISPOMENI
#define UC_MACRO_NAME_1F40 0x1F40 // ὀ GREEK SMALL LETTER OMICRON WITH PSILI
#define UC_MACRO_NAME_1F41 0x1F41 // ὁ GREEK SMALL LETTER OMICRON WITH DASIA
#define UC_MACRO_NAME_1F42 0x1F42 // ὂ GREEK SMALL LETTER OMICRON WITH PSILI AND VARIA
#define UC_MACRO_NAME_1F43 0x1F43 // ὃ GREEK SMALL LETTER OMICRON WITH DASIA AND VARIA
#define UC_MACRO_NAME_1F44 0x1F44 // ὄ GREEK SMALL LETTER OMICRON WITH PSILI AND OXIA
#define UC_MACRO_NAME_1F45 0x1F45 // ὅ GREEK SMALL LETTER OMICRON WITH DASIA AND OXIA
#define UC_MACRO_NAME_1F48 0x1F48 // Ὀ GREEK CAPITAL LETTER OMICRON WITH PSILI
#define UC_MACRO_NAME_1F49 0x1F49 // Ὁ GREEK CAPITAL LETTER OMICRON WITH DASIA
#define UC_MACRO_NAME_1F4A 0x1F4A // Ὂ GREEK CAPITAL LETTER OMICRON WITH PSILI AND VARIA
#define UC_MACRO_NAME_1F4B 0x1F4B // Ὃ GREEK CAPITAL LETTER OMICRON WITH DASIA AND VARIA
#define UC_MACRO_NAME_1F4C 0x1F4C // Ὄ GREEK CAPITAL LETTER OMICRON WITH PSILI AND OXIA
#define UC_MACRO_NAME_1F4D 0x1F4D // Ὅ GREEK CAPITAL LETTER OMICRON WITH DASIA AND OXIA
#define UC_MACRO_NAME_1F50 0x1F50 // ὐ GREEK SMALL LETTER UPSILON WITH PSILI
#define UC_MACRO_NAME_1F51 0x1F51 // ὑ GREEK SMALL LETTER UPSILON WITH DASIA
#define UC_MACRO_NAME_1F52 0x1F52 // ὒ GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA
#define UC_MACRO_NAME_1F53 0x1F53 // ὓ GREEK SMALL LETTER UPSILON WITH DASIA AND VARIA
#define UC_MACRO_NAME_1F54 0x1F54 // ὔ GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA
#define UC_MACRO_NAME_1F55 0x1F55 // ὕ GREEK SMALL LETTER UPSILON WITH DASIA AND OXIA
#define UC_MACRO_NAME_1F56 0x1F56 // ὖ GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI
#define UC_MACRO_NAME_1F57 0x1F57 // ὗ GREEK SMALL LETTER UPSILON WITH DASIA AND PERISPOMENI
#define UC_MACRO_NAME_1F59 0x1F59 // Ὑ GREEK CAPITAL LETTER UPSILON WITH DASIA
#define UC_MACRO_NAME_1F5B 0x1F5B // Ὓ GREEK CAPITAL LETTER UPSILON WITH DASIA AND VARIA
#define UC_MACRO_NAME_1F5D 0x1F5D // Ὕ GREEK CAPITAL LETTER UPSILON WITH DASIA AND OXIA
#define UC_MACRO_NAME_1F5F 0x1F5F // Ὗ GREEK CAPITAL LETTER UPSILON WITH DASIA AND PERISPOMENI
#define UC_MACRO_NAME_1F60 0x1F60 // ὠ GREEK SMALL LETTER OMEGA WITH PSILI
#define UC_MACRO_NAME_1F61 0x1F61 // ὡ GREEK SMALL LETTER OMEGA WITH DASIA
#define UC_MACRO_NAME_1F62 0x1F62 // ὢ GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA
#define UC_MACRO_NAME_1F63 0x1F63 // ὣ GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA
#define UC_MACRO_NAME_1F64 0x1F64 // ὤ GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA
#define UC_MACRO_NAME_1F65 0x1F65 // ὥ GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA
#define UC_MACRO_NAME_1F66 0x1F66 // ὦ GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI
#define UC_MACRO_NAME_1F67 0x1F67 // ὧ GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI
#define UC_MACRO_NAME_1F68 0x1F68 // Ὠ GREEK CAPITAL LETTER OMEGA WITH PSILI
#define UC_MACRO_NAME_1F69 0x1F69 // Ὡ GREEK CAPITAL LETTER OMEGA WITH DASIA
#define UC_MACRO_NAME_1F6A 0x1F6A // Ὢ GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA
#define UC_MACRO_NAME_1F6B 0x1F6B // Ὣ GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA
#define UC_MACRO_NAME_1F6C 0x1F6C // Ὤ GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA
#define UC_MACRO_NAME_1F6D 0x1F6D // Ὥ GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA
#define UC_MACRO_NAME_1F6E 0x1F6E // Ὦ GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI
#define UC_MACRO_NAME_1F6F 0x1F6F // Ὧ GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI
#define UC_MACRO_NAME_1F70 0x1F70 // ὰ GREEK SMALL LETTER ALPHA WITH VARIA
#define UC_MACRO_NAME_1F71 0x1F71 // ά GREEK SMALL LETTER ALPHA WITH OXIA
#define UC_MACRO_NAME_1F72 0x1F72 // ὲ GREEK SMALL LETTER EPSILON WITH VARIA
#define UC_MACRO_NAME_1F73 0x1F73 // έ GREEK SMALL LETTER EPSILON WITH OXIA
#define UC_MACRO_NAME_1F74 0x1F74 // ὴ GREEK SMALL LETTER ETA WITH VARIA
#define UC_MACRO_NAME_1F75 0x1F75 // ή GREEK SMALL LETTER ETA WITH OXIA
#define UC_MACRO_NAME_1F76 0x1F76 // ὶ GREEK SMALL LETTER IOTA WITH VARIA
#define UC_MACRO_NAME_1F77 0x1F77 // ί GREEK SMALL LETTER IOTA WITH OXIA
#define UC_MACRO_NAME_1F78 0x1F78 // ὸ GREEK SMALL LETTER OMICRON WITH VARIA
#define UC_MACRO_NAME_1F79 0x1F79 // ό GREEK SMALL LETTER OMICRON WITH OXIA
#define UC_MACRO_NAME_1F7A 0x1F7A // ὺ GREEK SMALL LETTER UPSILON WITH VARIA
#define UC_MACRO_NAME_1F7B 0x1F7B // ύ GREEK SMALL LETTER UPSILON WITH OXIA
#define UC_MACRO_NAME_1F7C 0x1F7C // ὼ GREEK SMALL LETTER OMEGA WITH VARIA
#define UC_MACRO_NAME_1F7D 0x1F7D // ώ GREEK SMALL LETTER OMEGA WITH OXIA
#define UC_MACRO_NAME_1F80 0x1F80 // ᾀ GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1F81 0x1F81 // ᾁ GREEK SMALL LETTER ALPHA WITH DASIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1F82 0x1F82 // ᾂ GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1F83 0x1F83 // ᾃ GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1F84 0x1F84 // ᾄ GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1F85 0x1F85 // ᾅ GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1F86 0x1F86 // ᾆ GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1F87 0x1F87 // ᾇ GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1F88 0x1F88 // ᾈ GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1F89 0x1F89 // ᾉ GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1F8A 0x1F8A // ᾊ GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1F8B 0x1F8B // ᾋ GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1F8C 0x1F8C // ᾌ GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1F8D 0x1F8D // ᾍ GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1F8E 0x1F8E // ᾎ GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1F8F 0x1F8F // ᾏ GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1F90 0x1F90 // ᾐ GREEK SMALL LETTER ETA WITH PSILI AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1F91 0x1F91 // ᾑ GREEK SMALL LETTER ETA WITH DASIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1F92 0x1F92 // ᾒ GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1F93 0x1F93 // ᾓ GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1F94 0x1F94 // ᾔ GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1F95 0x1F95 // ᾕ GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1F96 0x1F96 // ᾖ GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1F97 0x1F97 // ᾗ GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1F98 0x1F98 // ᾘ GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1F99 0x1F99 // ᾙ GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1F9A 0x1F9A // ᾚ GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1F9B 0x1F9B // ᾛ GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1F9C 0x1F9C // ᾜ GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1F9D 0x1F9D // ᾝ GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1F9E 0x1F9E // ᾞ GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1F9F 0x1F9F // ᾟ GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1FA0 0x1FA0 // ᾠ GREEK SMALL LETTER OMEGA WITH PSILI AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1FA1 0x1FA1 // ᾡ GREEK SMALL LETTER OMEGA WITH DASIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1FA2 0x1FA2 // ᾢ GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1FA3 0x1FA3 // ᾣ GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1FA4 0x1FA4 // ᾤ GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1FA5 0x1FA5 // ᾥ GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1FA6 0x1FA6 // ᾦ GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1FA7 0x1FA7 // ᾧ GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1FA8 0x1FA8 // ᾨ GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1FA9 0x1FA9 // ᾩ GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1FAA 0x1FAA // ᾪ GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1FAB 0x1FAB // ᾫ GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1FAC 0x1FAC // ᾬ GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1FAD 0x1FAD // ᾭ GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1FAE 0x1FAE // ᾮ GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1FAF 0x1FAF // ᾯ GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
#define UC_MACRO_NAME_1FB0 0x1FB0 // ᾰ GREEK SMALL LETTER ALPHA WITH VRACHY
#define UC_MACRO_NAME_1FB1 0x1FB1 // ᾱ GREEK SMALL LETTER ALPHA WITH MACRON
#define UC_MACRO_NAME_1FB2 0x1FB2 // ᾲ GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1FB3 0x1FB3 // ᾳ GREEK SMALL LETTER ALPHA WITH YPOGEGRAMMENI
#define UC_MACRO_NAME_1FB4 0x1FB4 // ᾴ GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1FB6 0x1FB6 // ᾶ GREEK SMALL LETTER ALPHA WITH PERISPOMENI
#define UC_MACRO_NAME_1FB7 0x1FB7 // ᾷ GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1FB8 0x1FB8 // Ᾰ GREEK CAPITAL LETTER ALPHA WITH VRACHY
#define UC_MACRO_NAME_1FB9 0x1FB9 // Ᾱ GREEK CAPITAL LETTER ALPHA WITH MACRON
#define UC_MACRO_NAME_1FBA 0x1FBA // Ὰ GREEK CAPITAL LETTER ALPHA WITH VARIA
#define UC_MACRO_NAME_1FBB 0x1FBB // Ά GREEK CAPITAL LETTER ALPHA WITH OXIA
#define UC_MACRO_NAME_1FBC 0x1FBC // ᾼ GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI
#define UC_MACRO_NAME_1FBD 0x1FBD // ᾽ GREEK KORONIS
#define UC_MACRO_NAME_1FBE 0x1FBE // ι GREEK PROSGEGRAMMENI
#define UC_MACRO_NAME_1FBF 0x1FBF // ᾿ GREEK PSILI
#define UC_MACRO_NAME_1FC0 0x1FC0 // ῀ GREEK PERISPOMENI
#define UC_MACRO_NAME_1FC1 0x1FC1 // ῁ GREEK DIALYTIKA AND PERISPOMENI
#define UC_MACRO_NAME_1FC2 0x1FC2 // ῂ GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1FC3 0x1FC3 // ῃ GREEK SMALL LETTER ETA WITH YPOGEGRAMMENI
#define UC_MACRO_NAME_1FC4 0x1FC4 // ῄ GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1FC6 0x1FC6 // ῆ GREEK SMALL LETTER ETA WITH PERISPOMENI
#define UC_MACRO_NAME_1FC7 0x1FC7 // ῇ GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1FC8 0x1FC8 // Ὲ GREEK CAPITAL LETTER EPSILON WITH VARIA
#define UC_MACRO_NAME_1FC9 0x1FC9 // Έ GREEK CAPITAL LETTER EPSILON WITH OXIA
#define UC_MACRO_NAME_1FCA 0x1FCA // Ὴ GREEK CAPITAL LETTER ETA WITH VARIA
#define UC_MACRO_NAME_1FCB 0x1FCB // Ή GREEK CAPITAL LETTER ETA WITH OXIA
#define UC_MACRO_NAME_1FCC 0x1FCC // ῌ GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
#define UC_MACRO_NAME_1FCD 0x1FCD // ῍ GREEK PSILI AND VARIA
#define UC_MACRO_NAME_1FCE 0x1FCE // ῎ GREEK PSILI AND OXIA
#define UC_MACRO_NAME_1FCF 0x1FCF // ῏ GREEK PSILI AND PERISPOMENI
#define UC_MACRO_NAME_1FD0 0x1FD0 // ῐ GREEK SMALL LETTER IOTA WITH VRACHY
#define UC_MACRO_NAME_1FD1 0x1FD1 // ῑ GREEK SMALL LETTER IOTA WITH MACRON
#define UC_MACRO_NAME_1FD2 0x1FD2 // ῒ GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA
#define UC_MACRO_NAME_1FD3 0x1FD3 // ΐ GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
#define UC_MACRO_NAME_1FD6 0x1FD6 // ῖ GREEK SMALL LETTER IOTA WITH PERISPOMENI
#define UC_MACRO_NAME_1FD7 0x1FD7 // ῗ GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI
#define UC_MACRO_NAME_1FD8 0x1FD8 // Ῐ GREEK CAPITAL LETTER IOTA WITH VRACHY
#define UC_MACRO_NAME_1FD9 0x1FD9 // Ῑ GREEK CAPITAL LETTER IOTA WITH MACRON
#define UC_MACRO_NAME_1FDA 0x1FDA // Ὶ GREEK CAPITAL LETTER IOTA WITH VARIA
#define UC_MACRO_NAME_1FDB 0x1FDB // Ί GREEK CAPITAL LETTER IOTA WITH OXIA
#define UC_MACRO_NAME_1FDD 0x1FDD // ῝ GREEK DASIA AND VARIA
#define UC_MACRO_NAME_1FDE 0x1FDE // ῞ GREEK DASIA AND OXIA
#define UC_MACRO_NAME_1FDF 0x1FDF // ῟ GREEK DASIA AND PERISPOMENI
#define UC_MACRO_NAME_1FE0 0x1FE0 // ῠ GREEK SMALL LETTER UPSILON WITH VRACHY
#define UC_MACRO_NAME_1FE1 0x1FE1 // ῡ GREEK SMALL LETTER UPSILON WITH MACRON
#define UC_MACRO_NAME_1FE2 0x1FE2 // ῢ GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA
#define UC_MACRO_NAME_1FE3 0x1FE3 // ΰ GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA
#define UC_MACRO_NAME_1FE4 0x1FE4 // ῤ GREEK SMALL LETTER RHO WITH PSILI
#define UC_MACRO_NAME_1FE5 0x1FE5 // ῥ GREEK SMALL LETTER RHO WITH DASIA
#define UC_MACRO_NAME_1FE6 0x1FE6 // ῦ GREEK SMALL LETTER UPSILON WITH PERISPOMENI
#define UC_MACRO_NAME_1FE7 0x1FE7 // ῧ GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI
#define UC_MACRO_NAME_1FE8 0x1FE8 // Ῠ GREEK CAPITAL LETTER UPSILON WITH VRACHY
#define UC_MACRO_NAME_1FE9 0x1FE9 // Ῡ GREEK CAPITAL LETTER UPSILON WITH MACRON
#define UC_MACRO_NAME_1FEA 0x1FEA // Ὺ GREEK CAPITAL LETTER UPSILON WITH VARIA
#define UC_MACRO_NAME_1FEB 0x1FEB // Ύ GREEK CAPITAL LETTER UPSILON WITH OXIA
#define UC_MACRO_NAME_1FEC 0x1FEC // Ῥ GREEK CAPITAL LETTER RHO WITH DASIA
#define UC_MACRO_NAME_1FED 0x1FED // ῭ GREEK DIALYTIKA AND VARIA
#define UC_MACRO_NAME_1FEE 0x1FEE // ΅ GREEK DIALYTIKA AND OXIA
#define UC_MACRO_NAME_1FEF 0x1FEF // ` GREEK VARIA
#define UC_MACRO_NAME_1FF2 0x1FF2 // ῲ GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1FF3 0x1FF3 // ῳ GREEK SMALL LETTER OMEGA WITH YPOGEGRAMMENI
#define UC_MACRO_NAME_1FF4 0x1FF4 // ῴ GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1FF6 0x1FF6 // ῶ GREEK SMALL LETTER OMEGA WITH PERISPOMENI
#define UC_MACRO_NAME_1FF7 0x1FF7 // ῷ GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI
#define UC_MACRO_NAME_1FF8 0x1FF8 // Ὸ GREEK CAPITAL LETTER OMICRON WITH VARIA
#define UC_MACRO_NAME_1FF9 0x1FF9 // Ό GREEK CAPITAL LETTER OMICRON WITH OXIA
#define UC_MACRO_NAME_1FFA 0x1FFA // Ὼ GREEK CAPITAL LETTER OMEGA WITH VARIA
#define UC_MACRO_NAME_1FFB 0x1FFB // Ώ GREEK CAPITAL LETTER OMEGA WITH OXIA
#define UC_MACRO_NAME_1FFC 0x1FFC // ῼ GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI
#define UC_MACRO_NAME_1FFD 0x1FFD // ´ GREEK OXIA
#define UC_MACRO_NAME_1FFE 0x1FFE // ῾ GREEK DASIA


#endif // UC_H_GREEK_EXTENDED
