/*
 * Unicode Block: Gujarati
 * Range: U+0A80..U+0AFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Gujarati may refer to:
 *
 */
#ifndef UC_H_GUJARATI
#define UC_H_GUJARATI

#define UC_MACRO_NAME_A81 0x0A81 // ઁ GUJARATI SIGN CANDRABINDU
#define UC_MACRO_NAME_A82 0x0A82 // ં GUJARATI SIGN ANUSVARA
#define UC_MACRO_NAME_A83 0x0A83 // ઃ GUJARATI SIGN VISARGA
#define UC_MACRO_NAME_A85 0x0A85 // અ GUJARATI LETTER A
#define UC_MACRO_NAME_A86 0x0A86 // આ GUJARATI LETTER AA
#define UC_MACRO_NAME_A87 0x0A87 // ઇ GUJARATI LETTER I
#define UC_MACRO_NAME_A88 0x0A88 // ઈ GUJARATI LETTER II
#define UC_MACRO_NAME_A89 0x0A89 // ઉ GUJARATI LETTER U
#define UC_MACRO_NAME_A8A 0x0A8A // ઊ GUJARATI LETTER UU
#define UC_MACRO_NAME_A8B 0x0A8B // ઋ GUJARATI LETTER VOCALIC R
#define UC_MACRO_NAME_A8C 0x0A8C // ઌ GUJARATI LETTER VOCALIC L
#define UC_MACRO_NAME_A8D 0x0A8D // ઍ GUJARATI VOWEL CANDRA E
#define UC_MACRO_NAME_A8F 0x0A8F // એ GUJARATI LETTER E
#define UC_MACRO_NAME_A90 0x0A90 // ઐ GUJARATI LETTER AI
#define UC_MACRO_NAME_A91 0x0A91 // ઑ GUJARATI VOWEL CANDRA O
#define UC_MACRO_NAME_A93 0x0A93 // ઓ GUJARATI LETTER O
#define UC_MACRO_NAME_A94 0x0A94 // ઔ GUJARATI LETTER AU
#define UC_MACRO_NAME_A95 0x0A95 // ક GUJARATI LETTER KA
#define UC_MACRO_NAME_A96 0x0A96 // ખ GUJARATI LETTER KHA
#define UC_MACRO_NAME_A97 0x0A97 // ગ GUJARATI LETTER GA
#define UC_MACRO_NAME_A98 0x0A98 // ઘ GUJARATI LETTER GHA
#define UC_MACRO_NAME_A99 0x0A99 // ઙ GUJARATI LETTER NGA
#define UC_MACRO_NAME_A9A 0x0A9A // ચ GUJARATI LETTER CA
#define UC_MACRO_NAME_A9B 0x0A9B // છ GUJARATI LETTER CHA
#define UC_MACRO_NAME_A9C 0x0A9C // જ GUJARATI LETTER JA
#define UC_MACRO_NAME_A9D 0x0A9D // ઝ GUJARATI LETTER JHA
#define UC_MACRO_NAME_A9E 0x0A9E // ઞ GUJARATI LETTER NYA
#define UC_MACRO_NAME_A9F 0x0A9F // ટ GUJARATI LETTER TTA
#define UC_MACRO_NAME_AA0 0x0AA0 // ઠ GUJARATI LETTER TTHA
#define UC_MACRO_NAME_AA1 0x0AA1 // ડ GUJARATI LETTER DDA
#define UC_MACRO_NAME_AA2 0x0AA2 // ઢ GUJARATI LETTER DDHA
#define UC_MACRO_NAME_AA3 0x0AA3 // ણ GUJARATI LETTER NNA
#define UC_MACRO_NAME_AA4 0x0AA4 // ત GUJARATI LETTER TA
#define UC_MACRO_NAME_AA5 0x0AA5 // થ GUJARATI LETTER THA
#define UC_MACRO_NAME_AA6 0x0AA6 // દ GUJARATI LETTER DA
#define UC_MACRO_NAME_AA7 0x0AA7 // ધ GUJARATI LETTER DHA
#define UC_MACRO_NAME_AA8 0x0AA8 // ન GUJARATI LETTER NA
#define UC_MACRO_NAME_AAA 0x0AAA // પ GUJARATI LETTER PA
#define UC_MACRO_NAME_AAB 0x0AAB // ફ GUJARATI LETTER PHA
#define UC_MACRO_NAME_AAC 0x0AAC // બ GUJARATI LETTER BA
#define UC_MACRO_NAME_AAD 0x0AAD // ભ GUJARATI LETTER BHA
#define UC_MACRO_NAME_AAE 0x0AAE // મ GUJARATI LETTER MA
#define UC_MACRO_NAME_AAF 0x0AAF // ય GUJARATI LETTER YA
#define UC_MACRO_NAME_AB0 0x0AB0 // ર GUJARATI LETTER RA
#define UC_MACRO_NAME_AB2 0x0AB2 // લ GUJARATI LETTER LA
#define UC_MACRO_NAME_AB3 0x0AB3 // ળ GUJARATI LETTER LLA
#define UC_MACRO_NAME_AB5 0x0AB5 // વ GUJARATI LETTER VA
#define UC_MACRO_NAME_AB6 0x0AB6 // શ GUJARATI LETTER SHA
#define UC_MACRO_NAME_AB7 0x0AB7 // ષ GUJARATI LETTER SSA
#define UC_MACRO_NAME_AB8 0x0AB8 // સ GUJARATI LETTER SA
#define UC_MACRO_NAME_AB9 0x0AB9 // હ GUJARATI LETTER HA
#define UC_MACRO_NAME_ABC 0x0ABC // ઼ GUJARATI SIGN NUKTA
#define UC_MACRO_NAME_ABD 0x0ABD // ઽ GUJARATI SIGN AVAGRAHA
#define UC_MACRO_NAME_ABE 0x0ABE // ા GUJARATI VOWEL SIGN AA
#define UC_MACRO_NAME_ABF 0x0ABF // િ GUJARATI VOWEL SIGN I
#define UC_MACRO_NAME_AC0 0x0AC0 // ી GUJARATI VOWEL SIGN II
#define UC_MACRO_NAME_AC1 0x0AC1 // ુ GUJARATI VOWEL SIGN U
#define UC_MACRO_NAME_AC2 0x0AC2 // ૂ GUJARATI VOWEL SIGN UU
#define UC_MACRO_NAME_AC3 0x0AC3 // ૃ GUJARATI VOWEL SIGN VOCALIC R
#define UC_MACRO_NAME_AC4 0x0AC4 // ૄ GUJARATI VOWEL SIGN VOCALIC RR
#define UC_MACRO_NAME_AC5 0x0AC5 // ૅ GUJARATI VOWEL SIGN CANDRA E
#define UC_MACRO_NAME_AC7 0x0AC7 // ે GUJARATI VOWEL SIGN E
#define UC_MACRO_NAME_AC8 0x0AC8 // ૈ GUJARATI VOWEL SIGN AI
#define UC_MACRO_NAME_AC9 0x0AC9 // ૉ GUJARATI VOWEL SIGN CANDRA O
#define UC_MACRO_NAME_ACB 0x0ACB // ો GUJARATI VOWEL SIGN O
#define UC_MACRO_NAME_ACC 0x0ACC // ૌ GUJARATI VOWEL SIGN AU
#define UC_MACRO_NAME_ACD 0x0ACD // ્ GUJARATI SIGN VIRAMA
#define UC_MACRO_NAME_AD0 0x0AD0 // ૐ GUJARATI OM
#define UC_MACRO_NAME_AE0 0x0AE0 // ૠ GUJARATI LETTER VOCALIC RR
#define UC_MACRO_NAME_AE1 0x0AE1 // ૡ GUJARATI LETTER VOCALIC LL
#define UC_MACRO_NAME_AE2 0x0AE2 // ૢ GUJARATI VOWEL SIGN VOCALIC L
#define UC_MACRO_NAME_AE3 0x0AE3 // ૣ GUJARATI VOWEL SIGN VOCALIC LL
#define UC_MACRO_NAME_AE6 0x0AE6 // ૦ GUJARATI DIGIT ZERO
#define UC_MACRO_NAME_AE7 0x0AE7 // ૧ GUJARATI DIGIT ONE
#define UC_MACRO_NAME_AE8 0x0AE8 // ૨ GUJARATI DIGIT TWO
#define UC_MACRO_NAME_AE9 0x0AE9 // ૩ GUJARATI DIGIT THREE
#define UC_MACRO_NAME_AEA 0x0AEA // ૪ GUJARATI DIGIT FOUR
#define UC_MACRO_NAME_AEB 0x0AEB // ૫ GUJARATI DIGIT FIVE
#define UC_MACRO_NAME_AEC 0x0AEC // ૬ GUJARATI DIGIT SIX
#define UC_MACRO_NAME_AED 0x0AED // ૭ GUJARATI DIGIT SEVEN
#define UC_MACRO_NAME_AEE 0x0AEE // ૮ GUJARATI DIGIT EIGHT
#define UC_MACRO_NAME_AEF 0x0AEF // ૯ GUJARATI DIGIT NINE
#define UC_MACRO_NAME_AF0 0x0AF0 // ૰ GUJARATI ABBREVIATION SIGN
#define UC_MACRO_NAME_AF1 0x0AF1 // ૱ GUJARATI RUPEE SIGN
#define UC_MACRO_NAME_AF9 0x0AF9 // ૹ GUJARATI LETTER ZHA
#define UC_MACRO_NAME_AFA 0x0AFA // ૺ GUJARATI SIGN SUKUN
#define UC_MACRO_NAME_AFB 0x0AFB // ૻ GUJARATI SIGN SHADDA
#define UC_MACRO_NAME_AFC 0x0AFC // ૼ GUJARATI SIGN MADDAH
#define UC_MACRO_NAME_AFD 0x0AFD // ૽ GUJARATI SIGN THREE-DOT NUKTA ABOVE
#define UC_MACRO_NAME_AFE 0x0AFE // ૾ GUJARATI SIGN CIRCLE NUKTA ABOVE
#define UC_MACRO_NAME_AFF 0x0AFF // ૿ GUJARATI SIGN TWO-CIRCLE NUKTA ABOVE


#endif // UC_H_GUJARATI
