/*
 * Unicode Block: Georgian Extended
 * Range: U+1C90..U+1CBF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Georgian Extended is a Unicode block containing Georgian Mtavruli (
 * Georgian : მთავრული , "title" or "heading") letters that function as
 * uppercase versions of their Mkhedruli counterparts in the Georgian
 * block . Unlike all other casing scripts in Unicode, there is no title
 * casing between Mkhedruli and Mtavruli letters, because Mtavruli is
 * typically used only in all-caps text, although there have been some
 * historical attempts at capitalization.
 * The following Unicode-related documents record the purpose and process
 * of defining specific characters in the Georgian Extended block:
 *
 */
#ifndef UC_H_GEORGIAN_EXTENDED
#define UC_H_GEORGIAN_EXTENDED

#define UC_MACRO_NAME_1C90 0x1C90 // Ა GEORGIAN MTAVRULI CAPITAL LETTER AN
#define UC_MACRO_NAME_1C91 0x1C91 // Ბ GEORGIAN MTAVRULI CAPITAL LETTER BAN
#define UC_MACRO_NAME_1C92 0x1C92 // Გ GEORGIAN MTAVRULI CAPITAL LETTER GAN
#define UC_MACRO_NAME_1C93 0x1C93 // Დ GEORGIAN MTAVRULI CAPITAL LETTER DON
#define UC_MACRO_NAME_1C94 0x1C94 // Ე GEORGIAN MTAVRULI CAPITAL LETTER EN
#define UC_MACRO_NAME_1C95 0x1C95 // Ვ GEORGIAN MTAVRULI CAPITAL LETTER VIN
#define UC_MACRO_NAME_1C96 0x1C96 // Ზ GEORGIAN MTAVRULI CAPITAL LETTER ZEN
#define UC_MACRO_NAME_1C97 0x1C97 // Თ GEORGIAN MTAVRULI CAPITAL LETTER TAN
#define UC_MACRO_NAME_1C98 0x1C98 // Ი GEORGIAN MTAVRULI CAPITAL LETTER IN
#define UC_MACRO_NAME_1C99 0x1C99 // Კ GEORGIAN MTAVRULI CAPITAL LETTER KAN
#define UC_MACRO_NAME_1C9A 0x1C9A // Ლ GEORGIAN MTAVRULI CAPITAL LETTER LAS
#define UC_MACRO_NAME_1C9B 0x1C9B // Მ GEORGIAN MTAVRULI CAPITAL LETTER MAN
#define UC_MACRO_NAME_1C9C 0x1C9C // Ნ GEORGIAN MTAVRULI CAPITAL LETTER NAR
#define UC_MACRO_NAME_1C9D 0x1C9D // Ო GEORGIAN MTAVRULI CAPITAL LETTER ON
#define UC_MACRO_NAME_1C9E 0x1C9E // Პ GEORGIAN MTAVRULI CAPITAL LETTER PAR
#define UC_MACRO_NAME_1C9F 0x1C9F // Ჟ GEORGIAN MTAVRULI CAPITAL LETTER ZHAR
#define UC_MACRO_NAME_1CA0 0x1CA0 // Რ GEORGIAN MTAVRULI CAPITAL LETTER RAE
#define UC_MACRO_NAME_1CA1 0x1CA1 // Ს GEORGIAN MTAVRULI CAPITAL LETTER SAN
#define UC_MACRO_NAME_1CA2 0x1CA2 // Ტ GEORGIAN MTAVRULI CAPITAL LETTER TAR
#define UC_MACRO_NAME_1CA3 0x1CA3 // Უ GEORGIAN MTAVRULI CAPITAL LETTER UN
#define UC_MACRO_NAME_1CA4 0x1CA4 // Ფ GEORGIAN MTAVRULI CAPITAL LETTER PHAR
#define UC_MACRO_NAME_1CA5 0x1CA5 // Ქ GEORGIAN MTAVRULI CAPITAL LETTER KHAR
#define UC_MACRO_NAME_1CA6 0x1CA6 // Ღ GEORGIAN MTAVRULI CAPITAL LETTER GHAN
#define UC_MACRO_NAME_1CA7 0x1CA7 // Ყ GEORGIAN MTAVRULI CAPITAL LETTER QAR
#define UC_MACRO_NAME_1CA8 0x1CA8 // Შ GEORGIAN MTAVRULI CAPITAL LETTER SHIN
#define UC_MACRO_NAME_1CA9 0x1CA9 // Ჩ GEORGIAN MTAVRULI CAPITAL LETTER CHIN
#define UC_MACRO_NAME_1CAA 0x1CAA // Ც GEORGIAN MTAVRULI CAPITAL LETTER CAN
#define UC_MACRO_NAME_1CAB 0x1CAB // Ძ GEORGIAN MTAVRULI CAPITAL LETTER JIL
#define UC_MACRO_NAME_1CAC 0x1CAC // Წ GEORGIAN MTAVRULI CAPITAL LETTER CIL
#define UC_MACRO_NAME_1CAD 0x1CAD // Ჭ GEORGIAN MTAVRULI CAPITAL LETTER CHAR
#define UC_MACRO_NAME_1CAE 0x1CAE // Ხ GEORGIAN MTAVRULI CAPITAL LETTER XAN
#define UC_MACRO_NAME_1CAF 0x1CAF // Ჯ GEORGIAN MTAVRULI CAPITAL LETTER JHAN
#define UC_MACRO_NAME_1CB0 0x1CB0 // Ჰ GEORGIAN MTAVRULI CAPITAL LETTER HAE
#define UC_MACRO_NAME_1CB1 0x1CB1 // Ჱ GEORGIAN MTAVRULI CAPITAL LETTER HE
#define UC_MACRO_NAME_1CB2 0x1CB2 // Ჲ GEORGIAN MTAVRULI CAPITAL LETTER HIE
#define UC_MACRO_NAME_1CB3 0x1CB3 // Ჳ GEORGIAN MTAVRULI CAPITAL LETTER WE
#define UC_MACRO_NAME_1CB4 0x1CB4 // Ჴ GEORGIAN MTAVRULI CAPITAL LETTER HAR
#define UC_MACRO_NAME_1CB5 0x1CB5 // Ჵ GEORGIAN MTAVRULI CAPITAL LETTER HOE
#define UC_MACRO_NAME_1CB6 0x1CB6 // Ჶ GEORGIAN MTAVRULI CAPITAL LETTER FI
#define UC_MACRO_NAME_1CB7 0x1CB7 // Ჷ GEORGIAN MTAVRULI CAPITAL LETTER YN
#define UC_MACRO_NAME_1CB8 0x1CB8 // Ჸ GEORGIAN MTAVRULI CAPITAL LETTER ELIFI
#define UC_MACRO_NAME_1CB9 0x1CB9 // Ჹ GEORGIAN MTAVRULI CAPITAL LETTER TURNED GAN
#define UC_MACRO_NAME_1CBA 0x1CBA // Ჺ GEORGIAN MTAVRULI CAPITAL LETTER AIN
#define UC_MACRO_NAME_1CBD 0x1CBD // Ჽ GEORGIAN MTAVRULI CAPITAL LETTER AEN
#define UC_MACRO_NAME_1CBE 0x1CBE // Ჾ GEORGIAN MTAVRULI CAPITAL LETTER HARD SIGN
#define UC_MACRO_NAME_1CBF 0x1CBF // Ჿ GEORGIAN MTAVRULI CAPITAL LETTER LABIAL SIGN


#endif // UC_H_GEORGIAN_EXTENDED
