/*
 * Unicode Block: Geometric Shapes
 * Range: U+25A0..U+25FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_GEOMETRIC_SHAPES
#define UC_H_GEOMETRIC_SHAPES

#define UC_MACRO_NAME_25A0 0x25A0 // ■ BLACK SQUARE
#define UC_MACRO_NAME_25A1 0x25A1 // □ WHITE SQUARE
#define UC_MACRO_NAME_25A2 0x25A2 // ▢ WHITE SQUARE WITH ROUNDED CORNERS
#define UC_MACRO_NAME_25A3 0x25A3 // ▣ WHITE SQUARE CONTAINING BLACK SMALL SQUARE
#define UC_MACRO_NAME_25A4 0x25A4 // ▤ SQUARE WITH HORIZONTAL FILL
#define UC_MACRO_NAME_25A5 0x25A5 // ▥ SQUARE WITH VERTICAL FILL
#define UC_MACRO_NAME_25A6 0x25A6 // ▦ SQUARE WITH ORTHOGONAL CROSSHATCH FILL
#define UC_MACRO_NAME_25A7 0x25A7 // ▧ SQUARE WITH UPPER LEFT TO LOWER RIGHT FILL
#define UC_MACRO_NAME_25A8 0x25A8 // ▨ SQUARE WITH UPPER RIGHT TO LOWER LEFT FILL
#define UC_MACRO_NAME_25A9 0x25A9 // ▩ SQUARE WITH DIAGONAL CROSSHATCH FILL
#define UC_MACRO_NAME_25AA 0x25AA // ▪ BLACK SMALL SQUARE
#define UC_MACRO_NAME_25AB 0x25AB // ▫ WHITE SMALL SQUARE
#define UC_MACRO_NAME_25AC 0x25AC // ▬ BLACK RECTANGLE
#define UC_MACRO_NAME_25AD 0x25AD // ▭ WHITE RECTANGLE
#define UC_MACRO_NAME_25AE 0x25AE // ▮ BLACK VERTICAL RECTANGLE
#define UC_MACRO_NAME_25AF 0x25AF // ▯ WHITE VERTICAL RECTANGLE
#define UC_MACRO_NAME_25B0 0x25B0 // ▰ BLACK PARALLELOGRAM
#define UC_MACRO_NAME_25B1 0x25B1 // ▱ WHITE PARALLELOGRAM
#define UC_MACRO_NAME_25B2 0x25B2 // ▲ BLACK UP-POINTING TRIANGLE
#define UC_MACRO_NAME_25B3 0x25B3 // △ WHITE UP-POINTING TRIANGLE
#define UC_MACRO_NAME_25B4 0x25B4 // ▴ BLACK UP-POINTING SMALL TRIANGLE
#define UC_MACRO_NAME_25B5 0x25B5 // ▵ WHITE UP-POINTING SMALL TRIANGLE
#define UC_MACRO_NAME_25B6 0x25B6 // ▶ BLACK RIGHT-POINTING TRIANGLE
#define UC_MACRO_NAME_25B7 0x25B7 // ▷ WHITE RIGHT-POINTING TRIANGLE
#define UC_MACRO_NAME_25B8 0x25B8 // ▸ BLACK RIGHT-POINTING SMALL TRIANGLE
#define UC_MACRO_NAME_25B9 0x25B9 // ▹ WHITE RIGHT-POINTING SMALL TRIANGLE
#define UC_MACRO_NAME_25BA 0x25BA // ► BLACK RIGHT-POINTING POINTER
#define UC_MACRO_NAME_25BB 0x25BB // ▻ WHITE RIGHT-POINTING POINTER
#define UC_MACRO_NAME_25BC 0x25BC // ▼ BLACK DOWN-POINTING TRIANGLE
#define UC_MACRO_NAME_25BD 0x25BD // ▽ WHITE DOWN-POINTING TRIANGLE
#define UC_MACRO_NAME_25BE 0x25BE // ▾ BLACK DOWN-POINTING SMALL TRIANGLE
#define UC_MACRO_NAME_25BF 0x25BF // ▿ WHITE DOWN-POINTING SMALL TRIANGLE
#define UC_MACRO_NAME_25C0 0x25C0 // ◀ BLACK LEFT-POINTING TRIANGLE
#define UC_MACRO_NAME_25C1 0x25C1 // ◁ WHITE LEFT-POINTING TRIANGLE
#define UC_MACRO_NAME_25C2 0x25C2 // ◂ BLACK LEFT-POINTING SMALL TRIANGLE
#define UC_MACRO_NAME_25C3 0x25C3 // ◃ WHITE LEFT-POINTING SMALL TRIANGLE
#define UC_MACRO_NAME_25C4 0x25C4 // ◄ BLACK LEFT-POINTING POINTER
#define UC_MACRO_NAME_25C5 0x25C5 // ◅ WHITE LEFT-POINTING POINTER
#define UC_MACRO_NAME_25C6 0x25C6 // ◆ BLACK DIAMOND
#define UC_MACRO_NAME_25C7 0x25C7 // ◇ WHITE DIAMOND
#define UC_MACRO_NAME_25C8 0x25C8 // ◈ WHITE DIAMOND CONTAINING BLACK SMALL DIAMOND
#define UC_MACRO_NAME_25C9 0x25C9 // ◉ FISHEYE
#define UC_MACRO_NAME_25CA 0x25CA // ◊ LOZENGE
#define UC_MACRO_NAME_25CB 0x25CB // ○ WHITE CIRCLE
#define UC_MACRO_NAME_25CC 0x25CC // ◌ DOTTED CIRCLE
#define UC_MACRO_NAME_25CD 0x25CD // ◍ CIRCLE WITH VERTICAL FILL
#define UC_MACRO_NAME_25CE 0x25CE // ◎ BULLSEYE
#define UC_MACRO_NAME_25CF 0x25CF // ● BLACK CIRCLE
#define UC_MACRO_NAME_25D0 0x25D0 // ◐ CIRCLE WITH LEFT HALF BLACK
#define UC_MACRO_NAME_25D1 0x25D1 // ◑ CIRCLE WITH RIGHT HALF BLACK
#define UC_MACRO_NAME_25D2 0x25D2 // ◒ CIRCLE WITH LOWER HALF BLACK
#define UC_MACRO_NAME_25D3 0x25D3 // ◓ CIRCLE WITH UPPER HALF BLACK
#define UC_MACRO_NAME_25D4 0x25D4 // ◔ CIRCLE WITH UPPER RIGHT QUADRANT BLACK
#define UC_MACRO_NAME_25D5 0x25D5 // ◕ CIRCLE WITH ALL BUT UPPER LEFT QUADRANT BLACK
#define UC_MACRO_NAME_25D6 0x25D6 // ◖ LEFT HALF BLACK CIRCLE
#define UC_MACRO_NAME_25D7 0x25D7 // ◗ RIGHT HALF BLACK CIRCLE
#define UC_MACRO_NAME_25D8 0x25D8 // ◘ INVERSE BULLET
#define UC_MACRO_NAME_25D9 0x25D9 // ◙ INVERSE WHITE CIRCLE
#define UC_MACRO_NAME_25DA 0x25DA // ◚ UPPER HALF INVERSE WHITE CIRCLE
#define UC_MACRO_NAME_25DB 0x25DB // ◛ LOWER HALF INVERSE WHITE CIRCLE
#define UC_MACRO_NAME_25DC 0x25DC // ◜ UPPER LEFT QUADRANT CIRCULAR ARC
#define UC_MACRO_NAME_25DD 0x25DD // ◝ UPPER RIGHT QUADRANT CIRCULAR ARC
#define UC_MACRO_NAME_25DE 0x25DE // ◞ LOWER RIGHT QUADRANT CIRCULAR ARC
#define UC_MACRO_NAME_25DF 0x25DF // ◟ LOWER LEFT QUADRANT CIRCULAR ARC
#define UC_MACRO_NAME_25E0 0x25E0 // ◠ UPPER HALF CIRCLE
#define UC_MACRO_NAME_25E1 0x25E1 // ◡ LOWER HALF CIRCLE
#define UC_MACRO_NAME_25E2 0x25E2 // ◢ BLACK LOWER RIGHT TRIANGLE
#define UC_MACRO_NAME_25E3 0x25E3 // ◣ BLACK LOWER LEFT TRIANGLE
#define UC_MACRO_NAME_25E4 0x25E4 // ◤ BLACK UPPER LEFT TRIANGLE
#define UC_MACRO_NAME_25E5 0x25E5 // ◥ BLACK UPPER RIGHT TRIANGLE
#define UC_MACRO_NAME_25E6 0x25E6 // ◦ WHITE BULLET
#define UC_MACRO_NAME_25E7 0x25E7 // ◧ SQUARE WITH LEFT HALF BLACK
#define UC_MACRO_NAME_25E8 0x25E8 // ◨ SQUARE WITH RIGHT HALF BLACK
#define UC_MACRO_NAME_25E9 0x25E9 // ◩ SQUARE WITH UPPER LEFT DIAGONAL HALF BLACK
#define UC_MACRO_NAME_25EA 0x25EA // ◪ SQUARE WITH LOWER RIGHT DIAGONAL HALF BLACK
#define UC_MACRO_NAME_25EB 0x25EB // ◫ WHITE SQUARE WITH VERTICAL BISECTING LINE
#define UC_MACRO_NAME_25EC 0x25EC // ◬ WHITE UP-POINTING TRIANGLE WITH DOT
#define UC_MACRO_NAME_25ED 0x25ED // ◭ UP-POINTING TRIANGLE WITH LEFT HALF BLACK
#define UC_MACRO_NAME_25EE 0x25EE // ◮ UP-POINTING TRIANGLE WITH RIGHT HALF BLACK
#define UC_MACRO_NAME_25EF 0x25EF // ◯ LARGE CIRCLE
#define UC_MACRO_NAME_25F0 0x25F0 // ◰ WHITE SQUARE WITH UPPER LEFT QUADRANT
#define UC_MACRO_NAME_25F1 0x25F1 // ◱ WHITE SQUARE WITH LOWER LEFT QUADRANT
#define UC_MACRO_NAME_25F2 0x25F2 // ◲ WHITE SQUARE WITH LOWER RIGHT QUADRANT
#define UC_MACRO_NAME_25F3 0x25F3 // ◳ WHITE SQUARE WITH UPPER RIGHT QUADRANT
#define UC_MACRO_NAME_25F4 0x25F4 // ◴ WHITE CIRCLE WITH UPPER LEFT QUADRANT
#define UC_MACRO_NAME_25F5 0x25F5 // ◵ WHITE CIRCLE WITH LOWER LEFT QUADRANT
#define UC_MACRO_NAME_25F6 0x25F6 // ◶ WHITE CIRCLE WITH LOWER RIGHT QUADRANT
#define UC_MACRO_NAME_25F7 0x25F7 // ◷ WHITE CIRCLE WITH UPPER RIGHT QUADRANT
#define UC_MACRO_NAME_25F8 0x25F8 // ◸ UPPER LEFT TRIANGLE
#define UC_MACRO_NAME_25F9 0x25F9 // ◹ UPPER RIGHT TRIANGLE
#define UC_MACRO_NAME_25FA 0x25FA // ◺ LOWER LEFT TRIANGLE
#define UC_MACRO_NAME_25FB 0x25FB // ◻ WHITE MEDIUM SQUARE
#define UC_MACRO_NAME_25FC 0x25FC // ◼ BLACK MEDIUM SQUARE
#define UC_MACRO_NAME_25FD 0x25FD // ◽ WHITE MEDIUM SMALL SQUARE
#define UC_MACRO_NAME_25FE 0x25FE // ◾ BLACK MEDIUM SMALL SQUARE
#define UC_MACRO_NAME_25FF 0x25FF // ◿ LOWER RIGHT TRIANGLE


#endif // UC_H_GEOMETRIC_SHAPES
