/*
 * Unicode Block: Greek and Coptic
 * Range: U+0370..U+03FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_GREEK_AND_COPTIC
#define UC_H_GREEK_AND_COPTIC

#define UC_MACRO_NAME_370 0x0370 // Ͱ GREEK CAPITAL LETTER HETA
#define UC_MACRO_NAME_371 0x0371 // ͱ GREEK SMALL LETTER HETA
#define UC_MACRO_NAME_372 0x0372 // Ͳ GREEK CAPITAL LETTER ARCHAIC SAMPI
#define UC_MACRO_NAME_373 0x0373 // ͳ GREEK SMALL LETTER ARCHAIC SAMPI
#define UC_MACRO_NAME_374 0x0374 // ʹ GREEK NUMERAL SIGN
#define UC_MACRO_NAME_375 0x0375 // ͵ GREEK LOWER NUMERAL SIGN
#define UC_MACRO_NAME_376 0x0376 // Ͷ GREEK CAPITAL LETTER PAMPHYLIAN DIGAMMA
#define UC_MACRO_NAME_377 0x0377 // ͷ GREEK SMALL LETTER PAMPHYLIAN DIGAMMA
#define UC_MACRO_NAME_37A 0x037A // ͺ GREEK YPOGEGRAMMENI
#define UC_MACRO_NAME_37B 0x037B // ͻ GREEK SMALL REVERSED LUNATE SIGMA SYMBOL
#define UC_MACRO_NAME_37C 0x037C // ͼ GREEK SMALL DOTTED LUNATE SIGMA SYMBOL
#define UC_MACRO_NAME_37D 0x037D // ͽ GREEK SMALL REVERSED DOTTED LUNATE SIGMA SYMBOL
#define UC_MACRO_NAME_37E 0x037E // ; GREEK QUESTION MARK
#define UC_MACRO_NAME_37F 0x037F // Ϳ GREEK CAPITAL LETTER YOT
#define UC_MACRO_NAME_384 0x0384 // ΄ GREEK TONOS
#define UC_MACRO_NAME_385 0x0385 // ΅ GREEK DIALYTIKA TONOS
#define UC_MACRO_NAME_386 0x0386 // Ά GREEK CAPITAL LETTER ALPHA WITH TONOS
#define UC_MACRO_NAME_387 0x0387 // · GREEK ANO TELEIA
#define UC_MACRO_NAME_388 0x0388 // Έ GREEK CAPITAL LETTER EPSILON WITH TONOS
#define UC_MACRO_NAME_389 0x0389 // Ή GREEK CAPITAL LETTER ETA WITH TONOS
#define UC_MACRO_NAME_38A 0x038A // Ί GREEK CAPITAL LETTER IOTA WITH TONOS
#define UC_MACRO_NAME_38C 0x038C // Ό GREEK CAPITAL LETTER OMICRON WITH TONOS
#define UC_MACRO_NAME_38E 0x038E // Ύ GREEK CAPITAL LETTER UPSILON WITH TONOS
#define UC_MACRO_NAME_38F 0x038F // Ώ GREEK CAPITAL LETTER OMEGA WITH TONOS
#define UC_MACRO_NAME_390 0x0390 // ΐ GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
#define UC_MACRO_NAME_391 0x0391 // Α GREEK CAPITAL LETTER ALPHA
#define UC_MACRO_NAME_392 0x0392 // Β GREEK CAPITAL LETTER BETA
#define UC_MACRO_NAME_393 0x0393 // Γ GREEK CAPITAL LETTER GAMMA
#define UC_MACRO_NAME_394 0x0394 // Δ GREEK CAPITAL LETTER DELTA
#define UC_MACRO_NAME_395 0x0395 // Ε GREEK CAPITAL LETTER EPSILON
#define UC_MACRO_NAME_396 0x0396 // Ζ GREEK CAPITAL LETTER ZETA
#define UC_MACRO_NAME_397 0x0397 // Η GREEK CAPITAL LETTER ETA
#define UC_MACRO_NAME_398 0x0398 // Θ GREEK CAPITAL LETTER THETA
#define UC_MACRO_NAME_399 0x0399 // Ι GREEK CAPITAL LETTER IOTA
#define UC_MACRO_NAME_39A 0x039A // Κ GREEK CAPITAL LETTER KAPPA
#define UC_MACRO_NAME_39B 0x039B // Λ GREEK CAPITAL LETTER LAMDA
#define UC_MACRO_NAME_39C 0x039C // Μ GREEK CAPITAL LETTER MU
#define UC_MACRO_NAME_39D 0x039D // Ν GREEK CAPITAL LETTER NU
#define UC_MACRO_NAME_39E 0x039E // Ξ GREEK CAPITAL LETTER XI
#define UC_MACRO_NAME_39F 0x039F // Ο GREEK CAPITAL LETTER OMICRON
#define UC_MACRO_NAME_3A0 0x03A0 // Π GREEK CAPITAL LETTER PI
#define UC_MACRO_NAME_3A1 0x03A1 // Ρ GREEK CAPITAL LETTER RHO
#define UC_MACRO_NAME_3A3 0x03A3 // Σ GREEK CAPITAL LETTER SIGMA
#define UC_MACRO_NAME_3A4 0x03A4 // Τ GREEK CAPITAL LETTER TAU
#define UC_MACRO_NAME_3A5 0x03A5 // Υ GREEK CAPITAL LETTER UPSILON
#define UC_MACRO_NAME_3A6 0x03A6 // Φ GREEK CAPITAL LETTER PHI
#define UC_MACRO_NAME_3A7 0x03A7 // Χ GREEK CAPITAL LETTER CHI
#define UC_MACRO_NAME_3A8 0x03A8 // Ψ GREEK CAPITAL LETTER PSI
#define UC_MACRO_NAME_3A9 0x03A9 // Ω GREEK CAPITAL LETTER OMEGA
#define UC_MACRO_NAME_3AA 0x03AA // Ϊ GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
#define UC_MACRO_NAME_3AB 0x03AB // Ϋ GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
#define UC_MACRO_NAME_3AC 0x03AC // ά GREEK SMALL LETTER ALPHA WITH TONOS
#define UC_MACRO_NAME_3AD 0x03AD // έ GREEK SMALL LETTER EPSILON WITH TONOS
#define UC_MACRO_NAME_3AE 0x03AE // ή GREEK SMALL LETTER ETA WITH TONOS
#define UC_MACRO_NAME_3AF 0x03AF // ί GREEK SMALL LETTER IOTA WITH TONOS
#define UC_MACRO_NAME_3B0 0x03B0 // ΰ GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
#define UC_MACRO_NAME_3B1 0x03B1 // α GREEK SMALL LETTER ALPHA
#define UC_MACRO_NAME_3B2 0x03B2 // β GREEK SMALL LETTER BETA
#define UC_MACRO_NAME_3B3 0x03B3 // γ GREEK SMALL LETTER GAMMA
#define UC_MACRO_NAME_3B4 0x03B4 // δ GREEK SMALL LETTER DELTA
#define UC_MACRO_NAME_3B5 0x03B5 // ε GREEK SMALL LETTER EPSILON
#define UC_MACRO_NAME_3B6 0x03B6 // ζ GREEK SMALL LETTER ZETA
#define UC_MACRO_NAME_3B7 0x03B7 // η GREEK SMALL LETTER ETA
#define UC_MACRO_NAME_3B8 0x03B8 // θ GREEK SMALL LETTER THETA
#define UC_MACRO_NAME_3B9 0x03B9 // ι GREEK SMALL LETTER IOTA
#define UC_MACRO_NAME_3BA 0x03BA // κ GREEK SMALL LETTER KAPPA
#define UC_MACRO_NAME_3BB 0x03BB // λ GREEK SMALL LETTER LAMDA
#define UC_MACRO_NAME_3BC 0x03BC // μ GREEK SMALL LETTER MU
#define UC_MACRO_NAME_3BD 0x03BD // ν GREEK SMALL LETTER NU
#define UC_MACRO_NAME_3BE 0x03BE // ξ GREEK SMALL LETTER XI
#define UC_MACRO_NAME_3BF 0x03BF // ο GREEK SMALL LETTER OMICRON
#define UC_MACRO_NAME_3C0 0x03C0 // π GREEK SMALL LETTER PI
#define UC_MACRO_NAME_3C1 0x03C1 // ρ GREEK SMALL LETTER RHO
#define UC_MACRO_NAME_3C2 0x03C2 // ς GREEK SMALL LETTER FINAL SIGMA
#define UC_MACRO_NAME_3C3 0x03C3 // σ GREEK SMALL LETTER SIGMA
#define UC_MACRO_NAME_3C4 0x03C4 // τ GREEK SMALL LETTER TAU
#define UC_MACRO_NAME_3C5 0x03C5 // υ GREEK SMALL LETTER UPSILON
#define UC_MACRO_NAME_3C6 0x03C6 // φ GREEK SMALL LETTER PHI
#define UC_MACRO_NAME_3C7 0x03C7 // χ GREEK SMALL LETTER CHI
#define UC_MACRO_NAME_3C8 0x03C8 // ψ GREEK SMALL LETTER PSI
#define UC_MACRO_NAME_3C9 0x03C9 // ω GREEK SMALL LETTER OMEGA
#define UC_MACRO_NAME_3CA 0x03CA // ϊ GREEK SMALL LETTER IOTA WITH DIALYTIKA
#define UC_MACRO_NAME_3CB 0x03CB // ϋ GREEK SMALL LETTER UPSILON WITH DIALYTIKA
#define UC_MACRO_NAME_3CC 0x03CC // ό GREEK SMALL LETTER OMICRON WITH TONOS
#define UC_MACRO_NAME_3CD 0x03CD // ύ GREEK SMALL LETTER UPSILON WITH TONOS
#define UC_MACRO_NAME_3CE 0x03CE // ώ GREEK SMALL LETTER OMEGA WITH TONOS
#define UC_MACRO_NAME_3CF 0x03CF // Ϗ GREEK CAPITAL KAI SYMBOL
#define UC_MACRO_NAME_3D0 0x03D0 // ϐ GREEK BETA SYMBOL
#define UC_MACRO_NAME_3D1 0x03D1 // ϑ GREEK THETA SYMBOL
#define UC_MACRO_NAME_3D2 0x03D2 // ϒ GREEK UPSILON WITH HOOK SYMBOL
#define UC_MACRO_NAME_3D3 0x03D3 // ϓ GREEK UPSILON WITH ACUTE AND HOOK SYMBOL
#define UC_MACRO_NAME_3D4 0x03D4 // ϔ GREEK UPSILON WITH DIAERESIS AND HOOK SYMBOL
#define UC_MACRO_NAME_3D5 0x03D5 // ϕ GREEK PHI SYMBOL
#define UC_MACRO_NAME_3D6 0x03D6 // ϖ GREEK PI SYMBOL
#define UC_MACRO_NAME_3D7 0x03D7 // ϗ GREEK KAI SYMBOL
#define UC_MACRO_NAME_3D8 0x03D8 // Ϙ GREEK LETTER ARCHAIC KOPPA
#define UC_MACRO_NAME_3D9 0x03D9 // ϙ GREEK SMALL LETTER ARCHAIC KOPPA
#define UC_MACRO_NAME_3DA 0x03DA // Ϛ GREEK LETTER STIGMA
#define UC_MACRO_NAME_3DB 0x03DB // ϛ GREEK SMALL LETTER STIGMA
#define UC_MACRO_NAME_3DC 0x03DC // Ϝ GREEK LETTER DIGAMMA
#define UC_MACRO_NAME_3DD 0x03DD // ϝ GREEK SMALL LETTER DIGAMMA
#define UC_MACRO_NAME_3DE 0x03DE // Ϟ GREEK LETTER KOPPA
#define UC_MACRO_NAME_3DF 0x03DF // ϟ GREEK SMALL LETTER KOPPA
#define UC_MACRO_NAME_3E0 0x03E0 // Ϡ GREEK LETTER SAMPI
#define UC_MACRO_NAME_3E1 0x03E1 // ϡ GREEK SMALL LETTER SAMPI
#define UC_MACRO_NAME_3E2 0x03E2 // Ϣ COPTIC CAPITAL LETTER SHEI
#define UC_MACRO_NAME_3E3 0x03E3 // ϣ COPTIC SMALL LETTER SHEI
#define UC_MACRO_NAME_3E4 0x03E4 // Ϥ COPTIC CAPITAL LETTER FEI
#define UC_MACRO_NAME_3E5 0x03E5 // ϥ COPTIC SMALL LETTER FEI
#define UC_MACRO_NAME_3E6 0x03E6 // Ϧ COPTIC CAPITAL LETTER KHEI
#define UC_MACRO_NAME_3E7 0x03E7 // ϧ COPTIC SMALL LETTER KHEI
#define UC_MACRO_NAME_3E8 0x03E8 // Ϩ COPTIC CAPITAL LETTER HORI
#define UC_MACRO_NAME_3E9 0x03E9 // ϩ COPTIC SMALL LETTER HORI
#define UC_MACRO_NAME_3EA 0x03EA // Ϫ COPTIC CAPITAL LETTER GANGIA
#define UC_MACRO_NAME_3EB 0x03EB // ϫ COPTIC SMALL LETTER GANGIA
#define UC_MACRO_NAME_3EC 0x03EC // Ϭ COPTIC CAPITAL LETTER SHIMA
#define UC_MACRO_NAME_3ED 0x03ED // ϭ COPTIC SMALL LETTER SHIMA
#define UC_MACRO_NAME_3EE 0x03EE // Ϯ COPTIC CAPITAL LETTER DEI
#define UC_MACRO_NAME_3EF 0x03EF // ϯ COPTIC SMALL LETTER DEI
#define UC_MACRO_NAME_3F0 0x03F0 // ϰ GREEK KAPPA SYMBOL
#define UC_MACRO_NAME_3F1 0x03F1 // ϱ GREEK RHO SYMBOL
#define UC_MACRO_NAME_3F2 0x03F2 // ϲ GREEK LUNATE SIGMA SYMBOL
#define UC_MACRO_NAME_3F3 0x03F3 // ϳ GREEK LETTER YOT
#define UC_MACRO_NAME_3F4 0x03F4 // ϴ GREEK CAPITAL THETA SYMBOL
#define UC_MACRO_NAME_3F5 0x03F5 // ϵ GREEK LUNATE EPSILON SYMBOL
#define UC_MACRO_NAME_3F6 0x03F6 // ϶ GREEK REVERSED LUNATE EPSILON SYMBOL
#define UC_MACRO_NAME_3F7 0x03F7 // Ϸ GREEK CAPITAL LETTER SHO
#define UC_MACRO_NAME_3F8 0x03F8 // ϸ GREEK SMALL LETTER SHO
#define UC_MACRO_NAME_3F9 0x03F9 // Ϲ GREEK CAPITAL LUNATE SIGMA SYMBOL
#define UC_MACRO_NAME_3FA 0x03FA // Ϻ GREEK CAPITAL LETTER SAN
#define UC_MACRO_NAME_3FB 0x03FB // ϻ GREEK SMALL LETTER SAN
#define UC_MACRO_NAME_3FC 0x03FC // ϼ GREEK RHO WITH STROKE SYMBOL
#define UC_MACRO_NAME_3FD 0x03FD // Ͻ GREEK CAPITAL REVERSED LUNATE SIGMA SYMBOL
#define UC_MACRO_NAME_3FE 0x03FE // Ͼ GREEK CAPITAL DOTTED LUNATE SIGMA SYMBOL
#define UC_MACRO_NAME_3FF 0x03FF // Ͽ GREEK CAPITAL REVERSED DOTTED LUNATE SIGMA SYMBOL


#endif // UC_H_GREEK_AND_COPTIC
