/*
 * Unicode Block: Gurmukhi
 * Range: U+0A00..U+0A7F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Gurmukhī ( Punjabi : ਗੁਰਮੁਖੀ , Shahmukhi : گُرمُکھی ) is an abugida
 * developed from the Laṇḍā scripts , standardized and used by the second
 * Sikh guru , Guru Angad (1504–1552). Commonly regarded as a Sikh
 * script, Gurmukhi is used in Punjab, India as the official script of
 * the Punjabi language .
 * The primary scripture of Sikhism , the Guru Granth Sahib , is written
 * in Gurmukhī, in various dialects and languages often subsumed under
 * the generic title Sant Bhasha or "saint language", in addition to
 * other languages like Persian and various phases of Indo-Aryan
 * languages.
 *
 */
#ifndef UC_H_GURMUKHI
#define UC_H_GURMUKHI

#define UC_MACRO_NAME_A01 0x0A01 // ਁ GURMUKHI SIGN ADAK BINDI
#define UC_MACRO_NAME_A02 0x0A02 // ਂ GURMUKHI SIGN BINDI
#define UC_MACRO_NAME_A03 0x0A03 // ਃ GURMUKHI SIGN VISARGA
#define UC_MACRO_NAME_A05 0x0A05 // ਅ GURMUKHI LETTER A
#define UC_MACRO_NAME_A06 0x0A06 // ਆ GURMUKHI LETTER AA
#define UC_MACRO_NAME_A07 0x0A07 // ਇ GURMUKHI LETTER I
#define UC_MACRO_NAME_A08 0x0A08 // ਈ GURMUKHI LETTER II
#define UC_MACRO_NAME_A09 0x0A09 // ਉ GURMUKHI LETTER U
#define UC_MACRO_NAME_A0A 0x0A0A // ਊ GURMUKHI LETTER UU
#define UC_MACRO_NAME_A0F 0x0A0F // ਏ GURMUKHI LETTER EE
#define UC_MACRO_NAME_A10 0x0A10 // ਐ GURMUKHI LETTER AI
#define UC_MACRO_NAME_A13 0x0A13 // ਓ GURMUKHI LETTER OO
#define UC_MACRO_NAME_A14 0x0A14 // ਔ GURMUKHI LETTER AU
#define UC_MACRO_NAME_A15 0x0A15 // ਕ GURMUKHI LETTER KA
#define UC_MACRO_NAME_A16 0x0A16 // ਖ GURMUKHI LETTER KHA
#define UC_MACRO_NAME_A17 0x0A17 // ਗ GURMUKHI LETTER GA
#define UC_MACRO_NAME_A18 0x0A18 // ਘ GURMUKHI LETTER GHA
#define UC_MACRO_NAME_A19 0x0A19 // ਙ GURMUKHI LETTER NGA
#define UC_MACRO_NAME_A1A 0x0A1A // ਚ GURMUKHI LETTER CA
#define UC_MACRO_NAME_A1B 0x0A1B // ਛ GURMUKHI LETTER CHA
#define UC_MACRO_NAME_A1C 0x0A1C // ਜ GURMUKHI LETTER JA
#define UC_MACRO_NAME_A1D 0x0A1D // ਝ GURMUKHI LETTER JHA
#define UC_MACRO_NAME_A1E 0x0A1E // ਞ GURMUKHI LETTER NYA
#define UC_MACRO_NAME_A1F 0x0A1F // ਟ GURMUKHI LETTER TTA
#define UC_MACRO_NAME_A20 0x0A20 // ਠ GURMUKHI LETTER TTHA
#define UC_MACRO_NAME_A21 0x0A21 // ਡ GURMUKHI LETTER DDA
#define UC_MACRO_NAME_A22 0x0A22 // ਢ GURMUKHI LETTER DDHA
#define UC_MACRO_NAME_A23 0x0A23 // ਣ GURMUKHI LETTER NNA
#define UC_MACRO_NAME_A24 0x0A24 // ਤ GURMUKHI LETTER TA
#define UC_MACRO_NAME_A25 0x0A25 // ਥ GURMUKHI LETTER THA
#define UC_MACRO_NAME_A26 0x0A26 // ਦ GURMUKHI LETTER DA
#define UC_MACRO_NAME_A27 0x0A27 // ਧ GURMUKHI LETTER DHA
#define UC_MACRO_NAME_A28 0x0A28 // ਨ GURMUKHI LETTER NA
#define UC_MACRO_NAME_A2A 0x0A2A // ਪ GURMUKHI LETTER PA
#define UC_MACRO_NAME_A2B 0x0A2B // ਫ GURMUKHI LETTER PHA
#define UC_MACRO_NAME_A2C 0x0A2C // ਬ GURMUKHI LETTER BA
#define UC_MACRO_NAME_A2D 0x0A2D // ਭ GURMUKHI LETTER BHA
#define UC_MACRO_NAME_A2E 0x0A2E // ਮ GURMUKHI LETTER MA
#define UC_MACRO_NAME_A2F 0x0A2F // ਯ GURMUKHI LETTER YA
#define UC_MACRO_NAME_A30 0x0A30 // ਰ GURMUKHI LETTER RA
#define UC_MACRO_NAME_A32 0x0A32 // ਲ GURMUKHI LETTER LA
#define UC_MACRO_NAME_A33 0x0A33 // ਲ਼ GURMUKHI LETTER LLA
#define UC_MACRO_NAME_A35 0x0A35 // ਵ GURMUKHI LETTER VA
#define UC_MACRO_NAME_A36 0x0A36 // ਸ਼ GURMUKHI LETTER SHA
#define UC_MACRO_NAME_A38 0x0A38 // ਸ GURMUKHI LETTER SA
#define UC_MACRO_NAME_A39 0x0A39 // ਹ GURMUKHI LETTER HA
#define UC_MACRO_NAME_A3C 0x0A3C // ਼ GURMUKHI SIGN NUKTA
#define UC_MACRO_NAME_A3E 0x0A3E // ਾ GURMUKHI VOWEL SIGN AA
#define UC_MACRO_NAME_A3F 0x0A3F // ਿ GURMUKHI VOWEL SIGN I
#define UC_MACRO_NAME_A40 0x0A40 // ੀ GURMUKHI VOWEL SIGN II
#define UC_MACRO_NAME_A41 0x0A41 // ੁ GURMUKHI VOWEL SIGN U
#define UC_MACRO_NAME_A42 0x0A42 // ੂ GURMUKHI VOWEL SIGN UU
#define UC_MACRO_NAME_A47 0x0A47 // ੇ GURMUKHI VOWEL SIGN EE
#define UC_MACRO_NAME_A48 0x0A48 // ੈ GURMUKHI VOWEL SIGN AI
#define UC_MACRO_NAME_A4B 0x0A4B // ੋ GURMUKHI VOWEL SIGN OO
#define UC_MACRO_NAME_A4C 0x0A4C // ੌ GURMUKHI VOWEL SIGN AU
#define UC_MACRO_NAME_A4D 0x0A4D // ੍ GURMUKHI SIGN VIRAMA
#define UC_MACRO_NAME_A51 0x0A51 // ੑ GURMUKHI SIGN UDAAT
#define UC_MACRO_NAME_A59 0x0A59 // ਖ਼ GURMUKHI LETTER KHHA
#define UC_MACRO_NAME_A5A 0x0A5A // ਗ਼ GURMUKHI LETTER GHHA
#define UC_MACRO_NAME_A5B 0x0A5B // ਜ਼ GURMUKHI LETTER ZA
#define UC_MACRO_NAME_A5C 0x0A5C // ੜ GURMUKHI LETTER RRA
#define UC_MACRO_NAME_A5E 0x0A5E // ਫ਼ GURMUKHI LETTER FA
#define UC_MACRO_NAME_A66 0x0A66 // ੦ GURMUKHI DIGIT ZERO
#define UC_MACRO_NAME_A67 0x0A67 // ੧ GURMUKHI DIGIT ONE
#define UC_MACRO_NAME_A68 0x0A68 // ੨ GURMUKHI DIGIT TWO
#define UC_MACRO_NAME_A69 0x0A69 // ੩ GURMUKHI DIGIT THREE
#define UC_MACRO_NAME_A6A 0x0A6A // ੪ GURMUKHI DIGIT FOUR
#define UC_MACRO_NAME_A6B 0x0A6B // ੫ GURMUKHI DIGIT FIVE
#define UC_MACRO_NAME_A6C 0x0A6C // ੬ GURMUKHI DIGIT SIX
#define UC_MACRO_NAME_A6D 0x0A6D // ੭ GURMUKHI DIGIT SEVEN
#define UC_MACRO_NAME_A6E 0x0A6E // ੮ GURMUKHI DIGIT EIGHT
#define UC_MACRO_NAME_A6F 0x0A6F // ੯ GURMUKHI DIGIT NINE
#define UC_MACRO_NAME_A70 0x0A70 // ੰ GURMUKHI TIPPI
#define UC_MACRO_NAME_A71 0x0A71 // ੱ GURMUKHI ADDAK
#define UC_MACRO_NAME_A72 0x0A72 // ੲ GURMUKHI IRI
#define UC_MACRO_NAME_A73 0x0A73 // ੳ GURMUKHI URA
#define UC_MACRO_NAME_A74 0x0A74 // ੴ GURMUKHI EK ONKAR
#define UC_MACRO_NAME_A75 0x0A75 // ੵ GURMUKHI SIGN YAKASH
#define UC_MACRO_NAME_A76 0x0A76 // ੶ GURMUKHI ABBREVIATION SIGN


#endif // UC_H_GURMUKHI
