/*
 * Unicode Block: Georgian Supplement
 * Range: U+2D00..U+2D2F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Georgian Supplement is a Unicode block containing characters for the
 * ecclesiastical form of the Georgian script, Nuskhuri ( Georgian :
 * ნუსხური ). To write the full ecclesiastical Khutsuri orthography, the
 * Asomtavruli capitals encoded in the Georgian block.
 * The following Unicode-related documents record the purpose and process
 * of defining specific characters in the Georgian Supplement block:
 *
 */
#ifndef UC_H_GEORGIAN_SUPPLEMENT
#define UC_H_GEORGIAN_SUPPLEMENT

#define UC_MACRO_NAME_2D00 0x2D00 // ⴀ GEORGIAN SMALL LETTER AN
#define UC_MACRO_NAME_2D01 0x2D01 // ⴁ GEORGIAN SMALL LETTER BAN
#define UC_MACRO_NAME_2D02 0x2D02 // ⴂ GEORGIAN SMALL LETTER GAN
#define UC_MACRO_NAME_2D03 0x2D03 // ⴃ GEORGIAN SMALL LETTER DON
#define UC_MACRO_NAME_2D04 0x2D04 // ⴄ GEORGIAN SMALL LETTER EN
#define UC_MACRO_NAME_2D05 0x2D05 // ⴅ GEORGIAN SMALL LETTER VIN
#define UC_MACRO_NAME_2D06 0x2D06 // ⴆ GEORGIAN SMALL LETTER ZEN
#define UC_MACRO_NAME_2D07 0x2D07 // ⴇ GEORGIAN SMALL LETTER TAN
#define UC_MACRO_NAME_2D08 0x2D08 // ⴈ GEORGIAN SMALL LETTER IN
#define UC_MACRO_NAME_2D09 0x2D09 // ⴉ GEORGIAN SMALL LETTER KAN
#define UC_MACRO_NAME_2D0A 0x2D0A // ⴊ GEORGIAN SMALL LETTER LAS
#define UC_MACRO_NAME_2D0B 0x2D0B // ⴋ GEORGIAN SMALL LETTER MAN
#define UC_MACRO_NAME_2D0C 0x2D0C // ⴌ GEORGIAN SMALL LETTER NAR
#define UC_MACRO_NAME_2D0D 0x2D0D // ⴍ GEORGIAN SMALL LETTER ON
#define UC_MACRO_NAME_2D0E 0x2D0E // ⴎ GEORGIAN SMALL LETTER PAR
#define UC_MACRO_NAME_2D0F 0x2D0F // ⴏ GEORGIAN SMALL LETTER ZHAR
#define UC_MACRO_NAME_2D10 0x2D10 // ⴐ GEORGIAN SMALL LETTER RAE
#define UC_MACRO_NAME_2D11 0x2D11 // ⴑ GEORGIAN SMALL LETTER SAN
#define UC_MACRO_NAME_2D12 0x2D12 // ⴒ GEORGIAN SMALL LETTER TAR
#define UC_MACRO_NAME_2D13 0x2D13 // ⴓ GEORGIAN SMALL LETTER UN
#define UC_MACRO_NAME_2D14 0x2D14 // ⴔ GEORGIAN SMALL LETTER PHAR
#define UC_MACRO_NAME_2D15 0x2D15 // ⴕ GEORGIAN SMALL LETTER KHAR
#define UC_MACRO_NAME_2D16 0x2D16 // ⴖ GEORGIAN SMALL LETTER GHAN
#define UC_MACRO_NAME_2D17 0x2D17 // ⴗ GEORGIAN SMALL LETTER QAR
#define UC_MACRO_NAME_2D18 0x2D18 // ⴘ GEORGIAN SMALL LETTER SHIN
#define UC_MACRO_NAME_2D19 0x2D19 // ⴙ GEORGIAN SMALL LETTER CHIN
#define UC_MACRO_NAME_2D1A 0x2D1A // ⴚ GEORGIAN SMALL LETTER CAN
#define UC_MACRO_NAME_2D1B 0x2D1B // ⴛ GEORGIAN SMALL LETTER JIL
#define UC_MACRO_NAME_2D1C 0x2D1C // ⴜ GEORGIAN SMALL LETTER CIL
#define UC_MACRO_NAME_2D1D 0x2D1D // ⴝ GEORGIAN SMALL LETTER CHAR
#define UC_MACRO_NAME_2D1E 0x2D1E // ⴞ GEORGIAN SMALL LETTER XAN
#define UC_MACRO_NAME_2D1F 0x2D1F // ⴟ GEORGIAN SMALL LETTER JHAN
#define UC_MACRO_NAME_2D20 0x2D20 // ⴠ GEORGIAN SMALL LETTER HAE
#define UC_MACRO_NAME_2D21 0x2D21 // ⴡ GEORGIAN SMALL LETTER HE
#define UC_MACRO_NAME_2D22 0x2D22 // ⴢ GEORGIAN SMALL LETTER HIE
#define UC_MACRO_NAME_2D23 0x2D23 // ⴣ GEORGIAN SMALL LETTER WE
#define UC_MACRO_NAME_2D24 0x2D24 // ⴤ GEORGIAN SMALL LETTER HAR
#define UC_MACRO_NAME_2D25 0x2D25 // ⴥ GEORGIAN SMALL LETTER HOE
#define UC_MACRO_NAME_2D27 0x2D27 // ⴧ GEORGIAN SMALL LETTER YN
#define UC_MACRO_NAME_2D2D 0x2D2D // ⴭ GEORGIAN SMALL LETTER AEN


#endif // UC_H_GEORGIAN_SUPPLEMENT
