/*
 * Unicode Block: Glagolitic
 * Range: U+2C00..U+2C5F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_GLAGOLITIC
#define UC_H_GLAGOLITIC

#define UC_MACRO_NAME_2C00 0x2C00 // Ⰰ GLAGOLITIC CAPITAL LETTER AZU
#define UC_MACRO_NAME_2C01 0x2C01 // Ⰱ GLAGOLITIC CAPITAL LETTER BUKY
#define UC_MACRO_NAME_2C02 0x2C02 // Ⰲ GLAGOLITIC CAPITAL LETTER VEDE
#define UC_MACRO_NAME_2C03 0x2C03 // Ⰳ GLAGOLITIC CAPITAL LETTER GLAGOLI
#define UC_MACRO_NAME_2C04 0x2C04 // Ⰴ GLAGOLITIC CAPITAL LETTER DOBRO
#define UC_MACRO_NAME_2C05 0x2C05 // Ⰵ GLAGOLITIC CAPITAL LETTER YESTU
#define UC_MACRO_NAME_2C06 0x2C06 // Ⰶ GLAGOLITIC CAPITAL LETTER ZHIVETE
#define UC_MACRO_NAME_2C07 0x2C07 // Ⰷ GLAGOLITIC CAPITAL LETTER DZELO
#define UC_MACRO_NAME_2C08 0x2C08 // Ⰸ GLAGOLITIC CAPITAL LETTER ZEMLJA
#define UC_MACRO_NAME_2C09 0x2C09 // Ⰹ GLAGOLITIC CAPITAL LETTER IZHE
#define UC_MACRO_NAME_2C0A 0x2C0A // Ⰺ GLAGOLITIC CAPITAL LETTER INITIAL IZHE
#define UC_MACRO_NAME_2C0B 0x2C0B // Ⰻ GLAGOLITIC CAPITAL LETTER I
#define UC_MACRO_NAME_2C0C 0x2C0C // Ⰼ GLAGOLITIC CAPITAL LETTER DJERVI
#define UC_MACRO_NAME_2C0D 0x2C0D // Ⰽ GLAGOLITIC CAPITAL LETTER KAKO
#define UC_MACRO_NAME_2C0E 0x2C0E // Ⰾ GLAGOLITIC CAPITAL LETTER LJUDIJE
#define UC_MACRO_NAME_2C0F 0x2C0F // Ⰿ GLAGOLITIC CAPITAL LETTER MYSLITE
#define UC_MACRO_NAME_2C10 0x2C10 // Ⱀ GLAGOLITIC CAPITAL LETTER NASHI
#define UC_MACRO_NAME_2C11 0x2C11 // Ⱁ GLAGOLITIC CAPITAL LETTER ONU
#define UC_MACRO_NAME_2C12 0x2C12 // Ⱂ GLAGOLITIC CAPITAL LETTER POKOJI
#define UC_MACRO_NAME_2C13 0x2C13 // Ⱃ GLAGOLITIC CAPITAL LETTER RITSI
#define UC_MACRO_NAME_2C14 0x2C14 // Ⱄ GLAGOLITIC CAPITAL LETTER SLOVO
#define UC_MACRO_NAME_2C15 0x2C15 // Ⱅ GLAGOLITIC CAPITAL LETTER TVRIDO
#define UC_MACRO_NAME_2C16 0x2C16 // Ⱆ GLAGOLITIC CAPITAL LETTER UKU
#define UC_MACRO_NAME_2C17 0x2C17 // Ⱇ GLAGOLITIC CAPITAL LETTER FRITU
#define UC_MACRO_NAME_2C18 0x2C18 // Ⱈ GLAGOLITIC CAPITAL LETTER HERU
#define UC_MACRO_NAME_2C19 0x2C19 // Ⱉ GLAGOLITIC CAPITAL LETTER OTU
#define UC_MACRO_NAME_2C1A 0x2C1A // Ⱊ GLAGOLITIC CAPITAL LETTER PE
#define UC_MACRO_NAME_2C1B 0x2C1B // Ⱋ GLAGOLITIC CAPITAL LETTER SHTA
#define UC_MACRO_NAME_2C1C 0x2C1C // Ⱌ GLAGOLITIC CAPITAL LETTER TSI
#define UC_MACRO_NAME_2C1D 0x2C1D // Ⱍ GLAGOLITIC CAPITAL LETTER CHRIVI
#define UC_MACRO_NAME_2C1E 0x2C1E // Ⱎ GLAGOLITIC CAPITAL LETTER SHA
#define UC_MACRO_NAME_2C1F 0x2C1F // Ⱏ GLAGOLITIC CAPITAL LETTER YERU
#define UC_MACRO_NAME_2C20 0x2C20 // Ⱐ GLAGOLITIC CAPITAL LETTER YERI
#define UC_MACRO_NAME_2C21 0x2C21 // Ⱑ GLAGOLITIC CAPITAL LETTER YATI
#define UC_MACRO_NAME_2C22 0x2C22 // Ⱒ GLAGOLITIC CAPITAL LETTER SPIDERY HA
#define UC_MACRO_NAME_2C23 0x2C23 // Ⱓ GLAGOLITIC CAPITAL LETTER YU
#define UC_MACRO_NAME_2C24 0x2C24 // Ⱔ GLAGOLITIC CAPITAL LETTER SMALL YUS
#define UC_MACRO_NAME_2C25 0x2C25 // Ⱕ GLAGOLITIC CAPITAL LETTER SMALL YUS WITH TAIL
#define UC_MACRO_NAME_2C26 0x2C26 // Ⱖ GLAGOLITIC CAPITAL LETTER YO
#define UC_MACRO_NAME_2C27 0x2C27 // Ⱗ GLAGOLITIC CAPITAL LETTER IOTATED SMALL YUS
#define UC_MACRO_NAME_2C28 0x2C28 // Ⱘ GLAGOLITIC CAPITAL LETTER BIG YUS
#define UC_MACRO_NAME_2C29 0x2C29 // Ⱙ GLAGOLITIC CAPITAL LETTER IOTATED BIG YUS
#define UC_MACRO_NAME_2C2A 0x2C2A // Ⱚ GLAGOLITIC CAPITAL LETTER FITA
#define UC_MACRO_NAME_2C2B 0x2C2B // Ⱛ GLAGOLITIC CAPITAL LETTER IZHITSA
#define UC_MACRO_NAME_2C2C 0x2C2C // Ⱜ GLAGOLITIC CAPITAL LETTER SHTAPIC
#define UC_MACRO_NAME_2C2D 0x2C2D // Ⱝ GLAGOLITIC CAPITAL LETTER TROKUTASTI A
#define UC_MACRO_NAME_2C2E 0x2C2E // Ⱞ GLAGOLITIC CAPITAL LETTER LATINATE MYSLITE
#define UC_MACRO_NAME_2C2F 0x2C2F // Ⱟ GLAGOLITIC CAPITAL LETTER CAUDATE CHRIVI
#define UC_MACRO_NAME_2C30 0x2C30 // ⰰ GLAGOLITIC SMALL LETTER AZU
#define UC_MACRO_NAME_2C31 0x2C31 // ⰱ GLAGOLITIC SMALL LETTER BUKY
#define UC_MACRO_NAME_2C32 0x2C32 // ⰲ GLAGOLITIC SMALL LETTER VEDE
#define UC_MACRO_NAME_2C33 0x2C33 // ⰳ GLAGOLITIC SMALL LETTER GLAGOLI
#define UC_MACRO_NAME_2C34 0x2C34 // ⰴ GLAGOLITIC SMALL LETTER DOBRO
#define UC_MACRO_NAME_2C35 0x2C35 // ⰵ GLAGOLITIC SMALL LETTER YESTU
#define UC_MACRO_NAME_2C36 0x2C36 // ⰶ GLAGOLITIC SMALL LETTER ZHIVETE
#define UC_MACRO_NAME_2C37 0x2C37 // ⰷ GLAGOLITIC SMALL LETTER DZELO
#define UC_MACRO_NAME_2C38 0x2C38 // ⰸ GLAGOLITIC SMALL LETTER ZEMLJA
#define UC_MACRO_NAME_2C39 0x2C39 // ⰹ GLAGOLITIC SMALL LETTER IZHE
#define UC_MACRO_NAME_2C3A 0x2C3A // ⰺ GLAGOLITIC SMALL LETTER INITIAL IZHE
#define UC_MACRO_NAME_2C3B 0x2C3B // ⰻ GLAGOLITIC SMALL LETTER I
#define UC_MACRO_NAME_2C3C 0x2C3C // ⰼ GLAGOLITIC SMALL LETTER DJERVI
#define UC_MACRO_NAME_2C3D 0x2C3D // ⰽ GLAGOLITIC SMALL LETTER KAKO
#define UC_MACRO_NAME_2C3E 0x2C3E // ⰾ GLAGOLITIC SMALL LETTER LJUDIJE
#define UC_MACRO_NAME_2C3F 0x2C3F // ⰿ GLAGOLITIC SMALL LETTER MYSLITE
#define UC_MACRO_NAME_2C40 0x2C40 // ⱀ GLAGOLITIC SMALL LETTER NASHI
#define UC_MACRO_NAME_2C41 0x2C41 // ⱁ GLAGOLITIC SMALL LETTER ONU
#define UC_MACRO_NAME_2C42 0x2C42 // ⱂ GLAGOLITIC SMALL LETTER POKOJI
#define UC_MACRO_NAME_2C43 0x2C43 // ⱃ GLAGOLITIC SMALL LETTER RITSI
#define UC_MACRO_NAME_2C44 0x2C44 // ⱄ GLAGOLITIC SMALL LETTER SLOVO
#define UC_MACRO_NAME_2C45 0x2C45 // ⱅ GLAGOLITIC SMALL LETTER TVRIDO
#define UC_MACRO_NAME_2C46 0x2C46 // ⱆ GLAGOLITIC SMALL LETTER UKU
#define UC_MACRO_NAME_2C47 0x2C47 // ⱇ GLAGOLITIC SMALL LETTER FRITU
#define UC_MACRO_NAME_2C48 0x2C48 // ⱈ GLAGOLITIC SMALL LETTER HERU
#define UC_MACRO_NAME_2C49 0x2C49 // ⱉ GLAGOLITIC SMALL LETTER OTU
#define UC_MACRO_NAME_2C4A 0x2C4A // ⱊ GLAGOLITIC SMALL LETTER PE
#define UC_MACRO_NAME_2C4B 0x2C4B // ⱋ GLAGOLITIC SMALL LETTER SHTA
#define UC_MACRO_NAME_2C4C 0x2C4C // ⱌ GLAGOLITIC SMALL LETTER TSI
#define UC_MACRO_NAME_2C4D 0x2C4D // ⱍ GLAGOLITIC SMALL LETTER CHRIVI
#define UC_MACRO_NAME_2C4E 0x2C4E // ⱎ GLAGOLITIC SMALL LETTER SHA
#define UC_MACRO_NAME_2C4F 0x2C4F // ⱏ GLAGOLITIC SMALL LETTER YERU
#define UC_MACRO_NAME_2C50 0x2C50 // ⱐ GLAGOLITIC SMALL LETTER YERI
#define UC_MACRO_NAME_2C51 0x2C51 // ⱑ GLAGOLITIC SMALL LETTER YATI
#define UC_MACRO_NAME_2C52 0x2C52 // ⱒ GLAGOLITIC SMALL LETTER SPIDERY HA
#define UC_MACRO_NAME_2C53 0x2C53 // ⱓ GLAGOLITIC SMALL LETTER YU
#define UC_MACRO_NAME_2C54 0x2C54 // ⱔ GLAGOLITIC SMALL LETTER SMALL YUS
#define UC_MACRO_NAME_2C55 0x2C55 // ⱕ GLAGOLITIC SMALL LETTER SMALL YUS WITH TAIL
#define UC_MACRO_NAME_2C56 0x2C56 // ⱖ GLAGOLITIC SMALL LETTER YO
#define UC_MACRO_NAME_2C57 0x2C57 // ⱗ GLAGOLITIC SMALL LETTER IOTATED SMALL YUS
#define UC_MACRO_NAME_2C58 0x2C58 // ⱘ GLAGOLITIC SMALL LETTER BIG YUS
#define UC_MACRO_NAME_2C59 0x2C59 // ⱙ GLAGOLITIC SMALL LETTER IOTATED BIG YUS
#define UC_MACRO_NAME_2C5A 0x2C5A // ⱚ GLAGOLITIC SMALL LETTER FITA
#define UC_MACRO_NAME_2C5B 0x2C5B // ⱛ GLAGOLITIC SMALL LETTER IZHITSA
#define UC_MACRO_NAME_2C5C 0x2C5C // ⱜ GLAGOLITIC SMALL LETTER SHTAPIC
#define UC_MACRO_NAME_2C5D 0x2C5D // ⱝ GLAGOLITIC SMALL LETTER TROKUTASTI A
#define UC_MACRO_NAME_2C5E 0x2C5E // ⱞ GLAGOLITIC SMALL LETTER LATINATE MYSLITE
#define UC_MACRO_NAME_2C5F 0x2C5F // ⱟ GLAGOLITIC SMALL LETTER CAUDATE CHRIVI


#endif // UC_H_GLAGOLITIC
