/*
 * Unicode Block: Hebrew
 * Range: U+0590..U+05FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_HEBREW
#define UC_H_HEBREW

#define UC_MACRO_NAME_591 0x0591 // ֑ HEBREW ACCENT ETNAHTA
#define UC_MACRO_NAME_592 0x0592 // ֒ HEBREW ACCENT SEGOL
#define UC_MACRO_NAME_593 0x0593 // ֓ HEBREW ACCENT SHALSHELET
#define UC_MACRO_NAME_594 0x0594 // ֔ HEBREW ACCENT ZAQEF QATAN
#define UC_MACRO_NAME_595 0x0595 // ֕ HEBREW ACCENT ZAQEF GADOL
#define UC_MACRO_NAME_596 0x0596 // ֖ HEBREW ACCENT TIPEHA
#define UC_MACRO_NAME_597 0x0597 // ֗ HEBREW ACCENT REVIA
#define UC_MACRO_NAME_598 0x0598 // ֘ HEBREW ACCENT ZARQA
#define UC_MACRO_NAME_599 0x0599 // ֙ HEBREW ACCENT PASHTA
#define UC_MACRO_NAME_59A 0x059A // ֚ HEBREW ACCENT YETIV
#define UC_MACRO_NAME_59B 0x059B // ֛ HEBREW ACCENT TEVIR
#define UC_MACRO_NAME_59C 0x059C // ֜ HEBREW ACCENT GERESH
#define UC_MACRO_NAME_59D 0x059D // ֝ HEBREW ACCENT GERESH MUQDAM
#define UC_MACRO_NAME_59E 0x059E // ֞ HEBREW ACCENT GERSHAYIM
#define UC_MACRO_NAME_59F 0x059F // ֟ HEBREW ACCENT QARNEY PARA
#define UC_MACRO_NAME_5A0 0x05A0 // ֠ HEBREW ACCENT TELISHA GEDOLA
#define UC_MACRO_NAME_5A1 0x05A1 // ֡ HEBREW ACCENT PAZER
#define UC_MACRO_NAME_5A2 0x05A2 // ֢ HEBREW ACCENT ATNAH HAFUKH
#define UC_MACRO_NAME_5A3 0x05A3 // ֣ HEBREW ACCENT MUNAH
#define UC_MACRO_NAME_5A4 0x05A4 // ֤ HEBREW ACCENT MAHAPAKH
#define UC_MACRO_NAME_5A5 0x05A5 // ֥ HEBREW ACCENT MERKHA
#define UC_MACRO_NAME_5A6 0x05A6 // ֦ HEBREW ACCENT MERKHA KEFULA
#define UC_MACRO_NAME_5A7 0x05A7 // ֧ HEBREW ACCENT DARGA
#define UC_MACRO_NAME_5A8 0x05A8 // ֨ HEBREW ACCENT QADMA
#define UC_MACRO_NAME_5A9 0x05A9 // ֩ HEBREW ACCENT TELISHA QETANA
#define UC_MACRO_NAME_5AA 0x05AA // ֪ HEBREW ACCENT YERAH BEN YOMO
#define UC_MACRO_NAME_5AB 0x05AB // ֫ HEBREW ACCENT OLE
#define UC_MACRO_NAME_5AC 0x05AC // ֬ HEBREW ACCENT ILUY
#define UC_MACRO_NAME_5AD 0x05AD // ֭ HEBREW ACCENT DEHI
#define UC_MACRO_NAME_5AE 0x05AE // ֮ HEBREW ACCENT ZINOR
#define UC_MACRO_NAME_5AF 0x05AF // ֯ HEBREW MARK MASORA CIRCLE
#define UC_MACRO_NAME_5B0 0x05B0 // ְ HEBREW POINT SHEVA
#define UC_MACRO_NAME_5B1 0x05B1 // ֱ HEBREW POINT HATAF SEGOL
#define UC_MACRO_NAME_5B2 0x05B2 // ֲ HEBREW POINT HATAF PATAH
#define UC_MACRO_NAME_5B3 0x05B3 // ֳ HEBREW POINT HATAF QAMATS
#define UC_MACRO_NAME_5B4 0x05B4 // ִ HEBREW POINT HIRIQ
#define UC_MACRO_NAME_5B5 0x05B5 // ֵ HEBREW POINT TSERE
#define UC_MACRO_NAME_5B6 0x05B6 // ֶ HEBREW POINT SEGOL
#define UC_MACRO_NAME_5B7 0x05B7 // ַ HEBREW POINT PATAH
#define UC_MACRO_NAME_5B8 0x05B8 // ָ HEBREW POINT QAMATS
#define UC_MACRO_NAME_5B9 0x05B9 // ֹ HEBREW POINT HOLAM
#define UC_MACRO_NAME_5BA 0x05BA // ֺ HEBREW POINT HOLAM HASER FOR VAV
#define UC_MACRO_NAME_5BB 0x05BB // ֻ HEBREW POINT QUBUTS
#define UC_MACRO_NAME_5BC 0x05BC // ּ HEBREW POINT DAGESH OR MAPIQ
#define UC_MACRO_NAME_5BD 0x05BD // ֽ HEBREW POINT METEG
#define UC_MACRO_NAME_5BE 0x05BE // ־ HEBREW PUNCTUATION MAQAF
#define UC_MACRO_NAME_5BF 0x05BF // ֿ HEBREW POINT RAFE
#define UC_MACRO_NAME_5C0 0x05C0 // ׀ HEBREW PUNCTUATION PASEQ
#define UC_MACRO_NAME_5C1 0x05C1 // ׁ HEBREW POINT SHIN DOT
#define UC_MACRO_NAME_5C2 0x05C2 // ׂ HEBREW POINT SIN DOT
#define UC_MACRO_NAME_5C3 0x05C3 // ׃ HEBREW PUNCTUATION SOF PASUQ
#define UC_MACRO_NAME_5C4 0x05C4 // ׄ HEBREW MARK UPPER DOT
#define UC_MACRO_NAME_5C5 0x05C5 // ׅ HEBREW MARK LOWER DOT
#define UC_MACRO_NAME_5C6 0x05C6 // ׆ HEBREW PUNCTUATION NUN HAFUKHA
#define UC_MACRO_NAME_5C7 0x05C7 // ׇ HEBREW POINT QAMATS QATAN
#define UC_MACRO_NAME_5D0 0x05D0 // א HEBREW LETTER ALEF
#define UC_MACRO_NAME_5D1 0x05D1 // ב HEBREW LETTER BET
#define UC_MACRO_NAME_5D2 0x05D2 // ג HEBREW LETTER GIMEL
#define UC_MACRO_NAME_5D3 0x05D3 // ד HEBREW LETTER DALET
#define UC_MACRO_NAME_5D4 0x05D4 // ה HEBREW LETTER HE
#define UC_MACRO_NAME_5D5 0x05D5 // ו HEBREW LETTER VAV
#define UC_MACRO_NAME_5D6 0x05D6 // ז HEBREW LETTER ZAYIN
#define UC_MACRO_NAME_5D7 0x05D7 // ח HEBREW LETTER HET
#define UC_MACRO_NAME_5D8 0x05D8 // ט HEBREW LETTER TET
#define UC_MACRO_NAME_5D9 0x05D9 // י HEBREW LETTER YOD
#define UC_MACRO_NAME_5DA 0x05DA // ך HEBREW LETTER FINAL KAF
#define UC_MACRO_NAME_5DB 0x05DB // כ HEBREW LETTER KAF
#define UC_MACRO_NAME_5DC 0x05DC // ל HEBREW LETTER LAMED
#define UC_MACRO_NAME_5DD 0x05DD // ם HEBREW LETTER FINAL MEM
#define UC_MACRO_NAME_5DE 0x05DE // מ HEBREW LETTER MEM
#define UC_MACRO_NAME_5DF 0x05DF // ן HEBREW LETTER FINAL NUN
#define UC_MACRO_NAME_5E0 0x05E0 // נ HEBREW LETTER NUN
#define UC_MACRO_NAME_5E1 0x05E1 // ס HEBREW LETTER SAMEKH
#define UC_MACRO_NAME_5E2 0x05E2 // ע HEBREW LETTER AYIN
#define UC_MACRO_NAME_5E3 0x05E3 // ף HEBREW LETTER FINAL PE
#define UC_MACRO_NAME_5E4 0x05E4 // פ HEBREW LETTER PE
#define UC_MACRO_NAME_5E5 0x05E5 // ץ HEBREW LETTER FINAL TSADI
#define UC_MACRO_NAME_5E6 0x05E6 // צ HEBREW LETTER TSADI
#define UC_MACRO_NAME_5E7 0x05E7 // ק HEBREW LETTER QOF
#define UC_MACRO_NAME_5E8 0x05E8 // ר HEBREW LETTER RESH
#define UC_MACRO_NAME_5E9 0x05E9 // ש HEBREW LETTER SHIN
#define UC_MACRO_NAME_5EA 0x05EA // ת HEBREW LETTER TAV
#define UC_MACRO_NAME_5EF 0x05EF // ׯ HEBREW YOD TRIANGLE
#define UC_MACRO_NAME_5F0 0x05F0 // װ HEBREW LIGATURE YIDDISH DOUBLE VAV
#define UC_MACRO_NAME_5F1 0x05F1 // ױ HEBREW LIGATURE YIDDISH VAV YOD
#define UC_MACRO_NAME_5F2 0x05F2 // ײ HEBREW LIGATURE YIDDISH DOUBLE YOD
#define UC_MACRO_NAME_5F3 0x05F3 // ׳ HEBREW PUNCTUATION GERESH
#define UC_MACRO_NAME_5F4 0x05F4 // ״ HEBREW PUNCTUATION GERSHAYIM


#endif // UC_H_HEBREW
