/*
 * Unicode Block: Hangul Jamo Extended-B
 * Range: U+D7B0..U+D7FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_HANGUL_JAMO_EXTENDED_B
#define UC_H_HANGUL_JAMO_EXTENDED_B

#define UC_MACRO_NAME_D7B0 0xD7B0 // ힰ HANGUL JUNGSEONG O-YEO
#define UC_MACRO_NAME_D7B1 0xD7B1 // ힱ HANGUL JUNGSEONG O-O-I
#define UC_MACRO_NAME_D7B2 0xD7B2 // ힲ HANGUL JUNGSEONG YO-A
#define UC_MACRO_NAME_D7B3 0xD7B3 // ힳ HANGUL JUNGSEONG YO-AE
#define UC_MACRO_NAME_D7B4 0xD7B4 // ힴ HANGUL JUNGSEONG YO-EO
#define UC_MACRO_NAME_D7B5 0xD7B5 // ힵ HANGUL JUNGSEONG U-YEO
#define UC_MACRO_NAME_D7B6 0xD7B6 // ힶ HANGUL JUNGSEONG U-I-I
#define UC_MACRO_NAME_D7B7 0xD7B7 // ힷ HANGUL JUNGSEONG YU-AE
#define UC_MACRO_NAME_D7B8 0xD7B8 // ힸ HANGUL JUNGSEONG YU-O
#define UC_MACRO_NAME_D7B9 0xD7B9 // ힹ HANGUL JUNGSEONG EU-A
#define UC_MACRO_NAME_D7BA 0xD7BA // ힺ HANGUL JUNGSEONG EU-EO
#define UC_MACRO_NAME_D7BB 0xD7BB // ힻ HANGUL JUNGSEONG EU-E
#define UC_MACRO_NAME_D7BC 0xD7BC // ힼ HANGUL JUNGSEONG EU-O
#define UC_MACRO_NAME_D7BD 0xD7BD // ힽ HANGUL JUNGSEONG I-YA-O
#define UC_MACRO_NAME_D7BE 0xD7BE // ힾ HANGUL JUNGSEONG I-YAE
#define UC_MACRO_NAME_D7BF 0xD7BF // ힿ HANGUL JUNGSEONG I-YEO
#define UC_MACRO_NAME_D7C0 0xD7C0 // ퟀ HANGUL JUNGSEONG I-YE
#define UC_MACRO_NAME_D7C1 0xD7C1 // ퟁ HANGUL JUNGSEONG I-O-I
#define UC_MACRO_NAME_D7C2 0xD7C2 // ퟂ HANGUL JUNGSEONG I-YO
#define UC_MACRO_NAME_D7C3 0xD7C3 // ퟃ HANGUL JUNGSEONG I-YU
#define UC_MACRO_NAME_D7C4 0xD7C4 // ퟄ HANGUL JUNGSEONG I-I
#define UC_MACRO_NAME_D7C5 0xD7C5 // ퟅ HANGUL JUNGSEONG ARAEA-A
#define UC_MACRO_NAME_D7C6 0xD7C6 // ퟆ HANGUL JUNGSEONG ARAEA-E
#define UC_MACRO_NAME_D7CB 0xD7CB // ퟋ HANGUL JONGSEONG NIEUN-RIEUL
#define UC_MACRO_NAME_D7CC 0xD7CC // ퟌ HANGUL JONGSEONG NIEUN-CHIEUCH
#define UC_MACRO_NAME_D7CD 0xD7CD // ퟍ HANGUL JONGSEONG SSANGTIKEUT
#define UC_MACRO_NAME_D7CE 0xD7CE // ퟎ HANGUL JONGSEONG SSANGTIKEUT-PIEUP
#define UC_MACRO_NAME_D7CF 0xD7CF // ퟏ HANGUL JONGSEONG TIKEUT-PIEUP
#define UC_MACRO_NAME_D7D0 0xD7D0 // ퟐ HANGUL JONGSEONG TIKEUT-SIOS
#define UC_MACRO_NAME_D7D1 0xD7D1 // ퟑ HANGUL JONGSEONG TIKEUT-SIOS-KIYEOK
#define UC_MACRO_NAME_D7D2 0xD7D2 // ퟒ HANGUL JONGSEONG TIKEUT-CIEUC
#define UC_MACRO_NAME_D7D3 0xD7D3 // ퟓ HANGUL JONGSEONG TIKEUT-CHIEUCH
#define UC_MACRO_NAME_D7D4 0xD7D4 // ퟔ HANGUL JONGSEONG TIKEUT-THIEUTH
#define UC_MACRO_NAME_D7D5 0xD7D5 // ퟕ HANGUL JONGSEONG RIEUL-SSANGKIYEOK
#define UC_MACRO_NAME_D7D6 0xD7D6 // ퟖ HANGUL JONGSEONG RIEUL-KIYEOK-HIEUH
#define UC_MACRO_NAME_D7D7 0xD7D7 // ퟗ HANGUL JONGSEONG SSANGRIEUL-KHIEUKH
#define UC_MACRO_NAME_D7D8 0xD7D8 // ퟘ HANGUL JONGSEONG RIEUL-MIEUM-HIEUH
#define UC_MACRO_NAME_D7D9 0xD7D9 // ퟙ HANGUL JONGSEONG RIEUL-PIEUP-TIKEUT
#define UC_MACRO_NAME_D7DA 0xD7DA // ퟚ HANGUL JONGSEONG RIEUL-PIEUP-PHIEUPH
#define UC_MACRO_NAME_D7DB 0xD7DB // ퟛ HANGUL JONGSEONG RIEUL-YESIEUNG
#define UC_MACRO_NAME_D7DC 0xD7DC // ퟜ HANGUL JONGSEONG RIEUL-YEORINHIEUH-HIEUH
#define UC_MACRO_NAME_D7DD 0xD7DD // ퟝ HANGUL JONGSEONG KAPYEOUNRIEUL
#define UC_MACRO_NAME_D7DE 0xD7DE // ퟞ HANGUL JONGSEONG MIEUM-NIEUN
#define UC_MACRO_NAME_D7DF 0xD7DF // ퟟ HANGUL JONGSEONG MIEUM-SSANGNIEUN
#define UC_MACRO_NAME_D7E0 0xD7E0 // ퟠ HANGUL JONGSEONG SSANGMIEUM
#define UC_MACRO_NAME_D7E1 0xD7E1 // ퟡ HANGUL JONGSEONG MIEUM-PIEUP-SIOS
#define UC_MACRO_NAME_D7E2 0xD7E2 // ퟢ HANGUL JONGSEONG MIEUM-CIEUC
#define UC_MACRO_NAME_D7E3 0xD7E3 // ퟣ HANGUL JONGSEONG PIEUP-TIKEUT
#define UC_MACRO_NAME_D7E4 0xD7E4 // ퟤ HANGUL JONGSEONG PIEUP-RIEUL-PHIEUPH
#define UC_MACRO_NAME_D7E5 0xD7E5 // ퟥ HANGUL JONGSEONG PIEUP-MIEUM
#define UC_MACRO_NAME_D7E6 0xD7E6 // ퟦ HANGUL JONGSEONG SSANGPIEUP
#define UC_MACRO_NAME_D7E7 0xD7E7 // ퟧ HANGUL JONGSEONG PIEUP-SIOS-TIKEUT
#define UC_MACRO_NAME_D7E8 0xD7E8 // ퟨ HANGUL JONGSEONG PIEUP-CIEUC
#define UC_MACRO_NAME_D7E9 0xD7E9 // ퟩ HANGUL JONGSEONG PIEUP-CHIEUCH
#define UC_MACRO_NAME_D7EA 0xD7EA // ퟪ HANGUL JONGSEONG SIOS-MIEUM
#define UC_MACRO_NAME_D7EB 0xD7EB // ퟫ HANGUL JONGSEONG SIOS-KAPYEOUNPIEUP
#define UC_MACRO_NAME_D7EC 0xD7EC // ퟬ HANGUL JONGSEONG SSANGSIOS-KIYEOK
#define UC_MACRO_NAME_D7ED 0xD7ED // ퟭ HANGUL JONGSEONG SSANGSIOS-TIKEUT
#define UC_MACRO_NAME_D7EE 0xD7EE // ퟮ HANGUL JONGSEONG SIOS-PANSIOS
#define UC_MACRO_NAME_D7EF 0xD7EF // ퟯ HANGUL JONGSEONG SIOS-CIEUC
#define UC_MACRO_NAME_D7F0 0xD7F0 // ퟰ HANGUL JONGSEONG SIOS-CHIEUCH
#define UC_MACRO_NAME_D7F1 0xD7F1 // ퟱ HANGUL JONGSEONG SIOS-THIEUTH
#define UC_MACRO_NAME_D7F2 0xD7F2 // ퟲ HANGUL JONGSEONG SIOS-HIEUH
#define UC_MACRO_NAME_D7F3 0xD7F3 // ퟳ HANGUL JONGSEONG PANSIOS-PIEUP
#define UC_MACRO_NAME_D7F4 0xD7F4 // ퟴ HANGUL JONGSEONG PANSIOS-KAPYEOUNPIEUP
#define UC_MACRO_NAME_D7F5 0xD7F5 // ퟵ HANGUL JONGSEONG YESIEUNG-MIEUM
#define UC_MACRO_NAME_D7F6 0xD7F6 // ퟶ HANGUL JONGSEONG YESIEUNG-HIEUH
#define UC_MACRO_NAME_D7F7 0xD7F7 // ퟷ HANGUL JONGSEONG CIEUC-PIEUP
#define UC_MACRO_NAME_D7F8 0xD7F8 // ퟸ HANGUL JONGSEONG CIEUC-SSANGPIEUP
#define UC_MACRO_NAME_D7F9 0xD7F9 // ퟹ HANGUL JONGSEONG SSANGCIEUC
#define UC_MACRO_NAME_D7FA 0xD7FA // ퟺ HANGUL JONGSEONG PHIEUPH-SIOS
#define UC_MACRO_NAME_D7FB 0xD7FB // ퟻ HANGUL JONGSEONG PHIEUPH-THIEUTH


#endif // UC_H_HANGUL_JAMO_EXTENDED_B
