/*
 * Unicode Block: Halfwidth and Fullwidth Forms
 * Range: U+FF00..U+FFEF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * In CJK (Chinese, Japanese, and Korean) computing, graphic characters
 * are traditionally classed into fullwidth and halfwidth characters.
 * Unlike monospaced fonts , a halfwidth character occupies half the
 * width of a fullwidth character, hence the name.
 * Halfwidth and Fullwidth Forms is also the name of a Unicode block
 * U+FF00–FFEF, provided so that older encodings containing both
 * halfwidth and fullwidth characters can have lossless translation to
 * and from Unicode.
 *
 */
#ifndef UC_H_HALFWIDTH_AND_FULLWIDTH_FORMS
#define UC_H_HALFWIDTH_AND_FULLWIDTH_FORMS

#define UC_MACRO_NAME_FF01 0xFF01 // ！ FULLWIDTH EXCLAMATION MARK
#define UC_MACRO_NAME_FF02 0xFF02 // ＂ FULLWIDTH QUOTATION MARK
#define UC_MACRO_NAME_FF03 0xFF03 // ＃ FULLWIDTH NUMBER SIGN
#define UC_MACRO_NAME_FF04 0xFF04 // ＄ FULLWIDTH DOLLAR SIGN
#define UC_MACRO_NAME_FF05 0xFF05 // ％ FULLWIDTH PERCENT SIGN
#define UC_MACRO_NAME_FF06 0xFF06 // ＆ FULLWIDTH AMPERSAND
#define UC_MACRO_NAME_FF07 0xFF07 // ＇ FULLWIDTH APOSTROPHE
#define UC_MACRO_NAME_FF08 0xFF08 // （ FULLWIDTH LEFT PARENTHESIS
#define UC_MACRO_NAME_FF09 0xFF09 // ） FULLWIDTH RIGHT PARENTHESIS
#define UC_MACRO_NAME_FF0A 0xFF0A // ＊ FULLWIDTH ASTERISK
#define UC_MACRO_NAME_FF0B 0xFF0B // ＋ FULLWIDTH PLUS SIGN
#define UC_MACRO_NAME_FF0C 0xFF0C // ， FULLWIDTH COMMA
#define UC_MACRO_NAME_FF0D 0xFF0D // － FULLWIDTH HYPHEN-MINUS
#define UC_MACRO_NAME_FF0E 0xFF0E // ． FULLWIDTH FULL STOP
#define UC_MACRO_NAME_FF0F 0xFF0F // ／ FULLWIDTH SOLIDUS
#define UC_MACRO_NAME_FF10 0xFF10 // ０ FULLWIDTH DIGIT ZERO
#define UC_MACRO_NAME_FF11 0xFF11 // １ FULLWIDTH DIGIT ONE
#define UC_MACRO_NAME_FF12 0xFF12 // ２ FULLWIDTH DIGIT TWO
#define UC_MACRO_NAME_FF13 0xFF13 // ３ FULLWIDTH DIGIT THREE
#define UC_MACRO_NAME_FF14 0xFF14 // ４ FULLWIDTH DIGIT FOUR
#define UC_MACRO_NAME_FF15 0xFF15 // ５ FULLWIDTH DIGIT FIVE
#define UC_MACRO_NAME_FF16 0xFF16 // ６ FULLWIDTH DIGIT SIX
#define UC_MACRO_NAME_FF17 0xFF17 // ７ FULLWIDTH DIGIT SEVEN
#define UC_MACRO_NAME_FF18 0xFF18 // ８ FULLWIDTH DIGIT EIGHT
#define UC_MACRO_NAME_FF19 0xFF19 // ９ FULLWIDTH DIGIT NINE
#define UC_MACRO_NAME_FF1A 0xFF1A // ： FULLWIDTH COLON
#define UC_MACRO_NAME_FF1B 0xFF1B // ； FULLWIDTH SEMICOLON
#define UC_MACRO_NAME_FF1C 0xFF1C // ＜ FULLWIDTH LESS-THAN SIGN
#define UC_MACRO_NAME_FF1D 0xFF1D // ＝ FULLWIDTH EQUALS SIGN
#define UC_MACRO_NAME_FF1E 0xFF1E // ＞ FULLWIDTH GREATER-THAN SIGN
#define UC_MACRO_NAME_FF1F 0xFF1F // ？ FULLWIDTH QUESTION MARK
#define UC_MACRO_NAME_FF20 0xFF20 // ＠ FULLWIDTH COMMERCIAL AT
#define UC_MACRO_NAME_FF21 0xFF21 // Ａ FULLWIDTH LATIN CAPITAL LETTER A
#define UC_MACRO_NAME_FF22 0xFF22 // Ｂ FULLWIDTH LATIN CAPITAL LETTER B
#define UC_MACRO_NAME_FF23 0xFF23 // Ｃ FULLWIDTH LATIN CAPITAL LETTER C
#define UC_MACRO_NAME_FF24 0xFF24 // Ｄ FULLWIDTH LATIN CAPITAL LETTER D
#define UC_MACRO_NAME_FF25 0xFF25 // Ｅ FULLWIDTH LATIN CAPITAL LETTER E
#define UC_MACRO_NAME_FF26 0xFF26 // Ｆ FULLWIDTH LATIN CAPITAL LETTER F
#define UC_MACRO_NAME_FF27 0xFF27 // Ｇ FULLWIDTH LATIN CAPITAL LETTER G
#define UC_MACRO_NAME_FF28 0xFF28 // Ｈ FULLWIDTH LATIN CAPITAL LETTER H
#define UC_MACRO_NAME_FF29 0xFF29 // Ｉ FULLWIDTH LATIN CAPITAL LETTER I
#define UC_MACRO_NAME_FF2A 0xFF2A // Ｊ FULLWIDTH LATIN CAPITAL LETTER J
#define UC_MACRO_NAME_FF2B 0xFF2B // Ｋ FULLWIDTH LATIN CAPITAL LETTER K
#define UC_MACRO_NAME_FF2C 0xFF2C // Ｌ FULLWIDTH LATIN CAPITAL LETTER L
#define UC_MACRO_NAME_FF2D 0xFF2D // Ｍ FULLWIDTH LATIN CAPITAL LETTER M
#define UC_MACRO_NAME_FF2E 0xFF2E // Ｎ FULLWIDTH LATIN CAPITAL LETTER N
#define UC_MACRO_NAME_FF2F 0xFF2F // Ｏ FULLWIDTH LATIN CAPITAL LETTER O
#define UC_MACRO_NAME_FF30 0xFF30 // Ｐ FULLWIDTH LATIN CAPITAL LETTER P
#define UC_MACRO_NAME_FF31 0xFF31 // Ｑ FULLWIDTH LATIN CAPITAL LETTER Q
#define UC_MACRO_NAME_FF32 0xFF32 // Ｒ FULLWIDTH LATIN CAPITAL LETTER R
#define UC_MACRO_NAME_FF33 0xFF33 // Ｓ FULLWIDTH LATIN CAPITAL LETTER S
#define UC_MACRO_NAME_FF34 0xFF34 // Ｔ FULLWIDTH LATIN CAPITAL LETTER T
#define UC_MACRO_NAME_FF35 0xFF35 // Ｕ FULLWIDTH LATIN CAPITAL LETTER U
#define UC_MACRO_NAME_FF36 0xFF36 // Ｖ FULLWIDTH LATIN CAPITAL LETTER V
#define UC_MACRO_NAME_FF37 0xFF37 // Ｗ FULLWIDTH LATIN CAPITAL LETTER W
#define UC_MACRO_NAME_FF38 0xFF38 // Ｘ FULLWIDTH LATIN CAPITAL LETTER X
#define UC_MACRO_NAME_FF39 0xFF39 // Ｙ FULLWIDTH LATIN CAPITAL LETTER Y
#define UC_MACRO_NAME_FF3A 0xFF3A // Ｚ FULLWIDTH LATIN CAPITAL LETTER Z
#define UC_MACRO_NAME_FF3B 0xFF3B // ［ FULLWIDTH LEFT SQUARE BRACKET
#define UC_MACRO_NAME_FF3C 0xFF3C // ＼ FULLWIDTH REVERSE SOLIDUS
#define UC_MACRO_NAME_FF3D 0xFF3D // ］ FULLWIDTH RIGHT SQUARE BRACKET
#define UC_MACRO_NAME_FF3E 0xFF3E // ＾ FULLWIDTH CIRCUMFLEX ACCENT
#define UC_MACRO_NAME_FF3F 0xFF3F // ＿ FULLWIDTH LOW LINE
#define UC_MACRO_NAME_FF40 0xFF40 // ｀ FULLWIDTH GRAVE ACCENT
#define UC_MACRO_NAME_FF41 0xFF41 // ａ FULLWIDTH LATIN SMALL LETTER A
#define UC_MACRO_NAME_FF42 0xFF42 // ｂ FULLWIDTH LATIN SMALL LETTER B
#define UC_MACRO_NAME_FF43 0xFF43 // ｃ FULLWIDTH LATIN SMALL LETTER C
#define UC_MACRO_NAME_FF44 0xFF44 // ｄ FULLWIDTH LATIN SMALL LETTER D
#define UC_MACRO_NAME_FF45 0xFF45 // ｅ FULLWIDTH LATIN SMALL LETTER E
#define UC_MACRO_NAME_FF46 0xFF46 // ｆ FULLWIDTH LATIN SMALL LETTER F
#define UC_MACRO_NAME_FF47 0xFF47 // ｇ FULLWIDTH LATIN SMALL LETTER G
#define UC_MACRO_NAME_FF48 0xFF48 // ｈ FULLWIDTH LATIN SMALL LETTER H
#define UC_MACRO_NAME_FF49 0xFF49 // ｉ FULLWIDTH LATIN SMALL LETTER I
#define UC_MACRO_NAME_FF4A 0xFF4A // ｊ FULLWIDTH LATIN SMALL LETTER J
#define UC_MACRO_NAME_FF4B 0xFF4B // ｋ FULLWIDTH LATIN SMALL LETTER K
#define UC_MACRO_NAME_FF4C 0xFF4C // ｌ FULLWIDTH LATIN SMALL LETTER L
#define UC_MACRO_NAME_FF4D 0xFF4D // ｍ FULLWIDTH LATIN SMALL LETTER M
#define UC_MACRO_NAME_FF4E 0xFF4E // ｎ FULLWIDTH LATIN SMALL LETTER N
#define UC_MACRO_NAME_FF4F 0xFF4F // ｏ FULLWIDTH LATIN SMALL LETTER O
#define UC_MACRO_NAME_FF50 0xFF50 // ｐ FULLWIDTH LATIN SMALL LETTER P
#define UC_MACRO_NAME_FF51 0xFF51 // ｑ FULLWIDTH LATIN SMALL LETTER Q
#define UC_MACRO_NAME_FF52 0xFF52 // ｒ FULLWIDTH LATIN SMALL LETTER R
#define UC_MACRO_NAME_FF53 0xFF53 // ｓ FULLWIDTH LATIN SMALL LETTER S
#define UC_MACRO_NAME_FF54 0xFF54 // ｔ FULLWIDTH LATIN SMALL LETTER T
#define UC_MACRO_NAME_FF55 0xFF55 // ｕ FULLWIDTH LATIN SMALL LETTER U
#define UC_MACRO_NAME_FF56 0xFF56 // ｖ FULLWIDTH LATIN SMALL LETTER V
#define UC_MACRO_NAME_FF57 0xFF57 // ｗ FULLWIDTH LATIN SMALL LETTER W
#define UC_MACRO_NAME_FF58 0xFF58 // ｘ FULLWIDTH LATIN SMALL LETTER X
#define UC_MACRO_NAME_FF59 0xFF59 // ｙ FULLWIDTH LATIN SMALL LETTER Y
#define UC_MACRO_NAME_FF5A 0xFF5A // ｚ FULLWIDTH LATIN SMALL LETTER Z
#define UC_MACRO_NAME_FF5B 0xFF5B // ｛ FULLWIDTH LEFT CURLY BRACKET
#define UC_MACRO_NAME_FF5C 0xFF5C // ｜ FULLWIDTH VERTICAL LINE
#define UC_MACRO_NAME_FF5D 0xFF5D // ｝ FULLWIDTH RIGHT CURLY BRACKET
#define UC_MACRO_NAME_FF5E 0xFF5E // ～ FULLWIDTH TILDE
#define UC_MACRO_NAME_FF5F 0xFF5F // ｟ FULLWIDTH LEFT WHITE PARENTHESIS
#define UC_MACRO_NAME_FF60 0xFF60 // ｠ FULLWIDTH RIGHT WHITE PARENTHESIS
#define UC_MACRO_NAME_FF61 0xFF61 // ｡ HALFWIDTH IDEOGRAPHIC FULL STOP
#define UC_MACRO_NAME_FF62 0xFF62 // ｢ HALFWIDTH LEFT CORNER BRACKET
#define UC_MACRO_NAME_FF63 0xFF63 // ｣ HALFWIDTH RIGHT CORNER BRACKET
#define UC_MACRO_NAME_FF64 0xFF64 // ､ HALFWIDTH IDEOGRAPHIC COMMA
#define UC_MACRO_NAME_FF65 0xFF65 // ･ HALFWIDTH KATAKANA MIDDLE DOT
#define UC_MACRO_NAME_FF66 0xFF66 // ｦ HALFWIDTH KATAKANA LETTER WO
#define UC_MACRO_NAME_FF67 0xFF67 // ｧ HALFWIDTH KATAKANA LETTER SMALL A
#define UC_MACRO_NAME_FF68 0xFF68 // ｨ HALFWIDTH KATAKANA LETTER SMALL I
#define UC_MACRO_NAME_FF69 0xFF69 // ｩ HALFWIDTH KATAKANA LETTER SMALL U
#define UC_MACRO_NAME_FF6A 0xFF6A // ｪ HALFWIDTH KATAKANA LETTER SMALL E
#define UC_MACRO_NAME_FF6B 0xFF6B // ｫ HALFWIDTH KATAKANA LETTER SMALL O
#define UC_MACRO_NAME_FF6C 0xFF6C // ｬ HALFWIDTH KATAKANA LETTER SMALL YA
#define UC_MACRO_NAME_FF6D 0xFF6D // ｭ HALFWIDTH KATAKANA LETTER SMALL YU
#define UC_MACRO_NAME_FF6E 0xFF6E // ｮ HALFWIDTH KATAKANA LETTER SMALL YO
#define UC_MACRO_NAME_FF6F 0xFF6F // ｯ HALFWIDTH KATAKANA LETTER SMALL TU
#define UC_MACRO_NAME_FF70 0xFF70 // ｰ HALFWIDTH KATAKANA-HIRAGANA PROLONGED SOUND MARK
#define UC_MACRO_NAME_FF71 0xFF71 // ｱ HALFWIDTH KATAKANA LETTER A
#define UC_MACRO_NAME_FF72 0xFF72 // ｲ HALFWIDTH KATAKANA LETTER I
#define UC_MACRO_NAME_FF73 0xFF73 // ｳ HALFWIDTH KATAKANA LETTER U
#define UC_MACRO_NAME_FF74 0xFF74 // ｴ HALFWIDTH KATAKANA LETTER E
#define UC_MACRO_NAME_FF75 0xFF75 // ｵ HALFWIDTH KATAKANA LETTER O
#define UC_MACRO_NAME_FF76 0xFF76 // ｶ HALFWIDTH KATAKANA LETTER KA
#define UC_MACRO_NAME_FF77 0xFF77 // ｷ HALFWIDTH KATAKANA LETTER KI
#define UC_MACRO_NAME_FF78 0xFF78 // ｸ HALFWIDTH KATAKANA LETTER KU
#define UC_MACRO_NAME_FF79 0xFF79 // ｹ HALFWIDTH KATAKANA LETTER KE
#define UC_MACRO_NAME_FF7A 0xFF7A // ｺ HALFWIDTH KATAKANA LETTER KO
#define UC_MACRO_NAME_FF7B 0xFF7B // ｻ HALFWIDTH KATAKANA LETTER SA
#define UC_MACRO_NAME_FF7C 0xFF7C // ｼ HALFWIDTH KATAKANA LETTER SI
#define UC_MACRO_NAME_FF7D 0xFF7D // ｽ HALFWIDTH KATAKANA LETTER SU
#define UC_MACRO_NAME_FF7E 0xFF7E // ｾ HALFWIDTH KATAKANA LETTER SE
#define UC_MACRO_NAME_FF7F 0xFF7F // ｿ HALFWIDTH KATAKANA LETTER SO
#define UC_MACRO_NAME_FF80 0xFF80 // ﾀ HALFWIDTH KATAKANA LETTER TA
#define UC_MACRO_NAME_FF81 0xFF81 // ﾁ HALFWIDTH KATAKANA LETTER TI
#define UC_MACRO_NAME_FF82 0xFF82 // ﾂ HALFWIDTH KATAKANA LETTER TU
#define UC_MACRO_NAME_FF83 0xFF83 // ﾃ HALFWIDTH KATAKANA LETTER TE
#define UC_MACRO_NAME_FF84 0xFF84 // ﾄ HALFWIDTH KATAKANA LETTER TO
#define UC_MACRO_NAME_FF85 0xFF85 // ﾅ HALFWIDTH KATAKANA LETTER NA
#define UC_MACRO_NAME_FF86 0xFF86 // ﾆ HALFWIDTH KATAKANA LETTER NI
#define UC_MACRO_NAME_FF87 0xFF87 // ﾇ HALFWIDTH KATAKANA LETTER NU
#define UC_MACRO_NAME_FF88 0xFF88 // ﾈ HALFWIDTH KATAKANA LETTER NE
#define UC_MACRO_NAME_FF89 0xFF89 // ﾉ HALFWIDTH KATAKANA LETTER NO
#define UC_MACRO_NAME_FF8A 0xFF8A // ﾊ HALFWIDTH KATAKANA LETTER HA
#define UC_MACRO_NAME_FF8B 0xFF8B // ﾋ HALFWIDTH KATAKANA LETTER HI
#define UC_MACRO_NAME_FF8C 0xFF8C // ﾌ HALFWIDTH KATAKANA LETTER HU
#define UC_MACRO_NAME_FF8D 0xFF8D // ﾍ HALFWIDTH KATAKANA LETTER HE
#define UC_MACRO_NAME_FF8E 0xFF8E // ﾎ HALFWIDTH KATAKANA LETTER HO
#define UC_MACRO_NAME_FF8F 0xFF8F // ﾏ HALFWIDTH KATAKANA LETTER MA
#define UC_MACRO_NAME_FF90 0xFF90 // ﾐ HALFWIDTH KATAKANA LETTER MI
#define UC_MACRO_NAME_FF91 0xFF91 // ﾑ HALFWIDTH KATAKANA LETTER MU
#define UC_MACRO_NAME_FF92 0xFF92 // ﾒ HALFWIDTH KATAKANA LETTER ME
#define UC_MACRO_NAME_FF93 0xFF93 // ﾓ HALFWIDTH KATAKANA LETTER MO
#define UC_MACRO_NAME_FF94 0xFF94 // ﾔ HALFWIDTH KATAKANA LETTER YA
#define UC_MACRO_NAME_FF95 0xFF95 // ﾕ HALFWIDTH KATAKANA LETTER YU
#define UC_MACRO_NAME_FF96 0xFF96 // ﾖ HALFWIDTH KATAKANA LETTER YO
#define UC_MACRO_NAME_FF97 0xFF97 // ﾗ HALFWIDTH KATAKANA LETTER RA
#define UC_MACRO_NAME_FF98 0xFF98 // ﾘ HALFWIDTH KATAKANA LETTER RI
#define UC_MACRO_NAME_FF99 0xFF99 // ﾙ HALFWIDTH KATAKANA LETTER RU
#define UC_MACRO_NAME_FF9A 0xFF9A // ﾚ HALFWIDTH KATAKANA LETTER RE
#define UC_MACRO_NAME_FF9B 0xFF9B // ﾛ HALFWIDTH KATAKANA LETTER RO
#define UC_MACRO_NAME_FF9C 0xFF9C // ﾜ HALFWIDTH KATAKANA LETTER WA
#define UC_MACRO_NAME_FF9D 0xFF9D // ﾝ HALFWIDTH KATAKANA LETTER N
#define UC_MACRO_NAME_FF9E 0xFF9E // ﾞ HALFWIDTH KATAKANA VOICED SOUND MARK
#define UC_MACRO_NAME_FF9F 0xFF9F // ﾟ HALFWIDTH KATAKANA SEMI-VOICED SOUND MARK
#define UC_MACRO_NAME_FFA0 0xFFA0 // ﾠ HALFWIDTH HANGUL FILLER
#define UC_MACRO_NAME_FFA1 0xFFA1 // ﾡ HALFWIDTH HANGUL LETTER KIYEOK
#define UC_MACRO_NAME_FFA2 0xFFA2 // ﾢ HALFWIDTH HANGUL LETTER SSANGKIYEOK
#define UC_MACRO_NAME_FFA3 0xFFA3 // ﾣ HALFWIDTH HANGUL LETTER KIYEOK-SIOS
#define UC_MACRO_NAME_FFA4 0xFFA4 // ﾤ HALFWIDTH HANGUL LETTER NIEUN
#define UC_MACRO_NAME_FFA5 0xFFA5 // ﾥ HALFWIDTH HANGUL LETTER NIEUN-CIEUC
#define UC_MACRO_NAME_FFA6 0xFFA6 // ﾦ HALFWIDTH HANGUL LETTER NIEUN-HIEUH
#define UC_MACRO_NAME_FFA7 0xFFA7 // ﾧ HALFWIDTH HANGUL LETTER TIKEUT
#define UC_MACRO_NAME_FFA8 0xFFA8 // ﾨ HALFWIDTH HANGUL LETTER SSANGTIKEUT
#define UC_MACRO_NAME_FFA9 0xFFA9 // ﾩ HALFWIDTH HANGUL LETTER RIEUL
#define UC_MACRO_NAME_FFAA 0xFFAA // ﾪ HALFWIDTH HANGUL LETTER RIEUL-KIYEOK
#define UC_MACRO_NAME_FFAB 0xFFAB // ﾫ HALFWIDTH HANGUL LETTER RIEUL-MIEUM
#define UC_MACRO_NAME_FFAC 0xFFAC // ﾬ HALFWIDTH HANGUL LETTER RIEUL-PIEUP
#define UC_MACRO_NAME_FFAD 0xFFAD // ﾭ HALFWIDTH HANGUL LETTER RIEUL-SIOS
#define UC_MACRO_NAME_FFAE 0xFFAE // ﾮ HALFWIDTH HANGUL LETTER RIEUL-THIEUTH
#define UC_MACRO_NAME_FFAF 0xFFAF // ﾯ HALFWIDTH HANGUL LETTER RIEUL-PHIEUPH
#define UC_MACRO_NAME_FFB0 0xFFB0 // ﾰ HALFWIDTH HANGUL LETTER RIEUL-HIEUH
#define UC_MACRO_NAME_FFB1 0xFFB1 // ﾱ HALFWIDTH HANGUL LETTER MIEUM
#define UC_MACRO_NAME_FFB2 0xFFB2 // ﾲ HALFWIDTH HANGUL LETTER PIEUP
#define UC_MACRO_NAME_FFB3 0xFFB3 // ﾳ HALFWIDTH HANGUL LETTER SSANGPIEUP
#define UC_MACRO_NAME_FFB4 0xFFB4 // ﾴ HALFWIDTH HANGUL LETTER PIEUP-SIOS
#define UC_MACRO_NAME_FFB5 0xFFB5 // ﾵ HALFWIDTH HANGUL LETTER SIOS
#define UC_MACRO_NAME_FFB6 0xFFB6 // ﾶ HALFWIDTH HANGUL LETTER SSANGSIOS
#define UC_MACRO_NAME_FFB7 0xFFB7 // ﾷ HALFWIDTH HANGUL LETTER IEUNG
#define UC_MACRO_NAME_FFB8 0xFFB8 // ﾸ HALFWIDTH HANGUL LETTER CIEUC
#define UC_MACRO_NAME_FFB9 0xFFB9 // ﾹ HALFWIDTH HANGUL LETTER SSANGCIEUC
#define UC_MACRO_NAME_FFBA 0xFFBA // ﾺ HALFWIDTH HANGUL LETTER CHIEUCH
#define UC_MACRO_NAME_FFBB 0xFFBB // ﾻ HALFWIDTH HANGUL LETTER KHIEUKH
#define UC_MACRO_NAME_FFBC 0xFFBC // ﾼ HALFWIDTH HANGUL LETTER THIEUTH
#define UC_MACRO_NAME_FFBD 0xFFBD // ﾽ HALFWIDTH HANGUL LETTER PHIEUPH
#define UC_MACRO_NAME_FFBE 0xFFBE // ﾾ HALFWIDTH HANGUL LETTER HIEUH
#define UC_MACRO_NAME_FFC2 0xFFC2 // ￂ HALFWIDTH HANGUL LETTER A
#define UC_MACRO_NAME_FFC3 0xFFC3 // ￃ HALFWIDTH HANGUL LETTER AE
#define UC_MACRO_NAME_FFC4 0xFFC4 // ￄ HALFWIDTH HANGUL LETTER YA
#define UC_MACRO_NAME_FFC5 0xFFC5 // ￅ HALFWIDTH HANGUL LETTER YAE
#define UC_MACRO_NAME_FFC6 0xFFC6 // ￆ HALFWIDTH HANGUL LETTER EO
#define UC_MACRO_NAME_FFC7 0xFFC7 // ￇ HALFWIDTH HANGUL LETTER E
#define UC_MACRO_NAME_FFCA 0xFFCA // ￊ HALFWIDTH HANGUL LETTER YEO
#define UC_MACRO_NAME_FFCB 0xFFCB // ￋ HALFWIDTH HANGUL LETTER YE
#define UC_MACRO_NAME_FFCC 0xFFCC // ￌ HALFWIDTH HANGUL LETTER O
#define UC_MACRO_NAME_FFCD 0xFFCD // ￍ HALFWIDTH HANGUL LETTER WA
#define UC_MACRO_NAME_FFCE 0xFFCE // ￎ HALFWIDTH HANGUL LETTER WAE
#define UC_MACRO_NAME_FFCF 0xFFCF // ￏ HALFWIDTH HANGUL LETTER OE
#define UC_MACRO_NAME_FFD2 0xFFD2 // ￒ HALFWIDTH HANGUL LETTER YO
#define UC_MACRO_NAME_FFD3 0xFFD3 // ￓ HALFWIDTH HANGUL LETTER U
#define UC_MACRO_NAME_FFD4 0xFFD4 // ￔ HALFWIDTH HANGUL LETTER WEO
#define UC_MACRO_NAME_FFD5 0xFFD5 // ￕ HALFWIDTH HANGUL LETTER WE
#define UC_MACRO_NAME_FFD6 0xFFD6 // ￖ HALFWIDTH HANGUL LETTER WI
#define UC_MACRO_NAME_FFD7 0xFFD7 // ￗ HALFWIDTH HANGUL LETTER YU
#define UC_MACRO_NAME_FFDA 0xFFDA // ￚ HALFWIDTH HANGUL LETTER EU
#define UC_MACRO_NAME_FFDB 0xFFDB // ￛ HALFWIDTH HANGUL LETTER YI
#define UC_MACRO_NAME_FFDC 0xFFDC // ￜ HALFWIDTH HANGUL LETTER I
#define UC_MACRO_NAME_FFE0 0xFFE0 // ￠ FULLWIDTH CENT SIGN
#define UC_MACRO_NAME_FFE1 0xFFE1 // ￡ FULLWIDTH POUND SIGN
#define UC_MACRO_NAME_FFE2 0xFFE2 // ￢ FULLWIDTH NOT SIGN
#define UC_MACRO_NAME_FFE3 0xFFE3 // ￣ FULLWIDTH MACRON
#define UC_MACRO_NAME_FFE4 0xFFE4 // ￤ FULLWIDTH BROKEN BAR
#define UC_MACRO_NAME_FFE5 0xFFE5 // ￥ FULLWIDTH YEN SIGN
#define UC_MACRO_NAME_FFE6 0xFFE6 // ￦ FULLWIDTH WON SIGN
#define UC_MACRO_NAME_FFE8 0xFFE8 // ￨ HALFWIDTH FORMS LIGHT VERTICAL
#define UC_MACRO_NAME_FFE9 0xFFE9 // ￩ HALFWIDTH LEFTWARDS ARROW
#define UC_MACRO_NAME_FFEA 0xFFEA // ￪ HALFWIDTH UPWARDS ARROW
#define UC_MACRO_NAME_FFEB 0xFFEB // ￫ HALFWIDTH RIGHTWARDS ARROW
#define UC_MACRO_NAME_FFEC 0xFFEC // ￬ HALFWIDTH DOWNWARDS ARROW
#define UC_MACRO_NAME_FFED 0xFFED // ￭ HALFWIDTH BLACK SQUARE
#define UC_MACRO_NAME_FFEE 0xFFEE // ￮ HALFWIDTH WHITE CIRCLE


#endif // UC_H_HALFWIDTH_AND_FULLWIDTH_FORMS
