/*
 * Unicode Block: Hangul Jamo Extended-A
 * Range: U+A960..U+A97F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_HANGUL_JAMO_EXTENDED_A
#define UC_H_HANGUL_JAMO_EXTENDED_A

#define UC_MACRO_NAME_A960 0xA960 // ꥠ HANGUL CHOSEONG TIKEUT-MIEUM
#define UC_MACRO_NAME_A961 0xA961 // ꥡ HANGUL CHOSEONG TIKEUT-PIEUP
#define UC_MACRO_NAME_A962 0xA962 // ꥢ HANGUL CHOSEONG TIKEUT-SIOS
#define UC_MACRO_NAME_A963 0xA963 // ꥣ HANGUL CHOSEONG TIKEUT-CIEUC
#define UC_MACRO_NAME_A964 0xA964 // ꥤ HANGUL CHOSEONG RIEUL-KIYEOK
#define UC_MACRO_NAME_A965 0xA965 // ꥥ HANGUL CHOSEONG RIEUL-SSANGKIYEOK
#define UC_MACRO_NAME_A966 0xA966 // ꥦ HANGUL CHOSEONG RIEUL-TIKEUT
#define UC_MACRO_NAME_A967 0xA967 // ꥧ HANGUL CHOSEONG RIEUL-SSANGTIKEUT
#define UC_MACRO_NAME_A968 0xA968 // ꥨ HANGUL CHOSEONG RIEUL-MIEUM
#define UC_MACRO_NAME_A969 0xA969 // ꥩ HANGUL CHOSEONG RIEUL-PIEUP
#define UC_MACRO_NAME_A96A 0xA96A // ꥪ HANGUL CHOSEONG RIEUL-SSANGPIEUP
#define UC_MACRO_NAME_A96B 0xA96B // ꥫ HANGUL CHOSEONG RIEUL-KAPYEOUNPIEUP
#define UC_MACRO_NAME_A96C 0xA96C // ꥬ HANGUL CHOSEONG RIEUL-SIOS
#define UC_MACRO_NAME_A96D 0xA96D // ꥭ HANGUL CHOSEONG RIEUL-CIEUC
#define UC_MACRO_NAME_A96E 0xA96E // ꥮ HANGUL CHOSEONG RIEUL-KHIEUKH
#define UC_MACRO_NAME_A96F 0xA96F // ꥯ HANGUL CHOSEONG MIEUM-KIYEOK
#define UC_MACRO_NAME_A970 0xA970 // ꥰ HANGUL CHOSEONG MIEUM-TIKEUT
#define UC_MACRO_NAME_A971 0xA971 // ꥱ HANGUL CHOSEONG MIEUM-SIOS
#define UC_MACRO_NAME_A972 0xA972 // ꥲ HANGUL CHOSEONG PIEUP-SIOS-THIEUTH
#define UC_MACRO_NAME_A973 0xA973 // ꥳ HANGUL CHOSEONG PIEUP-KHIEUKH
#define UC_MACRO_NAME_A974 0xA974 // ꥴ HANGUL CHOSEONG PIEUP-HIEUH
#define UC_MACRO_NAME_A975 0xA975 // ꥵ HANGUL CHOSEONG SSANGSIOS-PIEUP
#define UC_MACRO_NAME_A976 0xA976 // ꥶ HANGUL CHOSEONG IEUNG-RIEUL
#define UC_MACRO_NAME_A977 0xA977 // ꥷ HANGUL CHOSEONG IEUNG-HIEUH
#define UC_MACRO_NAME_A978 0xA978 // ꥸ HANGUL CHOSEONG SSANGCIEUC-HIEUH
#define UC_MACRO_NAME_A979 0xA979 // ꥹ HANGUL CHOSEONG SSANGTHIEUTH
#define UC_MACRO_NAME_A97A 0xA97A // ꥺ HANGUL CHOSEONG PHIEUPH-HIEUH
#define UC_MACRO_NAME_A97B 0xA97B // ꥻ HANGUL CHOSEONG HIEUH-SIOS
#define UC_MACRO_NAME_A97C 0xA97C // ꥼ HANGUL CHOSEONG SSANGYEORINHIEUH


#endif // UC_H_HANGUL_JAMO_EXTENDED_A
