/*
 * Unicode Block: Inscriptional Parthian
 * Range: U+10B40..U+10B5F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Inscriptional Parthian was a script used to write the Parthian
 * language ; the majority of the text found has been from clay
 * fragments. This script was used from the 2nd century CE to the 5th
 * century CE or in the Parthian Empire to the early Sasanian Empire .
 * During the Sasanian Empire , it was mostly used for official texts.
 * Inscriptional Parthian is written right to left, and the letters are
 * not joined.
 *
 */
#ifndef UC_H_INSCRIPTIONAL_PARTHIAN
#define UC_H_INSCRIPTIONAL_PARTHIAN

#define UC_MACRO_NAME_10B40 0x10B40 // 𐭀 INSCRIPTIONAL PARTHIAN LETTER ALEPH
#define UC_MACRO_NAME_10B41 0x10B41 // 𐭁 INSCRIPTIONAL PARTHIAN LETTER BETH
#define UC_MACRO_NAME_10B42 0x10B42 // 𐭂 INSCRIPTIONAL PARTHIAN LETTER GIMEL
#define UC_MACRO_NAME_10B43 0x10B43 // 𐭃 INSCRIPTIONAL PARTHIAN LETTER DALETH
#define UC_MACRO_NAME_10B44 0x10B44 // 𐭄 INSCRIPTIONAL PARTHIAN LETTER HE
#define UC_MACRO_NAME_10B45 0x10B45 // 𐭅 INSCRIPTIONAL PARTHIAN LETTER WAW
#define UC_MACRO_NAME_10B46 0x10B46 // 𐭆 INSCRIPTIONAL PARTHIAN LETTER ZAYIN
#define UC_MACRO_NAME_10B47 0x10B47 // 𐭇 INSCRIPTIONAL PARTHIAN LETTER HETH
#define UC_MACRO_NAME_10B48 0x10B48 // 𐭈 INSCRIPTIONAL PARTHIAN LETTER TETH
#define UC_MACRO_NAME_10B49 0x10B49 // 𐭉 INSCRIPTIONAL PARTHIAN LETTER YODH
#define UC_MACRO_NAME_10B4A 0x10B4A // 𐭊 INSCRIPTIONAL PARTHIAN LETTER KAPH
#define UC_MACRO_NAME_10B4B 0x10B4B // 𐭋 INSCRIPTIONAL PARTHIAN LETTER LAMEDH
#define UC_MACRO_NAME_10B4C 0x10B4C // 𐭌 INSCRIPTIONAL PARTHIAN LETTER MEM
#define UC_MACRO_NAME_10B4D 0x10B4D // 𐭍 INSCRIPTIONAL PARTHIAN LETTER NUN
#define UC_MACRO_NAME_10B4E 0x10B4E // 𐭎 INSCRIPTIONAL PARTHIAN LETTER SAMEKH
#define UC_MACRO_NAME_10B4F 0x10B4F // 𐭏 INSCRIPTIONAL PARTHIAN LETTER AYIN
#define UC_MACRO_NAME_10B50 0x10B50 // 𐭐 INSCRIPTIONAL PARTHIAN LETTER PE
#define UC_MACRO_NAME_10B51 0x10B51 // 𐭑 INSCRIPTIONAL PARTHIAN LETTER SADHE
#define UC_MACRO_NAME_10B52 0x10B52 // 𐭒 INSCRIPTIONAL PARTHIAN LETTER QOPH
#define UC_MACRO_NAME_10B53 0x10B53 // 𐭓 INSCRIPTIONAL PARTHIAN LETTER RESH
#define UC_MACRO_NAME_10B54 0x10B54 // 𐭔 INSCRIPTIONAL PARTHIAN LETTER SHIN
#define UC_MACRO_NAME_10B55 0x10B55 // 𐭕 INSCRIPTIONAL PARTHIAN LETTER TAW
#define UC_MACRO_NAME_10B58 0x10B58 // 𐭘 INSCRIPTIONAL PARTHIAN NUMBER ONE
#define UC_MACRO_NAME_10B59 0x10B59 // 𐭙 INSCRIPTIONAL PARTHIAN NUMBER TWO
#define UC_MACRO_NAME_10B5A 0x10B5A // 𐭚 INSCRIPTIONAL PARTHIAN NUMBER THREE
#define UC_MACRO_NAME_10B5B 0x10B5B // 𐭛 INSCRIPTIONAL PARTHIAN NUMBER FOUR
#define UC_MACRO_NAME_10B5C 0x10B5C // 𐭜 INSCRIPTIONAL PARTHIAN NUMBER TEN
#define UC_MACRO_NAME_10B5D 0x10B5D // 𐭝 INSCRIPTIONAL PARTHIAN NUMBER TWENTY
#define UC_MACRO_NAME_10B5E 0x10B5E // 𐭞 INSCRIPTIONAL PARTHIAN NUMBER ONE HUNDRED
#define UC_MACRO_NAME_10B5F 0x10B5F // 𐭟 INSCRIPTIONAL PARTHIAN NUMBER ONE THOUSAND


#endif // UC_H_INSCRIPTIONAL_PARTHIAN
