/*
 * Unicode Block: IPA Extensions
 * Range: U+0250..U+02AF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * IPA Extensions is a block (U+0250–U+02AF) of the Unicode standard that
 * contains full size letters used in the International Phonetic Alphabet
 * (IPA). Both modern and historical characters are included, as well as
 * former and proposed IPA signs and non-IPA phonetic letters. Additional
 * characters employed for phonetics, like the palatalization sign, are
 * encoded in the blocks Phonetic Extensions (1D00–1D7F) and Phonetic
 * Extensions Supplement (1D80–1DBF). Diacritics are found in the Spacing
 * Modifier Letters (02B0–02FF) and Combining Diacritical Marks
 * (0300–036F) blocks. Its block name in Unicode 1.0 was Standard
 * Phonetic .
 * With the ability to use Unicode for the presentation of IPA symbols,
 * ASCII-based systems such as X-SAMPA are being supplanted. Within the
 * Unicode blocks there are also a few former IPA characters no longer in
 * international use by linguists.
 *
 */
#ifndef UC_H_IPA_EXTENSIONS
#define UC_H_IPA_EXTENSIONS

#define UC_MACRO_NAME_250 0x0250 // ɐ LATIN SMALL LETTER TURNED A
#define UC_MACRO_NAME_251 0x0251 // ɑ LATIN SMALL LETTER ALPHA
#define UC_MACRO_NAME_252 0x0252 // ɒ LATIN SMALL LETTER TURNED ALPHA
#define UC_MACRO_NAME_253 0x0253 // ɓ LATIN SMALL LETTER B WITH HOOK
#define UC_MACRO_NAME_254 0x0254 // ɔ LATIN SMALL LETTER OPEN O
#define UC_MACRO_NAME_255 0x0255 // ɕ LATIN SMALL LETTER C WITH CURL
#define UC_MACRO_NAME_256 0x0256 // ɖ LATIN SMALL LETTER D WITH TAIL
#define UC_MACRO_NAME_257 0x0257 // ɗ LATIN SMALL LETTER D WITH HOOK
#define UC_MACRO_NAME_258 0x0258 // ɘ LATIN SMALL LETTER REVERSED E
#define UC_MACRO_NAME_259 0x0259 // ə LATIN SMALL LETTER SCHWA
#define UC_MACRO_NAME_25A 0x025A // ɚ LATIN SMALL LETTER SCHWA WITH HOOK
#define UC_MACRO_NAME_25B 0x025B // ɛ LATIN SMALL LETTER OPEN E
#define UC_MACRO_NAME_25C 0x025C // ɜ LATIN SMALL LETTER REVERSED OPEN E
#define UC_MACRO_NAME_25D 0x025D // ɝ LATIN SMALL LETTER REVERSED OPEN E WITH HOOK
#define UC_MACRO_NAME_25E 0x025E // ɞ LATIN SMALL LETTER CLOSED REVERSED OPEN E
#define UC_MACRO_NAME_25F 0x025F // ɟ LATIN SMALL LETTER DOTLESS J WITH STROKE
#define UC_MACRO_NAME_260 0x0260 // ɠ LATIN SMALL LETTER G WITH HOOK
#define UC_MACRO_NAME_261 0x0261 // ɡ LATIN SMALL LETTER SCRIPT G
#define UC_MACRO_NAME_262 0x0262 // ɢ LATIN LETTER SMALL CAPITAL G
#define UC_MACRO_NAME_263 0x0263 // ɣ LATIN SMALL LETTER GAMMA
#define UC_MACRO_NAME_264 0x0264 // ɤ LATIN SMALL LETTER RAMS HORN
#define UC_MACRO_NAME_265 0x0265 // ɥ LATIN SMALL LETTER TURNED H
#define UC_MACRO_NAME_266 0x0266 // ɦ LATIN SMALL LETTER H WITH HOOK
#define UC_MACRO_NAME_267 0x0267 // ɧ LATIN SMALL LETTER HENG WITH HOOK
#define UC_MACRO_NAME_268 0x0268 // ɨ LATIN SMALL LETTER I WITH STROKE
#define UC_MACRO_NAME_269 0x0269 // ɩ LATIN SMALL LETTER IOTA
#define UC_MACRO_NAME_26A 0x026A // ɪ LATIN LETTER SMALL CAPITAL I
#define UC_MACRO_NAME_26B 0x026B // ɫ LATIN SMALL LETTER L WITH MIDDLE TILDE
#define UC_MACRO_NAME_26C 0x026C // ɬ LATIN SMALL LETTER L WITH BELT
#define UC_MACRO_NAME_26D 0x026D // ɭ LATIN SMALL LETTER L WITH RETROFLEX HOOK
#define UC_MACRO_NAME_26E 0x026E // ɮ LATIN SMALL LETTER LEZH
#define UC_MACRO_NAME_26F 0x026F // ɯ LATIN SMALL LETTER TURNED M
#define UC_MACRO_NAME_270 0x0270 // ɰ LATIN SMALL LETTER TURNED M WITH LONG LEG
#define UC_MACRO_NAME_271 0x0271 // ɱ LATIN SMALL LETTER M WITH HOOK
#define UC_MACRO_NAME_272 0x0272 // ɲ LATIN SMALL LETTER N WITH LEFT HOOK
#define UC_MACRO_NAME_273 0x0273 // ɳ LATIN SMALL LETTER N WITH RETROFLEX HOOK
#define UC_MACRO_NAME_274 0x0274 // ɴ LATIN LETTER SMALL CAPITAL N
#define UC_MACRO_NAME_275 0x0275 // ɵ LATIN SMALL LETTER BARRED O
#define UC_MACRO_NAME_276 0x0276 // ɶ LATIN LETTER SMALL CAPITAL OE
#define UC_MACRO_NAME_277 0x0277 // ɷ LATIN SMALL LETTER CLOSED OMEGA
#define UC_MACRO_NAME_278 0x0278 // ɸ LATIN SMALL LETTER PHI
#define UC_MACRO_NAME_279 0x0279 // ɹ LATIN SMALL LETTER TURNED R
#define UC_MACRO_NAME_27A 0x027A // ɺ LATIN SMALL LETTER TURNED R WITH LONG LEG
#define UC_MACRO_NAME_27B 0x027B // ɻ LATIN SMALL LETTER TURNED R WITH HOOK
#define UC_MACRO_NAME_27C 0x027C // ɼ LATIN SMALL LETTER R WITH LONG LEG
#define UC_MACRO_NAME_27D 0x027D // ɽ LATIN SMALL LETTER R WITH TAIL
#define UC_MACRO_NAME_27E 0x027E // ɾ LATIN SMALL LETTER R WITH FISHHOOK
#define UC_MACRO_NAME_27F 0x027F // ɿ LATIN SMALL LETTER REVERSED R WITH FISHHOOK
#define UC_MACRO_NAME_280 0x0280 // ʀ LATIN LETTER SMALL CAPITAL R
#define UC_MACRO_NAME_281 0x0281 // ʁ LATIN LETTER SMALL CAPITAL INVERTED R
#define UC_MACRO_NAME_282 0x0282 // ʂ LATIN SMALL LETTER S WITH HOOK
#define UC_MACRO_NAME_283 0x0283 // ʃ LATIN SMALL LETTER ESH
#define UC_MACRO_NAME_284 0x0284 // ʄ LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK
#define UC_MACRO_NAME_285 0x0285 // ʅ LATIN SMALL LETTER SQUAT REVERSED ESH
#define UC_MACRO_NAME_286 0x0286 // ʆ LATIN SMALL LETTER ESH WITH CURL
#define UC_MACRO_NAME_287 0x0287 // ʇ LATIN SMALL LETTER TURNED T
#define UC_MACRO_NAME_288 0x0288 // ʈ LATIN SMALL LETTER T WITH RETROFLEX HOOK
#define UC_MACRO_NAME_289 0x0289 // ʉ LATIN SMALL LETTER U BAR
#define UC_MACRO_NAME_28A 0x028A // ʊ LATIN SMALL LETTER UPSILON
#define UC_MACRO_NAME_28B 0x028B // ʋ LATIN SMALL LETTER V WITH HOOK
#define UC_MACRO_NAME_28C 0x028C // ʌ LATIN SMALL LETTER TURNED V
#define UC_MACRO_NAME_28D 0x028D // ʍ LATIN SMALL LETTER TURNED W
#define UC_MACRO_NAME_28E 0x028E // ʎ LATIN SMALL LETTER TURNED Y
#define UC_MACRO_NAME_28F 0x028F // ʏ LATIN LETTER SMALL CAPITAL Y
#define UC_MACRO_NAME_290 0x0290 // ʐ LATIN SMALL LETTER Z WITH RETROFLEX HOOK
#define UC_MACRO_NAME_291 0x0291 // ʑ LATIN SMALL LETTER Z WITH CURL
#define UC_MACRO_NAME_292 0x0292 // ʒ LATIN SMALL LETTER EZH
#define UC_MACRO_NAME_293 0x0293 // ʓ LATIN SMALL LETTER EZH WITH CURL
#define UC_MACRO_NAME_294 0x0294 // ʔ LATIN LETTER GLOTTAL STOP
#define UC_MACRO_NAME_295 0x0295 // ʕ LATIN LETTER PHARYNGEAL VOICED FRICATIVE
#define UC_MACRO_NAME_296 0x0296 // ʖ LATIN LETTER INVERTED GLOTTAL STOP
#define UC_MACRO_NAME_297 0x0297 // ʗ LATIN LETTER STRETCHED C
#define UC_MACRO_NAME_298 0x0298 // ʘ LATIN LETTER BILABIAL CLICK
#define UC_MACRO_NAME_299 0x0299 // ʙ LATIN LETTER SMALL CAPITAL B
#define UC_MACRO_NAME_29A 0x029A // ʚ LATIN SMALL LETTER CLOSED OPEN E
#define UC_MACRO_NAME_29B 0x029B // ʛ LATIN LETTER SMALL CAPITAL G WITH HOOK
#define UC_MACRO_NAME_29C 0x029C // ʜ LATIN LETTER SMALL CAPITAL H
#define UC_MACRO_NAME_29D 0x029D // ʝ LATIN SMALL LETTER J WITH CROSSED-TAIL
#define UC_MACRO_NAME_29E 0x029E // ʞ LATIN SMALL LETTER TURNED K
#define UC_MACRO_NAME_29F 0x029F // ʟ LATIN LETTER SMALL CAPITAL L
#define UC_MACRO_NAME_2A0 0x02A0 // ʠ LATIN SMALL LETTER Q WITH HOOK
#define UC_MACRO_NAME_2A1 0x02A1 // ʡ LATIN LETTER GLOTTAL STOP WITH STROKE
#define UC_MACRO_NAME_2A2 0x02A2 // ʢ LATIN LETTER REVERSED GLOTTAL STOP WITH STROKE
#define UC_MACRO_NAME_2A3 0x02A3 // ʣ LATIN SMALL LETTER DZ DIGRAPH
#define UC_MACRO_NAME_2A4 0x02A4 // ʤ LATIN SMALL LETTER DEZH DIGRAPH
#define UC_MACRO_NAME_2A5 0x02A5 // ʥ LATIN SMALL LETTER DZ DIGRAPH WITH CURL
#define UC_MACRO_NAME_2A6 0x02A6 // ʦ LATIN SMALL LETTER TS DIGRAPH
#define UC_MACRO_NAME_2A7 0x02A7 // ʧ LATIN SMALL LETTER TESH DIGRAPH
#define UC_MACRO_NAME_2A8 0x02A8 // ʨ LATIN SMALL LETTER TC DIGRAPH WITH CURL
#define UC_MACRO_NAME_2A9 0x02A9 // ʩ LATIN SMALL LETTER FENG DIGRAPH
#define UC_MACRO_NAME_2AA 0x02AA // ʪ LATIN SMALL LETTER LS DIGRAPH
#define UC_MACRO_NAME_2AB 0x02AB // ʫ LATIN SMALL LETTER LZ DIGRAPH
#define UC_MACRO_NAME_2AC 0x02AC // ʬ LATIN LETTER BILABIAL PERCUSSIVE
#define UC_MACRO_NAME_2AD 0x02AD // ʭ LATIN LETTER BIDENTAL PERCUSSIVE
#define UC_MACRO_NAME_2AE 0x02AE // ʮ LATIN SMALL LETTER TURNED H WITH FISHHOOK
#define UC_MACRO_NAME_2AF 0x02AF // ʯ LATIN SMALL LETTER TURNED H WITH FISHHOOK AND TAIL


#endif // UC_H_IPA_EXTENSIONS
