/*
 * Unicode Block: Indic Siyaq Numbers
 * Range: U+1EC70..U+1ECBF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_INDIC_SIYAQ_NUMBERS
#define UC_H_INDIC_SIYAQ_NUMBERS

#define UC_MACRO_NAME_1EC71 0x1EC71 // 𞱱 INDIC SIYAQ NUMBER ONE
#define UC_MACRO_NAME_1EC72 0x1EC72 // 𞱲 INDIC SIYAQ NUMBER TWO
#define UC_MACRO_NAME_1EC73 0x1EC73 // 𞱳 INDIC SIYAQ NUMBER THREE
#define UC_MACRO_NAME_1EC74 0x1EC74 // 𞱴 INDIC SIYAQ NUMBER FOUR
#define UC_MACRO_NAME_1EC75 0x1EC75 // 𞱵 INDIC SIYAQ NUMBER FIVE
#define UC_MACRO_NAME_1EC76 0x1EC76 // 𞱶 INDIC SIYAQ NUMBER SIX
#define UC_MACRO_NAME_1EC77 0x1EC77 // 𞱷 INDIC SIYAQ NUMBER SEVEN
#define UC_MACRO_NAME_1EC78 0x1EC78 // 𞱸 INDIC SIYAQ NUMBER EIGHT
#define UC_MACRO_NAME_1EC79 0x1EC79 // 𞱹 INDIC SIYAQ NUMBER NINE
#define UC_MACRO_NAME_1EC7A 0x1EC7A // 𞱺 INDIC SIYAQ NUMBER TEN
#define UC_MACRO_NAME_1EC7B 0x1EC7B // 𞱻 INDIC SIYAQ NUMBER TWENTY
#define UC_MACRO_NAME_1EC7C 0x1EC7C // 𞱼 INDIC SIYAQ NUMBER THIRTY
#define UC_MACRO_NAME_1EC7D 0x1EC7D // 𞱽 INDIC SIYAQ NUMBER FORTY
#define UC_MACRO_NAME_1EC7E 0x1EC7E // 𞱾 INDIC SIYAQ NUMBER FIFTY
#define UC_MACRO_NAME_1EC7F 0x1EC7F // 𞱿 INDIC SIYAQ NUMBER SIXTY
#define UC_MACRO_NAME_1EC80 0x1EC80 // 𞲀 INDIC SIYAQ NUMBER SEVENTY
#define UC_MACRO_NAME_1EC81 0x1EC81 // 𞲁 INDIC SIYAQ NUMBER EIGHTY
#define UC_MACRO_NAME_1EC82 0x1EC82 // 𞲂 INDIC SIYAQ NUMBER NINETY
#define UC_MACRO_NAME_1EC83 0x1EC83 // 𞲃 INDIC SIYAQ NUMBER ONE HUNDRED
#define UC_MACRO_NAME_1EC84 0x1EC84 // 𞲄 INDIC SIYAQ NUMBER TWO HUNDRED
#define UC_MACRO_NAME_1EC85 0x1EC85 // 𞲅 INDIC SIYAQ NUMBER THREE HUNDRED
#define UC_MACRO_NAME_1EC86 0x1EC86 // 𞲆 INDIC SIYAQ NUMBER FOUR HUNDRED
#define UC_MACRO_NAME_1EC87 0x1EC87 // 𞲇 INDIC SIYAQ NUMBER FIVE HUNDRED
#define UC_MACRO_NAME_1EC88 0x1EC88 // 𞲈 INDIC SIYAQ NUMBER SIX HUNDRED
#define UC_MACRO_NAME_1EC89 0x1EC89 // 𞲉 INDIC SIYAQ NUMBER SEVEN HUNDRED
#define UC_MACRO_NAME_1EC8A 0x1EC8A // 𞲊 INDIC SIYAQ NUMBER EIGHT HUNDRED
#define UC_MACRO_NAME_1EC8B 0x1EC8B // 𞲋 INDIC SIYAQ NUMBER NINE HUNDRED
#define UC_MACRO_NAME_1EC8C 0x1EC8C // 𞲌 INDIC SIYAQ NUMBER ONE THOUSAND
#define UC_MACRO_NAME_1EC8D 0x1EC8D // 𞲍 INDIC SIYAQ NUMBER TWO THOUSAND
#define UC_MACRO_NAME_1EC8E 0x1EC8E // 𞲎 INDIC SIYAQ NUMBER THREE THOUSAND
#define UC_MACRO_NAME_1EC8F 0x1EC8F // 𞲏 INDIC SIYAQ NUMBER FOUR THOUSAND
#define UC_MACRO_NAME_1EC90 0x1EC90 // 𞲐 INDIC SIYAQ NUMBER FIVE THOUSAND
#define UC_MACRO_NAME_1EC91 0x1EC91 // 𞲑 INDIC SIYAQ NUMBER SIX THOUSAND
#define UC_MACRO_NAME_1EC92 0x1EC92 // 𞲒 INDIC SIYAQ NUMBER SEVEN THOUSAND
#define UC_MACRO_NAME_1EC93 0x1EC93 // 𞲓 INDIC SIYAQ NUMBER EIGHT THOUSAND
#define UC_MACRO_NAME_1EC94 0x1EC94 // 𞲔 INDIC SIYAQ NUMBER NINE THOUSAND
#define UC_MACRO_NAME_1EC95 0x1EC95 // 𞲕 INDIC SIYAQ NUMBER TEN THOUSAND
#define UC_MACRO_NAME_1EC96 0x1EC96 // 𞲖 INDIC SIYAQ NUMBER TWENTY THOUSAND
#define UC_MACRO_NAME_1EC97 0x1EC97 // 𞲗 INDIC SIYAQ NUMBER THIRTY THOUSAND
#define UC_MACRO_NAME_1EC98 0x1EC98 // 𞲘 INDIC SIYAQ NUMBER FORTY THOUSAND
#define UC_MACRO_NAME_1EC99 0x1EC99 // 𞲙 INDIC SIYAQ NUMBER FIFTY THOUSAND
#define UC_MACRO_NAME_1EC9A 0x1EC9A // 𞲚 INDIC SIYAQ NUMBER SIXTY THOUSAND
#define UC_MACRO_NAME_1EC9B 0x1EC9B // 𞲛 INDIC SIYAQ NUMBER SEVENTY THOUSAND
#define UC_MACRO_NAME_1EC9C 0x1EC9C // 𞲜 INDIC SIYAQ NUMBER EIGHTY THOUSAND
#define UC_MACRO_NAME_1EC9D 0x1EC9D // 𞲝 INDIC SIYAQ NUMBER NINETY THOUSAND
#define UC_MACRO_NAME_1EC9E 0x1EC9E // 𞲞 INDIC SIYAQ NUMBER LAKH
#define UC_MACRO_NAME_1EC9F 0x1EC9F // 𞲟 INDIC SIYAQ NUMBER LAKHAN
#define UC_MACRO_NAME_1ECA0 0x1ECA0 // 𞲠 INDIC SIYAQ LAKH MARK
#define UC_MACRO_NAME_1ECA1 0x1ECA1 // 𞲡 INDIC SIYAQ NUMBER KAROR
#define UC_MACRO_NAME_1ECA2 0x1ECA2 // 𞲢 INDIC SIYAQ NUMBER KARORAN
#define UC_MACRO_NAME_1ECA3 0x1ECA3 // 𞲣 INDIC SIYAQ NUMBER PREFIXED ONE
#define UC_MACRO_NAME_1ECA4 0x1ECA4 // 𞲤 INDIC SIYAQ NUMBER PREFIXED TWO
#define UC_MACRO_NAME_1ECA5 0x1ECA5 // 𞲥 INDIC SIYAQ NUMBER PREFIXED THREE
#define UC_MACRO_NAME_1ECA6 0x1ECA6 // 𞲦 INDIC SIYAQ NUMBER PREFIXED FOUR
#define UC_MACRO_NAME_1ECA7 0x1ECA7 // 𞲧 INDIC SIYAQ NUMBER PREFIXED FIVE
#define UC_MACRO_NAME_1ECA8 0x1ECA8 // 𞲨 INDIC SIYAQ NUMBER PREFIXED SIX
#define UC_MACRO_NAME_1ECA9 0x1ECA9 // 𞲩 INDIC SIYAQ NUMBER PREFIXED SEVEN
#define UC_MACRO_NAME_1ECAA 0x1ECAA // 𞲪 INDIC SIYAQ NUMBER PREFIXED EIGHT
#define UC_MACRO_NAME_1ECAB 0x1ECAB // 𞲫 INDIC SIYAQ NUMBER PREFIXED NINE
#define UC_MACRO_NAME_1ECAC 0x1ECAC // 𞲬 INDIC SIYAQ PLACEHOLDER
#define UC_MACRO_NAME_1ECAD 0x1ECAD // 𞲭 INDIC SIYAQ FRACTION ONE QUARTER
#define UC_MACRO_NAME_1ECAE 0x1ECAE // 𞲮 INDIC SIYAQ FRACTION ONE HALF
#define UC_MACRO_NAME_1ECAF 0x1ECAF // 𞲯 INDIC SIYAQ FRACTION THREE QUARTERS
#define UC_MACRO_NAME_1ECB0 0x1ECB0 // 𞲰 INDIC SIYAQ RUPEE MARK
#define UC_MACRO_NAME_1ECB1 0x1ECB1 // 𞲱 INDIC SIYAQ NUMBER ALTERNATE ONE
#define UC_MACRO_NAME_1ECB2 0x1ECB2 // 𞲲 INDIC SIYAQ NUMBER ALTERNATE TWO
#define UC_MACRO_NAME_1ECB3 0x1ECB3 // 𞲳 INDIC SIYAQ NUMBER ALTERNATE TEN THOUSAND
#define UC_MACRO_NAME_1ECB4 0x1ECB4 // 𞲴 INDIC SIYAQ ALTERNATE LAKH MARK


#endif // UC_H_INDIC_SIYAQ_NUMBERS
