/*
 * Unicode Block: Inscriptional Pahlavi
 * Range: U+10B60..U+10B7F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Inscriptional Pahlavi is the earliest attested form of Pahlavi scripts
 * , and is evident in clay fragments that have been dated to the reign
 * of Mithridates I ( r. 171–138 BC). Other early evidence includes the
 * Pahlavi inscriptions of Parthian coins and the rock inscriptions of
 * Sasanian emperors and other notables, such as Kartir the High Priest .
 *
 */
#ifndef UC_H_INSCRIPTIONAL_PAHLAVI
#define UC_H_INSCRIPTIONAL_PAHLAVI

#define UC_MACRO_NAME_10B60 0x10B60 // 𐭠 INSCRIPTIONAL PAHLAVI LETTER ALEPH
#define UC_MACRO_NAME_10B61 0x10B61 // 𐭡 INSCRIPTIONAL PAHLAVI LETTER BETH
#define UC_MACRO_NAME_10B62 0x10B62 // 𐭢 INSCRIPTIONAL PAHLAVI LETTER GIMEL
#define UC_MACRO_NAME_10B63 0x10B63 // 𐭣 INSCRIPTIONAL PAHLAVI LETTER DALETH
#define UC_MACRO_NAME_10B64 0x10B64 // 𐭤 INSCRIPTIONAL PAHLAVI LETTER HE
#define UC_MACRO_NAME_10B65 0x10B65 // 𐭥 INSCRIPTIONAL PAHLAVI LETTER WAW-AYIN-RESH
#define UC_MACRO_NAME_10B66 0x10B66 // 𐭦 INSCRIPTIONAL PAHLAVI LETTER ZAYIN
#define UC_MACRO_NAME_10B67 0x10B67 // 𐭧 INSCRIPTIONAL PAHLAVI LETTER HETH
#define UC_MACRO_NAME_10B68 0x10B68 // 𐭨 INSCRIPTIONAL PAHLAVI LETTER TETH
#define UC_MACRO_NAME_10B69 0x10B69 // 𐭩 INSCRIPTIONAL PAHLAVI LETTER YODH
#define UC_MACRO_NAME_10B6A 0x10B6A // 𐭪 INSCRIPTIONAL PAHLAVI LETTER KAPH
#define UC_MACRO_NAME_10B6B 0x10B6B // 𐭫 INSCRIPTIONAL PAHLAVI LETTER LAMEDH
#define UC_MACRO_NAME_10B6C 0x10B6C // 𐭬 INSCRIPTIONAL PAHLAVI LETTER MEM-QOPH
#define UC_MACRO_NAME_10B6D 0x10B6D // 𐭭 INSCRIPTIONAL PAHLAVI LETTER NUN
#define UC_MACRO_NAME_10B6E 0x10B6E // 𐭮 INSCRIPTIONAL PAHLAVI LETTER SAMEKH
#define UC_MACRO_NAME_10B6F 0x10B6F // 𐭯 INSCRIPTIONAL PAHLAVI LETTER PE
#define UC_MACRO_NAME_10B70 0x10B70 // 𐭰 INSCRIPTIONAL PAHLAVI LETTER SADHE
#define UC_MACRO_NAME_10B71 0x10B71 // 𐭱 INSCRIPTIONAL PAHLAVI LETTER SHIN
#define UC_MACRO_NAME_10B72 0x10B72 // 𐭲 INSCRIPTIONAL PAHLAVI LETTER TAW
#define UC_MACRO_NAME_10B78 0x10B78 // 𐭸 INSCRIPTIONAL PAHLAVI NUMBER ONE
#define UC_MACRO_NAME_10B79 0x10B79 // 𐭹 INSCRIPTIONAL PAHLAVI NUMBER TWO
#define UC_MACRO_NAME_10B7A 0x10B7A // 𐭺 INSCRIPTIONAL PAHLAVI NUMBER THREE
#define UC_MACRO_NAME_10B7B 0x10B7B // 𐭻 INSCRIPTIONAL PAHLAVI NUMBER FOUR
#define UC_MACRO_NAME_10B7C 0x10B7C // 𐭼 INSCRIPTIONAL PAHLAVI NUMBER TEN
#define UC_MACRO_NAME_10B7D 0x10B7D // 𐭽 INSCRIPTIONAL PAHLAVI NUMBER TWENTY
#define UC_MACRO_NAME_10B7E 0x10B7E // 𐭾 INSCRIPTIONAL PAHLAVI NUMBER ONE HUNDRED
#define UC_MACRO_NAME_10B7F 0x10B7F // 𐭿 INSCRIPTIONAL PAHLAVI NUMBER ONE THOUSAND


#endif // UC_H_INSCRIPTIONAL_PAHLAVI
