/*
 * Unicode Block: Javanese
 * Range: U+A980..U+A9DF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Javanese may refer to:
 *
 */
#ifndef UC_H_JAVANESE
#define UC_H_JAVANESE

#define UC_MACRO_NAME_A980 0xA980 // ꦀ JAVANESE SIGN PANYANGGA
#define UC_MACRO_NAME_A981 0xA981 // ꦁ JAVANESE SIGN CECAK
#define UC_MACRO_NAME_A982 0xA982 // ꦂ JAVANESE SIGN LAYAR
#define UC_MACRO_NAME_A983 0xA983 // ꦃ JAVANESE SIGN WIGNYAN
#define UC_MACRO_NAME_A984 0xA984 // ꦄ JAVANESE LETTER A
#define UC_MACRO_NAME_A985 0xA985 // ꦅ JAVANESE LETTER I KAWI
#define UC_MACRO_NAME_A986 0xA986 // ꦆ JAVANESE LETTER I
#define UC_MACRO_NAME_A987 0xA987 // ꦇ JAVANESE LETTER II
#define UC_MACRO_NAME_A988 0xA988 // ꦈ JAVANESE LETTER U
#define UC_MACRO_NAME_A989 0xA989 // ꦉ JAVANESE LETTER PA CEREK
#define UC_MACRO_NAME_A98A 0xA98A // ꦊ JAVANESE LETTER NGA LELET
#define UC_MACRO_NAME_A98B 0xA98B // ꦋ JAVANESE LETTER NGA LELET RASWADI
#define UC_MACRO_NAME_A98C 0xA98C // ꦌ JAVANESE LETTER E
#define UC_MACRO_NAME_A98D 0xA98D // ꦍ JAVANESE LETTER AI
#define UC_MACRO_NAME_A98E 0xA98E // ꦎ JAVANESE LETTER O
#define UC_MACRO_NAME_A98F 0xA98F // ꦏ JAVANESE LETTER KA
#define UC_MACRO_NAME_A990 0xA990 // ꦐ JAVANESE LETTER KA SASAK
#define UC_MACRO_NAME_A991 0xA991 // ꦑ JAVANESE LETTER KA MURDA
#define UC_MACRO_NAME_A992 0xA992 // ꦒ JAVANESE LETTER GA
#define UC_MACRO_NAME_A993 0xA993 // ꦓ JAVANESE LETTER GA MURDA
#define UC_MACRO_NAME_A994 0xA994 // ꦔ JAVANESE LETTER NGA
#define UC_MACRO_NAME_A995 0xA995 // ꦕ JAVANESE LETTER CA
#define UC_MACRO_NAME_A996 0xA996 // ꦖ JAVANESE LETTER CA MURDA
#define UC_MACRO_NAME_A997 0xA997 // ꦗ JAVANESE LETTER JA
#define UC_MACRO_NAME_A998 0xA998 // ꦘ JAVANESE LETTER NYA MURDA
#define UC_MACRO_NAME_A999 0xA999 // ꦙ JAVANESE LETTER JA MAHAPRANA
#define UC_MACRO_NAME_A99A 0xA99A // ꦚ JAVANESE LETTER NYA
#define UC_MACRO_NAME_A99B 0xA99B // ꦛ JAVANESE LETTER TTA
#define UC_MACRO_NAME_A99C 0xA99C // ꦜ JAVANESE LETTER TTA MAHAPRANA
#define UC_MACRO_NAME_A99D 0xA99D // ꦝ JAVANESE LETTER DDA
#define UC_MACRO_NAME_A99E 0xA99E // ꦞ JAVANESE LETTER DDA MAHAPRANA
#define UC_MACRO_NAME_A99F 0xA99F // ꦟ JAVANESE LETTER NA MURDA
#define UC_MACRO_NAME_A9A0 0xA9A0 // ꦠ JAVANESE LETTER TA
#define UC_MACRO_NAME_A9A1 0xA9A1 // ꦡ JAVANESE LETTER TA MURDA
#define UC_MACRO_NAME_A9A2 0xA9A2 // ꦢ JAVANESE LETTER DA
#define UC_MACRO_NAME_A9A3 0xA9A3 // ꦣ JAVANESE LETTER DA MAHAPRANA
#define UC_MACRO_NAME_A9A4 0xA9A4 // ꦤ JAVANESE LETTER NA
#define UC_MACRO_NAME_A9A5 0xA9A5 // ꦥ JAVANESE LETTER PA
#define UC_MACRO_NAME_A9A6 0xA9A6 // ꦦ JAVANESE LETTER PA MURDA
#define UC_MACRO_NAME_A9A7 0xA9A7 // ꦧ JAVANESE LETTER BA
#define UC_MACRO_NAME_A9A8 0xA9A8 // ꦨ JAVANESE LETTER BA MURDA
#define UC_MACRO_NAME_A9A9 0xA9A9 // ꦩ JAVANESE LETTER MA
#define UC_MACRO_NAME_A9AA 0xA9AA // ꦪ JAVANESE LETTER YA
#define UC_MACRO_NAME_A9AB 0xA9AB // ꦫ JAVANESE LETTER RA
#define UC_MACRO_NAME_A9AC 0xA9AC // ꦬ JAVANESE LETTER RA AGUNG
#define UC_MACRO_NAME_A9AD 0xA9AD // ꦭ JAVANESE LETTER LA
#define UC_MACRO_NAME_A9AE 0xA9AE // ꦮ JAVANESE LETTER WA
#define UC_MACRO_NAME_A9AF 0xA9AF // ꦯ JAVANESE LETTER SA MURDA
#define UC_MACRO_NAME_A9B0 0xA9B0 // ꦰ JAVANESE LETTER SA MAHAPRANA
#define UC_MACRO_NAME_A9B1 0xA9B1 // ꦱ JAVANESE LETTER SA
#define UC_MACRO_NAME_A9B2 0xA9B2 // ꦲ JAVANESE LETTER HA
#define UC_MACRO_NAME_A9B3 0xA9B3 // ꦳ JAVANESE SIGN CECAK TELU
#define UC_MACRO_NAME_A9B4 0xA9B4 // ꦴ JAVANESE VOWEL SIGN TARUNG
#define UC_MACRO_NAME_A9B5 0xA9B5 // ꦵ JAVANESE VOWEL SIGN TOLONG
#define UC_MACRO_NAME_A9B6 0xA9B6 // ꦶ JAVANESE VOWEL SIGN WULU
#define UC_MACRO_NAME_A9B7 0xA9B7 // ꦷ JAVANESE VOWEL SIGN WULU MELIK
#define UC_MACRO_NAME_A9B8 0xA9B8 // ꦸ JAVANESE VOWEL SIGN SUKU
#define UC_MACRO_NAME_A9B9 0xA9B9 // ꦹ JAVANESE VOWEL SIGN SUKU MENDUT
#define UC_MACRO_NAME_A9BA 0xA9BA // ꦺ JAVANESE VOWEL SIGN TALING
#define UC_MACRO_NAME_A9BB 0xA9BB // ꦻ JAVANESE VOWEL SIGN DIRGA MURE
#define UC_MACRO_NAME_A9BC 0xA9BC // ꦼ JAVANESE VOWEL SIGN PEPET
#define UC_MACRO_NAME_A9BD 0xA9BD // ꦽ JAVANESE CONSONANT SIGN KERET
#define UC_MACRO_NAME_A9BE 0xA9BE // ꦾ JAVANESE CONSONANT SIGN PENGKAL
#define UC_MACRO_NAME_A9BF 0xA9BF // ꦿ JAVANESE CONSONANT SIGN CAKRA
#define UC_MACRO_NAME_A9C0 0xA9C0 // ꧀ JAVANESE PANGKON
#define UC_MACRO_NAME_A9C1 0xA9C1 // ꧁ JAVANESE LEFT RERENGGAN
#define UC_MACRO_NAME_A9C2 0xA9C2 // ꧂ JAVANESE RIGHT RERENGGAN
#define UC_MACRO_NAME_A9C3 0xA9C3 // ꧃ JAVANESE PADA ANDAP
#define UC_MACRO_NAME_A9C4 0xA9C4 // ꧄ JAVANESE PADA MADYA
#define UC_MACRO_NAME_A9C5 0xA9C5 // ꧅ JAVANESE PADA LUHUR
#define UC_MACRO_NAME_A9C6 0xA9C6 // ꧆ JAVANESE PADA WINDU
#define UC_MACRO_NAME_A9C7 0xA9C7 // ꧇ JAVANESE PADA PANGKAT
#define UC_MACRO_NAME_A9C8 0xA9C8 // ꧈ JAVANESE PADA LINGSA
#define UC_MACRO_NAME_A9C9 0xA9C9 // ꧉ JAVANESE PADA LUNGSI
#define UC_MACRO_NAME_A9CA 0xA9CA // ꧊ JAVANESE PADA ADEG
#define UC_MACRO_NAME_A9CB 0xA9CB // ꧋ JAVANESE PADA ADEG ADEG
#define UC_MACRO_NAME_A9CC 0xA9CC // ꧌ JAVANESE PADA PISELEH
#define UC_MACRO_NAME_A9CD 0xA9CD // ꧍ JAVANESE TURNED PADA PISELEH
#define UC_MACRO_NAME_A9CF 0xA9CF // ꧏ JAVANESE PANGRANGKEP
#define UC_MACRO_NAME_A9D0 0xA9D0 // ꧐ JAVANESE DIGIT ZERO
#define UC_MACRO_NAME_A9D1 0xA9D1 // ꧑ JAVANESE DIGIT ONE
#define UC_MACRO_NAME_A9D2 0xA9D2 // ꧒ JAVANESE DIGIT TWO
#define UC_MACRO_NAME_A9D3 0xA9D3 // ꧓ JAVANESE DIGIT THREE
#define UC_MACRO_NAME_A9D4 0xA9D4 // ꧔ JAVANESE DIGIT FOUR
#define UC_MACRO_NAME_A9D5 0xA9D5 // ꧕ JAVANESE DIGIT FIVE
#define UC_MACRO_NAME_A9D6 0xA9D6 // ꧖ JAVANESE DIGIT SIX
#define UC_MACRO_NAME_A9D7 0xA9D7 // ꧗ JAVANESE DIGIT SEVEN
#define UC_MACRO_NAME_A9D8 0xA9D8 // ꧘ JAVANESE DIGIT EIGHT
#define UC_MACRO_NAME_A9D9 0xA9D9 // ꧙ JAVANESE DIGIT NINE
#define UC_MACRO_NAME_A9DE 0xA9DE // ꧞ JAVANESE PADA TIRTA TUMETES
#define UC_MACRO_NAME_A9DF 0xA9DF // ꧟ JAVANESE PADA ISEN-ISEN


#endif // UC_H_JAVANESE
