/*
 * Unicode Block: Kayah Li
 * Range: U+A900..U+A92F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * The Kayah Li alphabet (Kayah Li: ꤊꤢꤛꤢ꤭ ꤜꤟꤤ꤬ ) is used to write the
 * Kayah languages Eastern Kayah Li and Western Kayah Li , which are
 * members of Karenic branch of the Sino-Tibetan language family . They
 * are also known as Red Karen and Karenni . Eastern Kayah Li is spoken
 * by about 26,000 people, and Western Kayah Li by about 100,000 people,
 * mostly in the Kayah and Karen states of Myanmar , but also by people
 * living in Thailand .
 *
 */
#ifndef UC_H_KAYAH_LI
#define UC_H_KAYAH_LI

#define UC_MACRO_NAME_A900 0xA900 // ꤀ KAYAH LI DIGIT ZERO
#define UC_MACRO_NAME_A901 0xA901 // ꤁ KAYAH LI DIGIT ONE
#define UC_MACRO_NAME_A902 0xA902 // ꤂ KAYAH LI DIGIT TWO
#define UC_MACRO_NAME_A903 0xA903 // ꤃ KAYAH LI DIGIT THREE
#define UC_MACRO_NAME_A904 0xA904 // ꤄ KAYAH LI DIGIT FOUR
#define UC_MACRO_NAME_A905 0xA905 // ꤅ KAYAH LI DIGIT FIVE
#define UC_MACRO_NAME_A906 0xA906 // ꤆ KAYAH LI DIGIT SIX
#define UC_MACRO_NAME_A907 0xA907 // ꤇ KAYAH LI DIGIT SEVEN
#define UC_MACRO_NAME_A908 0xA908 // ꤈ KAYAH LI DIGIT EIGHT
#define UC_MACRO_NAME_A909 0xA909 // ꤉ KAYAH LI DIGIT NINE
#define UC_MACRO_NAME_A90A 0xA90A // ꤊ KAYAH LI LETTER KA
#define UC_MACRO_NAME_A90B 0xA90B // ꤋ KAYAH LI LETTER KHA
#define UC_MACRO_NAME_A90C 0xA90C // ꤌ KAYAH LI LETTER GA
#define UC_MACRO_NAME_A90D 0xA90D // ꤍ KAYAH LI LETTER NGA
#define UC_MACRO_NAME_A90E 0xA90E // ꤎ KAYAH LI LETTER SA
#define UC_MACRO_NAME_A90F 0xA90F // ꤏ KAYAH LI LETTER SHA
#define UC_MACRO_NAME_A910 0xA910 // ꤐ KAYAH LI LETTER ZA
#define UC_MACRO_NAME_A911 0xA911 // ꤑ KAYAH LI LETTER NYA
#define UC_MACRO_NAME_A912 0xA912 // ꤒ KAYAH LI LETTER TA
#define UC_MACRO_NAME_A913 0xA913 // ꤓ KAYAH LI LETTER HTA
#define UC_MACRO_NAME_A914 0xA914 // ꤔ KAYAH LI LETTER NA
#define UC_MACRO_NAME_A915 0xA915 // ꤕ KAYAH LI LETTER PA
#define UC_MACRO_NAME_A916 0xA916 // ꤖ KAYAH LI LETTER PHA
#define UC_MACRO_NAME_A917 0xA917 // ꤗ KAYAH LI LETTER MA
#define UC_MACRO_NAME_A918 0xA918 // ꤘ KAYAH LI LETTER DA
#define UC_MACRO_NAME_A919 0xA919 // ꤙ KAYAH LI LETTER BA
#define UC_MACRO_NAME_A91A 0xA91A // ꤚ KAYAH LI LETTER RA
#define UC_MACRO_NAME_A91B 0xA91B // ꤛ KAYAH LI LETTER YA
#define UC_MACRO_NAME_A91C 0xA91C // ꤜ KAYAH LI LETTER LA
#define UC_MACRO_NAME_A91D 0xA91D // ꤝ KAYAH LI LETTER WA
#define UC_MACRO_NAME_A91E 0xA91E // ꤞ KAYAH LI LETTER THA
#define UC_MACRO_NAME_A91F 0xA91F // ꤟ KAYAH LI LETTER HA
#define UC_MACRO_NAME_A920 0xA920 // ꤠ KAYAH LI LETTER VA
#define UC_MACRO_NAME_A921 0xA921 // ꤡ KAYAH LI LETTER CA
#define UC_MACRO_NAME_A922 0xA922 // ꤢ KAYAH LI LETTER A
#define UC_MACRO_NAME_A923 0xA923 // ꤣ KAYAH LI LETTER OE
#define UC_MACRO_NAME_A924 0xA924 // ꤤ KAYAH LI LETTER I
#define UC_MACRO_NAME_A925 0xA925 // ꤥ KAYAH LI LETTER OO
#define UC_MACRO_NAME_A926 0xA926 // ꤦ KAYAH LI VOWEL UE
#define UC_MACRO_NAME_A927 0xA927 // ꤧ KAYAH LI VOWEL E
#define UC_MACRO_NAME_A928 0xA928 // ꤨ KAYAH LI VOWEL U
#define UC_MACRO_NAME_A929 0xA929 // ꤩ KAYAH LI VOWEL EE
#define UC_MACRO_NAME_A92A 0xA92A // ꤪ KAYAH LI VOWEL O
#define UC_MACRO_NAME_A92B 0xA92B // ꤫ KAYAH LI TONE PLOPHU
#define UC_MACRO_NAME_A92C 0xA92C // ꤬ KAYAH LI TONE CALYA
#define UC_MACRO_NAME_A92D 0xA92D // ꤭ KAYAH LI TONE CALYA PLOPHU
#define UC_MACRO_NAME_A92E 0xA92E // ꤮ KAYAH LI SIGN CWI
#define UC_MACRO_NAME_A92F 0xA92F // ꤯ KAYAH LI SIGN SHYA


#endif // UC_H_KAYAH_LI
