/*
 * Unicode Block: Khmer Symbols
 * Range: U+19E0..U+19FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Khmer Symbols is a Unicode block containing lunar date symbols, used
 * in the writing system of the Khmer (Cambodian) language. For further
 * details see Khmer alphabet – Unicode .
 * The following Unicode-related documents record the purpose and process
 * of defining specific characters in the Khmer Symbols block:
 *
 */
#ifndef UC_H_KHMER_SYMBOLS
#define UC_H_KHMER_SYMBOLS

#define UC_MACRO_NAME_19E0 0x19E0 // ᧠ KHMER SYMBOL PATHAMASAT
#define UC_MACRO_NAME_19E1 0x19E1 // ᧡ KHMER SYMBOL MUOY KOET
#define UC_MACRO_NAME_19E2 0x19E2 // ᧢ KHMER SYMBOL PII KOET
#define UC_MACRO_NAME_19E3 0x19E3 // ᧣ KHMER SYMBOL BEI KOET
#define UC_MACRO_NAME_19E4 0x19E4 // ᧤ KHMER SYMBOL BUON KOET
#define UC_MACRO_NAME_19E5 0x19E5 // ᧥ KHMER SYMBOL PRAM KOET
#define UC_MACRO_NAME_19E6 0x19E6 // ᧦ KHMER SYMBOL PRAM-MUOY KOET
#define UC_MACRO_NAME_19E7 0x19E7 // ᧧ KHMER SYMBOL PRAM-PII KOET
#define UC_MACRO_NAME_19E8 0x19E8 // ᧨ KHMER SYMBOL PRAM-BEI KOET
#define UC_MACRO_NAME_19E9 0x19E9 // ᧩ KHMER SYMBOL PRAM-BUON KOET
#define UC_MACRO_NAME_19EA 0x19EA // ᧪ KHMER SYMBOL DAP KOET
#define UC_MACRO_NAME_19EB 0x19EB // ᧫ KHMER SYMBOL DAP-MUOY KOET
#define UC_MACRO_NAME_19EC 0x19EC // ᧬ KHMER SYMBOL DAP-PII KOET
#define UC_MACRO_NAME_19ED 0x19ED // ᧭ KHMER SYMBOL DAP-BEI KOET
#define UC_MACRO_NAME_19EE 0x19EE // ᧮ KHMER SYMBOL DAP-BUON KOET
#define UC_MACRO_NAME_19EF 0x19EF // ᧯ KHMER SYMBOL DAP-PRAM KOET
#define UC_MACRO_NAME_19F0 0x19F0 // ᧰ KHMER SYMBOL TUTEYASAT
#define UC_MACRO_NAME_19F1 0x19F1 // ᧱ KHMER SYMBOL MUOY ROC
#define UC_MACRO_NAME_19F2 0x19F2 // ᧲ KHMER SYMBOL PII ROC
#define UC_MACRO_NAME_19F3 0x19F3 // ᧳ KHMER SYMBOL BEI ROC
#define UC_MACRO_NAME_19F4 0x19F4 // ᧴ KHMER SYMBOL BUON ROC
#define UC_MACRO_NAME_19F5 0x19F5 // ᧵ KHMER SYMBOL PRAM ROC
#define UC_MACRO_NAME_19F6 0x19F6 // ᧶ KHMER SYMBOL PRAM-MUOY ROC
#define UC_MACRO_NAME_19F7 0x19F7 // ᧷ KHMER SYMBOL PRAM-PII ROC
#define UC_MACRO_NAME_19F8 0x19F8 // ᧸ KHMER SYMBOL PRAM-BEI ROC
#define UC_MACRO_NAME_19F9 0x19F9 // ᧹ KHMER SYMBOL PRAM-BUON ROC
#define UC_MACRO_NAME_19FA 0x19FA // ᧺ KHMER SYMBOL DAP ROC
#define UC_MACRO_NAME_19FB 0x19FB // ᧻ KHMER SYMBOL DAP-MUOY ROC
#define UC_MACRO_NAME_19FC 0x19FC // ᧼ KHMER SYMBOL DAP-PII ROC
#define UC_MACRO_NAME_19FD 0x19FD // ᧽ KHMER SYMBOL DAP-BEI ROC
#define UC_MACRO_NAME_19FE 0x19FE // ᧾ KHMER SYMBOL DAP-BUON ROC
#define UC_MACRO_NAME_19FF 0x19FF // ᧿ KHMER SYMBOL DAP-PRAM ROC


#endif // UC_H_KHMER_SYMBOLS
