/*
 * Unicode Block: Katakana
 * Range: U+30A0..U+30FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Katakana ( 片仮名 , カタカナ ; IPA: ) is a Japanese syllabary , one component
 * of the Japanese writing system along with hiragana , kanji and in some
 * cases the Latin script (known as rōmaji ).
 * The word katakana means "fragmentary kana", as the katakana characters
 * are derived from components or fragments of more complex kanji.
 * Katakana and hiragana are both kana systems. With one or two minor
 * exceptions, each syllable (strictly mora ) in the Japanese language is
 * represented by one character or kana in each system. Each kana
 * represents either a vowel such as " a " (katakana ア ); a consonant
 * followed by a vowel such as " ka " (katakana カ ); or " n " (katakana ン
 * ), a nasal sonorant which, depending on the context, sounds like
 * English m , n or ng ( ) or like the nasal vowels of Portuguese or
 * Galician .
 *
 */
#ifndef UC_H_KATAKANA
#define UC_H_KATAKANA

#define UC_MACRO_NAME_30A0 0x30A0 // ゠ KATAKANA-HIRAGANA DOUBLE HYPHEN
#define UC_MACRO_NAME_30A1 0x30A1 // ァ KATAKANA LETTER SMALL A
#define UC_MACRO_NAME_30A2 0x30A2 // ア KATAKANA LETTER A
#define UC_MACRO_NAME_30A3 0x30A3 // ィ KATAKANA LETTER SMALL I
#define UC_MACRO_NAME_30A4 0x30A4 // イ KATAKANA LETTER I
#define UC_MACRO_NAME_30A5 0x30A5 // ゥ KATAKANA LETTER SMALL U
#define UC_MACRO_NAME_30A6 0x30A6 // ウ KATAKANA LETTER U
#define UC_MACRO_NAME_30A7 0x30A7 // ェ KATAKANA LETTER SMALL E
#define UC_MACRO_NAME_30A8 0x30A8 // エ KATAKANA LETTER E
#define UC_MACRO_NAME_30A9 0x30A9 // ォ KATAKANA LETTER SMALL O
#define UC_MACRO_NAME_30AA 0x30AA // オ KATAKANA LETTER O
#define UC_MACRO_NAME_30AB 0x30AB // カ KATAKANA LETTER KA
#define UC_MACRO_NAME_30AC 0x30AC // ガ KATAKANA LETTER GA
#define UC_MACRO_NAME_30AD 0x30AD // キ KATAKANA LETTER KI
#define UC_MACRO_NAME_30AE 0x30AE // ギ KATAKANA LETTER GI
#define UC_MACRO_NAME_30AF 0x30AF // ク KATAKANA LETTER KU
#define UC_MACRO_NAME_30B0 0x30B0 // グ KATAKANA LETTER GU
#define UC_MACRO_NAME_30B1 0x30B1 // ケ KATAKANA LETTER KE
#define UC_MACRO_NAME_30B2 0x30B2 // ゲ KATAKANA LETTER GE
#define UC_MACRO_NAME_30B3 0x30B3 // コ KATAKANA LETTER KO
#define UC_MACRO_NAME_30B4 0x30B4 // ゴ KATAKANA LETTER GO
#define UC_MACRO_NAME_30B5 0x30B5 // サ KATAKANA LETTER SA
#define UC_MACRO_NAME_30B6 0x30B6 // ザ KATAKANA LETTER ZA
#define UC_MACRO_NAME_30B7 0x30B7 // シ KATAKANA LETTER SI
#define UC_MACRO_NAME_30B8 0x30B8 // ジ KATAKANA LETTER ZI
#define UC_MACRO_NAME_30B9 0x30B9 // ス KATAKANA LETTER SU
#define UC_MACRO_NAME_30BA 0x30BA // ズ KATAKANA LETTER ZU
#define UC_MACRO_NAME_30BB 0x30BB // セ KATAKANA LETTER SE
#define UC_MACRO_NAME_30BC 0x30BC // ゼ KATAKANA LETTER ZE
#define UC_MACRO_NAME_30BD 0x30BD // ソ KATAKANA LETTER SO
#define UC_MACRO_NAME_30BE 0x30BE // ゾ KATAKANA LETTER ZO
#define UC_MACRO_NAME_30BF 0x30BF // タ KATAKANA LETTER TA
#define UC_MACRO_NAME_30C0 0x30C0 // ダ KATAKANA LETTER DA
#define UC_MACRO_NAME_30C1 0x30C1 // チ KATAKANA LETTER TI
#define UC_MACRO_NAME_30C2 0x30C2 // ヂ KATAKANA LETTER DI
#define UC_MACRO_NAME_30C3 0x30C3 // ッ KATAKANA LETTER SMALL TU
#define UC_MACRO_NAME_30C4 0x30C4 // ツ KATAKANA LETTER TU
#define UC_MACRO_NAME_30C5 0x30C5 // ヅ KATAKANA LETTER DU
#define UC_MACRO_NAME_30C6 0x30C6 // テ KATAKANA LETTER TE
#define UC_MACRO_NAME_30C7 0x30C7 // デ KATAKANA LETTER DE
#define UC_MACRO_NAME_30C8 0x30C8 // ト KATAKANA LETTER TO
#define UC_MACRO_NAME_30C9 0x30C9 // ド KATAKANA LETTER DO
#define UC_MACRO_NAME_30CA 0x30CA // ナ KATAKANA LETTER NA
#define UC_MACRO_NAME_30CB 0x30CB // ニ KATAKANA LETTER NI
#define UC_MACRO_NAME_30CC 0x30CC // ヌ KATAKANA LETTER NU
#define UC_MACRO_NAME_30CD 0x30CD // ネ KATAKANA LETTER NE
#define UC_MACRO_NAME_30CE 0x30CE // ノ KATAKANA LETTER NO
#define UC_MACRO_NAME_30CF 0x30CF // ハ KATAKANA LETTER HA
#define UC_MACRO_NAME_30D0 0x30D0 // バ KATAKANA LETTER BA
#define UC_MACRO_NAME_30D1 0x30D1 // パ KATAKANA LETTER PA
#define UC_MACRO_NAME_30D2 0x30D2 // ヒ KATAKANA LETTER HI
#define UC_MACRO_NAME_30D3 0x30D3 // ビ KATAKANA LETTER BI
#define UC_MACRO_NAME_30D4 0x30D4 // ピ KATAKANA LETTER PI
#define UC_MACRO_NAME_30D5 0x30D5 // フ KATAKANA LETTER HU
#define UC_MACRO_NAME_30D6 0x30D6 // ブ KATAKANA LETTER BU
#define UC_MACRO_NAME_30D7 0x30D7 // プ KATAKANA LETTER PU
#define UC_MACRO_NAME_30D8 0x30D8 // ヘ KATAKANA LETTER HE
#define UC_MACRO_NAME_30D9 0x30D9 // ベ KATAKANA LETTER BE
#define UC_MACRO_NAME_30DA 0x30DA // ペ KATAKANA LETTER PE
#define UC_MACRO_NAME_30DB 0x30DB // ホ KATAKANA LETTER HO
#define UC_MACRO_NAME_30DC 0x30DC // ボ KATAKANA LETTER BO
#define UC_MACRO_NAME_30DD 0x30DD // ポ KATAKANA LETTER PO
#define UC_MACRO_NAME_30DE 0x30DE // マ KATAKANA LETTER MA
#define UC_MACRO_NAME_30DF 0x30DF // ミ KATAKANA LETTER MI
#define UC_MACRO_NAME_30E0 0x30E0 // ム KATAKANA LETTER MU
#define UC_MACRO_NAME_30E1 0x30E1 // メ KATAKANA LETTER ME
#define UC_MACRO_NAME_30E2 0x30E2 // モ KATAKANA LETTER MO
#define UC_MACRO_NAME_30E3 0x30E3 // ャ KATAKANA LETTER SMALL YA
#define UC_MACRO_NAME_30E4 0x30E4 // ヤ KATAKANA LETTER YA
#define UC_MACRO_NAME_30E5 0x30E5 // ュ KATAKANA LETTER SMALL YU
#define UC_MACRO_NAME_30E6 0x30E6 // ユ KATAKANA LETTER YU
#define UC_MACRO_NAME_30E7 0x30E7 // ョ KATAKANA LETTER SMALL YO
#define UC_MACRO_NAME_30E8 0x30E8 // ヨ KATAKANA LETTER YO
#define UC_MACRO_NAME_30E9 0x30E9 // ラ KATAKANA LETTER RA
#define UC_MACRO_NAME_30EA 0x30EA // リ KATAKANA LETTER RI
#define UC_MACRO_NAME_30EB 0x30EB // ル KATAKANA LETTER RU
#define UC_MACRO_NAME_30EC 0x30EC // レ KATAKANA LETTER RE
#define UC_MACRO_NAME_30ED 0x30ED // ロ KATAKANA LETTER RO
#define UC_MACRO_NAME_30EE 0x30EE // ヮ KATAKANA LETTER SMALL WA
#define UC_MACRO_NAME_30EF 0x30EF // ワ KATAKANA LETTER WA
#define UC_MACRO_NAME_30F0 0x30F0 // ヰ KATAKANA LETTER WI
#define UC_MACRO_NAME_30F1 0x30F1 // ヱ KATAKANA LETTER WE
#define UC_MACRO_NAME_30F2 0x30F2 // ヲ KATAKANA LETTER WO
#define UC_MACRO_NAME_30F3 0x30F3 // ン KATAKANA LETTER N
#define UC_MACRO_NAME_30F4 0x30F4 // ヴ KATAKANA LETTER VU
#define UC_MACRO_NAME_30F5 0x30F5 // ヵ KATAKANA LETTER SMALL KA
#define UC_MACRO_NAME_30F6 0x30F6 // ヶ KATAKANA LETTER SMALL KE
#define UC_MACRO_NAME_30F7 0x30F7 // ヷ KATAKANA LETTER VA
#define UC_MACRO_NAME_30F8 0x30F8 // ヸ KATAKANA LETTER VI
#define UC_MACRO_NAME_30F9 0x30F9 // ヹ KATAKANA LETTER VE
#define UC_MACRO_NAME_30FA 0x30FA // ヺ KATAKANA LETTER VO
#define UC_MACRO_NAME_30FB 0x30FB // ・ KATAKANA MIDDLE DOT
#define UC_MACRO_NAME_30FC 0x30FC // ー KATAKANA-HIRAGANA PROLONGED SOUND MARK
#define UC_MACRO_NAME_30FD 0x30FD // ヽ KATAKANA ITERATION MARK
#define UC_MACRO_NAME_30FE 0x30FE // ヾ KATAKANA VOICED ITERATION MARK
#define UC_MACRO_NAME_30FF 0x30FF // ヿ KATAKANA DIGRAPH KOTO


#endif // UC_H_KATAKANA
