/*
 * Unicode Block: Kana Extended-B
 * Range: U+1AFF0..U+1AFFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_KANA_EXTENDED_B
#define UC_H_KANA_EXTENDED_B

#define UC_MACRO_NAME_1AFF0 0x1AFF0 // 𚿰 KATAKANA LETTER MINNAN TONE-2
#define UC_MACRO_NAME_1AFF1 0x1AFF1 // 𚿱 KATAKANA LETTER MINNAN TONE-3
#define UC_MACRO_NAME_1AFF2 0x1AFF2 // 𚿲 KATAKANA LETTER MINNAN TONE-4
#define UC_MACRO_NAME_1AFF3 0x1AFF3 // 𚿳 KATAKANA LETTER MINNAN TONE-5
#define UC_MACRO_NAME_1AFF5 0x1AFF5 // 𚿵 KATAKANA LETTER MINNAN TONE-7
#define UC_MACRO_NAME_1AFF6 0x1AFF6 // 𚿶 KATAKANA LETTER MINNAN TONE-8
#define UC_MACRO_NAME_1AFF7 0x1AFF7 // 𚿷 KATAKANA LETTER MINNAN NASALIZED TONE-1
#define UC_MACRO_NAME_1AFF8 0x1AFF8 // 𚿸 KATAKANA LETTER MINNAN NASALIZED TONE-2
#define UC_MACRO_NAME_1AFF9 0x1AFF9 // 𚿹 KATAKANA LETTER MINNAN NASALIZED TONE-3
#define UC_MACRO_NAME_1AFFA 0x1AFFA // 𚿺 KATAKANA LETTER MINNAN NASALIZED TONE-4
#define UC_MACRO_NAME_1AFFB 0x1AFFB // 𚿻 KATAKANA LETTER MINNAN NASALIZED TONE-5
#define UC_MACRO_NAME_1AFFD 0x1AFFD // 𚿽 KATAKANA LETTER MINNAN NASALIZED TONE-7
#define UC_MACRO_NAME_1AFFE 0x1AFFE // 𚿾 KATAKANA LETTER MINNAN NASALIZED TONE-8


#endif // UC_H_KANA_EXTENDED_B
