/*
 * Unicode Block: Kaktovik Numerals
 * Range: U+1D2C0..U+1D2DF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_KAKTOVIK_NUMERALS
#define UC_H_KAKTOVIK_NUMERALS

#define UC_MACRO_NAME_1D2C0 0x1D2C0 // 𝋀 KAKTOVIK NUMERAL ZERO
#define UC_MACRO_NAME_1D2C1 0x1D2C1 // 𝋁 KAKTOVIK NUMERAL ONE
#define UC_MACRO_NAME_1D2C2 0x1D2C2 // 𝋂 KAKTOVIK NUMERAL TWO
#define UC_MACRO_NAME_1D2C3 0x1D2C3 // 𝋃 KAKTOVIK NUMERAL THREE
#define UC_MACRO_NAME_1D2C4 0x1D2C4 // 𝋄 KAKTOVIK NUMERAL FOUR
#define UC_MACRO_NAME_1D2C5 0x1D2C5 // 𝋅 KAKTOVIK NUMERAL FIVE
#define UC_MACRO_NAME_1D2C6 0x1D2C6 // 𝋆 KAKTOVIK NUMERAL SIX
#define UC_MACRO_NAME_1D2C7 0x1D2C7 // 𝋇 KAKTOVIK NUMERAL SEVEN
#define UC_MACRO_NAME_1D2C8 0x1D2C8 // 𝋈 KAKTOVIK NUMERAL EIGHT
#define UC_MACRO_NAME_1D2C9 0x1D2C9 // 𝋉 KAKTOVIK NUMERAL NINE
#define UC_MACRO_NAME_1D2CA 0x1D2CA // 𝋊 KAKTOVIK NUMERAL TEN
#define UC_MACRO_NAME_1D2CB 0x1D2CB // 𝋋 KAKTOVIK NUMERAL ELEVEN
#define UC_MACRO_NAME_1D2CC 0x1D2CC // 𝋌 KAKTOVIK NUMERAL TWELVE
#define UC_MACRO_NAME_1D2CD 0x1D2CD // 𝋍 KAKTOVIK NUMERAL THIRTEEN
#define UC_MACRO_NAME_1D2CE 0x1D2CE // 𝋎 KAKTOVIK NUMERAL FOURTEEN
#define UC_MACRO_NAME_1D2CF 0x1D2CF // 𝋏 KAKTOVIK NUMERAL FIFTEEN
#define UC_MACRO_NAME_1D2D0 0x1D2D0 // 𝋐 KAKTOVIK NUMERAL SIXTEEN
#define UC_MACRO_NAME_1D2D1 0x1D2D1 // 𝋑 KAKTOVIK NUMERAL SEVENTEEN
#define UC_MACRO_NAME_1D2D2 0x1D2D2 // 𝋒 KAKTOVIK NUMERAL EIGHTEEN
#define UC_MACRO_NAME_1D2D3 0x1D2D3 // 𝋓 KAKTOVIK NUMERAL NINETEEN


#endif // UC_H_KAKTOVIK_NUMERALS
