/*
 * Unicode Block: Kannada
 * Range: U+0C80..U+0CFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_KANNADA
#define UC_H_KANNADA

#define UC_MACRO_NAME_C80 0x0C80 // ಀ KANNADA SIGN SPACING CANDRABINDU
#define UC_MACRO_NAME_C81 0x0C81 // ಁ KANNADA SIGN CANDRABINDU
#define UC_MACRO_NAME_C82 0x0C82 // ಂ KANNADA SIGN ANUSVARA
#define UC_MACRO_NAME_C83 0x0C83 // ಃ KANNADA SIGN VISARGA
#define UC_MACRO_NAME_C84 0x0C84 // ಄ KANNADA SIGN SIDDHAM
#define UC_MACRO_NAME_C85 0x0C85 // ಅ KANNADA LETTER A
#define UC_MACRO_NAME_C86 0x0C86 // ಆ KANNADA LETTER AA
#define UC_MACRO_NAME_C87 0x0C87 // ಇ KANNADA LETTER I
#define UC_MACRO_NAME_C88 0x0C88 // ಈ KANNADA LETTER II
#define UC_MACRO_NAME_C89 0x0C89 // ಉ KANNADA LETTER U
#define UC_MACRO_NAME_C8A 0x0C8A // ಊ KANNADA LETTER UU
#define UC_MACRO_NAME_C8B 0x0C8B // ಋ KANNADA LETTER VOCALIC R
#define UC_MACRO_NAME_C8C 0x0C8C // ಌ KANNADA LETTER VOCALIC L
#define UC_MACRO_NAME_C8E 0x0C8E // ಎ KANNADA LETTER E
#define UC_MACRO_NAME_C8F 0x0C8F // ಏ KANNADA LETTER EE
#define UC_MACRO_NAME_C90 0x0C90 // ಐ KANNADA LETTER AI
#define UC_MACRO_NAME_C92 0x0C92 // ಒ KANNADA LETTER O
#define UC_MACRO_NAME_C93 0x0C93 // ಓ KANNADA LETTER OO
#define UC_MACRO_NAME_C94 0x0C94 // ಔ KANNADA LETTER AU
#define UC_MACRO_NAME_C95 0x0C95 // ಕ KANNADA LETTER KA
#define UC_MACRO_NAME_C96 0x0C96 // ಖ KANNADA LETTER KHA
#define UC_MACRO_NAME_C97 0x0C97 // ಗ KANNADA LETTER GA
#define UC_MACRO_NAME_C98 0x0C98 // ಘ KANNADA LETTER GHA
#define UC_MACRO_NAME_C99 0x0C99 // ಙ KANNADA LETTER NGA
#define UC_MACRO_NAME_C9A 0x0C9A // ಚ KANNADA LETTER CA
#define UC_MACRO_NAME_C9B 0x0C9B // ಛ KANNADA LETTER CHA
#define UC_MACRO_NAME_C9C 0x0C9C // ಜ KANNADA LETTER JA
#define UC_MACRO_NAME_C9D 0x0C9D // ಝ KANNADA LETTER JHA
#define UC_MACRO_NAME_C9E 0x0C9E // ಞ KANNADA LETTER NYA
#define UC_MACRO_NAME_C9F 0x0C9F // ಟ KANNADA LETTER TTA
#define UC_MACRO_NAME_CA0 0x0CA0 // ಠ KANNADA LETTER TTHA
#define UC_MACRO_NAME_CA1 0x0CA1 // ಡ KANNADA LETTER DDA
#define UC_MACRO_NAME_CA2 0x0CA2 // ಢ KANNADA LETTER DDHA
#define UC_MACRO_NAME_CA3 0x0CA3 // ಣ KANNADA LETTER NNA
#define UC_MACRO_NAME_CA4 0x0CA4 // ತ KANNADA LETTER TA
#define UC_MACRO_NAME_CA5 0x0CA5 // ಥ KANNADA LETTER THA
#define UC_MACRO_NAME_CA6 0x0CA6 // ದ KANNADA LETTER DA
#define UC_MACRO_NAME_CA7 0x0CA7 // ಧ KANNADA LETTER DHA
#define UC_MACRO_NAME_CA8 0x0CA8 // ನ KANNADA LETTER NA
#define UC_MACRO_NAME_CAA 0x0CAA // ಪ KANNADA LETTER PA
#define UC_MACRO_NAME_CAB 0x0CAB // ಫ KANNADA LETTER PHA
#define UC_MACRO_NAME_CAC 0x0CAC // ಬ KANNADA LETTER BA
#define UC_MACRO_NAME_CAD 0x0CAD // ಭ KANNADA LETTER BHA
#define UC_MACRO_NAME_CAE 0x0CAE // ಮ KANNADA LETTER MA
#define UC_MACRO_NAME_CAF 0x0CAF // ಯ KANNADA LETTER YA
#define UC_MACRO_NAME_CB0 0x0CB0 // ರ KANNADA LETTER RA
#define UC_MACRO_NAME_CB1 0x0CB1 // ಱ KANNADA LETTER RRA
#define UC_MACRO_NAME_CB2 0x0CB2 // ಲ KANNADA LETTER LA
#define UC_MACRO_NAME_CB3 0x0CB3 // ಳ KANNADA LETTER LLA
#define UC_MACRO_NAME_CB5 0x0CB5 // ವ KANNADA LETTER VA
#define UC_MACRO_NAME_CB6 0x0CB6 // ಶ KANNADA LETTER SHA
#define UC_MACRO_NAME_CB7 0x0CB7 // ಷ KANNADA LETTER SSA
#define UC_MACRO_NAME_CB8 0x0CB8 // ಸ KANNADA LETTER SA
#define UC_MACRO_NAME_CB9 0x0CB9 // ಹ KANNADA LETTER HA
#define UC_MACRO_NAME_CBC 0x0CBC // ಼ KANNADA SIGN NUKTA
#define UC_MACRO_NAME_CBD 0x0CBD // ಽ KANNADA SIGN AVAGRAHA
#define UC_MACRO_NAME_CBE 0x0CBE // ಾ KANNADA VOWEL SIGN AA
#define UC_MACRO_NAME_CBF 0x0CBF // ಿ KANNADA VOWEL SIGN I
#define UC_MACRO_NAME_CC0 0x0CC0 // ೀ KANNADA VOWEL SIGN II
#define UC_MACRO_NAME_CC1 0x0CC1 // ು KANNADA VOWEL SIGN U
#define UC_MACRO_NAME_CC2 0x0CC2 // ೂ KANNADA VOWEL SIGN UU
#define UC_MACRO_NAME_CC3 0x0CC3 // ೃ KANNADA VOWEL SIGN VOCALIC R
#define UC_MACRO_NAME_CC4 0x0CC4 // ೄ KANNADA VOWEL SIGN VOCALIC RR
#define UC_MACRO_NAME_CC6 0x0CC6 // ೆ KANNADA VOWEL SIGN E
#define UC_MACRO_NAME_CC7 0x0CC7 // ೇ KANNADA VOWEL SIGN EE
#define UC_MACRO_NAME_CC8 0x0CC8 // ೈ KANNADA VOWEL SIGN AI
#define UC_MACRO_NAME_CCA 0x0CCA // ೊ KANNADA VOWEL SIGN O
#define UC_MACRO_NAME_CCB 0x0CCB // ೋ KANNADA VOWEL SIGN OO
#define UC_MACRO_NAME_CCC 0x0CCC // ೌ KANNADA VOWEL SIGN AU
#define UC_MACRO_NAME_CCD 0x0CCD // ್ KANNADA SIGN VIRAMA
#define UC_MACRO_NAME_CD5 0x0CD5 // ೕ KANNADA LENGTH MARK
#define UC_MACRO_NAME_CD6 0x0CD6 // ೖ KANNADA AI LENGTH MARK
#define UC_MACRO_NAME_CDC 0x0CDC //  KANNADA ARCHAIC SHRII
#define UC_MACRO_NAME_CDD 0x0CDD // ೝ KANNADA LETTER NAKAARA POLLU
#define UC_MACRO_NAME_CDE 0x0CDE // ೞ KANNADA LETTER FA
#define UC_MACRO_NAME_CE0 0x0CE0 // ೠ KANNADA LETTER VOCALIC RR
#define UC_MACRO_NAME_CE1 0x0CE1 // ೡ KANNADA LETTER VOCALIC LL
#define UC_MACRO_NAME_CE2 0x0CE2 // ೢ KANNADA VOWEL SIGN VOCALIC L
#define UC_MACRO_NAME_CE3 0x0CE3 // ೣ KANNADA VOWEL SIGN VOCALIC LL
#define UC_MACRO_NAME_CE6 0x0CE6 // ೦ KANNADA DIGIT ZERO
#define UC_MACRO_NAME_CE7 0x0CE7 // ೧ KANNADA DIGIT ONE
#define UC_MACRO_NAME_CE8 0x0CE8 // ೨ KANNADA DIGIT TWO
#define UC_MACRO_NAME_CE9 0x0CE9 // ೩ KANNADA DIGIT THREE
#define UC_MACRO_NAME_CEA 0x0CEA // ೪ KANNADA DIGIT FOUR
#define UC_MACRO_NAME_CEB 0x0CEB // ೫ KANNADA DIGIT FIVE
#define UC_MACRO_NAME_CEC 0x0CEC // ೬ KANNADA DIGIT SIX
#define UC_MACRO_NAME_CED 0x0CED // ೭ KANNADA DIGIT SEVEN
#define UC_MACRO_NAME_CEE 0x0CEE // ೮ KANNADA DIGIT EIGHT
#define UC_MACRO_NAME_CEF 0x0CEF // ೯ KANNADA DIGIT NINE
#define UC_MACRO_NAME_CF1 0x0CF1 // ೱ KANNADA SIGN JIHVAMULIYA
#define UC_MACRO_NAME_CF2 0x0CF2 // ೲ KANNADA SIGN UPADHMANIYA
#define UC_MACRO_NAME_CF3 0x0CF3 // ೳ KANNADA SIGN COMBINING ANUSVARA ABOVE RIGHT


#endif // UC_H_KANNADA
