/*
 * Unicode Block: Kangxi Radicals
 * Range: U+2F00..U+2FDF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * The Kangxi radicals ( Chinese : 康熙部首 ; pinyin : Kāngxī bùshǒu ), also
 * known as Zihui radicals , are a set of 214 radicals that were collated
 * in the 18th-century Kangxi Dictionary to aid categorization of Chinese
 * characters . They are primarily sorted by stroke count . They are the
 * most popular system of radicals for dictionaries that order characters
 * by radical and stroke count. They are encoded in Unicode alongside
 * other CJK characters , under the block "Kangxi radicals", while
 * graphical variants are included in the block "CJK Radicals
 * Supplement".
 * Originally introduced in the Zihui dictionary of 1615, they are more
 * commonly referred to in relation to the 1716 Kangxi Dictionary —
 * Kangxi being the commissioning emperor's era name . The 1915
 * encyclopedic word dictionary Ciyuan also uses this system. In modern
 * times, many dictionaries that list Traditional Chinese head characters
 * continue to use this system, for example the Wang Li Character
 * Dictionary of Ancient Chinese (2000). The system of 214 Kangxi
 * radicals is based on the older system of 540 radicals used in the
 * Han-era Shuowen Jiezi . Since 2009, the Chinese government has
 * promoted a 201-radical system ( Table of Han Character Radicals )
 * called the Table of Indexing Chinese Character Components , as a
 * national standard for use with simplified characters .
 *
 */
#ifndef UC_H_KANGXI_RADICALS
#define UC_H_KANGXI_RADICALS

#define UC_MACRO_NAME_2F00 0x2F00 // ⼀ KANGXI RADICAL ONE
#define UC_MACRO_NAME_2F01 0x2F01 // ⼁ KANGXI RADICAL LINE
#define UC_MACRO_NAME_2F02 0x2F02 // ⼂ KANGXI RADICAL DOT
#define UC_MACRO_NAME_2F03 0x2F03 // ⼃ KANGXI RADICAL SLASH
#define UC_MACRO_NAME_2F04 0x2F04 // ⼄ KANGXI RADICAL SECOND
#define UC_MACRO_NAME_2F05 0x2F05 // ⼅ KANGXI RADICAL HOOK
#define UC_MACRO_NAME_2F06 0x2F06 // ⼆ KANGXI RADICAL TWO
#define UC_MACRO_NAME_2F07 0x2F07 // ⼇ KANGXI RADICAL LID
#define UC_MACRO_NAME_2F08 0x2F08 // ⼈ KANGXI RADICAL MAN
#define UC_MACRO_NAME_2F09 0x2F09 // ⼉ KANGXI RADICAL LEGS
#define UC_MACRO_NAME_2F0A 0x2F0A // ⼊ KANGXI RADICAL ENTER
#define UC_MACRO_NAME_2F0B 0x2F0B // ⼋ KANGXI RADICAL EIGHT
#define UC_MACRO_NAME_2F0C 0x2F0C // ⼌ KANGXI RADICAL DOWN BOX
#define UC_MACRO_NAME_2F0D 0x2F0D // ⼍ KANGXI RADICAL COVER
#define UC_MACRO_NAME_2F0E 0x2F0E // ⼎ KANGXI RADICAL ICE
#define UC_MACRO_NAME_2F0F 0x2F0F // ⼏ KANGXI RADICAL TABLE
#define UC_MACRO_NAME_2F10 0x2F10 // ⼐ KANGXI RADICAL OPEN BOX
#define UC_MACRO_NAME_2F11 0x2F11 // ⼑ KANGXI RADICAL KNIFE
#define UC_MACRO_NAME_2F12 0x2F12 // ⼒ KANGXI RADICAL POWER
#define UC_MACRO_NAME_2F13 0x2F13 // ⼓ KANGXI RADICAL WRAP
#define UC_MACRO_NAME_2F14 0x2F14 // ⼔ KANGXI RADICAL SPOON
#define UC_MACRO_NAME_2F15 0x2F15 // ⼕ KANGXI RADICAL RIGHT OPEN BOX
#define UC_MACRO_NAME_2F16 0x2F16 // ⼖ KANGXI RADICAL HIDING ENCLOSURE
#define UC_MACRO_NAME_2F17 0x2F17 // ⼗ KANGXI RADICAL TEN
#define UC_MACRO_NAME_2F18 0x2F18 // ⼘ KANGXI RADICAL DIVINATION
#define UC_MACRO_NAME_2F19 0x2F19 // ⼙ KANGXI RADICAL SEAL
#define UC_MACRO_NAME_2F1A 0x2F1A // ⼚ KANGXI RADICAL CLIFF
#define UC_MACRO_NAME_2F1B 0x2F1B // ⼛ KANGXI RADICAL PRIVATE
#define UC_MACRO_NAME_2F1C 0x2F1C // ⼜ KANGXI RADICAL AGAIN
#define UC_MACRO_NAME_2F1D 0x2F1D // ⼝ KANGXI RADICAL MOUTH
#define UC_MACRO_NAME_2F1E 0x2F1E // ⼞ KANGXI RADICAL ENCLOSURE
#define UC_MACRO_NAME_2F1F 0x2F1F // ⼟ KANGXI RADICAL EARTH
#define UC_MACRO_NAME_2F20 0x2F20 // ⼠ KANGXI RADICAL SCHOLAR
#define UC_MACRO_NAME_2F21 0x2F21 // ⼡ KANGXI RADICAL GO
#define UC_MACRO_NAME_2F22 0x2F22 // ⼢ KANGXI RADICAL GO SLOWLY
#define UC_MACRO_NAME_2F23 0x2F23 // ⼣ KANGXI RADICAL EVENING
#define UC_MACRO_NAME_2F24 0x2F24 // ⼤ KANGXI RADICAL BIG
#define UC_MACRO_NAME_2F25 0x2F25 // ⼥ KANGXI RADICAL WOMAN
#define UC_MACRO_NAME_2F26 0x2F26 // ⼦ KANGXI RADICAL CHILD
#define UC_MACRO_NAME_2F27 0x2F27 // ⼧ KANGXI RADICAL ROOF
#define UC_MACRO_NAME_2F28 0x2F28 // ⼨ KANGXI RADICAL INCH
#define UC_MACRO_NAME_2F29 0x2F29 // ⼩ KANGXI RADICAL SMALL
#define UC_MACRO_NAME_2F2A 0x2F2A // ⼪ KANGXI RADICAL LAME
#define UC_MACRO_NAME_2F2B 0x2F2B // ⼫ KANGXI RADICAL CORPSE
#define UC_MACRO_NAME_2F2C 0x2F2C // ⼬ KANGXI RADICAL SPROUT
#define UC_MACRO_NAME_2F2D 0x2F2D // ⼭ KANGXI RADICAL MOUNTAIN
#define UC_MACRO_NAME_2F2E 0x2F2E // ⼮ KANGXI RADICAL RIVER
#define UC_MACRO_NAME_2F2F 0x2F2F // ⼯ KANGXI RADICAL WORK
#define UC_MACRO_NAME_2F30 0x2F30 // ⼰ KANGXI RADICAL ONESELF
#define UC_MACRO_NAME_2F31 0x2F31 // ⼱ KANGXI RADICAL TURBAN
#define UC_MACRO_NAME_2F32 0x2F32 // ⼲ KANGXI RADICAL DRY
#define UC_MACRO_NAME_2F33 0x2F33 // ⼳ KANGXI RADICAL SHORT THREAD
#define UC_MACRO_NAME_2F34 0x2F34 // ⼴ KANGXI RADICAL DOTTED CLIFF
#define UC_MACRO_NAME_2F35 0x2F35 // ⼵ KANGXI RADICAL LONG STRIDE
#define UC_MACRO_NAME_2F36 0x2F36 // ⼶ KANGXI RADICAL TWO HANDS
#define UC_MACRO_NAME_2F37 0x2F37 // ⼷ KANGXI RADICAL SHOOT
#define UC_MACRO_NAME_2F38 0x2F38 // ⼸ KANGXI RADICAL BOW
#define UC_MACRO_NAME_2F39 0x2F39 // ⼹ KANGXI RADICAL SNOUT
#define UC_MACRO_NAME_2F3A 0x2F3A // ⼺ KANGXI RADICAL BRISTLE
#define UC_MACRO_NAME_2F3B 0x2F3B // ⼻ KANGXI RADICAL STEP
#define UC_MACRO_NAME_2F3C 0x2F3C // ⼼ KANGXI RADICAL HEART
#define UC_MACRO_NAME_2F3D 0x2F3D // ⼽ KANGXI RADICAL HALBERD
#define UC_MACRO_NAME_2F3E 0x2F3E // ⼾ KANGXI RADICAL DOOR
#define UC_MACRO_NAME_2F3F 0x2F3F // ⼿ KANGXI RADICAL HAND
#define UC_MACRO_NAME_2F40 0x2F40 // ⽀ KANGXI RADICAL BRANCH
#define UC_MACRO_NAME_2F41 0x2F41 // ⽁ KANGXI RADICAL RAP
#define UC_MACRO_NAME_2F42 0x2F42 // ⽂ KANGXI RADICAL SCRIPT
#define UC_MACRO_NAME_2F43 0x2F43 // ⽃ KANGXI RADICAL DIPPER
#define UC_MACRO_NAME_2F44 0x2F44 // ⽄ KANGXI RADICAL AXE
#define UC_MACRO_NAME_2F45 0x2F45 // ⽅ KANGXI RADICAL SQUARE
#define UC_MACRO_NAME_2F46 0x2F46 // ⽆ KANGXI RADICAL NOT
#define UC_MACRO_NAME_2F47 0x2F47 // ⽇ KANGXI RADICAL SUN
#define UC_MACRO_NAME_2F48 0x2F48 // ⽈ KANGXI RADICAL SAY
#define UC_MACRO_NAME_2F49 0x2F49 // ⽉ KANGXI RADICAL MOON
#define UC_MACRO_NAME_2F4A 0x2F4A // ⽊ KANGXI RADICAL TREE
#define UC_MACRO_NAME_2F4B 0x2F4B // ⽋ KANGXI RADICAL LACK
#define UC_MACRO_NAME_2F4C 0x2F4C // ⽌ KANGXI RADICAL STOP
#define UC_MACRO_NAME_2F4D 0x2F4D // ⽍ KANGXI RADICAL DEATH
#define UC_MACRO_NAME_2F4E 0x2F4E // ⽎ KANGXI RADICAL WEAPON
#define UC_MACRO_NAME_2F4F 0x2F4F // ⽏ KANGXI RADICAL DO NOT
#define UC_MACRO_NAME_2F50 0x2F50 // ⽐ KANGXI RADICAL COMPARE
#define UC_MACRO_NAME_2F51 0x2F51 // ⽑ KANGXI RADICAL FUR
#define UC_MACRO_NAME_2F52 0x2F52 // ⽒ KANGXI RADICAL CLAN
#define UC_MACRO_NAME_2F53 0x2F53 // ⽓ KANGXI RADICAL STEAM
#define UC_MACRO_NAME_2F54 0x2F54 // ⽔ KANGXI RADICAL WATER
#define UC_MACRO_NAME_2F55 0x2F55 // ⽕ KANGXI RADICAL FIRE
#define UC_MACRO_NAME_2F56 0x2F56 // ⽖ KANGXI RADICAL CLAW
#define UC_MACRO_NAME_2F57 0x2F57 // ⽗ KANGXI RADICAL FATHER
#define UC_MACRO_NAME_2F58 0x2F58 // ⽘ KANGXI RADICAL DOUBLE X
#define UC_MACRO_NAME_2F59 0x2F59 // ⽙ KANGXI RADICAL HALF TREE TRUNK
#define UC_MACRO_NAME_2F5A 0x2F5A // ⽚ KANGXI RADICAL SLICE
#define UC_MACRO_NAME_2F5B 0x2F5B // ⽛ KANGXI RADICAL FANG
#define UC_MACRO_NAME_2F5C 0x2F5C // ⽜ KANGXI RADICAL COW
#define UC_MACRO_NAME_2F5D 0x2F5D // ⽝ KANGXI RADICAL DOG
#define UC_MACRO_NAME_2F5E 0x2F5E // ⽞ KANGXI RADICAL PROFOUND
#define UC_MACRO_NAME_2F5F 0x2F5F // ⽟ KANGXI RADICAL JADE
#define UC_MACRO_NAME_2F60 0x2F60 // ⽠ KANGXI RADICAL MELON
#define UC_MACRO_NAME_2F61 0x2F61 // ⽡ KANGXI RADICAL TILE
#define UC_MACRO_NAME_2F62 0x2F62 // ⽢ KANGXI RADICAL SWEET
#define UC_MACRO_NAME_2F63 0x2F63 // ⽣ KANGXI RADICAL LIFE
#define UC_MACRO_NAME_2F64 0x2F64 // ⽤ KANGXI RADICAL USE
#define UC_MACRO_NAME_2F65 0x2F65 // ⽥ KANGXI RADICAL FIELD
#define UC_MACRO_NAME_2F66 0x2F66 // ⽦ KANGXI RADICAL BOLT OF CLOTH
#define UC_MACRO_NAME_2F67 0x2F67 // ⽧ KANGXI RADICAL SICKNESS
#define UC_MACRO_NAME_2F68 0x2F68 // ⽨ KANGXI RADICAL DOTTED TENT
#define UC_MACRO_NAME_2F69 0x2F69 // ⽩ KANGXI RADICAL WHITE
#define UC_MACRO_NAME_2F6A 0x2F6A // ⽪ KANGXI RADICAL SKIN
#define UC_MACRO_NAME_2F6B 0x2F6B // ⽫ KANGXI RADICAL DISH
#define UC_MACRO_NAME_2F6C 0x2F6C // ⽬ KANGXI RADICAL EYE
#define UC_MACRO_NAME_2F6D 0x2F6D // ⽭ KANGXI RADICAL SPEAR
#define UC_MACRO_NAME_2F6E 0x2F6E // ⽮ KANGXI RADICAL ARROW
#define UC_MACRO_NAME_2F6F 0x2F6F // ⽯ KANGXI RADICAL STONE
#define UC_MACRO_NAME_2F70 0x2F70 // ⽰ KANGXI RADICAL SPIRIT
#define UC_MACRO_NAME_2F71 0x2F71 // ⽱ KANGXI RADICAL TRACK
#define UC_MACRO_NAME_2F72 0x2F72 // ⽲ KANGXI RADICAL GRAIN
#define UC_MACRO_NAME_2F73 0x2F73 // ⽳ KANGXI RADICAL CAVE
#define UC_MACRO_NAME_2F74 0x2F74 // ⽴ KANGXI RADICAL STAND
#define UC_MACRO_NAME_2F75 0x2F75 // ⽵ KANGXI RADICAL BAMBOO
#define UC_MACRO_NAME_2F76 0x2F76 // ⽶ KANGXI RADICAL RICE
#define UC_MACRO_NAME_2F77 0x2F77 // ⽷ KANGXI RADICAL SILK
#define UC_MACRO_NAME_2F78 0x2F78 // ⽸ KANGXI RADICAL JAR
#define UC_MACRO_NAME_2F79 0x2F79 // ⽹ KANGXI RADICAL NET
#define UC_MACRO_NAME_2F7A 0x2F7A // ⽺ KANGXI RADICAL SHEEP
#define UC_MACRO_NAME_2F7B 0x2F7B // ⽻ KANGXI RADICAL FEATHER
#define UC_MACRO_NAME_2F7C 0x2F7C // ⽼ KANGXI RADICAL OLD
#define UC_MACRO_NAME_2F7D 0x2F7D // ⽽ KANGXI RADICAL AND
#define UC_MACRO_NAME_2F7E 0x2F7E // ⽾ KANGXI RADICAL PLOW
#define UC_MACRO_NAME_2F7F 0x2F7F // ⽿ KANGXI RADICAL EAR
#define UC_MACRO_NAME_2F80 0x2F80 // ⾀ KANGXI RADICAL BRUSH
#define UC_MACRO_NAME_2F81 0x2F81 // ⾁ KANGXI RADICAL MEAT
#define UC_MACRO_NAME_2F82 0x2F82 // ⾂ KANGXI RADICAL MINISTER
#define UC_MACRO_NAME_2F83 0x2F83 // ⾃ KANGXI RADICAL SELF
#define UC_MACRO_NAME_2F84 0x2F84 // ⾄ KANGXI RADICAL ARRIVE
#define UC_MACRO_NAME_2F85 0x2F85 // ⾅ KANGXI RADICAL MORTAR
#define UC_MACRO_NAME_2F86 0x2F86 // ⾆ KANGXI RADICAL TONGUE
#define UC_MACRO_NAME_2F87 0x2F87 // ⾇ KANGXI RADICAL OPPOSE
#define UC_MACRO_NAME_2F88 0x2F88 // ⾈ KANGXI RADICAL BOAT
#define UC_MACRO_NAME_2F89 0x2F89 // ⾉ KANGXI RADICAL STOPPING
#define UC_MACRO_NAME_2F8A 0x2F8A // ⾊ KANGXI RADICAL COLOR
#define UC_MACRO_NAME_2F8B 0x2F8B // ⾋ KANGXI RADICAL GRASS
#define UC_MACRO_NAME_2F8C 0x2F8C // ⾌ KANGXI RADICAL TIGER
#define UC_MACRO_NAME_2F8D 0x2F8D // ⾍ KANGXI RADICAL INSECT
#define UC_MACRO_NAME_2F8E 0x2F8E // ⾎ KANGXI RADICAL BLOOD
#define UC_MACRO_NAME_2F8F 0x2F8F // ⾏ KANGXI RADICAL WALK ENCLOSURE
#define UC_MACRO_NAME_2F90 0x2F90 // ⾐ KANGXI RADICAL CLOTHES
#define UC_MACRO_NAME_2F91 0x2F91 // ⾑ KANGXI RADICAL WEST
#define UC_MACRO_NAME_2F92 0x2F92 // ⾒ KANGXI RADICAL SEE
#define UC_MACRO_NAME_2F93 0x2F93 // ⾓ KANGXI RADICAL HORN
#define UC_MACRO_NAME_2F94 0x2F94 // ⾔ KANGXI RADICAL SPEECH
#define UC_MACRO_NAME_2F95 0x2F95 // ⾕ KANGXI RADICAL VALLEY
#define UC_MACRO_NAME_2F96 0x2F96 // ⾖ KANGXI RADICAL BEAN
#define UC_MACRO_NAME_2F97 0x2F97 // ⾗ KANGXI RADICAL PIG
#define UC_MACRO_NAME_2F98 0x2F98 // ⾘ KANGXI RADICAL BADGER
#define UC_MACRO_NAME_2F99 0x2F99 // ⾙ KANGXI RADICAL SHELL
#define UC_MACRO_NAME_2F9A 0x2F9A // ⾚ KANGXI RADICAL RED
#define UC_MACRO_NAME_2F9B 0x2F9B // ⾛ KANGXI RADICAL RUN
#define UC_MACRO_NAME_2F9C 0x2F9C // ⾜ KANGXI RADICAL FOOT
#define UC_MACRO_NAME_2F9D 0x2F9D // ⾝ KANGXI RADICAL BODY
#define UC_MACRO_NAME_2F9E 0x2F9E // ⾞ KANGXI RADICAL CART
#define UC_MACRO_NAME_2F9F 0x2F9F // ⾟ KANGXI RADICAL BITTER
#define UC_MACRO_NAME_2FA0 0x2FA0 // ⾠ KANGXI RADICAL MORNING
#define UC_MACRO_NAME_2FA1 0x2FA1 // ⾡ KANGXI RADICAL WALK
#define UC_MACRO_NAME_2FA2 0x2FA2 // ⾢ KANGXI RADICAL CITY
#define UC_MACRO_NAME_2FA3 0x2FA3 // ⾣ KANGXI RADICAL WINE
#define UC_MACRO_NAME_2FA4 0x2FA4 // ⾤ KANGXI RADICAL DISTINGUISH
#define UC_MACRO_NAME_2FA5 0x2FA5 // ⾥ KANGXI RADICAL VILLAGE
#define UC_MACRO_NAME_2FA6 0x2FA6 // ⾦ KANGXI RADICAL GOLD
#define UC_MACRO_NAME_2FA7 0x2FA7 // ⾧ KANGXI RADICAL LONG
#define UC_MACRO_NAME_2FA8 0x2FA8 // ⾨ KANGXI RADICAL GATE
#define UC_MACRO_NAME_2FA9 0x2FA9 // ⾩ KANGXI RADICAL MOUND
#define UC_MACRO_NAME_2FAA 0x2FAA // ⾪ KANGXI RADICAL SLAVE
#define UC_MACRO_NAME_2FAB 0x2FAB // ⾫ KANGXI RADICAL SHORT TAILED BIRD
#define UC_MACRO_NAME_2FAC 0x2FAC // ⾬ KANGXI RADICAL RAIN
#define UC_MACRO_NAME_2FAD 0x2FAD // ⾭ KANGXI RADICAL BLUE
#define UC_MACRO_NAME_2FAE 0x2FAE // ⾮ KANGXI RADICAL WRONG
#define UC_MACRO_NAME_2FAF 0x2FAF // ⾯ KANGXI RADICAL FACE
#define UC_MACRO_NAME_2FB0 0x2FB0 // ⾰ KANGXI RADICAL LEATHER
#define UC_MACRO_NAME_2FB1 0x2FB1 // ⾱ KANGXI RADICAL TANNED LEATHER
#define UC_MACRO_NAME_2FB2 0x2FB2 // ⾲ KANGXI RADICAL LEEK
#define UC_MACRO_NAME_2FB3 0x2FB3 // ⾳ KANGXI RADICAL SOUND
#define UC_MACRO_NAME_2FB4 0x2FB4 // ⾴ KANGXI RADICAL LEAF
#define UC_MACRO_NAME_2FB5 0x2FB5 // ⾵ KANGXI RADICAL WIND
#define UC_MACRO_NAME_2FB6 0x2FB6 // ⾶ KANGXI RADICAL FLY
#define UC_MACRO_NAME_2FB7 0x2FB7 // ⾷ KANGXI RADICAL EAT
#define UC_MACRO_NAME_2FB8 0x2FB8 // ⾸ KANGXI RADICAL HEAD
#define UC_MACRO_NAME_2FB9 0x2FB9 // ⾹ KANGXI RADICAL FRAGRANT
#define UC_MACRO_NAME_2FBA 0x2FBA // ⾺ KANGXI RADICAL HORSE
#define UC_MACRO_NAME_2FBB 0x2FBB // ⾻ KANGXI RADICAL BONE
#define UC_MACRO_NAME_2FBC 0x2FBC // ⾼ KANGXI RADICAL TALL
#define UC_MACRO_NAME_2FBD 0x2FBD // ⾽ KANGXI RADICAL HAIR
#define UC_MACRO_NAME_2FBE 0x2FBE // ⾾ KANGXI RADICAL FIGHT
#define UC_MACRO_NAME_2FBF 0x2FBF // ⾿ KANGXI RADICAL SACRIFICIAL WINE
#define UC_MACRO_NAME_2FC0 0x2FC0 // ⿀ KANGXI RADICAL CAULDRON
#define UC_MACRO_NAME_2FC1 0x2FC1 // ⿁ KANGXI RADICAL GHOST
#define UC_MACRO_NAME_2FC2 0x2FC2 // ⿂ KANGXI RADICAL FISH
#define UC_MACRO_NAME_2FC3 0x2FC3 // ⿃ KANGXI RADICAL BIRD
#define UC_MACRO_NAME_2FC4 0x2FC4 // ⿄ KANGXI RADICAL SALT
#define UC_MACRO_NAME_2FC5 0x2FC5 // ⿅ KANGXI RADICAL DEER
#define UC_MACRO_NAME_2FC6 0x2FC6 // ⿆ KANGXI RADICAL WHEAT
#define UC_MACRO_NAME_2FC7 0x2FC7 // ⿇ KANGXI RADICAL HEMP
#define UC_MACRO_NAME_2FC8 0x2FC8 // ⿈ KANGXI RADICAL YELLOW
#define UC_MACRO_NAME_2FC9 0x2FC9 // ⿉ KANGXI RADICAL MILLET
#define UC_MACRO_NAME_2FCA 0x2FCA // ⿊ KANGXI RADICAL BLACK
#define UC_MACRO_NAME_2FCB 0x2FCB // ⿋ KANGXI RADICAL EMBROIDERY
#define UC_MACRO_NAME_2FCC 0x2FCC // ⿌ KANGXI RADICAL FROG
#define UC_MACRO_NAME_2FCD 0x2FCD // ⿍ KANGXI RADICAL TRIPOD
#define UC_MACRO_NAME_2FCE 0x2FCE // ⿎ KANGXI RADICAL DRUM
#define UC_MACRO_NAME_2FCF 0x2FCF // ⿏ KANGXI RADICAL RAT
#define UC_MACRO_NAME_2FD0 0x2FD0 // ⿐ KANGXI RADICAL NOSE
#define UC_MACRO_NAME_2FD1 0x2FD1 // ⿑ KANGXI RADICAL EVEN
#define UC_MACRO_NAME_2FD2 0x2FD2 // ⿒ KANGXI RADICAL TOOTH
#define UC_MACRO_NAME_2FD3 0x2FD3 // ⿓ KANGXI RADICAL DRAGON
#define UC_MACRO_NAME_2FD4 0x2FD4 // ⿔ KANGXI RADICAL TURTLE
#define UC_MACRO_NAME_2FD5 0x2FD5 // ⿕ KANGXI RADICAL FLUTE


#endif // UC_H_KANGXI_RADICALS
