/*
 * Unicode Block: Latin Extended-G
 * Range: U+1DF00..U+1DFFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Latin Extended-G is a Unicode block containing additional characters
 * for phonetic transcription . The Latin Extended-F and -G blocks
 * contain the first Latin characters defined outside of the Basic
 * Multilingual Plane (BMP). They were created for Unicode version 14 in
 * 2021.
 * Because this is a recently created block, font support is poor. Fonts
 * that support at least some of Latin Extended-G include Gentium ,
 * Andika , Symbola , Unifont , Charis SIL , Noto Sans , Noto Serif , and
 * AncientSans .
 *
 */
#ifndef UC_H_LATIN_EXTENDED_G
#define UC_H_LATIN_EXTENDED_G

#define UC_MACRO_NAME_1DF00 0x1DF00 // 𝼀 LATIN SMALL LETTER FENG DIGRAPH WITH TRILL
#define UC_MACRO_NAME_1DF01 0x1DF01 // 𝼁 LATIN SMALL LETTER REVERSED SCRIPT G
#define UC_MACRO_NAME_1DF02 0x1DF02 // 𝼂 LATIN LETTER SMALL CAPITAL TURNED G
#define UC_MACRO_NAME_1DF03 0x1DF03 // 𝼃 LATIN SMALL LETTER REVERSED K
#define UC_MACRO_NAME_1DF04 0x1DF04 // 𝼄 LATIN LETTER SMALL CAPITAL L WITH BELT
#define UC_MACRO_NAME_1DF05 0x1DF05 // 𝼅 LATIN SMALL LETTER LEZH WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1DF06 0x1DF06 // 𝼆 LATIN SMALL LETTER TURNED Y WITH BELT
#define UC_MACRO_NAME_1DF07 0x1DF07 // 𝼇 LATIN SMALL LETTER REVERSED ENG
#define UC_MACRO_NAME_1DF08 0x1DF08 // 𝼈 LATIN SMALL LETTER TURNED R WITH LONG LEG AND RETROFLEX HOOK
#define UC_MACRO_NAME_1DF09 0x1DF09 // 𝼉 LATIN SMALL LETTER T WITH HOOK AND RETROFLEX HOOK
#define UC_MACRO_NAME_1DF0A 0x1DF0A // 𝼊 LATIN LETTER RETROFLEX CLICK WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1DF0B 0x1DF0B // 𝼋 LATIN SMALL LETTER ESH WITH DOUBLE BAR
#define UC_MACRO_NAME_1DF0C 0x1DF0C // 𝼌 LATIN SMALL LETTER ESH WITH DOUBLE BAR AND CURL
#define UC_MACRO_NAME_1DF0D 0x1DF0D // 𝼍 LATIN SMALL LETTER TURNED T WITH CURL
#define UC_MACRO_NAME_1DF0E 0x1DF0E // 𝼎 LATIN LETTER INVERTED GLOTTAL STOP WITH CURL
#define UC_MACRO_NAME_1DF0F 0x1DF0F // 𝼏 LATIN LETTER STRETCHED C WITH CURL
#define UC_MACRO_NAME_1DF10 0x1DF10 // 𝼐 LATIN LETTER SMALL CAPITAL TURNED K
#define UC_MACRO_NAME_1DF11 0x1DF11 // 𝼑 LATIN SMALL LETTER L WITH FISHHOOK
#define UC_MACRO_NAME_1DF12 0x1DF12 // 𝼒 LATIN SMALL LETTER DEZH DIGRAPH WITH PALATAL HOOK
#define UC_MACRO_NAME_1DF13 0x1DF13 // 𝼓 LATIN SMALL LETTER L WITH BELT AND PALATAL HOOK
#define UC_MACRO_NAME_1DF14 0x1DF14 // 𝼔 LATIN SMALL LETTER ENG WITH PALATAL HOOK
#define UC_MACRO_NAME_1DF15 0x1DF15 // 𝼕 LATIN SMALL LETTER TURNED R WITH PALATAL HOOK
#define UC_MACRO_NAME_1DF16 0x1DF16 // 𝼖 LATIN SMALL LETTER R WITH FISHHOOK AND PALATAL HOOK
#define UC_MACRO_NAME_1DF17 0x1DF17 // 𝼗 LATIN SMALL LETTER TESH DIGRAPH WITH PALATAL HOOK
#define UC_MACRO_NAME_1DF18 0x1DF18 // 𝼘 LATIN SMALL LETTER EZH WITH PALATAL HOOK
#define UC_MACRO_NAME_1DF19 0x1DF19 // 𝼙 LATIN SMALL LETTER DEZH DIGRAPH WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1DF1A 0x1DF1A // 𝼚 LATIN SMALL LETTER I WITH STROKE AND RETROFLEX HOOK
#define UC_MACRO_NAME_1DF1B 0x1DF1B // 𝼛 LATIN SMALL LETTER O WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1DF1C 0x1DF1C // 𝼜 LATIN SMALL LETTER TESH DIGRAPH WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1DF1D 0x1DF1D // 𝼝 LATIN SMALL LETTER C WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1DF1E 0x1DF1E // 𝼞 LATIN SMALL LETTER S WITH CURL
#define UC_MACRO_NAME_1DF25 0x1DF25 // 𝼥 LATIN SMALL LETTER D WITH MID-HEIGHT LEFT HOOK
#define UC_MACRO_NAME_1DF26 0x1DF26 // 𝼦 LATIN SMALL LETTER L WITH MID-HEIGHT LEFT HOOK
#define UC_MACRO_NAME_1DF27 0x1DF27 // 𝼧 LATIN SMALL LETTER N WITH MID-HEIGHT LEFT HOOK
#define UC_MACRO_NAME_1DF28 0x1DF28 // 𝼨 LATIN SMALL LETTER R WITH MID-HEIGHT LEFT HOOK
#define UC_MACRO_NAME_1DF29 0x1DF29 // 𝼩 LATIN SMALL LETTER S WITH MID-HEIGHT LEFT HOOK
#define UC_MACRO_NAME_1DF2A 0x1DF2A // 𝼪 LATIN SMALL LETTER T WITH MID-HEIGHT LEFT HOOK


#endif // UC_H_LATIN_EXTENDED_G
