/*
 * Unicode Block: Latin Extended-C
 * Range: U+2C60..U+2C7F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Latin Extended-C is a Unicode block containing Latin characters for
 * Uighur New Script , the Uralic Phonetic Alphabet , Shona , Claudian
 * Latin and the Swedish Dialect Alphabet .
 *
 */
#ifndef UC_H_LATIN_EXTENDED_C
#define UC_H_LATIN_EXTENDED_C

#define UC_MACRO_NAME_2C60 0x2C60 // Ⱡ LATIN CAPITAL LETTER L WITH DOUBLE BAR
#define UC_MACRO_NAME_2C61 0x2C61 // ⱡ LATIN SMALL LETTER L WITH DOUBLE BAR
#define UC_MACRO_NAME_2C62 0x2C62 // Ɫ LATIN CAPITAL LETTER L WITH MIDDLE TILDE
#define UC_MACRO_NAME_2C63 0x2C63 // Ᵽ LATIN CAPITAL LETTER P WITH STROKE
#define UC_MACRO_NAME_2C64 0x2C64 // Ɽ LATIN CAPITAL LETTER R WITH TAIL
#define UC_MACRO_NAME_2C65 0x2C65 // ⱥ LATIN SMALL LETTER A WITH STROKE
#define UC_MACRO_NAME_2C66 0x2C66 // ⱦ LATIN SMALL LETTER T WITH DIAGONAL STROKE
#define UC_MACRO_NAME_2C67 0x2C67 // Ⱨ LATIN CAPITAL LETTER H WITH DESCENDER
#define UC_MACRO_NAME_2C68 0x2C68 // ⱨ LATIN SMALL LETTER H WITH DESCENDER
#define UC_MACRO_NAME_2C69 0x2C69 // Ⱪ LATIN CAPITAL LETTER K WITH DESCENDER
#define UC_MACRO_NAME_2C6A 0x2C6A // ⱪ LATIN SMALL LETTER K WITH DESCENDER
#define UC_MACRO_NAME_2C6B 0x2C6B // Ⱬ LATIN CAPITAL LETTER Z WITH DESCENDER
#define UC_MACRO_NAME_2C6C 0x2C6C // ⱬ LATIN SMALL LETTER Z WITH DESCENDER
#define UC_MACRO_NAME_2C6D 0x2C6D // Ɑ LATIN CAPITAL LETTER ALPHA
#define UC_MACRO_NAME_2C6E 0x2C6E // Ɱ LATIN CAPITAL LETTER M WITH HOOK
#define UC_MACRO_NAME_2C6F 0x2C6F // Ɐ LATIN CAPITAL LETTER TURNED A
#define UC_MACRO_NAME_2C70 0x2C70 // Ɒ LATIN CAPITAL LETTER TURNED ALPHA
#define UC_MACRO_NAME_2C71 0x2C71 // ⱱ LATIN SMALL LETTER V WITH RIGHT HOOK
#define UC_MACRO_NAME_2C72 0x2C72 // Ⱳ LATIN CAPITAL LETTER W WITH HOOK
#define UC_MACRO_NAME_2C73 0x2C73 // ⱳ LATIN SMALL LETTER W WITH HOOK
#define UC_MACRO_NAME_2C74 0x2C74 // ⱴ LATIN SMALL LETTER V WITH CURL
#define UC_MACRO_NAME_2C75 0x2C75 // Ⱶ LATIN CAPITAL LETTER HALF H
#define UC_MACRO_NAME_2C76 0x2C76 // ⱶ LATIN SMALL LETTER HALF H
#define UC_MACRO_NAME_2C77 0x2C77 // ⱷ LATIN SMALL LETTER TAILLESS PHI
#define UC_MACRO_NAME_2C78 0x2C78 // ⱸ LATIN SMALL LETTER E WITH NOTCH
#define UC_MACRO_NAME_2C79 0x2C79 // ⱹ LATIN SMALL LETTER TURNED R WITH TAIL
#define UC_MACRO_NAME_2C7A 0x2C7A // ⱺ LATIN SMALL LETTER O WITH LOW RING INSIDE
#define UC_MACRO_NAME_2C7B 0x2C7B // ⱻ LATIN LETTER SMALL CAPITAL TURNED E
#define UC_MACRO_NAME_2C7C 0x2C7C // ⱼ LATIN SUBSCRIPT SMALL LETTER J
#define UC_MACRO_NAME_2C7D 0x2C7D // ⱽ MODIFIER LETTER CAPITAL V
#define UC_MACRO_NAME_2C7E 0x2C7E // Ȿ LATIN CAPITAL LETTER S WITH SWASH TAIL
#define UC_MACRO_NAME_2C7F 0x2C7F // Ɀ LATIN CAPITAL LETTER Z WITH SWASH TAIL


#endif // UC_H_LATIN_EXTENDED_C
