/*
 * Unicode Block: Latin Extended-A
 * Range: U+0100..U+017F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Latin Extended-A is a Unicode block and is the third block of the
 * Unicode standard. It encodes Latin letters from the Latin ISO
 * character sets other than Latin-1 (which is already encoded in the
 * Latin-1 Supplement block) and also legacy characters from the ISO 6937
 * standard.
 * The Latin Extended-A block has been in the Unicode Standard since
 * version 1.0, with its entire character repertoire, except for the
 * Latin Small Letter Long S, which was added during unification with ISO
 * 10646 in version 1.1. Its block name in Unicode 1.0 was European Latin
 * .
 *
 */
#ifndef UC_H_LATIN_EXTENDED_A
#define UC_H_LATIN_EXTENDED_A

#define UC_MACRO_NAME_100 0x0100 // Ā LATIN CAPITAL LETTER A WITH MACRON
#define UC_MACRO_NAME_101 0x0101 // ā LATIN SMALL LETTER A WITH MACRON
#define UC_MACRO_NAME_102 0x0102 // Ă LATIN CAPITAL LETTER A WITH BREVE
#define UC_MACRO_NAME_103 0x0103 // ă LATIN SMALL LETTER A WITH BREVE
#define UC_MACRO_NAME_104 0x0104 // Ą LATIN CAPITAL LETTER A WITH OGONEK
#define UC_MACRO_NAME_105 0x0105 // ą LATIN SMALL LETTER A WITH OGONEK
#define UC_MACRO_NAME_106 0x0106 // Ć LATIN CAPITAL LETTER C WITH ACUTE
#define UC_MACRO_NAME_107 0x0107 // ć LATIN SMALL LETTER C WITH ACUTE
#define UC_MACRO_NAME_108 0x0108 // Ĉ LATIN CAPITAL LETTER C WITH CIRCUMFLEX
#define UC_MACRO_NAME_109 0x0109 // ĉ LATIN SMALL LETTER C WITH CIRCUMFLEX
#define UC_MACRO_NAME_10A 0x010A // Ċ LATIN CAPITAL LETTER C WITH DOT ABOVE
#define UC_MACRO_NAME_10B 0x010B // ċ LATIN SMALL LETTER C WITH DOT ABOVE
#define UC_MACRO_NAME_10C 0x010C // Č LATIN CAPITAL LETTER C WITH CARON
#define UC_MACRO_NAME_10D 0x010D // č LATIN SMALL LETTER C WITH CARON
#define UC_MACRO_NAME_10E 0x010E // Ď LATIN CAPITAL LETTER D WITH CARON
#define UC_MACRO_NAME_10F 0x010F // ď LATIN SMALL LETTER D WITH CARON
#define UC_MACRO_NAME_110 0x0110 // Đ LATIN CAPITAL LETTER D WITH STROKE
#define UC_MACRO_NAME_111 0x0111 // đ LATIN SMALL LETTER D WITH STROKE
#define UC_MACRO_NAME_112 0x0112 // Ē LATIN CAPITAL LETTER E WITH MACRON
#define UC_MACRO_NAME_113 0x0113 // ē LATIN SMALL LETTER E WITH MACRON
#define UC_MACRO_NAME_114 0x0114 // Ĕ LATIN CAPITAL LETTER E WITH BREVE
#define UC_MACRO_NAME_115 0x0115 // ĕ LATIN SMALL LETTER E WITH BREVE
#define UC_MACRO_NAME_116 0x0116 // Ė LATIN CAPITAL LETTER E WITH DOT ABOVE
#define UC_MACRO_NAME_117 0x0117 // ė LATIN SMALL LETTER E WITH DOT ABOVE
#define UC_MACRO_NAME_118 0x0118 // Ę LATIN CAPITAL LETTER E WITH OGONEK
#define UC_MACRO_NAME_119 0x0119 // ę LATIN SMALL LETTER E WITH OGONEK
#define UC_MACRO_NAME_11A 0x011A // Ě LATIN CAPITAL LETTER E WITH CARON
#define UC_MACRO_NAME_11B 0x011B // ě LATIN SMALL LETTER E WITH CARON
#define UC_MACRO_NAME_11C 0x011C // Ĝ LATIN CAPITAL LETTER G WITH CIRCUMFLEX
#define UC_MACRO_NAME_11D 0x011D // ĝ LATIN SMALL LETTER G WITH CIRCUMFLEX
#define UC_MACRO_NAME_11E 0x011E // Ğ LATIN CAPITAL LETTER G WITH BREVE
#define UC_MACRO_NAME_11F 0x011F // ğ LATIN SMALL LETTER G WITH BREVE
#define UC_MACRO_NAME_120 0x0120 // Ġ LATIN CAPITAL LETTER G WITH DOT ABOVE
#define UC_MACRO_NAME_121 0x0121 // ġ LATIN SMALL LETTER G WITH DOT ABOVE
#define UC_MACRO_NAME_122 0x0122 // Ģ LATIN CAPITAL LETTER G WITH CEDILLA
#define UC_MACRO_NAME_123 0x0123 // ģ LATIN SMALL LETTER G WITH CEDILLA
#define UC_MACRO_NAME_124 0x0124 // Ĥ LATIN CAPITAL LETTER H WITH CIRCUMFLEX
#define UC_MACRO_NAME_125 0x0125 // ĥ LATIN SMALL LETTER H WITH CIRCUMFLEX
#define UC_MACRO_NAME_126 0x0126 // Ħ LATIN CAPITAL LETTER H WITH STROKE
#define UC_MACRO_NAME_127 0x0127 // ħ LATIN SMALL LETTER H WITH STROKE
#define UC_MACRO_NAME_128 0x0128 // Ĩ LATIN CAPITAL LETTER I WITH TILDE
#define UC_MACRO_NAME_129 0x0129 // ĩ LATIN SMALL LETTER I WITH TILDE
#define UC_MACRO_NAME_12A 0x012A // Ī LATIN CAPITAL LETTER I WITH MACRON
#define UC_MACRO_NAME_12B 0x012B // ī LATIN SMALL LETTER I WITH MACRON
#define UC_MACRO_NAME_12C 0x012C // Ĭ LATIN CAPITAL LETTER I WITH BREVE
#define UC_MACRO_NAME_12D 0x012D // ĭ LATIN SMALL LETTER I WITH BREVE
#define UC_MACRO_NAME_12E 0x012E // Į LATIN CAPITAL LETTER I WITH OGONEK
#define UC_MACRO_NAME_12F 0x012F // į LATIN SMALL LETTER I WITH OGONEK
#define UC_MACRO_NAME_130 0x0130 // İ LATIN CAPITAL LETTER I WITH DOT ABOVE
#define UC_MACRO_NAME_131 0x0131 // ı LATIN SMALL LETTER DOTLESS I
#define UC_MACRO_NAME_132 0x0132 // Ĳ LATIN CAPITAL LIGATURE IJ
#define UC_MACRO_NAME_133 0x0133 // ĳ LATIN SMALL LIGATURE IJ
#define UC_MACRO_NAME_134 0x0134 // Ĵ LATIN CAPITAL LETTER J WITH CIRCUMFLEX
#define UC_MACRO_NAME_135 0x0135 // ĵ LATIN SMALL LETTER J WITH CIRCUMFLEX
#define UC_MACRO_NAME_136 0x0136 // Ķ LATIN CAPITAL LETTER K WITH CEDILLA
#define UC_MACRO_NAME_137 0x0137 // ķ LATIN SMALL LETTER K WITH CEDILLA
#define UC_MACRO_NAME_138 0x0138 // ĸ LATIN SMALL LETTER KRA
#define UC_MACRO_NAME_139 0x0139 // Ĺ LATIN CAPITAL LETTER L WITH ACUTE
#define UC_MACRO_NAME_13A 0x013A // ĺ LATIN SMALL LETTER L WITH ACUTE
#define UC_MACRO_NAME_13B 0x013B // Ļ LATIN CAPITAL LETTER L WITH CEDILLA
#define UC_MACRO_NAME_13C 0x013C // ļ LATIN SMALL LETTER L WITH CEDILLA
#define UC_MACRO_NAME_13D 0x013D // Ľ LATIN CAPITAL LETTER L WITH CARON
#define UC_MACRO_NAME_13E 0x013E // ľ LATIN SMALL LETTER L WITH CARON
#define UC_MACRO_NAME_13F 0x013F // Ŀ LATIN CAPITAL LETTER L WITH MIDDLE DOT
#define UC_MACRO_NAME_140 0x0140 // ŀ LATIN SMALL LETTER L WITH MIDDLE DOT
#define UC_MACRO_NAME_141 0x0141 // Ł LATIN CAPITAL LETTER L WITH STROKE
#define UC_MACRO_NAME_142 0x0142 // ł LATIN SMALL LETTER L WITH STROKE
#define UC_MACRO_NAME_143 0x0143 // Ń LATIN CAPITAL LETTER N WITH ACUTE
#define UC_MACRO_NAME_144 0x0144 // ń LATIN SMALL LETTER N WITH ACUTE
#define UC_MACRO_NAME_145 0x0145 // Ņ LATIN CAPITAL LETTER N WITH CEDILLA
#define UC_MACRO_NAME_146 0x0146 // ņ LATIN SMALL LETTER N WITH CEDILLA
#define UC_MACRO_NAME_147 0x0147 // Ň LATIN CAPITAL LETTER N WITH CARON
#define UC_MACRO_NAME_148 0x0148 // ň LATIN SMALL LETTER N WITH CARON
#define UC_MACRO_NAME_149 0x0149 // ŉ LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
#define UC_MACRO_NAME_14A 0x014A // Ŋ LATIN CAPITAL LETTER ENG
#define UC_MACRO_NAME_14B 0x014B // ŋ LATIN SMALL LETTER ENG
#define UC_MACRO_NAME_14C 0x014C // Ō LATIN CAPITAL LETTER O WITH MACRON
#define UC_MACRO_NAME_14D 0x014D // ō LATIN SMALL LETTER O WITH MACRON
#define UC_MACRO_NAME_14E 0x014E // Ŏ LATIN CAPITAL LETTER O WITH BREVE
#define UC_MACRO_NAME_14F 0x014F // ŏ LATIN SMALL LETTER O WITH BREVE
#define UC_MACRO_NAME_150 0x0150 // Ő LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
#define UC_MACRO_NAME_151 0x0151 // ő LATIN SMALL LETTER O WITH DOUBLE ACUTE
#define UC_MACRO_NAME_152 0x0152 // Œ LATIN CAPITAL LIGATURE OE
#define UC_MACRO_NAME_153 0x0153 // œ LATIN SMALL LIGATURE OE
#define UC_MACRO_NAME_154 0x0154 // Ŕ LATIN CAPITAL LETTER R WITH ACUTE
#define UC_MACRO_NAME_155 0x0155 // ŕ LATIN SMALL LETTER R WITH ACUTE
#define UC_MACRO_NAME_156 0x0156 // Ŗ LATIN CAPITAL LETTER R WITH CEDILLA
#define UC_MACRO_NAME_157 0x0157 // ŗ LATIN SMALL LETTER R WITH CEDILLA
#define UC_MACRO_NAME_158 0x0158 // Ř LATIN CAPITAL LETTER R WITH CARON
#define UC_MACRO_NAME_159 0x0159 // ř LATIN SMALL LETTER R WITH CARON
#define UC_MACRO_NAME_15A 0x015A // Ś LATIN CAPITAL LETTER S WITH ACUTE
#define UC_MACRO_NAME_15B 0x015B // ś LATIN SMALL LETTER S WITH ACUTE
#define UC_MACRO_NAME_15C 0x015C // Ŝ LATIN CAPITAL LETTER S WITH CIRCUMFLEX
#define UC_MACRO_NAME_15D 0x015D // ŝ LATIN SMALL LETTER S WITH CIRCUMFLEX
#define UC_MACRO_NAME_15E 0x015E // Ş LATIN CAPITAL LETTER S WITH CEDILLA
#define UC_MACRO_NAME_15F 0x015F // ş LATIN SMALL LETTER S WITH CEDILLA
#define UC_MACRO_NAME_160 0x0160 // Š LATIN CAPITAL LETTER S WITH CARON
#define UC_MACRO_NAME_161 0x0161 // š LATIN SMALL LETTER S WITH CARON
#define UC_MACRO_NAME_162 0x0162 // Ţ LATIN CAPITAL LETTER T WITH CEDILLA
#define UC_MACRO_NAME_163 0x0163 // ţ LATIN SMALL LETTER T WITH CEDILLA
#define UC_MACRO_NAME_164 0x0164 // Ť LATIN CAPITAL LETTER T WITH CARON
#define UC_MACRO_NAME_165 0x0165 // ť LATIN SMALL LETTER T WITH CARON
#define UC_MACRO_NAME_166 0x0166 // Ŧ LATIN CAPITAL LETTER T WITH STROKE
#define UC_MACRO_NAME_167 0x0167 // ŧ LATIN SMALL LETTER T WITH STROKE
#define UC_MACRO_NAME_168 0x0168 // Ũ LATIN CAPITAL LETTER U WITH TILDE
#define UC_MACRO_NAME_169 0x0169 // ũ LATIN SMALL LETTER U WITH TILDE
#define UC_MACRO_NAME_16A 0x016A // Ū LATIN CAPITAL LETTER U WITH MACRON
#define UC_MACRO_NAME_16B 0x016B // ū LATIN SMALL LETTER U WITH MACRON
#define UC_MACRO_NAME_16C 0x016C // Ŭ LATIN CAPITAL LETTER U WITH BREVE
#define UC_MACRO_NAME_16D 0x016D // ŭ LATIN SMALL LETTER U WITH BREVE
#define UC_MACRO_NAME_16E 0x016E // Ů LATIN CAPITAL LETTER U WITH RING ABOVE
#define UC_MACRO_NAME_16F 0x016F // ů LATIN SMALL LETTER U WITH RING ABOVE
#define UC_MACRO_NAME_170 0x0170 // Ű LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
#define UC_MACRO_NAME_171 0x0171 // ű LATIN SMALL LETTER U WITH DOUBLE ACUTE
#define UC_MACRO_NAME_172 0x0172 // Ų LATIN CAPITAL LETTER U WITH OGONEK
#define UC_MACRO_NAME_173 0x0173 // ų LATIN SMALL LETTER U WITH OGONEK
#define UC_MACRO_NAME_174 0x0174 // Ŵ LATIN CAPITAL LETTER W WITH CIRCUMFLEX
#define UC_MACRO_NAME_175 0x0175 // ŵ LATIN SMALL LETTER W WITH CIRCUMFLEX
#define UC_MACRO_NAME_176 0x0176 // Ŷ LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
#define UC_MACRO_NAME_177 0x0177 // ŷ LATIN SMALL LETTER Y WITH CIRCUMFLEX
#define UC_MACRO_NAME_178 0x0178 // Ÿ LATIN CAPITAL LETTER Y WITH DIAERESIS
#define UC_MACRO_NAME_179 0x0179 // Ź LATIN CAPITAL LETTER Z WITH ACUTE
#define UC_MACRO_NAME_17A 0x017A // ź LATIN SMALL LETTER Z WITH ACUTE
#define UC_MACRO_NAME_17B 0x017B // Ż LATIN CAPITAL LETTER Z WITH DOT ABOVE
#define UC_MACRO_NAME_17C 0x017C // ż LATIN SMALL LETTER Z WITH DOT ABOVE
#define UC_MACRO_NAME_17D 0x017D // Ž LATIN CAPITAL LETTER Z WITH CARON
#define UC_MACRO_NAME_17E 0x017E // ž LATIN SMALL LETTER Z WITH CARON
#define UC_MACRO_NAME_17F 0x017F // ſ LATIN SMALL LETTER LONG S


#endif // UC_H_LATIN_EXTENDED_A
