/*
 * Unicode Block: Latin Extended-E
 * Range: U+AB30..U+AB6F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_LATIN_EXTENDED_E
#define UC_H_LATIN_EXTENDED_E

#define UC_MACRO_NAME_AB30 0xAB30 // ꬰ LATIN SMALL LETTER BARRED ALPHA
#define UC_MACRO_NAME_AB31 0xAB31 // ꬱ LATIN SMALL LETTER A REVERSED-SCHWA
#define UC_MACRO_NAME_AB32 0xAB32 // ꬲ LATIN SMALL LETTER BLACKLETTER E
#define UC_MACRO_NAME_AB33 0xAB33 // ꬳ LATIN SMALL LETTER BARRED E
#define UC_MACRO_NAME_AB34 0xAB34 // ꬴ LATIN SMALL LETTER E WITH FLOURISH
#define UC_MACRO_NAME_AB35 0xAB35 // ꬵ LATIN SMALL LETTER LENIS F
#define UC_MACRO_NAME_AB36 0xAB36 // ꬶ LATIN SMALL LETTER SCRIPT G WITH CROSSED-TAIL
#define UC_MACRO_NAME_AB37 0xAB37 // ꬷ LATIN SMALL LETTER L WITH INVERTED LAZY S
#define UC_MACRO_NAME_AB38 0xAB38 // ꬸ LATIN SMALL LETTER L WITH DOUBLE MIDDLE TILDE
#define UC_MACRO_NAME_AB39 0xAB39 // ꬹ LATIN SMALL LETTER L WITH MIDDLE RING
#define UC_MACRO_NAME_AB3A 0xAB3A // ꬺ LATIN SMALL LETTER M WITH CROSSED-TAIL
#define UC_MACRO_NAME_AB3B 0xAB3B // ꬻ LATIN SMALL LETTER N WITH CROSSED-TAIL
#define UC_MACRO_NAME_AB3C 0xAB3C // ꬼ LATIN SMALL LETTER ENG WITH CROSSED-TAIL
#define UC_MACRO_NAME_AB3D 0xAB3D // ꬽ LATIN SMALL LETTER BLACKLETTER O
#define UC_MACRO_NAME_AB3E 0xAB3E // ꬾ LATIN SMALL LETTER BLACKLETTER O WITH STROKE
#define UC_MACRO_NAME_AB3F 0xAB3F // ꬿ LATIN SMALL LETTER OPEN O WITH STROKE
#define UC_MACRO_NAME_AB40 0xAB40 // ꭀ LATIN SMALL LETTER INVERTED OE
#define UC_MACRO_NAME_AB41 0xAB41 // ꭁ LATIN SMALL LETTER TURNED OE WITH STROKE
#define UC_MACRO_NAME_AB42 0xAB42 // ꭂ LATIN SMALL LETTER TURNED OE WITH HORIZONTAL STROKE
#define UC_MACRO_NAME_AB43 0xAB43 // ꭃ LATIN SMALL LETTER TURNED O OPEN-O
#define UC_MACRO_NAME_AB44 0xAB44 // ꭄ LATIN SMALL LETTER TURNED O OPEN-O WITH STROKE
#define UC_MACRO_NAME_AB45 0xAB45 // ꭅ LATIN SMALL LETTER STIRRUP R
#define UC_MACRO_NAME_AB46 0xAB46 // ꭆ LATIN LETTER SMALL CAPITAL R WITH RIGHT LEG
#define UC_MACRO_NAME_AB47 0xAB47 // ꭇ LATIN SMALL LETTER R WITHOUT HANDLE
#define UC_MACRO_NAME_AB48 0xAB48 // ꭈ LATIN SMALL LETTER DOUBLE R
#define UC_MACRO_NAME_AB49 0xAB49 // ꭉ LATIN SMALL LETTER R WITH CROSSED-TAIL
#define UC_MACRO_NAME_AB4A 0xAB4A // ꭊ LATIN SMALL LETTER DOUBLE R WITH CROSSED-TAIL
#define UC_MACRO_NAME_AB4B 0xAB4B // ꭋ LATIN SMALL LETTER SCRIPT R
#define UC_MACRO_NAME_AB4C 0xAB4C // ꭌ LATIN SMALL LETTER SCRIPT R WITH RING
#define UC_MACRO_NAME_AB4D 0xAB4D // ꭍ LATIN SMALL LETTER BASELINE ESH
#define UC_MACRO_NAME_AB4E 0xAB4E // ꭎ LATIN SMALL LETTER U WITH SHORT RIGHT LEG
#define UC_MACRO_NAME_AB4F 0xAB4F // ꭏ LATIN SMALL LETTER U BAR WITH SHORT RIGHT LEG
#define UC_MACRO_NAME_AB50 0xAB50 // ꭐ LATIN SMALL LETTER UI
#define UC_MACRO_NAME_AB51 0xAB51 // ꭑ LATIN SMALL LETTER TURNED UI
#define UC_MACRO_NAME_AB52 0xAB52 // ꭒ LATIN SMALL LETTER U WITH LEFT HOOK
#define UC_MACRO_NAME_AB53 0xAB53 // ꭓ LATIN SMALL LETTER CHI
#define UC_MACRO_NAME_AB54 0xAB54 // ꭔ LATIN SMALL LETTER CHI WITH LOW RIGHT RING
#define UC_MACRO_NAME_AB55 0xAB55 // ꭕ LATIN SMALL LETTER CHI WITH LOW LEFT SERIF
#define UC_MACRO_NAME_AB56 0xAB56 // ꭖ LATIN SMALL LETTER X WITH LOW RIGHT RING
#define UC_MACRO_NAME_AB57 0xAB57 // ꭗ LATIN SMALL LETTER X WITH LONG LEFT LEG
#define UC_MACRO_NAME_AB58 0xAB58 // ꭘ LATIN SMALL LETTER X WITH LONG LEFT LEG AND LOW RIGHT RING
#define UC_MACRO_NAME_AB59 0xAB59 // ꭙ LATIN SMALL LETTER X WITH LONG LEFT LEG WITH SERIF
#define UC_MACRO_NAME_AB5A 0xAB5A // ꭚ LATIN SMALL LETTER Y WITH SHORT RIGHT LEG
#define UC_MACRO_NAME_AB5B 0xAB5B // ꭛ MODIFIER BREVE WITH INVERTED BREVE
#define UC_MACRO_NAME_AB5C 0xAB5C // ꭜ MODIFIER LETTER SMALL HENG
#define UC_MACRO_NAME_AB5D 0xAB5D // ꭝ MODIFIER LETTER SMALL L WITH INVERTED LAZY S
#define UC_MACRO_NAME_AB5E 0xAB5E // ꭞ MODIFIER LETTER SMALL L WITH MIDDLE TILDE
#define UC_MACRO_NAME_AB5F 0xAB5F // ꭟ MODIFIER LETTER SMALL U WITH LEFT HOOK
#define UC_MACRO_NAME_AB60 0xAB60 // ꭠ LATIN SMALL LETTER SAKHA YAT
#define UC_MACRO_NAME_AB61 0xAB61 // ꭡ LATIN SMALL LETTER IOTIFIED E
#define UC_MACRO_NAME_AB62 0xAB62 // ꭢ LATIN SMALL LETTER OPEN OE
#define UC_MACRO_NAME_AB63 0xAB63 // ꭣ LATIN SMALL LETTER UO
#define UC_MACRO_NAME_AB64 0xAB64 // ꭤ LATIN SMALL LETTER INVERTED ALPHA
#define UC_MACRO_NAME_AB65 0xAB65 // ꭥ GREEK LETTER SMALL CAPITAL OMEGA
#define UC_MACRO_NAME_AB66 0xAB66 // ꭦ LATIN SMALL LETTER DZ DIGRAPH WITH RETROFLEX HOOK
#define UC_MACRO_NAME_AB67 0xAB67 // ꭧ LATIN SMALL LETTER TS DIGRAPH WITH RETROFLEX HOOK
#define UC_MACRO_NAME_AB68 0xAB68 // ꭨ LATIN SMALL LETTER TURNED R WITH MIDDLE TILDE
#define UC_MACRO_NAME_AB69 0xAB69 // ꭩ MODIFIER LETTER SMALL TURNED W
#define UC_MACRO_NAME_AB6A 0xAB6A // ꭪ MODIFIER LETTER LEFT TACK
#define UC_MACRO_NAME_AB6B 0xAB6B // ꭫ MODIFIER LETTER RIGHT TACK


#endif // UC_H_LATIN_EXTENDED_E
