/*
 * Unicode Block: Latin Extended-B
 * Range: U+0180..U+024F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Latin Extended-B is the fourth block (0180-024F) of the Unicode
 * Standard. It has been included since version 1.0, where it was only
 * allocated to the code points 0180-01FF and contained 113 characters.
 * During unification with ISO 10646 for version 1.1, the block range was
 * extended by 80 code points and another 35 characters were assigned. In
 * version 3.0 and later, the last 60 available code points in the block
 * were assigned. Its block name in Unicode 1.0 was Extended Latin .
 *
 */
#ifndef UC_H_LATIN_EXTENDED_B
#define UC_H_LATIN_EXTENDED_B

#define UC_MACRO_NAME_180 0x0180 // ƀ LATIN SMALL LETTER B WITH STROKE
#define UC_MACRO_NAME_181 0x0181 // Ɓ LATIN CAPITAL LETTER B WITH HOOK
#define UC_MACRO_NAME_182 0x0182 // Ƃ LATIN CAPITAL LETTER B WITH TOPBAR
#define UC_MACRO_NAME_183 0x0183 // ƃ LATIN SMALL LETTER B WITH TOPBAR
#define UC_MACRO_NAME_184 0x0184 // Ƅ LATIN CAPITAL LETTER TONE SIX
#define UC_MACRO_NAME_185 0x0185 // ƅ LATIN SMALL LETTER TONE SIX
#define UC_MACRO_NAME_186 0x0186 // Ɔ LATIN CAPITAL LETTER OPEN O
#define UC_MACRO_NAME_187 0x0187 // Ƈ LATIN CAPITAL LETTER C WITH HOOK
#define UC_MACRO_NAME_188 0x0188 // ƈ LATIN SMALL LETTER C WITH HOOK
#define UC_MACRO_NAME_189 0x0189 // Ɖ LATIN CAPITAL LETTER AFRICAN D
#define UC_MACRO_NAME_18A 0x018A // Ɗ LATIN CAPITAL LETTER D WITH HOOK
#define UC_MACRO_NAME_18B 0x018B // Ƌ LATIN CAPITAL LETTER D WITH TOPBAR
#define UC_MACRO_NAME_18C 0x018C // ƌ LATIN SMALL LETTER D WITH TOPBAR
#define UC_MACRO_NAME_18D 0x018D // ƍ LATIN SMALL LETTER TURNED DELTA
#define UC_MACRO_NAME_18E 0x018E // Ǝ LATIN CAPITAL LETTER REVERSED E
#define UC_MACRO_NAME_18F 0x018F // Ə LATIN CAPITAL LETTER SCHWA
#define UC_MACRO_NAME_190 0x0190 // Ɛ LATIN CAPITAL LETTER OPEN E
#define UC_MACRO_NAME_191 0x0191 // Ƒ LATIN CAPITAL LETTER F WITH HOOK
#define UC_MACRO_NAME_192 0x0192 // ƒ LATIN SMALL LETTER F WITH HOOK
#define UC_MACRO_NAME_193 0x0193 // Ɠ LATIN CAPITAL LETTER G WITH HOOK
#define UC_MACRO_NAME_194 0x0194 // Ɣ LATIN CAPITAL LETTER GAMMA
#define UC_MACRO_NAME_195 0x0195 // ƕ LATIN SMALL LETTER HV
#define UC_MACRO_NAME_196 0x0196 // Ɩ LATIN CAPITAL LETTER IOTA
#define UC_MACRO_NAME_197 0x0197 // Ɨ LATIN CAPITAL LETTER I WITH STROKE
#define UC_MACRO_NAME_198 0x0198 // Ƙ LATIN CAPITAL LETTER K WITH HOOK
#define UC_MACRO_NAME_199 0x0199 // ƙ LATIN SMALL LETTER K WITH HOOK
#define UC_MACRO_NAME_19A 0x019A // ƚ LATIN SMALL LETTER L WITH BAR
#define UC_MACRO_NAME_19B 0x019B // ƛ LATIN SMALL LETTER LAMBDA WITH STROKE
#define UC_MACRO_NAME_19C 0x019C // Ɯ LATIN CAPITAL LETTER TURNED M
#define UC_MACRO_NAME_19D 0x019D // Ɲ LATIN CAPITAL LETTER N WITH LEFT HOOK
#define UC_MACRO_NAME_19E 0x019E // ƞ LATIN SMALL LETTER N WITH LONG RIGHT LEG
#define UC_MACRO_NAME_19F 0x019F // Ɵ LATIN CAPITAL LETTER O WITH MIDDLE TILDE
#define UC_MACRO_NAME_1A0 0x01A0 // Ơ LATIN CAPITAL LETTER O WITH HORN
#define UC_MACRO_NAME_1A1 0x01A1 // ơ LATIN SMALL LETTER O WITH HORN
#define UC_MACRO_NAME_1A2 0x01A2 // Ƣ LATIN CAPITAL LETTER OI
#define UC_MACRO_NAME_1A3 0x01A3 // ƣ LATIN SMALL LETTER OI
#define UC_MACRO_NAME_1A4 0x01A4 // Ƥ LATIN CAPITAL LETTER P WITH HOOK
#define UC_MACRO_NAME_1A5 0x01A5 // ƥ LATIN SMALL LETTER P WITH HOOK
#define UC_MACRO_NAME_1A6 0x01A6 // Ʀ LATIN LETTER YR
#define UC_MACRO_NAME_1A7 0x01A7 // Ƨ LATIN CAPITAL LETTER TONE TWO
#define UC_MACRO_NAME_1A8 0x01A8 // ƨ LATIN SMALL LETTER TONE TWO
#define UC_MACRO_NAME_1A9 0x01A9 // Ʃ LATIN CAPITAL LETTER ESH
#define UC_MACRO_NAME_1AA 0x01AA // ƪ LATIN LETTER REVERSED ESH LOOP
#define UC_MACRO_NAME_1AB 0x01AB // ƫ LATIN SMALL LETTER T WITH PALATAL HOOK
#define UC_MACRO_NAME_1AC 0x01AC // Ƭ LATIN CAPITAL LETTER T WITH HOOK
#define UC_MACRO_NAME_1AD 0x01AD // ƭ LATIN SMALL LETTER T WITH HOOK
#define UC_MACRO_NAME_1AE 0x01AE // Ʈ LATIN CAPITAL LETTER T WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1AF 0x01AF // Ư LATIN CAPITAL LETTER U WITH HORN
#define UC_MACRO_NAME_1B0 0x01B0 // ư LATIN SMALL LETTER U WITH HORN
#define UC_MACRO_NAME_1B1 0x01B1 // Ʊ LATIN CAPITAL LETTER UPSILON
#define UC_MACRO_NAME_1B2 0x01B2 // Ʋ LATIN CAPITAL LETTER V WITH HOOK
#define UC_MACRO_NAME_1B3 0x01B3 // Ƴ LATIN CAPITAL LETTER Y WITH HOOK
#define UC_MACRO_NAME_1B4 0x01B4 // ƴ LATIN SMALL LETTER Y WITH HOOK
#define UC_MACRO_NAME_1B5 0x01B5 // Ƶ LATIN CAPITAL LETTER Z WITH STROKE
#define UC_MACRO_NAME_1B6 0x01B6 // ƶ LATIN SMALL LETTER Z WITH STROKE
#define UC_MACRO_NAME_1B7 0x01B7 // Ʒ LATIN CAPITAL LETTER EZH
#define UC_MACRO_NAME_1B8 0x01B8 // Ƹ LATIN CAPITAL LETTER EZH REVERSED
#define UC_MACRO_NAME_1B9 0x01B9 // ƹ LATIN SMALL LETTER EZH REVERSED
#define UC_MACRO_NAME_1BA 0x01BA // ƺ LATIN SMALL LETTER EZH WITH TAIL
#define UC_MACRO_NAME_1BB 0x01BB // ƻ LATIN LETTER TWO WITH STROKE
#define UC_MACRO_NAME_1BC 0x01BC // Ƽ LATIN CAPITAL LETTER TONE FIVE
#define UC_MACRO_NAME_1BD 0x01BD // ƽ LATIN SMALL LETTER TONE FIVE
#define UC_MACRO_NAME_1BE 0x01BE // ƾ LATIN LETTER INVERTED GLOTTAL STOP WITH STROKE
#define UC_MACRO_NAME_1BF 0x01BF // ƿ LATIN LETTER WYNN
#define UC_MACRO_NAME_1C0 0x01C0 // ǀ LATIN LETTER DENTAL CLICK
#define UC_MACRO_NAME_1C1 0x01C1 // ǁ LATIN LETTER LATERAL CLICK
#define UC_MACRO_NAME_1C2 0x01C2 // ǂ LATIN LETTER ALVEOLAR CLICK
#define UC_MACRO_NAME_1C3 0x01C3 // ǃ LATIN LETTER RETROFLEX CLICK
#define UC_MACRO_NAME_1C4 0x01C4 // Ǆ LATIN CAPITAL LETTER DZ WITH CARON
#define UC_MACRO_NAME_1C5 0x01C5 // ǅ LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON
#define UC_MACRO_NAME_1C6 0x01C6 // ǆ LATIN SMALL LETTER DZ WITH CARON
#define UC_MACRO_NAME_1C7 0x01C7 // Ǉ LATIN CAPITAL LETTER LJ
#define UC_MACRO_NAME_1C8 0x01C8 // ǈ LATIN CAPITAL LETTER L WITH SMALL LETTER J
#define UC_MACRO_NAME_1C9 0x01C9 // ǉ LATIN SMALL LETTER LJ
#define UC_MACRO_NAME_1CA 0x01CA // Ǌ LATIN CAPITAL LETTER NJ
#define UC_MACRO_NAME_1CB 0x01CB // ǋ LATIN CAPITAL LETTER N WITH SMALL LETTER J
#define UC_MACRO_NAME_1CC 0x01CC // ǌ LATIN SMALL LETTER NJ
#define UC_MACRO_NAME_1CD 0x01CD // Ǎ LATIN CAPITAL LETTER A WITH CARON
#define UC_MACRO_NAME_1CE 0x01CE // ǎ LATIN SMALL LETTER A WITH CARON
#define UC_MACRO_NAME_1CF 0x01CF // Ǐ LATIN CAPITAL LETTER I WITH CARON
#define UC_MACRO_NAME_1D0 0x01D0 // ǐ LATIN SMALL LETTER I WITH CARON
#define UC_MACRO_NAME_1D1 0x01D1 // Ǒ LATIN CAPITAL LETTER O WITH CARON
#define UC_MACRO_NAME_1D2 0x01D2 // ǒ LATIN SMALL LETTER O WITH CARON
#define UC_MACRO_NAME_1D3 0x01D3 // Ǔ LATIN CAPITAL LETTER U WITH CARON
#define UC_MACRO_NAME_1D4 0x01D4 // ǔ LATIN SMALL LETTER U WITH CARON
#define UC_MACRO_NAME_1D5 0x01D5 // Ǖ LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON
#define UC_MACRO_NAME_1D6 0x01D6 // ǖ LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
#define UC_MACRO_NAME_1D7 0x01D7 // Ǘ LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE
#define UC_MACRO_NAME_1D8 0x01D8 // ǘ LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
#define UC_MACRO_NAME_1D9 0x01D9 // Ǚ LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON
#define UC_MACRO_NAME_1DA 0x01DA // ǚ LATIN SMALL LETTER U WITH DIAERESIS AND CARON
#define UC_MACRO_NAME_1DB 0x01DB // Ǜ LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE
#define UC_MACRO_NAME_1DC 0x01DC // ǜ LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
#define UC_MACRO_NAME_1DD 0x01DD // ǝ LATIN SMALL LETTER TURNED E
#define UC_MACRO_NAME_1DE 0x01DE // Ǟ LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON
#define UC_MACRO_NAME_1DF 0x01DF // ǟ LATIN SMALL LETTER A WITH DIAERESIS AND MACRON
#define UC_MACRO_NAME_1E0 0x01E0 // Ǡ LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON
#define UC_MACRO_NAME_1E1 0x01E1 // ǡ LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON
#define UC_MACRO_NAME_1E2 0x01E2 // Ǣ LATIN CAPITAL LETTER AE WITH MACRON
#define UC_MACRO_NAME_1E3 0x01E3 // ǣ LATIN SMALL LETTER AE WITH MACRON
#define UC_MACRO_NAME_1E4 0x01E4 // Ǥ LATIN CAPITAL LETTER G WITH STROKE
#define UC_MACRO_NAME_1E5 0x01E5 // ǥ LATIN SMALL LETTER G WITH STROKE
#define UC_MACRO_NAME_1E6 0x01E6 // Ǧ LATIN CAPITAL LETTER G WITH CARON
#define UC_MACRO_NAME_1E7 0x01E7 // ǧ LATIN SMALL LETTER G WITH CARON
#define UC_MACRO_NAME_1E8 0x01E8 // Ǩ LATIN CAPITAL LETTER K WITH CARON
#define UC_MACRO_NAME_1E9 0x01E9 // ǩ LATIN SMALL LETTER K WITH CARON
#define UC_MACRO_NAME_1EA 0x01EA // Ǫ LATIN CAPITAL LETTER O WITH OGONEK
#define UC_MACRO_NAME_1EB 0x01EB // ǫ LATIN SMALL LETTER O WITH OGONEK
#define UC_MACRO_NAME_1EC 0x01EC // Ǭ LATIN CAPITAL LETTER O WITH OGONEK AND MACRON
#define UC_MACRO_NAME_1ED 0x01ED // ǭ LATIN SMALL LETTER O WITH OGONEK AND MACRON
#define UC_MACRO_NAME_1EE 0x01EE // Ǯ LATIN CAPITAL LETTER EZH WITH CARON
#define UC_MACRO_NAME_1EF 0x01EF // ǯ LATIN SMALL LETTER EZH WITH CARON
#define UC_MACRO_NAME_1F0 0x01F0 // ǰ LATIN SMALL LETTER J WITH CARON
#define UC_MACRO_NAME_1F1 0x01F1 // Ǳ LATIN CAPITAL LETTER DZ
#define UC_MACRO_NAME_1F2 0x01F2 // ǲ LATIN CAPITAL LETTER D WITH SMALL LETTER Z
#define UC_MACRO_NAME_1F3 0x01F3 // ǳ LATIN SMALL LETTER DZ
#define UC_MACRO_NAME_1F4 0x01F4 // Ǵ LATIN CAPITAL LETTER G WITH ACUTE
#define UC_MACRO_NAME_1F5 0x01F5 // ǵ LATIN SMALL LETTER G WITH ACUTE
#define UC_MACRO_NAME_1F6 0x01F6 // Ƕ LATIN CAPITAL LETTER HWAIR
#define UC_MACRO_NAME_1F7 0x01F7 // Ƿ LATIN CAPITAL LETTER WYNN
#define UC_MACRO_NAME_1F8 0x01F8 // Ǹ LATIN CAPITAL LETTER N WITH GRAVE
#define UC_MACRO_NAME_1F9 0x01F9 // ǹ LATIN SMALL LETTER N WITH GRAVE
#define UC_MACRO_NAME_1FA 0x01FA // Ǻ LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE
#define UC_MACRO_NAME_1FB 0x01FB // ǻ LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
#define UC_MACRO_NAME_1FC 0x01FC // Ǽ LATIN CAPITAL LETTER AE WITH ACUTE
#define UC_MACRO_NAME_1FD 0x01FD // ǽ LATIN SMALL LETTER AE WITH ACUTE
#define UC_MACRO_NAME_1FE 0x01FE // Ǿ LATIN CAPITAL LETTER O WITH STROKE AND ACUTE
#define UC_MACRO_NAME_1FF 0x01FF // ǿ LATIN SMALL LETTER O WITH STROKE AND ACUTE
#define UC_MACRO_NAME_200 0x0200 // Ȁ LATIN CAPITAL LETTER A WITH DOUBLE GRAVE
#define UC_MACRO_NAME_201 0x0201 // ȁ LATIN SMALL LETTER A WITH DOUBLE GRAVE
#define UC_MACRO_NAME_202 0x0202 // Ȃ LATIN CAPITAL LETTER A WITH INVERTED BREVE
#define UC_MACRO_NAME_203 0x0203 // ȃ LATIN SMALL LETTER A WITH INVERTED BREVE
#define UC_MACRO_NAME_204 0x0204 // Ȅ LATIN CAPITAL LETTER E WITH DOUBLE GRAVE
#define UC_MACRO_NAME_205 0x0205 // ȅ LATIN SMALL LETTER E WITH DOUBLE GRAVE
#define UC_MACRO_NAME_206 0x0206 // Ȇ LATIN CAPITAL LETTER E WITH INVERTED BREVE
#define UC_MACRO_NAME_207 0x0207 // ȇ LATIN SMALL LETTER E WITH INVERTED BREVE
#define UC_MACRO_NAME_208 0x0208 // Ȉ LATIN CAPITAL LETTER I WITH DOUBLE GRAVE
#define UC_MACRO_NAME_209 0x0209 // ȉ LATIN SMALL LETTER I WITH DOUBLE GRAVE
#define UC_MACRO_NAME_20A 0x020A // Ȋ LATIN CAPITAL LETTER I WITH INVERTED BREVE
#define UC_MACRO_NAME_20B 0x020B // ȋ LATIN SMALL LETTER I WITH INVERTED BREVE
#define UC_MACRO_NAME_20C 0x020C // Ȍ LATIN CAPITAL LETTER O WITH DOUBLE GRAVE
#define UC_MACRO_NAME_20D 0x020D // ȍ LATIN SMALL LETTER O WITH DOUBLE GRAVE
#define UC_MACRO_NAME_20E 0x020E // Ȏ LATIN CAPITAL LETTER O WITH INVERTED BREVE
#define UC_MACRO_NAME_20F 0x020F // ȏ LATIN SMALL LETTER O WITH INVERTED BREVE
#define UC_MACRO_NAME_210 0x0210 // Ȑ LATIN CAPITAL LETTER R WITH DOUBLE GRAVE
#define UC_MACRO_NAME_211 0x0211 // ȑ LATIN SMALL LETTER R WITH DOUBLE GRAVE
#define UC_MACRO_NAME_212 0x0212 // Ȓ LATIN CAPITAL LETTER R WITH INVERTED BREVE
#define UC_MACRO_NAME_213 0x0213 // ȓ LATIN SMALL LETTER R WITH INVERTED BREVE
#define UC_MACRO_NAME_214 0x0214 // Ȕ LATIN CAPITAL LETTER U WITH DOUBLE GRAVE
#define UC_MACRO_NAME_215 0x0215 // ȕ LATIN SMALL LETTER U WITH DOUBLE GRAVE
#define UC_MACRO_NAME_216 0x0216 // Ȗ LATIN CAPITAL LETTER U WITH INVERTED BREVE
#define UC_MACRO_NAME_217 0x0217 // ȗ LATIN SMALL LETTER U WITH INVERTED BREVE
#define UC_MACRO_NAME_218 0x0218 // Ș LATIN CAPITAL LETTER S WITH COMMA BELOW
#define UC_MACRO_NAME_219 0x0219 // ș LATIN SMALL LETTER S WITH COMMA BELOW
#define UC_MACRO_NAME_21A 0x021A // Ț LATIN CAPITAL LETTER T WITH COMMA BELOW
#define UC_MACRO_NAME_21B 0x021B // ț LATIN SMALL LETTER T WITH COMMA BELOW
#define UC_MACRO_NAME_21C 0x021C // Ȝ LATIN CAPITAL LETTER YOGH
#define UC_MACRO_NAME_21D 0x021D // ȝ LATIN SMALL LETTER YOGH
#define UC_MACRO_NAME_21E 0x021E // Ȟ LATIN CAPITAL LETTER H WITH CARON
#define UC_MACRO_NAME_21F 0x021F // ȟ LATIN SMALL LETTER H WITH CARON
#define UC_MACRO_NAME_220 0x0220 // Ƞ LATIN CAPITAL LETTER N WITH LONG RIGHT LEG
#define UC_MACRO_NAME_221 0x0221 // ȡ LATIN SMALL LETTER D WITH CURL
#define UC_MACRO_NAME_222 0x0222 // Ȣ LATIN CAPITAL LETTER OU
#define UC_MACRO_NAME_223 0x0223 // ȣ LATIN SMALL LETTER OU
#define UC_MACRO_NAME_224 0x0224 // Ȥ LATIN CAPITAL LETTER Z WITH HOOK
#define UC_MACRO_NAME_225 0x0225 // ȥ LATIN SMALL LETTER Z WITH HOOK
#define UC_MACRO_NAME_226 0x0226 // Ȧ LATIN CAPITAL LETTER A WITH DOT ABOVE
#define UC_MACRO_NAME_227 0x0227 // ȧ LATIN SMALL LETTER A WITH DOT ABOVE
#define UC_MACRO_NAME_228 0x0228 // Ȩ LATIN CAPITAL LETTER E WITH CEDILLA
#define UC_MACRO_NAME_229 0x0229 // ȩ LATIN SMALL LETTER E WITH CEDILLA
#define UC_MACRO_NAME_22A 0x022A // Ȫ LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON
#define UC_MACRO_NAME_22B 0x022B // ȫ LATIN SMALL LETTER O WITH DIAERESIS AND MACRON
#define UC_MACRO_NAME_22C 0x022C // Ȭ LATIN CAPITAL LETTER O WITH TILDE AND MACRON
#define UC_MACRO_NAME_22D 0x022D // ȭ LATIN SMALL LETTER O WITH TILDE AND MACRON
#define UC_MACRO_NAME_22E 0x022E // Ȯ LATIN CAPITAL LETTER O WITH DOT ABOVE
#define UC_MACRO_NAME_22F 0x022F // ȯ LATIN SMALL LETTER O WITH DOT ABOVE
#define UC_MACRO_NAME_230 0x0230 // Ȱ LATIN CAPITAL LETTER O WITH DOT ABOVE AND MACRON
#define UC_MACRO_NAME_231 0x0231 // ȱ LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON
#define UC_MACRO_NAME_232 0x0232 // Ȳ LATIN CAPITAL LETTER Y WITH MACRON
#define UC_MACRO_NAME_233 0x0233 // ȳ LATIN SMALL LETTER Y WITH MACRON
#define UC_MACRO_NAME_234 0x0234 // ȴ LATIN SMALL LETTER L WITH CURL
#define UC_MACRO_NAME_235 0x0235 // ȵ LATIN SMALL LETTER N WITH CURL
#define UC_MACRO_NAME_236 0x0236 // ȶ LATIN SMALL LETTER T WITH CURL
#define UC_MACRO_NAME_237 0x0237 // ȷ LATIN SMALL LETTER DOTLESS J
#define UC_MACRO_NAME_238 0x0238 // ȸ LATIN SMALL LETTER DB DIGRAPH
#define UC_MACRO_NAME_239 0x0239 // ȹ LATIN SMALL LETTER QP DIGRAPH
#define UC_MACRO_NAME_23A 0x023A // Ⱥ LATIN CAPITAL LETTER A WITH STROKE
#define UC_MACRO_NAME_23B 0x023B // Ȼ LATIN CAPITAL LETTER C WITH STROKE
#define UC_MACRO_NAME_23C 0x023C // ȼ LATIN SMALL LETTER C WITH STROKE
#define UC_MACRO_NAME_23D 0x023D // Ƚ LATIN CAPITAL LETTER L WITH BAR
#define UC_MACRO_NAME_23E 0x023E // Ⱦ LATIN CAPITAL LETTER T WITH DIAGONAL STROKE
#define UC_MACRO_NAME_23F 0x023F // ȿ LATIN SMALL LETTER S WITH SWASH TAIL
#define UC_MACRO_NAME_240 0x0240 // ɀ LATIN SMALL LETTER Z WITH SWASH TAIL
#define UC_MACRO_NAME_241 0x0241 // Ɂ LATIN CAPITAL LETTER GLOTTAL STOP
#define UC_MACRO_NAME_242 0x0242 // ɂ LATIN SMALL LETTER GLOTTAL STOP
#define UC_MACRO_NAME_243 0x0243 // Ƀ LATIN CAPITAL LETTER B WITH STROKE
#define UC_MACRO_NAME_244 0x0244 // Ʉ LATIN CAPITAL LETTER U BAR
#define UC_MACRO_NAME_245 0x0245 // Ʌ LATIN CAPITAL LETTER TURNED V
#define UC_MACRO_NAME_246 0x0246 // Ɇ LATIN CAPITAL LETTER E WITH STROKE
#define UC_MACRO_NAME_247 0x0247 // ɇ LATIN SMALL LETTER E WITH STROKE
#define UC_MACRO_NAME_248 0x0248 // Ɉ LATIN CAPITAL LETTER J WITH STROKE
#define UC_MACRO_NAME_249 0x0249 // ɉ LATIN SMALL LETTER J WITH STROKE
#define UC_MACRO_NAME_24A 0x024A // Ɋ LATIN CAPITAL LETTER SMALL Q WITH HOOK TAIL
#define UC_MACRO_NAME_24B 0x024B // ɋ LATIN SMALL LETTER Q WITH HOOK TAIL
#define UC_MACRO_NAME_24C 0x024C // Ɍ LATIN CAPITAL LETTER R WITH STROKE
#define UC_MACRO_NAME_24D 0x024D // ɍ LATIN SMALL LETTER R WITH STROKE
#define UC_MACRO_NAME_24E 0x024E // Ɏ LATIN CAPITAL LETTER Y WITH STROKE
#define UC_MACRO_NAME_24F 0x024F // ɏ LATIN SMALL LETTER Y WITH STROKE


#endif // UC_H_LATIN_EXTENDED_B
