/*
 * Unicode Block: Latin Extended-D
 * Range: U+A720..U+A7FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Latin Extended-D is a Unicode block containing Latin characters for
 * phonetic, Mayanist , and Medieval transcription and notation systems.
 * 89 of the characters in this block are for medieval characters
 * proposed by the Medieval Unicode Font Initiative , many of which are
 * representative of scribal abbreviations used in Medieval manuscript
 * texts .
 *
 */
#ifndef UC_H_LATIN_EXTENDED_D
#define UC_H_LATIN_EXTENDED_D

#define UC_MACRO_NAME_A720 0xA720 // ꜠ MODIFIER LETTER STRESS AND HIGH TONE
#define UC_MACRO_NAME_A721 0xA721 // ꜡ MODIFIER LETTER STRESS AND LOW TONE
#define UC_MACRO_NAME_A722 0xA722 // Ꜣ LATIN CAPITAL LETTER EGYPTOLOGICAL ALEF
#define UC_MACRO_NAME_A723 0xA723 // ꜣ LATIN SMALL LETTER EGYPTOLOGICAL ALEF
#define UC_MACRO_NAME_A724 0xA724 // Ꜥ LATIN CAPITAL LETTER EGYPTOLOGICAL AIN
#define UC_MACRO_NAME_A725 0xA725 // ꜥ LATIN SMALL LETTER EGYPTOLOGICAL AIN
#define UC_MACRO_NAME_A726 0xA726 // Ꜧ LATIN CAPITAL LETTER HENG
#define UC_MACRO_NAME_A727 0xA727 // ꜧ LATIN SMALL LETTER HENG
#define UC_MACRO_NAME_A728 0xA728 // Ꜩ LATIN CAPITAL LETTER TZ
#define UC_MACRO_NAME_A729 0xA729 // ꜩ LATIN SMALL LETTER TZ
#define UC_MACRO_NAME_A72A 0xA72A // Ꜫ LATIN CAPITAL LETTER TRESILLO
#define UC_MACRO_NAME_A72B 0xA72B // ꜫ LATIN SMALL LETTER TRESILLO
#define UC_MACRO_NAME_A72C 0xA72C // Ꜭ LATIN CAPITAL LETTER CUATRILLO
#define UC_MACRO_NAME_A72D 0xA72D // ꜭ LATIN SMALL LETTER CUATRILLO
#define UC_MACRO_NAME_A72E 0xA72E // Ꜯ LATIN CAPITAL LETTER CUATRILLO WITH COMMA
#define UC_MACRO_NAME_A72F 0xA72F // ꜯ LATIN SMALL LETTER CUATRILLO WITH COMMA
#define UC_MACRO_NAME_A730 0xA730 // ꜰ LATIN LETTER SMALL CAPITAL F
#define UC_MACRO_NAME_A731 0xA731 // ꜱ LATIN LETTER SMALL CAPITAL S
#define UC_MACRO_NAME_A732 0xA732 // Ꜳ LATIN CAPITAL LETTER AA
#define UC_MACRO_NAME_A733 0xA733 // ꜳ LATIN SMALL LETTER AA
#define UC_MACRO_NAME_A734 0xA734 // Ꜵ LATIN CAPITAL LETTER AO
#define UC_MACRO_NAME_A735 0xA735 // ꜵ LATIN SMALL LETTER AO
#define UC_MACRO_NAME_A736 0xA736 // Ꜷ LATIN CAPITAL LETTER AU
#define UC_MACRO_NAME_A737 0xA737 // ꜷ LATIN SMALL LETTER AU
#define UC_MACRO_NAME_A738 0xA738 // Ꜹ LATIN CAPITAL LETTER AV
#define UC_MACRO_NAME_A739 0xA739 // ꜹ LATIN SMALL LETTER AV
#define UC_MACRO_NAME_A73A 0xA73A // Ꜻ LATIN CAPITAL LETTER AV WITH HORIZONTAL BAR
#define UC_MACRO_NAME_A73B 0xA73B // ꜻ LATIN SMALL LETTER AV WITH HORIZONTAL BAR
#define UC_MACRO_NAME_A73C 0xA73C // Ꜽ LATIN CAPITAL LETTER AY
#define UC_MACRO_NAME_A73D 0xA73D // ꜽ LATIN SMALL LETTER AY
#define UC_MACRO_NAME_A73E 0xA73E // Ꜿ LATIN CAPITAL LETTER REVERSED C WITH DOT
#define UC_MACRO_NAME_A73F 0xA73F // ꜿ LATIN SMALL LETTER REVERSED C WITH DOT
#define UC_MACRO_NAME_A740 0xA740 // Ꝁ LATIN CAPITAL LETTER K WITH STROKE
#define UC_MACRO_NAME_A741 0xA741 // ꝁ LATIN SMALL LETTER K WITH STROKE
#define UC_MACRO_NAME_A742 0xA742 // Ꝃ LATIN CAPITAL LETTER K WITH DIAGONAL STROKE
#define UC_MACRO_NAME_A743 0xA743 // ꝃ LATIN SMALL LETTER K WITH DIAGONAL STROKE
#define UC_MACRO_NAME_A744 0xA744 // Ꝅ LATIN CAPITAL LETTER K WITH STROKE AND DIAGONAL STROKE
#define UC_MACRO_NAME_A745 0xA745 // ꝅ LATIN SMALL LETTER K WITH STROKE AND DIAGONAL STROKE
#define UC_MACRO_NAME_A746 0xA746 // Ꝇ LATIN CAPITAL LETTER BROKEN L
#define UC_MACRO_NAME_A747 0xA747 // ꝇ LATIN SMALL LETTER BROKEN L
#define UC_MACRO_NAME_A748 0xA748 // Ꝉ LATIN CAPITAL LETTER L WITH HIGH STROKE
#define UC_MACRO_NAME_A749 0xA749 // ꝉ LATIN SMALL LETTER L WITH HIGH STROKE
#define UC_MACRO_NAME_A74A 0xA74A // Ꝋ LATIN CAPITAL LETTER O WITH LONG STROKE OVERLAY
#define UC_MACRO_NAME_A74B 0xA74B // ꝋ LATIN SMALL LETTER O WITH LONG STROKE OVERLAY
#define UC_MACRO_NAME_A74C 0xA74C // Ꝍ LATIN CAPITAL LETTER O WITH LOOP
#define UC_MACRO_NAME_A74D 0xA74D // ꝍ LATIN SMALL LETTER O WITH LOOP
#define UC_MACRO_NAME_A74E 0xA74E // Ꝏ LATIN CAPITAL LETTER OO
#define UC_MACRO_NAME_A74F 0xA74F // ꝏ LATIN SMALL LETTER OO
#define UC_MACRO_NAME_A750 0xA750 // Ꝑ LATIN CAPITAL LETTER P WITH STROKE THROUGH DESCENDER
#define UC_MACRO_NAME_A751 0xA751 // ꝑ LATIN SMALL LETTER P WITH STROKE THROUGH DESCENDER
#define UC_MACRO_NAME_A752 0xA752 // Ꝓ LATIN CAPITAL LETTER P WITH FLOURISH
#define UC_MACRO_NAME_A753 0xA753 // ꝓ LATIN SMALL LETTER P WITH FLOURISH
#define UC_MACRO_NAME_A754 0xA754 // Ꝕ LATIN CAPITAL LETTER P WITH SQUIRREL TAIL
#define UC_MACRO_NAME_A755 0xA755 // ꝕ LATIN SMALL LETTER P WITH SQUIRREL TAIL
#define UC_MACRO_NAME_A756 0xA756 // Ꝗ LATIN CAPITAL LETTER Q WITH STROKE THROUGH DESCENDER
#define UC_MACRO_NAME_A757 0xA757 // ꝗ LATIN SMALL LETTER Q WITH STROKE THROUGH DESCENDER
#define UC_MACRO_NAME_A758 0xA758 // Ꝙ LATIN CAPITAL LETTER Q WITH DIAGONAL STROKE
#define UC_MACRO_NAME_A759 0xA759 // ꝙ LATIN SMALL LETTER Q WITH DIAGONAL STROKE
#define UC_MACRO_NAME_A75A 0xA75A // Ꝛ LATIN CAPITAL LETTER R ROTUNDA
#define UC_MACRO_NAME_A75B 0xA75B // ꝛ LATIN SMALL LETTER R ROTUNDA
#define UC_MACRO_NAME_A75C 0xA75C // Ꝝ LATIN CAPITAL LETTER RUM ROTUNDA
#define UC_MACRO_NAME_A75D 0xA75D // ꝝ LATIN SMALL LETTER RUM ROTUNDA
#define UC_MACRO_NAME_A75E 0xA75E // Ꝟ LATIN CAPITAL LETTER V WITH DIAGONAL STROKE
#define UC_MACRO_NAME_A75F 0xA75F // ꝟ LATIN SMALL LETTER V WITH DIAGONAL STROKE
#define UC_MACRO_NAME_A760 0xA760 // Ꝡ LATIN CAPITAL LETTER VY
#define UC_MACRO_NAME_A761 0xA761 // ꝡ LATIN SMALL LETTER VY
#define UC_MACRO_NAME_A762 0xA762 // Ꝣ LATIN CAPITAL LETTER VISIGOTHIC Z
#define UC_MACRO_NAME_A763 0xA763 // ꝣ LATIN SMALL LETTER VISIGOTHIC Z
#define UC_MACRO_NAME_A764 0xA764 // Ꝥ LATIN CAPITAL LETTER THORN WITH STROKE
#define UC_MACRO_NAME_A765 0xA765 // ꝥ LATIN SMALL LETTER THORN WITH STROKE
#define UC_MACRO_NAME_A766 0xA766 // Ꝧ LATIN CAPITAL LETTER THORN WITH STROKE THROUGH DESCENDER
#define UC_MACRO_NAME_A767 0xA767 // ꝧ LATIN SMALL LETTER THORN WITH STROKE THROUGH DESCENDER
#define UC_MACRO_NAME_A768 0xA768 // Ꝩ LATIN CAPITAL LETTER VEND
#define UC_MACRO_NAME_A769 0xA769 // ꝩ LATIN SMALL LETTER VEND
#define UC_MACRO_NAME_A76A 0xA76A // Ꝫ LATIN CAPITAL LETTER ET
#define UC_MACRO_NAME_A76B 0xA76B // ꝫ LATIN SMALL LETTER ET
#define UC_MACRO_NAME_A76C 0xA76C // Ꝭ LATIN CAPITAL LETTER IS
#define UC_MACRO_NAME_A76D 0xA76D // ꝭ LATIN SMALL LETTER IS
#define UC_MACRO_NAME_A76E 0xA76E // Ꝯ LATIN CAPITAL LETTER CON
#define UC_MACRO_NAME_A76F 0xA76F // ꝯ LATIN SMALL LETTER CON
#define UC_MACRO_NAME_A770 0xA770 // ꝰ MODIFIER LETTER US
#define UC_MACRO_NAME_A771 0xA771 // ꝱ LATIN SMALL LETTER DUM
#define UC_MACRO_NAME_A772 0xA772 // ꝲ LATIN SMALL LETTER LUM
#define UC_MACRO_NAME_A773 0xA773 // ꝳ LATIN SMALL LETTER MUM
#define UC_MACRO_NAME_A774 0xA774 // ꝴ LATIN SMALL LETTER NUM
#define UC_MACRO_NAME_A775 0xA775 // ꝵ LATIN SMALL LETTER RUM
#define UC_MACRO_NAME_A776 0xA776 // ꝶ LATIN LETTER SMALL CAPITAL RUM
#define UC_MACRO_NAME_A777 0xA777 // ꝷ LATIN SMALL LETTER TUM
#define UC_MACRO_NAME_A778 0xA778 // ꝸ LATIN SMALL LETTER UM
#define UC_MACRO_NAME_A779 0xA779 // Ꝺ LATIN CAPITAL LETTER INSULAR D
#define UC_MACRO_NAME_A77A 0xA77A // ꝺ LATIN SMALL LETTER INSULAR D
#define UC_MACRO_NAME_A77B 0xA77B // Ꝼ LATIN CAPITAL LETTER INSULAR F
#define UC_MACRO_NAME_A77C 0xA77C // ꝼ LATIN SMALL LETTER INSULAR F
#define UC_MACRO_NAME_A77D 0xA77D // Ᵹ LATIN CAPITAL LETTER INSULAR G
#define UC_MACRO_NAME_A77E 0xA77E // Ꝿ LATIN CAPITAL LETTER TURNED INSULAR G
#define UC_MACRO_NAME_A77F 0xA77F // ꝿ LATIN SMALL LETTER TURNED INSULAR G
#define UC_MACRO_NAME_A780 0xA780 // Ꞁ LATIN CAPITAL LETTER TURNED L
#define UC_MACRO_NAME_A781 0xA781 // ꞁ LATIN SMALL LETTER TURNED L
#define UC_MACRO_NAME_A782 0xA782 // Ꞃ LATIN CAPITAL LETTER INSULAR R
#define UC_MACRO_NAME_A783 0xA783 // ꞃ LATIN SMALL LETTER INSULAR R
#define UC_MACRO_NAME_A784 0xA784 // Ꞅ LATIN CAPITAL LETTER INSULAR S
#define UC_MACRO_NAME_A785 0xA785 // ꞅ LATIN SMALL LETTER INSULAR S
#define UC_MACRO_NAME_A786 0xA786 // Ꞇ LATIN CAPITAL LETTER INSULAR T
#define UC_MACRO_NAME_A787 0xA787 // ꞇ LATIN SMALL LETTER INSULAR T
#define UC_MACRO_NAME_A788 0xA788 // ꞈ MODIFIER LETTER LOW CIRCUMFLEX ACCENT
#define UC_MACRO_NAME_A789 0xA789 // ꞉ MODIFIER LETTER COLON
#define UC_MACRO_NAME_A78A 0xA78A // ꞊ MODIFIER LETTER SHORT EQUALS SIGN
#define UC_MACRO_NAME_A78B 0xA78B // Ꞌ LATIN CAPITAL LETTER SALTILLO
#define UC_MACRO_NAME_A78C 0xA78C // ꞌ LATIN SMALL LETTER SALTILLO
#define UC_MACRO_NAME_A78D 0xA78D // Ɥ LATIN CAPITAL LETTER TURNED H
#define UC_MACRO_NAME_A78E 0xA78E // ꞎ LATIN SMALL LETTER L WITH RETROFLEX HOOK AND BELT
#define UC_MACRO_NAME_A78F 0xA78F // ꞏ LATIN LETTER SINOLOGICAL DOT
#define UC_MACRO_NAME_A790 0xA790 // Ꞑ LATIN CAPITAL LETTER N WITH DESCENDER
#define UC_MACRO_NAME_A791 0xA791 // ꞑ LATIN SMALL LETTER N WITH DESCENDER
#define UC_MACRO_NAME_A792 0xA792 // Ꞓ LATIN CAPITAL LETTER C WITH BAR
#define UC_MACRO_NAME_A793 0xA793 // ꞓ LATIN SMALL LETTER C WITH BAR
#define UC_MACRO_NAME_A794 0xA794 // ꞔ LATIN SMALL LETTER C WITH PALATAL HOOK
#define UC_MACRO_NAME_A795 0xA795 // ꞕ LATIN SMALL LETTER H WITH PALATAL HOOK
#define UC_MACRO_NAME_A796 0xA796 // Ꞗ LATIN CAPITAL LETTER B WITH FLOURISH
#define UC_MACRO_NAME_A797 0xA797 // ꞗ LATIN SMALL LETTER B WITH FLOURISH
#define UC_MACRO_NAME_A798 0xA798 // Ꞙ LATIN CAPITAL LETTER F WITH STROKE
#define UC_MACRO_NAME_A799 0xA799 // ꞙ LATIN SMALL LETTER F WITH STROKE
#define UC_MACRO_NAME_A79A 0xA79A // Ꞛ LATIN CAPITAL LETTER VOLAPUK AE
#define UC_MACRO_NAME_A79B 0xA79B // ꞛ LATIN SMALL LETTER VOLAPUK AE
#define UC_MACRO_NAME_A79C 0xA79C // Ꞝ LATIN CAPITAL LETTER VOLAPUK OE
#define UC_MACRO_NAME_A79D 0xA79D // ꞝ LATIN SMALL LETTER VOLAPUK OE
#define UC_MACRO_NAME_A79E 0xA79E // Ꞟ LATIN CAPITAL LETTER VOLAPUK UE
#define UC_MACRO_NAME_A79F 0xA79F // ꞟ LATIN SMALL LETTER VOLAPUK UE
#define UC_MACRO_NAME_A7A0 0xA7A0 // Ꞡ LATIN CAPITAL LETTER G WITH OBLIQUE STROKE
#define UC_MACRO_NAME_A7A1 0xA7A1 // ꞡ LATIN SMALL LETTER G WITH OBLIQUE STROKE
#define UC_MACRO_NAME_A7A2 0xA7A2 // Ꞣ LATIN CAPITAL LETTER K WITH OBLIQUE STROKE
#define UC_MACRO_NAME_A7A3 0xA7A3 // ꞣ LATIN SMALL LETTER K WITH OBLIQUE STROKE
#define UC_MACRO_NAME_A7A4 0xA7A4 // Ꞥ LATIN CAPITAL LETTER N WITH OBLIQUE STROKE
#define UC_MACRO_NAME_A7A5 0xA7A5 // ꞥ LATIN SMALL LETTER N WITH OBLIQUE STROKE
#define UC_MACRO_NAME_A7A6 0xA7A6 // Ꞧ LATIN CAPITAL LETTER R WITH OBLIQUE STROKE
#define UC_MACRO_NAME_A7A7 0xA7A7 // ꞧ LATIN SMALL LETTER R WITH OBLIQUE STROKE
#define UC_MACRO_NAME_A7A8 0xA7A8 // Ꞩ LATIN CAPITAL LETTER S WITH OBLIQUE STROKE
#define UC_MACRO_NAME_A7A9 0xA7A9 // ꞩ LATIN SMALL LETTER S WITH OBLIQUE STROKE
#define UC_MACRO_NAME_A7AA 0xA7AA // Ɦ LATIN CAPITAL LETTER H WITH HOOK
#define UC_MACRO_NAME_A7AB 0xA7AB // Ɜ LATIN CAPITAL LETTER REVERSED OPEN E
#define UC_MACRO_NAME_A7AC 0xA7AC // Ɡ LATIN CAPITAL LETTER SCRIPT G
#define UC_MACRO_NAME_A7AD 0xA7AD // Ɬ LATIN CAPITAL LETTER L WITH BELT
#define UC_MACRO_NAME_A7AE 0xA7AE // Ɪ LATIN CAPITAL LETTER SMALL CAPITAL I
#define UC_MACRO_NAME_A7AF 0xA7AF // ꞯ LATIN LETTER SMALL CAPITAL Q
#define UC_MACRO_NAME_A7B0 0xA7B0 // Ʞ LATIN CAPITAL LETTER TURNED K
#define UC_MACRO_NAME_A7B1 0xA7B1 // Ʇ LATIN CAPITAL LETTER TURNED T
#define UC_MACRO_NAME_A7B2 0xA7B2 // Ʝ LATIN CAPITAL LETTER J WITH CROSSED-TAIL
#define UC_MACRO_NAME_A7B3 0xA7B3 // Ꭓ LATIN CAPITAL LETTER CHI
#define UC_MACRO_NAME_A7B4 0xA7B4 // Ꞵ LATIN CAPITAL LETTER BETA
#define UC_MACRO_NAME_A7B5 0xA7B5 // ꞵ LATIN SMALL LETTER BETA
#define UC_MACRO_NAME_A7B6 0xA7B6 // Ꞷ LATIN CAPITAL LETTER OMEGA
#define UC_MACRO_NAME_A7B7 0xA7B7 // ꞷ LATIN SMALL LETTER OMEGA
#define UC_MACRO_NAME_A7B8 0xA7B8 // Ꞹ LATIN CAPITAL LETTER U WITH STROKE
#define UC_MACRO_NAME_A7B9 0xA7B9 // ꞹ LATIN SMALL LETTER U WITH STROKE
#define UC_MACRO_NAME_A7BA 0xA7BA // Ꞻ LATIN CAPITAL LETTER GLOTTAL A
#define UC_MACRO_NAME_A7BB 0xA7BB // ꞻ LATIN SMALL LETTER GLOTTAL A
#define UC_MACRO_NAME_A7BC 0xA7BC // Ꞽ LATIN CAPITAL LETTER GLOTTAL I
#define UC_MACRO_NAME_A7BD 0xA7BD // ꞽ LATIN SMALL LETTER GLOTTAL I
#define UC_MACRO_NAME_A7BE 0xA7BE // Ꞿ LATIN CAPITAL LETTER GLOTTAL U
#define UC_MACRO_NAME_A7BF 0xA7BF // ꞿ LATIN SMALL LETTER GLOTTAL U
#define UC_MACRO_NAME_A7C0 0xA7C0 // Ꟁ LATIN CAPITAL LETTER OLD POLISH O
#define UC_MACRO_NAME_A7C1 0xA7C1 // ꟁ LATIN SMALL LETTER OLD POLISH O
#define UC_MACRO_NAME_A7C2 0xA7C2 // Ꟃ LATIN CAPITAL LETTER ANGLICANA W
#define UC_MACRO_NAME_A7C3 0xA7C3 // ꟃ LATIN SMALL LETTER ANGLICANA W
#define UC_MACRO_NAME_A7C4 0xA7C4 // Ꞔ LATIN CAPITAL LETTER C WITH PALATAL HOOK
#define UC_MACRO_NAME_A7C5 0xA7C5 // Ʂ LATIN CAPITAL LETTER S WITH HOOK
#define UC_MACRO_NAME_A7C6 0xA7C6 // Ᶎ LATIN CAPITAL LETTER Z WITH PALATAL HOOK
#define UC_MACRO_NAME_A7C7 0xA7C7 // Ꟈ LATIN CAPITAL LETTER D WITH SHORT STROKE OVERLAY
#define UC_MACRO_NAME_A7C8 0xA7C8 // ꟈ LATIN SMALL LETTER D WITH SHORT STROKE OVERLAY
#define UC_MACRO_NAME_A7C9 0xA7C9 // Ꟊ LATIN CAPITAL LETTER S WITH SHORT STROKE OVERLAY
#define UC_MACRO_NAME_A7CA 0xA7CA // ꟊ LATIN SMALL LETTER S WITH SHORT STROKE OVERLAY
#define UC_MACRO_NAME_A7CB 0xA7CB //  LATIN CAPITAL LETTER RAMS HORN
#define UC_MACRO_NAME_A7CC 0xA7CC //  LATIN CAPITAL LETTER S WITH DIAGONAL STROKE
#define UC_MACRO_NAME_A7CD 0xA7CD //  LATIN SMALL LETTER S WITH DIAGONAL STROKE
#define UC_MACRO_NAME_A7CE 0xA7CE //  LATIN CAPITAL LETTER PHARYNGEAL VOICED FRICATIVE
#define UC_MACRO_NAME_A7CF 0xA7CF //  LATIN SMALL LETTER PHARYNGEAL VOICED FRICATIVE
#define UC_MACRO_NAME_A7D0 0xA7D0 // Ꟑ LATIN CAPITAL LETTER CLOSED INSULAR G
#define UC_MACRO_NAME_A7D1 0xA7D1 // ꟑ LATIN SMALL LETTER CLOSED INSULAR G
#define UC_MACRO_NAME_A7D2 0xA7D2 //  LATIN CAPITAL LETTER DOUBLE THORN
#define UC_MACRO_NAME_A7D3 0xA7D3 // ꟓ LATIN SMALL LETTER DOUBLE THORN
#define UC_MACRO_NAME_A7D4 0xA7D4 //  LATIN CAPITAL LETTER DOUBLE WYNN
#define UC_MACRO_NAME_A7D5 0xA7D5 // ꟕ LATIN SMALL LETTER DOUBLE WYNN
#define UC_MACRO_NAME_A7D6 0xA7D6 // Ꟗ LATIN CAPITAL LETTER MIDDLE SCOTS S
#define UC_MACRO_NAME_A7D7 0xA7D7 // ꟗ LATIN SMALL LETTER MIDDLE SCOTS S
#define UC_MACRO_NAME_A7D8 0xA7D8 // Ꟙ LATIN CAPITAL LETTER SIGMOID S
#define UC_MACRO_NAME_A7D9 0xA7D9 // ꟙ LATIN SMALL LETTER SIGMOID S
#define UC_MACRO_NAME_A7DA 0xA7DA //  LATIN CAPITAL LETTER LAMBDA
#define UC_MACRO_NAME_A7DB 0xA7DB //  LATIN SMALL LETTER LAMBDA
#define UC_MACRO_NAME_A7DC 0xA7DC //  LATIN CAPITAL LETTER LAMBDA WITH STROKE
#define UC_MACRO_NAME_A7F1 0xA7F1 //  MODIFIER LETTER CAPITAL S
#define UC_MACRO_NAME_A7F2 0xA7F2 // ꟲ MODIFIER LETTER CAPITAL C
#define UC_MACRO_NAME_A7F3 0xA7F3 // ꟳ MODIFIER LETTER CAPITAL F
#define UC_MACRO_NAME_A7F4 0xA7F4 // ꟴ MODIFIER LETTER CAPITAL Q
#define UC_MACRO_NAME_A7F5 0xA7F5 // Ꟶ LATIN CAPITAL LETTER REVERSED HALF H
#define UC_MACRO_NAME_A7F6 0xA7F6 // ꟶ LATIN SMALL LETTER REVERSED HALF H
#define UC_MACRO_NAME_A7F7 0xA7F7 // ꟷ LATIN EPIGRAPHIC LETTER SIDEWAYS I
#define UC_MACRO_NAME_A7F8 0xA7F8 // ꟸ MODIFIER LETTER CAPITAL H WITH STROKE
#define UC_MACRO_NAME_A7F9 0xA7F9 // ꟹ MODIFIER LETTER SMALL LIGATURE OE
#define UC_MACRO_NAME_A7FA 0xA7FA // ꟺ LATIN LETTER SMALL CAPITAL TURNED M
#define UC_MACRO_NAME_A7FB 0xA7FB // ꟻ LATIN EPIGRAPHIC LETTER REVERSED F
#define UC_MACRO_NAME_A7FC 0xA7FC // ꟼ LATIN EPIGRAPHIC LETTER REVERSED P
#define UC_MACRO_NAME_A7FD 0xA7FD // ꟽ LATIN EPIGRAPHIC LETTER INVERTED M
#define UC_MACRO_NAME_A7FE 0xA7FE // ꟾ LATIN EPIGRAPHIC LETTER I LONGA
#define UC_MACRO_NAME_A7FF 0xA7FF // ꟿ LATIN EPIGRAPHIC LETTER ARCHAIC M


#endif // UC_H_LATIN_EXTENDED_D
