/*
 * Unicode Block: Latin-1 Supplement
 * Range: U+0080..U+00FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_LATIN_1_SUPPLEMENT
#define UC_H_LATIN_1_SUPPLEMENT

#define UC_MACRO_NAME_A0 0x00A0 //  NO-BREAK SPACE
#define UC_MACRO_NAME_A1 0x00A1 // ¡ INVERTED EXCLAMATION MARK
#define UC_MACRO_NAME_A2 0x00A2 // ¢ CENT SIGN
#define UC_MACRO_NAME_A3 0x00A3 // £ POUND SIGN
#define UC_MACRO_NAME_A4 0x00A4 // ¤ CURRENCY SIGN
#define UC_MACRO_NAME_A5 0x00A5 // ¥ YEN SIGN
#define UC_MACRO_NAME_A6 0x00A6 // ¦ BROKEN BAR
#define UC_MACRO_NAME_A7 0x00A7 // § SECTION SIGN
#define UC_MACRO_NAME_A8 0x00A8 // ¨ DIAERESIS
#define UC_MACRO_NAME_A9 0x00A9 // © COPYRIGHT SIGN
#define UC_MACRO_NAME_AA 0x00AA // ª FEMININE ORDINAL INDICATOR
#define UC_MACRO_NAME_AB 0x00AB // « LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
#define UC_MACRO_NAME_AC 0x00AC // ¬ NOT SIGN
#define UC_MACRO_NAME_AD 0x00AD //  SOFT HYPHEN
#define UC_MACRO_NAME_AE 0x00AE // ® REGISTERED SIGN
#define UC_MACRO_NAME_AF 0x00AF // ¯ MACRON
#define UC_MACRO_NAME_B0 0x00B0 // ° DEGREE SIGN
#define UC_MACRO_NAME_B1 0x00B1 // ± PLUS-MINUS SIGN
#define UC_MACRO_NAME_B2 0x00B2 // ² SUPERSCRIPT TWO
#define UC_MACRO_NAME_B3 0x00B3 // ³ SUPERSCRIPT THREE
#define UC_MACRO_NAME_B4 0x00B4 // ´ ACUTE ACCENT
#define UC_MACRO_NAME_B5 0x00B5 // µ MICRO SIGN
#define UC_MACRO_NAME_B6 0x00B6 // ¶ PILCROW SIGN
#define UC_MACRO_NAME_B7 0x00B7 // · MIDDLE DOT
#define UC_MACRO_NAME_B8 0x00B8 // ¸ CEDILLA
#define UC_MACRO_NAME_B9 0x00B9 // ¹ SUPERSCRIPT ONE
#define UC_MACRO_NAME_BA 0x00BA // º MASCULINE ORDINAL INDICATOR
#define UC_MACRO_NAME_BB 0x00BB // » RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
#define UC_MACRO_NAME_BC 0x00BC // ¼ VULGAR FRACTION ONE QUARTER
#define UC_MACRO_NAME_BD 0x00BD // ½ VULGAR FRACTION ONE HALF
#define UC_MACRO_NAME_BE 0x00BE // ¾ VULGAR FRACTION THREE QUARTERS
#define UC_MACRO_NAME_BF 0x00BF // ¿ INVERTED QUESTION MARK
#define UC_MACRO_NAME_C0 0x00C0 // À LATIN CAPITAL LETTER A WITH GRAVE
#define UC_MACRO_NAME_C1 0x00C1 // Á LATIN CAPITAL LETTER A WITH ACUTE
#define UC_MACRO_NAME_C2 0x00C2 // Â LATIN CAPITAL LETTER A WITH CIRCUMFLEX
#define UC_MACRO_NAME_C3 0x00C3 // Ã LATIN CAPITAL LETTER A WITH TILDE
#define UC_MACRO_NAME_C4 0x00C4 // Ä LATIN CAPITAL LETTER A WITH DIAERESIS
#define UC_MACRO_NAME_C5 0x00C5 // Å LATIN CAPITAL LETTER A WITH RING ABOVE
#define UC_MACRO_NAME_C6 0x00C6 // Æ LATIN CAPITAL LETTER AE
#define UC_MACRO_NAME_C7 0x00C7 // Ç LATIN CAPITAL LETTER C WITH CEDILLA
#define UC_MACRO_NAME_C8 0x00C8 // È LATIN CAPITAL LETTER E WITH GRAVE
#define UC_MACRO_NAME_C9 0x00C9 // É LATIN CAPITAL LETTER E WITH ACUTE
#define UC_MACRO_NAME_CA 0x00CA // Ê LATIN CAPITAL LETTER E WITH CIRCUMFLEX
#define UC_MACRO_NAME_CB 0x00CB // Ë LATIN CAPITAL LETTER E WITH DIAERESIS
#define UC_MACRO_NAME_CC 0x00CC // Ì LATIN CAPITAL LETTER I WITH GRAVE
#define UC_MACRO_NAME_CD 0x00CD // Í LATIN CAPITAL LETTER I WITH ACUTE
#define UC_MACRO_NAME_CE 0x00CE // Î LATIN CAPITAL LETTER I WITH CIRCUMFLEX
#define UC_MACRO_NAME_CF 0x00CF // Ï LATIN CAPITAL LETTER I WITH DIAERESIS
#define UC_MACRO_NAME_D0 0x00D0 // Ð LATIN CAPITAL LETTER ETH
#define UC_MACRO_NAME_D1 0x00D1 // Ñ LATIN CAPITAL LETTER N WITH TILDE
#define UC_MACRO_NAME_D2 0x00D2 // Ò LATIN CAPITAL LETTER O WITH GRAVE
#define UC_MACRO_NAME_D3 0x00D3 // Ó LATIN CAPITAL LETTER O WITH ACUTE
#define UC_MACRO_NAME_D4 0x00D4 // Ô LATIN CAPITAL LETTER O WITH CIRCUMFLEX
#define UC_MACRO_NAME_D5 0x00D5 // Õ LATIN CAPITAL LETTER O WITH TILDE
#define UC_MACRO_NAME_D6 0x00D6 // Ö LATIN CAPITAL LETTER O WITH DIAERESIS
#define UC_MACRO_NAME_D7 0x00D7 // × MULTIPLICATION SIGN
#define UC_MACRO_NAME_D8 0x00D8 // Ø LATIN CAPITAL LETTER O WITH STROKE
#define UC_MACRO_NAME_D9 0x00D9 // Ù LATIN CAPITAL LETTER U WITH GRAVE
#define UC_MACRO_NAME_DA 0x00DA // Ú LATIN CAPITAL LETTER U WITH ACUTE
#define UC_MACRO_NAME_DB 0x00DB // Û LATIN CAPITAL LETTER U WITH CIRCUMFLEX
#define UC_MACRO_NAME_DC 0x00DC // Ü LATIN CAPITAL LETTER U WITH DIAERESIS
#define UC_MACRO_NAME_DD 0x00DD // Ý LATIN CAPITAL LETTER Y WITH ACUTE
#define UC_MACRO_NAME_DE 0x00DE // Þ LATIN CAPITAL LETTER THORN
#define UC_MACRO_NAME_DF 0x00DF // ß LATIN SMALL LETTER SHARP S
#define UC_MACRO_NAME_E0 0x00E0 // à LATIN SMALL LETTER A WITH GRAVE
#define UC_MACRO_NAME_E1 0x00E1 // á LATIN SMALL LETTER A WITH ACUTE
#define UC_MACRO_NAME_E2 0x00E2 // â LATIN SMALL LETTER A WITH CIRCUMFLEX
#define UC_MACRO_NAME_E3 0x00E3 // ã LATIN SMALL LETTER A WITH TILDE
#define UC_MACRO_NAME_E4 0x00E4 // ä LATIN SMALL LETTER A WITH DIAERESIS
#define UC_MACRO_NAME_E5 0x00E5 // å LATIN SMALL LETTER A WITH RING ABOVE
#define UC_MACRO_NAME_E6 0x00E6 // æ LATIN SMALL LETTER AE
#define UC_MACRO_NAME_E7 0x00E7 // ç LATIN SMALL LETTER C WITH CEDILLA
#define UC_MACRO_NAME_E8 0x00E8 // è LATIN SMALL LETTER E WITH GRAVE
#define UC_MACRO_NAME_E9 0x00E9 // é LATIN SMALL LETTER E WITH ACUTE
#define UC_MACRO_NAME_EA 0x00EA // ê LATIN SMALL LETTER E WITH CIRCUMFLEX
#define UC_MACRO_NAME_EB 0x00EB // ë LATIN SMALL LETTER E WITH DIAERESIS
#define UC_MACRO_NAME_EC 0x00EC // ì LATIN SMALL LETTER I WITH GRAVE
#define UC_MACRO_NAME_ED 0x00ED // í LATIN SMALL LETTER I WITH ACUTE
#define UC_MACRO_NAME_EE 0x00EE // î LATIN SMALL LETTER I WITH CIRCUMFLEX
#define UC_MACRO_NAME_EF 0x00EF // ï LATIN SMALL LETTER I WITH DIAERESIS
#define UC_MACRO_NAME_F0 0x00F0 // ð LATIN SMALL LETTER ETH
#define UC_MACRO_NAME_F1 0x00F1 // ñ LATIN SMALL LETTER N WITH TILDE
#define UC_MACRO_NAME_F2 0x00F2 // ò LATIN SMALL LETTER O WITH GRAVE
#define UC_MACRO_NAME_F3 0x00F3 // ó LATIN SMALL LETTER O WITH ACUTE
#define UC_MACRO_NAME_F4 0x00F4 // ô LATIN SMALL LETTER O WITH CIRCUMFLEX
#define UC_MACRO_NAME_F5 0x00F5 // õ LATIN SMALL LETTER O WITH TILDE
#define UC_MACRO_NAME_F6 0x00F6 // ö LATIN SMALL LETTER O WITH DIAERESIS
#define UC_MACRO_NAME_F7 0x00F7 // ÷ DIVISION SIGN
#define UC_MACRO_NAME_F8 0x00F8 // ø LATIN SMALL LETTER O WITH STROKE
#define UC_MACRO_NAME_F9 0x00F9 // ù LATIN SMALL LETTER U WITH GRAVE
#define UC_MACRO_NAME_FA 0x00FA // ú LATIN SMALL LETTER U WITH ACUTE
#define UC_MACRO_NAME_FB 0x00FB // û LATIN SMALL LETTER U WITH CIRCUMFLEX
#define UC_MACRO_NAME_FC 0x00FC // ü LATIN SMALL LETTER U WITH DIAERESIS
#define UC_MACRO_NAME_FD 0x00FD // ý LATIN SMALL LETTER Y WITH ACUTE
#define UC_MACRO_NAME_FE 0x00FE // þ LATIN SMALL LETTER THORN
#define UC_MACRO_NAME_FF 0x00FF // ÿ LATIN SMALL LETTER Y WITH DIAERESIS


#endif // UC_H_LATIN_1_SUPPLEMENT
