/*
 * Unicode Block: Lao
 * Range: U+0E80..U+0EFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Lao may refer to:
 *
 */
#ifndef UC_H_LAO
#define UC_H_LAO

#define UC_MACRO_NAME_E81 0x0E81 // ກ LAO LETTER KO
#define UC_MACRO_NAME_E82 0x0E82 // ຂ LAO LETTER KHO SUNG
#define UC_MACRO_NAME_E84 0x0E84 // ຄ LAO LETTER KHO TAM
#define UC_MACRO_NAME_E86 0x0E86 // ຆ LAO LETTER PALI GHA
#define UC_MACRO_NAME_E87 0x0E87 // ງ LAO LETTER NGO
#define UC_MACRO_NAME_E88 0x0E88 // ຈ LAO LETTER CO
#define UC_MACRO_NAME_E89 0x0E89 // ຉ LAO LETTER PALI CHA
#define UC_MACRO_NAME_E8A 0x0E8A // ຊ LAO LETTER SO TAM
#define UC_MACRO_NAME_E8C 0x0E8C // ຌ LAO LETTER PALI JHA
#define UC_MACRO_NAME_E8D 0x0E8D // ຍ LAO LETTER NYO
#define UC_MACRO_NAME_E8E 0x0E8E // ຎ LAO LETTER PALI NYA
#define UC_MACRO_NAME_E8F 0x0E8F // ຏ LAO LETTER PALI TTA
#define UC_MACRO_NAME_E90 0x0E90 // ຐ LAO LETTER PALI TTHA
#define UC_MACRO_NAME_E91 0x0E91 // ຑ LAO LETTER PALI DDA
#define UC_MACRO_NAME_E92 0x0E92 // ຒ LAO LETTER PALI DDHA
#define UC_MACRO_NAME_E93 0x0E93 // ຓ LAO LETTER PALI NNA
#define UC_MACRO_NAME_E94 0x0E94 // ດ LAO LETTER DO
#define UC_MACRO_NAME_E95 0x0E95 // ຕ LAO LETTER TO
#define UC_MACRO_NAME_E96 0x0E96 // ຖ LAO LETTER THO SUNG
#define UC_MACRO_NAME_E97 0x0E97 // ທ LAO LETTER THO TAM
#define UC_MACRO_NAME_E98 0x0E98 // ຘ LAO LETTER PALI DHA
#define UC_MACRO_NAME_E99 0x0E99 // ນ LAO LETTER NO
#define UC_MACRO_NAME_E9A 0x0E9A // ບ LAO LETTER BO
#define UC_MACRO_NAME_E9B 0x0E9B // ປ LAO LETTER PO
#define UC_MACRO_NAME_E9C 0x0E9C // ຜ LAO LETTER PHO SUNG
#define UC_MACRO_NAME_E9D 0x0E9D // ຝ LAO LETTER FO TAM
#define UC_MACRO_NAME_E9E 0x0E9E // ພ LAO LETTER PHO TAM
#define UC_MACRO_NAME_E9F 0x0E9F // ຟ LAO LETTER FO SUNG
#define UC_MACRO_NAME_EA0 0x0EA0 // ຠ LAO LETTER PALI BHA
#define UC_MACRO_NAME_EA1 0x0EA1 // ມ LAO LETTER MO
#define UC_MACRO_NAME_EA2 0x0EA2 // ຢ LAO LETTER YO
#define UC_MACRO_NAME_EA3 0x0EA3 // ຣ LAO LETTER LO LING
#define UC_MACRO_NAME_EA5 0x0EA5 // ລ LAO LETTER LO LOOT
#define UC_MACRO_NAME_EA7 0x0EA7 // ວ LAO LETTER WO
#define UC_MACRO_NAME_EA8 0x0EA8 // ຨ LAO LETTER SANSKRIT SHA
#define UC_MACRO_NAME_EA9 0x0EA9 // ຩ LAO LETTER SANSKRIT SSA
#define UC_MACRO_NAME_EAA 0x0EAA // ສ LAO LETTER SO SUNG
#define UC_MACRO_NAME_EAB 0x0EAB // ຫ LAO LETTER HO SUNG
#define UC_MACRO_NAME_EAC 0x0EAC // ຬ LAO LETTER PALI LLA
#define UC_MACRO_NAME_EAD 0x0EAD // ອ LAO LETTER O
#define UC_MACRO_NAME_EAE 0x0EAE // ຮ LAO LETTER HO TAM
#define UC_MACRO_NAME_EAF 0x0EAF // ຯ LAO ELLIPSIS
#define UC_MACRO_NAME_EB0 0x0EB0 // ະ LAO VOWEL SIGN A
#define UC_MACRO_NAME_EB1 0x0EB1 // ັ LAO VOWEL SIGN MAI KAN
#define UC_MACRO_NAME_EB2 0x0EB2 // າ LAO VOWEL SIGN AA
#define UC_MACRO_NAME_EB3 0x0EB3 // ຳ LAO VOWEL SIGN AM
#define UC_MACRO_NAME_EB4 0x0EB4 // ິ LAO VOWEL SIGN I
#define UC_MACRO_NAME_EB5 0x0EB5 // ີ LAO VOWEL SIGN II
#define UC_MACRO_NAME_EB6 0x0EB6 // ຶ LAO VOWEL SIGN Y
#define UC_MACRO_NAME_EB7 0x0EB7 // ື LAO VOWEL SIGN YY
#define UC_MACRO_NAME_EB8 0x0EB8 // ຸ LAO VOWEL SIGN U
#define UC_MACRO_NAME_EB9 0x0EB9 // ູ LAO VOWEL SIGN UU
#define UC_MACRO_NAME_EBA 0x0EBA // ຺ LAO SIGN PALI VIRAMA
#define UC_MACRO_NAME_EBB 0x0EBB // ົ LAO VOWEL SIGN MAI KON
#define UC_MACRO_NAME_EBC 0x0EBC // ຼ LAO SEMIVOWEL SIGN LO
#define UC_MACRO_NAME_EBD 0x0EBD // ຽ LAO SEMIVOWEL SIGN NYO
#define UC_MACRO_NAME_EC0 0x0EC0 // ເ LAO VOWEL SIGN E
#define UC_MACRO_NAME_EC1 0x0EC1 // ແ LAO VOWEL SIGN EI
#define UC_MACRO_NAME_EC2 0x0EC2 // ໂ LAO VOWEL SIGN O
#define UC_MACRO_NAME_EC3 0x0EC3 // ໃ LAO VOWEL SIGN AY
#define UC_MACRO_NAME_EC4 0x0EC4 // ໄ LAO VOWEL SIGN AI
#define UC_MACRO_NAME_EC6 0x0EC6 // ໆ LAO KO LA
#define UC_MACRO_NAME_EC8 0x0EC8 // ່ LAO TONE MAI EK
#define UC_MACRO_NAME_EC9 0x0EC9 // ້ LAO TONE MAI THO
#define UC_MACRO_NAME_ECA 0x0ECA // ໊ LAO TONE MAI TI
#define UC_MACRO_NAME_ECB 0x0ECB // ໋ LAO TONE MAI CATAWA
#define UC_MACRO_NAME_ECC 0x0ECC // ໌ LAO CANCELLATION MARK
#define UC_MACRO_NAME_ECD 0x0ECD // ໍ LAO NIGGAHITA
#define UC_MACRO_NAME_ECE 0x0ECE // ໎ LAO YAMAKKAN
#define UC_MACRO_NAME_ED0 0x0ED0 // ໐ LAO DIGIT ZERO
#define UC_MACRO_NAME_ED1 0x0ED1 // ໑ LAO DIGIT ONE
#define UC_MACRO_NAME_ED2 0x0ED2 // ໒ LAO DIGIT TWO
#define UC_MACRO_NAME_ED3 0x0ED3 // ໓ LAO DIGIT THREE
#define UC_MACRO_NAME_ED4 0x0ED4 // ໔ LAO DIGIT FOUR
#define UC_MACRO_NAME_ED5 0x0ED5 // ໕ LAO DIGIT FIVE
#define UC_MACRO_NAME_ED6 0x0ED6 // ໖ LAO DIGIT SIX
#define UC_MACRO_NAME_ED7 0x0ED7 // ໗ LAO DIGIT SEVEN
#define UC_MACRO_NAME_ED8 0x0ED8 // ໘ LAO DIGIT EIGHT
#define UC_MACRO_NAME_ED9 0x0ED9 // ໙ LAO DIGIT NINE
#define UC_MACRO_NAME_EDC 0x0EDC // ໜ LAO HO NO
#define UC_MACRO_NAME_EDD 0x0EDD // ໝ LAO HO MO
#define UC_MACRO_NAME_EDE 0x0EDE // ໞ LAO LETTER KHMU GO
#define UC_MACRO_NAME_EDF 0x0EDF // ໟ LAO LETTER KHMU NYO


#endif // UC_H_LAO
