/*
 * Unicode Block: Lisu
 * Range: U+A4D0..U+A4FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Lisu may refer to:
 *
 */
#ifndef UC_H_LISU
#define UC_H_LISU

#define UC_MACRO_NAME_A4D0 0xA4D0 // ꓐ LISU LETTER BA
#define UC_MACRO_NAME_A4D1 0xA4D1 // ꓑ LISU LETTER PA
#define UC_MACRO_NAME_A4D2 0xA4D2 // ꓒ LISU LETTER PHA
#define UC_MACRO_NAME_A4D3 0xA4D3 // ꓓ LISU LETTER DA
#define UC_MACRO_NAME_A4D4 0xA4D4 // ꓔ LISU LETTER TA
#define UC_MACRO_NAME_A4D5 0xA4D5 // ꓕ LISU LETTER THA
#define UC_MACRO_NAME_A4D6 0xA4D6 // ꓖ LISU LETTER GA
#define UC_MACRO_NAME_A4D7 0xA4D7 // ꓗ LISU LETTER KA
#define UC_MACRO_NAME_A4D8 0xA4D8 // ꓘ LISU LETTER KHA
#define UC_MACRO_NAME_A4D9 0xA4D9 // ꓙ LISU LETTER JA
#define UC_MACRO_NAME_A4DA 0xA4DA // ꓚ LISU LETTER CA
#define UC_MACRO_NAME_A4DB 0xA4DB // ꓛ LISU LETTER CHA
#define UC_MACRO_NAME_A4DC 0xA4DC // ꓜ LISU LETTER DZA
#define UC_MACRO_NAME_A4DD 0xA4DD // ꓝ LISU LETTER TSA
#define UC_MACRO_NAME_A4DE 0xA4DE // ꓞ LISU LETTER TSHA
#define UC_MACRO_NAME_A4DF 0xA4DF // ꓟ LISU LETTER MA
#define UC_MACRO_NAME_A4E0 0xA4E0 // ꓠ LISU LETTER NA
#define UC_MACRO_NAME_A4E1 0xA4E1 // ꓡ LISU LETTER LA
#define UC_MACRO_NAME_A4E2 0xA4E2 // ꓢ LISU LETTER SA
#define UC_MACRO_NAME_A4E3 0xA4E3 // ꓣ LISU LETTER ZHA
#define UC_MACRO_NAME_A4E4 0xA4E4 // ꓤ LISU LETTER ZA
#define UC_MACRO_NAME_A4E5 0xA4E5 // ꓥ LISU LETTER NGA
#define UC_MACRO_NAME_A4E6 0xA4E6 // ꓦ LISU LETTER HA
#define UC_MACRO_NAME_A4E7 0xA4E7 // ꓧ LISU LETTER XA
#define UC_MACRO_NAME_A4E8 0xA4E8 // ꓨ LISU LETTER HHA
#define UC_MACRO_NAME_A4E9 0xA4E9 // ꓩ LISU LETTER FA
#define UC_MACRO_NAME_A4EA 0xA4EA // ꓪ LISU LETTER WA
#define UC_MACRO_NAME_A4EB 0xA4EB // ꓫ LISU LETTER SHA
#define UC_MACRO_NAME_A4EC 0xA4EC // ꓬ LISU LETTER YA
#define UC_MACRO_NAME_A4ED 0xA4ED // ꓭ LISU LETTER GHA
#define UC_MACRO_NAME_A4EE 0xA4EE // ꓮ LISU LETTER A
#define UC_MACRO_NAME_A4EF 0xA4EF // ꓯ LISU LETTER AE
#define UC_MACRO_NAME_A4F0 0xA4F0 // ꓰ LISU LETTER E
#define UC_MACRO_NAME_A4F1 0xA4F1 // ꓱ LISU LETTER EU
#define UC_MACRO_NAME_A4F2 0xA4F2 // ꓲ LISU LETTER I
#define UC_MACRO_NAME_A4F3 0xA4F3 // ꓳ LISU LETTER O
#define UC_MACRO_NAME_A4F4 0xA4F4 // ꓴ LISU LETTER U
#define UC_MACRO_NAME_A4F5 0xA4F5 // ꓵ LISU LETTER UE
#define UC_MACRO_NAME_A4F6 0xA4F6 // ꓶ LISU LETTER UH
#define UC_MACRO_NAME_A4F7 0xA4F7 // ꓷ LISU LETTER OE
#define UC_MACRO_NAME_A4F8 0xA4F8 // ꓸ LISU LETTER TONE MYA TI
#define UC_MACRO_NAME_A4F9 0xA4F9 // ꓹ LISU LETTER TONE NA PO
#define UC_MACRO_NAME_A4FA 0xA4FA // ꓺ LISU LETTER TONE MYA CYA
#define UC_MACRO_NAME_A4FB 0xA4FB // ꓻ LISU LETTER TONE MYA BO
#define UC_MACRO_NAME_A4FC 0xA4FC // ꓼ LISU LETTER TONE MYA NA
#define UC_MACRO_NAME_A4FD 0xA4FD // ꓽ LISU LETTER TONE MYA JEU
#define UC_MACRO_NAME_A4FE 0xA4FE // ꓾ LISU PUNCTUATION COMMA
#define UC_MACRO_NAME_A4FF 0xA4FF // ꓿ LISU PUNCTUATION FULL STOP


#endif // UC_H_LISU
