/*
 * Unicode Block: Latin Extended Additional
 * Range: U+1E00..U+1EFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Latin Extended Additional is a Unicode block .
 * Almost all characters (as many as 246) in this block are precomposed
 * combinations of Latin letters with one or more general diacritical
 * marks. Ninety of the characters are used in the Vietnamese alphabet .
 * There are also a few Medievalist characters.
 *
 */
#ifndef UC_H_LATIN_EXTENDED_ADDITIONAL
#define UC_H_LATIN_EXTENDED_ADDITIONAL

#define UC_MACRO_NAME_1E00 0x1E00 // Ḁ LATIN CAPITAL LETTER A WITH RING BELOW
#define UC_MACRO_NAME_1E01 0x1E01 // ḁ LATIN SMALL LETTER A WITH RING BELOW
#define UC_MACRO_NAME_1E02 0x1E02 // Ḃ LATIN CAPITAL LETTER B WITH DOT ABOVE
#define UC_MACRO_NAME_1E03 0x1E03 // ḃ LATIN SMALL LETTER B WITH DOT ABOVE
#define UC_MACRO_NAME_1E04 0x1E04 // Ḅ LATIN CAPITAL LETTER B WITH DOT BELOW
#define UC_MACRO_NAME_1E05 0x1E05 // ḅ LATIN SMALL LETTER B WITH DOT BELOW
#define UC_MACRO_NAME_1E06 0x1E06 // Ḇ LATIN CAPITAL LETTER B WITH LINE BELOW
#define UC_MACRO_NAME_1E07 0x1E07 // ḇ LATIN SMALL LETTER B WITH LINE BELOW
#define UC_MACRO_NAME_1E08 0x1E08 // Ḉ LATIN CAPITAL LETTER C WITH CEDILLA AND ACUTE
#define UC_MACRO_NAME_1E09 0x1E09 // ḉ LATIN SMALL LETTER C WITH CEDILLA AND ACUTE
#define UC_MACRO_NAME_1E0A 0x1E0A // Ḋ LATIN CAPITAL LETTER D WITH DOT ABOVE
#define UC_MACRO_NAME_1E0B 0x1E0B // ḋ LATIN SMALL LETTER D WITH DOT ABOVE
#define UC_MACRO_NAME_1E0C 0x1E0C // Ḍ LATIN CAPITAL LETTER D WITH DOT BELOW
#define UC_MACRO_NAME_1E0D 0x1E0D // ḍ LATIN SMALL LETTER D WITH DOT BELOW
#define UC_MACRO_NAME_1E0E 0x1E0E // Ḏ LATIN CAPITAL LETTER D WITH LINE BELOW
#define UC_MACRO_NAME_1E0F 0x1E0F // ḏ LATIN SMALL LETTER D WITH LINE BELOW
#define UC_MACRO_NAME_1E10 0x1E10 // Ḑ LATIN CAPITAL LETTER D WITH CEDILLA
#define UC_MACRO_NAME_1E11 0x1E11 // ḑ LATIN SMALL LETTER D WITH CEDILLA
#define UC_MACRO_NAME_1E12 0x1E12 // Ḓ LATIN CAPITAL LETTER D WITH CIRCUMFLEX BELOW
#define UC_MACRO_NAME_1E13 0x1E13 // ḓ LATIN SMALL LETTER D WITH CIRCUMFLEX BELOW
#define UC_MACRO_NAME_1E14 0x1E14 // Ḕ LATIN CAPITAL LETTER E WITH MACRON AND GRAVE
#define UC_MACRO_NAME_1E15 0x1E15 // ḕ LATIN SMALL LETTER E WITH MACRON AND GRAVE
#define UC_MACRO_NAME_1E16 0x1E16 // Ḗ LATIN CAPITAL LETTER E WITH MACRON AND ACUTE
#define UC_MACRO_NAME_1E17 0x1E17 // ḗ LATIN SMALL LETTER E WITH MACRON AND ACUTE
#define UC_MACRO_NAME_1E18 0x1E18 // Ḙ LATIN CAPITAL LETTER E WITH CIRCUMFLEX BELOW
#define UC_MACRO_NAME_1E19 0x1E19 // ḙ LATIN SMALL LETTER E WITH CIRCUMFLEX BELOW
#define UC_MACRO_NAME_1E1A 0x1E1A // Ḛ LATIN CAPITAL LETTER E WITH TILDE BELOW
#define UC_MACRO_NAME_1E1B 0x1E1B // ḛ LATIN SMALL LETTER E WITH TILDE BELOW
#define UC_MACRO_NAME_1E1C 0x1E1C // Ḝ LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE
#define UC_MACRO_NAME_1E1D 0x1E1D // ḝ LATIN SMALL LETTER E WITH CEDILLA AND BREVE
#define UC_MACRO_NAME_1E1E 0x1E1E // Ḟ LATIN CAPITAL LETTER F WITH DOT ABOVE
#define UC_MACRO_NAME_1E1F 0x1E1F // ḟ LATIN SMALL LETTER F WITH DOT ABOVE
#define UC_MACRO_NAME_1E20 0x1E20 // Ḡ LATIN CAPITAL LETTER G WITH MACRON
#define UC_MACRO_NAME_1E21 0x1E21 // ḡ LATIN SMALL LETTER G WITH MACRON
#define UC_MACRO_NAME_1E22 0x1E22 // Ḣ LATIN CAPITAL LETTER H WITH DOT ABOVE
#define UC_MACRO_NAME_1E23 0x1E23 // ḣ LATIN SMALL LETTER H WITH DOT ABOVE
#define UC_MACRO_NAME_1E24 0x1E24 // Ḥ LATIN CAPITAL LETTER H WITH DOT BELOW
#define UC_MACRO_NAME_1E25 0x1E25 // ḥ LATIN SMALL LETTER H WITH DOT BELOW
#define UC_MACRO_NAME_1E26 0x1E26 // Ḧ LATIN CAPITAL LETTER H WITH DIAERESIS
#define UC_MACRO_NAME_1E27 0x1E27 // ḧ LATIN SMALL LETTER H WITH DIAERESIS
#define UC_MACRO_NAME_1E28 0x1E28 // Ḩ LATIN CAPITAL LETTER H WITH CEDILLA
#define UC_MACRO_NAME_1E29 0x1E29 // ḩ LATIN SMALL LETTER H WITH CEDILLA
#define UC_MACRO_NAME_1E2A 0x1E2A // Ḫ LATIN CAPITAL LETTER H WITH BREVE BELOW
#define UC_MACRO_NAME_1E2B 0x1E2B // ḫ LATIN SMALL LETTER H WITH BREVE BELOW
#define UC_MACRO_NAME_1E2C 0x1E2C // Ḭ LATIN CAPITAL LETTER I WITH TILDE BELOW
#define UC_MACRO_NAME_1E2D 0x1E2D // ḭ LATIN SMALL LETTER I WITH TILDE BELOW
#define UC_MACRO_NAME_1E2E 0x1E2E // Ḯ LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE
#define UC_MACRO_NAME_1E2F 0x1E2F // ḯ LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE
#define UC_MACRO_NAME_1E30 0x1E30 // Ḱ LATIN CAPITAL LETTER K WITH ACUTE
#define UC_MACRO_NAME_1E31 0x1E31 // ḱ LATIN SMALL LETTER K WITH ACUTE
#define UC_MACRO_NAME_1E32 0x1E32 // Ḳ LATIN CAPITAL LETTER K WITH DOT BELOW
#define UC_MACRO_NAME_1E33 0x1E33 // ḳ LATIN SMALL LETTER K WITH DOT BELOW
#define UC_MACRO_NAME_1E34 0x1E34 // Ḵ LATIN CAPITAL LETTER K WITH LINE BELOW
#define UC_MACRO_NAME_1E35 0x1E35 // ḵ LATIN SMALL LETTER K WITH LINE BELOW
#define UC_MACRO_NAME_1E36 0x1E36 // Ḷ LATIN CAPITAL LETTER L WITH DOT BELOW
#define UC_MACRO_NAME_1E37 0x1E37 // ḷ LATIN SMALL LETTER L WITH DOT BELOW
#define UC_MACRO_NAME_1E38 0x1E38 // Ḹ LATIN CAPITAL LETTER L WITH DOT BELOW AND MACRON
#define UC_MACRO_NAME_1E39 0x1E39 // ḹ LATIN SMALL LETTER L WITH DOT BELOW AND MACRON
#define UC_MACRO_NAME_1E3A 0x1E3A // Ḻ LATIN CAPITAL LETTER L WITH LINE BELOW
#define UC_MACRO_NAME_1E3B 0x1E3B // ḻ LATIN SMALL LETTER L WITH LINE BELOW
#define UC_MACRO_NAME_1E3C 0x1E3C // Ḽ LATIN CAPITAL LETTER L WITH CIRCUMFLEX BELOW
#define UC_MACRO_NAME_1E3D 0x1E3D // ḽ LATIN SMALL LETTER L WITH CIRCUMFLEX BELOW
#define UC_MACRO_NAME_1E3E 0x1E3E // Ḿ LATIN CAPITAL LETTER M WITH ACUTE
#define UC_MACRO_NAME_1E3F 0x1E3F // ḿ LATIN SMALL LETTER M WITH ACUTE
#define UC_MACRO_NAME_1E40 0x1E40 // Ṁ LATIN CAPITAL LETTER M WITH DOT ABOVE
#define UC_MACRO_NAME_1E41 0x1E41 // ṁ LATIN SMALL LETTER M WITH DOT ABOVE
#define UC_MACRO_NAME_1E42 0x1E42 // Ṃ LATIN CAPITAL LETTER M WITH DOT BELOW
#define UC_MACRO_NAME_1E43 0x1E43 // ṃ LATIN SMALL LETTER M WITH DOT BELOW
#define UC_MACRO_NAME_1E44 0x1E44 // Ṅ LATIN CAPITAL LETTER N WITH DOT ABOVE
#define UC_MACRO_NAME_1E45 0x1E45 // ṅ LATIN SMALL LETTER N WITH DOT ABOVE
#define UC_MACRO_NAME_1E46 0x1E46 // Ṇ LATIN CAPITAL LETTER N WITH DOT BELOW
#define UC_MACRO_NAME_1E47 0x1E47 // ṇ LATIN SMALL LETTER N WITH DOT BELOW
#define UC_MACRO_NAME_1E48 0x1E48 // Ṉ LATIN CAPITAL LETTER N WITH LINE BELOW
#define UC_MACRO_NAME_1E49 0x1E49 // ṉ LATIN SMALL LETTER N WITH LINE BELOW
#define UC_MACRO_NAME_1E4A 0x1E4A // Ṋ LATIN CAPITAL LETTER N WITH CIRCUMFLEX BELOW
#define UC_MACRO_NAME_1E4B 0x1E4B // ṋ LATIN SMALL LETTER N WITH CIRCUMFLEX BELOW
#define UC_MACRO_NAME_1E4C 0x1E4C // Ṍ LATIN CAPITAL LETTER O WITH TILDE AND ACUTE
#define UC_MACRO_NAME_1E4D 0x1E4D // ṍ LATIN SMALL LETTER O WITH TILDE AND ACUTE
#define UC_MACRO_NAME_1E4E 0x1E4E // Ṏ LATIN CAPITAL LETTER O WITH TILDE AND DIAERESIS
#define UC_MACRO_NAME_1E4F 0x1E4F // ṏ LATIN SMALL LETTER O WITH TILDE AND DIAERESIS
#define UC_MACRO_NAME_1E50 0x1E50 // Ṑ LATIN CAPITAL LETTER O WITH MACRON AND GRAVE
#define UC_MACRO_NAME_1E51 0x1E51 // ṑ LATIN SMALL LETTER O WITH MACRON AND GRAVE
#define UC_MACRO_NAME_1E52 0x1E52 // Ṓ LATIN CAPITAL LETTER O WITH MACRON AND ACUTE
#define UC_MACRO_NAME_1E53 0x1E53 // ṓ LATIN SMALL LETTER O WITH MACRON AND ACUTE
#define UC_MACRO_NAME_1E54 0x1E54 // Ṕ LATIN CAPITAL LETTER P WITH ACUTE
#define UC_MACRO_NAME_1E55 0x1E55 // ṕ LATIN SMALL LETTER P WITH ACUTE
#define UC_MACRO_NAME_1E56 0x1E56 // Ṗ LATIN CAPITAL LETTER P WITH DOT ABOVE
#define UC_MACRO_NAME_1E57 0x1E57 // ṗ LATIN SMALL LETTER P WITH DOT ABOVE
#define UC_MACRO_NAME_1E58 0x1E58 // Ṙ LATIN CAPITAL LETTER R WITH DOT ABOVE
#define UC_MACRO_NAME_1E59 0x1E59 // ṙ LATIN SMALL LETTER R WITH DOT ABOVE
#define UC_MACRO_NAME_1E5A 0x1E5A // Ṛ LATIN CAPITAL LETTER R WITH DOT BELOW
#define UC_MACRO_NAME_1E5B 0x1E5B // ṛ LATIN SMALL LETTER R WITH DOT BELOW
#define UC_MACRO_NAME_1E5C 0x1E5C // Ṝ LATIN CAPITAL LETTER R WITH DOT BELOW AND MACRON
#define UC_MACRO_NAME_1E5D 0x1E5D // ṝ LATIN SMALL LETTER R WITH DOT BELOW AND MACRON
#define UC_MACRO_NAME_1E5E 0x1E5E // Ṟ LATIN CAPITAL LETTER R WITH LINE BELOW
#define UC_MACRO_NAME_1E5F 0x1E5F // ṟ LATIN SMALL LETTER R WITH LINE BELOW
#define UC_MACRO_NAME_1E60 0x1E60 // Ṡ LATIN CAPITAL LETTER S WITH DOT ABOVE
#define UC_MACRO_NAME_1E61 0x1E61 // ṡ LATIN SMALL LETTER S WITH DOT ABOVE
#define UC_MACRO_NAME_1E62 0x1E62 // Ṣ LATIN CAPITAL LETTER S WITH DOT BELOW
#define UC_MACRO_NAME_1E63 0x1E63 // ṣ LATIN SMALL LETTER S WITH DOT BELOW
#define UC_MACRO_NAME_1E64 0x1E64 // Ṥ LATIN CAPITAL LETTER S WITH ACUTE AND DOT ABOVE
#define UC_MACRO_NAME_1E65 0x1E65 // ṥ LATIN SMALL LETTER S WITH ACUTE AND DOT ABOVE
#define UC_MACRO_NAME_1E66 0x1E66 // Ṧ LATIN CAPITAL LETTER S WITH CARON AND DOT ABOVE
#define UC_MACRO_NAME_1E67 0x1E67 // ṧ LATIN SMALL LETTER S WITH CARON AND DOT ABOVE
#define UC_MACRO_NAME_1E68 0x1E68 // Ṩ LATIN CAPITAL LETTER S WITH DOT BELOW AND DOT ABOVE
#define UC_MACRO_NAME_1E69 0x1E69 // ṩ LATIN SMALL LETTER S WITH DOT BELOW AND DOT ABOVE
#define UC_MACRO_NAME_1E6A 0x1E6A // Ṫ LATIN CAPITAL LETTER T WITH DOT ABOVE
#define UC_MACRO_NAME_1E6B 0x1E6B // ṫ LATIN SMALL LETTER T WITH DOT ABOVE
#define UC_MACRO_NAME_1E6C 0x1E6C // Ṭ LATIN CAPITAL LETTER T WITH DOT BELOW
#define UC_MACRO_NAME_1E6D 0x1E6D // ṭ LATIN SMALL LETTER T WITH DOT BELOW
#define UC_MACRO_NAME_1E6E 0x1E6E // Ṯ LATIN CAPITAL LETTER T WITH LINE BELOW
#define UC_MACRO_NAME_1E6F 0x1E6F // ṯ LATIN SMALL LETTER T WITH LINE BELOW
#define UC_MACRO_NAME_1E70 0x1E70 // Ṱ LATIN CAPITAL LETTER T WITH CIRCUMFLEX BELOW
#define UC_MACRO_NAME_1E71 0x1E71 // ṱ LATIN SMALL LETTER T WITH CIRCUMFLEX BELOW
#define UC_MACRO_NAME_1E72 0x1E72 // Ṳ LATIN CAPITAL LETTER U WITH DIAERESIS BELOW
#define UC_MACRO_NAME_1E73 0x1E73 // ṳ LATIN SMALL LETTER U WITH DIAERESIS BELOW
#define UC_MACRO_NAME_1E74 0x1E74 // Ṵ LATIN CAPITAL LETTER U WITH TILDE BELOW
#define UC_MACRO_NAME_1E75 0x1E75 // ṵ LATIN SMALL LETTER U WITH TILDE BELOW
#define UC_MACRO_NAME_1E76 0x1E76 // Ṷ LATIN CAPITAL LETTER U WITH CIRCUMFLEX BELOW
#define UC_MACRO_NAME_1E77 0x1E77 // ṷ LATIN SMALL LETTER U WITH CIRCUMFLEX BELOW
#define UC_MACRO_NAME_1E78 0x1E78 // Ṹ LATIN CAPITAL LETTER U WITH TILDE AND ACUTE
#define UC_MACRO_NAME_1E79 0x1E79 // ṹ LATIN SMALL LETTER U WITH TILDE AND ACUTE
#define UC_MACRO_NAME_1E7A 0x1E7A // Ṻ LATIN CAPITAL LETTER U WITH MACRON AND DIAERESIS
#define UC_MACRO_NAME_1E7B 0x1E7B // ṻ LATIN SMALL LETTER U WITH MACRON AND DIAERESIS
#define UC_MACRO_NAME_1E7C 0x1E7C // Ṽ LATIN CAPITAL LETTER V WITH TILDE
#define UC_MACRO_NAME_1E7D 0x1E7D // ṽ LATIN SMALL LETTER V WITH TILDE
#define UC_MACRO_NAME_1E7E 0x1E7E // Ṿ LATIN CAPITAL LETTER V WITH DOT BELOW
#define UC_MACRO_NAME_1E7F 0x1E7F // ṿ LATIN SMALL LETTER V WITH DOT BELOW
#define UC_MACRO_NAME_1E80 0x1E80 // Ẁ LATIN CAPITAL LETTER W WITH GRAVE
#define UC_MACRO_NAME_1E81 0x1E81 // ẁ LATIN SMALL LETTER W WITH GRAVE
#define UC_MACRO_NAME_1E82 0x1E82 // Ẃ LATIN CAPITAL LETTER W WITH ACUTE
#define UC_MACRO_NAME_1E83 0x1E83 // ẃ LATIN SMALL LETTER W WITH ACUTE
#define UC_MACRO_NAME_1E84 0x1E84 // Ẅ LATIN CAPITAL LETTER W WITH DIAERESIS
#define UC_MACRO_NAME_1E85 0x1E85 // ẅ LATIN SMALL LETTER W WITH DIAERESIS
#define UC_MACRO_NAME_1E86 0x1E86 // Ẇ LATIN CAPITAL LETTER W WITH DOT ABOVE
#define UC_MACRO_NAME_1E87 0x1E87 // ẇ LATIN SMALL LETTER W WITH DOT ABOVE
#define UC_MACRO_NAME_1E88 0x1E88 // Ẉ LATIN CAPITAL LETTER W WITH DOT BELOW
#define UC_MACRO_NAME_1E89 0x1E89 // ẉ LATIN SMALL LETTER W WITH DOT BELOW
#define UC_MACRO_NAME_1E8A 0x1E8A // Ẋ LATIN CAPITAL LETTER X WITH DOT ABOVE
#define UC_MACRO_NAME_1E8B 0x1E8B // ẋ LATIN SMALL LETTER X WITH DOT ABOVE
#define UC_MACRO_NAME_1E8C 0x1E8C // Ẍ LATIN CAPITAL LETTER X WITH DIAERESIS
#define UC_MACRO_NAME_1E8D 0x1E8D // ẍ LATIN SMALL LETTER X WITH DIAERESIS
#define UC_MACRO_NAME_1E8E 0x1E8E // Ẏ LATIN CAPITAL LETTER Y WITH DOT ABOVE
#define UC_MACRO_NAME_1E8F 0x1E8F // ẏ LATIN SMALL LETTER Y WITH DOT ABOVE
#define UC_MACRO_NAME_1E90 0x1E90 // Ẑ LATIN CAPITAL LETTER Z WITH CIRCUMFLEX
#define UC_MACRO_NAME_1E91 0x1E91 // ẑ LATIN SMALL LETTER Z WITH CIRCUMFLEX
#define UC_MACRO_NAME_1E92 0x1E92 // Ẓ LATIN CAPITAL LETTER Z WITH DOT BELOW
#define UC_MACRO_NAME_1E93 0x1E93 // ẓ LATIN SMALL LETTER Z WITH DOT BELOW
#define UC_MACRO_NAME_1E94 0x1E94 // Ẕ LATIN CAPITAL LETTER Z WITH LINE BELOW
#define UC_MACRO_NAME_1E95 0x1E95 // ẕ LATIN SMALL LETTER Z WITH LINE BELOW
#define UC_MACRO_NAME_1E96 0x1E96 // ẖ LATIN SMALL LETTER H WITH LINE BELOW
#define UC_MACRO_NAME_1E97 0x1E97 // ẗ LATIN SMALL LETTER T WITH DIAERESIS
#define UC_MACRO_NAME_1E98 0x1E98 // ẘ LATIN SMALL LETTER W WITH RING ABOVE
#define UC_MACRO_NAME_1E99 0x1E99 // ẙ LATIN SMALL LETTER Y WITH RING ABOVE
#define UC_MACRO_NAME_1E9A 0x1E9A // ẚ LATIN SMALL LETTER A WITH RIGHT HALF RING
#define UC_MACRO_NAME_1E9B 0x1E9B // ẛ LATIN SMALL LETTER LONG S WITH DOT ABOVE
#define UC_MACRO_NAME_1E9C 0x1E9C // ẜ LATIN SMALL LETTER LONG S WITH DIAGONAL STROKE
#define UC_MACRO_NAME_1E9D 0x1E9D // ẝ LATIN SMALL LETTER LONG S WITH HIGH STROKE
#define UC_MACRO_NAME_1E9E 0x1E9E // ẞ LATIN CAPITAL LETTER SHARP S
#define UC_MACRO_NAME_1E9F 0x1E9F // ẟ LATIN SMALL LETTER DELTA
#define UC_MACRO_NAME_1EA0 0x1EA0 // Ạ LATIN CAPITAL LETTER A WITH DOT BELOW
#define UC_MACRO_NAME_1EA1 0x1EA1 // ạ LATIN SMALL LETTER A WITH DOT BELOW
#define UC_MACRO_NAME_1EA2 0x1EA2 // Ả LATIN CAPITAL LETTER A WITH HOOK ABOVE
#define UC_MACRO_NAME_1EA3 0x1EA3 // ả LATIN SMALL LETTER A WITH HOOK ABOVE
#define UC_MACRO_NAME_1EA4 0x1EA4 // Ấ LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND ACUTE
#define UC_MACRO_NAME_1EA5 0x1EA5 // ấ LATIN SMALL LETTER A WITH CIRCUMFLEX AND ACUTE
#define UC_MACRO_NAME_1EA6 0x1EA6 // Ầ LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND GRAVE
#define UC_MACRO_NAME_1EA7 0x1EA7 // ầ LATIN SMALL LETTER A WITH CIRCUMFLEX AND GRAVE
#define UC_MACRO_NAME_1EA8 0x1EA8 // Ẩ LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
#define UC_MACRO_NAME_1EA9 0x1EA9 // ẩ LATIN SMALL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
#define UC_MACRO_NAME_1EAA 0x1EAA // Ẫ LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND TILDE
#define UC_MACRO_NAME_1EAB 0x1EAB // ẫ LATIN SMALL LETTER A WITH CIRCUMFLEX AND TILDE
#define UC_MACRO_NAME_1EAC 0x1EAC // Ậ LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW
#define UC_MACRO_NAME_1EAD 0x1EAD // ậ LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW
#define UC_MACRO_NAME_1EAE 0x1EAE // Ắ LATIN CAPITAL LETTER A WITH BREVE AND ACUTE
#define UC_MACRO_NAME_1EAF 0x1EAF // ắ LATIN SMALL LETTER A WITH BREVE AND ACUTE
#define UC_MACRO_NAME_1EB0 0x1EB0 // Ằ LATIN CAPITAL LETTER A WITH BREVE AND GRAVE
#define UC_MACRO_NAME_1EB1 0x1EB1 // ằ LATIN SMALL LETTER A WITH BREVE AND GRAVE
#define UC_MACRO_NAME_1EB2 0x1EB2 // Ẳ LATIN CAPITAL LETTER A WITH BREVE AND HOOK ABOVE
#define UC_MACRO_NAME_1EB3 0x1EB3 // ẳ LATIN SMALL LETTER A WITH BREVE AND HOOK ABOVE
#define UC_MACRO_NAME_1EB4 0x1EB4 // Ẵ LATIN CAPITAL LETTER A WITH BREVE AND TILDE
#define UC_MACRO_NAME_1EB5 0x1EB5 // ẵ LATIN SMALL LETTER A WITH BREVE AND TILDE
#define UC_MACRO_NAME_1EB6 0x1EB6 // Ặ LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW
#define UC_MACRO_NAME_1EB7 0x1EB7 // ặ LATIN SMALL LETTER A WITH BREVE AND DOT BELOW
#define UC_MACRO_NAME_1EB8 0x1EB8 // Ẹ LATIN CAPITAL LETTER E WITH DOT BELOW
#define UC_MACRO_NAME_1EB9 0x1EB9 // ẹ LATIN SMALL LETTER E WITH DOT BELOW
#define UC_MACRO_NAME_1EBA 0x1EBA // Ẻ LATIN CAPITAL LETTER E WITH HOOK ABOVE
#define UC_MACRO_NAME_1EBB 0x1EBB // ẻ LATIN SMALL LETTER E WITH HOOK ABOVE
#define UC_MACRO_NAME_1EBC 0x1EBC // Ẽ LATIN CAPITAL LETTER E WITH TILDE
#define UC_MACRO_NAME_1EBD 0x1EBD // ẽ LATIN SMALL LETTER E WITH TILDE
#define UC_MACRO_NAME_1EBE 0x1EBE // Ế LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND ACUTE
#define UC_MACRO_NAME_1EBF 0x1EBF // ế LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE
#define UC_MACRO_NAME_1EC0 0x1EC0 // Ề LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND GRAVE
#define UC_MACRO_NAME_1EC1 0x1EC1 // ề LATIN SMALL LETTER E WITH CIRCUMFLEX AND GRAVE
#define UC_MACRO_NAME_1EC2 0x1EC2 // Ể LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
#define UC_MACRO_NAME_1EC3 0x1EC3 // ể LATIN SMALL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
#define UC_MACRO_NAME_1EC4 0x1EC4 // Ễ LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND TILDE
#define UC_MACRO_NAME_1EC5 0x1EC5 // ễ LATIN SMALL LETTER E WITH CIRCUMFLEX AND TILDE
#define UC_MACRO_NAME_1EC6 0x1EC6 // Ệ LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND DOT BELOW
#define UC_MACRO_NAME_1EC7 0x1EC7 // ệ LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW
#define UC_MACRO_NAME_1EC8 0x1EC8 // Ỉ LATIN CAPITAL LETTER I WITH HOOK ABOVE
#define UC_MACRO_NAME_1EC9 0x1EC9 // ỉ LATIN SMALL LETTER I WITH HOOK ABOVE
#define UC_MACRO_NAME_1ECA 0x1ECA // Ị LATIN CAPITAL LETTER I WITH DOT BELOW
#define UC_MACRO_NAME_1ECB 0x1ECB // ị LATIN SMALL LETTER I WITH DOT BELOW
#define UC_MACRO_NAME_1ECC 0x1ECC // Ọ LATIN CAPITAL LETTER O WITH DOT BELOW
#define UC_MACRO_NAME_1ECD 0x1ECD // ọ LATIN SMALL LETTER O WITH DOT BELOW
#define UC_MACRO_NAME_1ECE 0x1ECE // Ỏ LATIN CAPITAL LETTER O WITH HOOK ABOVE
#define UC_MACRO_NAME_1ECF 0x1ECF // ỏ LATIN SMALL LETTER O WITH HOOK ABOVE
#define UC_MACRO_NAME_1ED0 0x1ED0 // Ố LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE
#define UC_MACRO_NAME_1ED1 0x1ED1 // ố LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE
#define UC_MACRO_NAME_1ED2 0x1ED2 // Ồ LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND GRAVE
#define UC_MACRO_NAME_1ED3 0x1ED3 // ồ LATIN SMALL LETTER O WITH CIRCUMFLEX AND GRAVE
#define UC_MACRO_NAME_1ED4 0x1ED4 // Ổ LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
#define UC_MACRO_NAME_1ED5 0x1ED5 // ổ LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
#define UC_MACRO_NAME_1ED6 0x1ED6 // Ỗ LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND TILDE
#define UC_MACRO_NAME_1ED7 0x1ED7 // ỗ LATIN SMALL LETTER O WITH CIRCUMFLEX AND TILDE
#define UC_MACRO_NAME_1ED8 0x1ED8 // Ộ LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND DOT BELOW
#define UC_MACRO_NAME_1ED9 0x1ED9 // ộ LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW
#define UC_MACRO_NAME_1EDA 0x1EDA // Ớ LATIN CAPITAL LETTER O WITH HORN AND ACUTE
#define UC_MACRO_NAME_1EDB 0x1EDB // ớ LATIN SMALL LETTER O WITH HORN AND ACUTE
#define UC_MACRO_NAME_1EDC 0x1EDC // Ờ LATIN CAPITAL LETTER O WITH HORN AND GRAVE
#define UC_MACRO_NAME_1EDD 0x1EDD // ờ LATIN SMALL LETTER O WITH HORN AND GRAVE
#define UC_MACRO_NAME_1EDE 0x1EDE // Ở LATIN CAPITAL LETTER O WITH HORN AND HOOK ABOVE
#define UC_MACRO_NAME_1EDF 0x1EDF // ở LATIN SMALL LETTER O WITH HORN AND HOOK ABOVE
#define UC_MACRO_NAME_1EE0 0x1EE0 // Ỡ LATIN CAPITAL LETTER O WITH HORN AND TILDE
#define UC_MACRO_NAME_1EE1 0x1EE1 // ỡ LATIN SMALL LETTER O WITH HORN AND TILDE
#define UC_MACRO_NAME_1EE2 0x1EE2 // Ợ LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW
#define UC_MACRO_NAME_1EE3 0x1EE3 // ợ LATIN SMALL LETTER O WITH HORN AND DOT BELOW
#define UC_MACRO_NAME_1EE4 0x1EE4 // Ụ LATIN CAPITAL LETTER U WITH DOT BELOW
#define UC_MACRO_NAME_1EE5 0x1EE5 // ụ LATIN SMALL LETTER U WITH DOT BELOW
#define UC_MACRO_NAME_1EE6 0x1EE6 // Ủ LATIN CAPITAL LETTER U WITH HOOK ABOVE
#define UC_MACRO_NAME_1EE7 0x1EE7 // ủ LATIN SMALL LETTER U WITH HOOK ABOVE
#define UC_MACRO_NAME_1EE8 0x1EE8 // Ứ LATIN CAPITAL LETTER U WITH HORN AND ACUTE
#define UC_MACRO_NAME_1EE9 0x1EE9 // ứ LATIN SMALL LETTER U WITH HORN AND ACUTE
#define UC_MACRO_NAME_1EEA 0x1EEA // Ừ LATIN CAPITAL LETTER U WITH HORN AND GRAVE
#define UC_MACRO_NAME_1EEB 0x1EEB // ừ LATIN SMALL LETTER U WITH HORN AND GRAVE
#define UC_MACRO_NAME_1EEC 0x1EEC // Ử LATIN CAPITAL LETTER U WITH HORN AND HOOK ABOVE
#define UC_MACRO_NAME_1EED 0x1EED // ử LATIN SMALL LETTER U WITH HORN AND HOOK ABOVE
#define UC_MACRO_NAME_1EEE 0x1EEE // Ữ LATIN CAPITAL LETTER U WITH HORN AND TILDE
#define UC_MACRO_NAME_1EEF 0x1EEF // ữ LATIN SMALL LETTER U WITH HORN AND TILDE
#define UC_MACRO_NAME_1EF0 0x1EF0 // Ự LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW
#define UC_MACRO_NAME_1EF1 0x1EF1 // ự LATIN SMALL LETTER U WITH HORN AND DOT BELOW
#define UC_MACRO_NAME_1EF2 0x1EF2 // Ỳ LATIN CAPITAL LETTER Y WITH GRAVE
#define UC_MACRO_NAME_1EF3 0x1EF3 // ỳ LATIN SMALL LETTER Y WITH GRAVE
#define UC_MACRO_NAME_1EF4 0x1EF4 // Ỵ LATIN CAPITAL LETTER Y WITH DOT BELOW
#define UC_MACRO_NAME_1EF5 0x1EF5 // ỵ LATIN SMALL LETTER Y WITH DOT BELOW
#define UC_MACRO_NAME_1EF6 0x1EF6 // Ỷ LATIN CAPITAL LETTER Y WITH HOOK ABOVE
#define UC_MACRO_NAME_1EF7 0x1EF7 // ỷ LATIN SMALL LETTER Y WITH HOOK ABOVE
#define UC_MACRO_NAME_1EF8 0x1EF8 // Ỹ LATIN CAPITAL LETTER Y WITH TILDE
#define UC_MACRO_NAME_1EF9 0x1EF9 // ỹ LATIN SMALL LETTER Y WITH TILDE
#define UC_MACRO_NAME_1EFA 0x1EFA // Ỻ LATIN CAPITAL LETTER MIDDLE-WELSH LL
#define UC_MACRO_NAME_1EFB 0x1EFB // ỻ LATIN SMALL LETTER MIDDLE-WELSH LL
#define UC_MACRO_NAME_1EFC 0x1EFC // Ỽ LATIN CAPITAL LETTER MIDDLE-WELSH V
#define UC_MACRO_NAME_1EFD 0x1EFD // ỽ LATIN SMALL LETTER MIDDLE-WELSH V
#define UC_MACRO_NAME_1EFE 0x1EFE // Ỿ LATIN CAPITAL LETTER Y WITH LOOP
#define UC_MACRO_NAME_1EFF 0x1EFF // ỿ LATIN SMALL LETTER Y WITH LOOP


#endif // UC_H_LATIN_EXTENDED_ADDITIONAL
