/*
 * Unicode Block: Meetei Mayek Extensions
 * Range: U+AAE0..U+AAFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Meetei Mayek Extensions are extensions to the Meetei Mayek (Unicode
 * block) containing characters for historic Meitei language
 * orthographies.
 * The following Unicode-related documents record the purpose and process
 * of defining specific characters in the Meetei Mayek Extensions block:
 *
 */
#ifndef UC_H_MEETEI_MAYEK_EXTENSIONS
#define UC_H_MEETEI_MAYEK_EXTENSIONS

#define UC_MACRO_NAME_AAE0 0xAAE0 // ꫠ MEETEI MAYEK LETTER E
#define UC_MACRO_NAME_AAE1 0xAAE1 // ꫡ MEETEI MAYEK LETTER O
#define UC_MACRO_NAME_AAE2 0xAAE2 // ꫢ MEETEI MAYEK LETTER CHA
#define UC_MACRO_NAME_AAE3 0xAAE3 // ꫣ MEETEI MAYEK LETTER NYA
#define UC_MACRO_NAME_AAE4 0xAAE4 // ꫤ MEETEI MAYEK LETTER TTA
#define UC_MACRO_NAME_AAE5 0xAAE5 // ꫥ MEETEI MAYEK LETTER TTHA
#define UC_MACRO_NAME_AAE6 0xAAE6 // ꫦ MEETEI MAYEK LETTER DDA
#define UC_MACRO_NAME_AAE7 0xAAE7 // ꫧ MEETEI MAYEK LETTER DDHA
#define UC_MACRO_NAME_AAE8 0xAAE8 // ꫨ MEETEI MAYEK LETTER NNA
#define UC_MACRO_NAME_AAE9 0xAAE9 // ꫩ MEETEI MAYEK LETTER SHA
#define UC_MACRO_NAME_AAEA 0xAAEA // ꫪ MEETEI MAYEK LETTER SSA
#define UC_MACRO_NAME_AAEB 0xAAEB // ꫫ MEETEI MAYEK VOWEL SIGN II
#define UC_MACRO_NAME_AAEC 0xAAEC // ꫬ MEETEI MAYEK VOWEL SIGN UU
#define UC_MACRO_NAME_AAED 0xAAED // ꫭ MEETEI MAYEK VOWEL SIGN AAI
#define UC_MACRO_NAME_AAEE 0xAAEE // ꫮ MEETEI MAYEK VOWEL SIGN AU
#define UC_MACRO_NAME_AAEF 0xAAEF // ꫯ MEETEI MAYEK VOWEL SIGN AAU
#define UC_MACRO_NAME_AAF0 0xAAF0 // ꫰ MEETEI MAYEK CHEIKHAN
#define UC_MACRO_NAME_AAF1 0xAAF1 // ꫱ MEETEI MAYEK AHANG KHUDAM
#define UC_MACRO_NAME_AAF2 0xAAF2 // ꫲ MEETEI MAYEK ANJI
#define UC_MACRO_NAME_AAF3 0xAAF3 // ꫳ MEETEI MAYEK SYLLABLE REPETITION MARK
#define UC_MACRO_NAME_AAF4 0xAAF4 // ꫴ MEETEI MAYEK WORD REPETITION MARK
#define UC_MACRO_NAME_AAF5 0xAAF5 // ꫵ MEETEI MAYEK VOWEL SIGN VISARGA
#define UC_MACRO_NAME_AAF6 0xAAF6 // ꫶ MEETEI MAYEK VIRAMA


#endif // UC_H_MEETEI_MAYEK_EXTENSIONS
