/*
 * Unicode Block: Miscellaneous Symbols and Arrows
 * Range: U+2B00..U+2BFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_MISCELLANEOUS_SYMBOLS_AND_ARROWS
#define UC_H_MISCELLANEOUS_SYMBOLS_AND_ARROWS

#define UC_MACRO_NAME_2B00 0x2B00 // ⬀ NORTH EAST WHITE ARROW
#define UC_MACRO_NAME_2B01 0x2B01 // ⬁ NORTH WEST WHITE ARROW
#define UC_MACRO_NAME_2B02 0x2B02 // ⬂ SOUTH EAST WHITE ARROW
#define UC_MACRO_NAME_2B03 0x2B03 // ⬃ SOUTH WEST WHITE ARROW
#define UC_MACRO_NAME_2B04 0x2B04 // ⬄ LEFT RIGHT WHITE ARROW
#define UC_MACRO_NAME_2B05 0x2B05 // ⬅ LEFTWARDS BLACK ARROW
#define UC_MACRO_NAME_2B06 0x2B06 // ⬆ UPWARDS BLACK ARROW
#define UC_MACRO_NAME_2B07 0x2B07 // ⬇ DOWNWARDS BLACK ARROW
#define UC_MACRO_NAME_2B08 0x2B08 // ⬈ NORTH EAST BLACK ARROW
#define UC_MACRO_NAME_2B09 0x2B09 // ⬉ NORTH WEST BLACK ARROW
#define UC_MACRO_NAME_2B0A 0x2B0A // ⬊ SOUTH EAST BLACK ARROW
#define UC_MACRO_NAME_2B0B 0x2B0B // ⬋ SOUTH WEST BLACK ARROW
#define UC_MACRO_NAME_2B0C 0x2B0C // ⬌ LEFT RIGHT BLACK ARROW
#define UC_MACRO_NAME_2B0D 0x2B0D // ⬍ UP DOWN BLACK ARROW
#define UC_MACRO_NAME_2B0E 0x2B0E // ⬎ RIGHTWARDS ARROW WITH TIP DOWNWARDS
#define UC_MACRO_NAME_2B0F 0x2B0F // ⬏ RIGHTWARDS ARROW WITH TIP UPWARDS
#define UC_MACRO_NAME_2B10 0x2B10 // ⬐ LEFTWARDS ARROW WITH TIP DOWNWARDS
#define UC_MACRO_NAME_2B11 0x2B11 // ⬑ LEFTWARDS ARROW WITH TIP UPWARDS
#define UC_MACRO_NAME_2B12 0x2B12 // ⬒ SQUARE WITH TOP HALF BLACK
#define UC_MACRO_NAME_2B13 0x2B13 // ⬓ SQUARE WITH BOTTOM HALF BLACK
#define UC_MACRO_NAME_2B14 0x2B14 // ⬔ SQUARE WITH UPPER RIGHT DIAGONAL HALF BLACK
#define UC_MACRO_NAME_2B15 0x2B15 // ⬕ SQUARE WITH LOWER LEFT DIAGONAL HALF BLACK
#define UC_MACRO_NAME_2B16 0x2B16 // ⬖ DIAMOND WITH LEFT HALF BLACK
#define UC_MACRO_NAME_2B17 0x2B17 // ⬗ DIAMOND WITH RIGHT HALF BLACK
#define UC_MACRO_NAME_2B18 0x2B18 // ⬘ DIAMOND WITH TOP HALF BLACK
#define UC_MACRO_NAME_2B19 0x2B19 // ⬙ DIAMOND WITH BOTTOM HALF BLACK
#define UC_MACRO_NAME_2B1A 0x2B1A // ⬚ DOTTED SQUARE
#define UC_MACRO_NAME_2B1B 0x2B1B // ⬛ BLACK LARGE SQUARE
#define UC_MACRO_NAME_2B1C 0x2B1C // ⬜ WHITE LARGE SQUARE
#define UC_MACRO_NAME_2B1D 0x2B1D // ⬝ BLACK VERY SMALL SQUARE
#define UC_MACRO_NAME_2B1E 0x2B1E // ⬞ WHITE VERY SMALL SQUARE
#define UC_MACRO_NAME_2B1F 0x2B1F // ⬟ BLACK PENTAGON
#define UC_MACRO_NAME_2B20 0x2B20 // ⬠ WHITE PENTAGON
#define UC_MACRO_NAME_2B21 0x2B21 // ⬡ WHITE HEXAGON
#define UC_MACRO_NAME_2B22 0x2B22 // ⬢ BLACK HEXAGON
#define UC_MACRO_NAME_2B23 0x2B23 // ⬣ HORIZONTAL BLACK HEXAGON
#define UC_MACRO_NAME_2B24 0x2B24 // ⬤ BLACK LARGE CIRCLE
#define UC_MACRO_NAME_2B25 0x2B25 // ⬥ BLACK MEDIUM DIAMOND
#define UC_MACRO_NAME_2B26 0x2B26 // ⬦ WHITE MEDIUM DIAMOND
#define UC_MACRO_NAME_2B27 0x2B27 // ⬧ BLACK MEDIUM LOZENGE
#define UC_MACRO_NAME_2B28 0x2B28 // ⬨ WHITE MEDIUM LOZENGE
#define UC_MACRO_NAME_2B29 0x2B29 // ⬩ BLACK SMALL DIAMOND
#define UC_MACRO_NAME_2B2A 0x2B2A // ⬪ BLACK SMALL LOZENGE
#define UC_MACRO_NAME_2B2B 0x2B2B // ⬫ WHITE SMALL LOZENGE
#define UC_MACRO_NAME_2B2C 0x2B2C // ⬬ BLACK HORIZONTAL ELLIPSE
#define UC_MACRO_NAME_2B2D 0x2B2D // ⬭ WHITE HORIZONTAL ELLIPSE
#define UC_MACRO_NAME_2B2E 0x2B2E // ⬮ BLACK VERTICAL ELLIPSE
#define UC_MACRO_NAME_2B2F 0x2B2F // ⬯ WHITE VERTICAL ELLIPSE
#define UC_MACRO_NAME_2B30 0x2B30 // ⬰ LEFT ARROW WITH SMALL CIRCLE
#define UC_MACRO_NAME_2B31 0x2B31 // ⬱ THREE LEFTWARDS ARROWS
#define UC_MACRO_NAME_2B32 0x2B32 // ⬲ LEFT ARROW WITH CIRCLED PLUS
#define UC_MACRO_NAME_2B33 0x2B33 // ⬳ LONG LEFTWARDS SQUIGGLE ARROW
#define UC_MACRO_NAME_2B34 0x2B34 // ⬴ LEFTWARDS TWO-HEADED ARROW WITH VERTICAL STROKE
#define UC_MACRO_NAME_2B35 0x2B35 // ⬵ LEFTWARDS TWO-HEADED ARROW WITH DOUBLE VERTICAL STROKE
#define UC_MACRO_NAME_2B36 0x2B36 // ⬶ LEFTWARDS TWO-HEADED ARROW FROM BAR
#define UC_MACRO_NAME_2B37 0x2B37 // ⬷ LEFTWARDS TWO-HEADED TRIPLE DASH ARROW
#define UC_MACRO_NAME_2B38 0x2B38 // ⬸ LEFTWARDS ARROW WITH DOTTED STEM
#define UC_MACRO_NAME_2B39 0x2B39 // ⬹ LEFTWARDS ARROW WITH TAIL WITH VERTICAL STROKE
#define UC_MACRO_NAME_2B3A 0x2B3A // ⬺ LEFTWARDS ARROW WITH TAIL WITH DOUBLE VERTICAL STROKE
#define UC_MACRO_NAME_2B3B 0x2B3B // ⬻ LEFTWARDS TWO-HEADED ARROW WITH TAIL
#define UC_MACRO_NAME_2B3C 0x2B3C // ⬼ LEFTWARDS TWO-HEADED ARROW WITH TAIL WITH VERTICAL STROKE
#define UC_MACRO_NAME_2B3D 0x2B3D // ⬽ LEFTWARDS TWO-HEADED ARROW WITH TAIL WITH DOUBLE VERTICAL STROKE
#define UC_MACRO_NAME_2B3E 0x2B3E // ⬾ LEFTWARDS ARROW THROUGH X
#define UC_MACRO_NAME_2B3F 0x2B3F // ⬿ WAVE ARROW POINTING DIRECTLY LEFT
#define UC_MACRO_NAME_2B40 0x2B40 // ⭀ EQUALS SIGN ABOVE LEFTWARDS ARROW
#define UC_MACRO_NAME_2B41 0x2B41 // ⭁ REVERSE TILDE OPERATOR ABOVE LEFTWARDS ARROW
#define UC_MACRO_NAME_2B42 0x2B42 // ⭂ LEFTWARDS ARROW ABOVE REVERSE ALMOST EQUAL TO
#define UC_MACRO_NAME_2B43 0x2B43 // ⭃ RIGHTWARDS ARROW THROUGH GREATER-THAN
#define UC_MACRO_NAME_2B44 0x2B44 // ⭄ RIGHTWARDS ARROW THROUGH SUPERSET
#define UC_MACRO_NAME_2B45 0x2B45 // ⭅ LEFTWARDS QUADRUPLE ARROW
#define UC_MACRO_NAME_2B46 0x2B46 // ⭆ RIGHTWARDS QUADRUPLE ARROW
#define UC_MACRO_NAME_2B47 0x2B47 // ⭇ REVERSE TILDE OPERATOR ABOVE RIGHTWARDS ARROW
#define UC_MACRO_NAME_2B48 0x2B48 // ⭈ RIGHTWARDS ARROW ABOVE REVERSE ALMOST EQUAL TO
#define UC_MACRO_NAME_2B49 0x2B49 // ⭉ TILDE OPERATOR ABOVE LEFTWARDS ARROW
#define UC_MACRO_NAME_2B4A 0x2B4A // ⭊ LEFTWARDS ARROW ABOVE ALMOST EQUAL TO
#define UC_MACRO_NAME_2B4B 0x2B4B // ⭋ LEFTWARDS ARROW ABOVE REVERSE TILDE OPERATOR
#define UC_MACRO_NAME_2B4C 0x2B4C // ⭌ RIGHTWARDS ARROW ABOVE REVERSE TILDE OPERATOR
#define UC_MACRO_NAME_2B4D 0x2B4D // ⭍ DOWNWARDS TRIANGLE-HEADED ZIGZAG ARROW
#define UC_MACRO_NAME_2B4E 0x2B4E // ⭎ SHORT SLANTED NORTH ARROW
#define UC_MACRO_NAME_2B4F 0x2B4F // ⭏ SHORT BACKSLANTED SOUTH ARROW
#define UC_MACRO_NAME_2B50 0x2B50 // ⭐ WHITE MEDIUM STAR
#define UC_MACRO_NAME_2B51 0x2B51 // ⭑ BLACK SMALL STAR
#define UC_MACRO_NAME_2B52 0x2B52 // ⭒ WHITE SMALL STAR
#define UC_MACRO_NAME_2B53 0x2B53 // ⭓ BLACK RIGHT-POINTING PENTAGON
#define UC_MACRO_NAME_2B54 0x2B54 // ⭔ WHITE RIGHT-POINTING PENTAGON
#define UC_MACRO_NAME_2B55 0x2B55 // ⭕ HEAVY LARGE CIRCLE
#define UC_MACRO_NAME_2B56 0x2B56 // ⭖ HEAVY OVAL WITH OVAL INSIDE
#define UC_MACRO_NAME_2B57 0x2B57 // ⭗ HEAVY CIRCLE WITH CIRCLE INSIDE
#define UC_MACRO_NAME_2B58 0x2B58 // ⭘ HEAVY CIRCLE
#define UC_MACRO_NAME_2B59 0x2B59 // ⭙ HEAVY CIRCLED SALTIRE
#define UC_MACRO_NAME_2B5A 0x2B5A // ⭚ SLANTED NORTH ARROW WITH HOOKED HEAD
#define UC_MACRO_NAME_2B5B 0x2B5B // ⭛ BACKSLANTED SOUTH ARROW WITH HOOKED TAIL
#define UC_MACRO_NAME_2B5C 0x2B5C // ⭜ SLANTED NORTH ARROW WITH HORIZONTAL TAIL
#define UC_MACRO_NAME_2B5D 0x2B5D // ⭝ BACKSLANTED SOUTH ARROW WITH HORIZONTAL TAIL
#define UC_MACRO_NAME_2B5E 0x2B5E // ⭞ BENT ARROW POINTING DOWNWARDS THEN NORTH EAST
#define UC_MACRO_NAME_2B5F 0x2B5F // ⭟ SHORT BENT ARROW POINTING DOWNWARDS THEN NORTH EAST
#define UC_MACRO_NAME_2B60 0x2B60 // ⭠ LEFTWARDS TRIANGLE-HEADED ARROW
#define UC_MACRO_NAME_2B61 0x2B61 // ⭡ UPWARDS TRIANGLE-HEADED ARROW
#define UC_MACRO_NAME_2B62 0x2B62 // ⭢ RIGHTWARDS TRIANGLE-HEADED ARROW
#define UC_MACRO_NAME_2B63 0x2B63 // ⭣ DOWNWARDS TRIANGLE-HEADED ARROW
#define UC_MACRO_NAME_2B64 0x2B64 // ⭤ LEFT RIGHT TRIANGLE-HEADED ARROW
#define UC_MACRO_NAME_2B65 0x2B65 // ⭥ UP DOWN TRIANGLE-HEADED ARROW
#define UC_MACRO_NAME_2B66 0x2B66 // ⭦ NORTH WEST TRIANGLE-HEADED ARROW
#define UC_MACRO_NAME_2B67 0x2B67 // ⭧ NORTH EAST TRIANGLE-HEADED ARROW
#define UC_MACRO_NAME_2B68 0x2B68 // ⭨ SOUTH EAST TRIANGLE-HEADED ARROW
#define UC_MACRO_NAME_2B69 0x2B69 // ⭩ SOUTH WEST TRIANGLE-HEADED ARROW
#define UC_MACRO_NAME_2B6A 0x2B6A // ⭪ LEFTWARDS TRIANGLE-HEADED DASHED ARROW
#define UC_MACRO_NAME_2B6B 0x2B6B // ⭫ UPWARDS TRIANGLE-HEADED DASHED ARROW
#define UC_MACRO_NAME_2B6C 0x2B6C // ⭬ RIGHTWARDS TRIANGLE-HEADED DASHED ARROW
#define UC_MACRO_NAME_2B6D 0x2B6D // ⭭ DOWNWARDS TRIANGLE-HEADED DASHED ARROW
#define UC_MACRO_NAME_2B6E 0x2B6E // ⭮ CLOCKWISE TRIANGLE-HEADED OPEN CIRCLE ARROW
#define UC_MACRO_NAME_2B6F 0x2B6F // ⭯ ANTICLOCKWISE TRIANGLE-HEADED OPEN CIRCLE ARROW
#define UC_MACRO_NAME_2B70 0x2B70 // ⭰ LEFTWARDS TRIANGLE-HEADED ARROW TO BAR
#define UC_MACRO_NAME_2B71 0x2B71 // ⭱ UPWARDS TRIANGLE-HEADED ARROW TO BAR
#define UC_MACRO_NAME_2B72 0x2B72 // ⭲ RIGHTWARDS TRIANGLE-HEADED ARROW TO BAR
#define UC_MACRO_NAME_2B73 0x2B73 // ⭳ DOWNWARDS TRIANGLE-HEADED ARROW TO BAR
#define UC_MACRO_NAME_2B76 0x2B76 // ⭶ NORTH WEST TRIANGLE-HEADED ARROW TO BAR
#define UC_MACRO_NAME_2B77 0x2B77 // ⭷ NORTH EAST TRIANGLE-HEADED ARROW TO BAR
#define UC_MACRO_NAME_2B78 0x2B78 // ⭸ SOUTH EAST TRIANGLE-HEADED ARROW TO BAR
#define UC_MACRO_NAME_2B79 0x2B79 // ⭹ SOUTH WEST TRIANGLE-HEADED ARROW TO BAR
#define UC_MACRO_NAME_2B7A 0x2B7A // ⭺ LEFTWARDS TRIANGLE-HEADED ARROW WITH DOUBLE HORIZONTAL STROKE
#define UC_MACRO_NAME_2B7B 0x2B7B // ⭻ UPWARDS TRIANGLE-HEADED ARROW WITH DOUBLE HORIZONTAL STROKE
#define UC_MACRO_NAME_2B7C 0x2B7C // ⭼ RIGHTWARDS TRIANGLE-HEADED ARROW WITH DOUBLE HORIZONTAL STROKE
#define UC_MACRO_NAME_2B7D 0x2B7D // ⭽ DOWNWARDS TRIANGLE-HEADED ARROW WITH DOUBLE HORIZONTAL STROKE
#define UC_MACRO_NAME_2B7E 0x2B7E // ⭾ HORIZONTAL TAB KEY
#define UC_MACRO_NAME_2B7F 0x2B7F // ⭿ VERTICAL TAB KEY
#define UC_MACRO_NAME_2B80 0x2B80 // ⮀ LEFTWARDS TRIANGLE-HEADED ARROW OVER RIGHTWARDS TRIANGLE-HEADED ARROW
#define UC_MACRO_NAME_2B81 0x2B81 // ⮁ UPWARDS TRIANGLE-HEADED ARROW LEFTWARDS OF DOWNWARDS TRIANGLE-HEADED ARROW
#define UC_MACRO_NAME_2B82 0x2B82 // ⮂ RIGHTWARDS TRIANGLE-HEADED ARROW OVER LEFTWARDS TRIANGLE-HEADED ARROW
#define UC_MACRO_NAME_2B83 0x2B83 // ⮃ DOWNWARDS TRIANGLE-HEADED ARROW LEFTWARDS OF UPWARDS TRIANGLE-HEADED ARROW
#define UC_MACRO_NAME_2B84 0x2B84 // ⮄ LEFTWARDS TRIANGLE-HEADED PAIRED ARROWS
#define UC_MACRO_NAME_2B85 0x2B85 // ⮅ UPWARDS TRIANGLE-HEADED PAIRED ARROWS
#define UC_MACRO_NAME_2B86 0x2B86 // ⮆ RIGHTWARDS TRIANGLE-HEADED PAIRED ARROWS
#define UC_MACRO_NAME_2B87 0x2B87 // ⮇ DOWNWARDS TRIANGLE-HEADED PAIRED ARROWS
#define UC_MACRO_NAME_2B88 0x2B88 // ⮈ LEFTWARDS BLACK CIRCLED WHITE ARROW
#define UC_MACRO_NAME_2B89 0x2B89 // ⮉ UPWARDS BLACK CIRCLED WHITE ARROW
#define UC_MACRO_NAME_2B8A 0x2B8A // ⮊ RIGHTWARDS BLACK CIRCLED WHITE ARROW
#define UC_MACRO_NAME_2B8B 0x2B8B // ⮋ DOWNWARDS BLACK CIRCLED WHITE ARROW
#define UC_MACRO_NAME_2B8C 0x2B8C // ⮌ ANTICLOCKWISE TRIANGLE-HEADED RIGHT U-SHAPED ARROW
#define UC_MACRO_NAME_2B8D 0x2B8D // ⮍ ANTICLOCKWISE TRIANGLE-HEADED BOTTOM U-SHAPED ARROW
#define UC_MACRO_NAME_2B8E 0x2B8E // ⮎ ANTICLOCKWISE TRIANGLE-HEADED LEFT U-SHAPED ARROW
#define UC_MACRO_NAME_2B8F 0x2B8F // ⮏ ANTICLOCKWISE TRIANGLE-HEADED TOP U-SHAPED ARROW
#define UC_MACRO_NAME_2B90 0x2B90 // ⮐ RETURN LEFT
#define UC_MACRO_NAME_2B91 0x2B91 // ⮑ RETURN RIGHT
#define UC_MACRO_NAME_2B92 0x2B92 // ⮒ NEWLINE LEFT
#define UC_MACRO_NAME_2B93 0x2B93 // ⮓ NEWLINE RIGHT
#define UC_MACRO_NAME_2B94 0x2B94 // ⮔ FOUR CORNER ARROWS CIRCLING ANTICLOCKWISE
#define UC_MACRO_NAME_2B95 0x2B95 // ⮕ RIGHTWARDS BLACK ARROW
#define UC_MACRO_NAME_2B96 0x2B96 //  EQUALS SIGN WITH INFINITY ABOVE
#define UC_MACRO_NAME_2B97 0x2B97 // ⮗ SYMBOL FOR TYPE A ELECTRONICS
#define UC_MACRO_NAME_2B98 0x2B98 // ⮘ THREE-D TOP-LIGHTED LEFTWARDS EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_2B99 0x2B99 // ⮙ THREE-D RIGHT-LIGHTED UPWARDS EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_2B9A 0x2B9A // ⮚ THREE-D TOP-LIGHTED RIGHTWARDS EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_2B9B 0x2B9B // ⮛ THREE-D LEFT-LIGHTED DOWNWARDS EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_2B9C 0x2B9C // ⮜ BLACK LEFTWARDS EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_2B9D 0x2B9D // ⮝ BLACK UPWARDS EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_2B9E 0x2B9E // ⮞ BLACK RIGHTWARDS EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_2B9F 0x2B9F // ⮟ BLACK DOWNWARDS EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_2BA0 0x2BA0 // ⮠ DOWNWARDS TRIANGLE-HEADED ARROW WITH LONG TIP LEFTWARDS
#define UC_MACRO_NAME_2BA1 0x2BA1 // ⮡ DOWNWARDS TRIANGLE-HEADED ARROW WITH LONG TIP RIGHTWARDS
#define UC_MACRO_NAME_2BA2 0x2BA2 // ⮢ UPWARDS TRIANGLE-HEADED ARROW WITH LONG TIP LEFTWARDS
#define UC_MACRO_NAME_2BA3 0x2BA3 // ⮣ UPWARDS TRIANGLE-HEADED ARROW WITH LONG TIP RIGHTWARDS
#define UC_MACRO_NAME_2BA4 0x2BA4 // ⮤ LEFTWARDS TRIANGLE-HEADED ARROW WITH LONG TIP UPWARDS
#define UC_MACRO_NAME_2BA5 0x2BA5 // ⮥ RIGHTWARDS TRIANGLE-HEADED ARROW WITH LONG TIP UPWARDS
#define UC_MACRO_NAME_2BA6 0x2BA6 // ⮦ LEFTWARDS TRIANGLE-HEADED ARROW WITH LONG TIP DOWNWARDS
#define UC_MACRO_NAME_2BA7 0x2BA7 // ⮧ RIGHTWARDS TRIANGLE-HEADED ARROW WITH LONG TIP DOWNWARDS
#define UC_MACRO_NAME_2BA8 0x2BA8 // ⮨ BLACK CURVED DOWNWARDS AND LEFTWARDS ARROW
#define UC_MACRO_NAME_2BA9 0x2BA9 // ⮩ BLACK CURVED DOWNWARDS AND RIGHTWARDS ARROW
#define UC_MACRO_NAME_2BAA 0x2BAA // ⮪ BLACK CURVED UPWARDS AND LEFTWARDS ARROW
#define UC_MACRO_NAME_2BAB 0x2BAB // ⮫ BLACK CURVED UPWARDS AND RIGHTWARDS ARROW
#define UC_MACRO_NAME_2BAC 0x2BAC // ⮬ BLACK CURVED LEFTWARDS AND UPWARDS ARROW
#define UC_MACRO_NAME_2BAD 0x2BAD // ⮭ BLACK CURVED RIGHTWARDS AND UPWARDS ARROW
#define UC_MACRO_NAME_2BAE 0x2BAE // ⮮ BLACK CURVED LEFTWARDS AND DOWNWARDS ARROW
#define UC_MACRO_NAME_2BAF 0x2BAF // ⮯ BLACK CURVED RIGHTWARDS AND DOWNWARDS ARROW
#define UC_MACRO_NAME_2BB0 0x2BB0 // ⮰ RIBBON ARROW DOWN LEFT
#define UC_MACRO_NAME_2BB1 0x2BB1 // ⮱ RIBBON ARROW DOWN RIGHT
#define UC_MACRO_NAME_2BB2 0x2BB2 // ⮲ RIBBON ARROW UP LEFT
#define UC_MACRO_NAME_2BB3 0x2BB3 // ⮳ RIBBON ARROW UP RIGHT
#define UC_MACRO_NAME_2BB4 0x2BB4 // ⮴ RIBBON ARROW LEFT UP
#define UC_MACRO_NAME_2BB5 0x2BB5 // ⮵ RIBBON ARROW RIGHT UP
#define UC_MACRO_NAME_2BB6 0x2BB6 // ⮶ RIBBON ARROW LEFT DOWN
#define UC_MACRO_NAME_2BB7 0x2BB7 // ⮷ RIBBON ARROW RIGHT DOWN
#define UC_MACRO_NAME_2BB8 0x2BB8 // ⮸ UPWARDS WHITE ARROW FROM BAR WITH HORIZONTAL BAR
#define UC_MACRO_NAME_2BB9 0x2BB9 // ⮹ UP ARROWHEAD IN A RECTANGLE BOX
#define UC_MACRO_NAME_2BBA 0x2BBA // ⮺ OVERLAPPING WHITE SQUARES
#define UC_MACRO_NAME_2BBB 0x2BBB // ⮻ OVERLAPPING WHITE AND BLACK SQUARES
#define UC_MACRO_NAME_2BBC 0x2BBC // ⮼ OVERLAPPING BLACK SQUARES
#define UC_MACRO_NAME_2BBD 0x2BBD // ⮽ BALLOT BOX WITH LIGHT X
#define UC_MACRO_NAME_2BBE 0x2BBE // ⮾ CIRCLED X
#define UC_MACRO_NAME_2BBF 0x2BBF // ⮿ CIRCLED BOLD X
#define UC_MACRO_NAME_2BC0 0x2BC0 // ⯀ BLACK SQUARE CENTRED
#define UC_MACRO_NAME_2BC1 0x2BC1 // ⯁ BLACK DIAMOND CENTRED
#define UC_MACRO_NAME_2BC2 0x2BC2 // ⯂ TURNED BLACK PENTAGON
#define UC_MACRO_NAME_2BC3 0x2BC3 // ⯃ HORIZONTAL BLACK OCTAGON
#define UC_MACRO_NAME_2BC4 0x2BC4 // ⯄ BLACK OCTAGON
#define UC_MACRO_NAME_2BC5 0x2BC5 // ⯅ BLACK MEDIUM UP-POINTING TRIANGLE CENTRED
#define UC_MACRO_NAME_2BC6 0x2BC6 // ⯆ BLACK MEDIUM DOWN-POINTING TRIANGLE CENTRED
#define UC_MACRO_NAME_2BC7 0x2BC7 // ⯇ BLACK MEDIUM LEFT-POINTING TRIANGLE CENTRED
#define UC_MACRO_NAME_2BC8 0x2BC8 // ⯈ BLACK MEDIUM RIGHT-POINTING TRIANGLE CENTRED
#define UC_MACRO_NAME_2BC9 0x2BC9 // ⯉ NEPTUNE FORM TWO
#define UC_MACRO_NAME_2BCA 0x2BCA // ⯊ TOP HALF BLACK CIRCLE
#define UC_MACRO_NAME_2BCB 0x2BCB // ⯋ BOTTOM HALF BLACK CIRCLE
#define UC_MACRO_NAME_2BCC 0x2BCC // ⯌ LIGHT FOUR POINTED BLACK CUSP
#define UC_MACRO_NAME_2BCD 0x2BCD // ⯍ ROTATED LIGHT FOUR POINTED BLACK CUSP
#define UC_MACRO_NAME_2BCE 0x2BCE // ⯎ WHITE FOUR POINTED CUSP
#define UC_MACRO_NAME_2BCF 0x2BCF // ⯏ ROTATED WHITE FOUR POINTED CUSP
#define UC_MACRO_NAME_2BD0 0x2BD0 // ⯐ SQUARE POSITION INDICATOR
#define UC_MACRO_NAME_2BD1 0x2BD1 // ⯑ UNCERTAINTY SIGN
#define UC_MACRO_NAME_2BD2 0x2BD2 // ⯒ GROUP MARK
#define UC_MACRO_NAME_2BD3 0x2BD3 // ⯓ PLUTO FORM TWO
#define UC_MACRO_NAME_2BD4 0x2BD4 // ⯔ PLUTO FORM THREE
#define UC_MACRO_NAME_2BD5 0x2BD5 // ⯕ PLUTO FORM FOUR
#define UC_MACRO_NAME_2BD6 0x2BD6 // ⯖ PLUTO FORM FIVE
#define UC_MACRO_NAME_2BD7 0x2BD7 // ⯗ TRANSPLUTO
#define UC_MACRO_NAME_2BD8 0x2BD8 // ⯘ PROSERPINA
#define UC_MACRO_NAME_2BD9 0x2BD9 // ⯙ ASTRAEA
#define UC_MACRO_NAME_2BDA 0x2BDA // ⯚ HYGIEA
#define UC_MACRO_NAME_2BDB 0x2BDB // ⯛ PHOLUS
#define UC_MACRO_NAME_2BDC 0x2BDC // ⯜ NESSUS
#define UC_MACRO_NAME_2BDD 0x2BDD // ⯝ WHITE MOON SELENA
#define UC_MACRO_NAME_2BDE 0x2BDE // ⯞ BLACK DIAMOND ON CROSS
#define UC_MACRO_NAME_2BDF 0x2BDF // ⯟ TRUE LIGHT MOON ARTA
#define UC_MACRO_NAME_2BE0 0x2BE0 // ⯠ CUPIDO
#define UC_MACRO_NAME_2BE1 0x2BE1 // ⯡ HADES
#define UC_MACRO_NAME_2BE2 0x2BE2 // ⯢ ZEUS
#define UC_MACRO_NAME_2BE3 0x2BE3 // ⯣ KRONOS
#define UC_MACRO_NAME_2BE4 0x2BE4 // ⯤ APOLLON
#define UC_MACRO_NAME_2BE5 0x2BE5 // ⯥ ADMETOS
#define UC_MACRO_NAME_2BE6 0x2BE6 // ⯦ VULCANUS
#define UC_MACRO_NAME_2BE7 0x2BE7 // ⯧ POSEIDON
#define UC_MACRO_NAME_2BE8 0x2BE8 // ⯨ LEFT HALF BLACK STAR
#define UC_MACRO_NAME_2BE9 0x2BE9 // ⯩ RIGHT HALF BLACK STAR
#define UC_MACRO_NAME_2BEA 0x2BEA // ⯪ STAR WITH LEFT HALF BLACK
#define UC_MACRO_NAME_2BEB 0x2BEB // ⯫ STAR WITH RIGHT HALF BLACK
#define UC_MACRO_NAME_2BEC 0x2BEC // ⯬ LEFTWARDS TWO-HEADED ARROW WITH TRIANGLE ARROWHEADS
#define UC_MACRO_NAME_2BED 0x2BED // ⯭ UPWARDS TWO-HEADED ARROW WITH TRIANGLE ARROWHEADS
#define UC_MACRO_NAME_2BEE 0x2BEE // ⯮ RIGHTWARDS TWO-HEADED ARROW WITH TRIANGLE ARROWHEADS
#define UC_MACRO_NAME_2BEF 0x2BEF // ⯯ DOWNWARDS TWO-HEADED ARROW WITH TRIANGLE ARROWHEADS
#define UC_MACRO_NAME_2BF0 0x2BF0 // ⯰ ERIS FORM ONE
#define UC_MACRO_NAME_2BF1 0x2BF1 // ⯱ ERIS FORM TWO
#define UC_MACRO_NAME_2BF2 0x2BF2 // ⯲ SEDNA
#define UC_MACRO_NAME_2BF3 0x2BF3 // ⯳ RUSSIAN ASTROLOGICAL SYMBOL VIGINTILE
#define UC_MACRO_NAME_2BF4 0x2BF4 // ⯴ RUSSIAN ASTROLOGICAL SYMBOL NOVILE
#define UC_MACRO_NAME_2BF5 0x2BF5 // ⯵ RUSSIAN ASTROLOGICAL SYMBOL QUINTILE
#define UC_MACRO_NAME_2BF6 0x2BF6 // ⯶ RUSSIAN ASTROLOGICAL SYMBOL BINOVILE
#define UC_MACRO_NAME_2BF7 0x2BF7 // ⯷ RUSSIAN ASTROLOGICAL SYMBOL SENTAGON
#define UC_MACRO_NAME_2BF8 0x2BF8 // ⯸ RUSSIAN ASTROLOGICAL SYMBOL TREDECILE
#define UC_MACRO_NAME_2BF9 0x2BF9 // ⯹ EQUALS SIGN WITH INFINITY BELOW
#define UC_MACRO_NAME_2BFA 0x2BFA // ⯺ UNITED SYMBOL
#define UC_MACRO_NAME_2BFB 0x2BFB // ⯻ SEPARATED SYMBOL
#define UC_MACRO_NAME_2BFC 0x2BFC // ⯼ DOUBLED SYMBOL
#define UC_MACRO_NAME_2BFD 0x2BFD // ⯽ PASSED SYMBOL
#define UC_MACRO_NAME_2BFE 0x2BFE // ⯾ REVERSED RIGHT ANGLE
#define UC_MACRO_NAME_2BFF 0x2BFF // ⯿ HELLSCHREIBER PAUSE SYMBOL


#endif // UC_H_MISCELLANEOUS_SYMBOLS_AND_ARROWS
