/*
 * Unicode Block: Miscellaneous Mathematical Symbols-A
 * Range: U+27C0..U+27EF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A
#define UC_H_MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A

#define UC_MACRO_NAME_27C0 0x27C0 // ⟀ THREE DIMENSIONAL ANGLE
#define UC_MACRO_NAME_27C1 0x27C1 // ⟁ WHITE TRIANGLE CONTAINING SMALL WHITE TRIANGLE
#define UC_MACRO_NAME_27C2 0x27C2 // ⟂ PERPENDICULAR
#define UC_MACRO_NAME_27C3 0x27C3 // ⟃ OPEN SUBSET
#define UC_MACRO_NAME_27C4 0x27C4 // ⟄ OPEN SUPERSET
#define UC_MACRO_NAME_27C5 0x27C5 // ⟅ LEFT S-SHAPED BAG DELIMITER
#define UC_MACRO_NAME_27C6 0x27C6 // ⟆ RIGHT S-SHAPED BAG DELIMITER
#define UC_MACRO_NAME_27C7 0x27C7 // ⟇ OR WITH DOT INSIDE
#define UC_MACRO_NAME_27C8 0x27C8 // ⟈ REVERSE SOLIDUS PRECEDING SUBSET
#define UC_MACRO_NAME_27C9 0x27C9 // ⟉ SUPERSET PRECEDING SOLIDUS
#define UC_MACRO_NAME_27CA 0x27CA // ⟊ VERTICAL BAR WITH HORIZONTAL STROKE
#define UC_MACRO_NAME_27CB 0x27CB // ⟋ MATHEMATICAL RISING DIAGONAL
#define UC_MACRO_NAME_27CC 0x27CC // ⟌ LONG DIVISION
#define UC_MACRO_NAME_27CD 0x27CD // ⟍ MATHEMATICAL FALLING DIAGONAL
#define UC_MACRO_NAME_27CE 0x27CE // ⟎ SQUARED LOGICAL AND
#define UC_MACRO_NAME_27CF 0x27CF // ⟏ SQUARED LOGICAL OR
#define UC_MACRO_NAME_27D0 0x27D0 // ⟐ WHITE DIAMOND WITH CENTRED DOT
#define UC_MACRO_NAME_27D1 0x27D1 // ⟑ AND WITH DOT
#define UC_MACRO_NAME_27D2 0x27D2 // ⟒ ELEMENT OF OPENING UPWARDS
#define UC_MACRO_NAME_27D3 0x27D3 // ⟓ LOWER RIGHT CORNER WITH DOT
#define UC_MACRO_NAME_27D4 0x27D4 // ⟔ UPPER LEFT CORNER WITH DOT
#define UC_MACRO_NAME_27D5 0x27D5 // ⟕ LEFT OUTER JOIN
#define UC_MACRO_NAME_27D6 0x27D6 // ⟖ RIGHT OUTER JOIN
#define UC_MACRO_NAME_27D7 0x27D7 // ⟗ FULL OUTER JOIN
#define UC_MACRO_NAME_27D8 0x27D8 // ⟘ LARGE UP TACK
#define UC_MACRO_NAME_27D9 0x27D9 // ⟙ LARGE DOWN TACK
#define UC_MACRO_NAME_27DA 0x27DA // ⟚ LEFT AND RIGHT DOUBLE TURNSTILE
#define UC_MACRO_NAME_27DB 0x27DB // ⟛ LEFT AND RIGHT TACK
#define UC_MACRO_NAME_27DC 0x27DC // ⟜ LEFT MULTIMAP
#define UC_MACRO_NAME_27DD 0x27DD // ⟝ LONG RIGHT TACK
#define UC_MACRO_NAME_27DE 0x27DE // ⟞ LONG LEFT TACK
#define UC_MACRO_NAME_27DF 0x27DF // ⟟ UP TACK WITH CIRCLE ABOVE
#define UC_MACRO_NAME_27E0 0x27E0 // ⟠ LOZENGE DIVIDED BY HORIZONTAL RULE
#define UC_MACRO_NAME_27E1 0x27E1 // ⟡ WHITE CONCAVE-SIDED DIAMOND
#define UC_MACRO_NAME_27E2 0x27E2 // ⟢ WHITE CONCAVE-SIDED DIAMOND WITH LEFTWARDS TICK
#define UC_MACRO_NAME_27E3 0x27E3 // ⟣ WHITE CONCAVE-SIDED DIAMOND WITH RIGHTWARDS TICK
#define UC_MACRO_NAME_27E4 0x27E4 // ⟤ WHITE SQUARE WITH LEFTWARDS TICK
#define UC_MACRO_NAME_27E5 0x27E5 // ⟥ WHITE SQUARE WITH RIGHTWARDS TICK
#define UC_MACRO_NAME_27E6 0x27E6 // ⟦ MATHEMATICAL LEFT WHITE SQUARE BRACKET
#define UC_MACRO_NAME_27E7 0x27E7 // ⟧ MATHEMATICAL RIGHT WHITE SQUARE BRACKET
#define UC_MACRO_NAME_27E8 0x27E8 // ⟨ MATHEMATICAL LEFT ANGLE BRACKET
#define UC_MACRO_NAME_27E9 0x27E9 // ⟩ MATHEMATICAL RIGHT ANGLE BRACKET
#define UC_MACRO_NAME_27EA 0x27EA // ⟪ MATHEMATICAL LEFT DOUBLE ANGLE BRACKET
#define UC_MACRO_NAME_27EB 0x27EB // ⟫ MATHEMATICAL RIGHT DOUBLE ANGLE BRACKET
#define UC_MACRO_NAME_27EC 0x27EC // ⟬ MATHEMATICAL LEFT WHITE TORTOISE SHELL BRACKET
#define UC_MACRO_NAME_27ED 0x27ED // ⟭ MATHEMATICAL RIGHT WHITE TORTOISE SHELL BRACKET
#define UC_MACRO_NAME_27EE 0x27EE // ⟮ MATHEMATICAL LEFT FLATTENED PARENTHESIS
#define UC_MACRO_NAME_27EF 0x27EF // ⟯ MATHEMATICAL RIGHT FLATTENED PARENTHESIS


#endif // UC_H_MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A
