/*
 * Unicode Block: Myanmar Extended-B
 * Range: U+A9E0..U+A9FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_MYANMAR_EXTENDED_B
#define UC_H_MYANMAR_EXTENDED_B

#define UC_MACRO_NAME_A9E0 0xA9E0 // ꧠ MYANMAR LETTER SHAN GHA
#define UC_MACRO_NAME_A9E1 0xA9E1 // ꧡ MYANMAR LETTER SHAN CHA
#define UC_MACRO_NAME_A9E2 0xA9E2 // ꧢ MYANMAR LETTER SHAN JHA
#define UC_MACRO_NAME_A9E3 0xA9E3 // ꧣ MYANMAR LETTER SHAN NNA
#define UC_MACRO_NAME_A9E4 0xA9E4 // ꧤ MYANMAR LETTER SHAN BHA
#define UC_MACRO_NAME_A9E5 0xA9E5 // ꧥ MYANMAR SIGN SHAN SAW
#define UC_MACRO_NAME_A9E6 0xA9E6 // ꧦ MYANMAR MODIFIER LETTER SHAN REDUPLICATION
#define UC_MACRO_NAME_A9E7 0xA9E7 // ꧧ MYANMAR LETTER TAI LAING NYA
#define UC_MACRO_NAME_A9E8 0xA9E8 // ꧨ MYANMAR LETTER TAI LAING FA
#define UC_MACRO_NAME_A9E9 0xA9E9 // ꧩ MYANMAR LETTER TAI LAING GA
#define UC_MACRO_NAME_A9EA 0xA9EA // ꧪ MYANMAR LETTER TAI LAING GHA
#define UC_MACRO_NAME_A9EB 0xA9EB // ꧫ MYANMAR LETTER TAI LAING JA
#define UC_MACRO_NAME_A9EC 0xA9EC // ꧬ MYANMAR LETTER TAI LAING JHA
#define UC_MACRO_NAME_A9ED 0xA9ED // ꧭ MYANMAR LETTER TAI LAING DDA
#define UC_MACRO_NAME_A9EE 0xA9EE // ꧮ MYANMAR LETTER TAI LAING DDHA
#define UC_MACRO_NAME_A9EF 0xA9EF // ꧯ MYANMAR LETTER TAI LAING NNA
#define UC_MACRO_NAME_A9F0 0xA9F0 // ꧰ MYANMAR TAI LAING DIGIT ZERO
#define UC_MACRO_NAME_A9F1 0xA9F1 // ꧱ MYANMAR TAI LAING DIGIT ONE
#define UC_MACRO_NAME_A9F2 0xA9F2 // ꧲ MYANMAR TAI LAING DIGIT TWO
#define UC_MACRO_NAME_A9F3 0xA9F3 // ꧳ MYANMAR TAI LAING DIGIT THREE
#define UC_MACRO_NAME_A9F4 0xA9F4 // ꧴ MYANMAR TAI LAING DIGIT FOUR
#define UC_MACRO_NAME_A9F5 0xA9F5 // ꧵ MYANMAR TAI LAING DIGIT FIVE
#define UC_MACRO_NAME_A9F6 0xA9F6 // ꧶ MYANMAR TAI LAING DIGIT SIX
#define UC_MACRO_NAME_A9F7 0xA9F7 // ꧷ MYANMAR TAI LAING DIGIT SEVEN
#define UC_MACRO_NAME_A9F8 0xA9F8 // ꧸ MYANMAR TAI LAING DIGIT EIGHT
#define UC_MACRO_NAME_A9F9 0xA9F9 // ꧹ MYANMAR TAI LAING DIGIT NINE
#define UC_MACRO_NAME_A9FA 0xA9FA // ꧺ MYANMAR LETTER TAI LAING LLA
#define UC_MACRO_NAME_A9FB 0xA9FB // ꧻ MYANMAR LETTER TAI LAING DA
#define UC_MACRO_NAME_A9FC 0xA9FC // ꧼ MYANMAR LETTER TAI LAING DHA
#define UC_MACRO_NAME_A9FD 0xA9FD // ꧽ MYANMAR LETTER TAI LAING BA
#define UC_MACRO_NAME_A9FE 0xA9FE // ꧾ MYANMAR LETTER TAI LAING BHA


#endif // UC_H_MYANMAR_EXTENDED_B
