/*
 * Unicode Block: Malayalam
 * Range: U+0D00..U+0D7F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_MALAYALAM
#define UC_H_MALAYALAM

#define UC_MACRO_NAME_D00 0x0D00 // ഀ MALAYALAM SIGN COMBINING ANUSVARA ABOVE
#define UC_MACRO_NAME_D01 0x0D01 // ഁ MALAYALAM SIGN CANDRABINDU
#define UC_MACRO_NAME_D02 0x0D02 // ം MALAYALAM SIGN ANUSVARA
#define UC_MACRO_NAME_D03 0x0D03 // ഃ MALAYALAM SIGN VISARGA
#define UC_MACRO_NAME_D04 0x0D04 // ഄ MALAYALAM LETTER VEDIC ANUSVARA
#define UC_MACRO_NAME_D05 0x0D05 // അ MALAYALAM LETTER A
#define UC_MACRO_NAME_D06 0x0D06 // ആ MALAYALAM LETTER AA
#define UC_MACRO_NAME_D07 0x0D07 // ഇ MALAYALAM LETTER I
#define UC_MACRO_NAME_D08 0x0D08 // ഈ MALAYALAM LETTER II
#define UC_MACRO_NAME_D09 0x0D09 // ഉ MALAYALAM LETTER U
#define UC_MACRO_NAME_D0A 0x0D0A // ഊ MALAYALAM LETTER UU
#define UC_MACRO_NAME_D0B 0x0D0B // ഋ MALAYALAM LETTER VOCALIC R
#define UC_MACRO_NAME_D0C 0x0D0C // ഌ MALAYALAM LETTER VOCALIC L
#define UC_MACRO_NAME_D0E 0x0D0E // എ MALAYALAM LETTER E
#define UC_MACRO_NAME_D0F 0x0D0F // ഏ MALAYALAM LETTER EE
#define UC_MACRO_NAME_D10 0x0D10 // ഐ MALAYALAM LETTER AI
#define UC_MACRO_NAME_D12 0x0D12 // ഒ MALAYALAM LETTER O
#define UC_MACRO_NAME_D13 0x0D13 // ഓ MALAYALAM LETTER OO
#define UC_MACRO_NAME_D14 0x0D14 // ഔ MALAYALAM LETTER AU
#define UC_MACRO_NAME_D15 0x0D15 // ക MALAYALAM LETTER KA
#define UC_MACRO_NAME_D16 0x0D16 // ഖ MALAYALAM LETTER KHA
#define UC_MACRO_NAME_D17 0x0D17 // ഗ MALAYALAM LETTER GA
#define UC_MACRO_NAME_D18 0x0D18 // ഘ MALAYALAM LETTER GHA
#define UC_MACRO_NAME_D19 0x0D19 // ങ MALAYALAM LETTER NGA
#define UC_MACRO_NAME_D1A 0x0D1A // ച MALAYALAM LETTER CA
#define UC_MACRO_NAME_D1B 0x0D1B // ഛ MALAYALAM LETTER CHA
#define UC_MACRO_NAME_D1C 0x0D1C // ജ MALAYALAM LETTER JA
#define UC_MACRO_NAME_D1D 0x0D1D // ഝ MALAYALAM LETTER JHA
#define UC_MACRO_NAME_D1E 0x0D1E // ഞ MALAYALAM LETTER NYA
#define UC_MACRO_NAME_D1F 0x0D1F // ട MALAYALAM LETTER TTA
#define UC_MACRO_NAME_D20 0x0D20 // ഠ MALAYALAM LETTER TTHA
#define UC_MACRO_NAME_D21 0x0D21 // ഡ MALAYALAM LETTER DDA
#define UC_MACRO_NAME_D22 0x0D22 // ഢ MALAYALAM LETTER DDHA
#define UC_MACRO_NAME_D23 0x0D23 // ണ MALAYALAM LETTER NNA
#define UC_MACRO_NAME_D24 0x0D24 // ത MALAYALAM LETTER TA
#define UC_MACRO_NAME_D25 0x0D25 // ഥ MALAYALAM LETTER THA
#define UC_MACRO_NAME_D26 0x0D26 // ദ MALAYALAM LETTER DA
#define UC_MACRO_NAME_D27 0x0D27 // ധ MALAYALAM LETTER DHA
#define UC_MACRO_NAME_D28 0x0D28 // ന MALAYALAM LETTER NA
#define UC_MACRO_NAME_D29 0x0D29 // ഩ MALAYALAM LETTER NNNA
#define UC_MACRO_NAME_D2A 0x0D2A // പ MALAYALAM LETTER PA
#define UC_MACRO_NAME_D2B 0x0D2B // ഫ MALAYALAM LETTER PHA
#define UC_MACRO_NAME_D2C 0x0D2C // ബ MALAYALAM LETTER BA
#define UC_MACRO_NAME_D2D 0x0D2D // ഭ MALAYALAM LETTER BHA
#define UC_MACRO_NAME_D2E 0x0D2E // മ MALAYALAM LETTER MA
#define UC_MACRO_NAME_D2F 0x0D2F // യ MALAYALAM LETTER YA
#define UC_MACRO_NAME_D30 0x0D30 // ര MALAYALAM LETTER RA
#define UC_MACRO_NAME_D31 0x0D31 // റ MALAYALAM LETTER RRA
#define UC_MACRO_NAME_D32 0x0D32 // ല MALAYALAM LETTER LA
#define UC_MACRO_NAME_D33 0x0D33 // ള MALAYALAM LETTER LLA
#define UC_MACRO_NAME_D34 0x0D34 // ഴ MALAYALAM LETTER LLLA
#define UC_MACRO_NAME_D35 0x0D35 // വ MALAYALAM LETTER VA
#define UC_MACRO_NAME_D36 0x0D36 // ശ MALAYALAM LETTER SHA
#define UC_MACRO_NAME_D37 0x0D37 // ഷ MALAYALAM LETTER SSA
#define UC_MACRO_NAME_D38 0x0D38 // സ MALAYALAM LETTER SA
#define UC_MACRO_NAME_D39 0x0D39 // ഹ MALAYALAM LETTER HA
#define UC_MACRO_NAME_D3A 0x0D3A // ഺ MALAYALAM LETTER TTTA
#define UC_MACRO_NAME_D3B 0x0D3B // ഻ MALAYALAM SIGN VERTICAL BAR VIRAMA
#define UC_MACRO_NAME_D3C 0x0D3C // ഼ MALAYALAM SIGN CIRCULAR VIRAMA
#define UC_MACRO_NAME_D3D 0x0D3D // ഽ MALAYALAM SIGN AVAGRAHA
#define UC_MACRO_NAME_D3E 0x0D3E // ാ MALAYALAM VOWEL SIGN AA
#define UC_MACRO_NAME_D3F 0x0D3F // ി MALAYALAM VOWEL SIGN I
#define UC_MACRO_NAME_D40 0x0D40 // ീ MALAYALAM VOWEL SIGN II
#define UC_MACRO_NAME_D41 0x0D41 // ു MALAYALAM VOWEL SIGN U
#define UC_MACRO_NAME_D42 0x0D42 // ൂ MALAYALAM VOWEL SIGN UU
#define UC_MACRO_NAME_D43 0x0D43 // ൃ MALAYALAM VOWEL SIGN VOCALIC R
#define UC_MACRO_NAME_D44 0x0D44 // ൄ MALAYALAM VOWEL SIGN VOCALIC RR
#define UC_MACRO_NAME_D46 0x0D46 // െ MALAYALAM VOWEL SIGN E
#define UC_MACRO_NAME_D47 0x0D47 // േ MALAYALAM VOWEL SIGN EE
#define UC_MACRO_NAME_D48 0x0D48 // ൈ MALAYALAM VOWEL SIGN AI
#define UC_MACRO_NAME_D4A 0x0D4A // ൊ MALAYALAM VOWEL SIGN O
#define UC_MACRO_NAME_D4B 0x0D4B // ോ MALAYALAM VOWEL SIGN OO
#define UC_MACRO_NAME_D4C 0x0D4C // ൌ MALAYALAM VOWEL SIGN AU
#define UC_MACRO_NAME_D4D 0x0D4D // ് MALAYALAM SIGN VIRAMA
#define UC_MACRO_NAME_D4E 0x0D4E // ൎ MALAYALAM LETTER DOT REPH
#define UC_MACRO_NAME_D4F 0x0D4F // ൏ MALAYALAM SIGN PARA
#define UC_MACRO_NAME_D54 0x0D54 // ൔ MALAYALAM LETTER CHILLU M
#define UC_MACRO_NAME_D55 0x0D55 // ൕ MALAYALAM LETTER CHILLU Y
#define UC_MACRO_NAME_D56 0x0D56 // ൖ MALAYALAM LETTER CHILLU LLL
#define UC_MACRO_NAME_D57 0x0D57 // ൗ MALAYALAM AU LENGTH MARK
#define UC_MACRO_NAME_D58 0x0D58 // ൘ MALAYALAM FRACTION ONE ONE-HUNDRED-AND-SIXTIETH
#define UC_MACRO_NAME_D59 0x0D59 // ൙ MALAYALAM FRACTION ONE FORTIETH
#define UC_MACRO_NAME_D5A 0x0D5A // ൚ MALAYALAM FRACTION THREE EIGHTIETHS
#define UC_MACRO_NAME_D5B 0x0D5B // ൛ MALAYALAM FRACTION ONE TWENTIETH
#define UC_MACRO_NAME_D5C 0x0D5C // ൜ MALAYALAM FRACTION ONE TENTH
#define UC_MACRO_NAME_D5D 0x0D5D // ൝ MALAYALAM FRACTION THREE TWENTIETHS
#define UC_MACRO_NAME_D5E 0x0D5E // ൞ MALAYALAM FRACTION ONE FIFTH
#define UC_MACRO_NAME_D5F 0x0D5F // ൟ MALAYALAM LETTER ARCHAIC II
#define UC_MACRO_NAME_D60 0x0D60 // ൠ MALAYALAM LETTER VOCALIC RR
#define UC_MACRO_NAME_D61 0x0D61 // ൡ MALAYALAM LETTER VOCALIC LL
#define UC_MACRO_NAME_D62 0x0D62 // ൢ MALAYALAM VOWEL SIGN VOCALIC L
#define UC_MACRO_NAME_D63 0x0D63 // ൣ MALAYALAM VOWEL SIGN VOCALIC LL
#define UC_MACRO_NAME_D66 0x0D66 // ൦ MALAYALAM DIGIT ZERO
#define UC_MACRO_NAME_D67 0x0D67 // ൧ MALAYALAM DIGIT ONE
#define UC_MACRO_NAME_D68 0x0D68 // ൨ MALAYALAM DIGIT TWO
#define UC_MACRO_NAME_D69 0x0D69 // ൩ MALAYALAM DIGIT THREE
#define UC_MACRO_NAME_D6A 0x0D6A // ൪ MALAYALAM DIGIT FOUR
#define UC_MACRO_NAME_D6B 0x0D6B // ൫ MALAYALAM DIGIT FIVE
#define UC_MACRO_NAME_D6C 0x0D6C // ൬ MALAYALAM DIGIT SIX
#define UC_MACRO_NAME_D6D 0x0D6D // ൭ MALAYALAM DIGIT SEVEN
#define UC_MACRO_NAME_D6E 0x0D6E // ൮ MALAYALAM DIGIT EIGHT
#define UC_MACRO_NAME_D6F 0x0D6F // ൯ MALAYALAM DIGIT NINE
#define UC_MACRO_NAME_D70 0x0D70 // ൰ MALAYALAM NUMBER TEN
#define UC_MACRO_NAME_D71 0x0D71 // ൱ MALAYALAM NUMBER ONE HUNDRED
#define UC_MACRO_NAME_D72 0x0D72 // ൲ MALAYALAM NUMBER ONE THOUSAND
#define UC_MACRO_NAME_D73 0x0D73 // ൳ MALAYALAM FRACTION ONE QUARTER
#define UC_MACRO_NAME_D74 0x0D74 // ൴ MALAYALAM FRACTION ONE HALF
#define UC_MACRO_NAME_D75 0x0D75 // ൵ MALAYALAM FRACTION THREE QUARTERS
#define UC_MACRO_NAME_D76 0x0D76 // ൶ MALAYALAM FRACTION ONE SIXTEENTH
#define UC_MACRO_NAME_D77 0x0D77 // ൷ MALAYALAM FRACTION ONE EIGHTH
#define UC_MACRO_NAME_D78 0x0D78 // ൸ MALAYALAM FRACTION THREE SIXTEENTHS
#define UC_MACRO_NAME_D79 0x0D79 // ൹ MALAYALAM DATE MARK
#define UC_MACRO_NAME_D7A 0x0D7A // ൺ MALAYALAM LETTER CHILLU NN
#define UC_MACRO_NAME_D7B 0x0D7B // ൻ MALAYALAM LETTER CHILLU N
#define UC_MACRO_NAME_D7C 0x0D7C // ർ MALAYALAM LETTER CHILLU RR
#define UC_MACRO_NAME_D7D 0x0D7D // ൽ MALAYALAM LETTER CHILLU L
#define UC_MACRO_NAME_D7E 0x0D7E // ൾ MALAYALAM LETTER CHILLU LL
#define UC_MACRO_NAME_D7F 0x0D7F // ൿ MALAYALAM LETTER CHILLU K


#endif // UC_H_MALAYALAM
