/*
 * Unicode Block: Myanmar Extended-A
 * Range: U+AA60..U+AA7F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_MYANMAR_EXTENDED_A
#define UC_H_MYANMAR_EXTENDED_A

#define UC_MACRO_NAME_AA60 0xAA60 // ꩠ MYANMAR LETTER KHAMTI GA
#define UC_MACRO_NAME_AA61 0xAA61 // ꩡ MYANMAR LETTER KHAMTI CA
#define UC_MACRO_NAME_AA62 0xAA62 // ꩢ MYANMAR LETTER KHAMTI CHA
#define UC_MACRO_NAME_AA63 0xAA63 // ꩣ MYANMAR LETTER KHAMTI JA
#define UC_MACRO_NAME_AA64 0xAA64 // ꩤ MYANMAR LETTER KHAMTI JHA
#define UC_MACRO_NAME_AA65 0xAA65 // ꩥ MYANMAR LETTER KHAMTI NYA
#define UC_MACRO_NAME_AA66 0xAA66 // ꩦ MYANMAR LETTER KHAMTI TTA
#define UC_MACRO_NAME_AA67 0xAA67 // ꩧ MYANMAR LETTER KHAMTI TTHA
#define UC_MACRO_NAME_AA68 0xAA68 // ꩨ MYANMAR LETTER KHAMTI DDA
#define UC_MACRO_NAME_AA69 0xAA69 // ꩩ MYANMAR LETTER KHAMTI DDHA
#define UC_MACRO_NAME_AA6A 0xAA6A // ꩪ MYANMAR LETTER KHAMTI DHA
#define UC_MACRO_NAME_AA6B 0xAA6B // ꩫ MYANMAR LETTER KHAMTI NA
#define UC_MACRO_NAME_AA6C 0xAA6C // ꩬ MYANMAR LETTER KHAMTI SA
#define UC_MACRO_NAME_AA6D 0xAA6D // ꩭ MYANMAR LETTER KHAMTI HA
#define UC_MACRO_NAME_AA6E 0xAA6E // ꩮ MYANMAR LETTER KHAMTI HHA
#define UC_MACRO_NAME_AA6F 0xAA6F // ꩯ MYANMAR LETTER KHAMTI FA
#define UC_MACRO_NAME_AA70 0xAA70 // ꩰ MYANMAR MODIFIER LETTER KHAMTI REDUPLICATION
#define UC_MACRO_NAME_AA71 0xAA71 // ꩱ MYANMAR LETTER KHAMTI XA
#define UC_MACRO_NAME_AA72 0xAA72 // ꩲ MYANMAR LETTER KHAMTI ZA
#define UC_MACRO_NAME_AA73 0xAA73 // ꩳ MYANMAR LETTER KHAMTI RA
#define UC_MACRO_NAME_AA74 0xAA74 // ꩴ MYANMAR LOGOGRAM KHAMTI OAY
#define UC_MACRO_NAME_AA75 0xAA75 // ꩵ MYANMAR LOGOGRAM KHAMTI QN
#define UC_MACRO_NAME_AA76 0xAA76 // ꩶ MYANMAR LOGOGRAM KHAMTI HM
#define UC_MACRO_NAME_AA77 0xAA77 // ꩷ MYANMAR SYMBOL AITON EXCLAMATION
#define UC_MACRO_NAME_AA78 0xAA78 // ꩸ MYANMAR SYMBOL AITON ONE
#define UC_MACRO_NAME_AA79 0xAA79 // ꩹ MYANMAR SYMBOL AITON TWO
#define UC_MACRO_NAME_AA7A 0xAA7A // ꩺ MYANMAR LETTER AITON RA
#define UC_MACRO_NAME_AA7B 0xAA7B // ꩻ MYANMAR SIGN PAO KAREN TONE
#define UC_MACRO_NAME_AA7C 0xAA7C // ꩼ MYANMAR SIGN TAI LAING TONE-2
#define UC_MACRO_NAME_AA7D 0xAA7D // ꩽ MYANMAR SIGN TAI LAING TONE-5
#define UC_MACRO_NAME_AA7E 0xAA7E // ꩾ MYANMAR LETTER SHWE PALAUNG CHA
#define UC_MACRO_NAME_AA7F 0xAA7F // ꩿ MYANMAR LETTER SHWE PALAUNG SHA


#endif // UC_H_MYANMAR_EXTENDED_A
