/*
 * Unicode Block: Manichaean
 * Range: U+10AC0..U+10AFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_MANICHAEAN
#define UC_H_MANICHAEAN

#define UC_MACRO_NAME_10AC0 0x10AC0 // 𐫀 MANICHAEAN LETTER ALEPH
#define UC_MACRO_NAME_10AC1 0x10AC1 // 𐫁 MANICHAEAN LETTER BETH
#define UC_MACRO_NAME_10AC2 0x10AC2 // 𐫂 MANICHAEAN LETTER BHETH
#define UC_MACRO_NAME_10AC3 0x10AC3 // 𐫃 MANICHAEAN LETTER GIMEL
#define UC_MACRO_NAME_10AC4 0x10AC4 // 𐫄 MANICHAEAN LETTER GHIMEL
#define UC_MACRO_NAME_10AC5 0x10AC5 // 𐫅 MANICHAEAN LETTER DALETH
#define UC_MACRO_NAME_10AC6 0x10AC6 // 𐫆 MANICHAEAN LETTER HE
#define UC_MACRO_NAME_10AC7 0x10AC7 // 𐫇 MANICHAEAN LETTER WAW
#define UC_MACRO_NAME_10AC8 0x10AC8 // 𐫈 MANICHAEAN SIGN UD
#define UC_MACRO_NAME_10AC9 0x10AC9 // 𐫉 MANICHAEAN LETTER ZAYIN
#define UC_MACRO_NAME_10ACA 0x10ACA // 𐫊 MANICHAEAN LETTER ZHAYIN
#define UC_MACRO_NAME_10ACB 0x10ACB // 𐫋 MANICHAEAN LETTER JAYIN
#define UC_MACRO_NAME_10ACC 0x10ACC // 𐫌 MANICHAEAN LETTER JHAYIN
#define UC_MACRO_NAME_10ACD 0x10ACD // 𐫍 MANICHAEAN LETTER HETH
#define UC_MACRO_NAME_10ACE 0x10ACE // 𐫎 MANICHAEAN LETTER TETH
#define UC_MACRO_NAME_10ACF 0x10ACF // 𐫏 MANICHAEAN LETTER YODH
#define UC_MACRO_NAME_10AD0 0x10AD0 // 𐫐 MANICHAEAN LETTER KAPH
#define UC_MACRO_NAME_10AD1 0x10AD1 // 𐫑 MANICHAEAN LETTER XAPH
#define UC_MACRO_NAME_10AD2 0x10AD2 // 𐫒 MANICHAEAN LETTER KHAPH
#define UC_MACRO_NAME_10AD3 0x10AD3 // 𐫓 MANICHAEAN LETTER LAMEDH
#define UC_MACRO_NAME_10AD4 0x10AD4 // 𐫔 MANICHAEAN LETTER DHAMEDH
#define UC_MACRO_NAME_10AD5 0x10AD5 // 𐫕 MANICHAEAN LETTER THAMEDH
#define UC_MACRO_NAME_10AD6 0x10AD6 // 𐫖 MANICHAEAN LETTER MEM
#define UC_MACRO_NAME_10AD7 0x10AD7 // 𐫗 MANICHAEAN LETTER NUN
#define UC_MACRO_NAME_10AD8 0x10AD8 // 𐫘 MANICHAEAN LETTER SAMEKH
#define UC_MACRO_NAME_10AD9 0x10AD9 // 𐫙 MANICHAEAN LETTER AYIN
#define UC_MACRO_NAME_10ADA 0x10ADA // 𐫚 MANICHAEAN LETTER AAYIN
#define UC_MACRO_NAME_10ADB 0x10ADB // 𐫛 MANICHAEAN LETTER PE
#define UC_MACRO_NAME_10ADC 0x10ADC // 𐫜 MANICHAEAN LETTER FE
#define UC_MACRO_NAME_10ADD 0x10ADD // 𐫝 MANICHAEAN LETTER SADHE
#define UC_MACRO_NAME_10ADE 0x10ADE // 𐫞 MANICHAEAN LETTER QOPH
#define UC_MACRO_NAME_10ADF 0x10ADF // 𐫟 MANICHAEAN LETTER XOPH
#define UC_MACRO_NAME_10AE0 0x10AE0 // 𐫠 MANICHAEAN LETTER QHOPH
#define UC_MACRO_NAME_10AE1 0x10AE1 // 𐫡 MANICHAEAN LETTER RESH
#define UC_MACRO_NAME_10AE2 0x10AE2 // 𐫢 MANICHAEAN LETTER SHIN
#define UC_MACRO_NAME_10AE3 0x10AE3 // 𐫣 MANICHAEAN LETTER SSHIN
#define UC_MACRO_NAME_10AE4 0x10AE4 // 𐫤 MANICHAEAN LETTER TAW
#define UC_MACRO_NAME_10AE5 0x10AE5 // 𐫥 MANICHAEAN ABBREVIATION MARK ABOVE
#define UC_MACRO_NAME_10AE6 0x10AE6 // 𐫦 MANICHAEAN ABBREVIATION MARK BELOW
#define UC_MACRO_NAME_10AEB 0x10AEB // 𐫫 MANICHAEAN NUMBER ONE
#define UC_MACRO_NAME_10AEC 0x10AEC // 𐫬 MANICHAEAN NUMBER FIVE
#define UC_MACRO_NAME_10AED 0x10AED // 𐫭 MANICHAEAN NUMBER TEN
#define UC_MACRO_NAME_10AEE 0x10AEE // 𐫮 MANICHAEAN NUMBER TWENTY
#define UC_MACRO_NAME_10AEF 0x10AEF // 𐫯 MANICHAEAN NUMBER ONE HUNDRED
#define UC_MACRO_NAME_10AF0 0x10AF0 // 𐫰 MANICHAEAN PUNCTUATION STAR
#define UC_MACRO_NAME_10AF1 0x10AF1 // 𐫱 MANICHAEAN PUNCTUATION FLEURON
#define UC_MACRO_NAME_10AF2 0x10AF2 // 𐫲 MANICHAEAN PUNCTUATION DOUBLE DOT WITHIN DOT
#define UC_MACRO_NAME_10AF3 0x10AF3 // 𐫳 MANICHAEAN PUNCTUATION DOT WITHIN DOT
#define UC_MACRO_NAME_10AF4 0x10AF4 // 𐫴 MANICHAEAN PUNCTUATION DOT
#define UC_MACRO_NAME_10AF5 0x10AF5 // 𐫵 MANICHAEAN PUNCTUATION TWO DOTS
#define UC_MACRO_NAME_10AF6 0x10AF6 // 𐫶 MANICHAEAN PUNCTUATION LINE FILLER


#endif // UC_H_MANICHAEAN
