/*
 * Unicode Block: Mathematical Alphanumeric Symbols
 * Range: U+1D400..U+1D7FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Mathematical Alphanumeric Symbols is a Unicode block comprising styled
 * forms of Latin and Greek letters and decimal digits that enable
 * mathematicians to denote different notions with different letter
 * styles. The letters in various fonts often have specific, fixed
 * meanings in particular areas of mathematics. By providing uniformity
 * over numerous mathematical articles and books, these conventions help
 * to read mathematical formulas. These also may be used to differentiate
 * between concepts that share a letter in a single problem.
 * Unicode includes many such symbols (in the range U+1D400–U+1D7FF). The
 * rationale behind this is that it enables design and usage of special
 * mathematical characters ( fonts ) that include all necessary
 * properties to differentiate from other alphanumerics, e.g. in
 * mathematics an italic letter "𝐴" can have a different meaning from a
 * roman letter "A". Unicode originally included a limited set of such
 * letter forms in its Letterlike Symbols block before completing the set
 * of Latin and Greek letter forms in this block beginning in version
 * 3.1.
 *
 */
#ifndef UC_H_MATHEMATICAL_ALPHANUMERIC_SYMBOLS
#define UC_H_MATHEMATICAL_ALPHANUMERIC_SYMBOLS

#define UC_MACRO_NAME_1D400 0x1D400 // 𝐀 MATHEMATICAL BOLD CAPITAL A
#define UC_MACRO_NAME_1D401 0x1D401 // 𝐁 MATHEMATICAL BOLD CAPITAL B
#define UC_MACRO_NAME_1D402 0x1D402 // 𝐂 MATHEMATICAL BOLD CAPITAL C
#define UC_MACRO_NAME_1D403 0x1D403 // 𝐃 MATHEMATICAL BOLD CAPITAL D
#define UC_MACRO_NAME_1D404 0x1D404 // 𝐄 MATHEMATICAL BOLD CAPITAL E
#define UC_MACRO_NAME_1D405 0x1D405 // 𝐅 MATHEMATICAL BOLD CAPITAL F
#define UC_MACRO_NAME_1D406 0x1D406 // 𝐆 MATHEMATICAL BOLD CAPITAL G
#define UC_MACRO_NAME_1D407 0x1D407 // 𝐇 MATHEMATICAL BOLD CAPITAL H
#define UC_MACRO_NAME_1D408 0x1D408 // 𝐈 MATHEMATICAL BOLD CAPITAL I
#define UC_MACRO_NAME_1D409 0x1D409 // 𝐉 MATHEMATICAL BOLD CAPITAL J
#define UC_MACRO_NAME_1D40A 0x1D40A // 𝐊 MATHEMATICAL BOLD CAPITAL K
#define UC_MACRO_NAME_1D40B 0x1D40B // 𝐋 MATHEMATICAL BOLD CAPITAL L
#define UC_MACRO_NAME_1D40C 0x1D40C // 𝐌 MATHEMATICAL BOLD CAPITAL M
#define UC_MACRO_NAME_1D40D 0x1D40D // 𝐍 MATHEMATICAL BOLD CAPITAL N
#define UC_MACRO_NAME_1D40E 0x1D40E // 𝐎 MATHEMATICAL BOLD CAPITAL O
#define UC_MACRO_NAME_1D40F 0x1D40F // 𝐏 MATHEMATICAL BOLD CAPITAL P
#define UC_MACRO_NAME_1D410 0x1D410 // 𝐐 MATHEMATICAL BOLD CAPITAL Q
#define UC_MACRO_NAME_1D411 0x1D411 // 𝐑 MATHEMATICAL BOLD CAPITAL R
#define UC_MACRO_NAME_1D412 0x1D412 // 𝐒 MATHEMATICAL BOLD CAPITAL S
#define UC_MACRO_NAME_1D413 0x1D413 // 𝐓 MATHEMATICAL BOLD CAPITAL T
#define UC_MACRO_NAME_1D414 0x1D414 // 𝐔 MATHEMATICAL BOLD CAPITAL U
#define UC_MACRO_NAME_1D415 0x1D415 // 𝐕 MATHEMATICAL BOLD CAPITAL V
#define UC_MACRO_NAME_1D416 0x1D416 // 𝐖 MATHEMATICAL BOLD CAPITAL W
#define UC_MACRO_NAME_1D417 0x1D417 // 𝐗 MATHEMATICAL BOLD CAPITAL X
#define UC_MACRO_NAME_1D418 0x1D418 // 𝐘 MATHEMATICAL BOLD CAPITAL Y
#define UC_MACRO_NAME_1D419 0x1D419 // 𝐙 MATHEMATICAL BOLD CAPITAL Z
#define UC_MACRO_NAME_1D41A 0x1D41A // 𝐚 MATHEMATICAL BOLD SMALL A
#define UC_MACRO_NAME_1D41B 0x1D41B // 𝐛 MATHEMATICAL BOLD SMALL B
#define UC_MACRO_NAME_1D41C 0x1D41C // 𝐜 MATHEMATICAL BOLD SMALL C
#define UC_MACRO_NAME_1D41D 0x1D41D // 𝐝 MATHEMATICAL BOLD SMALL D
#define UC_MACRO_NAME_1D41E 0x1D41E // 𝐞 MATHEMATICAL BOLD SMALL E
#define UC_MACRO_NAME_1D41F 0x1D41F // 𝐟 MATHEMATICAL BOLD SMALL F
#define UC_MACRO_NAME_1D420 0x1D420 // 𝐠 MATHEMATICAL BOLD SMALL G
#define UC_MACRO_NAME_1D421 0x1D421 // 𝐡 MATHEMATICAL BOLD SMALL H
#define UC_MACRO_NAME_1D422 0x1D422 // 𝐢 MATHEMATICAL BOLD SMALL I
#define UC_MACRO_NAME_1D423 0x1D423 // 𝐣 MATHEMATICAL BOLD SMALL J
#define UC_MACRO_NAME_1D424 0x1D424 // 𝐤 MATHEMATICAL BOLD SMALL K
#define UC_MACRO_NAME_1D425 0x1D425 // 𝐥 MATHEMATICAL BOLD SMALL L
#define UC_MACRO_NAME_1D426 0x1D426 // 𝐦 MATHEMATICAL BOLD SMALL M
#define UC_MACRO_NAME_1D427 0x1D427 // 𝐧 MATHEMATICAL BOLD SMALL N
#define UC_MACRO_NAME_1D428 0x1D428 // 𝐨 MATHEMATICAL BOLD SMALL O
#define UC_MACRO_NAME_1D429 0x1D429 // 𝐩 MATHEMATICAL BOLD SMALL P
#define UC_MACRO_NAME_1D42A 0x1D42A // 𝐪 MATHEMATICAL BOLD SMALL Q
#define UC_MACRO_NAME_1D42B 0x1D42B // 𝐫 MATHEMATICAL BOLD SMALL R
#define UC_MACRO_NAME_1D42C 0x1D42C // 𝐬 MATHEMATICAL BOLD SMALL S
#define UC_MACRO_NAME_1D42D 0x1D42D // 𝐭 MATHEMATICAL BOLD SMALL T
#define UC_MACRO_NAME_1D42E 0x1D42E // 𝐮 MATHEMATICAL BOLD SMALL U
#define UC_MACRO_NAME_1D42F 0x1D42F // 𝐯 MATHEMATICAL BOLD SMALL V
#define UC_MACRO_NAME_1D430 0x1D430 // 𝐰 MATHEMATICAL BOLD SMALL W
#define UC_MACRO_NAME_1D431 0x1D431 // 𝐱 MATHEMATICAL BOLD SMALL X
#define UC_MACRO_NAME_1D432 0x1D432 // 𝐲 MATHEMATICAL BOLD SMALL Y
#define UC_MACRO_NAME_1D433 0x1D433 // 𝐳 MATHEMATICAL BOLD SMALL Z
#define UC_MACRO_NAME_1D434 0x1D434 // 𝐴 MATHEMATICAL ITALIC CAPITAL A
#define UC_MACRO_NAME_1D435 0x1D435 // 𝐵 MATHEMATICAL ITALIC CAPITAL B
#define UC_MACRO_NAME_1D436 0x1D436 // 𝐶 MATHEMATICAL ITALIC CAPITAL C
#define UC_MACRO_NAME_1D437 0x1D437 // 𝐷 MATHEMATICAL ITALIC CAPITAL D
#define UC_MACRO_NAME_1D438 0x1D438 // 𝐸 MATHEMATICAL ITALIC CAPITAL E
#define UC_MACRO_NAME_1D439 0x1D439 // 𝐹 MATHEMATICAL ITALIC CAPITAL F
#define UC_MACRO_NAME_1D43A 0x1D43A // 𝐺 MATHEMATICAL ITALIC CAPITAL G
#define UC_MACRO_NAME_1D43B 0x1D43B // 𝐻 MATHEMATICAL ITALIC CAPITAL H
#define UC_MACRO_NAME_1D43C 0x1D43C // 𝐼 MATHEMATICAL ITALIC CAPITAL I
#define UC_MACRO_NAME_1D43D 0x1D43D // 𝐽 MATHEMATICAL ITALIC CAPITAL J
#define UC_MACRO_NAME_1D43E 0x1D43E // 𝐾 MATHEMATICAL ITALIC CAPITAL K
#define UC_MACRO_NAME_1D43F 0x1D43F // 𝐿 MATHEMATICAL ITALIC CAPITAL L
#define UC_MACRO_NAME_1D440 0x1D440 // 𝑀 MATHEMATICAL ITALIC CAPITAL M
#define UC_MACRO_NAME_1D441 0x1D441 // 𝑁 MATHEMATICAL ITALIC CAPITAL N
#define UC_MACRO_NAME_1D442 0x1D442 // 𝑂 MATHEMATICAL ITALIC CAPITAL O
#define UC_MACRO_NAME_1D443 0x1D443 // 𝑃 MATHEMATICAL ITALIC CAPITAL P
#define UC_MACRO_NAME_1D444 0x1D444 // 𝑄 MATHEMATICAL ITALIC CAPITAL Q
#define UC_MACRO_NAME_1D445 0x1D445 // 𝑅 MATHEMATICAL ITALIC CAPITAL R
#define UC_MACRO_NAME_1D446 0x1D446 // 𝑆 MATHEMATICAL ITALIC CAPITAL S
#define UC_MACRO_NAME_1D447 0x1D447 // 𝑇 MATHEMATICAL ITALIC CAPITAL T
#define UC_MACRO_NAME_1D448 0x1D448 // 𝑈 MATHEMATICAL ITALIC CAPITAL U
#define UC_MACRO_NAME_1D449 0x1D449 // 𝑉 MATHEMATICAL ITALIC CAPITAL V
#define UC_MACRO_NAME_1D44A 0x1D44A // 𝑊 MATHEMATICAL ITALIC CAPITAL W
#define UC_MACRO_NAME_1D44B 0x1D44B // 𝑋 MATHEMATICAL ITALIC CAPITAL X
#define UC_MACRO_NAME_1D44C 0x1D44C // 𝑌 MATHEMATICAL ITALIC CAPITAL Y
#define UC_MACRO_NAME_1D44D 0x1D44D // 𝑍 MATHEMATICAL ITALIC CAPITAL Z
#define UC_MACRO_NAME_1D44E 0x1D44E // 𝑎 MATHEMATICAL ITALIC SMALL A
#define UC_MACRO_NAME_1D44F 0x1D44F // 𝑏 MATHEMATICAL ITALIC SMALL B
#define UC_MACRO_NAME_1D450 0x1D450 // 𝑐 MATHEMATICAL ITALIC SMALL C
#define UC_MACRO_NAME_1D451 0x1D451 // 𝑑 MATHEMATICAL ITALIC SMALL D
#define UC_MACRO_NAME_1D452 0x1D452 // 𝑒 MATHEMATICAL ITALIC SMALL E
#define UC_MACRO_NAME_1D453 0x1D453 // 𝑓 MATHEMATICAL ITALIC SMALL F
#define UC_MACRO_NAME_1D454 0x1D454 // 𝑔 MATHEMATICAL ITALIC SMALL G
#define UC_MACRO_NAME_1D456 0x1D456 // 𝑖 MATHEMATICAL ITALIC SMALL I
#define UC_MACRO_NAME_1D457 0x1D457 // 𝑗 MATHEMATICAL ITALIC SMALL J
#define UC_MACRO_NAME_1D458 0x1D458 // 𝑘 MATHEMATICAL ITALIC SMALL K
#define UC_MACRO_NAME_1D459 0x1D459 // 𝑙 MATHEMATICAL ITALIC SMALL L
#define UC_MACRO_NAME_1D45A 0x1D45A // 𝑚 MATHEMATICAL ITALIC SMALL M
#define UC_MACRO_NAME_1D45B 0x1D45B // 𝑛 MATHEMATICAL ITALIC SMALL N
#define UC_MACRO_NAME_1D45C 0x1D45C // 𝑜 MATHEMATICAL ITALIC SMALL O
#define UC_MACRO_NAME_1D45D 0x1D45D // 𝑝 MATHEMATICAL ITALIC SMALL P
#define UC_MACRO_NAME_1D45E 0x1D45E // 𝑞 MATHEMATICAL ITALIC SMALL Q
#define UC_MACRO_NAME_1D45F 0x1D45F // 𝑟 MATHEMATICAL ITALIC SMALL R
#define UC_MACRO_NAME_1D460 0x1D460 // 𝑠 MATHEMATICAL ITALIC SMALL S
#define UC_MACRO_NAME_1D461 0x1D461 // 𝑡 MATHEMATICAL ITALIC SMALL T
#define UC_MACRO_NAME_1D462 0x1D462 // 𝑢 MATHEMATICAL ITALIC SMALL U
#define UC_MACRO_NAME_1D463 0x1D463 // 𝑣 MATHEMATICAL ITALIC SMALL V
#define UC_MACRO_NAME_1D464 0x1D464 // 𝑤 MATHEMATICAL ITALIC SMALL W
#define UC_MACRO_NAME_1D465 0x1D465 // 𝑥 MATHEMATICAL ITALIC SMALL X
#define UC_MACRO_NAME_1D466 0x1D466 // 𝑦 MATHEMATICAL ITALIC SMALL Y
#define UC_MACRO_NAME_1D467 0x1D467 // 𝑧 MATHEMATICAL ITALIC SMALL Z
#define UC_MACRO_NAME_1D468 0x1D468 // 𝑨 MATHEMATICAL BOLD ITALIC CAPITAL A
#define UC_MACRO_NAME_1D469 0x1D469 // 𝑩 MATHEMATICAL BOLD ITALIC CAPITAL B
#define UC_MACRO_NAME_1D46A 0x1D46A // 𝑪 MATHEMATICAL BOLD ITALIC CAPITAL C
#define UC_MACRO_NAME_1D46B 0x1D46B // 𝑫 MATHEMATICAL BOLD ITALIC CAPITAL D
#define UC_MACRO_NAME_1D46C 0x1D46C // 𝑬 MATHEMATICAL BOLD ITALIC CAPITAL E
#define UC_MACRO_NAME_1D46D 0x1D46D // 𝑭 MATHEMATICAL BOLD ITALIC CAPITAL F
#define UC_MACRO_NAME_1D46E 0x1D46E // 𝑮 MATHEMATICAL BOLD ITALIC CAPITAL G
#define UC_MACRO_NAME_1D46F 0x1D46F // 𝑯 MATHEMATICAL BOLD ITALIC CAPITAL H
#define UC_MACRO_NAME_1D470 0x1D470 // 𝑰 MATHEMATICAL BOLD ITALIC CAPITAL I
#define UC_MACRO_NAME_1D471 0x1D471 // 𝑱 MATHEMATICAL BOLD ITALIC CAPITAL J
#define UC_MACRO_NAME_1D472 0x1D472 // 𝑲 MATHEMATICAL BOLD ITALIC CAPITAL K
#define UC_MACRO_NAME_1D473 0x1D473 // 𝑳 MATHEMATICAL BOLD ITALIC CAPITAL L
#define UC_MACRO_NAME_1D474 0x1D474 // 𝑴 MATHEMATICAL BOLD ITALIC CAPITAL M
#define UC_MACRO_NAME_1D475 0x1D475 // 𝑵 MATHEMATICAL BOLD ITALIC CAPITAL N
#define UC_MACRO_NAME_1D476 0x1D476 // 𝑶 MATHEMATICAL BOLD ITALIC CAPITAL O
#define UC_MACRO_NAME_1D477 0x1D477 // 𝑷 MATHEMATICAL BOLD ITALIC CAPITAL P
#define UC_MACRO_NAME_1D478 0x1D478 // 𝑸 MATHEMATICAL BOLD ITALIC CAPITAL Q
#define UC_MACRO_NAME_1D479 0x1D479 // 𝑹 MATHEMATICAL BOLD ITALIC CAPITAL R
#define UC_MACRO_NAME_1D47A 0x1D47A // 𝑺 MATHEMATICAL BOLD ITALIC CAPITAL S
#define UC_MACRO_NAME_1D47B 0x1D47B // 𝑻 MATHEMATICAL BOLD ITALIC CAPITAL T
#define UC_MACRO_NAME_1D47C 0x1D47C // 𝑼 MATHEMATICAL BOLD ITALIC CAPITAL U
#define UC_MACRO_NAME_1D47D 0x1D47D // 𝑽 MATHEMATICAL BOLD ITALIC CAPITAL V
#define UC_MACRO_NAME_1D47E 0x1D47E // 𝑾 MATHEMATICAL BOLD ITALIC CAPITAL W
#define UC_MACRO_NAME_1D47F 0x1D47F // 𝑿 MATHEMATICAL BOLD ITALIC CAPITAL X
#define UC_MACRO_NAME_1D480 0x1D480 // 𝒀 MATHEMATICAL BOLD ITALIC CAPITAL Y
#define UC_MACRO_NAME_1D481 0x1D481 // 𝒁 MATHEMATICAL BOLD ITALIC CAPITAL Z
#define UC_MACRO_NAME_1D482 0x1D482 // 𝒂 MATHEMATICAL BOLD ITALIC SMALL A
#define UC_MACRO_NAME_1D483 0x1D483 // 𝒃 MATHEMATICAL BOLD ITALIC SMALL B
#define UC_MACRO_NAME_1D484 0x1D484 // 𝒄 MATHEMATICAL BOLD ITALIC SMALL C
#define UC_MACRO_NAME_1D485 0x1D485 // 𝒅 MATHEMATICAL BOLD ITALIC SMALL D
#define UC_MACRO_NAME_1D486 0x1D486 // 𝒆 MATHEMATICAL BOLD ITALIC SMALL E
#define UC_MACRO_NAME_1D487 0x1D487 // 𝒇 MATHEMATICAL BOLD ITALIC SMALL F
#define UC_MACRO_NAME_1D488 0x1D488 // 𝒈 MATHEMATICAL BOLD ITALIC SMALL G
#define UC_MACRO_NAME_1D489 0x1D489 // 𝒉 MATHEMATICAL BOLD ITALIC SMALL H
#define UC_MACRO_NAME_1D48A 0x1D48A // 𝒊 MATHEMATICAL BOLD ITALIC SMALL I
#define UC_MACRO_NAME_1D48B 0x1D48B // 𝒋 MATHEMATICAL BOLD ITALIC SMALL J
#define UC_MACRO_NAME_1D48C 0x1D48C // 𝒌 MATHEMATICAL BOLD ITALIC SMALL K
#define UC_MACRO_NAME_1D48D 0x1D48D // 𝒍 MATHEMATICAL BOLD ITALIC SMALL L
#define UC_MACRO_NAME_1D48E 0x1D48E // 𝒎 MATHEMATICAL BOLD ITALIC SMALL M
#define UC_MACRO_NAME_1D48F 0x1D48F // 𝒏 MATHEMATICAL BOLD ITALIC SMALL N
#define UC_MACRO_NAME_1D490 0x1D490 // 𝒐 MATHEMATICAL BOLD ITALIC SMALL O
#define UC_MACRO_NAME_1D491 0x1D491 // 𝒑 MATHEMATICAL BOLD ITALIC SMALL P
#define UC_MACRO_NAME_1D492 0x1D492 // 𝒒 MATHEMATICAL BOLD ITALIC SMALL Q
#define UC_MACRO_NAME_1D493 0x1D493 // 𝒓 MATHEMATICAL BOLD ITALIC SMALL R
#define UC_MACRO_NAME_1D494 0x1D494 // 𝒔 MATHEMATICAL BOLD ITALIC SMALL S
#define UC_MACRO_NAME_1D495 0x1D495 // 𝒕 MATHEMATICAL BOLD ITALIC SMALL T
#define UC_MACRO_NAME_1D496 0x1D496 // 𝒖 MATHEMATICAL BOLD ITALIC SMALL U
#define UC_MACRO_NAME_1D497 0x1D497 // 𝒗 MATHEMATICAL BOLD ITALIC SMALL V
#define UC_MACRO_NAME_1D498 0x1D498 // 𝒘 MATHEMATICAL BOLD ITALIC SMALL W
#define UC_MACRO_NAME_1D499 0x1D499 // 𝒙 MATHEMATICAL BOLD ITALIC SMALL X
#define UC_MACRO_NAME_1D49A 0x1D49A // 𝒚 MATHEMATICAL BOLD ITALIC SMALL Y
#define UC_MACRO_NAME_1D49B 0x1D49B // 𝒛 MATHEMATICAL BOLD ITALIC SMALL Z
#define UC_MACRO_NAME_1D49C 0x1D49C // 𝒜 MATHEMATICAL SCRIPT CAPITAL A
#define UC_MACRO_NAME_1D49E 0x1D49E // 𝒞 MATHEMATICAL SCRIPT CAPITAL C
#define UC_MACRO_NAME_1D49F 0x1D49F // 𝒟 MATHEMATICAL SCRIPT CAPITAL D
#define UC_MACRO_NAME_1D4A2 0x1D4A2 // 𝒢 MATHEMATICAL SCRIPT CAPITAL G
#define UC_MACRO_NAME_1D4A5 0x1D4A5 // 𝒥 MATHEMATICAL SCRIPT CAPITAL J
#define UC_MACRO_NAME_1D4A6 0x1D4A6 // 𝒦 MATHEMATICAL SCRIPT CAPITAL K
#define UC_MACRO_NAME_1D4A9 0x1D4A9 // 𝒩 MATHEMATICAL SCRIPT CAPITAL N
#define UC_MACRO_NAME_1D4AA 0x1D4AA // 𝒪 MATHEMATICAL SCRIPT CAPITAL O
#define UC_MACRO_NAME_1D4AB 0x1D4AB // 𝒫 MATHEMATICAL SCRIPT CAPITAL P
#define UC_MACRO_NAME_1D4AC 0x1D4AC // 𝒬 MATHEMATICAL SCRIPT CAPITAL Q
#define UC_MACRO_NAME_1D4AE 0x1D4AE // 𝒮 MATHEMATICAL SCRIPT CAPITAL S
#define UC_MACRO_NAME_1D4AF 0x1D4AF // 𝒯 MATHEMATICAL SCRIPT CAPITAL T
#define UC_MACRO_NAME_1D4B0 0x1D4B0 // 𝒰 MATHEMATICAL SCRIPT CAPITAL U
#define UC_MACRO_NAME_1D4B1 0x1D4B1 // 𝒱 MATHEMATICAL SCRIPT CAPITAL V
#define UC_MACRO_NAME_1D4B2 0x1D4B2 // 𝒲 MATHEMATICAL SCRIPT CAPITAL W
#define UC_MACRO_NAME_1D4B3 0x1D4B3 // 𝒳 MATHEMATICAL SCRIPT CAPITAL X
#define UC_MACRO_NAME_1D4B4 0x1D4B4 // 𝒴 MATHEMATICAL SCRIPT CAPITAL Y
#define UC_MACRO_NAME_1D4B5 0x1D4B5 // 𝒵 MATHEMATICAL SCRIPT CAPITAL Z
#define UC_MACRO_NAME_1D4B6 0x1D4B6 // 𝒶 MATHEMATICAL SCRIPT SMALL A
#define UC_MACRO_NAME_1D4B7 0x1D4B7 // 𝒷 MATHEMATICAL SCRIPT SMALL B
#define UC_MACRO_NAME_1D4B8 0x1D4B8 // 𝒸 MATHEMATICAL SCRIPT SMALL C
#define UC_MACRO_NAME_1D4B9 0x1D4B9 // 𝒹 MATHEMATICAL SCRIPT SMALL D
#define UC_MACRO_NAME_1D4BB 0x1D4BB // 𝒻 MATHEMATICAL SCRIPT SMALL F
#define UC_MACRO_NAME_1D4BD 0x1D4BD // 𝒽 MATHEMATICAL SCRIPT SMALL H
#define UC_MACRO_NAME_1D4BE 0x1D4BE // 𝒾 MATHEMATICAL SCRIPT SMALL I
#define UC_MACRO_NAME_1D4BF 0x1D4BF // 𝒿 MATHEMATICAL SCRIPT SMALL J
#define UC_MACRO_NAME_1D4C0 0x1D4C0 // 𝓀 MATHEMATICAL SCRIPT SMALL K
#define UC_MACRO_NAME_1D4C1 0x1D4C1 // 𝓁 MATHEMATICAL SCRIPT SMALL L
#define UC_MACRO_NAME_1D4C2 0x1D4C2 // 𝓂 MATHEMATICAL SCRIPT SMALL M
#define UC_MACRO_NAME_1D4C3 0x1D4C3 // 𝓃 MATHEMATICAL SCRIPT SMALL N
#define UC_MACRO_NAME_1D4C5 0x1D4C5 // 𝓅 MATHEMATICAL SCRIPT SMALL P
#define UC_MACRO_NAME_1D4C6 0x1D4C6 // 𝓆 MATHEMATICAL SCRIPT SMALL Q
#define UC_MACRO_NAME_1D4C7 0x1D4C7 // 𝓇 MATHEMATICAL SCRIPT SMALL R
#define UC_MACRO_NAME_1D4C8 0x1D4C8 // 𝓈 MATHEMATICAL SCRIPT SMALL S
#define UC_MACRO_NAME_1D4C9 0x1D4C9 // 𝓉 MATHEMATICAL SCRIPT SMALL T
#define UC_MACRO_NAME_1D4CA 0x1D4CA // 𝓊 MATHEMATICAL SCRIPT SMALL U
#define UC_MACRO_NAME_1D4CB 0x1D4CB // 𝓋 MATHEMATICAL SCRIPT SMALL V
#define UC_MACRO_NAME_1D4CC 0x1D4CC // 𝓌 MATHEMATICAL SCRIPT SMALL W
#define UC_MACRO_NAME_1D4CD 0x1D4CD // 𝓍 MATHEMATICAL SCRIPT SMALL X
#define UC_MACRO_NAME_1D4CE 0x1D4CE // 𝓎 MATHEMATICAL SCRIPT SMALL Y
#define UC_MACRO_NAME_1D4CF 0x1D4CF // 𝓏 MATHEMATICAL SCRIPT SMALL Z
#define UC_MACRO_NAME_1D4D0 0x1D4D0 // 𝓐 MATHEMATICAL BOLD SCRIPT CAPITAL A
#define UC_MACRO_NAME_1D4D1 0x1D4D1 // 𝓑 MATHEMATICAL BOLD SCRIPT CAPITAL B
#define UC_MACRO_NAME_1D4D2 0x1D4D2 // 𝓒 MATHEMATICAL BOLD SCRIPT CAPITAL C
#define UC_MACRO_NAME_1D4D3 0x1D4D3 // 𝓓 MATHEMATICAL BOLD SCRIPT CAPITAL D
#define UC_MACRO_NAME_1D4D4 0x1D4D4 // 𝓔 MATHEMATICAL BOLD SCRIPT CAPITAL E
#define UC_MACRO_NAME_1D4D5 0x1D4D5 // 𝓕 MATHEMATICAL BOLD SCRIPT CAPITAL F
#define UC_MACRO_NAME_1D4D6 0x1D4D6 // 𝓖 MATHEMATICAL BOLD SCRIPT CAPITAL G
#define UC_MACRO_NAME_1D4D7 0x1D4D7 // 𝓗 MATHEMATICAL BOLD SCRIPT CAPITAL H
#define UC_MACRO_NAME_1D4D8 0x1D4D8 // 𝓘 MATHEMATICAL BOLD SCRIPT CAPITAL I
#define UC_MACRO_NAME_1D4D9 0x1D4D9 // 𝓙 MATHEMATICAL BOLD SCRIPT CAPITAL J
#define UC_MACRO_NAME_1D4DA 0x1D4DA // 𝓚 MATHEMATICAL BOLD SCRIPT CAPITAL K
#define UC_MACRO_NAME_1D4DB 0x1D4DB // 𝓛 MATHEMATICAL BOLD SCRIPT CAPITAL L
#define UC_MACRO_NAME_1D4DC 0x1D4DC // 𝓜 MATHEMATICAL BOLD SCRIPT CAPITAL M
#define UC_MACRO_NAME_1D4DD 0x1D4DD // 𝓝 MATHEMATICAL BOLD SCRIPT CAPITAL N
#define UC_MACRO_NAME_1D4DE 0x1D4DE // 𝓞 MATHEMATICAL BOLD SCRIPT CAPITAL O
#define UC_MACRO_NAME_1D4DF 0x1D4DF // 𝓟 MATHEMATICAL BOLD SCRIPT CAPITAL P
#define UC_MACRO_NAME_1D4E0 0x1D4E0 // 𝓠 MATHEMATICAL BOLD SCRIPT CAPITAL Q
#define UC_MACRO_NAME_1D4E1 0x1D4E1 // 𝓡 MATHEMATICAL BOLD SCRIPT CAPITAL R
#define UC_MACRO_NAME_1D4E2 0x1D4E2 // 𝓢 MATHEMATICAL BOLD SCRIPT CAPITAL S
#define UC_MACRO_NAME_1D4E3 0x1D4E3 // 𝓣 MATHEMATICAL BOLD SCRIPT CAPITAL T
#define UC_MACRO_NAME_1D4E4 0x1D4E4 // 𝓤 MATHEMATICAL BOLD SCRIPT CAPITAL U
#define UC_MACRO_NAME_1D4E5 0x1D4E5 // 𝓥 MATHEMATICAL BOLD SCRIPT CAPITAL V
#define UC_MACRO_NAME_1D4E6 0x1D4E6 // 𝓦 MATHEMATICAL BOLD SCRIPT CAPITAL W
#define UC_MACRO_NAME_1D4E7 0x1D4E7 // 𝓧 MATHEMATICAL BOLD SCRIPT CAPITAL X
#define UC_MACRO_NAME_1D4E8 0x1D4E8 // 𝓨 MATHEMATICAL BOLD SCRIPT CAPITAL Y
#define UC_MACRO_NAME_1D4E9 0x1D4E9 // 𝓩 MATHEMATICAL BOLD SCRIPT CAPITAL Z
#define UC_MACRO_NAME_1D4EA 0x1D4EA // 𝓪 MATHEMATICAL BOLD SCRIPT SMALL A
#define UC_MACRO_NAME_1D4EB 0x1D4EB // 𝓫 MATHEMATICAL BOLD SCRIPT SMALL B
#define UC_MACRO_NAME_1D4EC 0x1D4EC // 𝓬 MATHEMATICAL BOLD SCRIPT SMALL C
#define UC_MACRO_NAME_1D4ED 0x1D4ED // 𝓭 MATHEMATICAL BOLD SCRIPT SMALL D
#define UC_MACRO_NAME_1D4EE 0x1D4EE // 𝓮 MATHEMATICAL BOLD SCRIPT SMALL E
#define UC_MACRO_NAME_1D4EF 0x1D4EF // 𝓯 MATHEMATICAL BOLD SCRIPT SMALL F
#define UC_MACRO_NAME_1D4F0 0x1D4F0 // 𝓰 MATHEMATICAL BOLD SCRIPT SMALL G
#define UC_MACRO_NAME_1D4F1 0x1D4F1 // 𝓱 MATHEMATICAL BOLD SCRIPT SMALL H
#define UC_MACRO_NAME_1D4F2 0x1D4F2 // 𝓲 MATHEMATICAL BOLD SCRIPT SMALL I
#define UC_MACRO_NAME_1D4F3 0x1D4F3 // 𝓳 MATHEMATICAL BOLD SCRIPT SMALL J
#define UC_MACRO_NAME_1D4F4 0x1D4F4 // 𝓴 MATHEMATICAL BOLD SCRIPT SMALL K
#define UC_MACRO_NAME_1D4F5 0x1D4F5 // 𝓵 MATHEMATICAL BOLD SCRIPT SMALL L
#define UC_MACRO_NAME_1D4F6 0x1D4F6 // 𝓶 MATHEMATICAL BOLD SCRIPT SMALL M
#define UC_MACRO_NAME_1D4F7 0x1D4F7 // 𝓷 MATHEMATICAL BOLD SCRIPT SMALL N
#define UC_MACRO_NAME_1D4F8 0x1D4F8 // 𝓸 MATHEMATICAL BOLD SCRIPT SMALL O
#define UC_MACRO_NAME_1D4F9 0x1D4F9 // 𝓹 MATHEMATICAL BOLD SCRIPT SMALL P
#define UC_MACRO_NAME_1D4FA 0x1D4FA // 𝓺 MATHEMATICAL BOLD SCRIPT SMALL Q
#define UC_MACRO_NAME_1D4FB 0x1D4FB // 𝓻 MATHEMATICAL BOLD SCRIPT SMALL R
#define UC_MACRO_NAME_1D4FC 0x1D4FC // 𝓼 MATHEMATICAL BOLD SCRIPT SMALL S
#define UC_MACRO_NAME_1D4FD 0x1D4FD // 𝓽 MATHEMATICAL BOLD SCRIPT SMALL T
#define UC_MACRO_NAME_1D4FE 0x1D4FE // 𝓾 MATHEMATICAL BOLD SCRIPT SMALL U
#define UC_MACRO_NAME_1D4FF 0x1D4FF // 𝓿 MATHEMATICAL BOLD SCRIPT SMALL V
#define UC_MACRO_NAME_1D500 0x1D500 // 𝔀 MATHEMATICAL BOLD SCRIPT SMALL W
#define UC_MACRO_NAME_1D501 0x1D501 // 𝔁 MATHEMATICAL BOLD SCRIPT SMALL X
#define UC_MACRO_NAME_1D502 0x1D502 // 𝔂 MATHEMATICAL BOLD SCRIPT SMALL Y
#define UC_MACRO_NAME_1D503 0x1D503 // 𝔃 MATHEMATICAL BOLD SCRIPT SMALL Z
#define UC_MACRO_NAME_1D504 0x1D504 // 𝔄 MATHEMATICAL FRAKTUR CAPITAL A
#define UC_MACRO_NAME_1D505 0x1D505 // 𝔅 MATHEMATICAL FRAKTUR CAPITAL B
#define UC_MACRO_NAME_1D507 0x1D507 // 𝔇 MATHEMATICAL FRAKTUR CAPITAL D
#define UC_MACRO_NAME_1D508 0x1D508 // 𝔈 MATHEMATICAL FRAKTUR CAPITAL E
#define UC_MACRO_NAME_1D509 0x1D509 // 𝔉 MATHEMATICAL FRAKTUR CAPITAL F
#define UC_MACRO_NAME_1D50A 0x1D50A // 𝔊 MATHEMATICAL FRAKTUR CAPITAL G
#define UC_MACRO_NAME_1D50D 0x1D50D // 𝔍 MATHEMATICAL FRAKTUR CAPITAL J
#define UC_MACRO_NAME_1D50E 0x1D50E // 𝔎 MATHEMATICAL FRAKTUR CAPITAL K
#define UC_MACRO_NAME_1D50F 0x1D50F // 𝔏 MATHEMATICAL FRAKTUR CAPITAL L
#define UC_MACRO_NAME_1D510 0x1D510 // 𝔐 MATHEMATICAL FRAKTUR CAPITAL M
#define UC_MACRO_NAME_1D511 0x1D511 // 𝔑 MATHEMATICAL FRAKTUR CAPITAL N
#define UC_MACRO_NAME_1D512 0x1D512 // 𝔒 MATHEMATICAL FRAKTUR CAPITAL O
#define UC_MACRO_NAME_1D513 0x1D513 // 𝔓 MATHEMATICAL FRAKTUR CAPITAL P
#define UC_MACRO_NAME_1D514 0x1D514 // 𝔔 MATHEMATICAL FRAKTUR CAPITAL Q
#define UC_MACRO_NAME_1D516 0x1D516 // 𝔖 MATHEMATICAL FRAKTUR CAPITAL S
#define UC_MACRO_NAME_1D517 0x1D517 // 𝔗 MATHEMATICAL FRAKTUR CAPITAL T
#define UC_MACRO_NAME_1D518 0x1D518 // 𝔘 MATHEMATICAL FRAKTUR CAPITAL U
#define UC_MACRO_NAME_1D519 0x1D519 // 𝔙 MATHEMATICAL FRAKTUR CAPITAL V
#define UC_MACRO_NAME_1D51A 0x1D51A // 𝔚 MATHEMATICAL FRAKTUR CAPITAL W
#define UC_MACRO_NAME_1D51B 0x1D51B // 𝔛 MATHEMATICAL FRAKTUR CAPITAL X
#define UC_MACRO_NAME_1D51C 0x1D51C // 𝔜 MATHEMATICAL FRAKTUR CAPITAL Y
#define UC_MACRO_NAME_1D51E 0x1D51E // 𝔞 MATHEMATICAL FRAKTUR SMALL A
#define UC_MACRO_NAME_1D51F 0x1D51F // 𝔟 MATHEMATICAL FRAKTUR SMALL B
#define UC_MACRO_NAME_1D520 0x1D520 // 𝔠 MATHEMATICAL FRAKTUR SMALL C
#define UC_MACRO_NAME_1D521 0x1D521 // 𝔡 MATHEMATICAL FRAKTUR SMALL D
#define UC_MACRO_NAME_1D522 0x1D522 // 𝔢 MATHEMATICAL FRAKTUR SMALL E
#define UC_MACRO_NAME_1D523 0x1D523 // 𝔣 MATHEMATICAL FRAKTUR SMALL F
#define UC_MACRO_NAME_1D524 0x1D524 // 𝔤 MATHEMATICAL FRAKTUR SMALL G
#define UC_MACRO_NAME_1D525 0x1D525 // 𝔥 MATHEMATICAL FRAKTUR SMALL H
#define UC_MACRO_NAME_1D526 0x1D526 // 𝔦 MATHEMATICAL FRAKTUR SMALL I
#define UC_MACRO_NAME_1D527 0x1D527 // 𝔧 MATHEMATICAL FRAKTUR SMALL J
#define UC_MACRO_NAME_1D528 0x1D528 // 𝔨 MATHEMATICAL FRAKTUR SMALL K
#define UC_MACRO_NAME_1D529 0x1D529 // 𝔩 MATHEMATICAL FRAKTUR SMALL L
#define UC_MACRO_NAME_1D52A 0x1D52A // 𝔪 MATHEMATICAL FRAKTUR SMALL M
#define UC_MACRO_NAME_1D52B 0x1D52B // 𝔫 MATHEMATICAL FRAKTUR SMALL N
#define UC_MACRO_NAME_1D52C 0x1D52C // 𝔬 MATHEMATICAL FRAKTUR SMALL O
#define UC_MACRO_NAME_1D52D 0x1D52D // 𝔭 MATHEMATICAL FRAKTUR SMALL P
#define UC_MACRO_NAME_1D52E 0x1D52E // 𝔮 MATHEMATICAL FRAKTUR SMALL Q
#define UC_MACRO_NAME_1D52F 0x1D52F // 𝔯 MATHEMATICAL FRAKTUR SMALL R
#define UC_MACRO_NAME_1D530 0x1D530 // 𝔰 MATHEMATICAL FRAKTUR SMALL S
#define UC_MACRO_NAME_1D531 0x1D531 // 𝔱 MATHEMATICAL FRAKTUR SMALL T
#define UC_MACRO_NAME_1D532 0x1D532 // 𝔲 MATHEMATICAL FRAKTUR SMALL U
#define UC_MACRO_NAME_1D533 0x1D533 // 𝔳 MATHEMATICAL FRAKTUR SMALL V
#define UC_MACRO_NAME_1D534 0x1D534 // 𝔴 MATHEMATICAL FRAKTUR SMALL W
#define UC_MACRO_NAME_1D535 0x1D535 // 𝔵 MATHEMATICAL FRAKTUR SMALL X
#define UC_MACRO_NAME_1D536 0x1D536 // 𝔶 MATHEMATICAL FRAKTUR SMALL Y
#define UC_MACRO_NAME_1D537 0x1D537 // 𝔷 MATHEMATICAL FRAKTUR SMALL Z
#define UC_MACRO_NAME_1D538 0x1D538 // 𝔸 MATHEMATICAL DOUBLE-STRUCK CAPITAL A
#define UC_MACRO_NAME_1D539 0x1D539 // 𝔹 MATHEMATICAL DOUBLE-STRUCK CAPITAL B
#define UC_MACRO_NAME_1D53B 0x1D53B // 𝔻 MATHEMATICAL DOUBLE-STRUCK CAPITAL D
#define UC_MACRO_NAME_1D53C 0x1D53C // 𝔼 MATHEMATICAL DOUBLE-STRUCK CAPITAL E
#define UC_MACRO_NAME_1D53D 0x1D53D // 𝔽 MATHEMATICAL DOUBLE-STRUCK CAPITAL F
#define UC_MACRO_NAME_1D53E 0x1D53E // 𝔾 MATHEMATICAL DOUBLE-STRUCK CAPITAL G
#define UC_MACRO_NAME_1D540 0x1D540 // 𝕀 MATHEMATICAL DOUBLE-STRUCK CAPITAL I
#define UC_MACRO_NAME_1D541 0x1D541 // 𝕁 MATHEMATICAL DOUBLE-STRUCK CAPITAL J
#define UC_MACRO_NAME_1D542 0x1D542 // 𝕂 MATHEMATICAL DOUBLE-STRUCK CAPITAL K
#define UC_MACRO_NAME_1D543 0x1D543 // 𝕃 MATHEMATICAL DOUBLE-STRUCK CAPITAL L
#define UC_MACRO_NAME_1D544 0x1D544 // 𝕄 MATHEMATICAL DOUBLE-STRUCK CAPITAL M
#define UC_MACRO_NAME_1D546 0x1D546 // 𝕆 MATHEMATICAL DOUBLE-STRUCK CAPITAL O
#define UC_MACRO_NAME_1D54A 0x1D54A // 𝕊 MATHEMATICAL DOUBLE-STRUCK CAPITAL S
#define UC_MACRO_NAME_1D54B 0x1D54B // 𝕋 MATHEMATICAL DOUBLE-STRUCK CAPITAL T
#define UC_MACRO_NAME_1D54C 0x1D54C // 𝕌 MATHEMATICAL DOUBLE-STRUCK CAPITAL U
#define UC_MACRO_NAME_1D54D 0x1D54D // 𝕍 MATHEMATICAL DOUBLE-STRUCK CAPITAL V
#define UC_MACRO_NAME_1D54E 0x1D54E // 𝕎 MATHEMATICAL DOUBLE-STRUCK CAPITAL W
#define UC_MACRO_NAME_1D54F 0x1D54F // 𝕏 MATHEMATICAL DOUBLE-STRUCK CAPITAL X
#define UC_MACRO_NAME_1D550 0x1D550 // 𝕐 MATHEMATICAL DOUBLE-STRUCK CAPITAL Y
#define UC_MACRO_NAME_1D552 0x1D552 // 𝕒 MATHEMATICAL DOUBLE-STRUCK SMALL A
#define UC_MACRO_NAME_1D553 0x1D553 // 𝕓 MATHEMATICAL DOUBLE-STRUCK SMALL B
#define UC_MACRO_NAME_1D554 0x1D554 // 𝕔 MATHEMATICAL DOUBLE-STRUCK SMALL C
#define UC_MACRO_NAME_1D555 0x1D555 // 𝕕 MATHEMATICAL DOUBLE-STRUCK SMALL D
#define UC_MACRO_NAME_1D556 0x1D556 // 𝕖 MATHEMATICAL DOUBLE-STRUCK SMALL E
#define UC_MACRO_NAME_1D557 0x1D557 // 𝕗 MATHEMATICAL DOUBLE-STRUCK SMALL F
#define UC_MACRO_NAME_1D558 0x1D558 // 𝕘 MATHEMATICAL DOUBLE-STRUCK SMALL G
#define UC_MACRO_NAME_1D559 0x1D559 // 𝕙 MATHEMATICAL DOUBLE-STRUCK SMALL H
#define UC_MACRO_NAME_1D55A 0x1D55A // 𝕚 MATHEMATICAL DOUBLE-STRUCK SMALL I
#define UC_MACRO_NAME_1D55B 0x1D55B // 𝕛 MATHEMATICAL DOUBLE-STRUCK SMALL J
#define UC_MACRO_NAME_1D55C 0x1D55C // 𝕜 MATHEMATICAL DOUBLE-STRUCK SMALL K
#define UC_MACRO_NAME_1D55D 0x1D55D // 𝕝 MATHEMATICAL DOUBLE-STRUCK SMALL L
#define UC_MACRO_NAME_1D55E 0x1D55E // 𝕞 MATHEMATICAL DOUBLE-STRUCK SMALL M
#define UC_MACRO_NAME_1D55F 0x1D55F // 𝕟 MATHEMATICAL DOUBLE-STRUCK SMALL N
#define UC_MACRO_NAME_1D560 0x1D560 // 𝕠 MATHEMATICAL DOUBLE-STRUCK SMALL O
#define UC_MACRO_NAME_1D561 0x1D561 // 𝕡 MATHEMATICAL DOUBLE-STRUCK SMALL P
#define UC_MACRO_NAME_1D562 0x1D562 // 𝕢 MATHEMATICAL DOUBLE-STRUCK SMALL Q
#define UC_MACRO_NAME_1D563 0x1D563 // 𝕣 MATHEMATICAL DOUBLE-STRUCK SMALL R
#define UC_MACRO_NAME_1D564 0x1D564 // 𝕤 MATHEMATICAL DOUBLE-STRUCK SMALL S
#define UC_MACRO_NAME_1D565 0x1D565 // 𝕥 MATHEMATICAL DOUBLE-STRUCK SMALL T
#define UC_MACRO_NAME_1D566 0x1D566 // 𝕦 MATHEMATICAL DOUBLE-STRUCK SMALL U
#define UC_MACRO_NAME_1D567 0x1D567 // 𝕧 MATHEMATICAL DOUBLE-STRUCK SMALL V
#define UC_MACRO_NAME_1D568 0x1D568 // 𝕨 MATHEMATICAL DOUBLE-STRUCK SMALL W
#define UC_MACRO_NAME_1D569 0x1D569 // 𝕩 MATHEMATICAL DOUBLE-STRUCK SMALL X
#define UC_MACRO_NAME_1D56A 0x1D56A // 𝕪 MATHEMATICAL DOUBLE-STRUCK SMALL Y
#define UC_MACRO_NAME_1D56B 0x1D56B // 𝕫 MATHEMATICAL DOUBLE-STRUCK SMALL Z
#define UC_MACRO_NAME_1D56C 0x1D56C // 𝕬 MATHEMATICAL BOLD FRAKTUR CAPITAL A
#define UC_MACRO_NAME_1D56D 0x1D56D // 𝕭 MATHEMATICAL BOLD FRAKTUR CAPITAL B
#define UC_MACRO_NAME_1D56E 0x1D56E // 𝕮 MATHEMATICAL BOLD FRAKTUR CAPITAL C
#define UC_MACRO_NAME_1D56F 0x1D56F // 𝕯 MATHEMATICAL BOLD FRAKTUR CAPITAL D
#define UC_MACRO_NAME_1D570 0x1D570 // 𝕰 MATHEMATICAL BOLD FRAKTUR CAPITAL E
#define UC_MACRO_NAME_1D571 0x1D571 // 𝕱 MATHEMATICAL BOLD FRAKTUR CAPITAL F
#define UC_MACRO_NAME_1D572 0x1D572 // 𝕲 MATHEMATICAL BOLD FRAKTUR CAPITAL G
#define UC_MACRO_NAME_1D573 0x1D573 // 𝕳 MATHEMATICAL BOLD FRAKTUR CAPITAL H
#define UC_MACRO_NAME_1D574 0x1D574 // 𝕴 MATHEMATICAL BOLD FRAKTUR CAPITAL I
#define UC_MACRO_NAME_1D575 0x1D575 // 𝕵 MATHEMATICAL BOLD FRAKTUR CAPITAL J
#define UC_MACRO_NAME_1D576 0x1D576 // 𝕶 MATHEMATICAL BOLD FRAKTUR CAPITAL K
#define UC_MACRO_NAME_1D577 0x1D577 // 𝕷 MATHEMATICAL BOLD FRAKTUR CAPITAL L
#define UC_MACRO_NAME_1D578 0x1D578 // 𝕸 MATHEMATICAL BOLD FRAKTUR CAPITAL M
#define UC_MACRO_NAME_1D579 0x1D579 // 𝕹 MATHEMATICAL BOLD FRAKTUR CAPITAL N
#define UC_MACRO_NAME_1D57A 0x1D57A // 𝕺 MATHEMATICAL BOLD FRAKTUR CAPITAL O
#define UC_MACRO_NAME_1D57B 0x1D57B // 𝕻 MATHEMATICAL BOLD FRAKTUR CAPITAL P
#define UC_MACRO_NAME_1D57C 0x1D57C // 𝕼 MATHEMATICAL BOLD FRAKTUR CAPITAL Q
#define UC_MACRO_NAME_1D57D 0x1D57D // 𝕽 MATHEMATICAL BOLD FRAKTUR CAPITAL R
#define UC_MACRO_NAME_1D57E 0x1D57E // 𝕾 MATHEMATICAL BOLD FRAKTUR CAPITAL S
#define UC_MACRO_NAME_1D57F 0x1D57F // 𝕿 MATHEMATICAL BOLD FRAKTUR CAPITAL T
#define UC_MACRO_NAME_1D580 0x1D580 // 𝖀 MATHEMATICAL BOLD FRAKTUR CAPITAL U
#define UC_MACRO_NAME_1D581 0x1D581 // 𝖁 MATHEMATICAL BOLD FRAKTUR CAPITAL V
#define UC_MACRO_NAME_1D582 0x1D582 // 𝖂 MATHEMATICAL BOLD FRAKTUR CAPITAL W
#define UC_MACRO_NAME_1D583 0x1D583 // 𝖃 MATHEMATICAL BOLD FRAKTUR CAPITAL X
#define UC_MACRO_NAME_1D584 0x1D584 // 𝖄 MATHEMATICAL BOLD FRAKTUR CAPITAL Y
#define UC_MACRO_NAME_1D585 0x1D585 // 𝖅 MATHEMATICAL BOLD FRAKTUR CAPITAL Z
#define UC_MACRO_NAME_1D586 0x1D586 // 𝖆 MATHEMATICAL BOLD FRAKTUR SMALL A
#define UC_MACRO_NAME_1D587 0x1D587 // 𝖇 MATHEMATICAL BOLD FRAKTUR SMALL B
#define UC_MACRO_NAME_1D588 0x1D588 // 𝖈 MATHEMATICAL BOLD FRAKTUR SMALL C
#define UC_MACRO_NAME_1D589 0x1D589 // 𝖉 MATHEMATICAL BOLD FRAKTUR SMALL D
#define UC_MACRO_NAME_1D58A 0x1D58A // 𝖊 MATHEMATICAL BOLD FRAKTUR SMALL E
#define UC_MACRO_NAME_1D58B 0x1D58B // 𝖋 MATHEMATICAL BOLD FRAKTUR SMALL F
#define UC_MACRO_NAME_1D58C 0x1D58C // 𝖌 MATHEMATICAL BOLD FRAKTUR SMALL G
#define UC_MACRO_NAME_1D58D 0x1D58D // 𝖍 MATHEMATICAL BOLD FRAKTUR SMALL H
#define UC_MACRO_NAME_1D58E 0x1D58E // 𝖎 MATHEMATICAL BOLD FRAKTUR SMALL I
#define UC_MACRO_NAME_1D58F 0x1D58F // 𝖏 MATHEMATICAL BOLD FRAKTUR SMALL J
#define UC_MACRO_NAME_1D590 0x1D590 // 𝖐 MATHEMATICAL BOLD FRAKTUR SMALL K
#define UC_MACRO_NAME_1D591 0x1D591 // 𝖑 MATHEMATICAL BOLD FRAKTUR SMALL L
#define UC_MACRO_NAME_1D592 0x1D592 // 𝖒 MATHEMATICAL BOLD FRAKTUR SMALL M
#define UC_MACRO_NAME_1D593 0x1D593 // 𝖓 MATHEMATICAL BOLD FRAKTUR SMALL N
#define UC_MACRO_NAME_1D594 0x1D594 // 𝖔 MATHEMATICAL BOLD FRAKTUR SMALL O
#define UC_MACRO_NAME_1D595 0x1D595 // 𝖕 MATHEMATICAL BOLD FRAKTUR SMALL P
#define UC_MACRO_NAME_1D596 0x1D596 // 𝖖 MATHEMATICAL BOLD FRAKTUR SMALL Q
#define UC_MACRO_NAME_1D597 0x1D597 // 𝖗 MATHEMATICAL BOLD FRAKTUR SMALL R
#define UC_MACRO_NAME_1D598 0x1D598 // 𝖘 MATHEMATICAL BOLD FRAKTUR SMALL S
#define UC_MACRO_NAME_1D599 0x1D599 // 𝖙 MATHEMATICAL BOLD FRAKTUR SMALL T
#define UC_MACRO_NAME_1D59A 0x1D59A // 𝖚 MATHEMATICAL BOLD FRAKTUR SMALL U
#define UC_MACRO_NAME_1D59B 0x1D59B // 𝖛 MATHEMATICAL BOLD FRAKTUR SMALL V
#define UC_MACRO_NAME_1D59C 0x1D59C // 𝖜 MATHEMATICAL BOLD FRAKTUR SMALL W
#define UC_MACRO_NAME_1D59D 0x1D59D // 𝖝 MATHEMATICAL BOLD FRAKTUR SMALL X
#define UC_MACRO_NAME_1D59E 0x1D59E // 𝖞 MATHEMATICAL BOLD FRAKTUR SMALL Y
#define UC_MACRO_NAME_1D59F 0x1D59F // 𝖟 MATHEMATICAL BOLD FRAKTUR SMALL Z
#define UC_MACRO_NAME_1D5A0 0x1D5A0 // 𝖠 MATHEMATICAL SANS-SERIF CAPITAL A
#define UC_MACRO_NAME_1D5A1 0x1D5A1 // 𝖡 MATHEMATICAL SANS-SERIF CAPITAL B
#define UC_MACRO_NAME_1D5A2 0x1D5A2 // 𝖢 MATHEMATICAL SANS-SERIF CAPITAL C
#define UC_MACRO_NAME_1D5A3 0x1D5A3 // 𝖣 MATHEMATICAL SANS-SERIF CAPITAL D
#define UC_MACRO_NAME_1D5A4 0x1D5A4 // 𝖤 MATHEMATICAL SANS-SERIF CAPITAL E
#define UC_MACRO_NAME_1D5A5 0x1D5A5 // 𝖥 MATHEMATICAL SANS-SERIF CAPITAL F
#define UC_MACRO_NAME_1D5A6 0x1D5A6 // 𝖦 MATHEMATICAL SANS-SERIF CAPITAL G
#define UC_MACRO_NAME_1D5A7 0x1D5A7 // 𝖧 MATHEMATICAL SANS-SERIF CAPITAL H
#define UC_MACRO_NAME_1D5A8 0x1D5A8 // 𝖨 MATHEMATICAL SANS-SERIF CAPITAL I
#define UC_MACRO_NAME_1D5A9 0x1D5A9 // 𝖩 MATHEMATICAL SANS-SERIF CAPITAL J
#define UC_MACRO_NAME_1D5AA 0x1D5AA // 𝖪 MATHEMATICAL SANS-SERIF CAPITAL K
#define UC_MACRO_NAME_1D5AB 0x1D5AB // 𝖫 MATHEMATICAL SANS-SERIF CAPITAL L
#define UC_MACRO_NAME_1D5AC 0x1D5AC // 𝖬 MATHEMATICAL SANS-SERIF CAPITAL M
#define UC_MACRO_NAME_1D5AD 0x1D5AD // 𝖭 MATHEMATICAL SANS-SERIF CAPITAL N
#define UC_MACRO_NAME_1D5AE 0x1D5AE // 𝖮 MATHEMATICAL SANS-SERIF CAPITAL O
#define UC_MACRO_NAME_1D5AF 0x1D5AF // 𝖯 MATHEMATICAL SANS-SERIF CAPITAL P
#define UC_MACRO_NAME_1D5B0 0x1D5B0 // 𝖰 MATHEMATICAL SANS-SERIF CAPITAL Q
#define UC_MACRO_NAME_1D5B1 0x1D5B1 // 𝖱 MATHEMATICAL SANS-SERIF CAPITAL R
#define UC_MACRO_NAME_1D5B2 0x1D5B2 // 𝖲 MATHEMATICAL SANS-SERIF CAPITAL S
#define UC_MACRO_NAME_1D5B3 0x1D5B3 // 𝖳 MATHEMATICAL SANS-SERIF CAPITAL T
#define UC_MACRO_NAME_1D5B4 0x1D5B4 // 𝖴 MATHEMATICAL SANS-SERIF CAPITAL U
#define UC_MACRO_NAME_1D5B5 0x1D5B5 // 𝖵 MATHEMATICAL SANS-SERIF CAPITAL V
#define UC_MACRO_NAME_1D5B6 0x1D5B6 // 𝖶 MATHEMATICAL SANS-SERIF CAPITAL W
#define UC_MACRO_NAME_1D5B7 0x1D5B7 // 𝖷 MATHEMATICAL SANS-SERIF CAPITAL X
#define UC_MACRO_NAME_1D5B8 0x1D5B8 // 𝖸 MATHEMATICAL SANS-SERIF CAPITAL Y
#define UC_MACRO_NAME_1D5B9 0x1D5B9 // 𝖹 MATHEMATICAL SANS-SERIF CAPITAL Z
#define UC_MACRO_NAME_1D5BA 0x1D5BA // 𝖺 MATHEMATICAL SANS-SERIF SMALL A
#define UC_MACRO_NAME_1D5BB 0x1D5BB // 𝖻 MATHEMATICAL SANS-SERIF SMALL B
#define UC_MACRO_NAME_1D5BC 0x1D5BC // 𝖼 MATHEMATICAL SANS-SERIF SMALL C
#define UC_MACRO_NAME_1D5BD 0x1D5BD // 𝖽 MATHEMATICAL SANS-SERIF SMALL D
#define UC_MACRO_NAME_1D5BE 0x1D5BE // 𝖾 MATHEMATICAL SANS-SERIF SMALL E
#define UC_MACRO_NAME_1D5BF 0x1D5BF // 𝖿 MATHEMATICAL SANS-SERIF SMALL F
#define UC_MACRO_NAME_1D5C0 0x1D5C0 // 𝗀 MATHEMATICAL SANS-SERIF SMALL G
#define UC_MACRO_NAME_1D5C1 0x1D5C1 // 𝗁 MATHEMATICAL SANS-SERIF SMALL H
#define UC_MACRO_NAME_1D5C2 0x1D5C2 // 𝗂 MATHEMATICAL SANS-SERIF SMALL I
#define UC_MACRO_NAME_1D5C3 0x1D5C3 // 𝗃 MATHEMATICAL SANS-SERIF SMALL J
#define UC_MACRO_NAME_1D5C4 0x1D5C4 // 𝗄 MATHEMATICAL SANS-SERIF SMALL K
#define UC_MACRO_NAME_1D5C5 0x1D5C5 // 𝗅 MATHEMATICAL SANS-SERIF SMALL L
#define UC_MACRO_NAME_1D5C6 0x1D5C6 // 𝗆 MATHEMATICAL SANS-SERIF SMALL M
#define UC_MACRO_NAME_1D5C7 0x1D5C7 // 𝗇 MATHEMATICAL SANS-SERIF SMALL N
#define UC_MACRO_NAME_1D5C8 0x1D5C8 // 𝗈 MATHEMATICAL SANS-SERIF SMALL O
#define UC_MACRO_NAME_1D5C9 0x1D5C9 // 𝗉 MATHEMATICAL SANS-SERIF SMALL P
#define UC_MACRO_NAME_1D5CA 0x1D5CA // 𝗊 MATHEMATICAL SANS-SERIF SMALL Q
#define UC_MACRO_NAME_1D5CB 0x1D5CB // 𝗋 MATHEMATICAL SANS-SERIF SMALL R
#define UC_MACRO_NAME_1D5CC 0x1D5CC // 𝗌 MATHEMATICAL SANS-SERIF SMALL S
#define UC_MACRO_NAME_1D5CD 0x1D5CD // 𝗍 MATHEMATICAL SANS-SERIF SMALL T
#define UC_MACRO_NAME_1D5CE 0x1D5CE // 𝗎 MATHEMATICAL SANS-SERIF SMALL U
#define UC_MACRO_NAME_1D5CF 0x1D5CF // 𝗏 MATHEMATICAL SANS-SERIF SMALL V
#define UC_MACRO_NAME_1D5D0 0x1D5D0 // 𝗐 MATHEMATICAL SANS-SERIF SMALL W
#define UC_MACRO_NAME_1D5D1 0x1D5D1 // 𝗑 MATHEMATICAL SANS-SERIF SMALL X
#define UC_MACRO_NAME_1D5D2 0x1D5D2 // 𝗒 MATHEMATICAL SANS-SERIF SMALL Y
#define UC_MACRO_NAME_1D5D3 0x1D5D3 // 𝗓 MATHEMATICAL SANS-SERIF SMALL Z
#define UC_MACRO_NAME_1D5D4 0x1D5D4 // 𝗔 MATHEMATICAL SANS-SERIF BOLD CAPITAL A
#define UC_MACRO_NAME_1D5D5 0x1D5D5 // 𝗕 MATHEMATICAL SANS-SERIF BOLD CAPITAL B
#define UC_MACRO_NAME_1D5D6 0x1D5D6 // 𝗖 MATHEMATICAL SANS-SERIF BOLD CAPITAL C
#define UC_MACRO_NAME_1D5D7 0x1D5D7 // 𝗗 MATHEMATICAL SANS-SERIF BOLD CAPITAL D
#define UC_MACRO_NAME_1D5D8 0x1D5D8 // 𝗘 MATHEMATICAL SANS-SERIF BOLD CAPITAL E
#define UC_MACRO_NAME_1D5D9 0x1D5D9 // 𝗙 MATHEMATICAL SANS-SERIF BOLD CAPITAL F
#define UC_MACRO_NAME_1D5DA 0x1D5DA // 𝗚 MATHEMATICAL SANS-SERIF BOLD CAPITAL G
#define UC_MACRO_NAME_1D5DB 0x1D5DB // 𝗛 MATHEMATICAL SANS-SERIF BOLD CAPITAL H
#define UC_MACRO_NAME_1D5DC 0x1D5DC // 𝗜 MATHEMATICAL SANS-SERIF BOLD CAPITAL I
#define UC_MACRO_NAME_1D5DD 0x1D5DD // 𝗝 MATHEMATICAL SANS-SERIF BOLD CAPITAL J
#define UC_MACRO_NAME_1D5DE 0x1D5DE // 𝗞 MATHEMATICAL SANS-SERIF BOLD CAPITAL K
#define UC_MACRO_NAME_1D5DF 0x1D5DF // 𝗟 MATHEMATICAL SANS-SERIF BOLD CAPITAL L
#define UC_MACRO_NAME_1D5E0 0x1D5E0 // 𝗠 MATHEMATICAL SANS-SERIF BOLD CAPITAL M
#define UC_MACRO_NAME_1D5E1 0x1D5E1 // 𝗡 MATHEMATICAL SANS-SERIF BOLD CAPITAL N
#define UC_MACRO_NAME_1D5E2 0x1D5E2 // 𝗢 MATHEMATICAL SANS-SERIF BOLD CAPITAL O
#define UC_MACRO_NAME_1D5E3 0x1D5E3 // 𝗣 MATHEMATICAL SANS-SERIF BOLD CAPITAL P
#define UC_MACRO_NAME_1D5E4 0x1D5E4 // 𝗤 MATHEMATICAL SANS-SERIF BOLD CAPITAL Q
#define UC_MACRO_NAME_1D5E5 0x1D5E5 // 𝗥 MATHEMATICAL SANS-SERIF BOLD CAPITAL R
#define UC_MACRO_NAME_1D5E6 0x1D5E6 // 𝗦 MATHEMATICAL SANS-SERIF BOLD CAPITAL S
#define UC_MACRO_NAME_1D5E7 0x1D5E7 // 𝗧 MATHEMATICAL SANS-SERIF BOLD CAPITAL T
#define UC_MACRO_NAME_1D5E8 0x1D5E8 // 𝗨 MATHEMATICAL SANS-SERIF BOLD CAPITAL U
#define UC_MACRO_NAME_1D5E9 0x1D5E9 // 𝗩 MATHEMATICAL SANS-SERIF BOLD CAPITAL V
#define UC_MACRO_NAME_1D5EA 0x1D5EA // 𝗪 MATHEMATICAL SANS-SERIF BOLD CAPITAL W
#define UC_MACRO_NAME_1D5EB 0x1D5EB // 𝗫 MATHEMATICAL SANS-SERIF BOLD CAPITAL X
#define UC_MACRO_NAME_1D5EC 0x1D5EC // 𝗬 MATHEMATICAL SANS-SERIF BOLD CAPITAL Y
#define UC_MACRO_NAME_1D5ED 0x1D5ED // 𝗭 MATHEMATICAL SANS-SERIF BOLD CAPITAL Z
#define UC_MACRO_NAME_1D5EE 0x1D5EE // 𝗮 MATHEMATICAL SANS-SERIF BOLD SMALL A
#define UC_MACRO_NAME_1D5EF 0x1D5EF // 𝗯 MATHEMATICAL SANS-SERIF BOLD SMALL B
#define UC_MACRO_NAME_1D5F0 0x1D5F0 // 𝗰 MATHEMATICAL SANS-SERIF BOLD SMALL C
#define UC_MACRO_NAME_1D5F1 0x1D5F1 // 𝗱 MATHEMATICAL SANS-SERIF BOLD SMALL D
#define UC_MACRO_NAME_1D5F2 0x1D5F2 // 𝗲 MATHEMATICAL SANS-SERIF BOLD SMALL E
#define UC_MACRO_NAME_1D5F3 0x1D5F3 // 𝗳 MATHEMATICAL SANS-SERIF BOLD SMALL F
#define UC_MACRO_NAME_1D5F4 0x1D5F4 // 𝗴 MATHEMATICAL SANS-SERIF BOLD SMALL G
#define UC_MACRO_NAME_1D5F5 0x1D5F5 // 𝗵 MATHEMATICAL SANS-SERIF BOLD SMALL H
#define UC_MACRO_NAME_1D5F6 0x1D5F6 // 𝗶 MATHEMATICAL SANS-SERIF BOLD SMALL I
#define UC_MACRO_NAME_1D5F7 0x1D5F7 // 𝗷 MATHEMATICAL SANS-SERIF BOLD SMALL J
#define UC_MACRO_NAME_1D5F8 0x1D5F8 // 𝗸 MATHEMATICAL SANS-SERIF BOLD SMALL K
#define UC_MACRO_NAME_1D5F9 0x1D5F9 // 𝗹 MATHEMATICAL SANS-SERIF BOLD SMALL L
#define UC_MACRO_NAME_1D5FA 0x1D5FA // 𝗺 MATHEMATICAL SANS-SERIF BOLD SMALL M
#define UC_MACRO_NAME_1D5FB 0x1D5FB // 𝗻 MATHEMATICAL SANS-SERIF BOLD SMALL N
#define UC_MACRO_NAME_1D5FC 0x1D5FC // 𝗼 MATHEMATICAL SANS-SERIF BOLD SMALL O
#define UC_MACRO_NAME_1D5FD 0x1D5FD // 𝗽 MATHEMATICAL SANS-SERIF BOLD SMALL P
#define UC_MACRO_NAME_1D5FE 0x1D5FE // 𝗾 MATHEMATICAL SANS-SERIF BOLD SMALL Q
#define UC_MACRO_NAME_1D5FF 0x1D5FF // 𝗿 MATHEMATICAL SANS-SERIF BOLD SMALL R
#define UC_MACRO_NAME_1D600 0x1D600 // 𝘀 MATHEMATICAL SANS-SERIF BOLD SMALL S
#define UC_MACRO_NAME_1D601 0x1D601 // 𝘁 MATHEMATICAL SANS-SERIF BOLD SMALL T
#define UC_MACRO_NAME_1D602 0x1D602 // 𝘂 MATHEMATICAL SANS-SERIF BOLD SMALL U
#define UC_MACRO_NAME_1D603 0x1D603 // 𝘃 MATHEMATICAL SANS-SERIF BOLD SMALL V
#define UC_MACRO_NAME_1D604 0x1D604 // 𝘄 MATHEMATICAL SANS-SERIF BOLD SMALL W
#define UC_MACRO_NAME_1D605 0x1D605 // 𝘅 MATHEMATICAL SANS-SERIF BOLD SMALL X
#define UC_MACRO_NAME_1D606 0x1D606 // 𝘆 MATHEMATICAL SANS-SERIF BOLD SMALL Y
#define UC_MACRO_NAME_1D607 0x1D607 // 𝘇 MATHEMATICAL SANS-SERIF BOLD SMALL Z
#define UC_MACRO_NAME_1D608 0x1D608 // 𝘈 MATHEMATICAL SANS-SERIF ITALIC CAPITAL A
#define UC_MACRO_NAME_1D609 0x1D609 // 𝘉 MATHEMATICAL SANS-SERIF ITALIC CAPITAL B
#define UC_MACRO_NAME_1D60A 0x1D60A // 𝘊 MATHEMATICAL SANS-SERIF ITALIC CAPITAL C
#define UC_MACRO_NAME_1D60B 0x1D60B // 𝘋 MATHEMATICAL SANS-SERIF ITALIC CAPITAL D
#define UC_MACRO_NAME_1D60C 0x1D60C // 𝘌 MATHEMATICAL SANS-SERIF ITALIC CAPITAL E
#define UC_MACRO_NAME_1D60D 0x1D60D // 𝘍 MATHEMATICAL SANS-SERIF ITALIC CAPITAL F
#define UC_MACRO_NAME_1D60E 0x1D60E // 𝘎 MATHEMATICAL SANS-SERIF ITALIC CAPITAL G
#define UC_MACRO_NAME_1D60F 0x1D60F // 𝘏 MATHEMATICAL SANS-SERIF ITALIC CAPITAL H
#define UC_MACRO_NAME_1D610 0x1D610 // 𝘐 MATHEMATICAL SANS-SERIF ITALIC CAPITAL I
#define UC_MACRO_NAME_1D611 0x1D611 // 𝘑 MATHEMATICAL SANS-SERIF ITALIC CAPITAL J
#define UC_MACRO_NAME_1D612 0x1D612 // 𝘒 MATHEMATICAL SANS-SERIF ITALIC CAPITAL K
#define UC_MACRO_NAME_1D613 0x1D613 // 𝘓 MATHEMATICAL SANS-SERIF ITALIC CAPITAL L
#define UC_MACRO_NAME_1D614 0x1D614 // 𝘔 MATHEMATICAL SANS-SERIF ITALIC CAPITAL M
#define UC_MACRO_NAME_1D615 0x1D615 // 𝘕 MATHEMATICAL SANS-SERIF ITALIC CAPITAL N
#define UC_MACRO_NAME_1D616 0x1D616 // 𝘖 MATHEMATICAL SANS-SERIF ITALIC CAPITAL O
#define UC_MACRO_NAME_1D617 0x1D617 // 𝘗 MATHEMATICAL SANS-SERIF ITALIC CAPITAL P
#define UC_MACRO_NAME_1D618 0x1D618 // 𝘘 MATHEMATICAL SANS-SERIF ITALIC CAPITAL Q
#define UC_MACRO_NAME_1D619 0x1D619 // 𝘙 MATHEMATICAL SANS-SERIF ITALIC CAPITAL R
#define UC_MACRO_NAME_1D61A 0x1D61A // 𝘚 MATHEMATICAL SANS-SERIF ITALIC CAPITAL S
#define UC_MACRO_NAME_1D61B 0x1D61B // 𝘛 MATHEMATICAL SANS-SERIF ITALIC CAPITAL T
#define UC_MACRO_NAME_1D61C 0x1D61C // 𝘜 MATHEMATICAL SANS-SERIF ITALIC CAPITAL U
#define UC_MACRO_NAME_1D61D 0x1D61D // 𝘝 MATHEMATICAL SANS-SERIF ITALIC CAPITAL V
#define UC_MACRO_NAME_1D61E 0x1D61E // 𝘞 MATHEMATICAL SANS-SERIF ITALIC CAPITAL W
#define UC_MACRO_NAME_1D61F 0x1D61F // 𝘟 MATHEMATICAL SANS-SERIF ITALIC CAPITAL X
#define UC_MACRO_NAME_1D620 0x1D620 // 𝘠 MATHEMATICAL SANS-SERIF ITALIC CAPITAL Y
#define UC_MACRO_NAME_1D621 0x1D621 // 𝘡 MATHEMATICAL SANS-SERIF ITALIC CAPITAL Z
#define UC_MACRO_NAME_1D622 0x1D622 // 𝘢 MATHEMATICAL SANS-SERIF ITALIC SMALL A
#define UC_MACRO_NAME_1D623 0x1D623 // 𝘣 MATHEMATICAL SANS-SERIF ITALIC SMALL B
#define UC_MACRO_NAME_1D624 0x1D624 // 𝘤 MATHEMATICAL SANS-SERIF ITALIC SMALL C
#define UC_MACRO_NAME_1D625 0x1D625 // 𝘥 MATHEMATICAL SANS-SERIF ITALIC SMALL D
#define UC_MACRO_NAME_1D626 0x1D626 // 𝘦 MATHEMATICAL SANS-SERIF ITALIC SMALL E
#define UC_MACRO_NAME_1D627 0x1D627 // 𝘧 MATHEMATICAL SANS-SERIF ITALIC SMALL F
#define UC_MACRO_NAME_1D628 0x1D628 // 𝘨 MATHEMATICAL SANS-SERIF ITALIC SMALL G
#define UC_MACRO_NAME_1D629 0x1D629 // 𝘩 MATHEMATICAL SANS-SERIF ITALIC SMALL H
#define UC_MACRO_NAME_1D62A 0x1D62A // 𝘪 MATHEMATICAL SANS-SERIF ITALIC SMALL I
#define UC_MACRO_NAME_1D62B 0x1D62B // 𝘫 MATHEMATICAL SANS-SERIF ITALIC SMALL J
#define UC_MACRO_NAME_1D62C 0x1D62C // 𝘬 MATHEMATICAL SANS-SERIF ITALIC SMALL K
#define UC_MACRO_NAME_1D62D 0x1D62D // 𝘭 MATHEMATICAL SANS-SERIF ITALIC SMALL L
#define UC_MACRO_NAME_1D62E 0x1D62E // 𝘮 MATHEMATICAL SANS-SERIF ITALIC SMALL M
#define UC_MACRO_NAME_1D62F 0x1D62F // 𝘯 MATHEMATICAL SANS-SERIF ITALIC SMALL N
#define UC_MACRO_NAME_1D630 0x1D630 // 𝘰 MATHEMATICAL SANS-SERIF ITALIC SMALL O
#define UC_MACRO_NAME_1D631 0x1D631 // 𝘱 MATHEMATICAL SANS-SERIF ITALIC SMALL P
#define UC_MACRO_NAME_1D632 0x1D632 // 𝘲 MATHEMATICAL SANS-SERIF ITALIC SMALL Q
#define UC_MACRO_NAME_1D633 0x1D633 // 𝘳 MATHEMATICAL SANS-SERIF ITALIC SMALL R
#define UC_MACRO_NAME_1D634 0x1D634 // 𝘴 MATHEMATICAL SANS-SERIF ITALIC SMALL S
#define UC_MACRO_NAME_1D635 0x1D635 // 𝘵 MATHEMATICAL SANS-SERIF ITALIC SMALL T
#define UC_MACRO_NAME_1D636 0x1D636 // 𝘶 MATHEMATICAL SANS-SERIF ITALIC SMALL U
#define UC_MACRO_NAME_1D637 0x1D637 // 𝘷 MATHEMATICAL SANS-SERIF ITALIC SMALL V
#define UC_MACRO_NAME_1D638 0x1D638 // 𝘸 MATHEMATICAL SANS-SERIF ITALIC SMALL W
#define UC_MACRO_NAME_1D639 0x1D639 // 𝘹 MATHEMATICAL SANS-SERIF ITALIC SMALL X
#define UC_MACRO_NAME_1D63A 0x1D63A // 𝘺 MATHEMATICAL SANS-SERIF ITALIC SMALL Y
#define UC_MACRO_NAME_1D63B 0x1D63B // 𝘻 MATHEMATICAL SANS-SERIF ITALIC SMALL Z
#define UC_MACRO_NAME_1D63C 0x1D63C // 𝘼 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL A
#define UC_MACRO_NAME_1D63D 0x1D63D // 𝘽 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL B
#define UC_MACRO_NAME_1D63E 0x1D63E // 𝘾 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL C
#define UC_MACRO_NAME_1D63F 0x1D63F // 𝘿 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL D
#define UC_MACRO_NAME_1D640 0x1D640 // 𝙀 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL E
#define UC_MACRO_NAME_1D641 0x1D641 // 𝙁 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL F
#define UC_MACRO_NAME_1D642 0x1D642 // 𝙂 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL G
#define UC_MACRO_NAME_1D643 0x1D643 // 𝙃 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL H
#define UC_MACRO_NAME_1D644 0x1D644 // 𝙄 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL I
#define UC_MACRO_NAME_1D645 0x1D645 // 𝙅 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL J
#define UC_MACRO_NAME_1D646 0x1D646 // 𝙆 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL K
#define UC_MACRO_NAME_1D647 0x1D647 // 𝙇 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL L
#define UC_MACRO_NAME_1D648 0x1D648 // 𝙈 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL M
#define UC_MACRO_NAME_1D649 0x1D649 // 𝙉 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL N
#define UC_MACRO_NAME_1D64A 0x1D64A // 𝙊 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL O
#define UC_MACRO_NAME_1D64B 0x1D64B // 𝙋 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL P
#define UC_MACRO_NAME_1D64C 0x1D64C // 𝙌 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL Q
#define UC_MACRO_NAME_1D64D 0x1D64D // 𝙍 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL R
#define UC_MACRO_NAME_1D64E 0x1D64E // 𝙎 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL S
#define UC_MACRO_NAME_1D64F 0x1D64F // 𝙏 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL T
#define UC_MACRO_NAME_1D650 0x1D650 // 𝙐 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL U
#define UC_MACRO_NAME_1D651 0x1D651 // 𝙑 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL V
#define UC_MACRO_NAME_1D652 0x1D652 // 𝙒 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL W
#define UC_MACRO_NAME_1D653 0x1D653 // 𝙓 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL X
#define UC_MACRO_NAME_1D654 0x1D654 // 𝙔 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL Y
#define UC_MACRO_NAME_1D655 0x1D655 // 𝙕 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL Z
#define UC_MACRO_NAME_1D656 0x1D656 // 𝙖 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL A
#define UC_MACRO_NAME_1D657 0x1D657 // 𝙗 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL B
#define UC_MACRO_NAME_1D658 0x1D658 // 𝙘 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL C
#define UC_MACRO_NAME_1D659 0x1D659 // 𝙙 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL D
#define UC_MACRO_NAME_1D65A 0x1D65A // 𝙚 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL E
#define UC_MACRO_NAME_1D65B 0x1D65B // 𝙛 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL F
#define UC_MACRO_NAME_1D65C 0x1D65C // 𝙜 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL G
#define UC_MACRO_NAME_1D65D 0x1D65D // 𝙝 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL H
#define UC_MACRO_NAME_1D65E 0x1D65E // 𝙞 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL I
#define UC_MACRO_NAME_1D65F 0x1D65F // 𝙟 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL J
#define UC_MACRO_NAME_1D660 0x1D660 // 𝙠 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL K
#define UC_MACRO_NAME_1D661 0x1D661 // 𝙡 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL L
#define UC_MACRO_NAME_1D662 0x1D662 // 𝙢 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL M
#define UC_MACRO_NAME_1D663 0x1D663 // 𝙣 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL N
#define UC_MACRO_NAME_1D664 0x1D664 // 𝙤 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL O
#define UC_MACRO_NAME_1D665 0x1D665 // 𝙥 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL P
#define UC_MACRO_NAME_1D666 0x1D666 // 𝙦 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL Q
#define UC_MACRO_NAME_1D667 0x1D667 // 𝙧 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL R
#define UC_MACRO_NAME_1D668 0x1D668 // 𝙨 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL S
#define UC_MACRO_NAME_1D669 0x1D669 // 𝙩 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL T
#define UC_MACRO_NAME_1D66A 0x1D66A // 𝙪 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL U
#define UC_MACRO_NAME_1D66B 0x1D66B // 𝙫 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL V
#define UC_MACRO_NAME_1D66C 0x1D66C // 𝙬 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL W
#define UC_MACRO_NAME_1D66D 0x1D66D // 𝙭 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL X
#define UC_MACRO_NAME_1D66E 0x1D66E // 𝙮 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL Y
#define UC_MACRO_NAME_1D66F 0x1D66F // 𝙯 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL Z
#define UC_MACRO_NAME_1D670 0x1D670 // 𝙰 MATHEMATICAL MONOSPACE CAPITAL A
#define UC_MACRO_NAME_1D671 0x1D671 // 𝙱 MATHEMATICAL MONOSPACE CAPITAL B
#define UC_MACRO_NAME_1D672 0x1D672 // 𝙲 MATHEMATICAL MONOSPACE CAPITAL C
#define UC_MACRO_NAME_1D673 0x1D673 // 𝙳 MATHEMATICAL MONOSPACE CAPITAL D
#define UC_MACRO_NAME_1D674 0x1D674 // 𝙴 MATHEMATICAL MONOSPACE CAPITAL E
#define UC_MACRO_NAME_1D675 0x1D675 // 𝙵 MATHEMATICAL MONOSPACE CAPITAL F
#define UC_MACRO_NAME_1D676 0x1D676 // 𝙶 MATHEMATICAL MONOSPACE CAPITAL G
#define UC_MACRO_NAME_1D677 0x1D677 // 𝙷 MATHEMATICAL MONOSPACE CAPITAL H
#define UC_MACRO_NAME_1D678 0x1D678 // 𝙸 MATHEMATICAL MONOSPACE CAPITAL I
#define UC_MACRO_NAME_1D679 0x1D679 // 𝙹 MATHEMATICAL MONOSPACE CAPITAL J
#define UC_MACRO_NAME_1D67A 0x1D67A // 𝙺 MATHEMATICAL MONOSPACE CAPITAL K
#define UC_MACRO_NAME_1D67B 0x1D67B // 𝙻 MATHEMATICAL MONOSPACE CAPITAL L
#define UC_MACRO_NAME_1D67C 0x1D67C // 𝙼 MATHEMATICAL MONOSPACE CAPITAL M
#define UC_MACRO_NAME_1D67D 0x1D67D // 𝙽 MATHEMATICAL MONOSPACE CAPITAL N
#define UC_MACRO_NAME_1D67E 0x1D67E // 𝙾 MATHEMATICAL MONOSPACE CAPITAL O
#define UC_MACRO_NAME_1D67F 0x1D67F // 𝙿 MATHEMATICAL MONOSPACE CAPITAL P
#define UC_MACRO_NAME_1D680 0x1D680 // 𝚀 MATHEMATICAL MONOSPACE CAPITAL Q
#define UC_MACRO_NAME_1D681 0x1D681 // 𝚁 MATHEMATICAL MONOSPACE CAPITAL R
#define UC_MACRO_NAME_1D682 0x1D682 // 𝚂 MATHEMATICAL MONOSPACE CAPITAL S
#define UC_MACRO_NAME_1D683 0x1D683 // 𝚃 MATHEMATICAL MONOSPACE CAPITAL T
#define UC_MACRO_NAME_1D684 0x1D684 // 𝚄 MATHEMATICAL MONOSPACE CAPITAL U
#define UC_MACRO_NAME_1D685 0x1D685 // 𝚅 MATHEMATICAL MONOSPACE CAPITAL V
#define UC_MACRO_NAME_1D686 0x1D686 // 𝚆 MATHEMATICAL MONOSPACE CAPITAL W
#define UC_MACRO_NAME_1D687 0x1D687 // 𝚇 MATHEMATICAL MONOSPACE CAPITAL X
#define UC_MACRO_NAME_1D688 0x1D688 // 𝚈 MATHEMATICAL MONOSPACE CAPITAL Y
#define UC_MACRO_NAME_1D689 0x1D689 // 𝚉 MATHEMATICAL MONOSPACE CAPITAL Z
#define UC_MACRO_NAME_1D68A 0x1D68A // 𝚊 MATHEMATICAL MONOSPACE SMALL A
#define UC_MACRO_NAME_1D68B 0x1D68B // 𝚋 MATHEMATICAL MONOSPACE SMALL B
#define UC_MACRO_NAME_1D68C 0x1D68C // 𝚌 MATHEMATICAL MONOSPACE SMALL C
#define UC_MACRO_NAME_1D68D 0x1D68D // 𝚍 MATHEMATICAL MONOSPACE SMALL D
#define UC_MACRO_NAME_1D68E 0x1D68E // 𝚎 MATHEMATICAL MONOSPACE SMALL E
#define UC_MACRO_NAME_1D68F 0x1D68F // 𝚏 MATHEMATICAL MONOSPACE SMALL F
#define UC_MACRO_NAME_1D690 0x1D690 // 𝚐 MATHEMATICAL MONOSPACE SMALL G
#define UC_MACRO_NAME_1D691 0x1D691 // 𝚑 MATHEMATICAL MONOSPACE SMALL H
#define UC_MACRO_NAME_1D692 0x1D692 // 𝚒 MATHEMATICAL MONOSPACE SMALL I
#define UC_MACRO_NAME_1D693 0x1D693 // 𝚓 MATHEMATICAL MONOSPACE SMALL J
#define UC_MACRO_NAME_1D694 0x1D694 // 𝚔 MATHEMATICAL MONOSPACE SMALL K
#define UC_MACRO_NAME_1D695 0x1D695 // 𝚕 MATHEMATICAL MONOSPACE SMALL L
#define UC_MACRO_NAME_1D696 0x1D696 // 𝚖 MATHEMATICAL MONOSPACE SMALL M
#define UC_MACRO_NAME_1D697 0x1D697 // 𝚗 MATHEMATICAL MONOSPACE SMALL N
#define UC_MACRO_NAME_1D698 0x1D698 // 𝚘 MATHEMATICAL MONOSPACE SMALL O
#define UC_MACRO_NAME_1D699 0x1D699 // 𝚙 MATHEMATICAL MONOSPACE SMALL P
#define UC_MACRO_NAME_1D69A 0x1D69A // 𝚚 MATHEMATICAL MONOSPACE SMALL Q
#define UC_MACRO_NAME_1D69B 0x1D69B // 𝚛 MATHEMATICAL MONOSPACE SMALL R
#define UC_MACRO_NAME_1D69C 0x1D69C // 𝚜 MATHEMATICAL MONOSPACE SMALL S
#define UC_MACRO_NAME_1D69D 0x1D69D // 𝚝 MATHEMATICAL MONOSPACE SMALL T
#define UC_MACRO_NAME_1D69E 0x1D69E // 𝚞 MATHEMATICAL MONOSPACE SMALL U
#define UC_MACRO_NAME_1D69F 0x1D69F // 𝚟 MATHEMATICAL MONOSPACE SMALL V
#define UC_MACRO_NAME_1D6A0 0x1D6A0 // 𝚠 MATHEMATICAL MONOSPACE SMALL W
#define UC_MACRO_NAME_1D6A1 0x1D6A1 // 𝚡 MATHEMATICAL MONOSPACE SMALL X
#define UC_MACRO_NAME_1D6A2 0x1D6A2 // 𝚢 MATHEMATICAL MONOSPACE SMALL Y
#define UC_MACRO_NAME_1D6A3 0x1D6A3 // 𝚣 MATHEMATICAL MONOSPACE SMALL Z
#define UC_MACRO_NAME_1D6A4 0x1D6A4 // 𝚤 MATHEMATICAL ITALIC SMALL DOTLESS I
#define UC_MACRO_NAME_1D6A5 0x1D6A5 // 𝚥 MATHEMATICAL ITALIC SMALL DOTLESS J
#define UC_MACRO_NAME_1D6A8 0x1D6A8 // 𝚨 MATHEMATICAL BOLD CAPITAL ALPHA
#define UC_MACRO_NAME_1D6A9 0x1D6A9 // 𝚩 MATHEMATICAL BOLD CAPITAL BETA
#define UC_MACRO_NAME_1D6AA 0x1D6AA // 𝚪 MATHEMATICAL BOLD CAPITAL GAMMA
#define UC_MACRO_NAME_1D6AB 0x1D6AB // 𝚫 MATHEMATICAL BOLD CAPITAL DELTA
#define UC_MACRO_NAME_1D6AC 0x1D6AC // 𝚬 MATHEMATICAL BOLD CAPITAL EPSILON
#define UC_MACRO_NAME_1D6AD 0x1D6AD // 𝚭 MATHEMATICAL BOLD CAPITAL ZETA
#define UC_MACRO_NAME_1D6AE 0x1D6AE // 𝚮 MATHEMATICAL BOLD CAPITAL ETA
#define UC_MACRO_NAME_1D6AF 0x1D6AF // 𝚯 MATHEMATICAL BOLD CAPITAL THETA
#define UC_MACRO_NAME_1D6B0 0x1D6B0 // 𝚰 MATHEMATICAL BOLD CAPITAL IOTA
#define UC_MACRO_NAME_1D6B1 0x1D6B1 // 𝚱 MATHEMATICAL BOLD CAPITAL KAPPA
#define UC_MACRO_NAME_1D6B2 0x1D6B2 // 𝚲 MATHEMATICAL BOLD CAPITAL LAMDA
#define UC_MACRO_NAME_1D6B3 0x1D6B3 // 𝚳 MATHEMATICAL BOLD CAPITAL MU
#define UC_MACRO_NAME_1D6B4 0x1D6B4 // 𝚴 MATHEMATICAL BOLD CAPITAL NU
#define UC_MACRO_NAME_1D6B5 0x1D6B5 // 𝚵 MATHEMATICAL BOLD CAPITAL XI
#define UC_MACRO_NAME_1D6B6 0x1D6B6 // 𝚶 MATHEMATICAL BOLD CAPITAL OMICRON
#define UC_MACRO_NAME_1D6B7 0x1D6B7 // 𝚷 MATHEMATICAL BOLD CAPITAL PI
#define UC_MACRO_NAME_1D6B8 0x1D6B8 // 𝚸 MATHEMATICAL BOLD CAPITAL RHO
#define UC_MACRO_NAME_1D6B9 0x1D6B9 // 𝚹 MATHEMATICAL BOLD CAPITAL THETA SYMBOL
#define UC_MACRO_NAME_1D6BA 0x1D6BA // 𝚺 MATHEMATICAL BOLD CAPITAL SIGMA
#define UC_MACRO_NAME_1D6BB 0x1D6BB // 𝚻 MATHEMATICAL BOLD CAPITAL TAU
#define UC_MACRO_NAME_1D6BC 0x1D6BC // 𝚼 MATHEMATICAL BOLD CAPITAL UPSILON
#define UC_MACRO_NAME_1D6BD 0x1D6BD // 𝚽 MATHEMATICAL BOLD CAPITAL PHI
#define UC_MACRO_NAME_1D6BE 0x1D6BE // 𝚾 MATHEMATICAL BOLD CAPITAL CHI
#define UC_MACRO_NAME_1D6BF 0x1D6BF // 𝚿 MATHEMATICAL BOLD CAPITAL PSI
#define UC_MACRO_NAME_1D6C0 0x1D6C0 // 𝛀 MATHEMATICAL BOLD CAPITAL OMEGA
#define UC_MACRO_NAME_1D6C1 0x1D6C1 // 𝛁 MATHEMATICAL BOLD NABLA
#define UC_MACRO_NAME_1D6C2 0x1D6C2 // 𝛂 MATHEMATICAL BOLD SMALL ALPHA
#define UC_MACRO_NAME_1D6C3 0x1D6C3 // 𝛃 MATHEMATICAL BOLD SMALL BETA
#define UC_MACRO_NAME_1D6C4 0x1D6C4 // 𝛄 MATHEMATICAL BOLD SMALL GAMMA
#define UC_MACRO_NAME_1D6C5 0x1D6C5 // 𝛅 MATHEMATICAL BOLD SMALL DELTA
#define UC_MACRO_NAME_1D6C6 0x1D6C6 // 𝛆 MATHEMATICAL BOLD SMALL EPSILON
#define UC_MACRO_NAME_1D6C7 0x1D6C7 // 𝛇 MATHEMATICAL BOLD SMALL ZETA
#define UC_MACRO_NAME_1D6C8 0x1D6C8 // 𝛈 MATHEMATICAL BOLD SMALL ETA
#define UC_MACRO_NAME_1D6C9 0x1D6C9 // 𝛉 MATHEMATICAL BOLD SMALL THETA
#define UC_MACRO_NAME_1D6CA 0x1D6CA // 𝛊 MATHEMATICAL BOLD SMALL IOTA
#define UC_MACRO_NAME_1D6CB 0x1D6CB // 𝛋 MATHEMATICAL BOLD SMALL KAPPA
#define UC_MACRO_NAME_1D6CC 0x1D6CC // 𝛌 MATHEMATICAL BOLD SMALL LAMDA
#define UC_MACRO_NAME_1D6CD 0x1D6CD // 𝛍 MATHEMATICAL BOLD SMALL MU
#define UC_MACRO_NAME_1D6CE 0x1D6CE // 𝛎 MATHEMATICAL BOLD SMALL NU
#define UC_MACRO_NAME_1D6CF 0x1D6CF // 𝛏 MATHEMATICAL BOLD SMALL XI
#define UC_MACRO_NAME_1D6D0 0x1D6D0 // 𝛐 MATHEMATICAL BOLD SMALL OMICRON
#define UC_MACRO_NAME_1D6D1 0x1D6D1 // 𝛑 MATHEMATICAL BOLD SMALL PI
#define UC_MACRO_NAME_1D6D2 0x1D6D2 // 𝛒 MATHEMATICAL BOLD SMALL RHO
#define UC_MACRO_NAME_1D6D3 0x1D6D3 // 𝛓 MATHEMATICAL BOLD SMALL FINAL SIGMA
#define UC_MACRO_NAME_1D6D4 0x1D6D4 // 𝛔 MATHEMATICAL BOLD SMALL SIGMA
#define UC_MACRO_NAME_1D6D5 0x1D6D5 // 𝛕 MATHEMATICAL BOLD SMALL TAU
#define UC_MACRO_NAME_1D6D6 0x1D6D6 // 𝛖 MATHEMATICAL BOLD SMALL UPSILON
#define UC_MACRO_NAME_1D6D7 0x1D6D7 // 𝛗 MATHEMATICAL BOLD SMALL PHI
#define UC_MACRO_NAME_1D6D8 0x1D6D8 // 𝛘 MATHEMATICAL BOLD SMALL CHI
#define UC_MACRO_NAME_1D6D9 0x1D6D9 // 𝛙 MATHEMATICAL BOLD SMALL PSI
#define UC_MACRO_NAME_1D6DA 0x1D6DA // 𝛚 MATHEMATICAL BOLD SMALL OMEGA
#define UC_MACRO_NAME_1D6DB 0x1D6DB // 𝛛 MATHEMATICAL BOLD PARTIAL DIFFERENTIAL
#define UC_MACRO_NAME_1D6DC 0x1D6DC // 𝛜 MATHEMATICAL BOLD EPSILON SYMBOL
#define UC_MACRO_NAME_1D6DD 0x1D6DD // 𝛝 MATHEMATICAL BOLD THETA SYMBOL
#define UC_MACRO_NAME_1D6DE 0x1D6DE // 𝛞 MATHEMATICAL BOLD KAPPA SYMBOL
#define UC_MACRO_NAME_1D6DF 0x1D6DF // 𝛟 MATHEMATICAL BOLD PHI SYMBOL
#define UC_MACRO_NAME_1D6E0 0x1D6E0 // 𝛠 MATHEMATICAL BOLD RHO SYMBOL
#define UC_MACRO_NAME_1D6E1 0x1D6E1 // 𝛡 MATHEMATICAL BOLD PI SYMBOL
#define UC_MACRO_NAME_1D6E2 0x1D6E2 // 𝛢 MATHEMATICAL ITALIC CAPITAL ALPHA
#define UC_MACRO_NAME_1D6E3 0x1D6E3 // 𝛣 MATHEMATICAL ITALIC CAPITAL BETA
#define UC_MACRO_NAME_1D6E4 0x1D6E4 // 𝛤 MATHEMATICAL ITALIC CAPITAL GAMMA
#define UC_MACRO_NAME_1D6E5 0x1D6E5 // 𝛥 MATHEMATICAL ITALIC CAPITAL DELTA
#define UC_MACRO_NAME_1D6E6 0x1D6E6 // 𝛦 MATHEMATICAL ITALIC CAPITAL EPSILON
#define UC_MACRO_NAME_1D6E7 0x1D6E7 // 𝛧 MATHEMATICAL ITALIC CAPITAL ZETA
#define UC_MACRO_NAME_1D6E8 0x1D6E8 // 𝛨 MATHEMATICAL ITALIC CAPITAL ETA
#define UC_MACRO_NAME_1D6E9 0x1D6E9 // 𝛩 MATHEMATICAL ITALIC CAPITAL THETA
#define UC_MACRO_NAME_1D6EA 0x1D6EA // 𝛪 MATHEMATICAL ITALIC CAPITAL IOTA
#define UC_MACRO_NAME_1D6EB 0x1D6EB // 𝛫 MATHEMATICAL ITALIC CAPITAL KAPPA
#define UC_MACRO_NAME_1D6EC 0x1D6EC // 𝛬 MATHEMATICAL ITALIC CAPITAL LAMDA
#define UC_MACRO_NAME_1D6ED 0x1D6ED // 𝛭 MATHEMATICAL ITALIC CAPITAL MU
#define UC_MACRO_NAME_1D6EE 0x1D6EE // 𝛮 MATHEMATICAL ITALIC CAPITAL NU
#define UC_MACRO_NAME_1D6EF 0x1D6EF // 𝛯 MATHEMATICAL ITALIC CAPITAL XI
#define UC_MACRO_NAME_1D6F0 0x1D6F0 // 𝛰 MATHEMATICAL ITALIC CAPITAL OMICRON
#define UC_MACRO_NAME_1D6F1 0x1D6F1 // 𝛱 MATHEMATICAL ITALIC CAPITAL PI
#define UC_MACRO_NAME_1D6F2 0x1D6F2 // 𝛲 MATHEMATICAL ITALIC CAPITAL RHO
#define UC_MACRO_NAME_1D6F3 0x1D6F3 // 𝛳 MATHEMATICAL ITALIC CAPITAL THETA SYMBOL
#define UC_MACRO_NAME_1D6F4 0x1D6F4 // 𝛴 MATHEMATICAL ITALIC CAPITAL SIGMA
#define UC_MACRO_NAME_1D6F5 0x1D6F5 // 𝛵 MATHEMATICAL ITALIC CAPITAL TAU
#define UC_MACRO_NAME_1D6F6 0x1D6F6 // 𝛶 MATHEMATICAL ITALIC CAPITAL UPSILON
#define UC_MACRO_NAME_1D6F7 0x1D6F7 // 𝛷 MATHEMATICAL ITALIC CAPITAL PHI
#define UC_MACRO_NAME_1D6F8 0x1D6F8 // 𝛸 MATHEMATICAL ITALIC CAPITAL CHI
#define UC_MACRO_NAME_1D6F9 0x1D6F9 // 𝛹 MATHEMATICAL ITALIC CAPITAL PSI
#define UC_MACRO_NAME_1D6FA 0x1D6FA // 𝛺 MATHEMATICAL ITALIC CAPITAL OMEGA
#define UC_MACRO_NAME_1D6FB 0x1D6FB // 𝛻 MATHEMATICAL ITALIC NABLA
#define UC_MACRO_NAME_1D6FC 0x1D6FC // 𝛼 MATHEMATICAL ITALIC SMALL ALPHA
#define UC_MACRO_NAME_1D6FD 0x1D6FD // 𝛽 MATHEMATICAL ITALIC SMALL BETA
#define UC_MACRO_NAME_1D6FE 0x1D6FE // 𝛾 MATHEMATICAL ITALIC SMALL GAMMA
#define UC_MACRO_NAME_1D6FF 0x1D6FF // 𝛿 MATHEMATICAL ITALIC SMALL DELTA
#define UC_MACRO_NAME_1D700 0x1D700 // 𝜀 MATHEMATICAL ITALIC SMALL EPSILON
#define UC_MACRO_NAME_1D701 0x1D701 // 𝜁 MATHEMATICAL ITALIC SMALL ZETA
#define UC_MACRO_NAME_1D702 0x1D702 // 𝜂 MATHEMATICAL ITALIC SMALL ETA
#define UC_MACRO_NAME_1D703 0x1D703 // 𝜃 MATHEMATICAL ITALIC SMALL THETA
#define UC_MACRO_NAME_1D704 0x1D704 // 𝜄 MATHEMATICAL ITALIC SMALL IOTA
#define UC_MACRO_NAME_1D705 0x1D705 // 𝜅 MATHEMATICAL ITALIC SMALL KAPPA
#define UC_MACRO_NAME_1D706 0x1D706 // 𝜆 MATHEMATICAL ITALIC SMALL LAMDA
#define UC_MACRO_NAME_1D707 0x1D707 // 𝜇 MATHEMATICAL ITALIC SMALL MU
#define UC_MACRO_NAME_1D708 0x1D708 // 𝜈 MATHEMATICAL ITALIC SMALL NU
#define UC_MACRO_NAME_1D709 0x1D709 // 𝜉 MATHEMATICAL ITALIC SMALL XI
#define UC_MACRO_NAME_1D70A 0x1D70A // 𝜊 MATHEMATICAL ITALIC SMALL OMICRON
#define UC_MACRO_NAME_1D70B 0x1D70B // 𝜋 MATHEMATICAL ITALIC SMALL PI
#define UC_MACRO_NAME_1D70C 0x1D70C // 𝜌 MATHEMATICAL ITALIC SMALL RHO
#define UC_MACRO_NAME_1D70D 0x1D70D // 𝜍 MATHEMATICAL ITALIC SMALL FINAL SIGMA
#define UC_MACRO_NAME_1D70E 0x1D70E // 𝜎 MATHEMATICAL ITALIC SMALL SIGMA
#define UC_MACRO_NAME_1D70F 0x1D70F // 𝜏 MATHEMATICAL ITALIC SMALL TAU
#define UC_MACRO_NAME_1D710 0x1D710 // 𝜐 MATHEMATICAL ITALIC SMALL UPSILON
#define UC_MACRO_NAME_1D711 0x1D711 // 𝜑 MATHEMATICAL ITALIC SMALL PHI
#define UC_MACRO_NAME_1D712 0x1D712 // 𝜒 MATHEMATICAL ITALIC SMALL CHI
#define UC_MACRO_NAME_1D713 0x1D713 // 𝜓 MATHEMATICAL ITALIC SMALL PSI
#define UC_MACRO_NAME_1D714 0x1D714 // 𝜔 MATHEMATICAL ITALIC SMALL OMEGA
#define UC_MACRO_NAME_1D715 0x1D715 // 𝜕 MATHEMATICAL ITALIC PARTIAL DIFFERENTIAL
#define UC_MACRO_NAME_1D716 0x1D716 // 𝜖 MATHEMATICAL ITALIC EPSILON SYMBOL
#define UC_MACRO_NAME_1D717 0x1D717 // 𝜗 MATHEMATICAL ITALIC THETA SYMBOL
#define UC_MACRO_NAME_1D718 0x1D718 // 𝜘 MATHEMATICAL ITALIC KAPPA SYMBOL
#define UC_MACRO_NAME_1D719 0x1D719 // 𝜙 MATHEMATICAL ITALIC PHI SYMBOL
#define UC_MACRO_NAME_1D71A 0x1D71A // 𝜚 MATHEMATICAL ITALIC RHO SYMBOL
#define UC_MACRO_NAME_1D71B 0x1D71B // 𝜛 MATHEMATICAL ITALIC PI SYMBOL
#define UC_MACRO_NAME_1D71C 0x1D71C // 𝜜 MATHEMATICAL BOLD ITALIC CAPITAL ALPHA
#define UC_MACRO_NAME_1D71D 0x1D71D // 𝜝 MATHEMATICAL BOLD ITALIC CAPITAL BETA
#define UC_MACRO_NAME_1D71E 0x1D71E // 𝜞 MATHEMATICAL BOLD ITALIC CAPITAL GAMMA
#define UC_MACRO_NAME_1D71F 0x1D71F // 𝜟 MATHEMATICAL BOLD ITALIC CAPITAL DELTA
#define UC_MACRO_NAME_1D720 0x1D720 // 𝜠 MATHEMATICAL BOLD ITALIC CAPITAL EPSILON
#define UC_MACRO_NAME_1D721 0x1D721 // 𝜡 MATHEMATICAL BOLD ITALIC CAPITAL ZETA
#define UC_MACRO_NAME_1D722 0x1D722 // 𝜢 MATHEMATICAL BOLD ITALIC CAPITAL ETA
#define UC_MACRO_NAME_1D723 0x1D723 // 𝜣 MATHEMATICAL BOLD ITALIC CAPITAL THETA
#define UC_MACRO_NAME_1D724 0x1D724 // 𝜤 MATHEMATICAL BOLD ITALIC CAPITAL IOTA
#define UC_MACRO_NAME_1D725 0x1D725 // 𝜥 MATHEMATICAL BOLD ITALIC CAPITAL KAPPA
#define UC_MACRO_NAME_1D726 0x1D726 // 𝜦 MATHEMATICAL BOLD ITALIC CAPITAL LAMDA
#define UC_MACRO_NAME_1D727 0x1D727 // 𝜧 MATHEMATICAL BOLD ITALIC CAPITAL MU
#define UC_MACRO_NAME_1D728 0x1D728 // 𝜨 MATHEMATICAL BOLD ITALIC CAPITAL NU
#define UC_MACRO_NAME_1D729 0x1D729 // 𝜩 MATHEMATICAL BOLD ITALIC CAPITAL XI
#define UC_MACRO_NAME_1D72A 0x1D72A // 𝜪 MATHEMATICAL BOLD ITALIC CAPITAL OMICRON
#define UC_MACRO_NAME_1D72B 0x1D72B // 𝜫 MATHEMATICAL BOLD ITALIC CAPITAL PI
#define UC_MACRO_NAME_1D72C 0x1D72C // 𝜬 MATHEMATICAL BOLD ITALIC CAPITAL RHO
#define UC_MACRO_NAME_1D72D 0x1D72D // 𝜭 MATHEMATICAL BOLD ITALIC CAPITAL THETA SYMBOL
#define UC_MACRO_NAME_1D72E 0x1D72E // 𝜮 MATHEMATICAL BOLD ITALIC CAPITAL SIGMA
#define UC_MACRO_NAME_1D72F 0x1D72F // 𝜯 MATHEMATICAL BOLD ITALIC CAPITAL TAU
#define UC_MACRO_NAME_1D730 0x1D730 // 𝜰 MATHEMATICAL BOLD ITALIC CAPITAL UPSILON
#define UC_MACRO_NAME_1D731 0x1D731 // 𝜱 MATHEMATICAL BOLD ITALIC CAPITAL PHI
#define UC_MACRO_NAME_1D732 0x1D732 // 𝜲 MATHEMATICAL BOLD ITALIC CAPITAL CHI
#define UC_MACRO_NAME_1D733 0x1D733 // 𝜳 MATHEMATICAL BOLD ITALIC CAPITAL PSI
#define UC_MACRO_NAME_1D734 0x1D734 // 𝜴 MATHEMATICAL BOLD ITALIC CAPITAL OMEGA
#define UC_MACRO_NAME_1D735 0x1D735 // 𝜵 MATHEMATICAL BOLD ITALIC NABLA
#define UC_MACRO_NAME_1D736 0x1D736 // 𝜶 MATHEMATICAL BOLD ITALIC SMALL ALPHA
#define UC_MACRO_NAME_1D737 0x1D737 // 𝜷 MATHEMATICAL BOLD ITALIC SMALL BETA
#define UC_MACRO_NAME_1D738 0x1D738 // 𝜸 MATHEMATICAL BOLD ITALIC SMALL GAMMA
#define UC_MACRO_NAME_1D739 0x1D739 // 𝜹 MATHEMATICAL BOLD ITALIC SMALL DELTA
#define UC_MACRO_NAME_1D73A 0x1D73A // 𝜺 MATHEMATICAL BOLD ITALIC SMALL EPSILON
#define UC_MACRO_NAME_1D73B 0x1D73B // 𝜻 MATHEMATICAL BOLD ITALIC SMALL ZETA
#define UC_MACRO_NAME_1D73C 0x1D73C // 𝜼 MATHEMATICAL BOLD ITALIC SMALL ETA
#define UC_MACRO_NAME_1D73D 0x1D73D // 𝜽 MATHEMATICAL BOLD ITALIC SMALL THETA
#define UC_MACRO_NAME_1D73E 0x1D73E // 𝜾 MATHEMATICAL BOLD ITALIC SMALL IOTA
#define UC_MACRO_NAME_1D73F 0x1D73F // 𝜿 MATHEMATICAL BOLD ITALIC SMALL KAPPA
#define UC_MACRO_NAME_1D740 0x1D740 // 𝝀 MATHEMATICAL BOLD ITALIC SMALL LAMDA
#define UC_MACRO_NAME_1D741 0x1D741 // 𝝁 MATHEMATICAL BOLD ITALIC SMALL MU
#define UC_MACRO_NAME_1D742 0x1D742 // 𝝂 MATHEMATICAL BOLD ITALIC SMALL NU
#define UC_MACRO_NAME_1D743 0x1D743 // 𝝃 MATHEMATICAL BOLD ITALIC SMALL XI
#define UC_MACRO_NAME_1D744 0x1D744 // 𝝄 MATHEMATICAL BOLD ITALIC SMALL OMICRON
#define UC_MACRO_NAME_1D745 0x1D745 // 𝝅 MATHEMATICAL BOLD ITALIC SMALL PI
#define UC_MACRO_NAME_1D746 0x1D746 // 𝝆 MATHEMATICAL BOLD ITALIC SMALL RHO
#define UC_MACRO_NAME_1D747 0x1D747 // 𝝇 MATHEMATICAL BOLD ITALIC SMALL FINAL SIGMA
#define UC_MACRO_NAME_1D748 0x1D748 // 𝝈 MATHEMATICAL BOLD ITALIC SMALL SIGMA
#define UC_MACRO_NAME_1D749 0x1D749 // 𝝉 MATHEMATICAL BOLD ITALIC SMALL TAU
#define UC_MACRO_NAME_1D74A 0x1D74A // 𝝊 MATHEMATICAL BOLD ITALIC SMALL UPSILON
#define UC_MACRO_NAME_1D74B 0x1D74B // 𝝋 MATHEMATICAL BOLD ITALIC SMALL PHI
#define UC_MACRO_NAME_1D74C 0x1D74C // 𝝌 MATHEMATICAL BOLD ITALIC SMALL CHI
#define UC_MACRO_NAME_1D74D 0x1D74D // 𝝍 MATHEMATICAL BOLD ITALIC SMALL PSI
#define UC_MACRO_NAME_1D74E 0x1D74E // 𝝎 MATHEMATICAL BOLD ITALIC SMALL OMEGA
#define UC_MACRO_NAME_1D74F 0x1D74F // 𝝏 MATHEMATICAL BOLD ITALIC PARTIAL DIFFERENTIAL
#define UC_MACRO_NAME_1D750 0x1D750 // 𝝐 MATHEMATICAL BOLD ITALIC EPSILON SYMBOL
#define UC_MACRO_NAME_1D751 0x1D751 // 𝝑 MATHEMATICAL BOLD ITALIC THETA SYMBOL
#define UC_MACRO_NAME_1D752 0x1D752 // 𝝒 MATHEMATICAL BOLD ITALIC KAPPA SYMBOL
#define UC_MACRO_NAME_1D753 0x1D753 // 𝝓 MATHEMATICAL BOLD ITALIC PHI SYMBOL
#define UC_MACRO_NAME_1D754 0x1D754 // 𝝔 MATHEMATICAL BOLD ITALIC RHO SYMBOL
#define UC_MACRO_NAME_1D755 0x1D755 // 𝝕 MATHEMATICAL BOLD ITALIC PI SYMBOL
#define UC_MACRO_NAME_1D756 0x1D756 // 𝝖 MATHEMATICAL SANS-SERIF BOLD CAPITAL ALPHA
#define UC_MACRO_NAME_1D757 0x1D757 // 𝝗 MATHEMATICAL SANS-SERIF BOLD CAPITAL BETA
#define UC_MACRO_NAME_1D758 0x1D758 // 𝝘 MATHEMATICAL SANS-SERIF BOLD CAPITAL GAMMA
#define UC_MACRO_NAME_1D759 0x1D759 // 𝝙 MATHEMATICAL SANS-SERIF BOLD CAPITAL DELTA
#define UC_MACRO_NAME_1D75A 0x1D75A // 𝝚 MATHEMATICAL SANS-SERIF BOLD CAPITAL EPSILON
#define UC_MACRO_NAME_1D75B 0x1D75B // 𝝛 MATHEMATICAL SANS-SERIF BOLD CAPITAL ZETA
#define UC_MACRO_NAME_1D75C 0x1D75C // 𝝜 MATHEMATICAL SANS-SERIF BOLD CAPITAL ETA
#define UC_MACRO_NAME_1D75D 0x1D75D // 𝝝 MATHEMATICAL SANS-SERIF BOLD CAPITAL THETA
#define UC_MACRO_NAME_1D75E 0x1D75E // 𝝞 MATHEMATICAL SANS-SERIF BOLD CAPITAL IOTA
#define UC_MACRO_NAME_1D75F 0x1D75F // 𝝟 MATHEMATICAL SANS-SERIF BOLD CAPITAL KAPPA
#define UC_MACRO_NAME_1D760 0x1D760 // 𝝠 MATHEMATICAL SANS-SERIF BOLD CAPITAL LAMDA
#define UC_MACRO_NAME_1D761 0x1D761 // 𝝡 MATHEMATICAL SANS-SERIF BOLD CAPITAL MU
#define UC_MACRO_NAME_1D762 0x1D762 // 𝝢 MATHEMATICAL SANS-SERIF BOLD CAPITAL NU
#define UC_MACRO_NAME_1D763 0x1D763 // 𝝣 MATHEMATICAL SANS-SERIF BOLD CAPITAL XI
#define UC_MACRO_NAME_1D764 0x1D764 // 𝝤 MATHEMATICAL SANS-SERIF BOLD CAPITAL OMICRON
#define UC_MACRO_NAME_1D765 0x1D765 // 𝝥 MATHEMATICAL SANS-SERIF BOLD CAPITAL PI
#define UC_MACRO_NAME_1D766 0x1D766 // 𝝦 MATHEMATICAL SANS-SERIF BOLD CAPITAL RHO
#define UC_MACRO_NAME_1D767 0x1D767 // 𝝧 MATHEMATICAL SANS-SERIF BOLD CAPITAL THETA SYMBOL
#define UC_MACRO_NAME_1D768 0x1D768 // 𝝨 MATHEMATICAL SANS-SERIF BOLD CAPITAL SIGMA
#define UC_MACRO_NAME_1D769 0x1D769 // 𝝩 MATHEMATICAL SANS-SERIF BOLD CAPITAL TAU
#define UC_MACRO_NAME_1D76A 0x1D76A // 𝝪 MATHEMATICAL SANS-SERIF BOLD CAPITAL UPSILON
#define UC_MACRO_NAME_1D76B 0x1D76B // 𝝫 MATHEMATICAL SANS-SERIF BOLD CAPITAL PHI
#define UC_MACRO_NAME_1D76C 0x1D76C // 𝝬 MATHEMATICAL SANS-SERIF BOLD CAPITAL CHI
#define UC_MACRO_NAME_1D76D 0x1D76D // 𝝭 MATHEMATICAL SANS-SERIF BOLD CAPITAL PSI
#define UC_MACRO_NAME_1D76E 0x1D76E // 𝝮 MATHEMATICAL SANS-SERIF BOLD CAPITAL OMEGA
#define UC_MACRO_NAME_1D76F 0x1D76F // 𝝯 MATHEMATICAL SANS-SERIF BOLD NABLA
#define UC_MACRO_NAME_1D770 0x1D770 // 𝝰 MATHEMATICAL SANS-SERIF BOLD SMALL ALPHA
#define UC_MACRO_NAME_1D771 0x1D771 // 𝝱 MATHEMATICAL SANS-SERIF BOLD SMALL BETA
#define UC_MACRO_NAME_1D772 0x1D772 // 𝝲 MATHEMATICAL SANS-SERIF BOLD SMALL GAMMA
#define UC_MACRO_NAME_1D773 0x1D773 // 𝝳 MATHEMATICAL SANS-SERIF BOLD SMALL DELTA
#define UC_MACRO_NAME_1D774 0x1D774 // 𝝴 MATHEMATICAL SANS-SERIF BOLD SMALL EPSILON
#define UC_MACRO_NAME_1D775 0x1D775 // 𝝵 MATHEMATICAL SANS-SERIF BOLD SMALL ZETA
#define UC_MACRO_NAME_1D776 0x1D776 // 𝝶 MATHEMATICAL SANS-SERIF BOLD SMALL ETA
#define UC_MACRO_NAME_1D777 0x1D777 // 𝝷 MATHEMATICAL SANS-SERIF BOLD SMALL THETA
#define UC_MACRO_NAME_1D778 0x1D778 // 𝝸 MATHEMATICAL SANS-SERIF BOLD SMALL IOTA
#define UC_MACRO_NAME_1D779 0x1D779 // 𝝹 MATHEMATICAL SANS-SERIF BOLD SMALL KAPPA
#define UC_MACRO_NAME_1D77A 0x1D77A // 𝝺 MATHEMATICAL SANS-SERIF BOLD SMALL LAMDA
#define UC_MACRO_NAME_1D77B 0x1D77B // 𝝻 MATHEMATICAL SANS-SERIF BOLD SMALL MU
#define UC_MACRO_NAME_1D77C 0x1D77C // 𝝼 MATHEMATICAL SANS-SERIF BOLD SMALL NU
#define UC_MACRO_NAME_1D77D 0x1D77D // 𝝽 MATHEMATICAL SANS-SERIF BOLD SMALL XI
#define UC_MACRO_NAME_1D77E 0x1D77E // 𝝾 MATHEMATICAL SANS-SERIF BOLD SMALL OMICRON
#define UC_MACRO_NAME_1D77F 0x1D77F // 𝝿 MATHEMATICAL SANS-SERIF BOLD SMALL PI
#define UC_MACRO_NAME_1D780 0x1D780 // 𝞀 MATHEMATICAL SANS-SERIF BOLD SMALL RHO
#define UC_MACRO_NAME_1D781 0x1D781 // 𝞁 MATHEMATICAL SANS-SERIF BOLD SMALL FINAL SIGMA
#define UC_MACRO_NAME_1D782 0x1D782 // 𝞂 MATHEMATICAL SANS-SERIF BOLD SMALL SIGMA
#define UC_MACRO_NAME_1D783 0x1D783 // 𝞃 MATHEMATICAL SANS-SERIF BOLD SMALL TAU
#define UC_MACRO_NAME_1D784 0x1D784 // 𝞄 MATHEMATICAL SANS-SERIF BOLD SMALL UPSILON
#define UC_MACRO_NAME_1D785 0x1D785 // 𝞅 MATHEMATICAL SANS-SERIF BOLD SMALL PHI
#define UC_MACRO_NAME_1D786 0x1D786 // 𝞆 MATHEMATICAL SANS-SERIF BOLD SMALL CHI
#define UC_MACRO_NAME_1D787 0x1D787 // 𝞇 MATHEMATICAL SANS-SERIF BOLD SMALL PSI
#define UC_MACRO_NAME_1D788 0x1D788 // 𝞈 MATHEMATICAL SANS-SERIF BOLD SMALL OMEGA
#define UC_MACRO_NAME_1D789 0x1D789 // 𝞉 MATHEMATICAL SANS-SERIF BOLD PARTIAL DIFFERENTIAL
#define UC_MACRO_NAME_1D78A 0x1D78A // 𝞊 MATHEMATICAL SANS-SERIF BOLD EPSILON SYMBOL
#define UC_MACRO_NAME_1D78B 0x1D78B // 𝞋 MATHEMATICAL SANS-SERIF BOLD THETA SYMBOL
#define UC_MACRO_NAME_1D78C 0x1D78C // 𝞌 MATHEMATICAL SANS-SERIF BOLD KAPPA SYMBOL
#define UC_MACRO_NAME_1D78D 0x1D78D // 𝞍 MATHEMATICAL SANS-SERIF BOLD PHI SYMBOL
#define UC_MACRO_NAME_1D78E 0x1D78E // 𝞎 MATHEMATICAL SANS-SERIF BOLD RHO SYMBOL
#define UC_MACRO_NAME_1D78F 0x1D78F // 𝞏 MATHEMATICAL SANS-SERIF BOLD PI SYMBOL
#define UC_MACRO_NAME_1D790 0x1D790 // 𝞐 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL ALPHA
#define UC_MACRO_NAME_1D791 0x1D791 // 𝞑 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL BETA
#define UC_MACRO_NAME_1D792 0x1D792 // 𝞒 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL GAMMA
#define UC_MACRO_NAME_1D793 0x1D793 // 𝞓 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL DELTA
#define UC_MACRO_NAME_1D794 0x1D794 // 𝞔 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL EPSILON
#define UC_MACRO_NAME_1D795 0x1D795 // 𝞕 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL ZETA
#define UC_MACRO_NAME_1D796 0x1D796 // 𝞖 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL ETA
#define UC_MACRO_NAME_1D797 0x1D797 // 𝞗 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL THETA
#define UC_MACRO_NAME_1D798 0x1D798 // 𝞘 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL IOTA
#define UC_MACRO_NAME_1D799 0x1D799 // 𝞙 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL KAPPA
#define UC_MACRO_NAME_1D79A 0x1D79A // 𝞚 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL LAMDA
#define UC_MACRO_NAME_1D79B 0x1D79B // 𝞛 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL MU
#define UC_MACRO_NAME_1D79C 0x1D79C // 𝞜 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL NU
#define UC_MACRO_NAME_1D79D 0x1D79D // 𝞝 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL XI
#define UC_MACRO_NAME_1D79E 0x1D79E // 𝞞 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL OMICRON
#define UC_MACRO_NAME_1D79F 0x1D79F // 𝞟 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL PI
#define UC_MACRO_NAME_1D7A0 0x1D7A0 // 𝞠 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL RHO
#define UC_MACRO_NAME_1D7A1 0x1D7A1 // 𝞡 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL THETA SYMBOL
#define UC_MACRO_NAME_1D7A2 0x1D7A2 // 𝞢 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL SIGMA
#define UC_MACRO_NAME_1D7A3 0x1D7A3 // 𝞣 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL TAU
#define UC_MACRO_NAME_1D7A4 0x1D7A4 // 𝞤 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL UPSILON
#define UC_MACRO_NAME_1D7A5 0x1D7A5 // 𝞥 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL PHI
#define UC_MACRO_NAME_1D7A6 0x1D7A6 // 𝞦 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL CHI
#define UC_MACRO_NAME_1D7A7 0x1D7A7 // 𝞧 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL PSI
#define UC_MACRO_NAME_1D7A8 0x1D7A8 // 𝞨 MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL OMEGA
#define UC_MACRO_NAME_1D7A9 0x1D7A9 // 𝞩 MATHEMATICAL SANS-SERIF BOLD ITALIC NABLA
#define UC_MACRO_NAME_1D7AA 0x1D7AA // 𝞪 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL ALPHA
#define UC_MACRO_NAME_1D7AB 0x1D7AB // 𝞫 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL BETA
#define UC_MACRO_NAME_1D7AC 0x1D7AC // 𝞬 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL GAMMA
#define UC_MACRO_NAME_1D7AD 0x1D7AD // 𝞭 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL DELTA
#define UC_MACRO_NAME_1D7AE 0x1D7AE // 𝞮 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL EPSILON
#define UC_MACRO_NAME_1D7AF 0x1D7AF // 𝞯 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL ZETA
#define UC_MACRO_NAME_1D7B0 0x1D7B0 // 𝞰 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL ETA
#define UC_MACRO_NAME_1D7B1 0x1D7B1 // 𝞱 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL THETA
#define UC_MACRO_NAME_1D7B2 0x1D7B2 // 𝞲 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL IOTA
#define UC_MACRO_NAME_1D7B3 0x1D7B3 // 𝞳 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL KAPPA
#define UC_MACRO_NAME_1D7B4 0x1D7B4 // 𝞴 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL LAMDA
#define UC_MACRO_NAME_1D7B5 0x1D7B5 // 𝞵 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL MU
#define UC_MACRO_NAME_1D7B6 0x1D7B6 // 𝞶 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL NU
#define UC_MACRO_NAME_1D7B7 0x1D7B7 // 𝞷 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL XI
#define UC_MACRO_NAME_1D7B8 0x1D7B8 // 𝞸 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL OMICRON
#define UC_MACRO_NAME_1D7B9 0x1D7B9 // 𝞹 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL PI
#define UC_MACRO_NAME_1D7BA 0x1D7BA // 𝞺 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL RHO
#define UC_MACRO_NAME_1D7BB 0x1D7BB // 𝞻 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL FINAL SIGMA
#define UC_MACRO_NAME_1D7BC 0x1D7BC // 𝞼 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL SIGMA
#define UC_MACRO_NAME_1D7BD 0x1D7BD // 𝞽 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL TAU
#define UC_MACRO_NAME_1D7BE 0x1D7BE // 𝞾 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL UPSILON
#define UC_MACRO_NAME_1D7BF 0x1D7BF // 𝞿 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL PHI
#define UC_MACRO_NAME_1D7C0 0x1D7C0 // 𝟀 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL CHI
#define UC_MACRO_NAME_1D7C1 0x1D7C1 // 𝟁 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL PSI
#define UC_MACRO_NAME_1D7C2 0x1D7C2 // 𝟂 MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL OMEGA
#define UC_MACRO_NAME_1D7C3 0x1D7C3 // 𝟃 MATHEMATICAL SANS-SERIF BOLD ITALIC PARTIAL DIFFERENTIAL
#define UC_MACRO_NAME_1D7C4 0x1D7C4 // 𝟄 MATHEMATICAL SANS-SERIF BOLD ITALIC EPSILON SYMBOL
#define UC_MACRO_NAME_1D7C5 0x1D7C5 // 𝟅 MATHEMATICAL SANS-SERIF BOLD ITALIC THETA SYMBOL
#define UC_MACRO_NAME_1D7C6 0x1D7C6 // 𝟆 MATHEMATICAL SANS-SERIF BOLD ITALIC KAPPA SYMBOL
#define UC_MACRO_NAME_1D7C7 0x1D7C7 // 𝟇 MATHEMATICAL SANS-SERIF BOLD ITALIC PHI SYMBOL
#define UC_MACRO_NAME_1D7C8 0x1D7C8 // 𝟈 MATHEMATICAL SANS-SERIF BOLD ITALIC RHO SYMBOL
#define UC_MACRO_NAME_1D7C9 0x1D7C9 // 𝟉 MATHEMATICAL SANS-SERIF BOLD ITALIC PI SYMBOL
#define UC_MACRO_NAME_1D7CA 0x1D7CA // 𝟊 MATHEMATICAL BOLD CAPITAL DIGAMMA
#define UC_MACRO_NAME_1D7CB 0x1D7CB // 𝟋 MATHEMATICAL BOLD SMALL DIGAMMA
#define UC_MACRO_NAME_1D7CE 0x1D7CE // 𝟎 MATHEMATICAL BOLD DIGIT ZERO
#define UC_MACRO_NAME_1D7CF 0x1D7CF // 𝟏 MATHEMATICAL BOLD DIGIT ONE
#define UC_MACRO_NAME_1D7D0 0x1D7D0 // 𝟐 MATHEMATICAL BOLD DIGIT TWO
#define UC_MACRO_NAME_1D7D1 0x1D7D1 // 𝟑 MATHEMATICAL BOLD DIGIT THREE
#define UC_MACRO_NAME_1D7D2 0x1D7D2 // 𝟒 MATHEMATICAL BOLD DIGIT FOUR
#define UC_MACRO_NAME_1D7D3 0x1D7D3 // 𝟓 MATHEMATICAL BOLD DIGIT FIVE
#define UC_MACRO_NAME_1D7D4 0x1D7D4 // 𝟔 MATHEMATICAL BOLD DIGIT SIX
#define UC_MACRO_NAME_1D7D5 0x1D7D5 // 𝟕 MATHEMATICAL BOLD DIGIT SEVEN
#define UC_MACRO_NAME_1D7D6 0x1D7D6 // 𝟖 MATHEMATICAL BOLD DIGIT EIGHT
#define UC_MACRO_NAME_1D7D7 0x1D7D7 // 𝟗 MATHEMATICAL BOLD DIGIT NINE
#define UC_MACRO_NAME_1D7D8 0x1D7D8 // 𝟘 MATHEMATICAL DOUBLE-STRUCK DIGIT ZERO
#define UC_MACRO_NAME_1D7D9 0x1D7D9 // 𝟙 MATHEMATICAL DOUBLE-STRUCK DIGIT ONE
#define UC_MACRO_NAME_1D7DA 0x1D7DA // 𝟚 MATHEMATICAL DOUBLE-STRUCK DIGIT TWO
#define UC_MACRO_NAME_1D7DB 0x1D7DB // 𝟛 MATHEMATICAL DOUBLE-STRUCK DIGIT THREE
#define UC_MACRO_NAME_1D7DC 0x1D7DC // 𝟜 MATHEMATICAL DOUBLE-STRUCK DIGIT FOUR
#define UC_MACRO_NAME_1D7DD 0x1D7DD // 𝟝 MATHEMATICAL DOUBLE-STRUCK DIGIT FIVE
#define UC_MACRO_NAME_1D7DE 0x1D7DE // 𝟞 MATHEMATICAL DOUBLE-STRUCK DIGIT SIX
#define UC_MACRO_NAME_1D7DF 0x1D7DF // 𝟟 MATHEMATICAL DOUBLE-STRUCK DIGIT SEVEN
#define UC_MACRO_NAME_1D7E0 0x1D7E0 // 𝟠 MATHEMATICAL DOUBLE-STRUCK DIGIT EIGHT
#define UC_MACRO_NAME_1D7E1 0x1D7E1 // 𝟡 MATHEMATICAL DOUBLE-STRUCK DIGIT NINE
#define UC_MACRO_NAME_1D7E2 0x1D7E2 // 𝟢 MATHEMATICAL SANS-SERIF DIGIT ZERO
#define UC_MACRO_NAME_1D7E3 0x1D7E3 // 𝟣 MATHEMATICAL SANS-SERIF DIGIT ONE
#define UC_MACRO_NAME_1D7E4 0x1D7E4 // 𝟤 MATHEMATICAL SANS-SERIF DIGIT TWO
#define UC_MACRO_NAME_1D7E5 0x1D7E5 // 𝟥 MATHEMATICAL SANS-SERIF DIGIT THREE
#define UC_MACRO_NAME_1D7E6 0x1D7E6 // 𝟦 MATHEMATICAL SANS-SERIF DIGIT FOUR
#define UC_MACRO_NAME_1D7E7 0x1D7E7 // 𝟧 MATHEMATICAL SANS-SERIF DIGIT FIVE
#define UC_MACRO_NAME_1D7E8 0x1D7E8 // 𝟨 MATHEMATICAL SANS-SERIF DIGIT SIX
#define UC_MACRO_NAME_1D7E9 0x1D7E9 // 𝟩 MATHEMATICAL SANS-SERIF DIGIT SEVEN
#define UC_MACRO_NAME_1D7EA 0x1D7EA // 𝟪 MATHEMATICAL SANS-SERIF DIGIT EIGHT
#define UC_MACRO_NAME_1D7EB 0x1D7EB // 𝟫 MATHEMATICAL SANS-SERIF DIGIT NINE
#define UC_MACRO_NAME_1D7EC 0x1D7EC // 𝟬 MATHEMATICAL SANS-SERIF BOLD DIGIT ZERO
#define UC_MACRO_NAME_1D7ED 0x1D7ED // 𝟭 MATHEMATICAL SANS-SERIF BOLD DIGIT ONE
#define UC_MACRO_NAME_1D7EE 0x1D7EE // 𝟮 MATHEMATICAL SANS-SERIF BOLD DIGIT TWO
#define UC_MACRO_NAME_1D7EF 0x1D7EF // 𝟯 MATHEMATICAL SANS-SERIF BOLD DIGIT THREE
#define UC_MACRO_NAME_1D7F0 0x1D7F0 // 𝟰 MATHEMATICAL SANS-SERIF BOLD DIGIT FOUR
#define UC_MACRO_NAME_1D7F1 0x1D7F1 // 𝟱 MATHEMATICAL SANS-SERIF BOLD DIGIT FIVE
#define UC_MACRO_NAME_1D7F2 0x1D7F2 // 𝟲 MATHEMATICAL SANS-SERIF BOLD DIGIT SIX
#define UC_MACRO_NAME_1D7F3 0x1D7F3 // 𝟳 MATHEMATICAL SANS-SERIF BOLD DIGIT SEVEN
#define UC_MACRO_NAME_1D7F4 0x1D7F4 // 𝟴 MATHEMATICAL SANS-SERIF BOLD DIGIT EIGHT
#define UC_MACRO_NAME_1D7F5 0x1D7F5 // 𝟵 MATHEMATICAL SANS-SERIF BOLD DIGIT NINE
#define UC_MACRO_NAME_1D7F6 0x1D7F6 // 𝟶 MATHEMATICAL MONOSPACE DIGIT ZERO
#define UC_MACRO_NAME_1D7F7 0x1D7F7 // 𝟷 MATHEMATICAL MONOSPACE DIGIT ONE
#define UC_MACRO_NAME_1D7F8 0x1D7F8 // 𝟸 MATHEMATICAL MONOSPACE DIGIT TWO
#define UC_MACRO_NAME_1D7F9 0x1D7F9 // 𝟹 MATHEMATICAL MONOSPACE DIGIT THREE
#define UC_MACRO_NAME_1D7FA 0x1D7FA // 𝟺 MATHEMATICAL MONOSPACE DIGIT FOUR
#define UC_MACRO_NAME_1D7FB 0x1D7FB // 𝟻 MATHEMATICAL MONOSPACE DIGIT FIVE
#define UC_MACRO_NAME_1D7FC 0x1D7FC // 𝟼 MATHEMATICAL MONOSPACE DIGIT SIX
#define UC_MACRO_NAME_1D7FD 0x1D7FD // 𝟽 MATHEMATICAL MONOSPACE DIGIT SEVEN
#define UC_MACRO_NAME_1D7FE 0x1D7FE // 𝟾 MATHEMATICAL MONOSPACE DIGIT EIGHT
#define UC_MACRO_NAME_1D7FF 0x1D7FF // 𝟿 MATHEMATICAL MONOSPACE DIGIT NINE


#endif // UC_H_MATHEMATICAL_ALPHANUMERIC_SYMBOLS
