/*
 * Unicode Block: Miscellaneous Mathematical Symbols-B
 * Range: U+2980..U+29FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B
#define UC_H_MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B

#define UC_MACRO_NAME_2980 0x2980 // ⦀ TRIPLE VERTICAL BAR DELIMITER
#define UC_MACRO_NAME_2981 0x2981 // ⦁ Z NOTATION SPOT
#define UC_MACRO_NAME_2982 0x2982 // ⦂ Z NOTATION TYPE COLON
#define UC_MACRO_NAME_2983 0x2983 // ⦃ LEFT WHITE CURLY BRACKET
#define UC_MACRO_NAME_2984 0x2984 // ⦄ RIGHT WHITE CURLY BRACKET
#define UC_MACRO_NAME_2985 0x2985 // ⦅ LEFT WHITE PARENTHESIS
#define UC_MACRO_NAME_2986 0x2986 // ⦆ RIGHT WHITE PARENTHESIS
#define UC_MACRO_NAME_2987 0x2987 // ⦇ Z NOTATION LEFT IMAGE BRACKET
#define UC_MACRO_NAME_2988 0x2988 // ⦈ Z NOTATION RIGHT IMAGE BRACKET
#define UC_MACRO_NAME_2989 0x2989 // ⦉ Z NOTATION LEFT BINDING BRACKET
#define UC_MACRO_NAME_298A 0x298A // ⦊ Z NOTATION RIGHT BINDING BRACKET
#define UC_MACRO_NAME_298B 0x298B // ⦋ LEFT SQUARE BRACKET WITH UNDERBAR
#define UC_MACRO_NAME_298C 0x298C // ⦌ RIGHT SQUARE BRACKET WITH UNDERBAR
#define UC_MACRO_NAME_298D 0x298D // ⦍ LEFT SQUARE BRACKET WITH TICK IN TOP CORNER
#define UC_MACRO_NAME_298E 0x298E // ⦎ RIGHT SQUARE BRACKET WITH TICK IN BOTTOM CORNER
#define UC_MACRO_NAME_298F 0x298F // ⦏ LEFT SQUARE BRACKET WITH TICK IN BOTTOM CORNER
#define UC_MACRO_NAME_2990 0x2990 // ⦐ RIGHT SQUARE BRACKET WITH TICK IN TOP CORNER
#define UC_MACRO_NAME_2991 0x2991 // ⦑ LEFT ANGLE BRACKET WITH DOT
#define UC_MACRO_NAME_2992 0x2992 // ⦒ RIGHT ANGLE BRACKET WITH DOT
#define UC_MACRO_NAME_2993 0x2993 // ⦓ LEFT ARC LESS-THAN BRACKET
#define UC_MACRO_NAME_2994 0x2994 // ⦔ RIGHT ARC GREATER-THAN BRACKET
#define UC_MACRO_NAME_2995 0x2995 // ⦕ DOUBLE LEFT ARC GREATER-THAN BRACKET
#define UC_MACRO_NAME_2996 0x2996 // ⦖ DOUBLE RIGHT ARC LESS-THAN BRACKET
#define UC_MACRO_NAME_2997 0x2997 // ⦗ LEFT BLACK TORTOISE SHELL BRACKET
#define UC_MACRO_NAME_2998 0x2998 // ⦘ RIGHT BLACK TORTOISE SHELL BRACKET
#define UC_MACRO_NAME_2999 0x2999 // ⦙ DOTTED FENCE
#define UC_MACRO_NAME_299A 0x299A // ⦚ VERTICAL ZIGZAG LINE
#define UC_MACRO_NAME_299B 0x299B // ⦛ MEASURED ANGLE OPENING LEFT
#define UC_MACRO_NAME_299C 0x299C // ⦜ RIGHT ANGLE VARIANT WITH SQUARE
#define UC_MACRO_NAME_299D 0x299D // ⦝ MEASURED RIGHT ANGLE WITH DOT
#define UC_MACRO_NAME_299E 0x299E // ⦞ ANGLE WITH S INSIDE
#define UC_MACRO_NAME_299F 0x299F // ⦟ ACUTE ANGLE
#define UC_MACRO_NAME_29A0 0x29A0 // ⦠ SPHERICAL ANGLE OPENING LEFT
#define UC_MACRO_NAME_29A1 0x29A1 // ⦡ SPHERICAL ANGLE OPENING UP
#define UC_MACRO_NAME_29A2 0x29A2 // ⦢ TURNED ANGLE
#define UC_MACRO_NAME_29A3 0x29A3 // ⦣ REVERSED ANGLE
#define UC_MACRO_NAME_29A4 0x29A4 // ⦤ ANGLE WITH UNDERBAR
#define UC_MACRO_NAME_29A5 0x29A5 // ⦥ REVERSED ANGLE WITH UNDERBAR
#define UC_MACRO_NAME_29A6 0x29A6 // ⦦ OBLIQUE ANGLE OPENING UP
#define UC_MACRO_NAME_29A7 0x29A7 // ⦧ OBLIQUE ANGLE OPENING DOWN
#define UC_MACRO_NAME_29A8 0x29A8 // ⦨ MEASURED ANGLE WITH OPEN ARM ENDING IN ARROW POINTING UP AND RIGHT
#define UC_MACRO_NAME_29A9 0x29A9 // ⦩ MEASURED ANGLE WITH OPEN ARM ENDING IN ARROW POINTING UP AND LEFT
#define UC_MACRO_NAME_29AA 0x29AA // ⦪ MEASURED ANGLE WITH OPEN ARM ENDING IN ARROW POINTING DOWN AND RIGHT
#define UC_MACRO_NAME_29AB 0x29AB // ⦫ MEASURED ANGLE WITH OPEN ARM ENDING IN ARROW POINTING DOWN AND LEFT
#define UC_MACRO_NAME_29AC 0x29AC // ⦬ MEASURED ANGLE WITH OPEN ARM ENDING IN ARROW POINTING RIGHT AND UP
#define UC_MACRO_NAME_29AD 0x29AD // ⦭ MEASURED ANGLE WITH OPEN ARM ENDING IN ARROW POINTING LEFT AND UP
#define UC_MACRO_NAME_29AE 0x29AE // ⦮ MEASURED ANGLE WITH OPEN ARM ENDING IN ARROW POINTING RIGHT AND DOWN
#define UC_MACRO_NAME_29AF 0x29AF // ⦯ MEASURED ANGLE WITH OPEN ARM ENDING IN ARROW POINTING LEFT AND DOWN
#define UC_MACRO_NAME_29B0 0x29B0 // ⦰ REVERSED EMPTY SET
#define UC_MACRO_NAME_29B1 0x29B1 // ⦱ EMPTY SET WITH OVERBAR
#define UC_MACRO_NAME_29B2 0x29B2 // ⦲ EMPTY SET WITH SMALL CIRCLE ABOVE
#define UC_MACRO_NAME_29B3 0x29B3 // ⦳ EMPTY SET WITH RIGHT ARROW ABOVE
#define UC_MACRO_NAME_29B4 0x29B4 // ⦴ EMPTY SET WITH LEFT ARROW ABOVE
#define UC_MACRO_NAME_29B5 0x29B5 // ⦵ CIRCLE WITH HORIZONTAL BAR
#define UC_MACRO_NAME_29B6 0x29B6 // ⦶ CIRCLED VERTICAL BAR
#define UC_MACRO_NAME_29B7 0x29B7 // ⦷ CIRCLED PARALLEL
#define UC_MACRO_NAME_29B8 0x29B8 // ⦸ CIRCLED REVERSE SOLIDUS
#define UC_MACRO_NAME_29B9 0x29B9 // ⦹ CIRCLED PERPENDICULAR
#define UC_MACRO_NAME_29BA 0x29BA // ⦺ CIRCLE DIVIDED BY HORIZONTAL BAR AND TOP HALF DIVIDED BY VERTICAL BAR
#define UC_MACRO_NAME_29BB 0x29BB // ⦻ CIRCLE WITH SUPERIMPOSED X
#define UC_MACRO_NAME_29BC 0x29BC // ⦼ CIRCLED ANTICLOCKWISE-ROTATED DIVISION SIGN
#define UC_MACRO_NAME_29BD 0x29BD // ⦽ UP ARROW THROUGH CIRCLE
#define UC_MACRO_NAME_29BE 0x29BE // ⦾ CIRCLED WHITE BULLET
#define UC_MACRO_NAME_29BF 0x29BF // ⦿ CIRCLED BULLET
#define UC_MACRO_NAME_29C0 0x29C0 // ⧀ CIRCLED LESS-THAN
#define UC_MACRO_NAME_29C1 0x29C1 // ⧁ CIRCLED GREATER-THAN
#define UC_MACRO_NAME_29C2 0x29C2 // ⧂ CIRCLE WITH SMALL CIRCLE TO THE RIGHT
#define UC_MACRO_NAME_29C3 0x29C3 // ⧃ CIRCLE WITH TWO HORIZONTAL STROKES TO THE RIGHT
#define UC_MACRO_NAME_29C4 0x29C4 // ⧄ SQUARED RISING DIAGONAL SLASH
#define UC_MACRO_NAME_29C5 0x29C5 // ⧅ SQUARED FALLING DIAGONAL SLASH
#define UC_MACRO_NAME_29C6 0x29C6 // ⧆ SQUARED ASTERISK
#define UC_MACRO_NAME_29C7 0x29C7 // ⧇ SQUARED SMALL CIRCLE
#define UC_MACRO_NAME_29C8 0x29C8 // ⧈ SQUARED SQUARE
#define UC_MACRO_NAME_29C9 0x29C9 // ⧉ TWO JOINED SQUARES
#define UC_MACRO_NAME_29CA 0x29CA // ⧊ TRIANGLE WITH DOT ABOVE
#define UC_MACRO_NAME_29CB 0x29CB // ⧋ TRIANGLE WITH UNDERBAR
#define UC_MACRO_NAME_29CC 0x29CC // ⧌ S IN TRIANGLE
#define UC_MACRO_NAME_29CD 0x29CD // ⧍ TRIANGLE WITH SERIFS AT BOTTOM
#define UC_MACRO_NAME_29CE 0x29CE // ⧎ RIGHT TRIANGLE ABOVE LEFT TRIANGLE
#define UC_MACRO_NAME_29CF 0x29CF // ⧏ LEFT TRIANGLE BESIDE VERTICAL BAR
#define UC_MACRO_NAME_29D0 0x29D0 // ⧐ VERTICAL BAR BESIDE RIGHT TRIANGLE
#define UC_MACRO_NAME_29D1 0x29D1 // ⧑ BOWTIE WITH LEFT HALF BLACK
#define UC_MACRO_NAME_29D2 0x29D2 // ⧒ BOWTIE WITH RIGHT HALF BLACK
#define UC_MACRO_NAME_29D3 0x29D3 // ⧓ BLACK BOWTIE
#define UC_MACRO_NAME_29D4 0x29D4 // ⧔ TIMES WITH LEFT HALF BLACK
#define UC_MACRO_NAME_29D5 0x29D5 // ⧕ TIMES WITH RIGHT HALF BLACK
#define UC_MACRO_NAME_29D6 0x29D6 // ⧖ WHITE HOURGLASS
#define UC_MACRO_NAME_29D7 0x29D7 // ⧗ BLACK HOURGLASS
#define UC_MACRO_NAME_29D8 0x29D8 // ⧘ LEFT WIGGLY FENCE
#define UC_MACRO_NAME_29D9 0x29D9 // ⧙ RIGHT WIGGLY FENCE
#define UC_MACRO_NAME_29DA 0x29DA // ⧚ LEFT DOUBLE WIGGLY FENCE
#define UC_MACRO_NAME_29DB 0x29DB // ⧛ RIGHT DOUBLE WIGGLY FENCE
#define UC_MACRO_NAME_29DC 0x29DC // ⧜ INCOMPLETE INFINITY
#define UC_MACRO_NAME_29DD 0x29DD // ⧝ TIE OVER INFINITY
#define UC_MACRO_NAME_29DE 0x29DE // ⧞ INFINITY NEGATED WITH VERTICAL BAR
#define UC_MACRO_NAME_29DF 0x29DF // ⧟ DOUBLE-ENDED MULTIMAP
#define UC_MACRO_NAME_29E0 0x29E0 // ⧠ SQUARE WITH CONTOURED OUTLINE
#define UC_MACRO_NAME_29E1 0x29E1 // ⧡ INCREASES AS
#define UC_MACRO_NAME_29E2 0x29E2 // ⧢ SHUFFLE PRODUCT
#define UC_MACRO_NAME_29E3 0x29E3 // ⧣ EQUALS SIGN AND SLANTED PARALLEL
#define UC_MACRO_NAME_29E4 0x29E4 // ⧤ EQUALS SIGN AND SLANTED PARALLEL WITH TILDE ABOVE
#define UC_MACRO_NAME_29E5 0x29E5 // ⧥ IDENTICAL TO AND SLANTED PARALLEL
#define UC_MACRO_NAME_29E6 0x29E6 // ⧦ GLEICH STARK
#define UC_MACRO_NAME_29E7 0x29E7 // ⧧ THERMODYNAMIC
#define UC_MACRO_NAME_29E8 0x29E8 // ⧨ DOWN-POINTING TRIANGLE WITH LEFT HALF BLACK
#define UC_MACRO_NAME_29E9 0x29E9 // ⧩ DOWN-POINTING TRIANGLE WITH RIGHT HALF BLACK
#define UC_MACRO_NAME_29EA 0x29EA // ⧪ BLACK DIAMOND WITH DOWN ARROW
#define UC_MACRO_NAME_29EB 0x29EB // ⧫ BLACK LOZENGE
#define UC_MACRO_NAME_29EC 0x29EC // ⧬ WHITE CIRCLE WITH DOWN ARROW
#define UC_MACRO_NAME_29ED 0x29ED // ⧭ BLACK CIRCLE WITH DOWN ARROW
#define UC_MACRO_NAME_29EE 0x29EE // ⧮ ERROR-BARRED WHITE SQUARE
#define UC_MACRO_NAME_29EF 0x29EF // ⧯ ERROR-BARRED BLACK SQUARE
#define UC_MACRO_NAME_29F0 0x29F0 // ⧰ ERROR-BARRED WHITE DIAMOND
#define UC_MACRO_NAME_29F1 0x29F1 // ⧱ ERROR-BARRED BLACK DIAMOND
#define UC_MACRO_NAME_29F2 0x29F2 // ⧲ ERROR-BARRED WHITE CIRCLE
#define UC_MACRO_NAME_29F3 0x29F3 // ⧳ ERROR-BARRED BLACK CIRCLE
#define UC_MACRO_NAME_29F4 0x29F4 // ⧴ RULE-DELAYED
#define UC_MACRO_NAME_29F5 0x29F5 // ⧵ REVERSE SOLIDUS OPERATOR
#define UC_MACRO_NAME_29F6 0x29F6 // ⧶ SOLIDUS WITH OVERBAR
#define UC_MACRO_NAME_29F7 0x29F7 // ⧷ REVERSE SOLIDUS WITH HORIZONTAL STROKE
#define UC_MACRO_NAME_29F8 0x29F8 // ⧸ BIG SOLIDUS
#define UC_MACRO_NAME_29F9 0x29F9 // ⧹ BIG REVERSE SOLIDUS
#define UC_MACRO_NAME_29FA 0x29FA // ⧺ DOUBLE PLUS
#define UC_MACRO_NAME_29FB 0x29FB // ⧻ TRIPLE PLUS
#define UC_MACRO_NAME_29FC 0x29FC // ⧼ LEFT-POINTING CURVED ANGLE BRACKET
#define UC_MACRO_NAME_29FD 0x29FD // ⧽ RIGHT-POINTING CURVED ANGLE BRACKET
#define UC_MACRO_NAME_29FE 0x29FE // ⧾ TINY
#define UC_MACRO_NAME_29FF 0x29FF // ⧿ MINY


#endif // UC_H_MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B
