/*
 * Unicode Block: Miscellaneous Symbols Supplement
 * Range: U+1CEC0..U+1CEFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Miscellaneous Symbols Supplement is a Unicode block containing a
 * variety of symbols: astronomical symbols , geomantic figures , and one
 * standard state chemical symbol.
 *
 */
#ifndef UC_H_MISCELLANEOUS_SYMBOLS_SUPPLEMENT
#define UC_H_MISCELLANEOUS_SYMBOLS_SUPPLEMENT

#define UC_MACRO_NAME_1CEC0 0x1CEC0 //  HEBE
#define UC_MACRO_NAME_1CEC1 0x1CEC1 //  IRIS
#define UC_MACRO_NAME_1CEC2 0x1CEC2 //  FLORA
#define UC_MACRO_NAME_1CEC3 0x1CEC3 //  METIS
#define UC_MACRO_NAME_1CEC4 0x1CEC4 //  PARTHENOPE
#define UC_MACRO_NAME_1CEC5 0x1CEC5 //  VICTORIA
#define UC_MACRO_NAME_1CEC6 0x1CEC6 //  EGERIA
#define UC_MACRO_NAME_1CEC7 0x1CEC7 //  IRENE
#define UC_MACRO_NAME_1CEC8 0x1CEC8 //  EUNOMIA
#define UC_MACRO_NAME_1CEC9 0x1CEC9 //  PSYCHE
#define UC_MACRO_NAME_1CECA 0x1CECA //  THETIS
#define UC_MACRO_NAME_1CECB 0x1CECB //  MELPOMENE
#define UC_MACRO_NAME_1CECC 0x1CECC //  FORTUNA
#define UC_MACRO_NAME_1CECD 0x1CECD //  ASTRONOMICAL SYMBOL FOR ASTEROID PROSERPINA
#define UC_MACRO_NAME_1CECE 0x1CECE //  BELLONA
#define UC_MACRO_NAME_1CECF 0x1CECF //  AMPHITRITE
#define UC_MACRO_NAME_1CED0 0x1CED0 //  LEUKOTHEA
#define UC_MACRO_NAME_1CEE0 0x1CEE0 //  GEOMANTIC FIGURE POPULUS
#define UC_MACRO_NAME_1CEE1 0x1CEE1 //  GEOMANTIC FIGURE TRISTITIA
#define UC_MACRO_NAME_1CEE2 0x1CEE2 //  GEOMANTIC FIGURE ALBUS
#define UC_MACRO_NAME_1CEE3 0x1CEE3 //  GEOMANTIC FIGURE FORTUNA MAJOR
#define UC_MACRO_NAME_1CEE4 0x1CEE4 //  GEOMANTIC FIGURE RUBEUS
#define UC_MACRO_NAME_1CEE5 0x1CEE5 //  GEOMANTIC FIGURE ACQUISITIO
#define UC_MACRO_NAME_1CEE6 0x1CEE6 //  GEOMANTIC FIGURE CONJUNCTIO
#define UC_MACRO_NAME_1CEE7 0x1CEE7 //  GEOMANTIC FIGURE CAPUT DRACONIS
#define UC_MACRO_NAME_1CEE8 0x1CEE8 //  GEOMANTIC FIGURE LAETITIA
#define UC_MACRO_NAME_1CEE9 0x1CEE9 //  GEOMANTIC FIGURE CARCER
#define UC_MACRO_NAME_1CEEA 0x1CEEA //  GEOMANTIC FIGURE AMISSIO
#define UC_MACRO_NAME_1CEEB 0x1CEEB //  GEOMANTIC FIGURE PUELLA
#define UC_MACRO_NAME_1CEEC 0x1CEEC //  GEOMANTIC FIGURE FORTUNA MINOR
#define UC_MACRO_NAME_1CEED 0x1CEED //  GEOMANTIC FIGURE PUER
#define UC_MACRO_NAME_1CEEE 0x1CEEE //  GEOMANTIC FIGURE CAUDA DRACONIS
#define UC_MACRO_NAME_1CEEF 0x1CEEF //  GEOMANTIC FIGURE VIA
#define UC_MACRO_NAME_1CEF0 0x1CEF0 //  MEDIUM SMALL WHITE CIRCLE WITH HORIZONTAL BAR


#endif // UC_H_MISCELLANEOUS_SYMBOLS_SUPPLEMENT
