/*
 * Unicode Block: NKo
 * Range: U+07C0..U+07FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * N'Ko may refer to:
 *
 */
#ifndef UC_H_NKO
#define UC_H_NKO

#define UC_MACRO_NAME_7C0 0x07C0 // ߀ NKO DIGIT ZERO
#define UC_MACRO_NAME_7C1 0x07C1 // ߁ NKO DIGIT ONE
#define UC_MACRO_NAME_7C2 0x07C2 // ߂ NKO DIGIT TWO
#define UC_MACRO_NAME_7C3 0x07C3 // ߃ NKO DIGIT THREE
#define UC_MACRO_NAME_7C4 0x07C4 // ߄ NKO DIGIT FOUR
#define UC_MACRO_NAME_7C5 0x07C5 // ߅ NKO DIGIT FIVE
#define UC_MACRO_NAME_7C6 0x07C6 // ߆ NKO DIGIT SIX
#define UC_MACRO_NAME_7C7 0x07C7 // ߇ NKO DIGIT SEVEN
#define UC_MACRO_NAME_7C8 0x07C8 // ߈ NKO DIGIT EIGHT
#define UC_MACRO_NAME_7C9 0x07C9 // ߉ NKO DIGIT NINE
#define UC_MACRO_NAME_7CA 0x07CA // ߊ NKO LETTER A
#define UC_MACRO_NAME_7CB 0x07CB // ߋ NKO LETTER EE
#define UC_MACRO_NAME_7CC 0x07CC // ߌ NKO LETTER I
#define UC_MACRO_NAME_7CD 0x07CD // ߍ NKO LETTER E
#define UC_MACRO_NAME_7CE 0x07CE // ߎ NKO LETTER U
#define UC_MACRO_NAME_7CF 0x07CF // ߏ NKO LETTER OO
#define UC_MACRO_NAME_7D0 0x07D0 // ߐ NKO LETTER O
#define UC_MACRO_NAME_7D1 0x07D1 // ߑ NKO LETTER DAGBASINNA
#define UC_MACRO_NAME_7D2 0x07D2 // ߒ NKO LETTER N
#define UC_MACRO_NAME_7D3 0x07D3 // ߓ NKO LETTER BA
#define UC_MACRO_NAME_7D4 0x07D4 // ߔ NKO LETTER PA
#define UC_MACRO_NAME_7D5 0x07D5 // ߕ NKO LETTER TA
#define UC_MACRO_NAME_7D6 0x07D6 // ߖ NKO LETTER JA
#define UC_MACRO_NAME_7D7 0x07D7 // ߗ NKO LETTER CHA
#define UC_MACRO_NAME_7D8 0x07D8 // ߘ NKO LETTER DA
#define UC_MACRO_NAME_7D9 0x07D9 // ߙ NKO LETTER RA
#define UC_MACRO_NAME_7DA 0x07DA // ߚ NKO LETTER RRA
#define UC_MACRO_NAME_7DB 0x07DB // ߛ NKO LETTER SA
#define UC_MACRO_NAME_7DC 0x07DC // ߜ NKO LETTER GBA
#define UC_MACRO_NAME_7DD 0x07DD // ߝ NKO LETTER FA
#define UC_MACRO_NAME_7DE 0x07DE // ߞ NKO LETTER KA
#define UC_MACRO_NAME_7DF 0x07DF // ߟ NKO LETTER LA
#define UC_MACRO_NAME_7E0 0x07E0 // ߠ NKO LETTER NA WOLOSO
#define UC_MACRO_NAME_7E1 0x07E1 // ߡ NKO LETTER MA
#define UC_MACRO_NAME_7E2 0x07E2 // ߢ NKO LETTER NYA
#define UC_MACRO_NAME_7E3 0x07E3 // ߣ NKO LETTER NA
#define UC_MACRO_NAME_7E4 0x07E4 // ߤ NKO LETTER HA
#define UC_MACRO_NAME_7E5 0x07E5 // ߥ NKO LETTER WA
#define UC_MACRO_NAME_7E6 0x07E6 // ߦ NKO LETTER YA
#define UC_MACRO_NAME_7E7 0x07E7 // ߧ NKO LETTER NYA WOLOSO
#define UC_MACRO_NAME_7E8 0x07E8 // ߨ NKO LETTER JONA JA
#define UC_MACRO_NAME_7E9 0x07E9 // ߩ NKO LETTER JONA CHA
#define UC_MACRO_NAME_7EA 0x07EA // ߪ NKO LETTER JONA RA
#define UC_MACRO_NAME_7EB 0x07EB // ߫ NKO COMBINING SHORT HIGH TONE
#define UC_MACRO_NAME_7EC 0x07EC // ߬ NKO COMBINING SHORT LOW TONE
#define UC_MACRO_NAME_7ED 0x07ED // ߭ NKO COMBINING SHORT RISING TONE
#define UC_MACRO_NAME_7EE 0x07EE // ߮ NKO COMBINING LONG DESCENDING TONE
#define UC_MACRO_NAME_7EF 0x07EF // ߯ NKO COMBINING LONG HIGH TONE
#define UC_MACRO_NAME_7F0 0x07F0 // ߰ NKO COMBINING LONG LOW TONE
#define UC_MACRO_NAME_7F1 0x07F1 // ߱ NKO COMBINING LONG RISING TONE
#define UC_MACRO_NAME_7F2 0x07F2 // ߲ NKO COMBINING NASALIZATION MARK
#define UC_MACRO_NAME_7F3 0x07F3 // ߳ NKO COMBINING DOUBLE DOT ABOVE
#define UC_MACRO_NAME_7F4 0x07F4 // ߴ NKO HIGH TONE APOSTROPHE
#define UC_MACRO_NAME_7F5 0x07F5 // ߵ NKO LOW TONE APOSTROPHE
#define UC_MACRO_NAME_7F6 0x07F6 // ߶ NKO SYMBOL OO DENNEN
#define UC_MACRO_NAME_7F7 0x07F7 // ߷ NKO SYMBOL GBAKURUNEN
#define UC_MACRO_NAME_7F8 0x07F8 // ߸ NKO COMMA
#define UC_MACRO_NAME_7F9 0x07F9 // ߹ NKO EXCLAMATION MARK
#define UC_MACRO_NAME_7FA 0x07FA // ߺ NKO LAJANYALAN
#define UC_MACRO_NAME_7FD 0x07FD // ߽ NKO DANTAYALAN
#define UC_MACRO_NAME_7FE 0x07FE // ߾ NKO DOROME SIGN
#define UC_MACRO_NAME_7FF 0x07FF // ߿ NKO TAMAN SIGN


#endif // UC_H_NKO
