/*
 * Unicode Block: Old North Arabian
 * Range: U+10A80..U+10A9F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Ancient North Arabian ( ANA ) is a collection of scripts and a
 * language or family of languages under the North Arabian languages
 * branch along with Old Arabic that were used in north and central
 * Arabia and south Syria from the 8th century BCE to the 4th century CE.
 * The term "Ancient North Arabian" is defined negatively. It refers to
 * all of the South Semitic scripts except Ancient South Arabian (ASA)
 * regardless of their genetic relationships.
 *
 */
#ifndef UC_H_OLD_NORTH_ARABIAN
#define UC_H_OLD_NORTH_ARABIAN

#define UC_MACRO_NAME_10A80 0x10A80 // 𐪀 OLD NORTH ARABIAN LETTER HEH
#define UC_MACRO_NAME_10A81 0x10A81 // 𐪁 OLD NORTH ARABIAN LETTER LAM
#define UC_MACRO_NAME_10A82 0x10A82 // 𐪂 OLD NORTH ARABIAN LETTER HAH
#define UC_MACRO_NAME_10A83 0x10A83 // 𐪃 OLD NORTH ARABIAN LETTER MEEM
#define UC_MACRO_NAME_10A84 0x10A84 // 𐪄 OLD NORTH ARABIAN LETTER QAF
#define UC_MACRO_NAME_10A85 0x10A85 // 𐪅 OLD NORTH ARABIAN LETTER WAW
#define UC_MACRO_NAME_10A86 0x10A86 // 𐪆 OLD NORTH ARABIAN LETTER ES-2
#define UC_MACRO_NAME_10A87 0x10A87 // 𐪇 OLD NORTH ARABIAN LETTER REH
#define UC_MACRO_NAME_10A88 0x10A88 // 𐪈 OLD NORTH ARABIAN LETTER BEH
#define UC_MACRO_NAME_10A89 0x10A89 // 𐪉 OLD NORTH ARABIAN LETTER TEH
#define UC_MACRO_NAME_10A8A 0x10A8A // 𐪊 OLD NORTH ARABIAN LETTER ES-1
#define UC_MACRO_NAME_10A8B 0x10A8B // 𐪋 OLD NORTH ARABIAN LETTER KAF
#define UC_MACRO_NAME_10A8C 0x10A8C // 𐪌 OLD NORTH ARABIAN LETTER NOON
#define UC_MACRO_NAME_10A8D 0x10A8D // 𐪍 OLD NORTH ARABIAN LETTER KHAH
#define UC_MACRO_NAME_10A8E 0x10A8E // 𐪎 OLD NORTH ARABIAN LETTER SAD
#define UC_MACRO_NAME_10A8F 0x10A8F // 𐪏 OLD NORTH ARABIAN LETTER ES-3
#define UC_MACRO_NAME_10A90 0x10A90 // 𐪐 OLD NORTH ARABIAN LETTER FEH
#define UC_MACRO_NAME_10A91 0x10A91 // 𐪑 OLD NORTH ARABIAN LETTER ALEF
#define UC_MACRO_NAME_10A92 0x10A92 // 𐪒 OLD NORTH ARABIAN LETTER AIN
#define UC_MACRO_NAME_10A93 0x10A93 // 𐪓 OLD NORTH ARABIAN LETTER DAD
#define UC_MACRO_NAME_10A94 0x10A94 // 𐪔 OLD NORTH ARABIAN LETTER GEEM
#define UC_MACRO_NAME_10A95 0x10A95 // 𐪕 OLD NORTH ARABIAN LETTER DAL
#define UC_MACRO_NAME_10A96 0x10A96 // 𐪖 OLD NORTH ARABIAN LETTER GHAIN
#define UC_MACRO_NAME_10A97 0x10A97 // 𐪗 OLD NORTH ARABIAN LETTER TAH
#define UC_MACRO_NAME_10A98 0x10A98 // 𐪘 OLD NORTH ARABIAN LETTER ZAIN
#define UC_MACRO_NAME_10A99 0x10A99 // 𐪙 OLD NORTH ARABIAN LETTER THAL
#define UC_MACRO_NAME_10A9A 0x10A9A // 𐪚 OLD NORTH ARABIAN LETTER YEH
#define UC_MACRO_NAME_10A9B 0x10A9B // 𐪛 OLD NORTH ARABIAN LETTER THEH
#define UC_MACRO_NAME_10A9C 0x10A9C // 𐪜 OLD NORTH ARABIAN LETTER ZAH
#define UC_MACRO_NAME_10A9D 0x10A9D // 𐪝 OLD NORTH ARABIAN NUMBER ONE
#define UC_MACRO_NAME_10A9E 0x10A9E // 𐪞 OLD NORTH ARABIAN NUMBER TEN
#define UC_MACRO_NAME_10A9F 0x10A9F // 𐪟 OLD NORTH ARABIAN NUMBER TWENTY


#endif // UC_H_OLD_NORTH_ARABIAN
