/*
 * Unicode Block: Old Hungarian
 * Range: U+10C80..U+10CFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Old Hungarian may refer to:
 *
 */
#ifndef UC_H_OLD_HUNGARIAN
#define UC_H_OLD_HUNGARIAN

#define UC_MACRO_NAME_10C80 0x10C80 // 𐲀 OLD HUNGARIAN CAPITAL LETTER A
#define UC_MACRO_NAME_10C81 0x10C81 // 𐲁 OLD HUNGARIAN CAPITAL LETTER AA
#define UC_MACRO_NAME_10C82 0x10C82 // 𐲂 OLD HUNGARIAN CAPITAL LETTER EB
#define UC_MACRO_NAME_10C83 0x10C83 // 𐲃 OLD HUNGARIAN CAPITAL LETTER AMB
#define UC_MACRO_NAME_10C84 0x10C84 // 𐲄 OLD HUNGARIAN CAPITAL LETTER EC
#define UC_MACRO_NAME_10C85 0x10C85 // 𐲅 OLD HUNGARIAN CAPITAL LETTER ENC
#define UC_MACRO_NAME_10C86 0x10C86 // 𐲆 OLD HUNGARIAN CAPITAL LETTER ECS
#define UC_MACRO_NAME_10C87 0x10C87 // 𐲇 OLD HUNGARIAN CAPITAL LETTER ED
#define UC_MACRO_NAME_10C88 0x10C88 // 𐲈 OLD HUNGARIAN CAPITAL LETTER AND
#define UC_MACRO_NAME_10C89 0x10C89 // 𐲉 OLD HUNGARIAN CAPITAL LETTER E
#define UC_MACRO_NAME_10C8A 0x10C8A // 𐲊 OLD HUNGARIAN CAPITAL LETTER CLOSE E
#define UC_MACRO_NAME_10C8B 0x10C8B // 𐲋 OLD HUNGARIAN CAPITAL LETTER EE
#define UC_MACRO_NAME_10C8C 0x10C8C // 𐲌 OLD HUNGARIAN CAPITAL LETTER EF
#define UC_MACRO_NAME_10C8D 0x10C8D // 𐲍 OLD HUNGARIAN CAPITAL LETTER EG
#define UC_MACRO_NAME_10C8E 0x10C8E // 𐲎 OLD HUNGARIAN CAPITAL LETTER EGY
#define UC_MACRO_NAME_10C8F 0x10C8F // 𐲏 OLD HUNGARIAN CAPITAL LETTER EH
#define UC_MACRO_NAME_10C90 0x10C90 // 𐲐 OLD HUNGARIAN CAPITAL LETTER I
#define UC_MACRO_NAME_10C91 0x10C91 // 𐲑 OLD HUNGARIAN CAPITAL LETTER II
#define UC_MACRO_NAME_10C92 0x10C92 // 𐲒 OLD HUNGARIAN CAPITAL LETTER EJ
#define UC_MACRO_NAME_10C93 0x10C93 // 𐲓 OLD HUNGARIAN CAPITAL LETTER EK
#define UC_MACRO_NAME_10C94 0x10C94 // 𐲔 OLD HUNGARIAN CAPITAL LETTER AK
#define UC_MACRO_NAME_10C95 0x10C95 // 𐲕 OLD HUNGARIAN CAPITAL LETTER UNK
#define UC_MACRO_NAME_10C96 0x10C96 // 𐲖 OLD HUNGARIAN CAPITAL LETTER EL
#define UC_MACRO_NAME_10C97 0x10C97 // 𐲗 OLD HUNGARIAN CAPITAL LETTER ELY
#define UC_MACRO_NAME_10C98 0x10C98 // 𐲘 OLD HUNGARIAN CAPITAL LETTER EM
#define UC_MACRO_NAME_10C99 0x10C99 // 𐲙 OLD HUNGARIAN CAPITAL LETTER EN
#define UC_MACRO_NAME_10C9A 0x10C9A // 𐲚 OLD HUNGARIAN CAPITAL LETTER ENY
#define UC_MACRO_NAME_10C9B 0x10C9B // 𐲛 OLD HUNGARIAN CAPITAL LETTER O
#define UC_MACRO_NAME_10C9C 0x10C9C // 𐲜 OLD HUNGARIAN CAPITAL LETTER OO
#define UC_MACRO_NAME_10C9D 0x10C9D // 𐲝 OLD HUNGARIAN CAPITAL LETTER NIKOLSBURG OE
#define UC_MACRO_NAME_10C9E 0x10C9E // 𐲞 OLD HUNGARIAN CAPITAL LETTER RUDIMENTA OE
#define UC_MACRO_NAME_10C9F 0x10C9F // 𐲟 OLD HUNGARIAN CAPITAL LETTER OEE
#define UC_MACRO_NAME_10CA0 0x10CA0 // 𐲠 OLD HUNGARIAN CAPITAL LETTER EP
#define UC_MACRO_NAME_10CA1 0x10CA1 // 𐲡 OLD HUNGARIAN CAPITAL LETTER EMP
#define UC_MACRO_NAME_10CA2 0x10CA2 // 𐲢 OLD HUNGARIAN CAPITAL LETTER ER
#define UC_MACRO_NAME_10CA3 0x10CA3 // 𐲣 OLD HUNGARIAN CAPITAL LETTER SHORT ER
#define UC_MACRO_NAME_10CA4 0x10CA4 // 𐲤 OLD HUNGARIAN CAPITAL LETTER ES
#define UC_MACRO_NAME_10CA5 0x10CA5 // 𐲥 OLD HUNGARIAN CAPITAL LETTER ESZ
#define UC_MACRO_NAME_10CA6 0x10CA6 // 𐲦 OLD HUNGARIAN CAPITAL LETTER ET
#define UC_MACRO_NAME_10CA7 0x10CA7 // 𐲧 OLD HUNGARIAN CAPITAL LETTER ENT
#define UC_MACRO_NAME_10CA8 0x10CA8 // 𐲨 OLD HUNGARIAN CAPITAL LETTER ETY
#define UC_MACRO_NAME_10CA9 0x10CA9 // 𐲩 OLD HUNGARIAN CAPITAL LETTER ECH
#define UC_MACRO_NAME_10CAA 0x10CAA // 𐲪 OLD HUNGARIAN CAPITAL LETTER U
#define UC_MACRO_NAME_10CAB 0x10CAB // 𐲫 OLD HUNGARIAN CAPITAL LETTER UU
#define UC_MACRO_NAME_10CAC 0x10CAC // 𐲬 OLD HUNGARIAN CAPITAL LETTER NIKOLSBURG UE
#define UC_MACRO_NAME_10CAD 0x10CAD // 𐲭 OLD HUNGARIAN CAPITAL LETTER RUDIMENTA UE
#define UC_MACRO_NAME_10CAE 0x10CAE // 𐲮 OLD HUNGARIAN CAPITAL LETTER EV
#define UC_MACRO_NAME_10CAF 0x10CAF // 𐲯 OLD HUNGARIAN CAPITAL LETTER EZ
#define UC_MACRO_NAME_10CB0 0x10CB0 // 𐲰 OLD HUNGARIAN CAPITAL LETTER EZS
#define UC_MACRO_NAME_10CB1 0x10CB1 // 𐲱 OLD HUNGARIAN CAPITAL LETTER ENT-SHAPED SIGN
#define UC_MACRO_NAME_10CB2 0x10CB2 // 𐲲 OLD HUNGARIAN CAPITAL LETTER US
#define UC_MACRO_NAME_10CC0 0x10CC0 // 𐳀 OLD HUNGARIAN SMALL LETTER A
#define UC_MACRO_NAME_10CC1 0x10CC1 // 𐳁 OLD HUNGARIAN SMALL LETTER AA
#define UC_MACRO_NAME_10CC2 0x10CC2 // 𐳂 OLD HUNGARIAN SMALL LETTER EB
#define UC_MACRO_NAME_10CC3 0x10CC3 // 𐳃 OLD HUNGARIAN SMALL LETTER AMB
#define UC_MACRO_NAME_10CC4 0x10CC4 // 𐳄 OLD HUNGARIAN SMALL LETTER EC
#define UC_MACRO_NAME_10CC5 0x10CC5 // 𐳅 OLD HUNGARIAN SMALL LETTER ENC
#define UC_MACRO_NAME_10CC6 0x10CC6 // 𐳆 OLD HUNGARIAN SMALL LETTER ECS
#define UC_MACRO_NAME_10CC7 0x10CC7 // 𐳇 OLD HUNGARIAN SMALL LETTER ED
#define UC_MACRO_NAME_10CC8 0x10CC8 // 𐳈 OLD HUNGARIAN SMALL LETTER AND
#define UC_MACRO_NAME_10CC9 0x10CC9 // 𐳉 OLD HUNGARIAN SMALL LETTER E
#define UC_MACRO_NAME_10CCA 0x10CCA // 𐳊 OLD HUNGARIAN SMALL LETTER CLOSE E
#define UC_MACRO_NAME_10CCB 0x10CCB // 𐳋 OLD HUNGARIAN SMALL LETTER EE
#define UC_MACRO_NAME_10CCC 0x10CCC // 𐳌 OLD HUNGARIAN SMALL LETTER EF
#define UC_MACRO_NAME_10CCD 0x10CCD // 𐳍 OLD HUNGARIAN SMALL LETTER EG
#define UC_MACRO_NAME_10CCE 0x10CCE // 𐳎 OLD HUNGARIAN SMALL LETTER EGY
#define UC_MACRO_NAME_10CCF 0x10CCF // 𐳏 OLD HUNGARIAN SMALL LETTER EH
#define UC_MACRO_NAME_10CD0 0x10CD0 // 𐳐 OLD HUNGARIAN SMALL LETTER I
#define UC_MACRO_NAME_10CD1 0x10CD1 // 𐳑 OLD HUNGARIAN SMALL LETTER II
#define UC_MACRO_NAME_10CD2 0x10CD2 // 𐳒 OLD HUNGARIAN SMALL LETTER EJ
#define UC_MACRO_NAME_10CD3 0x10CD3 // 𐳓 OLD HUNGARIAN SMALL LETTER EK
#define UC_MACRO_NAME_10CD4 0x10CD4 // 𐳔 OLD HUNGARIAN SMALL LETTER AK
#define UC_MACRO_NAME_10CD5 0x10CD5 // 𐳕 OLD HUNGARIAN SMALL LETTER UNK
#define UC_MACRO_NAME_10CD6 0x10CD6 // 𐳖 OLD HUNGARIAN SMALL LETTER EL
#define UC_MACRO_NAME_10CD7 0x10CD7 // 𐳗 OLD HUNGARIAN SMALL LETTER ELY
#define UC_MACRO_NAME_10CD8 0x10CD8 // 𐳘 OLD HUNGARIAN SMALL LETTER EM
#define UC_MACRO_NAME_10CD9 0x10CD9 // 𐳙 OLD HUNGARIAN SMALL LETTER EN
#define UC_MACRO_NAME_10CDA 0x10CDA // 𐳚 OLD HUNGARIAN SMALL LETTER ENY
#define UC_MACRO_NAME_10CDB 0x10CDB // 𐳛 OLD HUNGARIAN SMALL LETTER O
#define UC_MACRO_NAME_10CDC 0x10CDC // 𐳜 OLD HUNGARIAN SMALL LETTER OO
#define UC_MACRO_NAME_10CDD 0x10CDD // 𐳝 OLD HUNGARIAN SMALL LETTER NIKOLSBURG OE
#define UC_MACRO_NAME_10CDE 0x10CDE // 𐳞 OLD HUNGARIAN SMALL LETTER RUDIMENTA OE
#define UC_MACRO_NAME_10CDF 0x10CDF // 𐳟 OLD HUNGARIAN SMALL LETTER OEE
#define UC_MACRO_NAME_10CE0 0x10CE0 // 𐳠 OLD HUNGARIAN SMALL LETTER EP
#define UC_MACRO_NAME_10CE1 0x10CE1 // 𐳡 OLD HUNGARIAN SMALL LETTER EMP
#define UC_MACRO_NAME_10CE2 0x10CE2 // 𐳢 OLD HUNGARIAN SMALL LETTER ER
#define UC_MACRO_NAME_10CE3 0x10CE3 // 𐳣 OLD HUNGARIAN SMALL LETTER SHORT ER
#define UC_MACRO_NAME_10CE4 0x10CE4 // 𐳤 OLD HUNGARIAN SMALL LETTER ES
#define UC_MACRO_NAME_10CE5 0x10CE5 // 𐳥 OLD HUNGARIAN SMALL LETTER ESZ
#define UC_MACRO_NAME_10CE6 0x10CE6 // 𐳦 OLD HUNGARIAN SMALL LETTER ET
#define UC_MACRO_NAME_10CE7 0x10CE7 // 𐳧 OLD HUNGARIAN SMALL LETTER ENT
#define UC_MACRO_NAME_10CE8 0x10CE8 // 𐳨 OLD HUNGARIAN SMALL LETTER ETY
#define UC_MACRO_NAME_10CE9 0x10CE9 // 𐳩 OLD HUNGARIAN SMALL LETTER ECH
#define UC_MACRO_NAME_10CEA 0x10CEA // 𐳪 OLD HUNGARIAN SMALL LETTER U
#define UC_MACRO_NAME_10CEB 0x10CEB // 𐳫 OLD HUNGARIAN SMALL LETTER UU
#define UC_MACRO_NAME_10CEC 0x10CEC // 𐳬 OLD HUNGARIAN SMALL LETTER NIKOLSBURG UE
#define UC_MACRO_NAME_10CED 0x10CED // 𐳭 OLD HUNGARIAN SMALL LETTER RUDIMENTA UE
#define UC_MACRO_NAME_10CEE 0x10CEE // 𐳮 OLD HUNGARIAN SMALL LETTER EV
#define UC_MACRO_NAME_10CEF 0x10CEF // 𐳯 OLD HUNGARIAN SMALL LETTER EZ
#define UC_MACRO_NAME_10CF0 0x10CF0 // 𐳰 OLD HUNGARIAN SMALL LETTER EZS
#define UC_MACRO_NAME_10CF1 0x10CF1 // 𐳱 OLD HUNGARIAN SMALL LETTER ENT-SHAPED SIGN
#define UC_MACRO_NAME_10CF2 0x10CF2 // 𐳲 OLD HUNGARIAN SMALL LETTER US
#define UC_MACRO_NAME_10CFA 0x10CFA // 𐳺 OLD HUNGARIAN NUMBER ONE
#define UC_MACRO_NAME_10CFB 0x10CFB // 𐳻 OLD HUNGARIAN NUMBER FIVE
#define UC_MACRO_NAME_10CFC 0x10CFC // 𐳼 OLD HUNGARIAN NUMBER TEN
#define UC_MACRO_NAME_10CFD 0x10CFD // 𐳽 OLD HUNGARIAN NUMBER FIFTY
#define UC_MACRO_NAME_10CFE 0x10CFE // 𐳾 OLD HUNGARIAN NUMBER ONE HUNDRED
#define UC_MACRO_NAME_10CFF 0x10CFF // 𐳿 OLD HUNGARIAN NUMBER ONE THOUSAND


#endif // UC_H_OLD_HUNGARIAN
