/*
 * Unicode Block: Ottoman Siyaq Numbers
 * Range: U+1ED00..U+1ED4F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_OTTOMAN_SIYAQ_NUMBERS
#define UC_H_OTTOMAN_SIYAQ_NUMBERS

#define UC_MACRO_NAME_1ED01 0x1ED01 // 𞴁 OTTOMAN SIYAQ NUMBER ONE
#define UC_MACRO_NAME_1ED02 0x1ED02 // 𞴂 OTTOMAN SIYAQ NUMBER TWO
#define UC_MACRO_NAME_1ED03 0x1ED03 // 𞴃 OTTOMAN SIYAQ NUMBER THREE
#define UC_MACRO_NAME_1ED04 0x1ED04 // 𞴄 OTTOMAN SIYAQ NUMBER FOUR
#define UC_MACRO_NAME_1ED05 0x1ED05 // 𞴅 OTTOMAN SIYAQ NUMBER FIVE
#define UC_MACRO_NAME_1ED06 0x1ED06 // 𞴆 OTTOMAN SIYAQ NUMBER SIX
#define UC_MACRO_NAME_1ED07 0x1ED07 // 𞴇 OTTOMAN SIYAQ NUMBER SEVEN
#define UC_MACRO_NAME_1ED08 0x1ED08 // 𞴈 OTTOMAN SIYAQ NUMBER EIGHT
#define UC_MACRO_NAME_1ED09 0x1ED09 // 𞴉 OTTOMAN SIYAQ NUMBER NINE
#define UC_MACRO_NAME_1ED0A 0x1ED0A // 𞴊 OTTOMAN SIYAQ NUMBER TEN
#define UC_MACRO_NAME_1ED0B 0x1ED0B // 𞴋 OTTOMAN SIYAQ NUMBER TWENTY
#define UC_MACRO_NAME_1ED0C 0x1ED0C // 𞴌 OTTOMAN SIYAQ NUMBER THIRTY
#define UC_MACRO_NAME_1ED0D 0x1ED0D // 𞴍 OTTOMAN SIYAQ NUMBER FORTY
#define UC_MACRO_NAME_1ED0E 0x1ED0E // 𞴎 OTTOMAN SIYAQ NUMBER FIFTY
#define UC_MACRO_NAME_1ED0F 0x1ED0F // 𞴏 OTTOMAN SIYAQ NUMBER SIXTY
#define UC_MACRO_NAME_1ED10 0x1ED10 // 𞴐 OTTOMAN SIYAQ NUMBER SEVENTY
#define UC_MACRO_NAME_1ED11 0x1ED11 // 𞴑 OTTOMAN SIYAQ NUMBER EIGHTY
#define UC_MACRO_NAME_1ED12 0x1ED12 // 𞴒 OTTOMAN SIYAQ NUMBER NINETY
#define UC_MACRO_NAME_1ED13 0x1ED13 // 𞴓 OTTOMAN SIYAQ NUMBER ONE HUNDRED
#define UC_MACRO_NAME_1ED14 0x1ED14 // 𞴔 OTTOMAN SIYAQ NUMBER TWO HUNDRED
#define UC_MACRO_NAME_1ED15 0x1ED15 // 𞴕 OTTOMAN SIYAQ NUMBER THREE HUNDRED
#define UC_MACRO_NAME_1ED16 0x1ED16 // 𞴖 OTTOMAN SIYAQ NUMBER FOUR HUNDRED
#define UC_MACRO_NAME_1ED17 0x1ED17 // 𞴗 OTTOMAN SIYAQ NUMBER FIVE HUNDRED
#define UC_MACRO_NAME_1ED18 0x1ED18 // 𞴘 OTTOMAN SIYAQ NUMBER SIX HUNDRED
#define UC_MACRO_NAME_1ED19 0x1ED19 // 𞴙 OTTOMAN SIYAQ NUMBER SEVEN HUNDRED
#define UC_MACRO_NAME_1ED1A 0x1ED1A // 𞴚 OTTOMAN SIYAQ NUMBER EIGHT HUNDRED
#define UC_MACRO_NAME_1ED1B 0x1ED1B // 𞴛 OTTOMAN SIYAQ NUMBER NINE HUNDRED
#define UC_MACRO_NAME_1ED1C 0x1ED1C // 𞴜 OTTOMAN SIYAQ NUMBER ONE THOUSAND
#define UC_MACRO_NAME_1ED1D 0x1ED1D // 𞴝 OTTOMAN SIYAQ NUMBER TWO THOUSAND
#define UC_MACRO_NAME_1ED1E 0x1ED1E // 𞴞 OTTOMAN SIYAQ NUMBER THREE THOUSAND
#define UC_MACRO_NAME_1ED1F 0x1ED1F // 𞴟 OTTOMAN SIYAQ NUMBER FOUR THOUSAND
#define UC_MACRO_NAME_1ED20 0x1ED20 // 𞴠 OTTOMAN SIYAQ NUMBER FIVE THOUSAND
#define UC_MACRO_NAME_1ED21 0x1ED21 // 𞴡 OTTOMAN SIYAQ NUMBER SIX THOUSAND
#define UC_MACRO_NAME_1ED22 0x1ED22 // 𞴢 OTTOMAN SIYAQ NUMBER SEVEN THOUSAND
#define UC_MACRO_NAME_1ED23 0x1ED23 // 𞴣 OTTOMAN SIYAQ NUMBER EIGHT THOUSAND
#define UC_MACRO_NAME_1ED24 0x1ED24 // 𞴤 OTTOMAN SIYAQ NUMBER NINE THOUSAND
#define UC_MACRO_NAME_1ED25 0x1ED25 // 𞴥 OTTOMAN SIYAQ NUMBER TEN THOUSAND
#define UC_MACRO_NAME_1ED26 0x1ED26 // 𞴦 OTTOMAN SIYAQ NUMBER TWENTY THOUSAND
#define UC_MACRO_NAME_1ED27 0x1ED27 // 𞴧 OTTOMAN SIYAQ NUMBER THIRTY THOUSAND
#define UC_MACRO_NAME_1ED28 0x1ED28 // 𞴨 OTTOMAN SIYAQ NUMBER FORTY THOUSAND
#define UC_MACRO_NAME_1ED29 0x1ED29 // 𞴩 OTTOMAN SIYAQ NUMBER FIFTY THOUSAND
#define UC_MACRO_NAME_1ED2A 0x1ED2A // 𞴪 OTTOMAN SIYAQ NUMBER SIXTY THOUSAND
#define UC_MACRO_NAME_1ED2B 0x1ED2B // 𞴫 OTTOMAN SIYAQ NUMBER SEVENTY THOUSAND
#define UC_MACRO_NAME_1ED2C 0x1ED2C // 𞴬 OTTOMAN SIYAQ NUMBER EIGHTY THOUSAND
#define UC_MACRO_NAME_1ED2D 0x1ED2D // 𞴭 OTTOMAN SIYAQ NUMBER NINETY THOUSAND
#define UC_MACRO_NAME_1ED2E 0x1ED2E // 𞴮 OTTOMAN SIYAQ MARRATAN
#define UC_MACRO_NAME_1ED2F 0x1ED2F // 𞴯 OTTOMAN SIYAQ ALTERNATE NUMBER TWO
#define UC_MACRO_NAME_1ED30 0x1ED30 // 𞴰 OTTOMAN SIYAQ ALTERNATE NUMBER THREE
#define UC_MACRO_NAME_1ED31 0x1ED31 // 𞴱 OTTOMAN SIYAQ ALTERNATE NUMBER FOUR
#define UC_MACRO_NAME_1ED32 0x1ED32 // 𞴲 OTTOMAN SIYAQ ALTERNATE NUMBER FIVE
#define UC_MACRO_NAME_1ED33 0x1ED33 // 𞴳 OTTOMAN SIYAQ ALTERNATE NUMBER SIX
#define UC_MACRO_NAME_1ED34 0x1ED34 // 𞴴 OTTOMAN SIYAQ ALTERNATE NUMBER SEVEN
#define UC_MACRO_NAME_1ED35 0x1ED35 // 𞴵 OTTOMAN SIYAQ ALTERNATE NUMBER EIGHT
#define UC_MACRO_NAME_1ED36 0x1ED36 // 𞴶 OTTOMAN SIYAQ ALTERNATE NUMBER NINE
#define UC_MACRO_NAME_1ED37 0x1ED37 // 𞴷 OTTOMAN SIYAQ ALTERNATE NUMBER TEN
#define UC_MACRO_NAME_1ED38 0x1ED38 // 𞴸 OTTOMAN SIYAQ ALTERNATE NUMBER FOUR HUNDRED
#define UC_MACRO_NAME_1ED39 0x1ED39 // 𞴹 OTTOMAN SIYAQ ALTERNATE NUMBER SIX HUNDRED
#define UC_MACRO_NAME_1ED3A 0x1ED3A // 𞴺 OTTOMAN SIYAQ ALTERNATE NUMBER TWO THOUSAND
#define UC_MACRO_NAME_1ED3B 0x1ED3B // 𞴻 OTTOMAN SIYAQ ALTERNATE NUMBER TEN THOUSAND
#define UC_MACRO_NAME_1ED3C 0x1ED3C // 𞴼 OTTOMAN SIYAQ FRACTION ONE HALF
#define UC_MACRO_NAME_1ED3D 0x1ED3D // 𞴽 OTTOMAN SIYAQ FRACTION ONE SIXTH


#endif // UC_H_OTTOMAN_SIYAQ_NUMBERS
