/*
 * Unicode Block: Oriya
 * Range: U+0B00..U+0B7F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Oriya (also spelled Odia ) may refer to:
 *
 */
#ifndef UC_H_ORIYA
#define UC_H_ORIYA

#define UC_MACRO_NAME_B01 0x0B01 // ଁ ORIYA SIGN CANDRABINDU
#define UC_MACRO_NAME_B02 0x0B02 // ଂ ORIYA SIGN ANUSVARA
#define UC_MACRO_NAME_B03 0x0B03 // ଃ ORIYA SIGN VISARGA
#define UC_MACRO_NAME_B05 0x0B05 // ଅ ORIYA LETTER A
#define UC_MACRO_NAME_B06 0x0B06 // ଆ ORIYA LETTER AA
#define UC_MACRO_NAME_B07 0x0B07 // ଇ ORIYA LETTER I
#define UC_MACRO_NAME_B08 0x0B08 // ଈ ORIYA LETTER II
#define UC_MACRO_NAME_B09 0x0B09 // ଉ ORIYA LETTER U
#define UC_MACRO_NAME_B0A 0x0B0A // ଊ ORIYA LETTER UU
#define UC_MACRO_NAME_B0B 0x0B0B // ଋ ORIYA LETTER VOCALIC R
#define UC_MACRO_NAME_B0C 0x0B0C // ଌ ORIYA LETTER VOCALIC L
#define UC_MACRO_NAME_B0F 0x0B0F // ଏ ORIYA LETTER E
#define UC_MACRO_NAME_B10 0x0B10 // ଐ ORIYA LETTER AI
#define UC_MACRO_NAME_B13 0x0B13 // ଓ ORIYA LETTER O
#define UC_MACRO_NAME_B14 0x0B14 // ଔ ORIYA LETTER AU
#define UC_MACRO_NAME_B15 0x0B15 // କ ORIYA LETTER KA
#define UC_MACRO_NAME_B16 0x0B16 // ଖ ORIYA LETTER KHA
#define UC_MACRO_NAME_B17 0x0B17 // ଗ ORIYA LETTER GA
#define UC_MACRO_NAME_B18 0x0B18 // ଘ ORIYA LETTER GHA
#define UC_MACRO_NAME_B19 0x0B19 // ଙ ORIYA LETTER NGA
#define UC_MACRO_NAME_B1A 0x0B1A // ଚ ORIYA LETTER CA
#define UC_MACRO_NAME_B1B 0x0B1B // ଛ ORIYA LETTER CHA
#define UC_MACRO_NAME_B1C 0x0B1C // ଜ ORIYA LETTER JA
#define UC_MACRO_NAME_B1D 0x0B1D // ଝ ORIYA LETTER JHA
#define UC_MACRO_NAME_B1E 0x0B1E // ଞ ORIYA LETTER NYA
#define UC_MACRO_NAME_B1F 0x0B1F // ଟ ORIYA LETTER TTA
#define UC_MACRO_NAME_B20 0x0B20 // ଠ ORIYA LETTER TTHA
#define UC_MACRO_NAME_B21 0x0B21 // ଡ ORIYA LETTER DDA
#define UC_MACRO_NAME_B22 0x0B22 // ଢ ORIYA LETTER DDHA
#define UC_MACRO_NAME_B23 0x0B23 // ଣ ORIYA LETTER NNA
#define UC_MACRO_NAME_B24 0x0B24 // ତ ORIYA LETTER TA
#define UC_MACRO_NAME_B25 0x0B25 // ଥ ORIYA LETTER THA
#define UC_MACRO_NAME_B26 0x0B26 // ଦ ORIYA LETTER DA
#define UC_MACRO_NAME_B27 0x0B27 // ଧ ORIYA LETTER DHA
#define UC_MACRO_NAME_B28 0x0B28 // ନ ORIYA LETTER NA
#define UC_MACRO_NAME_B2A 0x0B2A // ପ ORIYA LETTER PA
#define UC_MACRO_NAME_B2B 0x0B2B // ଫ ORIYA LETTER PHA
#define UC_MACRO_NAME_B2C 0x0B2C // ବ ORIYA LETTER BA
#define UC_MACRO_NAME_B2D 0x0B2D // ଭ ORIYA LETTER BHA
#define UC_MACRO_NAME_B2E 0x0B2E // ମ ORIYA LETTER MA
#define UC_MACRO_NAME_B2F 0x0B2F // ଯ ORIYA LETTER YA
#define UC_MACRO_NAME_B30 0x0B30 // ର ORIYA LETTER RA
#define UC_MACRO_NAME_B32 0x0B32 // ଲ ORIYA LETTER LA
#define UC_MACRO_NAME_B33 0x0B33 // ଳ ORIYA LETTER LLA
#define UC_MACRO_NAME_B35 0x0B35 // ଵ ORIYA LETTER VA
#define UC_MACRO_NAME_B36 0x0B36 // ଶ ORIYA LETTER SHA
#define UC_MACRO_NAME_B37 0x0B37 // ଷ ORIYA LETTER SSA
#define UC_MACRO_NAME_B38 0x0B38 // ସ ORIYA LETTER SA
#define UC_MACRO_NAME_B39 0x0B39 // ହ ORIYA LETTER HA
#define UC_MACRO_NAME_B3C 0x0B3C // ଼ ORIYA SIGN NUKTA
#define UC_MACRO_NAME_B3D 0x0B3D // ଽ ORIYA SIGN AVAGRAHA
#define UC_MACRO_NAME_B3E 0x0B3E // ା ORIYA VOWEL SIGN AA
#define UC_MACRO_NAME_B3F 0x0B3F // ି ORIYA VOWEL SIGN I
#define UC_MACRO_NAME_B40 0x0B40 // ୀ ORIYA VOWEL SIGN II
#define UC_MACRO_NAME_B41 0x0B41 // ୁ ORIYA VOWEL SIGN U
#define UC_MACRO_NAME_B42 0x0B42 // ୂ ORIYA VOWEL SIGN UU
#define UC_MACRO_NAME_B43 0x0B43 // ୃ ORIYA VOWEL SIGN VOCALIC R
#define UC_MACRO_NAME_B44 0x0B44 // ୄ ORIYA VOWEL SIGN VOCALIC RR
#define UC_MACRO_NAME_B47 0x0B47 // େ ORIYA VOWEL SIGN E
#define UC_MACRO_NAME_B48 0x0B48 // ୈ ORIYA VOWEL SIGN AI
#define UC_MACRO_NAME_B4B 0x0B4B // ୋ ORIYA VOWEL SIGN O
#define UC_MACRO_NAME_B4C 0x0B4C // ୌ ORIYA VOWEL SIGN AU
#define UC_MACRO_NAME_B4D 0x0B4D // ୍ ORIYA SIGN VIRAMA
#define UC_MACRO_NAME_B55 0x0B55 // ୕ ORIYA SIGN OVERLINE
#define UC_MACRO_NAME_B56 0x0B56 // ୖ ORIYA AI LENGTH MARK
#define UC_MACRO_NAME_B57 0x0B57 // ୗ ORIYA AU LENGTH MARK
#define UC_MACRO_NAME_B5C 0x0B5C // ଡ଼ ORIYA LETTER RRA
#define UC_MACRO_NAME_B5D 0x0B5D // ଢ଼ ORIYA LETTER RHA
#define UC_MACRO_NAME_B5F 0x0B5F // ୟ ORIYA LETTER YYA
#define UC_MACRO_NAME_B60 0x0B60 // ୠ ORIYA LETTER VOCALIC RR
#define UC_MACRO_NAME_B61 0x0B61 // ୡ ORIYA LETTER VOCALIC LL
#define UC_MACRO_NAME_B62 0x0B62 // ୢ ORIYA VOWEL SIGN VOCALIC L
#define UC_MACRO_NAME_B63 0x0B63 // ୣ ORIYA VOWEL SIGN VOCALIC LL
#define UC_MACRO_NAME_B66 0x0B66 // ୦ ORIYA DIGIT ZERO
#define UC_MACRO_NAME_B67 0x0B67 // ୧ ORIYA DIGIT ONE
#define UC_MACRO_NAME_B68 0x0B68 // ୨ ORIYA DIGIT TWO
#define UC_MACRO_NAME_B69 0x0B69 // ୩ ORIYA DIGIT THREE
#define UC_MACRO_NAME_B6A 0x0B6A // ୪ ORIYA DIGIT FOUR
#define UC_MACRO_NAME_B6B 0x0B6B // ୫ ORIYA DIGIT FIVE
#define UC_MACRO_NAME_B6C 0x0B6C // ୬ ORIYA DIGIT SIX
#define UC_MACRO_NAME_B6D 0x0B6D // ୭ ORIYA DIGIT SEVEN
#define UC_MACRO_NAME_B6E 0x0B6E // ୮ ORIYA DIGIT EIGHT
#define UC_MACRO_NAME_B6F 0x0B6F // ୯ ORIYA DIGIT NINE
#define UC_MACRO_NAME_B70 0x0B70 // ୰ ORIYA ISSHAR
#define UC_MACRO_NAME_B71 0x0B71 // ୱ ORIYA LETTER WA
#define UC_MACRO_NAME_B72 0x0B72 // ୲ ORIYA FRACTION ONE QUARTER
#define UC_MACRO_NAME_B73 0x0B73 // ୳ ORIYA FRACTION ONE HALF
#define UC_MACRO_NAME_B74 0x0B74 // ୴ ORIYA FRACTION THREE QUARTERS
#define UC_MACRO_NAME_B75 0x0B75 // ୵ ORIYA FRACTION ONE SIXTEENTH
#define UC_MACRO_NAME_B76 0x0B76 // ୶ ORIYA FRACTION ONE EIGHTH
#define UC_MACRO_NAME_B77 0x0B77 // ୷ ORIYA FRACTION THREE SIXTEENTHS


#endif // UC_H_ORIYA
