/*
 * Unicode Block: Ol Onal
 * Range: U+1E5D0..U+1E5FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * The Ol Onal , also known as also known as Bhumij Lipi or Bhumij Onal ,
 * is an alphabetic writing system for the Bhumij language . Ol Onal
 * script was created between 1981 and 1992 by Ol Guru Mahendra Nath
 * Sardar . Ol Onal script is used to write the Bhumij language in some
 * parts of West Bengal , Jharkhand , Orissa , and Assam .
 *
 */
#ifndef UC_H_OL_ONAL
#define UC_H_OL_ONAL

#define UC_MACRO_NAME_1E5D0 0x1E5D0 //  OL ONAL LETTER O
#define UC_MACRO_NAME_1E5D1 0x1E5D1 //  OL ONAL LETTER OM
#define UC_MACRO_NAME_1E5D2 0x1E5D2 //  OL ONAL LETTER ONG
#define UC_MACRO_NAME_1E5D3 0x1E5D3 //  OL ONAL LETTER ORR
#define UC_MACRO_NAME_1E5D4 0x1E5D4 //  OL ONAL LETTER OO
#define UC_MACRO_NAME_1E5D5 0x1E5D5 //  OL ONAL LETTER OY
#define UC_MACRO_NAME_1E5D6 0x1E5D6 //  OL ONAL LETTER A
#define UC_MACRO_NAME_1E5D7 0x1E5D7 //  OL ONAL LETTER AD
#define UC_MACRO_NAME_1E5D8 0x1E5D8 //  OL ONAL LETTER AB
#define UC_MACRO_NAME_1E5D9 0x1E5D9 //  OL ONAL LETTER AH
#define UC_MACRO_NAME_1E5DA 0x1E5DA //  OL ONAL LETTER AL
#define UC_MACRO_NAME_1E5DB 0x1E5DB //  OL ONAL LETTER AW
#define UC_MACRO_NAME_1E5DC 0x1E5DC //  OL ONAL LETTER I
#define UC_MACRO_NAME_1E5DD 0x1E5DD //  OL ONAL LETTER IT
#define UC_MACRO_NAME_1E5DE 0x1E5DE //  OL ONAL LETTER IP
#define UC_MACRO_NAME_1E5DF 0x1E5DF //  OL ONAL LETTER ITT
#define UC_MACRO_NAME_1E5E0 0x1E5E0 //  OL ONAL LETTER ID
#define UC_MACRO_NAME_1E5E1 0x1E5E1 //  OL ONAL LETTER IN
#define UC_MACRO_NAME_1E5E2 0x1E5E2 //  OL ONAL LETTER U
#define UC_MACRO_NAME_1E5E3 0x1E5E3 //  OL ONAL LETTER UK
#define UC_MACRO_NAME_1E5E4 0x1E5E4 //  OL ONAL LETTER UDD
#define UC_MACRO_NAME_1E5E5 0x1E5E5 //  OL ONAL LETTER UJ
#define UC_MACRO_NAME_1E5E6 0x1E5E6 //  OL ONAL LETTER UNY
#define UC_MACRO_NAME_1E5E7 0x1E5E7 //  OL ONAL LETTER UR
#define UC_MACRO_NAME_1E5E8 0x1E5E8 //  OL ONAL LETTER E
#define UC_MACRO_NAME_1E5E9 0x1E5E9 //  OL ONAL LETTER ES
#define UC_MACRO_NAME_1E5EA 0x1E5EA //  OL ONAL LETTER EH
#define UC_MACRO_NAME_1E5EB 0x1E5EB //  OL ONAL LETTER EC
#define UC_MACRO_NAME_1E5EC 0x1E5EC //  OL ONAL LETTER ENN
#define UC_MACRO_NAME_1E5ED 0x1E5ED //  OL ONAL LETTER EG
#define UC_MACRO_NAME_1E5EE 0x1E5EE //  OL ONAL SIGN MU
#define UC_MACRO_NAME_1E5EF 0x1E5EF //  OL ONAL SIGN IKIR
#define UC_MACRO_NAME_1E5F0 0x1E5F0 //  OL ONAL SIGN HODDOND
#define UC_MACRO_NAME_1E5F1 0x1E5F1 //  OL ONAL DIGIT ZERO
#define UC_MACRO_NAME_1E5F2 0x1E5F2 //  OL ONAL DIGIT ONE
#define UC_MACRO_NAME_1E5F3 0x1E5F3 //  OL ONAL DIGIT TWO
#define UC_MACRO_NAME_1E5F4 0x1E5F4 //  OL ONAL DIGIT THREE
#define UC_MACRO_NAME_1E5F5 0x1E5F5 //  OL ONAL DIGIT FOUR
#define UC_MACRO_NAME_1E5F6 0x1E5F6 //  OL ONAL DIGIT FIVE
#define UC_MACRO_NAME_1E5F7 0x1E5F7 //  OL ONAL DIGIT SIX
#define UC_MACRO_NAME_1E5F8 0x1E5F8 //  OL ONAL DIGIT SEVEN
#define UC_MACRO_NAME_1E5F9 0x1E5F9 //  OL ONAL DIGIT EIGHT
#define UC_MACRO_NAME_1E5FA 0x1E5FA //  OL ONAL DIGIT NINE
#define UC_MACRO_NAME_1E5FF 0x1E5FF //  OL ONAL ABBREVIATION SIGN


#endif // UC_H_OL_ONAL
