/*
 * Unicode Block: Psalter Pahlavi
 * Range: U+10B80..U+10BAF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Psalter Pahlavi is a cursive abjad that was used for writing Middle
 * Persian on paper; it is thus described as one of the Pahlavi scripts .
 * It was written right to left, usually with spaces between words.
 * It takes its name from the Pahlavi Psalter , part of the Psalms
 * translated from Syriac to Middle Persian and found in what is now
 * western China.
 *
 */
#ifndef UC_H_PSALTER_PAHLAVI
#define UC_H_PSALTER_PAHLAVI

#define UC_MACRO_NAME_10B80 0x10B80 // 𐮀 PSALTER PAHLAVI LETTER ALEPH
#define UC_MACRO_NAME_10B81 0x10B81 // 𐮁 PSALTER PAHLAVI LETTER BETH
#define UC_MACRO_NAME_10B82 0x10B82 // 𐮂 PSALTER PAHLAVI LETTER GIMEL
#define UC_MACRO_NAME_10B83 0x10B83 // 𐮃 PSALTER PAHLAVI LETTER DALETH
#define UC_MACRO_NAME_10B84 0x10B84 // 𐮄 PSALTER PAHLAVI LETTER HE
#define UC_MACRO_NAME_10B85 0x10B85 // 𐮅 PSALTER PAHLAVI LETTER WAW-AYIN-RESH
#define UC_MACRO_NAME_10B86 0x10B86 // 𐮆 PSALTER PAHLAVI LETTER ZAYIN
#define UC_MACRO_NAME_10B87 0x10B87 // 𐮇 PSALTER PAHLAVI LETTER HETH
#define UC_MACRO_NAME_10B88 0x10B88 // 𐮈 PSALTER PAHLAVI LETTER YODH
#define UC_MACRO_NAME_10B89 0x10B89 // 𐮉 PSALTER PAHLAVI LETTER KAPH
#define UC_MACRO_NAME_10B8A 0x10B8A // 𐮊 PSALTER PAHLAVI LETTER LAMEDH
#define UC_MACRO_NAME_10B8B 0x10B8B // 𐮋 PSALTER PAHLAVI LETTER MEM-QOPH
#define UC_MACRO_NAME_10B8C 0x10B8C // 𐮌 PSALTER PAHLAVI LETTER NUN
#define UC_MACRO_NAME_10B8D 0x10B8D // 𐮍 PSALTER PAHLAVI LETTER SAMEKH
#define UC_MACRO_NAME_10B8E 0x10B8E // 𐮎 PSALTER PAHLAVI LETTER PE
#define UC_MACRO_NAME_10B8F 0x10B8F // 𐮏 PSALTER PAHLAVI LETTER SADHE
#define UC_MACRO_NAME_10B90 0x10B90 // 𐮐 PSALTER PAHLAVI LETTER SHIN
#define UC_MACRO_NAME_10B91 0x10B91 // 𐮑 PSALTER PAHLAVI LETTER TAW
#define UC_MACRO_NAME_10B99 0x10B99 // 𐮙 PSALTER PAHLAVI SECTION MARK
#define UC_MACRO_NAME_10B9A 0x10B9A // 𐮚 PSALTER PAHLAVI TURNED SECTION MARK
#define UC_MACRO_NAME_10B9B 0x10B9B // 𐮛 PSALTER PAHLAVI FOUR DOTS WITH CROSS
#define UC_MACRO_NAME_10B9C 0x10B9C // 𐮜 PSALTER PAHLAVI FOUR DOTS WITH DOT
#define UC_MACRO_NAME_10BA9 0x10BA9 // 𐮩 PSALTER PAHLAVI NUMBER ONE
#define UC_MACRO_NAME_10BAA 0x10BAA // 𐮪 PSALTER PAHLAVI NUMBER TWO
#define UC_MACRO_NAME_10BAB 0x10BAB // 𐮫 PSALTER PAHLAVI NUMBER THREE
#define UC_MACRO_NAME_10BAC 0x10BAC // 𐮬 PSALTER PAHLAVI NUMBER FOUR
#define UC_MACRO_NAME_10BAD 0x10BAD // 𐮭 PSALTER PAHLAVI NUMBER TEN
#define UC_MACRO_NAME_10BAE 0x10BAE // 𐮮 PSALTER PAHLAVI NUMBER TWENTY
#define UC_MACRO_NAME_10BAF 0x10BAF // 𐮯 PSALTER PAHLAVI NUMBER ONE HUNDRED


#endif // UC_H_PSALTER_PAHLAVI
