/*
 * Unicode Block: Phonetic Extensions
 * Range: U+1D00..U+1D7F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Phonetic Extensions is a Unicode block containing phonetic characters
 * used in the Uralic Phonetic Alphabet , Old Irish phonetic notation,
 * the Oxford English Dictionary and American dictionaries , and
 * Americanist and Russianist phonetic notations. Its character set is
 * continued in the following Unicode block, Phonetic Extensions
 * Supplement .
 *
 */
#ifndef UC_H_PHONETIC_EXTENSIONS
#define UC_H_PHONETIC_EXTENSIONS

#define UC_MACRO_NAME_1D00 0x1D00 // ᴀ LATIN LETTER SMALL CAPITAL A
#define UC_MACRO_NAME_1D01 0x1D01 // ᴁ LATIN LETTER SMALL CAPITAL AE
#define UC_MACRO_NAME_1D02 0x1D02 // ᴂ LATIN SMALL LETTER TURNED AE
#define UC_MACRO_NAME_1D03 0x1D03 // ᴃ LATIN LETTER SMALL CAPITAL BARRED B
#define UC_MACRO_NAME_1D04 0x1D04 // ᴄ LATIN LETTER SMALL CAPITAL C
#define UC_MACRO_NAME_1D05 0x1D05 // ᴅ LATIN LETTER SMALL CAPITAL D
#define UC_MACRO_NAME_1D06 0x1D06 // ᴆ LATIN LETTER SMALL CAPITAL ETH
#define UC_MACRO_NAME_1D07 0x1D07 // ᴇ LATIN LETTER SMALL CAPITAL E
#define UC_MACRO_NAME_1D08 0x1D08 // ᴈ LATIN SMALL LETTER TURNED OPEN E
#define UC_MACRO_NAME_1D09 0x1D09 // ᴉ LATIN SMALL LETTER TURNED I
#define UC_MACRO_NAME_1D0A 0x1D0A // ᴊ LATIN LETTER SMALL CAPITAL J
#define UC_MACRO_NAME_1D0B 0x1D0B // ᴋ LATIN LETTER SMALL CAPITAL K
#define UC_MACRO_NAME_1D0C 0x1D0C // ᴌ LATIN LETTER SMALL CAPITAL L WITH STROKE
#define UC_MACRO_NAME_1D0D 0x1D0D // ᴍ LATIN LETTER SMALL CAPITAL M
#define UC_MACRO_NAME_1D0E 0x1D0E // ᴎ LATIN LETTER SMALL CAPITAL REVERSED N
#define UC_MACRO_NAME_1D0F 0x1D0F // ᴏ LATIN LETTER SMALL CAPITAL O
#define UC_MACRO_NAME_1D10 0x1D10 // ᴐ LATIN LETTER SMALL CAPITAL OPEN O
#define UC_MACRO_NAME_1D11 0x1D11 // ᴑ LATIN SMALL LETTER SIDEWAYS O
#define UC_MACRO_NAME_1D12 0x1D12 // ᴒ LATIN SMALL LETTER SIDEWAYS OPEN O
#define UC_MACRO_NAME_1D13 0x1D13 // ᴓ LATIN SMALL LETTER SIDEWAYS O WITH STROKE
#define UC_MACRO_NAME_1D14 0x1D14 // ᴔ LATIN SMALL LETTER TURNED OE
#define UC_MACRO_NAME_1D15 0x1D15 // ᴕ LATIN LETTER SMALL CAPITAL OU
#define UC_MACRO_NAME_1D16 0x1D16 // ᴖ LATIN SMALL LETTER TOP HALF O
#define UC_MACRO_NAME_1D17 0x1D17 // ᴗ LATIN SMALL LETTER BOTTOM HALF O
#define UC_MACRO_NAME_1D18 0x1D18 // ᴘ LATIN LETTER SMALL CAPITAL P
#define UC_MACRO_NAME_1D19 0x1D19 // ᴙ LATIN LETTER SMALL CAPITAL REVERSED R
#define UC_MACRO_NAME_1D1A 0x1D1A // ᴚ LATIN LETTER SMALL CAPITAL TURNED R
#define UC_MACRO_NAME_1D1B 0x1D1B // ᴛ LATIN LETTER SMALL CAPITAL T
#define UC_MACRO_NAME_1D1C 0x1D1C // ᴜ LATIN LETTER SMALL CAPITAL U
#define UC_MACRO_NAME_1D1D 0x1D1D // ᴝ LATIN SMALL LETTER SIDEWAYS U
#define UC_MACRO_NAME_1D1E 0x1D1E // ᴞ LATIN SMALL LETTER SIDEWAYS DIAERESIZED U
#define UC_MACRO_NAME_1D1F 0x1D1F // ᴟ LATIN SMALL LETTER SIDEWAYS TURNED M
#define UC_MACRO_NAME_1D20 0x1D20 // ᴠ LATIN LETTER SMALL CAPITAL V
#define UC_MACRO_NAME_1D21 0x1D21 // ᴡ LATIN LETTER SMALL CAPITAL W
#define UC_MACRO_NAME_1D22 0x1D22 // ᴢ LATIN LETTER SMALL CAPITAL Z
#define UC_MACRO_NAME_1D23 0x1D23 // ᴣ LATIN LETTER SMALL CAPITAL EZH
#define UC_MACRO_NAME_1D24 0x1D24 // ᴤ LATIN LETTER VOICED LARYNGEAL SPIRANT
#define UC_MACRO_NAME_1D25 0x1D25 // ᴥ LATIN LETTER AIN
#define UC_MACRO_NAME_1D26 0x1D26 // ᴦ GREEK LETTER SMALL CAPITAL GAMMA
#define UC_MACRO_NAME_1D27 0x1D27 // ᴧ GREEK LETTER SMALL CAPITAL LAMDA
#define UC_MACRO_NAME_1D28 0x1D28 // ᴨ GREEK LETTER SMALL CAPITAL PI
#define UC_MACRO_NAME_1D29 0x1D29 // ᴩ GREEK LETTER SMALL CAPITAL RHO
#define UC_MACRO_NAME_1D2A 0x1D2A // ᴪ GREEK LETTER SMALL CAPITAL PSI
#define UC_MACRO_NAME_1D2B 0x1D2B // ᴫ CYRILLIC LETTER SMALL CAPITAL EL
#define UC_MACRO_NAME_1D2C 0x1D2C // ᴬ MODIFIER LETTER CAPITAL A
#define UC_MACRO_NAME_1D2D 0x1D2D // ᴭ MODIFIER LETTER CAPITAL AE
#define UC_MACRO_NAME_1D2E 0x1D2E // ᴮ MODIFIER LETTER CAPITAL B
#define UC_MACRO_NAME_1D2F 0x1D2F // ᴯ MODIFIER LETTER CAPITAL BARRED B
#define UC_MACRO_NAME_1D30 0x1D30 // ᴰ MODIFIER LETTER CAPITAL D
#define UC_MACRO_NAME_1D31 0x1D31 // ᴱ MODIFIER LETTER CAPITAL E
#define UC_MACRO_NAME_1D32 0x1D32 // ᴲ MODIFIER LETTER CAPITAL REVERSED E
#define UC_MACRO_NAME_1D33 0x1D33 // ᴳ MODIFIER LETTER CAPITAL G
#define UC_MACRO_NAME_1D34 0x1D34 // ᴴ MODIFIER LETTER CAPITAL H
#define UC_MACRO_NAME_1D35 0x1D35 // ᴵ MODIFIER LETTER CAPITAL I
#define UC_MACRO_NAME_1D36 0x1D36 // ᴶ MODIFIER LETTER CAPITAL J
#define UC_MACRO_NAME_1D37 0x1D37 // ᴷ MODIFIER LETTER CAPITAL K
#define UC_MACRO_NAME_1D38 0x1D38 // ᴸ MODIFIER LETTER CAPITAL L
#define UC_MACRO_NAME_1D39 0x1D39 // ᴹ MODIFIER LETTER CAPITAL M
#define UC_MACRO_NAME_1D3A 0x1D3A // ᴺ MODIFIER LETTER CAPITAL N
#define UC_MACRO_NAME_1D3B 0x1D3B // ᴻ MODIFIER LETTER CAPITAL REVERSED N
#define UC_MACRO_NAME_1D3C 0x1D3C // ᴼ MODIFIER LETTER CAPITAL O
#define UC_MACRO_NAME_1D3D 0x1D3D // ᴽ MODIFIER LETTER CAPITAL OU
#define UC_MACRO_NAME_1D3E 0x1D3E // ᴾ MODIFIER LETTER CAPITAL P
#define UC_MACRO_NAME_1D3F 0x1D3F // ᴿ MODIFIER LETTER CAPITAL R
#define UC_MACRO_NAME_1D40 0x1D40 // ᵀ MODIFIER LETTER CAPITAL T
#define UC_MACRO_NAME_1D41 0x1D41 // ᵁ MODIFIER LETTER CAPITAL U
#define UC_MACRO_NAME_1D42 0x1D42 // ᵂ MODIFIER LETTER CAPITAL W
#define UC_MACRO_NAME_1D43 0x1D43 // ᵃ MODIFIER LETTER SMALL A
#define UC_MACRO_NAME_1D44 0x1D44 // ᵄ MODIFIER LETTER SMALL TURNED A
#define UC_MACRO_NAME_1D45 0x1D45 // ᵅ MODIFIER LETTER SMALL ALPHA
#define UC_MACRO_NAME_1D46 0x1D46 // ᵆ MODIFIER LETTER SMALL TURNED AE
#define UC_MACRO_NAME_1D47 0x1D47 // ᵇ MODIFIER LETTER SMALL B
#define UC_MACRO_NAME_1D48 0x1D48 // ᵈ MODIFIER LETTER SMALL D
#define UC_MACRO_NAME_1D49 0x1D49 // ᵉ MODIFIER LETTER SMALL E
#define UC_MACRO_NAME_1D4A 0x1D4A // ᵊ MODIFIER LETTER SMALL SCHWA
#define UC_MACRO_NAME_1D4B 0x1D4B // ᵋ MODIFIER LETTER SMALL OPEN E
#define UC_MACRO_NAME_1D4C 0x1D4C // ᵌ MODIFIER LETTER SMALL TURNED OPEN E
#define UC_MACRO_NAME_1D4D 0x1D4D // ᵍ MODIFIER LETTER SMALL G
#define UC_MACRO_NAME_1D4E 0x1D4E // ᵎ MODIFIER LETTER SMALL TURNED I
#define UC_MACRO_NAME_1D4F 0x1D4F // ᵏ MODIFIER LETTER SMALL K
#define UC_MACRO_NAME_1D50 0x1D50 // ᵐ MODIFIER LETTER SMALL M
#define UC_MACRO_NAME_1D51 0x1D51 // ᵑ MODIFIER LETTER SMALL ENG
#define UC_MACRO_NAME_1D52 0x1D52 // ᵒ MODIFIER LETTER SMALL O
#define UC_MACRO_NAME_1D53 0x1D53 // ᵓ MODIFIER LETTER SMALL OPEN O
#define UC_MACRO_NAME_1D54 0x1D54 // ᵔ MODIFIER LETTER SMALL TOP HALF O
#define UC_MACRO_NAME_1D55 0x1D55 // ᵕ MODIFIER LETTER SMALL BOTTOM HALF O
#define UC_MACRO_NAME_1D56 0x1D56 // ᵖ MODIFIER LETTER SMALL P
#define UC_MACRO_NAME_1D57 0x1D57 // ᵗ MODIFIER LETTER SMALL T
#define UC_MACRO_NAME_1D58 0x1D58 // ᵘ MODIFIER LETTER SMALL U
#define UC_MACRO_NAME_1D59 0x1D59 // ᵙ MODIFIER LETTER SMALL SIDEWAYS U
#define UC_MACRO_NAME_1D5A 0x1D5A // ᵚ MODIFIER LETTER SMALL TURNED M
#define UC_MACRO_NAME_1D5B 0x1D5B // ᵛ MODIFIER LETTER SMALL V
#define UC_MACRO_NAME_1D5C 0x1D5C // ᵜ MODIFIER LETTER SMALL AIN
#define UC_MACRO_NAME_1D5D 0x1D5D // ᵝ MODIFIER LETTER SMALL BETA
#define UC_MACRO_NAME_1D5E 0x1D5E // ᵞ MODIFIER LETTER SMALL GREEK GAMMA
#define UC_MACRO_NAME_1D5F 0x1D5F // ᵟ MODIFIER LETTER SMALL DELTA
#define UC_MACRO_NAME_1D60 0x1D60 // ᵠ MODIFIER LETTER SMALL GREEK PHI
#define UC_MACRO_NAME_1D61 0x1D61 // ᵡ MODIFIER LETTER SMALL CHI
#define UC_MACRO_NAME_1D62 0x1D62 // ᵢ LATIN SUBSCRIPT SMALL LETTER I
#define UC_MACRO_NAME_1D63 0x1D63 // ᵣ LATIN SUBSCRIPT SMALL LETTER R
#define UC_MACRO_NAME_1D64 0x1D64 // ᵤ LATIN SUBSCRIPT SMALL LETTER U
#define UC_MACRO_NAME_1D65 0x1D65 // ᵥ LATIN SUBSCRIPT SMALL LETTER V
#define UC_MACRO_NAME_1D66 0x1D66 // ᵦ GREEK SUBSCRIPT SMALL LETTER BETA
#define UC_MACRO_NAME_1D67 0x1D67 // ᵧ GREEK SUBSCRIPT SMALL LETTER GAMMA
#define UC_MACRO_NAME_1D68 0x1D68 // ᵨ GREEK SUBSCRIPT SMALL LETTER RHO
#define UC_MACRO_NAME_1D69 0x1D69 // ᵩ GREEK SUBSCRIPT SMALL LETTER PHI
#define UC_MACRO_NAME_1D6A 0x1D6A // ᵪ GREEK SUBSCRIPT SMALL LETTER CHI
#define UC_MACRO_NAME_1D6B 0x1D6B // ᵫ LATIN SMALL LETTER UE
#define UC_MACRO_NAME_1D6C 0x1D6C // ᵬ LATIN SMALL LETTER B WITH MIDDLE TILDE
#define UC_MACRO_NAME_1D6D 0x1D6D // ᵭ LATIN SMALL LETTER D WITH MIDDLE TILDE
#define UC_MACRO_NAME_1D6E 0x1D6E // ᵮ LATIN SMALL LETTER F WITH MIDDLE TILDE
#define UC_MACRO_NAME_1D6F 0x1D6F // ᵯ LATIN SMALL LETTER M WITH MIDDLE TILDE
#define UC_MACRO_NAME_1D70 0x1D70 // ᵰ LATIN SMALL LETTER N WITH MIDDLE TILDE
#define UC_MACRO_NAME_1D71 0x1D71 // ᵱ LATIN SMALL LETTER P WITH MIDDLE TILDE
#define UC_MACRO_NAME_1D72 0x1D72 // ᵲ LATIN SMALL LETTER R WITH MIDDLE TILDE
#define UC_MACRO_NAME_1D73 0x1D73 // ᵳ LATIN SMALL LETTER R WITH FISHHOOK AND MIDDLE TILDE
#define UC_MACRO_NAME_1D74 0x1D74 // ᵴ LATIN SMALL LETTER S WITH MIDDLE TILDE
#define UC_MACRO_NAME_1D75 0x1D75 // ᵵ LATIN SMALL LETTER T WITH MIDDLE TILDE
#define UC_MACRO_NAME_1D76 0x1D76 // ᵶ LATIN SMALL LETTER Z WITH MIDDLE TILDE
#define UC_MACRO_NAME_1D77 0x1D77 // ᵷ LATIN SMALL LETTER TURNED G
#define UC_MACRO_NAME_1D78 0x1D78 // ᵸ MODIFIER LETTER CYRILLIC EN
#define UC_MACRO_NAME_1D79 0x1D79 // ᵹ LATIN SMALL LETTER INSULAR G
#define UC_MACRO_NAME_1D7A 0x1D7A // ᵺ LATIN SMALL LETTER TH WITH STRIKETHROUGH
#define UC_MACRO_NAME_1D7B 0x1D7B // ᵻ LATIN SMALL CAPITAL LETTER I WITH STROKE
#define UC_MACRO_NAME_1D7C 0x1D7C // ᵼ LATIN SMALL LETTER IOTA WITH STROKE
#define UC_MACRO_NAME_1D7D 0x1D7D // ᵽ LATIN SMALL LETTER P WITH STROKE
#define UC_MACRO_NAME_1D7E 0x1D7E // ᵾ LATIN SMALL CAPITAL LETTER U WITH STROKE
#define UC_MACRO_NAME_1D7F 0x1D7F // ᵿ LATIN SMALL LETTER UPSILON WITH STROKE


#endif // UC_H_PHONETIC_EXTENSIONS
