/*
 * Unicode Block: Playing Cards
 * Range: U+1F0A0..U+1F0FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_PLAYING_CARDS
#define UC_H_PLAYING_CARDS

#define UC_MACRO_NAME_1F0A0 0x1F0A0 // 🂠 PLAYING CARD BACK
#define UC_MACRO_NAME_1F0A1 0x1F0A1 // 🂡 PLAYING CARD ACE OF SPADES
#define UC_MACRO_NAME_1F0A2 0x1F0A2 // 🂢 PLAYING CARD TWO OF SPADES
#define UC_MACRO_NAME_1F0A3 0x1F0A3 // 🂣 PLAYING CARD THREE OF SPADES
#define UC_MACRO_NAME_1F0A4 0x1F0A4 // 🂤 PLAYING CARD FOUR OF SPADES
#define UC_MACRO_NAME_1F0A5 0x1F0A5 // 🂥 PLAYING CARD FIVE OF SPADES
#define UC_MACRO_NAME_1F0A6 0x1F0A6 // 🂦 PLAYING CARD SIX OF SPADES
#define UC_MACRO_NAME_1F0A7 0x1F0A7 // 🂧 PLAYING CARD SEVEN OF SPADES
#define UC_MACRO_NAME_1F0A8 0x1F0A8 // 🂨 PLAYING CARD EIGHT OF SPADES
#define UC_MACRO_NAME_1F0A9 0x1F0A9 // 🂩 PLAYING CARD NINE OF SPADES
#define UC_MACRO_NAME_1F0AA 0x1F0AA // 🂪 PLAYING CARD TEN OF SPADES
#define UC_MACRO_NAME_1F0AB 0x1F0AB // 🂫 PLAYING CARD JACK OF SPADES
#define UC_MACRO_NAME_1F0AC 0x1F0AC // 🂬 PLAYING CARD KNIGHT OF SPADES
#define UC_MACRO_NAME_1F0AD 0x1F0AD // 🂭 PLAYING CARD QUEEN OF SPADES
#define UC_MACRO_NAME_1F0AE 0x1F0AE // 🂮 PLAYING CARD KING OF SPADES
#define UC_MACRO_NAME_1F0B1 0x1F0B1 // 🂱 PLAYING CARD ACE OF HEARTS
#define UC_MACRO_NAME_1F0B2 0x1F0B2 // 🂲 PLAYING CARD TWO OF HEARTS
#define UC_MACRO_NAME_1F0B3 0x1F0B3 // 🂳 PLAYING CARD THREE OF HEARTS
#define UC_MACRO_NAME_1F0B4 0x1F0B4 // 🂴 PLAYING CARD FOUR OF HEARTS
#define UC_MACRO_NAME_1F0B5 0x1F0B5 // 🂵 PLAYING CARD FIVE OF HEARTS
#define UC_MACRO_NAME_1F0B6 0x1F0B6 // 🂶 PLAYING CARD SIX OF HEARTS
#define UC_MACRO_NAME_1F0B7 0x1F0B7 // 🂷 PLAYING CARD SEVEN OF HEARTS
#define UC_MACRO_NAME_1F0B8 0x1F0B8 // 🂸 PLAYING CARD EIGHT OF HEARTS
#define UC_MACRO_NAME_1F0B9 0x1F0B9 // 🂹 PLAYING CARD NINE OF HEARTS
#define UC_MACRO_NAME_1F0BA 0x1F0BA // 🂺 PLAYING CARD TEN OF HEARTS
#define UC_MACRO_NAME_1F0BB 0x1F0BB // 🂻 PLAYING CARD JACK OF HEARTS
#define UC_MACRO_NAME_1F0BC 0x1F0BC // 🂼 PLAYING CARD KNIGHT OF HEARTS
#define UC_MACRO_NAME_1F0BD 0x1F0BD // 🂽 PLAYING CARD QUEEN OF HEARTS
#define UC_MACRO_NAME_1F0BE 0x1F0BE // 🂾 PLAYING CARD KING OF HEARTS
#define UC_MACRO_NAME_1F0BF 0x1F0BF // 🂿 PLAYING CARD RED JOKER
#define UC_MACRO_NAME_1F0C1 0x1F0C1 // 🃁 PLAYING CARD ACE OF DIAMONDS
#define UC_MACRO_NAME_1F0C2 0x1F0C2 // 🃂 PLAYING CARD TWO OF DIAMONDS
#define UC_MACRO_NAME_1F0C3 0x1F0C3 // 🃃 PLAYING CARD THREE OF DIAMONDS
#define UC_MACRO_NAME_1F0C4 0x1F0C4 // 🃄 PLAYING CARD FOUR OF DIAMONDS
#define UC_MACRO_NAME_1F0C5 0x1F0C5 // 🃅 PLAYING CARD FIVE OF DIAMONDS
#define UC_MACRO_NAME_1F0C6 0x1F0C6 // 🃆 PLAYING CARD SIX OF DIAMONDS
#define UC_MACRO_NAME_1F0C7 0x1F0C7 // 🃇 PLAYING CARD SEVEN OF DIAMONDS
#define UC_MACRO_NAME_1F0C8 0x1F0C8 // 🃈 PLAYING CARD EIGHT OF DIAMONDS
#define UC_MACRO_NAME_1F0C9 0x1F0C9 // 🃉 PLAYING CARD NINE OF DIAMONDS
#define UC_MACRO_NAME_1F0CA 0x1F0CA // 🃊 PLAYING CARD TEN OF DIAMONDS
#define UC_MACRO_NAME_1F0CB 0x1F0CB // 🃋 PLAYING CARD JACK OF DIAMONDS
#define UC_MACRO_NAME_1F0CC 0x1F0CC // 🃌 PLAYING CARD KNIGHT OF DIAMONDS
#define UC_MACRO_NAME_1F0CD 0x1F0CD // 🃍 PLAYING CARD QUEEN OF DIAMONDS
#define UC_MACRO_NAME_1F0CE 0x1F0CE // 🃎 PLAYING CARD KING OF DIAMONDS
#define UC_MACRO_NAME_1F0CF 0x1F0CF // 🃏 PLAYING CARD BLACK JOKER
#define UC_MACRO_NAME_1F0D1 0x1F0D1 // 🃑 PLAYING CARD ACE OF CLUBS
#define UC_MACRO_NAME_1F0D2 0x1F0D2 // 🃒 PLAYING CARD TWO OF CLUBS
#define UC_MACRO_NAME_1F0D3 0x1F0D3 // 🃓 PLAYING CARD THREE OF CLUBS
#define UC_MACRO_NAME_1F0D4 0x1F0D4 // 🃔 PLAYING CARD FOUR OF CLUBS
#define UC_MACRO_NAME_1F0D5 0x1F0D5 // 🃕 PLAYING CARD FIVE OF CLUBS
#define UC_MACRO_NAME_1F0D6 0x1F0D6 // 🃖 PLAYING CARD SIX OF CLUBS
#define UC_MACRO_NAME_1F0D7 0x1F0D7 // 🃗 PLAYING CARD SEVEN OF CLUBS
#define UC_MACRO_NAME_1F0D8 0x1F0D8 // 🃘 PLAYING CARD EIGHT OF CLUBS
#define UC_MACRO_NAME_1F0D9 0x1F0D9 // 🃙 PLAYING CARD NINE OF CLUBS
#define UC_MACRO_NAME_1F0DA 0x1F0DA // 🃚 PLAYING CARD TEN OF CLUBS
#define UC_MACRO_NAME_1F0DB 0x1F0DB // 🃛 PLAYING CARD JACK OF CLUBS
#define UC_MACRO_NAME_1F0DC 0x1F0DC // 🃜 PLAYING CARD KNIGHT OF CLUBS
#define UC_MACRO_NAME_1F0DD 0x1F0DD // 🃝 PLAYING CARD QUEEN OF CLUBS
#define UC_MACRO_NAME_1F0DE 0x1F0DE // 🃞 PLAYING CARD KING OF CLUBS
#define UC_MACRO_NAME_1F0DF 0x1F0DF // 🃟 PLAYING CARD WHITE JOKER
#define UC_MACRO_NAME_1F0E0 0x1F0E0 // 🃠 PLAYING CARD FOOL
#define UC_MACRO_NAME_1F0E1 0x1F0E1 // 🃡 PLAYING CARD TRUMP-1
#define UC_MACRO_NAME_1F0E2 0x1F0E2 // 🃢 PLAYING CARD TRUMP-2
#define UC_MACRO_NAME_1F0E3 0x1F0E3 // 🃣 PLAYING CARD TRUMP-3
#define UC_MACRO_NAME_1F0E4 0x1F0E4 // 🃤 PLAYING CARD TRUMP-4
#define UC_MACRO_NAME_1F0E5 0x1F0E5 // 🃥 PLAYING CARD TRUMP-5
#define UC_MACRO_NAME_1F0E6 0x1F0E6 // 🃦 PLAYING CARD TRUMP-6
#define UC_MACRO_NAME_1F0E7 0x1F0E7 // 🃧 PLAYING CARD TRUMP-7
#define UC_MACRO_NAME_1F0E8 0x1F0E8 // 🃨 PLAYING CARD TRUMP-8
#define UC_MACRO_NAME_1F0E9 0x1F0E9 // 🃩 PLAYING CARD TRUMP-9
#define UC_MACRO_NAME_1F0EA 0x1F0EA // 🃪 PLAYING CARD TRUMP-10
#define UC_MACRO_NAME_1F0EB 0x1F0EB // 🃫 PLAYING CARD TRUMP-11
#define UC_MACRO_NAME_1F0EC 0x1F0EC // 🃬 PLAYING CARD TRUMP-12
#define UC_MACRO_NAME_1F0ED 0x1F0ED // 🃭 PLAYING CARD TRUMP-13
#define UC_MACRO_NAME_1F0EE 0x1F0EE // 🃮 PLAYING CARD TRUMP-14
#define UC_MACRO_NAME_1F0EF 0x1F0EF // 🃯 PLAYING CARD TRUMP-15
#define UC_MACRO_NAME_1F0F0 0x1F0F0 // 🃰 PLAYING CARD TRUMP-16
#define UC_MACRO_NAME_1F0F1 0x1F0F1 // 🃱 PLAYING CARD TRUMP-17
#define UC_MACRO_NAME_1F0F2 0x1F0F2 // 🃲 PLAYING CARD TRUMP-18
#define UC_MACRO_NAME_1F0F3 0x1F0F3 // 🃳 PLAYING CARD TRUMP-19
#define UC_MACRO_NAME_1F0F4 0x1F0F4 // 🃴 PLAYING CARD TRUMP-20
#define UC_MACRO_NAME_1F0F5 0x1F0F5 // 🃵 PLAYING CARD TRUMP-21


#endif // UC_H_PLAYING_CARDS
