/*
 * Unicode Block: Phonetic Extensions Supplement
 * Range: U+1D80..U+1DBF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Phonetic Extensions Supplement is a Unicode block containing
 * characters for specialized and deprecated forms of the International
 * Phonetic Alphabet .
 *
 */
#ifndef UC_H_PHONETIC_EXTENSIONS_SUPPLEMENT
#define UC_H_PHONETIC_EXTENSIONS_SUPPLEMENT

#define UC_MACRO_NAME_1D80 0x1D80 // ᶀ LATIN SMALL LETTER B WITH PALATAL HOOK
#define UC_MACRO_NAME_1D81 0x1D81 // ᶁ LATIN SMALL LETTER D WITH PALATAL HOOK
#define UC_MACRO_NAME_1D82 0x1D82 // ᶂ LATIN SMALL LETTER F WITH PALATAL HOOK
#define UC_MACRO_NAME_1D83 0x1D83 // ᶃ LATIN SMALL LETTER G WITH PALATAL HOOK
#define UC_MACRO_NAME_1D84 0x1D84 // ᶄ LATIN SMALL LETTER K WITH PALATAL HOOK
#define UC_MACRO_NAME_1D85 0x1D85 // ᶅ LATIN SMALL LETTER L WITH PALATAL HOOK
#define UC_MACRO_NAME_1D86 0x1D86 // ᶆ LATIN SMALL LETTER M WITH PALATAL HOOK
#define UC_MACRO_NAME_1D87 0x1D87 // ᶇ LATIN SMALL LETTER N WITH PALATAL HOOK
#define UC_MACRO_NAME_1D88 0x1D88 // ᶈ LATIN SMALL LETTER P WITH PALATAL HOOK
#define UC_MACRO_NAME_1D89 0x1D89 // ᶉ LATIN SMALL LETTER R WITH PALATAL HOOK
#define UC_MACRO_NAME_1D8A 0x1D8A // ᶊ LATIN SMALL LETTER S WITH PALATAL HOOK
#define UC_MACRO_NAME_1D8B 0x1D8B // ᶋ LATIN SMALL LETTER ESH WITH PALATAL HOOK
#define UC_MACRO_NAME_1D8C 0x1D8C // ᶌ LATIN SMALL LETTER V WITH PALATAL HOOK
#define UC_MACRO_NAME_1D8D 0x1D8D // ᶍ LATIN SMALL LETTER X WITH PALATAL HOOK
#define UC_MACRO_NAME_1D8E 0x1D8E // ᶎ LATIN SMALL LETTER Z WITH PALATAL HOOK
#define UC_MACRO_NAME_1D8F 0x1D8F // ᶏ LATIN SMALL LETTER A WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1D90 0x1D90 // ᶐ LATIN SMALL LETTER ALPHA WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1D91 0x1D91 // ᶑ LATIN SMALL LETTER D WITH HOOK AND TAIL
#define UC_MACRO_NAME_1D92 0x1D92 // ᶒ LATIN SMALL LETTER E WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1D93 0x1D93 // ᶓ LATIN SMALL LETTER OPEN E WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1D94 0x1D94 // ᶔ LATIN SMALL LETTER REVERSED OPEN E WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1D95 0x1D95 // ᶕ LATIN SMALL LETTER SCHWA WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1D96 0x1D96 // ᶖ LATIN SMALL LETTER I WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1D97 0x1D97 // ᶗ LATIN SMALL LETTER OPEN O WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1D98 0x1D98 // ᶘ LATIN SMALL LETTER ESH WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1D99 0x1D99 // ᶙ LATIN SMALL LETTER U WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1D9A 0x1D9A // ᶚ LATIN SMALL LETTER EZH WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1D9B 0x1D9B // ᶛ MODIFIER LETTER SMALL TURNED ALPHA
#define UC_MACRO_NAME_1D9C 0x1D9C // ᶜ MODIFIER LETTER SMALL C
#define UC_MACRO_NAME_1D9D 0x1D9D // ᶝ MODIFIER LETTER SMALL C WITH CURL
#define UC_MACRO_NAME_1D9E 0x1D9E // ᶞ MODIFIER LETTER SMALL ETH
#define UC_MACRO_NAME_1D9F 0x1D9F // ᶟ MODIFIER LETTER SMALL REVERSED OPEN E
#define UC_MACRO_NAME_1DA0 0x1DA0 // ᶠ MODIFIER LETTER SMALL F
#define UC_MACRO_NAME_1DA1 0x1DA1 // ᶡ MODIFIER LETTER SMALL DOTLESS J WITH STROKE
#define UC_MACRO_NAME_1DA2 0x1DA2 // ᶢ MODIFIER LETTER SMALL SCRIPT G
#define UC_MACRO_NAME_1DA3 0x1DA3 // ᶣ MODIFIER LETTER SMALL TURNED H
#define UC_MACRO_NAME_1DA4 0x1DA4 // ᶤ MODIFIER LETTER SMALL I WITH STROKE
#define UC_MACRO_NAME_1DA5 0x1DA5 // ᶥ MODIFIER LETTER SMALL IOTA
#define UC_MACRO_NAME_1DA6 0x1DA6 // ᶦ MODIFIER LETTER SMALL CAPITAL I
#define UC_MACRO_NAME_1DA7 0x1DA7 // ᶧ MODIFIER LETTER SMALL CAPITAL I WITH STROKE
#define UC_MACRO_NAME_1DA8 0x1DA8 // ᶨ MODIFIER LETTER SMALL J WITH CROSSED-TAIL
#define UC_MACRO_NAME_1DA9 0x1DA9 // ᶩ MODIFIER LETTER SMALL L WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1DAA 0x1DAA // ᶪ MODIFIER LETTER SMALL L WITH PALATAL HOOK
#define UC_MACRO_NAME_1DAB 0x1DAB // ᶫ MODIFIER LETTER SMALL CAPITAL L
#define UC_MACRO_NAME_1DAC 0x1DAC // ᶬ MODIFIER LETTER SMALL M WITH HOOK
#define UC_MACRO_NAME_1DAD 0x1DAD // ᶭ MODIFIER LETTER SMALL TURNED M WITH LONG LEG
#define UC_MACRO_NAME_1DAE 0x1DAE // ᶮ MODIFIER LETTER SMALL N WITH LEFT HOOK
#define UC_MACRO_NAME_1DAF 0x1DAF // ᶯ MODIFIER LETTER SMALL N WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1DB0 0x1DB0 // ᶰ MODIFIER LETTER SMALL CAPITAL N
#define UC_MACRO_NAME_1DB1 0x1DB1 // ᶱ MODIFIER LETTER SMALL BARRED O
#define UC_MACRO_NAME_1DB2 0x1DB2 // ᶲ MODIFIER LETTER SMALL PHI
#define UC_MACRO_NAME_1DB3 0x1DB3 // ᶳ MODIFIER LETTER SMALL S WITH HOOK
#define UC_MACRO_NAME_1DB4 0x1DB4 // ᶴ MODIFIER LETTER SMALL ESH
#define UC_MACRO_NAME_1DB5 0x1DB5 // ᶵ MODIFIER LETTER SMALL T WITH PALATAL HOOK
#define UC_MACRO_NAME_1DB6 0x1DB6 // ᶶ MODIFIER LETTER SMALL U BAR
#define UC_MACRO_NAME_1DB7 0x1DB7 // ᶷ MODIFIER LETTER SMALL UPSILON
#define UC_MACRO_NAME_1DB8 0x1DB8 // ᶸ MODIFIER LETTER SMALL CAPITAL U
#define UC_MACRO_NAME_1DB9 0x1DB9 // ᶹ MODIFIER LETTER SMALL V WITH HOOK
#define UC_MACRO_NAME_1DBA 0x1DBA // ᶺ MODIFIER LETTER SMALL TURNED V
#define UC_MACRO_NAME_1DBB 0x1DBB // ᶻ MODIFIER LETTER SMALL Z
#define UC_MACRO_NAME_1DBC 0x1DBC // ᶼ MODIFIER LETTER SMALL Z WITH RETROFLEX HOOK
#define UC_MACRO_NAME_1DBD 0x1DBD // ᶽ MODIFIER LETTER SMALL Z WITH CURL
#define UC_MACRO_NAME_1DBE 0x1DBE // ᶾ MODIFIER LETTER SMALL EZH
#define UC_MACRO_NAME_1DBF 0x1DBF // ᶿ MODIFIER LETTER SMALL THETA


#endif // UC_H_PHONETIC_EXTENSIONS_SUPPLEMENT
