/*
 * Unicode Block: Pau Cin Hau
 * Range: U+11AC0..U+11AFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Pau Cin Hau was the founder and the name of a religion followed by
 * some Tedim , Hakha in Chin state and Kale in Sagaing division in the
 * north-western part of Myanmar .
 * Pau Cin Hau was born in the Tedim (Tiddim) in 1859; and lived until
 * 1948.
 *
 */
#ifndef UC_H_PAU_CIN_HAU
#define UC_H_PAU_CIN_HAU

#define UC_MACRO_NAME_11AC0 0x11AC0 // 𑫀 PAU CIN HAU LETTER PA
#define UC_MACRO_NAME_11AC1 0x11AC1 // 𑫁 PAU CIN HAU LETTER KA
#define UC_MACRO_NAME_11AC2 0x11AC2 // 𑫂 PAU CIN HAU LETTER LA
#define UC_MACRO_NAME_11AC3 0x11AC3 // 𑫃 PAU CIN HAU LETTER MA
#define UC_MACRO_NAME_11AC4 0x11AC4 // 𑫄 PAU CIN HAU LETTER DA
#define UC_MACRO_NAME_11AC5 0x11AC5 // 𑫅 PAU CIN HAU LETTER ZA
#define UC_MACRO_NAME_11AC6 0x11AC6 // 𑫆 PAU CIN HAU LETTER VA
#define UC_MACRO_NAME_11AC7 0x11AC7 // 𑫇 PAU CIN HAU LETTER NGA
#define UC_MACRO_NAME_11AC8 0x11AC8 // 𑫈 PAU CIN HAU LETTER HA
#define UC_MACRO_NAME_11AC9 0x11AC9 // 𑫉 PAU CIN HAU LETTER GA
#define UC_MACRO_NAME_11ACA 0x11ACA // 𑫊 PAU CIN HAU LETTER KHA
#define UC_MACRO_NAME_11ACB 0x11ACB // 𑫋 PAU CIN HAU LETTER SA
#define UC_MACRO_NAME_11ACC 0x11ACC // 𑫌 PAU CIN HAU LETTER BA
#define UC_MACRO_NAME_11ACD 0x11ACD // 𑫍 PAU CIN HAU LETTER CA
#define UC_MACRO_NAME_11ACE 0x11ACE // 𑫎 PAU CIN HAU LETTER TA
#define UC_MACRO_NAME_11ACF 0x11ACF // 𑫏 PAU CIN HAU LETTER THA
#define UC_MACRO_NAME_11AD0 0x11AD0 // 𑫐 PAU CIN HAU LETTER NA
#define UC_MACRO_NAME_11AD1 0x11AD1 // 𑫑 PAU CIN HAU LETTER PHA
#define UC_MACRO_NAME_11AD2 0x11AD2 // 𑫒 PAU CIN HAU LETTER RA
#define UC_MACRO_NAME_11AD3 0x11AD3 // 𑫓 PAU CIN HAU LETTER FA
#define UC_MACRO_NAME_11AD4 0x11AD4 // 𑫔 PAU CIN HAU LETTER CHA
#define UC_MACRO_NAME_11AD5 0x11AD5 // 𑫕 PAU CIN HAU LETTER A
#define UC_MACRO_NAME_11AD6 0x11AD6 // 𑫖 PAU CIN HAU LETTER E
#define UC_MACRO_NAME_11AD7 0x11AD7 // 𑫗 PAU CIN HAU LETTER I
#define UC_MACRO_NAME_11AD8 0x11AD8 // 𑫘 PAU CIN HAU LETTER O
#define UC_MACRO_NAME_11AD9 0x11AD9 // 𑫙 PAU CIN HAU LETTER U
#define UC_MACRO_NAME_11ADA 0x11ADA // 𑫚 PAU CIN HAU LETTER UA
#define UC_MACRO_NAME_11ADB 0x11ADB // 𑫛 PAU CIN HAU LETTER IA
#define UC_MACRO_NAME_11ADC 0x11ADC // 𑫜 PAU CIN HAU LETTER FINAL P
#define UC_MACRO_NAME_11ADD 0x11ADD // 𑫝 PAU CIN HAU LETTER FINAL K
#define UC_MACRO_NAME_11ADE 0x11ADE // 𑫞 PAU CIN HAU LETTER FINAL T
#define UC_MACRO_NAME_11ADF 0x11ADF // 𑫟 PAU CIN HAU LETTER FINAL M
#define UC_MACRO_NAME_11AE0 0x11AE0 // 𑫠 PAU CIN HAU LETTER FINAL N
#define UC_MACRO_NAME_11AE1 0x11AE1 // 𑫡 PAU CIN HAU LETTER FINAL L
#define UC_MACRO_NAME_11AE2 0x11AE2 // 𑫢 PAU CIN HAU LETTER FINAL W
#define UC_MACRO_NAME_11AE3 0x11AE3 // 𑫣 PAU CIN HAU LETTER FINAL NG
#define UC_MACRO_NAME_11AE4 0x11AE4 // 𑫤 PAU CIN HAU LETTER FINAL Y
#define UC_MACRO_NAME_11AE5 0x11AE5 // 𑫥 PAU CIN HAU RISING TONE LONG
#define UC_MACRO_NAME_11AE6 0x11AE6 // 𑫦 PAU CIN HAU RISING TONE
#define UC_MACRO_NAME_11AE7 0x11AE7 // 𑫧 PAU CIN HAU SANDHI GLOTTAL STOP
#define UC_MACRO_NAME_11AE8 0x11AE8 // 𑫨 PAU CIN HAU RISING TONE LONG FINAL
#define UC_MACRO_NAME_11AE9 0x11AE9 // 𑫩 PAU CIN HAU RISING TONE FINAL
#define UC_MACRO_NAME_11AEA 0x11AEA // 𑫪 PAU CIN HAU SANDHI GLOTTAL STOP FINAL
#define UC_MACRO_NAME_11AEB 0x11AEB // 𑫫 PAU CIN HAU SANDHI TONE LONG
#define UC_MACRO_NAME_11AEC 0x11AEC // 𑫬 PAU CIN HAU SANDHI TONE
#define UC_MACRO_NAME_11AED 0x11AED // 𑫭 PAU CIN HAU SANDHI TONE LONG FINAL
#define UC_MACRO_NAME_11AEE 0x11AEE // 𑫮 PAU CIN HAU SANDHI TONE FINAL
#define UC_MACRO_NAME_11AEF 0x11AEF // 𑫯 PAU CIN HAU MID-LEVEL TONE
#define UC_MACRO_NAME_11AF0 0x11AF0 // 𑫰 PAU CIN HAU GLOTTAL STOP VARIANT
#define UC_MACRO_NAME_11AF1 0x11AF1 // 𑫱 PAU CIN HAU MID-LEVEL TONE LONG FINAL
#define UC_MACRO_NAME_11AF2 0x11AF2 // 𑫲 PAU CIN HAU MID-LEVEL TONE FINAL
#define UC_MACRO_NAME_11AF3 0x11AF3 // 𑫳 PAU CIN HAU LOW-FALLING TONE LONG
#define UC_MACRO_NAME_11AF4 0x11AF4 // 𑫴 PAU CIN HAU LOW-FALLING TONE
#define UC_MACRO_NAME_11AF5 0x11AF5 // 𑫵 PAU CIN HAU GLOTTAL STOP
#define UC_MACRO_NAME_11AF6 0x11AF6 // 𑫶 PAU CIN HAU LOW-FALLING TONE LONG FINAL
#define UC_MACRO_NAME_11AF7 0x11AF7 // 𑫷 PAU CIN HAU LOW-FALLING TONE FINAL
#define UC_MACRO_NAME_11AF8 0x11AF8 // 𑫸 PAU CIN HAU GLOTTAL STOP FINAL


#endif // UC_H_PAU_CIN_HAU
