/*
 * Unicode Block: Runic
 * Range: U+16A0..U+16FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_RUNIC
#define UC_H_RUNIC

#define UC_MACRO_NAME_16A0 0x16A0 // ᚠ RUNIC LETTER FEHU FEOH FE F
#define UC_MACRO_NAME_16A1 0x16A1 // ᚡ RUNIC LETTER V
#define UC_MACRO_NAME_16A2 0x16A2 // ᚢ RUNIC LETTER URUZ UR U
#define UC_MACRO_NAME_16A3 0x16A3 // ᚣ RUNIC LETTER YR
#define UC_MACRO_NAME_16A4 0x16A4 // ᚤ RUNIC LETTER Y
#define UC_MACRO_NAME_16A5 0x16A5 // ᚥ RUNIC LETTER W
#define UC_MACRO_NAME_16A6 0x16A6 // ᚦ RUNIC LETTER THURISAZ THURS THORN
#define UC_MACRO_NAME_16A7 0x16A7 // ᚧ RUNIC LETTER ETH
#define UC_MACRO_NAME_16A8 0x16A8 // ᚨ RUNIC LETTER ANSUZ A
#define UC_MACRO_NAME_16A9 0x16A9 // ᚩ RUNIC LETTER OS O
#define UC_MACRO_NAME_16AA 0x16AA // ᚪ RUNIC LETTER AC A
#define UC_MACRO_NAME_16AB 0x16AB // ᚫ RUNIC LETTER AESC
#define UC_MACRO_NAME_16AC 0x16AC // ᚬ RUNIC LETTER LONG-BRANCH-OSS O
#define UC_MACRO_NAME_16AD 0x16AD // ᚭ RUNIC LETTER SHORT-TWIG-OSS O
#define UC_MACRO_NAME_16AE 0x16AE // ᚮ RUNIC LETTER O
#define UC_MACRO_NAME_16AF 0x16AF // ᚯ RUNIC LETTER OE
#define UC_MACRO_NAME_16B0 0x16B0 // ᚰ RUNIC LETTER ON
#define UC_MACRO_NAME_16B1 0x16B1 // ᚱ RUNIC LETTER RAIDO RAD REID R
#define UC_MACRO_NAME_16B2 0x16B2 // ᚲ RUNIC LETTER KAUNA
#define UC_MACRO_NAME_16B3 0x16B3 // ᚳ RUNIC LETTER CEN
#define UC_MACRO_NAME_16B4 0x16B4 // ᚴ RUNIC LETTER KAUN K
#define UC_MACRO_NAME_16B5 0x16B5 // ᚵ RUNIC LETTER G
#define UC_MACRO_NAME_16B6 0x16B6 // ᚶ RUNIC LETTER ENG
#define UC_MACRO_NAME_16B7 0x16B7 // ᚷ RUNIC LETTER GEBO GYFU G
#define UC_MACRO_NAME_16B8 0x16B8 // ᚸ RUNIC LETTER GAR
#define UC_MACRO_NAME_16B9 0x16B9 // ᚹ RUNIC LETTER WUNJO WYNN W
#define UC_MACRO_NAME_16BA 0x16BA // ᚺ RUNIC LETTER HAGLAZ H
#define UC_MACRO_NAME_16BB 0x16BB // ᚻ RUNIC LETTER HAEGL H
#define UC_MACRO_NAME_16BC 0x16BC // ᚼ RUNIC LETTER LONG-BRANCH-HAGALL H
#define UC_MACRO_NAME_16BD 0x16BD // ᚽ RUNIC LETTER SHORT-TWIG-HAGALL H
#define UC_MACRO_NAME_16BE 0x16BE // ᚾ RUNIC LETTER NAUDIZ NYD NAUD N
#define UC_MACRO_NAME_16BF 0x16BF // ᚿ RUNIC LETTER SHORT-TWIG-NAUD N
#define UC_MACRO_NAME_16C0 0x16C0 // ᛀ RUNIC LETTER DOTTED-N
#define UC_MACRO_NAME_16C1 0x16C1 // ᛁ RUNIC LETTER ISAZ IS ISS I
#define UC_MACRO_NAME_16C2 0x16C2 // ᛂ RUNIC LETTER E
#define UC_MACRO_NAME_16C3 0x16C3 // ᛃ RUNIC LETTER JERAN J
#define UC_MACRO_NAME_16C4 0x16C4 // ᛄ RUNIC LETTER GER
#define UC_MACRO_NAME_16C5 0x16C5 // ᛅ RUNIC LETTER LONG-BRANCH-AR AE
#define UC_MACRO_NAME_16C6 0x16C6 // ᛆ RUNIC LETTER SHORT-TWIG-AR A
#define UC_MACRO_NAME_16C7 0x16C7 // ᛇ RUNIC LETTER IWAZ EOH
#define UC_MACRO_NAME_16C8 0x16C8 // ᛈ RUNIC LETTER PERTHO PEORTH P
#define UC_MACRO_NAME_16C9 0x16C9 // ᛉ RUNIC LETTER ALGIZ EOLHX
#define UC_MACRO_NAME_16CA 0x16CA // ᛊ RUNIC LETTER SOWILO S
#define UC_MACRO_NAME_16CB 0x16CB // ᛋ RUNIC LETTER SIGEL LONG-BRANCH-SOL S
#define UC_MACRO_NAME_16CC 0x16CC // ᛌ RUNIC LETTER SHORT-TWIG-SOL S
#define UC_MACRO_NAME_16CD 0x16CD // ᛍ RUNIC LETTER C
#define UC_MACRO_NAME_16CE 0x16CE // ᛎ RUNIC LETTER Z
#define UC_MACRO_NAME_16CF 0x16CF // ᛏ RUNIC LETTER TIWAZ TIR TYR T
#define UC_MACRO_NAME_16D0 0x16D0 // ᛐ RUNIC LETTER SHORT-TWIG-TYR T
#define UC_MACRO_NAME_16D1 0x16D1 // ᛑ RUNIC LETTER D
#define UC_MACRO_NAME_16D2 0x16D2 // ᛒ RUNIC LETTER BERKANAN BEORC BJARKAN B
#define UC_MACRO_NAME_16D3 0x16D3 // ᛓ RUNIC LETTER SHORT-TWIG-BJARKAN B
#define UC_MACRO_NAME_16D4 0x16D4 // ᛔ RUNIC LETTER DOTTED-P
#define UC_MACRO_NAME_16D5 0x16D5 // ᛕ RUNIC LETTER OPEN-P
#define UC_MACRO_NAME_16D6 0x16D6 // ᛖ RUNIC LETTER EHWAZ EH E
#define UC_MACRO_NAME_16D7 0x16D7 // ᛗ RUNIC LETTER MANNAZ MAN M
#define UC_MACRO_NAME_16D8 0x16D8 // ᛘ RUNIC LETTER LONG-BRANCH-MADR M
#define UC_MACRO_NAME_16D9 0x16D9 // ᛙ RUNIC LETTER SHORT-TWIG-MADR M
#define UC_MACRO_NAME_16DA 0x16DA // ᛚ RUNIC LETTER LAUKAZ LAGU LOGR L
#define UC_MACRO_NAME_16DB 0x16DB // ᛛ RUNIC LETTER DOTTED-L
#define UC_MACRO_NAME_16DC 0x16DC // ᛜ RUNIC LETTER INGWAZ
#define UC_MACRO_NAME_16DD 0x16DD // ᛝ RUNIC LETTER ING
#define UC_MACRO_NAME_16DE 0x16DE // ᛞ RUNIC LETTER DAGAZ DAEG D
#define UC_MACRO_NAME_16DF 0x16DF // ᛟ RUNIC LETTER OTHALAN ETHEL O
#define UC_MACRO_NAME_16E0 0x16E0 // ᛠ RUNIC LETTER EAR
#define UC_MACRO_NAME_16E1 0x16E1 // ᛡ RUNIC LETTER IOR
#define UC_MACRO_NAME_16E2 0x16E2 // ᛢ RUNIC LETTER CWEORTH
#define UC_MACRO_NAME_16E3 0x16E3 // ᛣ RUNIC LETTER CALC
#define UC_MACRO_NAME_16E4 0x16E4 // ᛤ RUNIC LETTER CEALC
#define UC_MACRO_NAME_16E5 0x16E5 // ᛥ RUNIC LETTER STAN
#define UC_MACRO_NAME_16E6 0x16E6 // ᛦ RUNIC LETTER LONG-BRANCH-YR
#define UC_MACRO_NAME_16E7 0x16E7 // ᛧ RUNIC LETTER SHORT-TWIG-YR
#define UC_MACRO_NAME_16E8 0x16E8 // ᛨ RUNIC LETTER ICELANDIC-YR
#define UC_MACRO_NAME_16E9 0x16E9 // ᛩ RUNIC LETTER Q
#define UC_MACRO_NAME_16EA 0x16EA // ᛪ RUNIC LETTER X
#define UC_MACRO_NAME_16EB 0x16EB // ᛫ RUNIC SINGLE PUNCTUATION
#define UC_MACRO_NAME_16EC 0x16EC // ᛬ RUNIC MULTIPLE PUNCTUATION
#define UC_MACRO_NAME_16ED 0x16ED // ᛭ RUNIC CROSS PUNCTUATION
#define UC_MACRO_NAME_16EE 0x16EE // ᛮ RUNIC ARLAUG SYMBOL
#define UC_MACRO_NAME_16EF 0x16EF // ᛯ RUNIC TVIMADUR SYMBOL
#define UC_MACRO_NAME_16F0 0x16F0 // ᛰ RUNIC BELGTHOR SYMBOL
#define UC_MACRO_NAME_16F1 0x16F1 // ᛱ RUNIC LETTER K
#define UC_MACRO_NAME_16F2 0x16F2 // ᛲ RUNIC LETTER SH
#define UC_MACRO_NAME_16F3 0x16F3 // ᛳ RUNIC LETTER OO
#define UC_MACRO_NAME_16F4 0x16F4 // ᛴ RUNIC LETTER FRANKS CASKET OS
#define UC_MACRO_NAME_16F5 0x16F5 // ᛵ RUNIC LETTER FRANKS CASKET IS
#define UC_MACRO_NAME_16F6 0x16F6 // ᛶ RUNIC LETTER FRANKS CASKET EH
#define UC_MACRO_NAME_16F7 0x16F7 // ᛷ RUNIC LETTER FRANKS CASKET AC
#define UC_MACRO_NAME_16F8 0x16F8 // ᛸ RUNIC LETTER FRANKS CASKET AESC


#endif // UC_H_RUNIC
