/*
 * Unicode Block: Samaritan
 * Range: U+0800..U+083F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Samaritans ( / s ə ˈ m ær ɪ t ən z / ; Samaritan Hebrew : ࠔࠠࠌࠝࠓࠩࠉࠌ ,
 * romanized: Šā̊merīm ; Hebrew : שומרונים , romanized : Šomronim ;
 * Arabic : السامريون , romanized : as-Sāmiriyyūn ), often preferring to
 * be called Israelite Samaritans , are an ethnoreligious group
 * originating from the Hebrews and Israelites of the ancient Near East .
 * They are indigenous to Samaria , a historical region of ancient Israel
 * and Judah that comprises the northern half of the West Bank in
 * Palestine . They are adherents of Samaritanism , an Abrahamic ,
 * monotheistic , and ethnic religion that developed alongside Judaism .
 * According to their tradition, the Samaritans' ancestors, the
 * Israelites, settled in Canaan in the 17th century BCE. The Samaritans
 * claim descent from the Israelites who, unlike the Ten Lost Tribes of
 * the Twelve Tribes of Israel , were not subject to the Assyrian
 * captivity after the northern Kingdom of Israel was destroyed and
 * annexed by the Neo-Assyrian Empire around 720 BCE.
 *
 */
#ifndef UC_H_SAMARITAN
#define UC_H_SAMARITAN

#define UC_MACRO_NAME_800 0x0800 // ࠀ SAMARITAN LETTER ALAF
#define UC_MACRO_NAME_801 0x0801 // ࠁ SAMARITAN LETTER BIT
#define UC_MACRO_NAME_802 0x0802 // ࠂ SAMARITAN LETTER GAMAN
#define UC_MACRO_NAME_803 0x0803 // ࠃ SAMARITAN LETTER DALAT
#define UC_MACRO_NAME_804 0x0804 // ࠄ SAMARITAN LETTER IY
#define UC_MACRO_NAME_805 0x0805 // ࠅ SAMARITAN LETTER BAA
#define UC_MACRO_NAME_806 0x0806 // ࠆ SAMARITAN LETTER ZEN
#define UC_MACRO_NAME_807 0x0807 // ࠇ SAMARITAN LETTER IT
#define UC_MACRO_NAME_808 0x0808 // ࠈ SAMARITAN LETTER TIT
#define UC_MACRO_NAME_809 0x0809 // ࠉ SAMARITAN LETTER YUT
#define UC_MACRO_NAME_80A 0x080A // ࠊ SAMARITAN LETTER KAAF
#define UC_MACRO_NAME_80B 0x080B // ࠋ SAMARITAN LETTER LABAT
#define UC_MACRO_NAME_80C 0x080C // ࠌ SAMARITAN LETTER MIM
#define UC_MACRO_NAME_80D 0x080D // ࠍ SAMARITAN LETTER NUN
#define UC_MACRO_NAME_80E 0x080E // ࠎ SAMARITAN LETTER SINGAAT
#define UC_MACRO_NAME_80F 0x080F // ࠏ SAMARITAN LETTER IN
#define UC_MACRO_NAME_810 0x0810 // ࠐ SAMARITAN LETTER FI
#define UC_MACRO_NAME_811 0x0811 // ࠑ SAMARITAN LETTER TSAADIY
#define UC_MACRO_NAME_812 0x0812 // ࠒ SAMARITAN LETTER QUF
#define UC_MACRO_NAME_813 0x0813 // ࠓ SAMARITAN LETTER RISH
#define UC_MACRO_NAME_814 0x0814 // ࠔ SAMARITAN LETTER SHAN
#define UC_MACRO_NAME_815 0x0815 // ࠕ SAMARITAN LETTER TAAF
#define UC_MACRO_NAME_816 0x0816 // ࠖ SAMARITAN MARK IN
#define UC_MACRO_NAME_817 0x0817 // ࠗ SAMARITAN MARK IN-ALAF
#define UC_MACRO_NAME_818 0x0818 // ࠘ SAMARITAN MARK OCCLUSION
#define UC_MACRO_NAME_819 0x0819 // ࠙ SAMARITAN MARK DAGESH
#define UC_MACRO_NAME_81A 0x081A // ࠚ SAMARITAN MODIFIER LETTER EPENTHETIC YUT
#define UC_MACRO_NAME_81B 0x081B // ࠛ SAMARITAN MARK EPENTHETIC YUT
#define UC_MACRO_NAME_81C 0x081C // ࠜ SAMARITAN VOWEL SIGN LONG E
#define UC_MACRO_NAME_81D 0x081D // ࠝ SAMARITAN VOWEL SIGN E
#define UC_MACRO_NAME_81E 0x081E // ࠞ SAMARITAN VOWEL SIGN OVERLONG AA
#define UC_MACRO_NAME_81F 0x081F // ࠟ SAMARITAN VOWEL SIGN LONG AA
#define UC_MACRO_NAME_820 0x0820 // ࠠ SAMARITAN VOWEL SIGN AA
#define UC_MACRO_NAME_821 0x0821 // ࠡ SAMARITAN VOWEL SIGN OVERLONG A
#define UC_MACRO_NAME_822 0x0822 // ࠢ SAMARITAN VOWEL SIGN LONG A
#define UC_MACRO_NAME_823 0x0823 // ࠣ SAMARITAN VOWEL SIGN A
#define UC_MACRO_NAME_824 0x0824 // ࠤ SAMARITAN MODIFIER LETTER SHORT A
#define UC_MACRO_NAME_825 0x0825 // ࠥ SAMARITAN VOWEL SIGN SHORT A
#define UC_MACRO_NAME_826 0x0826 // ࠦ SAMARITAN VOWEL SIGN LONG U
#define UC_MACRO_NAME_827 0x0827 // ࠧ SAMARITAN VOWEL SIGN U
#define UC_MACRO_NAME_828 0x0828 // ࠨ SAMARITAN MODIFIER LETTER I
#define UC_MACRO_NAME_829 0x0829 // ࠩ SAMARITAN VOWEL SIGN LONG I
#define UC_MACRO_NAME_82A 0x082A // ࠪ SAMARITAN VOWEL SIGN I
#define UC_MACRO_NAME_82B 0x082B // ࠫ SAMARITAN VOWEL SIGN O
#define UC_MACRO_NAME_82C 0x082C // ࠬ SAMARITAN VOWEL SIGN SUKUN
#define UC_MACRO_NAME_82D 0x082D // ࠭ SAMARITAN MARK NEQUDAA
#define UC_MACRO_NAME_830 0x0830 // ࠰ SAMARITAN PUNCTUATION NEQUDAA
#define UC_MACRO_NAME_831 0x0831 // ࠱ SAMARITAN PUNCTUATION AFSAAQ
#define UC_MACRO_NAME_832 0x0832 // ࠲ SAMARITAN PUNCTUATION ANGED
#define UC_MACRO_NAME_833 0x0833 // ࠳ SAMARITAN PUNCTUATION BAU
#define UC_MACRO_NAME_834 0x0834 // ࠴ SAMARITAN PUNCTUATION ATMAAU
#define UC_MACRO_NAME_835 0x0835 // ࠵ SAMARITAN PUNCTUATION SHIYYAALAA
#define UC_MACRO_NAME_836 0x0836 // ࠶ SAMARITAN ABBREVIATION MARK
#define UC_MACRO_NAME_837 0x0837 // ࠷ SAMARITAN PUNCTUATION MELODIC QITSA
#define UC_MACRO_NAME_838 0x0838 // ࠸ SAMARITAN PUNCTUATION ZIQAA
#define UC_MACRO_NAME_839 0x0839 // ࠹ SAMARITAN PUNCTUATION QITSA
#define UC_MACRO_NAME_83A 0x083A // ࠺ SAMARITAN PUNCTUATION ZAEF
#define UC_MACRO_NAME_83B 0x083B // ࠻ SAMARITAN PUNCTUATION TURU
#define UC_MACRO_NAME_83C 0x083C // ࠼ SAMARITAN PUNCTUATION ARKAANU
#define UC_MACRO_NAME_83D 0x083D // ࠽ SAMARITAN PUNCTUATION SOF MASHFAAT
#define UC_MACRO_NAME_83E 0x083E // ࠾ SAMARITAN PUNCTUATION ANNAAU


#endif // UC_H_SAMARITAN
