/*
 * Unicode Block: Sinhala
 * Range: U+0D80..U+0DFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Sinhala may refer to:
 *
 */
#ifndef UC_H_SINHALA
#define UC_H_SINHALA

#define UC_MACRO_NAME_D81 0x0D81 // ඁ SINHALA SIGN CANDRABINDU
#define UC_MACRO_NAME_D82 0x0D82 // ං SINHALA SIGN ANUSVARAYA
#define UC_MACRO_NAME_D83 0x0D83 // ඃ SINHALA SIGN VISARGAYA
#define UC_MACRO_NAME_D85 0x0D85 // අ SINHALA LETTER AYANNA
#define UC_MACRO_NAME_D86 0x0D86 // ආ SINHALA LETTER AAYANNA
#define UC_MACRO_NAME_D87 0x0D87 // ඇ SINHALA LETTER AEYANNA
#define UC_MACRO_NAME_D88 0x0D88 // ඈ SINHALA LETTER AEEYANNA
#define UC_MACRO_NAME_D89 0x0D89 // ඉ SINHALA LETTER IYANNA
#define UC_MACRO_NAME_D8A 0x0D8A // ඊ SINHALA LETTER IIYANNA
#define UC_MACRO_NAME_D8B 0x0D8B // උ SINHALA LETTER UYANNA
#define UC_MACRO_NAME_D8C 0x0D8C // ඌ SINHALA LETTER UUYANNA
#define UC_MACRO_NAME_D8D 0x0D8D // ඍ SINHALA LETTER IRUYANNA
#define UC_MACRO_NAME_D8E 0x0D8E // ඎ SINHALA LETTER IRUUYANNA
#define UC_MACRO_NAME_D8F 0x0D8F // ඏ SINHALA LETTER ILUYANNA
#define UC_MACRO_NAME_D90 0x0D90 // ඐ SINHALA LETTER ILUUYANNA
#define UC_MACRO_NAME_D91 0x0D91 // එ SINHALA LETTER EYANNA
#define UC_MACRO_NAME_D92 0x0D92 // ඒ SINHALA LETTER EEYANNA
#define UC_MACRO_NAME_D93 0x0D93 // ඓ SINHALA LETTER AIYANNA
#define UC_MACRO_NAME_D94 0x0D94 // ඔ SINHALA LETTER OYANNA
#define UC_MACRO_NAME_D95 0x0D95 // ඕ SINHALA LETTER OOYANNA
#define UC_MACRO_NAME_D96 0x0D96 // ඖ SINHALA LETTER AUYANNA
#define UC_MACRO_NAME_D9A 0x0D9A // ක SINHALA LETTER ALPAPRAANA KAYANNA
#define UC_MACRO_NAME_D9B 0x0D9B // ඛ SINHALA LETTER MAHAAPRAANA KAYANNA
#define UC_MACRO_NAME_D9C 0x0D9C // ග SINHALA LETTER ALPAPRAANA GAYANNA
#define UC_MACRO_NAME_D9D 0x0D9D // ඝ SINHALA LETTER MAHAAPRAANA GAYANNA
#define UC_MACRO_NAME_D9E 0x0D9E // ඞ SINHALA LETTER KANTAJA NAASIKYAYA
#define UC_MACRO_NAME_D9F 0x0D9F // ඟ SINHALA LETTER SANYAKA GAYANNA
#define UC_MACRO_NAME_DA0 0x0DA0 // ච SINHALA LETTER ALPAPRAANA CAYANNA
#define UC_MACRO_NAME_DA1 0x0DA1 // ඡ SINHALA LETTER MAHAAPRAANA CAYANNA
#define UC_MACRO_NAME_DA2 0x0DA2 // ජ SINHALA LETTER ALPAPRAANA JAYANNA
#define UC_MACRO_NAME_DA3 0x0DA3 // ඣ SINHALA LETTER MAHAAPRAANA JAYANNA
#define UC_MACRO_NAME_DA4 0x0DA4 // ඤ SINHALA LETTER TAALUJA NAASIKYAYA
#define UC_MACRO_NAME_DA5 0x0DA5 // ඥ SINHALA LETTER TAALUJA SANYOOGA NAAKSIKYAYA
#define UC_MACRO_NAME_DA6 0x0DA6 // ඦ SINHALA LETTER SANYAKA JAYANNA
#define UC_MACRO_NAME_DA7 0x0DA7 // ට SINHALA LETTER ALPAPRAANA TTAYANNA
#define UC_MACRO_NAME_DA8 0x0DA8 // ඨ SINHALA LETTER MAHAAPRAANA TTAYANNA
#define UC_MACRO_NAME_DA9 0x0DA9 // ඩ SINHALA LETTER ALPAPRAANA DDAYANNA
#define UC_MACRO_NAME_DAA 0x0DAA // ඪ SINHALA LETTER MAHAAPRAANA DDAYANNA
#define UC_MACRO_NAME_DAB 0x0DAB // ණ SINHALA LETTER MUURDHAJA NAYANNA
#define UC_MACRO_NAME_DAC 0x0DAC // ඬ SINHALA LETTER SANYAKA DDAYANNA
#define UC_MACRO_NAME_DAD 0x0DAD // ත SINHALA LETTER ALPAPRAANA TAYANNA
#define UC_MACRO_NAME_DAE 0x0DAE // ථ SINHALA LETTER MAHAAPRAANA TAYANNA
#define UC_MACRO_NAME_DAF 0x0DAF // ද SINHALA LETTER ALPAPRAANA DAYANNA
#define UC_MACRO_NAME_DB0 0x0DB0 // ධ SINHALA LETTER MAHAAPRAANA DAYANNA
#define UC_MACRO_NAME_DB1 0x0DB1 // න SINHALA LETTER DANTAJA NAYANNA
#define UC_MACRO_NAME_DB3 0x0DB3 // ඳ SINHALA LETTER SANYAKA DAYANNA
#define UC_MACRO_NAME_DB4 0x0DB4 // ප SINHALA LETTER ALPAPRAANA PAYANNA
#define UC_MACRO_NAME_DB5 0x0DB5 // ඵ SINHALA LETTER MAHAAPRAANA PAYANNA
#define UC_MACRO_NAME_DB6 0x0DB6 // බ SINHALA LETTER ALPAPRAANA BAYANNA
#define UC_MACRO_NAME_DB7 0x0DB7 // භ SINHALA LETTER MAHAAPRAANA BAYANNA
#define UC_MACRO_NAME_DB8 0x0DB8 // ම SINHALA LETTER MAYANNA
#define UC_MACRO_NAME_DB9 0x0DB9 // ඹ SINHALA LETTER AMBA BAYANNA
#define UC_MACRO_NAME_DBA 0x0DBA // ය SINHALA LETTER YAYANNA
#define UC_MACRO_NAME_DBB 0x0DBB // ර SINHALA LETTER RAYANNA
#define UC_MACRO_NAME_DBD 0x0DBD // ල SINHALA LETTER DANTAJA LAYANNA
#define UC_MACRO_NAME_DC0 0x0DC0 // ව SINHALA LETTER VAYANNA
#define UC_MACRO_NAME_DC1 0x0DC1 // ශ SINHALA LETTER TAALUJA SAYANNA
#define UC_MACRO_NAME_DC2 0x0DC2 // ෂ SINHALA LETTER MUURDHAJA SAYANNA
#define UC_MACRO_NAME_DC3 0x0DC3 // ස SINHALA LETTER DANTAJA SAYANNA
#define UC_MACRO_NAME_DC4 0x0DC4 // හ SINHALA LETTER HAYANNA
#define UC_MACRO_NAME_DC5 0x0DC5 // ළ SINHALA LETTER MUURDHAJA LAYANNA
#define UC_MACRO_NAME_DC6 0x0DC6 // ෆ SINHALA LETTER FAYANNA
#define UC_MACRO_NAME_DCA 0x0DCA // ් SINHALA SIGN AL-LAKUNA
#define UC_MACRO_NAME_DCF 0x0DCF // ා SINHALA VOWEL SIGN AELA-PILLA
#define UC_MACRO_NAME_DD0 0x0DD0 // ැ SINHALA VOWEL SIGN KETTI AEDA-PILLA
#define UC_MACRO_NAME_DD1 0x0DD1 // ෑ SINHALA VOWEL SIGN DIGA AEDA-PILLA
#define UC_MACRO_NAME_DD2 0x0DD2 // ි SINHALA VOWEL SIGN KETTI IS-PILLA
#define UC_MACRO_NAME_DD3 0x0DD3 // ී SINHALA VOWEL SIGN DIGA IS-PILLA
#define UC_MACRO_NAME_DD4 0x0DD4 // ු SINHALA VOWEL SIGN KETTI PAA-PILLA
#define UC_MACRO_NAME_DD6 0x0DD6 // ූ SINHALA VOWEL SIGN DIGA PAA-PILLA
#define UC_MACRO_NAME_DD8 0x0DD8 // ෘ SINHALA VOWEL SIGN GAETTA-PILLA
#define UC_MACRO_NAME_DD9 0x0DD9 // ෙ SINHALA VOWEL SIGN KOMBUVA
#define UC_MACRO_NAME_DDA 0x0DDA // ේ SINHALA VOWEL SIGN DIGA KOMBUVA
#define UC_MACRO_NAME_DDB 0x0DDB // ෛ SINHALA VOWEL SIGN KOMBU DEKA
#define UC_MACRO_NAME_DDC 0x0DDC // ො SINHALA VOWEL SIGN KOMBUVA HAA AELA-PILLA
#define UC_MACRO_NAME_DDD 0x0DDD // ෝ SINHALA VOWEL SIGN KOMBUVA HAA DIGA AELA-PILLA
#define UC_MACRO_NAME_DDE 0x0DDE // ෞ SINHALA VOWEL SIGN KOMBUVA HAA GAYANUKITTA
#define UC_MACRO_NAME_DDF 0x0DDF // ෟ SINHALA VOWEL SIGN GAYANUKITTA
#define UC_MACRO_NAME_DE6 0x0DE6 // ෦ SINHALA LITH DIGIT ZERO
#define UC_MACRO_NAME_DE7 0x0DE7 // ෧ SINHALA LITH DIGIT ONE
#define UC_MACRO_NAME_DE8 0x0DE8 // ෨ SINHALA LITH DIGIT TWO
#define UC_MACRO_NAME_DE9 0x0DE9 // ෩ SINHALA LITH DIGIT THREE
#define UC_MACRO_NAME_DEA 0x0DEA // ෪ SINHALA LITH DIGIT FOUR
#define UC_MACRO_NAME_DEB 0x0DEB // ෫ SINHALA LITH DIGIT FIVE
#define UC_MACRO_NAME_DEC 0x0DEC // ෬ SINHALA LITH DIGIT SIX
#define UC_MACRO_NAME_DED 0x0DED // ෭ SINHALA LITH DIGIT SEVEN
#define UC_MACRO_NAME_DEE 0x0DEE // ෮ SINHALA LITH DIGIT EIGHT
#define UC_MACRO_NAME_DEF 0x0DEF // ෯ SINHALA LITH DIGIT NINE
#define UC_MACRO_NAME_DF2 0x0DF2 // ෲ SINHALA VOWEL SIGN DIGA GAETTA-PILLA
#define UC_MACRO_NAME_DF3 0x0DF3 // ෳ SINHALA VOWEL SIGN DIGA GAYANUKITTA
#define UC_MACRO_NAME_DF4 0x0DF4 // ෴ SINHALA PUNCTUATION KUNDDALIYA


#endif // UC_H_SINHALA
