/*
 * Unicode Block: Symbols for Legacy Computing
 * Range: U+1FB00..U+1FBFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Symbols for Legacy Computing is a Unicode block containing graphic
 * characters that were used for various home computers from the 1970s
 * and 1980s and in teletext broadcasting standards. It includes
 * characters from the Amstrad CPC , MSX , Mattel Aquarius , RISC OS ,
 * MouseText , Atari ST , TRS-80 Color Computer , Oric , Texas
 * Instruments TI-99/4A , TRS-80 , Minitel , Teletext , ATASCII , PETSCII
 * , ZX80 , and ZX81 character sets. Semigraphics characters are also
 * included in the form of new block-shaped characters, line-drawing
 * characters, and 60 "sextant" characters (semigraphic character made up
 * of six smaller blocks). Additional characters were added to this block
 * in Unicode 16.0 as well.
 * A supplemental block ( Symbols for Legacy Computing Supplement ) was
 * added with Unicode 16.0.
 *
 */
#ifndef UC_H_SYMBOLS_FOR_LEGACY_COMPUTING
#define UC_H_SYMBOLS_FOR_LEGACY_COMPUTING

#define UC_MACRO_NAME_1FB00 0x1FB00 // 🬀 BLOCK SEXTANT-1
#define UC_MACRO_NAME_1FB01 0x1FB01 // 🬁 BLOCK SEXTANT-2
#define UC_MACRO_NAME_1FB02 0x1FB02 // 🬂 BLOCK SEXTANT-12
#define UC_MACRO_NAME_1FB03 0x1FB03 // 🬃 BLOCK SEXTANT-3
#define UC_MACRO_NAME_1FB04 0x1FB04 // 🬄 BLOCK SEXTANT-13
#define UC_MACRO_NAME_1FB05 0x1FB05 // 🬅 BLOCK SEXTANT-23
#define UC_MACRO_NAME_1FB06 0x1FB06 // 🬆 BLOCK SEXTANT-123
#define UC_MACRO_NAME_1FB07 0x1FB07 // 🬇 BLOCK SEXTANT-4
#define UC_MACRO_NAME_1FB08 0x1FB08 // 🬈 BLOCK SEXTANT-14
#define UC_MACRO_NAME_1FB09 0x1FB09 // 🬉 BLOCK SEXTANT-24
#define UC_MACRO_NAME_1FB0A 0x1FB0A // 🬊 BLOCK SEXTANT-124
#define UC_MACRO_NAME_1FB0B 0x1FB0B // 🬋 BLOCK SEXTANT-34
#define UC_MACRO_NAME_1FB0C 0x1FB0C // 🬌 BLOCK SEXTANT-134
#define UC_MACRO_NAME_1FB0D 0x1FB0D // 🬍 BLOCK SEXTANT-234
#define UC_MACRO_NAME_1FB0E 0x1FB0E // 🬎 BLOCK SEXTANT-1234
#define UC_MACRO_NAME_1FB0F 0x1FB0F // 🬏 BLOCK SEXTANT-5
#define UC_MACRO_NAME_1FB10 0x1FB10 // 🬐 BLOCK SEXTANT-15
#define UC_MACRO_NAME_1FB11 0x1FB11 // 🬑 BLOCK SEXTANT-25
#define UC_MACRO_NAME_1FB12 0x1FB12 // 🬒 BLOCK SEXTANT-125
#define UC_MACRO_NAME_1FB13 0x1FB13 // 🬓 BLOCK SEXTANT-35
#define UC_MACRO_NAME_1FB14 0x1FB14 // 🬔 BLOCK SEXTANT-235
#define UC_MACRO_NAME_1FB15 0x1FB15 // 🬕 BLOCK SEXTANT-1235
#define UC_MACRO_NAME_1FB16 0x1FB16 // 🬖 BLOCK SEXTANT-45
#define UC_MACRO_NAME_1FB17 0x1FB17 // 🬗 BLOCK SEXTANT-145
#define UC_MACRO_NAME_1FB18 0x1FB18 // 🬘 BLOCK SEXTANT-245
#define UC_MACRO_NAME_1FB19 0x1FB19 // 🬙 BLOCK SEXTANT-1245
#define UC_MACRO_NAME_1FB1A 0x1FB1A // 🬚 BLOCK SEXTANT-345
#define UC_MACRO_NAME_1FB1B 0x1FB1B // 🬛 BLOCK SEXTANT-1345
#define UC_MACRO_NAME_1FB1C 0x1FB1C // 🬜 BLOCK SEXTANT-2345
#define UC_MACRO_NAME_1FB1D 0x1FB1D // 🬝 BLOCK SEXTANT-12345
#define UC_MACRO_NAME_1FB1E 0x1FB1E // 🬞 BLOCK SEXTANT-6
#define UC_MACRO_NAME_1FB1F 0x1FB1F // 🬟 BLOCK SEXTANT-16
#define UC_MACRO_NAME_1FB20 0x1FB20 // 🬠 BLOCK SEXTANT-26
#define UC_MACRO_NAME_1FB21 0x1FB21 // 🬡 BLOCK SEXTANT-126
#define UC_MACRO_NAME_1FB22 0x1FB22 // 🬢 BLOCK SEXTANT-36
#define UC_MACRO_NAME_1FB23 0x1FB23 // 🬣 BLOCK SEXTANT-136
#define UC_MACRO_NAME_1FB24 0x1FB24 // 🬤 BLOCK SEXTANT-236
#define UC_MACRO_NAME_1FB25 0x1FB25 // 🬥 BLOCK SEXTANT-1236
#define UC_MACRO_NAME_1FB26 0x1FB26 // 🬦 BLOCK SEXTANT-46
#define UC_MACRO_NAME_1FB27 0x1FB27 // 🬧 BLOCK SEXTANT-146
#define UC_MACRO_NAME_1FB28 0x1FB28 // 🬨 BLOCK SEXTANT-1246
#define UC_MACRO_NAME_1FB29 0x1FB29 // 🬩 BLOCK SEXTANT-346
#define UC_MACRO_NAME_1FB2A 0x1FB2A // 🬪 BLOCK SEXTANT-1346
#define UC_MACRO_NAME_1FB2B 0x1FB2B // 🬫 BLOCK SEXTANT-2346
#define UC_MACRO_NAME_1FB2C 0x1FB2C // 🬬 BLOCK SEXTANT-12346
#define UC_MACRO_NAME_1FB2D 0x1FB2D // 🬭 BLOCK SEXTANT-56
#define UC_MACRO_NAME_1FB2E 0x1FB2E // 🬮 BLOCK SEXTANT-156
#define UC_MACRO_NAME_1FB2F 0x1FB2F // 🬯 BLOCK SEXTANT-256
#define UC_MACRO_NAME_1FB30 0x1FB30 // 🬰 BLOCK SEXTANT-1256
#define UC_MACRO_NAME_1FB31 0x1FB31 // 🬱 BLOCK SEXTANT-356
#define UC_MACRO_NAME_1FB32 0x1FB32 // 🬲 BLOCK SEXTANT-1356
#define UC_MACRO_NAME_1FB33 0x1FB33 // 🬳 BLOCK SEXTANT-2356
#define UC_MACRO_NAME_1FB34 0x1FB34 // 🬴 BLOCK SEXTANT-12356
#define UC_MACRO_NAME_1FB35 0x1FB35 // 🬵 BLOCK SEXTANT-456
#define UC_MACRO_NAME_1FB36 0x1FB36 // 🬶 BLOCK SEXTANT-1456
#define UC_MACRO_NAME_1FB37 0x1FB37 // 🬷 BLOCK SEXTANT-2456
#define UC_MACRO_NAME_1FB38 0x1FB38 // 🬸 BLOCK SEXTANT-12456
#define UC_MACRO_NAME_1FB39 0x1FB39 // 🬹 BLOCK SEXTANT-3456
#define UC_MACRO_NAME_1FB3A 0x1FB3A // 🬺 BLOCK SEXTANT-13456
#define UC_MACRO_NAME_1FB3B 0x1FB3B // 🬻 BLOCK SEXTANT-23456
#define UC_MACRO_NAME_1FB3C 0x1FB3C // 🬼 LOWER LEFT BLOCK DIAGONAL LOWER MIDDLE LEFT TO LOWER CENTRE
#define UC_MACRO_NAME_1FB3D 0x1FB3D // 🬽 LOWER LEFT BLOCK DIAGONAL LOWER MIDDLE LEFT TO LOWER RIGHT
#define UC_MACRO_NAME_1FB3E 0x1FB3E // 🬾 LOWER LEFT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER CENTRE
#define UC_MACRO_NAME_1FB3F 0x1FB3F // 🬿 LOWER LEFT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER RIGHT
#define UC_MACRO_NAME_1FB40 0x1FB40 // 🭀 LOWER LEFT BLOCK DIAGONAL UPPER LEFT TO LOWER CENTRE
#define UC_MACRO_NAME_1FB41 0x1FB41 // 🭁 LOWER RIGHT BLOCK DIAGONAL UPPER MIDDLE LEFT TO UPPER CENTRE
#define UC_MACRO_NAME_1FB42 0x1FB42 // 🭂 LOWER RIGHT BLOCK DIAGONAL UPPER MIDDLE LEFT TO UPPER RIGHT
#define UC_MACRO_NAME_1FB43 0x1FB43 // 🭃 LOWER RIGHT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER CENTRE
#define UC_MACRO_NAME_1FB44 0x1FB44 // 🭄 LOWER RIGHT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER RIGHT
#define UC_MACRO_NAME_1FB45 0x1FB45 // 🭅 LOWER RIGHT BLOCK DIAGONAL LOWER LEFT TO UPPER CENTRE
#define UC_MACRO_NAME_1FB46 0x1FB46 // 🭆 LOWER RIGHT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB47 0x1FB47 // 🭇 LOWER RIGHT BLOCK DIAGONAL LOWER CENTRE TO LOWER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB48 0x1FB48 // 🭈 LOWER RIGHT BLOCK DIAGONAL LOWER LEFT TO LOWER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB49 0x1FB49 // 🭉 LOWER RIGHT BLOCK DIAGONAL LOWER CENTRE TO UPPER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB4A 0x1FB4A // 🭊 LOWER RIGHT BLOCK DIAGONAL LOWER LEFT TO UPPER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB4B 0x1FB4B // 🭋 LOWER RIGHT BLOCK DIAGONAL LOWER CENTRE TO UPPER RIGHT
#define UC_MACRO_NAME_1FB4C 0x1FB4C // 🭌 LOWER LEFT BLOCK DIAGONAL UPPER CENTRE TO UPPER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB4D 0x1FB4D // 🭍 LOWER LEFT BLOCK DIAGONAL UPPER LEFT TO UPPER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB4E 0x1FB4E // 🭎 LOWER LEFT BLOCK DIAGONAL UPPER CENTRE TO LOWER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB4F 0x1FB4F // 🭏 LOWER LEFT BLOCK DIAGONAL UPPER LEFT TO LOWER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB50 0x1FB50 // 🭐 LOWER LEFT BLOCK DIAGONAL UPPER CENTRE TO LOWER RIGHT
#define UC_MACRO_NAME_1FB51 0x1FB51 // 🭑 LOWER LEFT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB52 0x1FB52 // 🭒 UPPER RIGHT BLOCK DIAGONAL LOWER MIDDLE LEFT TO LOWER CENTRE
#define UC_MACRO_NAME_1FB53 0x1FB53 // 🭓 UPPER RIGHT BLOCK DIAGONAL LOWER MIDDLE LEFT TO LOWER RIGHT
#define UC_MACRO_NAME_1FB54 0x1FB54 // 🭔 UPPER RIGHT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER CENTRE
#define UC_MACRO_NAME_1FB55 0x1FB55 // 🭕 UPPER RIGHT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER RIGHT
#define UC_MACRO_NAME_1FB56 0x1FB56 // 🭖 UPPER RIGHT BLOCK DIAGONAL UPPER LEFT TO LOWER CENTRE
#define UC_MACRO_NAME_1FB57 0x1FB57 // 🭗 UPPER LEFT BLOCK DIAGONAL UPPER MIDDLE LEFT TO UPPER CENTRE
#define UC_MACRO_NAME_1FB58 0x1FB58 // 🭘 UPPER LEFT BLOCK DIAGONAL UPPER MIDDLE LEFT TO UPPER RIGHT
#define UC_MACRO_NAME_1FB59 0x1FB59 // 🭙 UPPER LEFT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER CENTRE
#define UC_MACRO_NAME_1FB5A 0x1FB5A // 🭚 UPPER LEFT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER RIGHT
#define UC_MACRO_NAME_1FB5B 0x1FB5B // 🭛 UPPER LEFT BLOCK DIAGONAL LOWER LEFT TO UPPER CENTRE
#define UC_MACRO_NAME_1FB5C 0x1FB5C // 🭜 UPPER LEFT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB5D 0x1FB5D // 🭝 UPPER LEFT BLOCK DIAGONAL LOWER CENTRE TO LOWER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB5E 0x1FB5E // 🭞 UPPER LEFT BLOCK DIAGONAL LOWER LEFT TO LOWER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB5F 0x1FB5F // 🭟 UPPER LEFT BLOCK DIAGONAL LOWER CENTRE TO UPPER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB60 0x1FB60 // 🭠 UPPER LEFT BLOCK DIAGONAL LOWER LEFT TO UPPER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB61 0x1FB61 // 🭡 UPPER LEFT BLOCK DIAGONAL LOWER CENTRE TO UPPER RIGHT
#define UC_MACRO_NAME_1FB62 0x1FB62 // 🭢 UPPER RIGHT BLOCK DIAGONAL UPPER CENTRE TO UPPER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB63 0x1FB63 // 🭣 UPPER RIGHT BLOCK DIAGONAL UPPER LEFT TO UPPER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB64 0x1FB64 // 🭤 UPPER RIGHT BLOCK DIAGONAL UPPER CENTRE TO LOWER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB65 0x1FB65 // 🭥 UPPER RIGHT BLOCK DIAGONAL UPPER LEFT TO LOWER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB66 0x1FB66 // 🭦 UPPER RIGHT BLOCK DIAGONAL UPPER CENTRE TO LOWER RIGHT
#define UC_MACRO_NAME_1FB67 0x1FB67 // 🭧 UPPER RIGHT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER MIDDLE RIGHT
#define UC_MACRO_NAME_1FB68 0x1FB68 // 🭨 UPPER AND RIGHT AND LOWER TRIANGULAR THREE QUARTERS BLOCK
#define UC_MACRO_NAME_1FB69 0x1FB69 // 🭩 LEFT AND LOWER AND RIGHT TRIANGULAR THREE QUARTERS BLOCK
#define UC_MACRO_NAME_1FB6A 0x1FB6A // 🭪 UPPER AND LEFT AND LOWER TRIANGULAR THREE QUARTERS BLOCK
#define UC_MACRO_NAME_1FB6B 0x1FB6B // 🭫 LEFT AND UPPER AND RIGHT TRIANGULAR THREE QUARTERS BLOCK
#define UC_MACRO_NAME_1FB6C 0x1FB6C // 🭬 LEFT TRIANGULAR ONE QUARTER BLOCK
#define UC_MACRO_NAME_1FB6D 0x1FB6D // 🭭 UPPER TRIANGULAR ONE QUARTER BLOCK
#define UC_MACRO_NAME_1FB6E 0x1FB6E // 🭮 RIGHT TRIANGULAR ONE QUARTER BLOCK
#define UC_MACRO_NAME_1FB6F 0x1FB6F // 🭯 LOWER TRIANGULAR ONE QUARTER BLOCK
#define UC_MACRO_NAME_1FB70 0x1FB70 // 🭰 VERTICAL ONE EIGHTH BLOCK-2
#define UC_MACRO_NAME_1FB71 0x1FB71 // 🭱 VERTICAL ONE EIGHTH BLOCK-3
#define UC_MACRO_NAME_1FB72 0x1FB72 // 🭲 VERTICAL ONE EIGHTH BLOCK-4
#define UC_MACRO_NAME_1FB73 0x1FB73 // 🭳 VERTICAL ONE EIGHTH BLOCK-5
#define UC_MACRO_NAME_1FB74 0x1FB74 // 🭴 VERTICAL ONE EIGHTH BLOCK-6
#define UC_MACRO_NAME_1FB75 0x1FB75 // 🭵 VERTICAL ONE EIGHTH BLOCK-7
#define UC_MACRO_NAME_1FB76 0x1FB76 // 🭶 HORIZONTAL ONE EIGHTH BLOCK-2
#define UC_MACRO_NAME_1FB77 0x1FB77 // 🭷 HORIZONTAL ONE EIGHTH BLOCK-3
#define UC_MACRO_NAME_1FB78 0x1FB78 // 🭸 HORIZONTAL ONE EIGHTH BLOCK-4
#define UC_MACRO_NAME_1FB79 0x1FB79 // 🭹 HORIZONTAL ONE EIGHTH BLOCK-5
#define UC_MACRO_NAME_1FB7A 0x1FB7A // 🭺 HORIZONTAL ONE EIGHTH BLOCK-6
#define UC_MACRO_NAME_1FB7B 0x1FB7B // 🭻 HORIZONTAL ONE EIGHTH BLOCK-7
#define UC_MACRO_NAME_1FB7C 0x1FB7C // 🭼 LEFT AND LOWER ONE EIGHTH BLOCK
#define UC_MACRO_NAME_1FB7D 0x1FB7D // 🭽 LEFT AND UPPER ONE EIGHTH BLOCK
#define UC_MACRO_NAME_1FB7E 0x1FB7E // 🭾 RIGHT AND UPPER ONE EIGHTH BLOCK
#define UC_MACRO_NAME_1FB7F 0x1FB7F // 🭿 RIGHT AND LOWER ONE EIGHTH BLOCK
#define UC_MACRO_NAME_1FB80 0x1FB80 // 🮀 UPPER AND LOWER ONE EIGHTH BLOCK
#define UC_MACRO_NAME_1FB81 0x1FB81 // 🮁 HORIZONTAL ONE EIGHTH BLOCK-1358
#define UC_MACRO_NAME_1FB82 0x1FB82 // 🮂 UPPER ONE QUARTER BLOCK
#define UC_MACRO_NAME_1FB83 0x1FB83 // 🮃 UPPER THREE EIGHTHS BLOCK
#define UC_MACRO_NAME_1FB84 0x1FB84 // 🮄 UPPER FIVE EIGHTHS BLOCK
#define UC_MACRO_NAME_1FB85 0x1FB85 // 🮅 UPPER THREE QUARTERS BLOCK
#define UC_MACRO_NAME_1FB86 0x1FB86 // 🮆 UPPER SEVEN EIGHTHS BLOCK
#define UC_MACRO_NAME_1FB87 0x1FB87 // 🮇 RIGHT ONE QUARTER BLOCK
#define UC_MACRO_NAME_1FB88 0x1FB88 // 🮈 RIGHT THREE EIGHTHS BLOCK
#define UC_MACRO_NAME_1FB89 0x1FB89 // 🮉 RIGHT FIVE EIGHTHS BLOCK
#define UC_MACRO_NAME_1FB8A 0x1FB8A // 🮊 RIGHT THREE QUARTERS BLOCK
#define UC_MACRO_NAME_1FB8B 0x1FB8B // 🮋 RIGHT SEVEN EIGHTHS BLOCK
#define UC_MACRO_NAME_1FB8C 0x1FB8C // 🮌 LEFT HALF MEDIUM SHADE
#define UC_MACRO_NAME_1FB8D 0x1FB8D // 🮍 RIGHT HALF MEDIUM SHADE
#define UC_MACRO_NAME_1FB8E 0x1FB8E // 🮎 UPPER HALF MEDIUM SHADE
#define UC_MACRO_NAME_1FB8F 0x1FB8F // 🮏 LOWER HALF MEDIUM SHADE
#define UC_MACRO_NAME_1FB90 0x1FB90 // 🮐 INVERSE MEDIUM SHADE
#define UC_MACRO_NAME_1FB91 0x1FB91 // 🮑 UPPER HALF BLOCK AND LOWER HALF INVERSE MEDIUM SHADE
#define UC_MACRO_NAME_1FB92 0x1FB92 // 🮒 UPPER HALF INVERSE MEDIUM SHADE AND LOWER HALF BLOCK
#define UC_MACRO_NAME_1FB94 0x1FB94 // 🮔 LEFT HALF INVERSE MEDIUM SHADE AND RIGHT HALF BLOCK
#define UC_MACRO_NAME_1FB95 0x1FB95 // 🮕 CHECKER BOARD FILL
#define UC_MACRO_NAME_1FB96 0x1FB96 // 🮖 INVERSE CHECKER BOARD FILL
#define UC_MACRO_NAME_1FB97 0x1FB97 // 🮗 HEAVY HORIZONTAL FILL
#define UC_MACRO_NAME_1FB98 0x1FB98 // 🮘 UPPER LEFT TO LOWER RIGHT FILL
#define UC_MACRO_NAME_1FB99 0x1FB99 // 🮙 UPPER RIGHT TO LOWER LEFT FILL
#define UC_MACRO_NAME_1FB9A 0x1FB9A // 🮚 UPPER AND LOWER TRIANGULAR HALF BLOCK
#define UC_MACRO_NAME_1FB9B 0x1FB9B // 🮛 LEFT AND RIGHT TRIANGULAR HALF BLOCK
#define UC_MACRO_NAME_1FB9C 0x1FB9C // 🮜 UPPER LEFT TRIANGULAR MEDIUM SHADE
#define UC_MACRO_NAME_1FB9D 0x1FB9D // 🮝 UPPER RIGHT TRIANGULAR MEDIUM SHADE
#define UC_MACRO_NAME_1FB9E 0x1FB9E // 🮞 LOWER RIGHT TRIANGULAR MEDIUM SHADE
#define UC_MACRO_NAME_1FB9F 0x1FB9F // 🮟 LOWER LEFT TRIANGULAR MEDIUM SHADE
#define UC_MACRO_NAME_1FBA0 0x1FBA0 // 🮠 BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE LEFT
#define UC_MACRO_NAME_1FBA1 0x1FBA1 // 🮡 BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE RIGHT
#define UC_MACRO_NAME_1FBA2 0x1FBA2 // 🮢 BOX DRAWINGS LIGHT DIAGONAL MIDDLE LEFT TO LOWER CENTRE
#define UC_MACRO_NAME_1FBA3 0x1FBA3 // 🮣 BOX DRAWINGS LIGHT DIAGONAL MIDDLE RIGHT TO LOWER CENTRE
#define UC_MACRO_NAME_1FBA4 0x1FBA4 // 🮤 BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE LEFT TO LOWER CENTRE
#define UC_MACRO_NAME_1FBA5 0x1FBA5 // 🮥 BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE RIGHT TO LOWER CENTRE
#define UC_MACRO_NAME_1FBA6 0x1FBA6 // 🮦 BOX DRAWINGS LIGHT DIAGONAL MIDDLE LEFT TO LOWER CENTRE TO MIDDLE RIGHT
#define UC_MACRO_NAME_1FBA7 0x1FBA7 // 🮧 BOX DRAWINGS LIGHT DIAGONAL MIDDLE LEFT TO UPPER CENTRE TO MIDDLE RIGHT
#define UC_MACRO_NAME_1FBA8 0x1FBA8 // 🮨 BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE LEFT AND MIDDLE RIGHT TO LOWER CENTRE
#define UC_MACRO_NAME_1FBA9 0x1FBA9 // 🮩 BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE RIGHT AND MIDDLE LEFT TO LOWER CENTRE
#define UC_MACRO_NAME_1FBAA 0x1FBAA // 🮪 BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE RIGHT TO LOWER CENTRE TO MIDDLE LEFT
#define UC_MACRO_NAME_1FBAB 0x1FBAB // 🮫 BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE LEFT TO LOWER CENTRE TO MIDDLE RIGHT
#define UC_MACRO_NAME_1FBAC 0x1FBAC // 🮬 BOX DRAWINGS LIGHT DIAGONAL MIDDLE LEFT TO UPPER CENTRE TO MIDDLE RIGHT TO LOWER CENTRE
#define UC_MACRO_NAME_1FBAD 0x1FBAD // 🮭 BOX DRAWINGS LIGHT DIAGONAL MIDDLE RIGHT TO UPPER CENTRE TO MIDDLE LEFT TO LOWER CENTRE
#define UC_MACRO_NAME_1FBAE 0x1FBAE // 🮮 BOX DRAWINGS LIGHT DIAGONAL DIAMOND
#define UC_MACRO_NAME_1FBAF 0x1FBAF // 🮯 BOX DRAWINGS LIGHT HORIZONTAL WITH VERTICAL STROKE
#define UC_MACRO_NAME_1FBB0 0x1FBB0 // 🮰 ARROWHEAD-SHAPED POINTER
#define UC_MACRO_NAME_1FBB1 0x1FBB1 // 🮱 INVERSE CHECK MARK
#define UC_MACRO_NAME_1FBB2 0x1FBB2 // 🮲 LEFT HALF RUNNING MAN
#define UC_MACRO_NAME_1FBB3 0x1FBB3 // 🮳 RIGHT HALF RUNNING MAN
#define UC_MACRO_NAME_1FBB4 0x1FBB4 // 🮴 INVERSE DOWNWARDS ARROW WITH TIP LEFTWARDS
#define UC_MACRO_NAME_1FBB5 0x1FBB5 // 🮵 LEFTWARDS ARROW AND UPPER AND LOWER ONE EIGHTH BLOCK
#define UC_MACRO_NAME_1FBB6 0x1FBB6 // 🮶 RIGHTWARDS ARROW AND UPPER AND LOWER ONE EIGHTH BLOCK
#define UC_MACRO_NAME_1FBB7 0x1FBB7 // 🮷 DOWNWARDS ARROW AND RIGHT ONE EIGHTH BLOCK
#define UC_MACRO_NAME_1FBB8 0x1FBB8 // 🮸 UPWARDS ARROW AND RIGHT ONE EIGHTH BLOCK
#define UC_MACRO_NAME_1FBB9 0x1FBB9 // 🮹 LEFT HALF FOLDER
#define UC_MACRO_NAME_1FBBA 0x1FBBA // 🮺 RIGHT HALF FOLDER
#define UC_MACRO_NAME_1FBBB 0x1FBBB // 🮻 VOIDED GREEK CROSS
#define UC_MACRO_NAME_1FBBC 0x1FBBC // 🮼 RIGHT OPEN SQUARED DOT
#define UC_MACRO_NAME_1FBBD 0x1FBBD // 🮽 NEGATIVE DIAGONAL CROSS
#define UC_MACRO_NAME_1FBBE 0x1FBBE // 🮾 NEGATIVE DIAGONAL MIDDLE RIGHT TO LOWER CENTRE
#define UC_MACRO_NAME_1FBBF 0x1FBBF // 🮿 NEGATIVE DIAGONAL DIAMOND
#define UC_MACRO_NAME_1FBC0 0x1FBC0 // 🯀 WHITE HEAVY SALTIRE WITH ROUNDED CORNERS
#define UC_MACRO_NAME_1FBC1 0x1FBC1 // 🯁 LEFT THIRD WHITE RIGHT POINTING INDEX
#define UC_MACRO_NAME_1FBC2 0x1FBC2 // 🯂 MIDDLE THIRD WHITE RIGHT POINTING INDEX
#define UC_MACRO_NAME_1FBC3 0x1FBC3 // 🯃 RIGHT THIRD WHITE RIGHT POINTING INDEX
#define UC_MACRO_NAME_1FBC4 0x1FBC4 // 🯄 NEGATIVE SQUARED QUESTION MARK
#define UC_MACRO_NAME_1FBC5 0x1FBC5 // 🯅 STICK FIGURE
#define UC_MACRO_NAME_1FBC6 0x1FBC6 // 🯆 STICK FIGURE WITH ARMS RAISED
#define UC_MACRO_NAME_1FBC7 0x1FBC7 // 🯇 STICK FIGURE LEANING LEFT
#define UC_MACRO_NAME_1FBC8 0x1FBC8 // 🯈 STICK FIGURE LEANING RIGHT
#define UC_MACRO_NAME_1FBC9 0x1FBC9 // 🯉 STICK FIGURE WITH DRESS
#define UC_MACRO_NAME_1FBCA 0x1FBCA // 🯊 WHITE UP-POINTING CHEVRON
#define UC_MACRO_NAME_1FBCB 0x1FBCB //  WHITE CROSS MARK
#define UC_MACRO_NAME_1FBCC 0x1FBCC //  RAISED SMALL LEFT SQUARE BRACKET
#define UC_MACRO_NAME_1FBCD 0x1FBCD //  BLACK SMALL UP-POINTING CHEVRON
#define UC_MACRO_NAME_1FBCE 0x1FBCE //  LEFT TWO THIRDS BLOCK
#define UC_MACRO_NAME_1FBCF 0x1FBCF //  LEFT ONE THIRD BLOCK
#define UC_MACRO_NAME_1FBD0 0x1FBD0 //  BOX DRAWINGS LIGHT DIAGONAL MIDDLE RIGHT TO LOWER LEFT
#define UC_MACRO_NAME_1FBD1 0x1FBD1 //  BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO MIDDLE LEFT
#define UC_MACRO_NAME_1FBD2 0x1FBD2 //  BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO MIDDLE RIGHT
#define UC_MACRO_NAME_1FBD3 0x1FBD3 //  BOX DRAWINGS LIGHT DIAGONAL MIDDLE LEFT TO LOWER RIGHT
#define UC_MACRO_NAME_1FBD4 0x1FBD4 //  BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER CENTRE
#define UC_MACRO_NAME_1FBD5 0x1FBD5 //  BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO LOWER RIGHT
#define UC_MACRO_NAME_1FBD6 0x1FBD6 //  BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER CENTRE
#define UC_MACRO_NAME_1FBD7 0x1FBD7 //  BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO LOWER LEFT
#define UC_MACRO_NAME_1FBD8 0x1FBD8 //  BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO MIDDLE CENTRE TO UPPER RIGHT
#define UC_MACRO_NAME_1FBD9 0x1FBD9 //  BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO MIDDLE CENTRE TO LOWER RIGHT
#define UC_MACRO_NAME_1FBDA 0x1FBDA //  BOX DRAWINGS LIGHT DIAGONAL LOWER LEFT TO MIDDLE CENTRE TO LOWER RIGHT
#define UC_MACRO_NAME_1FBDB 0x1FBDB //  BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO MIDDLE CENTRE TO LOWER LEFT
#define UC_MACRO_NAME_1FBDC 0x1FBDC //  BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER CENTRE TO UPPER RIGHT
#define UC_MACRO_NAME_1FBDD 0x1FBDD //  BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO MIDDLE LEFT TO LOWER RIGHT
#define UC_MACRO_NAME_1FBDE 0x1FBDE //  BOX DRAWINGS LIGHT DIAGONAL LOWER LEFT TO UPPER CENTRE TO LOWER RIGHT
#define UC_MACRO_NAME_1FBDF 0x1FBDF //  BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO MIDDLE RIGHT TO LOWER LEFT
#define UC_MACRO_NAME_1FBE0 0x1FBE0 //  TOP JUSTIFIED LOWER HALF WHITE CIRCLE
#define UC_MACRO_NAME_1FBE1 0x1FBE1 //  RIGHT JUSTIFIED LEFT HALF WHITE CIRCLE
#define UC_MACRO_NAME_1FBE2 0x1FBE2 //  BOTTOM JUSTIFIED UPPER HALF WHITE CIRCLE
#define UC_MACRO_NAME_1FBE3 0x1FBE3 //  LEFT JUSTIFIED RIGHT HALF WHITE CIRCLE
#define UC_MACRO_NAME_1FBE4 0x1FBE4 //  UPPER CENTRE ONE QUARTER BLOCK
#define UC_MACRO_NAME_1FBE5 0x1FBE5 //  LOWER CENTRE ONE QUARTER BLOCK
#define UC_MACRO_NAME_1FBE6 0x1FBE6 //  MIDDLE LEFT ONE QUARTER BLOCK
#define UC_MACRO_NAME_1FBE7 0x1FBE7 //  MIDDLE RIGHT ONE QUARTER BLOCK
#define UC_MACRO_NAME_1FBE8 0x1FBE8 //  TOP JUSTIFIED LOWER HALF BLACK CIRCLE
#define UC_MACRO_NAME_1FBE9 0x1FBE9 //  RIGHT JUSTIFIED LEFT HALF BLACK CIRCLE
#define UC_MACRO_NAME_1FBEA 0x1FBEA //  BOTTOM JUSTIFIED UPPER HALF BLACK CIRCLE
#define UC_MACRO_NAME_1FBEB 0x1FBEB //  LEFT JUSTIFIED RIGHT HALF BLACK CIRCLE
#define UC_MACRO_NAME_1FBEC 0x1FBEC //  TOP RIGHT JUSTIFIED LOWER LEFT QUARTER BLACK CIRCLE
#define UC_MACRO_NAME_1FBED 0x1FBED //  BOTTOM LEFT JUSTIFIED UPPER RIGHT QUARTER BLACK CIRCLE
#define UC_MACRO_NAME_1FBEE 0x1FBEE //  BOTTOM RIGHT JUSTIFIED UPPER LEFT QUARTER BLACK CIRCLE
#define UC_MACRO_NAME_1FBEF 0x1FBEF //  TOP LEFT JUSTIFIED LOWER RIGHT QUARTER BLACK CIRCLE
#define UC_MACRO_NAME_1FBF0 0x1FBF0 // 🯰 SEGMENTED DIGIT ZERO
#define UC_MACRO_NAME_1FBF1 0x1FBF1 // 🯱 SEGMENTED DIGIT ONE
#define UC_MACRO_NAME_1FBF2 0x1FBF2 // 🯲 SEGMENTED DIGIT TWO
#define UC_MACRO_NAME_1FBF3 0x1FBF3 // 🯳 SEGMENTED DIGIT THREE
#define UC_MACRO_NAME_1FBF4 0x1FBF4 // 🯴 SEGMENTED DIGIT FOUR
#define UC_MACRO_NAME_1FBF5 0x1FBF5 // 🯵 SEGMENTED DIGIT FIVE
#define UC_MACRO_NAME_1FBF6 0x1FBF6 // 🯶 SEGMENTED DIGIT SIX
#define UC_MACRO_NAME_1FBF7 0x1FBF7 // 🯷 SEGMENTED DIGIT SEVEN
#define UC_MACRO_NAME_1FBF8 0x1FBF8 // 🯸 SEGMENTED DIGIT EIGHT
#define UC_MACRO_NAME_1FBF9 0x1FBF9 // 🯹 SEGMENTED DIGIT NINE
#define UC_MACRO_NAME_1FBFA 0x1FBFA //  ALARM BELL SYMBOL


#endif // UC_H_SYMBOLS_FOR_LEGACY_COMPUTING
