/*
 * Unicode Block: Sundanese
 * Range: U+1B80..U+1BBF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Sundanese may refer to:
 *
 */
#ifndef UC_H_SUNDANESE
#define UC_H_SUNDANESE

#define UC_MACRO_NAME_1B80 0x1B80 // ᮀ SUNDANESE SIGN PANYECEK
#define UC_MACRO_NAME_1B81 0x1B81 // ᮁ SUNDANESE SIGN PANGLAYAR
#define UC_MACRO_NAME_1B82 0x1B82 // ᮂ SUNDANESE SIGN PANGWISAD
#define UC_MACRO_NAME_1B83 0x1B83 // ᮃ SUNDANESE LETTER A
#define UC_MACRO_NAME_1B84 0x1B84 // ᮄ SUNDANESE LETTER I
#define UC_MACRO_NAME_1B85 0x1B85 // ᮅ SUNDANESE LETTER U
#define UC_MACRO_NAME_1B86 0x1B86 // ᮆ SUNDANESE LETTER AE
#define UC_MACRO_NAME_1B87 0x1B87 // ᮇ SUNDANESE LETTER O
#define UC_MACRO_NAME_1B88 0x1B88 // ᮈ SUNDANESE LETTER E
#define UC_MACRO_NAME_1B89 0x1B89 // ᮉ SUNDANESE LETTER EU
#define UC_MACRO_NAME_1B8A 0x1B8A // ᮊ SUNDANESE LETTER KA
#define UC_MACRO_NAME_1B8B 0x1B8B // ᮋ SUNDANESE LETTER QA
#define UC_MACRO_NAME_1B8C 0x1B8C // ᮌ SUNDANESE LETTER GA
#define UC_MACRO_NAME_1B8D 0x1B8D // ᮍ SUNDANESE LETTER NGA
#define UC_MACRO_NAME_1B8E 0x1B8E // ᮎ SUNDANESE LETTER CA
#define UC_MACRO_NAME_1B8F 0x1B8F // ᮏ SUNDANESE LETTER JA
#define UC_MACRO_NAME_1B90 0x1B90 // ᮐ SUNDANESE LETTER ZA
#define UC_MACRO_NAME_1B91 0x1B91 // ᮑ SUNDANESE LETTER NYA
#define UC_MACRO_NAME_1B92 0x1B92 // ᮒ SUNDANESE LETTER TA
#define UC_MACRO_NAME_1B93 0x1B93 // ᮓ SUNDANESE LETTER DA
#define UC_MACRO_NAME_1B94 0x1B94 // ᮔ SUNDANESE LETTER NA
#define UC_MACRO_NAME_1B95 0x1B95 // ᮕ SUNDANESE LETTER PA
#define UC_MACRO_NAME_1B96 0x1B96 // ᮖ SUNDANESE LETTER FA
#define UC_MACRO_NAME_1B97 0x1B97 // ᮗ SUNDANESE LETTER VA
#define UC_MACRO_NAME_1B98 0x1B98 // ᮘ SUNDANESE LETTER BA
#define UC_MACRO_NAME_1B99 0x1B99 // ᮙ SUNDANESE LETTER MA
#define UC_MACRO_NAME_1B9A 0x1B9A // ᮚ SUNDANESE LETTER YA
#define UC_MACRO_NAME_1B9B 0x1B9B // ᮛ SUNDANESE LETTER RA
#define UC_MACRO_NAME_1B9C 0x1B9C // ᮜ SUNDANESE LETTER LA
#define UC_MACRO_NAME_1B9D 0x1B9D // ᮝ SUNDANESE LETTER WA
#define UC_MACRO_NAME_1B9E 0x1B9E // ᮞ SUNDANESE LETTER SA
#define UC_MACRO_NAME_1B9F 0x1B9F // ᮟ SUNDANESE LETTER XA
#define UC_MACRO_NAME_1BA0 0x1BA0 // ᮠ SUNDANESE LETTER HA
#define UC_MACRO_NAME_1BA1 0x1BA1 // ᮡ SUNDANESE CONSONANT SIGN PAMINGKAL
#define UC_MACRO_NAME_1BA2 0x1BA2 // ᮢ SUNDANESE CONSONANT SIGN PANYAKRA
#define UC_MACRO_NAME_1BA3 0x1BA3 // ᮣ SUNDANESE CONSONANT SIGN PANYIKU
#define UC_MACRO_NAME_1BA4 0x1BA4 // ᮤ SUNDANESE VOWEL SIGN PANGHULU
#define UC_MACRO_NAME_1BA5 0x1BA5 // ᮥ SUNDANESE VOWEL SIGN PANYUKU
#define UC_MACRO_NAME_1BA6 0x1BA6 // ᮦ SUNDANESE VOWEL SIGN PANAELAENG
#define UC_MACRO_NAME_1BA7 0x1BA7 // ᮧ SUNDANESE VOWEL SIGN PANOLONG
#define UC_MACRO_NAME_1BA8 0x1BA8 // ᮨ SUNDANESE VOWEL SIGN PAMEPET
#define UC_MACRO_NAME_1BA9 0x1BA9 // ᮩ SUNDANESE VOWEL SIGN PANEULEUNG
#define UC_MACRO_NAME_1BAA 0x1BAA // ᮪ SUNDANESE SIGN PAMAAEH
#define UC_MACRO_NAME_1BAB 0x1BAB // ᮫ SUNDANESE SIGN VIRAMA
#define UC_MACRO_NAME_1BAC 0x1BAC // ᮬ SUNDANESE CONSONANT SIGN PASANGAN MA
#define UC_MACRO_NAME_1BAD 0x1BAD // ᮭ SUNDANESE CONSONANT SIGN PASANGAN WA
#define UC_MACRO_NAME_1BAE 0x1BAE // ᮮ SUNDANESE LETTER KHA
#define UC_MACRO_NAME_1BAF 0x1BAF // ᮯ SUNDANESE LETTER SYA
#define UC_MACRO_NAME_1BB0 0x1BB0 // ᮰ SUNDANESE DIGIT ZERO
#define UC_MACRO_NAME_1BB1 0x1BB1 // ᮱ SUNDANESE DIGIT ONE
#define UC_MACRO_NAME_1BB2 0x1BB2 // ᮲ SUNDANESE DIGIT TWO
#define UC_MACRO_NAME_1BB3 0x1BB3 // ᮳ SUNDANESE DIGIT THREE
#define UC_MACRO_NAME_1BB4 0x1BB4 // ᮴ SUNDANESE DIGIT FOUR
#define UC_MACRO_NAME_1BB5 0x1BB5 // ᮵ SUNDANESE DIGIT FIVE
#define UC_MACRO_NAME_1BB6 0x1BB6 // ᮶ SUNDANESE DIGIT SIX
#define UC_MACRO_NAME_1BB7 0x1BB7 // ᮷ SUNDANESE DIGIT SEVEN
#define UC_MACRO_NAME_1BB8 0x1BB8 // ᮸ SUNDANESE DIGIT EIGHT
#define UC_MACRO_NAME_1BB9 0x1BB9 // ᮹ SUNDANESE DIGIT NINE
#define UC_MACRO_NAME_1BBA 0x1BBA // ᮺ SUNDANESE AVAGRAHA
#define UC_MACRO_NAME_1BBB 0x1BBB // ᮻ SUNDANESE LETTER REU
#define UC_MACRO_NAME_1BBC 0x1BBC // ᮼ SUNDANESE LETTER LEU
#define UC_MACRO_NAME_1BBD 0x1BBD // ᮽ SUNDANESE LETTER BHA
#define UC_MACRO_NAME_1BBE 0x1BBE // ᮾ SUNDANESE LETTER FINAL K
#define UC_MACRO_NAME_1BBF 0x1BBF // ᮿ SUNDANESE LETTER FINAL M


#endif // UC_H_SUNDANESE
