/*
 * Unicode Block: Supplemental Mathematical Operators
 * Range: U+2A00..U+2AFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Supplemental Mathematical Operators is a Unicode block containing
 * various mathematical symbols, including N-ary operators, summations
 * and integrals, intersections and unions, logical and relational
 * operators, and subset/superset relations.
 *
 */
#ifndef UC_H_SUPPLEMENTAL_MATHEMATICAL_OPERATORS
#define UC_H_SUPPLEMENTAL_MATHEMATICAL_OPERATORS

#define UC_MACRO_NAME_2A00 0x2A00 // ⨀ N-ARY CIRCLED DOT OPERATOR
#define UC_MACRO_NAME_2A01 0x2A01 // ⨁ N-ARY CIRCLED PLUS OPERATOR
#define UC_MACRO_NAME_2A02 0x2A02 // ⨂ N-ARY CIRCLED TIMES OPERATOR
#define UC_MACRO_NAME_2A03 0x2A03 // ⨃ N-ARY UNION OPERATOR WITH DOT
#define UC_MACRO_NAME_2A04 0x2A04 // ⨄ N-ARY UNION OPERATOR WITH PLUS
#define UC_MACRO_NAME_2A05 0x2A05 // ⨅ N-ARY SQUARE INTERSECTION OPERATOR
#define UC_MACRO_NAME_2A06 0x2A06 // ⨆ N-ARY SQUARE UNION OPERATOR
#define UC_MACRO_NAME_2A07 0x2A07 // ⨇ TWO LOGICAL AND OPERATOR
#define UC_MACRO_NAME_2A08 0x2A08 // ⨈ TWO LOGICAL OR OPERATOR
#define UC_MACRO_NAME_2A09 0x2A09 // ⨉ N-ARY TIMES OPERATOR
#define UC_MACRO_NAME_2A0A 0x2A0A // ⨊ MODULO TWO SUM
#define UC_MACRO_NAME_2A0B 0x2A0B // ⨋ SUMMATION WITH INTEGRAL
#define UC_MACRO_NAME_2A0C 0x2A0C // ⨌ QUADRUPLE INTEGRAL OPERATOR
#define UC_MACRO_NAME_2A0D 0x2A0D // ⨍ FINITE PART INTEGRAL
#define UC_MACRO_NAME_2A0E 0x2A0E // ⨎ INTEGRAL WITH DOUBLE STROKE
#define UC_MACRO_NAME_2A0F 0x2A0F // ⨏ INTEGRAL AVERAGE WITH SLASH
#define UC_MACRO_NAME_2A10 0x2A10 // ⨐ CIRCULATION FUNCTION
#define UC_MACRO_NAME_2A11 0x2A11 // ⨑ ANTICLOCKWISE INTEGRATION
#define UC_MACRO_NAME_2A12 0x2A12 // ⨒ LINE INTEGRATION WITH RECTANGULAR PATH AROUND POLE
#define UC_MACRO_NAME_2A13 0x2A13 // ⨓ LINE INTEGRATION WITH SEMICIRCULAR PATH AROUND POLE
#define UC_MACRO_NAME_2A14 0x2A14 // ⨔ LINE INTEGRATION NOT INCLUDING THE POLE
#define UC_MACRO_NAME_2A15 0x2A15 // ⨕ INTEGRAL AROUND A POINT OPERATOR
#define UC_MACRO_NAME_2A16 0x2A16 // ⨖ QUATERNION INTEGRAL OPERATOR
#define UC_MACRO_NAME_2A17 0x2A17 // ⨗ INTEGRAL WITH LEFTWARDS ARROW WITH HOOK
#define UC_MACRO_NAME_2A18 0x2A18 // ⨘ INTEGRAL WITH TIMES SIGN
#define UC_MACRO_NAME_2A19 0x2A19 // ⨙ INTEGRAL WITH INTERSECTION
#define UC_MACRO_NAME_2A1A 0x2A1A // ⨚ INTEGRAL WITH UNION
#define UC_MACRO_NAME_2A1B 0x2A1B // ⨛ INTEGRAL WITH OVERBAR
#define UC_MACRO_NAME_2A1C 0x2A1C // ⨜ INTEGRAL WITH UNDERBAR
#define UC_MACRO_NAME_2A1D 0x2A1D // ⨝ JOIN
#define UC_MACRO_NAME_2A1E 0x2A1E // ⨞ LARGE LEFT TRIANGLE OPERATOR
#define UC_MACRO_NAME_2A1F 0x2A1F // ⨟ Z NOTATION SCHEMA COMPOSITION
#define UC_MACRO_NAME_2A20 0x2A20 // ⨠ Z NOTATION SCHEMA PIPING
#define UC_MACRO_NAME_2A21 0x2A21 // ⨡ Z NOTATION SCHEMA PROJECTION
#define UC_MACRO_NAME_2A22 0x2A22 // ⨢ PLUS SIGN WITH SMALL CIRCLE ABOVE
#define UC_MACRO_NAME_2A23 0x2A23 // ⨣ PLUS SIGN WITH CIRCUMFLEX ACCENT ABOVE
#define UC_MACRO_NAME_2A24 0x2A24 // ⨤ PLUS SIGN WITH TILDE ABOVE
#define UC_MACRO_NAME_2A25 0x2A25 // ⨥ PLUS SIGN WITH DOT BELOW
#define UC_MACRO_NAME_2A26 0x2A26 // ⨦ PLUS SIGN WITH TILDE BELOW
#define UC_MACRO_NAME_2A27 0x2A27 // ⨧ PLUS SIGN WITH SUBSCRIPT TWO
#define UC_MACRO_NAME_2A28 0x2A28 // ⨨ PLUS SIGN WITH BLACK TRIANGLE
#define UC_MACRO_NAME_2A29 0x2A29 // ⨩ MINUS SIGN WITH COMMA ABOVE
#define UC_MACRO_NAME_2A2A 0x2A2A // ⨪ MINUS SIGN WITH DOT BELOW
#define UC_MACRO_NAME_2A2B 0x2A2B // ⨫ MINUS SIGN WITH FALLING DOTS
#define UC_MACRO_NAME_2A2C 0x2A2C // ⨬ MINUS SIGN WITH RISING DOTS
#define UC_MACRO_NAME_2A2D 0x2A2D // ⨭ PLUS SIGN IN LEFT HALF CIRCLE
#define UC_MACRO_NAME_2A2E 0x2A2E // ⨮ PLUS SIGN IN RIGHT HALF CIRCLE
#define UC_MACRO_NAME_2A2F 0x2A2F // ⨯ VECTOR OR CROSS PRODUCT
#define UC_MACRO_NAME_2A30 0x2A30 // ⨰ MULTIPLICATION SIGN WITH DOT ABOVE
#define UC_MACRO_NAME_2A31 0x2A31 // ⨱ MULTIPLICATION SIGN WITH UNDERBAR
#define UC_MACRO_NAME_2A32 0x2A32 // ⨲ SEMIDIRECT PRODUCT WITH BOTTOM CLOSED
#define UC_MACRO_NAME_2A33 0x2A33 // ⨳ SMASH PRODUCT
#define UC_MACRO_NAME_2A34 0x2A34 // ⨴ MULTIPLICATION SIGN IN LEFT HALF CIRCLE
#define UC_MACRO_NAME_2A35 0x2A35 // ⨵ MULTIPLICATION SIGN IN RIGHT HALF CIRCLE
#define UC_MACRO_NAME_2A36 0x2A36 // ⨶ CIRCLED MULTIPLICATION SIGN WITH CIRCUMFLEX ACCENT
#define UC_MACRO_NAME_2A37 0x2A37 // ⨷ MULTIPLICATION SIGN IN DOUBLE CIRCLE
#define UC_MACRO_NAME_2A38 0x2A38 // ⨸ CIRCLED DIVISION SIGN
#define UC_MACRO_NAME_2A39 0x2A39 // ⨹ PLUS SIGN IN TRIANGLE
#define UC_MACRO_NAME_2A3A 0x2A3A // ⨺ MINUS SIGN IN TRIANGLE
#define UC_MACRO_NAME_2A3B 0x2A3B // ⨻ MULTIPLICATION SIGN IN TRIANGLE
#define UC_MACRO_NAME_2A3C 0x2A3C // ⨼ INTERIOR PRODUCT
#define UC_MACRO_NAME_2A3D 0x2A3D // ⨽ RIGHTHAND INTERIOR PRODUCT
#define UC_MACRO_NAME_2A3E 0x2A3E // ⨾ Z NOTATION RELATIONAL COMPOSITION
#define UC_MACRO_NAME_2A3F 0x2A3F // ⨿ AMALGAMATION OR COPRODUCT
#define UC_MACRO_NAME_2A40 0x2A40 // ⩀ INTERSECTION WITH DOT
#define UC_MACRO_NAME_2A41 0x2A41 // ⩁ UNION WITH MINUS SIGN
#define UC_MACRO_NAME_2A42 0x2A42 // ⩂ UNION WITH OVERBAR
#define UC_MACRO_NAME_2A43 0x2A43 // ⩃ INTERSECTION WITH OVERBAR
#define UC_MACRO_NAME_2A44 0x2A44 // ⩄ INTERSECTION WITH LOGICAL AND
#define UC_MACRO_NAME_2A45 0x2A45 // ⩅ UNION WITH LOGICAL OR
#define UC_MACRO_NAME_2A46 0x2A46 // ⩆ UNION ABOVE INTERSECTION
#define UC_MACRO_NAME_2A47 0x2A47 // ⩇ INTERSECTION ABOVE UNION
#define UC_MACRO_NAME_2A48 0x2A48 // ⩈ UNION ABOVE BAR ABOVE INTERSECTION
#define UC_MACRO_NAME_2A49 0x2A49 // ⩉ INTERSECTION ABOVE BAR ABOVE UNION
#define UC_MACRO_NAME_2A4A 0x2A4A // ⩊ UNION BESIDE AND JOINED WITH UNION
#define UC_MACRO_NAME_2A4B 0x2A4B // ⩋ INTERSECTION BESIDE AND JOINED WITH INTERSECTION
#define UC_MACRO_NAME_2A4C 0x2A4C // ⩌ CLOSED UNION WITH SERIFS
#define UC_MACRO_NAME_2A4D 0x2A4D // ⩍ CLOSED INTERSECTION WITH SERIFS
#define UC_MACRO_NAME_2A4E 0x2A4E // ⩎ DOUBLE SQUARE INTERSECTION
#define UC_MACRO_NAME_2A4F 0x2A4F // ⩏ DOUBLE SQUARE UNION
#define UC_MACRO_NAME_2A50 0x2A50 // ⩐ CLOSED UNION WITH SERIFS AND SMASH PRODUCT
#define UC_MACRO_NAME_2A51 0x2A51 // ⩑ LOGICAL AND WITH DOT ABOVE
#define UC_MACRO_NAME_2A52 0x2A52 // ⩒ LOGICAL OR WITH DOT ABOVE
#define UC_MACRO_NAME_2A53 0x2A53 // ⩓ DOUBLE LOGICAL AND
#define UC_MACRO_NAME_2A54 0x2A54 // ⩔ DOUBLE LOGICAL OR
#define UC_MACRO_NAME_2A55 0x2A55 // ⩕ TWO INTERSECTING LOGICAL AND
#define UC_MACRO_NAME_2A56 0x2A56 // ⩖ TWO INTERSECTING LOGICAL OR
#define UC_MACRO_NAME_2A57 0x2A57 // ⩗ SLOPING LARGE OR
#define UC_MACRO_NAME_2A58 0x2A58 // ⩘ SLOPING LARGE AND
#define UC_MACRO_NAME_2A59 0x2A59 // ⩙ LOGICAL OR OVERLAPPING LOGICAL AND
#define UC_MACRO_NAME_2A5A 0x2A5A // ⩚ LOGICAL AND WITH MIDDLE STEM
#define UC_MACRO_NAME_2A5B 0x2A5B // ⩛ LOGICAL OR WITH MIDDLE STEM
#define UC_MACRO_NAME_2A5C 0x2A5C // ⩜ LOGICAL AND WITH HORIZONTAL DASH
#define UC_MACRO_NAME_2A5D 0x2A5D // ⩝ LOGICAL OR WITH HORIZONTAL DASH
#define UC_MACRO_NAME_2A5E 0x2A5E // ⩞ LOGICAL AND WITH DOUBLE OVERBAR
#define UC_MACRO_NAME_2A5F 0x2A5F // ⩟ LOGICAL AND WITH UNDERBAR
#define UC_MACRO_NAME_2A60 0x2A60 // ⩠ LOGICAL AND WITH DOUBLE UNDERBAR
#define UC_MACRO_NAME_2A61 0x2A61 // ⩡ SMALL VEE WITH UNDERBAR
#define UC_MACRO_NAME_2A62 0x2A62 // ⩢ LOGICAL OR WITH DOUBLE OVERBAR
#define UC_MACRO_NAME_2A63 0x2A63 // ⩣ LOGICAL OR WITH DOUBLE UNDERBAR
#define UC_MACRO_NAME_2A64 0x2A64 // ⩤ Z NOTATION DOMAIN ANTIRESTRICTION
#define UC_MACRO_NAME_2A65 0x2A65 // ⩥ Z NOTATION RANGE ANTIRESTRICTION
#define UC_MACRO_NAME_2A66 0x2A66 // ⩦ EQUALS SIGN WITH DOT BELOW
#define UC_MACRO_NAME_2A67 0x2A67 // ⩧ IDENTICAL WITH DOT ABOVE
#define UC_MACRO_NAME_2A68 0x2A68 // ⩨ TRIPLE HORIZONTAL BAR WITH DOUBLE VERTICAL STROKE
#define UC_MACRO_NAME_2A69 0x2A69 // ⩩ TRIPLE HORIZONTAL BAR WITH TRIPLE VERTICAL STROKE
#define UC_MACRO_NAME_2A6A 0x2A6A // ⩪ TILDE OPERATOR WITH DOT ABOVE
#define UC_MACRO_NAME_2A6B 0x2A6B // ⩫ TILDE OPERATOR WITH RISING DOTS
#define UC_MACRO_NAME_2A6C 0x2A6C // ⩬ SIMILAR MINUS SIMILAR
#define UC_MACRO_NAME_2A6D 0x2A6D // ⩭ CONGRUENT WITH DOT ABOVE
#define UC_MACRO_NAME_2A6E 0x2A6E // ⩮ EQUALS WITH ASTERISK
#define UC_MACRO_NAME_2A6F 0x2A6F // ⩯ ALMOST EQUAL TO WITH CIRCUMFLEX ACCENT
#define UC_MACRO_NAME_2A70 0x2A70 // ⩰ APPROXIMATELY EQUAL OR EQUAL TO
#define UC_MACRO_NAME_2A71 0x2A71 // ⩱ EQUALS SIGN ABOVE PLUS SIGN
#define UC_MACRO_NAME_2A72 0x2A72 // ⩲ PLUS SIGN ABOVE EQUALS SIGN
#define UC_MACRO_NAME_2A73 0x2A73 // ⩳ EQUALS SIGN ABOVE TILDE OPERATOR
#define UC_MACRO_NAME_2A74 0x2A74 // ⩴ DOUBLE COLON EQUAL
#define UC_MACRO_NAME_2A75 0x2A75 // ⩵ TWO CONSECUTIVE EQUALS SIGNS
#define UC_MACRO_NAME_2A76 0x2A76 // ⩶ THREE CONSECUTIVE EQUALS SIGNS
#define UC_MACRO_NAME_2A77 0x2A77 // ⩷ EQUALS SIGN WITH TWO DOTS ABOVE AND TWO DOTS BELOW
#define UC_MACRO_NAME_2A78 0x2A78 // ⩸ EQUIVALENT WITH FOUR DOTS ABOVE
#define UC_MACRO_NAME_2A79 0x2A79 // ⩹ LESS-THAN WITH CIRCLE INSIDE
#define UC_MACRO_NAME_2A7A 0x2A7A // ⩺ GREATER-THAN WITH CIRCLE INSIDE
#define UC_MACRO_NAME_2A7B 0x2A7B // ⩻ LESS-THAN WITH QUESTION MARK ABOVE
#define UC_MACRO_NAME_2A7C 0x2A7C // ⩼ GREATER-THAN WITH QUESTION MARK ABOVE
#define UC_MACRO_NAME_2A7D 0x2A7D // ⩽ LESS-THAN OR SLANTED EQUAL TO
#define UC_MACRO_NAME_2A7E 0x2A7E // ⩾ GREATER-THAN OR SLANTED EQUAL TO
#define UC_MACRO_NAME_2A7F 0x2A7F // ⩿ LESS-THAN OR SLANTED EQUAL TO WITH DOT INSIDE
#define UC_MACRO_NAME_2A80 0x2A80 // ⪀ GREATER-THAN OR SLANTED EQUAL TO WITH DOT INSIDE
#define UC_MACRO_NAME_2A81 0x2A81 // ⪁ LESS-THAN OR SLANTED EQUAL TO WITH DOT ABOVE
#define UC_MACRO_NAME_2A82 0x2A82 // ⪂ GREATER-THAN OR SLANTED EQUAL TO WITH DOT ABOVE
#define UC_MACRO_NAME_2A83 0x2A83 // ⪃ LESS-THAN OR SLANTED EQUAL TO WITH DOT ABOVE RIGHT
#define UC_MACRO_NAME_2A84 0x2A84 // ⪄ GREATER-THAN OR SLANTED EQUAL TO WITH DOT ABOVE LEFT
#define UC_MACRO_NAME_2A85 0x2A85 // ⪅ LESS-THAN OR APPROXIMATE
#define UC_MACRO_NAME_2A86 0x2A86 // ⪆ GREATER-THAN OR APPROXIMATE
#define UC_MACRO_NAME_2A87 0x2A87 // ⪇ LESS-THAN AND SINGLE-LINE NOT EQUAL TO
#define UC_MACRO_NAME_2A88 0x2A88 // ⪈ GREATER-THAN AND SINGLE-LINE NOT EQUAL TO
#define UC_MACRO_NAME_2A89 0x2A89 // ⪉ LESS-THAN AND NOT APPROXIMATE
#define UC_MACRO_NAME_2A8A 0x2A8A // ⪊ GREATER-THAN AND NOT APPROXIMATE
#define UC_MACRO_NAME_2A8B 0x2A8B // ⪋ LESS-THAN ABOVE DOUBLE-LINE EQUAL ABOVE GREATER-THAN
#define UC_MACRO_NAME_2A8C 0x2A8C // ⪌ GREATER-THAN ABOVE DOUBLE-LINE EQUAL ABOVE LESS-THAN
#define UC_MACRO_NAME_2A8D 0x2A8D // ⪍ LESS-THAN ABOVE SIMILAR OR EQUAL
#define UC_MACRO_NAME_2A8E 0x2A8E // ⪎ GREATER-THAN ABOVE SIMILAR OR EQUAL
#define UC_MACRO_NAME_2A8F 0x2A8F // ⪏ LESS-THAN ABOVE SIMILAR ABOVE GREATER-THAN
#define UC_MACRO_NAME_2A90 0x2A90 // ⪐ GREATER-THAN ABOVE SIMILAR ABOVE LESS-THAN
#define UC_MACRO_NAME_2A91 0x2A91 // ⪑ LESS-THAN ABOVE GREATER-THAN ABOVE DOUBLE-LINE EQUAL
#define UC_MACRO_NAME_2A92 0x2A92 // ⪒ GREATER-THAN ABOVE LESS-THAN ABOVE DOUBLE-LINE EQUAL
#define UC_MACRO_NAME_2A93 0x2A93 // ⪓ LESS-THAN ABOVE SLANTED EQUAL ABOVE GREATER-THAN ABOVE SLANTED EQUAL
#define UC_MACRO_NAME_2A94 0x2A94 // ⪔ GREATER-THAN ABOVE SLANTED EQUAL ABOVE LESS-THAN ABOVE SLANTED EQUAL
#define UC_MACRO_NAME_2A95 0x2A95 // ⪕ SLANTED EQUAL TO OR LESS-THAN
#define UC_MACRO_NAME_2A96 0x2A96 // ⪖ SLANTED EQUAL TO OR GREATER-THAN
#define UC_MACRO_NAME_2A97 0x2A97 // ⪗ SLANTED EQUAL TO OR LESS-THAN WITH DOT INSIDE
#define UC_MACRO_NAME_2A98 0x2A98 // ⪘ SLANTED EQUAL TO OR GREATER-THAN WITH DOT INSIDE
#define UC_MACRO_NAME_2A99 0x2A99 // ⪙ DOUBLE-LINE EQUAL TO OR LESS-THAN
#define UC_MACRO_NAME_2A9A 0x2A9A // ⪚ DOUBLE-LINE EQUAL TO OR GREATER-THAN
#define UC_MACRO_NAME_2A9B 0x2A9B // ⪛ DOUBLE-LINE SLANTED EQUAL TO OR LESS-THAN
#define UC_MACRO_NAME_2A9C 0x2A9C // ⪜ DOUBLE-LINE SLANTED EQUAL TO OR GREATER-THAN
#define UC_MACRO_NAME_2A9D 0x2A9D // ⪝ SIMILAR OR LESS-THAN
#define UC_MACRO_NAME_2A9E 0x2A9E // ⪞ SIMILAR OR GREATER-THAN
#define UC_MACRO_NAME_2A9F 0x2A9F // ⪟ SIMILAR ABOVE LESS-THAN ABOVE EQUALS SIGN
#define UC_MACRO_NAME_2AA0 0x2AA0 // ⪠ SIMILAR ABOVE GREATER-THAN ABOVE EQUALS SIGN
#define UC_MACRO_NAME_2AA1 0x2AA1 // ⪡ DOUBLE NESTED LESS-THAN
#define UC_MACRO_NAME_2AA2 0x2AA2 // ⪢ DOUBLE NESTED GREATER-THAN
#define UC_MACRO_NAME_2AA3 0x2AA3 // ⪣ DOUBLE NESTED LESS-THAN WITH UNDERBAR
#define UC_MACRO_NAME_2AA4 0x2AA4 // ⪤ GREATER-THAN OVERLAPPING LESS-THAN
#define UC_MACRO_NAME_2AA5 0x2AA5 // ⪥ GREATER-THAN BESIDE LESS-THAN
#define UC_MACRO_NAME_2AA6 0x2AA6 // ⪦ LESS-THAN CLOSED BY CURVE
#define UC_MACRO_NAME_2AA7 0x2AA7 // ⪧ GREATER-THAN CLOSED BY CURVE
#define UC_MACRO_NAME_2AA8 0x2AA8 // ⪨ LESS-THAN CLOSED BY CURVE ABOVE SLANTED EQUAL
#define UC_MACRO_NAME_2AA9 0x2AA9 // ⪩ GREATER-THAN CLOSED BY CURVE ABOVE SLANTED EQUAL
#define UC_MACRO_NAME_2AAA 0x2AAA // ⪪ SMALLER THAN
#define UC_MACRO_NAME_2AAB 0x2AAB // ⪫ LARGER THAN
#define UC_MACRO_NAME_2AAC 0x2AAC // ⪬ SMALLER THAN OR EQUAL TO
#define UC_MACRO_NAME_2AAD 0x2AAD // ⪭ LARGER THAN OR EQUAL TO
#define UC_MACRO_NAME_2AAE 0x2AAE // ⪮ EQUALS SIGN WITH BUMPY ABOVE
#define UC_MACRO_NAME_2AAF 0x2AAF // ⪯ PRECEDES ABOVE SINGLE-LINE EQUALS SIGN
#define UC_MACRO_NAME_2AB0 0x2AB0 // ⪰ SUCCEEDS ABOVE SINGLE-LINE EQUALS SIGN
#define UC_MACRO_NAME_2AB1 0x2AB1 // ⪱ PRECEDES ABOVE SINGLE-LINE NOT EQUAL TO
#define UC_MACRO_NAME_2AB2 0x2AB2 // ⪲ SUCCEEDS ABOVE SINGLE-LINE NOT EQUAL TO
#define UC_MACRO_NAME_2AB3 0x2AB3 // ⪳ PRECEDES ABOVE EQUALS SIGN
#define UC_MACRO_NAME_2AB4 0x2AB4 // ⪴ SUCCEEDS ABOVE EQUALS SIGN
#define UC_MACRO_NAME_2AB5 0x2AB5 // ⪵ PRECEDES ABOVE NOT EQUAL TO
#define UC_MACRO_NAME_2AB6 0x2AB6 // ⪶ SUCCEEDS ABOVE NOT EQUAL TO
#define UC_MACRO_NAME_2AB7 0x2AB7 // ⪷ PRECEDES ABOVE ALMOST EQUAL TO
#define UC_MACRO_NAME_2AB8 0x2AB8 // ⪸ SUCCEEDS ABOVE ALMOST EQUAL TO
#define UC_MACRO_NAME_2AB9 0x2AB9 // ⪹ PRECEDES ABOVE NOT ALMOST EQUAL TO
#define UC_MACRO_NAME_2ABA 0x2ABA // ⪺ SUCCEEDS ABOVE NOT ALMOST EQUAL TO
#define UC_MACRO_NAME_2ABB 0x2ABB // ⪻ DOUBLE PRECEDES
#define UC_MACRO_NAME_2ABC 0x2ABC // ⪼ DOUBLE SUCCEEDS
#define UC_MACRO_NAME_2ABD 0x2ABD // ⪽ SUBSET WITH DOT
#define UC_MACRO_NAME_2ABE 0x2ABE // ⪾ SUPERSET WITH DOT
#define UC_MACRO_NAME_2ABF 0x2ABF // ⪿ SUBSET WITH PLUS SIGN BELOW
#define UC_MACRO_NAME_2AC0 0x2AC0 // ⫀ SUPERSET WITH PLUS SIGN BELOW
#define UC_MACRO_NAME_2AC1 0x2AC1 // ⫁ SUBSET WITH MULTIPLICATION SIGN BELOW
#define UC_MACRO_NAME_2AC2 0x2AC2 // ⫂ SUPERSET WITH MULTIPLICATION SIGN BELOW
#define UC_MACRO_NAME_2AC3 0x2AC3 // ⫃ SUBSET OF OR EQUAL TO WITH DOT ABOVE
#define UC_MACRO_NAME_2AC4 0x2AC4 // ⫄ SUPERSET OF OR EQUAL TO WITH DOT ABOVE
#define UC_MACRO_NAME_2AC5 0x2AC5 // ⫅ SUBSET OF ABOVE EQUALS SIGN
#define UC_MACRO_NAME_2AC6 0x2AC6 // ⫆ SUPERSET OF ABOVE EQUALS SIGN
#define UC_MACRO_NAME_2AC7 0x2AC7 // ⫇ SUBSET OF ABOVE TILDE OPERATOR
#define UC_MACRO_NAME_2AC8 0x2AC8 // ⫈ SUPERSET OF ABOVE TILDE OPERATOR
#define UC_MACRO_NAME_2AC9 0x2AC9 // ⫉ SUBSET OF ABOVE ALMOST EQUAL TO
#define UC_MACRO_NAME_2ACA 0x2ACA // ⫊ SUPERSET OF ABOVE ALMOST EQUAL TO
#define UC_MACRO_NAME_2ACB 0x2ACB // ⫋ SUBSET OF ABOVE NOT EQUAL TO
#define UC_MACRO_NAME_2ACC 0x2ACC // ⫌ SUPERSET OF ABOVE NOT EQUAL TO
#define UC_MACRO_NAME_2ACD 0x2ACD // ⫍ SQUARE LEFT OPEN BOX OPERATOR
#define UC_MACRO_NAME_2ACE 0x2ACE // ⫎ SQUARE RIGHT OPEN BOX OPERATOR
#define UC_MACRO_NAME_2ACF 0x2ACF // ⫏ CLOSED SUBSET
#define UC_MACRO_NAME_2AD0 0x2AD0 // ⫐ CLOSED SUPERSET
#define UC_MACRO_NAME_2AD1 0x2AD1 // ⫑ CLOSED SUBSET OR EQUAL TO
#define UC_MACRO_NAME_2AD2 0x2AD2 // ⫒ CLOSED SUPERSET OR EQUAL TO
#define UC_MACRO_NAME_2AD3 0x2AD3 // ⫓ SUBSET ABOVE SUPERSET
#define UC_MACRO_NAME_2AD4 0x2AD4 // ⫔ SUPERSET ABOVE SUBSET
#define UC_MACRO_NAME_2AD5 0x2AD5 // ⫕ SUBSET ABOVE SUBSET
#define UC_MACRO_NAME_2AD6 0x2AD6 // ⫖ SUPERSET ABOVE SUPERSET
#define UC_MACRO_NAME_2AD7 0x2AD7 // ⫗ SUPERSET BESIDE SUBSET
#define UC_MACRO_NAME_2AD8 0x2AD8 // ⫘ SUPERSET BESIDE AND JOINED BY DASH WITH SUBSET
#define UC_MACRO_NAME_2AD9 0x2AD9 // ⫙ ELEMENT OF OPENING DOWNWARDS
#define UC_MACRO_NAME_2ADA 0x2ADA // ⫚ PITCHFORK WITH TEE TOP
#define UC_MACRO_NAME_2ADB 0x2ADB // ⫛ TRANSVERSAL INTERSECTION
#define UC_MACRO_NAME_2ADC 0x2ADC // ⫝̸ FORKING
#define UC_MACRO_NAME_2ADD 0x2ADD // ⫝ NONFORKING
#define UC_MACRO_NAME_2ADE 0x2ADE // ⫞ SHORT LEFT TACK
#define UC_MACRO_NAME_2ADF 0x2ADF // ⫟ SHORT DOWN TACK
#define UC_MACRO_NAME_2AE0 0x2AE0 // ⫠ SHORT UP TACK
#define UC_MACRO_NAME_2AE1 0x2AE1 // ⫡ PERPENDICULAR WITH S
#define UC_MACRO_NAME_2AE2 0x2AE2 // ⫢ VERTICAL BAR TRIPLE RIGHT TURNSTILE
#define UC_MACRO_NAME_2AE3 0x2AE3 // ⫣ DOUBLE VERTICAL BAR LEFT TURNSTILE
#define UC_MACRO_NAME_2AE4 0x2AE4 // ⫤ VERTICAL BAR DOUBLE LEFT TURNSTILE
#define UC_MACRO_NAME_2AE5 0x2AE5 // ⫥ DOUBLE VERTICAL BAR DOUBLE LEFT TURNSTILE
#define UC_MACRO_NAME_2AE6 0x2AE6 // ⫦ LONG DASH FROM LEFT MEMBER OF DOUBLE VERTICAL
#define UC_MACRO_NAME_2AE7 0x2AE7 // ⫧ SHORT DOWN TACK WITH OVERBAR
#define UC_MACRO_NAME_2AE8 0x2AE8 // ⫨ SHORT UP TACK WITH UNDERBAR
#define UC_MACRO_NAME_2AE9 0x2AE9 // ⫩ SHORT UP TACK ABOVE SHORT DOWN TACK
#define UC_MACRO_NAME_2AEA 0x2AEA // ⫪ DOUBLE DOWN TACK
#define UC_MACRO_NAME_2AEB 0x2AEB // ⫫ DOUBLE UP TACK
#define UC_MACRO_NAME_2AEC 0x2AEC // ⫬ DOUBLE STROKE NOT SIGN
#define UC_MACRO_NAME_2AED 0x2AED // ⫭ REVERSED DOUBLE STROKE NOT SIGN
#define UC_MACRO_NAME_2AEE 0x2AEE // ⫮ DOES NOT DIVIDE WITH REVERSED NEGATION SLASH
#define UC_MACRO_NAME_2AEF 0x2AEF // ⫯ VERTICAL LINE WITH CIRCLE ABOVE
#define UC_MACRO_NAME_2AF0 0x2AF0 // ⫰ VERTICAL LINE WITH CIRCLE BELOW
#define UC_MACRO_NAME_2AF1 0x2AF1 // ⫱ DOWN TACK WITH CIRCLE BELOW
#define UC_MACRO_NAME_2AF2 0x2AF2 // ⫲ PARALLEL WITH HORIZONTAL STROKE
#define UC_MACRO_NAME_2AF3 0x2AF3 // ⫳ PARALLEL WITH TILDE OPERATOR
#define UC_MACRO_NAME_2AF4 0x2AF4 // ⫴ TRIPLE VERTICAL BAR BINARY RELATION
#define UC_MACRO_NAME_2AF5 0x2AF5 // ⫵ TRIPLE VERTICAL BAR WITH HORIZONTAL STROKE
#define UC_MACRO_NAME_2AF6 0x2AF6 // ⫶ TRIPLE COLON OPERATOR
#define UC_MACRO_NAME_2AF7 0x2AF7 // ⫷ TRIPLE NESTED LESS-THAN
#define UC_MACRO_NAME_2AF8 0x2AF8 // ⫸ TRIPLE NESTED GREATER-THAN
#define UC_MACRO_NAME_2AF9 0x2AF9 // ⫹ DOUBLE-LINE SLANTED LESS-THAN OR EQUAL TO
#define UC_MACRO_NAME_2AFA 0x2AFA // ⫺ DOUBLE-LINE SLANTED GREATER-THAN OR EQUAL TO
#define UC_MACRO_NAME_2AFB 0x2AFB // ⫻ TRIPLE SOLIDUS BINARY RELATION
#define UC_MACRO_NAME_2AFC 0x2AFC // ⫼ LARGE TRIPLE VERTICAL BAR OPERATOR
#define UC_MACRO_NAME_2AFD 0x2AFD // ⫽ DOUBLE SOLIDUS OPERATOR
#define UC_MACRO_NAME_2AFE 0x2AFE // ⫾ WHITE VERTICAL BAR
#define UC_MACRO_NAME_2AFF 0x2AFF // ⫿ N-ARY WHITE VERTICAL BAR


#endif // UC_H_SUPPLEMENTAL_MATHEMATICAL_OPERATORS
