/*
 * Unicode Block: Sutton SignWriting
 * Range: U+1D800..U+1DAAF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Sutton SignWriting , or simply SignWriting, is a writing system for
 * sign languages . It can be used to write any sign language, including
 * American Sign Language , Brazilian Sign Language , Tunisian Sign
 * Language , and many others.
 * SignWriting is the only international writing system for sign
 * languages. It has been used to publish young adult fiction, translate
 * the Bible, caption YouTube videos, and study sign language literacy.
 *
 */
#ifndef UC_H_SUTTON_SIGNWRITING
#define UC_H_SUTTON_SIGNWRITING

#define UC_MACRO_NAME_1D800 0x1D800 // 𝠀 SIGNWRITING HAND-FIST INDEX
#define UC_MACRO_NAME_1D801 0x1D801 // 𝠁 SIGNWRITING HAND-CIRCLE INDEX
#define UC_MACRO_NAME_1D802 0x1D802 // 𝠂 SIGNWRITING HAND-CUP INDEX
#define UC_MACRO_NAME_1D803 0x1D803 // 𝠃 SIGNWRITING HAND-OVAL INDEX
#define UC_MACRO_NAME_1D804 0x1D804 // 𝠄 SIGNWRITING HAND-HINGE INDEX
#define UC_MACRO_NAME_1D805 0x1D805 // 𝠅 SIGNWRITING HAND-ANGLE INDEX
#define UC_MACRO_NAME_1D806 0x1D806 // 𝠆 SIGNWRITING HAND-FIST INDEX BENT
#define UC_MACRO_NAME_1D807 0x1D807 // 𝠇 SIGNWRITING HAND-CIRCLE INDEX BENT
#define UC_MACRO_NAME_1D808 0x1D808 // 𝠈 SIGNWRITING HAND-FIST THUMB UNDER INDEX BENT
#define UC_MACRO_NAME_1D809 0x1D809 // 𝠉 SIGNWRITING HAND-FIST INDEX RAISED KNUCKLE
#define UC_MACRO_NAME_1D80A 0x1D80A // 𝠊 SIGNWRITING HAND-FIST INDEX CUPPED
#define UC_MACRO_NAME_1D80B 0x1D80B // 𝠋 SIGNWRITING HAND-FIST INDEX HINGED
#define UC_MACRO_NAME_1D80C 0x1D80C // 𝠌 SIGNWRITING HAND-FIST INDEX HINGED LOW
#define UC_MACRO_NAME_1D80D 0x1D80D // 𝠍 SIGNWRITING HAND-CIRCLE INDEX HINGE
#define UC_MACRO_NAME_1D80E 0x1D80E // 𝠎 SIGNWRITING HAND-FIST INDEX MIDDLE
#define UC_MACRO_NAME_1D80F 0x1D80F // 𝠏 SIGNWRITING HAND-CIRCLE INDEX MIDDLE
#define UC_MACRO_NAME_1D810 0x1D810 // 𝠐 SIGNWRITING HAND-FIST INDEX MIDDLE BENT
#define UC_MACRO_NAME_1D811 0x1D811 // 𝠑 SIGNWRITING HAND-FIST INDEX MIDDLE RAISED KNUCKLES
#define UC_MACRO_NAME_1D812 0x1D812 // 𝠒 SIGNWRITING HAND-FIST INDEX MIDDLE HINGED
#define UC_MACRO_NAME_1D813 0x1D813 // 𝠓 SIGNWRITING HAND-FIST INDEX UP MIDDLE HINGED
#define UC_MACRO_NAME_1D814 0x1D814 // 𝠔 SIGNWRITING HAND-FIST INDEX HINGED MIDDLE UP
#define UC_MACRO_NAME_1D815 0x1D815 // 𝠕 SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED
#define UC_MACRO_NAME_1D816 0x1D816 // 𝠖 SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED INDEX BENT
#define UC_MACRO_NAME_1D817 0x1D817 // 𝠗 SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED MIDDLE BENT
#define UC_MACRO_NAME_1D818 0x1D818 // 𝠘 SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED CUPPED
#define UC_MACRO_NAME_1D819 0x1D819 // 𝠙 SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED HINGED
#define UC_MACRO_NAME_1D81A 0x1D81A // 𝠚 SIGNWRITING HAND-FIST INDEX MIDDLE CROSSED
#define UC_MACRO_NAME_1D81B 0x1D81B // 𝠛 SIGNWRITING HAND-CIRCLE INDEX MIDDLE CROSSED
#define UC_MACRO_NAME_1D81C 0x1D81C // 𝠜 SIGNWRITING HAND-FIST MIDDLE BENT OVER INDEX
#define UC_MACRO_NAME_1D81D 0x1D81D // 𝠝 SIGNWRITING HAND-FIST INDEX BENT OVER MIDDLE
#define UC_MACRO_NAME_1D81E 0x1D81E // 𝠞 SIGNWRITING HAND-FIST INDEX MIDDLE THUMB
#define UC_MACRO_NAME_1D81F 0x1D81F // 𝠟 SIGNWRITING HAND-CIRCLE INDEX MIDDLE THUMB
#define UC_MACRO_NAME_1D820 0x1D820 // 𝠠 SIGNWRITING HAND-FIST INDEX MIDDLE STRAIGHT THUMB BENT
#define UC_MACRO_NAME_1D821 0x1D821 // 𝠡 SIGNWRITING HAND-FIST INDEX MIDDLE BENT THUMB STRAIGHT
#define UC_MACRO_NAME_1D822 0x1D822 // 𝠢 SIGNWRITING HAND-FIST INDEX MIDDLE THUMB BENT
#define UC_MACRO_NAME_1D823 0x1D823 // 𝠣 SIGNWRITING HAND-FIST INDEX MIDDLE HINGED SPREAD THUMB SIDE
#define UC_MACRO_NAME_1D824 0x1D824 // 𝠤 SIGNWRITING HAND-FIST INDEX UP MIDDLE HINGED THUMB SIDE
#define UC_MACRO_NAME_1D825 0x1D825 // 𝠥 SIGNWRITING HAND-FIST INDEX UP MIDDLE HINGED THUMB CONJOINED
#define UC_MACRO_NAME_1D826 0x1D826 // 𝠦 SIGNWRITING HAND-FIST INDEX HINGED MIDDLE UP THUMB SIDE
#define UC_MACRO_NAME_1D827 0x1D827 // 𝠧 SIGNWRITING HAND-FIST INDEX MIDDLE UP SPREAD THUMB FORWARD
#define UC_MACRO_NAME_1D828 0x1D828 // 𝠨 SIGNWRITING HAND-FIST INDEX MIDDLE THUMB CUPPED
#define UC_MACRO_NAME_1D829 0x1D829 // 𝠩 SIGNWRITING HAND-FIST INDEX MIDDLE THUMB CIRCLED
#define UC_MACRO_NAME_1D82A 0x1D82A // 𝠪 SIGNWRITING HAND-FIST INDEX MIDDLE THUMB HOOKED
#define UC_MACRO_NAME_1D82B 0x1D82B // 𝠫 SIGNWRITING HAND-FIST INDEX MIDDLE THUMB HINGED
#define UC_MACRO_NAME_1D82C 0x1D82C // 𝠬 SIGNWRITING HAND-FIST THUMB BETWEEN INDEX MIDDLE STRAIGHT
#define UC_MACRO_NAME_1D82D 0x1D82D // 𝠭 SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED THUMB SIDE
#define UC_MACRO_NAME_1D82E 0x1D82E // 𝠮 SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED THUMB SIDE CONJOINED
#define UC_MACRO_NAME_1D82F 0x1D82F // 𝠯 SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED THUMB SIDE BENT
#define UC_MACRO_NAME_1D830 0x1D830 // 𝠰 SIGNWRITING HAND-FIST MIDDLE THUMB HOOKED INDEX UP
#define UC_MACRO_NAME_1D831 0x1D831 // 𝠱 SIGNWRITING HAND-FIST INDEX THUMB HOOKED MIDDLE UP
#define UC_MACRO_NAME_1D832 0x1D832 // 𝠲 SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED HINGED THUMB SIDE
#define UC_MACRO_NAME_1D833 0x1D833 // 𝠳 SIGNWRITING HAND-FIST INDEX MIDDLE CROSSED THUMB SIDE
#define UC_MACRO_NAME_1D834 0x1D834 // 𝠴 SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED THUMB FORWARD
#define UC_MACRO_NAME_1D835 0x1D835 // 𝠵 SIGNWRITING HAND-FIST INDEX MIDDLE CONJOINED CUPPED THUMB FORWARD
#define UC_MACRO_NAME_1D836 0x1D836 // 𝠶 SIGNWRITING HAND-FIST MIDDLE THUMB CUPPED INDEX UP
#define UC_MACRO_NAME_1D837 0x1D837 // 𝠷 SIGNWRITING HAND-FIST INDEX THUMB CUPPED MIDDLE UP
#define UC_MACRO_NAME_1D838 0x1D838 // 𝠸 SIGNWRITING HAND-FIST MIDDLE THUMB CIRCLED INDEX UP
#define UC_MACRO_NAME_1D839 0x1D839 // 𝠹 SIGNWRITING HAND-FIST MIDDLE THUMB CIRCLED INDEX HINGED
#define UC_MACRO_NAME_1D83A 0x1D83A // 𝠺 SIGNWRITING HAND-FIST INDEX THUMB ANGLED OUT MIDDLE UP
#define UC_MACRO_NAME_1D83B 0x1D83B // 𝠻 SIGNWRITING HAND-FIST INDEX THUMB ANGLED IN MIDDLE UP
#define UC_MACRO_NAME_1D83C 0x1D83C // 𝠼 SIGNWRITING HAND-FIST INDEX THUMB CIRCLED MIDDLE UP
#define UC_MACRO_NAME_1D83D 0x1D83D // 𝠽 SIGNWRITING HAND-FIST INDEX MIDDLE THUMB CONJOINED HINGED
#define UC_MACRO_NAME_1D83E 0x1D83E // 𝠾 SIGNWRITING HAND-FIST INDEX MIDDLE THUMB ANGLED OUT
#define UC_MACRO_NAME_1D83F 0x1D83F // 𝠿 SIGNWRITING HAND-FIST INDEX MIDDLE THUMB ANGLED
#define UC_MACRO_NAME_1D840 0x1D840 // 𝡀 SIGNWRITING HAND-FIST MIDDLE THUMB ANGLED OUT INDEX UP
#define UC_MACRO_NAME_1D841 0x1D841 // 𝡁 SIGNWRITING HAND-FIST MIDDLE THUMB ANGLED OUT INDEX CROSSED
#define UC_MACRO_NAME_1D842 0x1D842 // 𝡂 SIGNWRITING HAND-FIST MIDDLE THUMB ANGLED INDEX UP
#define UC_MACRO_NAME_1D843 0x1D843 // 𝡃 SIGNWRITING HAND-FIST INDEX THUMB HOOKED MIDDLE HINGED
#define UC_MACRO_NAME_1D844 0x1D844 // 𝡄 SIGNWRITING HAND-FLAT FOUR FINGERS
#define UC_MACRO_NAME_1D845 0x1D845 // 𝡅 SIGNWRITING HAND-FLAT FOUR FINGERS BENT
#define UC_MACRO_NAME_1D846 0x1D846 // 𝡆 SIGNWRITING HAND-FLAT FOUR FINGERS HINGED
#define UC_MACRO_NAME_1D847 0x1D847 // 𝡇 SIGNWRITING HAND-FLAT FOUR FINGERS CONJOINED
#define UC_MACRO_NAME_1D848 0x1D848 // 𝡈 SIGNWRITING HAND-FLAT FOUR FINGERS CONJOINED SPLIT
#define UC_MACRO_NAME_1D849 0x1D849 // 𝡉 SIGNWRITING HAND-CLAW FOUR FINGERS CONJOINED
#define UC_MACRO_NAME_1D84A 0x1D84A // 𝡊 SIGNWRITING HAND-FIST FOUR FINGERS CONJOINED BENT
#define UC_MACRO_NAME_1D84B 0x1D84B // 𝡋 SIGNWRITING HAND-HINGE FOUR FINGERS CONJOINED
#define UC_MACRO_NAME_1D84C 0x1D84C // 𝡌 SIGNWRITING HAND-FLAT FIVE FINGERS SPREAD
#define UC_MACRO_NAME_1D84D 0x1D84D // 𝡍 SIGNWRITING HAND-FLAT HEEL FIVE FINGERS SPREAD
#define UC_MACRO_NAME_1D84E 0x1D84E // 𝡎 SIGNWRITING HAND-FLAT FIVE FINGERS SPREAD FOUR BENT
#define UC_MACRO_NAME_1D84F 0x1D84F // 𝡏 SIGNWRITING HAND-FLAT HEEL FIVE FINGERS SPREAD FOUR BENT
#define UC_MACRO_NAME_1D850 0x1D850 // 𝡐 SIGNWRITING HAND-FLAT FIVE FINGERS SPREAD BENT
#define UC_MACRO_NAME_1D851 0x1D851 // 𝡑 SIGNWRITING HAND-FLAT HEEL FIVE FINGERS SPREAD BENT
#define UC_MACRO_NAME_1D852 0x1D852 // 𝡒 SIGNWRITING HAND-FLAT FIVE FINGERS SPREAD THUMB FORWARD
#define UC_MACRO_NAME_1D853 0x1D853 // 𝡓 SIGNWRITING HAND-CUP FIVE FINGERS SPREAD
#define UC_MACRO_NAME_1D854 0x1D854 // 𝡔 SIGNWRITING HAND-CUP FIVE FINGERS SPREAD OPEN
#define UC_MACRO_NAME_1D855 0x1D855 // 𝡕 SIGNWRITING HAND-HINGE FIVE FINGERS SPREAD OPEN
#define UC_MACRO_NAME_1D856 0x1D856 // 𝡖 SIGNWRITING HAND-OVAL FIVE FINGERS SPREAD
#define UC_MACRO_NAME_1D857 0x1D857 // 𝡗 SIGNWRITING HAND-FLAT FIVE FINGERS SPREAD HINGED
#define UC_MACRO_NAME_1D858 0x1D858 // 𝡘 SIGNWRITING HAND-FLAT FIVE FINGERS SPREAD HINGED THUMB SIDE
#define UC_MACRO_NAME_1D859 0x1D859 // 𝡙 SIGNWRITING HAND-FLAT FIVE FINGERS SPREAD HINGED NO THUMB
#define UC_MACRO_NAME_1D85A 0x1D85A // 𝡚 SIGNWRITING HAND-FLAT
#define UC_MACRO_NAME_1D85B 0x1D85B // 𝡛 SIGNWRITING HAND-FLAT BETWEEN PALM FACINGS
#define UC_MACRO_NAME_1D85C 0x1D85C // 𝡜 SIGNWRITING HAND-FLAT HEEL
#define UC_MACRO_NAME_1D85D 0x1D85D // 𝡝 SIGNWRITING HAND-FLAT THUMB SIDE
#define UC_MACRO_NAME_1D85E 0x1D85E // 𝡞 SIGNWRITING HAND-FLAT HEEL THUMB SIDE
#define UC_MACRO_NAME_1D85F 0x1D85F // 𝡟 SIGNWRITING HAND-FLAT THUMB BENT
#define UC_MACRO_NAME_1D860 0x1D860 // 𝡠 SIGNWRITING HAND-FLAT THUMB FORWARD
#define UC_MACRO_NAME_1D861 0x1D861 // 𝡡 SIGNWRITING HAND-FLAT SPLIT INDEX THUMB SIDE
#define UC_MACRO_NAME_1D862 0x1D862 // 𝡢 SIGNWRITING HAND-FLAT SPLIT CENTRE
#define UC_MACRO_NAME_1D863 0x1D863 // 𝡣 SIGNWRITING HAND-FLAT SPLIT CENTRE THUMB SIDE
#define UC_MACRO_NAME_1D864 0x1D864 // 𝡤 SIGNWRITING HAND-FLAT SPLIT CENTRE THUMB SIDE BENT
#define UC_MACRO_NAME_1D865 0x1D865 // 𝡥 SIGNWRITING HAND-FLAT SPLIT LITTLE
#define UC_MACRO_NAME_1D866 0x1D866 // 𝡦 SIGNWRITING HAND-CLAW
#define UC_MACRO_NAME_1D867 0x1D867 // 𝡧 SIGNWRITING HAND-CLAW THUMB SIDE
#define UC_MACRO_NAME_1D868 0x1D868 // 𝡨 SIGNWRITING HAND-CLAW NO THUMB
#define UC_MACRO_NAME_1D869 0x1D869 // 𝡩 SIGNWRITING HAND-CLAW THUMB FORWARD
#define UC_MACRO_NAME_1D86A 0x1D86A // 𝡪 SIGNWRITING HAND-HOOK CURLICUE
#define UC_MACRO_NAME_1D86B 0x1D86B // 𝡫 SIGNWRITING HAND-HOOK
#define UC_MACRO_NAME_1D86C 0x1D86C // 𝡬 SIGNWRITING HAND-CUP OPEN
#define UC_MACRO_NAME_1D86D 0x1D86D // 𝡭 SIGNWRITING HAND-CUP
#define UC_MACRO_NAME_1D86E 0x1D86E // 𝡮 SIGNWRITING HAND-CUP OPEN THUMB SIDE
#define UC_MACRO_NAME_1D86F 0x1D86F // 𝡯 SIGNWRITING HAND-CUP THUMB SIDE
#define UC_MACRO_NAME_1D870 0x1D870 // 𝡰 SIGNWRITING HAND-CUP OPEN NO THUMB
#define UC_MACRO_NAME_1D871 0x1D871 // 𝡱 SIGNWRITING HAND-CUP NO THUMB
#define UC_MACRO_NAME_1D872 0x1D872 // 𝡲 SIGNWRITING HAND-CUP OPEN THUMB FORWARD
#define UC_MACRO_NAME_1D873 0x1D873 // 𝡳 SIGNWRITING HAND-CUP THUMB FORWARD
#define UC_MACRO_NAME_1D874 0x1D874 // 𝡴 SIGNWRITING HAND-CURLICUE OPEN
#define UC_MACRO_NAME_1D875 0x1D875 // 𝡵 SIGNWRITING HAND-CURLICUE
#define UC_MACRO_NAME_1D876 0x1D876 // 𝡶 SIGNWRITING HAND-CIRCLE
#define UC_MACRO_NAME_1D877 0x1D877 // 𝡷 SIGNWRITING HAND-OVAL
#define UC_MACRO_NAME_1D878 0x1D878 // 𝡸 SIGNWRITING HAND-OVAL THUMB SIDE
#define UC_MACRO_NAME_1D879 0x1D879 // 𝡹 SIGNWRITING HAND-OVAL NO THUMB
#define UC_MACRO_NAME_1D87A 0x1D87A // 𝡺 SIGNWRITING HAND-OVAL THUMB FORWARD
#define UC_MACRO_NAME_1D87B 0x1D87B // 𝡻 SIGNWRITING HAND-HINGE OPEN
#define UC_MACRO_NAME_1D87C 0x1D87C // 𝡼 SIGNWRITING HAND-HINGE OPEN THUMB FORWARD
#define UC_MACRO_NAME_1D87D 0x1D87D // 𝡽 SIGNWRITING HAND-HINGE
#define UC_MACRO_NAME_1D87E 0x1D87E // 𝡾 SIGNWRITING HAND-HINGE SMALL
#define UC_MACRO_NAME_1D87F 0x1D87F // 𝡿 SIGNWRITING HAND-HINGE OPEN THUMB SIDE
#define UC_MACRO_NAME_1D880 0x1D880 // 𝢀 SIGNWRITING HAND-HINGE THUMB SIDE
#define UC_MACRO_NAME_1D881 0x1D881 // 𝢁 SIGNWRITING HAND-HINGE OPEN NO THUMB
#define UC_MACRO_NAME_1D882 0x1D882 // 𝢂 SIGNWRITING HAND-HINGE NO THUMB
#define UC_MACRO_NAME_1D883 0x1D883 // 𝢃 SIGNWRITING HAND-HINGE THUMB SIDE TOUCHING INDEX
#define UC_MACRO_NAME_1D884 0x1D884 // 𝢄 SIGNWRITING HAND-HINGE THUMB BETWEEN MIDDLE RING
#define UC_MACRO_NAME_1D885 0x1D885 // 𝢅 SIGNWRITING HAND-ANGLE
#define UC_MACRO_NAME_1D886 0x1D886 // 𝢆 SIGNWRITING HAND-FIST INDEX MIDDLE RING
#define UC_MACRO_NAME_1D887 0x1D887 // 𝢇 SIGNWRITING HAND-CIRCLE INDEX MIDDLE RING
#define UC_MACRO_NAME_1D888 0x1D888 // 𝢈 SIGNWRITING HAND-HINGE INDEX MIDDLE RING
#define UC_MACRO_NAME_1D889 0x1D889 // 𝢉 SIGNWRITING HAND-ANGLE INDEX MIDDLE RING
#define UC_MACRO_NAME_1D88A 0x1D88A // 𝢊 SIGNWRITING HAND-HINGE LITTLE
#define UC_MACRO_NAME_1D88B 0x1D88B // 𝢋 SIGNWRITING HAND-FIST INDEX MIDDLE RING BENT
#define UC_MACRO_NAME_1D88C 0x1D88C // 𝢌 SIGNWRITING HAND-FIST INDEX MIDDLE RING CONJOINED
#define UC_MACRO_NAME_1D88D 0x1D88D // 𝢍 SIGNWRITING HAND-HINGE INDEX MIDDLE RING CONJOINED
#define UC_MACRO_NAME_1D88E 0x1D88E // 𝢎 SIGNWRITING HAND-FIST LITTLE DOWN
#define UC_MACRO_NAME_1D88F 0x1D88F // 𝢏 SIGNWRITING HAND-FIST LITTLE DOWN RIPPLE STRAIGHT
#define UC_MACRO_NAME_1D890 0x1D890 // 𝢐 SIGNWRITING HAND-FIST LITTLE DOWN RIPPLE CURVED
#define UC_MACRO_NAME_1D891 0x1D891 // 𝢑 SIGNWRITING HAND-FIST LITTLE DOWN OTHERS CIRCLED
#define UC_MACRO_NAME_1D892 0x1D892 // 𝢒 SIGNWRITING HAND-FIST LITTLE UP
#define UC_MACRO_NAME_1D893 0x1D893 // 𝢓 SIGNWRITING HAND-FIST THUMB UNDER LITTLE UP
#define UC_MACRO_NAME_1D894 0x1D894 // 𝢔 SIGNWRITING HAND-CIRCLE LITTLE UP
#define UC_MACRO_NAME_1D895 0x1D895 // 𝢕 SIGNWRITING HAND-OVAL LITTLE UP
#define UC_MACRO_NAME_1D896 0x1D896 // 𝢖 SIGNWRITING HAND-ANGLE LITTLE UP
#define UC_MACRO_NAME_1D897 0x1D897 // 𝢗 SIGNWRITING HAND-FIST LITTLE RAISED KNUCKLE
#define UC_MACRO_NAME_1D898 0x1D898 // 𝢘 SIGNWRITING HAND-FIST LITTLE BENT
#define UC_MACRO_NAME_1D899 0x1D899 // 𝢙 SIGNWRITING HAND-FIST LITTLE TOUCHES THUMB
#define UC_MACRO_NAME_1D89A 0x1D89A // 𝢚 SIGNWRITING HAND-FIST LITTLE THUMB
#define UC_MACRO_NAME_1D89B 0x1D89B // 𝢛 SIGNWRITING HAND-HINGE LITTLE THUMB
#define UC_MACRO_NAME_1D89C 0x1D89C // 𝢜 SIGNWRITING HAND-FIST LITTLE INDEX THUMB
#define UC_MACRO_NAME_1D89D 0x1D89D // 𝢝 SIGNWRITING HAND-HINGE LITTLE INDEX THUMB
#define UC_MACRO_NAME_1D89E 0x1D89E // 𝢞 SIGNWRITING HAND-ANGLE LITTLE INDEX THUMB INDEX THUMB OUT
#define UC_MACRO_NAME_1D89F 0x1D89F // 𝢟 SIGNWRITING HAND-ANGLE LITTLE INDEX THUMB INDEX THUMB
#define UC_MACRO_NAME_1D8A0 0x1D8A0 // 𝢠 SIGNWRITING HAND-FIST LITTLE INDEX
#define UC_MACRO_NAME_1D8A1 0x1D8A1 // 𝢡 SIGNWRITING HAND-CIRCLE LITTLE INDEX
#define UC_MACRO_NAME_1D8A2 0x1D8A2 // 𝢢 SIGNWRITING HAND-HINGE LITTLE INDEX
#define UC_MACRO_NAME_1D8A3 0x1D8A3 // 𝢣 SIGNWRITING HAND-ANGLE LITTLE INDEX
#define UC_MACRO_NAME_1D8A4 0x1D8A4 // 𝢤 SIGNWRITING HAND-FIST INDEX MIDDLE LITTLE
#define UC_MACRO_NAME_1D8A5 0x1D8A5 // 𝢥 SIGNWRITING HAND-CIRCLE INDEX MIDDLE LITTLE
#define UC_MACRO_NAME_1D8A6 0x1D8A6 // 𝢦 SIGNWRITING HAND-HINGE INDEX MIDDLE LITTLE
#define UC_MACRO_NAME_1D8A7 0x1D8A7 // 𝢧 SIGNWRITING HAND-HINGE RING
#define UC_MACRO_NAME_1D8A8 0x1D8A8 // 𝢨 SIGNWRITING HAND-ANGLE INDEX MIDDLE LITTLE
#define UC_MACRO_NAME_1D8A9 0x1D8A9 // 𝢩 SIGNWRITING HAND-FIST INDEX MIDDLE CROSS LITTLE
#define UC_MACRO_NAME_1D8AA 0x1D8AA // 𝢪 SIGNWRITING HAND-CIRCLE INDEX MIDDLE CROSS LITTLE
#define UC_MACRO_NAME_1D8AB 0x1D8AB // 𝢫 SIGNWRITING HAND-FIST RING DOWN
#define UC_MACRO_NAME_1D8AC 0x1D8AC // 𝢬 SIGNWRITING HAND-HINGE RING DOWN INDEX THUMB HOOK MIDDLE
#define UC_MACRO_NAME_1D8AD 0x1D8AD // 𝢭 SIGNWRITING HAND-ANGLE RING DOWN MIDDLE THUMB INDEX CROSS
#define UC_MACRO_NAME_1D8AE 0x1D8AE // 𝢮 SIGNWRITING HAND-FIST RING UP
#define UC_MACRO_NAME_1D8AF 0x1D8AF // 𝢯 SIGNWRITING HAND-FIST RING RAISED KNUCKLE
#define UC_MACRO_NAME_1D8B0 0x1D8B0 // 𝢰 SIGNWRITING HAND-FIST RING LITTLE
#define UC_MACRO_NAME_1D8B1 0x1D8B1 // 𝢱 SIGNWRITING HAND-CIRCLE RING LITTLE
#define UC_MACRO_NAME_1D8B2 0x1D8B2 // 𝢲 SIGNWRITING HAND-OVAL RING LITTLE
#define UC_MACRO_NAME_1D8B3 0x1D8B3 // 𝢳 SIGNWRITING HAND-ANGLE RING LITTLE
#define UC_MACRO_NAME_1D8B4 0x1D8B4 // 𝢴 SIGNWRITING HAND-FIST RING MIDDLE
#define UC_MACRO_NAME_1D8B5 0x1D8B5 // 𝢵 SIGNWRITING HAND-FIST RING MIDDLE CONJOINED
#define UC_MACRO_NAME_1D8B6 0x1D8B6 // 𝢶 SIGNWRITING HAND-FIST RING MIDDLE RAISED KNUCKLES
#define UC_MACRO_NAME_1D8B7 0x1D8B7 // 𝢷 SIGNWRITING HAND-FIST RING INDEX
#define UC_MACRO_NAME_1D8B8 0x1D8B8 // 𝢸 SIGNWRITING HAND-FIST RING THUMB
#define UC_MACRO_NAME_1D8B9 0x1D8B9 // 𝢹 SIGNWRITING HAND-HOOK RING THUMB
#define UC_MACRO_NAME_1D8BA 0x1D8BA // 𝢺 SIGNWRITING HAND-FIST INDEX RING LITTLE
#define UC_MACRO_NAME_1D8BB 0x1D8BB // 𝢻 SIGNWRITING HAND-CIRCLE INDEX RING LITTLE
#define UC_MACRO_NAME_1D8BC 0x1D8BC // 𝢼 SIGNWRITING HAND-CURLICUE INDEX RING LITTLE ON
#define UC_MACRO_NAME_1D8BD 0x1D8BD // 𝢽 SIGNWRITING HAND-HOOK INDEX RING LITTLE OUT
#define UC_MACRO_NAME_1D8BE 0x1D8BE // 𝢾 SIGNWRITING HAND-HOOK INDEX RING LITTLE IN
#define UC_MACRO_NAME_1D8BF 0x1D8BF // 𝢿 SIGNWRITING HAND-HOOK INDEX RING LITTLE UNDER
#define UC_MACRO_NAME_1D8C0 0x1D8C0 // 𝣀 SIGNWRITING HAND-CUP INDEX RING LITTLE
#define UC_MACRO_NAME_1D8C1 0x1D8C1 // 𝣁 SIGNWRITING HAND-HINGE INDEX RING LITTLE
#define UC_MACRO_NAME_1D8C2 0x1D8C2 // 𝣂 SIGNWRITING HAND-ANGLE INDEX RING LITTLE OUT
#define UC_MACRO_NAME_1D8C3 0x1D8C3 // 𝣃 SIGNWRITING HAND-ANGLE INDEX RING LITTLE
#define UC_MACRO_NAME_1D8C4 0x1D8C4 // 𝣄 SIGNWRITING HAND-FIST MIDDLE DOWN
#define UC_MACRO_NAME_1D8C5 0x1D8C5 // 𝣅 SIGNWRITING HAND-HINGE MIDDLE
#define UC_MACRO_NAME_1D8C6 0x1D8C6 // 𝣆 SIGNWRITING HAND-FIST MIDDLE UP
#define UC_MACRO_NAME_1D8C7 0x1D8C7 // 𝣇 SIGNWRITING HAND-CIRCLE MIDDLE UP
#define UC_MACRO_NAME_1D8C8 0x1D8C8 // 𝣈 SIGNWRITING HAND-FIST MIDDLE RAISED KNUCKLE
#define UC_MACRO_NAME_1D8C9 0x1D8C9 // 𝣉 SIGNWRITING HAND-FIST MIDDLE UP THUMB SIDE
#define UC_MACRO_NAME_1D8CA 0x1D8CA // 𝣊 SIGNWRITING HAND-HOOK MIDDLE THUMB
#define UC_MACRO_NAME_1D8CB 0x1D8CB // 𝣋 SIGNWRITING HAND-FIST MIDDLE THUMB LITTLE
#define UC_MACRO_NAME_1D8CC 0x1D8CC // 𝣌 SIGNWRITING HAND-FIST MIDDLE LITTLE
#define UC_MACRO_NAME_1D8CD 0x1D8CD // 𝣍 SIGNWRITING HAND-FIST MIDDLE RING LITTLE
#define UC_MACRO_NAME_1D8CE 0x1D8CE // 𝣎 SIGNWRITING HAND-CIRCLE MIDDLE RING LITTLE
#define UC_MACRO_NAME_1D8CF 0x1D8CF // 𝣏 SIGNWRITING HAND-CURLICUE MIDDLE RING LITTLE ON
#define UC_MACRO_NAME_1D8D0 0x1D8D0 // 𝣐 SIGNWRITING HAND-CUP MIDDLE RING LITTLE
#define UC_MACRO_NAME_1D8D1 0x1D8D1 // 𝣑 SIGNWRITING HAND-HINGE MIDDLE RING LITTLE
#define UC_MACRO_NAME_1D8D2 0x1D8D2 // 𝣒 SIGNWRITING HAND-ANGLE MIDDLE RING LITTLE OUT
#define UC_MACRO_NAME_1D8D3 0x1D8D3 // 𝣓 SIGNWRITING HAND-ANGLE MIDDLE RING LITTLE IN
#define UC_MACRO_NAME_1D8D4 0x1D8D4 // 𝣔 SIGNWRITING HAND-ANGLE MIDDLE RING LITTLE
#define UC_MACRO_NAME_1D8D5 0x1D8D5 // 𝣕 SIGNWRITING HAND-CIRCLE MIDDLE RING LITTLE BENT
#define UC_MACRO_NAME_1D8D6 0x1D8D6 // 𝣖 SIGNWRITING HAND-CLAW MIDDLE RING LITTLE CONJOINED
#define UC_MACRO_NAME_1D8D7 0x1D8D7 // 𝣗 SIGNWRITING HAND-CLAW MIDDLE RING LITTLE CONJOINED SIDE
#define UC_MACRO_NAME_1D8D8 0x1D8D8 // 𝣘 SIGNWRITING HAND-HOOK MIDDLE RING LITTLE CONJOINED OUT
#define UC_MACRO_NAME_1D8D9 0x1D8D9 // 𝣙 SIGNWRITING HAND-HOOK MIDDLE RING LITTLE CONJOINED IN
#define UC_MACRO_NAME_1D8DA 0x1D8DA // 𝣚 SIGNWRITING HAND-HOOK MIDDLE RING LITTLE CONJOINED
#define UC_MACRO_NAME_1D8DB 0x1D8DB // 𝣛 SIGNWRITING HAND-HINGE INDEX HINGED
#define UC_MACRO_NAME_1D8DC 0x1D8DC // 𝣜 SIGNWRITING HAND-FIST INDEX THUMB SIDE
#define UC_MACRO_NAME_1D8DD 0x1D8DD // 𝣝 SIGNWRITING HAND-HINGE INDEX THUMB SIDE
#define UC_MACRO_NAME_1D8DE 0x1D8DE // 𝣞 SIGNWRITING HAND-FIST INDEX THUMB SIDE THUMB DIAGONAL
#define UC_MACRO_NAME_1D8DF 0x1D8DF // 𝣟 SIGNWRITING HAND-FIST INDEX THUMB SIDE THUMB CONJOINED
#define UC_MACRO_NAME_1D8E0 0x1D8E0 // 𝣠 SIGNWRITING HAND-FIST INDEX THUMB SIDE THUMB BENT
#define UC_MACRO_NAME_1D8E1 0x1D8E1 // 𝣡 SIGNWRITING HAND-FIST INDEX THUMB SIDE INDEX BENT
#define UC_MACRO_NAME_1D8E2 0x1D8E2 // 𝣢 SIGNWRITING HAND-FIST INDEX THUMB SIDE BOTH BENT
#define UC_MACRO_NAME_1D8E3 0x1D8E3 // 𝣣 SIGNWRITING HAND-FIST INDEX THUMB SIDE INDEX HINGE
#define UC_MACRO_NAME_1D8E4 0x1D8E4 // 𝣤 SIGNWRITING HAND-FIST INDEX THUMB FORWARD INDEX STRAIGHT
#define UC_MACRO_NAME_1D8E5 0x1D8E5 // 𝣥 SIGNWRITING HAND-FIST INDEX THUMB FORWARD INDEX BENT
#define UC_MACRO_NAME_1D8E6 0x1D8E6 // 𝣦 SIGNWRITING HAND-FIST INDEX THUMB HOOK
#define UC_MACRO_NAME_1D8E7 0x1D8E7 // 𝣧 SIGNWRITING HAND-FIST INDEX THUMB CURLICUE
#define UC_MACRO_NAME_1D8E8 0x1D8E8 // 𝣨 SIGNWRITING HAND-FIST INDEX THUMB CURVE THUMB INSIDE
#define UC_MACRO_NAME_1D8E9 0x1D8E9 // 𝣩 SIGNWRITING HAND-CLAW INDEX THUMB CURVE THUMB INSIDE
#define UC_MACRO_NAME_1D8EA 0x1D8EA // 𝣪 SIGNWRITING HAND-FIST INDEX THUMB CURVE THUMB UNDER
#define UC_MACRO_NAME_1D8EB 0x1D8EB // 𝣫 SIGNWRITING HAND-FIST INDEX THUMB CIRCLE
#define UC_MACRO_NAME_1D8EC 0x1D8EC // 𝣬 SIGNWRITING HAND-CUP INDEX THUMB
#define UC_MACRO_NAME_1D8ED 0x1D8ED // 𝣭 SIGNWRITING HAND-CUP INDEX THUMB OPEN
#define UC_MACRO_NAME_1D8EE 0x1D8EE // 𝣮 SIGNWRITING HAND-HINGE INDEX THUMB OPEN
#define UC_MACRO_NAME_1D8EF 0x1D8EF // 𝣯 SIGNWRITING HAND-HINGE INDEX THUMB LARGE
#define UC_MACRO_NAME_1D8F0 0x1D8F0 // 𝣰 SIGNWRITING HAND-HINGE INDEX THUMB
#define UC_MACRO_NAME_1D8F1 0x1D8F1 // 𝣱 SIGNWRITING HAND-HINGE INDEX THUMB SMALL
#define UC_MACRO_NAME_1D8F2 0x1D8F2 // 𝣲 SIGNWRITING HAND-ANGLE INDEX THUMB OUT
#define UC_MACRO_NAME_1D8F3 0x1D8F3 // 𝣳 SIGNWRITING HAND-ANGLE INDEX THUMB IN
#define UC_MACRO_NAME_1D8F4 0x1D8F4 // 𝣴 SIGNWRITING HAND-ANGLE INDEX THUMB
#define UC_MACRO_NAME_1D8F5 0x1D8F5 // 𝣵 SIGNWRITING HAND-FIST THUMB
#define UC_MACRO_NAME_1D8F6 0x1D8F6 // 𝣶 SIGNWRITING HAND-FIST THUMB HEEL
#define UC_MACRO_NAME_1D8F7 0x1D8F7 // 𝣷 SIGNWRITING HAND-FIST THUMB SIDE DIAGONAL
#define UC_MACRO_NAME_1D8F8 0x1D8F8 // 𝣸 SIGNWRITING HAND-FIST THUMB SIDE CONJOINED
#define UC_MACRO_NAME_1D8F9 0x1D8F9 // 𝣹 SIGNWRITING HAND-FIST THUMB SIDE BENT
#define UC_MACRO_NAME_1D8FA 0x1D8FA // 𝣺 SIGNWRITING HAND-FIST THUMB FORWARD
#define UC_MACRO_NAME_1D8FB 0x1D8FB // 𝣻 SIGNWRITING HAND-FIST THUMB BETWEEN INDEX MIDDLE
#define UC_MACRO_NAME_1D8FC 0x1D8FC // 𝣼 SIGNWRITING HAND-FIST THUMB BETWEEN MIDDLE RING
#define UC_MACRO_NAME_1D8FD 0x1D8FD // 𝣽 SIGNWRITING HAND-FIST THUMB BETWEEN RING LITTLE
#define UC_MACRO_NAME_1D8FE 0x1D8FE // 𝣾 SIGNWRITING HAND-FIST THUMB UNDER TWO FINGERS
#define UC_MACRO_NAME_1D8FF 0x1D8FF // 𝣿 SIGNWRITING HAND-FIST THUMB OVER TWO FINGERS
#define UC_MACRO_NAME_1D900 0x1D900 // 𝤀 SIGNWRITING HAND-FIST THUMB UNDER THREE FINGERS
#define UC_MACRO_NAME_1D901 0x1D901 // 𝤁 SIGNWRITING HAND-FIST THUMB UNDER FOUR FINGERS
#define UC_MACRO_NAME_1D902 0x1D902 // 𝤂 SIGNWRITING HAND-FIST THUMB OVER FOUR RAISED KNUCKLES
#define UC_MACRO_NAME_1D903 0x1D903 // 𝤃 SIGNWRITING HAND-FIST
#define UC_MACRO_NAME_1D904 0x1D904 // 𝤄 SIGNWRITING HAND-FIST HEEL
#define UC_MACRO_NAME_1D905 0x1D905 // 𝤅 SIGNWRITING TOUCH SINGLE
#define UC_MACRO_NAME_1D906 0x1D906 // 𝤆 SIGNWRITING TOUCH MULTIPLE
#define UC_MACRO_NAME_1D907 0x1D907 // 𝤇 SIGNWRITING TOUCH BETWEEN
#define UC_MACRO_NAME_1D908 0x1D908 // 𝤈 SIGNWRITING GRASP SINGLE
#define UC_MACRO_NAME_1D909 0x1D909 // 𝤉 SIGNWRITING GRASP MULTIPLE
#define UC_MACRO_NAME_1D90A 0x1D90A // 𝤊 SIGNWRITING GRASP BETWEEN
#define UC_MACRO_NAME_1D90B 0x1D90B // 𝤋 SIGNWRITING STRIKE SINGLE
#define UC_MACRO_NAME_1D90C 0x1D90C // 𝤌 SIGNWRITING STRIKE MULTIPLE
#define UC_MACRO_NAME_1D90D 0x1D90D // 𝤍 SIGNWRITING STRIKE BETWEEN
#define UC_MACRO_NAME_1D90E 0x1D90E // 𝤎 SIGNWRITING BRUSH SINGLE
#define UC_MACRO_NAME_1D90F 0x1D90F // 𝤏 SIGNWRITING BRUSH MULTIPLE
#define UC_MACRO_NAME_1D910 0x1D910 // 𝤐 SIGNWRITING BRUSH BETWEEN
#define UC_MACRO_NAME_1D911 0x1D911 // 𝤑 SIGNWRITING RUB SINGLE
#define UC_MACRO_NAME_1D912 0x1D912 // 𝤒 SIGNWRITING RUB MULTIPLE
#define UC_MACRO_NAME_1D913 0x1D913 // 𝤓 SIGNWRITING RUB BETWEEN
#define UC_MACRO_NAME_1D914 0x1D914 // 𝤔 SIGNWRITING SURFACE SYMBOLS
#define UC_MACRO_NAME_1D915 0x1D915 // 𝤕 SIGNWRITING SURFACE BETWEEN
#define UC_MACRO_NAME_1D916 0x1D916 // 𝤖 SIGNWRITING SQUEEZE LARGE SINGLE
#define UC_MACRO_NAME_1D917 0x1D917 // 𝤗 SIGNWRITING SQUEEZE SMALL SINGLE
#define UC_MACRO_NAME_1D918 0x1D918 // 𝤘 SIGNWRITING SQUEEZE LARGE MULTIPLE
#define UC_MACRO_NAME_1D919 0x1D919 // 𝤙 SIGNWRITING SQUEEZE SMALL MULTIPLE
#define UC_MACRO_NAME_1D91A 0x1D91A // 𝤚 SIGNWRITING SQUEEZE SEQUENTIAL
#define UC_MACRO_NAME_1D91B 0x1D91B // 𝤛 SIGNWRITING FLICK LARGE SINGLE
#define UC_MACRO_NAME_1D91C 0x1D91C // 𝤜 SIGNWRITING FLICK SMALL SINGLE
#define UC_MACRO_NAME_1D91D 0x1D91D // 𝤝 SIGNWRITING FLICK LARGE MULTIPLE
#define UC_MACRO_NAME_1D91E 0x1D91E // 𝤞 SIGNWRITING FLICK SMALL MULTIPLE
#define UC_MACRO_NAME_1D91F 0x1D91F // 𝤟 SIGNWRITING FLICK SEQUENTIAL
#define UC_MACRO_NAME_1D920 0x1D920 // 𝤠 SIGNWRITING SQUEEZE FLICK ALTERNATING
#define UC_MACRO_NAME_1D921 0x1D921 // 𝤡 SIGNWRITING MOVEMENT-HINGE UP DOWN LARGE
#define UC_MACRO_NAME_1D922 0x1D922 // 𝤢 SIGNWRITING MOVEMENT-HINGE UP DOWN SMALL
#define UC_MACRO_NAME_1D923 0x1D923 // 𝤣 SIGNWRITING MOVEMENT-HINGE UP SEQUENTIAL
#define UC_MACRO_NAME_1D924 0x1D924 // 𝤤 SIGNWRITING MOVEMENT-HINGE DOWN SEQUENTIAL
#define UC_MACRO_NAME_1D925 0x1D925 // 𝤥 SIGNWRITING MOVEMENT-HINGE UP DOWN ALTERNATING LARGE
#define UC_MACRO_NAME_1D926 0x1D926 // 𝤦 SIGNWRITING MOVEMENT-HINGE UP DOWN ALTERNATING SMALL
#define UC_MACRO_NAME_1D927 0x1D927 // 𝤧 SIGNWRITING MOVEMENT-HINGE SIDE TO SIDE SCISSORS
#define UC_MACRO_NAME_1D928 0x1D928 // 𝤨 SIGNWRITING MOVEMENT-WALLPLANE FINGER CONTACT
#define UC_MACRO_NAME_1D929 0x1D929 // 𝤩 SIGNWRITING MOVEMENT-FLOORPLANE FINGER CONTACT
#define UC_MACRO_NAME_1D92A 0x1D92A // 𝤪 SIGNWRITING MOVEMENT-WALLPLANE SINGLE STRAIGHT SMALL
#define UC_MACRO_NAME_1D92B 0x1D92B // 𝤫 SIGNWRITING MOVEMENT-WALLPLANE SINGLE STRAIGHT MEDIUM
#define UC_MACRO_NAME_1D92C 0x1D92C // 𝤬 SIGNWRITING MOVEMENT-WALLPLANE SINGLE STRAIGHT LARGE
#define UC_MACRO_NAME_1D92D 0x1D92D // 𝤭 SIGNWRITING MOVEMENT-WALLPLANE SINGLE STRAIGHT LARGEST
#define UC_MACRO_NAME_1D92E 0x1D92E // 𝤮 SIGNWRITING MOVEMENT-WALLPLANE SINGLE WRIST FLEX
#define UC_MACRO_NAME_1D92F 0x1D92F // 𝤯 SIGNWRITING MOVEMENT-WALLPLANE DOUBLE STRAIGHT
#define UC_MACRO_NAME_1D930 0x1D930 // 𝤰 SIGNWRITING MOVEMENT-WALLPLANE DOUBLE WRIST FLEX
#define UC_MACRO_NAME_1D931 0x1D931 // 𝤱 SIGNWRITING MOVEMENT-WALLPLANE DOUBLE ALTERNATING
#define UC_MACRO_NAME_1D932 0x1D932 // 𝤲 SIGNWRITING MOVEMENT-WALLPLANE DOUBLE ALTERNATING WRIST FLEX
#define UC_MACRO_NAME_1D933 0x1D933 // 𝤳 SIGNWRITING MOVEMENT-WALLPLANE CROSS
#define UC_MACRO_NAME_1D934 0x1D934 // 𝤴 SIGNWRITING MOVEMENT-WALLPLANE TRIPLE STRAIGHT MOVEMENT
#define UC_MACRO_NAME_1D935 0x1D935 // 𝤵 SIGNWRITING MOVEMENT-WALLPLANE TRIPLE WRIST FLEX
#define UC_MACRO_NAME_1D936 0x1D936 // 𝤶 SIGNWRITING MOVEMENT-WALLPLANE TRIPLE ALTERNATING
#define UC_MACRO_NAME_1D937 0x1D937 // 𝤷 SIGNWRITING MOVEMENT-WALLPLANE TRIPLE ALTERNATING WRIST FLEX
#define UC_MACRO_NAME_1D938 0x1D938 // 𝤸 SIGNWRITING MOVEMENT-WALLPLANE BEND SMALL
#define UC_MACRO_NAME_1D939 0x1D939 // 𝤹 SIGNWRITING MOVEMENT-WALLPLANE BEND MEDIUM
#define UC_MACRO_NAME_1D93A 0x1D93A // 𝤺 SIGNWRITING MOVEMENT-WALLPLANE BEND LARGE
#define UC_MACRO_NAME_1D93B 0x1D93B // 𝤻 SIGNWRITING MOVEMENT-WALLPLANE CORNER SMALL
#define UC_MACRO_NAME_1D93C 0x1D93C // 𝤼 SIGNWRITING MOVEMENT-WALLPLANE CORNER MEDIUM
#define UC_MACRO_NAME_1D93D 0x1D93D // 𝤽 SIGNWRITING MOVEMENT-WALLPLANE CORNER LARGE
#define UC_MACRO_NAME_1D93E 0x1D93E // 𝤾 SIGNWRITING MOVEMENT-WALLPLANE CORNER ROTATION
#define UC_MACRO_NAME_1D93F 0x1D93F // 𝤿 SIGNWRITING MOVEMENT-WALLPLANE CHECK SMALL
#define UC_MACRO_NAME_1D940 0x1D940 // 𝥀 SIGNWRITING MOVEMENT-WALLPLANE CHECK MEDIUM
#define UC_MACRO_NAME_1D941 0x1D941 // 𝥁 SIGNWRITING MOVEMENT-WALLPLANE CHECK LARGE
#define UC_MACRO_NAME_1D942 0x1D942 // 𝥂 SIGNWRITING MOVEMENT-WALLPLANE BOX SMALL
#define UC_MACRO_NAME_1D943 0x1D943 // 𝥃 SIGNWRITING MOVEMENT-WALLPLANE BOX MEDIUM
#define UC_MACRO_NAME_1D944 0x1D944 // 𝥄 SIGNWRITING MOVEMENT-WALLPLANE BOX LARGE
#define UC_MACRO_NAME_1D945 0x1D945 // 𝥅 SIGNWRITING MOVEMENT-WALLPLANE ZIGZAG SMALL
#define UC_MACRO_NAME_1D946 0x1D946 // 𝥆 SIGNWRITING MOVEMENT-WALLPLANE ZIGZAG MEDIUM
#define UC_MACRO_NAME_1D947 0x1D947 // 𝥇 SIGNWRITING MOVEMENT-WALLPLANE ZIGZAG LARGE
#define UC_MACRO_NAME_1D948 0x1D948 // 𝥈 SIGNWRITING MOVEMENT-WALLPLANE PEAKS SMALL
#define UC_MACRO_NAME_1D949 0x1D949 // 𝥉 SIGNWRITING MOVEMENT-WALLPLANE PEAKS MEDIUM
#define UC_MACRO_NAME_1D94A 0x1D94A // 𝥊 SIGNWRITING MOVEMENT-WALLPLANE PEAKS LARGE
#define UC_MACRO_NAME_1D94B 0x1D94B // 𝥋 SIGNWRITING TRAVEL-WALLPLANE ROTATION-WALLPLANE SINGLE
#define UC_MACRO_NAME_1D94C 0x1D94C // 𝥌 SIGNWRITING TRAVEL-WALLPLANE ROTATION-WALLPLANE DOUBLE
#define UC_MACRO_NAME_1D94D 0x1D94D // 𝥍 SIGNWRITING TRAVEL-WALLPLANE ROTATION-WALLPLANE ALTERNATING
#define UC_MACRO_NAME_1D94E 0x1D94E // 𝥎 SIGNWRITING TRAVEL-WALLPLANE ROTATION-FLOORPLANE SINGLE
#define UC_MACRO_NAME_1D94F 0x1D94F // 𝥏 SIGNWRITING TRAVEL-WALLPLANE ROTATION-FLOORPLANE DOUBLE
#define UC_MACRO_NAME_1D950 0x1D950 // 𝥐 SIGNWRITING TRAVEL-WALLPLANE ROTATION-FLOORPLANE ALTERNATING
#define UC_MACRO_NAME_1D951 0x1D951 // 𝥑 SIGNWRITING TRAVEL-WALLPLANE SHAKING
#define UC_MACRO_NAME_1D952 0x1D952 // 𝥒 SIGNWRITING TRAVEL-WALLPLANE ARM SPIRAL SINGLE
#define UC_MACRO_NAME_1D953 0x1D953 // 𝥓 SIGNWRITING TRAVEL-WALLPLANE ARM SPIRAL DOUBLE
#define UC_MACRO_NAME_1D954 0x1D954 // 𝥔 SIGNWRITING TRAVEL-WALLPLANE ARM SPIRAL TRIPLE
#define UC_MACRO_NAME_1D955 0x1D955 // 𝥕 SIGNWRITING MOVEMENT-DIAGONAL AWAY SMALL
#define UC_MACRO_NAME_1D956 0x1D956 // 𝥖 SIGNWRITING MOVEMENT-DIAGONAL AWAY MEDIUM
#define UC_MACRO_NAME_1D957 0x1D957 // 𝥗 SIGNWRITING MOVEMENT-DIAGONAL AWAY LARGE
#define UC_MACRO_NAME_1D958 0x1D958 // 𝥘 SIGNWRITING MOVEMENT-DIAGONAL AWAY LARGEST
#define UC_MACRO_NAME_1D959 0x1D959 // 𝥙 SIGNWRITING MOVEMENT-DIAGONAL TOWARDS SMALL
#define UC_MACRO_NAME_1D95A 0x1D95A // 𝥚 SIGNWRITING MOVEMENT-DIAGONAL TOWARDS MEDIUM
#define UC_MACRO_NAME_1D95B 0x1D95B // 𝥛 SIGNWRITING MOVEMENT-DIAGONAL TOWARDS LARGE
#define UC_MACRO_NAME_1D95C 0x1D95C // 𝥜 SIGNWRITING MOVEMENT-DIAGONAL TOWARDS LARGEST
#define UC_MACRO_NAME_1D95D 0x1D95D // 𝥝 SIGNWRITING MOVEMENT-DIAGONAL BETWEEN AWAY SMALL
#define UC_MACRO_NAME_1D95E 0x1D95E // 𝥞 SIGNWRITING MOVEMENT-DIAGONAL BETWEEN AWAY MEDIUM
#define UC_MACRO_NAME_1D95F 0x1D95F // 𝥟 SIGNWRITING MOVEMENT-DIAGONAL BETWEEN AWAY LARGE
#define UC_MACRO_NAME_1D960 0x1D960 // 𝥠 SIGNWRITING MOVEMENT-DIAGONAL BETWEEN AWAY LARGEST
#define UC_MACRO_NAME_1D961 0x1D961 // 𝥡 SIGNWRITING MOVEMENT-DIAGONAL BETWEEN TOWARDS SMALL
#define UC_MACRO_NAME_1D962 0x1D962 // 𝥢 SIGNWRITING MOVEMENT-DIAGONAL BETWEEN TOWARDS MEDIUM
#define UC_MACRO_NAME_1D963 0x1D963 // 𝥣 SIGNWRITING MOVEMENT-DIAGONAL BETWEEN TOWARDS LARGE
#define UC_MACRO_NAME_1D964 0x1D964 // 𝥤 SIGNWRITING MOVEMENT-DIAGONAL BETWEEN TOWARDS LARGEST
#define UC_MACRO_NAME_1D965 0x1D965 // 𝥥 SIGNWRITING MOVEMENT-FLOORPLANE SINGLE STRAIGHT SMALL
#define UC_MACRO_NAME_1D966 0x1D966 // 𝥦 SIGNWRITING MOVEMENT-FLOORPLANE SINGLE STRAIGHT MEDIUM
#define UC_MACRO_NAME_1D967 0x1D967 // 𝥧 SIGNWRITING MOVEMENT-FLOORPLANE SINGLE STRAIGHT LARGE
#define UC_MACRO_NAME_1D968 0x1D968 // 𝥨 SIGNWRITING MOVEMENT-FLOORPLANE SINGLE STRAIGHT LARGEST
#define UC_MACRO_NAME_1D969 0x1D969 // 𝥩 SIGNWRITING MOVEMENT-FLOORPLANE SINGLE WRIST FLEX
#define UC_MACRO_NAME_1D96A 0x1D96A // 𝥪 SIGNWRITING MOVEMENT-FLOORPLANE DOUBLE STRAIGHT
#define UC_MACRO_NAME_1D96B 0x1D96B // 𝥫 SIGNWRITING MOVEMENT-FLOORPLANE DOUBLE WRIST FLEX
#define UC_MACRO_NAME_1D96C 0x1D96C // 𝥬 SIGNWRITING MOVEMENT-FLOORPLANE DOUBLE ALTERNATING
#define UC_MACRO_NAME_1D96D 0x1D96D // 𝥭 SIGNWRITING MOVEMENT-FLOORPLANE DOUBLE ALTERNATING WRIST FLEX
#define UC_MACRO_NAME_1D96E 0x1D96E // 𝥮 SIGNWRITING MOVEMENT-FLOORPLANE CROSS
#define UC_MACRO_NAME_1D96F 0x1D96F // 𝥯 SIGNWRITING MOVEMENT-FLOORPLANE TRIPLE STRAIGHT MOVEMENT
#define UC_MACRO_NAME_1D970 0x1D970 // 𝥰 SIGNWRITING MOVEMENT-FLOORPLANE TRIPLE WRIST FLEX
#define UC_MACRO_NAME_1D971 0x1D971 // 𝥱 SIGNWRITING MOVEMENT-FLOORPLANE TRIPLE ALTERNATING MOVEMENT
#define UC_MACRO_NAME_1D972 0x1D972 // 𝥲 SIGNWRITING MOVEMENT-FLOORPLANE TRIPLE ALTERNATING WRIST FLEX
#define UC_MACRO_NAME_1D973 0x1D973 // 𝥳 SIGNWRITING MOVEMENT-FLOORPLANE BEND
#define UC_MACRO_NAME_1D974 0x1D974 // 𝥴 SIGNWRITING MOVEMENT-FLOORPLANE CORNER SMALL
#define UC_MACRO_NAME_1D975 0x1D975 // 𝥵 SIGNWRITING MOVEMENT-FLOORPLANE CORNER MEDIUM
#define UC_MACRO_NAME_1D976 0x1D976 // 𝥶 SIGNWRITING MOVEMENT-FLOORPLANE CORNER LARGE
#define UC_MACRO_NAME_1D977 0x1D977 // 𝥷 SIGNWRITING MOVEMENT-FLOORPLANE CHECK
#define UC_MACRO_NAME_1D978 0x1D978 // 𝥸 SIGNWRITING MOVEMENT-FLOORPLANE BOX SMALL
#define UC_MACRO_NAME_1D979 0x1D979 // 𝥹 SIGNWRITING MOVEMENT-FLOORPLANE BOX MEDIUM
#define UC_MACRO_NAME_1D97A 0x1D97A // 𝥺 SIGNWRITING MOVEMENT-FLOORPLANE BOX LARGE
#define UC_MACRO_NAME_1D97B 0x1D97B // 𝥻 SIGNWRITING MOVEMENT-FLOORPLANE ZIGZAG SMALL
#define UC_MACRO_NAME_1D97C 0x1D97C // 𝥼 SIGNWRITING MOVEMENT-FLOORPLANE ZIGZAG MEDIUM
#define UC_MACRO_NAME_1D97D 0x1D97D // 𝥽 SIGNWRITING MOVEMENT-FLOORPLANE ZIGZAG LARGE
#define UC_MACRO_NAME_1D97E 0x1D97E // 𝥾 SIGNWRITING MOVEMENT-FLOORPLANE PEAKS SMALL
#define UC_MACRO_NAME_1D97F 0x1D97F // 𝥿 SIGNWRITING MOVEMENT-FLOORPLANE PEAKS MEDIUM
#define UC_MACRO_NAME_1D980 0x1D980 // 𝦀 SIGNWRITING MOVEMENT-FLOORPLANE PEAKS LARGE
#define UC_MACRO_NAME_1D981 0x1D981 // 𝦁 SIGNWRITING TRAVEL-FLOORPLANE ROTATION-FLOORPLANE SINGLE
#define UC_MACRO_NAME_1D982 0x1D982 // 𝦂 SIGNWRITING TRAVEL-FLOORPLANE ROTATION-FLOORPLANE DOUBLE
#define UC_MACRO_NAME_1D983 0x1D983 // 𝦃 SIGNWRITING TRAVEL-FLOORPLANE ROTATION-FLOORPLANE ALTERNATING
#define UC_MACRO_NAME_1D984 0x1D984 // 𝦄 SIGNWRITING TRAVEL-FLOORPLANE ROTATION-WALLPLANE SINGLE
#define UC_MACRO_NAME_1D985 0x1D985 // 𝦅 SIGNWRITING TRAVEL-FLOORPLANE ROTATION-WALLPLANE DOUBLE
#define UC_MACRO_NAME_1D986 0x1D986 // 𝦆 SIGNWRITING TRAVEL-FLOORPLANE ROTATION-WALLPLANE ALTERNATING
#define UC_MACRO_NAME_1D987 0x1D987 // 𝦇 SIGNWRITING TRAVEL-FLOORPLANE SHAKING
#define UC_MACRO_NAME_1D988 0x1D988 // 𝦈 SIGNWRITING MOVEMENT-WALLPLANE CURVE QUARTER SMALL
#define UC_MACRO_NAME_1D989 0x1D989 // 𝦉 SIGNWRITING MOVEMENT-WALLPLANE CURVE QUARTER MEDIUM
#define UC_MACRO_NAME_1D98A 0x1D98A // 𝦊 SIGNWRITING MOVEMENT-WALLPLANE CURVE QUARTER LARGE
#define UC_MACRO_NAME_1D98B 0x1D98B // 𝦋 SIGNWRITING MOVEMENT-WALLPLANE CURVE QUARTER LARGEST
#define UC_MACRO_NAME_1D98C 0x1D98C // 𝦌 SIGNWRITING MOVEMENT-WALLPLANE CURVE HALF-CIRCLE SMALL
#define UC_MACRO_NAME_1D98D 0x1D98D // 𝦍 SIGNWRITING MOVEMENT-WALLPLANE CURVE HALF-CIRCLE MEDIUM
#define UC_MACRO_NAME_1D98E 0x1D98E // 𝦎 SIGNWRITING MOVEMENT-WALLPLANE CURVE HALF-CIRCLE LARGE
#define UC_MACRO_NAME_1D98F 0x1D98F // 𝦏 SIGNWRITING MOVEMENT-WALLPLANE CURVE HALF-CIRCLE LARGEST
#define UC_MACRO_NAME_1D990 0x1D990 // 𝦐 SIGNWRITING MOVEMENT-WALLPLANE CURVE THREE-QUARTER CIRCLE SMALL
#define UC_MACRO_NAME_1D991 0x1D991 // 𝦑 SIGNWRITING MOVEMENT-WALLPLANE CURVE THREE-QUARTER CIRCLE MEDIUM
#define UC_MACRO_NAME_1D992 0x1D992 // 𝦒 SIGNWRITING MOVEMENT-WALLPLANE HUMP SMALL
#define UC_MACRO_NAME_1D993 0x1D993 // 𝦓 SIGNWRITING MOVEMENT-WALLPLANE HUMP MEDIUM
#define UC_MACRO_NAME_1D994 0x1D994 // 𝦔 SIGNWRITING MOVEMENT-WALLPLANE HUMP LARGE
#define UC_MACRO_NAME_1D995 0x1D995 // 𝦕 SIGNWRITING MOVEMENT-WALLPLANE LOOP SMALL
#define UC_MACRO_NAME_1D996 0x1D996 // 𝦖 SIGNWRITING MOVEMENT-WALLPLANE LOOP MEDIUM
#define UC_MACRO_NAME_1D997 0x1D997 // 𝦗 SIGNWRITING MOVEMENT-WALLPLANE LOOP LARGE
#define UC_MACRO_NAME_1D998 0x1D998 // 𝦘 SIGNWRITING MOVEMENT-WALLPLANE LOOP SMALL DOUBLE
#define UC_MACRO_NAME_1D999 0x1D999 // 𝦙 SIGNWRITING MOVEMENT-WALLPLANE WAVE CURVE DOUBLE SMALL
#define UC_MACRO_NAME_1D99A 0x1D99A // 𝦚 SIGNWRITING MOVEMENT-WALLPLANE WAVE CURVE DOUBLE MEDIUM
#define UC_MACRO_NAME_1D99B 0x1D99B // 𝦛 SIGNWRITING MOVEMENT-WALLPLANE WAVE CURVE DOUBLE LARGE
#define UC_MACRO_NAME_1D99C 0x1D99C // 𝦜 SIGNWRITING MOVEMENT-WALLPLANE WAVE CURVE TRIPLE SMALL
#define UC_MACRO_NAME_1D99D 0x1D99D // 𝦝 SIGNWRITING MOVEMENT-WALLPLANE WAVE CURVE TRIPLE MEDIUM
#define UC_MACRO_NAME_1D99E 0x1D99E // 𝦞 SIGNWRITING MOVEMENT-WALLPLANE WAVE CURVE TRIPLE LARGE
#define UC_MACRO_NAME_1D99F 0x1D99F // 𝦟 SIGNWRITING MOVEMENT-WALLPLANE CURVE THEN STRAIGHT
#define UC_MACRO_NAME_1D9A0 0x1D9A0 // 𝦠 SIGNWRITING MOVEMENT-WALLPLANE CURVED CROSS SMALL
#define UC_MACRO_NAME_1D9A1 0x1D9A1 // 𝦡 SIGNWRITING MOVEMENT-WALLPLANE CURVED CROSS MEDIUM
#define UC_MACRO_NAME_1D9A2 0x1D9A2 // 𝦢 SIGNWRITING ROTATION-WALLPLANE SINGLE
#define UC_MACRO_NAME_1D9A3 0x1D9A3 // 𝦣 SIGNWRITING ROTATION-WALLPLANE DOUBLE
#define UC_MACRO_NAME_1D9A4 0x1D9A4 // 𝦤 SIGNWRITING ROTATION-WALLPLANE ALTERNATE
#define UC_MACRO_NAME_1D9A5 0x1D9A5 // 𝦥 SIGNWRITING MOVEMENT-WALLPLANE SHAKING
#define UC_MACRO_NAME_1D9A6 0x1D9A6 // 𝦦 SIGNWRITING MOVEMENT-WALLPLANE CURVE HITTING FRONT WALL
#define UC_MACRO_NAME_1D9A7 0x1D9A7 // 𝦧 SIGNWRITING MOVEMENT-WALLPLANE HUMP HITTING FRONT WALL
#define UC_MACRO_NAME_1D9A8 0x1D9A8 // 𝦨 SIGNWRITING MOVEMENT-WALLPLANE LOOP HITTING FRONT WALL
#define UC_MACRO_NAME_1D9A9 0x1D9A9 // 𝦩 SIGNWRITING MOVEMENT-WALLPLANE WAVE HITTING FRONT WALL
#define UC_MACRO_NAME_1D9AA 0x1D9AA // 𝦪 SIGNWRITING ROTATION-WALLPLANE SINGLE HITTING FRONT WALL
#define UC_MACRO_NAME_1D9AB 0x1D9AB // 𝦫 SIGNWRITING ROTATION-WALLPLANE DOUBLE HITTING FRONT WALL
#define UC_MACRO_NAME_1D9AC 0x1D9AC // 𝦬 SIGNWRITING ROTATION-WALLPLANE ALTERNATING HITTING FRONT WALL
#define UC_MACRO_NAME_1D9AD 0x1D9AD // 𝦭 SIGNWRITING MOVEMENT-WALLPLANE CURVE HITTING CHEST
#define UC_MACRO_NAME_1D9AE 0x1D9AE // 𝦮 SIGNWRITING MOVEMENT-WALLPLANE HUMP HITTING CHEST
#define UC_MACRO_NAME_1D9AF 0x1D9AF // 𝦯 SIGNWRITING MOVEMENT-WALLPLANE LOOP HITTING CHEST
#define UC_MACRO_NAME_1D9B0 0x1D9B0 // 𝦰 SIGNWRITING MOVEMENT-WALLPLANE WAVE HITTING CHEST
#define UC_MACRO_NAME_1D9B1 0x1D9B1 // 𝦱 SIGNWRITING ROTATION-WALLPLANE SINGLE HITTING CHEST
#define UC_MACRO_NAME_1D9B2 0x1D9B2 // 𝦲 SIGNWRITING ROTATION-WALLPLANE DOUBLE HITTING CHEST
#define UC_MACRO_NAME_1D9B3 0x1D9B3 // 𝦳 SIGNWRITING ROTATION-WALLPLANE ALTERNATING HITTING CHEST
#define UC_MACRO_NAME_1D9B4 0x1D9B4 // 𝦴 SIGNWRITING MOVEMENT-WALLPLANE WAVE DIAGONAL PATH SMALL
#define UC_MACRO_NAME_1D9B5 0x1D9B5 // 𝦵 SIGNWRITING MOVEMENT-WALLPLANE WAVE DIAGONAL PATH MEDIUM
#define UC_MACRO_NAME_1D9B6 0x1D9B6 // 𝦶 SIGNWRITING MOVEMENT-WALLPLANE WAVE DIAGONAL PATH LARGE
#define UC_MACRO_NAME_1D9B7 0x1D9B7 // 𝦷 SIGNWRITING MOVEMENT-FLOORPLANE CURVE HITTING CEILING SMALL
#define UC_MACRO_NAME_1D9B8 0x1D9B8 // 𝦸 SIGNWRITING MOVEMENT-FLOORPLANE CURVE HITTING CEILING LARGE
#define UC_MACRO_NAME_1D9B9 0x1D9B9 // 𝦹 SIGNWRITING MOVEMENT-FLOORPLANE HUMP HITTING CEILING SMALL DOUBLE
#define UC_MACRO_NAME_1D9BA 0x1D9BA // 𝦺 SIGNWRITING MOVEMENT-FLOORPLANE HUMP HITTING CEILING LARGE DOUBLE
#define UC_MACRO_NAME_1D9BB 0x1D9BB // 𝦻 SIGNWRITING MOVEMENT-FLOORPLANE HUMP HITTING CEILING SMALL TRIPLE
#define UC_MACRO_NAME_1D9BC 0x1D9BC // 𝦼 SIGNWRITING MOVEMENT-FLOORPLANE HUMP HITTING CEILING LARGE TRIPLE
#define UC_MACRO_NAME_1D9BD 0x1D9BD // 𝦽 SIGNWRITING MOVEMENT-FLOORPLANE LOOP HITTING CEILING SMALL SINGLE
#define UC_MACRO_NAME_1D9BE 0x1D9BE // 𝦾 SIGNWRITING MOVEMENT-FLOORPLANE LOOP HITTING CEILING LARGE SINGLE
#define UC_MACRO_NAME_1D9BF 0x1D9BF // 𝦿 SIGNWRITING MOVEMENT-FLOORPLANE LOOP HITTING CEILING SMALL DOUBLE
#define UC_MACRO_NAME_1D9C0 0x1D9C0 // 𝧀 SIGNWRITING MOVEMENT-FLOORPLANE LOOP HITTING CEILING LARGE DOUBLE
#define UC_MACRO_NAME_1D9C1 0x1D9C1 // 𝧁 SIGNWRITING MOVEMENT-FLOORPLANE WAVE HITTING CEILING SMALL
#define UC_MACRO_NAME_1D9C2 0x1D9C2 // 𝧂 SIGNWRITING MOVEMENT-FLOORPLANE WAVE HITTING CEILING LARGE
#define UC_MACRO_NAME_1D9C3 0x1D9C3 // 𝧃 SIGNWRITING ROTATION-FLOORPLANE SINGLE HITTING CEILING
#define UC_MACRO_NAME_1D9C4 0x1D9C4 // 𝧄 SIGNWRITING ROTATION-FLOORPLANE DOUBLE HITTING CEILING
#define UC_MACRO_NAME_1D9C5 0x1D9C5 // 𝧅 SIGNWRITING ROTATION-FLOORPLANE ALTERNATING HITTING CEILING
#define UC_MACRO_NAME_1D9C6 0x1D9C6 // 𝧆 SIGNWRITING MOVEMENT-FLOORPLANE CURVE HITTING FLOOR SMALL
#define UC_MACRO_NAME_1D9C7 0x1D9C7 // 𝧇 SIGNWRITING MOVEMENT-FLOORPLANE CURVE HITTING FLOOR LARGE
#define UC_MACRO_NAME_1D9C8 0x1D9C8 // 𝧈 SIGNWRITING MOVEMENT-FLOORPLANE HUMP HITTING FLOOR SMALL DOUBLE
#define UC_MACRO_NAME_1D9C9 0x1D9C9 // 𝧉 SIGNWRITING MOVEMENT-FLOORPLANE HUMP HITTING FLOOR LARGE DOUBLE
#define UC_MACRO_NAME_1D9CA 0x1D9CA // 𝧊 SIGNWRITING MOVEMENT-FLOORPLANE HUMP HITTING FLOOR TRIPLE SMALL TRIPLE
#define UC_MACRO_NAME_1D9CB 0x1D9CB // 𝧋 SIGNWRITING MOVEMENT-FLOORPLANE HUMP HITTING FLOOR TRIPLE LARGE TRIPLE
#define UC_MACRO_NAME_1D9CC 0x1D9CC // 𝧌 SIGNWRITING MOVEMENT-FLOORPLANE LOOP HITTING FLOOR SMALL SINGLE
#define UC_MACRO_NAME_1D9CD 0x1D9CD // 𝧍 SIGNWRITING MOVEMENT-FLOORPLANE LOOP HITTING FLOOR LARGE SINGLE
#define UC_MACRO_NAME_1D9CE 0x1D9CE // 𝧎 SIGNWRITING MOVEMENT-FLOORPLANE LOOP HITTING FLOOR SMALL DOUBLE
#define UC_MACRO_NAME_1D9CF 0x1D9CF // 𝧏 SIGNWRITING MOVEMENT-FLOORPLANE LOOP HITTING FLOOR LARGE DOUBLE
#define UC_MACRO_NAME_1D9D0 0x1D9D0 // 𝧐 SIGNWRITING MOVEMENT-FLOORPLANE WAVE HITTING FLOOR SMALL
#define UC_MACRO_NAME_1D9D1 0x1D9D1 // 𝧑 SIGNWRITING MOVEMENT-FLOORPLANE WAVE HITTING FLOOR LARGE
#define UC_MACRO_NAME_1D9D2 0x1D9D2 // 𝧒 SIGNWRITING ROTATION-FLOORPLANE SINGLE HITTING FLOOR
#define UC_MACRO_NAME_1D9D3 0x1D9D3 // 𝧓 SIGNWRITING ROTATION-FLOORPLANE DOUBLE HITTING FLOOR
#define UC_MACRO_NAME_1D9D4 0x1D9D4 // 𝧔 SIGNWRITING ROTATION-FLOORPLANE ALTERNATING HITTING FLOOR
#define UC_MACRO_NAME_1D9D5 0x1D9D5 // 𝧕 SIGNWRITING MOVEMENT-FLOORPLANE CURVE SMALL
#define UC_MACRO_NAME_1D9D6 0x1D9D6 // 𝧖 SIGNWRITING MOVEMENT-FLOORPLANE CURVE MEDIUM
#define UC_MACRO_NAME_1D9D7 0x1D9D7 // 𝧗 SIGNWRITING MOVEMENT-FLOORPLANE CURVE LARGE
#define UC_MACRO_NAME_1D9D8 0x1D9D8 // 𝧘 SIGNWRITING MOVEMENT-FLOORPLANE CURVE LARGEST
#define UC_MACRO_NAME_1D9D9 0x1D9D9 // 𝧙 SIGNWRITING MOVEMENT-FLOORPLANE CURVE COMBINED
#define UC_MACRO_NAME_1D9DA 0x1D9DA // 𝧚 SIGNWRITING MOVEMENT-FLOORPLANE HUMP SMALL
#define UC_MACRO_NAME_1D9DB 0x1D9DB // 𝧛 SIGNWRITING MOVEMENT-FLOORPLANE LOOP SMALL
#define UC_MACRO_NAME_1D9DC 0x1D9DC // 𝧜 SIGNWRITING MOVEMENT-FLOORPLANE WAVE SNAKE
#define UC_MACRO_NAME_1D9DD 0x1D9DD // 𝧝 SIGNWRITING MOVEMENT-FLOORPLANE WAVE SMALL
#define UC_MACRO_NAME_1D9DE 0x1D9DE // 𝧞 SIGNWRITING MOVEMENT-FLOORPLANE WAVE LARGE
#define UC_MACRO_NAME_1D9DF 0x1D9DF // 𝧟 SIGNWRITING ROTATION-FLOORPLANE SINGLE
#define UC_MACRO_NAME_1D9E0 0x1D9E0 // 𝧠 SIGNWRITING ROTATION-FLOORPLANE DOUBLE
#define UC_MACRO_NAME_1D9E1 0x1D9E1 // 𝧡 SIGNWRITING ROTATION-FLOORPLANE ALTERNATING
#define UC_MACRO_NAME_1D9E2 0x1D9E2 // 𝧢 SIGNWRITING MOVEMENT-FLOORPLANE SHAKING PARALLEL
#define UC_MACRO_NAME_1D9E3 0x1D9E3 // 𝧣 SIGNWRITING MOVEMENT-WALLPLANE ARM CIRCLE SMALL SINGLE
#define UC_MACRO_NAME_1D9E4 0x1D9E4 // 𝧤 SIGNWRITING MOVEMENT-WALLPLANE ARM CIRCLE MEDIUM SINGLE
#define UC_MACRO_NAME_1D9E5 0x1D9E5 // 𝧥 SIGNWRITING MOVEMENT-WALLPLANE ARM CIRCLE SMALL DOUBLE
#define UC_MACRO_NAME_1D9E6 0x1D9E6 // 𝧦 SIGNWRITING MOVEMENT-WALLPLANE ARM CIRCLE MEDIUM DOUBLE
#define UC_MACRO_NAME_1D9E7 0x1D9E7 // 𝧧 SIGNWRITING MOVEMENT-FLOORPLANE ARM CIRCLE HITTING WALL SMALL SINGLE
#define UC_MACRO_NAME_1D9E8 0x1D9E8 // 𝧨 SIGNWRITING MOVEMENT-FLOORPLANE ARM CIRCLE HITTING WALL MEDIUM SINGLE
#define UC_MACRO_NAME_1D9E9 0x1D9E9 // 𝧩 SIGNWRITING MOVEMENT-FLOORPLANE ARM CIRCLE HITTING WALL LARGE SINGLE
#define UC_MACRO_NAME_1D9EA 0x1D9EA // 𝧪 SIGNWRITING MOVEMENT-FLOORPLANE ARM CIRCLE HITTING WALL SMALL DOUBLE
#define UC_MACRO_NAME_1D9EB 0x1D9EB // 𝧫 SIGNWRITING MOVEMENT-FLOORPLANE ARM CIRCLE HITTING WALL MEDIUM DOUBLE
#define UC_MACRO_NAME_1D9EC 0x1D9EC // 𝧬 SIGNWRITING MOVEMENT-FLOORPLANE ARM CIRCLE HITTING WALL LARGE DOUBLE
#define UC_MACRO_NAME_1D9ED 0x1D9ED // 𝧭 SIGNWRITING MOVEMENT-WALLPLANE WRIST CIRCLE FRONT SINGLE
#define UC_MACRO_NAME_1D9EE 0x1D9EE // 𝧮 SIGNWRITING MOVEMENT-WALLPLANE WRIST CIRCLE FRONT DOUBLE
#define UC_MACRO_NAME_1D9EF 0x1D9EF // 𝧯 SIGNWRITING MOVEMENT-FLOORPLANE WRIST CIRCLE HITTING WALL SINGLE
#define UC_MACRO_NAME_1D9F0 0x1D9F0 // 𝧰 SIGNWRITING MOVEMENT-FLOORPLANE WRIST CIRCLE HITTING WALL DOUBLE
#define UC_MACRO_NAME_1D9F1 0x1D9F1 // 𝧱 SIGNWRITING MOVEMENT-WALLPLANE FINGER CIRCLES SINGLE
#define UC_MACRO_NAME_1D9F2 0x1D9F2 // 𝧲 SIGNWRITING MOVEMENT-WALLPLANE FINGER CIRCLES DOUBLE
#define UC_MACRO_NAME_1D9F3 0x1D9F3 // 𝧳 SIGNWRITING MOVEMENT-FLOORPLANE FINGER CIRCLES HITTING WALL SINGLE
#define UC_MACRO_NAME_1D9F4 0x1D9F4 // 𝧴 SIGNWRITING MOVEMENT-FLOORPLANE FINGER CIRCLES HITTING WALL DOUBLE
#define UC_MACRO_NAME_1D9F5 0x1D9F5 // 𝧵 SIGNWRITING DYNAMIC ARROWHEAD SMALL
#define UC_MACRO_NAME_1D9F6 0x1D9F6 // 𝧶 SIGNWRITING DYNAMIC ARROWHEAD LARGE
#define UC_MACRO_NAME_1D9F7 0x1D9F7 // 𝧷 SIGNWRITING DYNAMIC FAST
#define UC_MACRO_NAME_1D9F8 0x1D9F8 // 𝧸 SIGNWRITING DYNAMIC SLOW
#define UC_MACRO_NAME_1D9F9 0x1D9F9 // 𝧹 SIGNWRITING DYNAMIC TENSE
#define UC_MACRO_NAME_1D9FA 0x1D9FA // 𝧺 SIGNWRITING DYNAMIC RELAXED
#define UC_MACRO_NAME_1D9FB 0x1D9FB // 𝧻 SIGNWRITING DYNAMIC SIMULTANEOUS
#define UC_MACRO_NAME_1D9FC 0x1D9FC // 𝧼 SIGNWRITING DYNAMIC SIMULTANEOUS ALTERNATING
#define UC_MACRO_NAME_1D9FD 0x1D9FD // 𝧽 SIGNWRITING DYNAMIC EVERY OTHER TIME
#define UC_MACRO_NAME_1D9FE 0x1D9FE // 𝧾 SIGNWRITING DYNAMIC GRADUAL
#define UC_MACRO_NAME_1D9FF 0x1D9FF // 𝧿 SIGNWRITING HEAD
#define UC_MACRO_NAME_1DA00 0x1DA00 // 𝨀 SIGNWRITING HEAD RIM
#define UC_MACRO_NAME_1DA01 0x1DA01 // 𝨁 SIGNWRITING HEAD MOVEMENT-WALLPLANE STRAIGHT
#define UC_MACRO_NAME_1DA02 0x1DA02 // 𝨂 SIGNWRITING HEAD MOVEMENT-WALLPLANE TILT
#define UC_MACRO_NAME_1DA03 0x1DA03 // 𝨃 SIGNWRITING HEAD MOVEMENT-FLOORPLANE STRAIGHT
#define UC_MACRO_NAME_1DA04 0x1DA04 // 𝨄 SIGNWRITING HEAD MOVEMENT-WALLPLANE CURVE
#define UC_MACRO_NAME_1DA05 0x1DA05 // 𝨅 SIGNWRITING HEAD MOVEMENT-FLOORPLANE CURVE
#define UC_MACRO_NAME_1DA06 0x1DA06 // 𝨆 SIGNWRITING HEAD MOVEMENT CIRCLE
#define UC_MACRO_NAME_1DA07 0x1DA07 // 𝨇 SIGNWRITING FACE DIRECTION POSITION NOSE FORWARD TILTING
#define UC_MACRO_NAME_1DA08 0x1DA08 // 𝨈 SIGNWRITING FACE DIRECTION POSITION NOSE UP OR DOWN
#define UC_MACRO_NAME_1DA09 0x1DA09 // 𝨉 SIGNWRITING FACE DIRECTION POSITION NOSE UP OR DOWN TILTING
#define UC_MACRO_NAME_1DA0A 0x1DA0A // 𝨊 SIGNWRITING EYEBROWS STRAIGHT UP
#define UC_MACRO_NAME_1DA0B 0x1DA0B // 𝨋 SIGNWRITING EYEBROWS STRAIGHT NEUTRAL
#define UC_MACRO_NAME_1DA0C 0x1DA0C // 𝨌 SIGNWRITING EYEBROWS STRAIGHT DOWN
#define UC_MACRO_NAME_1DA0D 0x1DA0D // 𝨍 SIGNWRITING DREAMY EYEBROWS NEUTRAL DOWN
#define UC_MACRO_NAME_1DA0E 0x1DA0E // 𝨎 SIGNWRITING DREAMY EYEBROWS DOWN NEUTRAL
#define UC_MACRO_NAME_1DA0F 0x1DA0F // 𝨏 SIGNWRITING DREAMY EYEBROWS UP NEUTRAL
#define UC_MACRO_NAME_1DA10 0x1DA10 // 𝨐 SIGNWRITING DREAMY EYEBROWS NEUTRAL UP
#define UC_MACRO_NAME_1DA11 0x1DA11 // 𝨑 SIGNWRITING FOREHEAD NEUTRAL
#define UC_MACRO_NAME_1DA12 0x1DA12 // 𝨒 SIGNWRITING FOREHEAD CONTACT
#define UC_MACRO_NAME_1DA13 0x1DA13 // 𝨓 SIGNWRITING FOREHEAD WRINKLED
#define UC_MACRO_NAME_1DA14 0x1DA14 // 𝨔 SIGNWRITING EYES OPEN
#define UC_MACRO_NAME_1DA15 0x1DA15 // 𝨕 SIGNWRITING EYES SQUEEZED
#define UC_MACRO_NAME_1DA16 0x1DA16 // 𝨖 SIGNWRITING EYES CLOSED
#define UC_MACRO_NAME_1DA17 0x1DA17 // 𝨗 SIGNWRITING EYE BLINK SINGLE
#define UC_MACRO_NAME_1DA18 0x1DA18 // 𝨘 SIGNWRITING EYE BLINK MULTIPLE
#define UC_MACRO_NAME_1DA19 0x1DA19 // 𝨙 SIGNWRITING EYES HALF OPEN
#define UC_MACRO_NAME_1DA1A 0x1DA1A // 𝨚 SIGNWRITING EYES WIDE OPEN
#define UC_MACRO_NAME_1DA1B 0x1DA1B // 𝨛 SIGNWRITING EYES HALF CLOSED
#define UC_MACRO_NAME_1DA1C 0x1DA1C // 𝨜 SIGNWRITING EYES WIDENING MOVEMENT
#define UC_MACRO_NAME_1DA1D 0x1DA1D // 𝨝 SIGNWRITING EYE WINK
#define UC_MACRO_NAME_1DA1E 0x1DA1E // 𝨞 SIGNWRITING EYELASHES UP
#define UC_MACRO_NAME_1DA1F 0x1DA1F // 𝨟 SIGNWRITING EYELASHES DOWN
#define UC_MACRO_NAME_1DA20 0x1DA20 // 𝨠 SIGNWRITING EYELASHES FLUTTERING
#define UC_MACRO_NAME_1DA21 0x1DA21 // 𝨡 SIGNWRITING EYEGAZE-WALLPLANE STRAIGHT
#define UC_MACRO_NAME_1DA22 0x1DA22 // 𝨢 SIGNWRITING EYEGAZE-WALLPLANE STRAIGHT DOUBLE
#define UC_MACRO_NAME_1DA23 0x1DA23 // 𝨣 SIGNWRITING EYEGAZE-WALLPLANE STRAIGHT ALTERNATING
#define UC_MACRO_NAME_1DA24 0x1DA24 // 𝨤 SIGNWRITING EYEGAZE-FLOORPLANE STRAIGHT
#define UC_MACRO_NAME_1DA25 0x1DA25 // 𝨥 SIGNWRITING EYEGAZE-FLOORPLANE STRAIGHT DOUBLE
#define UC_MACRO_NAME_1DA26 0x1DA26 // 𝨦 SIGNWRITING EYEGAZE-FLOORPLANE STRAIGHT ALTERNATING
#define UC_MACRO_NAME_1DA27 0x1DA27 // 𝨧 SIGNWRITING EYEGAZE-WALLPLANE CURVED
#define UC_MACRO_NAME_1DA28 0x1DA28 // 𝨨 SIGNWRITING EYEGAZE-FLOORPLANE CURVED
#define UC_MACRO_NAME_1DA29 0x1DA29 // 𝨩 SIGNWRITING EYEGAZE-WALLPLANE CIRCLING
#define UC_MACRO_NAME_1DA2A 0x1DA2A // 𝨪 SIGNWRITING CHEEKS PUFFED
#define UC_MACRO_NAME_1DA2B 0x1DA2B // 𝨫 SIGNWRITING CHEEKS NEUTRAL
#define UC_MACRO_NAME_1DA2C 0x1DA2C // 𝨬 SIGNWRITING CHEEKS SUCKED
#define UC_MACRO_NAME_1DA2D 0x1DA2D // 𝨭 SIGNWRITING TENSE CHEEKS HIGH
#define UC_MACRO_NAME_1DA2E 0x1DA2E // 𝨮 SIGNWRITING TENSE CHEEKS MIDDLE
#define UC_MACRO_NAME_1DA2F 0x1DA2F // 𝨯 SIGNWRITING TENSE CHEEKS LOW
#define UC_MACRO_NAME_1DA30 0x1DA30 // 𝨰 SIGNWRITING EARS
#define UC_MACRO_NAME_1DA31 0x1DA31 // 𝨱 SIGNWRITING NOSE NEUTRAL
#define UC_MACRO_NAME_1DA32 0x1DA32 // 𝨲 SIGNWRITING NOSE CONTACT
#define UC_MACRO_NAME_1DA33 0x1DA33 // 𝨳 SIGNWRITING NOSE WRINKLES
#define UC_MACRO_NAME_1DA34 0x1DA34 // 𝨴 SIGNWRITING NOSE WIGGLES
#define UC_MACRO_NAME_1DA35 0x1DA35 // 𝨵 SIGNWRITING AIR BLOWING OUT
#define UC_MACRO_NAME_1DA36 0x1DA36 // 𝨶 SIGNWRITING AIR SUCKING IN
#define UC_MACRO_NAME_1DA37 0x1DA37 // 𝨷 SIGNWRITING AIR BLOW SMALL ROTATIONS
#define UC_MACRO_NAME_1DA38 0x1DA38 // 𝨸 SIGNWRITING AIR SUCK SMALL ROTATIONS
#define UC_MACRO_NAME_1DA39 0x1DA39 // 𝨹 SIGNWRITING BREATH INHALE
#define UC_MACRO_NAME_1DA3A 0x1DA3A // 𝨺 SIGNWRITING BREATH EXHALE
#define UC_MACRO_NAME_1DA3B 0x1DA3B // 𝨻 SIGNWRITING MOUTH CLOSED NEUTRAL
#define UC_MACRO_NAME_1DA3C 0x1DA3C // 𝨼 SIGNWRITING MOUTH CLOSED FORWARD
#define UC_MACRO_NAME_1DA3D 0x1DA3D // 𝨽 SIGNWRITING MOUTH CLOSED CONTACT
#define UC_MACRO_NAME_1DA3E 0x1DA3E // 𝨾 SIGNWRITING MOUTH SMILE
#define UC_MACRO_NAME_1DA3F 0x1DA3F // 𝨿 SIGNWRITING MOUTH SMILE WRINKLED
#define UC_MACRO_NAME_1DA40 0x1DA40 // 𝩀 SIGNWRITING MOUTH SMILE OPEN
#define UC_MACRO_NAME_1DA41 0x1DA41 // 𝩁 SIGNWRITING MOUTH FROWN
#define UC_MACRO_NAME_1DA42 0x1DA42 // 𝩂 SIGNWRITING MOUTH FROWN WRINKLED
#define UC_MACRO_NAME_1DA43 0x1DA43 // 𝩃 SIGNWRITING MOUTH FROWN OPEN
#define UC_MACRO_NAME_1DA44 0x1DA44 // 𝩄 SIGNWRITING MOUTH OPEN CIRCLE
#define UC_MACRO_NAME_1DA45 0x1DA45 // 𝩅 SIGNWRITING MOUTH OPEN FORWARD
#define UC_MACRO_NAME_1DA46 0x1DA46 // 𝩆 SIGNWRITING MOUTH OPEN WRINKLED
#define UC_MACRO_NAME_1DA47 0x1DA47 // 𝩇 SIGNWRITING MOUTH OPEN OVAL
#define UC_MACRO_NAME_1DA48 0x1DA48 // 𝩈 SIGNWRITING MOUTH OPEN OVAL WRINKLED
#define UC_MACRO_NAME_1DA49 0x1DA49 // 𝩉 SIGNWRITING MOUTH OPEN OVAL YAWN
#define UC_MACRO_NAME_1DA4A 0x1DA4A // 𝩊 SIGNWRITING MOUTH OPEN RECTANGLE
#define UC_MACRO_NAME_1DA4B 0x1DA4B // 𝩋 SIGNWRITING MOUTH OPEN RECTANGLE WRINKLED
#define UC_MACRO_NAME_1DA4C 0x1DA4C // 𝩌 SIGNWRITING MOUTH OPEN RECTANGLE YAWN
#define UC_MACRO_NAME_1DA4D 0x1DA4D // 𝩍 SIGNWRITING MOUTH KISS
#define UC_MACRO_NAME_1DA4E 0x1DA4E // 𝩎 SIGNWRITING MOUTH KISS FORWARD
#define UC_MACRO_NAME_1DA4F 0x1DA4F // 𝩏 SIGNWRITING MOUTH KISS WRINKLED
#define UC_MACRO_NAME_1DA50 0x1DA50 // 𝩐 SIGNWRITING MOUTH TENSE
#define UC_MACRO_NAME_1DA51 0x1DA51 // 𝩑 SIGNWRITING MOUTH TENSE FORWARD
#define UC_MACRO_NAME_1DA52 0x1DA52 // 𝩒 SIGNWRITING MOUTH TENSE SUCKED
#define UC_MACRO_NAME_1DA53 0x1DA53 // 𝩓 SIGNWRITING LIPS PRESSED TOGETHER
#define UC_MACRO_NAME_1DA54 0x1DA54 // 𝩔 SIGNWRITING LIP LOWER OVER UPPER
#define UC_MACRO_NAME_1DA55 0x1DA55 // 𝩕 SIGNWRITING LIP UPPER OVER LOWER
#define UC_MACRO_NAME_1DA56 0x1DA56 // 𝩖 SIGNWRITING MOUTH CORNERS
#define UC_MACRO_NAME_1DA57 0x1DA57 // 𝩗 SIGNWRITING MOUTH WRINKLES SINGLE
#define UC_MACRO_NAME_1DA58 0x1DA58 // 𝩘 SIGNWRITING MOUTH WRINKLES DOUBLE
#define UC_MACRO_NAME_1DA59 0x1DA59 // 𝩙 SIGNWRITING TONGUE STICKING OUT FAR
#define UC_MACRO_NAME_1DA5A 0x1DA5A // 𝩚 SIGNWRITING TONGUE LICKING LIPS
#define UC_MACRO_NAME_1DA5B 0x1DA5B // 𝩛 SIGNWRITING TONGUE TIP BETWEEN LIPS
#define UC_MACRO_NAME_1DA5C 0x1DA5C // 𝩜 SIGNWRITING TONGUE TIP TOUCHING INSIDE MOUTH
#define UC_MACRO_NAME_1DA5D 0x1DA5D // 𝩝 SIGNWRITING TONGUE INSIDE MOUTH RELAXED
#define UC_MACRO_NAME_1DA5E 0x1DA5E // 𝩞 SIGNWRITING TONGUE MOVES AGAINST CHEEK
#define UC_MACRO_NAME_1DA5F 0x1DA5F // 𝩟 SIGNWRITING TONGUE CENTRE STICKING OUT
#define UC_MACRO_NAME_1DA60 0x1DA60 // 𝩠 SIGNWRITING TONGUE CENTRE INSIDE MOUTH
#define UC_MACRO_NAME_1DA61 0x1DA61 // 𝩡 SIGNWRITING TEETH
#define UC_MACRO_NAME_1DA62 0x1DA62 // 𝩢 SIGNWRITING TEETH MOVEMENT
#define UC_MACRO_NAME_1DA63 0x1DA63 // 𝩣 SIGNWRITING TEETH ON TONGUE
#define UC_MACRO_NAME_1DA64 0x1DA64 // 𝩤 SIGNWRITING TEETH ON TONGUE MOVEMENT
#define UC_MACRO_NAME_1DA65 0x1DA65 // 𝩥 SIGNWRITING TEETH ON LIPS
#define UC_MACRO_NAME_1DA66 0x1DA66 // 𝩦 SIGNWRITING TEETH ON LIPS MOVEMENT
#define UC_MACRO_NAME_1DA67 0x1DA67 // 𝩧 SIGNWRITING TEETH BITE LIPS
#define UC_MACRO_NAME_1DA68 0x1DA68 // 𝩨 SIGNWRITING MOVEMENT-WALLPLANE JAW
#define UC_MACRO_NAME_1DA69 0x1DA69 // 𝩩 SIGNWRITING MOVEMENT-FLOORPLANE JAW
#define UC_MACRO_NAME_1DA6A 0x1DA6A // 𝩪 SIGNWRITING NECK
#define UC_MACRO_NAME_1DA6B 0x1DA6B // 𝩫 SIGNWRITING HAIR
#define UC_MACRO_NAME_1DA6C 0x1DA6C // 𝩬 SIGNWRITING EXCITEMENT
#define UC_MACRO_NAME_1DA6D 0x1DA6D // 𝩭 SIGNWRITING SHOULDER HIP SPINE
#define UC_MACRO_NAME_1DA6E 0x1DA6E // 𝩮 SIGNWRITING SHOULDER HIP POSITIONS
#define UC_MACRO_NAME_1DA6F 0x1DA6F // 𝩯 SIGNWRITING WALLPLANE SHOULDER HIP MOVE
#define UC_MACRO_NAME_1DA70 0x1DA70 // 𝩰 SIGNWRITING FLOORPLANE SHOULDER HIP MOVE
#define UC_MACRO_NAME_1DA71 0x1DA71 // 𝩱 SIGNWRITING SHOULDER TILTING FROM WAIST
#define UC_MACRO_NAME_1DA72 0x1DA72 // 𝩲 SIGNWRITING TORSO-WALLPLANE STRAIGHT STRETCH
#define UC_MACRO_NAME_1DA73 0x1DA73 // 𝩳 SIGNWRITING TORSO-WALLPLANE CURVED BEND
#define UC_MACRO_NAME_1DA74 0x1DA74 // 𝩴 SIGNWRITING TORSO-FLOORPLANE TWISTING
#define UC_MACRO_NAME_1DA75 0x1DA75 // 𝩵 SIGNWRITING UPPER BODY TILTING FROM HIP JOINTS
#define UC_MACRO_NAME_1DA76 0x1DA76 // 𝩶 SIGNWRITING LIMB COMBINATION
#define UC_MACRO_NAME_1DA77 0x1DA77 // 𝩷 SIGNWRITING LIMB LENGTH-1
#define UC_MACRO_NAME_1DA78 0x1DA78 // 𝩸 SIGNWRITING LIMB LENGTH-2
#define UC_MACRO_NAME_1DA79 0x1DA79 // 𝩹 SIGNWRITING LIMB LENGTH-3
#define UC_MACRO_NAME_1DA7A 0x1DA7A // 𝩺 SIGNWRITING LIMB LENGTH-4
#define UC_MACRO_NAME_1DA7B 0x1DA7B // 𝩻 SIGNWRITING LIMB LENGTH-5
#define UC_MACRO_NAME_1DA7C 0x1DA7C // 𝩼 SIGNWRITING LIMB LENGTH-6
#define UC_MACRO_NAME_1DA7D 0x1DA7D // 𝩽 SIGNWRITING LIMB LENGTH-7
#define UC_MACRO_NAME_1DA7E 0x1DA7E // 𝩾 SIGNWRITING FINGER
#define UC_MACRO_NAME_1DA7F 0x1DA7F // 𝩿 SIGNWRITING LOCATION-WALLPLANE SPACE
#define UC_MACRO_NAME_1DA80 0x1DA80 // 𝪀 SIGNWRITING LOCATION-FLOORPLANE SPACE
#define UC_MACRO_NAME_1DA81 0x1DA81 // 𝪁 SIGNWRITING LOCATION HEIGHT
#define UC_MACRO_NAME_1DA82 0x1DA82 // 𝪂 SIGNWRITING LOCATION WIDTH
#define UC_MACRO_NAME_1DA83 0x1DA83 // 𝪃 SIGNWRITING LOCATION DEPTH
#define UC_MACRO_NAME_1DA84 0x1DA84 // 𝪄 SIGNWRITING LOCATION HEAD NECK
#define UC_MACRO_NAME_1DA85 0x1DA85 // 𝪅 SIGNWRITING LOCATION TORSO
#define UC_MACRO_NAME_1DA86 0x1DA86 // 𝪆 SIGNWRITING LOCATION LIMBS DIGITS
#define UC_MACRO_NAME_1DA87 0x1DA87 // 𝪇 SIGNWRITING COMMA
#define UC_MACRO_NAME_1DA88 0x1DA88 // 𝪈 SIGNWRITING FULL STOP
#define UC_MACRO_NAME_1DA89 0x1DA89 // 𝪉 SIGNWRITING SEMICOLON
#define UC_MACRO_NAME_1DA8A 0x1DA8A // 𝪊 SIGNWRITING COLON
#define UC_MACRO_NAME_1DA8B 0x1DA8B // 𝪋 SIGNWRITING PARENTHESIS
#define UC_MACRO_NAME_1DA9B 0x1DA9B // 𝪛 SIGNWRITING FILL MODIFIER-2
#define UC_MACRO_NAME_1DA9C 0x1DA9C // 𝪜 SIGNWRITING FILL MODIFIER-3
#define UC_MACRO_NAME_1DA9D 0x1DA9D // 𝪝 SIGNWRITING FILL MODIFIER-4
#define UC_MACRO_NAME_1DA9E 0x1DA9E // 𝪞 SIGNWRITING FILL MODIFIER-5
#define UC_MACRO_NAME_1DA9F 0x1DA9F // 𝪟 SIGNWRITING FILL MODIFIER-6
#define UC_MACRO_NAME_1DAA1 0x1DAA1 // 𝪡 SIGNWRITING ROTATION MODIFIER-2
#define UC_MACRO_NAME_1DAA2 0x1DAA2 // 𝪢 SIGNWRITING ROTATION MODIFIER-3
#define UC_MACRO_NAME_1DAA3 0x1DAA3 // 𝪣 SIGNWRITING ROTATION MODIFIER-4
#define UC_MACRO_NAME_1DAA4 0x1DAA4 // 𝪤 SIGNWRITING ROTATION MODIFIER-5
#define UC_MACRO_NAME_1DAA5 0x1DAA5 // 𝪥 SIGNWRITING ROTATION MODIFIER-6
#define UC_MACRO_NAME_1DAA6 0x1DAA6 // 𝪦 SIGNWRITING ROTATION MODIFIER-7
#define UC_MACRO_NAME_1DAA7 0x1DAA7 // 𝪧 SIGNWRITING ROTATION MODIFIER-8
#define UC_MACRO_NAME_1DAA8 0x1DAA8 // 𝪨 SIGNWRITING ROTATION MODIFIER-9
#define UC_MACRO_NAME_1DAA9 0x1DAA9 // 𝪩 SIGNWRITING ROTATION MODIFIER-10
#define UC_MACRO_NAME_1DAAA 0x1DAAA // 𝪪 SIGNWRITING ROTATION MODIFIER-11
#define UC_MACRO_NAME_1DAAB 0x1DAAB // 𝪫 SIGNWRITING ROTATION MODIFIER-12
#define UC_MACRO_NAME_1DAAC 0x1DAAC // 𝪬 SIGNWRITING ROTATION MODIFIER-13
#define UC_MACRO_NAME_1DAAD 0x1DAAD // 𝪭 SIGNWRITING ROTATION MODIFIER-14
#define UC_MACRO_NAME_1DAAE 0x1DAAE // 𝪮 SIGNWRITING ROTATION MODIFIER-15
#define UC_MACRO_NAME_1DAAF 0x1DAAF // 𝪯 SIGNWRITING ROTATION MODIFIER-16


#endif // UC_H_SUTTON_SIGNWRITING
