/*
 * Unicode Block: Sunuwar
 * Range: U+11BC0..U+11BFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * The Sunuwar or Koinch are a Tibeto-Burman ethnic group ( Nepali
 * :सुनुवार जाति| Sunuwār Jāti ), a Kirati tribe native to Nepal , parts
 * of India ( West Bengal and Sikkim ) and southern Bhutan. They speak
 * the Sunuwar language . According to the 2001 census of Nepal, 17% of
 * the tribe follow the Kirant religion and adopt the Mundhum (Kiranti)
 * culture.
 * The Kõinchs (Sunuwar) number 82,705 in total. The term ‘Kõinchs’ is
 * also the name of the mother tongue. Other terms like Mukhiya or Mukhia
 * are exonyms of the tribe. Sunuwar have a distinct language, religion,
 * culture and social customs.
 *
 */
#ifndef UC_H_SUNUWAR
#define UC_H_SUNUWAR

#define UC_MACRO_NAME_11BC0 0x11BC0 //  SUNUWAR LETTER DEVI
#define UC_MACRO_NAME_11BC1 0x11BC1 //  SUNUWAR LETTER TASLA
#define UC_MACRO_NAME_11BC2 0x11BC2 //  SUNUWAR LETTER EKO
#define UC_MACRO_NAME_11BC3 0x11BC3 //  SUNUWAR LETTER IMAR
#define UC_MACRO_NAME_11BC4 0x11BC4 //  SUNUWAR LETTER REU
#define UC_MACRO_NAME_11BC5 0x11BC5 //  SUNUWAR LETTER UTTHI
#define UC_MACRO_NAME_11BC6 0x11BC6 //  SUNUWAR LETTER KIK
#define UC_MACRO_NAME_11BC7 0x11BC7 //  SUNUWAR LETTER MA
#define UC_MACRO_NAME_11BC8 0x11BC8 //  SUNUWAR LETTER APPHO
#define UC_MACRO_NAME_11BC9 0x11BC9 //  SUNUWAR LETTER PIP
#define UC_MACRO_NAME_11BCA 0x11BCA //  SUNUWAR LETTER GIL
#define UC_MACRO_NAME_11BCB 0x11BCB //  SUNUWAR LETTER HAMSO
#define UC_MACRO_NAME_11BCC 0x11BCC //  SUNUWAR LETTER CARMI
#define UC_MACRO_NAME_11BCD 0x11BCD //  SUNUWAR LETTER NAH
#define UC_MACRO_NAME_11BCE 0x11BCE //  SUNUWAR LETTER BUR
#define UC_MACRO_NAME_11BCF 0x11BCF //  SUNUWAR LETTER JYAH
#define UC_MACRO_NAME_11BD0 0x11BD0 //  SUNUWAR LETTER LOACHA
#define UC_MACRO_NAME_11BD1 0x11BD1 //  SUNUWAR LETTER OTTHI
#define UC_MACRO_NAME_11BD2 0x11BD2 //  SUNUWAR LETTER SHYELE
#define UC_MACRO_NAME_11BD3 0x11BD3 //  SUNUWAR LETTER VARCA
#define UC_MACRO_NAME_11BD4 0x11BD4 //  SUNUWAR LETTER YAT
#define UC_MACRO_NAME_11BD5 0x11BD5 //  SUNUWAR LETTER AVA
#define UC_MACRO_NAME_11BD6 0x11BD6 //  SUNUWAR LETTER AAL
#define UC_MACRO_NAME_11BD7 0x11BD7 //  SUNUWAR LETTER DONGA
#define UC_MACRO_NAME_11BD8 0x11BD8 //  SUNUWAR LETTER THARI
#define UC_MACRO_NAME_11BD9 0x11BD9 //  SUNUWAR LETTER PHAR
#define UC_MACRO_NAME_11BDA 0x11BDA //  SUNUWAR LETTER NGAR
#define UC_MACRO_NAME_11BDB 0x11BDB //  SUNUWAR LETTER KHA
#define UC_MACRO_NAME_11BDC 0x11BDC //  SUNUWAR LETTER SHYER
#define UC_MACRO_NAME_11BDD 0x11BDD //  SUNUWAR LETTER CHELAP
#define UC_MACRO_NAME_11BDE 0x11BDE //  SUNUWAR LETTER TENTU
#define UC_MACRO_NAME_11BDF 0x11BDF //  SUNUWAR LETTER THELE
#define UC_MACRO_NAME_11BE0 0x11BE0 //  SUNUWAR LETTER KLOKO
#define UC_MACRO_NAME_11BE1 0x11BE1 //  SUNUWAR SIGN PVO
#define UC_MACRO_NAME_11BF0 0x11BF0 //  SUNUWAR DIGIT ZERO
#define UC_MACRO_NAME_11BF1 0x11BF1 //  SUNUWAR DIGIT ONE
#define UC_MACRO_NAME_11BF2 0x11BF2 //  SUNUWAR DIGIT TWO
#define UC_MACRO_NAME_11BF3 0x11BF3 //  SUNUWAR DIGIT THREE
#define UC_MACRO_NAME_11BF4 0x11BF4 //  SUNUWAR DIGIT FOUR
#define UC_MACRO_NAME_11BF5 0x11BF5 //  SUNUWAR DIGIT FIVE
#define UC_MACRO_NAME_11BF6 0x11BF6 //  SUNUWAR DIGIT SIX
#define UC_MACRO_NAME_11BF7 0x11BF7 //  SUNUWAR DIGIT SEVEN
#define UC_MACRO_NAME_11BF8 0x11BF8 //  SUNUWAR DIGIT EIGHT
#define UC_MACRO_NAME_11BF9 0x11BF9 //  SUNUWAR DIGIT NINE


#endif // UC_H_SUNUWAR
