/*
 * Unicode Block: Symbols and Pictographs Extended-A
 * Range: U+1FA70..U+1FAFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_SYMBOLS_AND_PICTOGRAPHS_EXTENDED_A
#define UC_H_SYMBOLS_AND_PICTOGRAPHS_EXTENDED_A

#define UC_MACRO_NAME_1FA70 0x1FA70 // 🩰 BALLET SHOES
#define UC_MACRO_NAME_1FA71 0x1FA71 // 🩱 ONE-PIECE SWIMSUIT
#define UC_MACRO_NAME_1FA72 0x1FA72 // 🩲 BRIEFS
#define UC_MACRO_NAME_1FA73 0x1FA73 // 🩳 SHORTS
#define UC_MACRO_NAME_1FA74 0x1FA74 // 🩴 THONG SANDAL
#define UC_MACRO_NAME_1FA75 0x1FA75 // 🩵 LIGHT BLUE HEART
#define UC_MACRO_NAME_1FA76 0x1FA76 // 🩶 GREY HEART
#define UC_MACRO_NAME_1FA77 0x1FA77 // 🩷 PINK HEART
#define UC_MACRO_NAME_1FA78 0x1FA78 // 🩸 DROP OF BLOOD
#define UC_MACRO_NAME_1FA79 0x1FA79 // 🩹 ADHESIVE BANDAGE
#define UC_MACRO_NAME_1FA7A 0x1FA7A // 🩺 STETHOSCOPE
#define UC_MACRO_NAME_1FA7B 0x1FA7B // 🩻 X-RAY
#define UC_MACRO_NAME_1FA7C 0x1FA7C // 🩼 CRUTCH
#define UC_MACRO_NAME_1FA80 0x1FA80 // 🪀 YO-YO
#define UC_MACRO_NAME_1FA81 0x1FA81 // 🪁 KITE
#define UC_MACRO_NAME_1FA82 0x1FA82 // 🪂 PARACHUTE
#define UC_MACRO_NAME_1FA83 0x1FA83 // 🪃 BOOMERANG
#define UC_MACRO_NAME_1FA84 0x1FA84 // 🪄 MAGIC WAND
#define UC_MACRO_NAME_1FA85 0x1FA85 // 🪅 PINATA
#define UC_MACRO_NAME_1FA86 0x1FA86 // 🪆 NESTING DOLLS
#define UC_MACRO_NAME_1FA87 0x1FA87 // 🪇 MARACAS
#define UC_MACRO_NAME_1FA88 0x1FA88 // 🪈 FLUTE
#define UC_MACRO_NAME_1FA89 0x1FA89 //  HARP
#define UC_MACRO_NAME_1FA8A 0x1FA8A //  TROMBONE
#define UC_MACRO_NAME_1FA8E 0x1FA8E //  TREASURE CHEST
#define UC_MACRO_NAME_1FA8F 0x1FA8F //  SHOVEL
#define UC_MACRO_NAME_1FA90 0x1FA90 // 🪐 RINGED PLANET
#define UC_MACRO_NAME_1FA91 0x1FA91 // 🪑 CHAIR
#define UC_MACRO_NAME_1FA92 0x1FA92 // 🪒 RAZOR
#define UC_MACRO_NAME_1FA93 0x1FA93 // 🪓 AXE
#define UC_MACRO_NAME_1FA94 0x1FA94 // 🪔 DIYA LAMP
#define UC_MACRO_NAME_1FA95 0x1FA95 // 🪕 BANJO
#define UC_MACRO_NAME_1FA96 0x1FA96 // 🪖 MILITARY HELMET
#define UC_MACRO_NAME_1FA97 0x1FA97 // 🪗 ACCORDION
#define UC_MACRO_NAME_1FA98 0x1FA98 // 🪘 LONG DRUM
#define UC_MACRO_NAME_1FA99 0x1FA99 // 🪙 COIN
#define UC_MACRO_NAME_1FA9A 0x1FA9A // 🪚 CARPENTRY SAW
#define UC_MACRO_NAME_1FA9B 0x1FA9B // 🪛 SCREWDRIVER
#define UC_MACRO_NAME_1FA9C 0x1FA9C // 🪜 LADDER
#define UC_MACRO_NAME_1FA9D 0x1FA9D // 🪝 HOOK
#define UC_MACRO_NAME_1FA9E 0x1FA9E // 🪞 MIRROR
#define UC_MACRO_NAME_1FA9F 0x1FA9F // 🪟 WINDOW
#define UC_MACRO_NAME_1FAA0 0x1FAA0 // 🪠 PLUNGER
#define UC_MACRO_NAME_1FAA1 0x1FAA1 // 🪡 SEWING NEEDLE
#define UC_MACRO_NAME_1FAA2 0x1FAA2 // 🪢 KNOT
#define UC_MACRO_NAME_1FAA3 0x1FAA3 // 🪣 BUCKET
#define UC_MACRO_NAME_1FAA4 0x1FAA4 // 🪤 MOUSE TRAP
#define UC_MACRO_NAME_1FAA5 0x1FAA5 // 🪥 TOOTHBRUSH
#define UC_MACRO_NAME_1FAA6 0x1FAA6 // 🪦 HEADSTONE
#define UC_MACRO_NAME_1FAA7 0x1FAA7 // 🪧 PLACARD
#define UC_MACRO_NAME_1FAA8 0x1FAA8 // 🪨 ROCK
#define UC_MACRO_NAME_1FAA9 0x1FAA9 // 🪩 MIRROR BALL
#define UC_MACRO_NAME_1FAAA 0x1FAAA // 🪪 IDENTIFICATION CARD
#define UC_MACRO_NAME_1FAAB 0x1FAAB // 🪫 LOW BATTERY
#define UC_MACRO_NAME_1FAAC 0x1FAAC // 🪬 HAMSA
#define UC_MACRO_NAME_1FAAD 0x1FAAD // 🪭 FOLDING HAND FAN
#define UC_MACRO_NAME_1FAAE 0x1FAAE // 🪮 HAIR PICK
#define UC_MACRO_NAME_1FAAF 0x1FAAF // 🪯 KHANDA
#define UC_MACRO_NAME_1FAB0 0x1FAB0 // 🪰 FLY
#define UC_MACRO_NAME_1FAB1 0x1FAB1 // 🪱 WORM
#define UC_MACRO_NAME_1FAB2 0x1FAB2 // 🪲 BEETLE
#define UC_MACRO_NAME_1FAB3 0x1FAB3 // 🪳 COCKROACH
#define UC_MACRO_NAME_1FAB4 0x1FAB4 // 🪴 POTTED PLANT
#define UC_MACRO_NAME_1FAB5 0x1FAB5 // 🪵 WOOD
#define UC_MACRO_NAME_1FAB6 0x1FAB6 // 🪶 FEATHER
#define UC_MACRO_NAME_1FAB7 0x1FAB7 // 🪷 LOTUS
#define UC_MACRO_NAME_1FAB8 0x1FAB8 // 🪸 CORAL
#define UC_MACRO_NAME_1FAB9 0x1FAB9 // 🪹 EMPTY NEST
#define UC_MACRO_NAME_1FABA 0x1FABA // 🪺 NEST WITH EGGS
#define UC_MACRO_NAME_1FABB 0x1FABB // 🪻 HYACINTH
#define UC_MACRO_NAME_1FABC 0x1FABC // 🪼 JELLYFISH
#define UC_MACRO_NAME_1FABD 0x1FABD // 🪽 WING
#define UC_MACRO_NAME_1FABE 0x1FABE //  LEAFLESS TREE
#define UC_MACRO_NAME_1FABF 0x1FABF // 🪿 GOOSE
#define UC_MACRO_NAME_1FAC0 0x1FAC0 // 🫀 ANATOMICAL HEART
#define UC_MACRO_NAME_1FAC1 0x1FAC1 // 🫁 LUNGS
#define UC_MACRO_NAME_1FAC2 0x1FAC2 // 🫂 PEOPLE HUGGING
#define UC_MACRO_NAME_1FAC3 0x1FAC3 // 🫃 PREGNANT MAN
#define UC_MACRO_NAME_1FAC4 0x1FAC4 // 🫄 PREGNANT PERSON
#define UC_MACRO_NAME_1FAC5 0x1FAC5 // 🫅 PERSON WITH CROWN
#define UC_MACRO_NAME_1FAC6 0x1FAC6 //  FINGERPRINT
#define UC_MACRO_NAME_1FAC8 0x1FAC8 //  HAIRY CREATURE
#define UC_MACRO_NAME_1FACD 0x1FACD //  ORCA
#define UC_MACRO_NAME_1FACE 0x1FACE // 🫎 MOOSE
#define UC_MACRO_NAME_1FACF 0x1FACF // 🫏 DONKEY
#define UC_MACRO_NAME_1FAD0 0x1FAD0 // 🫐 BLUEBERRIES
#define UC_MACRO_NAME_1FAD1 0x1FAD1 // 🫑 BELL PEPPER
#define UC_MACRO_NAME_1FAD2 0x1FAD2 // 🫒 OLIVE
#define UC_MACRO_NAME_1FAD3 0x1FAD3 // 🫓 FLATBREAD
#define UC_MACRO_NAME_1FAD4 0x1FAD4 // 🫔 TAMALE
#define UC_MACRO_NAME_1FAD5 0x1FAD5 // 🫕 FONDUE
#define UC_MACRO_NAME_1FAD6 0x1FAD6 // 🫖 TEAPOT
#define UC_MACRO_NAME_1FAD7 0x1FAD7 // 🫗 POURING LIQUID
#define UC_MACRO_NAME_1FAD8 0x1FAD8 // 🫘 BEANS
#define UC_MACRO_NAME_1FAD9 0x1FAD9 // 🫙 JAR
#define UC_MACRO_NAME_1FADA 0x1FADA // 🫚 GINGER ROOT
#define UC_MACRO_NAME_1FADB 0x1FADB // 🫛 PEA POD
#define UC_MACRO_NAME_1FADC 0x1FADC //  ROOT VEGETABLE
#define UC_MACRO_NAME_1FADF 0x1FADF //  SPLATTER
#define UC_MACRO_NAME_1FAE0 0x1FAE0 // 🫠 MELTING FACE
#define UC_MACRO_NAME_1FAE1 0x1FAE1 // 🫡 SALUTING FACE
#define UC_MACRO_NAME_1FAE2 0x1FAE2 // 🫢 FACE WITH OPEN EYES AND HAND OVER MOUTH
#define UC_MACRO_NAME_1FAE3 0x1FAE3 // 🫣 FACE WITH PEEKING EYE
#define UC_MACRO_NAME_1FAE4 0x1FAE4 // 🫤 FACE WITH DIAGONAL MOUTH
#define UC_MACRO_NAME_1FAE5 0x1FAE5 // 🫥 DOTTED LINE FACE
#define UC_MACRO_NAME_1FAE6 0x1FAE6 // 🫦 BITING LIP
#define UC_MACRO_NAME_1FAE7 0x1FAE7 // 🫧 BUBBLES
#define UC_MACRO_NAME_1FAE8 0x1FAE8 // 🫨 SHAKING FACE
#define UC_MACRO_NAME_1FAE9 0x1FAE9 //  FACE WITH BAGS UNDER EYES
#define UC_MACRO_NAME_1FAEA 0x1FAEA //  DISTORTED FACE
#define UC_MACRO_NAME_1FAEF 0x1FAEF //  FIGHT CLOUD
#define UC_MACRO_NAME_1FAF0 0x1FAF0 // 🫰 HAND WITH INDEX FINGER AND THUMB CROSSED
#define UC_MACRO_NAME_1FAF1 0x1FAF1 // 🫱 RIGHTWARDS HAND
#define UC_MACRO_NAME_1FAF2 0x1FAF2 // 🫲 LEFTWARDS HAND
#define UC_MACRO_NAME_1FAF3 0x1FAF3 // 🫳 PALM DOWN HAND
#define UC_MACRO_NAME_1FAF4 0x1FAF4 // 🫴 PALM UP HAND
#define UC_MACRO_NAME_1FAF5 0x1FAF5 // 🫵 INDEX POINTING AT THE VIEWER
#define UC_MACRO_NAME_1FAF6 0x1FAF6 // 🫶 HEART HANDS
#define UC_MACRO_NAME_1FAF7 0x1FAF7 // 🫷 LEFTWARDS PUSHING HAND
#define UC_MACRO_NAME_1FAF8 0x1FAF8 // 🫸 RIGHTWARDS PUSHING HAND


#endif // UC_H_SYMBOLS_AND_PICTOGRAPHS_EXTENDED_A
