/*
 * Unicode Block: Supplemental Punctuation
 * Range: U+2E00..U+2E7F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Supplemental Punctuation is a Unicode block containing historic and
 * specialized punctuation characters, including biblical editorial
 * symbols, ancient Greek punctuation, and German dictionary marks.
 * Additional punctuation characters are in the General Punctuation block
 * and sprinkled in dozens of other Unicode blocks.
 *
 */
#ifndef UC_H_SUPPLEMENTAL_PUNCTUATION
#define UC_H_SUPPLEMENTAL_PUNCTUATION

#define UC_MACRO_NAME_2E00 0x2E00 // ⸀ RIGHT ANGLE SUBSTITUTION MARKER
#define UC_MACRO_NAME_2E01 0x2E01 // ⸁ RIGHT ANGLE DOTTED SUBSTITUTION MARKER
#define UC_MACRO_NAME_2E02 0x2E02 // ⸂ LEFT SUBSTITUTION BRACKET
#define UC_MACRO_NAME_2E03 0x2E03 // ⸃ RIGHT SUBSTITUTION BRACKET
#define UC_MACRO_NAME_2E04 0x2E04 // ⸄ LEFT DOTTED SUBSTITUTION BRACKET
#define UC_MACRO_NAME_2E05 0x2E05 // ⸅ RIGHT DOTTED SUBSTITUTION BRACKET
#define UC_MACRO_NAME_2E06 0x2E06 // ⸆ RAISED INTERPOLATION MARKER
#define UC_MACRO_NAME_2E07 0x2E07 // ⸇ RAISED DOTTED INTERPOLATION MARKER
#define UC_MACRO_NAME_2E08 0x2E08 // ⸈ DOTTED TRANSPOSITION MARKER
#define UC_MACRO_NAME_2E09 0x2E09 // ⸉ LEFT TRANSPOSITION BRACKET
#define UC_MACRO_NAME_2E0A 0x2E0A // ⸊ RIGHT TRANSPOSITION BRACKET
#define UC_MACRO_NAME_2E0B 0x2E0B // ⸋ RAISED SQUARE
#define UC_MACRO_NAME_2E0C 0x2E0C // ⸌ LEFT RAISED OMISSION BRACKET
#define UC_MACRO_NAME_2E0D 0x2E0D // ⸍ RIGHT RAISED OMISSION BRACKET
#define UC_MACRO_NAME_2E0E 0x2E0E // ⸎ EDITORIAL CORONIS
#define UC_MACRO_NAME_2E0F 0x2E0F // ⸏ PARAGRAPHOS
#define UC_MACRO_NAME_2E10 0x2E10 // ⸐ FORKED PARAGRAPHOS
#define UC_MACRO_NAME_2E11 0x2E11 // ⸑ REVERSED FORKED PARAGRAPHOS
#define UC_MACRO_NAME_2E12 0x2E12 // ⸒ HYPODIASTOLE
#define UC_MACRO_NAME_2E13 0x2E13 // ⸓ DOTTED OBELOS
#define UC_MACRO_NAME_2E14 0x2E14 // ⸔ DOWNWARDS ANCORA
#define UC_MACRO_NAME_2E15 0x2E15 // ⸕ UPWARDS ANCORA
#define UC_MACRO_NAME_2E16 0x2E16 // ⸖ DOTTED RIGHT-POINTING ANGLE
#define UC_MACRO_NAME_2E17 0x2E17 // ⸗ DOUBLE OBLIQUE HYPHEN
#define UC_MACRO_NAME_2E18 0x2E18 // ⸘ INVERTED INTERROBANG
#define UC_MACRO_NAME_2E19 0x2E19 // ⸙ PALM BRANCH
#define UC_MACRO_NAME_2E1A 0x2E1A // ⸚ HYPHEN WITH DIAERESIS
#define UC_MACRO_NAME_2E1B 0x2E1B // ⸛ TILDE WITH RING ABOVE
#define UC_MACRO_NAME_2E1C 0x2E1C // ⸜ LEFT LOW PARAPHRASE BRACKET
#define UC_MACRO_NAME_2E1D 0x2E1D // ⸝ RIGHT LOW PARAPHRASE BRACKET
#define UC_MACRO_NAME_2E1E 0x2E1E // ⸞ TILDE WITH DOT ABOVE
#define UC_MACRO_NAME_2E1F 0x2E1F // ⸟ TILDE WITH DOT BELOW
#define UC_MACRO_NAME_2E20 0x2E20 // ⸠ LEFT VERTICAL BAR WITH QUILL
#define UC_MACRO_NAME_2E21 0x2E21 // ⸡ RIGHT VERTICAL BAR WITH QUILL
#define UC_MACRO_NAME_2E22 0x2E22 // ⸢ TOP LEFT HALF BRACKET
#define UC_MACRO_NAME_2E23 0x2E23 // ⸣ TOP RIGHT HALF BRACKET
#define UC_MACRO_NAME_2E24 0x2E24 // ⸤ BOTTOM LEFT HALF BRACKET
#define UC_MACRO_NAME_2E25 0x2E25 // ⸥ BOTTOM RIGHT HALF BRACKET
#define UC_MACRO_NAME_2E26 0x2E26 // ⸦ LEFT SIDEWAYS U BRACKET
#define UC_MACRO_NAME_2E27 0x2E27 // ⸧ RIGHT SIDEWAYS U BRACKET
#define UC_MACRO_NAME_2E28 0x2E28 // ⸨ LEFT DOUBLE PARENTHESIS
#define UC_MACRO_NAME_2E29 0x2E29 // ⸩ RIGHT DOUBLE PARENTHESIS
#define UC_MACRO_NAME_2E2A 0x2E2A // ⸪ TWO DOTS OVER ONE DOT PUNCTUATION
#define UC_MACRO_NAME_2E2B 0x2E2B // ⸫ ONE DOT OVER TWO DOTS PUNCTUATION
#define UC_MACRO_NAME_2E2C 0x2E2C // ⸬ SQUARED FOUR DOT PUNCTUATION
#define UC_MACRO_NAME_2E2D 0x2E2D // ⸭ FIVE DOT MARK
#define UC_MACRO_NAME_2E2E 0x2E2E // ⸮ REVERSED QUESTION MARK
#define UC_MACRO_NAME_2E2F 0x2E2F // ⸯ VERTICAL TILDE
#define UC_MACRO_NAME_2E30 0x2E30 // ⸰ RING POINT
#define UC_MACRO_NAME_2E31 0x2E31 // ⸱ WORD SEPARATOR MIDDLE DOT
#define UC_MACRO_NAME_2E32 0x2E32 // ⸲ TURNED COMMA
#define UC_MACRO_NAME_2E33 0x2E33 // ⸳ RAISED DOT
#define UC_MACRO_NAME_2E34 0x2E34 // ⸴ RAISED COMMA
#define UC_MACRO_NAME_2E35 0x2E35 // ⸵ TURNED SEMICOLON
#define UC_MACRO_NAME_2E36 0x2E36 // ⸶ DAGGER WITH LEFT GUARD
#define UC_MACRO_NAME_2E37 0x2E37 // ⸷ DAGGER WITH RIGHT GUARD
#define UC_MACRO_NAME_2E38 0x2E38 // ⸸ TURNED DAGGER
#define UC_MACRO_NAME_2E39 0x2E39 // ⸹ TOP HALF SECTION SIGN
#define UC_MACRO_NAME_2E3A 0x2E3A // ⸺ TWO-EM DASH
#define UC_MACRO_NAME_2E3B 0x2E3B // ⸻ THREE-EM DASH
#define UC_MACRO_NAME_2E3C 0x2E3C // ⸼ STENOGRAPHIC FULL STOP
#define UC_MACRO_NAME_2E3D 0x2E3D // ⸽ VERTICAL SIX DOTS
#define UC_MACRO_NAME_2E3E 0x2E3E // ⸾ WIGGLY VERTICAL LINE
#define UC_MACRO_NAME_2E3F 0x2E3F // ⸿ CAPITULUM
#define UC_MACRO_NAME_2E40 0x2E40 // ⹀ DOUBLE HYPHEN
#define UC_MACRO_NAME_2E41 0x2E41 // ⹁ REVERSED COMMA
#define UC_MACRO_NAME_2E42 0x2E42 // ⹂ DOUBLE LOW-REVERSED-9 QUOTATION MARK
#define UC_MACRO_NAME_2E43 0x2E43 // ⹃ DASH WITH LEFT UPTURN
#define UC_MACRO_NAME_2E44 0x2E44 // ⹄ DOUBLE SUSPENSION MARK
#define UC_MACRO_NAME_2E45 0x2E45 // ⹅ INVERTED LOW KAVYKA
#define UC_MACRO_NAME_2E46 0x2E46 // ⹆ INVERTED LOW KAVYKA WITH KAVYKA ABOVE
#define UC_MACRO_NAME_2E47 0x2E47 // ⹇ LOW KAVYKA
#define UC_MACRO_NAME_2E48 0x2E48 // ⹈ LOW KAVYKA WITH DOT
#define UC_MACRO_NAME_2E49 0x2E49 // ⹉ DOUBLE STACKED COMMA
#define UC_MACRO_NAME_2E4A 0x2E4A // ⹊ DOTTED SOLIDUS
#define UC_MACRO_NAME_2E4B 0x2E4B // ⹋ TRIPLE DAGGER
#define UC_MACRO_NAME_2E4C 0x2E4C // ⹌ MEDIEVAL COMMA
#define UC_MACRO_NAME_2E4D 0x2E4D // ⹍ PARAGRAPHUS MARK
#define UC_MACRO_NAME_2E4E 0x2E4E // ⹎ PUNCTUS ELEVATUS MARK
#define UC_MACRO_NAME_2E4F 0x2E4F // ⹏ CORNISH VERSE DIVIDER
#define UC_MACRO_NAME_2E50 0x2E50 // ⹐ CROSS PATTY WITH RIGHT CROSSBAR
#define UC_MACRO_NAME_2E51 0x2E51 // ⹑ CROSS PATTY WITH LEFT CROSSBAR
#define UC_MACRO_NAME_2E52 0x2E52 // ⹒ TIRONIAN SIGN CAPITAL ET
#define UC_MACRO_NAME_2E53 0x2E53 // ⹓ MEDIEVAL EXCLAMATION MARK
#define UC_MACRO_NAME_2E54 0x2E54 // ⹔ MEDIEVAL QUESTION MARK
#define UC_MACRO_NAME_2E55 0x2E55 // ⹕ LEFT SQUARE BRACKET WITH STROKE
#define UC_MACRO_NAME_2E56 0x2E56 // ⹖ RIGHT SQUARE BRACKET WITH STROKE
#define UC_MACRO_NAME_2E57 0x2E57 // ⹗ LEFT SQUARE BRACKET WITH DOUBLE STROKE
#define UC_MACRO_NAME_2E58 0x2E58 // ⹘ RIGHT SQUARE BRACKET WITH DOUBLE STROKE
#define UC_MACRO_NAME_2E59 0x2E59 // ⹙ TOP HALF LEFT PARENTHESIS
#define UC_MACRO_NAME_2E5A 0x2E5A // ⹚ TOP HALF RIGHT PARENTHESIS
#define UC_MACRO_NAME_2E5B 0x2E5B // ⹛ BOTTOM HALF LEFT PARENTHESIS
#define UC_MACRO_NAME_2E5C 0x2E5C // ⹜ BOTTOM HALF RIGHT PARENTHESIS
#define UC_MACRO_NAME_2E5D 0x2E5D // ⹝ OBLIQUE HYPHEN


#endif // UC_H_SUPPLEMENTAL_PUNCTUATION
