/*
 * Unicode Block: Supplemental Arrows-C
 * Range: U+1F800..U+1F8FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_SUPPLEMENTAL_ARROWS_C
#define UC_H_SUPPLEMENTAL_ARROWS_C

#define UC_MACRO_NAME_1F800 0x1F800 // 🠀 LEFTWARDS ARROW WITH SMALL TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F801 0x1F801 // 🠁 UPWARDS ARROW WITH SMALL TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F802 0x1F802 // 🠂 RIGHTWARDS ARROW WITH SMALL TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F803 0x1F803 // 🠃 DOWNWARDS ARROW WITH SMALL TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F804 0x1F804 // 🠄 LEFTWARDS ARROW WITH MEDIUM TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F805 0x1F805 // 🠅 UPWARDS ARROW WITH MEDIUM TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F806 0x1F806 // 🠆 RIGHTWARDS ARROW WITH MEDIUM TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F807 0x1F807 // 🠇 DOWNWARDS ARROW WITH MEDIUM TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F808 0x1F808 // 🠈 LEFTWARDS ARROW WITH LARGE TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F809 0x1F809 // 🠉 UPWARDS ARROW WITH LARGE TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F80A 0x1F80A // 🠊 RIGHTWARDS ARROW WITH LARGE TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F80B 0x1F80B // 🠋 DOWNWARDS ARROW WITH LARGE TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F810 0x1F810 // 🠐 LEFTWARDS ARROW WITH SMALL EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_1F811 0x1F811 // 🠑 UPWARDS ARROW WITH SMALL EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_1F812 0x1F812 // 🠒 RIGHTWARDS ARROW WITH SMALL EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_1F813 0x1F813 // 🠓 DOWNWARDS ARROW WITH SMALL EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_1F814 0x1F814 // 🠔 LEFTWARDS ARROW WITH EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_1F815 0x1F815 // 🠕 UPWARDS ARROW WITH EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_1F816 0x1F816 // 🠖 RIGHTWARDS ARROW WITH EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_1F817 0x1F817 // 🠗 DOWNWARDS ARROW WITH EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_1F818 0x1F818 // 🠘 HEAVY LEFTWARDS ARROW WITH EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_1F819 0x1F819 // 🠙 HEAVY UPWARDS ARROW WITH EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_1F81A 0x1F81A // 🠚 HEAVY RIGHTWARDS ARROW WITH EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_1F81B 0x1F81B // 🠛 HEAVY DOWNWARDS ARROW WITH EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_1F81C 0x1F81C // 🠜 HEAVY LEFTWARDS ARROW WITH LARGE EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_1F81D 0x1F81D // 🠝 HEAVY UPWARDS ARROW WITH LARGE EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_1F81E 0x1F81E // 🠞 HEAVY RIGHTWARDS ARROW WITH LARGE EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_1F81F 0x1F81F // 🠟 HEAVY DOWNWARDS ARROW WITH LARGE EQUILATERAL ARROWHEAD
#define UC_MACRO_NAME_1F820 0x1F820 // 🠠 LEFTWARDS TRIANGLE-HEADED ARROW WITH NARROW SHAFT
#define UC_MACRO_NAME_1F821 0x1F821 // 🠡 UPWARDS TRIANGLE-HEADED ARROW WITH NARROW SHAFT
#define UC_MACRO_NAME_1F822 0x1F822 // 🠢 RIGHTWARDS TRIANGLE-HEADED ARROW WITH NARROW SHAFT
#define UC_MACRO_NAME_1F823 0x1F823 // 🠣 DOWNWARDS TRIANGLE-HEADED ARROW WITH NARROW SHAFT
#define UC_MACRO_NAME_1F824 0x1F824 // 🠤 LEFTWARDS TRIANGLE-HEADED ARROW WITH MEDIUM SHAFT
#define UC_MACRO_NAME_1F825 0x1F825 // 🠥 UPWARDS TRIANGLE-HEADED ARROW WITH MEDIUM SHAFT
#define UC_MACRO_NAME_1F826 0x1F826 // 🠦 RIGHTWARDS TRIANGLE-HEADED ARROW WITH MEDIUM SHAFT
#define UC_MACRO_NAME_1F827 0x1F827 // 🠧 DOWNWARDS TRIANGLE-HEADED ARROW WITH MEDIUM SHAFT
#define UC_MACRO_NAME_1F828 0x1F828 // 🠨 LEFTWARDS TRIANGLE-HEADED ARROW WITH BOLD SHAFT
#define UC_MACRO_NAME_1F829 0x1F829 // 🠩 UPWARDS TRIANGLE-HEADED ARROW WITH BOLD SHAFT
#define UC_MACRO_NAME_1F82A 0x1F82A // 🠪 RIGHTWARDS TRIANGLE-HEADED ARROW WITH BOLD SHAFT
#define UC_MACRO_NAME_1F82B 0x1F82B // 🠫 DOWNWARDS TRIANGLE-HEADED ARROW WITH BOLD SHAFT
#define UC_MACRO_NAME_1F82C 0x1F82C // 🠬 LEFTWARDS TRIANGLE-HEADED ARROW WITH HEAVY SHAFT
#define UC_MACRO_NAME_1F82D 0x1F82D // 🠭 UPWARDS TRIANGLE-HEADED ARROW WITH HEAVY SHAFT
#define UC_MACRO_NAME_1F82E 0x1F82E // 🠮 RIGHTWARDS TRIANGLE-HEADED ARROW WITH HEAVY SHAFT
#define UC_MACRO_NAME_1F82F 0x1F82F // 🠯 DOWNWARDS TRIANGLE-HEADED ARROW WITH HEAVY SHAFT
#define UC_MACRO_NAME_1F830 0x1F830 // 🠰 LEFTWARDS TRIANGLE-HEADED ARROW WITH VERY HEAVY SHAFT
#define UC_MACRO_NAME_1F831 0x1F831 // 🠱 UPWARDS TRIANGLE-HEADED ARROW WITH VERY HEAVY SHAFT
#define UC_MACRO_NAME_1F832 0x1F832 // 🠲 RIGHTWARDS TRIANGLE-HEADED ARROW WITH VERY HEAVY SHAFT
#define UC_MACRO_NAME_1F833 0x1F833 // 🠳 DOWNWARDS TRIANGLE-HEADED ARROW WITH VERY HEAVY SHAFT
#define UC_MACRO_NAME_1F834 0x1F834 // 🠴 LEFTWARDS FINGER-POST ARROW
#define UC_MACRO_NAME_1F835 0x1F835 // 🠵 UPWARDS FINGER-POST ARROW
#define UC_MACRO_NAME_1F836 0x1F836 // 🠶 RIGHTWARDS FINGER-POST ARROW
#define UC_MACRO_NAME_1F837 0x1F837 // 🠷 DOWNWARDS FINGER-POST ARROW
#define UC_MACRO_NAME_1F838 0x1F838 // 🠸 LEFTWARDS SQUARED ARROW
#define UC_MACRO_NAME_1F839 0x1F839 // 🠹 UPWARDS SQUARED ARROW
#define UC_MACRO_NAME_1F83A 0x1F83A // 🠺 RIGHTWARDS SQUARED ARROW
#define UC_MACRO_NAME_1F83B 0x1F83B // 🠻 DOWNWARDS SQUARED ARROW
#define UC_MACRO_NAME_1F83C 0x1F83C // 🠼 LEFTWARDS COMPRESSED ARROW
#define UC_MACRO_NAME_1F83D 0x1F83D // 🠽 UPWARDS COMPRESSED ARROW
#define UC_MACRO_NAME_1F83E 0x1F83E // 🠾 RIGHTWARDS COMPRESSED ARROW
#define UC_MACRO_NAME_1F83F 0x1F83F // 🠿 DOWNWARDS COMPRESSED ARROW
#define UC_MACRO_NAME_1F840 0x1F840 // 🡀 LEFTWARDS HEAVY COMPRESSED ARROW
#define UC_MACRO_NAME_1F841 0x1F841 // 🡁 UPWARDS HEAVY COMPRESSED ARROW
#define UC_MACRO_NAME_1F842 0x1F842 // 🡂 RIGHTWARDS HEAVY COMPRESSED ARROW
#define UC_MACRO_NAME_1F843 0x1F843 // 🡃 DOWNWARDS HEAVY COMPRESSED ARROW
#define UC_MACRO_NAME_1F844 0x1F844 // 🡄 LEFTWARDS HEAVY ARROW
#define UC_MACRO_NAME_1F845 0x1F845 // 🡅 UPWARDS HEAVY ARROW
#define UC_MACRO_NAME_1F846 0x1F846 // 🡆 RIGHTWARDS HEAVY ARROW
#define UC_MACRO_NAME_1F847 0x1F847 // 🡇 DOWNWARDS HEAVY ARROW
#define UC_MACRO_NAME_1F850 0x1F850 // 🡐 LEFTWARDS SANS-SERIF ARROW
#define UC_MACRO_NAME_1F851 0x1F851 // 🡑 UPWARDS SANS-SERIF ARROW
#define UC_MACRO_NAME_1F852 0x1F852 // 🡒 RIGHTWARDS SANS-SERIF ARROW
#define UC_MACRO_NAME_1F853 0x1F853 // 🡓 DOWNWARDS SANS-SERIF ARROW
#define UC_MACRO_NAME_1F854 0x1F854 // 🡔 NORTH WEST SANS-SERIF ARROW
#define UC_MACRO_NAME_1F855 0x1F855 // 🡕 NORTH EAST SANS-SERIF ARROW
#define UC_MACRO_NAME_1F856 0x1F856 // 🡖 SOUTH EAST SANS-SERIF ARROW
#define UC_MACRO_NAME_1F857 0x1F857 // 🡗 SOUTH WEST SANS-SERIF ARROW
#define UC_MACRO_NAME_1F858 0x1F858 // 🡘 LEFT RIGHT SANS-SERIF ARROW
#define UC_MACRO_NAME_1F859 0x1F859 // 🡙 UP DOWN SANS-SERIF ARROW
#define UC_MACRO_NAME_1F860 0x1F860 // 🡠 WIDE-HEADED LEFTWARDS LIGHT BARB ARROW
#define UC_MACRO_NAME_1F861 0x1F861 // 🡡 WIDE-HEADED UPWARDS LIGHT BARB ARROW
#define UC_MACRO_NAME_1F862 0x1F862 // 🡢 WIDE-HEADED RIGHTWARDS LIGHT BARB ARROW
#define UC_MACRO_NAME_1F863 0x1F863 // 🡣 WIDE-HEADED DOWNWARDS LIGHT BARB ARROW
#define UC_MACRO_NAME_1F864 0x1F864 // 🡤 WIDE-HEADED NORTH WEST LIGHT BARB ARROW
#define UC_MACRO_NAME_1F865 0x1F865 // 🡥 WIDE-HEADED NORTH EAST LIGHT BARB ARROW
#define UC_MACRO_NAME_1F866 0x1F866 // 🡦 WIDE-HEADED SOUTH EAST LIGHT BARB ARROW
#define UC_MACRO_NAME_1F867 0x1F867 // 🡧 WIDE-HEADED SOUTH WEST LIGHT BARB ARROW
#define UC_MACRO_NAME_1F868 0x1F868 // 🡨 WIDE-HEADED LEFTWARDS BARB ARROW
#define UC_MACRO_NAME_1F869 0x1F869 // 🡩 WIDE-HEADED UPWARDS BARB ARROW
#define UC_MACRO_NAME_1F86A 0x1F86A // 🡪 WIDE-HEADED RIGHTWARDS BARB ARROW
#define UC_MACRO_NAME_1F86B 0x1F86B // 🡫 WIDE-HEADED DOWNWARDS BARB ARROW
#define UC_MACRO_NAME_1F86C 0x1F86C // 🡬 WIDE-HEADED NORTH WEST BARB ARROW
#define UC_MACRO_NAME_1F86D 0x1F86D // 🡭 WIDE-HEADED NORTH EAST BARB ARROW
#define UC_MACRO_NAME_1F86E 0x1F86E // 🡮 WIDE-HEADED SOUTH EAST BARB ARROW
#define UC_MACRO_NAME_1F86F 0x1F86F // 🡯 WIDE-HEADED SOUTH WEST BARB ARROW
#define UC_MACRO_NAME_1F870 0x1F870 // 🡰 WIDE-HEADED LEFTWARDS MEDIUM BARB ARROW
#define UC_MACRO_NAME_1F871 0x1F871 // 🡱 WIDE-HEADED UPWARDS MEDIUM BARB ARROW
#define UC_MACRO_NAME_1F872 0x1F872 // 🡲 WIDE-HEADED RIGHTWARDS MEDIUM BARB ARROW
#define UC_MACRO_NAME_1F873 0x1F873 // 🡳 WIDE-HEADED DOWNWARDS MEDIUM BARB ARROW
#define UC_MACRO_NAME_1F874 0x1F874 // 🡴 WIDE-HEADED NORTH WEST MEDIUM BARB ARROW
#define UC_MACRO_NAME_1F875 0x1F875 // 🡵 WIDE-HEADED NORTH EAST MEDIUM BARB ARROW
#define UC_MACRO_NAME_1F876 0x1F876 // 🡶 WIDE-HEADED SOUTH EAST MEDIUM BARB ARROW
#define UC_MACRO_NAME_1F877 0x1F877 // 🡷 WIDE-HEADED SOUTH WEST MEDIUM BARB ARROW
#define UC_MACRO_NAME_1F878 0x1F878 // 🡸 WIDE-HEADED LEFTWARDS HEAVY BARB ARROW
#define UC_MACRO_NAME_1F879 0x1F879 // 🡹 WIDE-HEADED UPWARDS HEAVY BARB ARROW
#define UC_MACRO_NAME_1F87A 0x1F87A // 🡺 WIDE-HEADED RIGHTWARDS HEAVY BARB ARROW
#define UC_MACRO_NAME_1F87B 0x1F87B // 🡻 WIDE-HEADED DOWNWARDS HEAVY BARB ARROW
#define UC_MACRO_NAME_1F87C 0x1F87C // 🡼 WIDE-HEADED NORTH WEST HEAVY BARB ARROW
#define UC_MACRO_NAME_1F87D 0x1F87D // 🡽 WIDE-HEADED NORTH EAST HEAVY BARB ARROW
#define UC_MACRO_NAME_1F87E 0x1F87E // 🡾 WIDE-HEADED SOUTH EAST HEAVY BARB ARROW
#define UC_MACRO_NAME_1F87F 0x1F87F // 🡿 WIDE-HEADED SOUTH WEST HEAVY BARB ARROW
#define UC_MACRO_NAME_1F880 0x1F880 // 🢀 WIDE-HEADED LEFTWARDS VERY HEAVY BARB ARROW
#define UC_MACRO_NAME_1F881 0x1F881 // 🢁 WIDE-HEADED UPWARDS VERY HEAVY BARB ARROW
#define UC_MACRO_NAME_1F882 0x1F882 // 🢂 WIDE-HEADED RIGHTWARDS VERY HEAVY BARB ARROW
#define UC_MACRO_NAME_1F883 0x1F883 // 🢃 WIDE-HEADED DOWNWARDS VERY HEAVY BARB ARROW
#define UC_MACRO_NAME_1F884 0x1F884 // 🢄 WIDE-HEADED NORTH WEST VERY HEAVY BARB ARROW
#define UC_MACRO_NAME_1F885 0x1F885 // 🢅 WIDE-HEADED NORTH EAST VERY HEAVY BARB ARROW
#define UC_MACRO_NAME_1F886 0x1F886 // 🢆 WIDE-HEADED SOUTH EAST VERY HEAVY BARB ARROW
#define UC_MACRO_NAME_1F887 0x1F887 // 🢇 WIDE-HEADED SOUTH WEST VERY HEAVY BARB ARROW
#define UC_MACRO_NAME_1F890 0x1F890 // 🢐 LEFTWARDS TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F891 0x1F891 // 🢑 UPWARDS TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F892 0x1F892 // 🢒 RIGHTWARDS TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F893 0x1F893 // 🢓 DOWNWARDS TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F894 0x1F894 // 🢔 LEFTWARDS WHITE ARROW WITHIN TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F895 0x1F895 // 🢕 UPWARDS WHITE ARROW WITHIN TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F896 0x1F896 // 🢖 RIGHTWARDS WHITE ARROW WITHIN TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F897 0x1F897 // 🢗 DOWNWARDS WHITE ARROW WITHIN TRIANGLE ARROWHEAD
#define UC_MACRO_NAME_1F898 0x1F898 // 🢘 LEFTWARDS ARROW WITH NOTCHED TAIL
#define UC_MACRO_NAME_1F899 0x1F899 // 🢙 UPWARDS ARROW WITH NOTCHED TAIL
#define UC_MACRO_NAME_1F89A 0x1F89A // 🢚 RIGHTWARDS ARROW WITH NOTCHED TAIL
#define UC_MACRO_NAME_1F89B 0x1F89B // 🢛 DOWNWARDS ARROW WITH NOTCHED TAIL
#define UC_MACRO_NAME_1F89C 0x1F89C // 🢜 HEAVY ARROW SHAFT WIDTH ONE
#define UC_MACRO_NAME_1F89D 0x1F89D // 🢝 HEAVY ARROW SHAFT WIDTH TWO THIRDS
#define UC_MACRO_NAME_1F89E 0x1F89E // 🢞 HEAVY ARROW SHAFT WIDTH ONE HALF
#define UC_MACRO_NAME_1F89F 0x1F89F // 🢟 HEAVY ARROW SHAFT WIDTH ONE THIRD
#define UC_MACRO_NAME_1F8A0 0x1F8A0 // 🢠 LEFTWARDS BOTTOM-SHADED WHITE ARROW
#define UC_MACRO_NAME_1F8A1 0x1F8A1 // 🢡 RIGHTWARDS BOTTOM SHADED WHITE ARROW
#define UC_MACRO_NAME_1F8A2 0x1F8A2 // 🢢 LEFTWARDS TOP SHADED WHITE ARROW
#define UC_MACRO_NAME_1F8A3 0x1F8A3 // 🢣 RIGHTWARDS TOP SHADED WHITE ARROW
#define UC_MACRO_NAME_1F8A4 0x1F8A4 // 🢤 LEFTWARDS LEFT-SHADED WHITE ARROW
#define UC_MACRO_NAME_1F8A5 0x1F8A5 // 🢥 RIGHTWARDS RIGHT-SHADED WHITE ARROW
#define UC_MACRO_NAME_1F8A6 0x1F8A6 // 🢦 LEFTWARDS RIGHT-SHADED WHITE ARROW
#define UC_MACRO_NAME_1F8A7 0x1F8A7 // 🢧 RIGHTWARDS LEFT-SHADED WHITE ARROW
#define UC_MACRO_NAME_1F8A8 0x1F8A8 // 🢨 LEFTWARDS BACK-TILTED SHADOWED WHITE ARROW
#define UC_MACRO_NAME_1F8A9 0x1F8A9 // 🢩 RIGHTWARDS BACK-TILTED SHADOWED WHITE ARROW
#define UC_MACRO_NAME_1F8AA 0x1F8AA // 🢪 LEFTWARDS FRONT-TILTED SHADOWED WHITE ARROW
#define UC_MACRO_NAME_1F8AB 0x1F8AB // 🢫 RIGHTWARDS FRONT-TILTED SHADOWED WHITE ARROW
#define UC_MACRO_NAME_1F8AC 0x1F8AC // 🢬 WHITE ARROW SHAFT WIDTH ONE
#define UC_MACRO_NAME_1F8AD 0x1F8AD // 🢭 WHITE ARROW SHAFT WIDTH TWO THIRDS
#define UC_MACRO_NAME_1F8B0 0x1F8B0 // 🢰 ARROW POINTING UPWARDS THEN NORTH WEST
#define UC_MACRO_NAME_1F8B1 0x1F8B1 // 🢱 ARROW POINTING RIGHTWARDS THEN CURVING SOUTH WEST
#define UC_MACRO_NAME_1F8B2 0x1F8B2 //  RIGHTWARDS ARROW WITH LOWER HOOK
#define UC_MACRO_NAME_1F8B3 0x1F8B3 //  DOWNWARDS BLACK ARROW TO BAR
#define UC_MACRO_NAME_1F8B4 0x1F8B4 //  NEGATIVE SQUARED LEFTWARDS ARROW
#define UC_MACRO_NAME_1F8B5 0x1F8B5 //  NEGATIVE SQUARED UPWARDS ARROW
#define UC_MACRO_NAME_1F8B6 0x1F8B6 //  NEGATIVE SQUARED RIGHTWARDS ARROW
#define UC_MACRO_NAME_1F8B7 0x1F8B7 //  NEGATIVE SQUARED DOWNWARDS ARROW
#define UC_MACRO_NAME_1F8B8 0x1F8B8 //  NORTH WEST ARROW FROM BAR
#define UC_MACRO_NAME_1F8B9 0x1F8B9 //  NORTH EAST ARROW FROM BAR
#define UC_MACRO_NAME_1F8BA 0x1F8BA //  SOUTH EAST ARROW FROM BAR
#define UC_MACRO_NAME_1F8BB 0x1F8BB //  SOUTH WEST ARROW FROM BAR
#define UC_MACRO_NAME_1F8C0 0x1F8C0 //  LEFTWARDS ARROW FROM DOWNWARDS ARROW
#define UC_MACRO_NAME_1F8C1 0x1F8C1 //  RIGHTWARDS ARROW FROM DOWNWARDS ARROW
#define UC_MACRO_NAME_1F8D0 0x1F8D0 //  LONG RIGHTWARDS ARROW OVER LONG LEFTWARDS ARROW
#define UC_MACRO_NAME_1F8D1 0x1F8D1 //  LONG RIGHTWARDS HARPOON OVER LONG LEFTWARDS HARPOON
#define UC_MACRO_NAME_1F8D2 0x1F8D2 //  LONG RIGHTWARDS HARPOON ABOVE SHORT LEFTWARDS HARPOON
#define UC_MACRO_NAME_1F8D3 0x1F8D3 //  SHORT RIGHTWARDS HARPOON ABOVE LONG LEFTWARDS HARPOON
#define UC_MACRO_NAME_1F8D4 0x1F8D4 //  LONG LEFTWARDS HARPOON ABOVE SHORT RIGHTWARDS HARPOON
#define UC_MACRO_NAME_1F8D5 0x1F8D5 //  SHORT LEFTWARDS HARPOON ABOVE LONG RIGHTWARDS HARPOON
#define UC_MACRO_NAME_1F8D6 0x1F8D6 //  LONG RIGHTWARDS ARROW THROUGH X
#define UC_MACRO_NAME_1F8D7 0x1F8D7 //  LONG RIGHTWARDS ARROW WITH DOUBLE SLASH
#define UC_MACRO_NAME_1F8D8 0x1F8D8 //  LONG LEFT RIGHT ARROW WITH DEPENDENT LOBE


#endif // UC_H_SUPPLEMENTAL_ARROWS_C
