/*
 * Unicode Block: Supplemental Arrows-A
 * Range: U+27F0..U+27FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_SUPPLEMENTAL_ARROWS_A
#define UC_H_SUPPLEMENTAL_ARROWS_A

#define UC_MACRO_NAME_27F0 0x27F0 // ⟰ UPWARDS QUADRUPLE ARROW
#define UC_MACRO_NAME_27F1 0x27F1 // ⟱ DOWNWARDS QUADRUPLE ARROW
#define UC_MACRO_NAME_27F2 0x27F2 // ⟲ ANTICLOCKWISE GAPPED CIRCLE ARROW
#define UC_MACRO_NAME_27F3 0x27F3 // ⟳ CLOCKWISE GAPPED CIRCLE ARROW
#define UC_MACRO_NAME_27F4 0x27F4 // ⟴ RIGHT ARROW WITH CIRCLED PLUS
#define UC_MACRO_NAME_27F5 0x27F5 // ⟵ LONG LEFTWARDS ARROW
#define UC_MACRO_NAME_27F6 0x27F6 // ⟶ LONG RIGHTWARDS ARROW
#define UC_MACRO_NAME_27F7 0x27F7 // ⟷ LONG LEFT RIGHT ARROW
#define UC_MACRO_NAME_27F8 0x27F8 // ⟸ LONG LEFTWARDS DOUBLE ARROW
#define UC_MACRO_NAME_27F9 0x27F9 // ⟹ LONG RIGHTWARDS DOUBLE ARROW
#define UC_MACRO_NAME_27FA 0x27FA // ⟺ LONG LEFT RIGHT DOUBLE ARROW
#define UC_MACRO_NAME_27FB 0x27FB // ⟻ LONG LEFTWARDS ARROW FROM BAR
#define UC_MACRO_NAME_27FC 0x27FC // ⟼ LONG RIGHTWARDS ARROW FROM BAR
#define UC_MACRO_NAME_27FD 0x27FD // ⟽ LONG LEFTWARDS DOUBLE ARROW FROM BAR
#define UC_MACRO_NAME_27FE 0x27FE // ⟾ LONG RIGHTWARDS DOUBLE ARROW FROM BAR
#define UC_MACRO_NAME_27FF 0x27FF // ⟿ LONG RIGHTWARDS SQUIGGLE ARROW


#endif // UC_H_SUPPLEMENTAL_ARROWS_A
