/*
 * Unicode Block: Spacing Modifier Letters
 * Range: U+02B0..U+02FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Spacing Modifier Letters is a Unicode block containing characters for
 * the IPA , UPA , and other phonetic transcriptions. Included are the
 * IPA tone marks, and modifiers for aspiration and palatalization . The
 * word spacing indicates that these characters occupy their own
 * horizontal space within a line of text. Its block name in Unicode 1.0
 * was simply Modifier Letters .
 *
 */
#ifndef UC_H_SPACING_MODIFIER_LETTERS
#define UC_H_SPACING_MODIFIER_LETTERS

#define UC_MACRO_NAME_2B0 0x02B0 // ʰ MODIFIER LETTER SMALL H
#define UC_MACRO_NAME_2B1 0x02B1 // ʱ MODIFIER LETTER SMALL H WITH HOOK
#define UC_MACRO_NAME_2B2 0x02B2 // ʲ MODIFIER LETTER SMALL J
#define UC_MACRO_NAME_2B3 0x02B3 // ʳ MODIFIER LETTER SMALL R
#define UC_MACRO_NAME_2B4 0x02B4 // ʴ MODIFIER LETTER SMALL TURNED R
#define UC_MACRO_NAME_2B5 0x02B5 // ʵ MODIFIER LETTER SMALL TURNED R WITH HOOK
#define UC_MACRO_NAME_2B6 0x02B6 // ʶ MODIFIER LETTER SMALL CAPITAL INVERTED R
#define UC_MACRO_NAME_2B7 0x02B7 // ʷ MODIFIER LETTER SMALL W
#define UC_MACRO_NAME_2B8 0x02B8 // ʸ MODIFIER LETTER SMALL Y
#define UC_MACRO_NAME_2B9 0x02B9 // ʹ MODIFIER LETTER PRIME
#define UC_MACRO_NAME_2BA 0x02BA // ʺ MODIFIER LETTER DOUBLE PRIME
#define UC_MACRO_NAME_2BB 0x02BB // ʻ MODIFIER LETTER TURNED COMMA
#define UC_MACRO_NAME_2BC 0x02BC // ʼ MODIFIER LETTER APOSTROPHE
#define UC_MACRO_NAME_2BD 0x02BD // ʽ MODIFIER LETTER REVERSED COMMA
#define UC_MACRO_NAME_2BE 0x02BE // ʾ MODIFIER LETTER RIGHT HALF RING
#define UC_MACRO_NAME_2BF 0x02BF // ʿ MODIFIER LETTER LEFT HALF RING
#define UC_MACRO_NAME_2C0 0x02C0 // ˀ MODIFIER LETTER GLOTTAL STOP
#define UC_MACRO_NAME_2C1 0x02C1 // ˁ MODIFIER LETTER REVERSED GLOTTAL STOP
#define UC_MACRO_NAME_2C2 0x02C2 // ˂ MODIFIER LETTER LEFT ARROWHEAD
#define UC_MACRO_NAME_2C3 0x02C3 // ˃ MODIFIER LETTER RIGHT ARROWHEAD
#define UC_MACRO_NAME_2C4 0x02C4 // ˄ MODIFIER LETTER UP ARROWHEAD
#define UC_MACRO_NAME_2C5 0x02C5 // ˅ MODIFIER LETTER DOWN ARROWHEAD
#define UC_MACRO_NAME_2C6 0x02C6 // ˆ MODIFIER LETTER CIRCUMFLEX ACCENT
#define UC_MACRO_NAME_2C7 0x02C7 // ˇ CARON
#define UC_MACRO_NAME_2C8 0x02C8 // ˈ MODIFIER LETTER VERTICAL LINE
#define UC_MACRO_NAME_2C9 0x02C9 // ˉ MODIFIER LETTER MACRON
#define UC_MACRO_NAME_2CA 0x02CA // ˊ MODIFIER LETTER ACUTE ACCENT
#define UC_MACRO_NAME_2CB 0x02CB // ˋ MODIFIER LETTER GRAVE ACCENT
#define UC_MACRO_NAME_2CC 0x02CC // ˌ MODIFIER LETTER LOW VERTICAL LINE
#define UC_MACRO_NAME_2CD 0x02CD // ˍ MODIFIER LETTER LOW MACRON
#define UC_MACRO_NAME_2CE 0x02CE // ˎ MODIFIER LETTER LOW GRAVE ACCENT
#define UC_MACRO_NAME_2CF 0x02CF // ˏ MODIFIER LETTER LOW ACUTE ACCENT
#define UC_MACRO_NAME_2D0 0x02D0 // ː MODIFIER LETTER TRIANGULAR COLON
#define UC_MACRO_NAME_2D1 0x02D1 // ˑ MODIFIER LETTER HALF TRIANGULAR COLON
#define UC_MACRO_NAME_2D2 0x02D2 // ˒ MODIFIER LETTER CENTRED RIGHT HALF RING
#define UC_MACRO_NAME_2D3 0x02D3 // ˓ MODIFIER LETTER CENTRED LEFT HALF RING
#define UC_MACRO_NAME_2D4 0x02D4 // ˔ MODIFIER LETTER UP TACK
#define UC_MACRO_NAME_2D5 0x02D5 // ˕ MODIFIER LETTER DOWN TACK
#define UC_MACRO_NAME_2D6 0x02D6 // ˖ MODIFIER LETTER PLUS SIGN
#define UC_MACRO_NAME_2D7 0x02D7 // ˗ MODIFIER LETTER MINUS SIGN
#define UC_MACRO_NAME_2D8 0x02D8 // ˘ BREVE
#define UC_MACRO_NAME_2D9 0x02D9 // ˙ DOT ABOVE
#define UC_MACRO_NAME_2DA 0x02DA // ˚ RING ABOVE
#define UC_MACRO_NAME_2DB 0x02DB // ˛ OGONEK
#define UC_MACRO_NAME_2DC 0x02DC // ˜ SMALL TILDE
#define UC_MACRO_NAME_2DD 0x02DD // ˝ DOUBLE ACUTE ACCENT
#define UC_MACRO_NAME_2DE 0x02DE // ˞ MODIFIER LETTER RHOTIC HOOK
#define UC_MACRO_NAME_2DF 0x02DF // ˟ MODIFIER LETTER CROSS ACCENT
#define UC_MACRO_NAME_2E0 0x02E0 // ˠ MODIFIER LETTER SMALL GAMMA
#define UC_MACRO_NAME_2E1 0x02E1 // ˡ MODIFIER LETTER SMALL L
#define UC_MACRO_NAME_2E2 0x02E2 // ˢ MODIFIER LETTER SMALL S
#define UC_MACRO_NAME_2E3 0x02E3 // ˣ MODIFIER LETTER SMALL X
#define UC_MACRO_NAME_2E4 0x02E4 // ˤ MODIFIER LETTER SMALL REVERSED GLOTTAL STOP
#define UC_MACRO_NAME_2E5 0x02E5 // ˥ MODIFIER LETTER EXTRA-HIGH TONE BAR
#define UC_MACRO_NAME_2E6 0x02E6 // ˦ MODIFIER LETTER HIGH TONE BAR
#define UC_MACRO_NAME_2E7 0x02E7 // ˧ MODIFIER LETTER MID TONE BAR
#define UC_MACRO_NAME_2E8 0x02E8 // ˨ MODIFIER LETTER LOW TONE BAR
#define UC_MACRO_NAME_2E9 0x02E9 // ˩ MODIFIER LETTER EXTRA-LOW TONE BAR
#define UC_MACRO_NAME_2EA 0x02EA // ˪ MODIFIER LETTER YIN DEPARTING TONE MARK
#define UC_MACRO_NAME_2EB 0x02EB // ˫ MODIFIER LETTER YANG DEPARTING TONE MARK
#define UC_MACRO_NAME_2EC 0x02EC // ˬ MODIFIER LETTER VOICING
#define UC_MACRO_NAME_2ED 0x02ED // ˭ MODIFIER LETTER UNASPIRATED
#define UC_MACRO_NAME_2EE 0x02EE // ˮ MODIFIER LETTER DOUBLE APOSTROPHE
#define UC_MACRO_NAME_2EF 0x02EF // ˯ MODIFIER LETTER LOW DOWN ARROWHEAD
#define UC_MACRO_NAME_2F0 0x02F0 // ˰ MODIFIER LETTER LOW UP ARROWHEAD
#define UC_MACRO_NAME_2F1 0x02F1 // ˱ MODIFIER LETTER LOW LEFT ARROWHEAD
#define UC_MACRO_NAME_2F2 0x02F2 // ˲ MODIFIER LETTER LOW RIGHT ARROWHEAD
#define UC_MACRO_NAME_2F3 0x02F3 // ˳ MODIFIER LETTER LOW RING
#define UC_MACRO_NAME_2F4 0x02F4 // ˴ MODIFIER LETTER MIDDLE GRAVE ACCENT
#define UC_MACRO_NAME_2F5 0x02F5 // ˵ MODIFIER LETTER MIDDLE DOUBLE GRAVE ACCENT
#define UC_MACRO_NAME_2F6 0x02F6 // ˶ MODIFIER LETTER MIDDLE DOUBLE ACUTE ACCENT
#define UC_MACRO_NAME_2F7 0x02F7 // ˷ MODIFIER LETTER LOW TILDE
#define UC_MACRO_NAME_2F8 0x02F8 // ˸ MODIFIER LETTER RAISED COLON
#define UC_MACRO_NAME_2F9 0x02F9 // ˹ MODIFIER LETTER BEGIN HIGH TONE
#define UC_MACRO_NAME_2FA 0x02FA // ˺ MODIFIER LETTER END HIGH TONE
#define UC_MACRO_NAME_2FB 0x02FB // ˻ MODIFIER LETTER BEGIN LOW TONE
#define UC_MACRO_NAME_2FC 0x02FC // ˼ MODIFIER LETTER END LOW TONE
#define UC_MACRO_NAME_2FD 0x02FD // ˽ MODIFIER LETTER SHELF
#define UC_MACRO_NAME_2FE 0x02FE // ˾ MODIFIER LETTER OPEN SHELF
#define UC_MACRO_NAME_2FF 0x02FF // ˿ MODIFIER LETTER LOW LEFT ARROW


#endif // UC_H_SPACING_MODIFIER_LETTERS
