/*
 * Unicode Block: Saurashtra
 * Range: U+A880..U+A8DF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Saurashtra may refer to:
 *
 */
#ifndef UC_H_SAURASHTRA
#define UC_H_SAURASHTRA

#define UC_MACRO_NAME_A880 0xA880 // ꢀ SAURASHTRA SIGN ANUSVARA
#define UC_MACRO_NAME_A881 0xA881 // ꢁ SAURASHTRA SIGN VISARGA
#define UC_MACRO_NAME_A882 0xA882 // ꢂ SAURASHTRA LETTER A
#define UC_MACRO_NAME_A883 0xA883 // ꢃ SAURASHTRA LETTER AA
#define UC_MACRO_NAME_A884 0xA884 // ꢄ SAURASHTRA LETTER I
#define UC_MACRO_NAME_A885 0xA885 // ꢅ SAURASHTRA LETTER II
#define UC_MACRO_NAME_A886 0xA886 // ꢆ SAURASHTRA LETTER U
#define UC_MACRO_NAME_A887 0xA887 // ꢇ SAURASHTRA LETTER UU
#define UC_MACRO_NAME_A888 0xA888 // ꢈ SAURASHTRA LETTER VOCALIC R
#define UC_MACRO_NAME_A889 0xA889 // ꢉ SAURASHTRA LETTER VOCALIC RR
#define UC_MACRO_NAME_A88A 0xA88A // ꢊ SAURASHTRA LETTER VOCALIC L
#define UC_MACRO_NAME_A88B 0xA88B // ꢋ SAURASHTRA LETTER VOCALIC LL
#define UC_MACRO_NAME_A88C 0xA88C // ꢌ SAURASHTRA LETTER E
#define UC_MACRO_NAME_A88D 0xA88D // ꢍ SAURASHTRA LETTER EE
#define UC_MACRO_NAME_A88E 0xA88E // ꢎ SAURASHTRA LETTER AI
#define UC_MACRO_NAME_A88F 0xA88F // ꢏ SAURASHTRA LETTER O
#define UC_MACRO_NAME_A890 0xA890 // ꢐ SAURASHTRA LETTER OO
#define UC_MACRO_NAME_A891 0xA891 // ꢑ SAURASHTRA LETTER AU
#define UC_MACRO_NAME_A892 0xA892 // ꢒ SAURASHTRA LETTER KA
#define UC_MACRO_NAME_A893 0xA893 // ꢓ SAURASHTRA LETTER KHA
#define UC_MACRO_NAME_A894 0xA894 // ꢔ SAURASHTRA LETTER GA
#define UC_MACRO_NAME_A895 0xA895 // ꢕ SAURASHTRA LETTER GHA
#define UC_MACRO_NAME_A896 0xA896 // ꢖ SAURASHTRA LETTER NGA
#define UC_MACRO_NAME_A897 0xA897 // ꢗ SAURASHTRA LETTER CA
#define UC_MACRO_NAME_A898 0xA898 // ꢘ SAURASHTRA LETTER CHA
#define UC_MACRO_NAME_A899 0xA899 // ꢙ SAURASHTRA LETTER JA
#define UC_MACRO_NAME_A89A 0xA89A // ꢚ SAURASHTRA LETTER JHA
#define UC_MACRO_NAME_A89B 0xA89B // ꢛ SAURASHTRA LETTER NYA
#define UC_MACRO_NAME_A89C 0xA89C // ꢜ SAURASHTRA LETTER TTA
#define UC_MACRO_NAME_A89D 0xA89D // ꢝ SAURASHTRA LETTER TTHA
#define UC_MACRO_NAME_A89E 0xA89E // ꢞ SAURASHTRA LETTER DDA
#define UC_MACRO_NAME_A89F 0xA89F // ꢟ SAURASHTRA LETTER DDHA
#define UC_MACRO_NAME_A8A0 0xA8A0 // ꢠ SAURASHTRA LETTER NNA
#define UC_MACRO_NAME_A8A1 0xA8A1 // ꢡ SAURASHTRA LETTER TA
#define UC_MACRO_NAME_A8A2 0xA8A2 // ꢢ SAURASHTRA LETTER THA
#define UC_MACRO_NAME_A8A3 0xA8A3 // ꢣ SAURASHTRA LETTER DA
#define UC_MACRO_NAME_A8A4 0xA8A4 // ꢤ SAURASHTRA LETTER DHA
#define UC_MACRO_NAME_A8A5 0xA8A5 // ꢥ SAURASHTRA LETTER NA
#define UC_MACRO_NAME_A8A6 0xA8A6 // ꢦ SAURASHTRA LETTER PA
#define UC_MACRO_NAME_A8A7 0xA8A7 // ꢧ SAURASHTRA LETTER PHA
#define UC_MACRO_NAME_A8A8 0xA8A8 // ꢨ SAURASHTRA LETTER BA
#define UC_MACRO_NAME_A8A9 0xA8A9 // ꢩ SAURASHTRA LETTER BHA
#define UC_MACRO_NAME_A8AA 0xA8AA // ꢪ SAURASHTRA LETTER MA
#define UC_MACRO_NAME_A8AB 0xA8AB // ꢫ SAURASHTRA LETTER YA
#define UC_MACRO_NAME_A8AC 0xA8AC // ꢬ SAURASHTRA LETTER RA
#define UC_MACRO_NAME_A8AD 0xA8AD // ꢭ SAURASHTRA LETTER LA
#define UC_MACRO_NAME_A8AE 0xA8AE // ꢮ SAURASHTRA LETTER VA
#define UC_MACRO_NAME_A8AF 0xA8AF // ꢯ SAURASHTRA LETTER SHA
#define UC_MACRO_NAME_A8B0 0xA8B0 // ꢰ SAURASHTRA LETTER SSA
#define UC_MACRO_NAME_A8B1 0xA8B1 // ꢱ SAURASHTRA LETTER SA
#define UC_MACRO_NAME_A8B2 0xA8B2 // ꢲ SAURASHTRA LETTER HA
#define UC_MACRO_NAME_A8B3 0xA8B3 // ꢳ SAURASHTRA LETTER LLA
#define UC_MACRO_NAME_A8B4 0xA8B4 // ꢴ SAURASHTRA CONSONANT SIGN HAARU
#define UC_MACRO_NAME_A8B5 0xA8B5 // ꢵ SAURASHTRA VOWEL SIGN AA
#define UC_MACRO_NAME_A8B6 0xA8B6 // ꢶ SAURASHTRA VOWEL SIGN I
#define UC_MACRO_NAME_A8B7 0xA8B7 // ꢷ SAURASHTRA VOWEL SIGN II
#define UC_MACRO_NAME_A8B8 0xA8B8 // ꢸ SAURASHTRA VOWEL SIGN U
#define UC_MACRO_NAME_A8B9 0xA8B9 // ꢹ SAURASHTRA VOWEL SIGN UU
#define UC_MACRO_NAME_A8BA 0xA8BA // ꢺ SAURASHTRA VOWEL SIGN VOCALIC R
#define UC_MACRO_NAME_A8BB 0xA8BB // ꢻ SAURASHTRA VOWEL SIGN VOCALIC RR
#define UC_MACRO_NAME_A8BC 0xA8BC // ꢼ SAURASHTRA VOWEL SIGN VOCALIC L
#define UC_MACRO_NAME_A8BD 0xA8BD // ꢽ SAURASHTRA VOWEL SIGN VOCALIC LL
#define UC_MACRO_NAME_A8BE 0xA8BE // ꢾ SAURASHTRA VOWEL SIGN E
#define UC_MACRO_NAME_A8BF 0xA8BF // ꢿ SAURASHTRA VOWEL SIGN EE
#define UC_MACRO_NAME_A8C0 0xA8C0 // ꣀ SAURASHTRA VOWEL SIGN AI
#define UC_MACRO_NAME_A8C1 0xA8C1 // ꣁ SAURASHTRA VOWEL SIGN O
#define UC_MACRO_NAME_A8C2 0xA8C2 // ꣂ SAURASHTRA VOWEL SIGN OO
#define UC_MACRO_NAME_A8C3 0xA8C3 // ꣃ SAURASHTRA VOWEL SIGN AU
#define UC_MACRO_NAME_A8C4 0xA8C4 // ꣄ SAURASHTRA SIGN VIRAMA
#define UC_MACRO_NAME_A8C5 0xA8C5 // ꣅ SAURASHTRA SIGN CANDRABINDU
#define UC_MACRO_NAME_A8CE 0xA8CE // ꣎ SAURASHTRA DANDA
#define UC_MACRO_NAME_A8CF 0xA8CF // ꣏ SAURASHTRA DOUBLE DANDA
#define UC_MACRO_NAME_A8D0 0xA8D0 // ꣐ SAURASHTRA DIGIT ZERO
#define UC_MACRO_NAME_A8D1 0xA8D1 // ꣑ SAURASHTRA DIGIT ONE
#define UC_MACRO_NAME_A8D2 0xA8D2 // ꣒ SAURASHTRA DIGIT TWO
#define UC_MACRO_NAME_A8D3 0xA8D3 // ꣓ SAURASHTRA DIGIT THREE
#define UC_MACRO_NAME_A8D4 0xA8D4 // ꣔ SAURASHTRA DIGIT FOUR
#define UC_MACRO_NAME_A8D5 0xA8D5 // ꣕ SAURASHTRA DIGIT FIVE
#define UC_MACRO_NAME_A8D6 0xA8D6 // ꣖ SAURASHTRA DIGIT SIX
#define UC_MACRO_NAME_A8D7 0xA8D7 // ꣗ SAURASHTRA DIGIT SEVEN
#define UC_MACRO_NAME_A8D8 0xA8D8 // ꣘ SAURASHTRA DIGIT EIGHT
#define UC_MACRO_NAME_A8D9 0xA8D9 // ꣙ SAURASHTRA DIGIT NINE


#endif // UC_H_SAURASHTRA
