/*
 * Unicode Block: Small Form Variants
 * Range: U+FE50..U+FE6F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Small Form Variants is a Unicode block containing small punctuation
 * characters for compatibility with the Chinese National Standard CNS
 * 11643 . Its block name in Unicode 1.0 was simply Small Variants .
 *
 */
#ifndef UC_H_SMALL_FORM_VARIANTS
#define UC_H_SMALL_FORM_VARIANTS

#define UC_MACRO_NAME_FE50 0xFE50 // ﹐ SMALL COMMA
#define UC_MACRO_NAME_FE51 0xFE51 // ﹑ SMALL IDEOGRAPHIC COMMA
#define UC_MACRO_NAME_FE52 0xFE52 // ﹒ SMALL FULL STOP
#define UC_MACRO_NAME_FE54 0xFE54 // ﹔ SMALL SEMICOLON
#define UC_MACRO_NAME_FE55 0xFE55 // ﹕ SMALL COLON
#define UC_MACRO_NAME_FE56 0xFE56 // ﹖ SMALL QUESTION MARK
#define UC_MACRO_NAME_FE57 0xFE57 // ﹗ SMALL EXCLAMATION MARK
#define UC_MACRO_NAME_FE58 0xFE58 // ﹘ SMALL EM DASH
#define UC_MACRO_NAME_FE59 0xFE59 // ﹙ SMALL LEFT PARENTHESIS
#define UC_MACRO_NAME_FE5A 0xFE5A // ﹚ SMALL RIGHT PARENTHESIS
#define UC_MACRO_NAME_FE5B 0xFE5B // ﹛ SMALL LEFT CURLY BRACKET
#define UC_MACRO_NAME_FE5C 0xFE5C // ﹜ SMALL RIGHT CURLY BRACKET
#define UC_MACRO_NAME_FE5D 0xFE5D // ﹝ SMALL LEFT TORTOISE SHELL BRACKET
#define UC_MACRO_NAME_FE5E 0xFE5E // ﹞ SMALL RIGHT TORTOISE SHELL BRACKET
#define UC_MACRO_NAME_FE5F 0xFE5F // ﹟ SMALL NUMBER SIGN
#define UC_MACRO_NAME_FE60 0xFE60 // ﹠ SMALL AMPERSAND
#define UC_MACRO_NAME_FE61 0xFE61 // ﹡ SMALL ASTERISK
#define UC_MACRO_NAME_FE62 0xFE62 // ﹢ SMALL PLUS SIGN
#define UC_MACRO_NAME_FE63 0xFE63 // ﹣ SMALL HYPHEN-MINUS
#define UC_MACRO_NAME_FE64 0xFE64 // ﹤ SMALL LESS-THAN SIGN
#define UC_MACRO_NAME_FE65 0xFE65 // ﹥ SMALL GREATER-THAN SIGN
#define UC_MACRO_NAME_FE66 0xFE66 // ﹦ SMALL EQUALS SIGN
#define UC_MACRO_NAME_FE68 0xFE68 // ﹨ SMALL REVERSE SOLIDUS
#define UC_MACRO_NAME_FE69 0xFE69 // ﹩ SMALL DOLLAR SIGN
#define UC_MACRO_NAME_FE6A 0xFE6A // ﹪ SMALL PERCENT SIGN
#define UC_MACRO_NAME_FE6B 0xFE6B // ﹫ SMALL COMMERCIAL AT


#endif // UC_H_SMALL_FORM_VARIANTS
