/*
 * Unicode Block: Telugu
 * Range: U+0C00..U+0C7F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Telugu may refer to:
 *
 */
#ifndef UC_H_TELUGU
#define UC_H_TELUGU

#define UC_MACRO_NAME_C00 0x0C00 // ఀ TELUGU SIGN COMBINING CANDRABINDU ABOVE
#define UC_MACRO_NAME_C01 0x0C01 // ఁ TELUGU SIGN CANDRABINDU
#define UC_MACRO_NAME_C02 0x0C02 // ం TELUGU SIGN ANUSVARA
#define UC_MACRO_NAME_C03 0x0C03 // ః TELUGU SIGN VISARGA
#define UC_MACRO_NAME_C04 0x0C04 // ఄ TELUGU SIGN COMBINING ANUSVARA ABOVE
#define UC_MACRO_NAME_C05 0x0C05 // అ TELUGU LETTER A
#define UC_MACRO_NAME_C06 0x0C06 // ఆ TELUGU LETTER AA
#define UC_MACRO_NAME_C07 0x0C07 // ఇ TELUGU LETTER I
#define UC_MACRO_NAME_C08 0x0C08 // ఈ TELUGU LETTER II
#define UC_MACRO_NAME_C09 0x0C09 // ఉ TELUGU LETTER U
#define UC_MACRO_NAME_C0A 0x0C0A // ఊ TELUGU LETTER UU
#define UC_MACRO_NAME_C0B 0x0C0B // ఋ TELUGU LETTER VOCALIC R
#define UC_MACRO_NAME_C0C 0x0C0C // ఌ TELUGU LETTER VOCALIC L
#define UC_MACRO_NAME_C0E 0x0C0E // ఎ TELUGU LETTER E
#define UC_MACRO_NAME_C0F 0x0C0F // ఏ TELUGU LETTER EE
#define UC_MACRO_NAME_C10 0x0C10 // ఐ TELUGU LETTER AI
#define UC_MACRO_NAME_C12 0x0C12 // ఒ TELUGU LETTER O
#define UC_MACRO_NAME_C13 0x0C13 // ఓ TELUGU LETTER OO
#define UC_MACRO_NAME_C14 0x0C14 // ఔ TELUGU LETTER AU
#define UC_MACRO_NAME_C15 0x0C15 // క TELUGU LETTER KA
#define UC_MACRO_NAME_C16 0x0C16 // ఖ TELUGU LETTER KHA
#define UC_MACRO_NAME_C17 0x0C17 // గ TELUGU LETTER GA
#define UC_MACRO_NAME_C18 0x0C18 // ఘ TELUGU LETTER GHA
#define UC_MACRO_NAME_C19 0x0C19 // ఙ TELUGU LETTER NGA
#define UC_MACRO_NAME_C1A 0x0C1A // చ TELUGU LETTER CA
#define UC_MACRO_NAME_C1B 0x0C1B // ఛ TELUGU LETTER CHA
#define UC_MACRO_NAME_C1C 0x0C1C // జ TELUGU LETTER JA
#define UC_MACRO_NAME_C1D 0x0C1D // ఝ TELUGU LETTER JHA
#define UC_MACRO_NAME_C1E 0x0C1E // ఞ TELUGU LETTER NYA
#define UC_MACRO_NAME_C1F 0x0C1F // ట TELUGU LETTER TTA
#define UC_MACRO_NAME_C20 0x0C20 // ఠ TELUGU LETTER TTHA
#define UC_MACRO_NAME_C21 0x0C21 // డ TELUGU LETTER DDA
#define UC_MACRO_NAME_C22 0x0C22 // ఢ TELUGU LETTER DDHA
#define UC_MACRO_NAME_C23 0x0C23 // ణ TELUGU LETTER NNA
#define UC_MACRO_NAME_C24 0x0C24 // త TELUGU LETTER TA
#define UC_MACRO_NAME_C25 0x0C25 // థ TELUGU LETTER THA
#define UC_MACRO_NAME_C26 0x0C26 // ద TELUGU LETTER DA
#define UC_MACRO_NAME_C27 0x0C27 // ధ TELUGU LETTER DHA
#define UC_MACRO_NAME_C28 0x0C28 // న TELUGU LETTER NA
#define UC_MACRO_NAME_C2A 0x0C2A // ప TELUGU LETTER PA
#define UC_MACRO_NAME_C2B 0x0C2B // ఫ TELUGU LETTER PHA
#define UC_MACRO_NAME_C2C 0x0C2C // బ TELUGU LETTER BA
#define UC_MACRO_NAME_C2D 0x0C2D // భ TELUGU LETTER BHA
#define UC_MACRO_NAME_C2E 0x0C2E // మ TELUGU LETTER MA
#define UC_MACRO_NAME_C2F 0x0C2F // య TELUGU LETTER YA
#define UC_MACRO_NAME_C30 0x0C30 // ర TELUGU LETTER RA
#define UC_MACRO_NAME_C31 0x0C31 // ఱ TELUGU LETTER RRA
#define UC_MACRO_NAME_C32 0x0C32 // ల TELUGU LETTER LA
#define UC_MACRO_NAME_C33 0x0C33 // ళ TELUGU LETTER LLA
#define UC_MACRO_NAME_C34 0x0C34 // ఴ TELUGU LETTER LLLA
#define UC_MACRO_NAME_C35 0x0C35 // వ TELUGU LETTER VA
#define UC_MACRO_NAME_C36 0x0C36 // శ TELUGU LETTER SHA
#define UC_MACRO_NAME_C37 0x0C37 // ష TELUGU LETTER SSA
#define UC_MACRO_NAME_C38 0x0C38 // స TELUGU LETTER SA
#define UC_MACRO_NAME_C39 0x0C39 // హ TELUGU LETTER HA
#define UC_MACRO_NAME_C3C 0x0C3C // ఼ TELUGU SIGN NUKTA
#define UC_MACRO_NAME_C3D 0x0C3D // ఽ TELUGU SIGN AVAGRAHA
#define UC_MACRO_NAME_C3E 0x0C3E // ా TELUGU VOWEL SIGN AA
#define UC_MACRO_NAME_C3F 0x0C3F // ి TELUGU VOWEL SIGN I
#define UC_MACRO_NAME_C40 0x0C40 // ీ TELUGU VOWEL SIGN II
#define UC_MACRO_NAME_C41 0x0C41 // ు TELUGU VOWEL SIGN U
#define UC_MACRO_NAME_C42 0x0C42 // ూ TELUGU VOWEL SIGN UU
#define UC_MACRO_NAME_C43 0x0C43 // ృ TELUGU VOWEL SIGN VOCALIC R
#define UC_MACRO_NAME_C44 0x0C44 // ౄ TELUGU VOWEL SIGN VOCALIC RR
#define UC_MACRO_NAME_C46 0x0C46 // ె TELUGU VOWEL SIGN E
#define UC_MACRO_NAME_C47 0x0C47 // ే TELUGU VOWEL SIGN EE
#define UC_MACRO_NAME_C48 0x0C48 // ై TELUGU VOWEL SIGN AI
#define UC_MACRO_NAME_C4A 0x0C4A // ొ TELUGU VOWEL SIGN O
#define UC_MACRO_NAME_C4B 0x0C4B // ో TELUGU VOWEL SIGN OO
#define UC_MACRO_NAME_C4C 0x0C4C // ౌ TELUGU VOWEL SIGN AU
#define UC_MACRO_NAME_C4D 0x0C4D // ్ TELUGU SIGN VIRAMA
#define UC_MACRO_NAME_C55 0x0C55 // ౕ TELUGU LENGTH MARK
#define UC_MACRO_NAME_C56 0x0C56 // ౖ TELUGU AI LENGTH MARK
#define UC_MACRO_NAME_C58 0x0C58 // ౘ TELUGU LETTER TSA
#define UC_MACRO_NAME_C59 0x0C59 // ౙ TELUGU LETTER DZA
#define UC_MACRO_NAME_C5A 0x0C5A // ౚ TELUGU LETTER RRRA
#define UC_MACRO_NAME_C5C 0x0C5C //  TELUGU ARCHAIC SHRII
#define UC_MACRO_NAME_C5D 0x0C5D // ౝ TELUGU LETTER NAKAARA POLLU
#define UC_MACRO_NAME_C60 0x0C60 // ౠ TELUGU LETTER VOCALIC RR
#define UC_MACRO_NAME_C61 0x0C61 // ౡ TELUGU LETTER VOCALIC LL
#define UC_MACRO_NAME_C62 0x0C62 // ౢ TELUGU VOWEL SIGN VOCALIC L
#define UC_MACRO_NAME_C63 0x0C63 // ౣ TELUGU VOWEL SIGN VOCALIC LL
#define UC_MACRO_NAME_C66 0x0C66 // ౦ TELUGU DIGIT ZERO
#define UC_MACRO_NAME_C67 0x0C67 // ౧ TELUGU DIGIT ONE
#define UC_MACRO_NAME_C68 0x0C68 // ౨ TELUGU DIGIT TWO
#define UC_MACRO_NAME_C69 0x0C69 // ౩ TELUGU DIGIT THREE
#define UC_MACRO_NAME_C6A 0x0C6A // ౪ TELUGU DIGIT FOUR
#define UC_MACRO_NAME_C6B 0x0C6B // ౫ TELUGU DIGIT FIVE
#define UC_MACRO_NAME_C6C 0x0C6C // ౬ TELUGU DIGIT SIX
#define UC_MACRO_NAME_C6D 0x0C6D // ౭ TELUGU DIGIT SEVEN
#define UC_MACRO_NAME_C6E 0x0C6E // ౮ TELUGU DIGIT EIGHT
#define UC_MACRO_NAME_C6F 0x0C6F // ౯ TELUGU DIGIT NINE
#define UC_MACRO_NAME_C77 0x0C77 // ౷ TELUGU SIGN SIDDHAM
#define UC_MACRO_NAME_C78 0x0C78 // ౸ TELUGU FRACTION DIGIT ZERO FOR ODD POWERS OF FOUR
#define UC_MACRO_NAME_C79 0x0C79 // ౹ TELUGU FRACTION DIGIT ONE FOR ODD POWERS OF FOUR
#define UC_MACRO_NAME_C7A 0x0C7A // ౺ TELUGU FRACTION DIGIT TWO FOR ODD POWERS OF FOUR
#define UC_MACRO_NAME_C7B 0x0C7B // ౻ TELUGU FRACTION DIGIT THREE FOR ODD POWERS OF FOUR
#define UC_MACRO_NAME_C7C 0x0C7C // ౼ TELUGU FRACTION DIGIT ONE FOR EVEN POWERS OF FOUR
#define UC_MACRO_NAME_C7D 0x0C7D // ౽ TELUGU FRACTION DIGIT TWO FOR EVEN POWERS OF FOUR
#define UC_MACRO_NAME_C7E 0x0C7E // ౾ TELUGU FRACTION DIGIT THREE FOR EVEN POWERS OF FOUR
#define UC_MACRO_NAME_C7F 0x0C7F // ౿ TELUGU SIGN TUUMU


#endif // UC_H_TELUGU
