/*
 * Unicode Block: Tibetan
 * Range: U+0F00..U+0FFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Tibetan may mean:
 * Tibetan may additionally refer to:
 *
 */
#ifndef UC_H_TIBETAN
#define UC_H_TIBETAN

#define UC_MACRO_NAME_F00 0x0F00 // ༀ TIBETAN SYLLABLE OM
#define UC_MACRO_NAME_F01 0x0F01 // ༁ TIBETAN MARK GTER YIG MGO TRUNCATED A
#define UC_MACRO_NAME_F02 0x0F02 // ༂ TIBETAN MARK GTER YIG MGO -UM RNAM BCAD MA
#define UC_MACRO_NAME_F03 0x0F03 // ༃ TIBETAN MARK GTER YIG MGO -UM GTER TSHEG MA
#define UC_MACRO_NAME_F04 0x0F04 // ༄ TIBETAN MARK INITIAL YIG MGO MDUN MA
#define UC_MACRO_NAME_F05 0x0F05 // ༅ TIBETAN MARK CLOSING YIG MGO SGAB MA
#define UC_MACRO_NAME_F06 0x0F06 // ༆ TIBETAN MARK CARET YIG MGO PHUR SHAD MA
#define UC_MACRO_NAME_F07 0x0F07 // ༇ TIBETAN MARK YIG MGO TSHEG SHAD MA
#define UC_MACRO_NAME_F08 0x0F08 // ༈ TIBETAN MARK SBRUL SHAD
#define UC_MACRO_NAME_F09 0x0F09 // ༉ TIBETAN MARK BSKUR YIG MGO
#define UC_MACRO_NAME_F0A 0x0F0A // ༊ TIBETAN MARK BKA- SHOG YIG MGO
#define UC_MACRO_NAME_F0B 0x0F0B // ་ TIBETAN MARK INTERSYLLABIC TSHEG
#define UC_MACRO_NAME_F0C 0x0F0C // ༌ TIBETAN MARK DELIMITER TSHEG BSTAR
#define UC_MACRO_NAME_F0D 0x0F0D // ། TIBETAN MARK SHAD
#define UC_MACRO_NAME_F0E 0x0F0E // ༎ TIBETAN MARK NYIS SHAD
#define UC_MACRO_NAME_F0F 0x0F0F // ༏ TIBETAN MARK TSHEG SHAD
#define UC_MACRO_NAME_F10 0x0F10 // ༐ TIBETAN MARK NYIS TSHEG SHAD
#define UC_MACRO_NAME_F11 0x0F11 // ༑ TIBETAN MARK RIN CHEN SPUNGS SHAD
#define UC_MACRO_NAME_F12 0x0F12 // ༒ TIBETAN MARK RGYA GRAM SHAD
#define UC_MACRO_NAME_F13 0x0F13 // ༓ TIBETAN MARK CARET -DZUD RTAGS ME LONG CAN
#define UC_MACRO_NAME_F14 0x0F14 // ༔ TIBETAN MARK GTER TSHEG
#define UC_MACRO_NAME_F15 0x0F15 // ༕ TIBETAN LOGOTYPE SIGN CHAD RTAGS
#define UC_MACRO_NAME_F16 0x0F16 // ༖ TIBETAN LOGOTYPE SIGN LHAG RTAGS
#define UC_MACRO_NAME_F17 0x0F17 // ༗ TIBETAN ASTROLOGICAL SIGN SGRA GCAN -CHAR RTAGS
#define UC_MACRO_NAME_F18 0x0F18 // ༘ TIBETAN ASTROLOGICAL SIGN -KHYUD PA
#define UC_MACRO_NAME_F19 0x0F19 // ༙ TIBETAN ASTROLOGICAL SIGN SDONG TSHUGS
#define UC_MACRO_NAME_F1A 0x0F1A // ༚ TIBETAN SIGN RDEL DKAR GCIG
#define UC_MACRO_NAME_F1B 0x0F1B // ༛ TIBETAN SIGN RDEL DKAR GNYIS
#define UC_MACRO_NAME_F1C 0x0F1C // ༜ TIBETAN SIGN RDEL DKAR GSUM
#define UC_MACRO_NAME_F1D 0x0F1D // ༝ TIBETAN SIGN RDEL NAG GCIG
#define UC_MACRO_NAME_F1E 0x0F1E // ༞ TIBETAN SIGN RDEL NAG GNYIS
#define UC_MACRO_NAME_F1F 0x0F1F // ༟ TIBETAN SIGN RDEL DKAR RDEL NAG
#define UC_MACRO_NAME_F20 0x0F20 // ༠ TIBETAN DIGIT ZERO
#define UC_MACRO_NAME_F21 0x0F21 // ༡ TIBETAN DIGIT ONE
#define UC_MACRO_NAME_F22 0x0F22 // ༢ TIBETAN DIGIT TWO
#define UC_MACRO_NAME_F23 0x0F23 // ༣ TIBETAN DIGIT THREE
#define UC_MACRO_NAME_F24 0x0F24 // ༤ TIBETAN DIGIT FOUR
#define UC_MACRO_NAME_F25 0x0F25 // ༥ TIBETAN DIGIT FIVE
#define UC_MACRO_NAME_F26 0x0F26 // ༦ TIBETAN DIGIT SIX
#define UC_MACRO_NAME_F27 0x0F27 // ༧ TIBETAN DIGIT SEVEN
#define UC_MACRO_NAME_F28 0x0F28 // ༨ TIBETAN DIGIT EIGHT
#define UC_MACRO_NAME_F29 0x0F29 // ༩ TIBETAN DIGIT NINE
#define UC_MACRO_NAME_F2A 0x0F2A // ༪ TIBETAN DIGIT HALF ONE
#define UC_MACRO_NAME_F2B 0x0F2B // ༫ TIBETAN DIGIT HALF TWO
#define UC_MACRO_NAME_F2C 0x0F2C // ༬ TIBETAN DIGIT HALF THREE
#define UC_MACRO_NAME_F2D 0x0F2D // ༭ TIBETAN DIGIT HALF FOUR
#define UC_MACRO_NAME_F2E 0x0F2E // ༮ TIBETAN DIGIT HALF FIVE
#define UC_MACRO_NAME_F2F 0x0F2F // ༯ TIBETAN DIGIT HALF SIX
#define UC_MACRO_NAME_F30 0x0F30 // ༰ TIBETAN DIGIT HALF SEVEN
#define UC_MACRO_NAME_F31 0x0F31 // ༱ TIBETAN DIGIT HALF EIGHT
#define UC_MACRO_NAME_F32 0x0F32 // ༲ TIBETAN DIGIT HALF NINE
#define UC_MACRO_NAME_F33 0x0F33 // ༳ TIBETAN DIGIT HALF ZERO
#define UC_MACRO_NAME_F34 0x0F34 // ༴ TIBETAN MARK BSDUS RTAGS
#define UC_MACRO_NAME_F35 0x0F35 // ༵ TIBETAN MARK NGAS BZUNG NYI ZLA
#define UC_MACRO_NAME_F36 0x0F36 // ༶ TIBETAN MARK CARET -DZUD RTAGS BZHI MIG CAN
#define UC_MACRO_NAME_F37 0x0F37 // ༷ TIBETAN MARK NGAS BZUNG SGOR RTAGS
#define UC_MACRO_NAME_F38 0x0F38 // ༸ TIBETAN MARK CHE MGO
#define UC_MACRO_NAME_F39 0x0F39 // ༹ TIBETAN MARK TSA -PHRU
#define UC_MACRO_NAME_F3A 0x0F3A // ༺ TIBETAN MARK GUG RTAGS GYON
#define UC_MACRO_NAME_F3B 0x0F3B // ༻ TIBETAN MARK GUG RTAGS GYAS
#define UC_MACRO_NAME_F3C 0x0F3C // ༼ TIBETAN MARK ANG KHANG GYON
#define UC_MACRO_NAME_F3D 0x0F3D // ༽ TIBETAN MARK ANG KHANG GYAS
#define UC_MACRO_NAME_F3E 0x0F3E // ༾ TIBETAN SIGN YAR TSHES
#define UC_MACRO_NAME_F3F 0x0F3F // ༿ TIBETAN SIGN MAR TSHES
#define UC_MACRO_NAME_F40 0x0F40 // ཀ TIBETAN LETTER KA
#define UC_MACRO_NAME_F41 0x0F41 // ཁ TIBETAN LETTER KHA
#define UC_MACRO_NAME_F42 0x0F42 // ག TIBETAN LETTER GA
#define UC_MACRO_NAME_F43 0x0F43 // གྷ TIBETAN LETTER GHA
#define UC_MACRO_NAME_F44 0x0F44 // ང TIBETAN LETTER NGA
#define UC_MACRO_NAME_F45 0x0F45 // ཅ TIBETAN LETTER CA
#define UC_MACRO_NAME_F46 0x0F46 // ཆ TIBETAN LETTER CHA
#define UC_MACRO_NAME_F47 0x0F47 // ཇ TIBETAN LETTER JA
#define UC_MACRO_NAME_F49 0x0F49 // ཉ TIBETAN LETTER NYA
#define UC_MACRO_NAME_F4A 0x0F4A // ཊ TIBETAN LETTER TTA
#define UC_MACRO_NAME_F4B 0x0F4B // ཋ TIBETAN LETTER TTHA
#define UC_MACRO_NAME_F4C 0x0F4C // ཌ TIBETAN LETTER DDA
#define UC_MACRO_NAME_F4D 0x0F4D // ཌྷ TIBETAN LETTER DDHA
#define UC_MACRO_NAME_F4E 0x0F4E // ཎ TIBETAN LETTER NNA
#define UC_MACRO_NAME_F4F 0x0F4F // ཏ TIBETAN LETTER TA
#define UC_MACRO_NAME_F50 0x0F50 // ཐ TIBETAN LETTER THA
#define UC_MACRO_NAME_F51 0x0F51 // ད TIBETAN LETTER DA
#define UC_MACRO_NAME_F52 0x0F52 // དྷ TIBETAN LETTER DHA
#define UC_MACRO_NAME_F53 0x0F53 // ན TIBETAN LETTER NA
#define UC_MACRO_NAME_F54 0x0F54 // པ TIBETAN LETTER PA
#define UC_MACRO_NAME_F55 0x0F55 // ཕ TIBETAN LETTER PHA
#define UC_MACRO_NAME_F56 0x0F56 // བ TIBETAN LETTER BA
#define UC_MACRO_NAME_F57 0x0F57 // བྷ TIBETAN LETTER BHA
#define UC_MACRO_NAME_F58 0x0F58 // མ TIBETAN LETTER MA
#define UC_MACRO_NAME_F59 0x0F59 // ཙ TIBETAN LETTER TSA
#define UC_MACRO_NAME_F5A 0x0F5A // ཚ TIBETAN LETTER TSHA
#define UC_MACRO_NAME_F5B 0x0F5B // ཛ TIBETAN LETTER DZA
#define UC_MACRO_NAME_F5C 0x0F5C // ཛྷ TIBETAN LETTER DZHA
#define UC_MACRO_NAME_F5D 0x0F5D // ཝ TIBETAN LETTER WA
#define UC_MACRO_NAME_F5E 0x0F5E // ཞ TIBETAN LETTER ZHA
#define UC_MACRO_NAME_F5F 0x0F5F // ཟ TIBETAN LETTER ZA
#define UC_MACRO_NAME_F60 0x0F60 // འ TIBETAN LETTER -A
#define UC_MACRO_NAME_F61 0x0F61 // ཡ TIBETAN LETTER YA
#define UC_MACRO_NAME_F62 0x0F62 // ར TIBETAN LETTER RA
#define UC_MACRO_NAME_F63 0x0F63 // ལ TIBETAN LETTER LA
#define UC_MACRO_NAME_F64 0x0F64 // ཤ TIBETAN LETTER SHA
#define UC_MACRO_NAME_F65 0x0F65 // ཥ TIBETAN LETTER SSA
#define UC_MACRO_NAME_F66 0x0F66 // ས TIBETAN LETTER SA
#define UC_MACRO_NAME_F67 0x0F67 // ཧ TIBETAN LETTER HA
#define UC_MACRO_NAME_F68 0x0F68 // ཨ TIBETAN LETTER A
#define UC_MACRO_NAME_F69 0x0F69 // ཀྵ TIBETAN LETTER KSSA
#define UC_MACRO_NAME_F6A 0x0F6A // ཪ TIBETAN LETTER FIXED-FORM RA
#define UC_MACRO_NAME_F6B 0x0F6B // ཫ TIBETAN LETTER KKA
#define UC_MACRO_NAME_F6C 0x0F6C // ཬ TIBETAN LETTER RRA
#define UC_MACRO_NAME_F71 0x0F71 // ཱ TIBETAN VOWEL SIGN AA
#define UC_MACRO_NAME_F72 0x0F72 // ི TIBETAN VOWEL SIGN I
#define UC_MACRO_NAME_F73 0x0F73 // ཱི TIBETAN VOWEL SIGN II
#define UC_MACRO_NAME_F74 0x0F74 // ུ TIBETAN VOWEL SIGN U
#define UC_MACRO_NAME_F75 0x0F75 // ཱུ TIBETAN VOWEL SIGN UU
#define UC_MACRO_NAME_F76 0x0F76 // ྲྀ TIBETAN VOWEL SIGN VOCALIC R
#define UC_MACRO_NAME_F77 0x0F77 // ཷ TIBETAN VOWEL SIGN VOCALIC RR
#define UC_MACRO_NAME_F78 0x0F78 // ླྀ TIBETAN VOWEL SIGN VOCALIC L
#define UC_MACRO_NAME_F79 0x0F79 // ཹ TIBETAN VOWEL SIGN VOCALIC LL
#define UC_MACRO_NAME_F7A 0x0F7A // ེ TIBETAN VOWEL SIGN E
#define UC_MACRO_NAME_F7B 0x0F7B // ཻ TIBETAN VOWEL SIGN EE
#define UC_MACRO_NAME_F7C 0x0F7C // ོ TIBETAN VOWEL SIGN O
#define UC_MACRO_NAME_F7D 0x0F7D // ཽ TIBETAN VOWEL SIGN OO
#define UC_MACRO_NAME_F7E 0x0F7E // ཾ TIBETAN SIGN RJES SU NGA RO
#define UC_MACRO_NAME_F7F 0x0F7F // ཿ TIBETAN SIGN RNAM BCAD
#define UC_MACRO_NAME_F80 0x0F80 // ྀ TIBETAN VOWEL SIGN REVERSED I
#define UC_MACRO_NAME_F81 0x0F81 // ཱྀ TIBETAN VOWEL SIGN REVERSED II
#define UC_MACRO_NAME_F82 0x0F82 // ྂ TIBETAN SIGN NYI ZLA NAA DA
#define UC_MACRO_NAME_F83 0x0F83 // ྃ TIBETAN SIGN SNA LDAN
#define UC_MACRO_NAME_F84 0x0F84 // ྄ TIBETAN MARK HALANTA
#define UC_MACRO_NAME_F85 0x0F85 // ྅ TIBETAN MARK PALUTA
#define UC_MACRO_NAME_F86 0x0F86 // ྆ TIBETAN SIGN LCI RTAGS
#define UC_MACRO_NAME_F87 0x0F87 // ྇ TIBETAN SIGN YANG RTAGS
#define UC_MACRO_NAME_F88 0x0F88 // ྈ TIBETAN SIGN LCE TSA CAN
#define UC_MACRO_NAME_F89 0x0F89 // ྉ TIBETAN SIGN MCHU CAN
#define UC_MACRO_NAME_F8A 0x0F8A // ྊ TIBETAN SIGN GRU CAN RGYINGS
#define UC_MACRO_NAME_F8B 0x0F8B // ྋ TIBETAN SIGN GRU MED RGYINGS
#define UC_MACRO_NAME_F8C 0x0F8C // ྌ TIBETAN SIGN INVERTED MCHU CAN
#define UC_MACRO_NAME_F8D 0x0F8D // ྍ TIBETAN SUBJOINED SIGN LCE TSA CAN
#define UC_MACRO_NAME_F8E 0x0F8E // ྎ TIBETAN SUBJOINED SIGN MCHU CAN
#define UC_MACRO_NAME_F8F 0x0F8F // ྏ TIBETAN SUBJOINED SIGN INVERTED MCHU CAN
#define UC_MACRO_NAME_F90 0x0F90 // ྐ TIBETAN SUBJOINED LETTER KA
#define UC_MACRO_NAME_F91 0x0F91 // ྑ TIBETAN SUBJOINED LETTER KHA
#define UC_MACRO_NAME_F92 0x0F92 // ྒ TIBETAN SUBJOINED LETTER GA
#define UC_MACRO_NAME_F93 0x0F93 // ྒྷ TIBETAN SUBJOINED LETTER GHA
#define UC_MACRO_NAME_F94 0x0F94 // ྔ TIBETAN SUBJOINED LETTER NGA
#define UC_MACRO_NAME_F95 0x0F95 // ྕ TIBETAN SUBJOINED LETTER CA
#define UC_MACRO_NAME_F96 0x0F96 // ྖ TIBETAN SUBJOINED LETTER CHA
#define UC_MACRO_NAME_F97 0x0F97 // ྗ TIBETAN SUBJOINED LETTER JA
#define UC_MACRO_NAME_F99 0x0F99 // ྙ TIBETAN SUBJOINED LETTER NYA
#define UC_MACRO_NAME_F9A 0x0F9A // ྚ TIBETAN SUBJOINED LETTER TTA
#define UC_MACRO_NAME_F9B 0x0F9B // ྛ TIBETAN SUBJOINED LETTER TTHA
#define UC_MACRO_NAME_F9C 0x0F9C // ྜ TIBETAN SUBJOINED LETTER DDA
#define UC_MACRO_NAME_F9D 0x0F9D // ྜྷ TIBETAN SUBJOINED LETTER DDHA
#define UC_MACRO_NAME_F9E 0x0F9E // ྞ TIBETAN SUBJOINED LETTER NNA
#define UC_MACRO_NAME_F9F 0x0F9F // ྟ TIBETAN SUBJOINED LETTER TA
#define UC_MACRO_NAME_FA0 0x0FA0 // ྠ TIBETAN SUBJOINED LETTER THA
#define UC_MACRO_NAME_FA1 0x0FA1 // ྡ TIBETAN SUBJOINED LETTER DA
#define UC_MACRO_NAME_FA2 0x0FA2 // ྡྷ TIBETAN SUBJOINED LETTER DHA
#define UC_MACRO_NAME_FA3 0x0FA3 // ྣ TIBETAN SUBJOINED LETTER NA
#define UC_MACRO_NAME_FA4 0x0FA4 // ྤ TIBETAN SUBJOINED LETTER PA
#define UC_MACRO_NAME_FA5 0x0FA5 // ྥ TIBETAN SUBJOINED LETTER PHA
#define UC_MACRO_NAME_FA6 0x0FA6 // ྦ TIBETAN SUBJOINED LETTER BA
#define UC_MACRO_NAME_FA7 0x0FA7 // ྦྷ TIBETAN SUBJOINED LETTER BHA
#define UC_MACRO_NAME_FA8 0x0FA8 // ྨ TIBETAN SUBJOINED LETTER MA
#define UC_MACRO_NAME_FA9 0x0FA9 // ྩ TIBETAN SUBJOINED LETTER TSA
#define UC_MACRO_NAME_FAA 0x0FAA // ྪ TIBETAN SUBJOINED LETTER TSHA
#define UC_MACRO_NAME_FAB 0x0FAB // ྫ TIBETAN SUBJOINED LETTER DZA
#define UC_MACRO_NAME_FAC 0x0FAC // ྫྷ TIBETAN SUBJOINED LETTER DZHA
#define UC_MACRO_NAME_FAD 0x0FAD // ྭ TIBETAN SUBJOINED LETTER WA
#define UC_MACRO_NAME_FAE 0x0FAE // ྮ TIBETAN SUBJOINED LETTER ZHA
#define UC_MACRO_NAME_FAF 0x0FAF // ྯ TIBETAN SUBJOINED LETTER ZA
#define UC_MACRO_NAME_FB0 0x0FB0 // ྰ TIBETAN SUBJOINED LETTER -A
#define UC_MACRO_NAME_FB1 0x0FB1 // ྱ TIBETAN SUBJOINED LETTER YA
#define UC_MACRO_NAME_FB2 0x0FB2 // ྲ TIBETAN SUBJOINED LETTER RA
#define UC_MACRO_NAME_FB3 0x0FB3 // ླ TIBETAN SUBJOINED LETTER LA
#define UC_MACRO_NAME_FB4 0x0FB4 // ྴ TIBETAN SUBJOINED LETTER SHA
#define UC_MACRO_NAME_FB5 0x0FB5 // ྵ TIBETAN SUBJOINED LETTER SSA
#define UC_MACRO_NAME_FB6 0x0FB6 // ྶ TIBETAN SUBJOINED LETTER SA
#define UC_MACRO_NAME_FB7 0x0FB7 // ྷ TIBETAN SUBJOINED LETTER HA
#define UC_MACRO_NAME_FB8 0x0FB8 // ྸ TIBETAN SUBJOINED LETTER A
#define UC_MACRO_NAME_FB9 0x0FB9 // ྐྵ TIBETAN SUBJOINED LETTER KSSA
#define UC_MACRO_NAME_FBA 0x0FBA // ྺ TIBETAN SUBJOINED LETTER FIXED-FORM WA
#define UC_MACRO_NAME_FBB 0x0FBB // ྻ TIBETAN SUBJOINED LETTER FIXED-FORM YA
#define UC_MACRO_NAME_FBC 0x0FBC // ྼ TIBETAN SUBJOINED LETTER FIXED-FORM RA
#define UC_MACRO_NAME_FBE 0x0FBE // ྾ TIBETAN KU RU KHA
#define UC_MACRO_NAME_FBF 0x0FBF // ྿ TIBETAN KU RU KHA BZHI MIG CAN
#define UC_MACRO_NAME_FC0 0x0FC0 // ࿀ TIBETAN CANTILLATION SIGN HEAVY BEAT
#define UC_MACRO_NAME_FC1 0x0FC1 // ࿁ TIBETAN CANTILLATION SIGN LIGHT BEAT
#define UC_MACRO_NAME_FC2 0x0FC2 // ࿂ TIBETAN CANTILLATION SIGN CANG TE-U
#define UC_MACRO_NAME_FC3 0x0FC3 // ࿃ TIBETAN CANTILLATION SIGN SBUB -CHAL
#define UC_MACRO_NAME_FC4 0x0FC4 // ࿄ TIBETAN SYMBOL DRIL BU
#define UC_MACRO_NAME_FC5 0x0FC5 // ࿅ TIBETAN SYMBOL RDO RJE
#define UC_MACRO_NAME_FC6 0x0FC6 // ࿆ TIBETAN SYMBOL PADMA GDAN
#define UC_MACRO_NAME_FC7 0x0FC7 // ࿇ TIBETAN SYMBOL RDO RJE RGYA GRAM
#define UC_MACRO_NAME_FC8 0x0FC8 // ࿈ TIBETAN SYMBOL PHUR PA
#define UC_MACRO_NAME_FC9 0x0FC9 // ࿉ TIBETAN SYMBOL NOR BU
#define UC_MACRO_NAME_FCA 0x0FCA // ࿊ TIBETAN SYMBOL NOR BU NYIS -KHYIL
#define UC_MACRO_NAME_FCB 0x0FCB // ࿋ TIBETAN SYMBOL NOR BU GSUM -KHYIL
#define UC_MACRO_NAME_FCC 0x0FCC // ࿌ TIBETAN SYMBOL NOR BU BZHI -KHYIL
#define UC_MACRO_NAME_FCE 0x0FCE // ࿎ TIBETAN SIGN RDEL NAG RDEL DKAR
#define UC_MACRO_NAME_FCF 0x0FCF // ࿏ TIBETAN SIGN RDEL NAG GSUM
#define UC_MACRO_NAME_FD0 0x0FD0 // ࿐ TIBETAN MARK BSKA- SHOG GI MGO RGYAN
#define UC_MACRO_NAME_FD1 0x0FD1 // ࿑ TIBETAN MARK MNYAM YIG GI MGO RGYAN
#define UC_MACRO_NAME_FD2 0x0FD2 // ࿒ TIBETAN MARK NYIS TSHEG
#define UC_MACRO_NAME_FD3 0x0FD3 // ࿓ TIBETAN MARK INITIAL BRDA RNYING YIG MGO MDUN MA
#define UC_MACRO_NAME_FD4 0x0FD4 // ࿔ TIBETAN MARK CLOSING BRDA RNYING YIG MGO SGAB MA
#define UC_MACRO_NAME_FD5 0x0FD5 // ࿕ RIGHT-FACING SVASTI SIGN
#define UC_MACRO_NAME_FD6 0x0FD6 // ࿖ LEFT-FACING SVASTI SIGN
#define UC_MACRO_NAME_FD7 0x0FD7 // ࿗ RIGHT-FACING SVASTI SIGN WITH DOTS
#define UC_MACRO_NAME_FD8 0x0FD8 // ࿘ LEFT-FACING SVASTI SIGN WITH DOTS
#define UC_MACRO_NAME_FD9 0x0FD9 // ࿙ TIBETAN MARK LEADING MCHAN RTAGS
#define UC_MACRO_NAME_FDA 0x0FDA // ࿚ TIBETAN MARK TRAILING MCHAN RTAGS


#endif // UC_H_TIBETAN
