/*
 * Unicode Block: Tolong Siki
 * Range: U+11DB0..U+11DEF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Tolong Siki is an alphabetic script made specifically for Kurux
 * language in 1999 by Narayan Oraon, a doctor. Many books and magazines
 * have been published in Tolong Siki, and it was officially recognized
 * by the state of Jharkhand in 2007. The Kurukh Literary Society of
 * India has been instrumental in spreading the Tolong Siki script for
 * Kurukh literature.
 * Tolong Siki was added to the Unicode Standard in September 2025 with
 * the release of version 17.0.
 *
 */
#ifndef UC_H_TOLONG_SIKI
#define UC_H_TOLONG_SIKI

#define UC_MACRO_NAME_11DB0 0x11DB0 //  TOLONG SIKI LETTER I
#define UC_MACRO_NAME_11DB1 0x11DB1 //  TOLONG SIKI LETTER E
#define UC_MACRO_NAME_11DB2 0x11DB2 //  TOLONG SIKI LETTER U
#define UC_MACRO_NAME_11DB3 0x11DB3 //  TOLONG SIKI LETTER O
#define UC_MACRO_NAME_11DB4 0x11DB4 //  TOLONG SIKI LETTER A
#define UC_MACRO_NAME_11DB5 0x11DB5 //  TOLONG SIKI LETTER AA
#define UC_MACRO_NAME_11DB6 0x11DB6 //  TOLONG SIKI LETTER P
#define UC_MACRO_NAME_11DB7 0x11DB7 //  TOLONG SIKI LETTER PH
#define UC_MACRO_NAME_11DB8 0x11DB8 //  TOLONG SIKI LETTER B
#define UC_MACRO_NAME_11DB9 0x11DB9 //  TOLONG SIKI LETTER BH
#define UC_MACRO_NAME_11DBA 0x11DBA //  TOLONG SIKI LETTER M
#define UC_MACRO_NAME_11DBB 0x11DBB //  TOLONG SIKI LETTER T
#define UC_MACRO_NAME_11DBC 0x11DBC //  TOLONG SIKI LETTER TH
#define UC_MACRO_NAME_11DBD 0x11DBD //  TOLONG SIKI LETTER D
#define UC_MACRO_NAME_11DBE 0x11DBE //  TOLONG SIKI LETTER DH
#define UC_MACRO_NAME_11DBF 0x11DBF //  TOLONG SIKI LETTER N
#define UC_MACRO_NAME_11DC0 0x11DC0 //  TOLONG SIKI LETTER TT
#define UC_MACRO_NAME_11DC1 0x11DC1 //  TOLONG SIKI LETTER TTH
#define UC_MACRO_NAME_11DC2 0x11DC2 //  TOLONG SIKI LETTER DD
#define UC_MACRO_NAME_11DC3 0x11DC3 //  TOLONG SIKI LETTER DDH
#define UC_MACRO_NAME_11DC4 0x11DC4 //  TOLONG SIKI LETTER NN
#define UC_MACRO_NAME_11DC5 0x11DC5 //  TOLONG SIKI LETTER C
#define UC_MACRO_NAME_11DC6 0x11DC6 //  TOLONG SIKI LETTER CH
#define UC_MACRO_NAME_11DC7 0x11DC7 //  TOLONG SIKI LETTER J
#define UC_MACRO_NAME_11DC8 0x11DC8 //  TOLONG SIKI LETTER JH
#define UC_MACRO_NAME_11DC9 0x11DC9 //  TOLONG SIKI LETTER NY
#define UC_MACRO_NAME_11DCA 0x11DCA //  TOLONG SIKI LETTER K
#define UC_MACRO_NAME_11DCB 0x11DCB //  TOLONG SIKI LETTER KH
#define UC_MACRO_NAME_11DCC 0x11DCC //  TOLONG SIKI LETTER G
#define UC_MACRO_NAME_11DCD 0x11DCD //  TOLONG SIKI LETTER GH
#define UC_MACRO_NAME_11DCE 0x11DCE //  TOLONG SIKI LETTER NG
#define UC_MACRO_NAME_11DCF 0x11DCF //  TOLONG SIKI LETTER Y
#define UC_MACRO_NAME_11DD0 0x11DD0 //  TOLONG SIKI LETTER R
#define UC_MACRO_NAME_11DD1 0x11DD1 //  TOLONG SIKI LETTER L
#define UC_MACRO_NAME_11DD2 0x11DD2 //  TOLONG SIKI LETTER V
#define UC_MACRO_NAME_11DD3 0x11DD3 //  TOLONG SIKI LETTER NNY
#define UC_MACRO_NAME_11DD4 0x11DD4 //  TOLONG SIKI LETTER S
#define UC_MACRO_NAME_11DD5 0x11DD5 //  TOLONG SIKI LETTER H
#define UC_MACRO_NAME_11DD6 0x11DD6 //  TOLONG SIKI LETTER X
#define UC_MACRO_NAME_11DD7 0x11DD7 //  TOLONG SIKI LETTER RR
#define UC_MACRO_NAME_11DD8 0x11DD8 //  TOLONG SIKI LETTER RRH
#define UC_MACRO_NAME_11DD9 0x11DD9 //  TOLONG SIKI SIGN SELA
#define UC_MACRO_NAME_11DDA 0x11DDA //  TOLONG SIKI SIGN HECAKA
#define UC_MACRO_NAME_11DDB 0x11DDB //  TOLONG SIKI UNGGA
#define UC_MACRO_NAME_11DE0 0x11DE0 //  TOLONG SIKI DIGIT ZERO
#define UC_MACRO_NAME_11DE1 0x11DE1 //  TOLONG SIKI DIGIT ONE
#define UC_MACRO_NAME_11DE2 0x11DE2 //  TOLONG SIKI DIGIT TWO
#define UC_MACRO_NAME_11DE3 0x11DE3 //  TOLONG SIKI DIGIT THREE
#define UC_MACRO_NAME_11DE4 0x11DE4 //  TOLONG SIKI DIGIT FOUR
#define UC_MACRO_NAME_11DE5 0x11DE5 //  TOLONG SIKI DIGIT FIVE
#define UC_MACRO_NAME_11DE6 0x11DE6 //  TOLONG SIKI DIGIT SIX
#define UC_MACRO_NAME_11DE7 0x11DE7 //  TOLONG SIKI DIGIT SEVEN
#define UC_MACRO_NAME_11DE8 0x11DE8 //  TOLONG SIKI DIGIT EIGHT
#define UC_MACRO_NAME_11DE9 0x11DE9 //  TOLONG SIKI DIGIT NINE


#endif // UC_H_TOLONG_SIKI
