/*
 * Unicode Block: Thaana
 * Range: U+0780..U+07BF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Thaana , Tãna , Taana or Tāna ( ތާނަ ) is the present writing system
 * of the Maldivian language spoken in the Maldives . Thaana has
 * characteristics of both an abugida (diacritics, vowel-killer strokes )
 * and a true alphabet (all vowels are written), with consonants derived
 * from indigenous and Arabic numerals, and vowels derived from the vowel
 * diacritics of the Arabic abjad . Maldivian orthography in Thaana is
 * largely phonemic .
 *
 */
#ifndef UC_H_THAANA
#define UC_H_THAANA

#define UC_MACRO_NAME_780 0x0780 // ހ THAANA LETTER HAA
#define UC_MACRO_NAME_781 0x0781 // ށ THAANA LETTER SHAVIYANI
#define UC_MACRO_NAME_782 0x0782 // ނ THAANA LETTER NOONU
#define UC_MACRO_NAME_783 0x0783 // ރ THAANA LETTER RAA
#define UC_MACRO_NAME_784 0x0784 // ބ THAANA LETTER BAA
#define UC_MACRO_NAME_785 0x0785 // ޅ THAANA LETTER LHAVIYANI
#define UC_MACRO_NAME_786 0x0786 // ކ THAANA LETTER KAAFU
#define UC_MACRO_NAME_787 0x0787 // އ THAANA LETTER ALIFU
#define UC_MACRO_NAME_788 0x0788 // ވ THAANA LETTER VAAVU
#define UC_MACRO_NAME_789 0x0789 // މ THAANA LETTER MEEMU
#define UC_MACRO_NAME_78A 0x078A // ފ THAANA LETTER FAAFU
#define UC_MACRO_NAME_78B 0x078B // ދ THAANA LETTER DHAALU
#define UC_MACRO_NAME_78C 0x078C // ތ THAANA LETTER THAA
#define UC_MACRO_NAME_78D 0x078D // ލ THAANA LETTER LAAMU
#define UC_MACRO_NAME_78E 0x078E // ގ THAANA LETTER GAAFU
#define UC_MACRO_NAME_78F 0x078F // ޏ THAANA LETTER GNAVIYANI
#define UC_MACRO_NAME_790 0x0790 // ސ THAANA LETTER SEENU
#define UC_MACRO_NAME_791 0x0791 // ޑ THAANA LETTER DAVIYANI
#define UC_MACRO_NAME_792 0x0792 // ޒ THAANA LETTER ZAVIYANI
#define UC_MACRO_NAME_793 0x0793 // ޓ THAANA LETTER TAVIYANI
#define UC_MACRO_NAME_794 0x0794 // ޔ THAANA LETTER YAA
#define UC_MACRO_NAME_795 0x0795 // ޕ THAANA LETTER PAVIYANI
#define UC_MACRO_NAME_796 0x0796 // ޖ THAANA LETTER JAVIYANI
#define UC_MACRO_NAME_797 0x0797 // ޗ THAANA LETTER CHAVIYANI
#define UC_MACRO_NAME_798 0x0798 // ޘ THAANA LETTER TTAA
#define UC_MACRO_NAME_799 0x0799 // ޙ THAANA LETTER HHAA
#define UC_MACRO_NAME_79A 0x079A // ޚ THAANA LETTER KHAA
#define UC_MACRO_NAME_79B 0x079B // ޛ THAANA LETTER THAALU
#define UC_MACRO_NAME_79C 0x079C // ޜ THAANA LETTER ZAA
#define UC_MACRO_NAME_79D 0x079D // ޝ THAANA LETTER SHEENU
#define UC_MACRO_NAME_79E 0x079E // ޞ THAANA LETTER SAADHU
#define UC_MACRO_NAME_79F 0x079F // ޟ THAANA LETTER DAADHU
#define UC_MACRO_NAME_7A0 0x07A0 // ޠ THAANA LETTER TO
#define UC_MACRO_NAME_7A1 0x07A1 // ޡ THAANA LETTER ZO
#define UC_MACRO_NAME_7A2 0x07A2 // ޢ THAANA LETTER AINU
#define UC_MACRO_NAME_7A3 0x07A3 // ޣ THAANA LETTER GHAINU
#define UC_MACRO_NAME_7A4 0x07A4 // ޤ THAANA LETTER QAAFU
#define UC_MACRO_NAME_7A5 0x07A5 // ޥ THAANA LETTER WAAVU
#define UC_MACRO_NAME_7A6 0x07A6 // ަ THAANA ABAFILI
#define UC_MACRO_NAME_7A7 0x07A7 // ާ THAANA AABAAFILI
#define UC_MACRO_NAME_7A8 0x07A8 // ި THAANA IBIFILI
#define UC_MACRO_NAME_7A9 0x07A9 // ީ THAANA EEBEEFILI
#define UC_MACRO_NAME_7AA 0x07AA // ު THAANA UBUFILI
#define UC_MACRO_NAME_7AB 0x07AB // ޫ THAANA OOBOOFILI
#define UC_MACRO_NAME_7AC 0x07AC // ެ THAANA EBEFILI
#define UC_MACRO_NAME_7AD 0x07AD // ޭ THAANA EYBEYFILI
#define UC_MACRO_NAME_7AE 0x07AE // ޮ THAANA OBOFILI
#define UC_MACRO_NAME_7AF 0x07AF // ޯ THAANA OABOAFILI
#define UC_MACRO_NAME_7B0 0x07B0 // ް THAANA SUKUN
#define UC_MACRO_NAME_7B1 0x07B1 // ޱ THAANA LETTER NAA


#endif // UC_H_THAANA
