/*
 * Unicode Block: Tamil Supplement
 * Range: U+11FC0..U+11FFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Tamil Supplement is a Unicode block containing Tamil historic
 * fractions and symbols.
 * The following Unicode-related documents record the purpose and process
 * of defining specific characters in the Tamil Supplement block:
 *
 */
#ifndef UC_H_TAMIL_SUPPLEMENT
#define UC_H_TAMIL_SUPPLEMENT

#define UC_MACRO_NAME_11FC0 0x11FC0 // 𑿀 TAMIL FRACTION ONE THREE-HUNDRED-AND-TWENTIETH
#define UC_MACRO_NAME_11FC1 0x11FC1 // 𑿁 TAMIL FRACTION ONE ONE-HUNDRED-AND-SIXTIETH
#define UC_MACRO_NAME_11FC2 0x11FC2 // 𑿂 TAMIL FRACTION ONE EIGHTIETH
#define UC_MACRO_NAME_11FC3 0x11FC3 // 𑿃 TAMIL FRACTION ONE SIXTY-FOURTH
#define UC_MACRO_NAME_11FC4 0x11FC4 // 𑿄 TAMIL FRACTION ONE FORTIETH
#define UC_MACRO_NAME_11FC5 0x11FC5 // 𑿅 TAMIL FRACTION ONE THIRTY-SECOND
#define UC_MACRO_NAME_11FC6 0x11FC6 // 𑿆 TAMIL FRACTION THREE EIGHTIETHS
#define UC_MACRO_NAME_11FC7 0x11FC7 // 𑿇 TAMIL FRACTION THREE SIXTY-FOURTHS
#define UC_MACRO_NAME_11FC8 0x11FC8 // 𑿈 TAMIL FRACTION ONE TWENTIETH
#define UC_MACRO_NAME_11FC9 0x11FC9 // 𑿉 TAMIL FRACTION ONE SIXTEENTH-1
#define UC_MACRO_NAME_11FCA 0x11FCA // 𑿊 TAMIL FRACTION ONE SIXTEENTH-2
#define UC_MACRO_NAME_11FCB 0x11FCB // 𑿋 TAMIL FRACTION ONE TENTH
#define UC_MACRO_NAME_11FCC 0x11FCC // 𑿌 TAMIL FRACTION ONE EIGHTH
#define UC_MACRO_NAME_11FCD 0x11FCD // 𑿍 TAMIL FRACTION THREE TWENTIETHS
#define UC_MACRO_NAME_11FCE 0x11FCE // 𑿎 TAMIL FRACTION THREE SIXTEENTHS
#define UC_MACRO_NAME_11FCF 0x11FCF // 𑿏 TAMIL FRACTION ONE FIFTH
#define UC_MACRO_NAME_11FD0 0x11FD0 // 𑿐 TAMIL FRACTION ONE QUARTER
#define UC_MACRO_NAME_11FD1 0x11FD1 // 𑿑 TAMIL FRACTION ONE HALF-1
#define UC_MACRO_NAME_11FD2 0x11FD2 // 𑿒 TAMIL FRACTION ONE HALF-2
#define UC_MACRO_NAME_11FD3 0x11FD3 // 𑿓 TAMIL FRACTION THREE QUARTERS
#define UC_MACRO_NAME_11FD4 0x11FD4 // 𑿔 TAMIL FRACTION DOWNSCALING FACTOR KIIZH
#define UC_MACRO_NAME_11FD5 0x11FD5 // 𑿕 TAMIL SIGN NEL
#define UC_MACRO_NAME_11FD6 0x11FD6 // 𑿖 TAMIL SIGN CEVITU
#define UC_MACRO_NAME_11FD7 0x11FD7 // 𑿗 TAMIL SIGN AAZHAAKKU
#define UC_MACRO_NAME_11FD8 0x11FD8 // 𑿘 TAMIL SIGN UZHAKKU
#define UC_MACRO_NAME_11FD9 0x11FD9 // 𑿙 TAMIL SIGN MUUVUZHAKKU
#define UC_MACRO_NAME_11FDA 0x11FDA // 𑿚 TAMIL SIGN KURUNI
#define UC_MACRO_NAME_11FDB 0x11FDB // 𑿛 TAMIL SIGN PATHAKKU
#define UC_MACRO_NAME_11FDC 0x11FDC // 𑿜 TAMIL SIGN MUKKURUNI
#define UC_MACRO_NAME_11FDD 0x11FDD // 𑿝 TAMIL SIGN KAACU
#define UC_MACRO_NAME_11FDE 0x11FDE // 𑿞 TAMIL SIGN PANAM
#define UC_MACRO_NAME_11FDF 0x11FDF // 𑿟 TAMIL SIGN PON
#define UC_MACRO_NAME_11FE0 0x11FE0 // 𑿠 TAMIL SIGN VARAAKAN
#define UC_MACRO_NAME_11FE1 0x11FE1 // 𑿡 TAMIL SIGN PAARAM
#define UC_MACRO_NAME_11FE2 0x11FE2 // 𑿢 TAMIL SIGN KUZHI
#define UC_MACRO_NAME_11FE3 0x11FE3 // 𑿣 TAMIL SIGN VELI
#define UC_MACRO_NAME_11FE4 0x11FE4 // 𑿤 TAMIL WET CULTIVATION SIGN
#define UC_MACRO_NAME_11FE5 0x11FE5 // 𑿥 TAMIL DRY CULTIVATION SIGN
#define UC_MACRO_NAME_11FE6 0x11FE6 // 𑿦 TAMIL LAND SIGN
#define UC_MACRO_NAME_11FE7 0x11FE7 // 𑿧 TAMIL SALT PAN SIGN
#define UC_MACRO_NAME_11FE8 0x11FE8 // 𑿨 TAMIL TRADITIONAL CREDIT SIGN
#define UC_MACRO_NAME_11FE9 0x11FE9 // 𑿩 TAMIL TRADITIONAL NUMBER SIGN
#define UC_MACRO_NAME_11FEA 0x11FEA // 𑿪 TAMIL CURRENT SIGN
#define UC_MACRO_NAME_11FEB 0x11FEB // 𑿫 TAMIL AND ODD SIGN
#define UC_MACRO_NAME_11FEC 0x11FEC // 𑿬 TAMIL SPENT SIGN
#define UC_MACRO_NAME_11FED 0x11FED // 𑿭 TAMIL TOTAL SIGN
#define UC_MACRO_NAME_11FEE 0x11FEE // 𑿮 TAMIL IN POSSESSION SIGN
#define UC_MACRO_NAME_11FEF 0x11FEF // 𑿯 TAMIL STARTING FROM SIGN
#define UC_MACRO_NAME_11FF0 0x11FF0 // 𑿰 TAMIL SIGN MUTHALIYA
#define UC_MACRO_NAME_11FF1 0x11FF1 // 𑿱 TAMIL SIGN VAKAIYARAA
#define UC_MACRO_NAME_11FFF 0x11FFF // 𑿿 TAMIL PUNCTUATION END OF TEXT


#endif // UC_H_TAMIL_SUPPLEMENT
