/*
 * Unicode Block: Tai Viet
 * Range: U+AA80..U+AADF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * The Tai Viet script ( Tai Dam : ꪎꪳ ꪼꪕ ("Tai script"), Vietnamese : Chữ
 * Thái Việt , Thai : อักษรไทดำ , RTGS : akson taidam ) is a Brahmic
 * script used by the Tai Dam people and various other Thai people in
 * Vietnam and Thailand .
 *
 */
#ifndef UC_H_TAI_VIET
#define UC_H_TAI_VIET

#define UC_MACRO_NAME_AA80 0xAA80 // ꪀ TAI VIET LETTER LOW KO
#define UC_MACRO_NAME_AA81 0xAA81 // ꪁ TAI VIET LETTER HIGH KO
#define UC_MACRO_NAME_AA82 0xAA82 // ꪂ TAI VIET LETTER LOW KHO
#define UC_MACRO_NAME_AA83 0xAA83 // ꪃ TAI VIET LETTER HIGH KHO
#define UC_MACRO_NAME_AA84 0xAA84 // ꪄ TAI VIET LETTER LOW KHHO
#define UC_MACRO_NAME_AA85 0xAA85 // ꪅ TAI VIET LETTER HIGH KHHO
#define UC_MACRO_NAME_AA86 0xAA86 // ꪆ TAI VIET LETTER LOW GO
#define UC_MACRO_NAME_AA87 0xAA87 // ꪇ TAI VIET LETTER HIGH GO
#define UC_MACRO_NAME_AA88 0xAA88 // ꪈ TAI VIET LETTER LOW NGO
#define UC_MACRO_NAME_AA89 0xAA89 // ꪉ TAI VIET LETTER HIGH NGO
#define UC_MACRO_NAME_AA8A 0xAA8A // ꪊ TAI VIET LETTER LOW CO
#define UC_MACRO_NAME_AA8B 0xAA8B // ꪋ TAI VIET LETTER HIGH CO
#define UC_MACRO_NAME_AA8C 0xAA8C // ꪌ TAI VIET LETTER LOW CHO
#define UC_MACRO_NAME_AA8D 0xAA8D // ꪍ TAI VIET LETTER HIGH CHO
#define UC_MACRO_NAME_AA8E 0xAA8E // ꪎ TAI VIET LETTER LOW SO
#define UC_MACRO_NAME_AA8F 0xAA8F // ꪏ TAI VIET LETTER HIGH SO
#define UC_MACRO_NAME_AA90 0xAA90 // ꪐ TAI VIET LETTER LOW NYO
#define UC_MACRO_NAME_AA91 0xAA91 // ꪑ TAI VIET LETTER HIGH NYO
#define UC_MACRO_NAME_AA92 0xAA92 // ꪒ TAI VIET LETTER LOW DO
#define UC_MACRO_NAME_AA93 0xAA93 // ꪓ TAI VIET LETTER HIGH DO
#define UC_MACRO_NAME_AA94 0xAA94 // ꪔ TAI VIET LETTER LOW TO
#define UC_MACRO_NAME_AA95 0xAA95 // ꪕ TAI VIET LETTER HIGH TO
#define UC_MACRO_NAME_AA96 0xAA96 // ꪖ TAI VIET LETTER LOW THO
#define UC_MACRO_NAME_AA97 0xAA97 // ꪗ TAI VIET LETTER HIGH THO
#define UC_MACRO_NAME_AA98 0xAA98 // ꪘ TAI VIET LETTER LOW NO
#define UC_MACRO_NAME_AA99 0xAA99 // ꪙ TAI VIET LETTER HIGH NO
#define UC_MACRO_NAME_AA9A 0xAA9A // ꪚ TAI VIET LETTER LOW BO
#define UC_MACRO_NAME_AA9B 0xAA9B // ꪛ TAI VIET LETTER HIGH BO
#define UC_MACRO_NAME_AA9C 0xAA9C // ꪜ TAI VIET LETTER LOW PO
#define UC_MACRO_NAME_AA9D 0xAA9D // ꪝ TAI VIET LETTER HIGH PO
#define UC_MACRO_NAME_AA9E 0xAA9E // ꪞ TAI VIET LETTER LOW PHO
#define UC_MACRO_NAME_AA9F 0xAA9F // ꪟ TAI VIET LETTER HIGH PHO
#define UC_MACRO_NAME_AAA0 0xAAA0 // ꪠ TAI VIET LETTER LOW FO
#define UC_MACRO_NAME_AAA1 0xAAA1 // ꪡ TAI VIET LETTER HIGH FO
#define UC_MACRO_NAME_AAA2 0xAAA2 // ꪢ TAI VIET LETTER LOW MO
#define UC_MACRO_NAME_AAA3 0xAAA3 // ꪣ TAI VIET LETTER HIGH MO
#define UC_MACRO_NAME_AAA4 0xAAA4 // ꪤ TAI VIET LETTER LOW YO
#define UC_MACRO_NAME_AAA5 0xAAA5 // ꪥ TAI VIET LETTER HIGH YO
#define UC_MACRO_NAME_AAA6 0xAAA6 // ꪦ TAI VIET LETTER LOW RO
#define UC_MACRO_NAME_AAA7 0xAAA7 // ꪧ TAI VIET LETTER HIGH RO
#define UC_MACRO_NAME_AAA8 0xAAA8 // ꪨ TAI VIET LETTER LOW LO
#define UC_MACRO_NAME_AAA9 0xAAA9 // ꪩ TAI VIET LETTER HIGH LO
#define UC_MACRO_NAME_AAAA 0xAAAA // ꪪ TAI VIET LETTER LOW VO
#define UC_MACRO_NAME_AAAB 0xAAAB // ꪫ TAI VIET LETTER HIGH VO
#define UC_MACRO_NAME_AAAC 0xAAAC // ꪬ TAI VIET LETTER LOW HO
#define UC_MACRO_NAME_AAAD 0xAAAD // ꪭ TAI VIET LETTER HIGH HO
#define UC_MACRO_NAME_AAAE 0xAAAE // ꪮ TAI VIET LETTER LOW O
#define UC_MACRO_NAME_AAAF 0xAAAF // ꪯ TAI VIET LETTER HIGH O
#define UC_MACRO_NAME_AAB0 0xAAB0 // ꪰ TAI VIET MAI KANG
#define UC_MACRO_NAME_AAB1 0xAAB1 // ꪱ TAI VIET VOWEL AA
#define UC_MACRO_NAME_AAB2 0xAAB2 // ꪲ TAI VIET VOWEL I
#define UC_MACRO_NAME_AAB3 0xAAB3 // ꪳ TAI VIET VOWEL UE
#define UC_MACRO_NAME_AAB4 0xAAB4 // ꪴ TAI VIET VOWEL U
#define UC_MACRO_NAME_AAB5 0xAAB5 // ꪵ TAI VIET VOWEL E
#define UC_MACRO_NAME_AAB6 0xAAB6 // ꪶ TAI VIET VOWEL O
#define UC_MACRO_NAME_AAB7 0xAAB7 // ꪷ TAI VIET MAI KHIT
#define UC_MACRO_NAME_AAB8 0xAAB8 // ꪸ TAI VIET VOWEL IA
#define UC_MACRO_NAME_AAB9 0xAAB9 // ꪹ TAI VIET VOWEL UEA
#define UC_MACRO_NAME_AABA 0xAABA // ꪺ TAI VIET VOWEL UA
#define UC_MACRO_NAME_AABB 0xAABB // ꪻ TAI VIET VOWEL AUE
#define UC_MACRO_NAME_AABC 0xAABC // ꪼ TAI VIET VOWEL AY
#define UC_MACRO_NAME_AABD 0xAABD // ꪽ TAI VIET VOWEL AN
#define UC_MACRO_NAME_AABE 0xAABE // ꪾ TAI VIET VOWEL AM
#define UC_MACRO_NAME_AABF 0xAABF // ꪿ TAI VIET TONE MAI EK
#define UC_MACRO_NAME_AAC0 0xAAC0 // ꫀ TAI VIET TONE MAI NUENG
#define UC_MACRO_NAME_AAC1 0xAAC1 // ꫁ TAI VIET TONE MAI THO
#define UC_MACRO_NAME_AAC2 0xAAC2 // ꫂ TAI VIET TONE MAI SONG
#define UC_MACRO_NAME_AADB 0xAADB // ꫛ TAI VIET SYMBOL KON
#define UC_MACRO_NAME_AADC 0xAADC // ꫜ TAI VIET SYMBOL NUENG
#define UC_MACRO_NAME_AADD 0xAADD // ꫝ TAI VIET SYMBOL SAM
#define UC_MACRO_NAME_AADE 0xAADE // ꫞ TAI VIET SYMBOL HO HOI
#define UC_MACRO_NAME_AADF 0xAADF // ꫟ TAI VIET SYMBOL KOI KOI


#endif // UC_H_TAI_VIET
