/*
 * Unicode Block: Tamil
 * Range: U+0B80..U+0BFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Tamil may refer to:
 *
 */
#ifndef UC_H_TAMIL
#define UC_H_TAMIL

#define UC_MACRO_NAME_B82 0x0B82 // ஂ TAMIL SIGN ANUSVARA
#define UC_MACRO_NAME_B83 0x0B83 // ஃ TAMIL SIGN VISARGA
#define UC_MACRO_NAME_B85 0x0B85 // அ TAMIL LETTER A
#define UC_MACRO_NAME_B86 0x0B86 // ஆ TAMIL LETTER AA
#define UC_MACRO_NAME_B87 0x0B87 // இ TAMIL LETTER I
#define UC_MACRO_NAME_B88 0x0B88 // ஈ TAMIL LETTER II
#define UC_MACRO_NAME_B89 0x0B89 // உ TAMIL LETTER U
#define UC_MACRO_NAME_B8A 0x0B8A // ஊ TAMIL LETTER UU
#define UC_MACRO_NAME_B8E 0x0B8E // எ TAMIL LETTER E
#define UC_MACRO_NAME_B8F 0x0B8F // ஏ TAMIL LETTER EE
#define UC_MACRO_NAME_B90 0x0B90 // ஐ TAMIL LETTER AI
#define UC_MACRO_NAME_B92 0x0B92 // ஒ TAMIL LETTER O
#define UC_MACRO_NAME_B93 0x0B93 // ஓ TAMIL LETTER OO
#define UC_MACRO_NAME_B94 0x0B94 // ஔ TAMIL LETTER AU
#define UC_MACRO_NAME_B95 0x0B95 // க TAMIL LETTER KA
#define UC_MACRO_NAME_B99 0x0B99 // ங TAMIL LETTER NGA
#define UC_MACRO_NAME_B9A 0x0B9A // ச TAMIL LETTER CA
#define UC_MACRO_NAME_B9C 0x0B9C // ஜ TAMIL LETTER JA
#define UC_MACRO_NAME_B9E 0x0B9E // ஞ TAMIL LETTER NYA
#define UC_MACRO_NAME_B9F 0x0B9F // ட TAMIL LETTER TTA
#define UC_MACRO_NAME_BA3 0x0BA3 // ண TAMIL LETTER NNA
#define UC_MACRO_NAME_BA4 0x0BA4 // த TAMIL LETTER TA
#define UC_MACRO_NAME_BA8 0x0BA8 // ந TAMIL LETTER NA
#define UC_MACRO_NAME_BA9 0x0BA9 // ன TAMIL LETTER NNNA
#define UC_MACRO_NAME_BAA 0x0BAA // ப TAMIL LETTER PA
#define UC_MACRO_NAME_BAE 0x0BAE // ம TAMIL LETTER MA
#define UC_MACRO_NAME_BAF 0x0BAF // ய TAMIL LETTER YA
#define UC_MACRO_NAME_BB0 0x0BB0 // ர TAMIL LETTER RA
#define UC_MACRO_NAME_BB1 0x0BB1 // ற TAMIL LETTER RRA
#define UC_MACRO_NAME_BB2 0x0BB2 // ல TAMIL LETTER LA
#define UC_MACRO_NAME_BB3 0x0BB3 // ள TAMIL LETTER LLA
#define UC_MACRO_NAME_BB4 0x0BB4 // ழ TAMIL LETTER LLLA
#define UC_MACRO_NAME_BB5 0x0BB5 // வ TAMIL LETTER VA
#define UC_MACRO_NAME_BB6 0x0BB6 // ஶ TAMIL LETTER SHA
#define UC_MACRO_NAME_BB7 0x0BB7 // ஷ TAMIL LETTER SSA
#define UC_MACRO_NAME_BB8 0x0BB8 // ஸ TAMIL LETTER SA
#define UC_MACRO_NAME_BB9 0x0BB9 // ஹ TAMIL LETTER HA
#define UC_MACRO_NAME_BBE 0x0BBE // ா TAMIL VOWEL SIGN AA
#define UC_MACRO_NAME_BBF 0x0BBF // ி TAMIL VOWEL SIGN I
#define UC_MACRO_NAME_BC0 0x0BC0 // ீ TAMIL VOWEL SIGN II
#define UC_MACRO_NAME_BC1 0x0BC1 // ு TAMIL VOWEL SIGN U
#define UC_MACRO_NAME_BC2 0x0BC2 // ூ TAMIL VOWEL SIGN UU
#define UC_MACRO_NAME_BC6 0x0BC6 // ெ TAMIL VOWEL SIGN E
#define UC_MACRO_NAME_BC7 0x0BC7 // ே TAMIL VOWEL SIGN EE
#define UC_MACRO_NAME_BC8 0x0BC8 // ை TAMIL VOWEL SIGN AI
#define UC_MACRO_NAME_BCA 0x0BCA // ொ TAMIL VOWEL SIGN O
#define UC_MACRO_NAME_BCB 0x0BCB // ோ TAMIL VOWEL SIGN OO
#define UC_MACRO_NAME_BCC 0x0BCC // ௌ TAMIL VOWEL SIGN AU
#define UC_MACRO_NAME_BCD 0x0BCD // ் TAMIL SIGN VIRAMA
#define UC_MACRO_NAME_BD0 0x0BD0 // ௐ TAMIL OM
#define UC_MACRO_NAME_BD7 0x0BD7 // ௗ TAMIL AU LENGTH MARK
#define UC_MACRO_NAME_BE6 0x0BE6 // ௦ TAMIL DIGIT ZERO
#define UC_MACRO_NAME_BE7 0x0BE7 // ௧ TAMIL DIGIT ONE
#define UC_MACRO_NAME_BE8 0x0BE8 // ௨ TAMIL DIGIT TWO
#define UC_MACRO_NAME_BE9 0x0BE9 // ௩ TAMIL DIGIT THREE
#define UC_MACRO_NAME_BEA 0x0BEA // ௪ TAMIL DIGIT FOUR
#define UC_MACRO_NAME_BEB 0x0BEB // ௫ TAMIL DIGIT FIVE
#define UC_MACRO_NAME_BEC 0x0BEC // ௬ TAMIL DIGIT SIX
#define UC_MACRO_NAME_BED 0x0BED // ௭ TAMIL DIGIT SEVEN
#define UC_MACRO_NAME_BEE 0x0BEE // ௮ TAMIL DIGIT EIGHT
#define UC_MACRO_NAME_BEF 0x0BEF // ௯ TAMIL DIGIT NINE
#define UC_MACRO_NAME_BF0 0x0BF0 // ௰ TAMIL NUMBER TEN
#define UC_MACRO_NAME_BF1 0x0BF1 // ௱ TAMIL NUMBER ONE HUNDRED
#define UC_MACRO_NAME_BF2 0x0BF2 // ௲ TAMIL NUMBER ONE THOUSAND
#define UC_MACRO_NAME_BF3 0x0BF3 // ௳ TAMIL DAY SIGN
#define UC_MACRO_NAME_BF4 0x0BF4 // ௴ TAMIL MONTH SIGN
#define UC_MACRO_NAME_BF5 0x0BF5 // ௵ TAMIL YEAR SIGN
#define UC_MACRO_NAME_BF6 0x0BF6 // ௶ TAMIL DEBIT SIGN
#define UC_MACRO_NAME_BF7 0x0BF7 // ௷ TAMIL CREDIT SIGN
#define UC_MACRO_NAME_BF8 0x0BF8 // ௸ TAMIL AS ABOVE SIGN
#define UC_MACRO_NAME_BF9 0x0BF9 // ௹ TAMIL RUPEE SIGN
#define UC_MACRO_NAME_BFA 0x0BFA // ௺ TAMIL NUMBER SIGN


#endif // UC_H_TAMIL
