/*
 * Unicode Block: Tai Tham
 * Range: U+1A20..U+1AAF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Tai Tham script ( Tham meaning "scripture") is an abugida writing
 * system used mainly for a group of Southwestern Tai languages i.e.,
 * Northern Thai , Tai Lü , Khün and Lao ; as well as the liturgical
 * languages of Buddhism i.e., Pali and Sanskrit . It is historically
 * known as Tua Tham ( ᨲ᩠ᩅᩫᨵᨾ᩠ᨾ᩼ or ᨲ᩠ᩅᩫᨵᩢᨾ᩠ᨾ᩼ ). In Thailand and Myanmar
 * , the script is often referred to as Lanna script ( Thai :
 * อักษรธรรมล้านนา RTGS : Akson Tham Lan Na ; Burmese : လန်နာအက္ခရာ ,
 * MLCTS : Lanna Akhkara ) in relation to the historical kingdom of Lan
 * Na situating in the Northern region of modern day Thailand and
 * Kyaingtong , Shan state in Myanmar. Local people in Northern Thailand
 * also call the script as Tua Mueang ( ᨲ᩠ᩅᩫᨾᩮᩥᩬᨦ , Northern Thai
 * pronunciation: listen ⓘ ) in parallel to Kam Mueang , a local name for
 * Northern Thai language . In Laos and Isan region of Thailand, a
 * variation of Tai Tham script, often dubbed Lao Tham , is also known by
 * the locals as To Tham Lao ( Northeastern Thai : โตธรรมลาว
 * /toː˩.tʰam˧˥.laːw˧/ , cf. Lao : ໂຕທຳ/ໂຕທັມ BGN/PCGN to tham ) or Yuan
 * script. Tai Tham script is traditionally written on a dried palm leaf
 * as a palm-leaf manuscript .
 * The Northern Thai language is a close relative of (standard) Thai . It
 * is spoken by nearly 6 million people in Northern Thailand and several
 * thousand in Laos of whom few are literate in Lanna script. The script
 * is still read by older monks. Northern Thai has six linguistic tones
 * and Thai only five, making transcription into the Thai alphabet
 * problematic. There is some resurgent interest in the script among
 * younger people, but an added complication is that the modern spoken
 * form, called Kam Muang, differs in pronunciation from the older form.
 *
 */
#ifndef UC_H_TAI_THAM
#define UC_H_TAI_THAM

#define UC_MACRO_NAME_1A20 0x1A20 // ᨠ TAI THAM LETTER HIGH KA
#define UC_MACRO_NAME_1A21 0x1A21 // ᨡ TAI THAM LETTER HIGH KHA
#define UC_MACRO_NAME_1A22 0x1A22 // ᨢ TAI THAM LETTER HIGH KXA
#define UC_MACRO_NAME_1A23 0x1A23 // ᨣ TAI THAM LETTER LOW KA
#define UC_MACRO_NAME_1A24 0x1A24 // ᨤ TAI THAM LETTER LOW KXA
#define UC_MACRO_NAME_1A25 0x1A25 // ᨥ TAI THAM LETTER LOW KHA
#define UC_MACRO_NAME_1A26 0x1A26 // ᨦ TAI THAM LETTER NGA
#define UC_MACRO_NAME_1A27 0x1A27 // ᨧ TAI THAM LETTER HIGH CA
#define UC_MACRO_NAME_1A28 0x1A28 // ᨨ TAI THAM LETTER HIGH CHA
#define UC_MACRO_NAME_1A29 0x1A29 // ᨩ TAI THAM LETTER LOW CA
#define UC_MACRO_NAME_1A2A 0x1A2A // ᨪ TAI THAM LETTER LOW SA
#define UC_MACRO_NAME_1A2B 0x1A2B // ᨫ TAI THAM LETTER LOW CHA
#define UC_MACRO_NAME_1A2C 0x1A2C // ᨬ TAI THAM LETTER NYA
#define UC_MACRO_NAME_1A2D 0x1A2D // ᨭ TAI THAM LETTER RATA
#define UC_MACRO_NAME_1A2E 0x1A2E // ᨮ TAI THAM LETTER HIGH RATHA
#define UC_MACRO_NAME_1A2F 0x1A2F // ᨯ TAI THAM LETTER DA
#define UC_MACRO_NAME_1A30 0x1A30 // ᨰ TAI THAM LETTER LOW RATHA
#define UC_MACRO_NAME_1A31 0x1A31 // ᨱ TAI THAM LETTER RANA
#define UC_MACRO_NAME_1A32 0x1A32 // ᨲ TAI THAM LETTER HIGH TA
#define UC_MACRO_NAME_1A33 0x1A33 // ᨳ TAI THAM LETTER HIGH THA
#define UC_MACRO_NAME_1A34 0x1A34 // ᨴ TAI THAM LETTER LOW TA
#define UC_MACRO_NAME_1A35 0x1A35 // ᨵ TAI THAM LETTER LOW THA
#define UC_MACRO_NAME_1A36 0x1A36 // ᨶ TAI THAM LETTER NA
#define UC_MACRO_NAME_1A37 0x1A37 // ᨷ TAI THAM LETTER BA
#define UC_MACRO_NAME_1A38 0x1A38 // ᨸ TAI THAM LETTER HIGH PA
#define UC_MACRO_NAME_1A39 0x1A39 // ᨹ TAI THAM LETTER HIGH PHA
#define UC_MACRO_NAME_1A3A 0x1A3A // ᨺ TAI THAM LETTER HIGH FA
#define UC_MACRO_NAME_1A3B 0x1A3B // ᨻ TAI THAM LETTER LOW PA
#define UC_MACRO_NAME_1A3C 0x1A3C // ᨼ TAI THAM LETTER LOW FA
#define UC_MACRO_NAME_1A3D 0x1A3D // ᨽ TAI THAM LETTER LOW PHA
#define UC_MACRO_NAME_1A3E 0x1A3E // ᨾ TAI THAM LETTER MA
#define UC_MACRO_NAME_1A3F 0x1A3F // ᨿ TAI THAM LETTER LOW YA
#define UC_MACRO_NAME_1A40 0x1A40 // ᩀ TAI THAM LETTER HIGH YA
#define UC_MACRO_NAME_1A41 0x1A41 // ᩁ TAI THAM LETTER RA
#define UC_MACRO_NAME_1A42 0x1A42 // ᩂ TAI THAM LETTER RUE
#define UC_MACRO_NAME_1A43 0x1A43 // ᩃ TAI THAM LETTER LA
#define UC_MACRO_NAME_1A44 0x1A44 // ᩄ TAI THAM LETTER LUE
#define UC_MACRO_NAME_1A45 0x1A45 // ᩅ TAI THAM LETTER WA
#define UC_MACRO_NAME_1A46 0x1A46 // ᩆ TAI THAM LETTER HIGH SHA
#define UC_MACRO_NAME_1A47 0x1A47 // ᩇ TAI THAM LETTER HIGH SSA
#define UC_MACRO_NAME_1A48 0x1A48 // ᩈ TAI THAM LETTER HIGH SA
#define UC_MACRO_NAME_1A49 0x1A49 // ᩉ TAI THAM LETTER HIGH HA
#define UC_MACRO_NAME_1A4A 0x1A4A // ᩊ TAI THAM LETTER LLA
#define UC_MACRO_NAME_1A4B 0x1A4B // ᩋ TAI THAM LETTER A
#define UC_MACRO_NAME_1A4C 0x1A4C // ᩌ TAI THAM LETTER LOW HA
#define UC_MACRO_NAME_1A4D 0x1A4D // ᩍ TAI THAM LETTER I
#define UC_MACRO_NAME_1A4E 0x1A4E // ᩎ TAI THAM LETTER II
#define UC_MACRO_NAME_1A4F 0x1A4F // ᩏ TAI THAM LETTER U
#define UC_MACRO_NAME_1A50 0x1A50 // ᩐ TAI THAM LETTER UU
#define UC_MACRO_NAME_1A51 0x1A51 // ᩑ TAI THAM LETTER EE
#define UC_MACRO_NAME_1A52 0x1A52 // ᩒ TAI THAM LETTER OO
#define UC_MACRO_NAME_1A53 0x1A53 // ᩓ TAI THAM LETTER LAE
#define UC_MACRO_NAME_1A54 0x1A54 // ᩔ TAI THAM LETTER GREAT SA
#define UC_MACRO_NAME_1A55 0x1A55 // ᩕ TAI THAM CONSONANT SIGN MEDIAL RA
#define UC_MACRO_NAME_1A56 0x1A56 // ᩖ TAI THAM CONSONANT SIGN MEDIAL LA
#define UC_MACRO_NAME_1A57 0x1A57 // ᩗ TAI THAM CONSONANT SIGN LA TANG LAI
#define UC_MACRO_NAME_1A58 0x1A58 // ᩘ TAI THAM SIGN MAI KANG LAI
#define UC_MACRO_NAME_1A59 0x1A59 // ᩙ TAI THAM CONSONANT SIGN FINAL NGA
#define UC_MACRO_NAME_1A5A 0x1A5A // ᩚ TAI THAM CONSONANT SIGN LOW PA
#define UC_MACRO_NAME_1A5B 0x1A5B // ᩛ TAI THAM CONSONANT SIGN HIGH RATHA OR LOW PA
#define UC_MACRO_NAME_1A5C 0x1A5C // ᩜ TAI THAM CONSONANT SIGN MA
#define UC_MACRO_NAME_1A5D 0x1A5D // ᩝ TAI THAM CONSONANT SIGN BA
#define UC_MACRO_NAME_1A5E 0x1A5E // ᩞ TAI THAM CONSONANT SIGN SA
#define UC_MACRO_NAME_1A60 0x1A60 // ᩠ TAI THAM SIGN SAKOT
#define UC_MACRO_NAME_1A61 0x1A61 // ᩡ TAI THAM VOWEL SIGN A
#define UC_MACRO_NAME_1A62 0x1A62 // ᩢ TAI THAM VOWEL SIGN MAI SAT
#define UC_MACRO_NAME_1A63 0x1A63 // ᩣ TAI THAM VOWEL SIGN AA
#define UC_MACRO_NAME_1A64 0x1A64 // ᩤ TAI THAM VOWEL SIGN TALL AA
#define UC_MACRO_NAME_1A65 0x1A65 // ᩥ TAI THAM VOWEL SIGN I
#define UC_MACRO_NAME_1A66 0x1A66 // ᩦ TAI THAM VOWEL SIGN II
#define UC_MACRO_NAME_1A67 0x1A67 // ᩧ TAI THAM VOWEL SIGN UE
#define UC_MACRO_NAME_1A68 0x1A68 // ᩨ TAI THAM VOWEL SIGN UUE
#define UC_MACRO_NAME_1A69 0x1A69 // ᩩ TAI THAM VOWEL SIGN U
#define UC_MACRO_NAME_1A6A 0x1A6A // ᩪ TAI THAM VOWEL SIGN UU
#define UC_MACRO_NAME_1A6B 0x1A6B // ᩫ TAI THAM VOWEL SIGN O
#define UC_MACRO_NAME_1A6C 0x1A6C // ᩬ TAI THAM VOWEL SIGN OA BELOW
#define UC_MACRO_NAME_1A6D 0x1A6D // ᩭ TAI THAM VOWEL SIGN OY
#define UC_MACRO_NAME_1A6E 0x1A6E // ᩮ TAI THAM VOWEL SIGN E
#define UC_MACRO_NAME_1A6F 0x1A6F // ᩯ TAI THAM VOWEL SIGN AE
#define UC_MACRO_NAME_1A70 0x1A70 // ᩰ TAI THAM VOWEL SIGN OO
#define UC_MACRO_NAME_1A71 0x1A71 // ᩱ TAI THAM VOWEL SIGN AI
#define UC_MACRO_NAME_1A72 0x1A72 // ᩲ TAI THAM VOWEL SIGN THAM AI
#define UC_MACRO_NAME_1A73 0x1A73 // ᩳ TAI THAM VOWEL SIGN OA ABOVE
#define UC_MACRO_NAME_1A74 0x1A74 // ᩴ TAI THAM SIGN MAI KANG
#define UC_MACRO_NAME_1A75 0x1A75 // ᩵ TAI THAM SIGN TONE-1
#define UC_MACRO_NAME_1A76 0x1A76 // ᩶ TAI THAM SIGN TONE-2
#define UC_MACRO_NAME_1A77 0x1A77 // ᩷ TAI THAM SIGN KHUEN TONE-3
#define UC_MACRO_NAME_1A78 0x1A78 // ᩸ TAI THAM SIGN KHUEN TONE-4
#define UC_MACRO_NAME_1A79 0x1A79 // ᩹ TAI THAM SIGN KHUEN TONE-5
#define UC_MACRO_NAME_1A7A 0x1A7A // ᩺ TAI THAM SIGN RA HAAM
#define UC_MACRO_NAME_1A7B 0x1A7B // ᩻ TAI THAM SIGN MAI SAM
#define UC_MACRO_NAME_1A7C 0x1A7C // ᩼ TAI THAM SIGN KHUEN-LUE KARAN
#define UC_MACRO_NAME_1A7F 0x1A7F // ᩿ TAI THAM COMBINING CRYPTOGRAMMIC DOT
#define UC_MACRO_NAME_1A80 0x1A80 // ᪀ TAI THAM HORA DIGIT ZERO
#define UC_MACRO_NAME_1A81 0x1A81 // ᪁ TAI THAM HORA DIGIT ONE
#define UC_MACRO_NAME_1A82 0x1A82 // ᪂ TAI THAM HORA DIGIT TWO
#define UC_MACRO_NAME_1A83 0x1A83 // ᪃ TAI THAM HORA DIGIT THREE
#define UC_MACRO_NAME_1A84 0x1A84 // ᪄ TAI THAM HORA DIGIT FOUR
#define UC_MACRO_NAME_1A85 0x1A85 // ᪅ TAI THAM HORA DIGIT FIVE
#define UC_MACRO_NAME_1A86 0x1A86 // ᪆ TAI THAM HORA DIGIT SIX
#define UC_MACRO_NAME_1A87 0x1A87 // ᪇ TAI THAM HORA DIGIT SEVEN
#define UC_MACRO_NAME_1A88 0x1A88 // ᪈ TAI THAM HORA DIGIT EIGHT
#define UC_MACRO_NAME_1A89 0x1A89 // ᪉ TAI THAM HORA DIGIT NINE
#define UC_MACRO_NAME_1A90 0x1A90 // ᪐ TAI THAM THAM DIGIT ZERO
#define UC_MACRO_NAME_1A91 0x1A91 // ᪑ TAI THAM THAM DIGIT ONE
#define UC_MACRO_NAME_1A92 0x1A92 // ᪒ TAI THAM THAM DIGIT TWO
#define UC_MACRO_NAME_1A93 0x1A93 // ᪓ TAI THAM THAM DIGIT THREE
#define UC_MACRO_NAME_1A94 0x1A94 // ᪔ TAI THAM THAM DIGIT FOUR
#define UC_MACRO_NAME_1A95 0x1A95 // ᪕ TAI THAM THAM DIGIT FIVE
#define UC_MACRO_NAME_1A96 0x1A96 // ᪖ TAI THAM THAM DIGIT SIX
#define UC_MACRO_NAME_1A97 0x1A97 // ᪗ TAI THAM THAM DIGIT SEVEN
#define UC_MACRO_NAME_1A98 0x1A98 // ᪘ TAI THAM THAM DIGIT EIGHT
#define UC_MACRO_NAME_1A99 0x1A99 // ᪙ TAI THAM THAM DIGIT NINE
#define UC_MACRO_NAME_1AA0 0x1AA0 // ᪠ TAI THAM SIGN WIANG
#define UC_MACRO_NAME_1AA1 0x1AA1 // ᪡ TAI THAM SIGN WIANGWAAK
#define UC_MACRO_NAME_1AA2 0x1AA2 // ᪢ TAI THAM SIGN SAWAN
#define UC_MACRO_NAME_1AA3 0x1AA3 // ᪣ TAI THAM SIGN KEOW
#define UC_MACRO_NAME_1AA4 0x1AA4 // ᪤ TAI THAM SIGN HOY
#define UC_MACRO_NAME_1AA5 0x1AA5 // ᪥ TAI THAM SIGN DOKMAI
#define UC_MACRO_NAME_1AA6 0x1AA6 // ᪦ TAI THAM SIGN REVERSED ROTATED RANA
#define UC_MACRO_NAME_1AA7 0x1AA7 // ᪧ TAI THAM SIGN MAI YAMOK
#define UC_MACRO_NAME_1AA8 0x1AA8 // ᪨ TAI THAM SIGN KAAN
#define UC_MACRO_NAME_1AA9 0x1AA9 // ᪩ TAI THAM SIGN KAANKUU
#define UC_MACRO_NAME_1AAA 0x1AAA // ᪪ TAI THAM SIGN SATKAAN
#define UC_MACRO_NAME_1AAB 0x1AAB // ᪫ TAI THAM SIGN SATKAANKUU
#define UC_MACRO_NAME_1AAC 0x1AAC // ᪬ TAI THAM SIGN HANG
#define UC_MACRO_NAME_1AAD 0x1AAD // ᪭ TAI THAM SIGN CAANG


#endif // UC_H_TAI_THAM
