/*
 * Unicode Block: Thai
 * Range: U+0E00..U+0E7F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Thai or THAI may refer to:
 *
 */
#ifndef UC_H_THAI
#define UC_H_THAI

#define UC_MACRO_NAME_E01 0x0E01 // ก THAI CHARACTER KO KAI
#define UC_MACRO_NAME_E02 0x0E02 // ข THAI CHARACTER KHO KHAI
#define UC_MACRO_NAME_E03 0x0E03 // ฃ THAI CHARACTER KHO KHUAT
#define UC_MACRO_NAME_E04 0x0E04 // ค THAI CHARACTER KHO KHWAI
#define UC_MACRO_NAME_E05 0x0E05 // ฅ THAI CHARACTER KHO KHON
#define UC_MACRO_NAME_E06 0x0E06 // ฆ THAI CHARACTER KHO RAKHANG
#define UC_MACRO_NAME_E07 0x0E07 // ง THAI CHARACTER NGO NGU
#define UC_MACRO_NAME_E08 0x0E08 // จ THAI CHARACTER CHO CHAN
#define UC_MACRO_NAME_E09 0x0E09 // ฉ THAI CHARACTER CHO CHING
#define UC_MACRO_NAME_E0A 0x0E0A // ช THAI CHARACTER CHO CHANG
#define UC_MACRO_NAME_E0B 0x0E0B // ซ THAI CHARACTER SO SO
#define UC_MACRO_NAME_E0C 0x0E0C // ฌ THAI CHARACTER CHO CHOE
#define UC_MACRO_NAME_E0D 0x0E0D // ญ THAI CHARACTER YO YING
#define UC_MACRO_NAME_E0E 0x0E0E // ฎ THAI CHARACTER DO CHADA
#define UC_MACRO_NAME_E0F 0x0E0F // ฏ THAI CHARACTER TO PATAK
#define UC_MACRO_NAME_E10 0x0E10 // ฐ THAI CHARACTER THO THAN
#define UC_MACRO_NAME_E11 0x0E11 // ฑ THAI CHARACTER THO NANGMONTHO
#define UC_MACRO_NAME_E12 0x0E12 // ฒ THAI CHARACTER THO PHUTHAO
#define UC_MACRO_NAME_E13 0x0E13 // ณ THAI CHARACTER NO NEN
#define UC_MACRO_NAME_E14 0x0E14 // ด THAI CHARACTER DO DEK
#define UC_MACRO_NAME_E15 0x0E15 // ต THAI CHARACTER TO TAO
#define UC_MACRO_NAME_E16 0x0E16 // ถ THAI CHARACTER THO THUNG
#define UC_MACRO_NAME_E17 0x0E17 // ท THAI CHARACTER THO THAHAN
#define UC_MACRO_NAME_E18 0x0E18 // ธ THAI CHARACTER THO THONG
#define UC_MACRO_NAME_E19 0x0E19 // น THAI CHARACTER NO NU
#define UC_MACRO_NAME_E1A 0x0E1A // บ THAI CHARACTER BO BAIMAI
#define UC_MACRO_NAME_E1B 0x0E1B // ป THAI CHARACTER PO PLA
#define UC_MACRO_NAME_E1C 0x0E1C // ผ THAI CHARACTER PHO PHUNG
#define UC_MACRO_NAME_E1D 0x0E1D // ฝ THAI CHARACTER FO FA
#define UC_MACRO_NAME_E1E 0x0E1E // พ THAI CHARACTER PHO PHAN
#define UC_MACRO_NAME_E1F 0x0E1F // ฟ THAI CHARACTER FO FAN
#define UC_MACRO_NAME_E20 0x0E20 // ภ THAI CHARACTER PHO SAMPHAO
#define UC_MACRO_NAME_E21 0x0E21 // ม THAI CHARACTER MO MA
#define UC_MACRO_NAME_E22 0x0E22 // ย THAI CHARACTER YO YAK
#define UC_MACRO_NAME_E23 0x0E23 // ร THAI CHARACTER RO RUA
#define UC_MACRO_NAME_E24 0x0E24 // ฤ THAI CHARACTER RU
#define UC_MACRO_NAME_E25 0x0E25 // ล THAI CHARACTER LO LING
#define UC_MACRO_NAME_E26 0x0E26 // ฦ THAI CHARACTER LU
#define UC_MACRO_NAME_E27 0x0E27 // ว THAI CHARACTER WO WAEN
#define UC_MACRO_NAME_E28 0x0E28 // ศ THAI CHARACTER SO SALA
#define UC_MACRO_NAME_E29 0x0E29 // ษ THAI CHARACTER SO RUSI
#define UC_MACRO_NAME_E2A 0x0E2A // ส THAI CHARACTER SO SUA
#define UC_MACRO_NAME_E2B 0x0E2B // ห THAI CHARACTER HO HIP
#define UC_MACRO_NAME_E2C 0x0E2C // ฬ THAI CHARACTER LO CHULA
#define UC_MACRO_NAME_E2D 0x0E2D // อ THAI CHARACTER O ANG
#define UC_MACRO_NAME_E2E 0x0E2E // ฮ THAI CHARACTER HO NOKHUK
#define UC_MACRO_NAME_E2F 0x0E2F // ฯ THAI CHARACTER PAIYANNOI
#define UC_MACRO_NAME_E30 0x0E30 // ะ THAI CHARACTER SARA A
#define UC_MACRO_NAME_E31 0x0E31 // ั THAI CHARACTER MAI HAN-AKAT
#define UC_MACRO_NAME_E32 0x0E32 // า THAI CHARACTER SARA AA
#define UC_MACRO_NAME_E33 0x0E33 // ำ THAI CHARACTER SARA AM
#define UC_MACRO_NAME_E34 0x0E34 // ิ THAI CHARACTER SARA I
#define UC_MACRO_NAME_E35 0x0E35 // ี THAI CHARACTER SARA II
#define UC_MACRO_NAME_E36 0x0E36 // ึ THAI CHARACTER SARA UE
#define UC_MACRO_NAME_E37 0x0E37 // ื THAI CHARACTER SARA UEE
#define UC_MACRO_NAME_E38 0x0E38 // ุ THAI CHARACTER SARA U
#define UC_MACRO_NAME_E39 0x0E39 // ู THAI CHARACTER SARA UU
#define UC_MACRO_NAME_E3A 0x0E3A // ฺ THAI CHARACTER PHINTHU
#define UC_MACRO_NAME_E3F 0x0E3F // ฿ THAI CURRENCY SYMBOL BAHT
#define UC_MACRO_NAME_E40 0x0E40 // เ THAI CHARACTER SARA E
#define UC_MACRO_NAME_E41 0x0E41 // แ THAI CHARACTER SARA AE
#define UC_MACRO_NAME_E42 0x0E42 // โ THAI CHARACTER SARA O
#define UC_MACRO_NAME_E43 0x0E43 // ใ THAI CHARACTER SARA AI MAIMUAN
#define UC_MACRO_NAME_E44 0x0E44 // ไ THAI CHARACTER SARA AI MAIMALAI
#define UC_MACRO_NAME_E45 0x0E45 // ๅ THAI CHARACTER LAKKHANGYAO
#define UC_MACRO_NAME_E46 0x0E46 // ๆ THAI CHARACTER MAIYAMOK
#define UC_MACRO_NAME_E47 0x0E47 // ็ THAI CHARACTER MAITAIKHU
#define UC_MACRO_NAME_E48 0x0E48 // ่ THAI CHARACTER MAI EK
#define UC_MACRO_NAME_E49 0x0E49 // ้ THAI CHARACTER MAI THO
#define UC_MACRO_NAME_E4A 0x0E4A // ๊ THAI CHARACTER MAI TRI
#define UC_MACRO_NAME_E4B 0x0E4B // ๋ THAI CHARACTER MAI CHATTAWA
#define UC_MACRO_NAME_E4C 0x0E4C // ์ THAI CHARACTER THANTHAKHAT
#define UC_MACRO_NAME_E4D 0x0E4D // ํ THAI CHARACTER NIKHAHIT
#define UC_MACRO_NAME_E4E 0x0E4E // ๎ THAI CHARACTER YAMAKKAN
#define UC_MACRO_NAME_E4F 0x0E4F // ๏ THAI CHARACTER FONGMAN
#define UC_MACRO_NAME_E50 0x0E50 // ๐ THAI DIGIT ZERO
#define UC_MACRO_NAME_E51 0x0E51 // ๑ THAI DIGIT ONE
#define UC_MACRO_NAME_E52 0x0E52 // ๒ THAI DIGIT TWO
#define UC_MACRO_NAME_E53 0x0E53 // ๓ THAI DIGIT THREE
#define UC_MACRO_NAME_E54 0x0E54 // ๔ THAI DIGIT FOUR
#define UC_MACRO_NAME_E55 0x0E55 // ๕ THAI DIGIT FIVE
#define UC_MACRO_NAME_E56 0x0E56 // ๖ THAI DIGIT SIX
#define UC_MACRO_NAME_E57 0x0E57 // ๗ THAI DIGIT SEVEN
#define UC_MACRO_NAME_E58 0x0E58 // ๘ THAI DIGIT EIGHT
#define UC_MACRO_NAME_E59 0x0E59 // ๙ THAI DIGIT NINE
#define UC_MACRO_NAME_E5A 0x0E5A // ๚ THAI CHARACTER ANGKHANKHU
#define UC_MACRO_NAME_E5B 0x0E5B // ๛ THAI CHARACTER KHOMUT


#endif // UC_H_THAI
