/*
 * Unicode Block: Unified Canadian Aboriginal Syllabics Extended-A
 * Range: U+11AB0..U+11ABF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 */
#ifndef UC_H_UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED_A
#define UC_H_UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED_A

#define UC_MACRO_NAME_11AB0 0x11AB0 // 𑪰 CANADIAN SYLLABICS NATTILIK HI
#define UC_MACRO_NAME_11AB1 0x11AB1 // 𑪱 CANADIAN SYLLABICS NATTILIK HII
#define UC_MACRO_NAME_11AB2 0x11AB2 // 𑪲 CANADIAN SYLLABICS NATTILIK HO
#define UC_MACRO_NAME_11AB3 0x11AB3 // 𑪳 CANADIAN SYLLABICS NATTILIK HOO
#define UC_MACRO_NAME_11AB4 0x11AB4 // 𑪴 CANADIAN SYLLABICS NATTILIK HA
#define UC_MACRO_NAME_11AB5 0x11AB5 // 𑪵 CANADIAN SYLLABICS NATTILIK HAA
#define UC_MACRO_NAME_11AB6 0x11AB6 // 𑪶 CANADIAN SYLLABICS NATTILIK SHRI
#define UC_MACRO_NAME_11AB7 0x11AB7 // 𑪷 CANADIAN SYLLABICS NATTILIK SHRII
#define UC_MACRO_NAME_11AB8 0x11AB8 // 𑪸 CANADIAN SYLLABICS NATTILIK SHRO
#define UC_MACRO_NAME_11AB9 0x11AB9 // 𑪹 CANADIAN SYLLABICS NATTILIK SHROO
#define UC_MACRO_NAME_11ABA 0x11ABA // 𑪺 CANADIAN SYLLABICS NATTILIK SHRA
#define UC_MACRO_NAME_11ABB 0x11ABB // 𑪻 CANADIAN SYLLABICS NATTILIK SHRAA
#define UC_MACRO_NAME_11ABC 0x11ABC // 𑪼 CANADIAN SYLLABICS SPE
#define UC_MACRO_NAME_11ABD 0x11ABD // 𑪽 CANADIAN SYLLABICS SPI
#define UC_MACRO_NAME_11ABE 0x11ABE // 𑪾 CANADIAN SYLLABICS SPO
#define UC_MACRO_NAME_11ABF 0x11ABF // 𑪿 CANADIAN SYLLABICS SPA


#endif // UC_H_UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED_A
