/*
 * Unicode Block: Unified Canadian Aboriginal Syllabics Extended
 * Range: U+18B0..U+18FF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Unified Canadian Aboriginal Syllabics Extended is a Unicode block
 * containing extensions to the Canadian syllabics contained in the
 * Unified Canadian Aboriginal Syllabics Unicode block for some dialects
 * of Cree , Ojibwe , Dene , and Carrier .
 * The following Unicode-related documents record the purpose and process
 * of defining specific characters in the Unified Canadian Aboriginal
 * Syllabics Extended block:
 *
 */
#ifndef UC_H_UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED
#define UC_H_UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED

#define UC_MACRO_NAME_18B0 0x18B0 // ᢰ CANADIAN SYLLABICS OY
#define UC_MACRO_NAME_18B1 0x18B1 // ᢱ CANADIAN SYLLABICS AY
#define UC_MACRO_NAME_18B2 0x18B2 // ᢲ CANADIAN SYLLABICS AAY
#define UC_MACRO_NAME_18B3 0x18B3 // ᢳ CANADIAN SYLLABICS WAY
#define UC_MACRO_NAME_18B4 0x18B4 // ᢴ CANADIAN SYLLABICS POY
#define UC_MACRO_NAME_18B5 0x18B5 // ᢵ CANADIAN SYLLABICS PAY
#define UC_MACRO_NAME_18B6 0x18B6 // ᢶ CANADIAN SYLLABICS PWOY
#define UC_MACRO_NAME_18B7 0x18B7 // ᢷ CANADIAN SYLLABICS TAY
#define UC_MACRO_NAME_18B8 0x18B8 // ᢸ CANADIAN SYLLABICS KAY
#define UC_MACRO_NAME_18B9 0x18B9 // ᢹ CANADIAN SYLLABICS KWAY
#define UC_MACRO_NAME_18BA 0x18BA // ᢺ CANADIAN SYLLABICS MAY
#define UC_MACRO_NAME_18BB 0x18BB // ᢻ CANADIAN SYLLABICS NOY
#define UC_MACRO_NAME_18BC 0x18BC // ᢼ CANADIAN SYLLABICS NAY
#define UC_MACRO_NAME_18BD 0x18BD // ᢽ CANADIAN SYLLABICS LAY
#define UC_MACRO_NAME_18BE 0x18BE // ᢾ CANADIAN SYLLABICS SOY
#define UC_MACRO_NAME_18BF 0x18BF // ᢿ CANADIAN SYLLABICS SAY
#define UC_MACRO_NAME_18C0 0x18C0 // ᣀ CANADIAN SYLLABICS SHOY
#define UC_MACRO_NAME_18C1 0x18C1 // ᣁ CANADIAN SYLLABICS SHAY
#define UC_MACRO_NAME_18C2 0x18C2 // ᣂ CANADIAN SYLLABICS SHWOY
#define UC_MACRO_NAME_18C3 0x18C3 // ᣃ CANADIAN SYLLABICS YOY
#define UC_MACRO_NAME_18C4 0x18C4 // ᣄ CANADIAN SYLLABICS YAY
#define UC_MACRO_NAME_18C5 0x18C5 // ᣅ CANADIAN SYLLABICS RAY
#define UC_MACRO_NAME_18C6 0x18C6 // ᣆ CANADIAN SYLLABICS NWI
#define UC_MACRO_NAME_18C7 0x18C7 // ᣇ CANADIAN SYLLABICS OJIBWAY NWI
#define UC_MACRO_NAME_18C8 0x18C8 // ᣈ CANADIAN SYLLABICS NWII
#define UC_MACRO_NAME_18C9 0x18C9 // ᣉ CANADIAN SYLLABICS OJIBWAY NWII
#define UC_MACRO_NAME_18CA 0x18CA // ᣊ CANADIAN SYLLABICS NWO
#define UC_MACRO_NAME_18CB 0x18CB // ᣋ CANADIAN SYLLABICS OJIBWAY NWO
#define UC_MACRO_NAME_18CC 0x18CC // ᣌ CANADIAN SYLLABICS NWOO
#define UC_MACRO_NAME_18CD 0x18CD // ᣍ CANADIAN SYLLABICS OJIBWAY NWOO
#define UC_MACRO_NAME_18CE 0x18CE // ᣎ CANADIAN SYLLABICS RWEE
#define UC_MACRO_NAME_18CF 0x18CF // ᣏ CANADIAN SYLLABICS RWI
#define UC_MACRO_NAME_18D0 0x18D0 // ᣐ CANADIAN SYLLABICS RWII
#define UC_MACRO_NAME_18D1 0x18D1 // ᣑ CANADIAN SYLLABICS RWO
#define UC_MACRO_NAME_18D2 0x18D2 // ᣒ CANADIAN SYLLABICS RWOO
#define UC_MACRO_NAME_18D3 0x18D3 // ᣓ CANADIAN SYLLABICS RWA
#define UC_MACRO_NAME_18D4 0x18D4 // ᣔ CANADIAN SYLLABICS OJIBWAY P
#define UC_MACRO_NAME_18D5 0x18D5 // ᣕ CANADIAN SYLLABICS OJIBWAY T
#define UC_MACRO_NAME_18D6 0x18D6 // ᣖ CANADIAN SYLLABICS OJIBWAY K
#define UC_MACRO_NAME_18D7 0x18D7 // ᣗ CANADIAN SYLLABICS OJIBWAY C
#define UC_MACRO_NAME_18D8 0x18D8 // ᣘ CANADIAN SYLLABICS OJIBWAY M
#define UC_MACRO_NAME_18D9 0x18D9 // ᣙ CANADIAN SYLLABICS OJIBWAY N
#define UC_MACRO_NAME_18DA 0x18DA // ᣚ CANADIAN SYLLABICS OJIBWAY S
#define UC_MACRO_NAME_18DB 0x18DB // ᣛ CANADIAN SYLLABICS OJIBWAY SH
#define UC_MACRO_NAME_18DC 0x18DC // ᣜ CANADIAN SYLLABICS EASTERN W
#define UC_MACRO_NAME_18DD 0x18DD // ᣝ CANADIAN SYLLABICS WESTERN W
#define UC_MACRO_NAME_18DE 0x18DE // ᣞ CANADIAN SYLLABICS FINAL SMALL RING
#define UC_MACRO_NAME_18DF 0x18DF // ᣟ CANADIAN SYLLABICS FINAL RAISED DOT
#define UC_MACRO_NAME_18E0 0x18E0 // ᣠ CANADIAN SYLLABICS R-CREE RWE
#define UC_MACRO_NAME_18E1 0x18E1 // ᣡ CANADIAN SYLLABICS WEST-CREE LOO
#define UC_MACRO_NAME_18E2 0x18E2 // ᣢ CANADIAN SYLLABICS WEST-CREE LAA
#define UC_MACRO_NAME_18E3 0x18E3 // ᣣ CANADIAN SYLLABICS THWE
#define UC_MACRO_NAME_18E4 0x18E4 // ᣤ CANADIAN SYLLABICS THWA
#define UC_MACRO_NAME_18E5 0x18E5 // ᣥ CANADIAN SYLLABICS TTHWE
#define UC_MACRO_NAME_18E6 0x18E6 // ᣦ CANADIAN SYLLABICS TTHOO
#define UC_MACRO_NAME_18E7 0x18E7 // ᣧ CANADIAN SYLLABICS TTHAA
#define UC_MACRO_NAME_18E8 0x18E8 // ᣨ CANADIAN SYLLABICS TLHWE
#define UC_MACRO_NAME_18E9 0x18E9 // ᣩ CANADIAN SYLLABICS TLHOO
#define UC_MACRO_NAME_18EA 0x18EA // ᣪ CANADIAN SYLLABICS SAYISI SHWE
#define UC_MACRO_NAME_18EB 0x18EB // ᣫ CANADIAN SYLLABICS SAYISI SHOO
#define UC_MACRO_NAME_18EC 0x18EC // ᣬ CANADIAN SYLLABICS SAYISI HOO
#define UC_MACRO_NAME_18ED 0x18ED // ᣭ CANADIAN SYLLABICS CARRIER GWU
#define UC_MACRO_NAME_18EE 0x18EE // ᣮ CANADIAN SYLLABICS CARRIER DENE GEE
#define UC_MACRO_NAME_18EF 0x18EF // ᣯ CANADIAN SYLLABICS CARRIER GAA
#define UC_MACRO_NAME_18F0 0x18F0 // ᣰ CANADIAN SYLLABICS CARRIER GWA
#define UC_MACRO_NAME_18F1 0x18F1 // ᣱ CANADIAN SYLLABICS SAYISI JUU
#define UC_MACRO_NAME_18F2 0x18F2 // ᣲ CANADIAN SYLLABICS CARRIER JWA
#define UC_MACRO_NAME_18F3 0x18F3 // ᣳ CANADIAN SYLLABICS BEAVER DENE L
#define UC_MACRO_NAME_18F4 0x18F4 // ᣴ CANADIAN SYLLABICS BEAVER DENE R
#define UC_MACRO_NAME_18F5 0x18F5 // ᣵ CANADIAN SYLLABICS CARRIER DENTAL S


#endif // UC_H_UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED
