/*
 * Unicode Block: Vedic Extensions
 * Range: U+1CD0..U+1CFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Vedic Extensions is a Unicode block containing characters for
 * representing tones and other vedic symbols in Devanagari and other
 * Indic scripts. Related symbols (also used in many scripts to represent
 * vedic accents) are defined in two other blocks: Devanagari
 * (U+0900–U+097F) and Devanagari Extended (U+A8E0–U+A8FF).
 *
 */
#ifndef UC_H_VEDIC_EXTENSIONS
#define UC_H_VEDIC_EXTENSIONS

#define UC_MACRO_NAME_1CD0 0x1CD0 // ᳐ VEDIC TONE KARSHANA
#define UC_MACRO_NAME_1CD1 0x1CD1 // ᳑ VEDIC TONE SHARA
#define UC_MACRO_NAME_1CD2 0x1CD2 // ᳒ VEDIC TONE PRENKHA
#define UC_MACRO_NAME_1CD3 0x1CD3 // ᳓ VEDIC SIGN NIHSHVASA
#define UC_MACRO_NAME_1CD4 0x1CD4 // ᳔ VEDIC SIGN YAJURVEDIC MIDLINE SVARITA
#define UC_MACRO_NAME_1CD5 0x1CD5 // ᳕ VEDIC TONE YAJURVEDIC AGGRAVATED INDEPENDENT SVARITA
#define UC_MACRO_NAME_1CD6 0x1CD6 // ᳖ VEDIC TONE YAJURVEDIC INDEPENDENT SVARITA
#define UC_MACRO_NAME_1CD7 0x1CD7 // ᳗ VEDIC TONE YAJURVEDIC KATHAKA INDEPENDENT SVARITA
#define UC_MACRO_NAME_1CD8 0x1CD8 // ᳘ VEDIC TONE CANDRA BELOW
#define UC_MACRO_NAME_1CD9 0x1CD9 // ᳙ VEDIC TONE YAJURVEDIC KATHAKA INDEPENDENT SVARITA SCHROEDER
#define UC_MACRO_NAME_1CDA 0x1CDA // ᳚ VEDIC TONE DOUBLE SVARITA
#define UC_MACRO_NAME_1CDB 0x1CDB // ᳛ VEDIC TONE TRIPLE SVARITA
#define UC_MACRO_NAME_1CDC 0x1CDC // ᳜ VEDIC TONE KATHAKA ANUDATTA
#define UC_MACRO_NAME_1CDD 0x1CDD // ᳝ VEDIC TONE DOT BELOW
#define UC_MACRO_NAME_1CDE 0x1CDE // ᳞ VEDIC TONE TWO DOTS BELOW
#define UC_MACRO_NAME_1CDF 0x1CDF // ᳟ VEDIC TONE THREE DOTS BELOW
#define UC_MACRO_NAME_1CE0 0x1CE0 // ᳠ VEDIC TONE RIGVEDIC KASHMIRI INDEPENDENT SVARITA
#define UC_MACRO_NAME_1CE1 0x1CE1 // ᳡ VEDIC TONE ATHARVAVEDIC INDEPENDENT SVARITA
#define UC_MACRO_NAME_1CE2 0x1CE2 // ᳢ VEDIC SIGN VISARGA SVARITA
#define UC_MACRO_NAME_1CE3 0x1CE3 // ᳣ VEDIC SIGN VISARGA UDATTA
#define UC_MACRO_NAME_1CE4 0x1CE4 // ᳤ VEDIC SIGN REVERSED VISARGA UDATTA
#define UC_MACRO_NAME_1CE5 0x1CE5 // ᳥ VEDIC SIGN VISARGA ANUDATTA
#define UC_MACRO_NAME_1CE6 0x1CE6 // ᳦ VEDIC SIGN REVERSED VISARGA ANUDATTA
#define UC_MACRO_NAME_1CE7 0x1CE7 // ᳧ VEDIC SIGN VISARGA UDATTA WITH TAIL
#define UC_MACRO_NAME_1CE8 0x1CE8 // ᳨ VEDIC SIGN VISARGA ANUDATTA WITH TAIL
#define UC_MACRO_NAME_1CE9 0x1CE9 // ᳩ VEDIC SIGN ANUSVARA ANTARGOMUKHA
#define UC_MACRO_NAME_1CEA 0x1CEA // ᳪ VEDIC SIGN ANUSVARA BAHIRGOMUKHA
#define UC_MACRO_NAME_1CEB 0x1CEB // ᳫ VEDIC SIGN ANUSVARA VAMAGOMUKHA
#define UC_MACRO_NAME_1CEC 0x1CEC // ᳬ VEDIC SIGN ANUSVARA VAMAGOMUKHA WITH TAIL
#define UC_MACRO_NAME_1CED 0x1CED // ᳭ VEDIC SIGN TIRYAK
#define UC_MACRO_NAME_1CEE 0x1CEE // ᳮ VEDIC SIGN HEXIFORM LONG ANUSVARA
#define UC_MACRO_NAME_1CEF 0x1CEF // ᳯ VEDIC SIGN LONG ANUSVARA
#define UC_MACRO_NAME_1CF0 0x1CF0 // ᳰ VEDIC SIGN RTHANG LONG ANUSVARA
#define UC_MACRO_NAME_1CF1 0x1CF1 // ᳱ VEDIC SIGN ANUSVARA UBHAYATO MUKHA
#define UC_MACRO_NAME_1CF2 0x1CF2 // ᳲ VEDIC SIGN ARDHAVISARGA
#define UC_MACRO_NAME_1CF3 0x1CF3 // ᳳ VEDIC SIGN ROTATED ARDHAVISARGA
#define UC_MACRO_NAME_1CF4 0x1CF4 // ᳴ VEDIC TONE CANDRA ABOVE
#define UC_MACRO_NAME_1CF5 0x1CF5 // ᳵ VEDIC SIGN JIHVAMULIYA
#define UC_MACRO_NAME_1CF6 0x1CF6 // ᳶ VEDIC SIGN UPADHMANIYA
#define UC_MACRO_NAME_1CF7 0x1CF7 // ᳷ VEDIC SIGN ATIKRAMA
#define UC_MACRO_NAME_1CF8 0x1CF8 // ᳸ VEDIC TONE RING ABOVE
#define UC_MACRO_NAME_1CF9 0x1CF9 // ᳹ VEDIC TONE DOUBLE RING ABOVE
#define UC_MACRO_NAME_1CFA 0x1CFA // ᳺ VEDIC SIGN DOUBLE ANUSVARA ANTARGOMUKHA


#endif // UC_H_VEDIC_EXTENSIONS
