/*
 * Unicode Block: Vertical Forms
 * Range: U+FE10..U+FE1F
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Vertical Forms is a Unicode block containing vertical punctuation for
 * compatibility characters with the Chinese Standard GB 18030 .
 * In the Unicode specification, U+FE18 ︘ PRESENTATION FORM FOR VERTICAL
 * RIGHT WHITE LENTICULAR BRAKCET has a typo in its name; "BRACKET" is
 * spelt as "BRAKCET".
 *
 */
#ifndef UC_H_VERTICAL_FORMS
#define UC_H_VERTICAL_FORMS

#define UC_MACRO_NAME_FE10 0xFE10 // ︐ PRESENTATION FORM FOR VERTICAL COMMA
#define UC_MACRO_NAME_FE11 0xFE11 // ︑ PRESENTATION FORM FOR VERTICAL IDEOGRAPHIC COMMA
#define UC_MACRO_NAME_FE12 0xFE12 // ︒ PRESENTATION FORM FOR VERTICAL IDEOGRAPHIC FULL STOP
#define UC_MACRO_NAME_FE13 0xFE13 // ︓ PRESENTATION FORM FOR VERTICAL COLON
#define UC_MACRO_NAME_FE14 0xFE14 // ︔ PRESENTATION FORM FOR VERTICAL SEMICOLON
#define UC_MACRO_NAME_FE15 0xFE15 // ︕ PRESENTATION FORM FOR VERTICAL EXCLAMATION MARK
#define UC_MACRO_NAME_FE16 0xFE16 // ︖ PRESENTATION FORM FOR VERTICAL QUESTION MARK
#define UC_MACRO_NAME_FE17 0xFE17 // ︗ PRESENTATION FORM FOR VERTICAL LEFT WHITE LENTICULAR BRACKET
#define UC_MACRO_NAME_FE18 0xFE18 // ︘ PRESENTATION FORM FOR VERTICAL RIGHT WHITE LENTICULAR BRAKCET
#define UC_MACRO_NAME_FE19 0xFE19 // ︙ PRESENTATION FORM FOR VERTICAL HORIZONTAL ELLIPSIS


#endif // UC_H_VERTICAL_FORMS
