/*
 * Unicode Block: Yijing Hexagram Symbols
 * Range: U+4DC0..U+4DFF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Yijing Hexagram Symbols is a Unicode block containing the 64 hexagrams
 * from the I Ching .
 * The following Unicode-related documents record the purpose and process
 * of defining specific characters in the Yijing Hexagram Symbols block:
 *
 */
#ifndef UC_H_YIJING_HEXAGRAM_SYMBOLS
#define UC_H_YIJING_HEXAGRAM_SYMBOLS

#define UC_MACRO_NAME_4DC0 0x4DC0 // ䷀ HEXAGRAM FOR THE CREATIVE HEAVEN
#define UC_MACRO_NAME_4DC1 0x4DC1 // ䷁ HEXAGRAM FOR THE RECEPTIVE EARTH
#define UC_MACRO_NAME_4DC2 0x4DC2 // ䷂ HEXAGRAM FOR DIFFICULTY AT THE BEGINNING
#define UC_MACRO_NAME_4DC3 0x4DC3 // ䷃ HEXAGRAM FOR YOUTHFUL FOLLY
#define UC_MACRO_NAME_4DC4 0x4DC4 // ䷄ HEXAGRAM FOR WAITING
#define UC_MACRO_NAME_4DC5 0x4DC5 // ䷅ HEXAGRAM FOR CONFLICT
#define UC_MACRO_NAME_4DC6 0x4DC6 // ䷆ HEXAGRAM FOR THE ARMY
#define UC_MACRO_NAME_4DC7 0x4DC7 // ䷇ HEXAGRAM FOR HOLDING TOGETHER
#define UC_MACRO_NAME_4DC8 0x4DC8 // ䷈ HEXAGRAM FOR SMALL TAMING
#define UC_MACRO_NAME_4DC9 0x4DC9 // ䷉ HEXAGRAM FOR TREADING
#define UC_MACRO_NAME_4DCA 0x4DCA // ䷊ HEXAGRAM FOR PEACE
#define UC_MACRO_NAME_4DCB 0x4DCB // ䷋ HEXAGRAM FOR STANDSTILL
#define UC_MACRO_NAME_4DCC 0x4DCC // ䷌ HEXAGRAM FOR FELLOWSHIP
#define UC_MACRO_NAME_4DCD 0x4DCD // ䷍ HEXAGRAM FOR GREAT POSSESSION
#define UC_MACRO_NAME_4DCE 0x4DCE // ䷎ HEXAGRAM FOR MODESTY
#define UC_MACRO_NAME_4DCF 0x4DCF // ䷏ HEXAGRAM FOR ENTHUSIASM
#define UC_MACRO_NAME_4DD0 0x4DD0 // ䷐ HEXAGRAM FOR FOLLOWING
#define UC_MACRO_NAME_4DD1 0x4DD1 // ䷑ HEXAGRAM FOR WORK ON THE DECAYED
#define UC_MACRO_NAME_4DD2 0x4DD2 // ䷒ HEXAGRAM FOR APPROACH
#define UC_MACRO_NAME_4DD3 0x4DD3 // ䷓ HEXAGRAM FOR CONTEMPLATION
#define UC_MACRO_NAME_4DD4 0x4DD4 // ䷔ HEXAGRAM FOR BITING THROUGH
#define UC_MACRO_NAME_4DD5 0x4DD5 // ䷕ HEXAGRAM FOR GRACE
#define UC_MACRO_NAME_4DD6 0x4DD6 // ䷖ HEXAGRAM FOR SPLITTING APART
#define UC_MACRO_NAME_4DD7 0x4DD7 // ䷗ HEXAGRAM FOR RETURN
#define UC_MACRO_NAME_4DD8 0x4DD8 // ䷘ HEXAGRAM FOR INNOCENCE
#define UC_MACRO_NAME_4DD9 0x4DD9 // ䷙ HEXAGRAM FOR GREAT TAMING
#define UC_MACRO_NAME_4DDA 0x4DDA // ䷚ HEXAGRAM FOR MOUTH CORNERS
#define UC_MACRO_NAME_4DDB 0x4DDB // ䷛ HEXAGRAM FOR GREAT PREPONDERANCE
#define UC_MACRO_NAME_4DDC 0x4DDC // ䷜ HEXAGRAM FOR THE ABYSMAL WATER
#define UC_MACRO_NAME_4DDD 0x4DDD // ䷝ HEXAGRAM FOR THE CLINGING FIRE
#define UC_MACRO_NAME_4DDE 0x4DDE // ䷞ HEXAGRAM FOR INFLUENCE
#define UC_MACRO_NAME_4DDF 0x4DDF // ䷟ HEXAGRAM FOR DURATION
#define UC_MACRO_NAME_4DE0 0x4DE0 // ䷠ HEXAGRAM FOR RETREAT
#define UC_MACRO_NAME_4DE1 0x4DE1 // ䷡ HEXAGRAM FOR GREAT POWER
#define UC_MACRO_NAME_4DE2 0x4DE2 // ䷢ HEXAGRAM FOR PROGRESS
#define UC_MACRO_NAME_4DE3 0x4DE3 // ䷣ HEXAGRAM FOR DARKENING OF THE LIGHT
#define UC_MACRO_NAME_4DE4 0x4DE4 // ䷤ HEXAGRAM FOR THE FAMILY
#define UC_MACRO_NAME_4DE5 0x4DE5 // ䷥ HEXAGRAM FOR OPPOSITION
#define UC_MACRO_NAME_4DE6 0x4DE6 // ䷦ HEXAGRAM FOR OBSTRUCTION
#define UC_MACRO_NAME_4DE7 0x4DE7 // ䷧ HEXAGRAM FOR DELIVERANCE
#define UC_MACRO_NAME_4DE8 0x4DE8 // ䷨ HEXAGRAM FOR DECREASE
#define UC_MACRO_NAME_4DE9 0x4DE9 // ䷩ HEXAGRAM FOR INCREASE
#define UC_MACRO_NAME_4DEA 0x4DEA // ䷪ HEXAGRAM FOR BREAKTHROUGH
#define UC_MACRO_NAME_4DEB 0x4DEB // ䷫ HEXAGRAM FOR COMING TO MEET
#define UC_MACRO_NAME_4DEC 0x4DEC // ䷬ HEXAGRAM FOR GATHERING TOGETHER
#define UC_MACRO_NAME_4DED 0x4DED // ䷭ HEXAGRAM FOR PUSHING UPWARD
#define UC_MACRO_NAME_4DEE 0x4DEE // ䷮ HEXAGRAM FOR OPPRESSION
#define UC_MACRO_NAME_4DEF 0x4DEF // ䷯ HEXAGRAM FOR THE WELL
#define UC_MACRO_NAME_4DF0 0x4DF0 // ䷰ HEXAGRAM FOR REVOLUTION
#define UC_MACRO_NAME_4DF1 0x4DF1 // ䷱ HEXAGRAM FOR THE CAULDRON
#define UC_MACRO_NAME_4DF2 0x4DF2 // ䷲ HEXAGRAM FOR THE AROUSING THUNDER
#define UC_MACRO_NAME_4DF3 0x4DF3 // ䷳ HEXAGRAM FOR THE KEEPING STILL MOUNTAIN
#define UC_MACRO_NAME_4DF4 0x4DF4 // ䷴ HEXAGRAM FOR DEVELOPMENT
#define UC_MACRO_NAME_4DF5 0x4DF5 // ䷵ HEXAGRAM FOR THE MARRYING MAIDEN
#define UC_MACRO_NAME_4DF6 0x4DF6 // ䷶ HEXAGRAM FOR ABUNDANCE
#define UC_MACRO_NAME_4DF7 0x4DF7 // ䷷ HEXAGRAM FOR THE WANDERER
#define UC_MACRO_NAME_4DF8 0x4DF8 // ䷸ HEXAGRAM FOR THE GENTLE WIND
#define UC_MACRO_NAME_4DF9 0x4DF9 // ䷹ HEXAGRAM FOR THE JOYOUS LAKE
#define UC_MACRO_NAME_4DFA 0x4DFA // ䷺ HEXAGRAM FOR DISPERSION
#define UC_MACRO_NAME_4DFB 0x4DFB // ䷻ HEXAGRAM FOR LIMITATION
#define UC_MACRO_NAME_4DFC 0x4DFC // ䷼ HEXAGRAM FOR INNER TRUTH
#define UC_MACRO_NAME_4DFD 0x4DFD // ䷽ HEXAGRAM FOR SMALL PREPONDERANCE
#define UC_MACRO_NAME_4DFE 0x4DFE // ䷾ HEXAGRAM FOR AFTER COMPLETION
#define UC_MACRO_NAME_4DFF 0x4DFF // ䷿ HEXAGRAM FOR BEFORE COMPLETION


#endif // UC_H_YIJING_HEXAGRAM_SYMBOLS
