/*
 * Unicode Block: Yi Radicals
 * Range: U+A490..U+A4CF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Yi Radicals is a Unicode block containing character elements used for
 * organizing Yi dictionaries in the standard Liangshan Yi script.
 *
 */
#ifndef UC_H_YI_RADICALS
#define UC_H_YI_RADICALS

#define UC_MACRO_NAME_A490 0xA490 // ꒐ YI RADICAL QOT
#define UC_MACRO_NAME_A491 0xA491 // ꒑ YI RADICAL LI
#define UC_MACRO_NAME_A492 0xA492 // ꒒ YI RADICAL KIT
#define UC_MACRO_NAME_A493 0xA493 // ꒓ YI RADICAL NYIP
#define UC_MACRO_NAME_A494 0xA494 // ꒔ YI RADICAL CYP
#define UC_MACRO_NAME_A495 0xA495 // ꒕ YI RADICAL SSI
#define UC_MACRO_NAME_A496 0xA496 // ꒖ YI RADICAL GGOP
#define UC_MACRO_NAME_A497 0xA497 // ꒗ YI RADICAL GEP
#define UC_MACRO_NAME_A498 0xA498 // ꒘ YI RADICAL MI
#define UC_MACRO_NAME_A499 0xA499 // ꒙ YI RADICAL HXIT
#define UC_MACRO_NAME_A49A 0xA49A // ꒚ YI RADICAL LYR
#define UC_MACRO_NAME_A49B 0xA49B // ꒛ YI RADICAL BBUT
#define UC_MACRO_NAME_A49C 0xA49C // ꒜ YI RADICAL MOP
#define UC_MACRO_NAME_A49D 0xA49D // ꒝ YI RADICAL YO
#define UC_MACRO_NAME_A49E 0xA49E // ꒞ YI RADICAL PUT
#define UC_MACRO_NAME_A49F 0xA49F // ꒟ YI RADICAL HXUO
#define UC_MACRO_NAME_A4A0 0xA4A0 // ꒠ YI RADICAL TAT
#define UC_MACRO_NAME_A4A1 0xA4A1 // ꒡ YI RADICAL GA
#define UC_MACRO_NAME_A4A2 0xA4A2 // ꒢ YI RADICAL ZUP
#define UC_MACRO_NAME_A4A3 0xA4A3 // ꒣ YI RADICAL CYT
#define UC_MACRO_NAME_A4A4 0xA4A4 // ꒤ YI RADICAL DDUR
#define UC_MACRO_NAME_A4A5 0xA4A5 // ꒥ YI RADICAL BUR
#define UC_MACRO_NAME_A4A6 0xA4A6 // ꒦ YI RADICAL GGUO
#define UC_MACRO_NAME_A4A7 0xA4A7 // ꒧ YI RADICAL NYOP
#define UC_MACRO_NAME_A4A8 0xA4A8 // ꒨ YI RADICAL TU
#define UC_MACRO_NAME_A4A9 0xA4A9 // ꒩ YI RADICAL OP
#define UC_MACRO_NAME_A4AA 0xA4AA // ꒪ YI RADICAL JJUT
#define UC_MACRO_NAME_A4AB 0xA4AB // ꒫ YI RADICAL ZOT
#define UC_MACRO_NAME_A4AC 0xA4AC // ꒬ YI RADICAL PYT
#define UC_MACRO_NAME_A4AD 0xA4AD // ꒭ YI RADICAL HMO
#define UC_MACRO_NAME_A4AE 0xA4AE // ꒮ YI RADICAL YIT
#define UC_MACRO_NAME_A4AF 0xA4AF // ꒯ YI RADICAL VUR
#define UC_MACRO_NAME_A4B0 0xA4B0 // ꒰ YI RADICAL SHY
#define UC_MACRO_NAME_A4B1 0xA4B1 // ꒱ YI RADICAL VEP
#define UC_MACRO_NAME_A4B2 0xA4B2 // ꒲ YI RADICAL ZA
#define UC_MACRO_NAME_A4B3 0xA4B3 // ꒳ YI RADICAL JO
#define UC_MACRO_NAME_A4B4 0xA4B4 // ꒴ YI RADICAL NZUP
#define UC_MACRO_NAME_A4B5 0xA4B5 // ꒵ YI RADICAL JJY
#define UC_MACRO_NAME_A4B6 0xA4B6 // ꒶ YI RADICAL GOT
#define UC_MACRO_NAME_A4B7 0xA4B7 // ꒷ YI RADICAL JJIE
#define UC_MACRO_NAME_A4B8 0xA4B8 // ꒸ YI RADICAL WO
#define UC_MACRO_NAME_A4B9 0xA4B9 // ꒹ YI RADICAL DU
#define UC_MACRO_NAME_A4BA 0xA4BA // ꒺ YI RADICAL SHUR
#define UC_MACRO_NAME_A4BB 0xA4BB // ꒻ YI RADICAL LIE
#define UC_MACRO_NAME_A4BC 0xA4BC // ꒼ YI RADICAL CY
#define UC_MACRO_NAME_A4BD 0xA4BD // ꒽ YI RADICAL CUOP
#define UC_MACRO_NAME_A4BE 0xA4BE // ꒾ YI RADICAL CIP
#define UC_MACRO_NAME_A4BF 0xA4BF // ꒿ YI RADICAL HXOP
#define UC_MACRO_NAME_A4C0 0xA4C0 // ꓀ YI RADICAL SHAT
#define UC_MACRO_NAME_A4C1 0xA4C1 // ꓁ YI RADICAL ZUR
#define UC_MACRO_NAME_A4C2 0xA4C2 // ꓂ YI RADICAL SHOP
#define UC_MACRO_NAME_A4C3 0xA4C3 // ꓃ YI RADICAL CHE
#define UC_MACRO_NAME_A4C4 0xA4C4 // ꓄ YI RADICAL ZZIET
#define UC_MACRO_NAME_A4C5 0xA4C5 // ꓅ YI RADICAL NBIE
#define UC_MACRO_NAME_A4C6 0xA4C6 // ꓆ YI RADICAL KE


#endif // UC_H_YI_RADICALS
