/*
 * Unicode Block: Znamenny Musical Notation
 * Range: U+1CF00..U+1CFCF
 * Properties: Unicode 17.0.0
 * Block Data: Unicode 17.0.0
 * -------------------------------------------------------------
 * Znamenny Musical Notation is a Unicode block containing characters for
 * Znamenny musical notation from Russia.
 * Few fonts support this block as of 2021. Ones that do and are free for
 * personal use include the specialist fonts Mezenets Unicode , Slavonic
 * 1.00 (non-commercial use only), Voskresensky and Smolensky , as well
 * as Symbola 14.0.
 *
 */
#ifndef UC_H_ZNAMENNY_MUSICAL_NOTATION
#define UC_H_ZNAMENNY_MUSICAL_NOTATION

#define UC_MACRO_NAME_1CF00 0x1CF00 // 𜼀 ZNAMENNY COMBINING MARK GORAZDO NIZKO S KRYZHEM ON LEFT
#define UC_MACRO_NAME_1CF01 0x1CF01 // 𜼁 ZNAMENNY COMBINING MARK NIZKO S KRYZHEM ON LEFT
#define UC_MACRO_NAME_1CF02 0x1CF02 // 𜼂 ZNAMENNY COMBINING MARK TSATA ON LEFT
#define UC_MACRO_NAME_1CF03 0x1CF03 // 𜼃 ZNAMENNY COMBINING MARK GORAZDO NIZKO ON LEFT
#define UC_MACRO_NAME_1CF04 0x1CF04 // 𜼄 ZNAMENNY COMBINING MARK NIZKO ON LEFT
#define UC_MACRO_NAME_1CF05 0x1CF05 // 𜼅 ZNAMENNY COMBINING MARK SREDNE ON LEFT
#define UC_MACRO_NAME_1CF06 0x1CF06 // 𜼆 ZNAMENNY COMBINING MARK MALO POVYSHE ON LEFT
#define UC_MACRO_NAME_1CF07 0x1CF07 // 𜼇 ZNAMENNY COMBINING MARK POVYSHE ON LEFT
#define UC_MACRO_NAME_1CF08 0x1CF08 // 𜼈 ZNAMENNY COMBINING MARK VYSOKO ON LEFT
#define UC_MACRO_NAME_1CF09 0x1CF09 // 𜼉 ZNAMENNY COMBINING MARK MALO POVYSHE S KHOKHLOM ON LEFT
#define UC_MACRO_NAME_1CF0A 0x1CF0A // 𜼊 ZNAMENNY COMBINING MARK POVYSHE S KHOKHLOM ON LEFT
#define UC_MACRO_NAME_1CF0B 0x1CF0B // 𜼋 ZNAMENNY COMBINING MARK VYSOKO S KHOKHLOM ON LEFT
#define UC_MACRO_NAME_1CF0C 0x1CF0C // 𜼌 ZNAMENNY COMBINING MARK GORAZDO NIZKO S KRYZHEM ON RIGHT
#define UC_MACRO_NAME_1CF0D 0x1CF0D // 𜼍 ZNAMENNY COMBINING MARK NIZKO S KRYZHEM ON RIGHT
#define UC_MACRO_NAME_1CF0E 0x1CF0E // 𜼎 ZNAMENNY COMBINING MARK TSATA ON RIGHT
#define UC_MACRO_NAME_1CF0F 0x1CF0F // 𜼏 ZNAMENNY COMBINING MARK GORAZDO NIZKO ON RIGHT
#define UC_MACRO_NAME_1CF10 0x1CF10 // 𜼐 ZNAMENNY COMBINING MARK NIZKO ON RIGHT
#define UC_MACRO_NAME_1CF11 0x1CF11 // 𜼑 ZNAMENNY COMBINING MARK SREDNE ON RIGHT
#define UC_MACRO_NAME_1CF12 0x1CF12 // 𜼒 ZNAMENNY COMBINING MARK MALO POVYSHE ON RIGHT
#define UC_MACRO_NAME_1CF13 0x1CF13 // 𜼓 ZNAMENNY COMBINING MARK POVYSHE ON RIGHT
#define UC_MACRO_NAME_1CF14 0x1CF14 // 𜼔 ZNAMENNY COMBINING MARK VYSOKO ON RIGHT
#define UC_MACRO_NAME_1CF15 0x1CF15 // 𜼕 ZNAMENNY COMBINING MARK MALO POVYSHE S KHOKHLOM ON RIGHT
#define UC_MACRO_NAME_1CF16 0x1CF16 // 𜼖 ZNAMENNY COMBINING MARK POVYSHE S KHOKHLOM ON RIGHT
#define UC_MACRO_NAME_1CF17 0x1CF17 // 𜼗 ZNAMENNY COMBINING MARK VYSOKO S KHOKHLOM ON RIGHT
#define UC_MACRO_NAME_1CF18 0x1CF18 // 𜼘 ZNAMENNY COMBINING MARK TSATA S KRYZHEM
#define UC_MACRO_NAME_1CF19 0x1CF19 // 𜼙 ZNAMENNY COMBINING MARK MALO POVYSHE S KRYZHEM
#define UC_MACRO_NAME_1CF1A 0x1CF1A // 𜼚 ZNAMENNY COMBINING MARK STRANNO MALO POVYSHE
#define UC_MACRO_NAME_1CF1B 0x1CF1B // 𜼛 ZNAMENNY COMBINING MARK POVYSHE S KRYZHEM
#define UC_MACRO_NAME_1CF1C 0x1CF1C // 𜼜 ZNAMENNY COMBINING MARK POVYSHE STRANNO
#define UC_MACRO_NAME_1CF1D 0x1CF1D // 𜼝 ZNAMENNY COMBINING MARK VYSOKO S KRYZHEM
#define UC_MACRO_NAME_1CF1E 0x1CF1E // 𜼞 ZNAMENNY COMBINING MARK MALO POVYSHE STRANNO
#define UC_MACRO_NAME_1CF1F 0x1CF1F // 𜼟 ZNAMENNY COMBINING MARK GORAZDO VYSOKO
#define UC_MACRO_NAME_1CF20 0x1CF20 // 𜼠 ZNAMENNY COMBINING MARK ZELO
#define UC_MACRO_NAME_1CF21 0x1CF21 // 𜼡 ZNAMENNY COMBINING MARK ON
#define UC_MACRO_NAME_1CF22 0x1CF22 // 𜼢 ZNAMENNY COMBINING MARK RAVNO
#define UC_MACRO_NAME_1CF23 0x1CF23 // 𜼣 ZNAMENNY COMBINING MARK TIKHAYA
#define UC_MACRO_NAME_1CF24 0x1CF24 // 𜼤 ZNAMENNY COMBINING MARK BORZAYA
#define UC_MACRO_NAME_1CF25 0x1CF25 // 𜼥 ZNAMENNY COMBINING MARK UDARKA
#define UC_MACRO_NAME_1CF26 0x1CF26 // 𜼦 ZNAMENNY COMBINING MARK PODVERTKA
#define UC_MACRO_NAME_1CF27 0x1CF27 // 𜼧 ZNAMENNY COMBINING MARK LOMKA
#define UC_MACRO_NAME_1CF28 0x1CF28 // 𜼨 ZNAMENNY COMBINING MARK KUPNAYA
#define UC_MACRO_NAME_1CF29 0x1CF29 // 𜼩 ZNAMENNY COMBINING MARK KACHKA
#define UC_MACRO_NAME_1CF2A 0x1CF2A // 𜼪 ZNAMENNY COMBINING MARK ZEVOK
#define UC_MACRO_NAME_1CF2B 0x1CF2B // 𜼫 ZNAMENNY COMBINING MARK SKOBA
#define UC_MACRO_NAME_1CF2C 0x1CF2C // 𜼬 ZNAMENNY COMBINING MARK RAZSEKA
#define UC_MACRO_NAME_1CF2D 0x1CF2D // 𜼭 ZNAMENNY COMBINING MARK KRYZH ON LEFT
#define UC_MACRO_NAME_1CF30 0x1CF30 // 𜼰 ZNAMENNY COMBINING TONAL RANGE MARK MRACHNO
#define UC_MACRO_NAME_1CF31 0x1CF31 // 𜼱 ZNAMENNY COMBINING TONAL RANGE MARK SVETLO
#define UC_MACRO_NAME_1CF32 0x1CF32 // 𜼲 ZNAMENNY COMBINING TONAL RANGE MARK TRESVETLO
#define UC_MACRO_NAME_1CF33 0x1CF33 // 𜼳 ZNAMENNY COMBINING MARK ZADERZHKA
#define UC_MACRO_NAME_1CF34 0x1CF34 // 𜼴 ZNAMENNY COMBINING MARK DEMESTVENNY ZADERZHKA
#define UC_MACRO_NAME_1CF35 0x1CF35 // 𜼵 ZNAMENNY COMBINING MARK OTSECHKA
#define UC_MACRO_NAME_1CF36 0x1CF36 // 𜼶 ZNAMENNY COMBINING MARK PODCHASHIE
#define UC_MACRO_NAME_1CF37 0x1CF37 // 𜼷 ZNAMENNY COMBINING MARK PODCHASHIE WITH VERTICAL STROKE
#define UC_MACRO_NAME_1CF38 0x1CF38 // 𜼸 ZNAMENNY COMBINING MARK CHASHKA
#define UC_MACRO_NAME_1CF39 0x1CF39 // 𜼹 ZNAMENNY COMBINING MARK CHASHKA POLNAYA
#define UC_MACRO_NAME_1CF3A 0x1CF3A // 𜼺 ZNAMENNY COMBINING MARK OBLACHKO
#define UC_MACRO_NAME_1CF3B 0x1CF3B // 𜼻 ZNAMENNY COMBINING MARK SOROCHYA NOZHKA
#define UC_MACRO_NAME_1CF3C 0x1CF3C // 𜼼 ZNAMENNY COMBINING MARK TOCHKA
#define UC_MACRO_NAME_1CF3D 0x1CF3D // 𜼽 ZNAMENNY COMBINING MARK DVOETOCHIE
#define UC_MACRO_NAME_1CF3E 0x1CF3E // 𜼾 ZNAMENNY COMBINING ATTACHING VERTICAL OMET
#define UC_MACRO_NAME_1CF3F 0x1CF3F // 𜼿 ZNAMENNY COMBINING MARK CURVED OMET
#define UC_MACRO_NAME_1CF40 0x1CF40 // 𜽀 ZNAMENNY COMBINING MARK KRYZH
#define UC_MACRO_NAME_1CF41 0x1CF41 // 𜽁 ZNAMENNY COMBINING LOWER TONAL RANGE INDICATOR
#define UC_MACRO_NAME_1CF42 0x1CF42 // 𜽂 ZNAMENNY PRIZNAK MODIFIER LEVEL-2
#define UC_MACRO_NAME_1CF43 0x1CF43 // 𜽃 ZNAMENNY PRIZNAK MODIFIER LEVEL-3
#define UC_MACRO_NAME_1CF44 0x1CF44 // 𜽄 ZNAMENNY PRIZNAK MODIFIER DIRECTION FLIP
#define UC_MACRO_NAME_1CF45 0x1CF45 // 𜽅 ZNAMENNY PRIZNAK MODIFIER KRYZH
#define UC_MACRO_NAME_1CF46 0x1CF46 // 𜽆 ZNAMENNY PRIZNAK MODIFIER ROG
#define UC_MACRO_NAME_1CF50 0x1CF50 // 𜽐 ZNAMENNY NEUME KRYUK
#define UC_MACRO_NAME_1CF51 0x1CF51 // 𜽑 ZNAMENNY NEUME KRYUK TIKHY
#define UC_MACRO_NAME_1CF52 0x1CF52 // 𜽒 ZNAMENNY NEUME PARAKLIT
#define UC_MACRO_NAME_1CF53 0x1CF53 // 𜽓 ZNAMENNY NEUME DVA V CHELNU
#define UC_MACRO_NAME_1CF54 0x1CF54 // 𜽔 ZNAMENNY NEUME KLYUCH
#define UC_MACRO_NAME_1CF55 0x1CF55 // 𜽕 ZNAMENNY NEUME ZANOZHEK
#define UC_MACRO_NAME_1CF56 0x1CF56 // 𜽖 ZNAMENNY NEUME STOPITSA
#define UC_MACRO_NAME_1CF57 0x1CF57 // 𜽗 ZNAMENNY NEUME STOPITSA S OCHKOM
#define UC_MACRO_NAME_1CF58 0x1CF58 // 𜽘 ZNAMENNY NEUME PEREVODKA
#define UC_MACRO_NAME_1CF59 0x1CF59 // 𜽙 ZNAMENNY NEUME PEREVODKA NEPOSTOYANNAYA
#define UC_MACRO_NAME_1CF5A 0x1CF5A // 𜽚 ZNAMENNY NEUME STOPITSA WITH SOROCHYA NOZHKA
#define UC_MACRO_NAME_1CF5B 0x1CF5B // 𜽛 ZNAMENNY NEUME CHELYUSTKA
#define UC_MACRO_NAME_1CF5C 0x1CF5C // 𜽜 ZNAMENNY NEUME PALKA
#define UC_MACRO_NAME_1CF5D 0x1CF5D // 𜽝 ZNAMENNY NEUME ZAPYATAYA
#define UC_MACRO_NAME_1CF5E 0x1CF5E // 𜽞 ZNAMENNY NEUME GOLUBCHIK BORZY
#define UC_MACRO_NAME_1CF5F 0x1CF5F // 𜽟 ZNAMENNY NEUME GOLUBCHIK TIKHY
#define UC_MACRO_NAME_1CF60 0x1CF60 // 𜽠 ZNAMENNY NEUME GOLUBCHIK MRACHNY
#define UC_MACRO_NAME_1CF61 0x1CF61 // 𜽡 ZNAMENNY NEUME GOLUBCHIK SVETLY
#define UC_MACRO_NAME_1CF62 0x1CF62 // 𜽢 ZNAMENNY NEUME GOLUBCHIK TRESVETLY
#define UC_MACRO_NAME_1CF63 0x1CF63 // 𜽣 ZNAMENNY NEUME VRAKHIYA PROSTAYA
#define UC_MACRO_NAME_1CF64 0x1CF64 // 𜽤 ZNAMENNY NEUME VRAKHIYA MRACHNAYA
#define UC_MACRO_NAME_1CF65 0x1CF65 // 𜽥 ZNAMENNY NEUME VRAKHIYA SVETLAYA
#define UC_MACRO_NAME_1CF66 0x1CF66 // 𜽦 ZNAMENNY NEUME VRAKHIYA TRESVETLAYA
#define UC_MACRO_NAME_1CF67 0x1CF67 // 𜽧 ZNAMENNY NEUME VRAKHIYA KLYUCHEVAYA PROSTAYA
#define UC_MACRO_NAME_1CF68 0x1CF68 // 𜽨 ZNAMENNY NEUME VRAKHIYA KLYUCHEVAYA MRACHNAYA
#define UC_MACRO_NAME_1CF69 0x1CF69 // 𜽩 ZNAMENNY NEUME VRAKHIYA KLYUCHEVAYA SVETLAYA
#define UC_MACRO_NAME_1CF6A 0x1CF6A // 𜽪 ZNAMENNY NEUME VRAKHIYA KLYUCHEVAYA TRESVETLAYA
#define UC_MACRO_NAME_1CF6B 0x1CF6B // 𜽫 ZNAMENNY NEUME DOUBLE ZAPYATAYA
#define UC_MACRO_NAME_1CF6C 0x1CF6C // 𜽬 ZNAMENNY NEUME REVERSED CHELYUSTKA
#define UC_MACRO_NAME_1CF6D 0x1CF6D // 𜽭 ZNAMENNY NEUME DERBITSA
#define UC_MACRO_NAME_1CF6E 0x1CF6E // 𜽮 ZNAMENNY NEUME KHAMILO
#define UC_MACRO_NAME_1CF6F 0x1CF6F // 𜽯 ZNAMENNY NEUME CHASHKA
#define UC_MACRO_NAME_1CF70 0x1CF70 // 𜽰 ZNAMENNY NEUME PODCHASHIE
#define UC_MACRO_NAME_1CF71 0x1CF71 // 𜽱 ZNAMENNY NEUME SKAMEYTSA MRACHNAYA
#define UC_MACRO_NAME_1CF72 0x1CF72 // 𜽲 ZNAMENNY NEUME SKAMEYTSA SVETLAYA
#define UC_MACRO_NAME_1CF73 0x1CF73 // 𜽳 ZNAMENNY NEUME SKAMEYTSA TRESVETLAYA
#define UC_MACRO_NAME_1CF74 0x1CF74 // 𜽴 ZNAMENNY NEUME SKAMEYTSA TIKHAYA
#define UC_MACRO_NAME_1CF75 0x1CF75 // 𜽵 ZNAMENNY NEUME DEMESTVENNY KLYUCH
#define UC_MACRO_NAME_1CF76 0x1CF76 // 𜽶 ZNAMENNY NEUME SKAMEYTSA KLYUCHEVAYA SVETLAYA
#define UC_MACRO_NAME_1CF77 0x1CF77 // 𜽷 ZNAMENNY NEUME SKAMEYTSA KLYUCHENEPOSTOYANNAYA
#define UC_MACRO_NAME_1CF78 0x1CF78 // 𜽸 ZNAMENNY NEUME SKAMEYTSA KLYUCHEVAYA TIKHAYA
#define UC_MACRO_NAME_1CF79 0x1CF79 // 𜽹 ZNAMENNY NEUME SKAMEYTSA DVOECHELNAYA PROSTAYA
#define UC_MACRO_NAME_1CF7A 0x1CF7A // 𜽺 ZNAMENNY NEUME SKAMEYTSA DVOECHELNAYA SVETLAYA
#define UC_MACRO_NAME_1CF7B 0x1CF7B // 𜽻 ZNAMENNY NEUME SKAMEYTSA DVOECHELNAYA NEPOSTOYANNAYA
#define UC_MACRO_NAME_1CF7C 0x1CF7C // 𜽼 ZNAMENNY NEUME SKAMEYTSA DVOECHELNAYA KLYUCHEVAYA
#define UC_MACRO_NAME_1CF7D 0x1CF7D // 𜽽 ZNAMENNY NEUME SLOZHITIE
#define UC_MACRO_NAME_1CF7E 0x1CF7E // 𜽾 ZNAMENNY NEUME SLOZHITIE S ZAPYATOY
#define UC_MACRO_NAME_1CF7F 0x1CF7F // 𜽿 ZNAMENNY NEUME SLOZHITIE ZAKRYTOE
#define UC_MACRO_NAME_1CF80 0x1CF80 // 𜾀 ZNAMENNY NEUME SLOZHITIE S KRYZHEM
#define UC_MACRO_NAME_1CF81 0x1CF81 // 𜾁 ZNAMENNY NEUME KRYZH
#define UC_MACRO_NAME_1CF82 0x1CF82 // 𜾂 ZNAMENNY NEUME ROG
#define UC_MACRO_NAME_1CF83 0x1CF83 // 𜾃 ZNAMENNY NEUME FITA
#define UC_MACRO_NAME_1CF84 0x1CF84 // 𜾄 ZNAMENNY NEUME KOBYLA
#define UC_MACRO_NAME_1CF85 0x1CF85 // 𜾅 ZNAMENNY NEUME ZMEYTSA
#define UC_MACRO_NAME_1CF86 0x1CF86 // 𜾆 ZNAMENNY NEUME STATYA
#define UC_MACRO_NAME_1CF87 0x1CF87 // 𜾇 ZNAMENNY NEUME STATYA S ZAPYATOY
#define UC_MACRO_NAME_1CF88 0x1CF88 // 𜾈 ZNAMENNY NEUME STATYA S KRYZHEM
#define UC_MACRO_NAME_1CF89 0x1CF89 // 𜾉 ZNAMENNY NEUME STATYA S ZAPYATOY I KRYZHEM
#define UC_MACRO_NAME_1CF8A 0x1CF8A // 𜾊 ZNAMENNY NEUME STATYA S KRYZHEM I ZAPYATOY
#define UC_MACRO_NAME_1CF8B 0x1CF8B // 𜾋 ZNAMENNY NEUME STATYA ZAKRYTAYA
#define UC_MACRO_NAME_1CF8C 0x1CF8C // 𜾌 ZNAMENNY NEUME STATYA ZAKRYTAYA S ZAPYATOY
#define UC_MACRO_NAME_1CF8D 0x1CF8D // 𜾍 ZNAMENNY NEUME STATYA S ROGOM
#define UC_MACRO_NAME_1CF8E 0x1CF8E // 𜾎 ZNAMENNY NEUME STATYA S DVUMYA ZAPYATYMI
#define UC_MACRO_NAME_1CF8F 0x1CF8F // 𜾏 ZNAMENNY NEUME STATYA S ZAPYATOY I PODCHASHIEM
#define UC_MACRO_NAME_1CF90 0x1CF90 // 𜾐 ZNAMENNY NEUME POLKULIZMY
#define UC_MACRO_NAME_1CF91 0x1CF91 // 𜾑 ZNAMENNY NEUME STATYA NEPOSTOYANNAYA
#define UC_MACRO_NAME_1CF92 0x1CF92 // 𜾒 ZNAMENNY NEUME STRELA PROSTAYA
#define UC_MACRO_NAME_1CF93 0x1CF93 // 𜾓 ZNAMENNY NEUME STRELA MRACHNOTIKHAYA
#define UC_MACRO_NAME_1CF94 0x1CF94 // 𜾔 ZNAMENNY NEUME STRELA KRYZHEVAYA
#define UC_MACRO_NAME_1CF95 0x1CF95 // 𜾕 ZNAMENNY NEUME STRELA POLUPOVODNAYA
#define UC_MACRO_NAME_1CF96 0x1CF96 // 𜾖 ZNAMENNY NEUME STRELA POVODNAYA
#define UC_MACRO_NAME_1CF97 0x1CF97 // 𜾗 ZNAMENNY NEUME STRELA NEPOSTOYANNAYA
#define UC_MACRO_NAME_1CF98 0x1CF98 // 𜾘 ZNAMENNY NEUME STRELA KLYUCHEPOVODNAYA
#define UC_MACRO_NAME_1CF99 0x1CF99 // 𜾙 ZNAMENNY NEUME STRELA KLYUCHENEPOSTOYANNAYA
#define UC_MACRO_NAME_1CF9A 0x1CF9A // 𜾚 ZNAMENNY NEUME STRELA TIKHAYA PUTNAYA
#define UC_MACRO_NAME_1CF9B 0x1CF9B // 𜾛 ZNAMENNY NEUME STRELA DVOECHELNAYA
#define UC_MACRO_NAME_1CF9C 0x1CF9C // 𜾜 ZNAMENNY NEUME STRELA DVOECHELNOKRYZHEVAYA
#define UC_MACRO_NAME_1CF9D 0x1CF9D // 𜾝 ZNAMENNY NEUME STRELA DVOECHELNOPOVODNAYA
#define UC_MACRO_NAME_1CF9E 0x1CF9E // 𜾞 ZNAMENNY NEUME STRELA DVOECHELNAYA KLYUCHEVAYA
#define UC_MACRO_NAME_1CF9F 0x1CF9F // 𜾟 ZNAMENNY NEUME STRELA DVOECHELNOPOVODNAYA KLYUCHEVAYA
#define UC_MACRO_NAME_1CFA0 0x1CFA0 // 𜾠 ZNAMENNY NEUME STRELA GROMNAYA WITH SINGLE ZAPYATAYA
#define UC_MACRO_NAME_1CFA1 0x1CFA1 // 𜾡 ZNAMENNY NEUME STRELA GROMOPOVODNAYA WITH SINGLE ZAPYATAYA
#define UC_MACRO_NAME_1CFA2 0x1CFA2 // 𜾢 ZNAMENNY NEUME STRELA GROMNAYA
#define UC_MACRO_NAME_1CFA3 0x1CFA3 // 𜾣 ZNAMENNY NEUME STRELA GROMOPOVODNAYA
#define UC_MACRO_NAME_1CFA4 0x1CFA4 // 𜾤 ZNAMENNY NEUME STRELA GROMOPOVODNAYA WITH DOUBLE ZAPYATAYA
#define UC_MACRO_NAME_1CFA5 0x1CFA5 // 𜾥 ZNAMENNY NEUME STRELA GROMOKRYZHEVAYA
#define UC_MACRO_NAME_1CFA6 0x1CFA6 // 𜾦 ZNAMENNY NEUME STRELA GROMOKRYZHEVAYA POVODNAYA
#define UC_MACRO_NAME_1CFA7 0x1CFA7 // 𜾧 ZNAMENNY NEUME MECHIK
#define UC_MACRO_NAME_1CFA8 0x1CFA8 // 𜾨 ZNAMENNY NEUME MECHIK POVODNY
#define UC_MACRO_NAME_1CFA9 0x1CFA9 // 𜾩 ZNAMENNY NEUME MECHIK KLYUCHEVOY
#define UC_MACRO_NAME_1CFAA 0x1CFAA // 𜾪 ZNAMENNY NEUME MECHIK KLYUCHEPOVODNY
#define UC_MACRO_NAME_1CFAB 0x1CFAB // 𜾫 ZNAMENNY NEUME MECHIK KLYUCHENEPOSTOYANNY
#define UC_MACRO_NAME_1CFAC 0x1CFAC // 𜾬 ZNAMENNY NEUME STRELA TRYASOGLASNAYA
#define UC_MACRO_NAME_1CFAD 0x1CFAD // 𜾭 ZNAMENNY NEUME STRELA TRYASOPOVODNAYA
#define UC_MACRO_NAME_1CFAE 0x1CFAE // 𜾮 ZNAMENNY NEUME STRELA TRYASOSTRELNAYA
#define UC_MACRO_NAME_1CFAF 0x1CFAF // 𜾯 ZNAMENNY NEUME OSOKA
#define UC_MACRO_NAME_1CFB0 0x1CFB0 // 𜾰 ZNAMENNY NEUME OSOKA SVETLAYA
#define UC_MACRO_NAME_1CFB1 0x1CFB1 // 𜾱 ZNAMENNY NEUME OSOKA TRESVETLAYA
#define UC_MACRO_NAME_1CFB2 0x1CFB2 // 𜾲 ZNAMENNY NEUME OSOKA KRYUKOVAYA SVETLAYA
#define UC_MACRO_NAME_1CFB3 0x1CFB3 // 𜾳 ZNAMENNY NEUME OSOKA KLYUCHEVAYA SVETLAYA
#define UC_MACRO_NAME_1CFB4 0x1CFB4 // 𜾴 ZNAMENNY NEUME OSOKA KLYUCHEVAYA NEPOSTOYANNAYA
#define UC_MACRO_NAME_1CFB5 0x1CFB5 // 𜾵 ZNAMENNY NEUME STRELA KRYUKOVAYA
#define UC_MACRO_NAME_1CFB6 0x1CFB6 // 𜾶 ZNAMENNY NEUME STRELA KRYUKOVAYA POVODNAYA
#define UC_MACRO_NAME_1CFB7 0x1CFB7 // 𜾷 ZNAMENNY NEUME STRELA KRYUKOVAYA GROMNAYA WITH SINGLE ZAPYATAYA
#define UC_MACRO_NAME_1CFB8 0x1CFB8 // 𜾸 ZNAMENNY NEUME STRELA KRYUKOVAYA GROMOPOVODNAYA WITH SINGLE ZAPYATAYA
#define UC_MACRO_NAME_1CFB9 0x1CFB9 // 𜾹 ZNAMENNY NEUME STRELA KRYUKOVAYA GROMNAYA
#define UC_MACRO_NAME_1CFBA 0x1CFBA // 𜾺 ZNAMENNY NEUME STRELA KRYUKOVAYA GROMOPOVODNAYA
#define UC_MACRO_NAME_1CFBB 0x1CFBB // 𜾻 ZNAMENNY NEUME STRELA KRYUKOVAYA GROMOPOVODNAYA WITH DOUBLE ZAPYATAYA
#define UC_MACRO_NAME_1CFBC 0x1CFBC // 𜾼 ZNAMENNY NEUME STRELA KRYUKOVAYA GROMOKRYZHEVAYA
#define UC_MACRO_NAME_1CFBD 0x1CFBD // 𜾽 ZNAMENNY NEUME STRELA KRYUKOVAYA GROMOKRYZHEVAYA POVODNAYA
#define UC_MACRO_NAME_1CFBE 0x1CFBE // 𜾾 ZNAMENNY NEUME STRELA KRYUKOVAYA TRYASKA
#define UC_MACRO_NAME_1CFBF 0x1CFBF // 𜾿 ZNAMENNY NEUME KUFISMA
#define UC_MACRO_NAME_1CFC0 0x1CFC0 // 𜿀 ZNAMENNY NEUME OBLAKO
#define UC_MACRO_NAME_1CFC1 0x1CFC1 // 𜿁 ZNAMENNY NEUME DUDA
#define UC_MACRO_NAME_1CFC2 0x1CFC2 // 𜿂 ZNAMENNY NEUME NEMKA
#define UC_MACRO_NAME_1CFC3 0x1CFC3 // 𜿃 ZNAMENNY NEUME PAUK


#endif // UC_H_ZNAMENNY_MUSICAL_NOTATION
