/* ugaritic.h – Unicode constants for U+10380 … U+1039F
*
* Generated by generate_unicode_headers.py (Unicode 17.0.0)
*
* Source data for blocks: Blocks.txt (Unicode 17.0.0)
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_UGARITIC_ALPA                         0x10380 0  // 𐎀
#define UC_UGARITIC_BETA                         0x10381 0  // 𐎁
#define UC_UGARITIC_GAMLA                        0x10382 0  // 𐎂
#define UC_UGARITIC_KHA                          0x10383 0  // 𐎃
#define UC_UGARITIC_DELTA                        0x10384 0  // 𐎄
#define UC_UGARITIC_HO                           0x10385 0  // 𐎅
#define UC_UGARITIC_WO                           0x10386 0  // 𐎆
#define UC_UGARITIC_ZETA                         0x10387 0  // 𐎇
#define UC_UGARITIC_HOTA                         0x10388 0  // 𐎈
#define UC_UGARITIC_TET                          0x10389 0  // 𐎉
#define UC_UGARITIC_YOD                          0x1038A 0  // 𐎊
#define UC_UGARITIC_KAF                          0x1038B 0  // 𐎋
#define UC_UGARITIC_SHIN                         0x1038C 0  // 𐎌
#define UC_UGARITIC_LAMDA                        0x1038D 0  // 𐎍
#define UC_UGARITIC_MEM                          0x1038E 0  // 𐎎
#define UC_UGARITIC_DHAL                         0x1038F 0  // 𐎏
#define UC_UGARITIC_NUN                          0x10390 0  // 𐎐
#define UC_UGARITIC_ZU                           0x10391 0  // 𐎑
#define UC_UGARITIC_SAMKA                        0x10392 0  // 𐎒
#define UC_UGARITIC_AIN                          0x10393 0  // 𐎓
#define UC_UGARITIC_PU                           0x10394 0  // 𐎔
#define UC_UGARITIC_SADE                         0x10395 0  // 𐎕
#define UC_UGARITIC_QOPA                         0x10396 0  // 𐎖
#define UC_UGARITIC_RASHA                        0x10397 0  // 𐎗
#define UC_UGARITIC_THANNA                       0x10398 0  // 𐎘
#define UC_UGARITIC_GHAIN                        0x10399 0  // 𐎙
#define UC_UGARITIC_TO                           0x1039A 0  // 𐎚
#define UC_UGARITIC_I                            0x1039B 0  // 𐎛
#define UC_UGARITIC_U                            0x1039C 0  // 𐎜
#define UC_UGARITIC_SSU                          0x1039D 0  // 𐎝
#define UC_UGARITIC_WORD_DIVIDER                 0x1039F 0  // 𐎟
