/* unified_canadian_aboriginal_syllabics_extended_a.h – Unicode constants for U+11AB0 … U+11ABF
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_CANADIAN_SYLLABICS_NATTILIK_HI        0x11AB0 0  // 𑪰
#define UC_CANADIAN_SYLLABICS_NATTILIK_HII       0x11AB1 0  // 𑪱
#define UC_CANADIAN_SYLLABICS_NATTILIK_HO        0x11AB2 0  // 𑪲
#define UC_CANADIAN_SYLLABICS_NATTILIK_HOO       0x11AB3 0  // 𑪳
#define UC_CANADIAN_SYLLABICS_NATTILIK_HA        0x11AB4 0  // 𑪴
#define UC_CANADIAN_SYLLABICS_NATTILIK_HAA       0x11AB5 0  // 𑪵
#define UC_CANADIAN_SYLLABICS_NATTILIK_SHRI      0x11AB6 0  // 𑪶
#define UC_CANADIAN_SYLLABICS_NATTILIK_SHRII     0x11AB7 0  // 𑪷
#define UC_CANADIAN_SYLLABICS_NATTILIK_SHRO      0x11AB8 0  // 𑪸
#define UC_CANADIAN_SYLLABICS_NATTILIK_SHROO     0x11AB9 0  // 𑪹
#define UC_CANADIAN_SYLLABICS_NATTILIK_SHRA      0x11ABA 0  // 𑪺
#define UC_CANADIAN_SYLLABICS_NATTILIK_SHRAA     0x11ABB 0  // 𑪻
#define UC_CANADIAN_SYLLABICS_SPE                0x11ABC 0  // 𑪼
#define UC_CANADIAN_SYLLABICS_SPI                0x11ABD 0  // 𑪽
#define UC_CANADIAN_SYLLABICS_SPO                0x11ABE 0  // 𑪾
#define UC_CANADIAN_SYLLABICS_SPA                0x11ABF 0  // 𑪿
