/* vedic_extensions.h – Unicode constants for U+1CD0 … U+1CFF
*
* Generated by generate_unicode_headers.py (Unicode 17.0.0)
*
* Source data for blocks: Blocks.txt (Unicode 17.0.0)
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_VEDIC_TONE_KARSHANA                   0x1CD0 0  // ᳐
#define UC_VEDIC_TONE_SHARA                      0x1CD1 0  // ᳑
#define UC_VEDIC_TONE_PRENKHA                    0x1CD2 0  // ᳒
#define UC_VEDIC_SIGN_NIHSHVASA                  0x1CD3 0  // ᳓
#define UC_VEDIC_SIGN_YAJURVEDIC_MIDLINE_SVARITA 0x1CD4 0  // ᳔
#define UC_VEDIC_TONE_YAJURVEDIC_AGGRAVATED_INDEPENDENT_SVARITA 0x1CD5 0  // ᳕
#define UC_VEDIC_TONE_YAJURVEDIC_INDEPENDENT_SVARITA 0x1CD6 0  // ᳖
#define UC_VEDIC_TONE_YAJURVEDIC_KATHAKA_INDEPENDENT_SVARITA 0x1CD7 0  // ᳗
#define UC_VEDIC_TONE_CANDRA_BELOW               0x1CD8 0  // ᳘
#define UC_VEDIC_TONE_YAJURVEDIC_KATHAKA_INDEPENDENT_SVARITA_SCHROEDER 0x1CD9 0  // ᳙
#define UC_VEDIC_TONE_DOUBLE_SVARITA             0x1CDA 0  // ᳚
#define UC_VEDIC_TONE_TRIPLE_SVARITA             0x1CDB 0  // ᳛
#define UC_VEDIC_TONE_KATHAKA_ANUDATTA           0x1CDC 0  // ᳜
#define UC_VEDIC_TONE_DOT_BELOW                  0x1CDD 0  // ᳝
#define UC_VEDIC_TONE_TWO_DOTS_BELOW             0x1CDE 0  // ᳞
#define UC_VEDIC_TONE_THREE_DOTS_BELOW           0x1CDF 0  // ᳟
#define UC_VEDIC_TONE_RIGVEDIC_KASHMIRI_INDEPENDENT_SVARITA 0x1CE0 0  // ᳠
#define UC_VEDIC_TONE_ATHARVAVEDIC_INDEPENDENT_SVARITA 0x1CE1 0  // ᳡
#define UC_VEDIC_SIGN_VISARGA_SVARITA            0x1CE2 0  // ᳢
#define UC_VEDIC_SIGN_VISARGA_UDATTA             0x1CE3 0  // ᳣
#define UC_VEDIC_SIGN_REVERSED_VISARGA_UDATTA    0x1CE4 0  // ᳤
#define UC_VEDIC_SIGN_VISARGA_ANUDATTA           0x1CE5 0  // ᳥
#define UC_VEDIC_SIGN_REVERSED_VISARGA_ANUDATTA  0x1CE6 0  // ᳦
#define UC_VEDIC_SIGN_VISARGA_UDATTA_TAIL        0x1CE7 0  // ᳧
#define UC_VEDIC_SIGN_VISARGA_ANUDATTA_TAIL      0x1CE8 0  // ᳨
#define UC_VEDIC_SIGN_ANUSVARA_ANTARGOMUKHA      0x1CE9 0  // ᳩ
#define UC_VEDIC_SIGN_ANUSVARA_BAHIRGOMUKHA      0x1CEA 0  // ᳪ
#define UC_VEDIC_SIGN_ANUSVARA_VAMAGOMUKHA       0x1CEB 0  // ᳫ
#define UC_VEDIC_SIGN_ANUSVARA_VAMAGOMUKHA_TAIL  0x1CEC 0  // ᳬ
#define UC_VEDIC_SIGN_TIRYAK                     0x1CED 0  // ᳭
#define UC_VEDIC_SIGN_HEXIFORM_LONG_ANUSVARA     0x1CEE 0  // ᳮ
#define UC_VEDIC_SIGN_LONG_ANUSVARA              0x1CEF 0  // ᳯ
#define UC_VEDIC_SIGN_RTHANG_LONG_ANUSVARA       0x1CF0 0  // ᳰ
#define UC_VEDIC_SIGN_ANUSVARA_UBHAYATO_MUKHA    0x1CF1 0  // ᳱ
#define UC_VEDIC_SIGN_ARDHAVISARGA               0x1CF2 0  // ᳲ
#define UC_VEDIC_SIGN_ROTATED_ARDHAVISARGA       0x1CF3 0  // ᳳ
#define UC_VEDIC_TONE_CANDRA_ABOVE               0x1CF4 0  // ᳴
#define UC_VEDIC_SIGN_JIHVAMULIYA                0x1CF5 0  // ᳵ
#define UC_VEDIC_SIGN_UPADHMANIYA                0x1CF6 0  // ᳶ
#define UC_VEDIC_SIGN_ATIKRAMA                   0x1CF7 0  // ᳷
#define UC_VEDIC_TONE_RING_ABOVE                 0x1CF8 0  // ᳸
#define UC_VEDIC_TONE_DOUBLE_RING_ABOVE          0x1CF9 0  // ᳹
#define UC_VEDIC_SIGN_DOUBLE_ANUSVARA_ANTARGOMUKHA 0x1CFA 0  // ᳺ
