/* vithkuqi.h – Unicode constants for U+105BB … U+105BC
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_VITHKUQI_LETTER_Y                     0x105BB 0x10594  // 𐖻/𐖔
#define UC_VITHKUQI_LETTER_ZE                    0x105BC 0x10595  // 𐖼/𐖕
