/* vithkuqi.h – Unicode constants for U+10570 … U+105BF
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via internal list)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_VITHKUQI_A                            0x10570 0x10597  // 𐕰/𐖗
#define UC_VITHKUQI_BBE                          0x10571 0x10598  // 𐕱/𐖘
#define UC_VITHKUQI_BE                           0x10572 0x10599  // 𐕲/𐖙
#define UC_VITHKUQI_CE                           0x10573 0x1059A  // 𐕳/𐖚
#define UC_VITHKUQI_CHE                          0x10574 0x1059B  // 𐕴/𐖛
#define UC_VITHKUQI_DE                           0x10575 0x1059C  // 𐕵/𐖜
#define UC_VITHKUQI_DHE                          0x10576 0x1059D  // 𐕶/𐖝
#define UC_VITHKUQI_EI                           0x10577 0x1059E  // 𐕷/𐖞
#define UC_VITHKUQI_E                            0x10578 0x1059F  // 𐕸/𐖟
#define UC_VITHKUQI_FE                           0x10579 0x105A0  // 𐕹/𐖠
#define UC_VITHKUQI_GA                           0x1057A 0x105A1  // 𐕺/𐖡
#define UC_VITHKUQI_HA                           0x1057C 0x105A3  // 𐕼/𐖣
#define UC_VITHKUQI_HHA                          0x1057D 0x105A4  // 𐕽/𐖤
#define UC_VITHKUQI_I                            0x1057E 0x105A5  // 𐕾/𐖥
#define UC_VITHKUQI_IJE                          0x1057F 0x105A6  // 𐕿/𐖦
#define UC_VITHKUQI_JE                           0x10580 0x105A7  // 𐖀/𐖧
#define UC_VITHKUQI_KA                           0x10581 0x105A8  // 𐖁/𐖨
#define UC_VITHKUQI_LA                           0x10582 0x105A9  // 𐖂/𐖩
#define UC_VITHKUQI_LLA                          0x10583 0x105AA  // 𐖃/𐖪
#define UC_VITHKUQI_ME                           0x10584 0x105AB  // 𐖄/𐖫
#define UC_VITHKUQI_NE                           0x10585 0x105AC  // 𐖅/𐖬
#define UC_VITHKUQI_NJE                          0x10586 0x105AD  // 𐖆/𐖭
#define UC_VITHKUQI_O                            0x10587 0x105AE  // 𐖇/𐖮
#define UC_VITHKUQI_PE                           0x10588 0x105AF  // 𐖈/𐖯
#define UC_VITHKUQI_QA                           0x10589 0x105B0  // 𐖉/𐖰
#define UC_VITHKUQI_RE                           0x1058A 0x105B1  // 𐖊/𐖱
#define UC_VITHKUQI_SE                           0x1058C 0x105B3  // 𐖌/𐖳
#define UC_VITHKUQI_SHE                          0x1058D 0x105B4  // 𐖍/𐖴
#define UC_VITHKUQI_TE                           0x1058E 0x105B5  // 𐖎/𐖵
#define UC_VITHKUQI_THE                          0x1058F 0x105B6  // 𐖏/𐖶
#define UC_VITHKUQI_U                            0x10590 0x105B7  // 𐖐/𐖷
#define UC_VITHKUQI_VE                           0x10591 0x105B8  // 𐖑/𐖸
#define UC_VITHKUQI_XE                           0x10592 0x105B9  // 𐖒/𐖹
#define UC_VITHKUQI_Y                            0x10594 0x105BB  // 𐖔/𐖻
#define UC_VITHKUQI_ZE                           0x10595 0x105BC  // 𐖕/𐖼
