/* Yi Radicals.h – Unicode constants for U+A490 … U+A4CF
*
* Generated by generate_unicode_headers.py from the Unicode Character Database.
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_YI_RADICAL_QOT                        0xA490   /* U+A490 (YI RADICAL QOT) ꒐ */
#define UC_YI_RADICAL_LI                         0xA491   /* U+A491 (YI RADICAL LI) ꒑ */
#define UC_YI_RADICAL_KIT                        0xA492   /* U+A492 (YI RADICAL KIT) ꒒ */
#define UC_YI_RADICAL_NYIP                       0xA493   /* U+A493 (YI RADICAL NYIP) ꒓ */
#define UC_YI_RADICAL_CYP                        0xA494   /* U+A494 (YI RADICAL CYP) ꒔ */
#define UC_YI_RADICAL_SSI                        0xA495   /* U+A495 (YI RADICAL SSI) ꒕ */
#define UC_YI_RADICAL_GGOP                       0xA496   /* U+A496 (YI RADICAL GGOP) ꒖ */
#define UC_YI_RADICAL_GEP                        0xA497   /* U+A497 (YI RADICAL GEP) ꒗ */
#define UC_YI_RADICAL_MI                         0xA498   /* U+A498 (YI RADICAL MI) ꒘ */
#define UC_YI_RADICAL_HXIT                       0xA499   /* U+A499 (YI RADICAL HXIT) ꒙ */
#define UC_YI_RADICAL_LYR                        0xA49A   /* U+A49A (YI RADICAL LYR) ꒚ */
#define UC_YI_RADICAL_BBUT                       0xA49B   /* U+A49B (YI RADICAL BBUT) ꒛ */
#define UC_YI_RADICAL_MOP                        0xA49C   /* U+A49C (YI RADICAL MOP) ꒜ */
#define UC_YI_RADICAL_YO                         0xA49D   /* U+A49D (YI RADICAL YO) ꒝ */
#define UC_YI_RADICAL_PUT                        0xA49E   /* U+A49E (YI RADICAL PUT) ꒞ */
#define UC_YI_RADICAL_HXUO                       0xA49F   /* U+A49F (YI RADICAL HXUO) ꒟ */
#define UC_YI_RADICAL_TAT                        0xA4A0   /* U+A4A0 (YI RADICAL TAT) ꒠ */
#define UC_YI_RADICAL_GA                         0xA4A1   /* U+A4A1 (YI RADICAL GA) ꒡ */
#define UC_YI_RADICAL_ZUP                        0xA4A2   /* U+A4A2 (YI RADICAL ZUP) ꒢ */
#define UC_YI_RADICAL_CYT                        0xA4A3   /* U+A4A3 (YI RADICAL CYT) ꒣ */
#define UC_YI_RADICAL_DDUR                       0xA4A4   /* U+A4A4 (YI RADICAL DDUR) ꒤ */
#define UC_YI_RADICAL_BUR                        0xA4A5   /* U+A4A5 (YI RADICAL BUR) ꒥ */
#define UC_YI_RADICAL_GGUO                       0xA4A6   /* U+A4A6 (YI RADICAL GGUO) ꒦ */
#define UC_YI_RADICAL_NYOP                       0xA4A7   /* U+A4A7 (YI RADICAL NYOP) ꒧ */
#define UC_YI_RADICAL_TU                         0xA4A8   /* U+A4A8 (YI RADICAL TU) ꒨ */
#define UC_YI_RADICAL_OP                         0xA4A9   /* U+A4A9 (YI RADICAL OP) ꒩ */
#define UC_YI_RADICAL_JJUT                       0xA4AA   /* U+A4AA (YI RADICAL JJUT) ꒪ */
#define UC_YI_RADICAL_ZOT                        0xA4AB   /* U+A4AB (YI RADICAL ZOT) ꒫ */
#define UC_YI_RADICAL_PYT                        0xA4AC   /* U+A4AC (YI RADICAL PYT) ꒬ */
#define UC_YI_RADICAL_HMO                        0xA4AD   /* U+A4AD (YI RADICAL HMO) ꒭ */
#define UC_YI_RADICAL_YIT                        0xA4AE   /* U+A4AE (YI RADICAL YIT) ꒮ */
#define UC_YI_RADICAL_VUR                        0xA4AF   /* U+A4AF (YI RADICAL VUR) ꒯ */
#define UC_YI_RADICAL_SHY                        0xA4B0   /* U+A4B0 (YI RADICAL SHY) ꒰ */
#define UC_YI_RADICAL_VEP                        0xA4B1   /* U+A4B1 (YI RADICAL VEP) ꒱ */
#define UC_YI_RADICAL_ZA                         0xA4B2   /* U+A4B2 (YI RADICAL ZA) ꒲ */
#define UC_YI_RADICAL_JO                         0xA4B3   /* U+A4B3 (YI RADICAL JO) ꒳ */
#define UC_YI_RADICAL_NZUP                       0xA4B4   /* U+A4B4 (YI RADICAL NZUP) ꒴ */
#define UC_YI_RADICAL_JJY                        0xA4B5   /* U+A4B5 (YI RADICAL JJY) ꒵ */
#define UC_YI_RADICAL_GOT                        0xA4B6   /* U+A4B6 (YI RADICAL GOT) ꒶ */
#define UC_YI_RADICAL_JJIE                       0xA4B7   /* U+A4B7 (YI RADICAL JJIE) ꒷ */
#define UC_YI_RADICAL_WO                         0xA4B8   /* U+A4B8 (YI RADICAL WO) ꒸ */
#define UC_YI_RADICAL_DU                         0xA4B9   /* U+A4B9 (YI RADICAL DU) ꒹ */
#define UC_YI_RADICAL_SHUR                       0xA4BA   /* U+A4BA (YI RADICAL SHUR) ꒺ */
#define UC_YI_RADICAL_LIE                        0xA4BB   /* U+A4BB (YI RADICAL LIE) ꒻ */
#define UC_YI_RADICAL_CY                         0xA4BC   /* U+A4BC (YI RADICAL CY) ꒼ */
#define UC_YI_RADICAL_CUOP                       0xA4BD   /* U+A4BD (YI RADICAL CUOP) ꒽ */
#define UC_YI_RADICAL_CIP                        0xA4BE   /* U+A4BE (YI RADICAL CIP) ꒾ */
#define UC_YI_RADICAL_HXOP                       0xA4BF   /* U+A4BF (YI RADICAL HXOP) ꒿ */
#define UC_YI_RADICAL_SHAT                       0xA4C0   /* U+A4C0 (YI RADICAL SHAT) ꓀ */
#define UC_YI_RADICAL_ZUR                        0xA4C1   /* U+A4C1 (YI RADICAL ZUR) ꓁ */
#define UC_YI_RADICAL_SHOP                       0xA4C2   /* U+A4C2 (YI RADICAL SHOP) ꓂ */
#define UC_YI_RADICAL_CHE                        0xA4C3   /* U+A4C3 (YI RADICAL CHE) ꓃ */
#define UC_YI_RADICAL_ZZIET                      0xA4C4   /* U+A4C4 (YI RADICAL ZZIET) ꓄ */
#define UC_YI_RADICAL_NBIE                       0xA4C5   /* U+A4C5 (YI RADICAL NBIE) ꓅ */
#define UC_YI_RADICAL_KE                         0xA4C6   /* U+A4C6 (YI RADICAL KE) ꓆ */
#define UC_UNKNOWN_A4C7                          0xA4C7   /* U+A4C7 (UNKNOWN_A4C7) */
#define UC_UNKNOWN_A4C8                          0xA4C8   /* U+A4C8 (UNKNOWN_A4C8) */
#define UC_UNKNOWN_A4C9                          0xA4C9   /* U+A4C9 (UNKNOWN_A4C9) */
#define UC_UNKNOWN_A4CA                          0xA4CA   /* U+A4CA (UNKNOWN_A4CA) */
#define UC_UNKNOWN_A4CB                          0xA4CB   /* U+A4CB (UNKNOWN_A4CB) */
#define UC_UNKNOWN_A4CC                          0xA4CC   /* U+A4CC (UNKNOWN_A4CC) */
#define UC_UNKNOWN_A4CD                          0xA4CD   /* U+A4CD (UNKNOWN_A4CD) */
#define UC_UNKNOWN_A4CE                          0xA4CE   /* U+A4CE (UNKNOWN_A4CE) */
#define UC_UNKNOWN_A4CF                          0xA4CF   /* U+A4CF (UNKNOWN_A4CF) */
