/* hatran.h – Unicode constants for U+108E0 … U+108FF
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
*
* See https://www.unicode.org/versions/latest/ for source data.


* Consistency Check:
* Total Defined Code Points: 26
* Total Significant Hex Values: 26
* Status: OK (Counts Match)

*/

#pragma once

#define UC_HATRAN_ALEPH                          0x108E0 0  // 𐣠
#define UC_HATRAN_BETH                           0x108E1 0  // 𐣡
#define UC_HATRAN_GIMEL                          0x108E2 0  // 𐣢
#define UC_HATRAN_DALETH_RESH                    0x108E3 0  // 𐣣
#define UC_HATRAN_HE                             0x108E4 0  // 𐣤
#define UC_HATRAN_WAW                            0x108E5 0  // 𐣥
#define UC_HATRAN_ZAYN                           0x108E6 0  // 𐣦
#define UC_HATRAN_HETH                           0x108E7 0  // 𐣧
#define UC_HATRAN_TETH                           0x108E8 0  // 𐣨
#define UC_HATRAN_YODH                           0x108E9 0  // 𐣩
#define UC_HATRAN_KAPH                           0x108EA 0  // 𐣪
#define UC_HATRAN_LAMEDH                         0x108EB 0  // 𐣫
#define UC_HATRAN_MEM                            0x108EC 0  // 𐣬
#define UC_HATRAN_NUN                            0x108ED 0  // 𐣭
#define UC_HATRAN_SAMEKH                         0x108EE 0  // 𐣮
#define UC_HATRAN_AYN                            0x108EF 0  // 𐣯
#define UC_HATRAN_PE                             0x108F0 0  // 𐣰
#define UC_HATRAN_SADHE                          0x108F1 0  // 𐣱
#define UC_HATRAN_QOPH                           0x108F2 0  // 𐣲
#define UC_HATRAN_SHIN                           0x108F4 0  // 𐣴
#define UC_HATRAN_TAW                            0x108F5 0  // 𐣵
#define UC_HATRAN_ONE                            0x108FB 0  // 𐣻
#define UC_HATRAN_FIVE                           0x108FC 0  // 𐣼
#define UC_HATRAN_TEN                            0x108FD 0  // 𐣽
#define UC_HATRAN_TWENTY                         0x108FE 0  // 𐣾
#define UC_HATRAN_ONE_HUNDRED                    0x108FF 0  // 𐣿
