/* phaistos_disc.h – Unicode constants for U+101D0 … U+101FF
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
*
* See https://www.unicode.org/versions/latest/ for source data.

 * The Phaistos Disc , or Phaistos Disk , is a disc of fired clay from the
 * island of Crete , Greece , possibly from the middle or late Minoan Bronze
 * Age ( second millennium BC ), bearing a text in an unknown script and
 * language. Its purpose and its original place of manufacture remain
 * disputed. It is now on display at the archaeological museum of Heraklion .
 * The name is sometimes spelled Phaestos or Festos .
 * The disc was discovered in 1908 by the Italian archaeologist Luigi Pernier
 * during the excavation of the Minoan palace of Phaistos . The disc is about
 * 16 cm (6.3 in) in diameter and is covered on each side with a spiral text,
 * consisting of a total of 241 occurrences of 45 distinct signs, which were
 * created by pressing individual sign stamps onto the soft clay before
 * firing. While its unique features initially led some scholars to suspect a
 * forgery or hoax , the disc is now generally accepted by archaeologists as
 * authentic.
 *

* Consistency Check:
* Total Defined Code Points: 46
* Total Significant Hex Values: 46
* Status: OK (Counts Match)

*/

#pragma once

#define UC_PHAISTOS_DISC_SIGN_PEDESTRIAN         0x101D0 0  // 𐇐
#define UC_PHAISTOS_DISC_SIGN_PLUMED_HEAD        0x101D1 0  // 𐇑
#define UC_PHAISTOS_DISC_SIGN_TATTOOED_HEAD      0x101D2 0  // 𐇒
#define UC_PHAISTOS_DISC_SIGN_CAPTIVE            0x101D3 0  // 𐇓
#define UC_PHAISTOS_DISC_SIGN_CHILD              0x101D4 0  // 𐇔
#define UC_PHAISTOS_DISC_SIGN_WOMAN              0x101D5 0  // 𐇕
#define UC_PHAISTOS_DISC_SIGN_HELMET             0x101D6 0  // 𐇖
#define UC_PHAISTOS_DISC_SIGN_GAUNTLET           0x101D7 0  // 𐇗
#define UC_PHAISTOS_DISC_SIGN_TIARA              0x101D8 0  // 𐇘
#define UC_PHAISTOS_DISC_SIGN_ARROW              0x101D9 0  // 𐇙
#define UC_PHAISTOS_DISC_SIGN_BOW                0x101DA 0  // 𐇚
#define UC_PHAISTOS_DISC_SIGN_SHIELD             0x101DB 0  // 𐇛
#define UC_PHAISTOS_DISC_SIGN_CLUB               0x101DC 0  // 𐇜
#define UC_PHAISTOS_DISC_SIGN_MANACLES           0x101DD 0  // 𐇝
#define UC_PHAISTOS_DISC_SIGN_MATTOCK            0x101DE 0  // 𐇞
#define UC_PHAISTOS_DISC_SIGN_SAW                0x101DF 0  // 𐇟
#define UC_PHAISTOS_DISC_SIGN_LID                0x101E0 0  // 𐇠
#define UC_PHAISTOS_DISC_SIGN_BOOMERANG          0x101E1 0  // 𐇡
#define UC_PHAISTOS_DISC_SIGN_CARPENTRY_PLANE    0x101E2 0  // 𐇢
#define UC_PHAISTOS_DISC_SIGN_DOLIUM             0x101E3 0  // 𐇣
#define UC_PHAISTOS_DISC_SIGN_COMB               0x101E4 0  // 𐇤
#define UC_PHAISTOS_DISC_SIGN_SLING              0x101E5 0  // 𐇥
#define UC_PHAISTOS_DISC_SIGN_COLUMN             0x101E6 0  // 𐇦
#define UC_PHAISTOS_DISC_SIGN_BEEHIVE            0x101E7 0  // 𐇧
#define UC_PHAISTOS_DISC_SIGN_SHIP               0x101E8 0  // 𐇨
#define UC_PHAISTOS_DISC_SIGN_HORN               0x101E9 0  // 𐇩
#define UC_PHAISTOS_DISC_SIGN_HIDE               0x101EA 0  // 𐇪
#define UC_PHAISTOS_DISC_SIGN_BULLS_LEG          0x101EB 0  // 𐇫
#define UC_PHAISTOS_DISC_SIGN_CAT                0x101EC 0  // 𐇬
#define UC_PHAISTOS_DISC_SIGN_RAM                0x101ED 0  // 𐇭
#define UC_PHAISTOS_DISC_SIGN_EAGLE              0x101EE 0  // 𐇮
#define UC_PHAISTOS_DISC_SIGN_DOVE               0x101EF 0  // 𐇯
#define UC_PHAISTOS_DISC_SIGN_TUNNY              0x101F0 0  // 𐇰
#define UC_PHAISTOS_DISC_SIGN_BEE                0x101F1 0  // 𐇱
#define UC_PHAISTOS_DISC_SIGN_PLANE_TREE         0x101F2 0  // 𐇲
#define UC_PHAISTOS_DISC_SIGN_VINE               0x101F3 0  // 𐇳
#define UC_PHAISTOS_DISC_SIGN_PAPYRUS            0x101F4 0  // 𐇴
#define UC_PHAISTOS_DISC_SIGN_ROSETTE            0x101F5 0  // 𐇵
#define UC_PHAISTOS_DISC_SIGN_LILY               0x101F6 0  // 𐇶
#define UC_PHAISTOS_DISC_SIGN_OX_BACK            0x101F7 0  // 𐇷
#define UC_PHAISTOS_DISC_SIGN_FLUTE              0x101F8 0  // 𐇸
#define UC_PHAISTOS_DISC_SIGN_GRATER             0x101F9 0  // 𐇹
#define UC_PHAISTOS_DISC_SIGN_STRAINER           0x101FA 0  // 𐇺
#define UC_PHAISTOS_DISC_SIGN_SMALL_AXE          0x101FB 0  // 𐇻
#define UC_PHAISTOS_DISC_SIGN_WAVY_BAND          0x101FC 0  // 𐇼
#define UC_PHAISTOS_DISC_SIGN_COMBINING_OBLIQUE_STROKE 0x101FD 0  // 𐇽
