/* sharada_supplement.h – Unicode constants for U+11B60 … U+11B7F
*
* Generated by generate_unicode_headers.py
* Character Properties Data (Names/Categories): Unicode 17.0.0 (via unicodedata2)
* Block Range Data (Boundaries): Unicode 17.0.0 (via unicode_blocks.json)
*
* See https://www.unicode.org/versions/latest/ for source data.

 * Sharada Supplement is a Unicode block containing Kashmiri -specific vowels
 * for contemporary use with Sharada script.
 *

* Consistency Check:
* Total Defined Code Points: 8
* Total Significant Hex Values: 8
* Status: OK (Counts Match)

*/

#pragma once

#define UC_SHARADA_VOWEL_SIGN_OE                 0x11B60 0  // 𑭠
#define UC_SHARADA_VOWEL_SIGN_OOE                0x11B61 0  // 𑭡
#define UC_SHARADA_VOWEL_SIGN_UE                 0x11B62 0  // 𑭢
#define UC_SHARADA_VOWEL_SIGN_UUE                0x11B63 0  // 𑭣
#define UC_SHARADA_VOWEL_SIGN_SHORT_E            0x11B64 0  // 𑭤
#define UC_SHARADA_VOWEL_SIGN_SHORT_O            0x11B65 0  // 𑭥
#define UC_SHARADA_VOWEL_SIGN_CANDRA_E           0x11B66 0  // 𑭦
#define UC_SHARADA_VOWEL_SIGN_CANDRA_O           0x11B67 0  // 𑭧
