/* gothic.h – Unicode constants for U+10330 … U+1034A
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_GOTHIC_AHSA                           0x10330 0  // 𐌰
#define UC_GOTHIC_BAIRKAN                        0x10331 0  // 𐌱
#define UC_GOTHIC_GIBA                           0x10332 0  // 𐌲
#define UC_GOTHIC_DAGS                           0x10333 0  // 𐌳
#define UC_GOTHIC_AIHVUS                         0x10334 0  // 𐌴
#define UC_GOTHIC_QAIRTHRA                       0x10335 0  // 𐌵
#define UC_GOTHIC_IUJA                           0x10336 0  // 𐌶
#define UC_GOTHIC_HAGL                           0x10337 0  // 𐌷
#define UC_GOTHIC_THIUTH                         0x10338 0  // 𐌸
#define UC_GOTHIC_EIS                            0x10339 0  // 𐌹
#define UC_GOTHIC_KUSMA                          0x1033A 0  // 𐌺
#define UC_GOTHIC_LAGUS                          0x1033B 0  // 𐌻
#define UC_GOTHIC_MANNA                          0x1033C 0  // 𐌼
#define UC_GOTHIC_NAUTHS                         0x1033D 0  // 𐌽
#define UC_GOTHIC_JER                            0x1033E 0  // 𐌾
#define UC_GOTHIC_URUS                           0x1033F 0  // 𐌿
#define UC_GOTHIC_PAIRTHRA                       0x10340 0  // 𐍀
#define UC_GOTHIC_NINETY                         0x10341 0  // 𐍁
#define UC_GOTHIC_RAIDA                          0x10342 0  // 𐍂
#define UC_GOTHIC_SAUIL                          0x10343 0  // 𐍃
#define UC_GOTHIC_TEIWS                          0x10344 0  // 𐍄
#define UC_GOTHIC_WINJA                          0x10345 0  // 𐍅
#define UC_GOTHIC_FAIHU                          0x10346 0  // 𐍆
#define UC_GOTHIC_IGGWS                          0x10347 0  // 𐍇
#define UC_GOTHIC_HWAIR                          0x10348 0  // 𐍈
#define UC_GOTHIC_OTHAL                          0x10349 0  // 𐍉
#define UC_GOTHIC_NINE_HUNDRED                   0x1034A 0  // 𐍊
