/* latin_extended_g.h – Unicode constants for U+1DF25 … U+1DF2A
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_SMALL_D_MID_HEIGHT_LEFT_HOOK          0x1DF25 0  // 𝼥
#define UC_SMALL_L_MID_HEIGHT_LEFT_HOOK          0x1DF26 0  // 𝼦
#define UC_SMALL_N_MID_HEIGHT_LEFT_HOOK          0x1DF27 0  // 𝼧
#define UC_SMALL_R_MID_HEIGHT_LEFT_HOOK          0x1DF28 0  // 𝼨
#define UC_SMALL_S_MID_HEIGHT_LEFT_HOOK          0x1DF29 0  // 𝼩
#define UC_SMALL_T_MID_HEIGHT_LEFT_HOOK          0x1DF2A 0  // 𝼪
