/* mathematical_alphanumeric_symbols.h – Unicode constants for U+1D7CE … U+1D7FF
*
* Generated by generate_unicode_headers.py (Unicode 16.0.0)
*
* See https://www.unicode.org/versions/latest/ for source data.
*/

#pragma once

#define UC_MA_BOLD_ZERO                          0x1D7CE 0  // 𝟎
#define UC_MA_BOLD_ONE                           0x1D7CF 0  // 𝟏
#define UC_MA_BOLD_TWO                           0x1D7D0 0  // 𝟐
#define UC_MA_BOLD_THREE                         0x1D7D1 0  // 𝟑
#define UC_MA_BOLD_FOUR                          0x1D7D2 0  // 𝟒
#define UC_MA_BOLD_FIVE                          0x1D7D3 0  // 𝟓
#define UC_MA_BOLD_SIX                           0x1D7D4 0  // 𝟔
#define UC_MA_BOLD_SEVEN                         0x1D7D5 0  // 𝟕
#define UC_MA_BOLD_EIGHT                         0x1D7D6 0  // 𝟖
#define UC_MA_BOLD_NINE                          0x1D7D7 0  // 𝟗
#define UC_MA_DS_ZERO                            0x1D7D8 0  // 𝟘
#define UC_MA_DS_ONE                             0x1D7D9 0  // 𝟙
#define UC_MA_DS_TWO                             0x1D7DA 0  // 𝟚
#define UC_MA_DS_THREE                           0x1D7DB 0  // 𝟛
#define UC_MA_DS_FOUR                            0x1D7DC 0  // 𝟜
#define UC_MA_DS_FIVE                            0x1D7DD 0  // 𝟝
#define UC_MA_DS_SIX                             0x1D7DE 0  // 𝟞
#define UC_MA_DS_SEVEN                           0x1D7DF 0  // 𝟟
#define UC_MA_DS_EIGHT                           0x1D7E0 0  // 𝟠
#define UC_MA_DS_NINE                            0x1D7E1 0  // 𝟡
#define UC_MA_SS_ZERO                            0x1D7E2 0  // 𝟢
#define UC_MA_SS_ONE                             0x1D7E3 0  // 𝟣
#define UC_MA_SS_TWO                             0x1D7E4 0  // 𝟤
#define UC_MA_SS_THREE                           0x1D7E5 0  // 𝟥
#define UC_MA_SS_FOUR                            0x1D7E6 0  // 𝟦
#define UC_MA_SS_FIVE                            0x1D7E7 0  // 𝟧
#define UC_MA_SS_SIX                             0x1D7E8 0  // 𝟨
#define UC_MA_SS_SEVEN                           0x1D7E9 0  // 𝟩
#define UC_MA_SS_EIGHT                           0x1D7EA 0  // 𝟪
#define UC_MA_SS_NINE                            0x1D7EB 0  // 𝟫
#define UC_MA_SS_BOLD_ZERO                       0x1D7EC 0  // 𝟬
#define UC_MA_SS_BOLD_ONE                        0x1D7ED 0  // 𝟭
#define UC_MA_SS_BOLD_TWO                        0x1D7EE 0  // 𝟮
#define UC_MA_SS_BOLD_THREE                      0x1D7EF 0  // 𝟯
#define UC_MA_SS_BOLD_FOUR                       0x1D7F0 0  // 𝟰
#define UC_MA_SS_BOLD_FIVE                       0x1D7F1 0  // 𝟱
#define UC_MA_SS_BOLD_SIX                        0x1D7F2 0  // 𝟲
#define UC_MA_SS_BOLD_SEVEN                      0x1D7F3 0  // 𝟳
#define UC_MA_SS_BOLD_EIGHT                      0x1D7F4 0  // 𝟴
#define UC_MA_SS_BOLD_NINE                       0x1D7F5 0  // 𝟵
#define UC_MA_MS_ZERO                            0x1D7F6 0  // 𝟶
#define UC_MA_MS_ONE                             0x1D7F7 0  // 𝟷
#define UC_MA_MS_TWO                             0x1D7F8 0  // 𝟸
#define UC_MA_MS_THREE                           0x1D7F9 0  // 𝟹
#define UC_MA_MS_FOUR                            0x1D7FA 0  // 𝟺
#define UC_MA_MS_FIVE                            0x1D7FB 0  // 𝟻
#define UC_MA_MS_SIX                             0x1D7FC 0  // 𝟼
#define UC_MA_MS_SEVEN                           0x1D7FD 0  // 𝟽
#define UC_MA_MS_EIGHT                           0x1D7FE 0  // 𝟾
#define UC_MA_MS_NINE                            0x1D7FF 0  // 𝟿
